<?
/* @var $this \ns_66112a2c_92c9_47c6_ae5b_bb35121e6654\HotelPriceCalculator */

    $product = $this->getApi()->getProductManager()->getProduct($_POST['data']['product']);
    $start = $_POST['data']['start'];
    $end = $_POST['data']['end'];
    $datetime1 = new DateTime($start);
    $datetime2 = new DateTime($end);
    $difference = $datetime1->diff($datetime2);
    $days = $difference->days;

    $this->getApi()->getHotelBookingManager()->setCart($product->id, $days, strtotime($start), strtotime($end));
    $mgr = $this->getApi()->getCartManager();
    $cart = $mgr->getCart();
    $price = $this->getApi()->getCartManager()->getCartTotalAmount();
    $origprice = $cart->items[0]->product->original_price * $days;
    if($origprice < $price) {
        $origprice = $price;
    }
    $discount = $origprice - $price;
?>
<table width="100%">
    <tr>
        <td><? echo $this->__w("Room"); ?></td>
        <td><? echo $product->name; ?></td>
    </tr>
    <tr>
        <td><? echo $this->__w("Days"); ?></td>
        <td><? echo $days; ?></td>
    </tr>
    <tr>
        <td><? echo $this->__w("Ordinary price"); ?></td>
        <td>Kr <? echo $origprice; ?></td>
    </tr>
    <tr>
        <td><? echo $this->__w("Discounted price"); ?></td>
        <td>Kr <? echo $price; ?></td>
    </tr>
    <? if($discount > 50) { ?>
        <tr>
            <td><? echo $this->__w("Your savings"); ?></td>
            <td>Kr <? echo $discount; ?> (<? echo round((1-($price/$origprice))*100,1) . "%"; ?>)</td>
        </tr>
    <? } ?>
    <tr>
        <td><? echo $this->__w("Average price"); ?></td>
        <td>Kr <? echo round($price / $days,2); ?></td>
    </tr>
</table>