<?php
/* @var $this ns_6f3bc804_02a1_44b0_a17d_4277f0c6dee8\Calendar */

$entry = $this->currentEntry;
if (!$entry)
    $entry = $this->getApiObject()->core_calendarmanager_data_Entry();

/* @var $entry core_calendarmanager_data_Entry */
$eventname = isset($entry) ? $entry->title : '';
$start = isset($entry) ? $entry->starttime : '';
$linkToPage = isset($entry) ? $entry->linkToPage : '';
$linkToPageText = $this->getPageName($linkToPage);
$stop = isset($entry) ? $entry->stoptime : '';
$max = isset($entry) ? $entry->maxAttendees : '';
$description = isset($entry) ? $entry->description : '';
$extraText = isset($entry) ? $entry->extraText : '';
$locked = isset($entry) && $entry->lockedForSignup ? ' checked ' : "";
$entryid = isset($entry) ? $entry->entryId : '';
$locations = $this->getApi()->getCalendarManager()->getAllLocations();

$events = $this->getApi()->getCalendarManager()->getEvents();

?>

<center>
    <div class='addevent'>
        <table>
            <tr><td width="150"><?php echo $this->__("event_name"); ?></td>
                <td>
                    <select id="add_event_event_selector">
                        <?
                        foreach ($events as $event) {
                            echo "<option value='$event->id'>".$event->title."</option>";
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr><td><?php echo $this->__("start", "common"); ?></td><td><input id="eventstart" type='textfield' value='<?php echo $start; ?>' placeholder="08:00"/></td></tr>
            <tr><td><?php echo $this->__("stop", "common"); ?></td><td><input id="eventstop" type='textfield' value='<?php echo $stop; ?>' placeholder="16:00"/></td></tr>
            
            <tr><td colspan="2" align="right">
                    <div entryid="<?php echo $entryid; ?>" day="<?php echo $this->day; ?>" year="<?php echo $this->year; ?>" month="<?php echo $this->month; ?>" id="save" class="button">
                        <div class="rightglare"></div>
                        <div class="filler"></div>
                        <ins><?php echo $this->__("save", "common"); ?></ins>
                    </div>
                </td>
            </tr>

        </table>
    </div>
</center>

<script>
    $("#extradays").datepicker({
        changeMonth: true,
        changeYear: true,
        closeText: "",
        showButtonPanel: true,
        onSelect: function(dateText, inst) {
            var selectedMonth = inst.selectedMonth + 1;
            var day = inst.selectedDay;
            var month = selectedMonth;
            var year = inst.selectedYear;
            Calendar.addAnotherDay(day, month, year);
            $(this).val("");
        }
    });
</script>
