<?
echo "<div>" . $this->__w("Entires marked in green is available for booking and entries marked in red is full") . "</div><br>";
$entries = $this->getListViewData();
foreach ($entries as $year => $months) {
    foreach ($months as $month => $locations) {

        if (!count($locations)) {
            continue;
        }

        $monthName = date("F", mktime(0, 0, 0, $month, 10));
        echo "<div class='calendar_listview_nameandplace'>" . $this->__w($monthName) . " " . $year . "</div>";

        echo "<table class='listview_month_location'>";
        echo "<tr><th>".$this->__f("Place")."</th>";
        echo "<th>".$this->__f("Event")."</th>";
        echo "<th>".$this->__f("Date")."</th>";
        echo "<th>".$this->__f("Available positions")."</th></tr>";

        foreach ($locations as $locationId => $entries) {
            
            $location = $this->getLocation($locationId);
            foreach ($entries as $entry) {
                if ($this->isEntryOutOfData($entry)){
                    continue;
                }
                $full = $entry->lockedForSignup || $entry->maxAttendees <= count($entry->attendees);
                $fullClass = $full ? "calendar_list_entry_full" : "calendar_list_entry_not_full";
                
                echo "<tr class='$fullClass'><td style='width: 100px;'>". $location->location."</td><td style='width: 300px;'>".$entry->title."</td><td style='width: 300px;'> ";
                    $i = 1;
                    $dayName = count($entry->otherDays) ? $this->__w("Day") . ":$i - " : "";
                    echo $dayName . $this->__w("Date") . ": " . $entry->day."/". $entry->month . " - " . $entry->starttime . "-" . $entry->stoptime;
                    foreach ($entry->otherDays as $otherDay) {
                        $i++;
                        $dayName = $this->__w("Day") . ":$i - ";
                        echo "<br>" . $dayName . $this->__w("Date") . ": " . $otherDay->day."/". $entry->month  . " - " . $otherDay->starttime . "-" . $otherDay->stoptime;
                    }
                    $count = $this->getCountOfFreePositions($entry);
                    echo "</td><td>$count</td>";
                echo "</tr>";
            }
            
            
        }
        echo "</table>";
    }
}
?>