<? 
/* @var $this \ns_6f3bc804_02a1_44b0_a17d_4277f0c6dee8\Calendar */
$id = $this->getConfiguration()->id;
$pageId = "";

if ($this->isShowTabsForViewMode() && $this->isEditorMode()) { ?>
    <div class="calendar_tabs">
        <a href="?page=<?echo $this->getPage()->id?>&asList=true"><div byname="list" class="calender_tab_entry"><? echo $this->__w("By list"); ?></div></a>
        <a href="?page=<?echo $this->getPage()->id?>&asList=false"><div byname="calendar" class="calender_tab_entry"><? echo $this->__w("By calendar"); ?></div></a>
    </div>
<? }

if ($this->asList()) {
?>
<div class='calendar_tab_content_view' calendar_tab_name="list" >
    <?
    echo "<a href='/generatePDF.php?type=calendar&id=$id&page=$pageId'><div class='downloadpdf'>".$this->__w("Download as pdf")."</div></a>";
    echo "<hr>";
    $this->renderList();
    ?>
</div>
<? } else { ?>
<div class='calendar_tab_content_view' calendar_tab_name="calendar" >
    <?php
    

    $month = $this->month;
    $year = $this->year;
    
    $headings = array(
        $this->__w('Monday', "common"),
        $this->__w('Tuesday', "common"),
        $this->__w('Wednesday', "common"),
        $this->__w('Thursday', "common"),
        $this->__w('Friday', "common"),
        $this->__w('Saturday', "common"),
        $this->__w('Sunday', "common")
    );
    
    $running_day = date('w', mktime(0, 0, 0, $month, 1, $year));
    $days_in_month = date('t', mktime(0, 0, 0, $month, 1, $year));
    $days_in_this_week = 1;
    $day_counter = 0;
    
    if ($running_day == 0) {
        $running_day = 7;
    }

//////////////////// This are added for the generate translation script to pick it up ///////////////
    $this->__w("January");
    $this->__w("February");
    $this->__w("March");
    $this->__w("April");
    $this->__w("May");
    $this->__w("June");
    $this->__w("July");
    $this->__w("August");
    $this->__w("September");
    $this->__w("October");
    $this->__w("November");
    $this->__w("December");
/////////////////////////////////////////////////////////////////////////////////////////////////////
    $monthname = $this->__w(date('F', mktime(0, 0, 0, $month, 1, $year)), 'common');
    ?>
    <div class="calendar inline">
        <table cellpadding="0" cellspacing="0" class="calendar">

            <tr class="calendar-row">
                <td class="calendar-day-head" colspan="2" style="cursor: pointer">
                    <div class="goToMonth" <?php echo $this->getPrevAttrs(); ?>>
                        <center>
                            <div class="left-arrow"></div>
                        </center>
                    </div>
                </td>
                <td class="calendar-day-head" colspan="5"><?php echo $monthname . " - " . $year ?></td>
                <td class="calendar-day-head" style="cursor: pointer">
                    <div class="goToMonth" <?php echo $this->getNextAttr(); ?>>
                        <center>
                            <div class="right-arrow"></div>
                        </center>
                    </div>
                </td>
            </tr>
            <?
            $dateweekcheck  = mktime(0, 0, 0, $month, 1, $year);
            $week  = (int)date('W', $dateweekcheck);
                        
            echo '<tr class="calendar-row"><td class="calendar-day-np week"></td><td class="calendar-day-head">' . implode('</td><td class="calendar-day-head">', $headings) . '</td></tr>';
            echo '<tr class="calendar-row"><td class="calendar-day-np week">'.$week.'</td>';

            for ($x = 0; $x < ($running_day-1); $x++) {
                echo '<td class="calendar-day-np">&nbsp;</td>';
                $days_in_this_week++;
            }

            for ($list_day = 1; $list_day <= $days_in_month; $list_day++) {
                $containsdata = "";
                $eventColor = "";

                if ($this->monthObject) {
                    $day = $this->getDay($list_day);
                    $containsdata = (count($day->entries) == 0) ? '' : 'containsdata';
                    $data = "";

                    foreach ($day->entries as $entry) {
                        if (isset($entry->isOriginal) && $entry->isOriginal > 0) {
                            $days = $this->getDaysCount($this->monthObject, $entry);
                            $eventColor = isset($entry->color) ? 'background-color: ' . $entry->color : $eventColor;
                            $data .= "<div class='outerdiv showentry'><div days='$days'>" . $entry->title . "</div></div>";
                        }
                    }
                }

                echo "<td class='calendar-day configable $containsdata' style='$eventColor'>";
                if (\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
                    echo "<div class='configuration'>";
                    echo "<div class='entries'>";
                    echo "<div class='entry addEvent' day='$list_day' year='$year' month='$month'>" . $this->__("add_event") . "</div>";
                    echo "</div>";
                    echo "</div>";
                }

                $pageid = $this->getPage()->getId();
                echo "<div class='calendercontent'>";
                echo "<div class='day-number'>$list_day</div>";
                echo "<div class='content'>$data</div>";
                
                echo "</div>";
                echo '</td>';

                if ($running_day == 7) {
                    echo '</tr>';
                    if (($day_counter + 1) != $days_in_month) {
                        $dateweekcheck  = mktime(0, 0, 0, $month, ($day_counter+2), $year);
                        $week  = (int)date('W', $dateweekcheck);
                        echo '<tr class="calendar-row"><td class="calendar-day-np week">'.$week.'</td>';
                    }
                    $running_day = 0;
                    $days_in_this_week = 0;
                }

                $days_in_this_week++;
                $running_day++;
                $day_counter++;
            }

            if ($days_in_this_week < 8 && $days_in_this_week != 1) {
                for ($x = 1; $x <= (8 - $days_in_this_week); $x++) {
                    echo '<td class="calendar-day-np">&nbsp;</td>';
                }
            }
            ?>

            </tr></table>
    </div>
    

    <script>
        Calendar.expandDays();
    </script>
        
    <?
    $this->renderEntry($entry);
    ?>
    
</div>
<? } ?>