<? 
/* @var $this \ns_6f3bc804_02a1_44b0_a17d_4277f0c6dee8\Calendar */
if ($this->isShowTabsForViewMode()) { ?>
    <div class="calendar_tabs">
        <div byname="calendar" class="calender_tab_entry"><? echo $this->__w("By calendar"); ?></div>
        <div byname="list" class="calender_tab_entry"><? echo $this->__w("By list"); ?></div>
    </div>
<? } ?>
<div class='calendar_tab_content_view' calendar_tab_name="list" style="display: none;">
    <?
    echo "<div>".$this->__w("Entires marked in green is available for booking and entries marked in red is full")."</div><br>";
    $entries = $this->getListViewData();
    foreach ($entries as $year => $months) {
        foreach ($months as $month => $locations) {
            
            if (!count($locations)) {
                continue;
            }
            
            $monthName = date("F", mktime(0, 0, 0, $month, 10));
            echo "<div class='calendar_listview_nameandplace'>".$this->__w($monthName)." ".$year."</div>";
            
            echo "<div class='listview_month'>";
            foreach ($locations as $locationId => $entries) {
                echo "<div class='listview_month_location'>";
                $location = $this->getLocation($locationId);
                echo "<div>".$location->location.":</div>";
               
                foreach ($entries as $entry) {
                    $full = $entry->lockedForSignup || $entry->maxAttendees <= count($entry->attendees);
                    $fullClass = $full ? "calendar_list_entry_full" : "calendar_list_entry_not_full";
                    echo "<div class='day_entry $fullClass'>";
                    $i = 1;
                    $dayName = count($entry->otherDays) ? $this->__w("Day").":$i - " : "";
                    echo "<div class='calendar_list_entry_title'>".$entry->title."</div>";
                    echo "<div class='calendar_list_dayinfo'>".$dayName.$this->__w("Date").": ".$entry->day." - ".$entry->starttime."-".$entry->stoptime."</div>";
                    foreach ($entry->otherDays as $otherDay) {
                        $i++;
                        $dayName = $this->__w("Day").":$i - ";
                        echo "<div class='calendar_list_dayinfo'>".$dayName.$this->__w("Date").": ".$otherDay->day." - ".$otherDay->starttime."-".$otherDay->stoptime."</div>";
                    }
                    echo "</div>";
                }
                echo "</div>";
            }
            echo "</div>";
        }   
    }
    ?>
</div>
<div class='calendar_tab_content_view' calendar_tab_name="calendar">
    <?php
    

    $month = $this->month;
    $year = $this->year;
    $headings = array(
        $this->__w('Sunday', "common"),
        $this->__w('Monday', "common"),
        $this->__w('Tuesday', "common"),
        $this->__w('Wednesday', "common"),
        $this->__w('Thursday', "common"),
        $this->__w('Friday', "common"),
        $this->__w('Saturday', "common"));
    $running_day = date('w', mktime(0, 0, 0, $month, 1, $year));
    $days_in_month = date('t', mktime(0, 0, 0, $month, 1, $year));
    $days_in_this_week = 1;
    $day_counter = 0;


//////////////////// This are added for the generate translation script to pick it up ///////////////
    $this->__w("January");
    $this->__w("February");
    $this->__w("March");
    $this->__w("April");
    $this->__w("May");
    $this->__w("June");
    $this->__w("July");
    $this->__w("August");
    $this->__w("September");
    $this->__w("October");
    $this->__w("November");
    $this->__w("December");
/////////////////////////////////////////////////////////////////////////////////////////////////////
    $monthname = $this->__w(date('F', mktime(0, 0, 0, $month, 1, $year)), 'common');
    ?>
    <div class="calendar inline">
        <table cellpadding="0" cellspacing="0" class="calendar">

            <tr class="calendar-row">
                <td class="calendar-day-head" style="cursor: pointer">
                    <a href="<?php echo $this->getPrevLink(); ?>">
                        <center>
                            <div class="left-arrow"></div>
                        </center>
                    </a>
                </td>
                <td class="calendar-day-head" colspan="5"><?php echo $monthname . " - " . $year ?></td>
                <td class="calendar-day-head" style="cursor: pointer">
                    <a href="<?php echo $this->getNextLink(); ?>">
                        <center>
                            <div class="right-arrow"></div>
                        </center>
                    </a>
                </td>
            </tr>
            <?
            echo '<tr class="calendar-row"><td class="calendar-day-head">' . implode('</td><td class="calendar-day-head">', $headings) . '</td></tr>';
            echo '<tr class="calendar-row">';

            for ($x = 0; $x < $running_day; $x++) {
                echo '<td class="calendar-day-np">&nbsp;</td>';
                $days_in_this_week++;
            }

            for ($list_day = 1; $list_day <= $days_in_month; $list_day++) {
                $containsdata = "";
                $eventColor = "";

                if ($this->monthObject) {
                    $day = $this->getDay($list_day);
                    $containsdata = (count($day->entries) == 0) ? '' : 'containsdata';
                    $data = "";

                    foreach ($day->entries as $entry) {
                        if (isset($entry->isOriginal) && $entry->isOriginal > 0) {
                            $days = $this->getDaysCount($this->monthObject, $entry);
                            $eventColor = isset($entry->color) ? 'background-color: ' . $entry->color : $eventColor;
                            $data .= "<div class='outerdiv'><div days='$days'>" . $entry->title . "</div></div>";
                        }
                    }
                }

                echo "<td class='calendar-day configable $containsdata' style='$eventColor'>";
                if (\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
                    echo "<div class='configuration'>";
                    echo "<div class='entries'>";
                    echo "<div class='entry addEvent' day='$list_day' year='$year' month='$month'>" . $this->__("add_event") . "</div>";
                    echo "</div>";
                    echo "</div>";
                }

                $pageid = $this->getPage()->getId();
                echo "<a href='?page=$pageid&day=$list_day&scroll_to_dayview=true'>";
                echo "<div class='calendercontent'>";
                echo "<div class='day-number'>$list_day</div>";
                echo "<div class='content'>$data</div>";
                echo "</div>";
                echo "</a>";
                echo '</td>';

                if ($running_day == 6) {
                    echo '</tr>';
                    if (($day_counter + 1) != $days_in_month) {
                        echo '<tr class="calendar-row">';
                    }
                    $running_day = -1;
                    $days_in_this_week = 0;
                }

                $days_in_this_week++;
                $running_day++;
                $day_counter++;
            }

            if ($days_in_this_week < 8 && $days_in_this_week != 1) {
                for ($x = 1; $x <= (8 - $days_in_this_week); $x++) {
                    echo '<td class="calendar-day-np">&nbsp;</td>';
                }
            }
            ?>

            </tr></table>
    </div>

    <script>
        Calendar.expandDays();
    </script>
    <?
    if (isset($this->day)) {
        $this->includefile('day');
    }
    ?>
</div>