<pre>
<?
/* @var $entryobject core_calendarmanager_data_Entry */
$entryobject = $this->getApi()->getCalendarManager()->getEntry($_POST['data']['entryId']);

$class = "on";
if(in_array($_POST['data']['userId'], $entryobject->dropDiploma)) {
    $class = "off";
}

?>

<input type="hidden" id="configuserid" value="<? echo $_POST['data']['userId']; ?>">
<input type="hidden" id="configentryId" value="<? echo $_POST['data']['entryId']; ?>">
</pre>
<div class="setting onoff" id="receiveDiploma">
    <span class="title"><?php echo $this->__("Should user receive an diploma?"); ?></span>
    <div class="onoff config <? echo $class; ?>" id="receiveDiploma_inner"></div>
    <div class="description">
        <?php echo $this->__("Disable this option if the user are not entitled to receive a diploma."); ?>
    </div>
</div>

<div class="dropdown setting" id="participated">
    <div class="text inline"><?php echo $this->__f("Participated"); ?></div>
    <select class="config">
        <option value="participated" <? echo $entryobject->participateData->{$_POST['data']['userId']} == "participated" ? 'selected="true"' : ''; ?>><? echo $this->__f("Participated"); ?></option>
        <option value="notvalid_cancel" <? echo $entryobject->participateData->{$_POST['data']['userId']} == "notvalid_cancel" ? 'selected="true"' : ''; ?>><? echo $this->__f("Not participated, illegal reason"); ?></option>
        <option value="valid_cancel" <? echo $entryobject->participateData->{$_POST['data']['userId']} == "valid_cancel" ? 'selected="true"' : ''; ?>> <? echo $this->__f("Not participated, leagal reason"); ?></option>
    </select>
</div>

<div class="bottom_menu_settings">
    <div class="gs_button save_candidate_setting"><?php echo $this->__("Save settings"); ?></div>
</div>

