<div style="padding: 30px;">
    <br/><input type="checkbox" id="checklist_1" <? echo $this->getConfigurationSetting("checklist_1".$_POST['data']['entryId']) == "true" ? "checked='checked'" : ""; ?> /> Lokal bokad
    <br/><input type="checkbox" id="checklist_2" <? echo $this->getConfigurationSetting("checklist_2".$_POST['data']['entryId']) == "true" ? "checked='checked'" : ""; ?> /> Ev elearning
    <br/><input type="checkbox" id="checklist_3" <? echo $this->getConfigurationSetting("checklist_3".$_POST['data']['entryId']) == "true" ? "checked='checked'" : ""; ?> /> Kursmaterial beställt
    <br/><input type="checkbox" id="checklist_4" <? echo $this->getConfigurationSetting("checklist_4".$_POST['data']['entryId']) == "true" ? "checked='checked'" : ""; ?> /> Pennor
    <br/><input type="checkbox" id="checklist_5" <? echo $this->getConfigurationSetting("checklist_5".$_POST['data']['entryId']) == "true" ? "checked='checked'" : ""; ?> /> Förevisningsmateriel/datorer
    <br/><input type="checkbox" id="checklist_6" <? echo $this->getConfigurationSetting("checklist_6".$_POST['data']['entryId']) == "true" ? "checked='checked'" : ""; ?> /> Praktikobjekt
    <br/><input type="checkbox" id="checklist_7" <? echo $this->getConfigurationSetting("checklist_7".$_POST['data']['entryId']) == "true" ? "checked='checked'" : ""; ?> /> Fika/lunch
    <br/><input type="checkbox" id="checklist_8" <? echo $this->getConfigurationSetting("checklist_8".$_POST['data']['entryId']) == "true" ? "checked='checked'" : ""; ?> /> Kursintyg
    <br/>
    <br/>
    <div class="gs_button saveCheckList"  entryid='<? echo $_POST['data']['entryId']; ?>' > Save </div>
</div>
