<div class="setting onoff" id="showfilter">
    <span class="title"><?php echo $this->__("Show location filter left for calendar"); ?></span>
    <div class="onoff config" id="showfilter"></div>
    <div class="description">
        <?php echo $this->__("If this function is enabled, it will show filter left for the calendar."); ?>
    </div>
</div>
<div class="setting onoff" id="showDescription">
    <span class="title"><?php echo $this->__("Show the description for days."); ?></span>
    <div class="onoff config" id="showDescription"></div>
    <div class="description">
        <?php echo $this->__("Default on, turn off if you dont want to show the full description."); ?>
    </div>
</div>
<div class="setting onoff" id="showBookingLink">
    <span class="title"><?php echo $this->__("Link to booking schema."); ?></span>
    <div class="onoff config" id="showBookingLink"></div>
    <div class="description">
        <?php echo $this->__("Should be turned on if you want to display a button where links to the booking schema."); ?>
    </div>
</div>
<div class="setting onoff" id="showTabsForViewMode">
    <span class="title"><?php echo $this->__("Activate this to show tabs for different modes."); ?></span>
    <div class="onoff config" id="showTabsForViewMode"></div>
    <div class="description">
        <?php echo $this->__("If this is activated, you will be able to show your customer a listview in additional."); ?>
    </div>
</div>
<div class="setting textfield" id="linkToBookingPage">
    <span class="title"><?php echo $this->__("Link to booking schema."); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__("Enter the pageid to the page where the booking form is."); ?>
    </div>
</div>

<div class="bottom_menu_settings">
    <div class="gs_button savebutton"><?php echo $this->__("Save settings"); ?></div>
</div>

<script>
    <? echo "currentSettings = ".json_encode($this->getConfiguration()->settings).";"; ?>
    var appInstance = $('#informationbox[appid=<? echo $this->getConfiguration()->id?>]');
    thundashop.app.Settings.init(appInstance);
</script>