<?php 
namespace ns_6f3bc804_02a1_44b0_a17d_4277f0c6dee8;

/* @var $this Calendar */ ?>
<div class="dayevents">
<?
$today = new \DateTime($this->year.'-'.$this->month.'-'.$this->day);
echo "<h2>".$this->day." - ".$this->__w($today->format('l'),'common')."</h2>";

$day = $this->getSelectedDay();
if (count($day->entries) == 0) {
    echo "<div class='noentry'><b>".$this->__('no_activites')."</b></div></div>";
    return;
}
    
    $k = 0;
    foreach ($day->entries as $entry) {
        $k++;
        /* @var $entry core_calendarmanager_data_Entry */
        $attendees = $this->getAttendees($entry);
        $waitingList = $this->getWaitingList($entry);
        
        $notConfirmed = $entry->needConfirmation ? " - (Not confirmed)" : "";
        $availablePositions = $this->getCountOfFreePositions($entry);
        $starttime = $entry->starttime;
        $stoptime = $entry->stoptime;
        $bookingLink = $this->getBookingLink($entry);
        $lockedForSignup = $entry->lockedForSignup;
        
        $link = "";
        if ($entry->linkToPage != "") {
            $link = "?page=".$entry->linkToPage;
        } 
        
        if (!$this->isCurrentEntryOutOfDate() || $availablePositions < 0) {
            $availablePositions = 0;
        }
        
        if (!$entry->isOriginal) {
            foreach ($entry->otherDays as $otherDay) {
                if ($otherDay->day == $this->day && $otherDay->month == $this->month && $otherDay->year == $this->year) {
                    $starttime = $otherDay->starttime != "" ? $otherDay->starttime : $starttime;
                    $stoptime = $otherDay->stoptime != "" ? $otherDay->stoptime : $stoptime;   
                }
            }
        }
        $odd = $k%2 ===  1 ? "odd" : "even";
    ?>
    <div class="dayentry configable <? echo $odd; ?>">
        <?php if ($this->hasReadAccess()) {?>
        <div class="reports">
            <center>
            <?
            echo "Reports<br> ";
            foreach ($this->getApi()->getUserManager()->getAllGroups() as $group) {
                echo "<a href='generateExcelReport.php?type=calendarbookedusers&entryid=$entry->entryId&group=$group->id'><span style='cursor: pointer; display: inline-block; border: dashed 1px; padding: 4px; margin-right: 10px;'>".$group->groupName."</span></a>";
            }
            ?>
            </center>
            <br>
        </div>
        <? } ?>
        <div class="availblepositions <? echo ($availablePositions === 0) ? 'notavailable' : ''; ?>">
            <div><? echo $availablePositions; ?></div>
            <div class="text"><? echo $this->__w("Available positions"); ?></div>
        </div>
        <?php if ($this->hasWriteAccess() && $entry->isOriginal) {?>
            <div class="configuration">
                <div class="entries">
                    <div class="entry deleteentry" entryid="<?php echo $entry->entryId;?>"><?php echo $this->__("delete", "common"); ?></div>
                    <div class="entry editentry" entryid="<?php echo $entry->entryId;?>"><?php echo $this->__("edit","common"); ?></div>
                    <div class="entry reminder" entryid="<?php echo $entry->entryId;?>"><?php echo $this->__("send_reminder"); ?></div>
                    <? if ($entry->needConfirmation) { ?>
                        <div class="entry confirmentry" entryid="<?php echo $entry->entryId;?>"><?php echo $this->__f("Confirm entry"); ?></div>
                    <? } ?>
                </div>
            </div>
        <?php } ?>
        <div class="title"><?php echo $entry->title; echo $notConfirmed ?></div>
        <div class="time">
            <?php 
                $daysCount = $this->getDaysCount($this->monthObject, $entry);
                if ($daysCount > 1) {
                    echo str_replace("{}", $daysCount, $this->__w("This is a {} days event."));
                    $i = 1;
                    echo "<br>".str_replace("{}", $i, $this->__f("Day {}")).": ".$entry->day."/".$entry->month."-".$entry->year." ".$this->__("start_time").":".$entry->starttime."-".$entry->stoptime; 
                    $i++;
                    foreach ($entry->otherDays as $ientry) {
                        echo "<br>".str_replace("{}", $i, $this->__f("Day {}")).": ".$ientry->day."/".$ientry->month."-".$ientry->year." ".$this->__("start_time").":".$ientry->starttime."-".$ientry->stoptime; 
                        $i++;
                    }
                } else {
                    echo $this->__("start_time").": ".$entry->day."/".$entry->month."-".$entry->year." ".$entry->starttime."-".$entry->stoptime; 
                }
                
                
            ?>
        </div>
        <div class="attendees"><?php echo $this->__("free_positions")." ".$availablePositions; ?></div>
        <div class="location"><b><?php echo $this->__w("location"); ?></b><div class='content'> <?php echo nl2br($entry->location); ?></div></div>
        <? if ($entry->locationExtended) { ?>
        <div class="extendedLocation">&nbsp;&nbsp; - <?php echo $entry->locationExtended; ?></div>
        <? } ?>
        
        <? if ($entry->extraText) { ?>
            <div class="extraText"><?php echo $entry->extraText; ?></div>
        <? } ?>
        <? if ($this->getConfigurationSetting("showDescription") == null || $this->getConfigurationSetting("showDescription") === true) { ?>
            <div class="description"><b><?php echo $this->__w("description"); ?></b><div class='content'> <?php echo nl2br($entry->description); ?></div></div>
        <? } ?>
        
        <div class=""></div>
        <?php
        if ($link != "" || $bookingLink != "") {
            echo "<div class='buttons'>";
            
            if ($link != "") {
                $moreInfo = $this->__w("More information");
                ?>
                <a href='<? echo $link; ?>'>;
                    <div class="button-large moreinfo">
                        <div class="rightglare"></div>
                        <div class="filler"></div>
                        <ins><? echo $moreInfo; ?></ins>
                    </div>
                </a>
            <?
            }

            if (!$lockedForSignup && $bookingLink != "" && $availablePositions > 0) { ?>
                <a href='/<? echo $bookingLink; ?>'>;
                    <div class="button-large booking">
                        <div class="rightglare"></div>
                        <div class="filler"></div>
                        <ins><? echo $this->__w("Booking"); ?></ins>
                    </div>
                </a>
            
            <? 
            }

            if (!$lockedForSignup && $bookingLink != "" && $availablePositions <= 0  && $this->isCurrentEntryOutOfDate()) { ?>
                <a href='/<? echo $bookingLink."&waiting=true"; ?>'>;
                    <div class="button-large booking">
                        <div class="rightglare"></div>
                        <div class="filler"></div>
                        <ins><? echo $this->__w("Waiting list"); ?></ins>
                    </div>
                </a>
            <? 
            } 
            echo "</div>";
        }
        
        if ($this->hasReadAccess()) {
            echo "<h2>".$this->__("Attendees")."</h2>";
            echo "<table width='100%' cellspacing='0'>";
            
            $i = 0;
            foreach ($attendees as $user) {
                $i++;
                /* @var $user core_usermanager_data_User */
                $userid = $user->id;
                $group = $this->getGroup($user);
                if ($group != "") {
                    $group = " - ".$group;
                }
                $entryid = $entry->entryId;
                
                $transfer = $this->hasWriteAccess() ? "<td width='50'><span class='transferUser' userId='$userid' entryId='$entryid' style='inline-block; border: solid 1px; padding: 3px; cursor: pointer; background-color: #000; color: #FFF;'>".$this->__("Transfer")."</span></td>" : "";
                $remove = $this->hasWriteAccess() ? "<div userid='$userid' entryid='$entryid' class='remove'></div>" : "";
                $activeComment = $this->isActiveComment($user, $entryid) ? "activeComment" : "";
                $comment = $this->hasWriteAccess() ? "<div userid='$userid' entryid='$entryid' class='addcomment $activeComment'></div>" : "";
                $link = \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator() ? "?page=users_all_users&userid=$userid" : "#";
                echo "<tr class='dayrow'><td width='22'>$remove</td><td><div class='attendee'><a href='$link'> $i. ".$user->fullName.$group."</a></div></td><td width='50'>$transfer</td><td width='22'>$comment</td></tr>";
            }

            echo "</table>";
            
            if (count($waitingList)) {
                echo "<br>";
                echo "<h2>".$this->__("Waiting list")."</h2>";
                echo "<table width='100%' cellspacing='0'>";

                $i = 0;
                foreach ($waitingList as $user) {
                    $i++;
                    /* @var $user core_usermanager_data_User */
                    $userid = $user->id;
                    $group = $this->getGroup($user);
                    if ($group != "") {
                        $group = " - ".$group;
                    }
                    $entryid = $entry->entryId;
                    $transfer = $this->hasWriteAccess() ? "<td width='50'><span class='transferUser' userId='$userid' entryId='$entryid' style='inline-block; border: solid 1px; padding: 3px; cursor: pointer; background-color: #000; color: #FFF;'>".$this->__("Transfer")."</span></td>" : "";
                    $accept = $this->hasWriteAccess() ? "<span class='acceptUser' userId='$userid' entryId='$entryid' style='inline-block; border: solid 1px; padding: 3px; cursor: pointer; background-color: #000; color: #FFF;'>".$this->__("Accept")."</span>" : "";
                    $remove = $this->hasWriteAccess() ? "<div userid='$userid' entryid='$entryid' class='remove'></div>" : "";
                    $activeComment = $this->isActiveComment($user, $entryid) ? "activeComment" : "";
                    $comment = $this->hasWriteAccess() ? "<div userid='$userid' entryid='$entryid' class='addcomment $activeComment'></div>" : "";
                    $link = \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator() ? "<a href='?page=users_all_users&userid=$userid'> $i. ".$user->fullName.$group."</a>" : "$i. ".$user->fullName.$group;
                    echo "<tr class='dayrow'><td><div class='attendee'>$link</div></td><td width='50'>$transfer</td><td width='50'>$accept</td><td width='22'>$comment</td></tr>";
                }

                echo "</table>";
            }
        }
        ?>
    </div>
<?
}
?>
</div>