<div class="day_entry_information">
    <div class="close_dayview">
        
    </div>
    <div class="content_image">
        <img src="http://www.lold.org/uploads/2011/08/forrest-wallpaper.jpg" width="400" style="border: solid 5px #FFF;"/>
    </div>
    
    <div class="content_information">
        <div style="font-size: 30px; font-weight: bold; padding-bottom: 10px;">Stølstur Laupsaflyane - Klippe</div>
        Dato: Fredag 15 juni, 17:00
        <br/> Lengde: 7km
        <br/> Stigning: 400m
        <br/> Varighet: 3 timaru
        
        <div style="margin-top: 30px; margin-bottom: 20px;">
            Frå parkeringsplassen ved Blekeld, i enden av Fitjadalsvatnet, følgjer vi stien bratt opp mot stølen Laupsaflyane. Her tek vi ein pause og nyt den flotte utsikten over Fitjadalen, fjellet og fjorden. Vidare går turen i lettare terreng langsmed Soldalsfjellet og til stølen Klippe.  Frå Klippe tek vi turen ned att til Fitjadalsvatnet. 
        </div>
        
        
        <div>
            Pris:
            <br/> Voksen: Kr 250,- 
            <br/> Barn: 125,-
        </div>
        <br/>
        <div class="shop_button">
            Bestill - 8 ledige plasser
        </div>
    </div>
</div>
    