<?
/* @var $this ns_6f3bc804_02a1_44b0_a17d_4277f0c6dee8\Calendar */
$entry = $this->getApi()->getCalendarManager()->getEntry($_POST['data']['entryId']);
$event = $entry->event;
$availablepos = $this->getCountOfFreePositions($entry);
?>

<div class="close_dayview">

</div>
<div class="content_image">
    <img src="/displayImage.php?id=<? echo $event->imageId; ?>" width="100%" style="border: solid 5px #FFF;"/>
</div>

<div class="content_information">
    <div style="font-size: 30px; font-weight: bold; padding-bottom: 10px;"><? echo $event->title; ?></div>
    <? echo $this->__w("Date"); ?>: <? echo $entry->day."/".$entry->month."-".$entry->year.", ".$entry->starttime." - ".$entry->stoptime; ?>
    
    <div style="margin-top: 30px; margin-bottom: 20px;">
        <?
        echo $event->description;
        ?>
    </div>


    <div>
        <? echo $this->__w("Price"); ?>:
        <br/> <? echo $this->__w("Adult"); ?>: Kr <? echo $event->priceAdults ?>,- 
        <br/> <? echo $this->__w("Children"); ?>: Kr <? echo $event->priceChild ?>,-
    </div>
    <br/>
    <?
    if ($entry->availableForBooking) {
    ?>
    <a href="/index.php?page=calbooking&entryId=<? echo $entry->entryId; ?>">
        <div class="shop_button">
            <? echo $this->__w("Order"); ?>- <? echo $availablepos; ?> <? echo $this->__w("free spots"); ?>
        </div>
    </a>
    <?
    }
    ?>
</div>    