<?
/* @var $this \ns_6f3bc804_02a1_44b0_a17d_4277f0c6dee8\Calendar */
/* @var $location  \core_calendarmanager_data_Location */
    $locationId = $_POST['data']['locationId'];
    $location = $this->getLocation($locationId, true);
    
    if ($location == null) {
        $location = new \core_calendarmanager_data_Location();
        $location->id = "";
        
    }
?>

<div class="editlocationscalendar">
    <input type="hidden" value="<? echo $location->id; ?>" id='locationId'/>
    
    <div class="contactinformation">
        <div style="border: solid 1px #AAA; margin-bottom: 10px; padding: 10px; ">
            <b><? echo $this->__f("Event location"); ?></b>
            <table>
                <tr><td style="width: 100px;"><? echo $this->__f("location", "common"); ?></td><td><input id='locationName' style="width: 800px" type="textfield" value="<? echo $location->location; ?>"/></td></tr>
                <tr><td><? echo $this->__f("Extended location"); ?></td><td><input id='locationExtra' style="width: 800px" type="textfield" value="<? echo $location->locationExtra; ?>"/></td></tr>
                <tr><td><? echo $this->__f("Contact person"); ?></td><td><input id='contactPerson' style="width: 800px" type="textfield" value="<? echo $location->contactPerson; ?>"/></td></tr>
                <tr><td><? echo $this->__f("Email"); ?></td><td><input id='locationEmail' style="width: 800px" type="textfield" value="<? echo $location->emailAddress; ?>"/></td></tr>
                <tr><td><? echo $this->__f("Mobile"); ?></td><td><input id='locationCellPhone' style="width: 800px" type="textfield" value="<? echo $location->mobile; ?>"/></td></tr>
                <tr><td><? echo $this->__f("Other"); ?></td><td><input id='otherinformation' style="width: 800px" type="textfield" value="<? echo $location->other; ?>"/></td></tr>
                <tr><td><? echo $this->__f("Lat"); ?></td><td><input id='location_lat' style="width: 800px" type="textfield" value="<? echo $location->lat; ?>"/></td></tr>
                <tr><td><? echo $this->__f("Lon"); ?></td><td><input id='location_lon' style="width: 800px" type="textfield" value="<? echo $location->lon; ?>"/></td></tr>
            </table>    
        </div>
    </div>
    
    <?
    $groups = $this->getApi()->getUserManager()->getAllGroups();
    foreach ($groups as $group) {
        $locationInfo = $this->getLoctionInfo($group, $location);
        ?>
        <div style="border: solid 1px #AAA; margin-bottom: 10px; padding: 10px; ">
            <b><? echo $group->groupName; ?></b>
            <table class="groupinformation">
                <tr><td style="width: 100px;"><? echo $this->__f("Name"); ?></td><td><input id='<? echo $group->id; ?>_contactPerson' style="width: 800px" type="textfield" value="<? echo $locationInfo->name; ?>"/></td></tr>
                <tr><td><? echo $this->__f("Email"); ?></td><td><input id='<? echo $group->id; ?>_email' style="width: 800px" type="textfield" value="<? echo $locationInfo->email; ?>"/></td></tr>
                <tr><td><? echo $this->__f("Cellphone"); ?></td><td><input id='<? echo $group->id; ?>_cellPhone' style="width: 800px" type="textfield" value="<? echo $locationInfo->mobile; ?>"/></td></tr>
                <tr><td><? echo $this->__f("Other"); ?></td><td><input id='<? echo $group->id; ?>_otherInformation' style="width: 800px" type="textfield" value="<? echo $locationInfo->other; ?>"/></td></tr>
            </table>
        </div>
        <?
    }
    ?>
    <div class="comments">
        <? 
        
        echo $this->__f("Comments"); 
        $this->moveCommentsToCommentField($location);
        ?>
    </div>
    
    <? if (count($location->subLocations)) { ?>
    <div style="margin-top: 30px;">
        
        <div style="text-align: center; border: solid 1px;">
            <div> Sublocations </div>
            <?
            foreach ($location->subLocations as $subLocation) {
                echo "<div class='gs_button selectlcoation' value='$subLocation->id'>"; 
                echo $subLocation->location ? $subLocation->location : "No name set";
                echo "</div>";
            }
            ?>
            </div>
    </div>
    <? 
    }
    ?>
    <br/>
    <div>
        <? echo $this->__f("Add comment"); ?>
        <br/>
        <textarea id='commentText' style="width: 945px; height: 150px;"><? echo $this->getConfigurationSetting("comment_".$location->id); ?></textarea>
        <br><div class="gs_button calendar_location_back"><? echo $this->__f("Back"); ?></div>
        
        
        <br><div class="gs_button calendar_location_save"><? echo $this->__f("Save"); ?></div>
        <br><div class="gs_button add_sub_location"><? echo $this->__f("Add sublocation"); ?></div><br/><br/>
    </div>
</div>

