<?php

namespace ns_6f3bc804_02a1_44b0_a17d_4277f0c6dee8;

/* @var $this Calendar */
$attendees = $this->getAttendees($this->currentEntry);
?>
<div class='reminderform'>
    <b>Subject:</b>
    <br>
    <input style='width: 925px; margin-left: 8px; margin-right: 8px' type="textfield" value="Reminder" id="remindersubject"/>
    <br><br>
    <b>Message:</b>
    <div>
        <textarea style='width: 925px; height: 150px; margin-left: 8px;'><?php echo $this->currentEntry->title; ?></textarea>
    </div>
    <br>
    <b>Send message to the following:</b>

     <div style='padding: 20px; border: solid 1px #EEE; margin-bottom: 20px; margin-top: 20px;'>
        {FULLNAME} - Name 
        <br/>{USER_CELLPHONE} - Users cellphone number 
        <br/>{USERNAME} - Username 
        <br/>{EVENT_TITLE} - event title 
        <br/>{EVENT_DATE} - event date, will display all days of a event including time. 
        <br/>{EVENT_LOCATION} - event location 
        <br/>{EVENT_LOCATION_EXTENDED} - event location extended 
        <br/>{EVENT_DESCRIPTION} - event description 
        <br/>{GROUP_LOGO} - logo of the group the current user belongs to. 
        <br/>{USER_EMAILADDRESS} - The email address from the users. 
        <br/>{COMPANY_NAME} - Name of the company. 
        <br/>{COMPANY_VAT} - Vat number of the company. 
        <br/>{COMPANY_STREETADDRESS} - Company street address. 
        <br/>{COMPANY_POSTNUMBER} - Company postnumber street address. 
        <br/>{COMPANY_COUNTRY} - Country where the company are registered. 
        <br/>{COMPANY_CITY} - City where the company are registered
    </div>
    
    <table>
        <?
        foreach ($attendees as $attendee) {
            /* @var $attendee core_usermanager_data_User */
            $id = $attendee->id;
            $name = $attendee->fullName;
            echo "<tr><td><input name='attendeestoremind' type='checkbox' value='$id'/ checked='checked'></td><td>$name</td></tr>";
        }
        ?>
    </table>
    
   
    
    
    <div>
        Attach file:
        <br><input type='file' id='file1'/>

    </div>

    <div style='text-align: right'>
        <div id="sendreminderbysms" entryid="<? echo $this->currentEntry->entryId; ?>" class='gs_button'>Sms</div>
        <div id="sendreminderbymail" entryid="<? echo $this->currentEntry->entryId; ?>"  class='gs_button'>Mail</div>    
    </div>
    
    

    <div class="all_reminder_history">
        <? $this->includefile("reminderhistory"); ?>
    </div>
    

</div>