<div class="page_row row_1">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pga_row1");
        ?>
    </div>
</div>

<div class="page_row row_3 image_left">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pga_row2");
        ?>
    </div>
</div>

<div class="page_row row_2 image_right">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pga_row3");
        ?>
    </div>
</div>


