<div style='text-align:right; padding-right: 10px; max-width:1500px; margin: auto; border-bottom: solid 4px #bbb; padding-bottom: 10px; margin-bottom: 10px;' gstype='form' method='updatefilter'>
    <span class='shop_button' gsname='Search' style='float:left;'>Filter by customer</span>
    <?php
    /* @var $this \ns_3746f382_0450_414c_aed5_51262ae85307\InvoiceOverview */
    $paymentMethods = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
    $start = date("d.m.Y", strtotime(date("01.m.Y", time())));
    $end = date("d.m.Y", strtotime(date("t.m.Y", time())));
    $filter = $this->getFilter();
    
    if(isset($filter->start)) { $start = date("d.m.Y", strtotime($filter->start)); }
    if(isset($filter->end)) { $end = date("d.m.Y", strtotime($filter->end)); }
    
    $states = $this->getStates();

    $filterType = array();
    
    echo "<select class='gsniceselect1' style='height:38px;' gsname='paymentmethod'>";
    echo "<option value=''>All</option>";
    foreach($paymentMethods as $pmethod) {
        $selected = "";
        if($filter->paymentMethod) {
            if($pmethod->id == $filter->paymentMethod) {
                $selected = "SELECTED";
            }
        } else if($pmethod->id == "70ace3f0-3981-11e3-aa6e-0800200c9a66") {
            $selected = "SELECTED";
        }
        
        echo  "<option value='".$pmethod->id."' $selected>" . $pmethod->appName . "</option>";
    }
    echo "</select> ";
    echo "<select class='gsniceselect1' style='height:38px;' gsname='state'>";
    foreach($states as $id => $state) {
        $selected = "";
        if(isset($filter->state) && $filter->state == $id) {
            $selected = "SELECTED";
        }
        echo  "<option value='$id' $selected>" . $state . "</option>";
    }
    echo "</select> ";
    ?>
    <input type="txt" class='gsniceinput1' gsname='startdate' value='<?php echo $start; ?>'>
    <input type="txt" class='gsniceinput1' gsname='enddate' value='<?php echo $end; ?>'>
    <?php
    
    $filterTypes = array();
    $filterTypes['createddate'] = "Order created date";
    $filterTypes['whenordered'] = "Shipment date";
    $filterTypes['paymentdate'] = "Payment date";
    $filterTypes['duedate'] = "Due date";
    
    echo "<select class='gsniceselect1' style='height:38px;' gsname='filtertype'>";
    foreach($filterTypes as $id => $state) {
        $selected = "";
        if(isset($filter->type) && $filter->type == $id) {
            $selected = "SELECTED";
        }
        
        echo  "<option value='$id' $selected>" . $state . "</option>";
    }
    echo "</select>";
    ?>
    <span class='shop_button' gstype='submit'>Load result</span>
</div>

<script>
    $('[gsname="startdate"]').datepicker({ dateFormat: "dd.mm.yy"});
    $('[gsname="enddate"]').datepicker({ dateFormat: "dd.mm.yy"});
</script>