<?php
/* @var $this \ns_3746f382_0450_414c_aed5_51262ae85307\InvoiceOverview */
$result = $this->getFilteredResult();

$attributes = array(
    array('id', 'gs_hidden', 'orderId'),
    array('incOrderId', 'Id', 'incOrderId'),
    array('orderDate', 'Date', null, 'formatOrderDate'),
    array('dueDate', 'Due', null, 'formatDueDate'),
    array('start', 'Peride', null, 'formatStartDate'),
    array('user', 'User', null, 'formatUser'),
    array('status', 'Status', null, 'formatStatus'),
    array('amountExTaxes', 'Ex tax', 'amountExTaxes'),
    array('amountIncTaxes', 'Inc tax', 'amountIncTaxes'),
    array('amountPaid', 'Paid', 'amountPaid'),
    array('restAmount', 'Rest', 'restAmount'),
    array('state', 'Options',null, 'formatState'),
);


$table = new \GetShopModuleTable($this, 'InvoiceOverview', 'loadOrder', null, $attributes);
$table->setSorting(array("id","incOrderId","orderDate","paymentDate","dueDate","start","end","user","status","amountExTaxes","amountIncTaxes","amountPaid","restAmount"));
if(isset($_SESSION['invoiceoverviewdisplayorder']) && $_SESSION['invoiceoverviewdisplayorder']) {
    $table->setExpandOnRow(1);
}

$table->setData($result);
echo "<div class='invoicetable'>";
$table->render();
echo "</div>";
$_SESSION['invoiceoverviewdisplayorder'] = null;
?>
<div style="text-align:right; padding-right: 10px; max-width:1500px; margin: auto; border-bottom: solid 4px #bbb; padding-bottom: 10px; margin-top: 10px;">
    <span class='shop_button' gs_downloadExcelReport="downloadExcelFile" gs_fileName="overview">Download result</span>
</div>