<div class="isnotactive" style='margin-top: 20px; width: 1500px; margin: auto;margin-bottom: 100px;'>
    <div class="kaipal infobox">
        <div class="image talking"></div>
        <div class="textbox">
            <div class="header" style='border-bottom: 0px;'><? echo $this->__f("You need to create rooms before you can continue."); ?></div>
            <div class="text" style='min-height:100px;'>
                <?
                echo "<div>" . $this->__f("Cleaning interval is set to 0, this means it is disabled and need to be configured.") . "</div>";
                echo "<div>" . $this->__f("Navigate to settings -> cleaning configuration and set up your cleaning program.") . "</div>";
                ?>
            </div>
        </div>
    </div>
</div>