<?
/* @var $this \ns_4404dc7d_e68a_4fd5_bd98_39813974a606\EcommerceProductView */
?>


<div class="menuarea">
    <div class="menuentry <? echo $this->isTabActive('details'); ?>" tab='details'><i class="fa fa-info"></i> <span><? echo $this->__f("Details"); ?></span></div>
    <div class="menuentry <? echo $this->isTabActive('prices'); ?>" tab='prices'><i class="fa fa-info"></i> <span><? echo $this->__f("Prices"); ?></span></div>
    <div class="menuentry <? echo $this->isTabActive('taxes'); ?>" tab='taxes'><i class="fa fa-info"></i> <span><? echo $this->__f("Taxes"); ?></span></div>
    <div class="menuentry <? echo $this->isTabActive('categories'); ?>" tab='categories'><i class="fa fa-info"></i> <span><? echo $this->__f("Categories"); ?></span></div>
    <div class="menuentry <? echo $this->isTabActive('lists'); ?>" tab='lists'><i class="fa fa-info"></i> <span><? echo $this->__f("Lists"); ?></span></div>
    <div class="menuentry <? echo $this->isTabActive('pictures'); ?>" tab='pictures'><i class="fa fa-info"></i> <span><? echo $this->__f("Pictures"); ?></span></div>
    <div class="menuentry <? echo $this->isTabActive('variations'); ?>" tab='variations'><i class="fa fa-info"></i> <span><? echo $this->__f("variations"); ?></span></div>
</div>

<div class="workarea">
    <div class="producttab <? echo $this->isTabActive('details'); ?>" tab='details'>
        <?
        $this->includefile("details");
        ?>
    </div>
    <div class="producttab <? echo $this->isTabActive('lists'); ?>" tab='lists'>
        <?
        $this->includefile("lists");
        ?>
    </div>
    <div class="producttab <? echo $this->isTabActive('prices'); ?>" tab='prices'>
        <?
        $this->includefile("prices");
        ?>
    </div>
    <div class="producttab <? echo $this->isTabActive('taxes'); ?>" tab='taxes'>
        <?
        $this->includefile("taxes");
        ?>
    </div>
    <div class="producttab <? echo $this->isTabActive('variations'); ?>" tab='variations'>
        <?
        $this->includefile("variations");
        ?>
    </div>
</div>