<?
/* @var $this \ns_4404dc7d_e68a_4fd5_bd98_39813974a606\EcommerceProductView */
$product = $this->getProduct();
?>
<div gstype="form" method="saveProductPrice">
    <?
    echo $this->__f("Price (inc taxes)").":";
    ?>
    <br/><input class="gsniceinput1" gsname="price" value="<? echo $product->price; ?>"/>
    <br/>
    <br/><div class="shop_button" gstype="submit"><? echo $this->__f("Save"); ?></div>
</div>

