<?
/* @var $this \ns_4404dc7d_e68a_4fd5_bd98_39813974a606\EcommerceProductView */
$product = $this->getProduct();
$taxes = $this->getApi()->getProductManager()->getTaxes();
?>


Default tax:
<div>
    <select class="gsniceselect1">
    <?
        foreach ($taxes as $tax) {
            $selected = $product->taxGroupObject && $product->taxGroupObject->id == $tax->id ? "selected='true'" : "";
            echo " <option $selected value='$tax->id'>$tax->taxRate </option>";
        }
    ?>    
    </select>
    
    <br/>
    <br/>
    Additional taxes:
    
    <?
    if (!$product->additionalTaxGroupObjects || !count($product->additionalTaxGroupObjects)) {
        echo $this->__f("No extra taxes added");
    } else {
        foreach ($product->additionalTaxGroupObjects as $taxGroup) {
            echo "<div><i class='gs_shop_small_icon fa fa-trash' gsclick='removeTax' productid='$product->id' taxgroupid='$taxGroup->id'></i> ".$taxGroup->taxRate."%</div>";
        }
    }
    ?>
</div>


<div class="addextratax" gstype="form" method="addExtraTax">
    
    <input type="hidden" gsname="productid" value="<? echo $product->id; ?>"/>
    Add extra tax:
    <br/>
    <select class="gsniceselect1" gsname='taxgroup'>
    <?
        foreach ($taxes as $tax) {
            echo " <option value='$tax->id'>$tax->taxRate </option>";
        }
    ?>    
    </select>
    <br/>
    <br/>
    <div class="shop_button" gstype="submit"><? echo $this->__f("Add"); ?></div>
</div>
