<?php
/* @var $this ns_ed7efba0_de37_4cd8_915b_cc7be10b8b8b\PmsBookingProductList */

$rooms = $this->getApi()->getPmsManager()->getAllRoomTypes($this->getSelectedName(), 
        $this->convertToJavaDate($this->getStartDate()), 
        $this->convertToJavaDate($this->getEndDate()));
$booking = $this->getCurrentBooking();

?>
<div class='continue_button_outer'>
    <div class='continue_button' next_page="<? echo $this->getText("next_page"); ?>"><? echo $this->getText("next_button"); ?></div>
</div>
<?php

foreach($rooms as $room) {
    /* @var $room core_pmsmanager_Room */
    $selected = "";
    $bookedCount = 0;
    foreach($booking->rooms as $bookedroom) {
        /* @var $product core_pmsmanager_PmsBookingRooms */
        if($bookedroom->bookingItemTypeId == $room->type->id) {
            $bookedCount++;
        }
    }
    
    
    $start = $this->convertToJavaDate($this->getStartDate());
    $end = $this->convertToJavaDate($this->getEndDate());
    $availability = $this->getApi()->getBookingEngine()->getNumberOfAvailable($this->getSelectedName(), $room->type->id, $start, $end);
    
    ?>
    <div class='productentry <? echo $selected; ?>'>
        <?
        if($availability == 0) {
            $text = $this->getText("no_rooms_available");
            if(!$text) {
                $text = "We are out of this type of room, select a different one.";
            }
        } else {
            $text = $this->getText("selected_room_count_text");
            if(!$text) {
                $text = "You have selected {count} of this room type";
            }

            $dropdown = "<select>";
            for($i = 0;$i <= $availability;$i++) {
               $selected = "";
               if($i == $bookedCount) {
                    $selected = "SELECTED";
               }
                $dropdown .= "<option value='$i' $selected>$i</option>"; 
            }
            $dropdown .= "</select>";

            $text = str_replace("{count}", $dropdown, $text);
        }
        ?>
        <span class='roomtypeselection'>
            <?php echo $text; ?>
        </span>
    <span class='name'><? echo $room->type->name; ?></span>
    <?php if($room->price > 0) { ?>
        <span class='price'><? echo $room->price; ?>,-</span>
    <?php } ?>
    </div>
    <?php
}
?>
<div class='continue_button_outer'>
    <div class='continue_button' next_page="<? echo $this->getText("next_page"); ?>"><? echo $this->getText("next_button"); ?></div>
</div>
