<?php
/* @var $this ns_ed7efba0_de37_4cd8_915b_cc7be10b8b8b\PmsBookingProductList */
$booking = $this->getBookings();
$rooms = $this->getRooms();
$numberSelected = 0;

$singleSelection = ($this->getText("onlyoneselectionallowed") == "true");

foreach($rooms as $room) {
    /* @var $room core_pmsmanager_Room */
    $selected = "";
    $bookedCount = 0;
    $selectedRow = false;
    foreach($booking->rooms as $bookedroom) {
        /* @var $product core_pmsmanager_PmsBookingRooms */
        if($bookedroom->bookingItemTypeId == $room->type->id) {
            $bookedCount++;
        }
    }
    if($numberSelected < $bookedCount) {
        $numberSelected = $bookedCount;
         if($singleSelection) {
            $selected = "selected";
            $selectedRow = true;
         }
    }

    $start = $this->convertToJavaDate($this->getStartDate());
    $end = $this->convertToJavaDate($this->getEndDate());
    $availability = $this->getApi()->getBookingEngine()->getNumberOfAvailable($this->getSelectedName(), $room->type->id, $start, $end);
    ?>
    <div class='productentry <? echo $selected; ?>'>
        <?php
        $imgs = $this->getImagesFromPage($room->type->id);
        foreach($imgs as $img) {
            echo "<span class='imgcontainer'>";
            echo "<img class='roomimg' src='displayImage.php?id=" . $img."'>";
            echo "</span>";
        }
        
        if($availability == 0) {
            $text = $this->getText("no_rooms_available");
            if(!$text) {
                $text = "We are out of this type of room, select a different one.";
            }
        } else {
            $text = $this->getText("selected_room_count_text");
            if(!$text) {
                $text = "You have selected {count} of this room type";
            }

            $dropdown = "<select class='roomcountselection' typeid='".$room->type->id."'>";
            for($i = 0;$i <= $availability;$i++) {
               $selected = "";
               if($i == $bookedCount) {
                    $selected = "SELECTED";
               }
                $dropdown .= "<option value='$i' $selected>$i</option>"; 
            }
            $dropdown .= "</select>";

            $text = str_replace("{count}", $dropdown, $text);
        }
        if(!$singleSelection) {
            ?>
            <span class='roomtypeselection'>
                <?php echo $text; ?>
            </span>
        <?php } else {
            if($availability) {
                if(!$selectedRow) {
                    ?>
                    <span class="selectbutton" gstype="clicksubmit" method="selectRoom" gsvalue="<?echo $room->type->id; ?>" gsname="typeid"><?php echo $this->getText("select_button"); ?></span>
                    <?php
                } else {
                    echo "<span class='selectedtext'>Selected</span>";
                }
            } else {
                ?>
                <span class='outofstocktext'>
                    <?php echo $text; ?>
                </span>
                <?php
            }
        } ?>
    <span class='name'>
        <? echo $room->type->name; ?>
        <?php 
            if($this->isEditorMode()) {
                echo "  <span style='position:absolute; top: 35px;left:170px;font-size: 12px;'><a href='?page=".$room->type->pageId."'>Configure</a></span>";
            }
        ?>
    </span>
    <?php if($room->price > 0 && $booking->priceType != 8) { ?>
        <span class='price <?php if($singleSelection) { echo "withselectbtn"; } ?>'><? echo round($room->price); ?>,-</span>
    <?php } ?>
    <?php if($booking->priceType == 8) { 
        $prices = $this->getApi()->getPmsManager()->getPrices($this->getSelectedName(),$this->convertToJavaDate(time()),$this->convertToJavaDate(time()));
        $progPrice = $prices->progressivePrices->{$room->type->id};
        echo "<span class='price'>";
        echo "Første " . (($progPrice[0]->numberOfTimeSlots)/7)." uker ". $progPrice[0]->price . " kr per dag.";
        if($progPrice[2]->price) {
            echo "<br>Mellom " . ($progPrice[0]->numberOfTimeSlots/7) . " og " . (($progPrice[0]->numberOfTimeSlots+$progPrice[1]->numberOfTimeSlots))/7 . " uker " . $progPrice[1]-> price. " kr per dag.";
            echo "<br>Over " . (($progPrice[0]->numberOfTimeSlots+$progPrice[1]->numberOfTimeSlots))/7 . " uker " . $progPrice[2]->price . " kr per dag.";
        }
        echo "</span>";
        ?>
    <?php } ?>
    </div>
    <?php
}
?>