<?php
/* @var $this ns_39fd9a07_94ea_4297_b6e8_01e052e3b8b9\PmsReport */
?>
<table width="100%">
    <tr>
        <th align='left'>Guests</th>
        <th align='left'>Billed</th>
        <th align='left'>Room price</th>
        <th align='left'>Remaining</th>
        <th align='left'>Room type</th>
        <th align='left'>Room</th>
        <th align='left'>Start</th>
        <th align='left'>End</th>
    </tr>
    <?php
    $data = json_decode($_SESSION['latestpmscoverageresult']);
    $total = 0;
    $totalForcasted = 0;
    $totalRemaining = 0;
    foreach($data->entries as $entry) {
        if(date("d.m.Y", strtotime($entry->date)) == date("d.m.Y", strtotime($_POST['data']['rowdate']))) {
            foreach($entry->roomsIncluded as $roomIncluded) {
                $booking = $this->getApi()->getPmsManager()->getBookingFromRoom($this->getSelectedMultilevelDomainName(), $roomIncluded);
                foreach($booking->rooms as $room) {
                    if($room->pmsBookingRoomId == $roomIncluded) {
                        $remaining = 0;
                        echo "<tr>";
                        echo "<td valign='top'>";
                        echo $room->guests[0]->name . "<br>";
                        echo "</td>";
                        echo "<td valign='top'>";
                        $price = $entry->roomsPrice->{$room->pmsBookingRoomId};
                        echo round($price);
                        $total += $price;
                        echo "</td>";
                        echo "<td>";
                        $pricef = $entry->roomsPriceForecasted->{$room->pmsBookingRoomId};
                        $remaining = $pricef-$price;
                        echo round($pricef);
                        $totalForcasted += $pricef;
                        $totalRemaining += $remaining;
                        echo "</td>";
                        echo "<td>".round($remaining)."</td>";
                        echo "<td>";
                        if($room->bookingItemTypeId) {
                            $type = $this->getApi()->getBookingEngine()->getBookingItemType($this->getSelectedMultilevelDomainName(), $room->bookingItemTypeId)->name;
                            echo $type;
                        }
                        echo "</td>";
                        echo "<td>";
                        if($room->bookingItemId) {
                            $item = $this->getApi()->getBookingEngine()->getBookingItem($this->getSelectedMultilevelDomainName(), $room->bookingItemId);
                            echo $item->bookingItemName;
                        } else {
                            echo "floating";
                        }
                        echo "</td>";
                        echo "<td>" . date("d.m.Y", strtotime($room->date->start)) . "</td>";
                        echo "<td>" . date("d.m.Y", strtotime($room->date->end)) . "</td>";
                        echo "</tr>";
                    }
                }
            }
            
            $totalRemoved = 0;
            foreach($entry->roomsRemovedFromStatistics as $roomId => $val) {
                $totalRemoved += $val;
            }
            if($totalRemoved > 1 || $totalRemoved < -1) {
                foreach($entry->roomsRemovedFromStatistics as $roomId => $val) {
                    $removedBooking = $this->getApi()->getPmsManager()->getBookingFromRoomIgnoreDeleted($this->getSelectedMultilevelDomainName(), $roomId);
                    if($removedBooking) {
                        foreach($removedBooking->rooms as $room) {
                            if($room->pmsBookingRoomId == $roomId) {
                                echo "<tr>";
                                echo "<td>" . $room->guests[0]->name . "</td>";
                                echo "<td>" . round($val) . "</td>";
                                echo "<td>0</td>";
                                echo "<td>" . round($val*-1) . "</td>";
                                echo "<td>";
                                $total += $val;
                                if($room->bookingItemTypeId) {
                                    $type = $this->getApi()->getBookingEngine()->getBookingItemType($this->getSelectedMultilevelDomainName(), $room->bookingItemTypeId)->name;
                                    echo $type;
                                }
                                echo "</td>";
                                echo "<td>";
                                if($room->bookingItemId) {
                                    $item = $this->getApi()->getBookingEngine()->getBookingItem($this->getSelectedMultilevelDomainName(), $room->bookingItemId);
                                    echo $item->bookingItemName;
                                } else {
                                    echo "floating";
                                }
                                echo "</td>";
                                echo "<td>" . date("d.m.Y", strtotime($room->date->start)) . "</td>";
                                echo "<td>" . date("d.m.Y", strtotime($room->date->end)) . "</td>";
                                echo "</tr>";
                                $totalRemaining -= $val;
                            }
                        }
                    }
                }
            }
       }
    }
    echo "<tr>";
    echo "<td></td>";
    echo "<td>".round($total)."</td>";
    echo "<td>".round($totalForcasted)."</td>";
    echo "<td>".round($totalRemaining)."</td>";
    echo "</tr>";
    ?>
</table>
