
<?php
echo "<div style='margin: auto;text-align:left; cursor:pointer; position:absolute; right: 0px; padding: 3px; border-bottom: solid 1px #bbb; padding-left: 20px; padding-right: 20px;   background-color: #efefef; border-left:solid 1px #bbb; border-bottom-left-radius: 3px;top:0px;'>";
echo "<span gs_downloadExcelReport='downloadReportRawNew' gs_fileName='incomereport'>Download this report to excel</span> - ";
echo "<span gs_downloadExcelReport='downloadIncomeReportExTaxesNew' gs_fileName='incomereportraw'>Download to excel ex taxes with </span> - ";
echo "<span gs_downloadExcelReport='downloadIncomeReportIncTaxesNew' gs_fileName='incomereport'>Download to excel inc taxes</span> - ";
echo "<span class='displayto30list'>Display top 30 customer list</span>";
echo "</div>";
        
/* @var $this ns_39fd9a07_94ea_4297_b6e8_01e052e3b8b9\PmsReport */
$data = $this->getIncomeReportData(false);

echo "<div class='newincomereportview'>";
echo "<div class='innernewincomereport'>";
echo "<div class='informationoverlay'><i class='fa fa-close closeDayInformation' style='font-size:25px; position:absolute; right: 5px; top: 5px; cursor:pointer;'></i><div class='inneroverlay'></div></div>";
$first = true;
$colums = 0;
foreach($data as $row) {
    $columns = sizeof($row);
    echo "<div class='incomereportrow'>";
    $firstCol = true;
    $date = "";
    foreach($row as $res) {
        $firstClass = $first ? "first" : "";
        $r = $res;
        if(!$first && !$firstCol) {
            $r = round($res,2);
        } else {
            $date = $res;
        }
        echo "<span class='column $firstClass' date='$date'>" . $r . "</span>";
        $firstCol = false;
    }
    $first = false;
    echo "</div>";
}
echo "</div>";
echo "</div>";
?>
<script>
    $('.innernewincomereport').css('width','<?php echo ($columns*150); ?>px');
</script>
