<div class="isnotactive" style='max-width:1500px; margin: auto;'>
    <div class="kaipal infobox">
        <div class="image happy"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("Reports are important"); ?></div>
            <div class="text">
                <?
                echo $this->__f("Reports are important for the day to day operations and I know that. However no bookings has been registered yet, so please register a booking and come back here then.");
                ?>    
            </div>
        </div>
    </div>
</div>