<?php
/* @var $this \ns_39fd9a07_94ea_4297_b6e8_01e052e3b8b9\PmsReport */
$filter = $this->getSelectedFilter();
$types = $this->getTypes();
$views = array();
$views['daily'] = "Daily";
$views['monthly'] = "Monthly";
$views['yearly'] = "Yearly";
$checked = ($filter->includeNonBookableRooms) ? "CHECKED" : ""; 
$departments = $this->getApi()->getDepartmentManager()->getAllDepartments();

$pmsManager = new ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement();
$channels = $pmsManager->getChannelMatrix();
$segments = $this->getApi()->getPmsCoverageAndIncomeReportManager()->getSegments($this->getSelectedMultilevelDomainName());

$pmssearchbox = new \ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBookingColumnFormatters(null);
$chnls = $pmssearchbox->getChannels();
?>
<div style='max-width:1500px;margin:auto;'>
    
    <div class="kaipal infobox">
        // faces: happy,sad,talking,danger
        <div class="image talking"></div>
        <div class="textbox">
            <div class="header">Statistics</div>
            <div class="text">
                I know insight is important for you. Here you find the coverage and income reports. Just specify the periode you want to look at. What type of view you want to look at; daily, monthly, yearly, and click load report.<br>
                <br>
                Ps: it is important to understand this report only include the rooms that has been paid for and future bookings. If you want to include orders not yet created, click on the forcasted report.<br>
                <b>Coverage:</b> Coverage in the hotel,earned until now + future bookings.<br>
                <b>Income report:</b> All money earned until now.<br>
                <b>Stay / Geographical report:</b> A report displaying where in the world the guests are from<br>
                <b>Cleaning report:</b> Reports from the cleaning staff<br>
            </div>
        </div>
    </div><br><br>
    
    
    <div style='height: 38px; border-bottom: solid 1px #bbb;'>
        <span type='coverage' class='pmsbutton tab <?php if($filter->type == "coverage") {echo "selected";}?>'><i class='fa fa-line-chart'></i> Coverage</span>
        <span type='incomereport' class='pmsbutton tab <?php if($filter->type == "incomereport") {echo "selected";}?>'><i class='fa fa-money'></i> Income report</span>
        <span type='geographical_report' class='pmsbutton tab <?php if($filter->type == "geographical_report") {echo "selected";}?>'><i class='fa fa-language'></i> Stay / Geographical report</span>
        <span type='cleaning_report' class='pmsbutton tab <?php if($filter->type == "cleaning_report") {echo "selected";}?>'><i class='fa fa-paint-brush'></i> Cleaning report</span>
    </div>
    <div gstype="form" method="setReportFilter">
    <table>
        <input type="hidden" id="coverageview" value="<?php echo $filter->type; ?>" gsname='type'>
        <tr>
            <td>
                Start date<br>
                <input type='text' value='<?php echo date("d.m.Y", strtotime($filter->start)); ?>' gsname="start" class='startcal gsniceinput1'>
            </td>
            <td>
                End date<br>
                <input type='text' value="<?php echo date("d.m.Y", strtotime($filter->end)); ?>" gsname="end" class='endcal gsniceinput1'>
            </td>
            <td  style="display:none;">
                View<br>
                <?php
                echo "<select gsname='view' class='gsniceselect1' style='height:37px'>";
                foreach($views as $view => $name) {
                    $selected = ($filter->view == $view) ? "SELECTED" : "";
                    echo "<option value='$view' $selected>$name</option>";
                }
                echo "</select>";
                ?>
            </td>
            <td>
                Channel<br>
                <?php
                echo "<select gsname='channel' class='gsniceselect1' style='height:37px'>";
                echo "<option value=''>All channels</option>";
                foreach($channels as $chanid => $chan) {
                    $selected = ($filter->channel == $chan) ? "SELECTED" : "";
                    echo "<option value='$chanid' $selected>".$chnls[$chanid]."</option>";
                }
                echo "</select>";
                ?>
            </td>
            <td>
                Segment<br>
                <?php
                echo "<select gsname='segment' class='gsniceselect1' style='height:37px'>";
                echo "<option value=''>All segments</option>";
                echo "<option value='none'>Not segmented</option>";
                foreach($segments as $segment) {
                    $selected = ($filter->segment == $segment->id) ? "SELECTED" : "";
                    echo "<option value='".$segment->id."' $selected>".$segment->name."</option>";
                }
                echo "</select>";
                ?>
            </td>
            <td><br><input type='button' value='Load report' gstype='submit' style='padding: 9px;'><bR>
            </td>
        </tr>
    </table>
        <span class='shop_button filterbycustomerbutton' style="float:right;">Filter by customers</span>
        <span class='customerfilter'>
            <div><input type='txt' class='gsniceinput1 customersearch' placeholder='Search for customer'></div>
            <div class='filtercustomerresult'></div>
            <div class='top30customerfilter'></div>
        </span>
    <div style='clear: both;'></div>
        
    <input type='checkbox' gsname='includenonbookable' <?php echo $checked; ?>> Include non bookable rooms as well when calculating the coverage.
    <?php $hideSelection = $this->getSelectedFilter()->segment ? "display:none;" : ""; ?>
        <div class='typeselectionboxes' <?php echo "style='$hideSelection'"; ?>>
        <?php
        foreach($types as $type) {
            $checked = "";
            $filterArray = array();
            if(isset($filter->typeFilter)) {
                $filterArray = (array)$filter->typeFilter;
            }
            if(in_array($type->id, $filterArray)) { $checked = "CHECKED"; }
            echo "<span style='display:inline-block'><input type='checkbox' gsname='typeselected_".$type->id."' $checked>" . $type->name . "</span> ";
        }
        ?>
        </div>
        <div class='filteredcustomerslist'>
            <?php $this->printAddedCustomers(); ?>
        </div>
    </div>
</div>

<script>
$('.PmsReport .startcal').datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
    onSelect: function(dateText) {
        var curEnd = moment.utc($('.PmsReport .endcal').val(), "DD.MM.YYYY").local();
        var date = moment.utc(dateText, "DD.MM.YYYY").local();

        var diff = curEnd.valueOf() - date.valueOf();
        if(diff <= 0) {
            date.add(7, 'days');
            $('.PmsReport .endcal').val(date.format('DD.MM.YYYY')); 
        }
    }
});
$('.PmsReport .endcal').datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
    onSelect: function(dateText) {
        var curStart = moment.utc($('.PmsReport .startcal').val(), "DD.MM.YYYY").local();
        var date = moment.utc(dateText, "DD.MM.YYYY").local();

        var diff = date.valueOf() - curStart.valueOf();
        if(diff <= 0) {
            date.add(-7, 'days');
            $('.PmsReport .startcal').val(date.format('DD.MM.YYYY')); 
        }
    }
});
</script>