<?php
/* @var $this \ns_39fd9a07_94ea_4297_b6e8_01e052e3b8b9\PmsReport */
$filter = $this->getSelectedFilter();
$views = array();
$views['daily'] = "Daily";
$views['monthly'] = "Monthly";
$views['yearly'] = "Yearly";
$checked = ($filter->includeNonBookableRooms) ? "CHECKED" : ""; 
?>
<div style='max-width:1500px;margin:auto;'>
    
    <div class="kaipal infobox">
        // faces: happy,sad,talking,danger
        <div class="image talking"></div>
        <div class="textbox">
            <div class="header">Statistics</div>
            <div class="text">
                I know insight is important for you. Here you find the coverage and income reports. Just specify the periode you want to look at. What type of view you want to look at; daily, monthly, yearly, and click load report.<br>
                <br>
                Ps: it is important to understand this report only include the rooms that has been paid for and future bookings. If you want to include orders not yet created, click on the forcasted report.<br>
                <b>Coverage:</b> Coverage in the hotel,earned until now + future bookings.<br>
                <b>Forecasted coverage:</b> All money possible to earn if you collect all the money.<br>
                <b>Income report:</b> All money earned until now.<br>
                <b>Forecasted income report:</b> All money potentially possible to earn if you collect all the money.<br>
            </div>
        </div>
    </div><br><br>
    
    
    <div style='height: 38px; border-bottom: solid 1px #bbb;'>
        <span type='coverage' class='pmsbutton tab <?php if($filter->type == "coverage") {echo "selected";}?>'><i class='fa fa-line-chart'></i> Coverage</span>
        <span type='forecasted_coverage' class='pmsbutton tab <?php if($filter->type == "forecasted_coverage") {echo "selected";}?>'><i class='fa fa-tint'></i> Forcasted coverage</span>
        <span type='incomereport' class='pmsbutton tab <?php if($filter->type == "incomereport") {echo "selected";}?>'><i class='fa fa-money'></i> Income report</span>
        <span type='forecasted_incomereport' class='pmsbutton tab <?php if($filter->type == "forecasted_incomereport") {echo "selected";}?>'><i class='fa fa-dashboard'></i> Forecasted income report</span>
        <span type='geographical_report' class='pmsbutton tab <?php if($filter->type == "geographical_report") {echo "selected";}?>'><i class='fa fa-language'></i> Stay / Geopgraphical report</span>
        <span type='cleaning_report' class='pmsbutton tab <?php if($filter->type == "cleaning_report") {echo "selected";}?>'><i class='fa fa-paint-brush'></i> Cleaning report</span>
    </div>
    <div gstype="form" method="setReportFilter">
    <table>
        <input type="hidden" id="coverageview" value="<?php echo $filter->type; ?>" gsname='type'>
        <tr>
            <td>
                Start date<br>
                <input type='text' value='<?php echo date("d.m.Y", strtotime($filter->start)); ?>' gsname="start" class='startcal gsniceinput1'>
            </td>
            <td>
                End date<br>
                <input type='text' value="<?php echo date("d.m.Y", strtotime($filter->end)); ?>" gsname="end" class='endcal gsniceinput1'>
            </td>
            <td>
                View<br>
                <?php
                echo "<select gsname='view' class='gsniceselect1' style='height:37px'>";
                foreach($views as $view => $name) {
                    $selected = ($filter->view == $view) ? "SELECTED" : "";
                    echo "<option value='$view' $selected>$name</option>";
                }
                echo "</select>";
                ?>
            </td>
            <td><br><input type='button' value='Load report' gstype='submit' style='padding: 9px;'><bR>
            </td>
        </tr>
    </table>
    <input type='checkbox' gsname='includenonbookable' <?php echo $checked; ?>> Include non bookable rooms as well when calculating the coverage.
    </div>
</div>

<script>
$('.PmsReport .startcal').datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
    onSelect: function(dateText) {
        var curEnd = moment.utc($('.PmsReport .endcal').val(), "DD.MM.YYYY").local();
        var date = moment.utc(dateText, "DD.MM.YYYY").local();

        var diff = curEnd.valueOf() - date.valueOf();
        if(diff <= 0) {
            date.add(7, 'days');
            $('.PmsReport .endcal').val(date.format('DD.MM.YYYY')); 
        }
    }
});
$('.PmsReport .endcal').datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
    onSelect: function(dateText) {
        var curStart = moment.utc($('.PmsReport .startcal').val(), "DD.MM.YYYY").local();
        var date = moment.utc(dateText, "DD.MM.YYYY").local();

        var diff = date.valueOf() - curStart.valueOf();
        if(diff <= 0) {
            date.add(-7, 'days');
            $('.PmsReport .startcal').val(date.format('DD.MM.YYYY')); 
        }
    }
});
</script>