<?php
/* @var $this \ns_3b18f464_5494_4f4a_9a49_662819803c4a\BookingEngineManagement */
$id = $_POST['data']['typeid'];
$item = $this->getApi()->getBookingEngine()->getBookingItem($this->getSelectedName(), $id);
$additional = $this->getApi()->getPmsManager()->getAdditionalInfo($this->getSelectedName(), $id);
?>

<div gstype="form" method="saveItem">
    <table width="80%" class="contactConfigTable">
        <input type="hidden" value='<? echo $id; ?>' gsname='itemid'>
        <tr>
            <td width="50%"><? echo $this->__w("Name"); ?></td>
            <td width="50%"><input type="text" gsname="bookingItemName" style='width:100%;' value="<? echo $item->bookingItemName; ?>"></td>
        </tr>
        <tr>
            <td width="50%"><? echo $this->__w("Alias"); ?></td>
            <td width="50%"><input type="text" gsname="bookingItemAlias" style='width:100%;' value="<? echo $item->bookingItemAlias; ?>"></td>
        </tr>
        <tr>
            <td width="50%"><? echo $this->__w("Door id (used for closing doors)"); ?></td>
            <td width="50%"><input type="text" gsname="doorId" style='width:100%;' value="<? echo $item->doorId; ?>"></td>
        </tr>
        <tr>
            <td width="50%">How many bookings is allowed to be on this bookingitem</td>
            <td width="50%"><input type="text" gsname="bookingSize" style='width:100%;' value="<? echo $item->bookingSize; ?>"></td>
        </tr>
        <tr>
            <td width="50%">Waiting list size</td>
            <td width="50%"><input type="text" gsname="waitingListSize" style='width:100%;' value="<? echo $item->waitingListSize; ?>"></td>
        </tr>
        <tr>
            <td width="50%">Capasity (full when counter hit this)</td>
            <td width="50%"><input type="text" gsname="fullWhenCountHit" style='width:100%;' value="<? echo $item->fullWhenCountHit; ?>"></td>
        </tr>
        <tr>
            <td width="50%">Square metres</td>
            <td width="50%"><input type="text" gsname="squareMetres" style='width:100%;' value="<? echo $additional->squareMetres; ?>"></td>
        </tr>
        <tr>
            <td width="50%">Description</td>
            <td width="50%"><input type="text" gsname="description" style='width:100%;' value="<? echo $item->description; ?>"></td>
        </tr>
        <tr>
            <td width="50%">Message to include in text message</td>
            <td width="50%"><textarea type="text" gsname="textMessageDescription" style='width:100%; height:80px;'><? echo $additional->textMessageDescription; ?></textarea></td>
        </tr>
        <tr>
            <?php
            $checked = ($additional->hideFromCleaningProgram) ? "CHECKED" : "";
            ?>
            <td width="50%">Hide room from cleaning program</td>
            <td width="50%"><input type='checkbox' <?php echo $checked; ?> gsname='hideFromCleaningProgram'></td>
        </tr>
        <tr>
            <td width="50%">Type</td>
            <td width="50%">
                <select gsname='bookingitemtype'>
                    <?
                    $types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
                    foreach ($types as $type) {
                        $checked = $type->id == $item->bookingItemTypeId ? "selected='true'" : "";
                        echo "<option $checked value='$type->id'>".$type->name."</option>";
                    }
                    ?>
                </select>
            </td>
        </tr>
    </table>
    <input gstype="submit" type="button" value='Save'>
</div>
