<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$bookingtypes = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
?>

<div class='addRoomBox'>
    <div gstype="form" method="addBookingItemType" class='addGroupOptions'>
        <h2 style='float:left;'><? echo $this->getSelectedName(); ?></h2>
        <input gsname="name" value="">
        <span gstype="submit" class="pmsbutton addGroupOptions"><? echo $this->__w("Create a booking group"); ?></span>
    </div>

    <div class="roomlist">
        <table width='100%'>
            <tr>
                <th width='10'></th>
                <th align='left'>Group name</th>
            </tr>
            
             <?php 
            foreach($bookingtypes as $room) {
                /* @var $room core_bookingengine_data_BookingItemType */
                echo "<tr bookingItemTypeId='".$room->id."'>";
                echo "<td><i class='fa fa-trash-o deletegroupid' bookingitemtypeid='".$room->id."'></i></td><td><span class='currentname'>" . $room->name . "</span></td>";
                echo "<td align='right'><span class='pmsbutton renameBookingItemButton pmsbuttonsmall'>Rename</span> ";
                echo "<span class='pmsbutton pmsbuttonsmall'>Edit content</span></td>";
                echo "</tr>";
            }
            ?>
        </table>
    </div>
</div>

