<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$bookingtypes = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
$allbookingtypes = array();
foreach($bookingtypes as $tp) {
    $allbookingtypes[$tp->id] = $tp;
}
$bookingitems = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
$config = $this->getApi()->getBookingEngine()->getConfig($this->getSelectedName());
$bookings = $this->getApi()->getBookingEngine()->getAllBookings($this->getSelectedName());
$products = $this->getApi()->getProductManager()->getAllProducts();
$products2 = array();
if($products) {
    foreach($products as $prod) {
        $products2[$prod->id] = $prod;
    }
}
$products=$products2;
?>
<div class='addRoomBox'>
    <h2 ><? echo $this->getSelectedName(); ?></h2>
    <table width='100%' cellspacing='2' class='mgrtable'>
        <tr>
            <td valign='top' width='50%'>
                <h3>Booking item types</h3>
                <div gstype="form" method="addBookingItemType" class='addGroupOptions'>
                    <input gsname="name" value="">
                    <span gstype="submit" class="pmsbutton addGroupOptions"><? echo $this->__w("Create a booking item type"); ?></span>
                </div>

                <div class="roomlist">
                    <table width='100%'>
                        <tr>
                            <th width='10'></th>
                            <th align='left'>Booking item name</th>
                        </tr>

                        <?php
                        foreach ($bookingtypes as $type) {
                            /* @var $type core_bookingengine_data_BookingItemType */
                            echo "<tr entryid='" . $type->id . "' type='itemtype'>";
                            echo "<td style='white-space: nowrap;'>";
                            echo "<i class='fa fa-trash-o deletegroupid' bookingitemtypeid='" . $type->id . "'></i>";
                            $selected = "";
                            if($type->visibleForBooking) {
                                $selected = "selected";
                            }
                            echo " <i class='fa fa-eye $selected' title='Visible for booking'></i>";
                            $selected = "";
                            if($type->addon) {
                                $selected = "selected";
                            }
                            echo " <i class='fa fa-plus $selected' title='Is addon'></i>";
                            echo "</td><td><span class='currentname'>" . $type->name . "</span>";
                            echo "<div class='secondary'>";
                            if(isset($products[$type->productId])) {
                                echo $products[$type->productId]->name;
                            }
                            echo "</div>";
                            echo "</td>";
                            echo "<td align='right'><span class='pmsbutton renameBookingItemButton pmsbuttonsmall'>Rename</span> ";
                            echo "<span class='pmsbutton pmsbuttonsmall editbookingitemtype'>Edit type</span></td>";
                            echo "</tr>";
                        }
                        ?>
                    </table>
                </div>
                <br>
                <br>
            </td>
            <td valign='top' width='50%'>
                <h3>Booking items</h3>
                <div gstype="form" method="addBookingItem" class='addGroupOptions'>
                    <input gsname="name" value="">
                    <span gstype="submit" class="pmsbutton addGroupOptions"><? echo $this->__w("Create a booking item"); ?></span>
                </div>

                <div class="roomlist">
                    <table width='100%'>
                        <tr>
                            <th width='10'></th>
                            <th align='left'>Booking item</th>
                        </tr>

                        <?php
                        if(is_array($bookingitems)) {
                            foreach ($bookingitems as $item) {
                                /* @var $type core_bookingengine_data_BookingItem */
                                echo "<tr entryid='" . $item->id . "'type='item'>";
                                echo "<td><i class='fa fa-trash-o deletetype' bookingitemid='" . $item->id . "'></i></td><td><span class='currentname'>" . $item->bookingItemName . "</span></td>";
                                echo "<td align='right'>";
                                echo "<select class='itemTypeSelector'>";
                                foreach($bookingtypes as $type) {
                                    $selected = "";
                                    if($type->id == $item->bookingItemTypeId) {
                                        $selected = "SELECTED";
                                    }
                                    echo "<option value='".$type->id."' $selected>" . $type->name . "</option>";
                                }
                                echo "</select>";
                                echo  "</td>";
                                
                                echo "<td align='right'><span class='pmsbutton renameBookingItemButton pmsbuttonsmall'>Rename</span> ";
                                echo "</tr>";
                            }
                        }
                        ?>
                    </table>
                </div>
                <br>
                <br>
            </td>
        </tr>
    </table>
    
    <h2>All booking added</h2>
    <table width='100%'>
        <tr>
            <th align='left'>Start date</th>
            <th align='left'>end date</th>
            <th align='left'>Group</th>
        </tr>
        <?php
        if($bookings) {
            foreach($bookings as $booking) {
                echo "<tr>";
                echo "<td>" . $booking->startDate . "</td>";
                echo "<td>" . $booking->endDate . "</td><td>";
                echo $allbookingtypes[$booking->bookingItemTypeId]->name . "</td>";
                echo "</tr>";
            }
        }
        ?>
    </table>
    
</div>

