<?
/* @var $this \ns_3b18f464_5494_4f4a_9a49_662819803c4a\BookingEngineManagement */
$id = $_POST['data']['typeid'];
$item = $this->getApi()->getBookingEngine()->getBookingItemType($this->getSelectedName(), $id);
$product = $this->getApi()->getProductManager()->getAllProducts();
$addons = array();
$addons[0] = "None";
$addons[1] = "One time";
$addons[2] = "Per timeslot";
?>
<div gstype="form" method="saveItemType">
    <input type='hidden' gsname='typeid' value='<? echo $id;?>'>
    <table width="80%" class="contactConfigTable">
    <tr>
        <td width="50%"><? echo $this->__w("Name"); ?></td>
        <td width="50%">
            <input type='text' value='<? echo $item->name; ?>' gsname='name'>
        </td>
    </tr>
    <tr>
        <td width="50%"><? echo $this->__w("Connect this to a product"); ?></td>
        <td width="50%">
            <select gsname="productId">
                <? 
                foreach($product as $key => $product) {
                    $seleted = "";
                    if($item->productId == $product->id) {
                        $seleted = "SELECTED";
                    }
                    echo "<option value='".$product->id."' $seleted>".$product->name."</option>";
                }
                ?>
            </select>
        </td>
    </tr>
    <tr>
        <td width="50%"><? echo $this->__w("Addon type"); ?></td>
        <td width="50%">
            <select gsname="addon">
                <? 
                foreach($addons as $key => $addon) {
                    $seleted = "";
                    if($key == $item->addon) {
                        $seleted = "SELECTED";
                    }
                    echo "<option value='".$key."' $seleted>".$addon."</option>";
                }
                ?>
            </select>
        </td>
    </tr>
    <tr>
        <td width="50%"><? echo $this->__w("Is visible for booking"); ?></td>
        <td width="50%">
            <select gsname="visibleForBooking">
                <option value='false'>No</option>
                <option value='true' <?php if($item->visibleForBooking) { echo "SELECTED"; } ?>>Yes</option>
            </select>
        </td>
    </tr>
    <tr>
        <td width="50%"><? echo $this->__w("Booking size"); ?></td>
        <td width="50%">
            <input type="number" style='width: 50px;' gsname="size" value="<? echo $item->size; ?>">
        </td>
    </tr>
    <tr>
        <td width="50%">Capasity (full when counter hit this)</td>
        <td width="50%"><input type="text" gsname="capacity" style='width:100%;' value="<? echo $item->capacity; ?>"></td>
    </tr>
    <tr>
        <td width="50%">Description</td>
        <td width="50%"><textarea type="text" gsname="description" style='width:100%;'><? echo $item->description; ?></textarea></td>
    </tr>
    
    </table>
    <input gstype="submit" type="button" value='Save'>
</div>



<div gstype="form" method="editFormFieldForType">
    <input type="hidden" gsname="typeid" value="<? echo $id; ?>">
    <input type="button" gstype="submitToInfoBox" type="button" value="Open field configuration">
</div>

<hr>
<h1>Opening hours configuration</h1>
<?php $this->includefile("addmoredates"); ?>
<br><br>
<div gstype="form" method="editFormFields">
    <input type="hidden" gsname="itemid" value="<? echo $id; ?>">
    <input type="button" gstype="submitToInfoBox" type="button" value="Open field configuration">
</div>

