<?php
/* @var $this \ns_2b4a865c_6aed_416e_bf52_ab6e2428bd1f\PmsWubookConfiguration */
$action = "";
if(isset($_POST['event']) && $_POST['event'] == "doAction") {
    $action = $_POST['data']['type'];
}

if(!$action) {
    return;
}

echo "<div>";
echo "<br>";
$wubookmgr = $this->getApi()->getWubookManager();
$name = $this->getSelectedMultilevelDomainName();
if($action == "testConnection") {
    $testing = $wubookmgr->testConnection($name);
    if($testing) {
        echo "Sucesfully connected to the wubook api.";
    } else {
        echo "Unable to connect to the api, make sure the username and password set in booking admin configuration are correct.";
    }
} else if($action == "runSparseUpdate") {
    $this->getApi()->getWubookManager()->updateShortAvailability($this->getSelectedMultilevelDomainName());
} else if($action == "updateMinStay") {
    $this->getApi()->getWubookManager()->updateMinStay($this->getSelectedMultilevelDomainName());
    echo "done";
} else if($action == "activateCallback") {
    $this->getApi()->getWubookManager()->activateWubookCallback($this->getSelectedMultilevelDomainName());
    echo "done";
} else if($action == "checkForNoShows") {
    $this->getApi()->getWubookManager()->checkForNoShowsAndMark($this->getSelectedMultilevelDomainName());
} else if($action == "markCCInvalid") {
    $id = $_POST['data']['id'];
    $res = $wubookmgr->markCCInvalid($name, $id);
    if(!$res) {
        echo "OK"; 
    } else {
        echo $res;
    }
} else if($action == "doubleCheckDeletions") {
    $wubookmgr->doubleCheckDeletedBookings($name);
} else if($action == "fetchBookingCodes") {
    $res = $wubookmgr->fetchBookingCodes($name, 2);
    echo "<pre>";
    print_r($res);
    echo "</pre>";
} else if($action == "addNewRoomsPastTwoDays") {
    $res = $wubookmgr->addNewBookingsPastDays($name, 3);
    $this->printBookingTable($res);
} else if($action == "markNoShow") {
    $id = $_POST['data']['id'];
    $res = $wubookmgr->markNoShow($name, $id);
    if(!$res) {
        echo "OK"; 
    } else {
        echo $res;
    }
} else if($action == "removeFromBooking") {
    $id = $_POST['data']['id'];
    $res = $wubookmgr->deleteBooking($name, $id);
    if(!$res) {
        echo "OK"; 
    } else {
        echo $res;
    }
} else if($action == "fetchAllBookings") {
    $res = $wubookmgr->fetchAllBookings($name, 900);
    $this->printBookingTable($res);
} else if($action == "fetchNewBookings") {
    $res = $wubookmgr->fetchNewBookings($name);
    $this->printBookingTable($res);
} else if($action == "deleteAllRooms") {
    $res = $wubookmgr->deleteAllRooms($name);
    $this->printBookingTable($res);
} else if($action == "addBooking") {
    $id = $_POST['data']['id'];
    $res = $wubookmgr->addBooking($name, $id);
    print_r($res);
} else if($action == "updatePrices") {
    $res = $wubookmgr->updatePrices($name);
    if(!$res) {
        echo "Prices has been updated";
    }
} else if($action == "updateAvailability") {
    $res = $wubookmgr->updateAvailabilityFromButton($name);
    if(!$res) {
        echo "Availability has been updated";
    }
} else if($action == "addAllRooms") {
    $res = $wubookmgr->insertAllRooms($name);
    echo "<pre>";
    print_r($res);
    echo "</pre>";
} else {
    echo $action;
}

echo "<br><br>";
echo "</div>";

?>