<?php /* @var $this \ns_2b4a865c_6aed_416e_bf52_ab6e2428bd1f\PmsWubookConfiguration */

$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
$callbackactive = $config->wubookcallbackactivated ? "<span style='color:green;'>callback is active</span>" : "<span style='color:red;'>callback is not active</span>";
$callbackurl = $this->getApi()->getWubookManager()->getCallbackUrl($this->getSelectedMultilevelDomainName());
?>
<br>
    <div class='section'>
        <h2>Actions available, <?php echo $callbackactive; ?></h2>
        <div>
            <?php echo "Callback url will be: " .$callbackurl; ?>
        </div>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='testConnection' gsname='type' method='doAction'>Test connection</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='fetchAllBookings' gsname='type' method='doAction'>Fetch all bookings</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='fetchBookingCodes' gsname='type' method='doAction'>Fetch booking codes</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='fetchNewBookings' gsname='type' method='doAction'>Fetch new bookings</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='updateAvailability' gsname='type' method='doAction'>Update availability</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='updatePrices' gsname='type' method='doAction'>Update prices</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='updateMinStay' gsname='type' method='doAction'>Update minstay</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='addAllRooms' gsname='type' method='doAction'>Insert rooms to wubook</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='addNewRoomsPastTwoDays' gsname='type' method='doAction'>Add new bookings past two days</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='checkForNoShows' gsname='type' method='doAction'>Check for no shows to mark</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='deleteAllRooms' gsname='type' method='doAction'>DANGER: delete all rooms</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='doubleCheckDeletions' gsname='type' method='doAction'>Double check if all cancelations has been cancelled.</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='runSparseUpdate' gsname='type' method='doAction'>Run sparse update.</span>
        <span class='gsmodulebutton' gstype="clicksubmit" gsvalue='activateCallback' gsname='type' method='doAction'>Start wubook callback activation</span>
    </div>
<br>
<br>
<div class='section'>
    <table width="100%">
        <tr>
            <td width="50%" valign="top">
                <h2>Booking actions</h2>
                <div gstype='form' method="doAction">
                    <input type="text" gsname="id" class='gsniceinput1' placeholder='Wubook rcode'>
                    <input type="hidden" gsname="type" value='addBooking' class='gsniceinput1'>
                    <span class='gsmodulebutton' gstype="submit" style='width:190px;'>Add booking to GetShop</span>
                </div>
                <div gstype='form' method="doAction">
                    <input type="text" gsname="id" class='gsniceinput1' placeholder='Wubook rcode'>
                    <input type="hidden" gsname="type" value='markCCInvalid' class='gsniceinput1'>
                    <span class='gsmodulebutton' gstype="submit" style='width:190px;'>Mark credit card as invalid</span>
                </div>
                <div gstype='form' method="doAction">
                    <input type="text" gsname="id" class='gsniceinput1' placeholder='Wubook rcode'>
                    <input type="hidden" gsname="type" value='markNoShow' class='gsniceinput1'>
                    <span class='gsmodulebutton' gstype="submit" style='width:190px;'>Mark booking as no show</span>
                </div>
                <div gstype='form' method="doAction">
                    <input type="text" gsname="id" class='gsniceinput1' placeholder='Wubook rcode'>
                    <input type="hidden" gsname="type" value='removeFromBooking' class='gsniceinput1'>
                    <span class='gsmodulebutton' gstype="submit" style='width:190px;'>Remove from getshop pms</span>
                </div>
           </td>
            <td valign="top">
                <h2>Wubook credentials</h2>
                <div gstype='form' method="saveCredentials">
                    <table>
                        <tr>
                            <td>Username
                            </td>
                            <td><input type="text" class='gsniceinput1' placeholder='Username' gsname="username" value="<?php echo $config->wubookusername; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td>Password
                            </td>
                            <td><input type="text" class='gsniceinput1' placeholder='Password' gsname="password" value="<?php echo $config->wubookpassword; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td>Lcode
                            </td>
                            <td><input type="text" class='gsniceinput1' placeholder='lcode' gsname="lcode" value="<?php echo $config->wubooklcode; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td>Increase price by percentage
                            </td>
                            <td><input type="text" class='gsniceinput1' placeholder='0' gsname="increaseByPercentage" value="<?php echo $config->increaseByPercentage; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td>Number of rooms to decrease from OTA'S<br>
                                <b>(to avoid overbooking)</b> 
                            </td>
                            <td><input type="text" class='gsniceinput1' placeholder='0' gsname="numberOfRoomsToRemoveFromBookingCom" value="<?php echo $config->numberOfRoomsToRemoveFromBookingCom; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td>Avoid sending noshow to booking.com
                            </td>
                            <?php $checked = $config->ignoreNoShow == true ? "CHECKED" : ""; ?>
                            <td><input type="checkbox" class='gsniceinput1' gsname="ignoreNoShow" <?php echo $checked; ?>> 
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td><span class='gsmodulebutton' gstype="submit" style='width:190px;'>Save Credentials</span>
                            </td>
                        </tr>
                    </table>
                </div>
                
            </td>
        </tr>
    </table>

</div>
<br><br>
<div class='section'>
    <h2>Room map</h2>
    <div gstype="form" method="updateRoomData">
    <?php
        $otas = $this->getApi()->getWubookManager()->getOtas($this->getSelectedMultilevelDomainName());
        $data = $this->getApi()->getWubookManager()->getWubookRoomData($this->getSelectedMultilevelDomainName());
        $items = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName());
        $roommap = array();
        $items = $this->indexList($items);
        echo "<table width='100%' cellspacing='1' cellpadding='0' bgcolor='#ffffff'>";
        echo "<tr bgcolor='#efefef'>";
         echo "<th align='left'>GetShop room category</th>";
        echo "<th align='center' width='10'>Room id (wubook)</th>";
        foreach($otas as $ota) {
            echo "<th>";
            if($ota->channel == 1) { echo "Expedia"; }
            if($ota->channel == 2) { echo "Booking.com"; }
            echo  " (" . $ota->id . ")";
            echo "</th>";
            $roommap[$ota->id] = $this->getApi()->getWubookManager()->getRoomRates($this->getSelectedMultilevelDomainName(), $ota->id, $ota->channel);
        }
        echo "</tr>";

        foreach($data as $id => $rdata) {
            if(!isset($items[$rdata->bookingEngineTypeId])) {
                continue;
            }
            /* @var $rdata core_wubook_WubookRoomData */
            echo "<tr bgcolor='#efefef'>";
            echo "<td align='left'>";
            if(isset($items[$rdata->bookingEngineTypeId])) {
               echo $items[$rdata->bookingEngineTypeId]->name;
            } else {
                echo "DELETED";
            }
            echo "</td>";
            if($rdata->virtualWubookRoomIds) {
                echo "<td align='right'><input type='txt' value='".$rdata->virtualWubookRoomIds."' gsname='".$id."' class='gsniceinput1' disabled></td>";
            } else {
                echo "<td align='right'><input type='txt' value='".$rdata->wubookroomid."' gsname='".$id."' class='gsniceinput1' disabled></td>";
            }
            echo "</td>";
            
            foreach($otas as $ota) {
                echo "<td align='center'>";
                if(isset($roommap[$ota->id])) {
                    $map = $roommap[$ota->id];
                    $mapped = false;
                    foreach($map as $room) {
                        if(stristr($rdata->virtualWubookRoomIds, $room->wubookRoomId) || $room->wubookRoomId == $rdata->wubookroomid) {
                            echo $room->name . " (" . $room->id . ")";
                            $mapped = true;
                        }
                    }
                    if(!$mapped) {
                        echo "<b style='color:red;'>Not mapped</b>";
                    }
                }
                echo "</td>";
            }
            echo "</tr>";
        }
        echo "<tr bgcolor='#efefef'>";
        echo "<td></td>";
        echo "<td></td>";
        
        foreach($otas as $ota) {
//            echo "<td align='center' style='cursor:pointer;color:blue;'>remap</td>";
        }
        echo "</tr>";
        echo "</table>";
        ?> <br><br>
    <div style="text-align:right; display:none;">
        <span class='gsmodulebutton' gstype="submit">Save settings</span>
    </div>
</div>
    
</div>
<div class='section'>
    <h3>Log</h3>
    <?php
    $logentries = (array)$this->getApi()->getWubookManager()->getLogEntries($this->getSelectedMultilevelDomainName());
    krsort($logentries);
    $i = 0;
    foreach($logentries as $time => $text) {
        echo "<div class='ellipsis' title='$text'>";
        echo date("d.m.Y H:i", $time / 1000) . " : " . $text . "<bR>";
        echo "</div>";
        if($i > 100) { 
            break;
        }
        $i++;
    }
    ?>
</div>
<style>
.ellipsis {
   width:800px;
   white-space: nowrap;
   overflow: hidden;
   text-overflow: ellipsis;
}
</style>