<br>
<?php
/* @var $this ns_9de81608_5cec_462d_898c_1266d1749320\PmsConfiguration */
$coupons = (array)$this->getApi()->getCartManager()->getCoupons();
$notificationSettings = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$channelConfig = $notificationSettings->channelConfiguration;

if(sizeof($coupons) == 0) {
    echo "<b>No coupon codes added yet.</b>";
}
?>
<table width='100%' cellspacing='1' cellpadding='1'>
    <?php
    foreach($coupons as $coupon) {
        echo "<tr>";
        echo "<td>" . $coupon->type . "</td>";
        echo "<td align='left'>" . $coupon->code . "</td>";
        echo "<td>" . $coupon->amount . "</td>";
        echo "<td>" . $coupon->timesLeft . "</td>";
        echo "<td align='right'>";
        echo "<select gsname='coupon_".$coupon->id."'>";
        echo "<option value=''>Connect to channel</option>";
        foreach($channelConfig as $key => $config) {
            $selected = ($coupon->channel == $key) ? "SELECTED" : "";
            echo "<option value='$key' $selected>" . $config->humanReadableText . "</option>";
        }
        echo "</select>";
        echo "</td>";
        
        echo "</tr>";
    }
    ?>
</table>