<br>
<?php
/* @var $this ns_9de81608_5cec_462d_898c_1266d1749320\PmsConfiguration */
$coupons = (array)$this->getApi()->getCartManager()->getCoupons();
$notificationSettings = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$channelConfig = $notificationSettings->channelConfiguration;

if(sizeof($coupons) == 0) {
    echo "<b>No coupon codes added yet.</b>";
}
?>

<table width='100%' cellspacing='1' cellpadding='1'>
    <tr>
        <th></th>
        <th align='left'>Code</th>
        <th align='left'>Discount</th>
        <th align='left'>Times left</th>
        <th align='left'>Type</th>
        <th align='left'>Description</th>
        <th align='left' width='80'>Restriction</th>
        <th align='right'>Channel</th>
    </tR>
    <?php
    foreach($coupons as $coupon) {
        echo "<tr>";
        echo "<td><i class='fa fa-trash-o' gstype='clicksubmit' method='removeCoupon' gsvalue='".$coupon->id."' gsname='id' style='cursor:pointer;'</i> </td>";
        echo "<td align='left'>" . $coupon->code . "</td>";
        echo "<td>" . $coupon->amount . "</td>";
        echo "<td>" . $coupon->timesLeft . "</td>";
        echo "<td>" . $coupon->type . "</td>";
        echo "<td><i class='fa fa-edit'onclick='$(this).closest(\"td\").find(\".editcomment\").fadeIn()'></i>" . $coupon->description;
        echo "<span class='editcomment' method='savecommentoncoupon'  gstype='form'>";
        echo "<input type='hidden' gsname='couponid' value='".$coupon->id."'>";
        echo "<input type='txt' gsname='description' value='".$coupon->description."'></input><br>";
        echo "<span class='pmsbutton' gstype='submit'>Save description</span>";
        echo "</span>";
        
        echo "</td>";
        echo "<td><i class='fa fa-edit'></i> </td>";
        echo "<td align='right'>";
        echo "<select class='changechanneloncoupon' couponid='".$coupon->id."'>";
        echo "<option value=''>Connect to channel</option>";
        foreach($channelConfig as $key => $config) {
            $selected = ($coupon->channel == $key) ? "SELECTED" : "";
            echo "<option value='$key' $selected>" . $config->humanReadableText . "</option>";
        }
        echo "</select>";
        echo "</td>";
        
        echo "</tr>";
    }
    ?>
</table>
<br>
<?php
if(isset($this->addCouponError) && $this->addCouponError) {
    echo "<div style='font-size: 16px; color: red; font-weight:bold;'>";
    echo $this->addCouponError;
    echo "</div>";
}
?>

<div gstype='form' method='createcoupon'>
    <label style='font-size: 12px; display:inline-block;'>
        Name of the code<br>
        <input type='text' gsname='code'>
    </label>
    <label style='font-size: 12px; display:inline-block;'>
        * Times<br>
        <input type='text' gsname='times' value='1' style='width:40px;'>
    </label>
    <label style='font-size: 12px; display:inline-block;'>
        * Amount<br>
        <input type='text' gsname='amount' style='width:60px;'>
    </label>
    <label style='font-size: 12px; display:inline-block;'>
        Type<br>
        <select gsname='type'>
            <option value='PERCENTAGE'>Percentage</option>
            <option value='FIXED'>Fixed discount</option>
            <option value='FIXEDPRICE'>Fixed price</option>
        </select>
    </label>
    <span class='pmsbutton' gstype='submit'>Add discount coupon</span>
    <div style='font-size: 12px;'>* Times: specify the number of times you want the code to be active for</div>
    <div style='font-size: 12px;'>* Amount: the amount to discount, if percentage enter the percentage as a number</div>
</div>