<?php
/* @var $this \ns_9de81608_5cec_462d_898c_1266d1749320\PmsConfiguration */
$notificationSettings = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
/* @var $factory Factory */
$factory = $this->getFactory();
$langauge = $factory->getCurrentLanguage();

$notifications = array();
$notifications['room_starting_0_hours_'.$langauge] = "Booking is started.";
$notifications['room_starting_4_hours_'.$langauge] = "Booking starting in 4 hours";
$notifications['room_starting_24_hours_'.$langauge] = "Booking starting in 1 day";
$notifications['room_starting_48_hours_'.$langauge] = "Booking starting in 2 days";
$notifications['booking_completed_'.$langauge] = "Booking has been completed";
$notifications['booking_confirmed_'.$langauge] = "Booking has been confirmed";
$notifications['room_ended_0_hours_'.$langauge] = "Booking has ended.";
$notifications['room_ended_24_hours_'.$langauge] = "Booking ended 1 day ago";
$notifications['room_ended_48_hours_'.$langauge] = "Booking ended two days ago";
$contractfield = "contract_$langauge";

$whenToPay = array();
$whenToPay[1] = "When booking";
$whenToPay[2] = "On confirmation";
$whenToPay[3] = "At check in date";
$whenToPay[4] = "After stay";
?>

<h1>Booking notification system</h1>

<span class="changeview pmsbutton active" data-panel='email_notifcations'>Emails</span>
<span class="changeview pmsbutton" data-panel='sms_notifcations'>Sms'es</span>
<span class="changeview pmsbutton" data-panel='admin_notifications'>Admin messages</span>
<span class="changeview pmsbutton" data-panel='email_template'>Email template</span>
<span class="changeview pmsbutton" data-panel='contracts'>Contracts</span>
<span class="changeview pmsbutton" data-panel='other_config'>Other configuration</span>
<div style='padding-top: 20px;'>
    Variables: {code},
    {room},
    {rooms}, 
    {checkin_date}, 
    {checkin_time},
    {checkout_date},
    {checkout_time},
    {name},
    {referenceNumber},
    {roomName}, 
    {roomType}, 
    {email}, 
    {city},
    {address}, 
    {postCode},
    {contact_name},
    {contact_prefix},
    {contact_phone},
    {contact_email}
</div>

<div gstype="form" method="saveNotifications">
    <div class='email_notifcations notificationpanel'>
        <?php
        foreach($notifications as $index => $name) {
            echo "<h2>$name</h2>";
            echo "<textarea gsname='".$index."_email' style='width: 100%; height: 400px;'>";
            if(isset($notificationSettings->emails->{$index})) {
                echo $notificationSettings->emails->{$index};
            }
            echo "</textarea>";
        }
        ?>
    </div>

    <div class='sms_notifcations addons'>
        Addons
    </div>
    
    <div class='sms_notifcations notificationpanel'>
        <?php
        foreach($notifications as $index => $name) {
            if($this->startsWith($index, "room_")) {
                $name = $name . " sent to all guests";
            } else {
                $name = $name . " sent to booker";
            }
            echo "<h2>$name</h2>";
            echo "<textarea gsname='".$index."_sms' style='width: 100%; height: 100px;'>";
            if(isset($notificationSettings->smses->{$index})) {
                echo $notificationSettings->smses->{$index};
            }
            echo "</textarea>";
        }
        ?>
    </div>

    <div class='admin_notifications notificationpanel'>
        <?php
        foreach($notifications as $index => $name) {
            echo "<h2>$name</h2>";
            echo "<textarea gsname='".$index."_admin' style='width: 100%; height: 100px;'>";
            if(isset($notificationSettings->adminmessages->{$index})) {
                echo $notificationSettings->adminmessages->{$index};
            }
            echo "</textarea>";
        }
        ?>
    </div>

    <div class='email_template notificationpanel'>
        <h2>The email template to use when sending emails</h2>
        <textarea gsname='emailTemplate' style='width: 100%; height: 300px;'><?php echo $notificationSettings->emailTemplate; ?></textarea>
    </div>
    
    <div class='contracts notificationpanel'>
        <h2>
            Contracts
        </h2>
        <div id="contractfield" gsname='<? echo $contractfield; ?>' style="border: solid 1px; min-height: 400px;"><?
            if(isset($notificationSettings->contracts->{$langauge})) {
                echo $notificationSettings->contracts->{$langauge};
            }
        ?></div>
    </div>
    
    <div class='other_config notificationpanel'>
        <h2>
            Other configurations
        </h2>
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->needConfirmation) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='needConfirmation' <? echo $checked; ?>>
            </span>
            Need confirmation
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->requirePayments) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='requirePayments' <? echo $checked; ?>>
            </span>
            Payments are required
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->exposeUnsecureBookings) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='exposeUnsecureBookings' <? echo $checked; ?>>
            </span>
            Expose bookings unsecure (for visibility in calendar)
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->needToAgreeOnContract) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='needToAgreeOnContract' <? echo $checked; ?>>
            </span>
            Make sure the customers agree to the terms and conditions
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->autoconfirmRegisteredUsers) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='autoconfirmRegisteredUsers' <? echo $checked; ?>>
            </span>
            Registered users are autoconfirmed.
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <select gsname='whenToPay'>
                    <? 
                    foreach($whenToPay as $idx => $value) {
                        $selected = "";
                        if($notificationSettings->whenToPay ==$idx) {
                            $selected = "SELECTED";
                        }
                        echo "<option value='$idx' $selected>$value</option>";
                    }
                    ?>
                </select>
            </span>
            When does the customers need to pay
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input type='number' style='width: 40px;' gsname='cleaningInterval' value='<? echo $notificationSettings->cleaningInterval; ?>'>
            </span>
            Cleaning interval default
        </div>
        <br><br>
        <h2>Arx settings</h2>
        <div class='configrow'>
            <span class='configentry'>
                <input type='text' gsname='arxHostname' value='<? echo $notificationSettings->arxHostname; ?>'>
            </span>
            Arx hostname
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input type='text' gsname='arxUsername' value='<? echo $notificationSettings->arxUsername; ?>'>
            </span>
            Arx username
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input type='text' gsname='arxPassword' value='<? echo $notificationSettings->arxPassword; ?>'>
            </span>
            Arx password
        </div>
    </div>
    <br><br>
    <div style='text-align: right;'>
        <span class='pmsbutton' gstype='submit'>Save changes</span>
    </div>
</div>

