<?php
/* @var $this \ns_9de81608_5cec_462d_898c_1266d1749320\PmsConfiguration */
$notificationSettings = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
/* @var $factory Factory */
$factory = $this->getFactory();
$langauge = $factory->getCurrentLanguage();

$hasEventCalendar = false;
$instances = $this->getApi()->getStoreApplicationInstancePool()->getApplicationInstances("27e174dc-b08c-4bf7-8179-9ea8379c91da");
foreach($instances as $instance) {
    if($instance->settings->{"engine_name"}->value == $this->getSelectedName()) {
        $hasEventCalendar = true;
    }
}

$locktype = array();
$locktype['arx'] = "Arx";
$locktype['getshop'] = "GetShop";

$hasArx = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName())->arxHostname;

$notifications = array();
$notifications['room_starting_0_hours_'.$langauge] = "Booking is started.";
$notifications['room_starting_4_hours_'.$langauge] = "Booking starting in 4 hours";
$notifications['room_starting_24_hours_'.$langauge] = "Booking starting in 1 day";
$notifications['room_starting_48_hours_'.$langauge] = "Booking starting in 2 days";
$notifications['booking_completed_'.$langauge] = "Booking has been completed";
$notifications['booking_confirmed_'.$langauge] = "Booking has been confirmed";
$notifications['booking_notconfirmed_'.$langauge] = "Booking has been rejected";
$notifications['room_ended_0_hours_'.$langauge] = "Booking has ended.";
$notifications['room_ended_24_hours_'.$langauge] = "Booking ended 1 day ago";
$notifications['room_ended_48_hours_'.$langauge] = "Booking ended two days ago";
if($hasArx) {
    $notifications['room_added_to_arx_'.$langauge] = "Room has been added to arx";
    $notifications['room_removed_from_arx_'.$langauge] = "Room has been removed from arx";
}
if($hasEventCalendar) {
    $notifications['booking_eventcalendar_'.$langauge] = "Message to send to event helder in the event calendar";
}
$contractfield = "contract_$langauge";
$defaultmessage = "defaultmessage_$langauge";

$whenToPay = array();
$whenToPay[1] = "When booking";
$whenToPay[2] = "On confirmation";
$whenToPay[3] = "At check in date";
$whenToPay[4] = "After stay";
?>

<h1>Booking notification system</h1>

<span class="changeview pmsbutton active" data-panel='email_notifcations'>Emails</span>
<span class="changeview pmsbutton" data-panel='sms_notifcations'>Sms'es</span>
<span class="changeview pmsbutton" data-panel='admin_notifications'>Admin messages</span>
<span class="changeview pmsbutton" data-panel='email_template'>Email template</span>
<span class="changeview pmsbutton" data-panel='contracts'>Contracts</span>
<span class="changeview pmsbutton" data-panel='defaultmessage'>Default message</span>
<span class="changeview pmsbutton" data-panel='other_config'>Other configuration</span>
<div style='padding-top: 20px;'>
    Variables: {code},
    {room},
    {rooms}, 
    {checkin_date}, 
    {checkin_time},
    {checkout_date},
    {checkout_time},
    {name},
    {referenceNumber},
    {roomName}, 
    {roomType}, 
    {email}, 
    {city},
    {address}, 
    {postCode},
    {contact_name},
    {contact_prefix},
    {contact_phone},
    {contact_email},
    {personalMessage},
    {roomlist},
    {bookingid},
    {bookinginformation}
</div>

<div gstype="form" method="saveNotifications">
    <div class='email_notifcations notificationpanel'>
        <?php
        foreach($notifications as $index => $name) {
            echo "<h2>$name</h2>";
            echo "<input type='txt' gsname='".$index."_title' style='width:100%; box-sizing:border-box;' value='".@$notificationSettings->emailTitles->{$index}."'><br>";
            echo "<textarea gsname='".$index."_email' style='width: 100%; height: 400px; box-sizing:border-box;'>";
            if(isset($notificationSettings->emails->{$index})) {
                echo $notificationSettings->emails->{$index};
            }
            echo "</textarea>";
        }
        ?>
    </div>

    <div class='sms_notifcations addons'>
        Addons
    </div>
    
    <div class='sms_notifcations notificationpanel'>
        <?php
        foreach($notifications as $index => $name) {
            if($this->startsWith($index, "room_")) {
                $name = $name . " sent to all guests";
            } else {
                $name = $name . " sent to booker";
            }
            echo "<h2>$name</h2>";
            echo "<textarea gsname='".$index."_sms' style='width: 100%; height: 100px;'>";
            if(isset($notificationSettings->smses->{$index})) {
                echo $notificationSettings->smses->{$index};
            }
            echo "</textarea>";
        }
        ?>
    </div>

    <div class='admin_notifications notificationpanel'>
        <?php
        foreach($notifications as $index => $name) {
            echo "<h2>$name</h2>";
            echo "<textarea gsname='".$index."_admin' style='width: 100%; height: 100px;'>";
            if(isset($notificationSettings->adminmessages->{$index})) {
                echo $notificationSettings->adminmessages->{$index};
            }
            echo "</textarea>";
        }
        ?>
    </div>

    <div class='email_template notificationpanel'>
        <h2>The email template to use when sending emails</h2>
        <textarea gsname='emailTemplate' style='width: 100%; height: 300px;'><?php echo $notificationSettings->emailTemplate; ?></textarea>
    </div>
    
    <div class='contracts notificationpanel'>
        <h2>
            Contracts
        </h2>
        <div id="contractfield" gsname='<? echo $contractfield; ?>' style="border: solid 1px; min-height: 400px;"><?
            if(isset($notificationSettings->contracts->{$langauge})) {
                echo $notificationSettings->contracts->{$langauge};
            }
        ?></div>
    </div>
    
    <div class='defaultmessage notificationpanel'>
        <h2>
            Default message to customer
        </h2>
        <textarea gsname='defaultmessage' style="border: solid 1px; min-height: 100px; width:100%;"><?
            if(isset($notificationSettings->defaultMessage->{$langauge})) {
                echo $notificationSettings->defaultMessage->{$langauge};
            }
        ?></textarea>
    </div>
    
    <div class='other_config notificationpanel'>
        <h2>
            Other configurations
        </h2>
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->needConfirmation) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='needConfirmation' <? echo $checked; ?>>
            </span>
            Need confirmation
        </div>
        
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->exposeUnsecureBookings) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='exposeUnsecureBookings' <? echo $checked; ?>>
            </span>
            Expose bookings unsecure (for visibility in calendar)
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->needToAgreeOnContract) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='needToAgreeOnContract' <? echo $checked; ?>>
            </span>
            Make sure the customers agree to the terms and conditions
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->supportMoreDates) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='supportMoreDates' <? echo $checked; ?>>
            </span>
            Support repetition / adding more dates to the booking.
        </div>
        
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->autoconfirmRegisteredUsers) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='autoconfirmRegisteredUsers' <? echo $checked; ?>>
            </span>
            Registered users are autoconfirmed.
        </div>
        
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->isItemBookingInsteadOfTypes) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='isItemBookingInsteadOfTypes' <? echo $checked; ?>>
            </span>
            Is item booking instead of type booking.
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input type='number' style='width: 40px;' gsname='cleaningInterval' value='<? echo $notificationSettings->cleaningInterval; ?>'>
            </span>
            Cleaning interval default (0, disabled)
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input type='number' style='width: 40px;' gsname='minStay' value='<? echo $notificationSettings->minStay; ?>'>
            </span>
            Minimum stay
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <select gsname='bookingTimeInterval'>
                    <option value="1">Hourly</option>
                    <option value="2" <?php if($notificationSettings->bookingTimeInterval == 2) { echo "SELECTED"; } ?> >Daily</option>
                </select>
            </span>
            Booking interval type
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input style='width: 40px;' gsname='defaultStart' value='<? echo $notificationSettings->defaultStart; ?>'>
            </span>
            Default start
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input style='width: 40px;' gsname='defaultEnd' value='<? echo $notificationSettings->defaultEnd; ?>'>
            </span>
            Default end
        </div>
        <br><br>
        <h2>
            Payment and order creations
        </h2>
<div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->prepayment) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='prepayment' <? echo $checked; ?>>
            </span>
            Prepayment, customers pay ahead of their stay
        </div>

        <div class='configrow'>
            <span class='configentry'>
                <input type='number' style='width: 40px;' gsname='createOrderAtDayInMonth' value='<? echo $notificationSettings->createOrderAtDayInMonth; ?>'>
            </span>
            Specify a specific date in month to create the orders (0 is turned off).
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <?
                $checked = "";
                if($notificationSettings->requirePayments) {
                    $checked = "CHECKED";
                }
                ?>
                <input type='checkbox' gsname='requirePayments' <? echo $checked; ?>>
            </span>
            Payments are required (force payment view when booking is completed)
        </div>
        <br><br>
        <h2>Lock settings</h2>
        <div class='configrow'>
            <span class='configentry'>
                <select gsname='locktype'>
                    <?php
                    foreach($locktype as $idx => $value) {
                        $selected = "";
                        if($notificationSettings->locktype == $idx) {
                            $selected = "SELECTED";
                        }
                        echo "<option value='$idx' $selected>$value</option>";
                    }
                    ?>
                </select>
            </span>
            Lock Type
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input type='text' gsname='arxHostname' value='<? echo $notificationSettings->arxHostname; ?>'>
            </span>
            Lock hostname
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input type='text' gsname='arxUsername' value='<? echo $notificationSettings->arxUsername; ?>'>
            </span>
            Lock username
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input type='text' gsname='arxPassword' value='<? echo $notificationSettings->arxPassword; ?>'>
            </span>
            Lock password
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input type='text' gsname='arxCardFormat' value='<? echo $notificationSettings->arxCardFormat; ?>'>
            </span>
            Kort format
        </div>
        <div class='configrow'>
            <span class='configentry'>
                <input type='text' gsname='codeSize' value='<? echo $notificationSettings->codeSize; ?>'>
            </span>
            Code size (on the code sent to the user)
        </div>
    </div>
    <br><br>
    <div style='text-align: right;'>
        <span class='pmsbutton' gstype='submit'>Save changes</span>
    </div>
</div>

