<?php
/* @var $this \ns_9de81608_5cec_462d_898c_1266d1749320\PmsConfiguration */
$selectedAddonConfig = $this->getSelectedAddonConfig();
$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());

if(!$selectedAddonConfig) {
    $selectedAddonConfig = new core_pmsmanager_PmsBookingAddonItem();
}
$includedIn = (array)$selectedAddonConfig->includedInBookingItemTypes;
?>
<div gstype="form" method="saveProductConfig">
    <input type='hidden' gsname='productId' gsvalue='<?php echo $_POST['data']['id']; ?>'>
    <table width="80%" class="contactConfigTable">
        <tr>
            <td width="50%"><? echo $this->__w("Count"); ?></td>
            <td width="50%"><input type="text" gsname="count" style='width:100%;' value="<? echo $selectedAddonConfig->count; ?>"></td>
        </tr>
        <tr>
            <td width="50%">Is included in room price</td>
            <?php $CHECKED = ($selectedAddonConfig->isIncludedInRoomPrice) ? "CHECKED" : ""; ?>
            <td width="50%"><input type="checkbox" gsname="isIncludedInRoomPrice" style='width:100%;' <?php echo $CHECKED; ?>></td>
        </tr>
        <tr>
            <td width="50%">Is per guest</td>
            <?php $CHECKED = ($selectedAddonConfig->dependsOnGuestCount) ? "CHECKED" : ""; ?>
            <td width="50%"><input type="checkbox" gsname="dependsOnGuestCount" style='width:100%;' <?php echo $CHECKED; ?>></td>
        </tr>
        <tr>
            <td width="50%">Non refundable addon (used as cancelations etc)</td>
            <?php $CHECKED = ($selectedAddonConfig->noRefundable) ? "CHECKED" : ""; ?>
            <td width="50%"><input type="checkbox" gsname="noRefundable" style='width:100%;' <?php echo $CHECKED; ?>></td>
        </tr>
        <tr>
            <td width="50%">Web description</td>
            <td width="50%"><input type="text" gsname="descriptionWeb" style='width:100%;' value="<? echo $selectedAddonConfig->descriptionWeb; ?>"></td>
        </tr>
    </table>
    <br><br>
    Is included for types<br>
    <?php
    foreach($types as $type) {
        $checked = in_array($type->id, $includedIn) ? "CHECKED" : "";
        echo "<input type='checkbox' gsname='includefortype_".$type->id."' $checked>" . $type->name . "<br>";
    }
    ?>
    
    <input gstype="submit" type="button" value='Save'>
</div>


<?php
$validDateranges = (array)$selectedAddonConfig->validDates;
$rangetype = array();
$rangetype[1] = "On stay";
$rangetype[2] = "On booking";
echo "<br>";
if(empty($validDateranges)) {
    echo "Valid for all dates<br>";
} else {
    echo "<div gstype='form' method='removeValidTimeRange'>";
    echo "<input type='hidden' value='".$_POST['data']['id']."' type='hidden' gsname='id'>";
    foreach($validDateranges as $vdate) {
        echo "<i class='fa fa-trash-o' style='cursor:pointer;' gstype='forceClicksubmitToInfoBox' gsname='rangeid' gsvalue='".$vdate->id."'></i> ";
        echo date("d.m.Y", strtotime($vdate->start));
        echo " - ";
        echo date("d.m.Y", strtotime($vdate->end));
        echo " (" . $rangetype[$vdate->validType]. ")<br>";
    }
    echo "</div>";
}
echo "<br>";
echo "<div gstype='form' method='addDateRange'>";
echo "<input type='hidden' value='".$_POST['data']['id']."' type='hidden' gsname='id'>";
echo "<b>Create a new date range:</b><br>";
echo "<input type='text' gsname='start' class='start_date_input'>";
echo "<input type='text' gsname='end' class='end_date_input'>";
echo "<select gsname='validtype'>";
foreach($rangetype as $id => $name) {
    echo "<option value='$id'>$name</option>";
}
echo "</select> ";
echo "<input type='button' gstype='submitToInfoBox' value='Set valid date range'>";
echo "</div>";
?>

<script>
     $('.start_date_input').datepicker({ dateFormat: "dd.mm.yy", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true});
     $('.end_date_input').datepicker({ dateFormat: "dd.mm.yy", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true});
</script>