<div class='gss_settings_header'>
    <i class='fa fa-menu'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Menu editor"); ?>
        </div>

        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("There are a few default behavoirs that can be changed.");
            ?>	
        </div>
    </div>       
</div>

<div class='gss_settings_content'>
    <div class="textfield gss_setting"  id="disableMenuItemsInsteadOfHide">
        <span class="title"><?php echo $this->__f("Disble menu items"); ?></span>
        <div class="gss_onoff" gs_model="menumodel" gs_model_attr="disableMenuItemsInsteadOfHide">
            <?
            $faclass = $this->getConfigurationSetting("disableMenuItemsInsteadOfHide") == "true" ? "fa-toggle-on" : "fa-toggle-off";
            ?>
            Off<i class="fa <? echo $faclass; ?>"></i>On
        </div>
        <div class="description">
            <?php echo $this->__("If user is not logged in and does not have access, disable menu entries instead of hide them."); ?>
        </div>
    </div>
    
    
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveGlobalSettings" gss_model="menumodel" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Update"); ?></div>
    </div>

</div>