<?
$entries = $this->getMenuEntries();
$hiddenMenu = "hidden_simple_menu";

if (!count($entries)) {
    echo $this->__f("Almost there! Click on the plus to add your first menu entry for this menu");
    $hiddenMenu = "";
}
?>

<div class="menuentries">
    <?
    foreach ($entries as $entry) {
        $name = $entry->name;
        $linkName = \GetShopHelper::makeSeoUrl($entry->name);
        $pageId = $entry->pageId;
        echo "<div class='entry'><a ajaxlink='/?page=$pageId' href='$linkName'><div>$name</div></a></div>";
    }
    ?>
</div>

<?
if ($this->isEditorMode()) {
?>
<div class="menu_simple_menu <? echo $hiddenMenu; ?>">
    <div class="simpleadd">
        <div class="simepladd_dialog">
            <? echo $this->__f("Enter the name of the page"); ?>
            <br/><input type="textfield" class="addtext"/> <span class="saveit" title="Save entry"><i class="fa fa-save"></i></span>
        </div>
        <div title="<? echo $this->__f("add entry"); ?>"><i class="fa fa-plus-circle"></i></div>
    </div>

    <? if (sizeof($entries) > 0) { ?>
        <div class="showedit" title="go to menu editor">
            <i class="fa fa-gear"></i>
        </div>
    <? } ?>
</div>

<? } ?>
