<?
/* @var $this \ns_4194456a_09b3_4eca_afb3_b3948d1f8767\QuestBackResultPrinter */
$test = $this->getCurrentTest();

$cats = $this->getCategories();
foreach ($cats as $cat) {
    echo "<div class='category_row'>";
        $class = "";
        $text = "";
        if ($cat->result < $test->redTo) {
            $class =  "red";
            $text = $test->redText;
        }
        
        if ($cat->result <= $test->yellowTo && $cat->result >= $test->yellowFrom) {
            $class =  "yellow";
            $text = $test->yellowText;
        }
        
        if ($cat->result > $test->greenFrom) {
            $class =  "green";
            $text = $test->greenText;
        }
        
    
        echo "<div class='trafficlight trafficlight_$class'></div>";
        echo "<div class='category_content'>";
            echo "<div class='category_title'>".$cat->name." ( $cat->result% riktige ) </div>";
            echo "<div class='cat_text_description'>";
                echo nl2br($text);  
            echo "</div>";
        echo "</div>";
        
        
    echo "</div>";
}
?>