<div class="gs_user_menu">
    <div class="gss_button" gss_fragment='projectlist' gss_view='gs_c3project_workarea'><i class="fa fa-list"></i><? echo $this->__f("All projects"); ?></div>
    <br/><div class="gss_button" gss_fragment='newproject' gss_view='gs_c3project_workarea'><i class="fa fa-plus"></i><? echo $this->__f("New project"); ?></div>
</div>

<div class="gs_c3project_workarea">
    <?
    $this->includefile('projectlist');
    ?>
</div>