<?
/* @var $this ns_af54ced1_4e2d_444f_b733_897c1542b5a8\PmsPaymentProcess */
$order = $this->getApi()->getOrderManager()->getOrder($_SESSION['ns_af54ced1_4e2d_444f_b733_897c1542b5a8_orderid']);
$invoiceData = new \stdClass();
$invoiceData->order = $order;
$invoiceData->accountingDetails = $this->getApi()->getInvoiceManager()->getAccountingDetails();
$serializedOrder = json_encode($invoiceData);

$app = $this->getApi()->getGetShopApplicationPool()->get("486009b1-3748-4ab6-aa1b-95a4d5e2d228");
$defaultAction = $this->getFactory()->getApplicationPool()->createInstace($app);
$defaultAction->order = $order;

$idArr = explode("\\", $order->payment->paymentType);
$id = $idArr[0];
$id = str_replace("_", "-", $id);
$id = str_replace("ns-", "", $id);
$app = $this->getApi()->getStoreApplicationPool()->getApplication($id);
$paymentApp = $this->getFactory()->getApplicationPool()->createInstace($app);
$paymentApp->setCurrentOrder($order);

$fullsize = $paymentApp->hasPaymentProcess() ? "" : "fullsize";

echo "<div class='paymentheaderoptions'>";
    $defaultAction->renderStandAlone();
echo "</div>";
?>

<div class="receipt_template <? echo $fullsize; ?>">
    <div class="receipt_template_inner">
        <?
        include 'scripts/invoicetemplates/template2.php';
        ?>
    </div>
</div>

<div class="payment_method_options <? echo $fullsize; ?>">
    
    <div class="paymenttypeheader">
        <? echo $paymentApp->getName(); ?>
    </div>
    
    <div class="paymentoptions">
        <? echo $paymentApp->renderStandAlone(); ?>
    </div>
</div>

<style>
    .gsoverlay3 .gsoverlayinner { background-color: #f5f8fa; }
</style>