<?
/* @var $this ns_af54ced1_4e2d_444f_b733_897c1542b5a8\PmsPaymentProcess */
$paymentMethods = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();

unset($_SESSION['ns_af54ced1_4e2d_444f_b733_897c1542b5a8_selected_userid'] );
?>

<div class="header">
    <? echo $this->__f("Step 1 - Please select payment method"); ?>
    <span style='float:right; cursor:pointer; font-size: 12px; color:#bbb;' onclick='$(".hiddenfrompaymentprocess").css("display","inline-block");'>Show hidden payment methods</span>
</div>
<div class='paymentmethodsselection'>
    <?
    $hasNewOrderSupport = $this->getApi()->getStoreManager()->supportsCreateOrderOnDemand();
    if($hasNewOrderSupport) {
        ?>
        <div class='getshop_box_1' style='background-color:#23314e;' gsclick="startOnlinePaymentRequest">
        <div class="descriptionimage"><img src="/skin/paymenticons/cash.svg"></div>
        <div class='title'>ONLINE PAYMENT REQUEST</div>
        </div>
        <?php
    }
    foreach ($paymentMethods as $method) {
        if ($method->id == "60f2f24e-ad41-4054-ba65-3a8a02ce0190") {
            continue;
        }
        if ($method->id == "cbe3bb0f-e54d-4896-8c70-e08a0d6e55ba") {
            continue;
        }
        
        $appInstance = $this->getFactory()->getApplicationPool()->createInstace($method);
        $color = $appInstance->getColor();
        $icon = $appInstance->getIcon();
        if($appInstance->hasPaymentLink() && $this->getApi()->getStoreManager()->supportsCreateOrderOnDemand()) {
            continue;
        }
        
        $value = $appInstance->getConfigurationSetting("hidefrombookingprocess");
        $hiddenFromPayment = "";
        if($value == "true" || $appInstance->hiddenFromPaymentProcess()) {
            $hiddenFromPayment = "hiddenfrompaymentprocess";
        }

        
        ?>
        <div class="getshop_box_1 <? echo $color. " " . $hiddenFromPayment; ?>" goto="checkavailability" gsclick="selectPaymentMethod" method="<? echo $method->id; ?>">

            <div class="descriptionimage">
                <img src="/skin/paymenticons/<?php echo $icon; ?>">
            </div>

            <div class="title"><? echo $appInstance->getName(); ?></div>
            <div class="description">
                <?
                if (method_exists($appInstance, "getShortPaymentDescription")) {
                    echo $appInstance->getShortPaymentDescription();
                }
                ?>
            </div>
        </div>
        <?
    }
    ?>

</div>