<?
/* @var $this ns_af54ced1_4e2d_444f_b733_897c1542b5a8\PmsPaymentProcess */
$bookings = $this->getSelectedBookings();
$fstartDate = isset($_SESSION['ns_af54ced1_4e2d_444f_b733_897c1542b5a8_startdate']) ? $_SESSION['ns_af54ced1_4e2d_444f_b733_897c1542b5a8_startdate'] : "";
$fendDate = isset($_SESSION['ns_af54ced1_4e2d_444f_b733_897c1542b5a8_enddate']) ? $_SESSION['ns_af54ced1_4e2d_444f_b733_897c1542b5a8_enddate'] : "";
$visibilityDate = $fstartDate && $fendDate ? "block" : "none";
$uniqueSegmentIds = array();
foreach ($bookings as $booking) {
    $uniqueSegmentIds[] = $booking->segmentId;
}
$uniqueSegmentIds = array_unique($uniqueSegmentIds);
$hasConferences = $this->getApi()->getPosManager()->hasConferences();
?>
<br/>
<br/>

    
<div class='header' style='position: relative; height: 43px;'>
    <? 
    echo $this->__f("Step 3 - Select orderlines");
    ?>
</div>

<div style='background-color: #EFEFEF; padding: 10px;'>
    <b><? echo $this->__f("Quick selection").":"; ?></b>
    <br/>
    <div class='shop_button toggledatefilter' >
        <i class='fa fa-calendar-plus-o'></i> <? echo $this->__f("Apply filter by dates"); ?>
    </div> 
    
    <div class='shop_button toggleaccomodation toggleselector' >
        <i class='fa fa-bed'></i> <? echo $this->__f("Accommodation"); ?>
    </div> 
    
    <div class='shop_button toggleaddoninc toggleselector' >
        <i class='fa fa-plus'></i> <? echo $this->__f("Addons (included)"); ?>
    </div>
    
    <div class='shop_button toggleaddonsex toggleselector' >
        <i class='fa fa-plus'></i> <? echo $this->__f("Addons (not included)"); ?>
    </div>
    
    <div class='shop_button showcalc' >
        <i class='fa fa-percent'></i> <? echo $this->__f("Calculate price"); ?>
    </div>
    
</div>

<div class='percentfilter' style='text-align: center; border: solid 1px #DDD; display: none;' gstype='form' method='applyDateFilter' >
    
    <div style='background-color: #ffffa2; padding: 5px; '>
        <?
        echo $this->__f("You can change both the percent and the total amount to calculate new prices for the selected rows");
        ?>
    </div>
    
    <div>
        <span style='text-align: center; width: 122px; display: inline-block'>Percent</span>
        <i class='fa fa-arrows-h'></i> 
        <span style='text-align: center; width: 122px; display: inline-block'>Total amount</span>
    </div>
    
    <input class='gsniceinput1 percentcalculator' style='text-align: center; width: 100px; display: inline-block' value="100"/> <i class='fa fa-arrows-h'></i> <input class='gsniceinput1 totalval totalvalcalculator' style='text-align: center; width: 100px;'/>
</div>

<div class='datefilter' style='text-align: center; border: solid 1px #DDD; display: <? echo $visibilityDate; ?>' gstype='form' method='applyDateFilter' >
    <input gsname='startdate' class='gsniceinput1 filter_date_start' style='margin: 10px;' value='<? echo $fstartDate; ?>'/> - <input gsname='enddate' class='gsniceinput1 filter_date_end' style='margin: 10px;' value='<? echo $fendDate; ?>'/>
    <div gstype='submit' class='shop_button'><? echo $this->__f("Apply"); ?></div>
</div>

<script>
    $('.filter_date_start').datepicker({dateFormat: "dd.mm.yy"});
    $('.filter_date_end').datepicker({dateFormat: "dd.mm.yy"});
</script>
    
<?
$distinctUserIds = array();

if (count($uniqueSegmentIds) > 1) {
    echo "<div style='font-size: 16px; padding-top: 30px; padding-bottom: 30px;'>".$this->__f("Not possible. Make sure that all rooms you have selected are on the same segment before continuing..")."</div>";
} else {

    foreach ($bookings as $booking) {
        $distinctUserIds[] = $booking->userId;
        $extrainforforbooking = "";
        if ($booking->userId) {
            $user = $this->getApi()->getUserManager()->getUserById($booking->userId);
            if ($user) {
                $extrainforforbooking = " - ".$user->fullName;
            }
        }
        ?>
        <div class='sub_header'>
            <? echo $this->__f("Booking").": ". $booking->incrementBookingId; ?>
        </div>

        <div class="cart_room_summary">

            <?
            foreach ($booking->rooms as $room) {
                $firstDate = date('d.m.Y', strtotime($room->date->start));
                $endDate = date('d.m.Y', strtotime($room->date->end));
                $firstGuestName = $room->guests ? $room->guests[0]->name : "";
                if (!$this->isSelectedRoom($room->pmsBookingRoomId)) {
                    continue;
                }
                $unpaidOrders = $this->getApi()->getPmsInvoiceManager()->getAllUnpaidOrdersForRoom($this->getSelectedMultilevelDomainName(), $room->pmsBookingRoomId);
                $hasUnpaidOrders = (is_array($unpaidOrders) && sizeof($unpaidOrders) > 0);
                if($hasUnpaidOrders) {
                    $hasUnpaidOrders = "<i class='fa fa-warning' style='color:red;' title='You have unpaid orders'></i>";
                }

                echo "<div class='room' roomid='$room->pmsBookingRoomId'>";
                    echo "<div class='roominformation row toggleshowdetailedroomview' style='position: relative;'>";
                        echo "<div class='col' style='margin-left: 10px; width: 200px;'>".$this->formatRoomHeader($room)."</div>";
                        echo "<div class='col' style='margin-left: 5px; width: 100px;'>".$firstDate."</div>";
                        echo "<div class='col' style='margin-left: 5px; width: 100px;'>".$endDate."</div>";
                        echo "<div class='col' style='margin-left: 10px; width: calc(100% - 550px);'>".$firstGuestName."</div>";
                        echo "<div class='col' style='margin-left: 10px;'>$hasUnpaidOrders <span class='totalforroom'></span></div>";
                        echo "<div class='col' style='margin-left: 10px;'><i style='position: absolute; right: 10px; top: 5px; font-size: 25px;' class='fa fa-angle-down'></i></div>";
                    echo "</div>";
                    $summary = $this->getApi()->getPmsManager()->getSummaryWithoutAccrued($this->getSelectedMultilevelDomainName(), $booking->id, $room->pmsBookingRoomId);
                    usort($summary->rows, array("ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView", "sortSummaryRowByDate"));
                    $anyFound = false;
                    echo "<div style='display: none;' class='detaileditemlines'>";
                        if($hasUnpaidOrders) {
                            echo "<div style='background-color:#4d3838; color:#fff; padding: 20px;font-size: 16px;'>";
                            echo "<div style='border-bottom: solid 1px; padding: 10px; margin-bottom: 10px;text-align:center;'><i class='fa fa-warning'></i> There is already started payments that needs to be handled if you want to charge the total amount for this room.</div>";
                            foreach($unpaidOrders as $tmpOrd) {
                                echo "<div>";
                                echo "Order " . $tmpOrd->incrementOrderId . " with a total amount of ";
                                echo $this->getApi()->getOrderManager()->getTotalAmount($tmpOrd);
                                echo " - <span class='showOrderSummary' style='color:#4da6cb; cursor:pointer;' orderid='".$tmpOrd->id."'>open order</span>";
                                if(!$tmpOrd->closed) {
                                    echo " - <span gsclick='deleteOrCreditOrder' orderid='".$tmpOrd->id."' style='color:#4da6cb; cursor:pointer;' orderid='".$tmpOrd->id."'>delete order</span>";
                                } else {
                                    echo " - <span gsclick='deleteOrCreditOrder' orderid='".$tmpOrd->id."' style='color:#4da6cb; cursor:pointer;' orderid='".$tmpOrd->id."'>credit order</span>";
                                }
                                echo "</div>";
                            }
                            echo "</div>";
                        }
                        foreach ($summary->rows as $row) {
                            if ($row->count == 0 || $this->removeDueToFilter($row, $fstartDate, $fendDate)) {
                                continue;
                            } 
                            
                            $anyFound = true;
                            $product = $this->getApi()->getProductManager()->getProduct($row->createOrderOnProductId);
                            $accomodation = $row->isAccomocation ? "accomocation" : "";
                            $included = $row->includedInRoomPrice ? "included" : "not_included";
                            if ($accomodation) {
                                $included = "";
                            }
                            $name = $product->name;
                            if($row->textOnOrder) { $name = $row->textOnOrder; }
                            ?>
                            <div class='row cartitemline <? echo $accomodation." ".$included; ?>' date='<? echo $row->date; ?>' createorderonproductid="<? echo $row->createOrderOnProductId; ?>" isaccomocation="<? echo $row->isAccomocation; ?>" includedinroomprice="<? echo $row->includedInRoomPrice; ?>">
                                <div class='col' style='margin-right: 10px; width: 20px; padding-top: 5px;'><input class='row_checkbox' style='font-size: 20px; height: 20px; width: 20px;' type='checkbox' checked='true'/></div>
                                <div class='col date' style='vertical-align: top;'><? echo $row->date; ?></div>
                                <div class='col count' style='vertical-align: top;'><input class='gsniceinput1 item_count' orgcount='<? echo $row->count; ?>' value='<? echo $row->count; ?>'/> x </div>
                                <div class='col price' style='vertical-align: top;'><input class='gsniceinput1 item_price' orgvalue='<? echo round($row->priceToCreateOrders,2); ?>' value='<? echo round($row->priceToCreateOrders,2); ?>'/></div>
                                <div class='col productname' style='vertical-align: top;'>
                                    <input class='gsniceinput1 textOnOrder' type='hidden' orgvalue='<? echo $name; ?>' value='<? echo $name; ?>'/>
                                    <input class='gsniceinput1 addonId' type='hidden' orgvalue='<? echo $row->addonId; ?>' value='<? echo $row->addonId; ?>'/>
                                </div>
                            </div>
                            <?
                        }

                        if (!$anyFound) {
                        ?>
                            <div class='row cartitemline'>
                                <div class='col date'>&nbsp;</div>
                                <div class='col productname'><i class="fa fa-warning"></i><? echo $this->__f("Nothing to do"); ?></div>
                                <div class='col count'></div>
                                <div class='col'></div>
                                <div class='col price'></div>
                            </div>
                        <?
                        }

                    echo "</div>";
                echo "</div>";
            }
            ?>

            <div class="row totalrow" style='font-weight:bold;'>
                <div class="col totaltext">
                    <?
                    echo $this->__f("Total to be charged").": ";
                    ?>
                </div>
                <div class="col totalval">
                    -
                </div>
                / Original total for selected rows:
                <div class="col totalvalforselect">
                    -
                </div>
            </div>
        </div>
        <?
    }
    
    $distinctUserIds = array_unique($distinctUserIds);
}

if ($hasConferences) {
    $conferencesToShow = $this->getApi()->getPosManager()->getConferencesThatHasUnsettledAmount($distinctUserIds);
    ?>
    <div class="addconferencedata">
        <div class="sub_header"><? echo $this->__f("Add from conferences?"); ?></div>
        <div class="postabs">
            
        </div>
        
        <?
        if ($conferencesToShow) {
            foreach ($conferencesToShow as $conference) {
                ?>
                <div class="conferenceuserhint" conferenceid="<? echo $conference->id; ?>">
                    <i class="fa fa-warning"></i> <? echo $this->__f("This booking is connected to a conference").": ".$conference->meetingTitle; ?>
                    <div class="shop_button add_pos_tab" conferenceid='<? echo $conference->id; ?>'><? echo $this->__f("Add tab"); ?></div>
                </div>
                <?
            }
        }
        ?>
        
        <div style="margin: 20px;">
            <? echo $this->__f("Search for conference"); ?>
            <br/><input class="gsniceinput1 searchfortabs" /> <div style="font-size: 16px; vertical-align: bottom;height: 20px;padding-top: 10px;" class="gs_shop_small_icon"><i class="fa fa-search"></i></div>
        </div>
        <div class="search_tab_conference_result">
            
        </div>
    </div>
    <?
}

?>

<br/>
<div class='buttonarea'>
    <div class='shop_button' gsclick='gotopaymentselection' style='background-color:#81cff3;-webkit-box-shadow:none; box-shadow:none; color:#000 !important;'><i class='fa fa-caret-left'></i> <? echo $this->__f("Back"); ?></div>
    <?
    if (count($uniqueSegmentIds) < 2) {
    ?>
        <div class='shop_button createorder'  style='float: right;'><? echo $this->__f("Complete payment creation"); ?> <i class='fa fa-caret-right'></i></div>
    <?
    }
    ?>
</div>

<script>
    $(document).ready(function() {
        app.PmsPaymentProcess.updateTotalValue();
    });
</script>
    