<div class='forgot_password' style='padding-left: 250px;'>
    <h1> <? echo $this->__f("Reset password."); ?></h1>
    <table style='width: 400px; margin-left: 50px;'>
        <tr><td><? echo $this->__f("Email"); ?></td><td align='right'><input style='width: 230px;' type='text' placeholder='your@email.com' id="reset_email_address"/></td></tr>

        <tr>
            <td align="right" colspan='2' colspan='2'>
                <br/>
                <div class='gs_login_button' onclick='app.ProMeisterLogin.show(true)'><? echo $this->__f("Cancel"); ?></div> 
                <div class='gs_login_button do_reset_password'><? echo $this->__f("Reset password"); ?></div>
            </td>
        </tr>
    </table>    
</div>