<div class="signupform_outer promeisterloginform" style='display: none;'>
    <div class='hidebackground'>
        
    </div>
    <div class="signupform">
        <div class='signupform_close'></div>
        <div class='signupform_content'>
            <div class='signupform_content_signin' style='padding-left: 250px;'>
                <h1> <? echo $this->__f("You have to login to continue"); ?></h1>
                <form id="loginform" action="/" method="POST"> 

                    <table style='width: 400px; margin-left: 50px;'>
                        <tr><td><? echo $this->__f("Email"); ?></td><td align='right'><input style='width: 230px;' type='text' placeholder='your@email.com' id="login_username" name="username"/></td></tr>
                        <tr><td><? echo $this->__f("Password"); ?></td><td align='right'><input style='width: 230px;' type='password' placeholder='******' id="login_password" name="password"></td></tr>
                    </table>
                    <br/>
                    <div>
                        <a href="/index.php?page=c62af6c7-9cb3-4771-b347-49da85551edc"><div class='gs_login_button go_to_contact_form'><? echo $this->__f("I need help"); ?></div> </a>
                        <div class='gs_login_button show_forgot_password'><? echo $this->__f("Forgot password?"); ?></div> 
                        <div class='gs_login_button login_create_new_account'><? echo $this->__f("Create new account"); ?></div> 
                        <div class='gs_login_button loginbutton'><? echo $this->__f("Login"); ?></div>
                    </div>
                </form>
            </div>
            
            <?
                $this->includefile("forgot_password");
                $this->includefile("login_step_1");
                $this->includefile("login_step_2");
                $this->includefile("login_step_3");
            ?>
        </div>
    </div>
</div>