<div class="signupform_outer">
    <div class='hidebackground'>
        
    </div>
    <div class="signupform">
        <div class='signupform_close'></div>
        <div class='signupform_content'>
            <div class='signupform_content_signin' style='padding-left: 250px;'>
                <h1> <? echo $this->__f("You have to login to continue"); ?></h1>
                <table style='width: 300px; margin-left: 50px;'>
                    <tr><td><? echo $this->__f("Email"); ?></td><td><input style='width: 230px;' type='text' placeholder='your@email.com'/></td></tr>
                    <tr><td><? echo $this->__f("Password"); ?></td><td><input style='width: 230px;' type='password' placeholder='******'/></td></tr>
                    
                    <tr>
                        <td align="right" colspan='2'>
                            <div class='gs_login_button login_create_new_account'><? echo $this->__f("Create new account"); ?></div> 
                            <div class='gs_login_button loginbutton'><? echo $this->__f("Login"); ?></div>
                        </td>
                    </tr>
                </table>    
            </div>
            
            <div class='signup_step1'>
                <?
                echo $this->__f("Please enter the information below");
                ?>
                <table>
                    <tr><td><? echo $this->__f("Name"); ?></td><td><input type='text'/></td></tr>
                    <tr><td><? echo $this->__f("Email"); ?></td><td><input type='text'/></td></tr>
                    <tr><td><? echo $this->__f("Cellphone"); ?></td><td><input type='text'/></td></tr>
                    <tr>
                        <td align="right" colspan='2'>
                            <div class='gs_login_button gs_step1_next'><? echo $this->__f("Next"); ?></div> 
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>