<?
/* @var $this ns_6daa9962_9ba6_40ae_b1a7_5be23cb89128\ProMeisterLogin */
?>

<div class="loginform" gstype="form" method="performLogin">
    <label><? echo $this->__f("Username"); ?></label>
    <br/><input class="gsniceinput1" type="txt" gsname="username"/>
    <br/>
    <br/><label><? echo $this->__f("Password"); ?></label>
    <br/><input class="gsniceinput1" type="password" gsname="password"/>
    <br/>
    <br/><div class="shop_button" gstype="submit"><? echo $this->__f("Login"); ?></div>
</div>
