<div class='gss_settings_header'>
    <i class='fa fa-list-ul'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Product lists"); ?>
        </div>

        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("This is the lists that is available to be displayed in your webshop. All products in a list will be available for search engines, customers and etc.");
            ?>	
        </div>
    </div>	
</div>


<div class="gs_user_menu">
    <div class="gss_button" gss_fragment='listsoverview' gss_view='gss_productwork_area'><i class="fa fa-list"></i><? echo $this->__f("All lists"); ?></div>
    <br/><div class="gss_button" gss_fragment='newlist' gss_view='gss_productwork_area'><i class="fa fa-plus"></i><? echo $this->__f("New list"); ?></div>
</div>

<div class="gss_productwork_area">
    <?
    $this->includefile('listsoverview');
    ?>
</div>