<?
 /* @var $this ns_f245b8ae_f3ba_454e_beb4_ecff5ec328d6\ProductLists */

$columnSize = $this->getColumnSize();
$view = $this->isGridView() ? "grid_view" : "";
$view = $this->isRowView() ? "row_view" : $view;

if($this->getFactory()->isMobile()) {
    $view = "grid_view";
}

?>
<div class="products <? echo $view; ?>"  listid="<? echo $this->getConfigurationSetting("productlist"); ?>">
    <?
    $products = $this->getAllProducts();
    
    if (!count($products) && $this->isSearchResultList()) {
        
        $this->includefile("nosearchresult");
    }
    
    if (!count($products) && !$this->isSearchResultList()) {
        echo "<div class='no_products_added_to_list'><i class='fa fa-warning'></i> ".$this->__f("There is no products added to this list, manage your productlists from the settings.")."</div>";
    }
    
    if (count($products)) {
        $i = 0;
        $j = 0;
        foreach ($products as $product) {
            $i++;
            $j++;
            $linkName = \GetShopHelper::makeSeoUrl($product->uniqueName);
            $pageId = $product->pageId;
            $mainImage = false;

            if ($product->mainImage && in_array($product->mainImage, $product->imagesAdded)) {
                $mainImage = $product->mainImage;
            }

            if (!$mainImage && count($product->imagesAdded)) {
                $mainImage = $product->imagesAdded[0];
            }

            
            if (!$mainImage) {
                $image = '<div class="image"><i class="fa fa-image"></i></div>';
            } else {
                $image = '<div class="image"><img src="/displayImage.php?id='.$mainImage.'&width=200"/></div>';
            }
            ?>
                <div class='productbox_outer'>
                    <div class='productbox'>
                    <?
                    if ($this->showRemoveButton()) {
                        echo "<div class='remove_product_from_list' product_id='$product->id'><i class='fa fa-trash' title='".$this->__f("Remove from list")."'></i></div>";
                    }
                    ?>
                    
                    <a ajaxlink='/?page=<? echo $pageId; ?>' href='<? echo $linkName;?>'>
                        <div class="product_row">
                            <?
                            if ($this->isRowView()) {
                                echo $image;
                            }
                            ?>
                            <div class="content">
                                <div class="product_title"><? echo $product->name; ?></div>
                                <?
                                    if ($this->isGridView()) {
                                        echo $image;
                                    }
                                ?>
                                <div class="short_description"><? echo nl2br($product->shortDescription); ?></div>
                            </div>
                        </div>
                    </a>
                        <div class="product_price" ><? echo ns_9de54ce1_f7a0_4729_b128_b062dc70dcce\ECommerceSettings::formatPrice($product->price); ?></div>
                    
                    <div class="webshop_button_area">
                        <div class="shop_button addProductToCart" productId='<? echo $product->id; ?>'><? echo $this->__f("Add to cart"); ?></div>
                    </div>

                    </div>
                </div>
            <?

            if ($i == $columnSize && count($products) != $j) {
                $i = 0;
                echo "<div class='product_line_seperator'></div>";
            }
        }
    }
    ?>
</div>
<script>
    $(function() {
        var innerWidth = $('.products.grid_view[listid="<? echo $this->getConfigurationSetting("productlist"); ?>"]').innerWidth();
        var columnSize = Math.floor(innerWidth/<? echo $columnSize; ?>);
        var totalSize = columnSize * <? echo $columnSize; ?>;
        if (totalSize === innerWidth) {
            columnSize--;    
        }
        if (innerWidth && $(window).width() > 800) {
            $('.productbox_outer').outerWidth(columnSize);
        }
    });
    
</script>