<?

namespace ns_df435931_9364_4b6a_b4b2_951c90cc0d70;

$notloggedInClass = "notloggedon";

$myAccount = $this->__w("My account");
$logouttext = $this->__w("Logout");
if ($this->isLoggedIn()) {
    $notloggedInClass = "";
}
?>

<div class="login_header_type_1">
    <?
    if (!$this->isLoggedIn()) {
        echo "<a href='?page=login'><i class='fa fa-key'></i></a>";
    } else {
        echo "<a href='?page=login'><i class='fa fa-user' title='$myAccount'></i></a>";
        echo "<i id='getshop_logout' class='fa fa-lock' title='$logouttext'></i>";
    }
    ?>
</div>

<div class='login_content'>
    <div class="loginform inner <? echo $notloggedInClass; ?>">
        <form method="POST" action="" name="loginform" class="loginform loginuserpasswordform">
            <? if ($this->errorMessage != "") { ?>
                <div><? echo $this->errorMessage; ?></div>
<? } ?>
<? if (!Login::getUserObject()) { 
        echo $this->__w("Please enter your username and password");
        ?>
        <div class="form">
            <div class="username"><input class="tstextfield" name="username" type="textfield" placeholder='<?php echo $this->__w('Username / Email'); ?>'></input></div>
            <div class="password"><input class="tstextfield" name="password" type="password" placeholder="<?php echo $this->__w('Password'); ?>"></input></div>
            <input type="hidden" name="loginbutton" value="true"/>
            <span class="loginbutton gs_button" type="submit"><? echo $this->__f("Login"); ?></span>
            <br><span class="recoverpassword gs_button"><?php echo $this->__w('Recover password'); ?></span>
        </div>
<? } ?>
        </form>
    

        <span class="recoverpasswordholder" style='display:none;'>

            <div class="recover_section_outer" step='1'>
                <div class="recover_section">
                    <div class="heading">1. <?php echo $this->__w("Please enter your email address:"); ?></div>
                    <br><br>
                    <input type="txt" class="recoverinput" id="recoverpasswordemail">
                    <input type="button" class="recoverinput" id="recoverinputbutton" value="<?php echo $this->__w("Send me a code"); ?>">
                </div>
            </div>

            <div class="recover_section_outer disabled" step='2'>
                <div class="recover_section">
                    <div class="heading">2. <?php echo $this->__w("Enter a new password."); ?></div>
                    <bR>
                    
                    <label>
                        <?php echo $this->__w("Enter the code sent to your email."); ?>
                        <input type="txt" class="recoverinput" id="recoverpasswordcode">
                    </label>
                    
                    <label><? echo $this->__w("New password"); ?>
                        <input type="password" class="recoverinput" id="newpassword">
                    </label>
                    <label><? echo $this->__w("Repeat new password"); ?>
                        <input type="password" class="recoverinput" id="repeat_newpassword">
                    </label>
                    <input type="button" class="recoverinput" id="resetpasswordbutton" value="<?php echo $this->__w("Change password"); ?>">
                </div>
            </div>
            
            <div style='clear:both;'></div>
        </span>


    <?
    if (Login::getUserObject()) { 
            $this->includefile("useraccount");
        }
    ?>
    </div>
    
</div>



