<?
namespace ns_df435931_9364_4b6a_b4b2_951c90cc0d70;
?>

<span class="recoverpasswordholder">
    <div class="information">
        <img style="float:right;" src="/skin/default/images/keys.png">
        <div><?php echo $this->__w("Lost your password?"); ?></div>
        <div><?php echo $this->__w("Please following theese steps to recover your password."); ?></div>
    </div>

    <div class="recover_section">
        <div class="heading">1. <?php echo $this->__w("Please enter your email address:"); ?></div>
        <input type="txt" class="recoverinput" id="recoverpasswordemail">
        <input type="button" class="recoverinput" id="recoverinputbutton" value="<?php echo $this->__w("Send me a code"); ?>">
    </div>

    <div class="recover_section">
        <div class="heading">2. <?php echo $this->__w("Enter the code sent to your email."); ?></div>
        <input type="txt" class="recoverinput" id="recoverpasswordcode">
    </div>

    <div class="recover_section">
        <div class="heading">3. <?php echo $this->__w("New password"); ?></div>
        <input type="password" class="recoverinput" id="newpassword">
    </div>

    <div class="recover_section">
        <div class="heading">4. <?php echo $this->__w("Repeat password"); ?></div>
        <input type="password" class="recoverinput" id="repeat_newpassword">
    </div>
    
    <div class="recover_section">
        <input type="button" class="recoverinput" id="resetpasswordbutton" value="<?php echo $this->__w("Change password"); ?>">
    </div>    
</span>