<?
/* @var $this \ns_3e89173c_42e2_493f_97bb_2261c0418bfe\GetShopLockSystem */
$lock = $this->getLock();

if ($this->isRazberryLock()) {
    $this->includefile('zwavelock');
}

echo "<div class='lockandserverids'>";
echo "Serverid: ".$this->getServer()->id;
echo "<br/>Lockid: ".$lock->id;
echo "</div>";
?>


<h2>Codes and slots</h2>
<?

foreach ($lock->userSlots as $slot) {
    /* @var $slot \core_getshoplocksystem_UserSlot */
    $this->setSlot($slot);
    $this->includefile('slotview');
}
?>

<h2>Lock logs:</h2>

<div class="shop_button" gsclick="cancelEditingLock">Back to overview</div>