<?
/* @var $this \ns_afec873d_d876_46c8_856c_2c599bada065\EditEventType */
$eventType = $this->getEventType();
$certificates = $this->getApi()->getEventBookingManager()->getCertificates($this->getBookingEngineName());
$groups = $this->getApi()->getUserManager()->getAllGroups();
$metaData = $this->getApi()->getEventBookingManager()->getBookingTypeMetaData($this->getBookingEngineName(), $eventType->id);

?>
<div gstype="form" method="saveEvent">
    <input type="hidden" value="<? echo $eventType->id; ?>" gsname="bookingItemTypeId"/>
    <label>Name</label><input type="txt" class="gsniceinput1" gsname="name" value="<? echo $eventType->name; ?>">
    <br><br>
    <label>Grouped name</label><input type="txt" class="gsniceinput1" gsname="eventItemGroup" value="<? echo $eventType->eventItemGroup ;?>">
    <br><br>
    <label>Description</label>
    <textarea class="gsniceinput1 eventdescription" gsname="descrption"><? echo $eventType->description; ?></textarea>
    <br><br>
    
    
    
    <div class="groupinformation">
        <div class="title">Not logged in (public)</div>
        <div class="inner">
            <label>Visible</label>
            
            <?
            $pucvchecked = $metaData->publicVisible ? "checked='true'" : "";
            ?>
            
            <input type="checkbox" gsname="public_visible" <? echo $pucvchecked; ?>> Yes
            <label>Price</label>
            <input type="txt" class="gsniceinput1" gsname="publicPrice" value="<? echo $metaData->publicPrice; ?>"> ( -1 = disabled / price not shown )
        </div>
    </div>
    
    <div> Set price to -1 to hide price ( -1 = disabled / price not shown )</div>
    <br>
    
    <table>
        
    </table>
    <?
    
    echo "<table class='tableEvent'>";
    echo "<tr id='headerTable'>
            <th>Name</th><th>Price</th><th>Certificates</th><th>Visible</th><th>Mandatory</th><th>Information/Warning</th>
        </tr>";
    
    foreach ($groups as $group) {

        echo "<tr>";
        
        echo "<td>$group->groupName</td>";
        
                $price = $metaData->groupPrices->{$group->id};
                $warningText = "";
                
                if ($metaData->groupWarningInformation && isset($metaData->groupWarningInformation->{$group->id})) {
                    $warningText = @$metaData->groupWarningInformation->{$group->id};
                }
                
                echo "<td><input gsname='price_$group->id' class='priceInput gsniceinput1' value='$price'/></td>";

                $certificateIds = $metaData->certificateIds->{$group->id};
               
                foreach ($certificates as $certificate) {
                    $certId = $certificate->id;
                    $checked = in_array($certId, $certificateIds) ? "checked='true'" : "";
                    echo "<td>&nbsp;&nbsp;<input type='checkbox' $checked gsname='certificate_".$group->id."_$certId'/>".$certificate->name."<br/></td>";
                }

                $checked = $metaData->visibleForGroup->{$group->id} ? "checked='true'" : "";
                $mandatoryChecked = (isset($metaData->mandatoryForGroup->{$group->id}) && $metaData->mandatoryForGroup->{$group->id}) ? "checked='true'" : "";
                echo "<td>&nbsp;&nbsp;<input type='checkbox' $checked gsname='visible_$group->id'/> Yes</td>";
                
                echo "<td>&nbsp;&nbsp;&nbsp;&nbsp;<input type='checkbox' $mandatoryChecked gsname='mandatory_$group->id'/> Yes </td>";
                echo "<td><input gsname='extrainfo_$group->id' class='extrainformationarea gsniceinput1' value='$warningText'/></td>";
            echo "</div>";
        echo "</div>";
        echo "</tr>";
        
    }
    echo "</table>";
    echo "<br>";
    
    $activated = $this->getApi()->getStoreApplicationPool()->isActivated("07422211-7818-445e-9f16-ad792320cb10");
    $tests = $this->getApi()->getQuestBackManager()->getAllTests();
    
    if ($activated && count($tests)) {
        echo "<div class='questback'>";
            echo "Do you want to send questbacks after events of this type has been completed to all users?<br/>";
            echo "<select gsname='questBackId' class='gsniceselect1'>";
                echo "<option value=''>Not selected</option>";
                foreach ($tests as $test) {
                    $selected = $metaData->questBackId == $test->id ? "selected='true'" : "";
                    echo "<option $selected value='$test->id'>$test->name</option>";
                }
            echo "</select>";
        echo "</div>";
    }
    
    
    $checkedRequirePersonalId = $metaData->requirePersonalId ? "checked='true'" : "";
    ?>
    
    <br/>
    <br/> <input type="checkbox" <? echo  $checkedRequirePersonalId; ?> gsname="requirePersonalId"/> Require personal identificator. (Will be stored encrypted in the database with a 2048 bit encryption)
    
    <br/><br/><div class="shop_button" gstype="submit">Save</div>
</div>