<?
/* @var $this ns_afec873d_d876_46c8_856c_2c599bada065\EditEventType */
$events = $this->getApi()->getEventBookingManager()->getEventsByType($this->getBookingEngineName(), $_GET['bookingItemTypeId']);

echo "<div class='connectedEvents'>";
    foreach ($events as $event) {
        $pageId = $event->bookingItem->pageId;
        echo "<a href='/?page=$pageId'><div class='row'>";
        echo $event->mainStartDate. " - ".$event->mainEndDate;
        echo "</div></a>";
    }
echo "</div>";
?>