<?
/* @var $this ns_f86e7042_f511_4b9b_bf0d_5545525f42de\PayOnRoom */
?>
<div class='gss_settings_header'>
    <i class='fa fa-list-ul'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Pay on room"); ?>
        </div>

        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("Need to specify a booking-engine.");
            ?>	
        </div>
    </div>	
</div>

<div class='gss_settings_content'>

    <div class="gss_simple_shipping">
        <div class="textfield gss_setting" >
            <span class="title"><? echo $this->__f("Name of bookingengine"); ?></span>
            <input type="textfield" gs_model='payonroom' gs_model_attr='bookingengine' value="<? echo $this->getConfigurationSetting("bookingengine"); ?>">
            <div class="description"><? echo $this->__f(""); ?></div>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="payonroom" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>
</div>