<?
/* @var $this ns_5278fb21_3c0a_4ea1_b282_be1b76896a4b\SedoxDownloadHistory */
/* @var $product core_sedox_SedoxProduct */
$product = $this->getCurrentProduct();
$productName = $product->printableName;

if (!function_exists("sedox_notAvailableCheck")) {
    function sedox_notAvailableCheck($input) {
        if (!$input) {
            return "N/A";
        }

        return $input;
    }
}
?>
<div class="sedox_internal_view">
    <div class="innerview">
        <div class='title boldFont'>
            <i class='fa fa-file'></i> <? echo $productName; ?>
        </div>
        <div class='downloadinfo'>
            <div class='box_header boldFont'>
                Download Information
            </div>
            <div class='box_content'>
                <?
                echo "<select class='fileselector'>";
                foreach ($product->binaryFiles as $binFile) {
                    $checksumCorrect = $binFile->checksumCorrected ? "Yes" : "No";
                    $extraInfo = sedox_notAvailableCheck($binFile->extraInformation);
                    echo "<option checksumupdated='$checksumCorrect' extrainfo='N/A' admintools='N/A'>" . $binFile->fileType . "</option>";
                }
                echo "</select>";
                ?>

                <div class='row_type1'>
                    Checksum updated:
                    <div class='row_subinfo' lookingfor="checksumupdated">-</div>
                </div>

                <div class='row_type1'>
                    Extra information:
                    <div class='row_subinfo' lookingfor="extrainfo">-</div>
                </div>

                <div class='row_type1'>
                    Admin Tools:
                    <div class='row_subinfo' lookingfor="admintools">-</div>
                </div>

                <div class='priceview'>
                    <div class='price boldFont'>100</div>
                    <div class='pricetext boldFont'>CREDITS</div>
                    <div class='sedox_blue_button'>Purchase and Download</div>
                </div>
            </div>
        </div>

        <div class='fileinfo'>
            <div class='box_header boldFont'>
                Project Details
                <div class='subinfo'>
                    Created: <? echo $product->rowCreatedDate; ?>
                </div>
            </div>

            <div class='box_content'>
                <div class='row_type2'>
                    Orig. Checksum:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->originalChecksum); ?></div>
                </div>

                <div class='row_type2'>
                    Reference:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck(@$product->reference->{ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->id}); ?></div>
                </div>

                <div class='row_type2'>
                    ECU Brand / Type:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->ecuBrand); ?></div>
                </div>

                <div class='row_type2'>
                    ECU Part No.:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->ecuPartNumber); ?></div>
                </div>

                <div class='row_type2'>
                    ECU Hardware No.:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->ecuHardwareNumber); ?></div>
                </div>

                <div class='row_type2'>
                    ECU Software No.:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->ecuSoftwareNumber); ?></div>
                </div>

                <div class='row_type2'>
                    ECU Version:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->ecuSoftwareVersion); ?></div>
                </div>

                <div class='row_type2'>
                    File Size:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->softwareSize); ?></div>
                </div>

                <div class='row_type2'>
                    Tool:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->tool); ?></div>
                </div>
            </div>            
        </div>    
        
        <div class='creditinformation'>
            <div class='sedox_blue_button'>Purchase Credits</div> 
            All files at this page are developed by Sedox Performance.
             <div class='redinfo'>Download is not available unless you have credit at your account.</div>
             
                 
         </div>
    </div>
    
</div>