<? 
/* @var $this ns_d755efca_9e02_4e88_92c2_37a3413f3f41\Settings */
?>
<div class='gss_imagebox'>
    <i class="fa fa-line-chart gs_fa-icon"></i>
</div>
<div class='gss_description'>
    <div class='title'><? echo $this->__f("Sms Usage"); ?></div>
    <div>
        <?
        $this->renderConfig(3);
        ?>
    </div>
</div>
<div gss_goto_app="39f1485a-85b8-4f09-ba70-0e33c16f8dc6" class='gss_activate_button'> <? echo $this->__f("more"); ?></div>