<?
/* @var $this ns_13e03ff7_8334_45eb_a280_c772c3262325\MecaFleetCars */
$cars = $this->getApi()->getMecaManager()->getCarsForMecaFleet($this->getPage()->getId());

if (!count($cars)) {
    return;
}

foreach ($cars as $car) {
?>
    
        <div class="carrowouter">
            <a href='/?page=<? echo $car->pageId; ?>'>
                <div class='car'>
                
                    <div><? echo $car->licensePlate; ?></div>
                    <div>Telefonnr: <? echo $car->cellPhone; ?></div>
                    <div>Nåværende kilometerstand: <? echo $car->kilometers; ?></div>        
                </div>
            </a>
            
            <div class="deletecar">
                <i gs_confirm="Are you sure you want to delete the car?" gsclick="deleteCar" carid='<? echo $car->id; ?>' class='gs_shop_small_icon fa fa-trash'></i>
            </div>
        </div>
    
<?
}
?>