<div class='app' appid='<? echo $this->getConfiguration()->id; ?>'>
    <div class='mailmanagerinformation'> 
        <b> <? echo $this->getName(); ?> </b>
        <p> <? echo $this->getDescription(); ?> </p>
    </div>

    <center>
        <div class='rows'>
            <div class='settingbox setuporderemail'><div class='image'></div><div class='text'><? echo $this->__f("Order email"); ?></div></div>
        </div>
    </center>
</div>
