<div class='heading'>
    <?php
    echo $this->__f("Payment succesfully completed");
    ?>
</div>
<div class='success'>
    <span class="icon-shield-check"></span>
</div>

<div class='information'>
    <?php
    echo $this->__f("If you are waiting for an accesscode it will be printed on the receipt if your room is ready, otherwise you will receive the code by SMS and Email when its ready.");
    ?>
</div>

<div class='buttonarea'>
    <a href='/?page=home'><div class='button'><?php echo $this->__f("Got it!"); ?></div></a>
</div>