<?php
   /* @var $this \ns_1859cf75_9323_407d_b0b1_5050aaa89ff8\ProMeisterEditUser */
    $notMySelf = isset($_SESSION['ProMeisterSpiderDiager_current_user_id_toshow']) && $_SESSION['ProMeisterSpiderDiager_current_user_id_toshow'] != \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->id;
    $userId = $notMySelf ? $_SESSION['ProMeisterSpiderDiager_current_user_id_toshow'] : \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->id;
    $user = $this->getApi()->getUserManager()->getUserById($userId);
?>
<div gstype="form" method="updateUser">
    <table>
        <tr>
            <th><? echo $this->__w("Name");?></th><th><input class="gsniceinput1"type="text" gsname="name" value="<?php echo $user->fullName; ?>"/></th>
            <th id="themail"><? echo $this->__w("Email");?></th><th><input class="gsniceinput1" type="text" gsname="email" value="<?php echo $user->emailAddress; ?>"/></th>
        </tr>
        <tr>
            <th><? echo $this->__w("Phone");?></th><th><input class="gsniceinput1" type="text" gsname="phone" value="<?php echo $user->cellPhone; ?>"/></th>
            <th></th>
            <th><span class="shop_button" gstype="submit"><? echo $this->__w("Update");?></span></th>
            <th><?php if(!$user->suspended) { ?>
                        <span class="shop_button" id="suspend" gsclick="suspendAccount"><? echo $this->__w("Suspend");?></span> 
                <?php } else {
                            echo " User is now suspended!";    
                        }
                ?>
            </th>
        </tr>      
    </table>
</div>