<?php
/* @var $this ns_02b94bcd_39b9_41aa_b40c_348a27ca5d9d\PmsConference */
$loggedOnUser = $this->getApi()->getUserManager()->getLoggedOnUser();
$start = $this->convertToJavaDate(strtotime($this->getCurrentStart() . " 00:00"));
$end = $this->convertToJavaDate(strtotime($this->getCurrentEnd() . " 23:59"));

$filter = new core_pmsmanager_PmsConferenceEventFilter();
$filter->start = $start;
$filter->end = $end;
$filter->itemIds = $this->getItemsFilterArray();
$statuses = $this->getStatuses();
$events = $this->getApi()->getPmsConferenceManager()->getConferenceEventsByFilter($filter);
$items = $this->getApi()->getPmsConferenceManager()->getAllItem("-1");
$items = $this->indexList($items);
$currentDate= null;

echo "<div class='eventreportarea'>";
$this->includefile("reportheader");
foreach($events as $event) {
    $from = "";
    if($event->from) { $from = date("d.m H:i", strtotime($event->from)); }
    $to = "";
    if($event->to) { $to = date("H:i", strtotime($event->to)); }
    $status = $statuses[$event->status];
    $item = $items[$event->pmsConferenceItemId]->name;
    $title = $event->title;
    $date = date("d.m.Y", strtotime($event->from));
    if($date != $currentDate) {
        $currentDate = $date;
        echo "<div class='dateheader'>$currentDate</div>";
    }
    ?>
    <div class='eventheader'>
    <span class='from'><?php echo $from; ?></span>
    <span class='to'><?php echo $to; ?></span>
    <span class='roomname'><?php echo $item; ?></span>
    <span class='conference openconference' conferenceid='<?php echo $event->pmsConferenceId; ?>'><?php echo $title; ?></span>
    <span class='status'><?php echo $status; ?></span>
    </div>
    <div class='eventdetails'>
    <?php $eventEntries = (array)$this->getApi()->getPmsConferenceManager()->getEventEntries($event->id); ?>
    <table cellspacing='0' cellpadding='0' class='evententries'>
    <?php
    foreach($eventEntries as $eventEntry) {
        $from = "";
        if($eventEntry->from) { $from = date("d.m H:i", strtotime($eventEntry->from)); }
        $to = "";
        if($eventEntry->to) { $to = date("H:i", strtotime($eventEntry->to)); }
        $text = $eventEntry->text;
        $count = $eventEntry->count;
        $extendedText = $eventEntry->extendedText;
        echo "<tr class='evententry'>";

        echo "<td class='from' valign='top'>$from</td>";
        echo "<td class='to' valign='top'>$to</td>";
        echo "<td class='text openevent' valign='top' class='' eventid='".$eventEntry->pmsEventId."'>$count x $text</td>";
        echo "<td class='extendedtext' valign='top'>";
        echo nl2br($extendedText);
        echo "</td>";

        echo "</tr>";
    }
    ?>
    </table>
    </div>
    <?php
}
echo "</div>";
?>

<style>
    .header { text-align: center; border-bottom: solid 2px; padding-bottom: 10px; margin-bottom: 10px;}
    .eventheader { margin-top: 10px; font-weight: bold; padding-bottom: 10px; }
    .eventdetails { border-bottom: dashed 1px; }
    .evententry { padding-left: 140px; }
    .from { display:inline-block; width: 90px; }
    .to { display:inline-block; width: 70px; }
    .text { display:inline-block; width: 240px; }
    .roomname { display:inline-block; width: 240px; }
    .conference { display:inline-block; width: 238px; }
    .dateheader { border: solid 1px #bbb; text-align: center; font-weight: bold; background-color:#efefef; margin: 10px; padding: 10px; }
    .extendedtext { display:inline-block; }
</style>