
<?php
/* @var $this ns_02b94bcd_39b9_41aa_b40c_348a27ca5d9d\PmsConference */

$start = $this->convertToJavaDate(strtotime($this->getCurrentStart() . " 00:00"));
$end = $this->convertToJavaDate(strtotime($this->getCurrentEnd() . " 23:59"));
$itemsFilter = $this->getItemsFilterArray();

$filter = new core_pmsmanager_PmsConferenceEventFilter();
$filter->start = $start;
$filter->end = $end;
$filter->itemIds = $itemsFilter;

$events = $this->getApi()->getPmsConferenceManager()->getConferenceEventsByFilter($filter);
$currentDate = "";
$conferenceItems = $this->getApi()->getPmsConferenceManager()->getAllItem("-1");
$conferenceItems = $this->indexList($conferenceItems);
$firstDate = true;

    $fromTime = strtotime($start) - 86400 * 3;
    $toTime = strtotime($end) + 86400 * 3;

    $bfilter = new core_pmsmanager_PmsConferenceEventFilter();
    $bfilter->start = $this->convertToJavaDate( $fromTime );
    $bfilter->end = $this->convertToJavaDate( $toTime );

    // TODO - Make filter of list to date range.
    $conferenceBooking = (array)$this->getApi()->getPmsManager()->getConferenceBookings($this->getSelectedMultilevelDomainName(), $bfilter);
    $conferences = array();
    foreach ($conferenceBooking as $conferenceBooking) {
         $conferences[$conferenceBooking->conferenceId] = $conferenceBooking->rooms[0]->pmsBookingRoomId;
    }


?>

<div class='eventreportarea'>
    <?php
    $this->includefile("reportheader");

    echo "<table width='100%' class='texttable' cellspacing='0' cellpadding='0'>";

    echo "<tr>";
    echo "<th valign='top' align='left'>From</th>";
    echo "<th valign='top' align='left'>To</th>";
    echo "<th valign='top' align='left'>Text</th>";
    echo "<th valign='top' align='left'>Extended text</th>";
    echo "<th valign='top' align='center'>Count</th>";
    echo "<th valign='top' align='left'>Room</th>";
    echo "<th valign='top' align='left'>Booking</th>";
    echo "</tr>";

    foreach($events as $event) {
        $conference = $this->getConference($event->pmsConferenceId);
        $date = date("d.m.Y", strtotime($event->from));
        
        $from = "";
        if($event->from) {
            $from = date("H:i", strtotime($event->from)); 
        }
        $to = "";
        if($event->to) { $to = date("H:i", strtotime($event->to)); }

        
        if($date != $currentDate) {
            $currentDate = $date;
            if(!$firstDate) {
                echo "<tr><td colspan='20'><br><br></td></tr>";
            }
            $firstDate = false;
            echo "<tr><td colspan='20' class='dateheader'>$date</td></tr>";
        }
        
        $count = $event->attendeeCount;
        if(!$count) {
            $count = $conference->attendeeCount;
        }
        
        echo "<tr style='font-weight:bold;' id='event_".$event->id."_conferenceid_".$event->pmsConferenceId."<'>";
        echo "<td>$from</td>";
        echo "<td>$to</td>";
        echo "<td>".$event->name."</td>";
        echo "<td>".$event->description."</td>";
        echo "<td align='center'>".$count."</td>";
        $name = $conferenceItems[$event->pmsConferenceItemId]->name;
        echo "<td>".$name."</td>";

        $roomid = "";
        if(isset($conferences[$event->pmsConferenceId])) {
            $roomid = $conferences[$event->pmsConferenceId];
        }
        if( $roomid != '' )
        {
          echo "<td><span method='loadBooking' gs_show_overlay='booking_room_view' id='$roomid' class='canOpenBooking evententry $thisConference' start='".strtotime($event->from)."' end='".strtotime($event->to)."' title='".$event->name." ($betweendate)'>".$conference->meetingTitle."</span>";
        }
        else
        {
          //try to find us a conference..
          $existingBooking = $this->getApi()->getPmsManager()->getconferenceBooking($this->getSelectedMultilevelDomainName(), $event->pmsConferenceId);
          if($existingBooking)
          {
              echo "<td><span method='loadBooking' gs_show_overlay='booking_room_view' id='". $existingBooking->id ."' class='canOpenBooking evententry $thisConference' start='".strtotime($event->from)."' end='".strtotime($event->to)."' title='".$event->name." ($betweendate)'>".$conference->meetingTitle."</span>";
          }
          else
          {
              echo "<td><span onclick='app.PmsConference.openConferenceById(\"".  $event->pmsConferenceId ."\")'>". $conference->meetingTitle ."</span> (<span onclick='app.PmsConference.reconnectConferenceWithBooking(\"".  $event->pmsConferenceId ."\")'>Reconnect conference</span>)</td>"; //echo "<span onClick='alertEventOutsideConferenceStart()' class='evententry $thisConference' start='".strtotime($event->from)."' end='".strtotime($event->to)."' title='".$event->name." ($betweendate)'>".$event->name."</span>";
          }
        }

         // <pre>".print_r($event,1)."#####".print_r($conference,1)."</pre>
        echo "</tr>";
        
        
        $eventEntries = (array) $this->getApi()->getPmsConferenceManager()->getEventEntries($event->id);
        foreach($eventEntries as $eventEntry) {

            $from = "";
            $gray = "";
            if($eventEntry->from) {
                $from = date("H:i", strtotime($eventEntry->from)); 
                if(strtotime($eventEntry->from) < (time()+600)) {
                    $gray = "style='color:gray'";
                }
            }
            $to = "";
            if($eventEntry->to) { $to = date("H:i", strtotime($eventEntry->to)); }
            $text = $eventEntry->text;
            $count = $eventEntry->count;
            if(!$count) {
                $count = $conference->attendeeCount;
            }
            
            echo "<tr $gray id='".$eventEntry->pmsEventId."'>";
            echo "<td valign='top'>$from</td>";
            echo "<td valign='top'>$to</td>";
            echo "<td valign='top'>".$eventEntry->text."</td>";
            echo "<td valign='top'>" . nl2br($eventEntry->extendedText) . "</td>";
            echo "<td valign='top' align='center'>$count</td>";
            echo "<td valign='top' class='openevent' eventid='".$eventEntry->pmsEventId."'></td>";
            echo "</tr>";
        }
    }
    echo "</table>";
    ?>
</div>
<style>
.canOpenBooking { cursor:pointer; color:#23314e;  }
<style>
<script>
    getshop_loadDatePicker($('.startdate'), { dependant : $('.enddate') });    
    getshop_loadDatePicker($('.enddate'), { dependant : $('.startdate') });
    setInterval(function() {
        if(app.PmsConference.disableAutoReload) {
            return;
        }
        document.location.reload();
    }, "600000");
</script>
