
<?php
/* @var $this ns_02b94bcd_39b9_41aa_b40c_348a27ca5d9d\PmsConference */

$start = $this->convertToJavaDate(strtotime($this->getCurrentStart() . " 00:00"));
$end = $this->convertToJavaDate(strtotime($this->getCurrentEnd() . " 23:59"));
$itemsFilter = $this->getItemsFilterArray();

$filter = new core_pmsmanager_PmsConferenceEventFilter();
$filter->start = $start;
$filter->end = $end;
$filter->itemIds = $itemsFilter;

$events = $this->getApi()->getPmsConferenceManager()->getEventEntriesByFilter($filter);
$currentDate = "";

?>

<div class='eventreportarea'>
    <?php
    $this->includefile("reportheader");

    echo "<table width='100%' class='texttable' cellspacing='0' cellpadding='0'>";

    echo "<tr>";
    echo "<th valign='top' align='left'>From</th>";
    echo "<th valign='top' align='left'>To</th>";
    echo "<th valign='top' align='left'>Text</th>";
    echo "<th valign='top' align='left'>Extended text</th>";
    echo "<th valign='top' align='left'>Count</th>";
    echo "<th valign='top' align='left'>Room</th>";
    echo "<th valign='top' align='left'>Conference</th>";
    echo "</tr>";

    foreach($events as $eventEntry) {
        $date = date("d.m.Y", strtotime($eventEntry->from));
        if($date != $currentDate) {
            $currentDate = $date;
            echo "<tr><td colspan='20' class='dateheader'>$date</td></tr>";
        }

        $from = "";
        $gray = "";
        if($eventEntry->from) {
            $from = date("H:i", strtotime($eventEntry->from)); 
            if(strtotime($eventEntry->from) < (time()+600)) {
                $gray = "style='color:gray'";
            }
        }
        $to = "";
        if($eventEntry->to) { $to = date("H:i", strtotime($eventEntry->to)); }
        $text = $eventEntry->text;
        $count = $eventEntry->count;

        echo "<tr $gray>";
        echo "<td valign='top'>$from</td>";
        echo "<td valign='top'>$to</td>";
        echo "<td valign='top'>".$eventEntry->text."</td>";
        echo "<td valign='top'>" . nl2br($eventEntry->extendedText) . "</td>";
        echo "<td valign='top'>$count</td>";
        echo "<td valign='top' class='openevent' eventid='".$eventEntry->pmsEventId."'>".$eventEntry->conferenceItem."</td>";
        echo "<td valign='top' class='openconference' conferenceid='".$eventEntry->conferenceId."'>".$eventEntry->meetingTitle."</td>";
        echo "</tr>";
    }
    echo "</table>";
    ?>
</div>

<script>
    getshop_loadDatePicker($('.startdate'), { dependant : $('.enddate') });    
    getshop_loadDatePicker($('.enddate'), { dependant : $('.startdate') });
    setInterval(function() {
        if(app.PmsConference.disableAutoReload) {
            return;
        }
        document.location.reload();
    }, "600000");
</script>
