<?php
/* @var $this \ns_02b94bcd_39b9_41aa_b40c_348a27ca5d9d\PmsConference */
$cureventid = $this->getCurrentEvent();
$guests = (array)$this->getApi()->getPmsConferenceManager()->getAllGuestsForEvent($cureventid);

if(sizeof($guests) == 0) {
    echo "No guests added yet.";
    return;
}

?>
<table width="100%">
<tr>
    <td></td>
    <td>Booker</td>
    <td>Start</td>
    <td>End</td>
    <td>Room type</td>
    <td>Room name</td>
    <td>Guest name</td>
    <td>Guest phone</td>
    <td>Guest email</td>
</tr>
<?php

foreach($guests as $guest) {
    ?>
    <tr>
        <td><i class='fa fa-trash-o removeguest' guestid='<?php echo $guest->guest->guestId; ?>' eventid='<?php echo $cureventid; ?>'></i></td>
        <td><?php echo $guest->bookerName; ?></td>
        <td><?php echo date("d.m.Y H:i", strtotime($guest->start)); ?></td>
        <td><?php echo date("d.m.Y H:i", strtotime($guest->end)); ?></td>
        <td><?php echo $guest->bookingItemTypeName; ?></td>
        <td><?php echo $guest->bookingItem ? $guest->bookingItem : "N/A"; ?></td>
        <td><?php echo $guest->guest->name; ?></td>
        <td><?php echo $guest->guest->prefix . " " . $guest->guest->phone; ?></td>
        <td><?php echo $guest->guest->email; ?></td>
    </tr>
    <?php
}
?>
</table>