<?php
$currentConference = $this->getSelectedConference();
if($currentConference) {
    $conference = $this->getApi()->getPmsConferenceManager()->getConference($currentConference);
    echo "You are currently operating under: " . $conference->meetingTitle . ", ";
    echo "<span onclick='$(\".PmsConference .conferenceoverview\").show();' class='openconference' conferenceid='".$currentConference."'>open</span>.";
}
$start = date("d.m.Y");
$end = date("d.m.Y", time()+86400);
?>
<div class='header'>
    <span style='position:relative'>
        <span class='shop_button' gsclick="loadConferences" gs_callback='app.PmsConference.allConferencesLoaded' synchron='true'>List all conferences</span>
        <div class='conferencelist'></div>
    </span>
    
    <div class="listreportsarea">
        <div style='text-align: right; margin-bottom: 5px; '>
            <span style='float:left;'>Reports</span>
            <i class='fa fa-close' onclick='$(".listreportsarea").slideUp();' style='cursor:pointer;'></i>
        </div>
        <input type='text' class='gsniceinput1 startdate' style='width:90px' value='<?php echo $start; ?>'>
        <input type='text' class='gsniceinput1 enddate' style='width:90px' value='<?php echo $end; ?>'>
        <span class='shop_button  downloadreport' type='event'>Download event report</span>
        <span class='shop_button  downloadreport' type='all'>Download report</span>
    </div>

    
    <span class='shop_button' onclick='$(".addconferencepanel").toggle();'>Create a new conference</span>
<?php
/* @var $this \ns_02b94bcd_39b9_41aa_b40c_348a27ca5d9d\PmsConference */

$subitem = $this->getCurrentSubitem();
$entries = (array)$this->getApi()->getPmsConferenceManager()->getAllItem($subitem);
if($subitem) {
    echo "<span class='shop_button' gsclick='loadSubitems' itemid='' style='float:left;'>Go back to overview</span>"; 
}
?>
</div>

<div class='addconferencepanel'>
    <h1>For what customer should this conference be attached to?</h1>
    <?php
    $extraArgs = array();
    $extraArgs['avoidCloseButton'] = "true";
    $extraArgs['hideWarning'] = "true";
    $extraArgs['overridesavebutton'] = "<span class='shop_button' gstype='submit' gs_callback='app.PmsConference.continueToConferenceView'>Continue <i class='fa fa-arrow-right' gs_callback='app.'></i></span>";

    $quser = new \ns_b5e9370e_121f_414d_bda2_74df44010c3b\GetShopQuickUser();
    $quser->extraArgs = $extraArgs;
    $quser->invokeJavascriptFunctionAfterActions = 'app.PmsConference.userSavedUpdated';
    $quser->renderApplication(true, $this);
    ?>
</div>

<script>
    getshop_loadDatePicker($('.startdate'), { dependant : $('.enddate'), jump : 1 });    
    getshop_loadDatePicker($('.enddate'), { dependant : $('.startdate'), jump : -1 });
</script>
