<br>Options:<br>
<span gstype='clicksubmit' class='pmsbutton' method='updateBComInventory'>Update inventory</span>
<span gstype='clicksubmit' class='pmsbutton' method='pushAllRoomsBookingComRateManager'>Upload all bookings</span>
<br><br><br>
<?php
/* @var $this \ns_9de81608_5cec_462d_898c_1266d1749320\PmsConfiguration */
$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName());

$config = $this->getApi()->getBookingComRateManagerManager()->getRateManagerConfig($this->getSelectedMultilevelDomainName());

echo "<div class='configurationpanel' gstype='form' method='saveRateManagerSettings'>";
echo "<span gstype='form' method='updateRateManagerConfig'>";
echo "<input type='txt' gsname='hotelid' style='float:right;' value='".$config->hotelId."' class='gsniceinput1'> Hotel id<br>";
echo "<b><bR>Room rate map (map your categories to the id's given by ratemanager)</br></b><br>";
echo "<div style='clear: both;'></div>";
foreach($types as $type) {
    $roomId = "";
    if(isset($config->roomTypeIdMap->{$type->id})) {
        $roomId = $config->roomTypeIdMap->{$type->id};
    }
    echo "<input type='txt' gsname='typeid_".$type->id."' style='float:right;' value='".$roomId."' class='gsniceinput1'>" . $type->name . "<bR>";
    echo "<div style='clear: both;'></div>";
}
echo "<br>";
echo "<input type='button' gstype='submit' value='Save settings' style='float:right;padding: 8px; width:200px;'>";
echo "</span>";
echo "<div style='clear:both;'></div>";
echo "</div>";
?>