<?
/* @var $this ns_c20ea6e2_bc0b_4fe1_b92a_0c73b67aead7\SalesPointReports */
$cashPoint = $this->getApi()->getPosManager()->getCashPoint($this->getSelectedCashPointId());

?>
<div class="leftmenu">
   
        <div class='entry all' tab='xreport'>
            <i class='fa fa-dollar'></i>
            X Report
        </div>

        <div class='entry all' tab='listtab'>
            <i class='fa fa-history'></i>
            Z Report
            <br/>History
        </div>

        <div class='entry all' tab='salesreport'>
            <i class='fa fa-pie-chart'></i>
            Sales
        </div>
    
        <?
        if ($cashPoint->isMaster) {
            ?>
                <div class='entry all' tab='masterreport'>
                    <i class='fa fa-lightbulb-o'></i>
                    Master 
                    <br/>Report
                </div>
            <?
        }
        ?>
    </div>
</div>