<?
/* @var $this ns_c20ea6e2_bc0b_4fe1_b92a_0c73b67aead7\SalesPointReports */
$report = $this->getCurrentZReport();

if ($this->isCurrentZReportASavedReport()) {
    echo "<div class='informationbox'>";
        echo $this->__f("You are looking at an old/saved Z-Report");
        echo "<br/><br/><div gsclick='cancelCurrentZReport' class='shop_button'>".$this->__f("Close")."</div>";
    echo "</div>";
}

if (!$report->orderIds || !count($report->orderIds)) {
    echo "<div class='nofound'>";
    echo $this->__f("No transactions found");
    echo "</div>";
    return;
}

$cashPointName = $this->getSelectedCashPointName();
if ($cashPointName) {
    echo "<div class='cashpointname'>";
        echo "Report for: ".$cashPointName;
    echo "</div>";
}


$orders = $this->getApi()->getOrderManager()->getOrders($report->orderIds, 1, 99999);
$totalForPaymentMethods = array();
$ordersGrouped = array();

/* @var $allCartItems \core_cartmanager_data_CartItem[] */
$allCartItems = array();

foreach ($orders as $order) {
    $terminalData = $this->getApi()->getOrderManager()->getTerminalInformation($order->id);
    $paymentTypeArr = explode("\\", $order->payment->paymentType);
    $paymentType = $this->getPaymentMethodName($paymentTypeArr[0]);
    
    $allCartItems = array_merge($allCartItems, $order->cart->items);
    
    if ($terminalData) {
        $paymentType .= " - ".ucfirst(strtolower(trim($terminalData->issuerName)))."";
    }
    
    if ($order->cashWithdrawal) {
        $cashWithdrawal = new stdClass();
        $cashWithdrawal->id = $order->id;
        $cashWithdrawal->incrementOrderId = $order->incrementOrderId;
        $cashWithdrawal->paymentDate = $order->paymentDate;
        $cashWithdrawal->userId = $order->userId;
        $cashWithdrawal->cashWithdrawalCorrection = $order->cashWithdrawal * -1;
        
        if (!isset($ordersGrouped['PayOnDelivery'])) {
            $ordersGrouped['PayOnDelivery'] = array();
        }
        
        $ordersGrouped['PayOnDelivery'][] = $cashWithdrawal;
    }

    if (!isset($ordersGrouped[$paymentType])) {
        $ordersGrouped[$paymentType] = array();
    }
    
    $ordersGrouped[$paymentType][] = $order;
}

foreach ($ordersGrouped as $paymentType => $orders) {
    echo "<div class='paymentrow'>";
        echo "<h2>".$this->__f($paymentType)."</h2>";
    ?>
        <div class="orderline">
            <div class='col orderid'><? echo $this->__f("id"); ?></div>
            <div class='col date'><? echo $this->__f("Payment Date"); ?></div>
            <div class='col name'><? echo $this->__f("Employee / customer"); ?></div>
            <div class='col type'><? echo $this->__f("Payment type"); ?></div>
            <div class='col totalfororder'><? echo $this->__f("Price"); ?></div>
        </div>
    <?
        
        $total = 0;
        foreach ($orders as $order) {
            $user = $this->getUserById($order->userId);
            $userFullName = $user ? $user->fullName : "N/A";
            
            $totalForOrder = $this->getApi()->getOrderManager()->getTotalAmount($order);
            
            if (isset($order->cashWithdrawalCorrection)) {
                $totalForOrder = $order->cashWithdrawalCorrection;
            }
            
            $total += $totalForOrder;

            echo "<div class='orderline'>";
                echo "<a href='/pos.php?page=orderviewpage&orderid=$order->id'>";
                
                    echo "<div class='col orderid'>".$order->incrementOrderId."</div>";
                    echo "<div class='col date'>".$this->formatDate($order->paymentDate)."</div>";
                    echo "<div class='col name'>".$userFullName."</div>";
                    echo "<div class='col type'>".$this->__f($paymentType)."</div>";
                    echo "<div class='col totalfororder'>".$totalForOrder."</div>";
                echo "</a>";
            echo "</div>";
        }

        $totalForPaymentMethods[$paymentType] = $total;
        echo "<h2> Total: ".$total."</h2>";
    echo "</div>";
}
?>

<div class="paymentrow summary">
    <h2><? echo $this->__f("Total summary"); ?></h2>
        <?
        $grandTotal = 0;
        foreach ($totalForPaymentMethods as $paymentType => $total) {
            echo '<div class="orderline">';
                echo "<div class='col name'>$paymentType</div>";
                echo "<div class='col'>$total</div>";
            echo "</div>";
            $grandTotal += $total;
        }
        ?>
    
    <h2><? echo $this->__f("Grand total").": ".$grandTotal; ?></h2>
</div>

<div class="paymentrow summary">
    <h2><? echo $this->__f("Prouduct summary"); ?></h2>
        <?
        $groupedCartItems = array();
        
        foreach ($allCartItems as $item) {
            $taxGroupNumber = $item->product->taxGroupObject->groupNumber;
            $groupedCartItems[$item->product->id][$taxGroupNumber][] = $item;
        }
        
        echo '<div class="orderline">';
            echo "<div class='col name'>Product</div>";
            echo "<div class='col sum_product_inc_tax'>TaxRate</div>";
            echo "<div class='col sum_product_inc_tax'>Total inc tax</div>";
            echo "<div class='col sum_product_ex_tax'>Total ex tax</div>";
            echo "<div class='col sum_product_ex_tax'>Count</div>";
        echo "</div>";

        $taxGroups = $this->getApi()->getProductManager()->getTaxes();
        
        foreach ($groupedCartItems as $productId => $groupByTaxGroup) {
            foreach ($groupByTaxGroup as $taxGroupNumber => $items) {
                $taxGroup = $this->getTaxGroup($taxGroupNumber, $taxGroups);
                $product = $this->getApi()->getProductManager()->getProduct($productId);
                $lineTotalIncTaxes = $this->getSumTotalOfItems($items, true);
                $lineTotalExTaxes = $this->getSumTotalOfItems($items, false);
                $lineCount = $this->getCount($items);
                echo '<div class="orderline">';
                    echo "<div class='col name'>$product->name</div>";
                    echo "<div class='col sum_product_inc_tax'>$taxGroup->taxRate%</div>";
                    echo "<div class='col sum_product_inc_tax'>$lineTotalIncTaxes</div>";
                    echo "<div class='col sum_product_ex_tax'>$lineTotalExTaxes</div>";
                    echo "<div class='col sum_product_ex_tax'>$lineCount</div>";
                echo "</div>";
            }
        }
        ?>
   
</div>
<?
echo count($allCartItems);

if (!$this->isCurrentZReportASavedReport() && $this->canMakeZReport()) {
?>
    <div style="padding: 50px;">
        <div class="shop_button" gsclick="createZReport"><? echo $this->__f("Create ZReport"); ?></div>
    </div>
<?
}
?>

  