<div class="page_row row_1">
    <div class="page_row_inner">
        <?php
            ContentManager::render("about_us_top");
        ?>
    </div>
</div>

<div class="page_row row_2">
    <div class="page_row_inner">
        <?php
            ContentManager::render("about_us_row_2");
        ?>
    </div>
</div>

<div class="page_row row_3">
    <div class="page_row_inner">
        <?php
            ContentManager::render("about_us_row_3");
        ?>
    </div>
</div>

<div class="page_row row_4">
    <div class="page_row_inner">
        <?php
            ContentManager::render("about_us_row_4");
        ?>
    </div>
</div>

<div class="page_row row_5">
    <div class="page_row_inner">
        <?php
            ContentManager::render("about_us_row_5");
        ?>
    </div>
</div>

<div class="page_row row_6">
    <div class="page_row_inner">
        <?php
            ContentManager::render("about_us_row_6");
        ?>
    </div>
</div>