
<div class="heading">
    <?php
    /* @var $this Home */
    echo $this->__f("Welcome");
    echo "<br/>";
    echo $this->__f("book or pay your stay here");
    ?>    
</div>

<div class="languageselector">
    <a href="?page=bookingfrontpage&lang=nb_NO"><div class="language langno"></div></a>
    <a href="?page=bookingfrontpage&lang=en_en"><div class="language langeng"></div></a>
</div>


<div class='commercial' onclick="document.location = '/?page=settings';">
    <?php
    echo $this->__f("System delivered by: ")." GetShop / www.getshop.com";
    ?>
</div>