<?php
/* @var $this ns_74220775_43f4_41de_9d6e_64a189d17e35\PmsNewBooking */
$start = $this->getStartDate();
$end = $this->getEndDate();
$number = 0;


$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
$start = $this->convertToJavaDate(strtotime($start. " " . $config->defaultStart));
$end = $this->convertToJavaDate(strtotime($end. " " . $config->defaultEnd));

$current = $this->getApi()->getPmsManager()->getCurrentBooking($this->getSelectedMultilevelDomainName());

ob_start();
echo "<div class='availableroomsheading'></div>";
$types = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);
echo "<table width='100%'>";
$total = 0;
foreach($types as $type) {
    $size = $this->getNumberOfAvailableForType($type,$current,$start,$end);
    $disabled = "";
    if($size <= 0) {
        $disabled = "disabled";
    }
    $total += $size;
    echo "<tr class='$disabled'>";
    echo "<td class='availabletypename' roomtype='".$type->id."'>" . $type->name . "</td><td class='availableroomscounter' roomtype='".$type->id."'>$size</td>";
    echo "</tr>";
}
echo "</table>";

$res = ob_get_clean();

$emo = "happy";
if($total <= 0) {
    $emo = "sad";
}
?>
<div class="kaipal infobox">
    <div class="image <?php echo $emo; ?>"></div>
    <div class="textbox">
        <div class="header">This is the rooms we have available</div>
        <div class="text">
            I have <?php echo $total; ?> rooms available for you between <?php echo date("d.m.Y", strtotime($start)) . " and " . date("d.m.Y", strtotime($end)); ?> 
        </div>
    </div>
</div>
<?php
echo $res;
?>