<?php
/* @var $this ns_74220775_43f4_41de_9d6e_64a189d17e35\PmsNewBooking */
$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName());
?>
<h3>Create a new room reservation</h3>
<div gstype='form' method='addRoom'>
    <div class="gs_headerbox">
        <div>
            <?
            echo $this->__f("From");
            ?>
        </div>

        <input class="gsniceinput1" id="startdate" value="<? echo $this->getStartDate(); ?>" gsname='from'/>

        <i class="icon-calendar-text"></i>
    </div>

    <div class="gs_headerbox">
        <div>
            <?
            echo $this->__f("To");
            ?>
        </div>

        <input class="gsniceinput1" id="enddate" value="<? echo $this->getEndDate(); ?>" gsname='to'/>

        <i class="icon-calendar-text"></i>
    </div>

    <div class="gs_headerbox">
        <div>
            <?
            echo $this->__f("Room type");
            ?>
        </div>
        <select class='gsniceselect2' gsname='type'>
            <?php
            foreach($types as $type) {
                echo "<option value='".$type->id."'>" . $type->name . "</option>";
            }
            ?>
        </select>
    </div>

    <div class="gs_headerbox">
        <div>
            <?
            echo $this->__f("Number of rooms");
            ?>
        </div>
        <input type='text' class='gsniceinput1' value='0' style='width: 70px;text-align: center;' gsname='numberOfRooms' class='numberofrooms'>
    </div>

    <div class="gs_headerbox">
        <div>
        </div>
        <span class='shop_button' style='cursor:pointer;' gstype='submit'>Add room</span>
    </div>
    <div class='moreThenAvailableWarning'>
        <div class="isnotactive">
            <div class="kaipal infobox">
               // faces: happy,sad,talking,danger
               <div class="image sad"></div>
               <div class="textbox">
                   <div class="header">Hey there, we have a problem.</div>
                   <div class="text">
                       You want me to create <span class='numberofrooms'></span> rooms. But I can only give you <span class='maxrooms'></span> rooms of type: <span class='typename'></span>. I will put <span class='roomsdiff'></span> rooms into a waiting list.
                   </div>
               </div>
           </div>
        </div>
        
    </div>
    
</div>



<script>
    $('#startdate').datepicker({ dateFormat: "dd.mm.yy", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            $('.PmsNewBooking [gsname="numberOfRooms"]').val(0);
            var curEnd = moment($('#enddate').val(), "DD.MM.YYYY");
            var date = moment(dateText, "DD.MM.YYYY");
            
            var diff = curEnd.valueOf() - date.valueOf();
            if(diff <= 0) {
                date.add(1, 'days');
                $('#enddate').val(date.format('DD.MM.YYYY')); 
                app.PmsNewBooking.reloadAvailability();
            }
        }
    });
    
    $('#enddate').datepicker({ dateFormat: "dd.mm.yy", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            $('.PmsNewBooking [gsname="numberOfRooms"]').val(0);
            var curStart = moment($('#startdate').val(), "DD.MM.YYYY");
            var date = moment(dateText, "DD.MM.YYYY");
            
            var diff = date.valueOf() - curStart.valueOf();
            if(diff <= 0) {
                date.add(-1, 'days');
                $('#startdate').val(date.format('DD.MM.YYYY')); 
                app.PmsNewBooking.reloadAvailability();
            }
            app.PmsNewBooking.reloadAvailability();
        }
    });
    $(document).on('click', '.PmsNewBooking .icon-calendar-text', function() {
        $(this).closest('div').find('input').focus();
    });
</script>
