<div class="isnotactive" style='width:1500px; margin:auto;'>
    <div class="kaipal infobox">
        <div class="image sad"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("Sorry, we do not have any rooms to add yet."); ?></div>
            <div class="text">
                <?
                echo $this->__f("Go to the settings area, navigate to rooms and create a room.");
                ?>    

            </div>
        </div>
    </div>
</div>