<?php
/* @var $this ns_74220775_43f4_41de_9d6e_64a189d17e35\PmsNewBooking */
$booking = $this->getApi()->getPmsManager()->getCurrentBooking($this->getSelectedMultilevelDomainName());
$types = $this->indexList($this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName()));
?>
<br><bR>
<h3>Rooms ready to be added</h3>

<?php
$found = false;

$rows = array();
$canBeAdded = true;
foreach($booking->rooms as $room) {
    $row = new stdClass();
    $row->type = "<i class='fa fa-trash-o' style='cursor:pointer;' gstype='clicksubmit' gsname='id' gsvalue='".$room->pmsBookingRoomId."' method='removeRoom'></i> " . $types[$room->bookingItemTypeId]->name;
    $row->start = date("d.m.Y H:i", strtotime($room->date->start));
    $row->end = date("d.m.Y H:i", strtotime($room->date->end));
    if($room->canBeAdded && !$room->addedToWaitingList) {
        $row->available = "<i class='fa fa-check'></i>";
    } else {
        $row->available = "<i class='fa fa-close'></i>";
        if($room->addedToWaitingList) {
            $row->available = " (waiting list)";
        }
        $canBeAdded = false;
    }
    
    $rows[] = $row;
    $found = true;
}

$attributes = array(
    array('type', 'Room type', 'type',null),
    array('checkin', 'Check in', 'start',null),
    array('checkout', 'Check out', 'end',null),
    array('available', 'Available', 'available',null)
);

if(!$found) {
    echo "No rooms added yet, add one or more rooms above.";
} else {
    $table = new \GetShopModuleTable($this, null,null, null, $attributes);
    $table->setData($rows);
    $table->render();
    
    echo "<div style='text-align: right; margin-top: 5px;'>";
    echo "<span class='shop_button' gstype='clicksubmit' method='completequickreservation'>Continue, reservation details is added in the next step <i class='fa fa-arrow-right'></i></span>";
    echo "</div>";
}
?>