<?php
/* @var $this ns_74220775_43f4_41de_9d6e_64a189d17e35\PmsNewBooking */
$booking = $this->getApi()->getPmsManager()->getCurrentBooking($this->getSelectedMultilevelDomainName());
$types = $this->indexList($this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName()));
?>
<br><bR>
<h3>Rooms ready to be added</h3>
<?php
$found = false;

$rows = array();
$canBeAdded = true;
foreach($booking->rooms as $room) {
    $row = new stdClass();
    if($room->bookingItemId) {
        $item = $this->getApi()->getBookingEngine()->getBookingItem($this->getSelectedMultilevelDomainName(), $room->bookingItemId);
        $name = $item->bookingItemName;
    } else {
        $name = $types[$room->bookingItemTypeId];
    }
    $row->type = "<i class='fa fa-trash-o' style='cursor:pointer;' gstype='clicksubmit' gsname='id' gsvalue='".$room->pmsBookingRoomId."' method='removeRoom'></i> " . $name;
    $row->start = date("d.m.Y H:i", strtotime($room->date->start));
    $row->end = date("d.m.Y H:i", strtotime($room->date->end));
    if($room->canBeAdded && !$room->addedToWaitingList) {
        $row->available = "<i class='fa fa-check'></i>";
    } else {
        $row->available = "<i class='fa fa-close'></i>";
        if($room->addedToWaitingList) {
            $row->available = " (waiting list)";
        }
        $canBeAdded = false;
    }
    
    $rows[] = $row;
    $found = true;
}

$attributes = array(
    array('type', 'Room type', 'type',null),
    array('checkin', 'Check in', 'start',null),
    array('checkout', 'Check out', 'end',null),
    array('available', 'Available', 'available',null)
);

if(!$found) {
    echo "No rooms added yet, add one or more rooms above.";
} else {
    ?>
    <?php
    $table = new \GetShopModuleTable($this, null,null, null, $attributes);
    $table->setData($rows);
    $table->render();
    
    ?>
    <div style='text-align: right; margin-top: 25px;' gstype='form' method='completequickreservation'>
        <span class='selecteduser' style='display:none;'><i class='fa fa-trash-o' style='cursor:pointer;'></i> <span class='name'></span></span>
        <input type='text' class='gsniceinput1' placeholder="Name of group holder" gsname='nameofholder'>
    <span class='shop_button' gstype='clicksubmit' method='removeAllSelectedRooms' style='float:left;background-color:red;'>Remove all rooms</span>
    <span class='shop_button' gstype='submit'>Continue, reservation details is added in the next step <i class='fa fa-arrow-right'></i></span>
    <div class='alreadyexists'></div>
    </div>
    <?php
}
?>