<?php
/* @var $this ns_74220775_43f4_41de_9d6e_64a189d17e35\PmsNewBooking */
$booking = $this->getApi()->getPmsManager()->getCurrentBooking($this->getSelectedMultilevelDomainName());
$types = $this->indexList($this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName()));
?>
<br>
<h3>Step 2. Verify rooms to be added</h3>
<div class="section">
    <?php
    $found = false;

    $rows = array();
    $canBeAdded = true;
    foreach ($booking->rooms as $room) {
        $row = new stdClass();
        if ($room->bookingItemId) {
            $item = $this->getApi()->getBookingEngine()->getBookingItem($this->getSelectedMultilevelDomainName(), $room->bookingItemId);
            $name = $item->bookingItemName;
        } else {
            $name = $types[$room->bookingItemTypeId]->name;
        }
        $row->type = "<i class='fa fa-trash-o' style='cursor:pointer;' gstype='clicksubmit' gsname='id' gsvalue='" . $room->pmsBookingRoomId . "' method='removeRoom'></i> " . $name;
        $row->start = date("d.m.Y H:i", strtotime($room->date->start));
        $row->end = date("d.m.Y H:i", strtotime($room->date->end));
        $row->numberOfGuests = $room->numberOfGuests;
        $row->cost = $room->totalCost;
        $row->roomid = $room->pmsBookingRoomId;
        if ($room->canBeAdded && !$room->addedToWaitingList) {
            $row->available = "<i class='fa fa-check'></i>";
        } else {
            $row->available = "<i class='fa fa-close'></i>";
            if ($room->addedToWaitingList) {
                $row->available = " (waiting list)";
            }
            $canBeAdded = false;
        }

        $rows[] = $row;
        $found = true;
    }

    $attributes = array(
        array('type', 'Room type', 'type', null),
        array('checkin', 'Check in', 'start', null),
        array('checkout', 'Check out', 'end', null),
        array('guests', 'Guest count', 'numberOfGuests', "formatNumberOfGuests"),
        array('available', 'Available', 'available', null),
        array('cost', 'Cost', 'cost', null)
    );
    if (!$found) {
        echo "No rooms added yet, add one or more rooms above.";
    } else {
        $table = new \GetShopModuleTable($this, null, null, null, $attributes);
        $table->setData($rows);
        $table->render();
        ?>
        <span class='shop_button' gstype='clicksubmit' method='removeAllSelectedRooms' style='float:left;background-color:red; margin-top: 5px;'>Remove all rooms</span>
        <div style="clear:both;"></div>
        <?php
    }
?>
</div>
<?php
if($found) { ?>
    <br><br>
    <h3>Step 3. Enter booking owner and continue</h3>
    <div class='section'>
        <div style='text-align:left;'>
        <div class='companytypeselection'>
            <div style='margin-bottom: 10px;'>
               What type of customer would you like to connect to this booking?
            </div>
            <span class='shop_button newcustomertypebutton' type='nextstepprivate'>Private person</span>
            <span class='shop_button newcustomertypebutton' type='nextstepcompany'>Company / orginasation</span>
            <span class='shop_button newcustomertypebutton' type='nextstepexisting'>Existing customer</span>
            <span class='shop_button newcustomertypebutton' gstype='clicksubmit' method='completequickreservation'>Quick reservation</span>
        </div>

        <div class='nextstep nextstepexisting' gstype='form' method='searchExistingCustomer'>
            <br>
            Search for an existing customer:<br>
            <input type='txt' class='gsniceinput1' gstype='submitenter' gs_callback='app.PmsNewBooking.existingSearchResult' gsname='searchword'>
            <span class='shop_button searchexistingcustomer' gstype='submit' gs_callback='app.PmsNewBooking.existingSearchResult'>Search</span>
            <div class='existingsearchcustomerresult'></div>
        </div>
            
        <div class='nextstep nextstepcompany' gstype='form' method='createNewCompanyCustomer'>
            <input type='hidden' gsname='type' value='company'>
            <div>
                <div style='margin-top:10px;'>Enter vat number and company name <span class='searchbrregbutton'>(search brreg)</span></div>
                <span class='searchbrregarea' gstype='form' method='searchbrreg'>
                    <input type='text' class='gsniceinput1' gsname='name'>
                    <span class='shop_button' gstype='submit' gs_callback='app.PmsNewBooking.searchResult'>Search</span>
                    <div class='brregsearchresult' style='max-height: 100px; overflow-y: auto;'></div>
                </span>
                <input type='txt' class='gsniceinput1' gsname='vatnumber' placeholder='Vat number'>
                <input type='txt' class='gsniceinput1' gsname='name' placeholder='Name'>
                <span class='shop_button' gstype='submit'>Register customer</span>
            </div>
        </div>
            
        <div class='nextstep nextstepprivate' style='margin-top: 25px;' gstype='form' method='completequickreservation'>
            <span class='selecteduser' style='display:none;'><i class='fa fa-trash-o' style='cursor:pointer;'></i> <span class='name'></span></span>
            <input type='text' class='gsniceinput1' placeholder="Name of group holder" gsname='nameofholder'>
            <span class='shop_button' gstype='submit'>Continue, reservation details is added in the next step <i class='fa fa-arrow-right'></i></span>
            <div class='alreadyexists'></div>
        </div>
    </div>
        
    </div>
    <?php
}
?>