<?
/* @var $this ns_a532618a_f189_4273_9145_c75b6a8289c5\ProMeisterAddionalEventSignonInformation */
$user = $this->getApi()->getUserManager()->getLoggedOnUser();
if ($this->getModalVariable("userid")) {
    $user = $this->getApi()->getUserManager()->getUserById($this->getModalVariable("userid"));
}

$event = $this->getApi()->getEventBookingManager()->getEvent($this->getBookingEngineName(), $this->getModalVariable("eventid"));
$groupId = \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject() != null 
        && \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->companyObject != null 
        && \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->companyObject->groupId 
        ? \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->companyObject->groupId : "";
$metaData = $this->getApi()->getEventBookingManager()->getBookingTypeMetaData($this->getBookingEngineName(), $event->bookingItemType->id);
$extraWarning = $metaData && $metaData->groupWarningInformation && isset($metaData->groupWarningInformation->{$groupId}) ? $metaData->groupWarningInformation->{$groupId} : false;

if ($extraWarning) {
    echo "<div class='extrawarning'>";
    echo nl2br($extraWarning);
    echo "</div>";
}
?>


<div gstype='form' method="confirmBooking">
    <div style="border: solid 1px; text-align: center; padding: 10px;margin-bottom: 10px;" class='gserrorfield' id='errorMessage'></div>
    <table>
        <?
        if ($metaData->requirePersonalId) {
            ?>
            <tr>
                <td class='col1' style="font-size: 16px">Personnr (11 siffer)</td>
                <td class='col2'>
                    <input class='gsniceinput1' type='textfield' gsname='personalid' value=''/>
                    <br/> <span style="font-style: italic; font-weight: bold; color: red; padding-bottom: 10px;">Vi lagrer personnret kryptert og sletter det etter vi har rapport deltakelsen til Staten.</span>
                    <br/>
                    <br/>
            </tr>    
            <?
        }
        ?>

        <tr>
            <td class='col1'><? $this->wrapApp("320ada5b-a53a-46d2-99b2-9b0b26a7105a", "textfield1"); ?></td>
            <td class='col2'><input class='gsniceinput1' type='textfield' gsname='alergic' value='<? echo @$user->metaData->{'event_signon_alergic'}; ?>'/>
        </tr>
        <tr>
            <td class='col1'><? $this->wrapApp("320ada5b-a53a-46d2-99b2-9b0b26a7105a", "textfield2"); ?></td>
            <td class='col2'><input class='gsniceinput1' type='textfield' gsname='specialfoodrequest' value='<? echo @$user->metaData->{'event_signon_specialfoodrequest'}; ?>'/>
        </tr>
        <tr>
            <td class='col1'><? $this->wrapApp("320ada5b-a53a-46d2-99b2-9b0b26a7105a", "textfield3"); ?></td>
            <td class='col2'><textarea gsname='additionalinfo'><? echo @$user->metaData->{'event_signon_additionalinfo'}; ?></textarea>
        </tr>
    </table>
    <br/>
    <input type='hidden' value='true' gsname='doConfirmBooking'/>
    <div class="shop_button" gstype="submit"><? echo $this->__f("Confirm"); ?></div>
</div>
    