<div appid='<? echo $this->getConfiguration()->id; ?>' class='app'>
    <div class="information">
        <?
        echo $this->__f("Enter the terms and condition text in the field below.");
        ?>
    </div>
    <div class="getshop_ckeditorcontent" style="background-color:#FFF; border:solid 1px; min-height: 200px;" altid="termsandcondition">
        <? echo $this->getTerms(); ?>
    </div>
</div>