<?
/* @var $this ns_47dec929_fc34_4d7d_9356_a9600d04797e\SalesPointOtherSettings */
$settings = $this->getApi()->getOrderManager()->getOrderManagerSettings();

?>

<div gstype="form" method="saveSettings">
    <div class="settingsrow">
        
        <div class="title">
            <? echo $this->__f("Close financial periode when creating z-report"); ?>
        </div>
        
        <div class="value">
            <select class="gsniceselect1" gsname="autoclose">
                <option value="true" <? echo $settings->autoCloseFinancialDataWhenCreatingZReport ? "selected='true'" : ""; ?>><? echo $this->__f("Yes"); ?></option>
                <option value="false" <? echo !$settings->autoCloseFinancialDataWhenCreatingZReport ? "selected='true'" : ""; ?>><? echo $this->__f("No"); ?></option>
            </select>
        </div>
    </div>
    
    <div class="settingsrow">
        <div class="shop_button" gstype="submit"><? echo $this->__f("Save"); ?></div>
    </div>
</div>