<?php
/* @var $this \ns_11234b3f_452e_42ce_ab52_88426fc48f8d\SalesPointTabPayment */
$tab = $this->getCurrentTab();
$paymentMethods = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();

if (!$tab || !count($tab->cartItems)) {
    echo "<script>$('.gsoverlay1').click();</script>";
//    echo "<div class='no_items'>";
//    echo $this->__f("The tab is empty, please create one and/or add items to the tab.");
//    echo "</div>";
    return;
}
?>
<div class='topinformation'>
    <?php
    echo $this->__f("You can do multiple payments for a tab. Please select the items you want to charge the customer for.");
    ?>
</div>
<?
$cartItems = $tab->cartItems;

foreach ($cartItems as $cartItem) {
    $priceToUse = $cartItem->product->price;

    if ($cartItem->overridePriceIncTaxes) {
        $priceToUse = $cartItem->overridePriceIncTaxes;
    }

    ?>
    <div class='cartitem itemlines' cartitemid='<? echo $cartItem->cartItemId; ?>'>
        <div class='col checkbox'><input type='checkbox' checked='true'/></div>
        <div class='col productname'><?php echo $cartItem->product->name; ?></div>
        <div class='col count'><input gstype='numpad' gsnumpadtitle='Please enter new count' class='gsniceinput1' value='<? echo $cartItem->count; ?>'/> x</div>
        <div class='col price'><input gstype='numpad' gsnumpadtitle='Please enter new price' class='gsniceinput1' value='<? echo $priceToUse; ?>'/></div>
    </div>
    <?
}
?>
<div class='cartitem totalrow'>
    <div class='col checkbox'></div>
    <div class='col productname'><?php echo $this->__f("Total"); ?></div>
    <div class='col count'></div>
    <div class='col price'><? echo $this->getApi()->getPosManager()->getTotal($tab->id) ?></div>
</div>

<?
$validPaymentMethods = array('565ea7bd-c56b-41fe-b421-18f873c63a8f', 
    '6dfcf735-238f-44e1-9086-b2d9bb4fdff2', 
    'f1c8301d-9900-420a-ad71-98adb44d7475', 
    'f86e7042-f511-4b9b-bf0d-5545525f42de', 
    '7587fdcb-ff65-4362-867a-1684cbae6aef', 
    'cbe3bb0f-e54d-4896-8c70-e08a0d6e55ba');
?>
<div class='paymentmethods'>
    <?
    foreach ($paymentMethods as $method) {
        if (!in_array($method->id, $validPaymentMethods)) {
            continue;
        }
        ?>
        <div class='shop_button startpayment' paymentid='<? echo $method->id; ?>'><i class='fa fa-money'></i> <? echo $this->getNameOfPaymentMethod($method->id); ?></div>
        <?
    }
    ?>
</div>
