<?
/* @var $this \ns_11234b3f_452e_42ce_ab52_88426fc48f8d\SalesPointTabPayment */
$order = $this->getCurrentOrder();
$state = $_SESSION['ns_11234b3f_452e_42ce_ab52_88426fc48f8d_complete_payment_state'];
echo $this->getLastTerminalMessage(); 
?>


<div class="buttonarea">
    <?
    if ($state == "in_progress") {
        ?>
        <div class="shop_button" gs_callback='app.SalesPointTabPayment.nullFunction' synchron="true" gsclick="cancelVerifonePayment"> <? echo $this->__f("Cancel payment process"); ?> </div>
        <script>
            setTimeout(app.SalesPointTabPayment.fetchTerminalMessages, 400);
        </script>
        <?
    }
    
    if ($state == "failed") {
        unset($_SESSION['ns_11234b3f_452e_42ce_ab52_88426fc48f8d_complete_payment_state']);
        unset($_SESSION['ns_11234b3f_452e_42ce_ab52_88426fc48f8d_last_terminal_message']);
        ?>
        <div class="shop_button" gsclick="cancelCurrentOrder"><? echo $this->__f("Back"); ?> </div>
        <div class="shop_button" gsclick="startVerifonePaymentProcess"><? echo $this->__f("Retry payment"); ?> </div>
        <?
    }
    
    if ($state == "completed") {
        unset($_SESSION['ns_11234b3f_452e_42ce_ab52_88426fc48f8d_complete_payment_state']);
        unset($_SESSION['ns_11234b3f_452e_42ce_ab52_88426fc48f8d_last_terminal_message']);
        $this->completeCurrentOrder();
        ?>
        <script>$('.gsoverlay1').click();</script>
        <?
    }
    ?>
</div>

