<?
/* @var $this ns_48a459b8_90b2_4dea_9bae_f548d006f526\CertegoSystemDepartments */
$departments = $this->getDepartments();
?>

<div class="gs_certego_system_department">

    <div class='gss_settings_header'>

        <span class="fa-stack fa-lg" style="margin-right: 40px;">
            <i class="fa fa-location-arrow fa-stack-1x"></i>
        </span>

        <div class='gss_settings_header_description'>
            <div class='gss_settings_header_title'>
                Manager System Departments.
            </div>
            <div class='gss_settings_header_description_inner'>
                <?

                ?>	
            </div>
        </div>
    </div>

    <div class='gss_settings_content'>

        <div class="textfield gss_setting"  id="name">
            <span class="title"><?php echo $this->__f("Name"); ?></span>
            <input type="textfield" gs_model='certegosytemsmodel' gs_model_attr='defaultemail' value="<? echo $this->getDefaultEmailAddress(); ?>" placeholder="">
            <div class="description">
                <?php echo $this->__("Default email address (when no system has been selected)"); ?>
            </div>
        </div>
    </div>
    
    <?
    foreach ($departments as $dep) {
    ?>
        <div class='gss_settings_content'>

            <div class="textfield gss_setting"  id="name">
                <span class="title"><?php echo $this->__f("Department name"); ?></span>
                <input type="textfield" gs_model='certegosytemsmodel' gs_model_attr='name_<? echo $dep; ?>' value="<? echo $this->getDepartmentName($dep); ?>" placeholder="">
                <div class="description">
                    <?php echo $this->__(""); ?>
                </div>
            </div>
            
            <div class="textfield gss_setting"  id="name">
                <span class="title"><?php echo $this->__f("Email"); ?></span>
                <input type="textfield" gs_model='certegosytemsmodel' gs_model_attr='mail_<? echo $dep; ?>' value="<? echo $this->getEmailAddress($dep); ?>" placeholder="">
                <div class="description">
                    <?php echo $this->__("Email address for this department"); ?>
                </div>
            </div>
        </div>

    <?
    }
    ?>
    
    <div class='gss_settings_content'>
        <div class='gss_button_area'>
            <div class="gss_button" gss_fragment="settings" gss_view="gs_certego_system_department" gss_method="addDepartment" gss_model="certegosytemsmodel"><i class='fa fa-trash'></i><?php echo $this->__("Add system department"); ?></div>
            <div class="gss_button" gss_fragment="settings" gss_view="gs_certego_system_department" gss_method="saveDepartments" gss_model="certegosytemsmodel" gss_success_message="Saved"><i class='fa fa-save'></i><?php echo $this->__("Update"); ?></div>
        </div>
    </div>

</div>