<?php
/* @var $this ns_d3951fc4_6929_4230_a275_f2a7314f97c1\PmsBookingContactData */
$booking = $this->getApi()->getPmsManager()->getCurrentBooking($this->getSelectedName());
$errors = $this->getValidation();
$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$types2 = array();
foreach($types as $type) {
    $types2[$type->id] = $type;
}
$types = $types2;


$pricetypes = array();
$pricetypes[1] = "Daily";
$pricetypes[2] = "Monthly";
$pricetypes[3] = "Weekly";
$pricetypes[4] = "Per minut";
$pricetypes[5] = "Hourly";
$pricetypes[6] = "Per second";

$headingRoomInformation = $this->__w("Room information");
if($this->getConfigurationSetting("headingroominfo")) {
    $headingRoomInformation = $this->getConfigurationSetting("headingroominfo");
}
?>
<h3 class='bottomborder'><? echo $headingRoomInformation; ?></h3>
<?
foreach($booking->rooms as $room) {
    for($i = 0; $i < $room->count; $i++) {
        $guestData = new core_pmsmanager_PmsGuests();
        $guestData->prefix = "47";
        if(isset($room->guests[$i])) {
            $guestData = $room->guests[$i];
        }
        if($types[$room->bookingItemTypeId]->addon > 0) {
            continue;
        }
        echo "<div class='roomdata' pmsBookingRoomId='".$room->pmsBookingRoomId."' offset='$i'>";
        echo "<span class='col-33'><label>".$this->getNameText()."<input type='text' name='name' value='".$guestData->name."'>";
        $this->validateRoom($room->pmsBookingRoomId, "name", $i);
        echo "</label></span>";
        echo "<span class='col-33'>";
        echo "<label>";
        echo $this->__w("Phone") . "<bR>";
        echo "<input type='text' name='prefix' value='+".$guestData->prefix."' style='width:20%;'>";
        echo "<input type='text' name='phone' value='".$guestData->phone."' style='width:70%;'>";
        echo "</label>";
        echo "<div style='clear:both;'></div>";
        $this->validateRoom($room->pmsBookingRoomId, "phone", $i);
        echo "</span>";
        echo "<span class='col-33'><label>".$this->__w("Email")."<input type='text' name='email' value='".$guestData->email."'>";
        $this->validateRoom($room->pmsBookingRoomId, "email", $i);
        echo "</label></span>";
        echo "</div>";
    }
}
?>
<div style='clear:both;'></div>
<br><br>

<?

$headingContactData = $this->__w("Billing information");
if($this->getConfigurationSetting("headingbillinginfo")) {
    $headingContactData = $this->getConfigurationSetting("headingbillinginfo");
}
?>

<h3 class='bottomborder'><? echo $headingContactData; ?></h3>
<span class='col-33'><label><input type='radio' name='type' class="typeSelection" view='private_person_form'><? echo $this->__w("Private person"); ?></label></span>
<span class='col-33'><label><input type='radio' name='type' class="typeSelection" view='company_form'><? echo $this->__w("Company"); ?></label></span>
<span class='col-33'><label><input type='radio' name='type' class="typeSelection" view='registered'><? echo $this->__w("Registered customer"); ?></label></span>
<div style='clear:both;'></div>
<div class='private_person_form billingform' style='display:none;'>
    <span class='col-33 hidenonsingleroom'><label><? echo $this->__w("Name"); ?><input type='text' name='name'  value="<? echo $booking->contactData->name; ?>"><? $this->validateContactData("name"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("Birth date"); ?><input type='text' name='birthday' value="<? echo $booking->contactData->birthday; ?>"><? $this->validateContactData("birthday"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("Address"); ?><input type='text' name='address'  value="<? echo $booking->contactData->address; ?>"><? $this->validateContactData("address"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("Postal code"); ?><input type='text' name='postalCode' value="<? echo $booking->contactData->postalCode; ?>"><? $this->validateContactData("postalCode"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("City"); ?><input type='text' name='city' value="<? echo $booking->contactData->city; ?>"><? $this->validateContactData("city"); ?></label></span>
    <span class='col-33 hidenonsingleroom'><label><? echo $this->__w("Email"); ?><input type='text' name='email' value="<? echo $booking->contactData->email; ?>"><? $this->validateContactData("email"); ?></label></span>
    <span class='col-33 hidenonsingleroom'><label><? echo $this->__w("Prefix"); ?><input type='text' name='prefix' value="<? echo $booking->contactData->prefix; ?>"><? $this->validateContactData("prefi"); ?></label></span>
    <span class='col-33 hidenonsingleroom'><label><? echo $this->__w("Phone"); ?><input type='text' name='phone' value="<? echo $booking->contactData->phone; ?>"><? $this->validateContactData("phone"); ?></label></span>
</div>
<div class='registered billingform' style='display:none;'>
    <span class='col-33'><label><? echo $this->__w("Username/email"); ?><input type='text' name='username' value="<? echo $booking->contactData->orgid; ?>"><? $this->validateContactData("username"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("Password"); ?><input type='password' name='password' value="<? echo $booking->contactData->name; ?>"><? $this->validateContactData("password"); ?></label></span>
</div>
<div class='company_form billingform' style='display:none;'>
    <span class='col-33'><label><? echo $this->__w("Orgnr"); ?><input type='text' name='orgid' value="<? echo $booking->contactData->orgid; ?>"><? $this->validateContactData("orgid"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("Organisation name"); ?><input type='text' name='name' value="<? echo $booking->contactData->name; ?>"><? $this->validateContactData("name"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("Address"); ?><input type='text' name='address' value="<? echo $booking->contactData->address; ?>"><? $this->validateContactData("address"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("Postal code"); ?><input type='text' name='postalCode' value="<? echo $booking->contactData->postalCode; ?>"><? $this->validateContactData("postalCode"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("City"); ?><input type='text' name='city' value="<? echo $booking->contactData->city; ?>"><? $this->validateContactData("city"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("Email"); ?><input type='text' name='email' value="<? echo $booking->contactData->email; ?>"><? $this->validateContactData("email"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("Prefix"); ?><input type='text' name='prefix' value="<? echo $booking->contactData->prefix; ?>"><? $this->validateContactData("prefi"); ?></label></span>
    <span class='col-33'><label><? echo $this->__w("Phone"); ?><input type='text' name='phone' value="<? echo $booking->contactData->phone; ?>"><? $this->validateContactData("phone"); ?></label></span>
</div>
<div style='clear:both;'></div>
<?php
if($config->needToAgreeOnContract) {
    $checked = "";
    if($booking->contactData->agreedToTerms) {
        $checked = "CHECKED";
    }
    echo "<div>";
    echo "<input type='checkbox' gsname='agreeonterms' $checked> I agree to the <a class='termslink' target='_new' onclick='window.open(\"/scripts/loadContract.php?engine=".$this->getSelectedName()."\")'>terms and conditions</a>";
    echo "</div>";
    $this->validateContactData("agreedToTerms");
}

$text = $this->getConfigurationSetting("complete_order_button");
if(!$text) {
    $text = $this->__w("Complete order");
}
?>

<span class='complete_button'><? echo $text; ?></span>
<?
echo $this->displayFailedBookingErrors();
?>
<script>
    <? if($booking->contactData->type == 2) {
        ?>
        $('.typeSelection[view="company_form"]').click();
        <?
    } else if($booking->contactData->type == 3) {
        ?>
        $('.typeSelection[view="registered"]').click();
        <?
    } else {
        ?>
        $('.typeSelection[view="private_person_form"]').click();
        <?
    }
    ?>
    if($('.roomdata').length ===1) {
        $('.hidenonsingleroom').hide();
        console.log('jahaha');
    }
</script>