<?php
/* @var $this \ns_d3951fc4_6929_4230_a275_f2a7314f97c1\PmsBookingContactData */
$config = $this->getConfigurationToUse();
$pmsconfig = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());

echo "<div gstype='form' method='submitForm' class='bookingregistrationform'>";

if($config->includeGuestData) {
    $this->includefile("guestdata");
}
foreach($config->data as $key => $value) {
    /* @var $value core_bookingengine_data_RegistrationRulesField */
    if(stristr($key, "field_")) {
        $this->printField($value);
    }
}

$booking = $this->getCurrentBooking();
if(sizeof($booking->rooms) == 0) {
    echo "<div style='font-size: 30px;'>No room has been selected, yet.<br>You need to select a room first.</div>";
    return;
}
foreach($config->data as $key => $value) {
    /* @var $value core_bookingengine_data_RegistrationRulesField */
    if(!stristr($key, "company_") && !stristr($key, "user_") && !stristr($key, "field_")) {
        $this->printField($value);
    }
}

switch($pmsconfig->bookingProfile) { 
   case "subscription":
         $completeText = $this->__w("Complete registration");
        break;
    case "storage":
         $completeText = $this->__w("Reserve your storage room now");
        break;
    default:
        $completeText = $this->__w("Reserve room now");
}

if(!$completeText) {
    $completeText = "Complete";
}

if(ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isCustomer()) {
    $user = $this->getApi()->getUserManager()->getLoggedOnUser();
    if($user->preferredPaymentType == "70ace3f0-3981-11e3-aa6e-0800200c9a66") {
        $note = "";
        if(isset($_POST['data']['invoicenote'])) {
            $note = $_POST['data']['invoicenote'];
        }
        echo "<h1>".$this->__w("Note on invoice")."</h1>";
        echo "<div style='padding-right: 10px;'>";
        echo "<textarea class='invoicenottextarea' gsname='invoicenote'>".$note."</textarea>";
        echo "</div>";
        if($this->validation) {
            foreach($this->validation as $error) {
                echo $error . "<br>";
            }
        }
    }
    
    $companyEmail = "";
    if(isset($booking->registrationData->resultAdded->{'company_email'})) {
        $companyEmail = $booking->registrationData->resultAdded->{'company_email'};
    }
    if($user->emailAddress) {
        $companyEmail = $user->emailAddress;
    }
    
    echo "<div style='clear:both;'></div>";
    echo "<label class='col-50'>";
    echo $this->__w("Send confirmation to an alternate email address") .":<br>";
    echo "<input type='text' gsname='company_email' value='".$companyEmail."'>";
    echo "<div class='errordesc'>";
    if(isset($this->validation["company_email"])) {
        echo "* " . $this->validation["company_email"];
    } else {
        echo "&nbsp;";
    }
    echo "</div>";
    echo "</label>";
    echo "<label class='col-50' style='position:absolute;'>Alternativ organisasjon<br>";
    echo "<span class='alternativeaccountbutton showsearchcompany'>Search</span>";
    $subid = "";
    if(isset($booking->alternativeOrginasation)) {
        $account = explode(";", $booking->alternativeOrginasation);
        $subid = $account[0];
        if(strlen($subid) < 15 && $subid) {
            echo "<span class='alternativeaccountbutton'><i class='fa fa-check'></i> ".$account[1]."</span>";
        }
    }
    $subUsers = (array)$user->subUserList;
    if(sizeof($subUsers) > 0) {
        $meSelected = "";
        if(!isset($booking->alternativeOrginasation) || !$booking->alternativeOrginasation) { $meSelected = "<i class='fa fa-check'></i>"; }
        echo "<span class='alternativeaccountbutton selectorgbtn' orgid=''>$meSelected Meg selv</span>";
        foreach($subUsers as $subUser) {
            $meSelected = "";
            if($subid == $subUser->id) {
                $meSelected = "<i class='fa fa-check'></i>";
            }
            echo "<span class='alternativeaccountbutton selectorgbtn' orgid='".$subUser->id.";" . $subUser->fullName."'>$meSelected " . $subUser->fullName . "</span>";
        }
    }
    
    echo "<span class='searchfororgpanel'>";
    echo "Navn på organisasjon<br>";
    echo "<input type='text' id='searchbrregkeyword'>";
    echo "<span class='alternativeaccountbutton searchbrregaltaccount'>Search</span>";
    echo "<div class='alternativeaccountresult'></div>";
    echo "</span>";
    echo "</label><br>";
    echo "<div style='clear:both;'></div>";

    $config2 = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
    if($config2->needToAgreeOnContract) {
        echo "<div>";
        echo "<span><div style='padding-bottom: 5px;'><input type='checkbox' gsname='agreetoterms'> ". $this->__w("I agree to the terms and conditions");
        echo "</div>";
          echo "<div style='font-size: 20px;color:red;'>";
            if(isset($this->validation['agreetoterms'])) {
                echo "* " . $this->validation['agreetoterms'];
            }
            echo "</div>";
        echo "<a class='termsandcondtext' onclick=\"window.open('/scripts/loadContractPdf.php?readable=true&engine=".$this->getSelectedName()."');\" >". $this->__w("Read the terms and conditions")."</a><br>";
        echo "<a class='termsandcondtext' onclick=\"window.open('/scripts/loadContractPdf.php?engine=".$this->getSelectedName()."');\">". $this->__w("Download the terms and conditions")."</a>";
        echo "</span>";
        echo "</div>";
    }
    
    echo "<span class='complete_button' id='reserveroom'>$completeText</span>";
} else {
    echo "<h2 class='paymentheaders'>".$this->__w("Contact information") . "</h2>";
    echo "<div class='chooseregform'>";
    echo "<label class='chooseprivateperson_label'><input type='radio' name='choosetyperadio' gsname='choosetyperadio' value='registration_private' class='ignoresaveform'> ". $this->__w("Private person") . "</label>";
    echo "<label class='choosecompany_label'><input type='radio' name='choosetyperadio' gsname='choosetyperadio' value='registration_company' class='ignoresaveform'> ". $this->__w("Organisation") . "</label>";
    if($this->isEditorMode()) {
        echo "<input type='radio' name='choosetyperadio' gsname='choosetyperadio' value='registered_user'> ". $this->__w("Registered customer");
    }
    echo "</div>";

    if($this->isEditorMode()) {
        echo "<div class='registered_user regforminput'>";
        echo "<br>";
        echo "<select class='selectregisterduser' style='width:100%;'>";
        $users = $this->getApi()->getUserManager()->getAllUsers();
        foreach($users as $user) {
            if($user->suspended) {
                continue;
            }
            $SELECTED = "";
            if($booking->userId == $user->id) {
                $SELECTED = "SELECTED";
            }
            echo "<option value='".$user->id."' $SELECTED>" . $user->fullName . "</option>";
        }
        echo "</select>";
        echo "<br><br>";
        echo "</div>";
    }

    echo "<div class='registration_private regforminput'>";
    $this->counter = 0;
    foreach($config->data as $key => $value) {
        /* @var $value core_bookingengine_data_RegistrationRulesField */
        if(stristr($key, "user_")) {
            $this->printField($value);
        }
    }
    echo "</div>";

    echo "<div class='registration_company regforminput'>";
    $this->counter = 0;
    foreach($config->data as $key => $value) {
        /* @var $value core_bookingengine_data_RegistrationRulesField */
        if(stristr($key, "company_")) {
            $this->printField($value);
        }
    }
    echo "</div>";

    if($config->displayContactsList) {
        echo "<div class='pmscontacts'>";
        $i = 0;
        foreach($this->getCurrentBooking()->registrationData->contactsList as $contacts) {
            echo "";
            echo "<label class='col-25'><i style='float:left;padding-right: 3px; cursor:pointer; ' class='fa fa-trash-o'  gstype='clicksubmit' method='removeIndex' gsname='index' gsvalue='$i'></i> Navn<input type='txt' style='box-sizing:border-box;' gsname='contact_name_$i' value='".@$contacts->name."'></label>";
            echo "<label class='col-25'>Epost<input type='txt' style='box-sizing:border-box;' gsname='contact_email_$i' value='".@$contacts->email."'></label>";
            echo "<label class='col-25'>Mobil<input type='txt' style='box-sizing:border-box;' gsname='contact_phone_$i' value='".@$contacts->phone."'></label>";
            echo "<label class='col-25'>Tittel<input type='txt' style='box-sizing:border-box;' gsname='contact_title_$i' value='".@$contacts->title."'></label>";
            $i++;
            echo "<div style='clear:both;'>";
            echo "</div>";
            echo "<br>";
        }
        echo "<div gstype='clicksubmit' method='addContact' gsname='id' gsvalue='somevalue' style='cursor:pointer;'>".$this->__w("Click here if you need to add more contacts") . "</div>";
        echo "</div>";
        echo "<br><br>";
    }

    $config2 = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
    echo "<div class='whenTypeIsSelected'>";
    if($config2->needToAgreeOnContract) {
        echo "<div>";
        echo "<span class='col-50'><div style='padding-bottom: 5px;'><input type='checkbox' gsname='agreetoterms'> ". $this->__w("I agree to the terms and conditions");
          echo "<span class='errordesc' style='font-size: 20px;'>";
            if(isset($this->validation['agreetoterms'])) {
                echo "* " . $this->validation['agreetoterms'];
            } else {
                echo "&nbsp;";
            }
            echo "</span>";

            echo "</label>";
        echo "</div>";
        echo "<a class='termsandcondtext' onclick=\"window.open('/scripts/loadContractPdf.php?readable=true&engine=".$this->getSelectedName()."');\" >". $this->__w("Read the terms and conditions")."</a><br>";
        echo "<a class='termsandcondtext' onclick=\"window.open('/scripts/loadContractPdf.php?engine=".$this->getSelectedName()."');\">". $this->__w("Download the terms and conditions")."</a>";
        echo "</span>";
        if($this->isEditorMode() && $pmsconfig->requirePayments && !$pmsconfig->autoCreateInvoices) {
            echo "<span class='col-50' style='padding-right:0px;'><span style='margin-top: 5px;' class='complete_button' gsvalue='nopay'>".$this->__w("Continue")."</span>";
        } else {
            echo "<span class='col-50' style='padding-right:0px;'><span class='complete_button' id='reserveroom'>$completeText</span>";
        }
        echo "</div>";
    } else {
        if($this->isEditorMode() && $pmsconfig->requirePayments && !$pmsconfig->autoCreateInvoices) {
            echo "<span style='margin-top: 5px;'  class='complete_button' gsvalue='nopay'>".$this->__w("Continue")."</span>";
        } else {
            echo "<span class='complete_button' id='reserveroom'>$completeText</span>";
        }
    }
    echo "</div>";
    if(isset($this->unknownError) && $this->unknownError) {
        echo "<b style='color:red'>" . $this->unknownError . ", please verify that all your dates are valid.</b>";
    }
    echo "<div style='clear:both;'></div>";
}
echo "</div>";

$curAddedFields = $this->getCurrentBooking()->registrationData->resultAdded;

if(isset($curAddedFields->{'choosetyperadio'})) {
    echo "<script>";
    echo "$('input[name=\"choosetyperadio\"][value=\"".$curAddedFields->{'choosetyperadio'}."\"]').click();";
    echo "</script>";
} else {
    echo "<script>";
    if($this->getConfigurationSetting("default_org") == "yes") {
        echo "$('input[name=\"choosetyperadio\"][value=\"registration_company\"]').click();";
    } else {
        echo "$('input[name=\"choosetyperadio\"][value=\"registration_private\"]').click();";
    }
    echo "</script>";
}

?>
