<?php
/* @var $this \ns_d3951fc4_6929_4230_a275_f2a7314f97c1\PmsBookingContactData */
$booking = $this->getApi()->getPmsManager()->getCurrentBooking($this->getSelectedName());

?>
<h3><? echo $this->__w("Room information"); ?></h3>
<?
foreach($booking->rooms as $room) {
    /* @var $room core_pmsmanager_PmsBookingRooms */
    for($i = 0; $i < $room->count; $i++) {
        echo "<div class='roomdata' bookingItemId='".$room->bookingItemTypeId."'>";
        echo "<span class='col-33'><label>".$this->__w("Name")."<input type='text' name='name'></label></span>";
        echo "<span class='col-33'><label>".$this->__w("Phone")."<input type='text' name='phone'></label></span>";
        echo "<span class='col-33'><label>".$this->__w("Email")."<input type='text' name='email'></label></span>";
        echo "</div>";
    }
}
?>
<div style='clear:both;'></div>
<br><br>
<h3><? echo $this->__w("Billing information"); ?></h3>
<span class='col-33'><label><input type='radio' name='type' class="typeSelection" view='private_person_form'><? echo $this->__w("Private person"); ?></label></span>
<span class='col-33'><label><input type='radio' name='type' class="typeSelection" view='company_form'><? echo $this->__w("Company"); ?></label></span>
<div style='clear:both;'></div>
<div class='private_person_form billingform' style='display:none;'>
    <span class='col-33'><label><? echo $this->__w("Birth date"); ?><input type='text'></label></span>
    <span class='col-33'><label><? echo $this->__w("Address"); ?><input type='text'></label></span>
    <span class='col-33'><label><? echo $this->__w("Postal code"); ?><input type='text'></label></span>
    <span class='col-33'><label><? echo $this->__w("City"); ?><input type='text'></label></span>
    <span class='col-33'><label><? echo $this->__w("Email"); ?><input type='text'></label></span>
</div>
<div class='company_form billingform' style='display:none;'>
    <span class='col-33'><label><? echo $this->__w("Orgnr"); ?><input type='text'></label></span>
    <span class='col-33'><label><? echo $this->__w("Organisation name"); ?><input type='text'></label></span>
    <span class='col-33'><label><? echo $this->__w("Address"); ?><input type='text'></label></span>
    <span class='col-33'><label><? echo $this->__w("Postal code"); ?><input type='text'></label></span>
    <span class='col-33'><label><? echo $this->__w("City"); ?><input type='text'></label></span>
    <span class='col-33'><label><? echo $this->__w("Email"); ?><input type='text'></label></span>
</div>
<div style='clear:both;'></div>
<span class='complete_button'><? echo $this->__w("Complete order"); ?></span>