
<div style='font-size: 20px; margin-left: 20px;margin-bottom:20px; color:red; font-weight: bold;'>
    <!--<i class="fa fa-warning"></i> Sommertider i GetShop, viktig informasjon om support og opplæring! <span onclick='$(".readcriticalmessage").slideDown()' style='color:blue; cursor:pointer;'>les mer</span>-->
</div>

<div class='readcriticalmessage' style='font-size: 20px; margin-left: 20px;margin-bottom:20px;font-weight: bold; display:none;'>
Endelig er sommeren her og det er vanligvis tiden for å slappe av og nyte det fine været.<br>
<br>
Vi ønsker alle en god og inntektsgivende sommer men vi må også minne om at GetShop går inn i en tid med begrenset support.
Vi kan derfor ikke være til stede i samme grad for å bistå med opplæring om det skulle være nødvendig.
<br>
<br>
Vi vet at enkelte hoteller tar inn sommervikarer som kan ha behov for ekstra opplæring, noe som både er tidkrevende og utfordrende.<br>
For å lette på dette har vi laget en opplæringsvideo i håp på å få overgangen enklere for dere.<br>
<br>
Filmen kan dere finne -> <a href='https://www.youtube.com/watch?v=MhBuoDj22T4' target='_new' style='color:red;'>her</a>, i kommentarfeltet på filmen kan dere navigere mellom kapitlene.<br>
<br>
Vi håper den er til hjelp for dere som har behov for den.<br>
<br>
Hvis det skulle være behov for support utover filmen kan dere opprette en ticket, ticket systemet er blir betjent som normalt, og urgent tickets blir prioritert.<br>
PS: Urgent skal kun benyttes hvis ikke det er mulig å vente på et svar, det vil si kun kritiske hendelser skal markeres som urgent, missbruk kan medføre utstengelse av ticketsystemet.<br><br>
Telefon supporten blir redusert fra 10:00 til 14:00.<br>
<hr>
</div>
