<div style='font-size: 20px; margin-left: 20px;margin-bottom:20px; color:red; font-weight: bold;'>
    <i class="fa fa-warning"></i> Important information; GetShop got struck by Corona! <span onclick='$(".readcriticalmessage").show()' style='color:blue; cursor:pointer;'>read more</span>.
</div>

<div class='readcriticalmessage' style='font-size: 20px; margin-left: 20px;margin-bottom:20px;font-weight: bold; display:none;'>
    The accommodation industry is facing a hard and challenging task ahead to stay alive while the world combat the virus.<br>
    Our statistics for the next months does not look good at all and we will need to take preventing measures to handle the crisis.<br><br>
    The latest announcement by the Norwegian government makes it really hard to operate at peak performance. Half of our staff already need to stay at home caring for their children.<br>
    Because of this we will have to do the following:
    <ul>
        <li>Put all software development on hold</li>
        <li>Focus all our effort into handling support and keeping the systems up and running, response time in the ticket system might be delayed.</li>
        <li>We will have to put all future delivery to new hotels on hold until the virus is under control.</li>
        <li>There will be no planned physical meetings.</li>
        <li>Phone will be answered as normal.</li>
    </ul>
    We are writing this in the hope that everyone understand that we might not be able to maintain the same level of support during this days. However we will do our best.<br><br>
    We really sympathies with everyone affected with this tragedy.
</div>
