<div class="statistics">
    <b>I dag</b>
    
    <div class="statiticbox counter1">
        <div class="filecount boldFont">12</div>
        <div class="subinfo boldFont"> Innsjekk</div>
    </div>

    <div class="statiticbox counter2">
        <div class="filecount boldFont">18</div>
        <div class="subinfo boldFont"> Utsjekk </div>
    </div>    
</div>

<div class="statistics">
    <b>I morgen</b>
    
    <div class="statiticbox counter1">
        <div class="filecount boldFont">10</div>
        <div class="subinfo boldFont"> Innsjekk</div>
    </div>

    <div class="statiticbox counter2">
        <div class="filecount boldFont">20</div>
        <div class="subinfo boldFont"> Utsjekk </div>
    </div>    
</div>

<div class="statistics">
    <b>Renhold</b>
    
    <div class="statiticbox counter1">
        <div class="filecount boldFont">7</div>
        <div class="subinfo boldFont">Stayovers</div>
    </div>

    <div class="statiticbox counter2">
        <div class="filecount boldFont">28</div>
        <div class="subinfo boldFont">Rom igjen <br/>å vaske</div>
    </div>    
</div>

<div class="statistics">
    <b>Whatever</b>
    
    <div class="statiticbox counter1">
        <div class="filecount boldFont">15</div>
        <div class="subinfo boldFont">Bla</div>
    </div>

    <div class="statiticbox counter2">
        <div class="filecount boldFont">21</div>
        <div class="subinfo boldFont">Bla</div>
    </div>    
</div>
