<div class="uploadfilemodal">
    
    <div class="modal_inner">
        <div class="modalcontent">
            
            
            <div class="progressbararea">
                <div class="progressheader">Uploading: <span class="sedox_upload_filename"> Test</span></div>
                
                <div class="meter">
                    <span style="width: 0%"></span>
                    <div class="progresindicator">0%</div>
                </div>
                
                <div class="selectfiletypearea">
                    <div class="closebutton"><i class="fa fa-close"></i></div>    
                    What type of file is this?
                    <br/>
                    <div class="filetype" type='Stage 1 Power'>Stage 1 Power</div>
                    <div class="filetype" type='Stage 2 Power'>Stage 2 Power</div>
                    <div class="filetype" type='Combi Power/ECO'>Combi Power/ECO</div>
                    <br/>
                    <div class="filetype" type='Full ECO'>Full ECO</div>
                    <div class="filetype" type='Original'>Original</div>
                    <div class="filetype" type='Various'>Various</div>
                    <div class="filetype" type='Truck'>Truck</div>
                    <div class="filetype" type='Tractor'>Tractor</div>
                </div>
            </div>
                
            <div class="selectarea">
                <div class="closebutton"><i class="fa fa-close"></i></div>    
                <div class="headertitle boldFont"> Upload your files </div>    
                <div class="dragdropfilesareas" id="dragdropfilesareas">
                    <i class="fa fa-cloud-upload"></i>
                    Drag and Drop File Here
                    <br/> or
                    <br/>

                    <div class="fileBrowse btn btn-primary sedox_blue_button selectFileButton">
                        <span>BROWSE</span>
                        <input type="file" id="sedox_file_upload_selector" class="upload" />
                    </div>
                </div>
            </div>
        </div>
    </div>
        
</div>
    