Enter email/name of the user: <input type='textfield' id='searchfield'>
<div class='result'>
    <?
    $users = $this->getSearchUsers();
    if (count($users)) {
        foreach ($users as $user) {
            $name = $user->fullName;
            $email = $user->emailAddress;
            $id = $user->id;
            echo "<div userId='$id' class='userentrysearch'>$name - $email</div>";
        }
    }
    ?>
</div>
