<?
$userid = $_POST['data']['userId'];
$user = $this->getApi()->getUserManager()->getUserById($userid);
$sedoxUser = $this->getApi()->getSedoxProductManager()->getSedoxUserAccountById($userid);
$checked = $sedoxUser->creditAccount->allowNegativeCredit ? "checked" : "";
$checkedwindowsapp = $sedoxUser->canUseExternalProgram ? "checked" : "";
$isASlave = $sedoxUser->masterUserId != null && $sedoxUser->masterUserId != "";
$passiveslavechecked = $sedoxUser->isPassiveSlave ? "checked='checked'" : "";
?>

<div class="useroverview" userid="<? echo $userid; ?>">
    Id: <? echo $userid; ?>
    <br> Name: <? echo $user->fullName; ?>
    <br> Email: <? echo $user->emailAddress; ?>
    <br> Current balance: <? echo $sedoxUser->creditAccount->balance; ?>
    <br> Allow negative credit: <input id="allownegativecredit" userId="<? echo $user->id; ?>" type="checkbox" <? echo $checked; ?> />
    <br> Allow use of windows program: <input id="allowwindowsapp" userId="<? echo $user->id; ?>" type="checkbox" <? echo $checkedwindowsapp; ?> />
    <br>
    <br><div class="gs_button saveusersettings" userId="<? echo $userid; ?>"> Save </div>
    <br>
    <hr>
    <b>Change credit amount:</b>
    <table>
        <tr><td>Description</td><td><input id="sedox_credit_description" type="textfield"/></td></tr>
        <tr><td>Amount</td><td><input type="textfield" id="amount"/></td></tr>
    </table>
    <div class="gs_button savecredit" userId="<? echo $userid; ?>"> Update </div>
    <hr/>
    <b>Slave/Master Setup:</b><br><br>
    <?
    if ($isASlave) {
        $sedoxMasterUser = $this->getApi()->getSedoxProductManager()->getSedoxUserAccountById($sedoxUser->masterUserId);
        $slaveUser = $this->getApi()->getUserManager()->getUserById($sedoxMasterUser->id);
                
        echo "This is a slave and is connected to master: <span class='showuser' userid='$slaveUser->id'>".$slaveUser->fullName ." (".$slaveUser->emailAddress.")</span>";
        echo "<br><br><input id='togglepassiveslave' $passiveslavechecked type='checkbox'/> Is this an passive slave?";
    } else {
        $slaves = $this->getApi()->getSedoxProductManager()->getSlaves($userid);
        if (!count($slaves)) {
            echo "no slaves connected to this user";
        } else {            
            foreach ($slaves as $slave) {
                $id = $slave->id;
                $user = $this->getApi()->getUserManager()->getUserById($slave->id);
                $remove = "<i class='fa fa-trash-o removeuser' userid='$id' style='cursor: pointer'></i> ";
                $extraIncome = $slave->slaveIncome;

                $slaveUserInfo = "<span class='showuser' userid='$user->id'>".$user->fullName ." (".$user->emailAddress.")</span>";
                echo "<div> $remove <input type='text' class='extraincometext' value='$extraIncome' userid='$id'/> $slaveUserInfo</div>";
            }
        }
        ?>
        <br>
        <br>Search for a slave add by enter text: &nbsp;<input id='slavesearchtextfield' type='text'/>
        <div class='add_slave_result'>

        </div>
    <? } ?>
</div>