<div class="related_product_administration">
    <center><h1><? echo $this->__f("Related product administration"); ?></h1></center>
    
    <? echo $this->__f("Enter product name here to search for a product to add as related"); ?>:
    <br/><input type="textfield" id="searchforproducts" placeholder="" value="<? echo isset($_SESSION['add_related_products_seachword']) ? $_SESSION['add_related_products_seachword'] : ""; ?>"/><i class="fa fa-search searchForRelatedProducts"></i>
    
    <div class="add_related_product_result">
        <?
        $this->includefile("searchresult");
        ?>
    </div>
</div>