<?
/* @var $this \ns_3cdcd5e5_b3e8_4fa1_9125_bef44fa6a082\RelatedProducts */

$res = $this->getApi()->getProductManager()->search($_SESSION['add_related_products_seachword'], 50, 1);

if (!count($res->products)) {
    echo $this->__f("No result found");
    return;
}
foreach ($res->products as $result) { 
    /* @var $result core_productmanager_data_Product */
    ?>
    <div class="search_result_product">
        <? echo $result->name; ?>
        <div class="shop_button add_product_as_related"  product_id="<? echo $result->id; ?>"><? echo $this->__f("Add as related"); ?></div>
    </div>
<?
}
?>