
<div class="gss_settings_header">
    <i class="fa fa-dollar"></i>

    <div class="gss_settings_header_description">
        <div class="gss_settings_header_title"> <? echo $this->__f("Payment methods"); ?></div>

        <div class="gss_settings_header_description_inner">
            Activate your desired payment method.
        </div>
    </div>	
</div>
<div class="gss_settings_content">
    <?php
    /* @var $this \ns_f474e3f0_7ef6_4611_9202_9332302a5e38\PaymentSettingsSetup */
    $multiplepaymentmethodsactivated = 0;
    $applications = $this->getApi()->getStoreApplicationPool()->getAvailableApplications();
    $activated = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
    $activatedDebtCollectors = $this->getApi()->getStoreApplicationPool()->getActivatedApplications("DebtCollectorApplication");
    if(is_array($activatedDebtCollectors)) {
        $activated = array_merge($activated, $activatedDebtCollectors);
    }
    
    
    $lockedPeriods = $this->getApi()->getPosManager()->hasLockedPeriods();
    $promptAccount = $lockedPeriods ? "gs_prompt='You need to specify an account for this payment application to be activated, please contact your accountant to get information on what account to post this transactions on'" : "";
    
    $res = array();
    $paymentsSupportForMultiplePayments = array();
    foreach($activated as $active) {
        $res[] = $active->id;
    }
    
    for($i = 0; $i < 2; $i++) {
        echo "<div style='clear:both;'></div>";
        if($i == 0) {
            echo "<h1>Payment methods</h1>";
        } else {
            echo "<h1>Manual payment methods</h1>";
        }
        foreach($applications as $app) {
            if($app->type == "PaymentApplication" || $app->type == "DebtCollectorApplication") {
                if($app->id == "6e930536-eca4-4742-9712-bf2042c8cf86") {
                    continue;
                }
                if($app->id == "d96f955a-0c21-4b1c-97dc-295008ae6e5a") {
                    continue;
                }
                if($app->id == "486009b1-3748-4ab6-aa1b-95a4d5e2d228") {
                    continue;
                }
                if($app->id == "bd13472e-87ee-4b8d-a1ae-95fb471cedce") {
                    continue;
                }
                $instance = $this->getFactory()->getApplicationPool()->createInstace($app);
                if(!method_exists($instance, "isPublicPaymentApp")) {
                    continue;
                }
                if(!$instance->isPublicPaymentApp()) {
                    continue;
                }
                if(method_exists($instance, "getName")) {
                    if($i == 0 && stristr($instance->applicationSettings->appName, "PaymentMethod")) {
                        continue;
                    }
                    if($i == 1 && !stristr($instance->applicationSettings->appName, "PaymentMethod")) {
                        continue;
                    }

                    echo "<span class='paymentappactivation'>";
                    echo "<div class='header'>" . $instance->getName() . "</div>";
                    echo "<div class='description'>" . $instance->getDescription() . "</div>";
                    if(in_array($app->id, $res)) {
                        if(method_exists($instance, "printButton")) {
                            $multiplepaymentmethodsactivated++;
                            $paymentsSupportForMultiplePayments[$app->id] = $instance->getName();
                        }
                        echo "<div class='footer deactivate' gstype='clicksubmit' gsvalue='".$app->id."' method='deactivateApp' gsname='id'>Deactivate</div>";
                    } else {
                        echo "<div class='footer' gstype='clicksubmit' gsvalue='".$app->id."' method='activateApp' gsname='id' $promptAccount>Activate</div>";
                    }
                    echo "</span>";
                }
            }
        }
    }

    ?>
    <div style='clear:both;'></div>
</div>
<?php
if($multiplepaymentmethodsactivated > 1) {
    ?><h1>Provide multiple payment methods for customers</h1><?php
    $multipleids = (array)$this->getApi()->getPaymentManager()->getMultiplePaymentMethods();
    echo "<span gstype='form' method='saveMultiplePayments'>";
    foreach($paymentsSupportForMultiplePayments as $id => $name) {
        $checked = in_array($id, $multipleids) ? "CHECKED" : "";
        echo "<input type='checkbox' gsname='method_$id' $checked> $name<br>";
    }
    echo "<br>";
    echo "<span class='shop_button' gstype='submit'>Save selection</span>";
    echo "<br>";
    echo "<br>";
    echo "</span>";
}
?>
