<?php
/* @var $this \ns_f474e3f0_7ef6_4611_9202_9332302a5e38\PaymentSettingsSetup */

$applications = $this->getApi()->getStoreApplicationPool()->getAvailableApplications();
$activated = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
$res = array();
foreach($activated as $active) {
    $res[] = $active->id;
}

foreach($applications as $app) {
    if($app->type == "PaymentApplication") {
        $instance = $this->getFactory()->getApplicationPool()->createInstace($app);
        if(!method_exists($instance, "isPublicPaymentApp")) {
            continue;
        }
        if(!$instance->isPublicPaymentApp()) {
            continue;
        }
        if(in_array($app->id, $res)) {
            continue;
        }
        if(method_exists($instance, "getName")) {
            echo "<span class='paymentappactivation'>";
            echo "<div class='header'>" . $instance->getName() . "</div>";
            echo "<div class='description'>" . $instance->getDescription() . "</div>";
            echo "<div class='footer'>Activate</div>";
            echo "</span>";
        }
    }
}

?>