<?php
/* @var $this BookCampingPage */
$config = $this->getApi()->getPmsBookingProcess()->getConfiguration($this->getBookingEngineName());
?>

<div class='heading'>
    <?php
    echo $this->__f("Who are you?");
    ?>
</div>

<div class='contactinfo'>
    <div class='col'>
        <div class='label'><?php echo $this->__f("Your name"); ?></div>
        <br/> <div type="text" tabindex="0" class='gstextfield reference' id="name"><div class="inner"></div></div>
    </div>
    <div class='col'>
        <div class='label'><?php echo $this->__f("Email"); ?></div>
        <br/> <div type="text" tabindex="0" class='gstextfield reference' id="email"><div class="inner"></div></div>
    </div>
    <div class='col'>
        <div class='label'><?php echo $this->__f("Phonenumber"); ?></div>
        <br/> <span>+</span><div type="text" tabindex="0" class='gstextfield reference' id="prefix"><div class="inner"><?php echo $config->phonePrefix; ?></div></div><span>-</span><div type="text" tabindex="0" class='gstextfield reference' id="phone"><div class="inner"></div></div>
    </div>
    
    <div class='summary'>
        <?php echo "<b>".$this->__f("Checkout")."</b>: " . $_SESSION['checkoutdate']; ?>
        <br/> <?php echo "<b>".$this->__f("Campingspot")."</b>: " . $this->getCampingSpot(); ?>
    </div>
    <br/>
    <div class='button startpayment'><?php echo $this->__f("Start payment"); ?></div> 
    <a href='/?page=bookingfrontpage'><div class='button cancel red'><?php echo $this->__f("Cancel"); ?></div></a>
</div>