<?php
/* @var $this BookCampingPage */
/* @var $items \core_bookingengine_data_BookingItem[] */

function sortByOrder($itema, $itemb) {
    return strcmp($itema->bookingItemName, $itemb->bookingItemName);
}

$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getBookingEngineName());
$allItems = $this->getApi()->getBookingEngine()->getBookingItems($this->getBookingEngineName());
?>

<div class='heading'>
    <?php
    echo $this->__f("Please select your campingspot");
    ?>
</div>

<div class='headerinfo'>
    <?php echo $this->__f("Checkout date").": ". $_SESSION['checkoutdate']; ?> 
    <div class='button changecheckoutdate'><?php echo $this->__f("Change checkout date"); ?></div>
    <a href='/?page=bookingfrontpage'><div class='button red cancelbooking'><?php echo $this->__f("Cancel booking"); ?></div></a>
</div>

<?php

foreach ($types as $type) {
    if ($type->systemCategory != 3) {
        continue;
    }

    
    $items = $this->getApi()->getBookingEngine()->getAvailbleItems($this->getBookingEngineName(), $type->id, $this->getJavaStartDate(), $this->getJavaCheckoutDate());
    
    
    
    usort($items, 'sortByOrder');
    
    echo "<div class='cattitle'>".$type->name."</div>";
    ?>
    <div class='bookingitems'>
        <?php
        foreach ($allItems as $item) {
            $available = $this->isInArray($item, $items);
            $inUse = !$available ? "inuse" : "selectable";
            
            if ($item->bookingItemTypeId != $type->id) {
                continue;
            }
            
            ?>
            <div class='bookingitem <?php echo $inUse; ?>' itemid='<?php echo $item->id; ?>'>
                <?php echo $item->bookingItemName; ?>
            </div>
            <?php
        }
        ?>
    </div>
    <?php
}
?>