<?php
/* @var $this ns_7db21d0e_6636_4dd3_a767_48b06932416c\PmsRestrictions */
$timePeriodeType = array();
$timePeriodeType[1] = "Closed";
$timePeriodeType[2] = "Min stay";
$timePeriodeType[3] = "Max stay";
$timePeriodeType[4] = "Deny same day booking";
$timePeriodeType[6] = "Force confirmation same day booking";
$timePeriodeType[7] = "No check in";
$timePeriodeType[8] = "No check out";
$curdate = date("d.m.Y", time());
?>

<input type='button' value='Create a restriction' onclick='$(".createrestricitonarea").toggle();' style='cursor:pointer;'>
<div style='height: 10px;'></div>
<span class='createrestricitonarea' gstype="form" method="createRestriction">
    <h3>What kind of restriction would you like to create?</h3>
    <select class='gsniceselect1 restrictiontype' style='width:100%;' gsname='timeperiodetype'>
        <?php
        foreach($timePeriodeType as $idx => $val) {
            echo "<option value='$idx'>$val</option>";
        }
        ?>
    </select>

    <h3>Start restriction at</h3>
    <div class="whenbooking" style="display:none;"> * When <b>booking</b> in this periode</div>
    <div class="whenstaying"> * When <b>staying</b> in this periode</div>
      <input type='txt' class='gsniceinput1 startdate' gsname='eventStartsAt' value='<?php echo $curdate; ?>' style='width: 90px;'>
      <input type='txt' class='gsniceinput1 starteventtime' style='width:40px;display:none;' value='00:00' gsname='starttime'>
      <input type='txt' class='gsniceinput1 endeventtime' style='width:40px;display:none;' value='23:59' gsname='endtime'>
      <input type="txt" class='gsniceinput1 mindays' placeholder='Days' style='width:40px; display:none;float:right;' gsname='timePeriodeTypeAttribute'>
      <h3>Repeat</h3>
        <select class="repeat_type gsniceselect1" style='width:100%;'  gsname='repeat_periode'>
            <option value="0" title="Daily"><? echo $this->__w("Daily"); ?></option>
            <option value="1" title="Weekly"><? echo $this->__w("Weekly"); ?></option>
            <option value="2" title="Monthly"><? echo $this->__w("Monthly"); ?></option>
        </select>

    <span class='optionbox'>
        <span class='repeat_0 repeatoption'></span>
        <span class='repeat_1 repeatoption'>
            <table>
                <tr>
                    <td><input type='checkbox' gsname='repeatMonday'><? echo $this->__w("Mon"); ?></td>
                    <td><input type='checkbox' gsname='repeatTuesday'><? echo $this->__w("Tue"); ?></td>
                    <td><input type='checkbox' gsname='repeatWednesday'><? echo $this->__w("Wed"); ?></td>
                    <td><input type='checkbox' gsname='repeatThursday'><? echo $this->__w("Thu"); ?></td>
                </tr>
                <tr>
                    <td><input type='checkbox' gsname='repeatFriday'><? echo $this->__w("Fri"); ?></td>
                    <td><input type='checkbox' gsname='repeatSaturday'><? echo $this->__w("Sat"); ?></td>
                    <td><input type='checkbox' gsname='repeatSunday'><? echo $this->__w("Sun"); ?></td>
                </tr>
            </table>
        </span>
        <span class='repeat_2 repeatoption' style='padding-bottom: 10px;'>
            <input type='radio' name='repeatmonthtype' gsname='repeatmonthtype' value='dayofmonth'><? echo $this->__w("day of the month"); ?><br>
            <input type='radio' name='repeatmonthtype' gsname='repeatmonthtype' value='dayofweek'><? echo $this->__w("day of the week"); ?>
        </span>
    </span>
    <h3>Ending at</h3>
    <input type='txt' class='gsniceinput1 enddate' value='<?php echo $curdate; ?>' style='width: 90px;' gsname='endingAt'>
    <hr>
    <h3>Include only this categories</h3>
    * PS: Category filter is in beta and might not work.<br>Please give us feedback if it does not work.<bR><bR>
    <?php
    $types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName());
    foreach($types as $type) {
        echo "<div><input type='checkbox' gsname='category_".$type->id."'>" . $type->name . "</div>";
    }
    ?>

    <input type='button' style='padding:9px;float:right;' value='Create restriction' gstype='submit'>
</span>

<script>
    $('.startdate').datepicker({ dateFormat: "dd.mm.yy"});
    $('.enddate').datepicker({ dateFormat: "dd.mm.yy"});
</script>
<style>
    .GetShopModuleTable .col_1 { width: 100%; }
</style>
