<?php
/* @var $this \ns_1be25b17_c17e_4308_be55_ae2988fecc7c\PmsPricing */
$itemTypes = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
$start = $this->getStart();
$end = $this->getEnd();
$priceObject = $this->getPrices();
$prices = $priceObject->dailyPrices;

$pricetypes = array();
$pricetypes[1] = "Daily";
$pricetypes[2] = "Monthly";
$pricetypes[3] = "Weekly";
$pricetypes[4] = "Per minute";
$pricetypes[5] = "Per hour";
$pricetypes[6] = "Per seconds";
$pricetypes[7] = "Progressive";
$pricetypes[8] = "Interval pricing";

?>
<div gstype='form' method="selectDates">
    <input type='text' gsname='start' value='<? echo $start; ?>'>
    <input type='text' gsname='end' value='<? echo $end; ?>'>
    <span gstype='submit' class='pmsbutton'>Set date range</span>
</div>
<br><br>
<br><br>

<table>
    <tr>
        <th align='left'>Item</th>
        <th align='left'>Mo<br><input type='checkbox' class='selectcol' weekday='1'></input></th>
        <th align='left'>Tu<br><input type='checkbox' class='selectcol' weekday='2'></input></th>
        <th align='left'>We<br><input type='checkbox' class='selectcol' weekday='3'></input></th>
        <th align='left'>Th<br><input type='checkbox' class='selectcol' weekday='4'></input></th>
        <th align='left'>Fr<br><input type='checkbox' class='selectcol' weekday='5'></input></th>
        <th align='left'>Sa<br><input type='checkbox' class='selectcol' weekday='6'></input></th>
        <th align='left'>Su<br><input type='checkbox' class='selectcol' weekday='0'></input></th>
        <th align='left'>Price<br>&nbsp;</th>
<?php
foreach($itemTypes as $item) {
    echo "<tr itemid='".$item->id."'>";
    echo "<td><input type='checkbox' class='selectrow'> " . $item->name . "</td>";
    echo "<td><input type='checkbox' weekday='1' class='pricecheckbox'></td>";
    echo "<td><input type='checkbox' weekday='2' class='pricecheckbox'></td>";
    echo "<td><input type='checkbox' weekday='3' class='pricecheckbox'></td>";
    echo "<td><input type='checkbox' weekday='4' class='pricecheckbox'></td>";
    echo "<td><input type='checkbox' weekday='5' class='pricecheckbox'></td>";
    echo "<td><input type='checkbox' weekday='6' class='pricecheckbox'></td>";
    echo "<td><input type='checkbox' weekday='0' class='pricecheckbox'></td>";
    echo "<td><input type='txt' class='priceinput'></td>";
    echo "</tr>";
}
?>
    <tr>
        <td colspan='8'></td>
        <td>
            <span class='pmsbutton updatePricingTable'>Set prices</span>
        </td>
    </tr>
</table>
<br><br>
<br><br>
<div gstype='form' method='updateProgressivePrices'>
    <?php
    $checked = "";
    if($priceObject->pricesExTaxes) {
        $checked = "CHECKED";
    }
    echo "<input type='checkbox' class='pricesextaxes' $checked> Prices ex taxes<br>";
    $checked = "";
    if($priceObject->privatePeopleDoNotPayTaxes) {
        $checked = "CHECKED";
    }
    echo "<input type='checkbox' class='privatePeopleDoNotPayTaxes' $checked> Private people and no tax registerd companies does not need to pay taxes<br>";
    echo "<select class='pricetypeselection' gsname='pricetype'>";
    foreach($pricetypes as $idx => $type) {
        $selected = "";
        if($idx == $priceObject->defaultPriceType) {
            $selected = "SELECTED";
        }
        echo "<option value='$idx' $selected>$type</option>";
    }
    echo "</select>";
    $this->includefile("discountpricing");
    if($priceObject->defaultPriceType == 7 || $priceObject->defaultPriceType == 8) {
        $this->includefile("progressivepricing");
    } else {
        $this->includefile("dailypriceediting");
    }
    ?>
</div>
<script>
    $('input[gsname="start"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('input[gsname="end"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
</script>