<?php
/* @var $this \ns_1be25b17_c17e_4308_be55_ae2988fecc7c\PmsPricing */
$itemTypes = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
$start = $this->getStart();
$end = $this->getEnd();
$priceObject = $this->getPrices();
$prices = $priceObject->dailyPrices;
echo "<pre>";
//print_r($priceObject);
echo "</pre>";

$pricetypes = array();
$pricetypes[1] = "Daily";
$pricetypes[2] = "Monthly";
$pricetypes[3] = "Weekly";
$pricetypes[4] = "Per minute";
$pricetypes[5] = "Per hour";
$pricetypes[6] = "Per seconds";
$pricetypes[7] = "Progressive";
$pricetypes[8] = "Interval pricing";

$priceCodes = $this->getApi()->getPmsManager()->getpriceCodes($this->getSelectedName());
?>
<div style="border-bottom: solid 1px; margin-bottom: 20px; padding-bottom: 20px;">
    <?php
    foreach($priceCodes as $code) {
        $selected = "";
        if($code == $this->getSelectedPricePlan()) {
            $selected = "selectedpriceplan";
        }
        echo '<span class="pmsbutton '.$selected.'" style="margin-right: 5px;" gstype="clicksubmit" method="selectPricePlan" gsname="selectedpriceplan" gsvalue="'.$code.'">'.$code.'</span>';
    }
    ?>
</div>

<input type='button' gstype='clicksubmitforce' gsvalue='<?php echo $priceObject->code; ?>' gsname='code' value='Delete price plan' style='float:right;' method='deletePricePlan'>
<div method='changepricetype' gstype='form'>
    <?php
    echo "<input type='text' gsname='code' value='".$priceObject->code."'><br>";
    echo "<select gsname='pricetype'>";
    foreach($pricetypes as $id => $type) {
        $selected = ($priceObject->defaultPriceType == $id) ? "SELECTED" : "";
        echo "<option value='$id' $selected>" . $type . "</option>";
    }
    echo "</select> ";
    echo "<input type='button' value='Change price type' gstype='submit'></input>";
    ?>
</div>

<table width='100%'>
    <tr>
        <td valign='top'>
            <h1>Step 1 / 3: Select a date range</h1>
            <div gstype='form' method="selectDates">
                <input type='text' gsname='start' value='<? echo $start; ?>' style='margin-right:5px; font-size: 20px; width: 110px; text-align:center;'>
                <input type='text' gsname='end' value='<? echo $end; ?>' style='margin-right:5px; font-size: 20px; width: 110px; text-align:center;'>
                <span gstype='submit' class='pmsbutton'>Set date range</span>
            </div>
        </td>
        <td valign='top' style='padding-left: 50px;'>

            <h1>Step 2 / 3: Set the prices</h1>
            <table width='100%'>
                <tr>
                    <th align='left'>Item</th>
                    <th align='left'>Mo<br><input type='checkbox' class='selectcol' weekday='1'></input></th>
                    <th align='left'>Tu<br><input type='checkbox' class='selectcol' weekday='2'></input></th>
                    <th align='left'>We<br><input type='checkbox' class='selectcol' weekday='3'></input></th>
                    <th align='left'>Th<br><input type='checkbox' class='selectcol' weekday='4'></input></th>
                    <th align='left'>Fr<br><input type='checkbox' class='selectcol' weekday='5'></input></th>
                    <th align='left'>Sa<br><input type='checkbox' class='selectcol' weekday='6'></input></th>
                    <th align='left'>Su<br><input type='checkbox' class='selectcol' weekday='0'></input></th>
                    <th align='left'>Price<br>&nbsp;</th>
            <?php
            foreach($itemTypes as $item) {
                echo "<tr itemid='".$item->id."'>";
                echo "<td><input type='checkbox' class='selectrow'> " . $item->name . "</td>";
                echo "<td><input type='checkbox' weekday='1' class='pricecheckbox'></td>";
                echo "<td><input type='checkbox' weekday='2' class='pricecheckbox'></td>";
                echo "<td><input type='checkbox' weekday='3' class='pricecheckbox'></td>";
                echo "<td><input type='checkbox' weekday='4' class='pricecheckbox'></td>";
                echo "<td><input type='checkbox' weekday='5' class='pricecheckbox'></td>";
                echo "<td><input type='checkbox' weekday='6' class='pricecheckbox'></td>";
                echo "<td><input type='checkbox' weekday='0' class='pricecheckbox'></td>";
                echo "<td><input type='txt' class='priceinput priceinputsetter' itemid='".$item->id."'></td>";
                echo "</tr>";
            }
            ?>
                <tr>
                    <td colspan='8'></td>
                    <td>
                        <span class='pmsbutton updatePricingTable'>Update</span>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<br>
<div gstype='form' method='updateProgressivePrices'>
    <?php
    echo "<input type='hidden' gsname='priceType' value='" . $priceObject->defaultPriceType . "'>";
    echo "<h1>Step 3 / 3: Verify the new pricing table</h1>";
    if($priceObject->defaultPriceType == 7 || $priceObject->defaultPriceType == 8) {
        $this->includefile("progressivepricing");
    } else {
        $this->includefile("dailypriceediting");
    }
    ?>
</div>

<div style="border-bottom: solid 1px; margin-bottom: 20px; padding-bottom: 20px;"></div>
<h1>Discount codes</h1>

<?php
$this->includefile("discounts");

if($this->getSelectedPricePlan() != "default") {
    ?>

    <div style="border-bottom: solid 1px; margin-bottom: 20px; padding-bottom: 20px;"></div>
    <h1>Override prices (leave empty to use default prices)</h1>

    <?php
    $this->includefile("addonsprice");
}
?>

<script>
    $('input[gsname="start"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('input[gsname="end"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    app.PmsPricing.loadpriceinput();
</script>