<?
/* @var $this \ns_f52bea98_9616_4b43_bd28_32e62fa95c91\ProductView */
$product = $this->getProduct();
?>


<div gstype='form' method="updateOrder" class="orderview">

    <div class="menuarea">
        <div class="menuentry <? echo $this->isTabActive('details'); ?>" tab='details'><span><? echo $this->__f("Details"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('lists'); ?>" tab='lists'><span><? echo $this->__f("Lists"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('categories'); ?>" tab='categories'><span><? echo $this->__f("Categories"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('variations'); ?>" tab='variations'><span><? echo $this->__f("Variations"); ?></span></div>
    </div>
    <div class="workarea">
        <div class="productinformation <? echo $this->isTabActive('details'); ?>" tab='details'>
            <?
            $this->includefile("details");
            ?>
        </div>

        <div class="productinformation <? echo $this->isTabActive('lists'); ?>" tab='lists'>
            <?
            $this->includefile("lists");
            ?>
        </div>

        <div class="productinformation <? echo $this->isTabActive('categories'); ?>" tab='categories'>
            <?
            $this->includefile("categories");
            ?>
        </div>

        <div class="productinformation <? echo $this->isTabActive('variations'); ?>" tab='variations'>
            <?
            $this->includefile("variations");
            ?>
        </div>
        
        <div class="buttonarea">
            <div class="shop_button" gstype="submit"><? echo $this->__f("Save"); ?></div>
        </div>
    </div>
</div>
