<?php
/* @var $this ns_2e51d163_8ed2_4c9a_a420_02c47b1f7d67\PmsCheckout */
$originalCart = $this->getOriginalCartFromSession();
$currentCart = $this->getCurrentCart();
$items = (array)$originalCart->items;
$start = null;
$end = null;
foreach($items as $item) {
    /* @var $item core_cartmanager_data_CartItem */
    if(!$start || ($item->startDate && strtotime($item->startDate) > $start)) {
        $start = strtotime($item->startDate);
    }
    if(!$end || ($item->endDate && strtotime($item->endDate) > $end)) {
        $end = strtotime($item->endDate);
    }
}
$startDate = "";
if($start) { $startDate = date("d.m.Y", $start); }
$endDate = "";
if($end) { $endDate = date("d.m.Y", $end); }
?>
<div gstype='form' method='filterCartByDate'>
    <label class='cartfilterdate'>
        Start date
        <input type='txt' class='gsniceinput1' id='startdate' gsname='start' value='<?php echo $startDate; ?>'>
    </label>
    <label class='cartfilterdate' style='float:right;text-align:right;'>
        End date
        <input type='txt' class='gsniceinput1 enddate' id='enddate' gsname='end' value='<?php echo $endDate; ?>'>
    </label>
    <div>
        <span class="shop_button" style='width:100%; margin-top: 17px;box-sizing: border-box;' gstype='submit' gs_callback='app.PmsCheckout.reloadCheckoutArea'>Apply dates</span>
    </div>
</div>
<bR>
<style>
    .cartfilterdate { width: 110px; display:inline-block;}
     .cartfilterdate input { width: 70px; }
</style>

<script>
    $('#startdate').datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            var curEnd = moment.utc($('#enddate').val(), "DD.MM.YYYY").local();
            var date = moment.utc(dateText, "DD.MM.YYYY").local();
            
            var diff = curEnd.valueOf() - date.valueOf();
            if(diff < 0) {
                date.add(7, 'days');
                $('#enddate').val(date.format('DD.MM.YYYY')); 
            }
        }
    });
    $('#enddate').datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            var curStart = moment.utc($('#startdate').val(), "DD.MM.YYYY").local();
            var date = moment.utc(dateText, "DD.MM.YYYY").local();
            
            var diff = date.valueOf() - curStart.valueOf();
            if(diff < 0) {
                date.add(-7, 'days');
                $('#startdate').val(date.format('DD.MM.YYYY')); 
            }
        }
    });
</script>