<?/* @var $this ns_2e51d163_8ed2_4c9a_a420_02c47b1f7d67\PmsCheckout */
$item = $this->getCurrentItem();
$i = 0;
$roomNumber = $item->product->additionalMetaData;
$guestName = $item->product->metaData;

$priceMatrix = (array)$item->priceMatrix;
uksort($priceMatrix, array('ns_28886d7d_91d6_409a_a455_9351a426bed5\PmsAvailability','sortByDate'));
if(trim($roomNumber)) {
    $roomNumber = " (" . $roomNumber . ")";
}
foreach ($priceMatrix as $date => $value) {
    $i++;
    $oddClass = $i % 2 ? "even" : "odd";
    ?>
    <div class='entryrow cartitemrow pricematrix_row <? echo $oddClass; ?> '>
        
        <?
        if ($this->isReadOnly()) {
        ?>
            <span><? echo trim($date);?></span>
            <span class='gsniceinput1 matrix_item matrix_price'><? echo $value; ?></span>
        <?
        } else {
        ?>
            <input type='checkbox' checked='true' class='item_checkbox matrix_input gsnicecheckbox1'> 
            <span><? echo trim($date);?></span>
            <input type='textfield' class='gsniceinput1 matrix_item matrix_price' value="<? echo $value; ?>" date="<?php echo $date; ?>">
            <div style="clear:both"></div>
        <?
        }
        ?>
    </div>
    <?
}
?>
