<div class="information">
    <?
    echo $this->__("Contact form configuration");
    ?>
</div>
<div class="setting onoff" id="showcompany">
    <span class="title"><?php echo $this->__("Show company field"); ?></span>
    <div class="onoff config" id="showcompany"></div>
    <div class="description">
        <?php echo $this->__("If this function is enabled, it will show the company field."); ?>
    </div>
</div>
<div class="button savebutton"><div class="rightglare"></div><div class="filler"></div><ins><?php echo $this->__("Save settings"); ?></ins></div>