<?php
/* @var $this \ns_9cea7eba_7807_4e4c_8d60_e7d58fbad13a\PmsGlobalSettings */
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
$user = \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject();
$disableCheckinCheckoutTime = "DISABLED";
if(stristr($user->emailAddress, "@getshop.com")) {
    $disableCheckinCheckoutTime = "";
}
?>
<h1>Global settings</h1>
<div class='settingsform' style='padding-right: 50px;' method='saveSettings' gstype='form'>
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='forceRequiredFieldsForEditors' <?php if($config->forceRequiredFieldsForEditors) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            Force required fields, when an editor / admin registers, does it need to fill in required fields?
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='avoidRandomRoomAssigning' <?php if($config->avoidRandomRoomAssigning) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            Avoid random assigning of room, use sorted list instead.
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='autoDeleteUnpaidBookings' <?php if($config->autoDeleteUnpaidBookings) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            Automatically delete unpaid bookings
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='forceRequiredFieldsForEditors' <?php if($config->forceRequiredFieldsForEditors) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            Make sure the customers agree to the terms and conditions
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='sendToBookerIfGuestIsEmpty' <?php if($config->sendToBookerIfGuestIsEmpty) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            If guest information is missing, send to booker instead
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='automaticallyCheckInOutGuests' <?php if($config->automaticallyCheckInOutGuests) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            Automatically check in guest when code is being sent out.
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='text' class='gsniceinput1' gsname='hourOfDayToStartBoarding' value='<?php echo $config->hourOfDayToStartBoarding; ?>' style='width: 50px; text-align: center;'>
        </span>
        <span class='title'>
            Start boarding at hour of day<br>
            * At what hour of the day would like to grant access to the room if it has been cleaned?
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='text' class='gsniceinput1' gsname='defaultStart' value='<?php echo $config->defaultStart; ?>' style='width: 50px; text-align: center;' <?php echo $disableCheckinCheckoutTime; ?>>
        </span>
        <span class='title'>
            Default start <b>(send an email to post@getshop.com to get this value changed)</b><br>
            * Default check in time.
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='text' class='gsniceinput1' gsname='defaultEnd' value='<?php echo $config->defaultEnd; ?>' style='width: 50px; text-align: center;' <?php echo $disableCheckinCheckoutTime; ?>>
        </span>
        <span class='title'>
            Default end <b>(send an email to post@getshop.com to get this value changed)</b><br>
            * Default check out time.
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='text' class='gsniceinput1' gsname='childMaxAge' value='<?php echo $config->childMaxAge; ?>' style='width: 50px; text-align: center;'>
        </span>
        <span class='title'>
            Children age<br>
            * At what age does a child become an adult?
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <select class='gsniceselect1' gsname="avoidRandomRoomAssigning">
                <option value='false'>Select a random clean room</option>
                <option value='true' <?php if($config->avoidRandomRoomAssigning) { echo "SELECTED"; } ?>>Select a clean room from sorted list</option>
            </select>
        </span>
        <span class='title'>
            Priority on autoassigned rooms<br>
            * The same day of arrival the system will try to automatically give the guest the best selected room, the sorted list is found in the configuration section for the rooms.<br><br>
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='text' class='gsniceinput1' gsname='smsName' value='<?php echo $config->smsName; ?>' style='width: 80px; text-align: center;'>
        </span>
        <span class='title'>
            Sms name<br>
            * Send sms'es from this name/number (max 8 characters).
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <?php
            $defaultLanguage = $config->defaultRegistrationLanguage;
             $states = $this->getFactory()->getLanguageReadable();
             
            echo "<select class='gsniceselect1' gsname='defaultRegistrationLanguage'>";
            echo "<option value=''>Use default language</option>";
             foreach($states as $state => $val) {
                 $selected = $defaultLanguage == $state ? "SELECTED" : "";
                 echo "<option value='$state' $selected>$val</option>";
             }
             echo "</select>";
            ?>
        </span>
        <span class='title'>
            Default registration language<br>
            * The default langauge to use when registering a booking, only used for under "new", when using the booking engine the selected language is used instead.
        </span>
    </div>
    <h1>Booking engine</h1>
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='doNotRecommendBestPrice' <?php if($config->doNotRecommendBestPrice) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            Do not recommend best possible price for the guest, give them a choice to choose themself.
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='ignoreGuestInformation' <?php if($config->ignoreGuestInformation) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            Do not force contact information on all guests.
        </span>
    </div>
    
    <div class='container'>
        <span class='option'>
            <input type='text' class='gsniceinput1' gsname='ignorePaymentWindowDaysAheadOfStay' value='<?php echo $config->ignorePaymentWindowDaysAheadOfStay; ?>' style='width: 50px; text-align: center;'>
        </span>
        <span class='title'>
            If stay is booked number of days before stay, do not show payment window.<br>
            Set to 0 if you always want to display the pay later button.<br/>
            To disable this feature set it to -1
        </span>
    </div>
    
    <h1>Payment and order creation</h1>
    <div class='container'>
        <span class='option'>
            <input type='text' class='gsniceinput1' gsname='numberOfDaysToSendPaymentLinkAheadOfStay' value='<?php echo $config->numberOfDaysToSendPaymentLinkAheadOfStay; ?>' style='width: 50px; text-align: center;'>
        </span>
        <span class='title'>
            Number of days to autosend payment requirements to.<br>
            Automatically send the payment link of type "If order has not been paid" the specified days ahead of the check in date.
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='autoSendPaymentReminder' <?php if($config->autoSendPaymentReminder) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            When payment are missing, automatically send payment link to booker.
        </span>
    </div>
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='autoSendInvoice' <?php if($config->autoSendInvoice) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            Automatically send invoices when they are created.
        </span>
    </div>
    
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='automarkInvoicesAsPaid' <?php if($config->automarkInvoicesAsPaid) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            Automark invoices as paid for.
        </span>
    </div>
    
    <div class='container'>
        <span class='option'>
            <input type='checkbox' gsname='autoSumarizeCartItems' <?php if($config->autoSumarizeCartItems) { echo "CHECKED"; } ?>>
        </span>
        <span class='title'>
            Automatically summarize items in cart when create order (credits and debets).
        </span>
    </div>
    
    <?php
    if($config->wubookAutoCharging) {
    ?>
    <div class='container'>
        <span class='option'>
            <input type='text' class='gsniceinput1' gsname='autochargeCardDaysBefore' value='<?php echo $config->autochargeCardDaysBefore; ?>' style='width: 50px; text-align: center;'>
        </span>
        <span class='title'>
            Number of days to before stay to try to automatically charge card.<br>
            -1 means disabled
        </span>
    </div>
    <?php } ?> 
    
    
    <h1>Enterprise settings</h1>

    <div class='container'>
        <span class='option'>
            <input type='text' class='gsniceinput1' gsname='bookingTag' value='<?php echo $config->bookingTag; ?>' style='width: 250px;'>
        </span>
        <span class='title'>
            Tag your booking system (if you have multiple systems to operate)<br>
            Example: Hotel Amandus
        </span>
    </div>    
    
    <div class='container'>
        <span class='option'>
            <select class="gsniceselect1" gsname="defaultmultilevelname">
                <?
                $selectedName = $this->getSelectedMultilevelDomainName();
                $names = $this->getApi()->getStoreManager()->getMultiLevelNames();
                foreach ($names as $name) {
                    $selected = $selectedName == $name ? "selected='true'" : "";
                    echo "<option $selected value='$name'>$name</option>";
                }
                ?>
            </select>
        </span>
        <span class='title'>
            GetShop supports multiple bookingsengines within the same system.<br>
            This is useful if you for instance have multiple buildings and want to seperate the bookings for each building, but want to have all orders/accounting together<br/>
            <b>Select what domain is the default one</b>
        </span>
        <?php if($this->getUser()->showHiddenFields) { ?>
            <div style='text-align: right;'>
                <input type='button' style='padding: 9px; width:200px; cursor:pointer;' value='Recalculate' gstype='clicksubmitforce' method='correctAllOrders' gs_prompt="Password">
            </div>
        
            <span class='title'>
                Recalculate all orders on the bookings (done if something has been wrong while importing at startup).
            </span>
        
            <div style='text-align: right;'>
                <input type='button' style='padding: 9px; width:200px; cursor:pointer;' value='Reset booking system' gstype='clicksubmitforce' method='clearBookingSystem' gs_prompt="Password">
            </div>
        
            <span class='title'>
            </span>
        <?php
        }
        ?>
    </div>
    
    <div style='text-align: right;'>
        <input type='button' style='padding: 9px; width:200px; cursor:pointer;' value='save' gstype='submit'>
    </div>
 
    <hr>
    <h1>Remote access</h1>
    <div>
        <?
        $tokens = $this->getApi()->getGetShopCentral()->getTokens();

        foreach ($tokens as $token) {
            echo "Name: ".$token->description;
            echo "<br/> Systemid: ".$this->getFactory()->getStore()->id;
            echo "<br/> Secret Key: ".$token->accessToken;
            echo "<hr/>";
            
        }
        ?>
    </div>
    <div gstype='form'method='createNewRemoteAccess'>
        <div class="container">
            <span class="option">
                <input type="text" class="gsniceinput1" gsname="name" value="" placeholder="name" style="width: 250px;">
            </span>
            <span class="title">
                Create new access to remote system.
            </span>
        
            <br/>
            <br/>
            <br/>
            <div style='text-align: right;'>
                <input type='button' style='padding: 9px; width:200px; cursor:pointer;' value='Create new' gstype='submit'>
            </div>
        </div>

    </div>
    <?
    
    ?>
</div>




