<?
/* @var $this ns_f1f2c4f4_fc7d_4bec_89ec_973ff192ff6d\C3RegisterHours */
$accessList = $this->getApi()->getC3Manager()->getAccessList();

$allActivated = $this->getViewMode();

if (!count($accessList)) {
    echo "Beklager, du har ikke tilgang til noen prosjekter enda. Kontakt administrator for tilgang til prosjekter";
    return;
}
$firstProject = $accessList[0];
$firstProject = $this->getApi()->getC3Manager()->getProject($firstProject->projectId);
$projectPeriodeToShow = $firstProject->currentProjectPeriode;

if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->isCompanyOwner) {
?>
    <div class="downloadofreport">
        <div class="viewselector">
            Visningsbilde:
            <div gsclick="setNormalView" class="shop_button <? echo !$allActivated ? 'active' : ''; ?>">Registrering av aktivitet</div>
            <div gsclick="setSummaryView" class="shop_button <? echo $allActivated ? 'active' : ''; ?>">Oversikt pr prosjekt</div>
        </div>
        
        <br/>Last ned SFI Rapport for aktiv periode (<? echo date('d.m.Y', strtotime($projectPeriodeToShow->from))." - ".date('d.m.Y', strtotime($projectPeriodeToShow->to)).")"; ?>
        <br/><div class="shop_button downloadReport" filename="SFIReport.xlsx">Kostnadsspesifikasjon pr WP</div> <div class="shop_button downloadReportTotal" filename="SFIReport.xlsx">Total kostnadsspesifikasjon</div> 
        
        
    </div>
<?
}

foreach ($accessList as $access) {
    $project = $this->getApi()->getC3Manager()->getProject($access->projectId);
    $projectPeriodeToShow = $project->currentProjectPeriode;
    $periodes = $this->getApi()->getC3Manager()->getPeriodesForProject($project->id);
    
    
    echo "<div class='projectoverview'>";
        echo "<h1>$project->projectNumber - $project->name</h1>";
        echo "( Åpen periode: ".date('d.m.Y', strtotime($projectPeriodeToShow->from))." - ".date('d.m.Y', strtotime($projectPeriodeToShow->to)).")";
        echo "<br/>";
        if ($allActivated) {
            $inHours = $this->getApi()->getC3Manager()->getProjectCostsForAllUsersInCompany($project->id, $projectPeriodeToShow->from, $projectPeriodeToShow->to);
            $hours = $this->sortAndGroup($inHours);
        } else {
            $hours = $this->getApi()->getC3Manager()->getProjectCostsForCurrentUser($project->id, $projectPeriodeToShow->from, $projectPeriodeToShow->to);
        }
        
        if ($hours) { 
            
            $totalHours = 0;
            $totalCost = 0;
            $headerComment = $allActivated ? "Bruker" : "Kommentar";
            echo "<div class='hourrow'><span class='editbutton'></span><span class='fromdate'>Fra</span><span class='todate'>Til</span><span class='hour'>Timer/Prosent</span><span class='othercost'>Kr</span><span class='comment'>$headerComment</span></div>";
            
            foreach ($hours as $hour) {
                $name = $allActivated ? $this->getApi()->getUserManager()->getUserById($hour->registeredByUserId)->fullName : "";
                $from = date('d.m.Y', strtotime($hour->from)); 
                $to = date('d.m.Y', strtotime($hour->to));
                
                if ($hour->costType === "userperiode") {
                    $newCost = $this->getApi()->getC3Manager()->calculateSum($hour->id);
                    
                    $editButton = "<span hourid='$hour->id' projectid='$project->id' gs_show_modal='hours' class='gs_shop_small_icon fa fa-edit'></span>";
                    $totalHours += 0;
                    $totalCost += $newCost;
                    $comment = $hour->nfr ? "(NFR)" : "";
                    $comment = $allActivated ? $name : $comment;
                    
                    if ($allActivated)
                        $editButton = "";
                    
                    echo "<div class='hourrow'><span class='editbutton'>$editButton</span><span class='fromdate'>$from</span><span class='todate'>$to</span><span class='hour'>$hour->percent%</span><span class='othercost'>$newCost</span><span class='comment'>$comment</span></div>";
                }
                
                if ($hour->costType === "hour") {
                    $editButton = "<span hourid='$hour->id' projectid='$project->id' gs_show_modal='hours' class='gs_shop_small_icon fa fa-edit'></span>";
                    $totalHours += $hour->hours;
                    $cost = $hour->cost;
                    $totalCost += $cost;
                    
                    $comment = $hour->nfr ? "(NFR)" : "";
                    $comment = $allActivated ? $name : $comment;
                    
                    if ($comment)
                        $comment .= " ";
                    
                    $comment .= "(Rate: ".$hour->rate.")";
                    
                    if ($allActivated)
                        $editButton = "";
                    echo "<div class='hourrow'><span class='editbutton'>$editButton</span><span class='fromdate'>$from</span><span class='todate'>$to</span><span class='hour'>$hour->hours</span><span class='othercost'>$cost</span><span class='comment'>$comment</span></div>";
                }
                
                if ($hour->costType === "other") {
                    $editButton = "<span otherid='$hour->id' projectid='$project->id' gs_show_modal='othercosts' class='gs_shop_small_icon fa fa-edit'></span>";
                    $cost = $hour->cost;
                    $type = $hour->comment;
                    $totalCost += $cost;
                    
                    if ($allActivated)
                        $editButton = "";
                    echo "<div class='hourrow'><span class='editbutton'>$editButton</span><span class='fromdate'>$from</span><span class='todate'>$to</span><span class='hour'></span><span class='othercost'>$cost</span><span class='comment'>$type</span></div>";
                }
            }
            
            echo "<div class='hourrow summary'><span class='editbutton'></span><span class='fromdate'></span><span class='todate'></span><span class='hour'>$totalHours</span><span class='othercost'>$totalCost</span></div>";
        }
        if (!$allActivated) {
            echo "<div class='buttons'>";
                echo "Registrer ny linje: ";
                echo " <div projectid='$project->id' gs_show_modal='hours' class='shop_button'>1.1 Ny timeregistrering</div>";
                echo " <div projectid='$project->id' class='shop_button' gs_show_modal='othercosts'>1.4 Andre kostnader</div>";
            echo "</div>";
        }
    echo "</div>";
}
?>

