<?
/* @var $this ns_f1f2c4f4_fc7d_4bec_89ec_973ff192ff6d\C3RegisterHours */
$accessList = $this->getApi()->getC3Manager()->getAccessList();


if (!count($accessList)) {
    echo "Beklager, du har ikke tilgang til noen prosjekter enda. Kontakt administrator for tilgang til prosjekter";
    return;
}

if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->isCompanyOwner) {
?>
    <div class="downloadofreport">
        Last ned SFI Rapport for nåværende periode
        <br/><div class="shop_button downloadReport" filename="SFIReport.xlsx">Last ned</div> <div class="shop_button downloadReportTotal" filename="SFIReport.xlsx">Last ned kostnadspesifikasjon</div> 
    </div>
<?
}

foreach ($accessList as $access) {
    $project = $this->getApi()->getC3Manager()->getProject($access->projectId);
    $projectPeriodeToShow = $project->currentProjectPeriode;
    $periodes = $this->getApi()->getC3Manager()->getPeriodesForProject($project->id);
    
    echo "<div class='projectoverview'>";
        echo "<h1>$project->projectNumber - $project->name</h1>";
        echo "( Åpen periode: ".date('d.m.Y', strtotime($projectPeriodeToShow->from))." - ".date('d.m.Y', strtotime($projectPeriodeToShow->to)).")";
        echo "<br/>";
        $hours = $this->getApi()->getC3Manager()->getProjectCostsForCurrentUser($project->id, $projectPeriodeToShow->from, $projectPeriodeToShow->to);
        
        if ($hours) {
            $totalHours = 0;
            $totalCost = 0;
            echo "<div class='hourrow'><span class='editbutton'></span><span class='fromdate'>Fra</span><span class='todate'>Til</span><span class='hour'>Timer</span><span class='othercost'>Kr</span><span class='comment'>Kommentar</span></div>";
            
            foreach ($hours as $hour) {
                
                $from = date('d.m.Y', strtotime($hour->from)); 
                $to = date('d.m.Y', strtotime($hour->to));
                
                if ($hour->costType === "userperiode") {
                    $editButton = "<span hourid='$hour->id' projectid='$project->id' gs_show_modal='hours' class='gs_shop_small_icon fa fa-edit'></span>";
                    $totalHours += 0;
                    $totalCost += 0;
                    $comment = $hour->nfr ? "(NFR)" : "";
                    echo "<div class='hourrow'><span class='editbutton'>$editButton</span><span class='fromdate'>$from</span><span class='todate'>$to</span><span class='hour'>Stilling: $hour->percent%</span><span class='othercost'>-</span><span class='comment'>$comment</span></div>";
                }
                
                if ($hour->costType === "hour") {
                    $editButton = "<span hourid='$hour->id' projectid='$project->id' gs_show_modal='hours' class='gs_shop_small_icon fa fa-edit'></span>";
                    $totalHours += $hour->hours;
                    $cost = $hour->cost;
                    $totalCost += $cost;
                    $comment = $hour->nfr ? "(NFR)" : "";
                    echo "<div class='hourrow'><span class='editbutton'>$editButton</span><span class='fromdate'>$from</span><span class='todate'>$to</span><span class='hour'>$hour->hours</span><span class='othercost'>$cost</span><span class='comment'>$comment</span></div>";
                }
                
                if ($hour->costType === "other") {
                    $editButton = "<span otherid='$hour->id' projectid='$project->id' gs_show_modal='othercosts' class='gs_shop_small_icon fa fa-edit'></span>";
                    $cost = $hour->cost;
                    $type = $hour->type;
                    
                    if ($type == "meeting")
                        $type = "(Møte)";
                    
                    if ($type == "travel")
                        $type = "(Reise)";
                    
                    if ($type == "other")
                        $type = "(Annet)";
                    
                    if ($hour->nfr) {
                        $type .= " (NFR)";
                    }
                    if ($hour->comment) {
                        $type .= " - ".$hour->comment;
                    }
                    
                    $totalCost += $cost;
                    echo "<div class='hourrow'><span class='editbutton'>$editButton</span><span class='fromdate'>$from</span><span class='todate'>$to</span><span class='hour'></span><span class='othercost'>$cost</span><span class='comment'>$type</span></div>";
                }
            }
            
            echo "<div class='hourrow summary'><span class='editbutton'></span><span class='fromdate'></span><span class='todate'></span><span class='hour'>$totalHours</span><span class='othercost'>$totalCost</span></div>";
        }
        echo "<div class='buttons'>";
            echo "Registrer ny linje: ";
            echo " <div projectid='$project->id' gs_show_modal='hours' class='shop_button'>1.1 Ny timeregistrering</div>";
            echo " <div projectid='$project->id' class='shop_button' gs_show_modal='othercosts'>1.4 Andre kostnader</div>";
        echo "</div>";
    echo "</div>";
}
?>

