<?php

namespace ns_020b57c2_8f80_46e1_a420_cb163f4fb2d2;

/* @var $this ns_020b57c2_8f80_46e1_a420_cb163f4fb2d2\HotelbookingCleaning */

$rooms = $this->getApi()->getHotelBookingManager()->getAllRooms();
$reservations = $this->getApi()->getHotelBookingManager()->getAllReservations();

$roomlist = array();
foreach ($rooms as $room) {
    $roomlist[$room->id] = $room;
}

echo "<br><br>";
echo "<h1>Guests arriving today</h1>";
printGuestTable($reservations, $roomlist, true);
echo "<br><br>";
echo "<h1>Guests leaving today</h1>";
printGuestTable($reservations, $roomlist, false);
echo "<br><br>";
printCleaningRows($reservations, $roomlist, 5);


function printCleaningRows($reservations, $roomlist, $interval) {
    echo "<h1>Cleaning table</h1>";
    echo "<i class='fa fa-sign-out'></i> leaving the room.<br>";
    echo "<i class='fa fa-refresh'></i> interval cleaning (each 5th day).<br>";
    echo "<br><table width='100%'>";
    echo "<tr>";
    for($i = 0; $i < 7; $i++) {
        echo "<td valign='top'>";
        $day = date(time()+(86400)*$i);
        echo "<b>" . date("d-m-Y", $day) . "</b><br>";
        foreach($reservations as $reservation) {
            $startDate = strtotime($reservation->startDate);
            $endDate = strtotime($reservation->endDate);
            
            if($endDate < date(time()+(86400)*($i-1))) {
                continue;
            }
            if(!$reservation->payedFor) {
                continue;
            }
            
            
            $diff = ceil(($day - $startDate)/86400)-1;
            $doPrint = false;
            $icon = "";
            if($diff % $interval == 0 && $diff != 0) {
                $doPrint = true;
                $icon = "<i class='fa fa-refresh'></i>";
            }
            if(date("y-m-d", $day) == date("y-m-d", $endDate)) {
                $doPrint = true;
                $icon = "<i class='fa fa-sign-out'></i>";
            }
            if(date("y-m-d", $day) == date("y-m-d", $endDate)) {
                $doPrint = true;
                $icon = "<i class='fa fa-sign-out'></i>";
            }

            if($doPrint) {
                foreach($reservation->roomsReserved as $resroom) {
                    echo "$icon <span title='".$resroom->visitors[0]->phone ."'>" . $roomlist[$resroom->roomId]->roomName . " - ".$resroom->visitors[0]->name ."</span><br>";
                }
            }
        }
        echo "</td>";
    }
    echo "</tr>";
    echo "</table>";
}

function printGuestTable($reservations, $roomlist, $arriving) {

    $found = false;
    echo "<div style='background-color:#efefef; width:100%; padding:5px;'>";
    echo "<table width='100%'>";
    echo "<tr>";
    echo "<th align='left' width='10%'>Room</th>";
    echo "<th align='left' width='20%'>Action</th>";
    echo "<th align='left'>Name of guest</th>";
    foreach ($reservations as $reservation) {
        if(!$reservation->payedFor) {
            continue;
        }
            
        
        if ($arriving) {
            $startdate = strtotime($reservation->startDate);
        } else {
            $startdate = strtotime($reservation->endDate);
        }
        if (date("Ymd", time()) == date("Ymd", $startdate)) {
            $found = true;
            echo "<tr>";
            echo "<td valign='top' width='150'>";
            foreach ($reservation->roomsReserved as $reservedRoom) {
                echo "<div style='line-height: 20px;'>" . $roomlist[$reservedRoom->roomId]->roomName . "</div>";
            }
            echo "</td>";
            echo "<td>";
            foreach ($reservation->roomsReserved as $reservedRoom) {
                if ($roomlist[$reservedRoom->roomId]->isClean || (isset($reservation->isApprovedForCheckIn->{$reservedRoom->roomId}) && $reservation->isApprovedForCheckIn->{$reservedRoom->roomId} && $arriving)) {
                    echo "<span style='line-height: 20px;' class='alreadyready'>room is marked as ready</span>";
                } else {
                    echo "<span style='line-height: 20px;' class='markroomasready' roomId='" . $reservedRoom->roomId . "'>Mark room as ready</span>";
                }
                echo "<br>";
            }
            echo "</td>";
            echo "<td valign='top'>";
            foreach ($reservation->roomsReserved as $reservedRoom) {
                echo "<div style='line-height: 20px;'>" . $reservedRoom->visitors[0]->name . "</div>";
            }
            echo "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";

    if (!$found) {
        echo "<span style='padding:5px;'>No guests for today.</span>";
    }
    echo "</div>";
}

function printIntervalCleaning($reservations, $roomlist, $scope) {
    /* @var $api2 GetShopApi */

    $result = array();
    foreach ($reservations as $reservation) {
        /* @var $order \core_ordermanager_data_Order */
        $order = $scope->getApi()->getOrderManager()->getOrderByReference($reservation->bookingReference);
        if (isset($order->cart->items)) {
            foreach ($order->cart->items as $item) {
                /* @var $item \core_cartmanager_data_CartItem */
                /* @var $product \core_productmanager_data_Product */
                if ($item->product->sku === "vask") {
                    $result[$item->product->name][] = $reservation;
                }
            }
        }
    }

    foreach ($result as $index => $cleaningarray) {
        echo "<br><br>";
        echo "<h1>" . $index . "</h1>";
        echo "<div style='background-color:#efefef; width:100%; padding:5px;'>";
        echo "<table width='100%'>";
        echo "<tr>";
        echo "<th align='left' width='10%'>Room</th>";
        echo "<th align='left' width='20%'>Action</th>";
        echo "<th align='left'>Name of guest</th>";
        echo "<th align='left'>Check in date</th>";
        echo "<th align='left'>Check out date</th>";
        
        foreach ($cleaningarray as $reservation) {
            echo "<tr>";
            echo "<td valign='top' width='150'>";
            foreach ($reservation->roomIds as $roomId) {
                echo "<div style='line-height: 20px;'>" . $roomlist[$roomId]->roomName . "</div>";
            }
            echo "</td>";
            echo "<td>";
            foreach ($reservation->roomIds as $roomId) {
                if ($roomlist[$roomId]->isClean || (isset($reservation->isApprovedForCheckIn->{$roomId}) && $reservation->isApprovedForCheckIn->{$roomId} && $arriving)) {
                    echo "<span style='line-height: 20px;' class='alreadyready'>room is already ready</span>";
                } else {
                    echo "<span style='line-height: 20px;' class='markroomasready' roomId='" . $roomId . "'>Mark room as ready</span>";
                }
                echo "<br>";
            }
            echo "</td>";
            echo "<td valign='top'>";
            foreach ($reservation->contact->names as $contact) {
                echo "<div style='line-height: 20px;'>" . $contact . "</div>";
            }
            echo "</td>";
            echo "<td>" . $reservation->startDate . "</td>";
            echo "<td>" . $reservation->endDate . "</td>";
            echo "</tr>";
        }
        echo "</table>";
        echo "</div>";
    }
}
?>
<br><br><br>
