<?php

namespace ns_020b57c2_8f80_46e1_a420_cb163f4fb2d2;

/* @var $this ns_020b57c2_8f80_46e1_a420_cb163f4fb2d2\HotelbookingCleaning */

/* @var $api \GetShopApi */
$api = $this->getApi();
$rooms = $this->getApi()->getHotelBookingManager()->getAllRooms();
$reservations = $this->getApi()->getHotelBookingManager()->getAllActiveUserBookings();
$orders = $api->getOrderManager()->getAllOrdersOnProduct("8dd279a2-4949-45ce-83c5-1d329f938179");
if(!$orders) {
    $orders = array();
}
$roomlist = array();
foreach ($rooms as $room) {
    $roomlist[$room->id] = $room;
}


echo "<br><br>";
echo "<h1>Guests arriving today</h1>";
printGuestTable($reservations, $roomlist, true,0);
echo "<br><br>";
echo "<h1>Guests leaving today</h1>";
printGuestTable($reservations, $roomlist, false,0);
echo "<br><br>";
printCleaningRows($reservations, $roomlist, 5, $orders, $api);

function printCleaningRows($bookingData, $roomlist, $interval, $orders, $api) {
    echo "<h1>Cleaning table</h1>";
    echo "<i class='fa fa-sign-out'></i> leaving the room.<br>";
    echo "<i class='fa fa-refresh'></i> interval cleaning (each 5th day).<br>";
    echo "<i class='fa fa-plus-circle'></i> Extra cleaning.<br>";
    echo "<br><table width='100%'>";
    echo "<tr>";
    for ($i = 0; $i < 7; $i++) {
        echo "<td valign='top'>";
        $day = date(time() + (86400) * $i);
        echo "<b>" . date("d-m-Y", $day) . "</b><br>";
        foreach ($orders as $order) {
            if ($order->status != 7) {
                continue;
            }
            
            /* @var $order \ns_def1e922_972f_4557_a315_a751a9b9eff1\Order */
            $date = strtotime($order->createdDate);
            $hour = (int) date("H", $date);
            $printCleaning = false;
            $room = $order->cart->items[0]->product->metaData;
            $name = $api->getUserManager()->getUserById($order->userId)->fullName;
            if ($hour < 12 && date("y-m-d", $date + 86400) == date("y-m-d", $day)) {
                $printCleaning = true;
            }
            if ($hour > 12 && date("y-m-d", $date + (86400 * 2)) == date("y-m-d", $day)) {
                $printCleaning = true;
            }
            if ($printCleaning) {
                echo "<i class='fa fa-plus-circle'></i> $room - $name<br>";
            }
        }
        foreach ($bookingData as $bdata) {
            foreach ($bdata->references as $reservation) {
                $startDate = strtotime($reservation->startDate);
                $endDate = strtotime($reservation->endDate);
                
                //If reservation is in the future, and not this today.
                if(($startDate > $day) && (date("y-m-d", $day) != date("y-m-d", $startDate))) {
                    continue;
                }
                
                //If reservation has been, and not this today.
                if(($endDate < $day) && (date("y-m-d", $day) != date("y-m-d", $endDate))) {
                    continue;
                }
                
                $diff = ceil(($day - $startDate) / 86400);
                $doPrint = false;
                $icon = "";
                if ($diff % $interval == 0 && $diff != 0) {
                    $doPrint = true;
                    $icon = "<i class='fa fa-refresh'></i>";
                }
                if (date("y-m-d", $day) == date("y-m-d", $endDate)) {
                    $doPrint = true;
                    $icon = "<i class='fa fa-sign-out'></i>";
                }

                if ($doPrint) {
                    foreach ($reservation->roomsReserved as $resroom) {
                        echo "$icon <span title='" . $resroom->visitors[0]->phone . "'>" . $roomlist[$resroom->roomId]->roomName . " - " . $resroom->visitors[0]->name . "</span><br>";
                    }
                }
            }
        }
        echo "</td>";
    }
    echo "</tr>";
    echo "</table>";
}

function printGuestTable($bookingData, $roomlist, $arriving, $datediff) {

    $found = false;
    echo "<div style='background-color:#efefef; width:100%; padding:5px;'>";
    echo "<table width='100%'>";
    echo "<tr>";
    echo "<th align='left' width='10%'>Room</th>";
    echo "<th align='left' width='20%'>Action</th>";
    echo "<th align='left'>Name of guest</th>";
    foreach ($bookingData as $bdata) {
        foreach ($bdata->references as $reservation) {
            if ($arriving) {
                $startdate = strtotime($reservation->startDate);
            } else {
                $startdate = strtotime($reservation->endDate);
            }
            if (date("Ymd", time()+$datediff) == date("Ymd", $startdate)) {
                $found = true;
                echo "<tr>";
                echo "<td valign='top' width='150'>";
                foreach ($reservation->roomsReserved as $reservedRoom) {
                    echo "<div style='line-height: 20px;'>" . $roomlist[$reservedRoom->roomId]->roomName . "</div>";
                }
                echo "</td>";
                echo "<td>";
                foreach ($reservation->roomsReserved as $reservedRoom) {
                    if (!$roomlist[$reservedRoom->roomId]->needCleaning) {
                        echo "<span style='line-height: 20px;' class='alreadyready'>room is marked as ready</span>";
                    } else {
                        echo "<span style='line-height: 20px;' class='markroomasready' roomId='" . $reservedRoom->roomId . "'>Mark room as ready</span>";
                    }
                    echo "<br>";
                }
                echo "</td>";
                echo "<td valign='top'>";
                foreach ($reservation->roomsReserved as $reservedRoom) {
                    echo "<div style='line-height: 20px;'>" . $reservedRoom->visitors[0]->name . "</div>";
                }
                echo "</td>";
                echo "</tr>";
            }
        }
    }
    echo "</table>";

    if (!$found) {
        echo "<span style='padding:5px;'>No guests for today.</span>";
    }
    echo "</div>";
}

function printIntervalCleaning($reservations, $roomlist, $scope) {
    /* @var $api2 GetShopApi */

    $result = array();
    foreach ($reservations as $reservation) {
        /* @var $order \core_ordermanager_data_Order */
        $order = $scope->getApi()->getOrderManager()->getOrderByReference($reservation->bookingReference);
        if (isset($order->cart->items)) {
            foreach ($order->cart->items as $item) {
                /* @var $item \core_cartmanager_data_CartItem */
                /* @var $product \core_productmanager_data_Product */
                if ($item->product->sku === "vask") {
                    $result[$item->product->name][] = $reservation;
                }
            }
        }
    }

    foreach ($result as $index => $cleaningarray) {
        echo "<br><br>";
        echo "<h1>" . $index . "</h1>";
        echo "<div style='background-color:#efefef; width:100%; padding:5px;'>";
        echo "<table width='100%'>";
        echo "<tr>";
        echo "<th align='left' width='10%'>Room</th>";
        echo "<th align='left' width='20%'>Action</th>";
        echo "<th align='left'>Name of guest</th>";
        echo "<th align='left'>Check in date</th>";
        echo "<th align='left'>Check out date</th>";

        foreach ($cleaningarray as $reservation) {
            echo "<tr>";
            echo "<td valign='top' width='150'>";
            foreach ($reservation->roomIds as $roomId) {
                echo "<div style='line-height: 20px;'>" . $roomlist[$roomId]->roomName . "</div>";
            }
            echo "</td>";
            echo "<td>";
            foreach ($reservation->roomIds as $roomId) {
                if (!$roomlist[$roomId]->needCleaning) {
                    echo "<span style='line-height: 20px;' class='alreadyready'>room is already ready</span>";
                } else {
                    echo "<span style='line-height: 20px;' class='markroomasready' roomId='" . $roomId . "'>Mark room as ready</span>";
                }
                echo "<br>";
            }
            echo "</td>";
            echo "<td valign='top'>";
            foreach ($reservation->contact->names as $contact) {
                echo "<div style='line-height: 20px;'>" . $contact . "</div>";
            }
            echo "</td>";
            echo "<td>" . $reservation->startDate . "</td>";
            echo "<td>" . $reservation->endDate . "</td>";
            echo "</tr>";
        }
        echo "</table>";
        echo "</div>";
    }
}
?>
<br>

<h1>Total room overview</h1>
Click on the room you want to mark as ready
<style>
    .room_not_clean { color:red !important; }
    .room_clean { color:green !important; }
</style>

<?
echo "<table>";
echo "<tr>";
foreach($roomlist as $room) {
    if($room->roomName == "201" || $room->roomName == "301") {
        echo "</tr><tr>";
    }
    
    $cleaned = "room_not_clean";
    if($room->isClean) {
        $cleaned = "room_clean";
    } 
    
    echo "<td style='font-size: 20px;padding: 7px;cursor:pointer;' class='$cleaned markroomasready' roomId='".$room->id."'>" . $room->roomName . "</td>";
}
echo "</tr></table>";
echo "<br><br>";
echo "<h1>Guests arriving tomorrow</h1>";
printGuestTable($reservations, $roomlist, true,86400);


?>
<br><br><br>
