<h1>Privacy Policy</h1>
<div>
    We need to collect privacy data of the subject or subjects that are staying at us. 
    This article aims to give you the idea of what your personal data is used for and what personal data we collect
</div>
<h2>What personal data do we collect</h2>
<div>
    We only collect the minimum amount of personal data in order for us to process your stay at us.
    <ul>
        <li>Name</li>
        <li>Email</li>
        <li>Address</li>
        <li>Nationallity</li>
        <li>Phonenumber</li>
    </ul>
</div>
<h2>Lawful basis</h2>
<div>
    In order to process personal data we need a lawful basis. We do have lawful basis based upon GDPR Art 6.1(b) and Art 6.1(f).
    
    <br/>
    <br/><b>6.1(b) Processing is necessary for the performance of a contract</b>
    <br/> When you as a guest stay at us we need the data in order to comply with other laws and used for communication purposes with you. 
    We consider the contract to start when you make an reservation and ends when you checkout. The personal data within this scope will be used for the following.
    <br/> 
    <ul>
        <li>Communication purposes</li>
        <li>Stay History </li>
        <li>Cleaning history</li>
        <li>Fire and crime safety</li>
    </ul>
    <br/><b>6.1 (f) Legitimate Instrests</b>
    <br/>
    <br/> We and you have legitimate interest in processing data in order to accomplish the following
    <br/>
    <ul>
        <li>Keep history of guests records to prevent crime at our hotel</li>
        <li>Laws forcing us to keep records for all accounting transactions</li>
        <li>To serve you as a guest at the best possible way</li>
    </ul>
    <br/> We will not use your personal data to marketing and we will not share the data with other then parties listed below. Personal data that has a high risk of identity thefts will be obfuscated as soon as there no need for processing.
</div>
<h2>Who do we share data with?</h2>
<div>
    Your personal data is shared only with compliant companies according to GDPR. In order for the hotel to operate properly we are sharing your data with the following parties.
    <ul>
        <li>SMS Providers</li>
        <li>Email Providers</li>
        <li>Accounting Systems</li>
        <li>GetShop Systems</li>
    </ul>
</div>
<h2>How do we collect data?</h2>
<div>
    We collect  your personal data trough phone calls, emails, bookingform at our webpage, OTA (Online Travel Agency) or GDS (Global Distribution System).
</div>
<h2>Insight to your data and opt-out.</h2>
<div>
    We have no problem giving you insight to what personal data we have about you, just contact us and we will provide you with the information. You also have the right to opt-out/be forgotten unless other laws prevent us for doing so.
</div>