<h2>Hvor fikk du først vite om varen?</h2>
<div method="saveform" gstype="form">
    <label><input type="radio" name="knowabout" gsname="facebook" value="1">Facebook</label><br>
    <label><input type="radio" name="knowabout" gsname="google" value="1">Google</label><br>
    <label><input type="radio" name="knowabout" gsname="twitter" value="1">Twitter</label><br>
    <label><input type="radio" name="knowabout" gsname="annet" value="1">Annet</label><br>

    <h2>Har du andre kommentarer / forbedringer</h2>
    <textarea style="width:100%; height: 100px;" gsname="comment"></textarea>
    <input type="button" value="Send inn ditt svar" style="width:100%;" gstype="submit">
</div>