<?
/* @var $this ns_009cd387_0ca4_4b05_98b4_d6dae4ad6a4a\ProMeisterMandatoryTestList */

$courses = $this->getApi()->getEventBookingManager()->getMandatoryCourses("booking", $this->getCurrentUser()->id);
?>
<div class="gss_overrideapp" gss_use_app_id="009cd387-0ca4-4b05-98b4-d6dae4ad6a4a">
    <input type="hidden" gs_model="mandatorycourses" gs_model_attr="userid" value="<? echo $this->getCurrentUser()->id; ?>"/>
    
    <center>Set forced participated to a course for this user</center>
    
    <?
    foreach ($courses as $course) {
    ?>
        <div class="textfield gss_setting">
            <span class="title"><? echo $course->name; ?></span>
            <div class="gss_onoff" gs_model="mandatorycourses" gs_model_attr="course_<? echo $course->id; ?>">
                <?
                $faclass = $this->getApi()->getEventBookingManager()->hasForcedMandatoryTest("booking", $course->id, $this->getCurrentUser()->id) ? "fa-toggle-on" : "fa-toggle-off";;
                ?>
                Off<i class="fa <? echo $faclass; ?> "></i>On
            </div>
            <div class="description"></div>
        </div>
    <?
    }
    ?>
    
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveMandatoryCoursesForUser" gss_model="mandatorycourses" gss_success_message="Updated"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>
</div>