<?
/* @var $this \ns_4a4d17cc_7691_4851_998a_10fae57efcee\C3Hour */
$projectId = $this->getModalVariable("projectid");
$user = ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject();
$groupInfo = $this->getApi()->getC3Manager()->getGroupInformation($user->companyObject->groupId);

$forskningsperiode = $this->getApi()->getC3Manager()->getCurrentForskningsPeriode();

$projectAccess = $this->getApi()->getC3Manager()->getAccessListByProjectId($projectId);

$hourObject = null;
$percentUsing = false;

if ($this->getModalVariable("hourid")) {
    $hourObject = $this->getApi()->getC3Manager()->getHourById($this->getModalVariable("hourid"));
}

if ($this->getModalVariable("hourid") && $hourObject == null) {
    $hourObject = $this->getApi()->getC3Manager()->getUserProjectPeriodeById($this->getModalVariable("hourid"));
    if ($hourObject) {
        $percentUsing = true;
    }
}

$from = $hourObject ? date('d.m.Y', strtotime($hourObject->from)) : "";
$to = $hourObject ? date('d.m.Y', strtotime($hourObject->to)) : "";
$hours = $hourObject && isset($hourObject->hours) ? $hourObject->hours : "";
$percent = $hourObject && isset($hourObject->percent) ? $hourObject->percent : "";
$project = $this->getApi()->getC3Manager()->getProject($projectId);
$projectPeriodeToShow = $project->currentProjectPeriode;


if (!$from && isset($_SESSION['scope_C3Registration_last_from'])) {
    $from = $_SESSION['scope_C3Registration_last_from'];
}

if (!$to && isset($_SESSION['scope_C3Registration_last_to'])) {
    $to = $_SESSION['scope_C3Registration_last_to'];
}

$costId = $hourObject ? $hourObject->id : "";
?>

<?
if ($forskningsperiode) {
?>



<div class='tabheader'>
    <div content='timer' class='tab active'>Timer</div>
    <div content='prosent' class='tab'>Prosent</div>
</div>



<div gstype='form' method='savePercent' content='prosent' class='tabcontent'>
    <div class="periodeopen">
        <?
        echo "<b>Prosjekt:</b> ".$project->name;
        echo "<br/><b>Åpen periode:</b> ".date('d.m.Y', strtotime($projectPeriodeToShow->from))." - ".date('d.m.Y', strtotime($projectPeriodeToShow->to));
        ?>
    </div>

    <div>
        Det er lagt inn en <? echo $forskningsperiode->percents; ?>% stilling for perioden: <? echo date('m.d.Y', strtotime($forskningsperiode->start)) . "-" . date('m.d.Y', strtotime($forskningsperiode->end)); ?>
    </div>
    
    <br/> Periode
    <div class='gserrorfield' id='errorMessage'></div>
    <br/><input class='gsniceinput1' type='text' gsname='from' id='from' value='<? echo $from; ?>'/> - <input class='gsniceinput1' type='text' gsname='to' id='to' value='<? echo $to; ?>'/> 
    <br/>
    <br/> Hvor mange prosent av denne stillingen brukte du på dette prosjektet ?<br/>(100% = hele stillingen gått til dette prosjektet)
    <br/>
    <div class='gserrorfield' id='errorMessageTimer'></div>
    <br/>
    <input class='gsniceinput1 timehours' type='text' gsname='hours' value='<? echo $percent; ?>'/>%
    
    <?
    
    if ($this->getApi()->getC3Manager()->allowedNfrHourCurrentUser()) {
        echo "<br/>";
        echo "<br/>";
        echo "<input type='checkbox' gsname='nfr'/> Er dette forskningsrådets midler?";
        echo "<br/>";
    }
    
    ?>
    
    <br/> <div class='shop_button' gsclick='deleteCost' costId='<? echo $costId; ?>'> Slett oppføring </div>
    <div class='shop_button' gstype='submit'> Lagre </div>
</div>

<? } ?>


<div gstype='form' method='saveHours' content='timer' class='tabcontent'>
    <div class="periodeopen">
        <?
        echo "<b>Prosjekt:</b> ".$project->name;
        echo "<br/><b>Åpen periode:</b> ".date('d.m.Y', strtotime($projectPeriodeToShow->from))." - ".date('d.m.Y', strtotime($projectPeriodeToShow->to));
        ?>
    </div>


    Periode:
    <div class='gserrorfield' id='errorMessage'></div>
    <br/><input class='gsniceinput1' type='text' gsname='from' id='from' value='<? echo $from; ?>'/> - <input class='gsniceinput1' type='text' gsname='to' id='to' value='<? echo $to; ?>'/> 
    <br/>
    <br/>Timer:
    <br/>
    <div class='gserrorfield' id='errorMessageTimer'></div>
    <input class='gsniceinput1 timehours' type='text' gsname='hours' value='<? echo $hours; ?>'/> x 
    <select class='gsniceselect1 hourrate' gsname='rate'>
        <?
        $rates = $this->getApi()->getC3Manager()->getTimeRates();
        $hourRate = $this->getApi()->getC3Manager()->getTimeRate(\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->id);
        foreach ($rates as $rate) {
            $selected = $rate->id == $hourRate->id ? "selected='true'" : "";
            echo "<option $selected value='$rate->id' rate='$rate->rate'>$rate->name ($rate->rate)</option>";
        }
        ?>
    </select>
    = <span class='sum'></span>
    <br/>
    <?
    
    if ($this->getApi()->getC3Manager()->allowedNfrHourCurrentUser()) {
        echo "<br/>";
        echo "<input type='checkbox' gsname='nfr'/> Er dette forskningsrådets midler?";
        echo "<br/>";
    }
    
    ?>
    <br/> 
    <? if ($costId) { ?>
        <div class='shop_button' gsclick='deleteCost' costId='<? echo $costId; ?>'> Slett oppføring </div>
    <? } ?>
    <div class='shop_button' gstype='submit'> Lagre </div>
</div>

<script>
    $('#from').datepicker({dateFormat: "dd.mm.yy"});
    $('#to').datepicker({dateFormat: "dd.mm.yy"});
    <? if ($percentUsing) { ?>
        $(".tab[content='prosent']").click();
        $(".tab[content='timer']").hide();
    <? } else {
        if ($hourObject) {
            ?>
            $(".tab[content='timer']").click();
            $(".tab[content='prosent']").hide();    
            <?
        } else {
        ?>
            $(".tab[content='timer']").click();
            
    <? 
        }
    } ?>
    
</script>