<?
/* @var $this ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2\Hotelbooking */
$this->loadBookingData();
?>

<br>
<div class="bookingsummary" gstype="form"  method="validateAndContinueToPayment">
    <div class="summaryview">
            <div class='summary_heading'><? echo $this->__w("Summary"); ?></div>
            <div class='price_row'>
                <? echo $this->__w("Booked time periode"); ?>
                <span class='right_aligned_price'><? echo date("d. M Y", $this->getStart()) . " " . $this->__w("to") . " " . date("d. M Y", $this->getEnd()); ?></span>
            </div>

            <?
            $total = 0;
            if($this->getCleaningOption()) {
                $cleaningproduct = $this->getApi()->getProductManager()->getProduct($this->getCleaningOption());
                $count = (int)($this->getDayCount() / $cleaningproduct->stockQuantity);
                echo $count . " stk " . strtolower($cleaningproduct->name) . " " . $cleaningproduct->price . "kr/" . $this->__w("each cleaning");
                echo "<span class='right_aligned_price'>" . $this->getCleaningPrice() . " kr</span>";
            }

            echo "<div class='price_row'>";
            $night = $this->__w("nights");
            if($this->getDayCount() == 1) {
                $night = $this->__w("night");
            }
            $in = $this->__w("in");
            
            echo "<span class='price_summary'>" . $this->getDayCount() . " $night $in " .$this->getRoomCount() . " " . $this->getProduct()->name  . " (" . $this->getProduct()->price . "/night)" . "</span>";
            echo "<span class='price_summary_price price_row'><span class='right_aligned_price'>" . $this->getRoomPrice() . " kr</span></span>";
            echo "</div>";

            $totalprice = $this->getDayCount() * $this->getProduct()->price * $this->getRoomCount();
            echo "<div class='summary_total'>";
            echo "<div class='price_summary'>" . $this->__w("Total price")."<span class='right_aligned_price'>". $this->getTotal() . " kr" ."</span></div>";
            echo "</div>";
            ?>
        </div>
    <div class="booking_contact_data">
        <div class='summary_heading'><? echo $this->__w("Visitor information"); ?></div>
        <?
            for($i = 1; $i <= $this->getPersonCount(); $i++) {
                if($this->getPersonCount() > 1) {
                    $var = $this->__w("Visitor no {count}");
                    $var = str_replace("{count}", $i, $var);
                    echo "<br><div class='visitor_heading'>$var</div>";
                }
                ?>
                <div class='contact_entry'>
                    <span class='contact_text'><? echo $this->__w("Name"); ?></span>
                    <span class='contact_input'><input type='text' gsname='name_<? echo $i; ?>' value='<? echo $this->getPost("name_$i"); ?>' class='<? echo $this->validateInput("name_$i"); ?>'></span>
                </div>
                <div class='contact_entry'>
                    <span class='contact_text'><? echo $this->__w("Phone"); ?></span>
                    <span class='contact_input'><input type='text' gsname='phone_<? echo $i; ?>' value='<? echo $this->getPost("phone_$i"); ?>'  class='<? echo $this->validateInput("phone_$i"); ?>'></span>
                </div>
                <?
            }
        ?>
        <br>
        <br>
        <div class="summary_heading">
            <? echo $this->__w("Additional contact data"); ?>
        </div>
        <div class='contact_entry'>
            <span class='contact_text'><? echo $this->__w("I have a partnership deal"); ?></span>
            <span class='contact_input'><input type='checkbox' gsname="partnershipdeal" <? if($this->partnerShipChecked()) { echo "checked"; } ?>></span>
        </div>
        <div class='contact_entry partnership common_input' <? if(!$this->partnerShipChecked()) { echo "style='display:none;'"; } ?>>
            <span class='contact_text'><? echo $this->__w("Reference number"); ?></span>
            <span class='contact_input'><input type='text' gsname="referencenumber" value='<? echo $this->getPost("referencenumber"); ?>' class='<? echo $this->validateInput("referencenumber"); ?>'></span>
            <div><? echo $this->__w("Please enter the reference number provided by Wilhelmsen House"); ?></div>
            <div class="continue_to_cart_button" gstype="submit"><? echo $this->__w("Complete the order"); ?></div>
        </div>
        <div class="common_input" <? if($this->partnerShipChecked()) { echo "style='display:none;'"; } ?>>
            <div class='contact_entry'>
                <span class='contact_text'><? echo $this->__w("Address"); ?></span>
                <span class='contact_input'><input type='text' gsname="address" value='<? echo $this->getPost("address"); ?>' class='<? echo $this->validateInput("address"); ?>'></span>
            </div>
            <div class='contact_entry'>
                <span class='contact_text'><? echo $this->__w("Postal code"); ?></span>
                <span class='contact_input'><input type='text' gsname='postal_code' value='<? echo $this->getPost("postal_code"); ?>' class='<? echo $this->validateInput("postal_code"); ?>'></span>
            </div>
            <div class='contact_entry'>
                <span class='contact_text'><? echo $this->__w("City"); ?></span>
                <span class='contact_input'><input type='text' gsname='city' value='<? echo $this->getPost("city"); ?>' class='<? echo $this->validateInput("city"); ?>'></span>
            </div>
            <div class='contact_entry'>
                <span class='contact_text'><? echo $this->__w("Email"); ?></span>
                <span class='contact_input'><input type='text' gsname='email' value='<? echo $this->getPost("email"); ?>' class='<? echo $this->validateInput("email"); ?>'></span>
            </div>
            <?
            if($this->hasErrors()) { 
                echo "<div>";
                echo $this->__w("All fields are required, please fill in the fields in red.");
                echo "</div>";
            }

            if($this->checkFailedReservation()) { 
                echo $this->__w("Failed to reserve room... please contact us.");
            } else {        ?>
                <div class="continue_to_cart_button common_input" gstype="submit"><? echo $this->__w("Continue to payment"); ?></div>
            <? } ?>
        </div>
    </div>
        
    <div style='clear:both;'></div>
    <br>
    <br>
    <br>    
</div>