<?
/* @var $this ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2\Hotelbooking */
$this->loadBookingData();
$continueCartButtonText = $this->__w("Continue to payment");
$roomTaxPrice = $this->__w("{percentage}% taxes on room");
$cleaningTaxPrice = $this->__w("{percentage}% taxes on cleaning");
$periode = $this->__w("night");
?>

<br>
<div class="bookingsummary" gstype="form"  method="completeRegularCheckout">
    <? $this->includefile("pricesummary"); ?>
    <div class="booking_contact_data">
        <?
        if($this->partnerShipChecked()) {
            $bookdata = $this->getBookingData();
            $partnertype = "";
            if(isset($bookdata['partner_type'])) {
                $partnertype = $bookdata['partner_type'];
            }
            ?>
        <bR><br>
            <h1><? echo $this->__w("PARTNERSHIP CODE"); ?></h1><div class="seperator"></div>
            
            <div>
                <label>
                    <input type='radio' gsname='partner_type' name='partner_type' value='existing' <? if($partnertype == "existing") { echo "CHECKED"; } ?>><? echo $this->__w("I have a partnership code"); ?>
                </label>
                <label>
                    <input type='radio' gsname='partner_type' name='partner_type' value='new' <? if($partnertype == "new") { echo "CHECKED"; } ?>><? echo $this->__w("I want to become a partnership member"); ?>
                </label>
            </div>
            <br>
            
            <? 
            if($partnertype == "existing") {
            ?>
                <div class="col-33">
                    <span class="contact_text"><? echo $this->__w("Enter your reference number"); ?></span>
                    <span class="contact_input"><input type="text" gsname="referenceNumber" value="<? echo $this->getPost("referenceNumber"); ?>" class="<? echo $this->validateInput("referenceNumber"); ?>"></span>

                    <?
                    if($this->validateInput("referenceNumber")) {
                        echo "* " . $this->__w("Your reference number is not correct.");
                    }
                    ?>
                </div>
            <? } ?>
            <br>
            <?
            if($partnertype == "new") {
                $this->includefile("bookingadditionalinfo");
            }
        } else {
            $partnertype = "regular_customer";
        }
        
        if($partnertype) {
            $this->includefile("visitorinformation");
            if(!$this->partnerShipChecked()) {
                ?>
                <div class="summary_heading">
                    <div class="spacer"></div>
                    <h1>
                        <? echo $this->__w("Additional contact data"); ?>
                    </h1>
                    <div class="seperator"></div>
                </div>
                <?
                $this->includefile("bookingadditionalinfo");
            }

            if ($this->hasErrors()) {
                echo "<div>";
                echo $this->__w("All fields are required, please fill in the fields in red.");
                foreach ($this->errors as $error) {
                    echo "<div>" . $error . "</div>";
                }
                echo "</div>";
            }

            if ($this->checkFailedReservation()) {
                echo $this->__w("Failed to reserve room... please contact us.");
            } else {
                ?>
                <div style="text-align:right;">
                    <?
                    if(!$this->partnerShipChecked()) {
                        echo '<div class="continue_to_cart_button common_input" gstype="submit">'.$continueCartButtonText.'</div>';
                    } else {
                        echo '<div class="complete_partner_checkout">'.$this->__w("Complete").'</div>';
                    }
                    ?>
                </div>
            <? } ?>
        <? } ?>
    </div>
</div>
<div style='clear:both;'></div>
