<? /* @var $this \ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2\Hotelbooking */ ?>
<div class="summary_heading">
    <div class="spacer"></div>
    <h1>
        <? echo $this->__w("Invoice information"); ?>
    </h1>
    <div class="seperator"></div>
</div>

<div style="padding-bottom:10px;">
    <input type="radio" name="customer_type" gsname="userData][customer_type]" value="private" <? if ($this->getCustomerType() == "private") echo "CHECKED"; ?>> Privatperson
    <input type="radio" name="customer_type" gsname="userData][customer_type]" value="company" <? if ($this->getCustomerType() == "company") echo "CHECKED"; ?>> Firma
    <input type="radio" name="customer_type" gsname="userData][customer_type]" value="existing" <? if ($this->getCustomerType() == "existing") echo "CHECKED"; ?>> Eksisterende kunde
</div>
<div class="common_input">
    <?
    if ($this->getCustomerType() == "existing") {
        if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
            $allUsers = $this->getApi()->getUserManager()->getAllUsers();
            echo "<select class='existinguserid'>";
            echo "<option value=''>Select a user</option>";
            foreach ($allUsers as $user) {
                $SELECTED = "";
                if($this->getPost("username") == $user->id) {
                    $SELECTED = "SELECTED";
                }
                echo "<option value='" . $user->id . "' $SELECTED>" . $user->fullName . "</option>";
            }
            echo "</select>";
        } else {
            ?>
            <div class='col-50'>
            <? echo $this->__w("Email") . " (<a href=''>glemt passord</a>)"; ?>
            <span class='contact_input'><input type='text' gsname="userData][username]" value='<? echo $this->getPost("username"); ?>' class='<? echo $this->validateInput("username"); ?>'></span>
            <?
            if ($this->validateInput("username")) {
                echo "<div style='padding-top: 10px;'>* Din epost eller passord er feil, prøv på nytt eller trykk på glemt passord.</div>";
            }
            ?>
            </div>
            <div class='col-50'>
                <? echo $this->__w("Password"); ?>
                <span class='contact_input'><input type='password' gsname="userData][password]" value='<? echo $this->getPost("password"); ?>' class='<? echo $this->validateInput("password"); ?>'></span>
            </div>
        <? } ?>
    <div style='clear:both;'></div>
    <div style="padding:10px; margin-bottom: 20px">
        <a href=""></a>
    </div>
    <?
    } else if ($this->getCustomerType()) {
        $text = $this->__w("Birth date (mm.dd.yy)");
        $nameText = $this->__w("Name of the one ordering");
        $birthdayPlaceholder = "13.06.84";
        if ($this->getCustomerType() == "company") {
            $text = $this->__w("Organisation number");
            $birthdayPlaceholder = "912999688";
            $nameText = $this->__w("Company name");
        }
        ?>
        <div class='col-50'>
            <?
            echo "<span class='common_text company'>" . $text . "</span>";
            ?>
            <span class='contact_input'><input type='text' gsname="userData][birthday]" value='<? echo $this->getPost("birthday"); ?>' class='<? echo $this->validateInput("birthday"); ?>' placeholder="<? echo $birthdayPlaceholder; ?>"></span>
        </div>

        <div class='col-50'>
            <? echo $this->__w("Address"); ?>
            <span class='contact_input'><input type='text' gsname="userData][address]" value='<? echo $this->getPost("address"); ?>' class='<? echo $this->validateInput("address"); ?>' placeholder="Nedre langgate 3A"></span>
        </div>
        <div class="row_seperator"></div>

        <div class='col-50'>
            <? echo $this->__w("Postal code"); ?>
            <span class='contact_input'><input type='text' gsname='userData][postal_code]' value='<? echo $this->getPost("postal_code"); ?>' class='<? echo $this->validateInput("postal_code"); ?>'  placeholder="3320"></span>
        </div>
        <div class='col-50'>
            <? echo $this->__w("Postal place"); ?>
            <span class='contact_input'><input type='text' gsname='userData][city]' value='<? echo $this->getPost("city"); ?>' class='<? echo $this->validateInput("city"); ?>'  placeholder="Tønsberg"></span>
        </div>

        <div class='col-50'>
            <? echo $nameText; ?>
            <span class='contact_input'><input type='text' gsname='userData][users_name]' value='<? echo $this->getPost("users_name"); ?>' class='<? echo $this->validateInput("users_name"); ?>'  placeholder="Navn"></span>
        </div>
        <div class='col-50'>
            <? echo $this->__w("Bestillers epost"); ?>
            <span class='contact_input'><input type='text' gsname='userData][users_email]' value='<? echo $this->getPost("users_email"); ?>' class='<? echo $this->validateInput("users_email"); ?>'  placeholder="din@epost.no"></span>
        </div>
        
        <? 
        if(\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
            /*
        ?>
            <h1 style='margin-top:50px;'>Admin choices</h1>
            <div class='col-33'>
                <? echo $this->__w("Billing period"); ?>
                <span class='contact_input'><select type='text' gsname='userData][overridetype]' value='<? echo $this->getPost("city"); ?>' class='<? echo $this->validateInput("billingtype"); ?>' style='width:100%;'>
                        <option value='standard'>Standard</option>
                        <option value='monthly'>Monthly</option>
                        <option value='total'>Total</option>
                    </select>
                </span>
            </div>
           <div class='col-33'>
                <? echo $this->__w("Billing type"); ?>
                <span class='contact_input'>
                    <span class='contact_input'><select type='text' gsname='userData][invoice_type]' value='<? echo $this->getPost("city"); ?>' class='<? echo $this->validateInput("invoice_type"); ?>' style='width:100%;'>
                            <option value='creditcard'>Credit card</option>
                            <option value='invoice'>Invoice</option>
                        </select>
                    </span>
                </span>
            </div>
           <div class='col-33'>
                <? echo "Override price (leave empty for default)"; ?>
                <span class='contact_input'><input type='text' gsname='userData][overrideprice]' value='<? echo $this->getPost("users_name"); ?>' class='<? echo $this->validateInput("overrideprice"); ?>'  placeholder="500"></span>
            </div>
    <div class="row_seperator"></div>
            
        <?
             */
        }
    } ?>
    <div class="row_seperator"></div>
</div>