<br><br>
<?php
/* @var $this \ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2\Hotelbooking */
$selectRoomText = $this->__w("Select a room");
$priceText = $this->__w("PRICE PER NIGHT");
$selectRoomButton = $this->__w("SELECT ROOM");
$headingtext = $this->__w("You have selected the following duration for your stay");

?>
<div class="top_row_container">
    <div class='title'><h1><? echo $headingtext; ?></h1></div>
    <div class='seperator'></div>
    <div class='top_box'>
        <? if ($this->getServiceType() == "hotel") { ?>
            <span class='booking_count_box'>
                <table>
                    <tr>
                        <td><? echo $this->__w("Number of rooms"); ?></td>
                        <td align='right'><input class='number_of_rooms' type='number' min="1" max="10" value='<? echo $this->getRoomCount(); ?>'></td>
                    </tr>
                    <tr>
                        <td><? echo $this->__w("I need a handicap room"); ?></td>
                        <? 
                        $checked = ""; 
                        if($this->getNeedHandicap()) {
                            $checked = "CHECKED";
                        }
                        ?>
                        
                        <td align='right'><input class='need_handicat' type='checkbox' <? echo $checked; ?>></td>
                    </tr>
                    <?
                    if ($this->getDayCount() > 3) {
                        ?>
                        <tr>
                            <td colspan='2'>
                                <br>
                                <? echo $this->__w("Cleaning 49,- each clean");
                                $vasking = $this->getCleaningProudcts();
                                $selectedOption = $this->getCleaningOption();

                                
                                ?>
                                <div>
                                    <select class="cleaning_option">
                                        <option value="no"><? echo $this->__f("No cleaning"); ?></option>
                                        <?
                                        foreach ($vasking as $vask) {
                                            $selected = "";
                                            if ($selectedOption == $vask->id) {
                                                $selected = "SELECTED";
                                            }
                                            echo "<option value='" . $vask->id . "' $selected>" . $vask->name . "</option>";
                                        }
                                        ?>
                                    </select>
                                </div>
                            </td>
                        </tr>
                    <? } ?>
                    <?
                    if ($this->hasAvailableParkingSpots()) {
                        $price = $this->getParkingProduct()->price;
                        ?>
                        <tr>
                            <td colspan='2'>
                                <br>
                                <div>
                                    <label>
                                        <input type="checkbox" class="parking_option" style="width:15px; margin:0px;padding:4px;" <? if($this->getParking()) { echo "CHECKED"; } ?>>
                                        <? echo $this->__w("Parking slot"); ?> + <? echo $this->getParkingPrice(); ?> kr
                                    </label>
                                </div>
                            </td>
                        </tr>
                    <? } ?>
                </table>
            </span>
        <? } ?>

        <span class='calendar left'>
            <? $this->printCalendar($this->getStart(), false, "startDate"); ?>
        </span>

        <span class='calendar right'>
            <? echo $this->printCalendar($this->getEnd(), $this->getStart(), "endDate"); ?>
        </span>
    </div>
    <?
    $days = $this->getMinumRentalTexted();
    if ($this->getShowExtraInformation()) {
        echo $this->getShowExtraInformation();
    } else if ($days) {
        $minimum = $this->__f("* Minimum rental periode is {days}");
        $minimum = str_replace("{days}", $days, $minimum);
        echo "<div class='error_text'>" . $minimum . "</div>";
    }
    ?>
    <?
    foreach ($this->errors as $error) {
        echo "<div class='error_text'>" . $error . "</div>";
    }
    ?>
</div>
<div class="bottom_row_container">
    <div class='title'><h1><? echo $selectRoomText; ?></h1></div>
    <div class="seperator"></div>
    <div class='room_selection_2 heading'>
        <span class='firstbox selection_box'>
            <div class='name'><? echo $this->__w("Room type"); ?></div>
        </span> 
        <? if ($this->getServiceType() == "hotel") { ?>
            <span class='secondbox selection_box'>
                <div><? echo $this->__w("MAX COUNT"); ?></div>
            </span>
        <? } ?>
        <span class='price_box'><? echo $priceText; ?></span>
        <div style='clear:both;'></div>
    </div>
    <div style="height:5px;"></div>

    <?
    $products = $this->getHotelRooms();
    $foundroom = 0;
    foreach ($products as $product) {
        $selectedclass = "";
        $avroom = $this->getNumberOfAvailableRooms($product->id);
        if ($product->id === $this->getProduct()->id) {
            $selectedclass = "selected";
        }
        $disabled = "";
        if ($avroom <= 0) {
            $selectedclass .= " disabled";
        }
        $images = $product->imagesAdded;

        $foundroom = true;
        echo "<div class='room_selection_2 product $selectedclass'>";
        /* @var $product core_productmanager_data_Product */
        echo "<span class='firstbox selection_box' productid='" . $product->id . "'>";
        if (sizeof($images) > 0 && $this->getDisplayRoomThumbnail()) {
            echo '<a href="displayImage.php?id=' . $images[0] . '" data-lightbox="' . $product->id . '" data-title=""><img class="imagepreview" src="displayImage.php?id=' . $images[0] . '"></a>';
            foreach ($images as $index => $image) {
                if ($index == 0) {
                    continue;
                }
                echo '<a href="displayImage.php?id=' . $image . '" data-lightbox="' . $product->id . '" data-title=""></a>';
            }
        }
        echo "<div class='name' >" . $product->name . "</div>";
        echo "<div class='roomdesc'>";
        if (isset($product->shortDescription)) {
            echo trim($product->shortDescription ? strip_tags($product->shortDescription) : '');
        }
        echo "</div>";
        echo "</span>";

        echo "<span class='secondbox selection_box'>";
        if ($this->getServiceType() == "hotel") {
            echo "<div><i class='fa fa-user'></i></div>";
            echo "<div class='personalcount'>2x</div>";
        }
        echo "</span>";
        if($product->price != 0) {
            echo "<span class='price_box'><span class='price_text'>" . $product->price . ",-";
        }
        if ($product->price < $product->original_price) {
            echo "<span class='rebated_product'> (-" . (100 - (int) (($product->price / $product->original_price) * 100)) . "%)</span>";
        }
        echo "</span>";
        if ($avroom <= 0) {
            echo "<span class='sold_out'>" . $this->__w("Sold out") . "</span>";
        } else {
            echo "<span class='selectbutton' gstype='clicksubmit' method='changeProduct' gsname='productid' gsvalue='" . $product->id . "'>" . $selectRoomButton . "</span>";
        }
        echo "</span>";
        echo "<div style='clear:both;'></div>";
        echo "<span class='available_rooms'>";
        echo $avroom;
        if ($avroom > 1) {
            echo " " . $this->__w("available rooms");
        } else {
            echo " " . $this->__w("available room");
        }
        echo "</span>";
        echo "</div>";
    }
    if (!$foundroom) {
        echo "<div class='no_room_available'>" . $this->__w("No rooms are available for this time periode.") . "</div>";
        echo "<script>$('.room_selection_2').hide();</script>";
    } else {
        if (!$this->errors) {
            ?>
    <div class='included_all_rooms'>
        <? echo $this->__w("Included in all rooms:"); ?> <i class="fa fa-wifi"></i> WI-FI
    </div>
    </div>
            <div class="to_checkout">
                <a href='?page=<? echo $this->getConfig()->summaryPage; ?>&subpage=summary'><div class="continue_to_cart_button"><? echo $this->__w("CONTINUE"); ?></div></a>
            </div>
        <? } ?>
    <? } ?>
</div>
<div style="clear:both;"></div>
