<br><br>
<?php
/* @var $this \ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2\Hotelbooking */
$selectRoomText = $this->__w("Select a room");
$priceText = $this->__w("PRICE PER NIGHT");
$selectRoomButton = $this->__w("SELECT ROOM");
$selectedRoomButton = $this->__w("SELECTED ROOM");
$headingtext = $this->__w("You have selected the following duration for your stay");
    
?>
<div class="top_row_container">
    <div class='title'><h1><? echo $headingtext; ?></h1></div>
    <div class='seperator'></div>
    <div class='top_box'>
        
        <? if($this->getFactory()->isMobile()) { ?>
            <span class='calendar left'>
                <? $this->printCalendar($this->getStart(), false, "startDate"); ?>
            </span>

            <span class='calendar right'>
                <? echo $this->printCalendar($this->getEnd(), $this->getStart(), "endDate"); ?>
            </span>
        <? } ?>
        
        <span class='booking_count_box'>
            <table>
                <tr>
                    <td><? echo $this->__w("Number of rooms"); ?></td>
                    <td align='right'>
                        <select class='number_of_rooms' type='number' min="1" max="10">
                            <? 
                            for($i = 1; $i <= 10; $i++) {
                                $selected = "";
                                if($this->getRoomCount() == $i) {
                                   $selected = "SELECTED";
                                }
                                echo "<option value='$i' $selected>$i</option>";
                            }
                                ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td valign='top'><? echo $this->__w("I need a handicap room"); ?></td>
                    <? 
                    $checked = ""; 
                    if($this->getNeedHandicap()) {
                        $checked = "CHECKED";
                    }
                    ?>

                    <td align='right'><input class='need_handicat' type='checkbox' <? echo $checked; ?>><br><br><br></td>
                </tr>
                <tr>
                    <td class='checkininfo'><? echo $this->__w("Check in date"); ?></td>
                    <? 
                    $checked = ""; 
                    if($this->getNeedHandicap()) {
                        $checked = "CHECKED";
                    }
                    ?>

                    <td align='right' class='checkininfo'>
                        <? echo date("d-m-Y", $this->getStart()); ?>
                    </td>
                </tr>
                <tr>
                    <td class='checkininfo'><? echo $this->__w("Check out date"); ?></td>
                    <? 
                    $checked = ""; 
                    if($this->getNeedHandicap()) {
                        $checked = "CHECKED";
                    }
                    ?>

                    <td align='right' class='checkininfo'>
                        <? echo date("d-m-Y", $this->getEnd()); ?>
                    </td>
                </tr>
                <tr>
                    <td class='checkininfo'><? echo $this->__w("Number of nights"); ?></td>
                    <? 
                    $checked = ""; 
                    if($this->getNeedHandicap()) {
                        $checked = "CHECKED";
                    }
                    ?>

                    <td align='right' class='checkininfo'>
                        <? echo $this->getDayCount(); ?>
                    </td>
                </tr>
            </table>
        </span>

        <? if(!$this->getFactory()->isMobile()) { ?>
            <span class='calendar left'>
                <? $this->printCalendar($this->getStart(), false, "startDate"); ?>
            </span>

            <span class='calendar right'>
                <? echo $this->printCalendar($this->getEnd(), $this->getStart(), "endDate"); ?>
            </span>
        <? } ?>
    </div>
    <?
    foreach ($this->errors as $error) {
        echo "<div class='error_text'>" . $error . "</div>";
    }
    ?>
</div>

 <?
 if($this->getDayCount() > $this->getConfig()->maxRentalDays) {
    echo "<br><bR>";
    echo $this->getPartnerText();
    echo "<br><bR>";
    echo "<br><bR>";
    return;
}

?>

<div class="bottom_row_container">
    <div class='title'>
        <h1>
            <? echo $selectRoomText; ?>
        </h1>
    </div>
    
    <div class="seperator"></div>
    <? if(!$this->getFactory()->isMobile()) { ?>
    <div class='room_selection_2 heading'>
        <span class='firstbox selection_box'>
            <div class='name'><? echo $this->__w("Room type"); ?></div>
        </span> 
        <span class='price_box'><? echo $priceText; ?></span>
        <div style='clear:both;'></div>
    </div>
    <div style="height:5px;"></div>
    <? } ?>
    <?
    $products = $this->getHotelRooms();
    $foundroom = 0;
    $atleastOne = false;
    foreach ($products as $product) {
        $selectedclass = "";
        $avroom = $this->getNumberOfAvailableRooms($product->id);
        $avroomHandicap = $this->getNumberOfAvailableRooms($product->id, true);
        if ($product->id === $this->getProduct()->id) {
            $selectedclass = "selected";
        }
        
        if($avroomHandicap == 1) {
            $handicapText = $this->__w("{room} room is fitted for handicap.");
        } else {
            $handicapText = $this->__w("{room} rooms are fitted for handicap.");
        }
        $handicapText = str_replace("{room}", $avroomHandicap, $handicapText);
        
        $disabled = "";
        if ($avroom <= 0) {
            $selectedclass .= " disabled";
        }
        $images = $product->imagesAdded;
        $mainImage = $product->mainImage;

        
        $foundroom = true;
        
        echo "<div class='room_selection_2 product $selectedclass'>";
        if($this->getFactory()->isMobile()) {
            $progressivePrice = $this->calculateProgressivePrice($product->id);
            $progressivePrice = round($progressivePrice,2);
            $price = $product->price;
            if($price != $progressivePrice) {
                $percentage = $price - $progressivePrice;
                if($percentage > 50) {
                    echo "<span style='font-size: 12px; display:inline-block;position: absolute;right: 5px;top: 26px;color: #bbb;font-weight: bold;'>$percentage kr rabatt fra ".$product->price.",-</span>";
                }
            }
                
            echo "<div class='name' ><span class='price_box'><span class='price_text' style='float:right;'>" . $progressivePrice . ",-</span></span>";
            echo "<i class='fa fa-info-circle' style='cursor:pointer' data-productid='".$product->id."'></i> " . $product->name . "</div>";
        }
        
        $this->printToolTip($product);
        
        /* @var $product core_productmanager_data_Product */
        echo "<span class='firstbox selection_box' productid='" . $product->id . "'>";
        if (sizeof($images) > 0 && $this->getConfig()->roomThumbNails) {
            $size = getimagesize("../uploadedfiles/" . $mainImage);
            echo "<span class='gsgalleryroot'>";
            echo '<span img="displayImage.php?id=' . $mainImage . '" class="gsgallery" width="'.$size[0].'" height="'.$size[1].'" index="0"><img class="imagepreview" src="displayImage.php?id=' . $mainImage . '"></span>';
            echo "<span class='hotelthumbnails'>";
            foreach ($images as $index => $image) {
                if($image == $mainImage) {
                    continue;
                }
                $size = getimagesize("../uploadedfiles/" . $image);
                echo '<span img="displayImage.php?id=' . $image . '" class="gsgallery" width="'.$size[0].'" height="'.$size[1].'" index="'.$index.'"><img class="imagepreviewthumb" src="displayImage.php?id=' . $images[$index] . '"></span>';
            }
            echo "</span>";
            echo "</span>";
        }

        if(!$this->getFactory()->isMobile()) {
            echo "<div class='name' ><i class='fa fa-info-circle' style='cursor:pointer' data-productid='".$product->id."'></i> " . $product->name . "</div>";
        }
        echo "<div class='roomdesc'>";
        if (isset($product->shortDescription)) {
            echo trim($product->shortDescription ? strip_tags($product->shortDescription) : '');
        }
        echo "</div>";
        echo "</span>";

        echo "<span class='secondbox selection_box'>";
        
        echo "<div><i class='fa fa-user'></i></div>";
        if($product->id == "248ec601-ee7a-4d3a-8644-be4de68b2412") {
            echo "<div class='personalcount'>4x</div>";
        } else {
            echo "<div class='personalcount'>2x</div>";
        }
        
        echo "</span>";
        
        $progressivePrice = $this->calculateProgressivePrice($product->id);
        $price = $product->price;
        
        if(!$this->getFactory()->isMobile()) {
            if($product->price != 0) {
                $progressivePrice = round($progressivePrice,2);
                echo "<span class='price_box'><span class='price_text'>" . $progressivePrice . ",-";
                if($price != $progressivePrice) {
                    $percentage = (double)100-(($progressivePrice/$price)*100);
                    $percentage = $price - $progressivePrice;
                    if($percentage > 50) {
                        echo "<br><span style='font-size: 12px;font-weight:normal; margin-top: 5px; display:inline-block;'>$percentage kr avslag fra ".$product->price."kr</span>";
                    }
                }
            }
        }
        
        

        if ($product->price < $product->original_price) {
            echo "<span class='rebated_product'> (-" . (100 - (int) (($product->price / $product->original_price) * 100)) . "%)</span>";
        }
        echo "</span>";
        if ($avroom <= 0) {
            echo "<span class='sold_out'>" . $this->__w("Sold out") . "</span>";
        } else {
            $atleastOne= true;
            $text = $selectRoomButton;
            if($selectedclass) {
                $text = $selectedRoomButton;
            }
            echo "<span class='selectbutton' gstype='clicksubmit' method='changeProduct' gsname='productid' gsvalue='" . $product->id . "'>" . $text . "</span>";
        }
        echo "</span>";
        echo "<div style='clear:both;'></div>";
        echo "<span class='available_rooms'>";
        echo $avroom;
        if ($avroom > 1) {
            echo " " . $this->__w("available rooms");
        } else {
            echo " " . $this->__w("available room");
        }
        if($avroomHandicap) {
            echo ", <i class='fa fa-wheelchair' title='".$handicapText."'></i> " . $handicapText;
        }
        echo ", " . $product->sku;
        echo "</span>";
        echo "</div>";
    }
    if (!$foundroom) {
        echo "<div class='no_room_available'>" . $this->__w("No rooms are available for this time periode.") . "</div>";
        echo "<script>$('.room_selection_2').hide();</script>";
    } else {
        if (!$this->errors) {
            ?>
    <div class='included_all_rooms'>
       <i class="fa fa-wifi"></i> WI-FI <? echo $this->__w("included in all rooms"); ?> 
    </div>
    </div>
<?
        if ($this->getStart() < strtotime("01-05-2015")) {
            echo "<center><h1>Beklager, men hotellet åpner ikke før 1. mai</h1></center><br><br>";
        } else if($atleastOne) {
            ?>
            <div class="to_checkout">
                <a href='?page=<? echo $this->getConfig()->summaryPage; ?>'><div class="continue_to_cart_button"><? echo $this->__w("CONTINUE"); ?></div></a>
            </div>
            <?
        }
    } ?>
    <? } ?>
</div>
<div style="clear:both;"></div>
