<?php
namespace ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2;
 /* @var $this Hotelbooking */

$pagenumber = 1;
if(isset($_GET['pagenumber'])) {
    $pagenumber = $_GET['pagenumber'];
}

?>
<div class='bookingbox'>
    <div class='boxontop'>
        <div class='booking_page page_selectroom'>
            <?
            /* @var $this \ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2\Hotelbooking */
            $checkintext = $this->__w("CHECK IN");
            $checkouttext = $this->__w("CHECK OUT");
            $roomtypetext = $this->__w("Apartment / room");
            $displayEnd = "display:inline-block;";
            $products = $this->getHotelRooms();
            ?>



            <span class='bookingcol datecol firstcalcol'>
            <? echo $checkintext; ?><br>
                <input type='text' class='date_selection_room' value='<? echo date('d.m.Y'); ?>' id='start_date'>
                <span class='calbackground start_cal'><i class='fa fa-calendar'></i></span>
            </span>
            <span class='bookingcol datecol'>
                <span style='text-align:left;<? echo $displayEnd; ?>'>
                    <? echo $checkouttext; ?><br>
                    <input type='text' class='date_selection_room' value='<? echo date('d.m.Y', time() + 86400); ?>' id='end_date'>
                    <span class='calbackground end_cal'><i class='fa fa-calendar'></i></span>
                </span>
            </span>
            <span class='bookingcol'>
                <? echo $roomtypetext; ?>
                <select class='room_selection'>
                    <?
                    foreach ($products as $product) {
                        /* @var $product \core_productmanager_data_Product */

                        $pricetext = $product->price . " NOK ";
                        if ($product->price < $product->original_price) {
                            $pricetext .= " (-" . (100 - (int) (($product->price / $product->original_price) * 100)) . "%)";
                        }

                        echo "<option value='" . $product->id . "'>" . $pricetext . " " . $product->name . "</option>";
                    }
                    ?>
                </select>
            </span>
            <span class='bookingcol'>
                <br>
                <div class='check_available_button' nextpage="<? echo $this->getConfig()->continuePage; ?>"><? echo $this->__w("Continue"); ?></div>
            </span>

            <div style='padding-top:20px;'>
                <span class='error_on_check date_before_start'>
                    <? echo $this->__f("Sorry, but the start date is before todays date."); ?>
                </span>
                <span class='error_on_check end_before_start'>
                    <? echo $this->__f("Sorry, but the start date is before todays date."); ?>
                </span>
            </div>
            <div style='clear:both;'></div>
            <div style='padding-top: 20px;'>
                <? 
                    $partnerText = $this->getPartnerText();
                    echo $this->__w($partnerText); 
                ?>
            </div>
        </div>
    </div>
</div>
<script>
    $('.Hotelbooking #start_date').datepicker({ dateFormat: "dd.mm.yy", minDate : 0 });
    $('.Hotelbooking #end_date').datepicker({ dateFormat: "dd.mm.yy" });
    $('.Hotelbooking .end_cal').on('click', function() { $('.Hotelbooking #end_date').focus(); });
    $('.Hotelbooking .start_cal').on('click', function() { $('.Hotelbooking #start_date').focus(); });
</script>