<?php
namespace ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2;
 /* @var $this Hotelbooking */

$pagenumber = 1;
if(isset($_GET['pagenumber'])) {
    $pagenumber = $_GET['pagenumber'];
}

$pages[1] = "selectroom";
$pages[2] = "bookroom";

?>
<div class='bookingbox'>
    <div class='boxontop'>
        <div class='booking_page page_<? echo $pagenumber; ?>'>
            <? $this->includefile($pages[$pagenumber]); ?>
        </div>
    </div>
</div>
<script>
    $('.Hotelbooking #start_date').datepicker({ dateFormat: "dd.mm.yy", minDate : 0 });
    $('.Hotelbooking #end_date').datepicker({ dateFormat: "dd.mm.yy" });
    $('.Hotelbooking .end_cal').on('click', function() { $('.Hotelbooking #end_date').focus(); });
    $('.Hotelbooking .start_cal').on('click', function() { $('.Hotelbooking #start_date').focus(); });
</script>