<?
/* @var $this \ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2\Hotelbooking */
$nightText = $this->__w("night");
$nightsText = $this->__w("nights");
$inText = $this->__w("with");
$bookTime = $this->__w("Booked time periode");
?>

<div class="summaryview">
    <div class='summary_heading'>
        <h1><? echo $this->__w("Summary"); ?></h1>
    </div>
    <div class="seperator"></div>
    <? if(!$this->partnerShipChecked()) { ?>
        <div class='price_row'>
            <? echo $bookTime; ?>
            <span class='right_aligned_price'>
                <?
                echo date("d. M Y", $this->getStart()) . " " . $this->__w("to") . " " . date("d. M Y", $this->getEnd());
                ?>
            </span>
        </div>
    <?
    }
    $total = 0;
    $totalDiff = 0;
    $cart = $this->getApi()->getCartManager()->getCart();
    $total = 0;
    $taxes = array();

    
    $i = 0;
    foreach ($cart->items as $cartItem) {
        /* @var $cartItem core_cartmanager_data_CartItem */
        $product = $cartItem->product;
        $nightTextToPrint = $nightText;
        if ($cartItem->count > 1) {
            $nightTextToPrint = $nightsText;
        }
        $text = $cartItem->count . " " . $nightTextToPrint . " " . $inText . " " . strtolower($product->name);
        if($this->partnerShipChecked()) {
//            $text .= " (" . date("d-m-Y", $partnerReservations[$i]->start) . " - " . date("d-m-Y", $partnerReservations[$i]->end) . ")";
        }
        $text .= "<br>";
        
        $price = $cartItem->product->original_price * $cartItem->count;
        $originalPrice = $price;
        $discountedPrice = $cartItem->product->price * $cartItem->count;
        $originalDiscountPrice = $discountedPrice;
        $diff = $discountedPrice - $price;
        $totalDiff += $diff;
        if ($product->taxGroupObject) {
            $taxgroup = $product->taxGroupObject->taxRate;
            if (!isset($taxes[$taxgroup])) {
                $taxes[$taxgroup] = 0;
            }
            $taxes[$taxgroup] += $discountedPrice * ($taxgroup / 100);
            $price -= $discountedPrice * ($taxgroup / 100);
        }
        $total += $price;
        $price = number_format((float) $price, 2, '.', '');

        echo "<div class='price_row'>";
        echo "<span class='right_aligned_price'><span class='right_aligned_price'>" . $price . " kr</span></span>";
        echo $text;
        echo "</div>";
        $i++;
    }
    if ($totalDiff < 0) {
        $percentage = (double)($originalDiscountPrice/$originalPrice)*100;
        $percentage = 100 - $percentage;
        $percentage = round($percentage, 1);

        $totalDiff = number_format((float) $totalDiff, 2, '.', '');
        echo "<div class='price_row'>";
        echo "<span class='right_aligned_price'><span class='right_aligned_price'>" . $totalDiff . " kr</span></span>";
        echo "Rabatt for lengere opphold ($percentage%)";
        echo "</div>";
        $total += $totalDiff;
    }

    foreach ($taxes as $taxgroup => $value) {
        $value = number_format((float) $value, 2, '.', '');
        echo "<div class='price_row'>";
        echo "<span class='right_aligned_price'><span class='right_aligned_price'>" . $value . " kr</span></span>";
        echo $taxgroup . "% MVA";
        echo "</div>";
        $total += $value;
    }
    
    $total = number_format((float) $total, 2, '.', '');

    echo "<div class='summary_total'>";
    echo "<div class='price_summary'>" . $this->__w("Total price") . "<span class='right_aligned_price'>" . $total . " kr" . "</span></div>";
    echo "</div>";
    if($this->partnerShipChecked()) {
        echo $this->__w("* The rooms are being billed monthly in advanced");
    }
    ?>
</div>