<?
$nightText = $this->__w("night");
$nightsText = $this->__w("nights");
$inText = $this->__w("with");
$bookTime = $this->__w("Booked time periode");
?>

<div class="summaryview">
    <div class='summary_heading'>
        <h1><? echo $this->__w("Summary"); ?></h1>
    </div>
    <div class="seperator"></div>
    <div class='price_row'>
        <? echo $bookTime; ?>
        <span class='right_aligned_price'>
            <?
            echo date("d. M Y", $this->getStart()) . " " . $this->__w("to") . " " . date("d. M Y", $this->getEnd());
            ?>
        </span>
    </div>

    <?
    $total = 0;
    $totalDiff = 0;
    $cart = $this->getApi()->getCartManager()->getCart();
    $total = 0;
    $taxes = array();
    foreach ($cart->items as $cartItem) {
        /* @var $cartItem core_cartmanager_data_CartItem */
        $product = $cartItem->product;
        if ($cartItem->product->sku == "vask" || $cartItem->product->sku == "parking") {
            $text = $cartItem->count . " " . strtolower($product->name) . "<br>";
        } else {
            $nightTextToPrint = $nightText;
            if ($cartItem->count > 1) {
                $nightTextToPrint = $nightsText;
            }
            $text = $cartItem->count . " " . $nightTextToPrint . " " . $inText . " " . strtolower($product->name) . "<br>";
        }
        $price = $cartItem->product->original_price * $cartItem->count;
        $discountedPrice = $cartItem->product->price * $cartItem->count;
        $diff = $discountedPrice - $price;
        $totalDiff += $diff;
        if ($product->taxGroupObject) {
            $taxgroup = $product->taxGroupObject->taxRate;
            if (!isset($taxes[$taxgroup])) {
                $taxes[$taxgroup] = 0;
            }
            $taxes[$taxgroup] += $discountedPrice * ($taxgroup / 100);
            $price -= $discountedPrice * ($taxgroup / 100);
        }
        $total += $price;
        $price = number_format((float) $price, 2, '.', '');

        echo "<div class='price_row'>";
        echo "<span class='right_aligned_price'><span class='right_aligned_price'>" . $price . " kr</span></span>";
        echo $text;
        echo "</div>";
    }
    if ($totalDiff < 0) {
        $totalDiff = number_format((float) $totalDiff, 2, '.', '');
        echo "<div class='price_row'>";
        echo "<span class='right_aligned_price'><span class='right_aligned_price'>" . $totalDiff . " kr</span></span>";
        echo "Rabatt for lengere opphold";
        echo "</div>";
        $total += $totalDiff;
    }

    if (($this->isMvaRegistered() && $product->privateExcluded) || !$product->privateExcluded) {
        foreach ($taxes as $taxgroup => $value) {
            $value = number_format((float) $value, 2, '.', '');
            echo "<div class='price_row'>";
            echo "<span class='right_aligned_price'><span class='right_aligned_price'>" . $value . " kr</span></span>";
            echo $taxgroup . "% MVA";
            echo "</div>";
            $total += $value;
        }
    }
    $total = number_format((float) $total, 2, '.', '');

    echo "<div class='summary_total'>";
    echo "<div class='price_summary'>" . $this->__w("Total price") . "<span class='right_aligned_price'>" . $total . " kr" . "</span></div>";
    echo "</div>";
    ?>
</div>