<?
/* @var $this \ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2\Hotelbooking */
$nightText = $this->__w("night");
$nightsText = $this->__w("nights");
$inText = $this->__w("with");
$bookTime = $this->__w("Booked time periode");
$numberOfNights = $this->getDayCount();
$flexProduct = $this->getFlexProduct();
?>

<div class="summaryview">
    <div class='summary_heading'>
        <h1><? echo $this->__w("Summary"); ?></h1>
    </div>
    <div class="seperator"></div>
    <?
    $total = 0;
    $totalDiff = 0;
    $cart = $this->getApi()->getCartManager()->getCart();
    $total = 0;
    $taxes = array();

    
    $i = 0;
    
    $totalOrignalPrice = 0;
    $totalDiscountedPrice = 0;
    
    foreach ($cart->items as $cartItem) {
        $totalDiscountedPrice += $cartItem->product->price * $cartItem->count;
        $totalOrignalPrice += $cartItem->product->original_price * $cartItem->count;    
    }
    
    echo "<div style='border-bottom: solid 1px #c9b9a3; padding-bottom: 5px; margin-bottom: 5px;'>";
    $totalDiff = $totalDiscountedPrice - $totalOrignalPrice;
    if ($totalDiff < 0) {
        $percentage = (double)($totalDiscountedPrice/$totalOrignalPrice)*100;
        $percentage = 100 - $percentage;
        $percentage = round($percentage, 1);

        $totalDiff = number_format((float) $totalDiff, 2, '.', '');
        echo "<div class='price_row'>";
        echo "<span class='right_aligned_price'><span class='right_aligned_price'>" . $totalDiff*-1 . " kr</span></span>";
        echo "Rabatt på oppholdet ($percentage%)";
        echo "</div>";
    }
    echo "</div>";
    
    foreach ($cart->items as $cartItem) {
        /* @var $cartItem core_cartmanager_data_CartItem */
        $product = $cartItem->product;
        $nightTextToPrint = $nightText;
        if ($cartItem->count > 1) {
            $nightTextToPrint = $nightsText;
        }
        $text = $cartItem->count . " " . $nightTextToPrint . " " . $inText . " " . strtolower($product->name);
        
        $text .= " - " . date("d.m.Y", strtotime($cartItem->startDate)) . " " . $this->__w("to") . " " . date("d.m.Y", strtotime($cartItem->endDate));

        $discountedPrice = $cartItem->product->price * $cartItem->count;
        
        if($product->id == $flexProduct->id) {
            $text = "Tillegg for flexibel leie";
        }

        $text .= "<br>";
        
        if ($product->taxGroupObject) {
            $taxgroup = $product->taxGroupObject->taxRate;
            if (!isset($taxes[$taxgroup])) {
                $taxes[$taxgroup] = 0;
            }
            $nettoDiscounted = $discountedPrice / (1+($taxgroup / 100));
            $taxes[$taxgroup] += $discountedPrice - $nettoDiscounted;
        } 
       
        echo "<div class='price_row'>";
        echo "<span class='right_aligned_price'><span class='right_aligned_price'>" . number_format((float) $nettoDiscounted, 2, '.', '') . " kr</span></span>";
        echo $text;
        echo "</div>";
        $total += $nettoDiscounted;
        $i++;
    }
    
  
    foreach ($taxes as $taxgroup => $value) {
        $value = number_format((float) $value, 2, '.', '');
        echo "<div class='price_row'>";
        echo "<span class='right_aligned_price'><span class='right_aligned_price'>" . $value . " kr</span></span>";
        echo $taxgroup . "% MVA";
        echo "</div>";
        $total += $value;
    }
    
    
    $total = number_format((float) $total, 2, '.', '');

    echo "<div class='summary_total'>";
    $avgprice = "";
    if($numberOfNights > 0) {
        $avgprice = round(($total/$numberOfNights), 2);
        $avgprice = " (" . $avgprice . " kr per natt)";
    }
    echo "<div class='price_summary'>" . $this->__w("Total price") . $avgprice  . "<span class='right_aligned_price'>" . $total . " kr" . "</span></div>";
    echo "</div>";
    if($this->isPartnershipBooking()) {
        echo $this->__w("* The rooms are being billed monthly in advanced");
    }
    ?>
</div>