<?
/* @var $this \ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2\Hotelbooking */
$checkintext = $this->__w("CHECK IN");
$checkouttext = $this->__w("CHECK OUT");
$roomtypetext = $this->__w("Apartment / room");
$displayEnd = "display:inline-block;";
$products = $this->getHotelRooms();
?>



<span class='bookingcol datecol firstcalcol'>
<? echo $checkintext; ?><br>
    <input type='text' class='date_selection_room' value='<? echo date('d.m.Y'); ?>' id='start_date'>
    <span class='calbackground start_cal'><i class='fa fa-calendar'></i></span>
</span>
<span class='bookingcol datecol'>
    <span style='text-align:left;<? echo $displayEnd; ?>'>
        <? echo $checkouttext; ?><br>
        <input type='text' class='date_selection_room' value='<? echo date('d.m.Y', time() + 86400); ?>' id='end_date'>
        <span class='calbackground end_cal'><i class='fa fa-calendar'></i></span>
    </span>
</span>
<span class='bookingcol'>
    <? echo $roomtypetext; ?>
    <select class='room_selection'>
        <?
        foreach ($products as $product) {
            /* @var $product \core_productmanager_data_Product */


            $pricetext = $product->price . " NOK ";
            if ($product->price < $product->original_price) {
                $pricetext .= " (-" . (100 - (int) (($product->price / $product->original_price) * 100)) . "%)";
            }

            echo "<option value='" . $product->id . "'>" . $pricetext . " " . $product->name . "</option>";
        }
        ?>
    </select>
</span>
<span class='bookingcol'>
    <br>
    <div class='check_available_button' nextpage="<? echo $this->getContinuePage(); ?>"><? echo $this->__w("Continue"); ?></div>
</span>
<?
$days = $this->getMinumRentalTexted();
if($days) {
    $minimum = $this->__f("* Minimum rental periode is {days}");
    $minimum = str_replace("{days}", $days, $minimum);
    echo "<div>" . $minimum . "</div>";
}
?>

<div style='padding-top:20px;'>
    <span class='error_on_check date_before_start'>
        <? echo $this->__f("Sorry, but the start date is before todays date."); ?>
    </span>
    <span class='error_on_check end_before_start'>
        <? echo $this->__f("Sorry, but the start date is before todays date."); ?>
    </span>
</div>