<?
/* @var $this \ns_d16b27d9_579f_4d44_b90b_4223de0eb6f2\Hotelbooking */
$text = $this->__w("BOOK A ROOM AT");
$checkintext = $this->__w("CHECK IN");
$checkouttext = $this->__w("CHECK OUT");
$roomtypetext = $this->__W("ROOM TYPE");
$displayEnd = "display:inline-block;";
if($this->getServiceType($text) == "storage") {
    $displayEnd = "display:none;";
    $text = $this->__w("GET A STORAGE ROOM FROM");
    $checkintext = $this->__w("Select start date");
    $checkouttext = $this->__w("END");
    $roomtypetext = $this->__w("Select size");
}
?>

<span class='heading'><? echo $text . "<br>" . $this->getProjectName() ; ?></span>
<table width='100%'>
    <tr>
        <td>
            <? echo $checkintext; ?><br>
            <span style='background-color:#b0bda4; display:inline-block;' class='start_cal'>
                <input type='text' class='date_selection_room' value='<? echo date('d.m.Y'); ?>' id='start_date'><i class='fa fa-calendar'></i>
            </span>
        </td>
        <td align='right'>
            <span style='text-align:left;<? echo $displayEnd; ?>'>
                <? echo $checkouttext; ?><br>
                <span style='background-color:#b0bda4; display:inline-block;' class='end_cal'>
                    <input type='text' class='date_selection_room' value='<? echo date('d.m.Y', time()+86400); ?>' id='end_date'><i class='fa fa-calendar'></i>
                </span>
            </span>
        </td>
    </tr>
</table>
<div class='space_betweenroom'></div>
<? echo $roomtypetext; ?><br>
<select class='room_selection'>
    <?
        $products = $this->getHotelRooms();
        foreach($products as $product) {
            /* @var $product \core_productmanager_data_Product */
            
            
            $pricetext = $product->price . " NOK ";
            if($product->price < $product->original_price) {
                $pricetext .= " (-". (100-(int)(($product->price / $product->original_price)*100)) . "%)";
            }
            
            echo "<option value='".$product->id."'>" . $pricetext . " " . $product->name . "</option>";
        }
    ?>
</select>
<?
$days = $this->getMinumRentalTexted();
if($days) {
    $minimum = $this->__f("* Minimum rental periode is {days}");
    $minimum = str_replace("{days}", $days, $minimum);
    echo "<div>" . $minimum . "</div>";
}
?>

<div class='check_available_button' nextpage="<? echo $this->getContinuePage(); ?>"><? echo $this->__w("Check availability and continue"); ?></div>
<div style='padding-top:20px;'>
    <span class='error_on_check date_before_start'>
        <? echo $this->__f("Sorry, but the start date is before todays date."); ?>
    </span>
    <span class='error_on_check end_before_start'>
        <? echo $this->__f("Sorry, but the start date is before todays date."); ?>
    </span>
</div>