<form method="post">
    Login
    <br>
    <br><input type='text' placeholder='ENTER YOUR USERNAME' name="emailAddress"/>
    <br><input type='password' placeholder='ENTER YOUR PASSWORD' name="password"/>
    <br><center><input type="submit" name='sedoxlogin' class='sedox_button sedox_login' value='LOGIN' style='width: 200px;'></center>    
</form>
<div style='padding-top: 5px;'>
   <center> <a style='color: red' target='_new' href='http://www.tuningfiles.com/customer/account/forgotpassword/'>Forgotten password?</a> </center>
</div>
    

<script>
    $('.SedoxLogin input, .SedoxLogin textarea').placeholder();
</script>
    