<div class="login_check_modal">
    <div class="content"></div>
</div>

<div class="col_50">
    <div class="inner">
        <div class="header boldFont">Already have an account?</div>
        <div class="logincontent">
            <div gstype="form" method="doLogin">
                <input value="login" gsname="sedoxlogin" type="hidden"/>
                
                <label>Username: </label>
                <input gsname='username' type="text"><br>
                
                <label>Password: </label>
                <input gsname='password' type="password">
                
                <div class="sedox_blue_button dologin">Login</div>
                <br/>
                <div style="color: blue; text-align: center;">
                    Forgot username or password? 
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col_50">
    <div class="inner">
        <div class="header boldFont">Register account</div>
        <div class="logincontent">
            <div gstype="form" method="createAccount">
                <input value="login" gsname="sedoxlogin" type="hidden"/>
                
                <label>First Name *</label>
                <input gsname='create_firstname' type="text" value=""><br>
                
                <label>Last Name *</label>
                <input gsname='create_lastname' type="text" value="">
                
                <label>Email Address *</label>
                <input gsname='create_email' type="text" value="">
                
                <label>Tax/VAT number *</label>
                <input gsname='create_tax' type="text" value="">
                
                <label>Password *</label>
                <input gsname='create_password' type="password" value="">
                
                <label>Confirm Password *</label>
                <input gsname='create_password2' type="password" value="">
                
                <div class="sedox_blue_button register_user">Register</div>
                
            </div>
        </div>
    </div>
</div>