<?
/* @var $this \ns_9683701a_8217_411f_a321_26775f645f06\EventTypeList */

    $eventTypes = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getBookingEgineName());
    
    if (!$eventTypes) {
        $eventTypes = [];
    }
    
    foreach ($eventTypes as $type) {
        $delete = $this->hasWriteAccess() ? "<i class='fa fa-trash' gsclick='deleteEventType' value='$type->id'></i>" : "";
        echo "<div class='eventtype'>";
        echo "<span>$type->name</span>";
        echo $delete ;
            
                echo "<a href='/?page=$type->pageId'><div class='shop_button'>".$this->__f("Go to page")."</div></a>";
                echo "&nbsp;&nbsp;<a href='/?page=edit_event_type&bookingItemTypeId=$type->id'><div class='shop_button'>".$this->__f("Edit")."</div></a>";
        echo "</div>";
    }
?>