<div class='gss_settings_header'>
    <i class='fa fa-google'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Google Remarketing"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->getDescription();
            ?>	
        </div>
    </div>	
</div>
<div class='gss_settings_content'>
    <div class="textfield gss_setting">
        <span class="title">Merchant-ID</span>
        <input type="textfield" gs_model='remarketingmodel' gs_model_attr='remarketingcode' value="<? echo $this->getConfigurationSetting("remarketingcode"); ?>" placeholder="">
        <div class="description">
             <?php  echo $this->__f("Please enter the google remarketing code."); ?>
        </div>
    </div>
    
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="remarketingmodel" gss_success_message="<? echo $this->__f("Saved settings"); ?>"><i class='fa fa-save'></i><?php echo $this->__("Save settings"); ?></div>
    </div>
</div>

