<?php
$quickadd = "false";
if(isset($_SESSION['quickaddaddons'])) {
    $quickadd = "true";
}
?>
<center>
    <h3>Addons possible to add to this room</h3>
</center>
<div class="addaddonrows step1">
    <?php
    /* @var $this ns_7ca01dc3_49e7_4bad_a0f9_4f1eae1199d6\PmsAddonSelection */
    $types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName());
    $productsToExclude = array();
    foreach($types as $type) {
        $productsToExclude[] = $type->productId;
    }
    $found = false;
    $products = $this->getApi()->getProductManager()->getAllProducts();
    $newproducts = array();
    foreach($products as $prod) {
        $newproducts[$prod->name] = $prod;
    }
    ksort($newproducts);
    
    foreach($newproducts as $product) {
        if(in_array($product->id, $productsToExclude)) {
            continue;
        }
        $found = true;
        echo "<div class='addonsrow'>" . $product->name;
        echo "<span class='shop_button addAddonsToRoom' productid='".$product->id."' quickadd='$quickadd'>Add</span>";
        echo "</div>";
    }
    if(!$found) {
        echo "<div style='padding: 10px;'>No addons has been created yet<br>Go to settings -> Products / Addons to set up addons.</div>";
    }
    ?>
</div>



<div class="addaddonrows step2">
    
</div>
