<?php

?>
<?php
     /* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
    $config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
    $addonItem = null;
    foreach($config->addonConfiguration as $id => $item) {
        if($item->productId == $_POST['data']['productId']) {
            $addonItem = $item;
        }
    }

    $addonProduct = $this->getApi()->getProductManager()->getProduct($addonItem->productId);
    $perGuest = "";
    $includedInRoomPrice = "";
    $selectedType = "";
    if($addonItem->dependsOnGuestCount || $addonItem->addonType == 1) {
        $perGuest = "CHECKED";
    }
    if($addonItem->isIncludedInRoomPrice) {
        $includedInRoomPrice = "CHECKED";
    }
    if(!$addonItem->isSingle || $addonItem->addonType == 1) {
        $selectedType = "alldays";
    }
    if($addonItem->atEndOfStay) {
        $selectedType = "endofstay";
    }

    $addPeriodeTypes = array();
    $addPeriodeTypes['single'] = "Single entry";
    $addPeriodeTypes['startofstay'] = "Start of stay";
    $addPeriodeTypes['endofstay'] = "End of stay";
    $addPeriodeTypes['repeat_weekly'] = "Weekly entries";
    $addPeriodeTypes['repeat_monthly'] = "Monthly entries";
    $addPeriodeTypes['alldays'] = "All days";
    $quickadd = "false";
    if(isset($_POST['data']['quickadd'])) {
        $quickadd = $_POST['data']['quickadd'];
    }
    ?>
    <div class='addaddonstep2' style='border-bottom: solid 1px #bbb; border-top: solid 1px #bbb; padding: 10px;text-align: center;font-size: 18px; margin-bottom: 10px;'>
        <i class='fa fa-arrow-left goBackToStart' style='float:left;cursor:pointer; color:#bbb; '></i> Add <?php echo $addonProduct->name . " to room"; ?>
    </div>
    <div style='padding: 10px;'>
        <div class='addaddonsstep2'>
            <span class='shop_button completeAddAddon' style='width:100%; box-sizing: border-box;left:0px; margin-bottom: 5px;'>Add addon</span>
            <input type='hidden' gsname='productId' value='<?php echo $addonItem->productId; ?>'>
            <input type='hidden' gsname='quickadd' value='<?php echo $quickadd; ?>'>
            <select style='width:100%' class='typeofaddon gsniceselect1' gsname='periode_selection'>
                <?php
                foreach($addPeriodeTypes as $id => $type) {
                    $selected = ($id == $selectedType) ? "SELECTED" : "";
                    echo "<option value='$id' $selected>$type</option>";
                }
                ?>
            </select>
            <input type='checkbox' gsname='isperguest' <?php echo $perGuest; ?>> Is per guest
            <div>
                <input type='checkbox' gsname='includedInRoomPrice' <?php echo $includedInRoomPrice; ?>> Is included in room price
            </div>
            <div class='optionpanel' type='repeat_weekly'>
                <div class='weekdayselectionbox'><input type='checkbox' class='weekdayselection' gsname='repeat_mon'> Monday</div>
                <div class='weekdayselectionbox'><input type='checkbox' class='weekdayselection' gsname='repeat_tue'> Tuesday</div>
                <div class='weekdayselectionbox'><input type='checkbox' class='weekdayselection' gsname='repeat_wed'> Wednesday</div>
                <div class='weekdayselectionbox'><input type='checkbox' class='weekdayselection' gsname='repeat_thu'> Thursday</div>
                <div class='weekdayselectionbox'><input type='checkbox' class='weekdayselection' gsname='repeat_fri'> Friday</div>
                <div class='weekdayselectionbox'><input type='checkbox' class='weekdayselection' gsname='repeat_sat'> Saturday</div>
                <div class='weekdayselectionbox'><input type='checkbox' class='weekdayselection' gsname='repeat_sun'> Sunday</div>
            </div>
        </div>
        <div></div>
        <br>
        <div gstype='form' method='addAdvancedAddons'>
            <input type='hidden' gsname='productId' value='<?php echo $addonItem->productId; ?>'>
            <input type='hidden' gsname='quickadd' value='<?php echo $quickadd; ?>'>
            <div class='addonpreview'></div>
            <br>
            Text on order<br>
            <input type="text" placeholder="Title" gsname='name' class='gsniceinput1' style="width:100%;box-sizing: border-box;margin-bottom:6px;" value='<?php echo $addonProduct->name; ?> '><br>
        </div>
    </div>

    <style>
        .optionpanel { display: none; }
        .addonpreview { max-height: 300px; overflow-y: auto;}
        .weekdayselectionbox { display:inline-block; width: 110px;}
    </style>

    <script>
        $('.PmsAddAddonsList .typeofaddon').on('change', function() {
            var type = $(this).val();
            $('.PmsAddAddonsList .optionpanel').hide();
            $('.PmsAddAddonsList .optionpanel[type="'+type+'"]').show();
            app.PmsAddAddonsList.loadAddonsToBeAddedList();
        });

        $('.weekdayselection').on('click', app.PmsAddAddonsList.loadAddonsToBeAddedList);
        $('input[gsname="isperguest"]').on('click', app.PmsAddAddonsList.loadAddonsToBeAddedList);
        $('input[gsname="dayofmonth"]').on('keyup', app.PmsAddAddonsList.loadAddonsToBeAddedList);
        app.PmsAddAddonsList.loadAddonsToBeAddedList();

        $('.addonpaneltitle').html('<?php echo $addonProduct->name; ?>');
    </script>