<?
/* @var $this ns_bce90759_5488_442b_b46c_a6585f353cfe\EcommerceOrderView */
$order = $this->getOrder();
?>
<div class="insideheader">
    <?
    echo $this->__f("Accounting details");
    ?> 
</div>
<div class="row">
    <div class="col col1">
        <?
        echo $this->__f("Date to be transferred");
        ?>
    </div>
    <div class="col col2">
        <?
        echo isset($order->transferToAccountingDate) ? $order->transferToAccountingDate : "N/A";
        ?>
    </div>
</div>
<div class="row">
    <div class="col col1">
        <?
        echo $this->__f("Should have been transferred");
        ?>
    </div>
    <div class="col col2">
        <?
        echo isset($order->shouldHaveBeenTransferredToAccountingOnDate) ? $order->shouldHaveBeenTransferredToAccountingOnDate : "N/A";
        ?>
    </div>
</div>
<div class="row">
    <div class="col col1">
        <?
        echo $this->__f("Is transferred");
        ?>
    </div>
    <div class="col col2">
        <?
        echo $order->transferredToAccountingSystem ? $this->__f("Yes") : $this->__f("No");
        ?>
    </div>
</div>
<div class="row">
    <div class="col col1">
        <?
        echo $this->__f("Tried to transfer");
        ?>
    </div>
    <div class="col col2">
        <?
        echo $order->triedTransferredToAccountingSystem ? $this->__f("Yes") : $this->__f("No");
        ?>
    </div>
</div>

<br/>
<?
if ($order->transferredToAccountingSystem) {
?>
<br/><div gsclick="markForResending" id="<? echo $order->id; ?>" class="shop_button"><? echo $this->__f("Mark for resending to accounting"); ?></div>
<?
}
?>

<?
$directTransfer = $this->getApi()->getGetShopAccountingManager()->canOrderBeTransferredDirect($order->id);
if ($directTransfer && !$order->transferredToAccountingSystem) {
?>
    <br/>
    <div class='gserrorfield' id='errorMessage'></div>
    <br/><div  gsclick="directTransferOrder" id="<? echo $order->id; ?>" class="shop_button"><? echo $this->__f("Transfer to accounting"); ?></div>
<?
}
?>