<?
/* @var $this ns_bce90759_5488_442b_b46c_a6585f353cfe\EcommerceOrderView */
$order = $this->getOrder();
if(!$order->closed) {
    ?>
    <div gstype='form' method='saveOrderDate'>
        <div class="insideheader">
            <? echo $this->__f("Created date"); ?>
        </div>
        <input type='hidden' gsname='orderid' value='<?php echo $order->id; ?>'>
        <input type="txt" gsname="date" class='gsniceinput1' value="<?php echo date("d.m.Y H:i", strtotime($order->rowCreatedDate)); ?>">
        <span class='shop_button' gstype='submit' gs_callback="app.EcommerceOrderList.refreshOrderRow('<?php echo $order->id; ?>')">Change order date</span>
    </div>
<?php } ?>
<div gstype='form' method='saveInvoiceNote'>
    <input type='hidden' gsname='orderid' value='<?php echo $order->id; ?>'>
    <div class="insideheader">
        <? echo $this->__f("Note"); ?>
    </div>
    <textarea gsname='invoiceNote' class='gsniceinput1 invoiceNote'><? echo isset($order->invoiceNote) ? $order->invoiceNote : ""; ?></textarea>
    <?php if(!$order->manuallyClosed) { ?>
        <span class='shop_button' gstype='submit' gs_callback="app.EcommerceOrderList.refreshOrderRow('<?php echo $order->id; ?>')">Save</span>
    <?php } ?>
</div>