<?
/* @var $this ns_bce90759_5488_442b_b46c_a6585f353cfe\EcommerceOrderView */
$order = $this->getOrder();
$cart = $order->cart;

$moreItems = 0;
$totalcount = 0;
$totalcost = 0;
$display = true;
$closed = $order->closed;
$disabled = "";
if($closed) {
    $disabled = "DISABLED";
}
if($order->manuallyClosed) {
    $closed = true;
}

foreach ($cart->items as $item) {
    $ids = (array)$this->getExternalReferenceIds();
    if(sizeof($ids) > 0) {
        if(!in_array($item->product->externalReferenceId, $ids)) {
            $moreItems++;
//            $display = false;
        } else {
            $totalcount += $item->count;
            $totalcost += ($item->count * $item->product->price);
        }
    }
    $product = $item->product;
    $start = "";
    $end = "";
    if($item->startDate) { $start = date("d.m.Y", strtotime($item->startDate)); }
    if($item->endDate) { $end = date("d.m.Y", strtotime($item->endDate)); }
    $displayStyle = "";
    if(!$display) {
        $displayStyle = "display:none;";
    }
    $hasSpecialItems = false;
    if(sizeof((array)$item->priceMatrix) > 0) {
        $hasSpecialItems = true;
    }
    if(isset($item->itemsAdded) && $item->itemsAdded && sizeof((array)$item->itemsAdded) > 0) {
        $hasSpecialItems = true;
    }
    $disabledCountAndPrice = "";
    if($hasSpecialItems) {
        $disabledCountAndPrice = "disabled";
    }
    $room = "";
    if(isset($item->product->additionalMetaData)) {
        $room = $item->product->additionalMetaData;
    }
    
    ?>
    <div class="cartitem open" style='<?php echo $displayStyle; ?>'>
        <span class='specialeditview'></span>
        <?php if(!$closed) { ?>
            <i class='fa fa-trash-o removecartitemtfromorder' style='cursor:pointer;' orderid='<?php echo $order->id; ?>' itemid='<?php echo $item->cartItemId; ?>'></i> 
        <?php } ?>
        <input gsname='<? echo $item->cartItemId; ?>_startdate' class="gsniceinput1 startdate" value="<? echo $start; ?>"  <?php echo $disabled; ?>/>
        <input gsname='<? echo $item->cartItemId; ?>_enddate' class="gsniceinput1 enddate" value="<? echo $end; ?>" <?php echo $disabled; ?>/>
        <input gsname='<? echo $item->cartItemId; ?>_productname' class="gsniceinput1 product" value="<? echo $product->name; ?>" <?php echo $disabled; ?>/>
        <input gsname='<? echo $item->cartItemId; ?>_additionalMetaData' class="gsniceinput1 additionalMetaData" value="<? echo $room; ?>" <?php echo $disabled; ?>/>
        <input gsname='<? echo $item->cartItemId; ?>_metaData' class="gsniceinput1 metaData" value="<? echo $item->product->metaData; ?>" <?php echo $disabled; ?>/>
        <input gsname='<? echo $item->cartItemId; ?>_count' class="gsniceinput1 count" value="<? echo $item->count; ?>" <?php echo $disabledCountAndPrice; ?> <?php echo $disabled; ?>/>
        x <input gsname='<? echo $item->cartItemId; ?>_price' class="gsniceinput1 price" value="<? echo $product->price; ?>" <?php echo $disabledCountAndPrice; ?> <?php echo $disabled; ?>/>
        <?php 
        if($hasSpecialItems && !$closed) {
            echo "<i class='fa fa-edit specialedit' itemid='".$item->cartItemId."' orderid='".$order->id."' style='cursor:pointer;'></i>";
        }
        ?>
    </div>
    <?
}

if($moreItems > 0) {
    ?>
    <div class="cartitem header">
        <span class="startdate"></span>
        <span class="enddate"></span>
        <span class="product"></span>
        <span class="additionalMetaData"></span>
        <span class="metaData"></span>
        <span class="count"><? echo $totalcount; ?></span>
        &nbsp;&nbsp;&nbsp;<span class="price"><? echo $totalcost; ?></span>
    </div>
    <?php
//    echo "There are " . $moreItems . " more items to this order, <span style='color:blue; cursor:pointer;' onclick='$(\".cartitem\").show();'>display them.</span>";
}
if(!$closed) {
    ?>
    <div style='text-align: right; margin-top:10px;'>
        <span class='shop_button' gstype='submit' gs_callback="app.EcommerceOrderList.refreshOrderRow('<?php echo $order->id; ?>')">Save orderlines</span>
    </div>
<?php } ?>