<?
/* @var $this ns_bce90759_5488_442b_b46c_a6585f353cfe\EcommerceOrderView */
$this->setData();
$order = $this->getOrder();

$user = $this->getApi()->getUserManager()->getUserById($order->userId);

if (!$user) {
    echo $this->__f("Not available");
} else {
    $user->address = $order->cart->address;
    $user->emailAddress = $order->cart->address->emailAddress;
    $user->prefix = $order->cart->address->prefix;
    $user->cellPhone = $order->cart->address->phone;
    if(isset($order->cart->address->fullName)) {
        $user->fullName = $order->cart->address->fullName;
    }
    
    $quser = new \ns_b5e9370e_121f_414d_bda2_74df44010c3b\GetShopQuickUser();
    $quser->setUser($user);
    $quser->printEditDirect = true;
    $quser->hideWarning = true;
    $quser->avoidSaving = true;
    $quser->renderApplication(true, $this);
}
?>