<?
/* @var $this \ns_acb219a1_4a76_4ead_b0dd_6f3ba3776421\CrmCustomerView */
$user = $this->getUser();
?>
<div class="insideheader"><? echo $this->__f("Accounting details"); ?></div>
<div class="row">
    <div class="col col1">
        <? echo $this->__f("Accounting user id"); ?>
    </div>
    <div class="col col2">
        <input class="gsniceinput1" gsname="accountingId" value="<? echo $user->accountingId; ?>"/>
    </div>
</div>

<div class="row">
    <div class="col col1">
        <? echo $this->__f("External accounting id"); ?>
    </div>
    <div class="col col2">
        <input class="gsniceinput1" gsname="externalAccountingId" value="<? echo $user->externalAccountingId; ?>"/>
    </div>
</div>