<?
/* @var $this \ns_acb219a1_4a76_4ead_b0dd_6f3ba3776421\CrmCustomerView */
$user = $this->getUser();

?>

<div class="insideheader"><? echo $this->__f("Admins"); ?></div>

<div class="row">
    <div class="col col1">
        <? echo $this->__f("Can change page layout"); ?>
    </div>
    
    <div class="col col2">
        <input gsname="canchangepagelayout" <? echo $user->canChangeLayout ? "checked='true'" : ""; ?> type="checkbox" class="gsnicecheckbox1"/>
    </div>
</div>
