<?php
/* @var $this \ns_acb219a1_4a76_4ead_b0dd_6f3ba3776421\CrmCustomerView */
$domains = $this->getDomains();
$user = $this->getUser();
?>
<div class='header'>Bookings registered</div>
<?php
foreach($domains as $domain) {
    echo $domain . "<br>";
    $filter = new core_pmsmanager_PmsBookingFilter();
    $filter->userId = $user->id;
    $bookings = $this->getApi()->getPmsManager()->getAllBookings($domain, $filter);
    
    
}
?>