<?php
 /* @var $this \ns_7b68e527_b6fe_4d56_8628_0f981e0b87eb\UsersRow */
$user = $this->getUser();
?>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "overview") { echo "selectedmenuentry"; } ?>' area='overview'>Overview</div>
<?php
if($user->primaryCompanyUser) {
    ?>
    <div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "subaccounts") { echo "selectedmenuentry"; } ?>' area='subaccounts'>Subaccounts</div>
    <?php
}
?>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "password") { echo "selectedmenuentry"; } ?>' area='password'>Password</div>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "payments") { echo "selectedmenuentry"; } ?>' area='payments'>Payments</div>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "bookings") { echo "selectedmenuentry"; } ?>' area='bookings'>Bookings</div>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "discounts") { echo "selectedmenuentry"; } ?>' area='discounts'>Discounts</div>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "savedcards") { echo "selectedmenuentry"; } ?>' area='savedcards'>Saved cards</div>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "settings") { echo "selectedmenuentry"; } ?>' area='settings'>Settings</div>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "accounting") { echo "selectedmenuentry"; } ?>' area='accounting'>Accounting</div>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "modules") { echo "selectedmenuentry"; } ?>' area='modules'>Modules</div>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "pms") { echo "selectedmenuentry"; } ?>' area='pms'>PMS</div>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "salespoint") { echo "selectedmenuentry"; } ?>' area='salespoint'>SalesPoint</div>
<div class='menuentry crmmenuentry <?php if($this->getSelectedArea() == "getshopexpress") { echo "selectedmenuentry"; } ?>' area='getshopexpress'>GetShop.express</div>
