<?
/* @var $this \ns_acb219a1_4a76_4ead_b0dd_6f3ba3776421\CrmCustomerView */
$user = $this->getUser();
?>
<div gstype="form" method="saveCumsterDetails">
    <input type="hidden" gsname='userid' value="<?php echo $user->id; ?>">
    <table width='100%'>
        <tr>
            <td valign='top' width='50%'>
                <div gstype='form' method='updateUser'>
                    <div class="header"><? echo $this->__f("Customer details"); ?></div>
                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("GetShop id"); ?>
                        </div>
                        <div class="col col2"><?php echo $user->customerId; ?></div>
                    </div>

                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("Name"); ?>
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="fullName" value="<? echo $user->fullName; ?>"/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("Email"); ?>
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="emailAddress" value="<? echo $user->emailAddress; ?>"/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("Phone prefix"); ?>
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="prefix" value="<? echo $user->prefix; ?>"/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("Cellphone"); ?>
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="cellPhone" value="<? echo $user->cellPhone; ?>"/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("Invoice email"); ?>
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="emailAddressToInvoice" value="<? echo $user->emailAddressToInvoice; ?>"/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("Default due dates"); ?><br>
                            -1 means using standard.
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="defaultDueDate" value="<? echo $user->defaultDueDate; ?>"/>
                        </div>
                    </div>

                    <div class='header'><? echo $this->__f("Address"); ?></div>
                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("Name"); ?>
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="address_fullname" value="<? echo @$user->address->fullName; ?>"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("Address"); ?>
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="address_address" value="<? echo @$user->address->address; ?>"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("C/O"); ?>
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="address_co" value="<? echo @$user->address->co; ?>"/>
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("Post code"); ?>
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="address_postcode" value="<? echo @$user->address->postCode; ?>"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col1">
                            <? echo $this->__f("City"); ?>
                        </div>
                        <div class="col col2">
                            <input class="gsniceinput1" gsname="address_city" value="<? echo @$user->address->city; ?>"/>
                        </div>
                    </div>
                </div>
            </td>
            <td valign='top'>
                <?php
                $this->includefile("companydetails");
                ?>
            </td>
        </tr>
    </table>


    <div class='footer'>
        <span class='shop_button' gstype='submit' gs_callback='app.CrmCustomerView.success'>Save details</span>
    </div>
</div>