<?
/* @var $this ns_acb219a1_4a76_4ead_b0dd_6f3ba3776421\CrmCustomerView */
$tokens = array();
if ($this->getUser()->id == ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->id) {
    $tokens = $this->getApi()->getUserManager()->getTokenList();
}
?>
<div gstype='form' method='changePassword'>
    <div class="header"><? echo $this->__f("Password"); ?></div>
    <div class="row">
        <input class="gsniceinput1" gsname="password" value=""/><span class='shop_button' gstype='submit' gs_callback='app.CrmCustomerView.success'>Update password</span>
    </div>
</div>

<?
if (count($tokens)) {
?>
<div>
    <h2>Login tokens</h2>
    <?
    $i = 0;
    foreach ($tokens as $token) {
        $i++;
        echo "<div>$i - ".$token->lastUsed."</div>";
    }
    ?>
    <div gsclick='clearTokenList' class='shop_button'> Clear tokens </div>
</div>
<? } ?>
