<div class='settingsarea'>
    <div class="header"><? echo $this->__f("Settings"); ?></div>
    <?
    /* @var $this \ns_acb219a1_4a76_4ead_b0dd_6f3ba3776421\CrmCustomerView */
    $user = $this->getUser();
    ?>
    <div gstype='form' method='saveUserSettings'>

        <div class="row">
            <div class="col col1">
                <? echo $this->__f("Account type"); ?>
            </div>

            <div class="col col2">
                <select gsname="type" class="gsniceselect1">
                    <option <? echo $user->type == 10 ? 'selected="true"' : ''; ?> value="10"><? echo $this->__f("Customer"); ?></option>
                    <option <? echo $user->type == 50 ? 'selected="true"' : ''; ?> value="50"><? echo $this->__f("Editor"); ?></option>
                    <option <? echo $user->type == 100 ? 'selected="true"' : ''; ?> value="100"><? echo $this->__f("Administrator"); ?></option>
                </select>
            </div>
        </div>

    <?
        if ($user->type == 100) {
            $this->includefile("adminsettings");
        }
    ?>
    <div class='footer'>
        <span class='shop_button' gs_callback='app.CrmCustomerView.success' gstype='submit'>Save settings</span>
    </div>
    <div class='footer'>
        <span class='shop_button' gsclick='deleteUser' style='background-color:red' userid='<?php echo $user->id; ?>' gs_confirm="Are you sure?">Delete this user</span>
    </div>
        
        
</div>
