<?php
/* @var $this ns_acb219a1_4a76_4ead_b0dd_6f3ba3776421\CrmCustomerView */
$user = $this->getUser();
$company = $user->companyObject;
$users = $this->getApi()->getUserManager()->getUsersByCompanyId($company->id);
$filteredUsers = array();
foreach($users as $usr) {
    if($usr->id == $user->id) {
        continue;
    }
    $filteredUsers[] = $usr;
}
//echo "<pre>";
//print_r($users);
//echo "</pre>";

$attributes = array(
            array('id', 'gs_hidden', 'id'),
            array('rowCreatedDate', 'CREATED', null, 'formatRowCreatedDate'),
            array('fullname', 'NAME', 'fullName'),
            array('email', 'EMAIL', 'emailAddress'),
            array('callPhone', 'PHONE', 'cellPhone'),
);

$table = new \GetShopModuleTable($this, 'CrmCustomerView', 'loadBooking', 'loadUser', $attributes);
$table->setData($filteredUsers);
$table->render();
?>
<div class='footer'>
    <span class='shop_button'>Add subaccount</span>
</div>