<?
/* @var $this ns_5278fb21_3c0a_4ea1_b282_be1b76896a4b\SedoxDownloadHistory */
/* @var $product core_sedox_SedoxProduct */

$product = $this->getCurrentProduct();
$productName = $product->printableName;
$creditPrice = $this->getApi()->getSedoxProductManager()->getPriceForProduct($product->id, [$product->binaryFiles[0]->id]);

if (!function_exists("sedox_notAvailableCheck")) {
    function sedox_notAvailableCheck($input) {
        if (!$input) {
            return "N/A";
        }

        return $input;
    }
}
?>
<div class="sedox_internal_view">
    <div class="innerview" productid="<? echo $product->id; ?>">
        <div class='title boldFont'>
            <i class='fa fa-file'></i> <? echo $productName; ?>
        </div>
        <div class='downloadinfo'>
            <? $this->includefile("productdetails", "ns_4f89c95c_99dc_4ed7_9352_1e1c51f4630c"); ?>
        </div>

        <div class='fileinfo'>
            <div class='box_header boldFont'>
                Project Details
                <div class='subinfo'>
                    Created: <? echo $product->rowCreatedDate; ?>
                </div>
            </div>

            <div class='box_content'>
                <div class='row_type2'>
                    Orig. Checksum:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->originalChecksum); ?></div>
                </div>

                <div class='row_type2'>
                    Reference:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck(@$product->reference->{ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->id}); ?></div>
                </div>

                <div class='row_type2'>
                    ECU Brand / Type:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->ecuBrand); ?></div>
                </div>

                <div class='row_type2'>
                    ECU Part No.:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->ecuPartNumber); ?></div>
                </div>

                <div class='row_type2'>
                    ECU Hardware No.:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->ecuHardwareNumber); ?></div>
                </div>

                <div class='row_type2'>
                    ECU Software No.:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->ecuSoftwareNumber); ?></div>
                </div>

                <div class='row_type2'>
                    ECU Version:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->ecuSoftwareVersion); ?></div>
                </div>

                <div class='row_type2'>
                    File Size:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->softwareSize); ?></div>
                </div>

                <div class='row_type2'>
                    Tool:
                    <div class='row_subinfo'><? echo sedox_notAvailableCheck($product->tool); ?></div>
                </div>
            </div>            
        </div>    
        
        <div class='creditinformation'>
            <div class='sedox_blue_button'>Purchase Credits</div> 
            All files at this page are developed by Sedox Performance.
             <div class='redinfo'>Download is not available unless you have credit at your account.</div>
             
                 
         </div>
    </div>
    
</div>