<?
$product = $this->getCurrentProduct();
$productName = $product->printableName;
$creditPrice = $this->getApi()->getSedoxProductManager()->getPriceForProduct($product->id, [$product->binaryFiles[0]->id]);

?>
<div class='box_header boldFont'>
    Download Information
</div>
<div class='box_content'>
    <?
    echo "<select class='fileselector'>";
    foreach ($product->binaryFiles as $binFile) {
        $checksumCorrect = $binFile->checksumCorrected ? "Yes" : "No";
        $extraInfo = sedox_notAvailableCheck($binFile->extraInformation);
        
         $extraRequests = "";

            if($binFile->options->requested_adblue) {
                $extraRequests .= "AdBlue, ";
            }
            if($binFile->options->requested_decat) {
                $extraRequests .= "Decat, ";
            }
            if($binFile->options->requested_dpf) {
                $extraRequests .= "DPF, ";
            }
            if($binFile->options->requested_dtc) {
                $extraRequests .= "DTC, ";
            }
            if($binFile->options->requested_egr) {
                $extraRequests .= "EGR, ";
            }
            if($binFile->options->requested_vmax) {
                $extraRequests .= "Vmax, ";
            }
            if($extraRequests != "") {
                $extraRequests = substr($extraRequests, 0, -2);
            }

            if($binFile->fileType == "Original") {
                $origRequestType = $binFile->options->requested_remaptype;
                $originalExtraRequests = $extraRequests;
            }

            if ($this->isSelected($product->id, $binFile->id)) {
                $_POST['data']['fileId'] = $binFile->id;
            }

            $checksumCorrect = $binFile->checksumCorrected ? "Yes" : "No";
            $selected = $this->isSelected($product->id, $binFile->id) ? "selected='true'" : "";
            $extraInfo = $binFile->extraInformation . ($binFile->extraInformation != "" && $extraRequests != "" ? " - " : "") . $extraRequests;
            if (strtolower($binFile->fileType) == "original" || strtolower($binFile->fileType) == "cmdencrypted") {
                $extraInfo = "";
            }
            
            $starIndicator = $extraInfo ? "*" : "";
        
        echo "<option checksumupdated='$checksumCorrect' extrainfo='$extraInfo' admintools='N/A' value='$binFile->id'>" . $starIndicator . $binFile->fileType . "</option>";
    }
    echo "</select>";
    ?>

    <div class='row_type1'>
        Checksum updated:
        <div class='row_subinfo' lookingfor="checksumupdated">-</div>
    </div>

    <div class='row_type1'>
        Extra information:
        <div class='row_subinfo extra_info_text' lookingfor="extrainfo">-</div>
    </div>

    <div class='row_type1'>
        Admin Tools:
        <div class='row_subinfo' lookingfor="admintools">-</div>
    </div>

    <div class='priceview'>
        <div class='price boldFont'><? echo $creditPrice; ?></div>
        <div class='pricetext boldFont'>CREDITS</div>
        <div class='sedox_blue_button action_purchase_product' productId="<? echo $product->id; ?>" sedox_file_id="">Purchase and Download</div>
    </div>
</div>