<?
/* @var $this ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBooking */
$pmsBooking = $this->getPmsBooking();
?>
<div class="bookinginformation">
    <div class=" row">
        <div class="col col1"><i class="fa fa-key"></i><? echo $this->__f("GetShop booking id"); ?></div>
        <div class="col col2"><? echo $pmsBooking->incrementBookingId; ?></div>    
    </div>
    
    <div class=" row">
        <div class="col col1"><? echo $this->__f("GetShop booking id"); ?></div>
        <div class="col col2"><? echo $pmsBooking->incrementBookingId; ?></div>    
    </div>
    
</div>
