<?
/* @var $this ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBooking */
$pmsBooking = $this->getPmsBooking();
$bookingEngineBooking = $this->getBookingEngineBooking();
$pmsSelectedRoom = $this->getSelectedRoom();
$user = $this->getUserForBooking();

$disabled = "";
if ($user->isTransferredToAccountSystem && $config->denyUpdateUserWhenTransferredToAccounting) {
    $disabled = "DISABLED";
}
$paymentApps = (array) $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
if ($user->type > 10) {
    $disabled = "DISABLED";
}
?>
<div gstype="form" method="saveUser">
    <input type="hidden" gsname="userid" value="<? echo $user->id; ?>"/>
    <input type="hidden" gsname="id" value="<? echo $bookingEngineBooking->id; ?>"/>
    <input type="hidden" gsname="roomId" value="<? echo $pmsSelectedRoom->pmsBookingRoomId; ?>"/>
    <?

    if ($user->companyObject) { ?>
        <div class='row'>
            <div class='col col1'>Orgid</div>
            <div class='col col'><input class='gsniceinput1' type="txt" gsname="fullName" value="<?php echo $user->companyObject->vatNumber; ?>" DISABLED></div>
        </div>
    <?php } ?>

    <div class="warning">
        <i class="fa fa-warning"></i> <? echo $this->__f("When you update information here, you will change it for all other bookings connected to this user."); ?>
        <br/><i class="fa fa-info-circle"></i> <? echo $this->__f("The name of the booker, if a company this is the company name. If its a private person its the name of the person."); ?>
    </div>

    <div class="colbox">
        <div class='row'><div class='col col1'>Name</div><div class='col col'><input class='gsniceinput1 fullName 'type="txt" gsname="fullName" value="<?php echo $user->fullName; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Prefix</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="prefix" value="<?php echo $user->prefix; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Phone</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="cellPhone" value="<?php echo $user->cellPhone; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Email</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="emailAddress" value="<?php echo $user->emailAddress; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Address</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="address.address" value="<?php echo $user->address ? $user->address->address : ""; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Postcode</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="address.postCode" value="<?php echo $user->address ? $user->address->postCode : ""; ?>" <?php echo $disabled; ?>></div></div>
    </div>
    <div class="colbox">
        <div class='row'><div class='col col1'>City</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="address.city" value="<?php echo $user->address ? $user->address->city : ""; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Birthdate</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="birthDay" value="<?php echo $user->birthDay; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Relationship</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="relationship" value="<?php echo $user->relationship; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'>
            <div class='col col1'>Payment type</div>
            <div class='col col2'>
                <select class="gsniceselect1" gsname='preferredpaymenttype' <?php echo $disabled; ?>>
                    <?php
                    echo "<option value='' $selected>Default</option>";
                    foreach ($paymentApps as $id => $type) {
                        $selected = "";
                        $instance = $this->getFactory()->getApplicationPool()->createInstace($type);
                        if ($type->id == $user->preferredPaymentType) {
                            $selected = "SELECTED";
                        }
                        if (method_exists($instance, "getName")) {
                            echo "<option value='" . $type->id . "' $selected>" . $instance->getName() . "</option>";
                        }
                    }
                    ?>
                </select>

            </div>
        </div>

        <?php
        if ($this->hasAccountingTransfer()) {
            $accId = $user->customerId;
            if ($user->accountingId) {
                $accId = $user->accountingId;
            }
            if ($accId == -1 || $accId == "-1") {
                $accId = "";
            }
            ?>
            <div class='row'>
                <div class='col col1'>Accounting id</div><div class='col col1'>
                    <input class='gsniceinput1' type="txt" gsname="accountingId" value="<?php echo $accId; ?>" disabled>
                </div>

                <div class='col col2'>
                <?php
                if ($user->isTransferredToAccountSystem && $config->denyUpdateUserWhenTransferredToAccounting) {
                    echo "This user has been transferred to accounting, and can not be updated anymore.";
                }
                ?>
                </div>
            </div>
        <?php
            }
        ?>

        <div class='row'>
            <div class="col col1">Country</div>
            <div class='col col2'>
                <select  class="gsniceselect1" gsname='countryCode'>
                    <option value=''>No default country set</option>
                    <?php
                    foreach (CountryCodes::getCodes() as $code => $country) {
                        $selected = "";
                        if ($user->address->countrycode == $code) {
                            $selected = "SELECTED";
                        }
                        echo "<option value='$code' $selected>$country</option>";
                    }
                    ?>
                </select>
            </div>
        </div>
    </div>

    <div class='row' style="text-align: right; padding-top: 5px;">
        <div class="shop_button show_edit_user">
            <i class="fa fa-close"></i> <? echo $this->__f("Close"); ?>
        </div>
        <div class="shop_button" gstype="submit" gs_callback="app.PmsSearchBooking.userUpdated">
            <i class="fa fa-save"></i> <? echo $this->__f("Save"); ?>
        </div>
    </div>

</div>