<?
/* @var $this ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBooking */
$filter = $this->getSelectedFilter();
$channels = (array)$this->getChannelMatrix();
$start = date('d.m.Y', strtotime($filter->startDate));
$end = date('d.m.Y', strtotime($filter->endDate));


?>


<div class="filterbox" gstype="form" method="setFilter">

    <div class='quickfilters'>
        <div class="header"><? echo $this->__f("Quick Filters"); ?></div>
        <div><b><i class="fa fa-download"></i> <? echo $this->__f("Checkin"); ?></b></div>
        <div class='quickfilter_sub' gsclick="showCheckins" day="-1"><? echo $this->__f("Yesterday"); ?></div>
        <div class='quickfilter_sub' gsclick="showCheckins" day="0"><? echo $this->__f("Today"); ?></div>
        <div class='quickfilter_sub' gsclick="showCheckins" day="1"><? echo $this->__f("Tomorrow"); ?></div>

        <div style="border-top: solid 1px #DDD; padding-top: 10px;"><b><i class="fa fa-upload"></i> <? echo $this->__f("Checkout"); ?></b></div>
        <div class='quickfilter_sub' gsclick="showCheckouts" day="-1"><? echo $this->__f("Yesterday"); ?></div>
        <div class='quickfilter_sub' gsclick="showCheckouts" day="0"><? echo $this->__f("Today"); ?></div>
        <div class='quickfilter_sub' gsclick="showCheckouts" day="1"><? echo $this->__f("Tomorrow"); ?></div>
    </div>

    <div class="searchbox">
        <div class="tabs">
            <div class="tab active" tab="simple"><? echo $this->__f("Simple"); ?> </div>
            <div class="tab" tab="advanced"><? echo $this->__f("Advanced"); ?> </div>
        </div>
        
        <div class="tab_content active" tab="simple" gstype="form" method="searchBooking">
            <h2><? echo $this->__f("Search"); ?></h2>
            <input gsname="searchtext" gstype="submitenter" class="gsniceinput1" placeholder="<? echo $this->__f("Freetext"); ?>" value="<? echo $filter->searchWord; ?>"/>
            <div class="buttonareaadvanced">
                <div class="shop_button" gstype="submit"><i class="fa fa-search"></i> <? echo $this->__f("Search"); ?></div>     
            </div>
            
        </div>

        <div class="tab_content" tab="advanced">
            <div>
                <div class="startdate"><input class="gsniceinput1" gsname="startdate" value="<? echo $start; ?>"></div>
                <div class="enddate"><input class="gsniceinput1" gsname="enddate" value="<? echo $end; ?>"></div>

                <div class="dropdowns">
                    <select class="managementviewdropdowninput filterType gsniceselect1" gsname="filterType">
                        <option value="registered">Registered</option>
                        <option value="active"><? echo $this->__f("Active"); ?></option>
                        <option value="uncofirmed"><? echo $this->__f("Unconfirmed"); ?></option>
                        <option value="checkin"><? echo $this->__f("Checking in"); ?></option>
                        <option value="checkout"><? echo $this->__f("Checking out"); ?></option>
                        <option value="waiting"><? echo $this->__f("Waiting"); ?></option>
                        <option value="activecheckin"><? echo $this->__f("Checkin + stayover"); ?></option>
                        <option value="activecheckout"><? echo $this->__f("Checkout + stayover"); ?></option>
                        <option value="inhouse"><? echo $this->__f("Inhouse"); ?></option>
                        <option value="stats"><? echo $this->__f("Coverage"); ?></option>
                        <option value="summary"><? echo $this->__f("Summary"); ?></option>
                        <option value="orderstats"><? echo $this->__f("Income report"); ?></option>
                        <option value="afterstayorder"><? echo $this->__f("Order created after stay"); ?></option>
                        <option value="unsettled"><? echo $this->__f("Bookings with unsettled amounts"); ?></option>
                    </select>

                    <? if (sizeof($channels) > 0) { ?>
                        <select class="managementviewdropdowninput gsniceselect1" gsname='channel'>
                            <?php
                            echo "<option value=''>All channels</option>";
                            foreach ($channels as $idx => $channel) {
                                $selected = "";
                                if ($filter->channel == $idx) {
                                    $selected = "SELECTED";
                                }
                                echo "<option value='$idx' $selected>$channel</option>";
                            }
                            ?>
                        </select>
                    <? } ?>
            </div>
                
                <div class="buttonareaadvanced">
                    <div class="shop_button"><i class="fa fa-search"></i> <? echo $this->__f("Update"); ?></div>
                </div>
                
            </div>
        </div>

    </div>

</div>

