<?
/* @var $this ns_f1fc4af3_656e_4294_a268_40d2a82d0aa1\ApplicationSelector */
?>
<div class='gss_settings_header'>
	<i class='fa fa-heart-o'></i>

	<div class='gss_settings_header_description'>
		<div class='gss_settings_header_title'>
			<? echo $this->__f("Applications"); ?>
		</div>
		<div class='gss_settings_header_description_inner'>
			<?
			echo $this->__f("We all have different expectations and requirements for our web solution. By activating apps you can get more or less functionallity into your web solution.");
			?>	
		</div>

	</div>	
</div>

<div class='gss_settings_main_area'>
    <div class='gss_appviews'>
        <?
        $apps = $this->getApi()->getStoreApplicationPool()->getAvailableApplicationsThatIsNotActivated();
        foreach ($apps as $app) {
            $namespace = $this->getFactory()->convertUUIDtoString($app->id);
            $name = $app->appName;
            $emptyInstance = $this->getFactory()->getApplicationPool()->createInstace($app);
            $imgsrc = "/showApplicationImages.php?appNamespace=$namespace&image=$name.png";
            
            if ($app->type == "SystemApplication" || $app->type == "ThemeApplication") {
                continue;
            }
            
            if (!$emptyInstance) {
                continue;
            }
            
            ?>
            <div class='gss_appview'>
                <? echo "<img src='$imgsrc'/>"; ?>
                
                <div class="gss_app_desc">
                    <div style="font-size: 16px; font-weight: 700; margin-bottom: 3px;"><? echo $app->appName; ?></div>
                    <? echo $app->type; ?><br/>
                    <? echo $emptyInstance->getDescription(); ?>
                    
                </div>
                <div gss_method="activate_application" gss_value="<? echo $app->id; ?>" class="gss_activate_button"> <? echo $this->__f("Activate"); ?></div>
            </div>  
            <?
        }
        ?>
        
    </div>
</div>
