<div class="informationboxbannersettings">
    <div class="banner_settings">
        <table>
            <tr><td><? echo $this->__f("Delay (ms)");?></td><td><input type="text"/></td></tr>
        </table>
        <br>
    </div>
    <div>
        <div class='banner_settings_preview'>
            <div class='banner_preview_title'><? echo $this->__f("Your image list"); ?></div>
            <div class='banner_settings_images'>
                <? 
                $banners = $this->getBanners();
                
                if (count($banners) == 0) {
                    echo "<div style='display:block;' class='no_image_text_information'><br>&nbsp;&nbsp;<b>".$this->__f("Dude! you have not uploaded any images yet. Click the add image button")."</b></div>";
                } else {
                    echo "<div class='no_image_text_information'><br>&nbsp;&nbsp;<b>".$this->__f("Dude! you have not uploaded any images yet. Click the add image button")."</b></div>";
                }
                foreach ($banners as $banner) { 
                    $crops = json_decode($banner->crop_cordinates);
                    $cropsData = "";
                    $rotation = isset($banner->rotation) ? $banner->rotation : 0;
                    
                    if ($crops) {
                        $cropsData = $crops->x.":".$crops->y.":".$crops->x2.":".$crops->y2;
                    }
                    
                    ?>
                    <div class='imageholder' rotation="<? echo $rotation; ?>" crops="<? echo $cropsData ?>" imageId="<? echo $banner->imageId; ?>">
                        <div class='innerholder' >
                            <img src="/displayImage.php?id=<? echo $banner->imageId; ?>"/>
                        </div>
                    </div>
                <? } ?>
            </div>
            <span class='gs_button addnewbanner'><? echo $this->__f("Add image"); ?></span>
            <span class='gs_button saveset'><? echo $this->__f("Save"); ?></span>
        </div>    
        
        <div class='banner_image_editor'>
            <div class='image_editor_got_no_image'><? echo $this->__f("Please select an image from you image list"); ?></div>
        </div>
    </div>
</div>
