<?
/* @var $this \ns_b5e9370e_121f_414d_bda2_74df44010c3b\GetShopQuickUser */
$user = $this->user;
if(!$user) {
    echo "No user connected yet.";
    echo "<script>";
    echo "$('.GetShopQuickUser .change_user_form').show();";
    echo "</script>";
    return;
}
$extraArgs = $this->getExtraArgs();

$disabled = "";
if ($user && $user->isTransferredToAccountSystem && $config->denyUpdateUserWhenTransferredToAccounting) {
    $disabled = "DISABLED";
}
$paymentApps = (array) $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
if ($user && $user->type > 10 || ($user && $user->id == "quickreservation")) {
    $disabled = "DISABLED";
}

$invoke = $this->invokeJavascriptFunctionAfterActions;
if(isset($extraArgs['invokeJavascriptFunctionAfterActions'])) {
    $invoke = $extraArgs['invokeJavascriptFunctionAfterActions'];
}
?>
<div gstype="form" method="saveUser" invokeJavascriptFunctionAfterActions='<? echo $invoke; ?>'>
    <?
    $xargs = $this->getExtraArgs();
    
    if($this->avoidSaving || (isset($xargs['avoidsave']) && $xargs['avoidsave'] == "true")) {
        echo "<input type='hidden' gsname='avoidsaving' value='true'>";
    }
    if((isset($xargs['avoidprintuseraftersave']) && $xargs['avoidprintuseraftersave'] == "true")) {
        echo "<input type='hidden' gsname='avoidlistuser' value='true'>";
    }
    if($disabled) {
        echo "<div style='color:red; font-weight: bold; text-align:center; font-size: 16px;'>You can not change the values for this user.</div>";
    }
    foreach ($extraArgs as $key => $value) {
        ?>
        <input type="hidden" gsname="<? echo $key; ?>" value="<? echo $value; ?>"/>
        <?
    }
   
    $extra = "";
    foreach ($extraArgs as $key => $value) {
        $extra .= "$key,";
    }
    ?>
        <input type="hidden" gsname="gs_extras" value="<? echo $extra; ?>"/>
    <?
  
    if ($user && $user->companyObject) { ?>
        <div class='row'>
            <div class='col col1'>Orgid</div>
            <div class='col col'><input class='gsniceinput1' type="txt" gsname="vatNumber" value="<?php echo $user->companyObject->vatNumber; ?>" DISABLED></div>
        </div>
    <?php } ?>

    <input type="hidden" gsname="userid" value="<? echo $user ? $user->id : ""; ?>"/>
    <?php if(!$this->hideWarning && (!isset($this->extraArgs['avoidCloseButton']) || $this->extraArgs['avoidCloseButton'] != "true")) { ?>
        <div class="warning">
            <i class="fa fa-warning"></i> <? echo $this->__f("When you update information here, you will change it for all other bookings connected to this user."); ?>
            <br/><i class="fa fa-info-circle"></i> <? echo $this->__f("The name of the booker, if a company this is the company name. If its a private person its the name of the person."); ?>
        </div>
    <? } ?>

    <div class="colbox">
        <div class='row'><div class='col col1'>Name</div><div class='col col'><input class='gsniceinput1 fullName 'type="txt" gsname="fullName" value="<?php echo $user->fullName; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Prefix</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="prefix" value="<?php echo $user->prefix; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Phone</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="cellPhone" value="<?php echo $user->cellPhone; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Email</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="emailAddress" value="<?php echo $user->emailAddress; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Invoice email</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="emailAddressToInvoice" value="<?php echo $user->emailAddressToInvoice; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Address</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="address.address" value="<?php echo $user->address ? $user->address->address : ""; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Address2</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="address.address2" value="<?php echo $user->address ? $user->address->address2 : ""; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Postcode</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="address.postCode" value="<?php echo $user->address ? $user->address->postCode : ""; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>C/O</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="address.co" value="<?php echo $user->address ? $user->address->co : ""; ?>" <?php echo $disabled; ?>></div></div>
    </div>
    <div class="colbox">
        <div class='row'><div class='col col1'>City</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="address.city" value="<?php echo $user->address ? $user->address->city : ""; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Birthdate</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="birthDay" value="<?php echo $user->birthDay; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Relationship</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="relationship" value="<?php echo $user->relationship; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'><div class='col col1'>Default due days (-1 using standard)</div><div class='col col'><input class='gsniceinput1' type="txt" gsname="defaultDueDate" value="<?php echo $user->defaultDueDate; ?>" <?php echo $disabled; ?>></div></div>
        <div class='row'>
            <div class='col col1'>Payment type</div>
            <div class='col col2'>
                <select class="gsniceselect1" gsname='preferredpaymenttype' <?php echo $disabled; ?>>
                    <?php
                    echo "<option value=''>Default</option>";
                    foreach ($paymentApps as $id => $type) {
                        $selected = "";
                        $instance = $this->getFactory()->getApplicationPool()->createInstace($type);
                        if ($type->id == $user->preferredPaymentType) {
                            $selected = "SELECTED";
                        }
                        if (method_exists($instance, "getName")) {
                            echo "<option value='" . $type->id . "' $selected>" . $instance->getName() . "</option>";
                        }
                    }
                    ?>
                </select>

            </div>
        </div>
        <div class='row'>
            <div class='col col1'>Agreed to campaigns</div>
            <div class='col col2'>
                <select class="gsniceselect1" gsname='agreeToSpam'>
                    <?php
                    $agreed = array();
                    $agreed["false"] = "No";
                    $agreed["true"] = "Yes";
                    
                    foreach($agreed as $val => $name) {
                        $selected = ($val == "true" && $user->agreeToSpam) ? "SELECTED" : "";
                        echo "<option value='$val' $selected>$name</option>";
                    }
                    ?>
                </select>

            </div>
        </div>

        <?php
        if ($this->hasAccountingTransfer()) {
            $accId = $user->customerId;
            if ($user->accountingId) {
                $accId = $user->accountingId;
            }
            if ($accId == -1 || $accId == "-1") {
                $accId = "";
            }
            ?>
            <div class='row'>
                <div class='col col1'>Accounting id</div><div class='col col1'>
                    <input class='gsniceinput1' type="txt" gsname="accountingId" value="<?php echo $accId; ?>" disabled>
                </div>

                <div class='col col2'>
                <?php
                if ($user->isTransferredToAccountSystem && $config->denyUpdateUserWhenTransferredToAccounting) {
                    echo "This user has been transferred to accounting, and can not be updated anymore.";
                }
                ?>
                </div>
            </div>
        <?php
            }
        ?>

        <div class='row'>
            <div class="col col1">Country</div>
            <div class='col col2'>
                <select  class="gsniceselect1" gsname='countryCode'>
                    <option value=''>No default country set</option>
                    <?php
                    foreach (CountryCodes::getCodes() as $code => $country) {
                        $selected = "";
                        if ($user->address->countrycode == $code) {
                            $selected = "SELECTED";
                        }
                        echo "<option value='$code' $selected>$country</option>";
                    }
                    ?>
                </select>
            </div>
        </div>

        <div class='row'>
            <div class="col col1"><span style='line-height: 80px; float:left;'>Additional information</span></div>
            <div class='col col2'><textarea class='additionalDescription' gsname='additionalDescription'><?php echo $user->additionalDescription; ?></textarea></div>
        </div>
    </div>

    <div class='row buttonrow' style="text-align: right; padding-top: 5px;">
        <?php
        if(!$this->printEditDirect) {
            ?>
                <?php if(!isset($this->extraArgs['avoidCloseButton']) || $this->extraArgs['avoidCloseButton'] != "true") { ?>
                    <div class="shop_button show_edit_user">
                        <i class="fa fa-close"></i> <? echo $this->__f("Close"); ?>
                    </div>
                <?php } ?>
            <?php
        }
        
        $name = $this->__f("Save");
        $xtra = $this->getExtraArgs();
        if(isset($xtra['savebtnname'])) {
            $xtra = $xtra['savebtnname'];
        }
        if(isset($xtra['overridesavebutton'])) {
            echo $xtra['overridesavebutton'];
        } else {
            ?>
            <div class="shop_button updateuserbtn">
                <i class="fa fa-save"></i> <? echo $name; ?>
            </div>
            <?php
        }
        ?>
    </div>

</div>