<?
/* @var $this \ns_b5e9370e_121f_414d_bda2_74df44010c3b\GetShopQuickUser */
$user = $this->user;


if (!isset($_POST['data']['searchvalue'])) {
    return;
}

$searchvalue = $_POST['data']['searchvalue'];


if (strlen($searchvalue) < 3) {
    echo $this->__f("Minimum 3 letters");
    return;
}

$extra = "";
foreach ($_POST['data'] as $key => $value) {
    if($key != "userid") {
        $extra .= $key."=\"".$value."\" ";
    }
}

$users = (array)$this->getApi()->getUserManager()->findUsers($searchvalue);
$callback = 'gs_callback="app.GetShopQuickUser.userChanged"';
$extraArgs = $this->getExtraArgs();
if(isset($extraArgs['invokeJavascriptFunctionAfterActions'])) {
    $callback = 'gs_callback="'.$extraArgs['invokeJavascriptFunctionAfterActions'].'"';
}

if(sizeof($users) == 0) {
    return;
}

echo "<h1>Search result</h1>";

foreach ($users as $user) {
    ?>
    <div class="row usersearchrow">
        
        <div class="user_col user_col0"><? echo $user->isCompanyMainContact || $user->primaryCompanyUser ? "<i class='fa fa-industry'></i>" : "<i class='fa fa-user'></i>"; ?></div>
        <div class="user_col user_col1"><? echo $user->fullName; ?></div>
        <div class="user_col user_col2"><? echo $user->emailAddress; ?></div>
        <div class="user_col user_col3"><? echo $user->cellPhone; ?></div>
        <div class="user_col user_col4"> 
           <div class="gs_shop_small_icon" 
                <? echo $extra; ?>
                gsclick="changeUser"
                <?php echo $callback; ?>
                synchron="true"
                userid="<? echo $user->id; ?>"
                >
                    <? echo $this->__f("Select"); ?> <i class="fa fa-arrow-right"></i>
            </div>
        </div>
    </div>
    <?
}
?>