<div class="contentrow firstrow"> 
    <div class="row_inner">
        <?php
        ContentManager::render("menu");
        ?>
    </div>
</div>

<div class="contentrow row_width_degreed"> 
    <div class="row_inner">
        <?php
        ContentManager::render("lunsj");
        ?>
    </div>
</div>

<div class="contentrow"> 
    <div class="row_inner">
        <?php
        ContentManager::render("row_3");
        ?>
    </div>
</div>

<div class="contentrow row_width_degreed"> 
    <div class="row_inner">
        <?php
        ContentManager::render("row_4_menu");
        ?>
    </div>
</div>

<div class="contentrow"> 
    <div class="row_inner">
        <?php
        ContentManager::render("row_5_menu");
        ?>
    </div>
</div>

<div class="contentrow row_width_degreed"> 
    <div class="row_inner">
        <?php
        ContentManager::render("row_6_menu");
        ?>
    </div>
</div>


<div class="contentrow"> 
    <div class="row_inner">
        <?php
        ContentManager::render("row_7_menu");
        ?>
    </div>
</div>

