<?php
/* @var $this \ns_e9d04f19_6eaa_4a17_9b7b_aa387dbaed92\CategoryLister */
?>
<span class='gss_button gss_add_attribute'>Add attribute to product</span>
<br>
<br>

<div class="addedattributes" style="float:right; border: solid 1px #bbb; padding: 10px; background-color:#fff;">
    <h2>Already added attributes</h2>
    <div class='addedattributeslist'>
        
    </div>
</div>

<div id="attributelist">
<?
$list = $this->getApi()->getListManager()->getJsTree("attributes");
$generator = new JsTreeGenerator();
$generator->printTree($list);
?>
</div>
<div style='clear:both;'></div>

<script>
  getshop.jstree.initJsTree("attributelist", "attributes");
</script>