<?
/* @var $this \ns_e073a75a_87c9_4d92_a73a_bc54feb7317f\Products */
$product = $this->getApi()->getProductManager()->getProduct($_POST['value']);
?>

<div class='gss_product_title_header'>
    <? echo $product->name; ?>
</div>

<div class='gss_tabbar'> 
    <div class='gss_tab gss_tab_active' gss_tab='1'><? echo $this->__f("Product info"); ?></div>
    <div class='gss_tab' gss_tab='3'>Images</div>
    <div class='gss_tab' gss_tab='2'>Lists</div>
    <div class='gss_tab_content'>
        <input type="hidden" gs_model='productmodel' gs_model_attr='productid' value="<? echo $product->id; ?>">
        <div class='gss_tab_view gss_tab_active' gss_tab='1'>
            <div class="textfield gss_setting"  id="title">
                <span class="title"><?php echo $this->__f("Product title"); ?></span>
                <input type="textfield" gs_model='productmodel' gs_model_attr='title' value="<? echo $product->name; ?>" placeholder="">
                <div class="description">
                    <?php echo $this->__("This is the title of the product, example \"White cute teddy bear\" "); ?>
                </div>
            </div>

            <div class="textfield gss_setting"  id="price">
                <span class="title"><?php echo $this->__f("Price (inc taxes)"); ?></span>
                <input type="textfield" gs_model='productmodel' gs_model_attr='price' value="<? echo $product->price; ?>"  placeholder="">
                <div class="description">
                    <?php echo $this->__("The total cost of the product, included taxes."); ?>
                </div>
            </div>

            <div class="textfield gss_setting"  id="sku">
                <span class="title"><?php echo $this->__f("SKU"); ?></span>
                <input type="textfield" gs_model='productmodel' gs_model_attr='sku' value="<? echo $product->sku; ?>" placeholder=''>
                <div class="description">
                    <?php echo $this->__("A unique identifier for the product."); ?>
                </div>
            </div>

            <div class="textarea gss_setting"  id="listviewdescription">
                <span class="title"><?php echo $this->__f("Listview description"); ?></span>
                <textarea class='gss_mediumsize' gs_model='productmodel' gs_model_attr='lisviewdescription'><? echo $product->shortDescription; ?></textarea>
                <div class="description">
                    <?php echo $this->__("This description will show up in list views, if blank it will take the first part of the larger description."); ?>
                </div>
            </div>

            <div class='gss_product_more_options_info'>
                <i class='fa fa-info-circle'></i> Looking for more options? You can add much more information to your product by going to the frontend of the product and use GetShop's entire application sortiment like, Images Carousel, YouTube, Facebook etc. The possibilites are endless.
            </div>
        </div>

        <div class='gss_tab_view' gss_tab='2'>
            <?  $this->includefile("productlist"); ?>
        </div>
        

        <div class='gss_tab_view' gss_tab='3'>
            
            <div>
                <div class="gss_image_box1">
                    <i class="fa fa-picture-o"></i>
                    <? echo $this->__f("Below you can see all the pictures, if you want to upload a picture to this product you can simply upload by using the options to the right"); ?>
                </div><div class="gss_image_box3">
                    <i class="fa fa-save gss_product_saveuploadimage" productid="<? echo $product->id; ?>"></i>
                    <? echo $this->__f("Click on the disk above to upload a file."); ?>
                </div>
            </div>
      
            <div class="gss_products_overview" id="gss_product_thumbnails">
                <? 
                $this->includefile("images");
                ?>
            </div>
        </div>
    </div>
</div>

<div class='gss_button_area'>
    <div class='gss_button' gss_confirmation="<? echo $this->__f("Are you sure you want to delete this product?"); ?>" gss_method="deleteProduct" gss_value="<? echo $product->id; ?>"><i class='fa fa-remove'></i><? echo $this->__f("Delete"); ?></div>
    <div class='gss_button' id="gss_gotoproduct" pageid="<? echo $product->pageId; ?>" productId="<? echo \GetShopHelper::makeSeoUrl($product->name); ?>"><i class='fa fa-delicious'></i><? echo $this->__f("View product"); ?></div>
    <div class='gss_button' gss_method="updateProduct" gss_model="productmodel" gss_success_message="<? echo $this->__f("Updated successfully"); ?>"><i class='fa fa-save'></i><? echo $this->__f("Save product"); ?></div>
</div>
