<div class='gss_newproduct'>

    <div class='gss_product_title_header'>
        <? echo $this->__f("Create a new product"); ?>
    </div>

    <div class="textfield gss_setting"  id="title">
        <span class="title"><?php echo $this->__f("Product title"); ?></span>
        <input type="textfield" gs_model='productmodel' gs_model_attr='title' value="" placeholder="">
        <div class="description">
            <?php echo $this->__("This is the title of the product, example \"White cute teddy bear\" "); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="price">
        <span class="title"><?php echo $this->__f("Price (inc taxes)"); ?></span>
        <input type="textfield" gs_model='productmodel' gs_model_attr='price' value="" placeholder="">
        <div class="description">
            <?php echo $this->__("The total cost of the product, included taxes."); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="sku">
        <span class="title"><?php echo $this->__f("SKU"); ?></span>
        <input type="textfield" gs_model='productmodel' gs_model_attr='sku' value="" placeholder=''>
        <div class="description">
            <?php echo $this->__("A unique identifier for the product."); ?>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_success_method="navigateToProduct" gss_method="createProduct" gss_model="productmodel"><i class='fa fa-plus'></i><?php echo $this->__("Create product"); ?></div>
    </div>

</div>