<?
/* @var $this \ns_e073a75a_87c9_4d92_a73a_bc54feb7317f\Products */

$allProducts = $this->getApi()->getProductManager()->getAllProducts();

if(!count($allProducts)) {
    $this->includefile("no_products");
    return;
} 

?>

<div class="textfield gss_setting" style='padding-left: 20px;'>
    <span class="title"><? echo $this->__f("All your products"); ?></span>
    <input type='textfield' placeholder='<? echo $this->__f("Filter products"); ?>'/>
    <div class="description">
        <? echo $this->__f("Below you see a list with all of your products, you can filter it by using the textbox to the right. Click on the product you want to see more information about."); ?>
    </div>
</div>
<?

foreach ($allProducts as $product) {
    ?>
    <div gss_fragment='editproduct' gss_view='gss_productwork_area' gss_value='<? echo $product->id ?>' class='gss_product'>
        <div class='gss_product_inner_desc'>
            <div class='gss_product_title'><? echo $product->name; ?></div>
            <div class='gss_product_price'><? echo $product->price; ?></div>
            <div class='gss_product_created'><? echo $product->rowCreatedDate; ?></div>    
        </div>
        
    </div>
    <?
}
?>