<?php
/* @var $this \ns_e9d04f19_6eaa_4a17_9b7b_aa387dbaed92\CategoryLister */
$product = $this->getApi()->getProductManager()->getProduct($_POST['value']);
?>

<div id="variationslistlist_<? echo $product->id; ?>">
<?
$list = $this->getApi()->getListManager()->getJsTree("variationslist_product_".$product->id);
$generator = new JsTreeGenerator();
$generator->printTree($list);
?>
</div>

<div style='clear:both;'></div>

<script>
    getshop.jstree.initJsTree("variationslistlist_<? echo $product->id; ?>", "variationslist_product_<? echo $product->id; ?>");
<!--</script>--> 