<?php

namespace ns_deab499e_b133_4cb6_a1b2_532018c31d46;

$taxes = $this->getApi()->getProductManager()->getTaxes();
if (!is_array($taxes)) {
    $taxes = [];
}

$shipment = isset($taxes[0]) ? $taxes[0]->taxRate : "";
$group1 = isset($taxes[1]) ? $taxes[1]->taxRate : "";
$group2 = isset($taxes[2]) ? $taxes[2]->taxRate : "";
$group3 = isset($taxes[3]) ? $taxes[3]->taxRate : "";
$group4 = isset($taxes[4]) ? $taxes[4]->taxRate : "";
$group5 = isset($taxes[5]) ? $taxes[5]->taxRate : "";

/* @var $this \ns_deab499e_b133_4cb6_a1b2_532018c31d46\Taxes */
?>

<div class="gss_settings_header">
    <i class="fa fa-dollar"></i>

    <div class="gss_settings_header_description">
        <div class="gss_settings_header_title"> <? echo $this->__f("Taxes"); ?></div>

        <div class="gss_settings_header_description_inner">
            <? echo $this->getDescription(); ?>
        </div>
    </div>	
</div>


<div class='gss_settings_content'>
    <div class="textfield gss_setting"  id="admin">
        <span class="title"><?php echo $this->__f("Activated"); ?></span>
        <div class="gss_onoff" gs_model="taxmodel" gs_model_attr="isactivated">
            <? echo $this->__f("Off"); ?><i class="fa fa-toggle-off"></i><? echo $this->__f("On"); ?>
        </div>
        <div class="description">
            <?php echo $this->__("Please activate this if you want to use taxes in the e-commerce solution"); ?>
        </div>
    </div>

    <div class="textfield gss_setting" id="title">
        <span class="title"><?php echo $this->__("Shipment taxes"); ?></span>
        <input type="textfield" gs_model="taxmodel" gs_model_attr="shipment" value="<? echo $shipment; ?>">
        <div class="description"><?php echo $this->__f("What is the shipment taxes?"); ?></div>
    </div>

    <div class="textfield gss_setting" id="title">
        <span class="title"><?php echo $this->__("Taxgroup") . " 1 (". $this->__f("Default").")"; ?></span>
        <input type="textfield" gs_model="taxmodel" gs_model_attr="group1" value="<? echo $group1; ?>" value="<? echo $group2; ?>">
        <div class="description"><?php echo $this->__f("This tax group will be possible to select in your product management."); ?></div>
    </div>


    <div class="textfield gss_setting" id="title">
        <span class="title"><?php echo $this->__("Taxgroup") . " 2"; ?></span>
        <input type="textfield" gs_model="taxmodel" gs_model_attr="group2" value="<? echo $group2; ?>">
        <div class="description"><?php echo $this->__f("This tax group will be possible to select in your product management."); ?></div>
    </div>


    <div class="textfield gss_setting" id="title">
        <span class="title"><?php echo $this->__("Taxgroup") . " 3"; ?></span>
        <input type="textfield" gs_model="taxmodel" gs_model_attr="group3"  value="<? echo $group3; ?>">
        <div class="description"><?php echo $this->__f("This tax group will be possible to select in your product management."); ?></div>
    </div>


    <div class="textfield gss_setting" id="title">
        <span class="title"><?php echo $this->__("Taxgroup") . " 4"; ?></span>
        <input type="textfield" gs_model="taxmodel" gs_model_attr="group4"  value="<? echo $group4; ?>">
        <div class="description"><?php echo $this->__f("This tax group will be possible to select in your product management."); ?></div>
    </div>


    <div class="textfield gss_setting" id="title">
        <span class="title"><?php echo $this->__("Taxgroup") . " 5"; ?></span>
        <input type="textfield" gs_model="taxmodel" gs_model_attr="group5"  value="<? echo $group5; ?>">
        <div class="description"><?php echo $this->__f("This tax group will be possible to select in your product management."); ?></div>
    </div>


    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveTaxes" gss_model="taxmodel"><i class='fa fa-save'></i><?php echo $this->__("Save taxes"); ?></div>
    </div>


</div>