<?
/* @var $this \ns_0b125d61_9516_4b24_90bc_16a84cd014b4\CustomerSearch */
$searchword = $_POST['data']['keyword'];

//echo "<pre>";
$users = $this->getApi()->getUserManager()->findUsers($searchword);
    
foreach($users as $user) {
    echo "<table width='100%' style='border-bottom: solid 1px #333; padding-bottom: 10px;'>";
    /* @var $user core_usermanager_data_User */
    $link = "<a href='?page=users_all_users&userid=".$user->id."' style='color:#FFFFFF;'>";
    
    echo "<tr>";
    echo "<td style='width: 500px;'>$link<div style='margin-top:10px;'></div>" .  $user->fullName . "</a></td>";
    echo "<td>$link<div style='margin-top:10px;'></div>" . @$user->company->name . "</a></td>";
    echo "</tr>";
    $events = $this->getApi()->getCalendarManager()->getEntriesByUserId($user->id);
    $hasKsvTest = false;
    
    if ($user->comments) {
        foreach ($user->comments as $comment) {
            if ($comment->appId == "6ee27b0d-ba5a-4986-8bb4-0beb2b850f7c" ) {
                echo "<tr>";
                echo "<td style='color:#AAA'>&nbsp;&nbsp;&nbsp;KSV</td>";
                echo "<td style='color:#AAA'>".$this->__f("This user has received an KSV test.")."</td>";
                echo "</tr>";
                $hasKsvTest = true;
                break;
            }
        }   
    } 
    
    if($events) {
        foreach($events as $event) {
            /* @var $event core_calendarmanager_data_Entry */
            echo "<tr>";
            echo "<td style='color:#AAA'>&nbsp;&nbsp;&nbsp;" . $event->title . "</td>";
            echo "<td style='color:#AAA'>" . $event->location . " (" . $event->day . "." . $event->month . "." . $event->year . ")</td>";
            echo "</tr>";
        }
    } else {
        if (!$hasKsvTest) {
            echo "<tr>";
            echo "<td colspan='2'style='color:#AAA'>&nbsp;&nbsp;&nbsp;" . $this->__w("This user has not attended any events yet") . "</td>";
            echo "</tr>";
        }
    }
    echo "</a>";
    echo "</table>";
    
}

    
    echo "<br>";
//print_r($users);
echo "</pre>";
?>