<?
/* @var $this ns_d6e01372_c0d8_442e_ae4f_6aa0eafd2a22\ProMeisterScoreSettings */

$groups = $this->getApi()->getUserManager()->getAllGroups();
$tests = $this->getApi()->getQuestBackManager()->getAllTests();

$score = $this->getApi()->getQuestBackManager()->getResultRequirement();
if (!$score) {
    $score = new \core_questback_data_ResultRequirement();
}

?>

<div gstype='form' method='saveresult'>
<?
    echo "<div class='testselection'>";
        echo "What tests should be used in the diagram?";

        foreach ($tests as $test) {
            $use = in_array($test->id, $score->testsThatShouldBeUsed) ? "checked='true'" : "";
            echo "<br/><input type='checkbox' $use class='selectTest' gsname='use_$test->id' value='$test->id'>$test->name</option>";
        }
    echo "</div>";

    foreach ($groups as $group) {
        $groupid = $group->id;

        echo "<div class='groupsetting'>";
            echo "<div class='title'>$group->groupName</div>";
            echo "<div class='inner'>";
                foreach ($tests as $test) {
                    $hide = in_array($test->id, $score->testsThatShouldBeUsed) ? "" : "display: none;";
                    echo "<div style='$hide' class='catrow' testid='$test->id'>";
                        $testid = $test->id;
                        echo "<label>".$test->name."</label>";
                        $valueReq = @$score->groupRequiments->{$groupid}->requirements->{$testid}->required;
                        echo "<input class='gsniceinput1' type='txt' gsname='required_".$groupid."_".$testid."' value='$valueReq'/>";
                    echo "</div>";
                }
            echo "</div>";
        echo "</div>";
    }
    ?>
    
    <?
    if (isset($_POST['data']['testname'])) {
        ?> 
    <i class="fa fa-check-circle"></i> Saved<br/><br/>
    <?
    }
    ?>
    <div class='shop_button' gstype='submit'>Save</div>
</div>