<?
/* @var $this \ns_b9642995_2bb2_474c_b1e8_5c859dad67a1\SedoxFileServiceStatus */
?>

<div class='gss_settings_header'>
    <span class="fa-stack fa-lg" style="margin-right: 60px;">
        <i class="fa fa-gears fa-stack-1x"></i>
    </span>
    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Sedox Performance Configuration"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("File Service Status");
            ?>	
        </div>
    </div>	
</div>
<div class='gss_settings_content'>
    <div class="textfield gss_setting"  id="name">
        <span class="title"><?php echo $this->__f("Force Service Status"); ?></span>
        <div class="gss_onoff" gs_model="servicestatus" gs_model_attr="forced">
            <?
            $faclass = $this->getConfigurationSetting("forced") == "true" ? "fa-toggle-on" : "fa-toggle-off";
            ?>
            Off<i class="fa <? echo $faclass; ?>"></i>On
        </div>
    </div>
    <div class="textfield gss_setting full_width"  id="name">
        <span class="title"><?php echo $this->__f("Forced Status"); ?></span>
        <div class="gss_slider" gs_model="servicestatus" gs_model_attr="forcedstatus">
            <?
            $forcedstatus = $this->getConfigurationSetting("forcedstatus");
            ?>
            <input type="radio" name="forcedStatus" <? echo $forcedstatus == "off" ? "checked" : ""; ?> id="state_one" value="off"></input>
            <input type="radio" name="forcedStatus" <? echo $forcedstatus == "limited" ? "checked" : ""; ?> id="state_two" value="limited"></input>
            <input type="radio" name="forcedStatus" <? echo $forcedstatus == "full" ? "checked" : ""; ?> id="state_three" value="full"></input>
            <label for="state_one"></label>
            <label for="state_two"></label>
            <label for="state_three"></label>
            <?
            if($forcedstatus == "off") {
                $left = "-2px";
                $bgcolor = "red";
            } else if($forcedstatus == "limited") {
                $left = "16px";
                $bgcolor = "yellow";
            } else if($forcedstatus == "full") {
                $left = "34px";
                $bgcolor = "green";
            }
            ?>
            <div class="slider_button" style="left: <? echo $left ?>; background-color: <? echo $bgcolor ?>"></div>
        </div>
    </div>
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveStatus" gss_model="servicestatus"><i class='fa fa-save'></i><?php echo $this->__f("Save"); ?></div>
    </div>
</div>