<?php
/* @var $this \ns_b675ce83_d771_4332_ba09_a54ed8537282\PmsBookingMyBookingList */
$bookings = $this->getBookings();
$items = $this->getBookingItems();
$types = $this->getBookingItemTypes();
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$rules = $this->getApi()->getBookingEngine()->getDefaultRegistrationRules($this->getSelectedName());


$prices = array();
$prices[1] = "daily";
$prices[2] = "monthly";
$prices[3] = "weekly";
$prices[4] = "minutly";
$prices[5] = "hourly";
$prices[6] = "secondly";
$prices[7] = "daily";
$prices[8] = "daily";

echo "<b>";
echo $this->wrapContentManager("headingtext", "Room booked");
echo "</b>";

echo "<table cellspacing='0' cellpadding='0' width='100%'>";
echo "<tr>";
echo "<th width='10'></th>";
if($config->bookingProfile == "subscription") {
    echo "<th width='10'>".$this->__w("Type")."</th>";
} else {
    echo "<th width='10'>".$this->__w("Room")."</th>";
}
echo "<th width='200'>".$this->__w("Time periode")."</th>";
if($rules->includeGuestData) {
    echo "<th>".$this->__w("Guest name")."</th>";
    echo "<th>".$this->__w("Guest phone")."</th>";
    echo "<th>".$this->__w("Guest email")."</th>";
}
if($config->bookingProfile == "subscription") {
    echo "<th width='100'>Subscription</th>";
} else {    
    echo "<th width='100'>Room type</th>";
}
if($config->requirePayments) {
    echo "<th width='100'>".$this->__w("Price")."</th>";
    echo "<th width='100'>".$this->__w("Invoiced to")."</th>";
    echo "<th width='100'>".$this->__w("Paid")."</th>";
}
if($this->getConfigurationSetting("can_end_stay") == "true") {
    echo "<th width='10' class='endstay'>End</th>";
}
echo "</tr>";

if(!$bookings) {
    $bookings = array();
}
$orderIds = array();
$allRooms = array();
foreach($bookings as $booking) {
    foreach($booking->orderIds as $id) {
        $orderIds[] = $id;
    }
    foreach($booking->rooms as $room) {
        $startTime = strtotime($room->date->start);
        if($room->deleted) {
            continue;
        }
        $room->pmsBookingId = $booking->id;
        $allRooms[$startTime] = $room;
    }
}

ksort($allRooms);

foreach($allRooms as $room) {
    echo "<tr bookingid='".$room->pmsBookingId."' roomid='".$room->pmsBookingRoomId ."'>";
    echo "<td width='30'>";
    if($this->isEditorMode() || $this->isAdminMode()) {
        echo "<i class='fa fa-trash-o deleteroom'></i> ";
    }
    if($config->bookingProfile != "subscription") {
        echo "<i class='fa fa-edit editroom' style='cursor:pointer;'></i>";
    }
    echo "</td>";
    echo "<td>";
    if(isset($items[$room->bookingItemId])) {
        echo $items[$room->bookingItemId]->bookingItemName;
    }
    echo "</td>";
    echo "<td>" . date("d.m.Y H:i", strtotime($room->date->start)) . " - " . date("d.m.Y H:i", strtotime($room->date->end)) . "</td>";
    if($rules->includeGuestData) {
        echo "<td>";
        foreach($room->guests as $guest) {
            echo $guest->name . "<bR>";
        }
        echo "</td>";
        echo "<td>";
        foreach($room->guests as $guest) {
            echo $guest->phone . "<bR>";
        }
        echo "</td>";
        echo "<td>";
        foreach($room->guests as $guest) {
            echo $guest->email . "<bR>";
        }
        echo "</td>";
    }
    echo "<td>" . $types[$room->bookingItemTypeId]->name . "</td>";
    if($config->requirePayments) {
        echo "<td>".$room->price ."</td>";
        if($room->invoicedTo) {
            echo "<td>".date("d.m.Y", strtotime($room->invoicedTo)) ."</td>";
        } else {
            echo "<td>".$this->__w("Not invoiced yet")."</td>";
        }
        echo "<td>";
        if($this->getApi()->getPmsInvoiceManager()->isRoomPaidFor($this->getSelectedName(), $room->pmsBookingRoomId)) {
            echo "<i class='fa fa-check'></i>";
        } else {
            echo "Missing:<bR>";
            $toPay = $this->getApi()->getPmsInvoiceManager()->getOrdersForRoomToPay($this->getSelectedName(), $room->pmsBookingRoomId);
            foreach($toPay as $incId) {
                echo $incId . "<br>";
            }
        }
        echo "</td>";
    }

    if($this->getConfigurationSetting("can_end_stay") == "true") {
        if(strtotime($room->date->end) > (time() + (1000*60*24*90))) {
            $canEnd= true;
            $type = $types[$room->bookingItemTypeId];
            $product = $this->getApi()->getProductManager()->getProduct($type->productId);


            if($product->minPeriode > 0) {
                $total = time() - strtotime($room->date->start);
                if($total < $product->minPeriode) {
                    $canEnd = false;
                }
            }

            if($canEnd) {
                echo "<td width='10' class='runEndStay'>End</td>";
            } else {
                echo "<td width='10'>Not expired yet</td>";
            }

        } else {
            echo "<td width='10'>Ended</td>";
        }
    }

    echo "</tr>";
}
echo "</table>";

if($config->requirePayments) {
    echo "<br><br><b>".$this->__w("Order history")."</b>";
    echo "<div>";
    echo "</div>";
    $orders = $this->getApi()->getOrderManager()->getAllOrdersForUser($this->getTmpUser());
    echo "<table cellspacing='0' width='100%'>";
    echo "<tr>";
    echo "<th>".$this->__w("Orderid")."</th>";
    echo "<th>".$this->__w("Order date")."</th>";
    echo "<th>".$this->__w("Orderlines")."</th>";
    echo "<th width='150'>".$this->__w("Total")."</th>";
    echo "<th>Paid</th>";
    echo "</tr>";
    $total = 0;
    $totalTaxes = 0;
    foreach($orders as $order) {
        if(!in_array($order->id, $orderIds) && $order->status != 7) {
            continue;
        }
        
        if($order->status == 5) {
            //Do not print cancelled orderes.
            continue;
        }
        
        echo "<tr>";
        echo "<td valign='top'>";
        if($this->isEditorMode()) {
            echo "<span style='color:blue; cursor:pointer;' class='showorderbutton' orderid='".$order->id."'>" . $order->incrementOrderId . "</span>";
        } else {
            echo $order->incrementOrderId;
        }
        echo "</td>";
        echo "<td valign='top'>" . date("d.m.Y", strtotime($order->rowCreatedDate)) . "</td>";
        echo "<td>";
        $items = $order->cart->items;
        foreach($items as $cartItem) {
            $metaText = $cartItem->product->metaData ? " ( " .$cartItem->product->metaData." )" : "";
            $dates = "";
            $additionalMetaData = $cartItem->product->additionalMetaData ? " (" .$cartItem->product->additionalMetaData.")" : "";
            if($cartItem->startDate) { $dates .= date("d.m.Y H:i", strtotime($cartItem->startDate)); }
            if($cartItem->endDate) { $dates .= " - " . date("d.m.Y H:i", strtotime($cartItem->endDate)); }
            echo "<div cartItemId='".$cartItem->cartItemId."'>".$cartItem->count." x ".$cartItem->product->name." $metaText $additionalMetaData $dates<span style='float:right;'>".round($cartItem->product->priceExTaxes,2)."</span></div>";
        }
        
        $taxes = $this->getApi()->getOrderManager()->getTaxes($order);
        $taxsum = 0;
        foreach($taxes as $tax) {
            $taxsum += round($tax->sum,2);
            echo "<div>" . $tax->taxGroup->taxRate . "% MVA <span style='float:right;'>" . round($tax->sum,2) . "</span></div>";
        }
        
        $rowTotal = $this->getApi()->getOrderManager()->getTotalAmountExTaxes($order);
        $total += $rowTotal;
        $totalTaxes += $taxsum;
        echo "</td>";
        echo "<td valign='top'>";
        echo "Eks mva <span style='float:right;'>" . round($rowTotal,0) . "</span><br>";
        echo "Ink mva <span style='float:right;'>" . round($rowTotal+$taxsum,0) . "</span><br>";
        echo "</td>";
        echo "<td>";
        if(!stristr($order->payment->paymentType, "invoice") && $rowTotal > 0) {
            if($order->status == 7) {
                echo "<i class='fa fa-check'></i>";
            } else {
                echo "<a href='/?page=cart&payorder=".$order->id."' style='color:blue; cursor:pointer;'>Pay</a>";
            }
        }
        echo "";
        echo "</td>";
        echo "</tr>";
    }
    echo "<tr>";
    echo "<td colspan='3'>".$this->__w("Total")."</td>";
    echo "<td>Eks mva: $total<br>Ink mva: ".round($total + $totalTaxes). "</td>";
    echo "</tr>";
    echo "</table>";
}
?>