<?
/* @var $this ns_d02f8b7a_7395_455d_b754_888d7d701db8\Dibs */

$dibs = $this->getConfigurationSetting("merchantid");
?>

<div class='gss_settings_header'>
    <i class='fa fa-cc-visa'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <?php echo $this->getName(); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?php echo $this->getDescription(); ?>
            ?>	
        </div>
    </div>	
</div>

<div class='gss_settings_content'>

    <div class="gss_simple_shipping">
        <div class="textfield gss_setting"  id="merchantid">
            <span class="title"><?php echo $this->__f("Merchant Id"); ?></span>
            <input type="textfield" gs_model='dibsmodel' gs_model_attr='merchantid' value="<? echo $dibs; ?>">
            <div class="description">
                <?php  echo $this->__f("The Merchant-ID is provided by Dibs, please contact us for more information."); ?>
            </div>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="dibsmodel" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>
</div>