<? namespace ns_d02f8b7a_7395_455d_b754_888d7d701db8; ?>
<div class="information">
    <?php echo $this->getDescription(); ?>
    <br><br>
    <div>
        <?php  echo $this->__f("Have a look at http://www.dibspayment.com/ for more information."); ?>
    </div>
</div>

<div class="textfield setting"  id="merchantid">
    <span class="title">Merchant-ID</span>
    <input type="textfield" class="config" id="selenium_smtp_host">
    <div class="description">
        <?php  echo $this->__f("The Merchant-ID is provided by Dibs, please contact us for more information."); ?>
    </div>
</div>
<div class="button savebutton"><div class="rightglare"></div><div class="filler"></div><ins>Save settings</ins></div>