<?
/* @var $this ns_d02f8b7a_7395_455d_b754_888d7d701db8\Dibs */

$dibs = $this->getConfigurationSetting("merchantid");
$paymentsuccess = $this->getConfigurationSetting("paymentsuccess");
$paymentfailed = $this->getConfigurationSetting("paymentfailed");
$paymentcancelled = $this->getConfigurationSetting("paymentcancelled");
$hmac = $this->getConfigurationSetting("hmac");
$md5k1 = $this->getConfigurationSetting("md5k1");
$md5k2 = $this->getConfigurationSetting("md5k2");
$redirectsuccesstopage = $this->getConfigurationSetting("redirectsuccesstopage");
?>

<div class='gss_settings_header'>
    <i class='fa fa-cc-visa'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <?php echo $this->getName(); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?php echo $this->getDescription(); ?>
        </div>
    </div>	
</div>

<div class='gss_settings_content'>

    <div class="gss_simple_shipping">
        <div class="textfield gss_setting"  id="merchantid">
            <span class="title"><?php echo $this->__f("Merchant Id"); ?></span>
            <input type="textfield" gs_model='dibsmodel' gs_model_attr='merchantid' value="<? echo $dibs; ?>">
            <div class="description">
                <?php  echo $this->__f("The Merchant-ID is provided by Dibs, please contact us for more information."); ?>
            </div>
        </div>
        <div class="textfield gss_setting"  id="hmac">
            <span class="title"><?php echo $this->__f("HMAC key provided by dibs"); ?></span>
            <input type="textfield" gs_model='dibsmodel' gs_model_attr='hmac' value="<? echo $hmac; ?>">
            <div class="description">
                <?php  echo $this->__f("The Merchant-ID is provided by Dibs, please contact us for more information."); ?>
            </div>
        </div>
        
        <div class="textfield gss_setting"  id="redirectsuccesstopage">
            <span class="title"><?php echo $this->__f("Redirect success to page"); ?></span>
            <input type="textfield" gs_model='dibsmodel' gs_model_attr='redirectsuccesstopage' value="<? echo $redirectsuccesstopage; ?>">
            <div class="description">
                <?php  echo $this->__f("Type in a specific page you would like to redirect to when completed, if not set its transferred to a default success page"); ?>
            </div>
        </div>
        
        <div class="textfield gss_setting"  id="savecard">
               <span class="title"><?php echo $this->__f("Save card"); ?></span>
               <div class="gss_onoff" gs_model="dibsmodel" gs_model_attr="savecard">
                   <?
                   $class = $this->getConfigurationSetting("savecard") == "true" ? "fa-toggle-on" : "fa-toggle-off";
                   ?>
                   <? echo $this->__f("Off"); ?><i class="fa <? echo $class; ?>"></i><? echo $this->__f("On"); ?>
               </div>
               <div class="description">
                   <?php echo $this->__w("Save the cards instead of extracting the amount?"); ?>
               </div>
        </div>
        
        <div class="textfield gss_setting"  id="testmode">
               <span class="title"><?php echo $this->__f("Test mode"); ?></span>
               <div class="gss_onoff" gs_model="dibsmodel" gs_model_attr="testmode">
                   <?
                   $class = $this->getConfigurationSetting("testmode") == "true" ? "fa-toggle-on" : "fa-toggle-off";
                   ?>
                   <? echo $this->__f("Off"); ?><i class="fa <? echo $class; ?>"></i><? echo $this->__f("On"); ?>
               </div>
               <div class="description">
                   <?php echo $this->__w("Run dibs in test mode?"); ?>
               </div>
        </div>
        
        <div class="textfield gss_setting"  id="hasssl">
               <span class="title"><?php echo $this->__f("Supports ssl callbacks?"); ?></span>
               <div class="gss_onoff" gs_model="dibsmodel" gs_model_attr="hasssl">
                   <?
                   $class = $this->getConfigurationSetting("hasssl") == "true" ? "fa-toggle-on" : "fa-toggle-off";
                   ?>
                   <? echo $this->__f("Off"); ?><i class="fa <? echo $class; ?>"></i><? echo $this->__f("On"); ?>
               </div>
               <div class="description">
                   <?php echo $this->__w("Can the end user be redirected to a ssl enabled page?"); ?>
               </div>
        </div>
        
        <div class="textfield gss_setting"  id="useflexwin">
               <span class="title"><?php echo $this->__f("Use flexwin"); ?></span>
               <div class="gss_onoff" gs_model="dibsmodel" gs_model_attr="useflexwin">
                   <?
                   $class = $this->getConfigurationSetting("useflexwin") == "true" ? "fa-toggle-on" : "fa-toggle-off";
                   ?>
                   <? echo $this->__f("Off"); ?><i class="fa <? echo $class; ?>"></i><? echo $this->__f("On"); ?>
               </div>
               <div class="description">
                   <?php echo $this->__w("Use flexwin payment window instead of DPW."); ?>
               </div>
        </div>
        
        <div class="textfield gss_setting"  id="md5k1">
            <span class="title"><?php echo $this->__f("MD5 key 1 for flexwin"); ?></span>
            <input type="textfield" gs_model='dibsmodel' gs_model_attr='md5k1' value="<? echo $md5k1; ?>">
            <div class="description">
                <?php  echo $this->__f("The md5 key found in the dibs admin panel (for flexwin)."); ?>
            </div>
        </div>
        
        <div class="textfield gss_setting"  id="md5k2">
            <span class="title"><?php echo $this->__f("MD5 key 2 for flexwin"); ?></span>
            <input type="textfield" gs_model='dibsmodel' gs_model_attr='md5k2' value="<? echo $md5k2; ?>">
            <div class="description">
                <?php  echo $this->__f("The md5 key found in the dibs admin panel (for flexwin)."); ?>
            </div>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="dibsmodel" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>
</div>