<?php
/* @var $this ns_624fa4ac_9b27_4166_9fc3_5c1d1831b56b\PmsSendMessagesConfiguration */
$notificationSettings = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());

$languages = $this->getFactory()->getLanguageCodes();
$languages[] = $this->getFactory()->getMainLanguage();
$selected = $this->getFactory()->getSelectedLanguage();

/* @var $factory Factory */
$factory = $this->getFactory();
$langauge = $this->getLanguage();
$hasArx = $notificationSettings->arxHostname;
if($this->getApi()->getPmsManager()->hasLockSystemActive($this->getSelectedMultilevelDomainName())) {
    $hasArx = true;
}
$hasEventCalendar = false;
$instances = $this->getApi()->getStoreApplicationInstancePool()->getApplicationInstances("27e174dc-b08c-4bf7-8179-9ea8379c91da");
if(!$instances) {
    $instances = array();
}
foreach($instances as $instance) {
    if(@$instance->settings->{"engine_name"}->value == $this->getSelectedName()) {
        $hasEventCalendar = true;
    }
}

$notifications = $this->getNotifications($langauge, $hasArx, $hasEventCalendar);

?>
<div style='padding-top: 20px;' data-include-for-type='old'>
    Variables: {code},
    {roomName}, 
    {rooms}, 
    {checkin_date}, 
    {checkin_time},
    {checkout_date},
    {checkout_time},
    {name},
    {referenceNumber},
    {roomType}, 
    {email}, 
    {city},
    {phone},
    {address}, 
    {orderid}, 
    {postCode},
    {contact_prefix},
    {personalMessage},
    {roomlist},
    {bookingid},
    {bookinginformation},
    {extrafield},
    {userid},
    {roomDescription},
    {simpleRoomList}, {nightprice}, {totalcost}.<br>
    
    <b>Specifics:</b><br>
    <?php echo htmlentities('<specific channel="wubook_2" text="Remember the card you registered will be charged 2 days ahead of your stay."></specific>');  ?><br>
    <?php echo htmlentities('<specific type="d93a80e2-fcd6-47a5-8aec-6e9be48e3c1e" text="Remember to clean the room."></specific>'); ?>
</div>
<br>
<div gstype="form" method="addMessage">
    Select a message type: 
    <div>
        <select class='gsniceselect1 changeLanguage' style='width:29%; display:none;' gsname="language">
            <?php
                foreach($languages as $key) {
                    $selected = ($key == $langauge) ? "SELECTED" : "";
                    echo "<option value='$key' $selected>$key</option>";
                }
            ?>
        </select>
        <select class='gsniceselect1' style='width:100%; float:right;' gsname="type">
            <?php
            foreach($notifications as $key => $value) {
                echo "<option value='$key'>$value</option>";
            }
            ?>
        </select>
    </div>
    <div style=' margin-top: 10px;'>The message goes here:</div>
    <textarea style='width:100%;box-sizing: border-box;height: 200px;' class='gsniceinput1' gsname="message"></textarea>
    <div style='text-align: right'>
        <input type='button' value='Add as email' style='padding:9px;' gstype='submit' gsvalue="emails"> or
        <input type='button' value='Add as sms' style='padding:9px;' gstype='submit' gsvalue="smses"> or
        <input type='button' value='Add as admin message' style='padding:9px;' gstype='submit' gsvalue="adminmessages">
    </div>
</div>
<?php

$types = array();
$types['smses'] = "Messages sent by sms";
$types['emails'] = "Messages sent by email";
$types['adminmessages'] = "Messages sent to you";

echo "<h1>Payment link adress (web adress)</h1>";

$paymentProductConfig = $this->getApi()->getPmsInvoiceManager()->getPaymentLinkConfig($this->getSelectedMultilevelDomainName());
?>
<div gstype='form' method='savepaymentlinksetup'>
    <input class='webadressclass gsniceinput1' type='text' gsname='webadress' value='<?php echo $paymentProductConfig->webAdress; ?>' class=''>
    <span class="shop_button" gstype='submit' gs_callback='alert("saved");'>Save</span>
</div>
<?php
foreach($types as $type => $text) {
    echo "<h1>$text</h1>";
    $found = false;
    foreach($notificationSettings->{$type} as $key => $value) {
        if(!$this->endsWith($key, $langauge)) {
            continue;
        }
        ?>
        <div class="messagebox-outer" gstype="form" method="updateMessage">
            <div class="messagebox">
                <div class='heading'>
                    <?php echo "<input type='hidden' gsname='key' value='$key'>"; ?>
                    <?php echo "<input type='hidden' gsname='type' value='$type'>"; ?>
                    <?php echo $notifications[$key]; $found = true; ?>
                    <i class='fa fa-trash-o' gstype="submit" gsvalue="remove"></i>
                </div>
                <div class="body">
                    <?php
                    if($type == "emails") {
                        $title = $notificationSettings->{'emailTitles'}->{$key};
                        echo "<input type='txt' gsname='title' class='gsniceinput1' style='width:100%;box-sizing:border-box; margin-bottom:2px;' value='$title'>";
                    }
                    ?>
                    <textarea gsname="message"><?php echo $value; ?></textarea>
                </div>
                <div class="footer">
                    <input type="button" value="Save" gstype="submit">
                </div>
            </div>
        </div>
        <?php
    }
    if(!$found) {
        echo "No messages are being sent to you.";
    }
    echo "<div style='clear:both;'></div>";
}
?>
