<?php
/* @var $this ns_624fa4ac_9b27_4166_9fc3_5c1d1831b56b\PmsSendMessagesConfiguration */
$notificationSettings = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());

$languages = $this->getFactory()->getLanguageCodes();
$languages[] = $this->getFactory()->getMainLanguage();
$selected = $this->getFactory()->getSelectedLanguage();

/* @var $factory Factory */
$factory = $this->getFactory();
$langauge = $this->getLanguage();
$hasArx = $notificationSettings->arxHostname;
if($this->getApi()->getPmsManager()->hasLockSystemActive($this->getSelectedMultilevelDomainName())) {
    $hasArx = true;
}
$hasEventCalendar = false;
$instances = $this->getApi()->getStoreApplicationInstancePool()->getApplicationInstances("27e174dc-b08c-4bf7-8179-9ea8379c91da");
if(!$instances) {
    $instances = array();
}
foreach($instances as $instance) {
    if(@$instance->settings->{"engine_name"}->value == $this->getSelectedName()) {
        $hasEventCalendar = true;
    }
}

$notifications = array();
$notifications['room_starting_0_hours_'.$langauge] = "Booking is started.";
$notifications['room_morning_message_'.$langauge] = "Greeting message sent in the morning same day check in (sent at 07:00) to guests.";
$notifications['room_starting_4_hours_'.$langauge] = "Booking starting in 4 hours";
$notifications['room_starting_12_hours_'.$langauge] = "Booking starting in 12 hours";
$notifications['room_starting_24_hours_'.$langauge] = "Booking starting in 1 day";
$notifications['room_starting_48_hours_'.$langauge] = "Booking starting in 2 days";
$notifications['room_started_4_hours_'.$langauge] = "Booking started 4 hours ago";
$notifications['room_started_12_hours_'.$langauge] = "Booking started 12 hours ago";
$notifications['room_started_24_hours_'.$langauge] = "Booking started 24 hours ago";
$notifications['room_started_48_hours_'.$langauge] = "Booking started 48 hours ago";
$notifications['room_changed_'.$langauge] = "Room has been changed while stay is started";
$notifications['room_resendcode_'.$langauge] = "When resending a code to the guest";
$notifications['room_dooropenedfirsttime_'.$langauge] = "When guest opens the door";
$notifications['date_changed_'.$langauge] = "Stay dates has been changed";
$notifications['booking_completed_'.$langauge] = "Booking has been completed";
$notifications['booking_completed_ota_'.$langauge] = "Booking has been completed by OTA (overrides standard complete message)";
$notifications['booking_completed_payed_ota_'.$langauge] = "Booking has been completed and charged by OTA (overrides standard both ota and completed message)";
$notifications['booking_notconfirmed_'.$langauge] = "Booking has been rejected";
$notifications['room_ended_0_hours_'.$langauge] = "Booking has ended.";
$notifications['room_ended_24_hours_'.$langauge] = "Booking ended 1 day ago";
$notifications['room_ended_48_hours_'.$langauge] = "Booking ended two days ago";
$notifications['sendreciept_'.$langauge] = "When sending a reciept";
$notifications['sendinvoice_'.$langauge] = "When sending an invoice";
$notifications['warnfirstordernotpaid_'.$langauge] = "If order has not been paid for.";
if($notificationSettings->runAutoPayWithCard) {
    $notifications['order_unabletopaywithsavecardwarning_'.$langauge] = "Warning sent 3 days before order expire (unable to pay with saved card)";
    $notifications['order_unabletopaywithsavecard_'.$langauge] = "Message sent when the order has expired and payment has not been completed.";
}
if($hasArx) {
    $notifications['room_added_to_arx_'.$langauge] = "When code is being sent out";
    $notifications['room_removed_from_arx_'.$langauge] = "When code is removed from the door";
}
if($hasEventCalendar) {
    $notifications['booking_eventcalendar_'.$langauge] = "Message to send to event helder in the event calendar";
}
$notifications['booking_paymentmissing_'.$langauge] = "When payment is missing (autosending)";
$notifications['booking_sendpaymentlink_'.$langauge] = "Sending the payment link (manually sending)";
$notifications['booking_unabletochargecard_'.$langauge] = "Not able to charge card";

?>
<div style='padding-top: 20px;' data-include-for-type='old'>
    Variables: {code},
    {roomName}, 
    {rooms}, 
    {checkin_date}, 
    {checkin_time},
    {checkout_date},
    {checkout_time},
    {name},
    {referenceNumber},
    {roomType}, 
    {email}, 
    {city},
    {phone},
    {address}, 
    {orderid}, 
    {postCode},
    {contact_prefix},
    {personalMessage},
    {roomlist},
    {bookingid},
    {bookinginformation},
    {extrafield},
    {userid},
    {roomDescription},
    {simpleRoomList}, {nightprice}, {totalcost}.<br>
    
    <b>Specifics:</b><br>
    <?php echo htmlentities('<specific channel="wubook_2" text="Remember the card you registered will be charged 2 days ahead of your stay."></specific>');  ?><br>
    <?php echo htmlentities('<specific type="d93a80e2-fcd6-47a5-8aec-6e9be48e3c1e" text="Remember to clean the room."></specific>'); ?>
</div>
<br>
<div gstype="form" method="addMessage">
    Select a message type: 
    <div>
        <select class='gsniceselect1 changeLanguage' style='width:29%; display:none;' gsname="language">
            <?php
                foreach($languages as $key) {
                    $selected = ($key == $langauge) ? "SELECTED" : "";
                    echo "<option value='$key' $selected>$key</option>";
                }
            ?>
        </select>
        <select class='gsniceselect1' style='width:100%; float:right;' gsname="type">
            <?php
            foreach($notifications as $key => $value) {
                echo "<option value='$key'>$value</option>";
            }
            ?>
        </select>
    </div>
    <div style=' margin-top: 10px;'>The message goes here:</div>
    <textarea style='width:100%;box-sizing: border-box;height: 200px;' class='gsniceinput1' gsname="message"></textarea>
    <div style='text-align: right'>
        <input type='button' value='Add as email' style='padding:9px;' gstype='submit' gsvalue="emails"> or
        <input type='button' value='Add as sms' style='padding:9px;' gstype='submit' gsvalue="smses"> or
        <input type='button' value='Add as admin message' style='padding:9px;' gstype='submit' gsvalue="adminmessages">
    </div>
</div>
<?php

$types = array();
$types['smses'] = "Messages sent by sms";
$types['emails'] = "Messages sent by email";
$types['adminmessages'] = "Messages sent to you";

echo "<h1>Payment link adress (web adress)</h1>";

$paymentProductConfig = $this->getApi()->getPmsInvoiceManager()->getPaymentLinkConfig($this->getSelectedMultilevelDomainName());
?>
<div gstype='form' method='savepaymentlinksetup'>
    <input class='webadressclass gsniceinput1' type='text' gsname='webadress' value='<?php echo $paymentProductConfig->webAdress; ?>' class=''>
    <span class="shop_button" gstype='submit' gs_callback='alert("saved");'>Save</span>
</div>
<?php
foreach($types as $type => $text) {
    echo "<h1>$text</h1>";
    $found = false;
    foreach($notificationSettings->{$type} as $key => $value) {
        if(!$this->endsWith($key, $langauge)) {
            continue;
        }
        ?>
        <div class="messagebox-outer" gstype="form" method="updateMessage">
            <div class="messagebox">
                <div class='heading'>
                    <?php echo "<input type='hidden' gsname='key' value='$key'>"; ?>
                    <?php echo "<input type='hidden' gsname='type' value='$type'>"; ?>
                    <?php echo $notifications[$key]; $found = true; ?>
                    <i class='fa fa-trash-o' gstype="submit" gsvalue="remove"></i>
                </div>
                <div class="body">
                    <?php
                    if($type == "emails") {
                        $title = $notificationSettings->{'emailTitles'}->{$key};
                        echo "<input type='txt' gsname='title' class='gsniceinput1' style='width:100%;box-sizing:border-box; margin-bottom:2px;' value='$title'>";
                    }
                    ?>
                    <textarea gsname="message"><?php echo $value; ?></textarea>
                </div>
                <div class="footer">
                    <input type="button" value="Save" gstype="submit">
                </div>
            </div>
        </div>
        <?php
    }
    if(!$found) {
        echo "No messages are being sent to you.";
    }
    echo "<div style='clear:both;'></div>";
}
?>
