<?php
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
?>
<div class="loadeditevent"></div>
<span class="shop_button" loadeditmeesage="-1">Create a new automated message</span>

<?php 
if($config->avoidSendingBookingConfigurationsToOTA) {
    echo '<span class="shop_button" style="background-color:blue;float:right;" gsclick="toggleAvoidSendingConfirmationToOTA">Confirmation is not sent to OTAs anymore, activat eit again</span>';
} else {
    echo '<span class="shop_button" style="background-color:red;float:right;" gsclick="toggleAvoidSendingConfirmationToOTA">Stop sending confirmations to OTAs</span>';
}
?>

<br>
<br>

<?php
/* @var $this ns_624fa4ac_9b27_4166_9fc3_5c1d1831b56b\PmsSendMessagesConfiguration */
$msgs = $this->getApi()->getPmsNotificationManager()->getAllMessages($this->getSelectedMultilevelDomainName());
$keys = array();
foreach($msgs as $msg) {
    $keys[$msg->key] = 1;
}


$notifications = $this->getNotifications("", true, true);
$paymentProductConfig = $this->getApi()->getPmsInvoiceManager()->getPaymentLinkConfig($this->getSelectedMultilevelDomainName());
echo "<h1>Payment link adress (web adress)</h1>";
?>

<select class='gsniceselect1 filterbykeytype' style='float:right;'>
    <option value=''>Filter by message type</option>
    <?php
    foreach($keys as $k => $val) {
        echo "<option value='$k'>".$notifications[$k."_"]."</option>";
    }
    ?>
</select>

<div gstype='form' method='savepaymentlinksetup'>
    <input class='webadressclass gsniceinput1' type='text' gsname='webadress' value='<?php echo $paymentProductConfig->webAdress; ?>' class=''>
    <span class="shop_button" gstype='submit' gs_callback='alert("saved");'>Save</span>
</div>
<br>
<?php $regardlessofpayment = $config->sendMessagesRegardlessOfPayments ? "CHECKED" : ""; ?>
<input type="checkbox" class='toggleSendMessagesRegardlessOfPayment' gsname="sendMessagesRegardlessOfPayments" <?php echo $regardlessofpayment; ?>> Send messages regardless of payments
<?php

foreach($msgs as $msg) {
    echo "<div class='messageboxnew' key='".$msg->key."'>";
    if($msg->type == "email") {
        echo "<div class='title'>" . $msg->title  . "</div>";
    }
    echo "<div class='content'>";
    echo nl2br($msg->content);
    echo "</div>";
    echo "<div class='footer'>";
    echo $notifications[$msg->key."_"] . " (" . $msg->type . ")";
    if($msg->timeofday) {
        echo ", sent at " . $msg->timeofday;
    }
    echo "<div class='optionspreview ".$msg->type."'>";
    if(sizeof($msg->prefixes) != 0 || sizeof($msg->languages) != 0) {
        $this->printLanguagesSelected($msg);

        if($msg->type == "sms") {
            $this->printPrefixesSelected($msg);
        }
    } else {
        if(!$msg->isManual) {
            echo "<b>Automated message</b>, ";
        } else {
            echo "<b>Manual message</b>, ";
        }
        echo "This message is being used if no match on other criterias.<br>";
    }
    echo "</div>";
    echo "<i class='fa fa-edit' loadeditmeesage='".$msg->id."'></i>";
    echo "<i class='fa fa-trash-o' msgid='".$msg->id."'></i>";
    echo "</div>";
    echo "</div>";
}

?>
<h1>Email template</h1>
<?php
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
?>
<div gstype='form' method='saveEmailTemplate'>
<textarea style='width:100%; height: 400px;' gsname='email'><?php echo $config->emailTemplate; ?></textarea>
<div style='text-align:right;'>
    <span class="shop_button" gstype='submit'>Update email template</span>
</div>
<script>
    var hash = window.location.hash;
    if(hash.startsWith("#filter=")) {
        var key = hash.replace("#filter=", "");
        app.PmsSendMessagesConfiguration.filterBySpecifiedKey(key);
        $('.filterbykeytype').val(key);
    }
</script>