<?php

namespace ns_d37cbec7_fbb1_4903_a7af_e372c16ac7dd;

/* @var $this \ns_d37cbec7_fbb1_4903_a7af_e372c16ac7dd\HelloWorld */
?>
<div class='datainputfield'>
    <input type="text" placeholder="Navn" name="name" class="personal_data name">
    <input type="text" placeholder="Telefon nummer" name="phone" class="personal_data phone">
    <input type="text" placeholder="Epost" name="email" class="personal_data email"><br>
    <select id="whatisitabout">
        <option value="nettbutikk demo">Jeg ønsker en demo på nettbutikk</option>
        <option value="hjelp til å starte en nettbutikk">Jeg ønsker hjelp til å starte en nettbutikk</option>
        <option value="flytte eksisterende">Jeg har en eksisterende nettbutikk og vurderer å flytte den.</option>
        <option value="ønsker en webside">Jeg ønsker meg en webside</option>
    </select><br>
    <input type="submit" value="Send forespørsel" class="submit_contact">
</div>
<div class='thanks'>
    <br>
    Takk for din henvendelse.<br>
    Nettmannen vil kontakte deg så snart som mulig.
    <br><br>
</div>