<?
/* @var $this ns_4be8e427_bead_491e_8d9f_7dd16356d8eb\OrderView */
?>

<?
/* @var $this ns_bce90759_5488_442b_b46c_a6585f353cfe\EcommerceOrderView */
$order = $this->getOrder();
?>

<div class="insideheader">
    <?
    echo $this->__f("Accounting details");
    ?> 
</div>

<div class="row_account">
    <div class="col col1">
        <?
        echo $this->__f("Date to be transferred");
        ?>
    </div>
    <div class="col col2">
        <?
        echo isset($order->transferToAccountingDate) ? $order->transferToAccountingDate : "N/A";
        ?>
    </div>
</div>
<div class="row_account">
    <div class="col col1">
        <?
        echo $this->__f("Should have been transferred");
        ?>
    </div>
    <div class="col col2">
        <?
        echo isset($order->shouldHaveBeenTransferredToAccountingOnDate) ? $order->shouldHaveBeenTransferredToAccountingOnDate : "N/A";
        ?>
    </div>
</div>
<div class="row_account">
    <div class="col col1">
        <?
        echo $this->__f("Is transferred");
        ?>
    </div>
    <div class="col col2">
        <?
        echo $order->transferredToAccountingSystem ? $this->__f("Yes") : $this->__f("No");
        ?>
    </div>
</div>
<div class="row_account">
    <div class="col col1">
        <?
        echo $this->__f("Tried to transfer");
        ?>
    </div>
    <div class="col col2">
        <?
        echo $order->triedTransferredToAccountingSystem ? $this->__f("Yes") : $this->__f("No");
        ?>
    </div>
</div>
<div class="row_account">
    <div class="col col1">
        <?
        echo $this->__f("Override accountingdate");
        ?>
    </div>
    <div class="col col2">
        <?
        echo $order->overrideAccountingDate;
        ?>
        
        <div style='color:blue; cursor: pointer;' class='' onclick='$(".OrderView .changeoverridedatebox").toggle()'>( <? echo $this->__f("change"); ?> )</div>
        <div class='changeoverridedatebox'>
            <input class='gsniceinput1 overrideboxdate'/>
            <br/><div class='shop_button'><? echo $this->__f("Submit"); ?></div>
        </div>
    </div>
</div>
<div class="row_account">
    <div class="col col1">
        <?
        echo $this->__f("Excluded from f-report");
        ?>
    </div>
    <div class="col col2">
        <?
        echo $order->excludeFromFReport ? "Yes" : "No";
        ?>
    </div>
</div>

<div class="row_account">
    <div class="col col1">
        <?
        echo $this->__f("Is order closed");
        ?>
    </div>
    <div class="col col2">
        <?
        echo $order->closed ? 'Yes' : "No";
        ?>
    </div>
</div>

<script>
    $('.OrderView .gsniceinput1.overrideboxdate').datepicker({dateFormat: "dd.mm.yy"});
</script>
    