<?
/* @var ns_4be8e427_bead_491e_8d9f_7dd16356d8eb\OrderView */
?>

<div class='menu'>
    <div class='entry taboperation' tab='customers' reprint='true'>
        <i class='fa fa-user'></i>
        Customer
    </div>
    <div class='entry taboperation' tab='orderlines' reprint='true'>
        <i class='fa fa-list'></i>
        Orderlines
    </div>
    <div class='entry taboperation' tab='receipts' reprint='true'>
        <i class='fa fa-print'></i>
        Recipts
    </div>
    <div class='entry taboperation' tab='history' reprint='true'>
        <i class='fa fa-history'></i>
        History
    </div>
    <div class='entry taboperation' tab='paymenthistory' reprint='true'>
        <i class='fa fa-dollar'></i>
        Payment<br/>History
    </div>
    
    <div class='entry taboperation' tab='accounting' reprint='true'>
        <i class='fa fa-calculator'></i>
        Accounting
    </div>
    
    <div class='entry taboperation' tab='sendorder' reprint='true'>
        <i class='fa fa-envelope'></i>
        Send
    </div>
    
</div>
