<?
/* @var ns_4be8e427_bead_491e_8d9f_7dd16356d8eb\OrderView */
$order = $this->getOrder();
$cart = $order->cart;
$closed = $order->closed;
$cartItemsPms = $this->getPmsCartItems();
$cartItemsNormal = $this->getNormalCartItems();


if($order->manuallyClosed) {
    $closed = $order->manuallyClosed;
}

if($order->isCreditNote) {
    echo "<div style='background-color:red; color:#fff; font-size: 20px;padding-bottom: 20px; text-align:center;'>A credit note can not be modified</div>";
}

if (!count($cart->items)) {
    echo $this->__f("No orderlines added to this order");
}

if (count($cartItemsPms)) {
?>
    <div class="orderlinesarea pms">
        <div class='summaryheader'><? echo $this->__f("From PMS"); ?></div>
        <?
        $this->includefile('orderlinespms');
        ?>
    </div>
<?
}

if (!($closed && !count($cartItemsNormal))) {
?>

<div class="orderlinesarea other">
    <div class='summaryheader'><? echo $this->__f("Orderlines"); ?>
    <?php
    if(!$closed) {
        $ecomsettings = new ns_9de54ce1_f7a0_4729_b128_b062dc70dcce\ECommerceSettings();
        $currencies = $ecomsettings->getCurrencies();
//        $languages = $ecomsettings->
        ?>
        <div style="float: right">
            

            <select class='gsniceselect1 updatecurrencyonorder' >
                <?php
                echo "<option value=''>Default currency</option>";
                foreach($currencies as $currencyCode => $currencyName) {
                    $selected = $currencyCode == $order->currency ? "SELECTED" : "";
                    echo "<option value='$currencyCode' $selected>$currencyCode : $currencyName</option>";
                }
                ?>
            </select>
            -
            <select gsname="language" class="gsniceselect1 updatelanguageonorder">
                <option>Not selected</option>
                <?php
                $states = $this->getFactory()->getLanguageReadable();
                foreach ($states as $key => $lang) {
                    $selected = $order->language == $key ? "selected='true'" : "";
                    ?>
                    <option <? echo $selected; ?> value="<? echo $key; ?>"><? echo $lang; ?></option>
                <?php } ?>
            </select>
        </div>
        <?php
    }
    ?>
    
    </div>
    <?
    $this->includefile('orderlinesother');
    ?>
</div>
<?
}
?>

<div class='ordersummary'>
    <div class="cartitem header">
       <?
       $totalEx = $this->getApi()->getOrderManager()->getTotalAmountExTaxes($order);
       $totalInc = $this->getApi()->getOrderManager()->getTotalAmount($order);
       
       echo $this->__f("Total ex taxes").": ".round($totalEx, 2);
       if (@$order->currency) {
           echo " (".$order->currency.")";
       }
       echo "<br/>".$this->__f("Total inc taxes").": ".round($totalInc, 2);
       
       if (@$order->currency) {
           echo " (".$order->currency.")";
       }
       if ($order->cashWithdrawal) {
            echo "<br/>".$this->__f("Cash withdrawal").": ".$order->cashWithdrawal;
       }
       ?>
        <span class="price"></span>
    </div>
</div>
<?
if ($order->isCreditNote) {
    $incid = $this->getApi()->getOrderManager()->getIncrementalOrderIdByOrderId($order->parentOrder);
    echo "<span style='font-weight: bold; padding: 20px; color: red;'>Credit note! ref id: $incid</span>";
}
?>

<div class='searchForProductBox'>
    <div class='searchForProductBoxInner'>
        <div class='closebutton'><i class='fa fa-close'></i></div>
        <input class='gsniceinput1 searchword' placeholder='<? echo $this->__f("Product name"); ?>'/><div class='gs_shop_small_icon doproductsearch'><i class='fa fa-search'></i></div>    
        <div class='searchresult'>
            <?
            $this->includefile("productsearchresult");
            ?>
        </div>
    </div>
</div>
<div style="margin-left: 20px;">
    <span class="shop_button" onclick='window.open("/scripts/downloadInvoice.php?orderId=<?php echo $order->id; ?>&incrementalOrderId=<?php echo $order->incrementOrderId; ?>");'>Download</span>
</div>
