<?
/* @var $this ns_4be8e427_bead_491e_8d9f_7dd16356d8eb\OrderView */
$order = $this->getOrder();
$totalForOrderInLocalCurrency = 0;

if(!@$order->currency) {
    $order->currency = "NOK";
}

if ($order->currency) {
    $totalForOrderInLocalCurrency = $this->getApi()->getOrderManager()->getTotalForOrderInLocalCurrencyById($order->id);
}
?>

<div class="summaryheader"><? echo $this->__f("Payment history"); ?></div>
<?
if (!count($order->orderTransactions)) {
    echo "<div class='warning_not_sent'>";
        echo "<i class='fa fa-warning'></i> ".$this->__f("This order has no payment records");
    echo "</div>";
} else {
    echo "<div class='shipmentlogline'>";
        echo "<div class='date'>".$this->__f("Date")."</div>";
        echo "<div class='amount'>".$this->__f("Amount")."</div>";
        echo "<div class='user'>".$this->__f("By user")."</div>";
        echo "<div class='comment'>".$this->__f("Comment")."</div>";
        echo "<div class='addeddate'>".$this->__f("Date added")."</div>";
    echo "</div>";
    foreach ($order->orderTransactions as $paymentLog) {
        $type = "";
        if (@$paymentLog->accountingDetailId) {
            $accountingDetail = $this->getApi()->getProductManager()->getAccountingDetailById($paymentLog->accountingDetailId);
            $type = $accountingDetail->accountNumber . " - " . $accountingDetail->description;
        }
        $user = $this->getApi()->getUserManager()->getUserById($paymentLog->userId);
        echo "<div class='shipmentlogline'>";
            echo "<div class='date'>".date('d.m.Y H:i', strtotime($paymentLog->date))."</div>";
            
            echo "<div class='amount'>";
                echo $paymentLog->amount;
                if (@$paymentLog->amountInLocalCurrency) {
                    echo "<br/> Local: ".$paymentLog->amountInLocalCurrency;
                }
                if (@$paymentLog->agio) {
                    echo "<br/> Agio: ".$paymentLog->agio;
                }
            echo "</div>";
            
            echo "<div class='user'>".$user->fullName."</div>";
            echo "<div class='comment'>";
                echo $type;
                if($paymentLog->transactionType == 4) {
                    echo "Registered as loss";
                }
                if ($type && $paymentLog->comment) {
                    echo " / ";
                }
                echo @$paymentLog->comment."</div>";
            echo "<div class='addeddate'>".date('d.m.Y H:i', strtotime($paymentLog->rowCreatedDate))."</div>";
        echo "</div>";
    }
}

$accounts = $this->getApi()->getProductManager()->getAccountingAccounts();
$feeAccounts = array();
foreach ($accounts as $account) {
    if ($account->type == "fee") {
        $feeAccounts[] = $account;
    }
}
?>
<div style='margin:10px;'>
    <span class='shop_button actiontabbtn' tab='registerpayment'>Manually register a payment</span>
    <span class='shop_button actiontabbtn' tab='registerloss'>Register loss</span>
    <span class='shop_button actiontabbtn' tab='registeraglorounding'>Register rounding or currency loss</span>
</div>

<div class='registerpaymentactionarea' style='margin: 10px;'>
    <div class='actiontabarea' actiontab='registerloss'><?php $this->includefile("registerloss"); ?></div>
    <div class='actiontabarea' actiontab='registerpayment'><?php $this->includefile("registerpayment"); ?></div>
    <div class='actiontabarea' actiontab='registeraglorounding'><?php $this->includefile("registeraglorounding"); ?></div>
</div>
<script>
    $('.manualregisterpaymentdate').datepicker({ dateFormat: "dd.mm.yy"});
</script>