<?php
/* @var $this ns_4be8e427_bead_491e_8d9f_7dd16356d8eb\OrderView */
$generalconfig = $this->getApi()->getPaymentManager()->getGeneralPaymentConfig();
$roundingAccount = $generalconfig->conversionAccount;
$currencyAccount = $generalconfig->agioAccount;
$dissAgioAccount = $generalconfig->dissAgioAccount;
$order = $this->getOrder();
$restAmount = $order->restAmount;
$now = date("d.m.Y", time());
?>
<h1>Register rounding</h1>
<div class='registerRoundingAgioForm'>
    <input type='hidden' gsname='orderid' value='<?php echo $order->id; ?>'>
    
    <div>
        <span style='display: inline-block; width: 200px;'>Date</span>
        <span style='display: inline-block; width: 200px;'>Comment</span>
        <span style='display: inline-block; width: 200px;'>Value</span>
    </div>
    
    <input class="gsniceinput1 aglodate" gsname='date' value="<? echo $now; ?>" />
    <input class="gsniceinput1 aglocomment" gsname='comment' placeholder="<? echo $this->__f('Optional comment'); ?>" />
    <input type='txt' class='gsniceinput1' gsname='amount' value='<?php echo $restAmount; ?>' style='width:40px;'>
    <br>
    <br>
    <div style='margin-bottom: 5px;'><span class='shop_button registerRoundingAgioBtn' transactiontype='6' style='width:410px;text-align:left;'>Register rounding <span style='float:right;'>(posting to account <?php echo $roundingAccount; ?>)</span></span></div>
    <div style='margin-bottom: 5px;'><span class='shop_button registerRoundingAgioBtn' transactiontype='5' style='width:410px;text-align:left;' gstype='submit'>Register currency earning <span style='float:right;'>(posting to account <?php echo $currencyAccount; ?>)</span></span></div>
    <div style='margin-bottom: 5px;'><span class='shop_button registerRoundingAgioBtn' transactiontype='7' style='width:410px;text-align:left;' gstype='submit'>Register currency loss <span style='float:right;'>(posting to account <?php echo $dissAgioAccount; ?>)</span></span></div>
</div>
