<?php
/* @var $this ns_4be8e427_bead_491e_8d9f_7dd16356d8eb\OrderView */
$order = $this->getOrder();
$restAmount = $order->restAmount;
$total = $this->getApi()->getOrderManager()->getTotalAmount($order);
$percentage = ($restAmount / $total);
if($restAmount <= 0) {
    echo "Nothing to register";
    return;
}
?>
<div>
    <table>
        <tr>
            <td width="400">Product name</td>
            <td>Count</td>
            <td>Total value</td>
        </tr>
        <?php
        $totalRest = 0;
        foreach ($order->cart->items as $item) {
            $totalRest += ($item->count * ($item->product->price * $percentage));
            ?>
            <tr class="registerlossrow" cartitemid='<?php echo $item->cartItemId; ?>'>
                <td><?php echo $item->product->name; ?></td>
                <td><input type='txt' class='gsniceinput1 registerlossinput' gsname='count' value='<?php echo $item->count; ?>' style="width:30px;text-align: center;"></td>
                <td><input type='txt' class='gsniceinput1 registerlossinput' gsname='price' value='<?php echo $item->product->price * $percentage; ?>' style="width:120px;text-align: center;"></td>
            </<tr>
                <?php
            }
            ?>
        <tr>
            <td><div>Total unpaid amount: <span class='totaltoregister'><?php echo $restAmount; ?></span></div></td>
            <td></td>
            <td><input type='txt' class='gsniceinput1 totalissame totalregisterview' value='<?php echo $totalRest; ?>' style="width:120px;text-align: center;" disabled></td>
        </tr>
        <tr>
            <td><div class='amountmissing'>Total amount missing to register as loss: <span class='totalismissing'>0</span></div></td>
            <td></td>
            <td><span class="shop_button doRegisterLoss" style="width:100%; box-sizing: border-box;" orderid='<?php echo $order->id; ?>'>Register loss</span></td>
        </tr>
    </table>
    <?php
    echo "";
    ?>
</div>