<?php
namespace ns_1051b4cf_6e9f_475d_aa12_fc83a89d2fd4;

/* *  @var $menu TopMenu */
$menu = $this;
$entries = $menu->getEntries();
$pageId = $menu->getPage()->javapage->id;


$renaming = false;
$currentUser = \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject();
if(isset($_POST['event']) && $_POST['event'] == "renameEntry") {
    $renaming = true;
}

?>
<i class="fa fa-align-justify mobile_button"></i>

<ul class="breadcrumb-menu" id="topmenuline">
    <li class="mobile" style="display: none;"><? echo $this->__w("Menu"); ?></li>
    <span class="droparea droparea_first"></span>
    <?php
    
    
    
    $this->printEntries($entries, $pageId, $menu, $this, true, $currentUser);
    if (\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
        ?>
        <li class="addnew">
            <span id="add_new_top">
                <i class="fa fa-plus-square" title="<? echo $this->__f("Add new menu entry"); ?>"></i>
            </span>
        </li>
    <?php } ?>
</ul>
<?
if($this->isEditorMode() && !$renaming) {
?>
    <script>
    thundashop.app.TopMenu.activateOrdering();
    </script>
<? } ?>
