<?
/* @var $this ns_9c29f94a_6c42_4590_aa1c_7736c58ff0a5\TicketCreateNew */


?>
<div gstype="form" method="createNewTicket">
    
    <div class='gserrorfield' id='errorMessage'></div>
    
    <? 
    echo $this->__f("Create ticket for").": " ;
    echo "<div style='display: inline-block; width: 500px;'>";
    $quser = new \ns_b5e9370e_121f_414d_bda2_74df44010c3b\GetShopQuickUser();
    if (isset($this->user)) {
        $quser->setUser($this->user);
    }
    $quser->renderApplication(true, $this);    
    echo "</div>";
    ?>
    <div style='margin-top: 10px;'>
        <div style="display: inline-block; vertical-align: top;">
            Type:<br/>
            <select gsname="type" class="gsniceselect1">
                <option value="SUPPORT"><? echo $this->__f("Support"); ?></option>
                <option value="BUG"><? echo $this->__f("Bug"); ?></option>
                <option value="FEATURE"><? echo $this->__f("Feature"); ?></option>
            </select>
        </div>
        <div style="display: inline-block; vertical-align: top;">
            Title:<br/>
            <input class="gsniceinput1" gsname="title" style='height: 29px; line-height: 29px;'/>
        </div>    

        
        <div style='height: 50px; line-height: 50px; margin-top: 18px;' class="shop_button" gstype="submit"><? echo $this->__f("Create"); ?></div>
    </div>
</div>
    