<? /* @var $this ns_cbe3bb0f_e54d_4896_8c70_e08a0d6e55ba\SamleFaktura */
$order = $this->getApi()->getOrderManager()->getOrder($_SESSION['samlefaktura_order_id']);
$user = $this->getApi()->getUserManager()->getUserById($order->userId);

echo "<script>";
echo "window.open('/invoicing.php?page=orderviewpage&orderid=$order->id&tab=sendorder','_blank');";
echo "</script>";

echo "<h2> The order has been opened in new tab, make sure you allow popups from GetShop</h2>";
echo "<br/><a href='/invoicing.php?page=orderviewpage&orderid=$order->id&tab=sendorder'><div class='shop_button'> Open order </div></a>";
    