<?
/* @var $this ns_cbe3bb0f_e54d_4896_8c70_e08a0d6e55ba\SamleFaktura */
$orders = $this->getApi()->getOrderManager()->getAllUnpaid("ns_cbe3bb0f_e54d_4896_8c70_e08a0d6e55ba\SamleFaktura");
$groupedOrders = $this->groupOrdersByUserId($orders);

$total = 0;
foreach ($groupedOrders as $userId => $orders) {
    foreach ($orders as $order) {
        $total += $this->getApi()->getOrderManager()->getTotalAmount($order);
    }
}

if (!$total) {
    echo "<h2>".$this->__f("You dont have any group invoices")."</h2>";
    return;
}


?>
<div gstype='form' method='showSelectUser'>
<?
foreach ($groupedOrders as $userId => $orders) {
    $user = $this->getApi()->getUserManager()->getUserById($userId);
    $total = 0;
    foreach ($orders as $order) {
        $total += $this->getApi()->getOrderManager()->getTotalAmount($order);
    }
    if (!$total)
        continue;
    
    //119525 119858 119524
    
    ?>
    <div class='groupedbyuser'>
        <div class='userinfo'>
            <?
            echo $user->fullName;
            ?>
        </div>

        <?
        foreach ($orders as $order) {
            $incremental = $order->incrementOrderId;
            
            $name = $order->cart->address && isset($order->cart->address->fullName) ? $order->cart->address->fullName : "";
            if (!$name) {
                $user = $this->getApi()->getUserManager()->getUserById($order->userId);
                $name = $user->fullName;
            }
            
            $total = $this->getApi()->getOrderManager()->getTotalAmount($order);
            $date = date("d/m-Y", strtotime($order->rowCreatedDate));
            
            if ($total == 0) {
                continue;
            }
            ?> 
            <div class='row'>
                <div class='col col1'><input type='checkbox' gsname='orderid_<? echo $order->id; ?>' value='<? echo $order->id; ?>'/></div>
                <div class='col col2'><? echo $incremental; ?></div>
                <div class='col col3'><? echo $date; ?></div>
                <div class='col col4'>
                    <?
                    foreach ($order->cart->items as $item) {
                        $metadata = $item->product && $item->product->metaData ? "( " .$item->product->metaData." )" : "";
                        echo "<div style='display: inline-block; width: 49%;'>".$item->count . " x " . $item->product->name." $metadata</div>";
                        
                        
                        if ($item->startDate && $item->endDate) {
                            echo "<div style='display: inline-block; width: 49%;'>".date("d/m-Y", strtotime($item->startDate))." -".date("d/m-Y", strtotime($item->endDate))."</div>";
                        }
                        
                    }
                    ?>
                
                </div>
                <div class='col col5'><? echo $total; ?></div>
            </div>
            <?
        }
    ?>
    </div>
    <?
}
?>
    
    <div gstype='submit' class='shop_button'><? echo $this->__f("Next"); ?></div>
</div>