<?
/* @var $this ns_cbe3bb0f_e54d_4896_8c70_e08a0d6e55ba\SamleFaktura */

$orders = $this->getOrdersToBeConsilidated();

$groupedByUserid = $this->groupOrdersByUserId($orders);

$grandTotal = 0;
foreach ($orders as $order) {
    $grandTotal += $this->getApi()->getOrderManager()->getTotalAmount($order);
}

$allSegments = $this->getApi()->getPmsCoverageAndIncomeReportManager()->getSegments($this->getSelectedMultilevelDomainName());
$allSegments = $this->indexList($allSegments);

$segmentIds = array();
foreach ($orders as $order) {
    $booking = $this->getApi()->getPmsManager()->getBookingWithOrderId($this->getSelectedMultilevelDomainName(), $order->id);
    if(isset($_GET['chooseSegment'])) {
        $this->getApi()->getPmsCoverageAndIncomeReportManager()->forceUpdateSegmentsOnBooking($this->getSelectedMultilevelDomainName(), $booking->id, $_GET['chooseSegment']);
        $booking->segmentId = $_GET['chooseSegment'];
    }
    if ($booking != null) {
        $segmentIds[] = $booking->segmentId;
    }
}

$segmentIds = array_unique($segmentIds);

if (count($segmentIds) > 1) {
    echo "Please make sure that all rooms connected to the orders selected in previouse step are registered to the same segment.<br>";
    echo "We can change the segments to the same segment, just choose the segment you would like to connect this invoice to below.<br>";
    echo "PS: Historical reports will be changed due to this.<br>";
    foreach($segmentIds as $segment) {
        echo $allSegments[$segment]->name . " - <a style='color:blue;' href='/pos.php?page=invoicing&gs_getshopmodule=&chooseSegment=".$segment."'>select</a><br>";
    }
    echo "<br/>";
    echo "<br/>";
} else {
    ?>

    <h2>Summary</h2>
    Orders: <? echo count($orders); ?>
    <br/>Grand total: <? echo $grandTotal; ?>

    <h2>Invoice note?</h2>
    <textarea class='invoicenote' gsname='invoicenote'></textarea>
    <h2>Please select what account/user you want to create this invoice on.</h2>
    <?
    foreach ($groupedByUserid as $userId => $order) {
        $user = $this->getApi()->getUserManager()->getUserById($userId);
        ?>
        <div class='selectUser'>
            Name: <? echo $user->fullName; ?>
            <br/>Email: <? echo $user->emailAddress; ?>
            <br/>Cellphone: <? echo $user->cellPhone; ?>
            <br/>
            <br/>
            <div class='shop_button' gs_also='invoicenote' gsclick='createInvoice' userid='<? echo $user->id; ?>'>Create on this user</div>
        </div>

        <?
    }
}
?>

<div gsclick="cancel" class="shop_button">
    <? echo $this->__f("Cancel"); ?>
</div>