<?
/* @var $this ns_bea0c467_dd4d_4066_891c_172adc42bb9f\SimpleEventBookingSchemaFrigo */

?>

<div gstype='form' method='signup'>
    <div class='row'>
        <div class='col1'>Ditt navn</div>
        <div class='col2'> <input class='gsniceinput1' gsname="name"/> </div>
    </div>
    
    <div class='row'>
        <div class='col1'>Mobilnr</div>
        <div class='col2'> <input class='gsniceinput1' gsname="cellphone"/> </div>
    </div>
    
    <div class='row'>
        <div class='col1'>Epost</div>
        <div class='col2'> <input class='gsniceinput1'  gsname="email"/> </div>
    </div>
    
    <div class='row'>
        <div class='col1'>Skole</div>
        <div class='col2'> <input class='gsniceinput1'  gsname="school"/> </div>
    </div>
    
    <div class='row'>
        <div class='col1'>Klasse</div>
        <div class='col2'> <input class='gsniceinput1'  gsname="schoolclass"/> </div>
    </div>
    
    <div class='row'>
        <div class='col1'>Kjønn</div>
        <select class="gsniceselect1" gsname="sex">
            <option value="dame">Dame</option>
            <option value="dame">Mann</option>
        </select>
    </div>
    
    <div class='row'>
        <div class='col1'>Addresse</div>
        <div class='col2'> <input class='gsniceinput1' placeholder='Gate'  gsname="street"/> </div>
        <div class='col2'> <input class='gsniceinput1' placeholder="Postaddresse"  gsname="postcode"/> </div>
        <div class='col2'> <input class='gsniceinput1' placeholder="By"  gsname="city"/> </div>
    </div>
    
    <div class='row'>
        <div class='col1'>Foresatte</div>
        <div class='col2'> <input class='gsniceinput1' placeholder='Navn på far/mor'  gsname="parentname"/> </div>
        <div class='col2'> <input class='gsniceinput1' placeholder="Mobilnr"  gsname="parentcell"/> </div>
    </div>
    <br/>
    * Grunnet behandling av sensitiv informasjon ønsker vi at dere kontaker oss dersom din sønn/datter trenger spesielle behov angående mat eller annet.
    <br/>
    <br/>
    
    <input type="checkbox" gsname="usepicutres"/> Jeg bekrefter at Frigo kan publisere bilder av min datter/sønn på nett og brosjyrer.
    <br/>
    <br/>
    
    <?
    if (isset($_POST['event']) && $_POST['event'] == "signup") {
        echo "Du er nå meldt på..";
    } else {
    ?>
    <div class='shop_button' gstype="submit">Meld deg på</div>
    <?
    }
    ?>
</div>
