<?
/* @var $this ns_bea0c467_dd4d_4066_891c_172adc42bb9f\SimpleEventBookingSchemaFrigo */
$pageIdToUse = $this->getModalVariable("pageid") ? $this->getModalVariable("pageid") : $this->getPage()->getId();
$event = $this->getApi()->getSimpleEventManager()->getEventByPageId($pageIdToUse);

echo "<hr/>";

echo "<div style='text-align: center; font-weight: bold; margin-top: 40px; margin-bottom: 20px; '> Admin område - påmeldte </div>";
echo "<div class='shop_button' gs_downloadExcelReport='downloadUserList' gs_fileName='deltakerliste'>Last ned excel liste</div><br/><br/>";
foreach ($event->userIds as $userId) {
    $user = $this->getApi()->getUserManager()->getUserById($userId);
    if ($user) {
        echo "<div style='border: solid 1px #EEE; padding: 5px;'>";
        ?>
        <div> Navn: <? echo $user->fullName; ?> </div>
        <div> Fødselsdato <?echo $user->birthDay; ?> </div>
        <div> Mobilnr: <? echo $user->cellPhone; ?> </div>
        <div> Epost: <? echo $user->emailAddress; ?> </div>
        <div> Address: <? echo $user->address->address. " " . $user->address->postCode. " " .$user->address->city; ?> </div>
        <div> Foresatte: <? echo $user->metaData->{'parentName'}. " / " . $user->metaData->{'parentcell'};?> </div>
        <div> Kommentar: <? if(isset($user->metaData->{'comments'})){echo $user->metaData->{'comments'};}?> </div>
        <div> Bruke bilder: <? echo $user->metaData->{'usepictures'}; ?></div>
        <div> Bekreftet over 18: <? echo $user->metaData->{'overAge'}; ?></div>
        <?
        echo "</div>";
    }
}
?>