<?
/* @var $this \ns_15e67fa1_c862_4bc3_9b17_dfd818f30712\HotelbookingManagement */
$date = strtotime($_POST['data']['date']);
$periode = $_POST['data']['periode'];

if($periode == "daily") {
    $daysPeriode = 1;
}
if($periode == "weekly") {
    $daysPeriode = 7;
}
if($periode == "monthly") {
    $daysPeriode = 31;
}
$endrange = $date+(86400*$daysPeriode);

$bdata = $this->getApi()->getHotelBookingManager()->getAllUsersInPeriode($date, $endrange);
?>
<div style='padding: 10px; color:#fff;'>
    <? 
    foreach($bdata as $data) {
        /* @var $data core_hotelbookingmanager_UsersBookingData */
        $user = $this->getApi()->getUserManager()->getUserById($data->additonalInformation->userId);
        $nights = 0;
        $result = "";
        $rooms = 0;
        foreach($data->references as $reference) {
            /* @var $reference core_hotelbookingmanager_BookingReference */
            
            if(strtotime($reference->endDate) < $date || strtotime($reference->startDate) > $endrange) {
                continue;
            }
            
            $res = "";
            foreach($reference->roomsReserved as $roomInfo) {
                $res .= $this->getApi()->getHotelBookingManager()->getRoom($roomInfo->roomId)->roomName . ",";
            }
            $res = substr($res, 0, -1);
            $result .= "($res)<br>";
            
            $nights += (int)round((strtotime($reference->endDate) - strtotime($reference->startDate))/86400);
            
            $result .= "<div style='padding-left: 10px; color:#bbb'>".date("d.m.Y", strtotime($reference->startDate)) . " - " . date("d.m.Y", strtotime($reference->endDate)) . " ($nights nights)<bR>";
            foreach($reference->roomsReserved as $roomInfo) {
                $result .= "&nbsp;&nbsp;" . $roomInfo->visitors[0]->name . " - " . $roomInfo->visitors[0]->phone . " - " . $roomInfo->visitors[0]->email . "<bR>";
                $rooms++;
            }

            $result .= "</div>";
            
        }
        $toUse = $daysPeriode;
        if($daysPeriode > 1) {
            $toUse--;
        }
        if($daysPeriode > $nights) {
            $toUse = $nights;
        }        
        echo $user->fullName . ", " . round(($data->bookingPrice*$toUse*$rooms)) . " NOK, ordered " . $data->rowCreatedDate . ", room ";
        echo $result;
        
        echo "<br>";
    }
    ?>
    
</div>