<?php
namespace ns_15e67fa1_c862_4bc3_9b17_dfd818f30712;

/* @var $this HotelbookingManagement */
$hmanager = $this->getApi()->getHotelBookingManager();
$rooms = $hmanager->getAllRooms();
$newRoom = array();
foreach($rooms as $room) {
    $newRoom[$room->id] = $room;
}
$rooms = $newRoom;

$types = $hmanager->getRoomTypes();
$selectedType = new \core_hotelbookingmanager_RoomType();
if(isset($_POST['data']['typeId'])) {
    foreach($types as $type) {
        if($type->id == $_POST['data']['typeId']) {
            $selectedType = $type;
        }
    }
}
?>

<? echo $this->__w("Add a room"); ?>
<div gstype="form" method="addRoom">
    <input type="text" gsname="roomname" placeholder="Room name">
    <input type="hidden" gsname="newroom" value="true">
    <input type="submit" gstype="submit" gsname="submit">
</div>
<br>
<? 
if(isset($_POST['data']['updated'])) { 
    echo "<span class='updatedtext' style='float:right;'>Data har blitt oppdatert.</span>";
    ?>
    <script>
        setTimeout(function() {
            $('.updatedtext').hide();
        }, "2000");
    </script>
    <?
}
?>
Existing rooms:<br>
<div style="padding:10px; border: solid 1px;background-color:#EFEFEF;">
    <table width="100%" gstype='form' method='addRoom'>
        <input type="hidden" value="true" gsname="updated">
        <tr>
            <td colspan='6' align='center'><div style='text-align:right'><i class='fa fa-floppy-o' style='cursor:pointer; color:green;' gstype='submit'></div></td>
        </tr>

        <tr>
            <td></td>
            <td>Room type</td>
            <td>Active</td>
            <td>Room name</td>
            <td>Lock id</td>
            <td>Current code</td>
        </tr>
        <?
        foreach($rooms as $room) {
            $this->printRoomRow($room, $types);
        }
        ?>
        <tr>
            <td colspan='6' align='center'><div style='text-align:right'><i class='fa fa-floppy-o' style='cursor:pointer; color:green;' gstype='submit'></div></td>
        </tr>
    </table>
</div>
<br>
<br>
<br>
<br>

<? echo $this->__w("New room type"); ?>
<div style="padding:10px; border: solid 1px;background-color:#EFEFEF;">
    <div>
        <select id="type">
            <?
                foreach($types as $type) {
                    echo "<option value='" . $type->id . "'>" . $type->name . "</option>";
                }
            ?>
        </select>
        <span class="edit_type">Edit</span>
        <span class="delete_type">Delete</span>
    </div>
    <div gstype="form" method="addType">
        <input type="hidden" gsname="id" value="<? echo $selectedType->id; ?>">
        <input gstype="value" type="txt" gsname='name' placeholder="Enter a name for the room type" style="width:50%;" value="<? echo $selectedType->name; ?>"><br>
        <input gstype="value" type="txt" gsname='en_desc' placeholder="Enter the norwegian description" style="width:50%;"  value="<? echo $selectedType->description_no; ?>"><br>
        <input gstype="value" type="txt" gsname='no_desc' placeholder="Enter the english description" style="width:50%;"  value="<? echo $selectedType->description_en; ?>"><br>
        <input gstype="submit" type="button" value="save">
    </div>
</div>
<br>
<br>
<br>
Existing booking references
<div style="padding:10px; border: solid 1px;background-color:#EFEFEF;">
    <table width="100%">
        <tr>
            <th>Registration date</th>
            <th>Reserved by</th>
            <th>Reservation number</th>
            <th>Room (code)</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Remove</th>
        </tr>
        <?
        $reservations = $this->getApi()->getHotelBookingManager()->getAllReservations();
        foreach($reservations as $reservation) {
            $roomarray = array();
            /* $rooms \core_hotelbookingmanager_Room[] */
            foreach($reservation->roomIds as $index => $id) {
                $roomarray[] = $rooms[$id]->roomName . " (" . $reservation->codes[$index] . ")";
            }

            $order = $this->getApi()->getOrderManager()->getOrderByReference($reservation->bookingReference);
            
            /* @var $reservation \core_hotelbookingmanager_BookingReference */
            echo "<tr>";
            echo "<td>" . $reservation->rowCreatedDate . "</td>";
            echo "<td>";
            if($order) {
                $user = $this->getApi()->getUserManager()->getUserById($order->userId);
                echo "<a href='?page=users_all_users&userid=".$order->userId."'>" . $user->fullName . "</a>";
            }
            echo "</td>";
            echo "<td style='text-align:center;'>" . $reservation->bookingReference . "</td>";
            echo "<td style='text-align:center;'>" . join(", ", $roomarray) . "</td>";
            echo "<td style='text-align:center;'>" . $reservation->startDate . "</td>";
            echo "<td style='text-align:center;'>" . $reservation->endDate . "</td>";
            echo "<td style='text-align:center;'><i style='cursor:pointer' refid='".$reservation->bookingReference."' class='fa fa-trash-o delete_reference'></td>";
            echo "</tr>";
        }
        ?>
    </table>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>