<?php
namespace ns_15e67fa1_c862_4bc3_9b17_dfd818f30712;

/* @var $this HotelbookingManagement */
$hmanager = $this->getApi()->getHotelBookingManager();
$config = $this->getConfiguration();
$rooms = $hmanager->getAllRooms();
$newRoom = array();
foreach($rooms as $room) {
    $newRoom[$room->id] = $room;
}
$rooms = $newRoom;

if(isset($_POST['data']['updated'])) { 
    echo "<span class='updatedtext' style='float:right;'>Data har blitt oppdatert.</span>";
    ?>
    <script>
        setTimeout(function() {
            $('.updatedtext').hide();
        }, "2000");
    </script>
    <?
}
?>
<br>
    
    Check availability<br>
    <div gstype="form" method="displayHotelBookingOverview">
        <input type="text" gsname="startdate" value='<? echo date("d-m-Y", $this->getStartDate()); ?>'>
        <input type="text" gsname="enddate" value='<? echo date("d-m-Y", $this->getEndDate()); ?>'> 
    <input type="button" gstype="submit" value="Oppdater">
    </div>
    <? 
    if(isset($_POST['data']['startDate'])) {
        $this->displayRoomAvailability(); 
    }
    ?>
<br>
<div style="clear:both;"></div>
<br>
<br>
    
Existing booking references
<div style="">
    <table width="100%" id="datatableadmin">
        <thead>
            <tr>
                <th>Ref id</th>
                <th>Different actions</th>
                <th>Registration date</th>
                <th>Reserved by</th>
                <th>Start date</th>
                <th>End date</th>
                <th>Payed for</th>
            </tr>
        </thead>
        <tbody>
        <?
        $bookingData = $this->getApi()->getHotelBookingManager()->getAllUsersBookingData();
        foreach($bookingData as $bdata) {
            /* @var $bdata \core_hotelbookingmanager_UsersBookingData */
            foreach($bdata->references as $reservation) {
                if($bdata->sessionId) {
                    //Only display completed reservations.
                    continue;
                }
                
                $roomarray = array();
                /* $rooms \core_hotelbookingmanager_Room[] */
                foreach($reservation->roomsReserved as $roomsReserved) {
                    $roomarray[] = "<span class='editroom' style='cursor:pointer;' refid='".$reservation->bookingReference."' roomid='$roomsReserved->roomId'>" . $rooms[$roomsReserved->roomId]->roomName . "</span>";
                }

                $order = $this->getApi()->getOrderManager()->getOrderByReference($reservation->bookingReference);
                $alreadyConfirmed = $reservation->confirmed;

                /* @var $reservation \core_hotelbookingmanager_BookingReference */
                echo "<tr reservation='".$reservation->bookingReference."'>";
                echo "<td style='text-align:center;' valign='top'>" . $reservation->bookingReference . "</td>";
                echo "<td style='text-align:left;' valign='top'>"
                . "<i style='cursor:pointer' refid='".$reservation->bookingReference."' class='fa fa-trash-o delete_reference'></i>";

                if($bdata->additonalInformation->isPartner) {
                    if(!$bdata->active) {
                        echo "&nbsp;&nbsp;&nbsp;<i class='fa fa-play go_live' bookingid='".$bdata->id."'></i>";
                    } else {
                        echo "&nbsp;&nbsp;&nbsp;<i class='fa fa-stop stop_reference_action' bookingid='".$bdata->id."'></i>";
                    }
                }
                echo "&nbsp;&nbsp;&nbsp;<i class='fa fa-info-circle' booking-id='".$bdata->id."'></i>";
                
                echo "</td>";
                echo "<td valign='top'>".$bdata->rowCreatedDate."</td>";
                echo "<td valign='top'>";
                foreach($reservation->roomsReserved as $reservedRoom) {
                    /* @var $reservedRoom \core_hotelbookingmanager_RoomInformation */
                    foreach($reservedRoom->visitors as $visitor) {
                        echo "rom: ". $rooms[$reservedRoom->roomId]->roomName. "&nbsp;" . $visitor->name  . ", " . $visitor->phone . "<bR>";
                    }
                }
                echo "</td>";
                echo "<td style='text-align:center;' valign='top'>" . date("d-m-Y", strtotime($reservation->startDate)) . "</td>";
                echo "<td style='text-align:center;' valign='top'>" . date("d-m-Y", strtotime($reservation->endDate)) . "</td>";
                echo "<td align='center'>";
                if($bdata->additonalInformation->isPartner) {
                    echo "-";
                } else {
                    if($bdata->payedFor) {
                        echo "Yes";
                    } else {
                        echo "No";
                    }
                }
                
                echo "</td>";
                echo "</tr>";
                break;
            }
        }
        ?>
        </tbody>
    </table>
</div>
<br>
<br>
<br>
<script>
    $('#datatableadmin').DataTable({
            "bJQueryUI": true,
            "aLengthMenu": [[10, 25, 50, 100, 200, -1], [10, 25, 50, 100, 200, "All"]],
            "iDisplayLength": 1000
        });
</script>
<br>

<? echo $this->__w("Add a room"); ?>
<div gstype="form" method="addRoom">
    <input type="text" gsname="roomname" placeholder="Room name">
    <input type="hidden" gsname="newroom" value="true">
    <input type="submit" gstype="submit" gsname="submit">
</div>
<br>
Existing rooms:<br>
<div style="padding:10px; border: solid 1px;background-color:#EFEFEF;">
    <table width="100%" gstype='form' method='addRoom' cellspacing="0" cellpadding="2">
        <input type="hidden" value="true" gsname="updated">
        <tr>
            <td colspan='6' align='center'><div style='text-align:right'><i class='fa fa-floppy-o' style='cursor:pointer; color:green;' gstype='submit'></div></td>
        </tr>

        <tr>
            <td></td>
            <td width='10'>Room type</td>
            <td width='10'>Active</td>
            <td>Last reservation</td>
            <td>Room name</td>
            <td align="right">
                <i class='fa fa-eraser' style='display:inline-block; width:14px; margin-right:3px;'></i>
                <i class='fa fa-bed' style='display:inline-block; width:14px; margin-right:3px;'></i>
                <i class='fa fa-wheelchair' style='display:inline-block; width:14px; margin-right:3px;'></i>
            </td>
        </tr>
        <?
        $products = $this->getApi()->getProductManager()->getAllProducts();
        foreach($rooms as $room) {
            $this->printRoomRow($room,$products);
        }
        ?>
        <tr>
            <td colspan='6' align='center'><div style='text-align:right'><i class='fa fa-floppy-o' style='cursor:pointer; color:green;' gstype='submit'></div></td>
        </tr>
    </table>
</div>
<br>
<br>
<br>
<br>
<? if($this->getFactory()->getStore()->id == "3292fa74-32a2-4d52-b88f-6be6f3dff813") { ?>

    <b>Information related to the contract</b>
    <table gstype="form" method="saveContractData">
        <tr>
            <td>landlord's name</td>
            <td><input type="text" gsname="utleier_navn" value="<? echo $this->getConfigurationSetting("utleier_navn"); ?>"></td>
        </tr>
        <tr>
            <td>landlord's address</td>
            <td><input type="text" gsname="utleier_adresse" value="<? echo $this->getConfigurationSetting("utleier_adresse"); ?>"></td>
        </tr>
        <tr>
            <td>landlord's place</td>
            <td><input type="text" gsname="utleier_sted" value="<? echo $this->getConfigurationSetting("utleier_sted"); ?>"></td>
        </tr>
        <tr>
            <td>landlord's postal code</td>
            <td><input type="text" gsname="utleier_postnr" value="<? echo $this->getConfigurationSetting("utleier_postnr"); ?>"></td>
        </tr>
        <tr>
            <td></td>
            <td><input gstype="submit" type="button" value="Lagre"></td>
        </tr>
    </table>
    <br>
    <b>Variables in use for contracts</b>
    <pre>
    [navn] = leietakers navn
    [org_fnr] = fødseldato eventuelt orgnr
    [postaddr] = adressen for leier
    [rom] = Rommet som skal leies ut
    [areal] = Størrelsen på boden / rommet
    [startdato] = Startdato   
    [pris] = Prisen ved inngåelse av leie
    [year] = Året
    [adresse] = Kundens adresse
    [postnr] = Kundens postadresse
    [dagensdato] = Dagens dato
    [dag_i_maned] = Dag i måned for bestilling
    [admingebyr] = Administrasjons gebyr
    [taxes] = Skatter og avgifter
    [total_price] = Total pris ink. skatter og avgifter.

    [belop_forslag] = Forslag på pris
    [utleier_sted] = Sted som kontrakten skrives ut på
    [utleier_navn] = Navnet på utleier
    [utleier_adresse] = Utleiers adresse
    [utleier_postnr] = Utleiers postnummer
    </pre>
<? } ?>


<b>Arx server</b>
<div>Variabler: {code}, {room}, {checkin_time}, {checkout_time}, {name}, {checkin_date}, {referenceNumber, {contacts}, {roomName}, {email}, {address}, {postCode}, {city}</div>
<table gstype="form" method="saveArxData">
    <tr><td>Sms from</td><td><input type="text" gsname="arx_smsfrom" value="<? echo $this->getConfigurationSetting("arx_smsfrom"); ?>"></td><tr>
    <tr><td>Sms welcome</td><td><input style="width: 800px;" type="text" gsname="arx_smswelcome" value="<? echo $this->getConfigurationSetting("arx_smswelcome"); ?>"></td><tr>
    <tr><td>Sms ready</td><td><input style="width: 800px;" type="text" gsname="arx_smsready" value="<? echo $this->getConfigurationSetting("arx_smsready"); ?>"></td><tr>
    <tr><td>Sms welcome (no)</td><td><input style="width: 800px;" type="text" gsname="arx_smswelcomeNO" value="<? echo $this->getConfigurationSetting("arx_smswelcomeNO"); ?>"></td><tr>
    <tr><td>Sms ready (no)</td><td><input style="width: 800px;" type="text" gsname="arx_smsreadyNO" value="<? echo $this->getConfigurationSetting("arx_smsreadyNO"); ?>"></td><tr>
    <tr><td>Welcome email title</td><td><input style="width: 800px;" type="text" gsname="arx_welcomeemail_title" value="<? echo $this->getConfigurationSetting("arx_welcomeemail_title"); ?>"></td><tr>
    <tr><td>Welcome email</td><td><textarea style="width: 800px;height:200px;" type="text" gsname="arx_welcomeEmail"><? echo $this->getConfigurationSetting("arx_welcomeEmail"); ?></textarea></td><tr>
    <tr><td>Welcome email title (no)</td><td><input style="width: 800px;" type="text" gsname="arx_welcomeemail_title_no" value="<? echo $this->getConfigurationSetting("arx_welcomeemail_title_no"); ?>"></td><tr>
    <tr><td>Welcome email (no)</td><td><textarea style="width: 800px;height:200px;" type="text" gsname="arx_welcomeEmailNO"><? echo $this->getConfigurationSetting("arx_welcomeEmailNO"); ?></textarea></td><tr>
    <tr><td></td><td><input gstype="submit" type="button" value="Save"></td><tr>
</table>
<br><br>


<b>Arx log</b>
<div class="arx_log">
    <?
    $this->includefile("arxlog");
    ?>
</div>
<br>
<br>
<br>
<script>
    setInterval(function(){ app.HotelbookingManagement.refreshArxLog(); }, 5000);
</script>
