<?php
namespace ns_15e67fa1_c862_4bc3_9b17_dfd818f30712;

/* @var $this HotelbookingManagement */
$hmanager = $this->getApi()->getHotelBookingManager();
$rooms = $hmanager->getAllRooms();
$newRoom = array();
foreach($rooms as $room) {
    $newRoom[$room->id] = $room;
}
$rooms = $newRoom;

$types = $hmanager->getRoomTypes();
$selectedType = new \core_hotelbookingmanager_RoomType();
if(isset($_POST['data']['typeId'])) {
    foreach($types as $type) {
        if($type->id == $_POST['data']['typeId']) {
            $selectedType = $type;
        }
    }
}

if(isset($_POST['data']['updated'])) { 
    echo "<span class='updatedtext' style='float:right;'>Data har blitt oppdatert.</span>";
    ?>
    <script>
        setTimeout(function() {
            $('.updatedtext').hide();
        }, "2000");
    </script>
    <?
}
?>
<br>
<br>
<br>
    
Existing booking references
<div style="padding:10px; border: solid 1px;background-color:#EFEFEF;">
    <table width="100%">
        <tr>
            <th>Remove</th>
            <th>Registration date</th>
            <th>Reserved by</th>
            <th>Reservation number</th>
            <th>Room (code)</th>
            <th>Start date</th>
            <th>End date</th>
            <? if($this->getFactory()->getStore()->id == "3292fa74-32a2-4d52-b88f-6be6f3dff813") { ?>
                <th>Gebyr</th>
                <th>Contract</th>
            <? } ?>
        </tr>
        <?
        $reservations = $this->getApi()->getHotelBookingManager()->getAllReservations();
        foreach($reservations as $reservation) {
            $roomarray = array();
            /* $rooms \core_hotelbookingmanager_Room[] */
            foreach($reservation->roomIds as $index => $id) {
                $roomarray[] = "<span class='editroom' style='cursor:pointer;' refid='".$reservation->bookingReference."' roomid='$id'>" . $rooms[$id]->roomName . " (" . $reservation->codes[$index] . ")</span>";
            }

            $order = $this->getApi()->getOrderManager()->getOrderByReference($reservation->bookingReference);
            /* @var $reservation \core_hotelbookingmanager_BookingReference */
            echo "<tr reservation='".$reservation->bookingReference."'>";
            echo "<td style='text-align:center;' valign='top'><i style='cursor:pointer' refid='".$reservation->bookingReference."' class='fa fa-trash-o delete_reference'></td>";
            echo "<td valign='top'>" . $reservation->rowCreatedDate . "</td>";
            echo "<td valign='top'>";
            if($order && $order->userId) {
                $user = $this->getApi()->getUserManager()->getUserById($order->userId);
                echo "<a href='?page=users_all_users&userid=".$order->userId."'>";
                echo join("<br>", $reservation->contact->names);
                echo "</a>";
            }
            echo "</td>";
            echo "<td style='text-align:center;' valign='top'>" . $reservation->bookingReference . "</td>";
            echo "<td style='text-align:center;' valign='top'>" . join("<br>", $roomarray) . "</td>";
            echo "<td style='text-align:center;' valign='top'>" . $reservation->startDate . "</td>";
            echo "<td style='text-align:center;' valign='top'>" . $reservation->endDate . "</td>";
            if($this->getFactory()->getStore()->id == "3292fa74-32a2-4d52-b88f-6be6f3dff813") {
                echo "<td style='text-align:center;' valign='top'><input type='text' style='width: 40px;' class='adminfee' value='".$reservation->bookingFee."'></td>";
                echo "<td style='text-align:center;' valign='top'>";
                echo "<a target='_new' onclick=\"window.open('/scripts/generateContract.php?userid=".@$user->id."&refid=".$reservation->bookingReference."&type=standard')\"><i style='cursor:pointer' refid='".$reservation->bookingReference."' userkey='".@$user->referenceKey."' class='fa fa-file-pdf-o'></i></a> ";
                echo "<a target='_new' onclick=\"window.open('http://".$_SERVER['SERVER_NAME']."/scripts/generateContract.php?userid=".@$user->id."&refid=".$reservation->bookingReference."&type=bilag')\"><i style='cursor:pointer' refid='".$reservation->bookingReference."' userkey='".@$user->referenceKey."' class='fa fa-plus'></i></a> ";
                echo "<a target='_new' onclick=\"window.open('http://".$_SERVER['SERVER_NAME']."/scripts/generateContract.php?userid=".@$user->id."&refid=".$reservation->bookingReference."&type=autogiro')\"><i style='cursor:pointer' refid='".$reservation->bookingReference."' userkey='".@$user->referenceKey."' class='fa fa-car'></i></a>";
                echo "</td>";
            }
            echo "</tr>";
        }
        ?>
    </table>
</div>
<br>
<br>
<br>
<br>

<? echo $this->__w("Add a room"); ?>
<div gstype="form" method="addRoom">
    <input type="text" gsname="roomname" placeholder="Room name">
    <input type="hidden" gsname="newroom" value="true">
    <input type="submit" gstype="submit" gsname="submit">
</div>
<br>
Existing rooms:<br>
<div style="padding:10px; border: solid 1px;background-color:#EFEFEF;">
    <table width="100%" gstype='form' method='addRoom' cellspacing="0" cellpadding="2">
        <input type="hidden" value="true" gsname="updated">
        <tr>
            <td colspan='6' align='center'><div style='text-align:right'><i class='fa fa-floppy-o' style='cursor:pointer; color:green;' gstype='submit'></div></td>
        </tr>

        <tr>
            <td></td>
            <td>Room type</td>
            <td>Active</td>
            <td>Room name</td>
            <td>Lock id</td>
        </tr>
        <?
        foreach($rooms as $room) {
            $this->printRoomRow($room, $types);
        }
        ?>
        <tr>
            <td colspan='6' align='center'><div style='text-align:right'><i class='fa fa-floppy-o' style='cursor:pointer; color:green;' gstype='submit'></div></td>
        </tr>
    </table>
</div>
<br>
<br>
<br>
<br>

<? echo $this->__w("New room type"); ?>
<div style="padding:10px; border: solid 1px;background-color:#EFEFEF;">
    <div>
        <select id="type">
            <?
                foreach($types as $type) {
                    echo "<option value='" . $type->id . "'>" . $type->name . "</option>";
                }
            ?>
        </select>
        <span class="edit_type">Edit</span>
        <span class="delete_type">Delete</span>
    </div>
    <div gstype="form" method="addType">
        <input type="hidden" gsname="id" value="<? echo $selectedType->id; ?>">
        <input gstype="value" type="txt" gsname='name' placeholder="Enter a name for the room type" style="width:50%;" value="<? echo $selectedType->name; ?>"><br>
        <input gstype="value" type="txt" gsname='en_desc' placeholder="Enter the norwegian description" style="width:50%;"  value="<? echo $selectedType->description_no; ?>"><br>
        <input gstype="value" type="txt" gsname='no_desc' placeholder="Enter the english description" style="width:50%;"  value="<? echo $selectedType->description_en; ?>"><br>
        <input gstype="submit" type="button" value="save">
    </div>
</div>
<br>
<? if($this->getFactory()->getStore()->id == "3292fa74-32a2-4d52-b88f-6be6f3dff813") { ?>

    <b>Information related to the contract</b>
    <table gstype="form" method="saveContractData">
        <tr>
            <td>landlord's name</td>
            <td><input type="text" gsname="utleier_navn" value="<? echo $this->getConfigurationSetting("utleier_navn"); ?>"></td>
        </tr>
        <tr>
            <td>landlord's address</td>
            <td><input type="text" gsname="utleier_adresse" value="<? echo $this->getConfigurationSetting("utleier_adresse"); ?>"></td>
        </tr>
        <tr>
            <td>landlord's place</td>
            <td><input type="text" gsname="utleier_sted" value="<? echo $this->getConfigurationSetting("utleier_sted"); ?>"></td>
        </tr>
        <tr>
            <td>landlord's postal code</td>
            <td><input type="text" gsname="utleier_postnr" value="<? echo $this->getConfigurationSetting("utleier_postnr"); ?>"></td>
        </tr>
        <tr>
            <td></td>
            <td><input gstype="submit" type="button" value="Lagre"></td>
        </tr>
    </table>
    <br>
    <b>Variables in use for contracts</b>
    <pre>
    [navn] = leietakers navn
    [org_fnr] = fødseldato eventuelt orgnr
    [postaddr] = adressen for leier
    [rom] = Rommet som skal leies ut
    [areal] = Størrelsen på boden / rommet
    [startdato] = Startdato   
    [pris] = Prisen ved inngåelse av leie
    [year] = Året
    [adresse] = Kundens adresse
    [postnr] = Kundens postadresse
    [dagensdato] = Dagens dato
    [dag_i_maned] = Dag i måned for bestilling
    [admingebyr] = Administrasjons gebyr
    [taxes] = Skatter og avgifter
    [total_price] = Total pris ink. skatter og avgifter.

    [belop_forslag] = Forslag på pris
    [utleier_sted] = Sted som kontrakten skrives ut på
    [utleier_navn] = Navnet på utleier
    [utleier_adresse] = Utleiers adresse
    [utleier_postnr] = Utleiers postnummer
    </pre>
<? } ?>


<b>Arx server</b>
<table gstype="form" method="saveArxData">
    <tr><td>Server address</td><td><input type="text" gsname="arx_server" value="<? echo $this->getConfigurationSetting("arx_server"); ?>"></td><tr>
    <tr><td>Server username</td><td><input type="text" gsname="arx_username" value="<? echo $this->getConfigurationSetting("arx_username"); ?>"></td><tr>
    <tr><td>Server password</td><td><input type="text" gsname="arx_password" value="<? echo $this->getConfigurationSetting("arx_password"); ?>"></td><tr>
    <tr><td></td><td><input gstype="submit" type="button" value="Save"></td><tr>
</table>

<b>Visma server</b>
<table gstype="form" method="saveVismaData">
    <tr><td>Server address</td><td><input type="text" gsname="visma_server" value="<? echo $this->getConfigurationSetting("visma_server"); ?>"></td><tr>
    <tr><td>Server username</td><td><input type="text" gsname="visma_username" value="<? echo $this->getConfigurationSetting("visma_username"); ?>"></td><tr>
    <tr><td>Server password</td><td><input type="text" gsname="visma_password" value="<? echo $this->getConfigurationSetting("visma_password"); ?>"></td><tr>
    <tr><td>Server port</td><td><input type="text" gsname="visma_port" value="<? echo $this->getConfigurationSetting("visma_port"); ?>"></td><tr>
    <tr><td></td><td><input gstype="submit" type="button" value="Save"></td><tr>
</table>

<b>Arx log</b>
<div class="arx_log">
    <?
    $this->includefile("arxlog");
    ?>
</div>
<br>
<br>
<br>
<script>
    setInterval(function(){ app.HotelbookingManagement.refreshArxLog(); }, 5000);
</script>

<?php

 $this->getApi()->getHotelBookingManager()->checkForVismaTransfer();
?>