<?php
$refid = $_POST['data']['refid'];
$reference = $this->getApi()->getHotelBookingManager()->getReservationByReferenceId($refid);
echo "<div style='padding:20px;'>";

/* @var $this ns_15e67fa1_c862_4bc3_9b17_dfd818f30712\HotelbookingManagement */
$user = $this->getApi()->getUserManager()->getUserById($reference->userId);

$types = array();
$types['ns_70ace3f0_3981_11e3_aa6e_0800200c9a66\InvoicePayment'] = "Invoice";
$types['ns_d02f8b7a_7395_455d_b754_888d7d701db8\Dibs'] = "Dibs";

$status = array();
$status[1] = "CREATED";
$status[2] = "WAITING_FOR_PAYMENT";
$status[3] = "PAYMENT_FAILED";
$status[4] = "COMPLETED";
$status[5] = "CANCELED";
$status[6] = "SENT";
$status[7] = "NEEDCOLLECTING";

$orders = $this->getApi()->getOrderManager()->getAllOrderByReference($reference->bookingReference);

for($i = 0; $i < sizeof($reference->contact->names);$i++) {
?>
        <input type='hidden' value='<? echo $refid; ?>' id='referenceId'>
        <?
        /* @var $this \ns_15e67fa1_c862_4bc3_9b17_dfd818f30712\HotelbookingManagement */
        $rooms = $this->getApi()->getHotelBookingManager()->getAllRooms();
        echo "<div style='height: 50px;'>";
        echo "<select style='float:right;' name='moveRoomSelection[".$i."]' class='roomselection' oldroom='".$reference->rooms[$i]->roomId."'>";
        foreach($rooms as $room) {
            /* @var $room core_hotelbookingmanager_Room */
            $selected = "";
            if($room->id == $reference->rooms[$i]->roomId) {
                $selected = "SELECTED";
            }
            
            echo "<option value='".$room->id."' ".$selected.">" . $room->roomName . "</option>";
        }
            ?>
            </select>
            <b><? echo $this->__f("Select a new room for") . " " . $reference->contact->names[$i]; ?> </b><br>
            <bR>
<?php } ?>
</div>
<div>
    <input type="text" class='startdate' style="float:right;" value='<? echo date("d-m-Y", strtotime($reference->startDate)); ?>'>
    Start date<br>
    <br>
</div>
<div>
    <input type="text" class='enddate' style="float:right;" value='<? echo date("d-m-Y", strtotime($reference->endDate)); ?>'>
    End date<br>
    <br>
</div>
<div>
    <input type="text" class='monthlyprice' style="float:right;" value='<? echo $reference->bookingFee; ?>'>
    Monthly price<br>
    <br>
</div>
<div>
    <input type="text" class='invoicedTo' style="float:right;" value='<? echo date("d.m.Y", strtotime($reference->invoicedTo)); ?>'>
    Next payment periode<br>
    <br>
</div>
<div>
    <select class='paymentType' style="float:right;">
        <?php
        foreach($types as $idx => $value) {
            $selected = "";
            if($user->preferredPaymentType == $idx) {
                $selected = "SELECTED";
            }
            echo "<option value='$idx' $selected>$value</option>";
        }
        ?>
        
    </select>
    Payment type<br>
    <br>
</div>
    <div style="text-align:right;">
        <input type="button" id="doChangeRoom" value="<? echo $this->__f("Update room"); ?>">
    </div>
</div>
<div style='padding: 10px;'>
<?php
echo "<table width='100%'>";
echo "<tr>";
echo "<th>Order id</th>";
echo "<th>Created date</th>";
echo "<th>Amount</th>";
echo "<th>Type</th>";
echo "<th>Status</th>";
echo "<th align='right'>Transferred</th>";
echo "</tr>";

foreach($orders as $order) {
    /* @var $order core_ordermanager_data_Order */
    echo "<tr>";
    echo "<td><a href='/?page=orderoverview&action=showorder&orderid=".$order->id."'>" . $order->incrementOrderId . "</a></td>";
    echo "<td>" . $order->rowCreatedDate . "</td>";
    echo "<td>" . $this->getApi()->getOrderManager()->getTotalAmount($order) . "</td>";
    if(!$order->transferedToAccountingSystem) {
        echo "<td>";
        echo "<select class='orderpaymenttype' orderid='".$order->id."' refid='".$reference->bookingReference."'>";
        foreach($types as $idx => $value) {
            $selected = "";
            if($order->payment->paymentType == $idx) {
                $selected = "SELECTED";
            }
            echo "<option value='$idx' $selected>$value</option>";
        }
        echo "</select>";
        echo "</td>";
    } else {
        echo "<td>" . $types[$order->payment->paymentType] . "</td>";
    }
    echo "<td>" . $status[$order->status];
    if($order->status == 2) {
        echo " - <a href='/?page=88c6642a-1c28-4b86-9a15-4b69e0303e05&payOrder=".$order->id."' style='color:blue;' target='_new'> payment link</a>";
    }
    echo "</td>";
    echo "<td align='right'>";
    if(@$order->transferedToAccountingSystem) {
        echo "Yes";
    } else {
        echo "No";
    }
    echo "</td>";
    echo "</tr>";
}
echo "</table>";
?>
</div>