<div style="padding: 20px; font-size: 16px; color: #FFF;" class="boxcontent">
    <?
    echo $this->__f("Are you sure you want to stop this reference?");
    ?>
    <div style="font-weight: bold; border: solid 1px #FFF; padding: 20px; margin-top: 20px; text-align: center;">
        <i class="fa fa-warning" style="font-size: 30px; display: inline-block; color: #AA0000; margin-bottom: 10px;"></i> <br/>
        <? 
            echo $this->__f("As soon as this action is taken there will be no more renewed invoices, all invoices has to be created manually."); 
        ?>    
    </div>
    <div style="margin-top: 20px;">
        <? 
        echo $this->__f("Please select the date you wish to stop this reference").":";
        ?>
        <br/>
        <input type="textfield" id="stopdate" value="<? echo $this->getStoppedReferenceDate($_POST['data']['refid']); ?>"/>
        <br/>
        <br/>
    </div>
    
    <script>
        $('#stopdate').datepicker({ dateFormat: "dd.mm.yy", minDate: "0d" });
    </script>
    
    <div class="gs_button stop_reference_action" ref="<? echo $_POST['data']['refid']; ?>"> Save </div>
</div>