<?
$id = $_POST['data']['bookingid'];
/* @var $bookingData core_hotelbookingmanager_UsersBookingData */
$bookingData = $this->getApi()->getHotelBookingManager()->getUserBookingData($id);
$product = $this->getApi()->getProductManager()->getProduct($bookingData->additonalInformation->roomProductId);

echo "<div style='padding: 10px;'>";
if($bookingData->additonalInformation->isPartner) {
    echo "Price:<br> <input type='text' value='".round($bookingData->bookingPrice,2)."' class='bookingprice' bookingid='$id'>";
    echo "<input type='button' value='Update price' class='updatebookingprice'>";
    echo "<br><br>";
}
echo "<b>room type:</b> " . $product->name . "<br>";
echo "<br><b>Contract:</b> <a href='/scripts/whcontract.php?id=$id' class='gs_ignorenavigate' target='_new'>Open</a><br>";
if(!$bookingData->payedFor) {
    echo "<br><b>Payed for:</b> <span class='markaspayedfor' bdata-id='$id' tyle='cursor:pointer;'>Mark as payed for (for testing)</span><br>";
}
echo "<bR>";
echo "<b>Booked dates</b><BR>";
foreach($bookingData->references as $reference) {
    echo "&nbsp;&nbsp;&nbsp;" . $reference->startDate . " - " . $reference->endDate."<BR>";
}
echo "</div>";
?>

Rooms :
<div style='padding: 20px;'>
<table>
<?
foreach($bookingData->references as $reference) {
    /* @var $reference core_hotelbookingmanager_BookingReference */
    foreach($reference->roomsReserved as $room) {
        /* @var $room core_hotelbookingmanager_RoomInformation */
        foreach($room->visitors as $visitor) {
            echo "<tr roomid='$room->roomId' bookinguserinfo='$bookingData->id' referenceid='$reference->bookingReference'>";
            echo "<td><input type='text' value='".$visitor->name."' name='name'></td>";
            echo "<td><input type='text' value='".$visitor->phone."' name='phone'></td>";
            echo "<td><input type='text' value='".$visitor->email."' name='email'><input type='button' value='Update' class='updatecontactinfo'></td>";
            echo "</tr>";
        }
    }
}
?>
</table>
</div>