<?
/* @var $this ns_15e67fa1_c862_4bc3_9b17_dfd818f30712\HotelbookingManagement */
$id = $_POST['data']['bookingid'];
/* @var $bookingData core_hotelbookingmanager_UsersBookingData */
$bookingData = $this->getApi()->getHotelBookingManager()->getUserBookingData($id);
$product = $this->getApi()->getProductManager()->getProduct($bookingData->additonalInformation->roomProductId);
$rooms = $this->getApi()->getHotelBookingManager()->getAllRooms();
$allRooms = array();
$user = $this->getApi()->getUserManager()->getUserById($bookingData->additonalInformation->userId);


foreach($rooms as $room) {
    $allRooms[$room->id] = $room;
}


echo "<div style='padding: 10px;'>";
if($bookingData->additonalInformation->isPartner) {
    echo "Price:<br> <input type='text' value='".round($bookingData->bookingPrice,2)."' class='bookingprice' bookingid='$id'>";
    echo "<input type='button' value='Update price' class='updatebookingprice'>";
    echo "<br><br>";
}
echo "<b>room type:</b> " . $product->name . "<br>";
echo "<br><b>Contract:</b> <a href='/scripts/whcontract.php?id=$id' class='gs_ignorenavigate' target='_new'>Open</a><br>";
if(!$bookingData->payedFor) {
    echo "<br><b>Payed for:</b> <span class='markaspayedfor' bdata-id='$id' style='cursor:pointer;'>Mark as payed for (for testing)</span><br>";
}
echo "<b>Booked by:</b> <a style='cursor:pointer;' onClick=\"thundashop.common.hideInformationBox();app.Users.gssinterface.showUser('".$user->id."')\">" .$user->fullName . ", open user</a><br>";
echo "<b>Payment links:</b>";
echo "&nbsp;&nbsp;&nbsp;&nbsp;";
foreach($bookingData->orderIds as $orderId) {
     echo "<a target='_new' href='http://".$_SERVER['SERVER_NAME'] . "?page=8d7776e2-2632-4ab9-bd01-86ac2d07899f&repayOrderId=$orderId"."'> open link</a>, ";
}
echo "<br>";
echo "<b>Orders:</b>";
echo "&nbsp;&nbsp;&nbsp;&nbsp;";
foreach($bookingData->orderIds as $orderId) {
     echo "<a style='cursor:pointer;' onClick=\"thundashop.common.hideInformationBox();app.OrderManager.gssinterface.showOrder('".$orderId."')\"> open order</a>, ";
}
echo "<bR>";
echo "<bR>";
echo "<bR>";
echo "<b>Booked dates</b><BR>";
foreach($bookingData->references as $reference) {
    echo "&nbsp;&nbsp;&nbsp; " . $reference->startDate . " - " . $reference->endDate." - <a class='extendstay' data-bdataid='".$bookingData->id."' data-reference='".$reference->bookingReference."' style='cursor:pointer;'>extend stay</a><BR>";
}
echo "</div>";
?>

Rooms :
<div style='padding: 20px;'>
<table>
<?
foreach($bookingData->references as $reference) {
    /* @var $reference core_hotelbookingmanager_BookingReference */
    if(sizeof($bookingData->references) > 1) {
        echo "<tr><td colspan='3'>" . $reference->startDate . " - " . $reference->endDate."</td></tr>";
    }

    foreach($reference->roomsReserved as $room) {
        /* @var $room core_hotelbookingmanager_RoomInformation */
        echo "<tr roomid='$room->roomId' bookinguserinfo='$bookingData->id' referenceid='$reference->bookingReference'>";
        echo "<td colspan='3'>";
        echo "<input type='button' value='Change room' class='changeroombutton'> ";
        echo "<input type='button' value='Remove room ".$allRooms[$room->roomId]->roomName." from order' class='deleteroom' data-roomid='".$room->roomId."' data-reference='".$reference->bookingReference."' data-bdata='".$bookingData->id."'>";
        echo "</td></tr>";
        foreach($room->visitors as $visitor) {
            echo "<tr roomid='$room->roomId' bookinguserinfo='$bookingData->id' referenceid='$reference->bookingReference'>";
            echo "<td width='10%'><input type='text' value='".$visitor->name."' name='name'></td>";
            echo "<td width='10%'><input type='text' value='".$visitor->phone."' name='phone'></td>";
            echo "<td width='80%'><input type='text' value='".$visitor->email."' name='email'><input type='button' value='Update ".$allRooms[$room->roomId]->roomName."' class='updatecontactinfo'></td>";
            echo "</tr>";
        }
        echo "<tr><td colspan='3'></td></tr>";
        
        if(sizeof($reference->roomsReserved) > 1) {
            echo "<tr><td>&nbsp;</td></tr>";
        }
    }
    
     if(sizeof($bookingData->references) > 1) {
         echo "<tr><td><br></td></tr>";
     }
}
?>
</table>
</div>