<?php
/* @var $this ns_1ee40ca9_27ac_4b97_944a_0eb02506d5e9\ProductCategories */
?>
<div>
    <div class="gss_settings_header">
        <i class="fa fa-credit-card"></i>

        <div class="gss_settings_header_description">
            <div class="gss_settings_header_title"><? echo $this->__f("Categories"); ?></div>
            <div class="gss_settings_header_description_inner">
                <?
                echo $this->__f("Set up and configure your categories.");
                ?>
            </div>
        </div>	
    </div>

    <div class='gss_settings_content'>
        <input type='text' class='gsniceinput1 gsnomagicposition' gs_model='wtf' gs_model_attr='categoryname' >
        <div class='gss_button' gss_model='wtf' gss_fragment='categoryconfig' gss_method='addCategory'><? echo $this->__f("Create a new category"); ?></div>
    </div>
    
    <div class='gss_settings_content'>
        <h1>Categories are configured from instance configuration, add a category list as an application and configure it.</h1>
    </div>
    
</div>

<script>
    $('#gss_order_filter_startdate').datepicker({ dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true });
    $('#gss_order_filter_enddate').datepicker({ dateFormat: "yy-mm-dd",changeMonth: true, changeYear: true });        
</script>