<?
/* @var $this Page */

if (!$this->getFactory()->isExtendedMode())
    return;
?>

<div class="gs_outer footer">
    <div class="gs_inner">
        <div area='footer' id="apparea-footer" class="applicationarea">
            <?php 
            if (!$this->emptySkeleton)    
                $this->getPage()->getApplicationArea('footer')->render(); 
            ?>
        </div>
    </div>
</div>
