<div class="skelholder skeleton16" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>
    <div class="mainarea">
        <div class='top_row gs_margin_bottom'>
            <div class='fifty fifty_left'>
                <div area='top_1' class="applicationarea apparea-top-1 left_box gs_margin_right">
                    <?php
                    $this->getPage()->getApplicationArea('top_1')->render();
                    ?>
                </div>
            </div>
            <div class='fifty'>
                <div area='top_2' class="applicationarea apparea-top-2 right_box gs_margin_left">
                    <?php
                    $this->getPage()->getApplicationArea('top_2')->render();
                    ?>
                </div>
            </div>
        </div>
        <div class='main_col'>
            <div area='main_1' class="applicationarea apparea-main-1">
                <?php
                $this->getPage()->getApplicationArea('main_1')->render();
                ?>
            </div>
        </div>
    </div>
</div>