<div class='gs_row r1 gs_outer'>
    <div class='gs_inner'>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td width="20%" valign="top" class='gs_col c1 gs_margin_right'>
                    <? AppAreaHelper::printAppArea($this->getPage(), "left_1"); ?>
                </td>
                <td valign="top" class='gs_margin_right gs_margin_left'>
                    <div class='gs_margin_bottom'>
                        <? AppAreaHelper::printAppArea($this->getPage(), "main_1"); ?>
                    </div>
                    <? AppAreaHelper::printRows($this->getPage(), 2); ?>
                </td>
            </tr>
        </table>
    </div>
</div>