<div class="skelholder skeleton2" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>
    <div class="gs_row r1 gs_outer ">
        <div class="gs_inner gs_margin_bottom">
            <table width="100%"  cellspacing='0' cellpadding='0'>
                <tr>
                    <td width="20%" valign="top"  class='app_row_entry'>
                        <div area='left_1' class="applicationarea gs_margin_right">
                            <?php $this->getPage()->getApplicationArea('left_1')->render(); ?>
                        </div>
                    </td>
                    <td valign="top"  class='app_row_entry'>
                        <div area='main_1' class="applicationarea gs_margin_left">
                            <?php $this->getPage()->getApplicationArea('main_1')->render(); ?>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <?php
    $this->includefile('footer');
    ?>
</div>