<div class="skelholder skeleton7" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>
    <div class="gs_outer gs_row r1">
        <div class="gs_inner">
            <table cellspacing="0" cellpadding="0" width="100%">
                <td class='gs_col c1 gs_margin_right' valign="top">
                    <div area='main_1' class="applicationarea gs_margin_bottom">
                        <?php
                        $this->getPage()->getApplicationArea('main_1')->render();
                        ?>
                    </div>
                    <div area='main_2' class="applicationarea">
                        <?php
                        $this->getPage()->getApplicationArea('main_2')->render();
                        ?>
                    </div>
                </td>
                <td class='gs_col c2 gs_margin_left' valign="top">
                    <div area='left_1' class="applicationarea gs_margin_bottom">
                        <?php
                        $this->getPage()->getApplicationArea('left_1')->render();
                        ?>
                    </div>
                    <div area='left_2' class="applicationarea gs_margin_bottom">
                        <?php
                        $this->getPage()->getApplicationArea('left_2')->render();
                        ?>
                    </div>
                    <div area='left_3' class="applicationarea ">
                        <?php
                        $this->getPage()->getApplicationArea('left_3')->render();
                        ?>
                    </div>
                </td>
            </table>
        </div>
    </div>
    
    <?php
        $this->includefile('footer');
    ?>
</div>