<div class="skeleton1">
<?php
$this->includefile('mainmenu');
$this->includefile('header');
?>


<div class="mainarea-outer 1col-layout">
    <div class="mainarea"> 
        <div area='middle' id="apparea-middle" class="applicationarea middle inline">
            <center><h1> Sorry, page not found </h1></center>
        </div>
    </div>
</div>

<?php
    $this->includefile('footer');
    $this->includefile('bottom');
?>
</div>