
<div class="gs_outer gs_row r1">
    <div class='gs_inner'>
        <? AppAreaHelper::printRows($this->getPage(), 3); ?>
    </div>
</div>

<div class="gs_outer gs_row r2 ">
    <div class='gs_inner'>
        <? AppAreaHelper::printAppArea($this->getPage(), "main_1"); ?>
    </div>
</div>
<div class='gs_outer gs_row r3'>
    <div class='gs_inner'>
        <? AppAreaHelper::printAppArea($this->getPage(), "top_2"); ?>
    </div>
</div>
