
<div class="gs_outer gs_row r1">
    <div class='gs_inner'>
        <div class='gs_col c1 gs_margin_right'>
                <? AppAreaHelper::printAppArea($this->getPage(), "main_1", true); ?>
                <? AppAreaHelper::printAppArea($this->getPage(), "main_2", false); ?>
        </div>
        <div class='gs_col c2 gs_margin_left'>
                <? AppAreaHelper::printAppArea($this->getPage(), "left_1", false); ?>
        </div>
        <div class='gs_bottom'></div>
    </div>
</div>