<div class="skelholder skeleton4" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>

    <div class="gs_row r1 gs_outer">
        <div class="gs_inner">
                <div area='main_1'  class="applicationarea gs_margin_bottom">
                    <?php $this->getPage()->getApplicationArea('main_1')->render(); ?>
                </div>    
        </div>
    </div>
</div>

<?php
$this->includefile('footer');
?>
