<div class="skelholder skeleton10" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>
    <div class="gs_outer gs_row r1">
        <div class='gs_inner'>
            <table width="100%" cellspacing='0' cellpadding='0'>
                <tr>
                    <td width='33%' class="gs_col c1">
                        <div area='top_1' class="applicationarea">
                            <?php
                            $this->getPage()->getApplicationArea('top_1')->render();
                            ?>
                        </div>
                    </td>
                    <td width='33%' class="gs_col c2  gs_margin_right gs_margin_left">
                        <div area='top_2' class="applicationarea">
                            <?php
                            $this->getPage()->getApplicationArea('top_2')->render();
                            ?>
                        </div>
                    </td>
                    <td width='33%' class="gs_col c3 gs_margin_left">
                        <div area='top_3' class="applicationarea">
                            <?php
                            $this->getPage()->getApplicationArea('top_3')->render();
                            ?>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="gs_outer gs_row r2 ">
        <div class='gs_inner'>
            <div area='main_1' class="applicationarea">
                <?php
                $this->getPage()->getApplicationArea('main_1')->render();
                ?>
            </div>
        </div>
    </div>
    <div class='gs_outer gs_row r3'>
        <div class='gs_inner'>
            <div area='main_2' class="applicationarea">
                <?php
                $this->getPage()->getApplicationArea('main_2')->render();
                ?>
            </div>
        </div>
    </div>

    <?php
    $this->includefile('footer');
    ?>
</div>