
<div class="gs_outer gs_row r1">
    <div class='gs_inner'>
        <table width="100%" cellspacing="0" cellpadding="0">
            <td class='gs_col c1 gs_margin_right' valign="top">
                <? AppAreaHelper::printAppArea($this->getPage(), "main_1", true); ?>
                <? AppAreaHelper::printAppArea($this->getPage(), "main_2", false); ?>
            </td>
            <td class='gs_col c2 gs_margin_left' valign="top">
                <? AppAreaHelper::printAppArea($this->getPage(), "left_1", false); ?>
            </td>
        </table>
    </div>
</div>