<div class="skelholder skeleton16" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>
    <div class="gs_row r1 gs_outer">
        <div class='gs_inner'>
            <? AppAreaHelper::printRows($this->getPage(), 2, 1); ?>
        </div>
    </div>
    <div class="gs_row r2 gs_outer">
        <div class='gs_inner'>
            <? AppAreaHelper::printAppArea($this->getPage(), "main_1"); ?>
        </div>
    </div>
    <div class="gs_row r3 gs_outer">
        <div class='gs_inner'>
            <? AppAreaHelper::printAppArea($this->getPage(), "main_2"); ?>
        </div>
    </div>
</div>