<div class="skelholder skeleton1" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>

    <div class='gs_row r1 gs_outer'>
        <div class='gs_inner gs_margin_bottom'>
            <table width="100%" cellspacing='0' cellpadding='0'>
                    <tr>
                        <td width="20%" valign="top"  class='app_row_entry gs_col_1 gs_margin_right'>
                            <div class="applicationarea">
                                <?php $this->getPage()->getApplicationArea('left_1')->render(); ?>
                            </div>
                        </td>
                        <td valign="top"  class='app_row_entry gs_col_2 gs_margin_right'>
                        <div class="applicationarea gs_margin_left">
                                <?php $this->getPage()->getApplicationArea('main_1')->render(); ?>
                            </div>
                        </td>
                        <td width="20%" valign="top"  class='app_row_entry gs_col_3 gs_margin_left'>
                            <div class="applicationarea">
                                <?php $this->getPage()->getApplicationArea('right_1')->render(); ?>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>

    <?php
        $this->includefile('footer');
    ?>
</div>