
<div class="gs_row r1 gs_outer">
    <div class="gs_inner">
        <table width="100%"  cellspacing='0' cellpadding='0'>
            <tr>
                <td valign="top"  class='gs_col c1 gs_margin_right'>
                    <? AppAreaHelper::printAppArea($this->getPage(), "main_1"); ?>
                </td>
                <td width="20%" valign="top" class='gs_col c2 gs_margin_left'>
                    <? AppAreaHelper::printAppArea($this->getPage(), "right_1"); ?>
                </td>
            </tr>
        </table>
    </div>
</div>