<div  class="skelholder skeleton3" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>

    <div class="gs_row r1 gs_outer">
        <div class="gs_inner">
            <table width="100%"  cellspacing='0' cellpadding='0'>
                <tr>
                    <td valign="top"  class='gs_col c1 gs_margin_right'>
                        <div area='main_1' class="applicationarea">
                            <?php $this->getPage()->getApplicationArea('main_1')->render(); ?>
                        </div>
                    </td>
                    <td width="20%" valign="top" class='gs_col c2 gs_margin_left'>
                        <div area='right_1' class="applicationarea">
                            <?php $this->getPage()->getApplicationArea('right_1')->render(); ?>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<?php
$this->includefile('footer');
?>