<div class="skelholder skeleton16" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>
    <div class="mainarea">
        <div class='top_row gs_margin_bottom application_row'>
            <table width='100%'>
                <tr>
                    <td width='50%' class='app_row_entry'>
                        <div area='top_1' class="applicationarea apparea-top-1 left_box gs_margin_right">
                            <?php
                            $this->getPage()->getApplicationArea('top_1')->render();
                            ?>
                        </div>
                    </td>
                    <td width='50%' class='app_row_entry'>
                        <div area='top_2' class="applicationarea apparea-top-2 right_box gs_margin_left">
                            <?php
                            $this->getPage()->getApplicationArea('top_2')->render();
                            ?>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <div class='main_col'>
            <div area='main_1' class="applicationarea apparea-main-1 gs_margin_bottom">
                <?php
                $this->getPage()->getApplicationArea('main_1')->render();
                ?>
            </div>
            <div area='main_2' class="applicationarea apparea-main-2">
                <?php
                $this->getPage()->getApplicationArea('main_2')->render();
                ?>
            </div>
        </div>
    </div>
</div>