<div class="skelholder skeleton1" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>

    <div class='gs_row r1 gs_outer'>
        <div class='gs_inner'>
            <table width="100%" cellspacing='0' cellpadding='0'>
                <tr>
                    <td width="20%" valign="top" class='gs_col c1 gs_margin_right'>
                        <? AppAreaHelper::printAppArea($this->getPage(), "left_1"); ?>
                    </td>
                    <td valign="top" class='gs_col c2 gs_margin_right gs_margin_left'>
                        <? AppAreaHelper::printAppArea($this->getPage(), "main_1"); ?>
                    </td>
                    <td width="20%" valign="top" class='gs_col c3 gs_margin_left'>
                        <? AppAreaHelper::printAppArea($this->getPage(), "right_1"); ?>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <?php
    $this->includefile('footer');
    ?>
</div>