<div class="skelholder skeleton11" theme='<? echo $this->getThemeApplicationSettingsId(); ?>'>
    <?php
    $this->includefile('pageinfo');
    $this->includefile('mainmenu');
    $this->includefile('header');
    ?>
    <div class="gs_row r1 gs_outer">
        <div class="gs_inner">
            <? AppAreaHelper::printAppArea($this->getPage(), "main_1"); ?>
        </div>
    </div>

    <div class="gs_row r1 gs_outer">
        <div class="gs_inner">
            <? AppAreaHelper::printRows($this->getPage(), 3); ?>
        </div>
    </div>
    
     <?php
    $this->includefile('footer');
    ?>
</div>