
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="https://unpkg.com/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"></script>



<div class="contentrow firstrow"> 
    <div class="row_inner">
        
        <div>
            <?php
            ContentManager::render("top_fasiliteter");
            ?>
        </div>
        <div style='max-width: 1000px; margin: 0 auto;' id='bookingprocess'></div>
    </div>
</div>


<div class="contentrow row_3" style='padding-top: 50px; padding-bottom: 50px;'> 
    <div class="row_inner">
        <div class="col col_1 col_size_2 mobilebox" style='color:#9a9999; padding-right:0px;'>
            <?php
                ContentManager::render("fasilitices_kontor");
            ?>
            <br>
            <a href='/?page=contactus'><div class='utleienaeringbtn'><?php ContentManager::render("kontaktossknapp"); ?></div></a>
        </div>
        <div class="col col_2 col_size_2 mobilebox" style='color:#9a9999; padding-right:0px;'>
            <?php
                ContentManager::render("fasilitices_takterasse");
            ?>
            <br>
            <a href='/?page=contactus'><div class='utleienaeringbtn'><?php ContentManager::render("kontaktossknapp"); ?></div></a>
        </div>
    </div>
</div>


<?php
echo "<div style='text-align:center;color:#585b9e; font-size: 36px; padding-bottom: 20px;padding-top: 50px;'>Bilder og fra møterom og takterasse</div>";
echo '<div id="roomcategorygallery">';
CategoryGallery::render("conferenceroomsgallery".$_GET['plan']);
echo '</div>';
echo "<script>";
echo "$(function() { $(window).scrollTop(localStorage.getItem('lastscroll')); });";
echo "</script>";

?>