<?
/* @var $this ns_3e89173c_42e2_493f_97bb_2261c0418bfe\GetShopLockSystem */
$group = $this->getGroup();
$servers = $this->getServers();

//echo "<pre>";
//print_r($group);
//echo "</pre>";
?>


    
    <div class='menuarea'>
        <div class='shop_button' gs_confirm="Are you sure you want to delete this?" gsclick='deleteGroup'><i class='fa fa-trash'></i> Delete group</div>
    </div>
    <br/>
    
    <div class='locks'>
        Group name: <? echo $group->name; ?>
        <br/>Maximum number of user slots: <? echo $group->numberOfSlotsInGroup; ?>
        <br/>
        <br/>
        <i class="fa fa-info-circle"></i> Check off all locks that you wish to be connected to this group.
        <br/>

        <div>

            <?
            foreach ($servers as $server) {
                $lockIdsAlreadyAdded = array();

                if (isset($group->connectedToLocks->{$server->id})) {
                    $lockIdsAlreadyAdded = $group->connectedToLocks->{$server->id};
                } 

                echo "<div class='servergroup' serverid='$server->id'>";
                    echo "<br/><b>".$server->givenName."</b>";
                    foreach ($server->locks as $lock) {
                        $checked = in_array($lock->id, $lockIdsAlreadyAdded) ? "checked='checked'" : ""
                        ?>
                        <div><input <? echo $checked; ?> class='lockingroup' type="checkbox" value="<? echo $lock->id; ?>"/> <? echo $lock->name; ?></div>
                        <?
                    }   
                echo "</div>";
            }
            ?>

            <br/><div class="shop_button saveGroup">Save</div>
        </div>
    </div>
    
   
<?
if (count($group->groupLockCodes)) {
?>
    <div class='codes'>
        <h2>Codes and slots</h2>
        <?

        foreach ($group->groupLockCodes as $slotId => $slot) {
            /* @var $slot \core_getshoplocksystem_UserSlot */
            $this->setSlot($slot);
            $this->includefile('slotview');
        }
        ?>

    </div>
<?
}
?>