<div class="footer_row"> 
    <div class='footer_inner'>
        <div class="col col1">
            <?php
            ContentManager::render("footer_product_text2", true);

            $pages = $router->getAllPages();
            echo "<ul>";
            foreach ($pages as $page) {
                if ($page->subpageof == "products") {
                    $className = get_class($page);
                    echo "<a href='?page=$className'><li>".$page->getMenuName()."</li></a>";
                }
            }
            echo "</ul>";
            ?>
        </div>
        
        <div class="col col2">
            <?php
                ContentManager::render("footer_text2", true);
            ?>
        </div>
        
        <div class="col col3">
            <?php
                ContentManager::render("footer_text3", true);
            ?>
        </div>
    </div>
    <div style='text-align: center; background-color: #8ce6d8;'>
        <a href='https://www.visa.no' target='_blank'><img style='margin: 20px;' src='gkroen/images/visa.png'/></a>
        <a href='https://www.visa.no' target='_blank'><img style='margin: 20px;' src='gkroen/images/verifiedbyvisa.png'/></a>
        <a href='https://www.mastercard.no' target='_blank'><img style='margin: 20px;' src='gkroen/images/mastercard.png'/></a>
        <a href='https://www.mastercard.no' target='_blank'><img style='margin: 20px;' src='gkroen/images/mastercardsecure.png'/></a>
    </div>
</div>