<?php
/* @var $this \ns_46b52a59_de5d_4878_aef6_13b71af2fc75\PmsBookingSummary */
$booking = $this->getApi()->getPmsManager()->getCurrentBooking($this->getSelectedName());
$items = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
foreach($items as $item) {
    $items[$item->id] = $item;
}
echo "<h3><i class='fa fa-clock-o'></i> " . $this->__w("Selected time periode") . "</h3>";
foreach($booking->dates as $date) {
    if(!$date->end) {
        echo $this->__w("Starting from") . " ";
    }
    echo date("d.m.Y h:i", strtotime($date->start));
    if($date->end) {
         echo " - " . date("d.m.Y h:i", strtotime($date->end));
    }
}

echo "<h3><i class='fa fa-home'></i> " . $this->__w("Rooms selected") . "</h3>";
foreach($booking->rooms as $room) {
    /* @var $room core_pmsmanager_PmsBookingRooms */
    $price = $room->price;
    echo "<div class='itemrow'>";
    echo $items[$room->bookingItemTypeId]->name . "<span class='price'>" . $price . " kr </span>";
    echo "</div>";
}
$printAddons = false;
foreach($booking->addons as $addon) {
    if($addon) {
        $printAddons = true;
    }
}

if($printAddons) {
    echo "<h3>" . $this->__w("Additional selections") . "</h3>";
    print_r($booking->addons);
}

echo "<hr>";

foreach($booking->rooms as $room) {
    $prices[$room->taxes] = $room->price;
}

$total = 0;
foreach($prices as $taxgroup => $price) {
    $taxes = $price - ($price / (($taxgroup + 100) / 100));
    $total += $price;
    echo "<div class='itemrow'>";
    echo "MVA " . $taxes . "% <span class='price'>" . $taxes . " kr </span>";
    echo "</div>";
}
echo "<div class='itemrow'>";
echo "Totalt <span class='price'>" . $total . " kr </span>";
echo "</div>";
?>