<?php
/* @var $this \ns_46b52a59_de5d_4878_aef6_13b71af2fc75\PmsBookingSummary */
$booking = $this->getApi()->getPmsManager()->getCurrentBooking($this->getSelectedName());
$items = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
$items2 = array();
foreach($items as $item) {
    $items2[$item->id] = $item;
}
$items = $items2;
$addonsAdded = array();
$bookingitems = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
foreach($bookingitems as $item) {
    $bookingitems[$item->id] = $item;
}

echo "<br>";

echo "<h3 class='bottomborder'>" . $this->__w("Rooms selected") . "</h3>";
foreach($booking->rooms as $room) {
    /* @var $room core_pmsmanager_PmsBookingRooms */
    $price = $room->price;
    echo "<div class='itemrow'>";
    if($items[$room->bookingItemTypeId]->addon > 0) {
        echo "<i class='fa fa-trash-o removeAddon bookedaction' itemtypeid='".$room->bookingItemTypeId."'></i> ";
        $addonsAdded[$room->bookingItemTypeId] = true;
    } else {
        echo "<span class='bookedaction'></span> ";
    }
    echo "<span class='itemname'>";
    if($room->bookingItemId) {
        echo $bookingitems[$room->bookingItemId]->bookingItemName;
    } else {
        echo $items[$room->bookingItemTypeId]->name;
    }
    echo "</span>";
    if($price > 0) {
        echo "<span class='price'>" . $price . " kr </span>";
    }
    $date =$room->date;
    
    if(!$date->end) {
        echo $this->__w("Starting from") . " ";
    }
    echo "<span>" . date("d.m.Y H:i", strtotime($date->start));
    if($date->end) {
         echo " - " . date("d.m.Y H:i", strtotime($date->end));
    }
    echo "</span>";
    echo "</div>";
}
$printAddons = false;
foreach($booking->addons as $addon) {
    if($addon) {
        $printAddons = true;
    }
}

if($printAddons) {
    echo "<h3>" . $this->__w("Additional selections") . "</h3>";
    print_r($booking->addons);
}

echo "<br>";
foreach($booking->rooms as $room) {
    $prices[$room->taxes] = $room->price;
}

$bottom = "<h3 class='bottomborder'> " . $this->__w("Total") . "</h3>";
$total = 0;
foreach($prices as $taxgroup => $price) {
    $taxes = $price - ($price / (($taxgroup + 100) / 100));
    $total += $price;
    if($taxes > 0) {
        $bottom .= "<div class='itemrow'>";
        $bottom .= "MVA " . $taxgroup . "% <span class='price'>" . round($taxes) . " kr </span>";
        $bottom .= "</div>";
    }
}
if($total > 0) {
    $bottom .= "<div class='itemrow ' style='padding-top: 10px;'>";
    $bottom .= "Totalt <span class='price'>" . $total . " kr </span>";
    $bottom .= "</div>";
}
if($total > 0) {
    echo $bottom;
}
?>

<?
$addons = "<h3 class='bottomborder'>Addons</h3>";
$addonsFound = false;
foreach($items as $item) {
    if(key_exists($item->id, $addonsAdded)) {
        continue;
    }
    if($item->addon > 0) {
        $addonsFound = true;
        $addons .= "<div class='itemrow ' itemid='".$item->id."' style='padding-top: 10px;'>";
        $addons .= "<span class='price addaddonsbutton'>" . $this->__w("Add") . "</span>";
        $addons .= $item->name;
        $addons .= "</div>";
    }
}
if($addonsFound) {
    echo $addons;
}
?>