<?
/* @var $this \ns_00c40488_e21c_4e54_bed4_8043df326268\C3SFIRapport */

$companies  = $this->getApi()->getUserManager()->getAllCompanies();

?>
<div class='timeframe'>
    Velg tidsperiode:
    <br/><input class='gsniceinput1 ' id='from' placeholder="Fra"/>
    - <input class='gsniceinput1' id='to' placeholder="Til"/>
</div>
<?
foreach ($companies as $company) {
    ?>
    <div class='selectButton'>
        <div class="shop_button downloadReport" filename='SFIReport_<? echo $company->name; ?>.xlsx' companyId='<? echo $company->id; ?>'>Last ned Excel</div>
        <div style='display: inline-block;'  value='<? echo $company->id; ?>'>
            <? echo $company->name; ?>
        </div>
    </div>
    
    <?
}
?>

<script>
    $('#from').datepicker({dateFormat: "dd.mm.yy"});
    $('#to').datepicker({dateFormat: "dd.mm.yy"});
</script>