<? 
/* @var $this ns_d755efca_9e02_4e88_92c2_37a3413f3f41\Settings */
?>
<div class='gss_imagebox'>
    <i class="fa fa-tachometer gs_fa-icon"></i>
</div>
<div class='gss_description'>
    <div class='title'><? echo $this->__f("Overview"); ?></div>
    <div>
        <?
        echo $this->__f("Available applications") . ": " . count($this->getApi()->getStoreApplicationPool()->getAvailableApplications());
        echo "<br/>" . $this->__f("Activated applications") . ": " . count($this->getApi()->getStoreApplicationPool()->getApplications());
        ?>
    </div>
</div>
<div class='gss_activate_button'> <? echo $this->__f("more"); ?></div>