<?
$countrycodes = $this->getFactory()->getTerritoriesList();
/* @var $factory Factory */
$factory = $this->getFactory();
$paymentMethods = $factory->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();

$languages = array();
$languages['nb_NO'] = "Norwegian";
$languages['se'] = "Swedish";
$languages['dk'] = "Danish";
$languages['en_en'] = "English";
$languages['nl_NL'] = "Dutch";
$languages['fi_FI'] = "Finish";
?>
<div class='gss_settings_header'>
    <i class='fa fa-info'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Settings"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("GetShop contains of much more then just some basic settings, the information and settings you find here is just the basic one that are unique for everyone. If you wish to change settings regarding e-commerce stuff you need first to activate e-commerce under applications and then change settings that shows up.");
            ?>	
        </div>
    </div>	
</div>
<div class='gss_settings_content'>
    <div class="gss_setting" id="language">
        <div class="text inline title"><?php echo $this->__f("Please select your language"); ?></div>

        <div class="gss_dropdown">
            <select class="config" gs_model='storesettings' gs_model_attr='language'>
                <? foreach ($languages as $key => $lang) { 
                    $selected = $this->getFactory()->getMainLanguage() == $key ? "selected='true'" : "";
                    ?>
                    <option <? echo $selected; ?> value="<? echo $key; ?>"><? echo $lang; ?></option>
                <? } ?>
            </select>
        </div>
        <div style='padding: 20px'>
            <?
            $extraLanguages = $this->getConfigurationSetting("languages");
            if ($extraLanguages) {
                $extraLanguagesCodes = json_decode($extraLanguages);
                if (count($extraLanguagesCodes)) {
                    echo $this->__f("Extra languages displayed on  your webpage").":";
                    foreach ($extraLanguagesCodes as $code) {
                        echo "<div class=''><i gss_confirmation='". $this->__f("Are you sure you want to remove this language?") ."' gss_method='removeLanguage' gss_value='$code' class='fa fa-remove removelanguage'></i> $code</div>";
                    }
                }
            }
            
            ?>
        </div>
    </div>
    
    <div class="gss_setting" id="paymentMethod">
        <div class="text inline title"><?php echo $this->__f("Please select your language"); ?></div>

        <div class="gss_dropdown">
            <select class="config" gs_model='storesettings' gs_model_attr='paymentMethod'>
                <option value="">Select payment method</option>
                <? foreach ($paymentMethods as $key => $method) { 
                    $selected = $this->getPaymentMethod() == $method->id ? "SELECTED" : "";
                    ?>
                    <option value="<? echo $method->id; ?>" <? echo $selected; ?>><? echo $method->appName; ?></option>
                <? } ?>
            </select>
        </div>
        <div class="description">
            <?php echo $this->__("This will be the default payment method for the users on creation of the user."); ?>
        </div>        
    </div>

    <div class="textfield gss_setting"  id="mainemailaddress">
        <span class="title"><?php echo $this->__f("Main email address"); ?></span>
        <input type="textfield" gs_model='storesettings' gs_model_attr='emailaddress' value="<? echo $this->getMainEmailAddress(); ?>">
        <div class="description">
            <?php echo $this->__("This is the main email address, if you change this all orders, contact forms and etc will be sent to this email address."); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="mainmobilephone">
        <span class="title"><?php echo $this->__f("Main mobile phone number"); ?></span>
        <input type="textfield" gs_model='storesettings' gs_model_attr='phoneNumber' value="<? echo $this->getMainMobilePhone(); ?>">
        <div class="description">
            <?php echo $this->__("This is the main email address, if you change this all orders, contact forms and etc will be sent to this email address."); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="title">
        <span class="title"><?php echo $this->__("Title"); ?></span>
        <input type="textfield" gs_model='storesettings' gs_model_attr='title' value="<? echo $this->getTitle(); ?>">
        <div class="description">
            <?php echo $this->__f("Specify a title for your webshop. this will be displayed on the tabs in etc chrome."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting"  id="url">
        <span class="title"><?php echo $this->__("Url"); ?></span>
        <input type="textfield" gs_model='storesettings' gs_model_attr='url' value="<? echo $this->getUrl(); ?>">
        <div class="description">
            <?php echo $this->__f("Enter the address you wish users should be able to access, example (yourdomein.com)."); ?>
        </div>
    </div>

    
    
    <div class="textfield gss_setting" id="uniqueusersonemail">
        <span class="title"><?php echo $this->__f("Force unique email addresses on users"); ?></span>
        <div class="gss_onoff" gs_model="storesettings" gs_model_attr="uniqueusersonemail">
            <? $faclass = $this->getConfigurationSetting("uniqueusersonemail") == "true" ? "fa-toggle-on" : "fa-toggle-off"; ?>
            <? echo $this->__f("Off"); ?><i class="fa <? echo $faclass; ?>"></i><? echo $this->__f("On"); ?>
        </div>
        <div class="description">
            <?php echo $this->__("If the same email is entered, it is forced as the same user if existing."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting" id="doubleauthentication">
        <span class="title"><?php echo $this->__f("Force users to login with pincode sent to phone"); ?></span>
        <div class="gss_onoff" gs_model="storesettings" gs_model_attr="doubleauthentication">
            <? $faclass = $this->getConfigurationSetting("doubleauthentication") == "true" ? "fa-toggle-on" : "fa-toggle-off"; ?>
            <? echo $this->__f("Off"); ?><i class="fa <? echo $faclass; ?>"></i><? echo $this->__f("On"); ?>
        </div>
        <div class="description">
            <?php echo $this->__("This feature gives you an extra layer of security."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting" id="singlegrouptouser">
        <span class="title"><?php echo $this->__f("A user can only be assigned to one usergroup"); ?></span>
        <div class="gss_onoff" gs_model="storesettings" gs_model_attr="singlegrouptouser">
            <? $faclass = $this->getConfigurationSetting("singlegrouptouser") == "true" ? "fa-toggle-on" : "fa-toggle-off"; ?>
            <? echo $this->__f("Off"); ?><i class="fa <? echo $faclass; ?>"></i><? echo $this->__f("On"); ?>
        </div>
        <div class="description">
            <?php echo $this->__("Turn this on to make sure that only one user can be assigned to each group."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting" id="seo">
        <span class="title"><?php echo $this->__f("SEO"); ?></span>
        <div class="gss_onoff" gs_model="storesettings" gs_model_attr="seo">
            <? $faclass = $this->getConfigurationSetting("seo") == "true" ? "fa-toggle-on" : "fa-toggle-off"; ?>
            <? echo $this->__f("Off"); ?><i class="fa <? echo $faclass; ?>"></i><? echo $this->__f("On"); ?>
        </div>
        <div class="description">
            <?php echo $this->__("Optimize your page by compressing images, css, javascript and lazy loading of css and javascript. (Warning might cause unstability)"); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting" id="singlegrouptouser">
        <span class="title"><?php echo $this->__f("Your favicon"); ?>
        </span>
        <div class="gss_onoff" gs_model="storesettings" gs_model_attr="singlegrouptouser">
            <img src="favicon.ico" id="favicondisplayer" style="border: solid 1px; width: 16px; height: 16px; float:right;">

            <input type="file" id="fileinput" />
            <script type="text/javascript">
              function readSingleFile(evt) {
                //Retrieve the first (and only!) File from the FileList object
                var f = evt.target.files[0]; 

                if (f) {
                  var r = new FileReader();
                  r.onload = function(e) { 
                      var contents = e.target.result;
                    $.ajax({
                           url: 'uploadfavicon.php',  //Server script to process data
                           type: 'POST',
                           //Ajax events
                           success: function() {
                               $('#favicondisplayer').attr('src','favicon.ico');
                           },
                           // Form data
                           data: contents,
                           //Options to tell jQuery not to process data or worry about content-type.
                           cache: false,
                           contentType: false,
                           processData: false
                       });
                  }
                  r.readAsDataURL(f);
                } else { 
                  alert("Failed to load file");
                }
              }

              document.getElementById('fileinput').addEventListener('change', readSingleFile, false);
            </script>
                
        </div>
        <div class="description">
            <?php echo $this->__("Upload a favicon to your site."); ?>
        </div>
    </div>
    
    <div class='gss_button_area'>
        <div class="gss_button addLanguage" ><i class='fa fa-language'></i><?php echo $this->__("Add a language"); ?></div>
        <div class="gss_button" gss_confirmation="<? echo $this->__f("Are you sure you want to delete your store? You will not be able to revert this action."); ?>" gss_method="deleteStore" gss_success_method="storeDeleted"><i class='fa fa-remove'></i><?php echo $this->__("Delete my store"); ?></div>

        <div class="gss_button" gss_method="saveStoreSettings" gss_model="storesettings" gss_success_message="<? echo $this->__f("Saved settings"); ?>"><i class='fa fa-save'></i><?php echo $this->__("Save settings"); ?></div>
    </div>
</div>

