<?php
/* @var $this \ns_acb219a1_4a76_4ead_b0dd_6f3ba3776421\CrmCustomerView */
$code = $this->getApi()->getCartManager()->getCoupon($_POST['data']['code']);
$coupon = $code;
$types = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);

$discountTypes = array();
$discountTypes["FIXED"] = "Fixed discount";
$discountTypes["PERCENTAGE"] = "Percentage";
$discountTypes["FIXEDPRICE"] = "Fixed daily price";
$discountTypes["FIXEDDISCOUNTSTAY"] = "Fixed discount on stay";
?>

<div class='discountsystemeditpanel'>
    <i class='fa fa-close' style='float:right; font-size: 20px; cursor:pointer;' onclick="$('.updateDiscountCodeForm').fadeOut();"></i>
    <div>
        <div>
            <span class='colspacer'>Code</span>
            <span class='colspacer'>Times left</span>
            <span class='colspacer'>Description</span>
            <span class='colspacer'>Type</span>
        </div>
        <div>
            <span class='colspacer'><input type='txt' disabled class='gsniceinput1' value='<?php echo $code->code; ?>'></span>
            <span class='colspacer'><input type='txt' class='gsniceinput1' gsname='timesLeft' value='<?php echo $code->timesLeft; ?>'></span>
            <span class='colspacer'><input type='txt' class='gsniceinput1' gsname='description' value='<?php echo $code->description; ?>'></span>
            <span class='colspacer'>
                <select class='gsniceselect1 pricetypeselection' gsname='type'>
                    <?php
                    foreach($discountTypes as $idx => $name) {
                        $selected = $code->type == $idx ? "SELECTED" :"";
                        echo "<option value='$idx' $selected>$name</option>";
                    }
                    ?>
                </select>
            </span>
        </div>
    </div>
    <span class="middlearea">
        <div class='restriction_addonstitile'>Prices</div>
        
        <input type='txt' class='gsniceinput1 otherpriceselection' gsname='otherpriceamount' value='<?php echo $code->amount; ?>'>
        <div class='fixeddailyprice'>
            <?php
            $first = true;
            
            $maxcount = 0;
            foreach($types as $type) {
                if($type->size > $maxcount) {
                    $maxcount = $type->size;
                }
            }
            echo "<span class='pricespacertype'>All categories</span>";

            echo "<div style='clear: both;'></div>";
            echo "<div>";
            for($i = 1; $i <= $maxcount; $i++) {
                echo "<span class='pricespacer'><input type='txt' class='gsniceinput1 allguestsetter' guest='$i' value='' style='width:50px;padding: 2px;' placeholder='Guest $i'></span>";
            }
            
            
            echo "</div>";
            echo "<div style='clear: both;'></div>";

            foreach($types as $type) {
                $key = $type->id;
                echo "<span class='pricespacertype'>" . $type->name . "</span>";
                echo "<div style='clear: both;'></div>";
                for($i=1;$i <= $type->size;$i++) {
                    $amount = "";
                    if(isset($code->dailyPriceAmountByType->{$key."_".$i})) {
                        $amount = $code->dailyPriceAmountByType->{$key."_".$i};
                    }
                    
                    echo "<span class='pricespacer'>";
                    echo "<input type='txt' class='gsniceinput1 categoryguestsetter' guest='$i' gsname='".$type->id."_$i' value='$amount' style='width:50px;padding: 2px;'>";
                    echo "</span>";
                }
                if($type->size == 0) {
                    echo "<b>0 guests allowed on this category<br>please correct under  settings->rooms</b>";
                }
                
                echo "<div style='clear: both;'></div>";
                $first=false;
            }
            ?>
            If empty, prices from price plan <b><?php echo $code->priceCode; ?></b> is being used.
        </div>
    </span>
    <span class='middlearea'>
        <div class='restriction_addonstitile'>Restrictions</div>
        <?php
            /* @var $this ns_9de81608_5cec_462d_898c_1266d1749320\PmsConfiguration */
            $endDate = time()+(86400*30);
            $repeatingData = $coupon->whenAvailable;
            $config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
            $starting = time();
        ?><div class='itemrow' style='position:relative;'>
            <span class='bookedaction'></span> 
            <span class='addMoredatesPanel' gstype='form' method='addRepeatingDates'>
                <input type="hidden" value="<?php echo $coupon->id; ?>" gsname="couponid">
                <input type="hidden" value="00:00" gsname="starttime">
                <input type="hidden" value="23:59" gsname="endtime">
                <input type='hidden' value='repeat' gsname='repeattype'>


                <div class='eventrow'>
                    <span class='title'><? echo $this->__w("Available when"); ?>:</span>
                    <span class='optionbox'>
                        <select style='width:100%; margin-right: 3px;' gsname='pmsWhenAvailable' class='gsniceselect1'>
                            <option value='REGISTERED'>The day of the booking</option>
                            <option value='DAYBOOKED'>The actual stay</option>
                        </select>
                    </span>
                </div>
                <br>
                <span class='discountcodeoptionsdate'>
                    <span class='datetypepanel repeat'><? echo $this->__w("Starting"); ?>:</span>
                    <input type='text'  class='gsniceinput1' gsname='eventStartsAt' style='width:90px;text-align: center; float:left;' value='<? echo date("d.m.Y", $starting); ?>'>
                </span>
                <span class='discountcodeoptionsdate'>
                    <span class='title'><? echo $this->__w("Ends"); ?>:</span>
                    <span class='optionbox'><input type='text'  class='gsniceinput1' gsname='endingAt' value='<? echo date("d.m.Y", $endDate); ?>' style='width:90px;text-align: center;'></span>
                </span>
                <div class='discountcodeoptions'>
                    <span class='title'><? echo $this->__w("Min days"); ?>:</span><br>
                    <span class='optionbox'><input type='text'  class='gsniceinput1' gsname='minDays' value='<? echo $coupon->minDays == 0 ? "" : $coupon->minDays ?>' style='width: 45px;text-align: center;'></span>
                </div>
                <div class='discountcodeoptions' style='text-align: right;'>
                    <span class='title'><? echo $this->__w("Max days"); ?>:</span><br>
                    <span class='optionbox'><input type='text'  class='gsniceinput1' gsname='maxDays' value='<? echo $coupon->maxDays == 0 ? "" : $coupon->maxDays ?>' style='width: 45px;text-align: center;'></span>
                </div>

                <div style='clear:both;'></div>
                <br>
                <div class='datetypepanel repeat'>
                    <div class='eventrow'>
                        <div><? echo $this->__w("Time interval"); ?>:</div>
                        <select class="repeat_type gsniceselect1" gsname='repeat_periode' style='box-sizing: border-box; width:100%;'>
                            <option value="3" title="Daily"><? echo $this->__w("All the time"); ?></option>
                            <option value="1" title="Weekly"><? echo $this->__w("Weekly"); ?></option>
                        </select>
                    </div>
                    <div class='eventrow repeatrow repeateachdaterow'>
                        <span class='title'><? echo $this->__w("Repeat every"); ?>:</span>
                        <span class='optionbox'>
                            <select style='width:20%; margin-right: 3px;' gsname='repeateachtime'>
                                <?php 
                                for($i = 1; $i <= 30; $i++) {
                                    echo "<option value='$i'>$i.</option>";
                                }
                                ?>
                            </select>
                            <span class='repeat_0 repeatoption'><? echo $this->__w("day"); ?></span>
                            <span class='repeat_1 repeatoption'><? echo $this->__w("week"); ?></span>
                            <span class='repeat_2 repeatoption'><? echo $this->__w("month"); ?></span>
                        </span>
                    </div>
                    <div class='eventrow repeatrow'>
                        <span class='title'><? echo $this->__w("Repeat on"); ?>:</span>
                        <span class='optionbox'>
                            <span class='repeat_0 repeatoption'></span>
                            <span class='repeat_1 repeatoption'>
                                <table width='100%'>
                                    <tr>
                                        <td><input type='checkbox' gsname='repeatMonday'><? echo $this->__w("Mon"); ?></td>
                                        <td><input type='checkbox' gsname='repeatTuesday'><? echo $this->__w("Tue"); ?></td>
                                        <td><input type='checkbox' gsname='repeatWednesday'><? echo $this->__w("Wed"); ?></td>
                                        <td><input type='checkbox' gsname='repeatThursday'><? echo $this->__w("Thu"); ?></td>
                                        <td><input type='checkbox' gsname='repeatFriday'><? echo $this->__w("Fri"); ?></td>
                                        <td><input type='checkbox' gsname='repeatSaturday'><? echo $this->__w("Sat"); ?></td>
                                        <td><input type='checkbox' gsname='repeatSunday'><? echo $this->__w("Sun"); ?></td>
                                    </tr>
                                    <tr>
                                    </tr>
                                </table>
                                <br>
                            </span>
                        </span>
                    </div>
                </div>

                <?php

                echo "<b>Limit discount to the following:</b><br>";
                echo "<table>";
                $i = 1;
                $style="";
                foreach($types as $type) {
                    if($i > 5) {
                        $style = "style='display:none'";
                    }
                    $product = $this->getApi()->getProductManager()->getProduct($type->productId);
                    $checked = "";
                    if(in_array($product->id, $coupon->productsToSupport)) {
                        $checked = "CHECKED";
                    }

                    echo "<tr $style class='productentryrow'>";
                    echo "<td><input type='checkbox' gsname='productdiscount_".$product->id."' $checked></td><td>" . $product->name . "</td>";
                    echo "</tr>";
                     $i++;
                }

                $config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
                foreach($config->addonConfiguration as $addonItem) {
                    /* @var $addonItem core_pmsmanager_PmsBookingAddonItem */
                    if(!$addonItem->isActive && !$addonItem->isAvailableForBooking) {
                        continue;
                    }
                    if($i > 5) {
                        $style = "style='display:none'";
                    }
                    $product = $this->getApi()->getProductManager()->getProduct($addonItem->productId);

                    $checked = "";
                    if(in_array($product->id, $coupon->productsToSupport)) {
                        $checked = "CHECKED";
                    }

                    echo "<tr $style class='productentryrow'>";
                    echo "<td><input type='checkbox' gsname='productdiscount_".$product->id."' $checked></td><td>Addon : " . $product->name . "</td>";
                    echo "</tr>";
                    $i++;
                }
                echo "</table>";

                if($style) {
                    echo "<span onclick='$(this).hide();$(\".productentryrow\").show();'>Show more</span>";
                }
                ?>
            </span>
            <div style='clear:both;'></div>
        </div>
    </span>
    <span class='middlearea'>
        <div class='restriction_addonstitile'>Addons included</div>
        <?php
        $addons = $this->getApi()->getPmsManager()->getAddonsAvailable($this->getSelectedMultilevelDomainName());
        $coupon = $code;

        echo "<div style='height: 258px; overflow:auto;'>";
        foreach($addons as $addon) {
            if(!$addon->name) {
                continue;
            }

            $included = "";
            $inroomprice = "";
            foreach($coupon->addonsToInclude as $addonav) {
                if($addonav->productId == $addon->productId) {
                    $included = "CHECKED";
                }
                if($addonav->productId == $addon->productId && $addonav->includeInRoomPrice) {
                    $inroomprice = "CHECKED";
                }
            }

            echo "<input type='checkbox' title='Include' gsname='".$addon->productId . "_toinclude' $included> ";
            echo "<input type='checkbox' title='Include in room price'  gsname='".$addon->productId . "_includedinroomprice' $inroomprice> ";
            echo $addon->name  . "<span style='float:right;'>" . $addon->price . "</span> ". "<br>";
        }
        echo "</div>";
        ?>
    </span>
    <div style="clear:both;"></div>
    <br>
    
    <?php
    $campaignChecked = $coupon->activeCampaign ? "CHECKED" : ""; 
    ?>
    <input type="checkbox" gsname="iscampaign" <?php echo $campaignChecked; ?>>Activate as campaign (possible to choose in the booking engine)
    <div style="border-bottom: solid 1px #bbb;margin-top: 5px; margin-bottom: 5px;"></div>
    <div class="activatedcampaigntable">
        <table width="100%">
            <tr>
                <td valign="top" width="50%">
                    <?php
                    $languages = $this->getFactory()->getLanguageCodes();
                    $languages[] = $this->getFactory()->getSelectedLanguage();
                    $states = $this->getFactory()->getLanguageReadable();
                    foreach($languages as $lang) {
                        $title = "";
                        $desc = "";
                        if(isset($coupon->campaignTitle->{$lang})) {
                            $title = $coupon->campaignTitle->{$lang};
                        }
                        if(isset($coupon->campaignDescription->{$lang})) {
                            $desc = $coupon->campaignDescription->{$lang};
                        }
                       echo "<div>Title and description in ".$states[$lang]."</div>";
                        echo "<input type='txt' class='gsniceinput1' placeholder='Title' style='margin-bottom: 4px;' gsname='campaigntitle_$lang' value='$title'><br>";
                        echo "<input type='txt' class='gsniceinput1' placeholder='Description' style='width: 500px;' gsname='campaigndescription_$lang' value='$desc'><br>";
                        echo "<br>";
                    }
                    $frontPageChecked = $coupon->presentCampaignOnFrontPage ? "CHECKED" : ""; 
                    ?>
                    <!--<input type='checkbox' gsname='presentonfrontpage' <?php echo $frontPageChecked; ?>> Present on frontpage-->
                </td>
                <td valign="top">
                    A campaign is a special system where you can customize packages or special deals to offer in you booking engine.<br>
                    It will be shown in step 2 and online if it a valid discount system.<br><br>
                    Examples on package:<br>
                    <ul>
                        <li>Get a meal for only 200 NOK extra, (configured by adding meal addon for 200)</li>
                        <li>Get breakfast included in your stay when staying for more than 3 days</li>
                        <li>Late checkout for only 200 extra?</li>
                        <li>Summer campaign, 10% discount for juni</li>
                        <li>Be creative</li>
                    </ul>
                    <div>
                        <b>PS: A guest can only choose one campaign at a time.</b>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>

<style>
    .discountsystemeditpanel .fixeddailyprice {display:none;}
    .colspacer { width: 24%; display:inline-block;}
    .middlearea,.fixeddailypriceinformation { width: 33.3%; display:inline-block; float: left; box-sizing: border-box;}
    .discountcodeoptionsdate { width: 30%; display:inline-block; float: left; box-sizing: border-box;}
    .discountcodeoptions { width: 20%; display:inline-block; float: left; box-sizing: border-box;}
    .discountsystemeditpanel .pricespacer{ display: inline-block; float:left; margin-right: 5px; text-align: center;}
    .discountsystemeditpanel .pricespacertype{ display: inline-block; float:left; width:300px; text-align: left; font-size:14px; line-height: 30px;height: 30px; }
    .discountsystemeditpanel .pricespacertypefirst{ margin-top: 16px;}
    .discountsystemeditpanel .addMoredatesPanel, 
    .discountsystemeditpanel .addaddonsinludepanel { 
        padding: 5px; 
        left: 0px; 
        top: 5px; 
        width: 100%; 
        z-index: 2;
        display:inline-block;
        box-sizing: border-box;
        padding-right: 30px;
    }
    .discountsystemeditpanel .addaddonsinludepanel,
    .discountsystemeditpanel .editcomment,
    .discountsystemeditpanel .addMoredatesPanel .addMoredatesPanel{
        border: solid 1px #bbb; 
        background-color:#fff !important; 
        box-shadow: 0px 0px 5px 1px #bbb; 
        z-index: 1;
    }
    .discountsystemeditpanel .addMoredatesPanel .addMoredatesPanel{
        padding-top: 20px;
    }

    .discountsystemeditpanel .addMoredatesPanel .optionbox select,    .discountsystemeditpanel .addMoredatesPanel .optionbox input
    { border: solid 1px #bbb; background-color:#fff; font-size: 12px; width: 100%; box-sizing: border-box; }
    .discountsystemeditpanel .addMoredatesPanel .repeatoption { display:none; }
    .discountsystemeditpanel .addMoredatesPanel .repeatoption.repeat_0 { display:inline-block; }
    .discountsystemeditpanel .addMoredatesPanel .optionbox input[type="button"] {width: 100%; float:left; cursor:pointer; }
    .discountsystemeditpanel .addMoredatesPanel .optionbox input[type="checkbox"] {width: inherit; cursor:pointer; }
    .discountsystemeditpanel .addMoredatesPanel .optionbox input[type="radio"] {width: inherit; cursor:pointer; }
    .discountsystemeditpanel .addMoredatesPanel .optionbox input[type="button"]:hover { background-color:#eaeaea; }
    .discountsystemeditpanel .addMoredatesPanel .repeatrow { display:none; }
    .discountsystemeditpanel .adddatetype { margin-bottom: 15px; display:inline-block; padding: 2px; cursor:pointer; background-color:#efefef; width: 115px; text-align: center;border: solid 1px #bbb; }
    .discountsystemeditpanel .adddatetype.selected { background-color:#fff;   border: solid 1px #bbb; }
    .discountsystemeditpanel .addMoredatesPanel .datetypepanel { display:none; }
    .discountsystemeditpanel .addMoredatesPanel .datetypepanel.repeat { display:inherit; width:100%;}
    .discountsystemeditpanel .restriction_addonstitile {border-bottom: solid 1px #bbb; margin-right: 3px; margin-left:3px; font-size: 16px; text-align: center; margin-top:20px; padding-bottom: 10px; margin-bottom: 10px; font-weight: bold; }
</style>


<?php
if($repeatingData) {
    ?>
    <script>
    $('[gsname="itemid"]').val('<? echo $repeatingData->bookingItemId; ?>');
    $('[gsname="typeid"]').val('<? echo @$repeatingData->bookingTypeId; ?>');
    $('[gsname="repeateachtime"]').val('<? echo @$repeatingData->data->repeatEachTime; ?>');
    $('[gsname="repeat_periode"]').val(<? echo @$repeatingData->data->repeatPeride; ?>);
    $('[gsname="pmsWhenAvailable"]').val('<? echo $coupon->pmsWhenAvailable; ?>');
    $('[gsname="repeat_periode"]').change();
    
    $('[gsname="repeatMonday"]').attr('checked', <? if(@$repeatingData->data->repeatMonday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatTuesday"]').attr('checked', <? if(@$repeatingData->data->repeatTuesday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatWednesday"]').attr('checked', <? if(@$repeatingData->data->repeatWednesday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatThursday"]').attr('checked', <? if(@$repeatingData->data->repeatThursday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatFriday"]').attr('checked', <? if(@$repeatingData->data->repeatFriday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatSaturday"]').attr('checked', <? if(@$repeatingData->data->repeatSaturday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatSunday"]').attr('checked', <? if(@$repeatingData->data->repeatSunday) { echo "true"; } else { echo "false"; } ?>);
    
    $('[gsname="endingAt"]').val('<? echo date("d.m.Y", strtotime(@$repeatingData->data->endingAt)); ?>');
    
    $('[gsname="eventStartsAt"]').val('<? echo date("d.m.Y", strtotime(@$repeatingData->data->firstEvent->start)); ?>');
    $('[gsname="eventEndsAt"]').val('<? echo date("d.m.Y", strtotime(@$repeatingData->data->firstEvent->end)); ?>');
    </script>
    <?
}
?>
<script>

$('[gsname="eventStartsAt"],[gsname="eventEndsAt"],[gsname="endingAt"]').datepicker({ 
    changeMonth: true,
    changeYear: true,
    showButtonPanel: true,
    dateFormat: "dd.mm.yy", minDate : 0,
onSelect: function(dateText) {
    var date = moment(dateText, "DD.MM.YYYY");
    var month = (moment(date).get('month')+1);
    if(month < 10) {
        month = "0" + month;
    }
    $('#end_date').val((moment(date).get('date')+1) + "." + month + "." + moment(date).get('year'));
  }
});

$('.allguestsetter').on('keyup', function() {
    var guest = $(this).attr('guest');
    var value = $(this).val();
    console.log(guest);
    $('.categoryguestsetter[guest="' + guest + '"]').val(value);
});

function getshopdiscount_changePriceType() {
    var value = $(this).val();
    if(value === "FIXEDPRICE") {
        $('.discountsystemeditpanel .fixeddailyprice').show();
        $('.discountsystemeditpanel .otherpriceselection').hide();
    } else {
        $('.discountsystemeditpanel .fixeddailyprice').hide();
        $('.discountsystemeditpanel .otherpriceselection').show();
    }
}
    
function getshopdiscount_changeRepeatType() {
    var type = $(this).val();
    $('.repeatrow').hide();
    if(type !== "3") {
        $('.repeatrow').show();
    } 
    $('.repeateachdaterow').hide();
    if(type === "1") {
        $('.repeateachdaterow').show();
    }

    $('.repeatoption').hide();
    $('.repeat_' + type).show();
}
$(document).on('change','.discountsystemeditpanel .repeat_type', getshopdiscount_changeRepeatType);
$(document).on('change','.discountsystemeditpanel .pricetypeselection', getshopdiscount_changePriceType);
$('.discountsystemeditpanel .pricetypeselection').each(function() {
    if($(this).is(':visible')) { $(this).change(); }
});
</script>
