<div class="isnotactive" style='max-width:1500px; margin: auto;'>
    <div class="kaipal infobox">
        <div class="image happy"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("Hey there, no prices can be set up yet"); ?></div>
            <div class="text">
                <?
                echo $this->__f("I have no clue how to set up prices when no categories are added. Please set up a room category first by navigating to settings -> rooms.");
                ?>    
            </div>
        </div>
    </div>
</div>