<?php
$priceCodes = (array)$this->getApi()->getPmsManager()->getpriceCodes($this->getSelectedName());

if(sizeof($priceCodes) == 0) {
    $this->getApi()->getPmsManager()->createNewPricePlan($this->getSelectedMultilevelDomainName(), "default");
}


/* @var $this \ns_1be25b17_c17e_4308_be55_ae2988fecc7c\PmsPricing */
$itemTypes = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedName(), null);
$start = $this->getStart();
$end = $this->getEnd();
$priceObject = $this->getPrices();
$prices = $priceObject->dailyPrices;

$pricetypes = array();
$pricetypes[1] = "Daily";
$pricetypes[2] = "Monthly";
$pricetypes[3] = "Weekly";
$pricetypes[4] = "Per minute";
$pricetypes[5] = "Per hour";
$pricetypes[6] = "Per seconds";
$pricetypes[7] = "Progressive";
$pricetypes[8] = "Interval pricing";

$priceCodes = (array)$this->getApi()->getPmsManager()->getpriceCodes($this->getSelectedName());
?>
<div style=" margin-bottom: 20px; padding-bottom: 20px;">
    <?php
    foreach($priceCodes as $code) {
        $selected = "";
        if($code == $this->getSelectedPricePlan()) {
            $selected = "selectedpriceplan";
        }
        echo '<span class="pmsbutton '.$selected.'" gstype="clicksubmit" method="selectPricePlan" style="border-top-right-radius: 0px;border-bottom-right-radius: 0px;" gsname="selectedpriceplan" gsvalue="'.$code.'">'.$code."</span>";
        echo "<span class='displayEditPriceCode' code='$code' style='background-color:green; color:#fff; padding: 8px;margin-right: 5px;border-top-right-radius: 3px;border-bottom-right-radius: 3px; cursor:pointer;'>";
        echo "<i class='fa fa-edit'></i></span>";
        echo "</span>";
    }
    ?>
    <span class="pmsbutton" onclick='$(".createnewplanform").toggle();'>New plan</span>
    <div style='margin-top: 20px; display:none;' class='createnewplanform' gstype='form' method='creatnewpriceplan'>
        <input type='text' class="gsniceinput1" gsname='newplan'><input type='button' value='Create new plan' gstype='submit' style='padding: 9px;'>
    </div>
</div>



<div class="priceplansettings" style="display:none;" code="<?php echo $priceObject->code; ?>">
    <input type='button' gstype='clicksubmitforce' gsvalue='<?php echo $priceObject->code; ?>' gsname='code' value='Delete price plan' style='float:right;padding:9px;' method='deletePricePlan'>
    <div method='changepricetype' gstype='form'>
        <?php
        $checkedExTaxes = $priceObject->pricesExTaxes ? "CHECKED" : "";
       
        echo "<input type='checkbox' gsname='pricesExTaxes' $checkedExTaxes> Is prices ex taxes?<br>";
        echo "<input type='text' class='gsniceinput1' gsname='code' value='".$priceObject->code."'>";
        echo "<select gsname='pricetype' class='gsniceselect1' style='display:none;'>";
        foreach($pricetypes as $id => $type) {
            $selected = ($priceObject->defaultPriceType == $id) ? "SELECTED" : "";
            echo "<option value='$id' $selected>" . $type . "</option>";
        }
        echo "</select> ";
        echo "<input type='button' value='Change name' gstype='submit' style='padding:9px;cursor:pointer;'></input>";
        ?>
    </div>
</div>

<table width='100%'>
    <tr>
        <td valign='top'>
            <div class="stepbox">
                <h1>Step 1 / 3: Select a date range</h1>
                <div gstype='form' method="selectDates">
                    <input type='text' gsname='start' value='<? echo $start; ?>' style='margin-right:5px; font-size: 20px; width: 110px; text-align:center;' class="gsniceinput1">
                    <input type='text' gsname='end' value='<? echo $end; ?>' style='margin-right:5px; font-size: 20px; width: 110px; text-align:center;' class="gsniceinput1">
                    <span gstype='submit' class='pmsbutton'>Set date range</span>
                </div>
            </div>
        </td>
        <td valign='top' style='padding-left: 50px;'>
            <div class="stepbox">
                <h1>Step 2 / 3: Set the prices</h1>
                <table width='100%'>
                    <tr>
                        <th align='left'>Item</th>
                        <th align='left'>Mo<br><input type='checkbox' class='selectcol' weekday='1'></input></th>
                        <th align='left'>Tu<br><input type='checkbox' class='selectcol' weekday='2'></input></th>
                        <th align='left'>We<br><input type='checkbox' class='selectcol' weekday='3'></input></th>
                        <th align='left'>Th<br><input type='checkbox' class='selectcol' weekday='4'></input></th>
                        <th align='left'>Fr<br><input type='checkbox' class='selectcol' weekday='5'></input></th>
                        <th align='left'>Sa<br><input type='checkbox' class='selectcol' weekday='6'></input></th>
                        <th align='left'>Su<br><input type='checkbox' class='selectcol' weekday='0'></input></th>
                        <th align='left'>Price<br>&nbsp;</th>
                <?php
                foreach($itemTypes as $item) {
                    echo "<tr itemid='".$item->id."'>";
                    echo "<td><input type='checkbox' class='selectrow'> " . $item->name . "</td>";
                    echo "<td><input type='checkbox' weekday='1' class='pricecheckbox'></td>";
                    echo "<td><input type='checkbox' weekday='2' class='pricecheckbox'></td>";
                    echo "<td><input type='checkbox' weekday='3' class='pricecheckbox'></td>";
                    echo "<td><input type='checkbox' weekday='4' class='pricecheckbox'></td>";
                    echo "<td><input type='checkbox' weekday='5' class='pricecheckbox'></td>";
                    echo "<td><input type='checkbox' weekday='6' class='pricecheckbox'></td>";
                    echo "<td><input type='checkbox' weekday='0' class='pricecheckbox'></td>";
                    echo "<td><input type='txt' class='priceinput priceinputsetter ' itemid='".$item->id."'></td>";
                    echo "</tr>";
                }
                ?>
                    <tr>
                        <td colspan='8'></td>
                        <td>
                            <span class='pmsbutton updatePricingTable'>Update</span>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>
<br>
<div gstype='form' method='updateProgressivePrices' style='position:relative;'>
    <?php
    echo "<div class='stepbox'>";
    echo "<input type='hidden' gsname='priceType' value='" . $priceObject->defaultPriceType . "'>";
    echo "<h1>Step 3 / 3: Verify the new pricing table</h1>";
    if($priceObject->defaultPriceType == 7 || $priceObject->defaultPriceType == 8) {
        $this->includefile("progressivepricing");
    } else {
        $this->includefile("dailypriceediting");
    }
    echo "</div>";
    ?>
</div>

    <?php
    $this->includefile("discounts");
    
if($this->getSelectedPricePlan() != "default") {
    ?>

    <div style="border-bottom: solid 1px; margin-bottom: 20px; padding-bottom: 20px;"></div>
    <h1>Override prices (leave empty to use default prices)</h1>

    <?php
    $this->includefile("addonsprice");
}
?>

<script>
    $('input[gsname="start"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('input[gsname="end"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    app.PmsPricingNew.loadpriceinput();
</script>