<?
/* @var $this \ns_b794bba8_d25c_49a7_96c9_0aea81a408ee\ProMeisterMekonomenDatabase */
$res = array();
$searchValue = isset($_POST['data']['name']) ? $_POST['data']['name'] : "";
if ($searchValue) {
    $res = $this->getApi()->getMekonomenManager()->searchForUser($searchValue);
}

?>

<div gstype="form" method="searchForUsers">
    <input type="textfield" class="gsniceinput1" gsname="name" placeholder="name"/>
    <div class="shop_button" gstype="submit"><? echo $this->__f("Search"); ?></div>
</div>

<?
foreach ($res as $rest) {
    ?>
<div class='candidaterow'>
    <div class='userinfo'>
        <div>Name: <? echo $rest->firstName." ".$rest->sureName; ?></div>
        <div>Group: <? echo $rest->groupName; ?></div>
        <div>Managerlogin: <? echo $rest->managerLogin; ?></div>
        <div>Befattning: <? echo $rest->befattning; ?></div>
        <div>Username: <? echo $rest->username; ?></div>
    </div>
    <div class='eventsummary'>Event(s): 
        <?
        foreach ($rest->events as $event) {
            echo "<div class='eventrow'><div>".$event->event->eventName."</div><div>".$event->startDate."</div><div>".$event->endDate."</div></div>";
        }
        ?>
    </div>
</div>
    <?
}
?>