<?php
namespace ns_831647b5_6a63_4c46_a3a3_1b4a7c36710a;

/*  @var $this \ns_831647b5_6a63_4c46_a3a3_1b4a7c36710a/ImageDisplayer */

$prefix = $this->getPrefix();


$link = $this->getConfigurationSetting("link".$prefix);
$adjust = $this->getConfigurationSetting("adjustment".$prefix);
$originalSize = $this->getConfigurationSetting("originalSize".$prefix);

$id = $this->getImageId();
$cords = $this->getTranslatedConfigurationSettings("image_cords");
$original = $this->getTranslatedConfigurationSettings("original_image");
$height = $this->getTranslatedConfigurationSettings("image_height");
$texts = $this->getTexts();
$rotation = $this->getTranslatedConfigurationSettings("rotation") != null ? $this->getTranslatedConfigurationSettings("rotation") : 0;
$crop = "";
$appId = $this->getConfiguration()->id;

if($this->getTranslatedConfigurationSettings("new_type") == "1") {
    $id = $original;
    $compress = $this->getTranslatedConfigurationSettings("compression");
    $cordSplitted = explode(":", $cords);
    if($compress) {
        $crop = "&crop=true&x=".$cordSplitted[0]/$compress."&x2=".$cordSplitted[1]/$compress."&y=".$cordSplitted[2]/$compress."&y2=".$cordSplitted[3]/$compress."&rotation=".$rotation;
    }
}

if($link) {
    $target = "";
    $length = strlen("http");
    if((substr($link, 0, $length) === "http")) {
        $target = "target='_NEW'";
    }
    echo "<a href='$link' $target>";
}

$origSize = "";
$adjustment = "adjust_" . $adjust;
if($originalSize == "true") {
    $origSize = "originalSize";
}

$imageCompressionEnabled = $this->isCompressionActivated();
$containerId = uniqid()."_".  uniqid();
$imageSrc = "";

?>
<div class='displayimagecontainer' containerId="<? echo $containerId ?>">
    <span class='imagecontainer <? echo $origSize .  " " . $adjustment; ?>'  >
        <? if ($id) { 
            $imageSrc = "/displayImage.php?id=".$id.$crop; 
            
            if ($imageCompressionEnabled) {
                $zoomable=  $this->isZoomAble() ? "true" : "false";
                echo '<div zoomable="'.$zoomable.'" style="text-align: center; font-size: 30px; padding: 20px; color: #DDD;" class="loadshower"><i class="fa fa-spinner fa-spin"></i></div>';
            } else {
                ?>
                <img zoomable='<? echo $this->isZoomAble() ? "true" : "false"; ?>' src="<? echo $imageSrc; ?>"/>
                <?
            }
            ?>            
        <? } ?>
    </span>
</div>
<? echo "</a>"; ?>

<script>
    <? if ($imageCompressionEnabled) { ?>
    $(document).ready(function() {  
        app.ImageDisplayer.loadImage('<? echo $containerId; ?>', '<? echo $imageSrc; ?>');
    });    
    <? } ?>
</script>

<? if (!$id) { ?>
    <script>        
        var appId = '<? echo $this->getConfiguration()->id; ?>';
        var currentApp = $('.app[appid='+appId+']');
        var editor = getshop.ImageEditorApi.get(appId);
       
        if (editor) {
            currentApp.find('.imagedisplayer_upload_form_menu').hide();
            var imageContainer = currentApp.find('.displayimagecontainer');
            imageContainer.show();

            var holder = imageContainer.find('.imagecontainer')
            var image = imageDisplayer.getImage();
            holder.html(image);
        }
    </script>
<? }
?>

