//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.14 at 06:02:02 PM GMT+01:00 
//


package com.assaabloy.arxdata.persons;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accessCategoryUpdatesList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accessCategoryUpdatesList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="access_category_add" type="{}accessCategoryType" maxOccurs="250" minOccurs="0"/>
 *         &lt;element name="access_category_remove" type="{}accessCategoryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="access_category_replace" type="{}accessCategoryType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accessCategoryUpdatesList", propOrder = {
    "accessCategoryAdd",
    "accessCategoryRemove",
    "accessCategoryReplace"
})
public class AccessCategoryUpdatesList {

    @XmlElement(name = "access_category_add")
    protected List<AccessCategoryType> accessCategoryAdd;
    @XmlElement(name = "access_category_remove")
    protected List<AccessCategoryType> accessCategoryRemove;
    @XmlElement(name = "access_category_replace")
    protected List<AccessCategoryType> accessCategoryReplace;

    /**
     * Gets the value of the accessCategoryAdd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessCategoryAdd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessCategoryAdd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessCategoryType }
     * 
     * 
     */
    public List<AccessCategoryType> getAccessCategoryAdd() {
        if (accessCategoryAdd == null) {
            accessCategoryAdd = new ArrayList<AccessCategoryType>();
        }
        return this.accessCategoryAdd;
    }

    /**
     * Gets the value of the accessCategoryRemove property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessCategoryRemove property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessCategoryRemove().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessCategoryType }
     * 
     * 
     */
    public List<AccessCategoryType> getAccessCategoryRemove() {
        if (accessCategoryRemove == null) {
            accessCategoryRemove = new ArrayList<AccessCategoryType>();
        }
        return this.accessCategoryRemove;
    }

    /**
     * Gets the value of the accessCategoryReplace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessCategoryReplace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessCategoryReplace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessCategoryType }
     * 
     * 
     */
    public List<AccessCategoryType> getAccessCategoryReplace() {
        if (accessCategoryReplace == null) {
            accessCategoryReplace = new ArrayList<AccessCategoryType>();
        }
        return this.accessCategoryReplace;
    }

}
