//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.14 at 06:02:02 PM GMT+01:00 
//


package com.assaabloy.arxdata.persons;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the arx package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AccessCategoryListAccessCategory_QNAME = new QName("", "access_category");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: arx
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccessCategoryUpdatesList }
     * 
     */
    public AccessCategoryUpdatesList createAccessCategoryUpdatesList() {
        return new AccessCategoryUpdatesList();
    }

    /**
     * Create an instance of {@link ExtraFieldList }
     * 
     */
    public ExtraFieldList createExtraFieldList() {
        return new ExtraFieldList();
    }

    /**
     * Create an instance of {@link AccessCategoryType }
     * 
     */
    public AccessCategoryType createAccessCategoryType() {
        return new AccessCategoryType();
    }

    /**
     * Create an instance of {@link ResourceAccessUpdateList }
     * 
     */
    public ResourceAccessUpdateList createResourceAccessUpdateList() {
        return new ResourceAccessUpdateList();
    }

    /**
     * Create an instance of {@link CardListType }
     * 
     */
    public CardListType createCardListType() {
        return new CardListType();
    }

    /**
     * Create an instance of {@link PersonListType }
     * 
     */
    public PersonListType createPersonListType() {
        return new PersonListType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link ExtraFieldType }
     * 
     */
    public ExtraFieldType createExtraFieldType() {
        return new ExtraFieldType();
    }

    /**
     * Create an instance of {@link CardType }
     * 
     */
    public CardType createCardType() {
        return new CardType();
    }

    /**
     * Create an instance of {@link Arxdata }
     * 
     */
    public Arxdata createArxdata() {
        return new Arxdata();
    }

    /**
     * Create an instance of {@link ResourceAccessList }
     * 
     */
    public ResourceAccessList createResourceAccessList() {
        return new ResourceAccessList();
    }

    /**
     * Create an instance of {@link AccessCategoryList }
     * 
     */
    public AccessCategoryList createAccessCategoryList() {
        return new AccessCategoryList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessCategoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "access_category", scope = AccessCategoryList.class)
    public JAXBElement<AccessCategoryType> createAccessCategoryListAccessCategory(AccessCategoryType value) {
        return new JAXBElement<AccessCategoryType>(_AccessCategoryListAccessCategory_QNAME, AccessCategoryType.class, AccessCategoryList.class, value);
    }

}
