<div class="contentrow row_width_degreed"> 
    <div class="row_inner">
        <div class="col col_1 col_size_2">
            <img  onclick='showGallary("apartment")' src="xprosjekt/images/leilighet/leilighet4-6pers1.jpg" style="width: 100%; border-radius: 10px;"/>
        </div>
        <div class="col col_2 col_size_2">
            <?php
                ContentManager::render("row_2_room_1");
            ?>
        </div>
    </div>
</div>

<div class="contentrow "> 
    <div class="row_inner">
        <div class="col col_1 col_size_2">
            <img  onclick='showGallary("studioapartment")' src="xprosjekt/images/studioleilighet/st1.jpg" style=" border-radius: 10px; width:100%;"/>
        </div>
        <div class="col col_2 col_size_2">
            <?php
                ContentManager::render("row_3_room_1");
            ?>
        </div>
    </div>
</div>

<div class="contentrow row_width_degreed_reversed"> 
    <div class="row_inner">
        <div class="col col_1 col_size_2">
            <img  onclick='showGallary("anneks")' src="xprosjekt/images/anneks/anneks1.jpg" style="width: 100%; border-radius: 10px;"/>
        </div>
        <div class="col col_2 col_size_2">
            <?php
                ContentManager::render("row_4_room_1");
            ?>
        </div>
    </div>
</div>

<div class="contentrow"> 
    <div class="row_inner">
        <div class="col col_1 col_size_2">
            <img  onclick='showGallary("dobbeltrom")' src="xprosjekt/images/dobbeltrom/dobbeltrom2.jpg" style="width: 100%; border-radius: 10px;"/>
        </div>
        <div class="col col_2 col_size_2">
            <?php
                ContentManager::render("row_5_room_1");
            ?>
        </div>
    </div>
</div>

<script>
    function showGallary(t) {
        var pswpElement = document.querySelectorAll('.pswp')[0];

        if (t == "studioapartment") {
            var items = [
            <?php
            for($i = 1; $i <= 6; $i++) {
                $size = getimagesize("xprosjekt/images/studioleilighet/st$i.jpg");
                ?>
                {
                    src: 'xprosjekt/images/studioleilighet/st<?php echo $i; ?>.jpg',
                    w: <?php echo $size[0] ?>,
                    h: <?php echo $size[1] ?>
                },
                <?php
            }
            ?>
        ];
        }

        if (t == "anneks") {
            var items = [
            <?php
            for($i = 1; $i <= 7; $i++) {
                $size = getimagesize("xprosjekt/images/anneks/anneks$i.jpg");
                ?>
                {
                    src: 'xprosjekt/images/anneks/anneks<?php echo $i; ?>.jpg',
                    w: <?php echo $size[0] ?>,
                    h: <?php echo $size[1] ?>
                },
                <?php
            }
            ?>
        ];
        }
        
        if (t == "dobbeltrom") {
                var items = [
                <?php
                for($i = 1; $i <= 6; $i++) {
                    $size = getimagesize("xprosjekt/images/dobbeltrom/dobbeltrom$i.jpg");
                    ?>
                    {
                        src: 'xprosjekt/images/dobbeltrom/dobbeltrom<?php echo $i; ?>.jpg',
                        w: <?php echo $size[0] ?>,
                        h: <?php echo $size[1] ?>
                    },
                    <?php
                }
                ?>
            ];
        }
        
        
        
        if (t == "apartment") {
                var items = [
                <?php
                for($i = 1; $i <= 6; $i++) {
                    $size = getimagesize("xprosjekt/images/leilighet/leilighet4-6pers$i.jpg");
                    ?>
                    {
                        src: 'xprosjekt/images/leilighet/leilighet4-6pers<?php echo $i; ?>.jpg',
                        w: <?php echo $size[0] ?>,
                        h: <?php echo $size[1] ?>
                    },
                    <?php
                }
                ?>
            ];
        }
        
        
        
        // define options (if needed)
        var options = {
            // optionName: 'option value'
            // for example:
            index: 0 // start at first slide
        };

        // Initializes and opens PhotoSwipe
        var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
        gallery.init();
    }
</script>