<h1><? echo $this->__f("Order email"); ?></h1>    

<div class="textfield gss_setting"  id="shouldSendEmail">
    <span class="title"><?php echo $this->__f("Send email to customers"); ?></span>
    <div class="gss_onoff" gs_model="emailmodel" gs_model_attr="shouldSendEmail">
        <?
        $class = ($this->getConfigurationSetting("shouldSendEmail") == "true") ? "fa-toggle-on" : "fa-toggle-off";
        ?>
        <? echo $this->__f("Off"); ?><i class="fa <? echo $class; ?>"></i><? echo $this->__f("On"); ?>
    </div>
    <div class="description">
        <?php echo $this->__("When a customer places a order, should he/she receive an email with a confirmation?"); ?>
    </div>
</div>
<div class="textfield gss_setting"  id="shouldSendEmailAfterPaymentCompleted">
    <span class="title"><?php echo $this->__f("Send email to customers after payment completed"); ?></span>
    <div class="gss_onoff" gs_model="emailmodel" gs_model_attr="shouldSendEmailAfterCompleted">
        <?
        $class = ($this->getConfigurationSetting("shouldSendEmailAfterCompleted") == "true") ? "fa-toggle-on" : "fa-toggle-off";
        ?>
        <? echo $this->__f("Off"); ?><i class="fa <? echo $class; ?>"></i><? echo $this->__f("On"); ?>
    </div>
    <div class="description">
        <?php echo $this->__("When a customer places a order, should he/she receive an email with a confirmation?"); ?>
    </div>
</div>

<div class="textfield gss_setting"  id="shouldSendEmail">
    <span class="title"><?php echo $this->__f("Order subject"); ?></span>
    <input type='textfield' gs_model='emailmodel' gs_model_attr='ordersubject' value="<? echo $this->getConfigurationSetting("ordersubject"); ?>"/>
    <div class="description">
        <?php echo $this->__("What should the subject be?"); ?>
    </div>
</div>


<div class="textfield gss_setting"  id="shouldSendEmail">
    <span class="title"><?php echo $this->__f("Main order email"); ?></span>
    <textarea gs_model='emailmodel' gs_model_attr='emailconfig' style='position: initial; width: 945px; height: 300px;'><? echo $this->getConfigurationSetting("orderemail"); ?></textarea>
    <div class="description">
        <div>
            <br/>
            <? echo $this->__f("Variables that can be used in email and subject"); ?>:
            <br/> {Customer.Name} = <? echo $this->__f("Name of the customer"); ?>
            <br/> {Customer.Email} = <? echo $this->__f("Email of the customer"); ?>
            <br/> {Customer.Address} = <? echo $this->__f("Street address of the customer"); ?>
            <br/> {Customer.City} = <? echo $this->__f("City of the customer"); ?>
            <br/> {Customer.Postcode} = <? echo $this->__f("Customers postcode"); ?>
            <br/> {Customer.Phone} = <? echo $this->__f("Phonenumber to the customer"); ?>
            <br/> {Order.Id} = <? echo $this->__f("Id of the order"); ?>
            <br/> {Order.IncrementalOrderId} = <? echo $this->__f("Incremental order id of the order"); ?>
            <br/> {Order.Lines} = <? echo $this->__f("Orderlines"); ?>
        </div>
    </div>
</div>
