<?
/* @var $this ns_27716a58_0749_4601_a1bc_051a43a16d14\OrderManager */
$orders = $this->getFilteredData();

$states = array();
$states[0] = "All";
$states[1] = "Created";
$states[2] = "Waiting for payment";
$states[3] = "Payment failed";
$states[4] = "Completed";
$states[5] = "Canceled";
$states[6] = "Sent";
$states[7] = "Payment completed";
$states[8] = "Collection failed";
$states[9] = "Need collecting";
$states[10] = "Send to invoice";

if (!count($orders)) { ?>
<div class='gss_no_orders_found'>
    <i class='fa fa-warning'></i>
    <br/> <? echo $this->__f("No orders found."); ?>
</div>
<?
    return;  
}

$total = 0;

echo "<div class='gss_overview_order'>";
echo "<div class='gss_order_col gss_col_0'><input type='checkbox' class='gsscheckallorders'></input></div>";
echo "<div class='gss_order_col gss_col_1'>" . $this->__f("Order id") . "</div>";
echo "<div class='gss_order_col gss_col_2'>" . $this->__f("Date") . "</div>";
echo "<div class='gss_order_col gss_col_3'>" . $this->__f("Name") . "</div>";
echo "<div class='gss_order_col gss_col_4'>" . $this->__f("Price") . "</div>";
echo "<div class='gss_order_col gss_col_5'>" . $this->__f("State") . "</div>";
echo "</div>";

foreach ($orders as $order) {
    $this->setCurrentOrder($order);
    $orderPaid = $order->status == 7 ? "<i style='color: green;' class='fa fa-check' title='Paid'></i>" : "" ;
    $orderPaid = $order->status == 5 ? "<i style='color: blue;' class='fa fa-times' title='Cancled'></i>" : $orderPaid ;
    $orderPaid = $order->status == 3 ? "<i style='color: red;' class='fa fa-frown-o' title='Paiment failed'></i>" : $orderPaid ;
    $orderPaid = $order->status == 2 ? "<i style='color: #c18800;' class='fa fa-circle-o-notch' title='Waiting for payment'></i>" : $orderPaid ;
    $price = $this->getApi()->getCartManager()->calculateTotalCost($order->cart);
    if(!isset($order->cart->address->fullName)) {
        $name = $this->__w("Unknown name");
    } else {
        $name = $order->cart->address->fullName;
    }
    echo "<div class='gss_overview_order_outer'>";
        echo "<div class='gss_overview_order'>";
        echo "<div class='gss_order_col gss_col_0'><input type='checkbox' class='gssordercheckbox' orderid='".$order->id."'></input></div>";
        echo "<div class='gss_order_col gss_col_1'>$order->incrementOrderId</div>";
        echo "<div class='gss_order_col gss_col_2'>" . date("d.m.Y H:i", strtotime($order->rowCreatedDate)) . "</div>";
        echo "<div class='gss_order_col gss_col_3'>" . $name . "</div>";
        echo "<div class='gss_order_col gss_col_4'>" . round($price,1) . "</div>";
        echo "<div class='gss_order_col gss_col_5'>".$states[$order->status]."</div>";
        echo "</div>";
        $total += $price;
        $this->includefile("ordersmallinfo");
    echo "</div>";
}

echo "<div class='gss_overview_order_outer'>";
    echo "<div class='gss_overview_order'>";
    echo "<div class='gss_order_col gss_col_0'></div>";
    echo "<div class='gss_order_col gss_col_1'>Sum</div>";
    echo "<div class='gss_order_col gss_col_2'></div>";
    echo "<div class='gss_order_col gss_col_3'></div>";
    echo "<div class='gss_order_col gss_col_4'>".round($total,1)."</div>";
    echo "<div class='gss_order_col gss_col_5'></div>";
    echo "</div>";
echo "</div>";
?>
<br>
<select class='gss_neworderstate'>
    <?php 
    foreach($states as $idx => $value) {
        echo "<option value='$idx'>$value</option>";
    }
    ?>
</select>
<input type='button' value='Set new order state' class='gss_setneworderstate'>

<div class="gss_pagenumber_bottom">
    <? echo $this->__f("Page") . ": " . $this->getPageNumber() . "/" . $this->getTotalPageCount(); ?>
    
    <div style='margin-top: 10px; text-align: center;'>
        <? echo $this->__f("Pagesize"); ?>
        <span gss_method='setPageSize' gss_value='10' style='cursor: pointer;'>10</span>,
        <span gss_method='setPageSize' gss_value='20' style='cursor: pointer;'>20</span>,
        <span gss_method='setPageSize' gss_value='30' style='cursor: pointer;'>30</span>,
        <span gss_method='setPageSize' gss_value='50' style='cursor: pointer;'>50</span>,
        <span gss_method='setPageSize' gss_value='100' style='cursor: pointer;'>100</span>,
        <span gss_method='setPageSize' gss_value='200' style='cursor: pointer;'>200</span>,
        <span gss_method='setPageSize' gss_value='300' style='cursor: pointer;'>300</span>,
        <span gss_method='setPageSize' gss_value='500' style='cursor: pointer;'>500</span>
    </div>
</div>
<div class="gss_order_nextprevbuttons">
    <? if ($this->hasPrevPage()) { ?>
        <div class='gss_button order_gss_prev_buttons' gss_method="prevOrderPage"><i class='fa fa-arrow-left'></i> <? echo $this->__f("Previouse page"); ?></div>
    <? } ?>

    <? if ($this->hasNextPage()) { ?>
        <div class='gss_button order_gss_next_buttons' gss_method="nextOrderPage"><i class='fa fa-arrow-right'></i> <? echo $this->__f("Next page"); ?></div>
    <? } ?>
</div>
