<?
/* @var $this ns_27716a58_0749_4601_a1bc_051a43a16d14\OrderManager */
/* @var $address core_usermanager_data_Address */
/* @var $order core_ordermanager_data_Order */
/* @var $cartItem core_cartmanager_data_CartItem */
if (!isset($_POST['value'])) {
    return;
}

$order = $this->getApi()->getOrderManager()->getOrder($_POST['value']);
if (!$order) {
    echo $this->__f("Order not found");
    return;
}

$canChangeOrder = $this->canChangeOrder($order);

$orderStatusText = "";
$orderStatusText = $order->status == 1 ? $this->__f("Created") : $orderStatusText;
$orderStatusText = $order->status == 2 ? $this->__f("Waiting for payment") : $orderStatusText;
$orderStatusText = $order->status == 3 ? $this->__f("Payment failed") : $orderStatusText;
$orderStatusText = $order->status == 4 ? $this->__f("Completed") : $orderStatusText;
$orderStatusText = $order->status == 5 ? $this->__f("Canceled") : $orderStatusText;
$orderStatusText = $order->status == 6 ? $this->__f("Sent") : $orderStatusText;
$orderStatusText = $order->status == 7 ? $this->__f("Payment completed") : $orderStatusText;
$orderStatusText = $order->status == 8 ? $this->__f("Capture failed") : $orderStatusText;
        
        
$cart = $order->cart;
?>
<div class='orderoverview' orderId='<? echo $_POST['value']; ?>'>
    <div class='customerdetails'>
        <?
        $address = $order->cart->address;
        ?>
        <div class='gss_label'><? echo $this->__f("Name"); ?></div>
        <div class='gss_label_content'><? echo $address->fullName; ?></div>
        <div class='gss_label'><? echo $this->__f("Invoice information"); ?></div>
        <div class='gss_label_content'><textarea id="invoiceinformationbox" style="position:relative;height: 100px; width: 100%;"><? echo $order->invoiceNote; ?></textarea><br><br>
        <? if($this->canChangeOrder($order)) { ?>
            <input type="button" value="Update invoice information" id="updateinvoiceinfo">
        <? } ?>
        </div>
        
        <div class='gss_label_content'>
        <? if(!$this->canChangeOrder($order)) { ?>
            <? if(sizeof($order->creditOrderId) > 0) {
                for($i = 1; $i <= sizeof($order->creditOrderId); $i++) {
                    $creditId = $order->creditOrderId[($i-1)];
                    echo '<input type="button" gss_view="gss_orderview" gss_fragment="orderview" gss_method="showOrder" gss_value="'.$creditId.'" value="Open credited order '.$i.'" style="float:right;">';
                }
            }  ?>
            <input type="button" value="Credit order" class="creditinvoice" style="float:right;" orderid="<? echo $order->id; ?>" style='margin-right:10px;'>
        <? } ?>
        </div>
        
        <div class='gss_label'><? echo $this->__f("Incremental order id"); ?></div>
        <div class='gss_label_content'><? echo $order->incrementOrderId; ?></div>
        <div class='gss_label'><? echo $this->__f("Transferred to accounting"); ?></div>
        <div class='gss_label_content'><? echo $order->transferredToAccountingSystem ? $this->__f("Yes") : $this->__f("No"); ?></div>
        <div class='gss_label'><? echo $this->__f("Email"); ?></div>
        <div class='gss_label_content'><? echo $address->emailAddress; ?></div>
        <div class='gss_label'><? echo $this->__f("Phone"); ?></div>
        <div class='gss_label_content'><? echo $address->phone; ?></div>
        <div class='gss_label'><? echo $this->__f("Order date"); ?></div>
        <div class='gss_label_content'><? echo $order->createdDate; ?></div>
        
        <div class='gss_label'><? echo $this->__f("Payment"); ?></div>
        <div class='gss_label_content'>
            <?
            $changeText = $canChangeOrder ? "<i class='fa fa-edit gss_changePaymentType'></i> " : "";
            if ($order->payment->paymentType) {
                $paymentApp = new $order->payment->paymentType();
                echo $changeText.$paymentApp->getName();
                echo "<br/>";
            }
            
            echo $orderStatusText; 
            
            if($order->status == 2 || $order->status == 5 || $order->status == 3) {
                echo " - <a class='gsspayorder' style='color:blue; cursor:pointer;' orderid='".$order->id."'>pay order</a>";
            }
            ?>
            
            <div class="gss_orderview_available_payments">
                <?
                $paymentsApplications= $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
                foreach ($paymentsApplications as $app) {
                    $appInstance = $this->getFactory()->getApplicationPool()->createInstace($app);
                    $id = $app->id;
                    if ($appInstance) {
                        echo "<div class='gss_order_view_select_payement_method' payementMethodId='$id'>".$appInstance->getName()."</div>";
                    }
                }
                ?>
            </div>
        </div>
        
        
        <div class='gss_label'><? echo $this->__f("Shipping"); ?></div>
        <div class='gss_label_content'>
            <? 
            echo $address->fullName."<br/>";
            echo $address->address."<br/>"; 
            echo $address->postCode." ".$address->city."<br/>"; 
            ?>
        </div>
    </div>
    
    <div class='gss_label'>
        <? echo $this->__f("Order"); ?>
    </div>
    <?
    foreach ($cart->items as $cartItem) {
//        echo "<div class='gss_label_content'>";
        $editButton = $canChangeOrder ? "<i class='fa fa-edit gss_changeOrderLine'></i>" : "";
        $editCountButton = $canChangeOrder ? "<i class='fa fa-edit gss_changeOrderCount'></i>" : "";
        $metaText = $cartItem->product->metaData ? " ( " .$cartItem->product->metaData." )" : "";
        
        $dates = "";
        if($cartItem->startDate) {
            $dates .= date("d.m.Y H:i", strtotime($cartItem->startDate));
        }
        if($cartItem->endDate) {
            $dates .= " - " . date("d.m.Y H:i", strtotime($cartItem->endDate));
        }
        echo "<div class='gss_order_line' cartItemId='".$cartItem->cartItemId."'>$editCountButton ".$cartItem->count." x ".$cartItem->product->name." $metaText $dates<span class='gss_order_line_price'>".$cartItem->product->price." $editButton</span></div>";
//        echo "</div>";
    }
    if($this->canChangeOrder($order)) {
    ?>
    <div class='gss_label'>
        <? echo $this->__f("Add item"); ?>
    </div>
    <div class='gss_label_content'>
        <select id='addproductitem'>
            <?
            $products = $this->getApi()->getProductManager()->getAllProducts();
            foreach($products as $product) {
                echo "<option value='".$product->id."'>" . $product->name."</option>";
            }
            ?>
        </select>
        <i class='fa fa-plus-circle gss_addOrderItem' style="cursor:pointer;"></i>
    </div>
    <? } ?>
    <div class='gss_label'>
        <? echo $this->__f("Total price"); ?>
    </div>
    <div class='gss_label_content'>
        <? echo $this->getApi()->getCartManager()->calculateTotalCost($cart); ?>
    </div>
</div>
<br/>

<?
if ($order->transactions) {
    echo "<br/>";
    echo "<b>".$this->__f("Credit card transactions (registered)")."</b>:";
    foreach ($order->transactions as $transaction) {
        echo "<div>&nbsp;&nbsp;Date: ".$transaction->date.", amount: ".$transaction->amount." (".$transaction->microTransactionReference.")</div>";
    }
    echo "<br/><br/>";
}
if($this->canChangeOrder($order)) {
?>

&nbsp;
<div class="gss_button" onclick="$('.gss_more_order_settings').slideDown();">
    <? echo $this->__f("Show more settings"); ?>
</div>
<? } ?>


<?
if ($canChangeOrder) {
?>
    <div orderId='<? echo $order->id; ?>' class="gss_button gss_mark_order_as_paid">
        <? echo $this->__f("Mark order as paid"); ?>
    </div>
<?
}
echo "<a href='/scripts/downloadInvoice.php?orderId=$order->id&incrementalOrderId=$order->incrementOrderId'><div class='gss_button'> Download receipt </div></a>";
echo "<div class='gss_button' style='float:right;' onclick='$(\".gshiddenlogparams\").show();'>Advance settings</div>";
?>
<div class="gss_more_order_settings">
    <center>
        <font style="color: red; font-weight: bold;">
        <?
        echo $this->__f("Please be careful here, this settings should normally be updated automatically.");
        ?>
        </font>
    </center>
    
    
    <div class="textfield gss_setting"  id="isCaptured">
        <span class="title"><?php echo $this->__f("Captured"); ?></span>
        <?
        $class = $order->captured ? "fa-toggle-on" : "fa-toggle-off";
        ?>
        <div class="gss_onoff" gs_model="ordermodel" gs_model_attr="isCaptured">
            Off<i class="fa <? echo $class; ?>"></i>On
        </div>
        <div class="description">
            <?php echo $this->__("Is order captured?"); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="isTestOrder">
        <span class="title"><?php echo $this->__f("Test order"); ?></span>
        
        <?
        $class = $order->testOrder ? "fa-toggle-on" : "fa-toggle-off";
        ?>
        <div class="gss_onoff" gs_model="ordermodel" gs_model_attr="isTestOrder">
            Off<i class="fa <? echo $class; ?>"></i>On
        </div>
        
        <div class="description">
            <?php echo $this->__("This is a test order, should not be accounted and is not part of the summaries."); ?>
        </div>
    </div>
    
    <div class="gss_button" gss_value="<? echo $order->id; ?>" gss_method="updateOrder" gss_model="ordermodel" gss_fragment="orderview" gss_view="gss_orderview">
        <? echo $this->__f("Save"); ?>
    </div>
</div>
<div class='gshiddenlogparams' style='display:none;'>
    <hr>
    <h1>Advance settings</h1>
    <h1>Transaction log</h1>
    <?

    $log = array();
    foreach($order->payment->transactionLog as $time => $value) {
        $log[$time] = $value;
    }
    ksort($log);

    foreach($log as $time => $value) {
        echo date("d.m.Y - H:i:s", ($time/1000)) . " - " . $value . "<br>";
    }

    echo "<br>";
    echo "<br>";
    echo "<h1>Return values from payment gateway</h1>";
    echo "<table>";
    foreach($order->payment->callBackParameters as $key => $value) {
        echo "<tr>";
        echo "<td>" . $key . "</td>";
        echo "<td>" . $value . "</td>";
        echo "</tr>";
    }
    echo "</table>";

    ?>
</div>