<div class="updaterow">
    <div class="label">First Name</div>
    <div class="field"><input type="text"></div>
</div>

<div class="updaterow">
    <div class="label">Last Name</div>
    <div class="field"><input type="text"></div>
</div>

<div class="updaterow">
    <div class="label">Email</div>
    <div class="field"><input type="text"></div>
</div>

<div class="updaterow">
    <div class="label">Cellphone (receive sms on this)</div>
    <div class="field"><input type="text"></div>
</div>

<div class="sedox_blue_button saveprofile">Save</div>
    