<?php
if(isset($_POST['event']) && $_POST['event'] == "addEmail") {
    echo "<script>";
    echo "thundashop.common.goToPage('?page=thankyou_collect');";
    echo "</script>";
} else {
?>
<div gstype="form" method="addEmail">
    <input gsname='email' type='text' placeholder="<? echo $this->__w("your@email.com"); ?>" gstype="submitenter">
    <input gstype="submit" type="button" value='<? echo $this->__w("Register email"); ?>'>
</div>
<?php } ?>
