<?
/* @var $this ns_e4a506de_4702_4d82_8224_f30e5fdb1d2e\MecaFleetServiceList */
$cars = $this->getCarList();
?>
<div class="fleetlist <? echo $this->mode; ?>">
    <div class='servicerow header'>
        <div></div>
        <div></div>
        <div>Flåte</div>
        <div>Regnr </div>
        <div>KM til neste service</div>
        <div>Måneder til neste service</div>
        <div>Dato for PKK</div>
        <div></div>
    </div>
    <?
    foreach ($cars as $car) {
        
        $monthToNextService = $car->monthsToNextService;
        $fleet = $this->getApi()->getMecaManager()->getFleetByCar($car);
        $nextServiceDate = isset($car->nextService) ? date('d/m-Y', strtotime($car->nextService)) : "";

        $agreementStatus = "disabled";
        $agreementStatus = isset($car->needAttentionToService) && $car->needAttentionToService ? "red" : $agreementStatus;
        $agreementStatus = isset($car->nextServiceAgreed) && $car->nextServiceAgreed != null && !@$car->nextServiceAcceptedByCarOwner ? "yellow" : $agreementStatus;
        $agreementStatus = isset($car->nextServiceAgreed) && $car->nextServiceAgreed != null && @$car->nextServiceAcceptedByCarOwner ? "green" : $agreementStatus;

        $agreementStatusBullseye = $agreementStatus;

        $canAgreePkk = isset($car->canAgreeControlDate) && $car->canAgreeControlDate;

        $agreementStatusPkk = "disabled";
        $agreementStatusPkk = $canAgreePkk ? "red" : $agreementStatusPkk;
        $agreementStatusPkk = isset($car->nextControlAgreed) && $car->nextControlAgreed != null && !@$car->nextControlAcceptedByCarOwner ? "yellow" : $agreementStatusPkk;
        $agreementStatusPkk = isset($car->nextControlAgreed) && $car->nextControlAgreed != null && @$car->nextControlAcceptedByCarOwner ? "green" : $agreementStatusPkk;

        $pkkStyleColor = "";
        if ($agreementStatusPkk === "red") {
            $pkkStyleColor = "color: red";
            $agreementStatusBullseye = "red";
        }
        
        $serviceStyleColor = isset($car->needAttentionToService) && $car->needAttentionToService ? "color:red;" : "";
        ?>
        <div class='servicerow'>
            <div>
                <i class="fa fa-bullseye <? echo $agreementStatusBullseye; ?>"></i>
            </div>
            <div>
                <a href='/?page=<? echo $car->pageId; ?>'><i class='gs_shop_small_icon fa fa-edit'></i></a>
            </div>
            <div><? echo isset($fleet->name) ? $fleet->name : "N/A"; ?> </div>
            <div><? echo $car->licensePlate; ?></div>
            <div><? echo isset($car->kilometersToNextService) ? $car->kilometersToNextService : 'N/A'; ?></div>
            <div style="<? echo $serviceStyleColor; ?>"><? echo isset($monthToNextService) ? $monthToNextService . " ( $nextServiceDate ) " : "N/A";  ?> </div>
            <div style="<? echo $pkkStyleColor; ?>"><? echo isset($car->nextControll) ? date('d/m-Y', strtotime($car->nextControll)) : 'N/A'; ?></div>


            <div style="position: relative" class="outercommentfield">
                <div class="gs_shop_small_icon show_comment_field <? echo $car->comment ? 'hasdata' : 'nodata'; ?>"><i class="fa fa-comment-o"></i></div>
                <div class="commentfield" gstype="form" method="saveComment">
                    <input type="hidden" value="<? echo $car->id; ?>" gsname="carid">
                    <textarea gsname="comment"><? echo @$car->comment; ?></textarea>
                    <div class="shop_button" gstype="submit"><? echo $this->__f("Save Comment"); ?></div>
                </div>
                <?
                $used = false;
                if ($agreementStatus === "red") {
                    if ($fleet->followup) {
                        $buttonText = "Sett dato";
                    } else {
                        $buttonText = "Foreslå dato";
                    }
                    echo "<span class='shop_button' gs_show_modal='agreeForService' carid='$car->id' type='service'>$buttonText</span>";
                    $used = true;
                }

                if ($agreementStatus === "yellow" && !$used) {
                    echo "<span class='shop_button' gs_show_modal='agreeForService' carid='$car->id' type='service'>Bytt dato</span>";
                    $used = true;
                }

                if ($agreementStatusPkk == "red" && !$used) {
                    $used = true;
                    ?>
                    <span class="shop_button" gs_show_modal='agreeForService' carid='<? echo $car->id; ?>' type='service'>Foreslå dato</span>
                    <?
                }
                ?>
            </div>


            <?
            if ($agreementStatus === "yellow") {
                echo '<div class="details">';
                $text = isset($car->serviceDateRejected) && $car->serviceDateRejected ? "<span style='color: red'>Tidspunktet passet ikke for kjøretøy eller sjåfør, foreslå et annet tidspunkt</span>" : "Venter på bekreftelse fra kjøretøy eller sjåfør";
                echo "$text. <br/> Foreslått dato: " . date('d/m-Y H:i', strtotime($car->nextServiceAgreed));
                if (isset($car->newSuggestedDate) && $car->newSuggestedDate) {
                    echo "<br/> Sjåfør eller kjøretøy ønsker dato: " . date('d/m-Y H:i', strtotime($car->newSuggestedDate));
                }
                echo '</div>';
            }

            if ($agreementStatus === "green") {
                echo '<div class="details">';
                echo "Sjåfør eller kjøretøy har bekreftet servicedato: " . date('d/m-Y H:i', strtotime($car->nextServiceAgreed));
                echo "<br/> Nåværende kilometerstand <input gsname='currentkilometers' class='current_kilometers' type='number'/> ";
                echo "<div style='block;' class='gserrorfield' id='errorMessage'></div>";
                echo "<br/><span class='shop_button' gs_also='current_kilometers' gsclick='serviceCompleted' carid='$car->id'> Service gjennomført</span>";
                echo " <span class='shop_button' gs_also='current_kilometers' gsclick='pkkCompleted' carid='$car->id'> PKK Gjennomført</span>";
                echo " <span class='shop_button' gs_also='current_kilometers' gsclick='serviceAndCompleted' carid='$car->id'> Service og PKK Gjennomført</span>";
                ?>
                <span style='margin-top: 5px;' class="shop_button" gsclick='noShow' carid='<? echo $car->id; ?>' type='control'>Ikke møtt</span>
                <?
                echo '</div>';
            }
            ?>

        </div>
        <?
    }
    ?>
</div>