<br>
<h2>Actions available</h2>
<br>
<span class='shop_button' gstype="clicksubmit" gsvalue='testConnection' gsname='type' method='doAction'>Test connection</span>
<span class='shop_button' gstype="clicksubmit" gsvalue='fetchAllBookings' gsname='type' method='doAction'>Fetch all bookings</span>
<span class='shop_button' gstype="clicksubmit" gsvalue='fetchNewBookings' gsname='type' method='doAction'>Fetch new bookings</span>
<span class='shop_button' gstype="clicksubmit" gsvalue='updateAvailability' gsname='type' method='doAction'>Update availability</span>
<span class='shop_button' gstype="clicksubmit" gsvalue='markNoShow' gsname='type' method='doAction'>Mark booking as no show</span>
<span class='shop_button' gstype="clicksubmit" gsvalue='updatePrices' gsname='type' method='doAction'>Update prices</span>
<span class='shop_button' gstype="clicksubmit" gsvalue='addAllRooms' gsname='type' method='doAction'>Insert rooms to wubook</span>
<span class='shop_button' gstype="clicksubmit" gsvalue='markCCInvalid' gsname='type' method='doAction'>Mark credit card as invalid</span>
