<?
/* @var $this \ns_24206ea4_45f2_4a08_ac57_ed2c6c8b22f5\PmsCheckList */
$error = $this->getCurrentError();
$booking = $this->getApi()->getPmsManager()->getBooking($this->getSelectedMultilevelDomainName(), $error->metaData->pmsbookingid);
$room = null;
$name = "";
foreach ($booking->rooms as $iroom) {
    if ($iroom->pmsBookingRoomId == $error->metaData->pmsbookingroomid) {
        $room = $iroom;
        $item = "";
        $user =  $this->getApi()->getUserManager()->getUserById($booking->userId);
        if($user) { $name = $user->fullName; }
    }
}
?>

<div class='col bookingId'>
    <? echo "Booking: ".$this->getApi()->getPmsManager()->getBookingSummaryText($this->getSelectedMultilevelDomainName(),$error->metaData->pmsbookingid); ?>
</div>
<div class='col type'>
    <? echo "Room has been set to have pay after stay.<br>"; 
    ?>
</div>
<div class='col orderId'>
<?php
    echo date("d.m.Y", strtotime($room->date->start)) . " " . date("d.m.Y", strtotime($room->date->end));
?>
</div>
<div class='col total'>
    <?php echo $name; ?>
</div>
<div class='col button'>
    <?php
    $pmsapp = new ns_3e2bc00a_4d7c_44f4_a1ea_4b1b953d8c01\PmsBookingGroupRoomView();
    if($pmsapp->useNew()) { ?>
        <div class='gs_shop_small_icon' <?php echo $pmsapp->displayPopUpAttributes($room); ?> ><? echo $this->__f("Open booking"); ?></div>
    <?php } else { ?>
        <div class='gs_shop_small_icon' gs_show_modal='booking_room_view' bookingid="<? echo $booking->id; ?>" roomid="<? echo $room->pmsBookingRoomId; ?>"><? echo $this->__f("Open booking"); ?></div>
    <? } ?>
</div>
