<?
/* @var $this \ns_24206ea4_45f2_4a08_ac57_ed2c6c8b22f5\PmsCheckList */
$error = $this->getCurrentError();
$order = $this->getApi()->getOrderManager()->getOrder($error->metaData->orderid);
$total = $this->getApi()->getOrderManager()->getTotalForOrderById($order->id);
$booking = $this->getApi()->getPmsManager()->getBooking($this->getSelectedMultilevelDomainName(), $error->metaData->pmsbookingid);
$room = $booking->rooms[0];
?>

<div class='col bookingId'>
    <? echo "Booking: ".$this->getApi()->getPmsManager()->getBookingSummaryText($this->getSelectedMultilevelDomainName(),$error->metaData->pmsbookingid); ?>
</div>
<div class='col type'>
    <? echo "Booking.com payment not collected"; ?>
</div>
<div class='col orderId'>
    <? echo "Orderid: ".$order->incrementOrderId; ?>
</div>
<div class='col total'>
    <? echo "Amount: ".$total; ?>
</div>
<div class='col button'>
    <?php
    $pmsapp = new ns_3e2bc00a_4d7c_44f4_a1ea_4b1b953d8c01\PmsBookingGroupRoomView();
    if($pmsapp->useNew()) { ?>
        <div class='gs_shop_small_icon' <?php echo $pmsapp->displayPopUpAttributes($room); ?> ><? echo $this->__f("Open booking"); ?></div>
    <?php } else { ?>
        <div class='gs_shop_small_icon' gs_show_modal='booking_room_view' bookingid="<? echo $booking->id; ?>" roomid="<? echo $room->pmsBookingRoomId; ?>"><? echo $this->__f("Open booking"); ?></div>
    <? } ?>
    <div class='gs_shop_small_icon markorderasbillable' orderid='<? echo $order->id; ?>' bookingid="<? echo $booking->id; ?>" roomid="<? echo $room->pmsBookingRoomId; ?>"><? echo $this->__f("Bill booking.com"); ?></div>
</div>
