<?
/* @var $this \ns_24206ea4_45f2_4a08_ac57_ed2c6c8b22f5\PmsCheckList */
$error = $this->getCurrentError();
$booking = $this->getApi()->getPmsManager()->getBooking($this->getSelectedMultilevelDomainName(), $error->metaData->pmsbookingid);
$diff = $error->metaData->diff;

?>

<div class='col bookingId'>
    <? echo "Booking: ".$this->getApi()->getPmsManager()->getBookingSummaryText($this->getSelectedMultilevelDomainName(),$error->metaData->pmsbookingid); ?>
</div>
<div class='col type' style='width: 400px'>
    <?
    if ($error->metaData->deletedAndNotRefundable) {
        echo "Booking is marked as none refundable and not charged or overcharged.";
    } else {
        echo "Diffrent on total paid amount"; 
    }
    ?>
</div>
<div class='col total'>
    <? echo "Diff: ".$diff; ?>
</div>
<div class='col button'>
    <?php
    $pmsapp = new ns_3e2bc00a_4d7c_44f4_a1ea_4b1b953d8c01\PmsBookingGroupRoomView();
    if($pmsapp->useNew()) { ?>
        <div class='gs_shop_small_icon' <?php echo $pmsapp->displayPopUpAttributes(null, $error->metaData->pmsBookingRoomId); ?> ><? echo $this->__f("Open booking"); ?></div>
    <?php } else { ?>
        <div class='gs_shop_small_icon' gs_show_modal='booking_room_view' bookingid="<? echo $booking->id; ?>" roomid="<? echo $error->metaData->pmsBookingRoomId; ?>"><? echo $this->__f("Open booking"); ?></div>
    <? } ?>
</div>
