<?
/* @var $this \ns_24206ea4_45f2_4a08_ac57_ed2c6c8b22f5\PmsCheckList */
$error = $this->getCurrentError();
$order = $this->getApi()->getOrderManager()->getOrder($error->metaData->orderId);
$total = $this->getApi()->getOrderManager()->getTotalForOrderById($order->id);
$booking = $this->getApi()->getPmsManager()->getBooking($this->getSelectedMultilevelDomainName(), $error->metaData->pmsBookingId);
$room = $booking->rooms[0];
?>

<div class='col bookingId'>
    <? echo "Booking: ".$this->getApi()->getPmsManager()->getBookingSummaryText($this->getSelectedMultilevelDomainName(),$error->metaData->pmsBookingId); ?>
</div>
<div class='col type'>
    <? echo "Expired payment link"; ?>
</div>
<div class='col orderId'>
    <? echo "Orderid: ".$order->incrementOrderId; ?>
</div>
<div class='col total'>
    <? echo "Amount: ".$total; ?>
</div>
<div class='col button'>
    <div class='gs_shop_small_icon' gs_show_modal='booking_room_view' bookingid="<? echo $booking->id; ?>" roomid="<? echo $room->pmsBookingRoomId; ?>"><? echo $this->__f("Open booking"); ?></div>
</div>
