<?

 namespace ns_c7736539_4523_4691_8453_a6aa1e784fc1; ?>
<div class="information">
    <?php echo $this->getDescription(); ?>
</div>

<div class="textfield setting" id="account_1">
    <input type="textfield" value="" class="config"/>
    <div class="description">
        <? echo $this->__f("Specify an airgram account."); ?></div>
</div>

<div class="textfield setting" id="account_2">
    <input type="textfield" value="" class="config"/>
    <div class="description">
        <? echo $this->__f("Specify an airgram account."); ?></div>
</div>

<div class="textfield setting" id="account_3">
    <input type="textfield" value="" class="config"/>
    <div class="description">
        <? echo $this->__f("Specify an airgram account."); ?></div>
</div>

<div class="textfield setting" id="account_4">
    <input type="textfield" value="" class="config"/>
    <div class="description">
        <? echo $this->__f("Specify an airgram account."); ?></div>
</div>

<div class="textfield setting" id="account_5">
    <input type="textfield" value="" class="config"/>
    <div class="description">
        <? echo $this->__f("Specify an airgram account."); ?></div>
</div>

<div class="button savebutton"><div class="rightglare"></div><div class="filler"></div><ins><?php echo $this->__("Save settings"); ?></ins></div>