<span class='eventeditarea'></span>
<?php
/* @var $this ns_28886d7d_91d6_409a_a455_9351a426bed5\PmsAvailability */
$activities = array();
$activities['closed'] = "Closed off";
$activities['overbooking'] = "Waiting list / overbook";
$start = $this->convertToJavaDate($this->getStartDate());
$end = $this->convertToJavaDate($this->getEndDate());
$lines = $this->getApi()->getPmsManager()->getActivitiesEntries($this->getSelectedMultilevelDomainName(), $start, $end);
foreach($lines->lines as $key => $l) {
    $activities[$key] = $key;
}
ksort($activities);
$numberOfLines = sizeof($activities);
?>
<div class="type_line">
    <div class="timeline_item_name">
        <div class="category_name">Activities</div>
        <?php
        foreach($activities as $activity => $name) {
            if(stristr($activity, "conference")) { $name = "Conference"; }
            if(stristr($activity, "otherevents")) { $name = "Other events"; }
            if(stristr($activity, "blocked")) { $name = "Closed off"; }
            if(stristr($activity, "overbooking")) { $name = "Overbooking / waiting list"; }
            if(stristr($activity, "closed")) { $name = "Closed off"; }

            echo '<div class="item_name">'.$name.'</div>';
        }
        ?>
    </div>

    <div class="timeline" style='width: calc(100% - 205px);' typeid="">
        <?php
        $i = 0;
        foreach($activities as $activity => $name) {
            $odd = $i % 2 ? "odd" : "even";
            echo "<div class='timeline_row $odd'>";
            $time = $this->getStartDate();
            while(true) { 
                $colName = $colDate = date("D", $time) . "<br>" . date("d.m", $time);
                $isWeekend = (date('N', $time) >= 6) ? "weekend" : "";
                ?>
                <div class=" col col_width col_data nodata col_outer first_in_row last_in_row" style="width: 170px;">
                    <?php
                    if($i == 0) {
                        ?>
                        <div class="header col_width <?php echo $isWeekend; ?>"><?php echo $colName; ?></div>
                        <?php
                    }
                    $hasBooking = "";
                    $entry = $this->hasEventEntries($time, $lines, $activity);
                    $bookingId = "";
                    if($entry) { 
                        $bookingId = "bookingid='".$entry->activityId."'";
                        $hasBooking = "normal contains_booking"; 
                    }
                                        
                    $displayWaitinglist = "";
                    if($activity == "closed" || $activity == "overbooking") {
                        $displayWaitinglist = "displaywatinglist";
                    }
                    $offset = (date('z', $time) + 1) . "-" . date("Y", $time);
                    
                    $typecategory = "";
                    $sourceId = "";
                    if($entry) {
                        if(stristr($activity, "conference")) { $typecategory = "conference"; }
                        if(stristr($activity, "otherevents")) { $typecategory = "otherevents"; }
                        if(stristr($activity, "blocked")) { $typecategory = "blocked"; }
                        if(stristr($activity, "overbooking")) { $typecategory = "overbooking"; }
                        if(stristr($activity, "closed")) { $typecategory = "closedoffhotel"; }
                        $sourceId = "sourceid='".$entry->sourceId."'";
                    }
                    ?>
                   <div <?php echo $bookingId; ?> roomid="" class="<?php echo $hasBooking . " " . $typecategory; ?> timeline_col1 col col_width col_data first_in_row last_in_row <?php echo $displayWaitinglist; ?>" <?php echo $sourceId; ?>>
                        <div class="bookername" numberofblocks="1" style="margin-right: 0px;">
                            <?php if($entry && !$this->printedNameOnActivity($entry->activityId)) { ?>
                            <span class="fullname" style="display: inline;" title="<?php echo $entry->title; ?>"><?php echo $entry->title; ?></span>
                            <span class="acronyme" style="display: none;"></span>
                            <?php } ?>
                        </div>
                   </div>
                </div>
                <?php
               if($time > $this->getEndDate()) {
                   break;
               }
               $time += 86400;
            }
            $i++;
           echo "</div>";
        }
        ?>
    </div>
</div>