<?
/* @var $this ns_28886d7d_91d6_409a_a455_9351a426bed5\PmsAvailability */
$currentBooking = $this->getCurrentBookingFromBookingEngine();
$types = $this->getTypes();
$items = $this->getItems();

$startDate = $this->convertToJavaDate(strtotime($currentBooking->startDate));
$endDate = $this->convertToJavaDate(strtotime($currentBooking->endDate));
$availableItems = $this->getApi()->getBookingEngine()->getAllAvailbleItemsWithBookingConsidered($this->getSelectedMultilevelDomainName(), $startDate, $endDate, $currentBooking->id);

function canUseItem($item, $availeableitems) {
    foreach ($availeableitems as $available) {
        if ($available->id == $item->id) {
            return true;
        }
    }
    
    return false;
}
?>
<?
foreach ($types as $type) {
?>
    <div class='movetotype'>
        <div class="headername"><? echo $type->name; ?></div>
        <div>
            <?
            foreach ($items as $item) {
                if ($item->bookingItemTypeId != $type->id) {
                    continue;
                }
                
                $useClass = canUseItem($item, $availableItems) ? "canUse" : "canNotUse";
                echo "<div class='bookingitem $useClass'>".$item->bookingItemName."</div>";
            }
            ?>
        </div>
    </div>
<?
}
?>