<div class="isnotactive" style='margin-top: 20px; width: 1500px; margin: auto;margin-bottom: 100px;'>
    <div class="kaipal infobox">
        <div class="image talking"></div>
        <div class="textbox">
            <div class="header" style='border-bottom: 0px;'><? echo $this->__f("You need to create rooms before you can continue."); ?></div>
            <div class="text" style='min-height:100px;'>
                <?
                echo "<div>" . $this->__f("I have an awesome availability view to show you. But without any rooms its not much to show, please go to settings and help me add some rooms for you.") . "</div>";
                echo "<div>" . $this->__f("The availability view gives you a total overview of all the rooms and who needs the different rooms.") . "</div>";
                ?>
            </div>
        </div>
    </div>
</div>