
<div class="closemodalarea"></div>
<?
/* @var $this ns_28886d7d_91d6_409a_a455_9351a426bed5\PmsAvailability */

$items = $this->getItems();
$timelines = $this->getData();
$types = $this->getTypes();
$typesIndexed = $this->indexList($types);
$sorting = $this->getSortType();
$allInOne = false;
if($sorting == "room") {
    $allInOne = true;
}
$cats = $this->getCategoryFilter();
foreach ($types as $type) {
    if(sizeof($cats) > 0 && !in_array($type->id, $cats) && !$allInOne) {
        continue;
    }
?>
   
    <div class='type_line'>
        
        <div class='timeline_item_name'>
            
            <?
            echo "<div class='category_name'>";
            if(!$allInOne) {
                echo $type->name;
            }
            echo "</div>";
            
            foreach ($items as $item) {
                if ($item->bookingItemTypeId != $type->id && !$allInOne) {
                    continue;
                }
                if($allInOne && sizeof($cats) > 0 && !in_array($item->bookingItemTypeId, $cats)) {
                    continue;
                }
                
                echo "<div class='item_name'>";
                echo $item->bookingItemName . " " . $typesIndexed[$item->bookingItemTypeId]->name;
                echo "</div>";
            }
            ?>
        </div>
        
        <div class='timeline'>
            <?
            
            $j = 0;
            foreach ($items as $item) {
                
                if ($item->bookingItemTypeId != $type->id && !$allInOne) {
                    continue;
                }
                
                if($allInOne && sizeof($cats) > 0 && !in_array($item->bookingItemTypeId, $cats)) {
                    continue;
                }
                
                $itemTimeLines = $timelines->itemTimeLines->{$item->id};
                $i = 1;
                
                
                $odd = $j % 2 ? "odd" : "even";
                echo "<div class='timeline_row $odd'>";
                    $prevBookingIds = array();
                    
                    foreach ($itemTimeLines as $time => $data) {
                        $header = "";
                        $colDate = date("d.m.y", $time/1000);
                        $colDate2 = date("m/d/y", $time/1000);
                        
                        if ($j == 0) {
                            $header = "<div class='header col_width'>$colDate</div>";
                        }
                        
                        $nextBookingIds = $this->getNextBookingIds($itemTimeLines, $time);
                        $inPrev = $this->anyMatches($data->bookingIds, $prevBookingIds) ? "connected_with_prev" : "";
                        $inNext = $this->anyMatches($data->bookingIds, $nextBookingIds) ? "connected_with_next" : "";
                        
                        $firstInRow = (!$inPrev && $inNext) || (!$inNext && !$inPrev)  ? "first_in_row" : "";
                        $lastInRow = ($inPrev && !$inNext) || (!$inNext && !$inPrev) ? "last_in_row" : "";
                        
                        $color = $data->state;
                        
                        if ($this->anyMatches($data->bookingIds, $data->virtuallyAssigned) && $data->state === "normal") {
                            $color = "grey";
                        }
                        
                        $containsBooking = count($data->bookingIds) ? "contains_booking" : "";
                        $bookingId = count($data->bookingIds) ? $data->bookingIds[0] : "";
                        
                        if (!$inPrev && $containsBooking) {
                            $header .= $this->createNameOfBooker($data);
                        }
                        
                        $firstInRowOuter = "";
                        if ($firstInRow && $containsBooking) {
                            $firstInRowOuter = $firstInRow."_outer";
                        }
                        
                        $lastInRowOuter = "";
                        if ($lastInRow && $containsBooking) {
                            $lastInRowOuter = $lastInRow."_outer";
                        }
                        
                        $noData = !$containsBooking ? "nodata" : "";
                        $canShowModal = $containsBooking && $data->state == "normal" ? "hasBookingYes"  : "";
                        $dragging = "";
                        $marking = "";
                        $dragging .= "ondragstart='app.PmsAvailability.onDragStart(event)' ondrop='app.PmsAvailability.onDragDrop(event)' ondragleave='app.PmsAvailability.onDragLeave(event)' ondragover='app.PmsAvailability.onDragOver(event)' onmousedown='app.PmsAvailability.startMarking(event)' onmouseup='app.PmsAvailability.endMarking(event)' onmouseover='app.PmsAvailability.markArea(event)'";
                        if($canShowModal) {
                            $dragging .= " draggable='true' ";
                        }
                        echo "<div typeid='$type->id' col='$i' bookingitemid='$item->id' date='$colDate2' row='$j' class='col_outer $noData $firstInRowOuter $lastInRowOuter'><div $canShowModal bookingid='$bookingId' roomid='$data->roomId' $dragging class='$color timeline_col$i col col_width col_data $containsBooking $inPrev $inNext $firstInRow $lastInRow'>$header</div></div>";
                        $prevBookingIds = $data->bookingIds;
                        $i++;
                    }
                    
                    $j++;
                    
                echo "</div>";

            }
            ?>
        </div>
    </div>
<?
    if($allInOne) {
        break;
    }
}


$conferenceRooms = array();
foreach($items as $item) {
    if($item->bookingItemTypeId == "gsconference") {
        $conferenceRooms[] = $item;
    }
}
if(sizeof($conferenceRooms) > 0) {
    $filter = $this->getSelectedFilter();
    $toPrint = array();
    foreach($conferenceRooms as $confRoom) {
        $start = $this->convertToJavaDate(strtotime($filter->start));
        $end = $this->convertToJavaDate(strtotime($filter->end));
        $reservations = $this->getApi()->getBookingEngine()->getAllBookingsByBookingItemInDateRange($this->getSelectedMultilevelDomainName(), 
                $confRoom->id, $start, $end);
        foreach((array)$reservations as $reservation) {
            $entry = new ns_e8fedc44_b227_400b_8f4d_52d52e58ecfe\DayViewCalendarEntry();
            $entry->start = strtotime($reservation->startDate);
            $entry->end = strtotime($reservation->endDate);
            $entry->roomId = $confRoom->id;
            $entry->id = $reservation->id;
            $entry->type = "reservation";
            $toPrint[] = $entry;
        }
    }
    
    echo "<h3>Conference room overview</h3>";
    
    $app = new \ns_e8fedc44_b227_400b_8f4d_52d52e58ecfe\DayViewCalendar();
    $app->setNumberOfRooms(sizeof($conferenceRooms));
    $app->setDateRange($filter->start, $filter->end);
    $app->setEvents($toPrint);
    foreach($conferenceRooms as $confRoom) {
        $color = $app->getColorForRoomId($confRoom->id);
        if(!$color) {
            echo "<span class='availabilitylabel' style='color:#aaa;'> " . $confRoom->bookingItemName . " (not in use)</span>";
        } else {
            echo "<span class='availabilitylabel' style='color:$color;'> " . $confRoom->bookingItemName . "</span>";
        }
    }
    $app->render();
}



?>
<script>
$(document).ready(function() {
    
    var count = $('.timeline_row:first').find('.header').size();
    var width = $(this).find('.timeline_item_name').outerWidth() + 5;
    $(this).find('.timeline').css('width', 'calc(100% - ' + width + "px)");
    width = $(this).find('.timeline').width();
    var size = width/count;
    
    if (size < 64) {
        size = 64;
    }
    
    $(".col_outer").outerWidth(size);
    
    $('.bookername').each(function() {
        var col = $(this).closest('.col_outer').find('.col_data');
        var bookingid = col.attr('bookingid');
        var numberOfBlocks = $('.col_data[bookingid="'+bookingid+'"]').size();
        var marginLeft = size * numberOfBlocks;
        marginLeft -= size;
        $(this).css('margin-right', "-"+marginLeft+"px");
        $(this).find('span').hide();
        $(this).attr('numberofblocks', numberOfBlocks);
        
        if (size > 100 || numberOfBlocks > 1) {
            $(this).find('.fullname').fadeIn();
        } else {
            $(this).find('.acronyme').fadeIn();
        }
    });
    document.addEventListener('scroll', function (event) {
        var line = $(event.target);
        if($(event.target).hasClass('timeline')) {
            console.log(line.scrollLeft());
            $('.timeline').scrollLeft(line.scrollLeft());
        }
    }, true /*Capture event*/);
});
</script>