<? namespace ns_e2554f70_ecdb_47a6_ba37_79497ea65986; ?>
<br>
<div style="font-size: 16px; padding: 10px;">Thank you for watching our introduction movie.<br>This movie shows you quickly how fast you can get started with getshop.</div>
<br>
<div style="text-align: center;" >
    <iframe width="900" height="506" src="http://www.youtube.com/embed/01EHOSHfTs4?vq=hd720" frameborder="0" allowfullscreen></iframe>    
</div>
