<?
/* @var $this ns_e6570c0a_8240_4971_be34_2e67f0253fd3\AccountFinanceReport */
if (isset($_POST['data']['value']) && $_POST['data']['value']) {
    $_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_paymentid'] = $_POST['data']['value'];
}

if ($_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_paymentid'] == null || !isset($_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_paymentid'])) {
    return;
}
$name = $this->getNameOfPaymentMethod($this->getApi()->getStoreApplicationPool()->getApplication($_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_paymentid']));

$start = $this->getStart();
$end = $this->getEnd();
$dayIncomes = $this->getApi()->getOrderManager()->getPaymentRecords($_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_paymentid'], $start, $end);
$isLocked = $this->getApi()->getOrderManager()->isLocked($end);
$bankAccountClosed = $this->getApi()->getOrderManager()->isBankAccountClosed($end);
$isShowingExTaxes = $this->isShowingIncTaxes();
$invoiceActivated = $_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_paymentid'] == "70ace3f0-3981-11e3-aa6e-0800200c9a66";
$autoCloseActivated = $this->getApi()->getOrderManager()->getOrderManagerSettings()->autoCloseFinancialDataWhenCreatingZReport;
$monthHasPassed = strtotime($end) < time();

$selectedYear = date('Y', strtotime($start));
$selectedMonth = date('m', strtotime($start));

$errors  = array();
foreach ($dayIncomes as $dayIncome) {
    if ($dayIncome->errorMsg) {
        $errors[] = $dayIncome->errorMsg;
    } else {
        foreach ($dayIncome->dayEntries as $entry) {
            if ($entry->isTaxTransaction && $this->isShowingIncTaxes()) {
                continue;
            }
            $allAccountNumbers[] = $entry->accountingNumber;
        }
    }
}

if (count($errors)) {
    echo "<h1>".$this->__f("There are a few errors you have to sort out first.")."</h1>";
    foreach ($errors as $error) {
        echo "<div style='color: red; margin-left: 50px;'>- ".$error."</div>";
    }
    return;
}

$accounts = array_unique($allAccountNumbers);
sort($accounts);
$store = $this->getApi()->getStoreManager()->getMyStore();
$storeYear = date('Y', strtotime($store->rowCreatedDate));
echo "<script>";
    echo "storeCreatedYear = ".$storeYear.";";
    echo "storeCreatedMonth = ".date('m', strtotime($store->rowCreatedDate)).";";
echo "</script>";
?>
<div class="infoheader">
    <div class="divededheader">
        <?
        echo "<div class='head'>".$this->__f("Transaction report for")." $name</div>";
        echo $this->__f("Periode").": ".date('d.m.Y', strtotime($start))." - ".date('d.m.Y', strtotime($end));
        ?>
        <div>
            <? echo $this->__f("You can click on each row to inspect each day and see how the amounts are for each account."); ?>
        </div>

        <br/><b>Please select: </b>
        <br/>
        <div gstype='form' method='showMonth'>
            <select  gsname='month' class='gsniceselect1 timeperiode'>
                <option value="1" <? echo $selectedMonth == 1 ? 'selected="true"' :""; ?>>Jan</option>
                <option value="2" <? echo $selectedMonth == 2 ? 'selected="true"' :""; ?>>Feb</option>
                <option value="3" <? echo $selectedMonth == 3 ? 'selected="true"' :""; ?>>Mar</option>
                <option value="4" <? echo $selectedMonth == 4 ? 'selected="true"' :""; ?>>Apr</option>
                <option value="5" <? echo $selectedMonth == 5 ? 'selected="true"' :""; ?>>May</option>
                <option value="6" <? echo $selectedMonth == 6 ? 'selected="true"' :""; ?>>June</option>
                <option value="7" <? echo $selectedMonth == 7 ? 'selected="true"' :""; ?>>July</option>
                <option value="8" <? echo $selectedMonth == 8 ? 'selected="true"' :""; ?>>Aug</option>
                <option value="9" <? echo $selectedMonth == 9 ? 'selected="true"' :""; ?>>Sep</option>
                <option value="10" <? echo $selectedMonth == 10 ? 'selected="true"' :""; ?>>Oct</option>
                <option value="11" <? echo $selectedMonth == 11 ? 'selected="true"' :""; ?>>Nov</option>
                <option value="12" <? echo $selectedMonth == 12 ? 'selected="true"' :""; ?>>Dec</option>
            </select>
            -
            <select gsname='year' class='gsniceselect1 timeperiode'>
                <?
                $nextYear = date('Y') + 1;
                for ($i=$storeYear; $i<=$nextYear; $i++) {
                    $year = $i;
                    $selected = $year == $selectedYear ? 'selected="true"' :""; 
                    echo "<option $selected year='$year'>$year</option>";
                }
                ?>
            </select>
            -
            <div gstype='submit' class='shop_button showresultbutton'><? echo $this->__f("Show"); ?></div>
        </div>
    </div>
    
    <div class="divededheader">
        <?
        if ($invoiceActivated && $monthHasPassed) {
            echo "<div class='head'>".$this->__f("Bank account")."</div>";
            if ($bankAccountClosed) {
            ?>
                <div><? echo $this->__f("Bank account has been closed for this periode"); ?></div>
            <?
            } else {
            ?>
                <div>
                    <? echo $this->__f("When a bank account is open for the periode you can register manually payments for the periode. This is normally done with manually mark invoices as paid."); ?>
                    <br/>
                    <br/><div class="shop_button" gsclick="closeBankAccount"> <? echo $this->__f("Close bank account"); ?></div>
                </div>
            <?
            }
        }
        ?>
    </div>
    
</div>

<?
$system = $this->getApi()->getGetShopAccountingManager()->getCurrentSystemOther();
$appTemplateFile = '../app/'.$appname.'/template/' . $system . "_BUTTON.phtml";

if (file_exists($appTemplateFile)) {
    $files = $this->getApi()->getOrderManager()->getAllDoublePostTransferFiles($paymentId, $start, $end);
?>
<div class="accountdownloadfilearea">
    <h2>Accounting transfer</h2>
    <?
    foreach ($files as $file) {
        $accountsSum = $this->getSum($file);
        $user = $this->getApi()->getUserManager()->getUserById($file->userId);
        
        ?>
        <div class='downloadlink'>
            <div class='col'><? echo date('d.m.Y H:i', strtotime($file->rowCreatedDate)); ?></div>
            <div class='col'><? echo $user->fullName; ?></div>
            <?
            foreach ($accountsSum as $acc => $sumi) {
                ?>
                <div  class='col'>
                    <? echo "<b>".$acc."</b><br/> ".$sumi; ?>
                </div>
                <?
            }
            ?>
            <div class='col'> 
                <?
                $_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_current_doublepostfileid'] = $file->id;
                $this->includefile($system."_BUTTON");
                unset($_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_current_doublepostfileid']);
                ?>
            </div>
        </div>
        <?
    }
    ?>
    <div class="shop_button" gsclick="createTransferFiles">
        <?
        echo $this->__f("Create new file");
        ?>
    </div>
    <?
    
    ?>
</div>
<?
}

if ($this->extramessage) {
?>
    <div>
        <?
        echo $this->extramessage;
        ?>
    </div>
<?
}

echo "<div class='outer' style='display: inline-block; vertical-align: top;'>";
    echo "<div class='top_row_header'>";
        echo "<div>".$this->__f("Balance report ( f-report + payment transactions )")."</div>";
    echo "</div>";
    
    $this->includefile("doublepostbalancereport");
echo "</div>";
?>
<script>
    $(document).ready(function() {
        app.AccountFinanceReport.changePeriodeOptions();
    })
</script>