<?
if (isset($_POST['data']['value']) && $_POST['data']['value']) {
    $_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_paymentid'] = $_POST['data']['value'];
}

$name = $this->getNameOfPaymentMethod($this->getApi()->getStoreApplicationPool()->getApplication($_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_paymentid']));

$start = $this->getStart();
$end = $this->getEnd();
$dayIncomes = $this->getApi()->getOrderManager()->getPaymentRecords($_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_paymentid'], $start, $end);

$isLocked = $this->getApi()->getOrderManager()->isLocked($end);
$bankAccountClosed = $this->getApi()->getOrderManager()->isBankAccountClosed($end);
$isShowingExTaxes = $this->isShowingIncTaxes();
$autoCloseActivated = $this->getApi()->getOrderManager()->getOrderManagerSettings()->autoCloseFinancialDataWhenCreatingZReport;
$incomeBalance = $this->getApi()->getOrderManager()->getBalance($start, $_SESSION['ns_e6570c0a_8240_4971_be34_2e67f0253fd3_paymentid']);

$this->getApi()->getPmsManager()->markOtaPaymentsAutomaticallyPaidOnCheckin($this->getSelectedMultilevelDomainName(), $start, $end);

$monthHasPassed = strtotime($end) < time();

$selectedYear = date('Y', strtotime($start));
$selectedMonth = date('m', strtotime($start));

$isSuportingDirectTransfer = $this->getApi()->getGetShopAccountingManager()->isCurrentSelectedSupportingDirectTransfer();


$errors  = array();
foreach ($dayIncomes as $dayIncome) {
    if ($dayIncome->errorMsg) {
        $errors[] = $dayIncome->errorMsg;
    } else {
        foreach ($dayIncome->dayEntries as $entry) {
            if ($entry->isTaxTransaction && $this->isShowingIncTaxes()) {
                continue;
            }
            $allAccountNumbers[] = $entry->accountingNumber;
        }
    }
}

if (count($errors)) {
    echo "<h1>".$this->__f("There are a few errors you have to sort out first.")."</h1>";
    foreach ($errors as $error) {
        if ($this->isJson($error)) {
            $json = json_decode($error);
             
            $correctbutton = $json->errorType == "MISSING_ACCOUNT_NUMBER" ? "<div class='gs_shop_small_icon' gs_show_modal='productview' selectedtab='accounting' productid='$json->productId'>Click to fix</div>" : "";;
            echo "<div style='color: red; margin-left: 50px;'>$correctbutton ".$json->msg."</div>";
        } else {
            echo "<div style='color: red; margin-left: 50px;'>- ".$error."</div>";
        }
        
    }
    return;
}

function printIncomeValues($accounts, $incomeBalance, $text) {
    echo "<div class='row' >";
        echo "<div class='inner_row inbalance2' >";
            echo "<div class='col orderid'>$text</div>";
            
            foreach ($accounts as $account) {
                $val = $incomeBalance->balances->{$account};
                echo "<div class='col $account'>".round($val,2)."</div>";
            }
            
            echo "<div class='col controlsum'>-</div>";
        echo "</div>";
    echo "</div>";
}

$accounts = array_unique($allAccountNumbers);
sort($accounts);
$store = $this->getApi()->getStoreManager()->getMyStore();
$storeYear = date('Y', strtotime($store->rowCreatedDate));
echo "<script>";
    echo "storeCreatedYear = ".$storeYear.";";
    echo "storeCreatedMonth = ".date('m', strtotime($store->rowCreatedDate)).";";
echo "</script>";

if ($this->extramessage) {
?>
    <div>
        <?
        echo $this->extramessage;
        ?>
    </div>
<?
}

echo "<div class='outer'>";

    echo "<div class='row header'>";
        echo "<div class='col orderid header'>Date</div>";
        foreach ($accounts as $account) {
            echo "<div class='col $account header' gsclick='showDetailedProductView' accountnumber='$account'>".$account;
                echo "<div class='accountdesc'>".$this->getAccountDescription($account)."</div>";;
            echo "</div>";
        }
        echo "<div class='col controlsum'>Zero Check</div>";
    echo "</div>";
    
    $i = 0;
    foreach ($dayIncomes as $dayIncome) {
        $i++;
        if ($i == 1) {
            printIncomeValues($accounts, $incomeBalance, $this->__f("Balance in"));
        }
        
        echo "<div class='row' >";
            echo "<div class='inner_row' gsclick='showDetailedReport'  start='$dayIncome->start' end='$dayIncome->end' >";
                
                $isLocked = $dayIncome->isFinal ? "<i class='fa fa-lock'></i>" : "";
                $grouped = $this->groupOnAccounting($dayIncome->dayEntries);
                echo "<div class='col orderid'>$isLocked ".date('d.m.Y H:i', strtotime($dayIncome->start))." - ".date('H:i', strtotime($dayIncome->end))."</div>";
                $controlSum = 0;
                foreach ($accounts as $account) {
                    if (isset($grouped[$account]) && $grouped[$account]) {
                        $sum[$account] = @$sum[$account] + $grouped[$account];
                    }

                    if (isset($grouped[$account]) && $grouped[$account]) {
                        $controlSum += ($grouped[$account]);
                    }

                    $val = isset($grouped[$account]) && $grouped[$account] ? $grouped[$account] : "&nbsp;";
                    echo "<div class='col $account'>".round($val,2)."</div>";
                }

                if ($controlSum < 0.00001 && $controlSum > -0.00001 ) {
                    $controlSum = 0;
                }
                echo "<div class='col controlsum'>".$controlSum."</div>";
            echo "</div>";
            
            if ($isSuportingDirectTransfer && $dayIncome->isFinal) {
                $checked = count($dayIncome->accountingTransfer) ? " <i class='fa fa-check' title='This day has already been transferred'></i>" : "";
//                $askForPassword = count($dayIncome->accountingTransfer) ? " gs_precheck='app.AccountFinanceReport.askForPassword'" : "";
                $askForPassword = "";
                echo "<div class='col' gsclick='startUploadOfData' $askForPassword start='$dayIncome->start' end='$dayIncome->end' synchron='true' gs_callback='app.AccountFinanceReport.transferredToAccounting'>".'<i class="gs_shop_small_icon fa fa-upload"></i>'.$checked."</div>";
                
            }

        echo "</div>";
    }
    
    echo "<div class='row summaryrow'>";

        echo "<div class='col orderid'>Total for month</div>";

        foreach ($accounts as $account) {
            if (!isset($incomeBalance->balances->{$account})) {
                $incomeBalance->balances->{$account} = 0;
            }
            
            $val = isset($sum[$account]) && $sum[$account] ? $sum[$account] : "&nbsp;";
            $incomeBalance->balances->{$account} += $val;
            echo "<div account='$account' class='col $account totalcolforaccount'>".round($val,2);
            ?>
            <div class='summarymenu'>
                <div class='entry' gsclick='showSummaryForAccount' account='<? echo $account; ?>' ><? echo $this->__f("Show open balances pr")." ".date('d.m.Y', strtotime($end)); ?></div>
                <div class='entry' gsclick='showAllTransactionsForMonth' account='<? echo $account; ?>' ><? echo $this->__f("Show all transactions for month"); ?></div>
            </div>
            <?
            echo "</div>";
        }

    echo "</div>";
    
    printIncomeValues($accounts, $incomeBalance, $this->__f("Balance out"));
echo "</div>";

?>