<?php
/* @var $this ns_e6570c0a_8240_4971_be34_2e67f0253fd3\AccountFinanceReport */

$accounts = $this->getApi()->getProductManager()->getAccountingAccounts();
usort($accounts, array('ns_4404dc7d_e68a_4fd5_bd98_39813974a606\EcommerceProductView','sortByAccountingDescription'));
?>
<div class="freeposting" gstype="form" method="createFreePosting">
    

    <div class="info">
        <?
        echo $this->__f("You can use this function to do corrections for your f-report.");
        ?>
    </div>
    Posting date: 
    <br/>
    <input class="gsniceinput1" gsname="date"/>
    <br/>
    <br/>
    Credit account: 
    <br/>
    <select class="gsniceselect1" gsname="creditaccount">
        <?
        foreach ($accounts as $account) {
            ?>
            <option value="<? echo $account->accountNumber; ?>"><? echo $account->accountNumber. " - ".$account->description; ?></option>
            <?
        }
        ?>
    </select>
    <br/>
    <br/>
    Debit account: 
    <br/>
    <select class="gsniceselect1" gsname="debitaccount">
        <?
        foreach ($accounts as $account) {
            ?>
            <option value="<? echo $account->accountNumber; ?>"><? echo $account->accountNumber. " - ".$account->description; ?></option>
            <?
        }
        ?>
    </select>
    <br/>
    <br/>
    Amount: 
    <br/>
    <input class="gsniceinput1" gsname="amount"/>
    <br/>
    <br/>
    Comment: 
    <br/>
    <input class="gsniceinput1" gsname="comment"/>
    <br/>
    <br/>
    <?
    if ($this->savedFreePost === null) {
    ?>
    <div style='font-size: 16px; color: red; font-weight: bold; padding-bottom: 20px;'>
        <? echo $this->__f("Failed to create freepost, please check the amount and that the date is not within a closed periode"); ?> 
    </div>
    <?
    }
    if ($this->savedFreePost) {
    ?>
    <div style='font-size: 16px; color: green; font-weight: bold; padding-bottom: 20px;'>
        <? echo $this->__f("Created..."); ?> 
    </div>
    <?
    }
    ?>
    <div class="shop_button" gstype="submit"><? echo $this->__f("Create"); ?></div>
</div>


<script>
    $('[gsname="date"]').datetimepicker({ dateFormat: "dd.mm.yy"});
</script>