<?
/* @var $this \ns_e6570c0a_8240_4971_be34_2e67f0253fd3\AccountFinanceReport */
$start = $this->getStart();
$end = $this->getEnd();
$dayIncomes = $this->getApi()->getOrderManager()->getDayIncomes($start, $end);


$rows = array();
foreach ($dayIncomes as $dayIncome) {
    $grouped = $this->groupOnAccounting($dayIncome->dayEntries);
    foreach ($grouped as $accountNumber => $amount) {
        $row = array();
        $row[0] = 'GBAT10'; 
        $row[1] = ''; 
        $row[2] = date('Ymd', strtotime($dayIncome->start));  // YYYYMMDD
        $row[3] = '1'; 
        $row[4] = date('m', strtotime($dayIncome->start));
        $row[5] = date('Y', strtotime($dayIncome->start));
        $row[6] = $accountNumber; 
        $row[7] = $this->getTaxCodeForAccount($accountNumber); 
        $row[8] = $amount; 
        $row[9] = ''; 
        $row[10] = ''; 
        $row[11] = ''; 
        $row[12] = ''; 
        $row[13] = ''; 
        $row[14] = ''; 
        $row[15] = ''; 
        $row[16] = ''; 
        $row[17] = ''; 
        $row[18] = ''; 
        $row[19] = ''; 
        $row[20] = ''; 
        $row[21] = ''; 
        $row[22] = ''; 
        $row[23] = ''; 
        $row[24] = ''; 
        $row[25] = ''; 
        $row[26] = 'T'; 
        $row[27] = ''; 
        $row[28] = ''; 
        $row[29] = ''; 
        $row[30] = ''; 
        $rows[] = $row;
    }
}

foreach ($rows as $row) {
    echo implode(";", $row)."\r\n";
}
?>