<?php
namespace ns_900e5f6b_4113_46ad_82df_8dafe7872c99;
?>

<div class="checkout">
    <div class="inline checkoutarea">
        <?
            $checkoutStep = $this->getCheckoutStep();
            if ($checkoutStep == "address") {
                $this->includefile("addressform");
            } else if ($checkoutStep == "shipping") {
                $this->includefile("deliverymethods");
            } else if ($checkoutStep == "payment") {
                $this->includefile("paymentform");
            }
        ?>
    </div>
</div>