<div class='step step2 nomatch'>
    <div class='stepnumber'>2</div>
    <div class='step_title'>Enter your car details.</div>
    <div class='subinfo'>
        <div class='line'><div class='col1'><input id="brand" placeholder='Brand (Ex, Audi)' type='textfield'></div></div>
        <div class='line'><div class='col1'><input id="model" placeholder='Model (ex, A4)' type='textfield'></div></div>
        <div class='line'><div class='col1'><input id="enginesize" placeholder='EngineSize (Ex, 2.0TDI)' type='textfield'></div></div>
        <div class='line'><div class='col1'><input id="power" placeholder='Power (Ex, 140hp)' type='textfield'></div></div>
        <div class='line'><div class='col1'><input id="year" placeholder='Year (Ex, 2014)' type='textfield'></div></div>
        <div class='line'><div class='col1'><input id="tool" placeholder='Tool (Ex, CMD / Frieling / Powergate / Kess)' type='textfield'></div></div>
        <div class='line'><textarea id="comments" placeholder='Comment! Do you have anything else to share with us?'></textarea></div>
        <div class='line multi'><div class='col1_1'>Automatic gear</div> 
            <div class='col2'>
                <div class="onoffswitch">
                    <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="automaticgear" >
                    <label class="onoffswitch-label" for="automaticgear">
                        <div class="onoffswitch-inner"></div>
                        <div class="onoffswitch-switch"></div>
                    </label>
                </div>
            </div>
        </div>
        <div class='line multi'><div class='col1_1'>Automatically withdraw my credit account and send the file back when ready</div> 
            <div class='col2'>
                <div class="onoffswitch">
                    <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="usecredit" checked>
                    <label class="onoffswitch-label" for="usecredit">
                        <div class="onoffswitch-inner"></div>
                        <div class="onoffswitch-switch"></div>
                    </label>
                </div>        
            </div>

        </div>
    </div>
    <div class='gs_button savecardetails'><i class='fa fa-arrow-circle-right'></i>&nbsp; Next</div>
</div>