<div class="information">
    <?
    echo $this->__f("What is your opening hours?");
    ?>
</div>

<div class="textfield setting"  id="redirectopageonsuccess">
    <span class="title"><?php echo $this->__f("Success page:"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 22:00"); ?>
    </div>
</div>

<div class="button savebutton"><div class="rightglare"></div><div class="filler"></div><ins><?php echo $this->__f("Save settings"); ?></ins></div>