<div class="uploadfilemodal">
    
    <div class="modal_inner">
        <div class="modalcontent">
            
            
            <div class="progressbararea">
                <div class="progressheader">Uploading: <span class="sedox_upload_filename"> Test</span></div>
                
                <div class="meter">
                    <span style="width: 0%"></span>
                    <div class="progresindicator">0%</div>
                </div>
                
            </div>
                
            <div class="selectarea">
                <div class="closebutton"><i class="fa fa-close"></i></div>    
                <div class="headertitle boldFont"> Upload your files </div>    
                <div class="dragdropfilesareas">
                    <i class="fa fa-cloud-upload"></i>
                    Drag and Drop File Here
                    <br/> or
                    <br/>

                    <div class="fileBrowse btn btn-primary sedox_blue_button selectFileButton">
                        <span>BROWSE</span>
                        <input type="file" id="sedox_file_upload_selector" class="upload" />
                    </div>
                </div>
            </div>
        </div>
    </div>
        
</div>
    