<div class='step step1'>
    <div class='stepnumber'>1</div>
    <div class='step_title'>Select your original file</div>

    <form id='uploadfileform' method="post" enctype="multipart/form-data">
        <div class='subinfo'>
            <input type='file' name="originalfile" id="originalfile"/>
        </div>
        <div class='sedox_button' onclick="$('#uploadfileform').submit();"><i class='fa fa-arrow-circle-right'></i>&nbsp;Next</div>
    </form>
</div>