<div class='gss_settings_header'>
    <i class='fa fa-cc-visa'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Nets"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->getDescription();
            ?>	
        </div>
    </div>	
</div>
<div class='gss_settings_content'>
    <div class="textfield gss_setting">
        <span class="title">Merchant-ID</span>
        <input type="textfield" gs_model='netsmodel' gs_model_attr='merchantid' value="<? echo $this->getConfigurationSetting("merchantid"); ?>" placeholder="">
        <div class="description">
             <?php  echo $this->__f("The Merchant-ID is provided by NetAxept, please contact us for more information."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting">
        <span class="title">Token</span>
        <input type="textfield" gs_model='netsmodel' gs_model_attr='token' value="<? echo $this->getConfigurationSetting("token"); ?>" placeholder="">
        <div class="description">
              <?php  echo $this->__f("The Merchant-ID is provided by NetAxept, please contact us for more information."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting">
        <span class="title">Success page</span>
        <input type="textfield" gs_model='netsmodel' gs_model_attr='okpage' value="<? echo $this->getConfigurationSetting("okpage"); ?>" placeholder="">
        <div class="description">
             <?php  echo $this->__f("Link to your thank you page."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting">
        <span class="title">Cancelled page</span>
        <input type="textfield" gs_model='netsmodel' gs_model_attr='canceledpage' value="<? echo $this->getConfigurationSetting("canceledpage"); ?>" placeholder="">
        <div class="description">
            <?php  echo $this->__f("Link to your cancelled you page."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting">
        <span class="title">Payment failed</span>
        <input type="textfield" gs_model='netsmodel' gs_model_attr='paymentfailed' value="<? echo $this->getConfigurationSetting("paymentfailed"); ?>" placeholder="">
        <div class="description">
            <?php  echo $this->__f("Link to your payment failed page."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting">
        <span class="title">Payment failed email title</span>
        <input type="textfield" gs_model='netsmodel' gs_model_attr='emailpaymentfailedtitle' value="<? echo $this->getConfigurationSetting("emailpaymentfailedtitle"); ?>" placeholder="">
        <div class="description">
            <?php  echo $this->__f("Payment failed / betaling feilet."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting">
        <span class="title">Payment failed email body</span>
        <textarea type="textfield" gs_model='netsmodel' gs_model_attr='emailpaymentfailedbody' ><? echo $this->getConfigurationSetting("emailpaymentfailedbody"); ?></textarea>
        <div class="description">
            <?php  echo $this->__f("Payment failed / betaling feilet."); ?>
        </div>
    </div>
    
     <div class="textfield gss_setting"  id="editor">
        <span class="title"><?php echo $this->__f("Test mode"); ?></span>
        <div class="gss_onoff" gs_model="netsmodel" gs_model_attr="debugmode">
            <?
            $class = $this->getConfigurationSetting("debugmode") == "true" ? "fa-toggle-on" : "fa-toggle-off";
            ?>
            <? echo $this->__f("Off"); ?><i class="fa <? echo $class; ?>"></i><? echo $this->__f("On"); ?>
        </div>
        <div class="description">
            <?php echo $this->__("Are you running this store in test mode?"); ?>
        </div>
    </div>
    
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="netsmodel" gss_success_message="<? echo $this->__f("Saved settings"); ?>"><i class='fa fa-save'></i><?php echo $this->__("Save settings"); ?></div>
    </div>
</div>

