<?
/* @var $this \ns_e913b056_a5e1_4ca8_83b6_92f192e2a06b\C3Management */
$user = $this->getCurrentUser();

if ($_POST['value']) {
    $user = $this->getApi()->getUserManager()->getUserById($_POST['value']);
}

$accessList = $this->getApi()->getC3Manager()->getAcceListForUser($user->id);
$forskningsperiodes = $this->getApi()->getC3Manager()->getForskningsPeriodesForUser($user->id);

?>

<div class="gss_overrideapp view_c3management" gss_use_app_id="e913b056-a5e1-4ca8-83b6-92f192e2a06b">
    
    <div class="textfield gss_setting">
        <span class="title"><?php echo $this->__f("Post 1.1 - Tilatt føre timer på forskningsrådets midler."); ?></span>
        <div class="gss_onoff" gs_model="c3manmodel" gs_model_attr="nfrhour">
            <? $faclass = $this->getApi()->getC3Manager()->allowedNfrHour($user->id) ? "fa-toggle-on" : "fa-toggle-off"; ?>
            <? echo $this->__f("Off"); ?><i class="fa <? echo $faclass; ?>"></i><? echo $this->__f("On"); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting">
        <span class="title"><?php echo $this->__f("Post 1.4 - Tilatt andre kostnader på forskningsrådets midler."); ?></span>
        <div class="gss_onoff" gs_model="c3manmodel" gs_model_attr="nfrother">
            <? $faclass = $this->getApi()->getC3Manager()->allowedNfrOtherCost($user->id) ? "fa-toggle-on" : "fa-toggle-off"; ?>
            <? echo $this->__f("Off"); ?><i class="fa <? echo $faclass; ?>"></i><? echo $this->__f("On"); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting">
        <span class="title"><?php echo $this->__f("Post 1.1 - Tilatt føre timeslønn på fastpris."); ?></span>
        <div class="gss_onoff" gs_model="c3manmodel" gs_model_attr="fixedHourCost">
            <? $faclass = $this->getApi()->getC3Manager()->allowedFixedHourCosts($user->id) ? "fa-toggle-on" : "fa-toggle-off"; ?>
            <? echo $this->__f("Off"); ?><i class="fa <? echo $faclass; ?>"></i><? echo $this->__f("On"); ?>
        </div>
    </div>

    
    <input type="hidden" gs_model="c3manmodel" gs_model_attr="userid" value="<? echo $user->id; ?>"/>
    <div class="textfield gss_setting"  id="name">
        <span class="title"><?php echo $this->__f("Timerate"); ?></span>
        <div class="gss_dropdown">
            <select class="property_select" gs_model="c3manmodel" gs_model_attr="hourrate">
                <?php
                echo "<option value=''>None</option>";
                foreach ($this->getApi()->getC3Manager()->getTimeRates() as $rate) {
                    $selected = $this->isSelected($rate, $user) ? "selected='true'" : "";
                    echo "<option value='" . $rate->id . "' $selected>" . $rate->name ."($rate->rate)". "</option>";
                }
                ?>
            </select>
        </div>
        <div class="description">
            Dersom brukeren registerer timer skal denne timeraten benyttes, velg til høyre.
        </div>
    </div>
    
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveHourRate" gss_model="c3manmodel" gss_success_message="Saved successfully"><i class='fa fa-save'></i>Lagre</div>
    </div>

    <div style="border-bottom: dashed 2px #DDD; margin-bottom: 20px;"></div>
    <center><h3>Forskingsbrukere (arbeidsperiode + stillingsprosent)</h3></center>
    <center> Dersom brukeren er en forskingsbruker, så kan du legge til arbeidsperioder under. Brukeren må da fordele sin stillingsprosent på de forskjellige prosjektene i gitte perioder.</center>
    <br/>
    <?
    if ($forskningsperiodes) {
        echo "<div style='background-color: #FCFCFC; padding: 20px; box-sizing: border-box; border: solid 1px #DDD;'>";
        $i = 0;
        foreach ($forskningsperiodes as $periode) {
            $i++;
            $bottomborder = count($forskningsperiodes) == $i ? "" : "border-bottom: solid 1px #DDD; ";
            echo "<div style='; padding: 5px; $bottomborder position: relative; padding-left: 50px'>";
            echo "<div class='gs_shop_small_icon' gss_view='view_c3management' gss_fragment='usersettings' gss_value='$user->id' gss_value_2='$periode->id' gss_method='deletePeriode' style='position: absolute; left: 5px; top: 5px;'><i class='fa fa-trash'></i></div>";
            echo "Periode: " . date('d/m-Y', strtotime($periode->start)) . ", til: " . date('d/m-Y', strtotime($periode->end)). "<br/>Stillingsprosent: ".$periode->percents ."%";
            echo "</div>";
        }
        echo "</div>";
        echo "<br/>";
    }
    ?>
    <?
        if ($accessList) {

    ?>
        <div style='background-color: #FCFCFC; padding: 20px; box-sizing: border-box; border: solid 1px #DDD;'>
        <h1>Legg til Forskningsrådets midler (Periode)</h1>
        
            <div class="textfield gss_setting">
                <span class="title">Dato fra </span>
                <input type="textfield" gs_model='c3managementmodel' gs_model_attr='from' value="" id='c3managementaddfrom'>
                <div class="description"></div>
            </div>
        
            <div class="textfield gss_setting">
                <span class="title">Dato til </span>
                <input type="textfield" gs_model='c3managementmodel' gs_model_attr='to' value="" id='c3managementaddto'>
                <div class="description"></div>
            </div>
        
            <div class="textfield gss_setting">
                <span class="title">Prosentsats</span>
                <input type="textfield" gs_model='c3managementmodel' gs_model_attr='percent' value="">
                <div class="description"></div>
            </div>
        
            <div class='gss_button_area'>
                <div class="gss_button" gss_method="addNewPeriode" gss_value='<? echo $user->id; ?>' gss_model="c3managementmodel" gss_view='view_c3management' gss_fragment='usersettings'><i class='fa fa-save'></i>Legg til</div>
            </div>
        </div>
    
        <?
    }
    ?>
    
</div>

