<?php
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$this->setData();
$addons = $this->getSelectedRoom()->addons;

$pickerOpen = false;
if(isset($_SESSION['gs_currently_showing_rightWidget'])) { 
    $pickerOpen = true;             
}
                

if(sizeof($addons) == 0 && !$pickerOpen) {
    ?>
    <div class="kaipal infobox">
        <div class="image sad"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("No addons added yet"); ?></div>
            <div class="text">
                <?
                echo $this->__f("Hi, we do not have any addons added to this room yet.");
                ?>    
                <div class="buttonarea">
                    <div class="buttonareaheader"><? echo $this->__f("What would you like to do?"); ?></div>
                    <div class="shop_button" onclick="thundashop.framework.toggleRightWidgetPanel('addaddons')"
                         gstype='clicksubmit' gscached='true' gsname="id" gsvalue="<?php echo $this->bookingEngineBooking->id; ?>" method="reloadAddons"  gstoarea=".addonsArea"
                         ><? echo $this->__f("Add addon"); ?></div>
                </div>
                

            </div>
        </div>
    </div>
    <?php
} else if($pickerOpen) {
    ?>
    <div class="kaipal infobox">
        <div class="image happy"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("Yiiihaa! Add some addons!"); ?></div>
            <div class="text">
                <?
                echo $this->__f("Add whatever addons from the menu to the left.");
                ?>
                <div class="buttonarea">
                    <div class="buttonareaheader"><? echo $this->__f("What would you like to do?"); ?></div>
                    <div class="shop_button" onclick="thundashop.framework.toggleRightWidgetPanel('addaddons')"
                         gstype='clicksubmit' gscached='true' gsname="id" gsvalue="<?php echo $this->bookingEngineBooking->id; ?>" method="reloadAddons"  gstoarea=".addonsArea"
                         ><? echo $this->__f("Close addons area"); ?></div>
                    <?php
                    if(sizeof($addons) > 0) {
                        ?>
                    <div class="shop_button removeselectedaddons"><i class='fa fa-trash-o'></i> <? echo $this->__f("Remove selected addons"); ?></div>
                    <?php
                    }?>
                </div>
            </div>
        </div>
    </div>
    <?php
} else {
    
    ?>
    <div class="kaipal infobox">
        <div class="image talking"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("You have addons added."); ?></div>
            <div class="text">
                <?
                echo $this->__f("You can edit the addons by clicking on the edit icon found in at the left of the addons added in the list below, or you could add more addons to the this booking. Last but not least, you can also select addons you would like to remove and have them removed.");
                ?>
                <div class="buttonarea">
                    <div class="buttonareaheader"><? echo $this->__f("What would you like to do?"); ?></div>
                    <div class="shop_button" onclick="thundashop.framework.toggleRightWidgetPanel('addaddons')"
                         gstype='clicksubmit' gscached='true' gsname="id" gsvalue="<?php echo $this->bookingEngineBooking->id; ?>" method="reloadAddons"  gstoarea=".addonsArea"
                         ><? echo $this->__f("Add more addons"); ?></div>
                    <div class="shop_button removeselectedaddons"><i class='fa fa-trash-o'></i> <? echo $this->__f("Remove selected addons"); ?></div>
                </div>
            </div>
        </div>
    </div>
    <?php
}

if(sizeof($addons) > 0) {
    ?>
    <div class='editaddonpanel' style='display:none;'></div>
    <h3>Addons added</h3>
    <div class='row headercol'>
        <div class='col col-1'></div><div class='col col-2'>Name</div><div class='col col-3'>Count</div><div class='col col-4'>Total</div><div class='col col-5'>Edit</div>
    </div>

    <?php
    $productAddonPrinted = array();
     foreach($addons as $addon) {
        if(in_array($addon->productId, $productAddonPrinted)) {
            continue;
        }
        $addonsCount = 0;
        $addonsTotal = 0;
        foreach($addons as $addon2) {
            if($addon2->productId != $addon->productId) {
                continue;
            }
            $addonsCount += $addon2->count;
            $addonsTotal += ($addon2->count * $addon2->price);
        }
        echo "<div class='row' productId='".$addon->productId."'>";
        echo "<div class='col col-1'><i class='fa fa-square-o toggleRemoveAddonCheckBox'></i></div>";
        
        $name = $addon->name;
        if(!$name) {
            $name = $this->getApi()->getProductManager()->getProduct($addon->productId)->name;
        }
        
        echo "<div class='col col-2'>".$name."</div>";
        echo "<div class='col col-3'>".$addonsCount."</div>";
        echo "<div class='col col-4'>".$addonsTotal."</div>";
        echo "<div class='col col-4'><i class='fa fa-edit editaddon' productId='".$addon->productId."'></i></div>";
        echo "</div>";
        $productAddonPrinted[] = $addon->productId;
     }
}
?>

<span gstype='clicksubmit' gscached='true' gsname="id" gsvalue="<?php echo $this->bookingEngineBooking->id; ?>" method="reloadAddons"  gstoarea=".addonsArea" id='reloadaddonsarea'></span>