<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$savedRoom = $this->getSelectedRoom();
$room = $this->getTmpSelectedRoom($savedRoom->pmsBookingRoomId);

$types = $this->getTypes();
$items = $this->getItems();

$startDate = $this->convertToJavaDate(strtotime($room->date->start));
$endDate = $this->convertToJavaDate(strtotime($room->date->end));

$isSameDayStart = date('Y-m-d', strtotime($startDate)) == date('Y-m-d', time());

function canUseItem($item, $availeableitems) {
    foreach ((array)$availeableitems as $available) {
        if ($available->id == $item->id) {
            return true;
        }
    }
    
    return false;
}

$warnAboutUnchanges = "";
$startDateToCheckOn = $startDate;

$cleanIcon = "";
$splitChecked = "";
if(isset($room->doSplitChange) && $room->doSplitChange) {
    $splitChecked = "CHECKED";
    $startDateToCheckOn = $this->convertToJavaDate(time());
}

$availableItems = $this->getApi()->getBookingEngine()->getAllAvailbleItemsWithBookingConsidered($this->getSelectedMultilevelDomainName(), $startDateToCheckOn, $endDate, $room->bookingId);
?>

<div class='updater'>
    <i class='fa fa-spin fa-spinner'></i> Updating.. please wait..
</div>
<div gstype="select" gsname="itemid"><?
    foreach ($types as $type) {
        $useClass = "canNotUse";

        $canUseFloating = "canNotUse";

        $currentlyUsingFloating = !$room->bookingItemId  && $room->bookingItemTypeId == $type->id ? "gs_selected" : "";
        foreach ($items as $item) {
            if ($item->bookingItemTypeId != $type->id) {
                continue;
            }

            if (canUseItem($item, $availableItems)) {
                $canUseFloating = "canUse";
            }
        }
    ?>
        <div class='movetotype' typeid='<? echo $type->id; ?>'>
            <div class="headername">
                <? echo $type->name; ?>
            </div>
            <div class="itemselector">
                <div class='bookingitem floatingbutton <? echo $canUseFloating." ".$currentlyUsingFloating; ?>' gs_value='<? echo $type->id; ?>' itemId=""><? echo $this->__f("Floating"); ?></div>
                <?

                foreach ($items as $item) {
                    if ($item->bookingItemTypeId != $type->id) {
                        continue;
                    }

                    if (canUseItem($item, $availableItems)) {
                        $useClass = "canUse";
                    }
                }

                $currentlyUsing = !$room->bookingItemId  && $room->bookingItemTypeId == $type->id ? "gs_selected" : "";
                foreach ($items as $item) {

                    if ($item->bookingItemTypeId != $type->id) {
                        continue;
                    }

                    if ($isSameDayStart) {
                        $cleanText = $this->__f("This room is clean");
                        $cleanIcon = $this->getApi()->getPmsManager()->isClean($this->getSelectedMultilevelDomainName(), $item->id) ? "<i title='$cleanText' class='gsicon-gs-cleaning'></i> " : "";
                    }
                    $currentlyUsing = $item->id == $room->bookingItemId ? "gs_selected" : "";
                    $useClass = canUseItem($item, $availableItems) ? "canUse" : "canNotUse";
                    echo "<div class='bookingitem $useClass $currentlyUsing' gs_value='".$type->id."_".$item->id."' itemId='".$item->id."'>$cleanIcon".$item->bookingItemName."</div>";
                }
                ?>
            </div>
        </div>
    <?
    }
    ?>
</div>

<div class='explenation'>
    <div class='expcolorouter'><div class='expcolor canUse'></div> <? echo $this->__f("Can be selected"); ?></div>
    <div class='expcolorouter'><div class='expcolor canNotUse'></div> <? echo $this->__f("Not available"); ?></div>
    <div class='expcolorouter'><div class='expcolor canNotUseGs_selected'></div> <? echo $this->__f("Guest is living in this room, but is not available for the given timeframe"); ?></div>
    <div class='expcolorouter'><div class='expcolor gs_selected'></div> <? echo $this->__f("Selected"); ?></div>
</div>    