<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$this->setData();

$pmsBooking = $this->getPmsBooking();
$bookingEngineBooking = $this->getBookingEngineBooking();
$pmsSelectedRoom = $this->getSelectedRoom();

?>

<div gstype='form' method="updateBooking" class="bookingoverview_content_row">
    <input type='hidden' gsname='roomId' value='<? echo $pmsSelectedRoom->pmsBookingRoomId; ?>'/>
   
     
    <div class="menuarea" roomId="<? echo $pmsSelectedRoom->pmsBookingRoomId; ?>" bookingEngineId="<? echo $bookingEngineBooking->id; ?>">
        <div class="menuentry <? echo $this->isTabActive('bookinginformation'); ?>" tab='bookinginformation'><i class="fa fa-info"></i> <span><? echo $this->__f("Booking"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('stayinformation'); ?>" tab='stayinformation'><i class="fa fa-calendar"></i> <span><? echo $this->__f("Stay"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('addons'); ?>" tab='addons'><i class="fa fa-plus-circle"></i> <span><? echo $this->__f("Addons"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('accesscodes'); ?>" tab='accesscodes'><i class="fa fa-key"></i> <span><? echo $this->__f("Access code"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('messages'); ?>" tab='messages'><i class="fa fa-envelope"></i> <span><? echo $this->__f("Messages"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('orders'); ?>" needAllSaved='true' clearTabContent="true" tab='orders'><i class="fa fa-dollar"></i> <span><? echo $this->__f("Payments"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('log'); ?>" clearTabContent="true" tab='log'><i class="fa fa-history"></i> <span><? echo $this->__f("Log"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('ticket'); ?>" needAllSaved='true' tab='ticket'><i class="fa fa-ticket"></i> <span><? echo $this->__f("Tickets"); ?></span></div>
    </div>
    
    <div class="workarea">
 
        <div class="guestinformation <? echo $this->isTabActive('bookinginformation'); ?>" tab='bookinginformation'>
            <?
            $this->includefile("bookinginformation");
            ?>
        </div>
        
        <div class="guestinformation <? echo $this->isTabActive('addons'); ?>" tab='addons'>
            <?php
            $this->includefile("addons");
            ?>
        </div>
        
        <div class="guestinformation <? echo $this->isTabActive('accesscodes'); ?> accesscode" tab='accesscodes'>
            <? $this->includefile("accesscode"); ?>
        </div>
        
        <div class="guestinformation <? echo $this->isTabActive('messages'); ?>" tab='messages'>
            messages
        </div>
        
        <div class="guestinformation <? echo $this->isTabActive('orders'); ?>" tab='orders'>
            <? 
            $this->includefile("orderstab");
            ?>
        </div>
        
        <div class="guestinformation <? echo $this->isTabActive('ticket'); ?>" tab='ticket'>
            <? 
            $this->includefile("ticket");
            ?>
        </div>
        
        <div class="guestinformation <? echo $this->isTabActive('log'); ?>" tab='log'>
            <?
            if ($_SESSION['currentSubMenu'] == "log") {
                $this->includefile("log");
            }
            ?>
        </div>
        
        <div class="stayinformation PmsAvailability <? echo $this->isTabActive('stayinformation'); ?>" tab='stayinformation'>
            <?
            $this->includefile("movebooking");
            ?>
        </div>
        
        <div class="bottommenuarea">
            <a href="/?page=groupbooking&bookingEngineId=<? echo $this->bookingEngineBooking->id; ?>">
                <div gstype="submit" class="shop_button" gs_local_update_only="true"><i class="fa fa-chain"></i> <? echo $this->__f("Open group"); ?></div>
            </a>
            <div gstype="submit" class="shop_button" gs_callback="app.PmsBookingRoomView.contentSaved" synchron="true"><i class="fa fa-save"></i> <? echo $this->__f("Save"); ?></div>
        </div>
    </div>
</div>
