<?php
$pmsBooking = $this->getPmsBooking();
$pmsSelectedRoom = $this->getSelectedRoom();
$user = $this->getUserForBooking();
$bookingEngineBooking = $this->getBookingEngineBooking();

$extraArgs = array();
$extraArgs['userid'] = $user->id;
$extraArgs['id'] = $bookingEngineBooking->id;
$extraArgs['roomId'] = $pmsSelectedRoom->pmsBookingRoomId;
?>
<div class="row odd">
    <div class="col col1"><? echo $this->__f("GetShop booking id"); ?></div>
    <div class="col col2"><? echo $pmsBooking->incrementBookingId; ?></div>    
</div>

<?php
if ($pmsBooking->wubookchannelreservationcode) {
    ?>
    <div class="row odd">
        <div class="col col1"><? echo $this->__f("Channel reservation id"); ?></div>
        <div class="col col2"><? echo $pmsBooking->wubookchannelreservationcode; ?></div>    
    </div>
    <?php
}
if ($pmsBooking->wubookreservationid) {
    ?>
    <div class="row odd">
        <div class="col col1"><? echo $this->__f("Wubook id"); ?></div>
        <div class="col col2"><? echo $pmsBooking->wubookreservationid . " (<a href='https://wubook.net/bookings/" . $pmsBooking->wubookreservationid . "' target='_new'>Open in wubook</a>)"; ?></div>    
    </div>
    <?php
}
?>

<div class="row odd">
    <div class="col col1"><? echo $this->__f("Non refundable"); ?></div>
    <?php
    if ($pmsBooking->nonrefundable) {
        ?>
        <div class="col col2">Yes, <span style='color:blue;cursor:pointer;' gsclick='togglerefundable'>make it refundable</span></div>    
        <?php
    } else {
        ?>
        <div class="col col2">No, <span style='color:blue;cursor:pointer;' gsclick='togglerefundable'>make it non refundable</span></div>    
        <?php
    }
    ?>
</div>

<div class="row">
    <div class="col col1"><? echo $this->__f("Date created"); ?></div>
    <div class="col col2"><? echo date("d.m.Y H:i", strtotime($pmsBooking->rowCreatedDate)); ?></div>    
</div>

<div class="row odd">
    <div class="col col1"><span><? echo $this->__f("Booked for"); ?></span></div>
    <div class="col col2">
        <?
        $quser = new \ns_b5e9370e_121f_414d_bda2_74df44010c3b\GetShopQuickUser();
        $quser->setUser($user);
        $quser->setExtraArgs($extraArgs);
        $quser->renderApplication(true, $this);
        ?>
    </div>
</div>

<div class="row odd">
    <div class="col col1"><span><? echo $this->__f("Adress"); ?></span></div>
    <div class="col col2">
        <?php
        if (isset($user->address)) {
            echo $user->address->address . "<br>";
            echo $user->address->postCode . " " . $user->address->city . "<br>";
        }
        ?>
    </div>
</div>

<div class="row odd">
    <div class="col col1"><span><? echo $this->__f("Registration information"); ?></span></div>
    <div class="col col2" onclick='$(".registeredinformation").toggle();' style='cursor:pointer;'>Display registration information</div>
    <div class='registeredinformation' style='display:none;'>
        <?php
        foreach ($pmsBooking->registrationData->resultAdded as $key => $val) {
            echo "<div>" . $key . " : " . $val . "</div>";
        }
        ?>
    </div>
</div>
