<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$this->setData();

$pmsBooking = $this->getPmsBooking();
$bookingEngineBooking = $this->getBookingEngineBooking();
$pmsSelectedRoom = $this->getSelectedRoom();

$stayPrice = $this->getStayPrice();
$addonsPrice = $this->getAddonsCost(false);
$addonsPriceToDisplay = $this->getAddonsCost(true);
$totalOnRoom = $stayPrice + $addonsPrice;

if(!$stayPrice) {$stayPrice = "";} else {
    $stayPrice = round($stayPrice);
    $stayPrice  = " - " . $stayPrice;
}


if(!$addonsPriceToDisplay) {$addonsPriceToDisplay = "";} else {$addonsPriceToDisplay  = " - " . $addonsPriceToDisplay;}



$numberOfRooms = 0;
foreach($pmsBooking->rooms as $room) {
    $numberOfRooms++;
}

if(isset($pmsSelectedRoom->hasBeenUpdated) && $pmsSelectedRoom->hasBeenUpdated) {
    $changes = $this->getDifferenceInRoom();
    echo "<div class='changespanel'></div>";
    echo "<div class='unsavedchangeswarning'><i class='fa fa-info-circle'></i> You have unsaved changes for this room (".$changes['totalchanges'].").";
    echo "<span style='position:absolute; right:5px; top: 5px;'>";
    echo "<span class='shop_button' style='margin-right: 5px;background-color:red;' gstype='clicksubmit' gsname='id' gsvalue='123' method='discardChanges'><i class='fa fa-trash-o'></i> Discard changes</span>";
    echo "<span class='shop_button seechangesbutton' style='margin-right: 5px;'>See changes</span>";
    echo "<span class='shop_button savechangesonroom' style='background-color:green; margin-right: 5px;'>Save</span>";
    echo "<span class='shop_button' style='background-color:green;'>Save&Pay</span>";
    echo "</span>";
    echo "</div>";
}

$this->includefile("overlayheader");

if($numberOfRooms > 0) {
    echo "<div class='isgroupinformation'>";
    echo "<i class='fa fa-arrow-down'></i> ";
    $listGroupButton= "";
    if(!$this->listGroupRooms()) {
        $listGroupButton = " - <a style='color:blue; cursor:pointer;' gsclick='toggleListGroupRooms' roomId='".$this->getSelectedRoom()->pmsBookingRoomId."'>list group</a>";
    }
   
    echo "This room is part of a group of " . $numberOfRooms . " rooms, <a bookingid='".$pmsBooking->id."' style='color:blue; cursor:pointer;' class='opengroup'>open group</a>$listGroupButton";
    
    echo "<span class='roomindication'>";
    if(sizeof($pmsSelectedRoom->guests) > 0 && $pmsSelectedRoom->guests[0]->name) {
        echo $pmsSelectedRoom->guests[0]->name . " ";
    }
    echo "(" . date("d.m.Y H:i", strtotime($pmsSelectedRoom->date->start)) . " - ";
    echo date("d.m.Y H:i", strtotime($pmsSelectedRoom->date->end)) . ")";
    if($pmsSelectedRoom->bookingItemTypeId) {
        echo " " . $this->getApi()->getBookingEngine()->getBookingItemType($this->getSelectedMultilevelDomainName(), $pmsSelectedRoom->bookingItemTypeId)->name;
    }
    if($pmsSelectedRoom->bookingItemId) {
        echo  " (" . $this->getApi()->getBookingEngine()->getBookingItem($this->getSelectedMultilevelDomainName(), $pmsSelectedRoom->bookingItemId)->bookingItemName . ")";
    }
    echo " <i class='fa fa-arrow-down'></i>";
    
    echo "</span>";
    
    echo "</div>";
}
if($pmsSelectedRoom->addedToWaitingList) {
    echo "<div class='isgroupinformation'>";
    echo "This room is added to the waiting list rooms, <a style='color:blue; cursor:pointer;' gstype='clicksubmit' gsname='id' gsvalue='".$pmsSelectedRoom->pmsBookingRoomId."' method='removeFromWaitingList'>try adding this room.</a>.";
    echo "<span style='float:right; background-color:red; color:#fff; padding-left:5px; padding-right: 5px; cursor:pointer;' gstype='clicksubmit' gsname='id' gsvalue='".$pmsSelectedRoom->pmsBookingRoomId."' method='deleteWaitingListRoom'>Delete from waiting list</span>";
    echo "</div>";
} 

if($pmsSelectedRoom->deleted) {
    echo "<div class='isdeletedinformation'>";
    echo "This room has been cancelled / deleted, <span class='tryundeleteroom' style='color:#be99d7;cursor:pointer;'>try to undelete it</span>.";
    if($pmsSelectedRoom->overbooking) {
        echo "<span gsclick='removeFromOverBookingList' style='float:right; color:#be99d7;cursor:pointer;' gs_confirm='Warning, this will not readd the booking, just remove it from the list, use undelete it to make sure it is readded.'>remove it from overbooking list</span>.";
    }
    echo "</div>";
} 

$totalOrdersOnRoom = $this->getApi()->getPmsInvoiceManager()->getTotalOnOrdersForRoom($this->getSelectedMultilevelDomainName(), $pmsSelectedRoom->pmsBookingRoomId, true);

$totalPaymentsText = "";
if($totalOrdersOnRoom) {
    $diff = $totalOnRoom - $totalOrdersOnRoom;
    $totalPaymentsText = " - " . $totalOrdersOnRoom;
} else {
    $diff = $totalOnRoom;
}
$warningPayments = "";
if($diff < -1 || $diff > 1) {
    $warningPayments = "<span class='fa fa-warning' style='padding:0px;margin:0px; color:red;' title='You have unhandled payments'></span> ";
}
$start = date("d.m.Y", time());
$end = date("d.m.Y", time()+86400);

if($this->listGroupRooms()) {
    echo "<div style='font-size: 20px; line-height:38px; background-color:#241b1b; padding: 10px; color:#fff;'>";
    echo "LISTING ALL ROOMS IN GROUP FOR BOOKING";
    echo "<span class='shop_button' style='float:right;' gsclick='toggleListGroupRooms' roomId='".$this->getSelectedRoom()->pmsBookingRoomId."'>Close group list mode</span>";
    echo "<span class='shop_button addanotherroomtogroup' style='float:right; margin-right: 5px; background-color:green;'  bookingId='".$this->getPmsBooking()->id."'>Add another room</span>";
    ?>
<div class='addanotherroompopup' gstype='form' method='addAnotherRoom'>
     <i class='fa fa-close' style='cursor:pointer; float:right;' onclick='$(".addanotherroompopup").slideUp()'></i>
    Start:
    <input type='txt' gsname='start' class='gsniceinput1' style='width:100%; box-sizing: border-box;' value='<?php echo $start; ?>'>
    End:
    <input type='txt' gsname='end' class='gsniceinput1' style='width:100%; box-sizing: border-box;' value='<?php echo $end; ?>'>
    Category:
    <select class='gsniceselect1' style='width:100%; box-sizing: border-box;' gsname='type'>
        <?php $this->printAvailableRoomsFromCategory($start, $end); ?>
    </select>
    <div>
    Number of rooms:
    </div>
    <input class='gsniceinput1' gsname='count' style='width: 30px; text-align: center;' value='1'>
    <input type='hidden' gsname='bookingid' value='<?php echo $this->getPmsBooking()->id; ?>'>
    <span class='shop_button' gstype='submit' style='float:right;'>Add room(s)</span>
    <script>
        var startinput = $('.PmsBookingRoomView .addanotherroompopup input[gsname="start"]');
        var endinput = $('.PmsBookingRoomView .addanotherroompopup input[gsname="end"]');
        
        startinput.datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
            onSelect: function(dateText) {
                var curEnd = moment(endinput.val(), "DD.MM.YYYY");
                var date = moment(dateText, "DD.MM.YYYY");

                var diff = curEnd.valueOf() - date.valueOf();
                if(diff <= 0) { date.add(1, 'days'); endinput.val(date.format('DD.MM.YYYY')); }
                app.PmsBookingRoomView.updateAddNewRoomDropDown();
            }
        });
        endinput.datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
            onSelect: function(dateText) {
                var curStart = moment(startinput.val(), "DD.MM.YYYY");
                var date = moment(dateText, "DD.MM.YYYY");

                var diff = date.valueOf() - curStart.valueOf();
                if(diff <= 0) { date.add(-1, 'days'); startinput.val(date.format('DD.MM.YYYY')); }
                app.PmsBookingRoomView.updateAddNewRoomDropDown();
            }
        });
    </script>
</div>
    <?php
    echo "</div>";
    
}

?>
<div class='grouppaymentprocess'></div>
<?php
if($this->listGroupRooms()) {
    $this->includefile("grouplist");
} else {
    ?>
    <div gstype='form' method="updateBooking" class="bookingoverview_content_row">
        <input type='hidden' gsname='roomId' value='<? echo $pmsSelectedRoom->pmsBookingRoomId; ?>'/>
        <div class="menuarea" roomId="<? echo $pmsSelectedRoom->pmsBookingRoomId; ?>" bookingEngineId="<? echo $bookingEngineBooking->id; ?>">
            <div class="menuentry <? echo $this->isTabActive('bookinginformation'); ?>" tab='bookinginformation'><i class="fa fa-info"></i> <span><? echo $this->__f("Guests"); ?></span></div>
            <div class="menuentry <? echo $this->isTabActive('stayinformation'); ?>" clearTabContent="true" tab='stayinformation'><i class="fa fa-calendar"></i> <span><? echo $this->__f("Stay") . $stayPrice; ?></span></div>
            <div class="menuentry <? echo $this->isTabActive('addons'); ?>" tab='addons'><i class="fa fa-plus-circle"></i> <span><? echo $this->__f("Addons") . " " . $addonsPriceToDisplay; ?></span></div>
            <div class="menuentry <? echo $this->isTabActive('accesscode'); ?>" tab='accesscode'><i class="fa fa-key"></i> <span><? echo $this->__f("Access code"); ?></span></div>
            <div class="menuentry <? echo $this->isTabActive('accesslog'); ?>" tab='accesslog'><i class="fa fa-key"></i> <span><? echo $this->__f("Access log"); ?></span></div>
            <div class="menuentry <? echo $this->isTabActive('messages'); ?>" tab='messages'><i class="fa fa-envelope"></i> <span><? echo $this->__f("Messages"); ?></span></div>
            <div class="menuentry <? echo $this->isTabActive('cleaning'); ?>" tab='cleaning'><i class="fa gsicon-gs-cleaning"></i> <span><? echo $this->__f("Cleaning"); ?></span></div>
            <div style='display:none;' class="menuentry <? echo $this->isTabActive('orders'); ?>" needAllSaved='true' clearTabContent="true" tab='orderstab'><i class="fa fa-dollar"></i> <span><? echo $this->__f("Payments"); ?></span></div>
            <div style='display:none;' class="menuentry <? echo $this->isTabActive('log'); ?>" clearTabContent="true" tab='log'><i class="fa fa-history"></i> <span><? echo $this->__f("Log"); ?></span></div>
            <div class="menuentry <? echo $this->isTabActive('pga'); ?>" tab='pga'><i class="fa fa-ticket"></i> <span><? echo $this->__f("PGA"); ?></span></div>
            <div class="menuentry <? echo $this->isTabActive('ticket'); ?>" needAllSaved='true' tab='ticket'><i class="fa fa-ticket"></i> <span><? echo $this->__f("Tickets"); ?></span></div>
        </div>

        <div class="workarea">

            <div class="guestinformation <? echo $this->isTabActive('bookinginformation'); ?>" tab='bookinginformation'>
                <?
                $this->includefile("bookinginformation");
                ?>
            </div>

            <div class="guestinformation <? echo $this->isTabActive('addons'); ?>" tab='addons'>
                <?php $this->printArea("addons"); ?>
            </div>

            <div class="guestinformation <? echo $this->isTabActive('accesscode'); ?> accesscode" tab='accesscode'>
                <?php $this->printArea("accesscode"); ?>
            </div>

            <div class="guestinformation <? echo $this->isTabActive('accesslog'); ?> accesslog" tab='accesslog'>
                <?php $this->printArea("accesslog"); ?>
            </div>

            <div class="guestinformation <? echo $this->isTabActive('messages'); ?>" tab='messages'>
                <?php $this->printArea("messages"); ?>
            </div>

            <div class="guestinformation <? echo $this->isTabActive('cleaning'); ?>" tab='cleaning'>
                <?php $this->printArea("cleaning"); ?>
            </div>

            <div class="guestinformation <? echo $this->isTabActive('orderstab'); ?>" tab='orderstab'>
                <?php $this->printArea("orderstab"); ?>
            </div>

            <div class="guestinformation <? echo $this->isTabActive('ticket'); ?>" tab='ticket'>
                <?php $this->printArea("ticket"); ?>
            </div>
            
            <div class="guestinformation <? echo $this->isTabActive('pga'); ?>" tab='pga'>
                <?php $this->printArea("pga"); ?>
            </div>

            <div class="guestinformation <? echo $this->isTabActive('log'); ?>" tab='log'>
                <?
                if ($_SESSION['currentSubMenu'] == "log") {
                    $this->printArea("log");
                }
                ?>
            </div>

            <div class="stayinformation PmsAvailability <? echo $this->isTabActive('stayinformation'); ?>" tab='stayinformation'>
                <?php $this->printArea("stayinformation"); ?>
            </div>
        </div>
        <div style='clear:both;'></div>
    </div>
    <?php
}
$isgroup = "no";
if(sizeof($pmsBooking->rooms) > 1) {
    $isgroup = "yes";
}

$totalOnRoom = $pmsSelectedRoom->totalCost;
$totalOrdersRoom = $this->getApi()->getPmsInvoiceManager()->getTotalOnOrdersForRoom($this->getSelectedMultilevelDomainName(), $pmsSelectedRoom->pmsBookingRoomId, true);
$unsettledRoom = $totalOnRoom - $totalOrdersRoom;
if($unsettledRoom > 1 || $unsettledRoom < -1) {

}

if(isset($pmsSelectedRoom->hasBeenUpdated) && $pmsSelectedRoom->hasBeenUpdated) {
    $changes = $this->getDifferenceInRoom();
    echo "<div class='changespanel'></div>";
    echo "<div class='unsavedchangeswarning'><i class='fa fa-info-circle'></i> You have unsaved changes for this room (".$changes['totalchanges'].").";
    echo "<span style='position:absolute; right:5px; top: 5px;'>";
    echo "<span class='shop_button' style='margin-right: 5px;background-color:red;' gstype='clicksubmit' gsname='id' gsvalue='123' method='discardChanges'><i class='fa fa-trash-o'></i> Discard changes</span>";
    echo "<span class='shop_button seechangesbutton' style='margin-right: 5px;'>See changes</span>";
    echo "<span class='shop_button savechangesonroom' style='background-color:green; margin-right: 5px;'>Save</span>";
    echo "<span class='shop_button' style='background-color:green;'>Save&Pay</span>";
    echo "</span>";
    echo "</div>";
}

if($warningPayments) {
    ?>
<script>
    if(typeof(warnaboutnopaymentsflashinterval) !== "undefined") {
        clearInterval(warnaboutnopaymentsflashinterval);
    }
    
    $('.addanotherroomtogroup').on('click', function() {
        $('.addanotherroompopup').slideDown();
    });
</script>
<?php
}
?>
<style>
    .addanotherroompopup { 
        position:absolute;
        right: 10px; 
        border: solid 1px; 
        background-color: #fff; 
        color:#000; 
        display:inline-block; 
        width: 200px; 
        font-size: 12px;    
        padding: 10px;
        display:none;
    }
</style>
