<?
/* @var $this ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */

$pmsBooking = $this->getPmsBooking();
$pmsSelectedRoom = $this->getSelectedRoom();
$comments = (array) $pmsBooking->comments;

$found = array();
foreach($comments as $idx => $cmt) {
    if($cmt->pmsBookingRoomId == $pmsSelectedRoom->pmsBookingRoomId) {
        $found[$idx] = $cmt;
        unset($comments[$idx]);
    }
}


krsort($comments);
krsort($found);


foreach($comments as $idx => $cmnt) {
    $found[$idx] = $cmnt;
}
$comments = $found;

foreach ($comments as $time => $comment) {
    $allStyle = "";
    if($comment->pmsBookingRoomId == $pmsSelectedRoom->pmsBookingRoomId) {
        $allStyle = "font-style: oblique;background-color:#91d7e2; ";
    }
    echo "<div style='vertical-align: top; border-bottom: solid 1px #DDD; padding: 3px; $allStyle' class='commentrow'>";

        $style = "";
        if ($comment->deleted) {
            $style = "text-decoration: line-through;";
        }
        echo "<div style='display: inline-block; vertical-align: top; width:215px; color:#777;$style'>";
            echo "<i class='fa fa-trash-o deletecomment' time='$time' style='cursor:pointer;'></i> ";
            echo "<i class='fa fa-edit' style='cursor:pointer;' onclick='$(\".savechangestocommentbtn\").fadeIn();$(\".contenttoedit\").focus();'></i> ";
            echo date("d.m.Y H:i", strtotime($comment->added));
        echo "</div>";

        echo "<div style='display: inline-block; margin-left: 20px;    width: calc(100% - 250px); $style' contenteditable='true' class='contenttoedit'>";
            echo nl2br($comment->comment);
        echo "</div>";
        foreach($comment->modifiedByUser as $time => $userId) {
            $user = $this->getApi()->getUserManager()->getUserById($userId);
            echo "<div style='color:#bbb; text-align:right; font-size:10px;'>Modified by " . $user->fullName . " at " . date("d.m.Y H:i", $time/1000) . "</div>";
        }
        echo "<div style='text-align:right;margin-top:10px;'><span class='shop_button savechangestocommentbtn' commentid='".$comment->commentId."' style='display:none;'>Save changes</span></div>";

        if ($comment->userId) {
            $commentUser = $this->getApi()->getUserManager()->getUserById($comment->userId);
            echo "<span style='float:right; color:#777;$style '>" . $commentUser->fullName . "</span>";
        }
    
    echo "</div>";
}
?>
