<?php
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$type = $_POST['data']['type'];
$roomId = $_POST['data']['roomid'];
$booking = $this->getApi()->getPmsManager()->getBookingFromRoom($this->getSelectedMultilevelDomainName(), $roomId);
$currentRoom = null;
 foreach($booking->rooms as $room) {
    if($room->pmsBookingRoomId == $roomId) {
        $currentRoom = $room;
    }
}
switch($type) {
    case "changeroom": 
        $roomId = $currentRoom->pmsBookingRoomId;
        $bookingId = $booking->id;
        $itemId = $_POST['data']['newroomid'];
        $this->getApi()->getPmsManager()->setBookingItem($this->getSelectedMultilevelDomainName(), $roomId, $bookingId, $itemId, false);
        break;
    case "delete":
        $this->getApi()->getPmsManager()->removeFromBooking($this->getSelectedMultilevelDomainName(), $booking->id, $roomId);
        break;
    case "changeprice":
        $room = $this->doUpdatePriceMatrixWithPeriodePrice($currentRoom);
        $this->getApi()->getPmsManager()->saveBooking($this->getSelectedMultilevelDomainName(), $booking);
        break;
    case "updateaddons":
        $products = array();
        foreach($currentRoom->addons as $addon) {
            $products[$addon->productId] = "1";
        }

        foreach($products as $prodId => $val) {
            if($_POST['data']['productid_'.$prodId] == "true") {
                $this->getApi()->getPmsManager()->removeProductFromRoom($this->getSelectedMultilevelDomainName(), $roomId, $prodId);
            }
        }
        break;
    case "changestay":
        $start = $this->convertToJavaDate(strtotime($_POST['data']['start'] . " " . $_POST['data']['starttime']));
        $end = $this->convertToJavaDate(strtotime($_POST['data']['end'] . " " . $_POST['data']['endtime']));
        $this->getApi()->getPmsManager()->changeDates($this->getSelectedMultilevelDomainName(), $roomId, $booking->id, $start, $end);
        break;
    case "guestinfo":
        $guests = array();
        $numberOfGuests = $_POST['data']['numberofguests'];
        for($i = 0; $i < 30; $i++) {
            if($i >= $numberOfGuests) {
                break;
            }
            $guestId = $_POST['data']['guestid_'.$i];
            $name = $_POST['data']['name_'.$i];
            $email = $_POST['data']['email_'.$i];
            $prefix = $_POST['data']['prefix_'.$i];
            $phone = $_POST['data']['phone_'.$i];
            
            $guestInfo = new core_pmsmanager_PmsGuests();
            $guestInfo->email = $email;
            $guestInfo->phone = $phone;
            $guestInfo->prefix = $prefix;
            $guestInfo->name = $name;
            $guests[] = $guestInfo;
        }
        $currentRoom->guests = $guests;
        $this->getApi()->getPmsManager()->setGuestOnRoom($this->getSelectedMultilevelDomainName(), $guests, $booking->id, $currentRoom->pmsBookingRoomId);
        break;
}

?>