<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$savedRoom = $this->getSelectedRoom();
$room = $this->getTmpSelectedRoom($savedRoom->pmsBookingRoomId);
$hasAcessControl = $this->getApi()->getPmsManager()->hasLockSystemActive($this->getSelectedMultilevelDomainName());

$types = $this->getTypes();
$items = $this->getItems();

$selectedType = $this->getSelectedTypeForRoom();
$selectedItem = $this->getSelectedItemForRoom();

$warnAboutUnchanges = "";

$startDate = strtotime($room->date->start);
$endDate = strtotime($room->date->end);

$validSelection = $this->isValidSelection($room);

if(!isset($room->tmpModified) || !$validSelection) {
    $warnAboutUnchanges = "display:none;";
}
?>

<div style="border: solid 1px; text-align: right;background-color:red; color:#fff;<?php echo $warnAboutUnchanges; ?>" class="warningchangesonroom"><span style='float:left; margin-top: 8px;margin-left:8px;'>You have modified this room and need to save it to be completed</span> <span class="shop_button savetmproom" roomid='<?php echo $room->pmsBookingRoomId; ?>'>save changes on room</span></div>
<div class="outerstay">
    <div class='itemview_inner stayperiodecontainer'>
        <h2>Stay periode</h2>
        Check-in<br>
        <input type="textfield" class="gsniceinput1 startdate" gsname="start" value="<? echo date("d.m.Y", $startDate); ?>"/>
        <input type="textfield" class="gsniceinput1 starttime time starttime" gsname="startTime" value="<? echo date("H:i", $startDate); ?>"/><br><br>
        Check-out<br>
        <input type="textfield" class="gsniceinput1 enddate" gsname="end" value="<? echo date("d.m.Y", $endDate); ?>"/> 

        <input type="textfield" class="gsniceinput1 endtime time endtime" gsname="endTime" value="<? echo date("H:i", $endDate); ?>"/> 
        <span class='shop_button setnewdates' style='width:100%;margin-top:5px;box-sizing: border-box;'>Change dates</span>
        <?php
        if(!$hasAcessControl) {
            if($this->startingToday($room) && !$room->checkedin) {
                echo "<span class='shop_button checkinguest' style='width:100%; margin-top: 5px;box-sizing:border-box; background-color:green;'>Check in guest</span>";
            }
            if($room->checkedin && !$room->checkedout) {
                echo "<span class='shop_button checkoutguest' style='width:100%; margin-top: 5px;box-sizing:border-box; background-color:blue;'>Check out guest</span>";
            }
        }
        ?>
    </div>

    <div class='itemview_inner roomandcats'>
        <h2>Room and categories</h2>

        <?
        echo $this->__f("Selected category").": ".$selectedType->name;
        echo "<br>".$this->__f("Selected room").": ";
        if ($selectedItem) {
            echo $selectedItem->bookingItemName;
            $isClean = $this->getApi()->getPmsManager()->isClean($this->getSelectedMultilevelDomainName(), $selectedItem->id);
            if($isClean) {
                echo "<div>Room is clean</div>";
            } else {
                echo "<div>Room is <b>not</b> clean</div>";
            }
        } else {
            echo $this->__f("Floating");
        }
        if(!$validSelection) {
            echo "<div class='notvalidselection'>This room selection is not valid.</div>";
        }

        ?>
        <?
    //    $this->includefile("availablerooms")
        ?>
        <br/>
        <br/>
        <div class="shop_button showroomstoselect"><? echo $this->__f("Change room or category"); ?></div>
    </div>

    <div class='itemview_inner pricesview'>
        <? $this->includefile("prices"); ?>
    </div>
</div>
<div class="itemview_inner roomstoselect" style="display: none;"></div>
<div style="border: solid 1px; text-align: right;background-color:red; color:#fff; <?php echo $warnAboutUnchanges; ?>" class="warningchangesonroom"><span style='float:left; margin-top: 8px;margin-left:8px;'>You have modified this room and need to save it to be completed</span> <span class="shop_button savetmproom" roomid='<?php echo $room->pmsBookingRoomId; ?>'>save changes on room</span></div>
