<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$room = $this->getSelectedRoom();
$types = $this->getTypes();
$items = $this->getItems();

$startDate = $this->convertToJavaDate(strtotime($room->date->start));
$endDate = $this->convertToJavaDate(strtotime($room->date->end));

$isSameDayStart = date('Y-m-d', strtotime($startDate)) == date('Y-m-d', time());

$availableItems = $this->getApi()->getBookingEngine()->getAllAvailbleItemsWithBookingConsidered($this->getSelectedMultilevelDomainName(), $startDate, $endDate, $room->bookingId);

$cleanIcon = "";

function canUseItem($item, $availeableitems) {
    foreach ($availeableitems as $available) {
        if ($available->id == $item->id) {
            return true;
        }
    }
    
    return false;
}
?>
<div class='itemview_inner'>
    <div class='updater'>
        <i class='fa fa-spin fa-spinner'></i> Updating.. please wait..
    </div>
    <div gstype="select" gsname="itemid"><?
        foreach ($types as $type) {
            $useClass = "canNotUse";
            
            $canUseFloating = "canNotUse";
            
            $currentlyUsingFloating = !$room->bookingItemId  && $room->bookingItemTypeId == $type->id ? "gs_selected" : "";
            foreach ($items as $item) {
                if ($item->bookingItemTypeId != $type->id) {
                    continue;
                }

                if (canUseItem($item, $availableItems)) {
                    $canUseFloating = "canUse";
                }
            }
        ?>
            <div class='movetotype' typeid='<? echo $type->id; ?>'>
                <div class="headername">
                    <? echo $type->name; ?>
                    <br/><div class='bookingitem floatingbutton <? echo $canUseFloating." ".$currentlyUsingFloating; ?>' gs_value='<? echo $type->id; ?>' itemId=""><? echo $this->__f("Floating"); ?></div>
                </div>
                <div class="itemselector">
                    <?
                    
                    foreach ($items as $item) {
                        if ($item->bookingItemTypeId != $type->id) {
                            continue;
                        }

                        if (canUseItem($item, $availableItems)) {
                            $useClass = "canUse";
                        }
                    }

                    $currentlyUsing = !$room->bookingItemId  && $room->bookingItemTypeId == $type->id ? "gs_selected" : "";
                    foreach ($items as $item) {

                        if ($item->bookingItemTypeId != $type->id) {
                            continue;
                        }
                        
                        if ($isSameDayStart) {
                            $cleanText = $this->__f("This room is clean");
                            $cleanIcon = $this->getApi()->getPmsManager()->isClean($this->getSelectedMultilevelDomainName(), $item->id) ? "<i title='$cleanText' class='icon-gs-cleaning'></i> " : "";
                        }
                        $currentlyUsing = $item->id == $room->bookingItemId ? "gs_selected" : "";
                        $useClass = canUseItem($item, $availableItems) ? "canUse" : "canNotUse";
                        echo "<div class='bookingitem $useClass $currentlyUsing' gs_value='".$type->id."_".$item->id."' itemId='".$item->id."'>$cleanIcon".$item->bookingItemName."</div>";
                    }
                    ?>
                </div>
            </div>
        <?
        }
        ?>
    </div>
</div>

<div class='pricesview'>
    <? $this->includefile("prices"); ?>
</div>