<?php
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$this->setData();
$room = $this->getSelectedRoom();
$guests = $room->guests;
$booking = $this->getPmsBooking();
$user = $this->getApi()->getUserManager()->getUserById($booking->userId);
?>

<br>
<div class="isnotactive">
    <div class="kaipal infobox">
        <div class="image talking"></div>
        <div class="textbox">
            <div class="text">
                <?
                echo $this->__f("Do you want me to inform the guests about something? Check the guest you would like to send a message to, enter the message you want me to send and press send as sms / email or both.");
                ?>    
            </div>
        </div>
    </div>
</div>


<table>
    <tr>
        <td width='50%' valign='top'>
            <div gstype='form' method='sendMessage'>
                <?php
                echo "<h3>Select the guests you want to send a message to</h3>";
                $idx = 0;
                foreach($guests as $guest) {
                    $checked = ($idx == 0) ? "checked" : "";
                    echo "<div>";
                    echo "<input type='checkbox' gsname='sendtoguest_$idx' $checked>";
                    echo "<input type='hidden' class='gsniceinput1' gsname='guestid_$idx' value='" . $guest->guestId ."' style='width:20px;'>";
                    echo "<input type='text' class='gsniceinput1' gsname='prefix_$idx' value='" . $guest->prefix ."' style='width:20px;'>";
                    echo "<input type='text' class='gsniceinput1' gsname='phone_$idx' value='" . $guest->phone ."'>";
                    echo "<input type='text' class='gsniceinput1' gsname='email_$idx' value='" . $guest->email ."' style='width: 300px;'>";
                    echo "</div>";
                    $idx++;
                }
                echo "<h3>Message</h3>";
                ?>
                <textarea class='sendmessagetext' gsname='message'></textarea><br>

                <span class="shop_button" gstype='submit' gsvalue='sendassms'>Send as sms</span>
                <span class="shop_button" gstype='submit' gsvalue='sendasemail'>Send as email</span>
                <span class="shop_button" gstype='submit' gsvalue='sendasboth'>Send as both</span>
            </div>
        </td>
        <td width='50%' valign='top' class='otheroptionstd'>
            <h3>Other options</h3>
            <div gstype='form' method='resendConfirmation'>
                <input type='text' class='gsniceinput1' style='width:300px;' value='<?php echo $user->emailAddress; ?>' gsname='email'><span class='shop_button' gstype='submit'>Send confirmation</span>
            </div>
        </td>
    </tr>
</table>
<br>
<br>
<h3>Message log</h3>
<?php
$logs = $this->getSelectedRoomLog();
$this->setLogEntries($logs);
$this->includefile("logentries");

?>