<?
if ($this->shouldUseNewPaymentWindow()) {
    $this->includefile("orderstab_new");
    return;
}
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$methods = (array)$this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
$hasPaymentMethods = false;
if(sizeof($methods) > 0) {
    $hasPaymentMethods = true;
}

$pmsBooking = $this->getPmsBooking();
$pmsSelectedRoom = $this->getSelectedRoom();
$booking = $this->getBookingEngineBooking();
$user = $this->getUserForBooking();
$showCredittedHistory = isset($_SESSION['ns_f8cc5247_85bf_4504_b4f3_b39937bd9955_showcredittedhistory']) && $_SESSION['ns_f8cc5247_85bf_4504_b4f3_b39937bd9955_showcredittedhistory'];
$showAllOrders = isset($_SESSION['ns_f8cc5247_85bf_4504_b4f3_b39937bd9955_showallorders']) && $_SESSION['ns_f8cc5247_85bf_4504_b4f3_b39937bd9955_showallorders'];

$totalOnRoom = $pmsSelectedRoom->totalCost;
$totalOrdersRoom = $this->getApi()->getPmsInvoiceManager()->getTotalOnOrdersForRoom($this->getSelectedMultilevelDomainName(), $pmsSelectedRoom->pmsBookingRoomId, true);
$unsettledRoom = $totalOnRoom - $totalOrdersRoom;

$totalOnBooking = $pmsBooking->totalPrice;
$totalMissingOnGroup = 0.0;
$totalOrdersOnGroup = 0.0;
foreach($pmsBooking->orderIds as $ordId) {
    $order = $this->getApi()->getOrderManager()->getOrder($ordId);
    $totalOrdersOnGroup += $this->getApi()->getOrderManager()->getTotalAmount($order);
}
$totalMissingOnGroup = $pmsBooking->totalPrice - $totalOrdersOnGroup;


if(isset($pmsSelectedRoom->hasBeenUpdated) && $pmsSelectedRoom->hasBeenUpdated) {
    ?>
    <div class="kaipal infobox">
        <div class="image sad"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("Unsaved changes"); ?></div>
            <div class="text">
                <?
                echo $this->__f("Before you can start handling payments you will have to save all the changes done first. Please save the payments by pressing the button above.");
                ?>    
            </div>
        </div>
    </div>
    <?
    return;
}

?>

<div class="topbuttons">
    <?
    $this->includefile("orderstabsimple");
    ?>
</div>
<script>
    app.PmsBookingRoomView.activateSelectedTabSubOrders('<? echo $pmsSelectedRoom->pmsBookingRoomId; ?>');
</script>
<?php if($hasPaymentMethods) { ?>
<div class='insideheader'><? echo $this->__f("Payment history"); ?> 
    <span class="showcredithistorybutton" gsclick='toggleCreditHistory'>
        <?
        if ($showCredittedHistory) {
            echo $this->__f("Hide credit history");
        } else {
            echo $this->__f("Show credit history");
        }
        ?>
    </span>
</div>
    <?
    if (!count($this->pmsBooking->orderIds)) {
        echo "No orders has been created yet, create an order by pressing the Start payment process button.";
    } else {
        $this->printOrderList();
    }
} else {
    $this->includefile("nopaymentmethodsyet");
}

$verifonePaymentInProgress = $this->getApi()->getVerifoneManager()->isPaymentInProgress();
if ($verifonePaymentInProgress) {
    echo '<div class="verifonestatus">';
    $this->includefile("verifonepaymentprocess");
    echo '</div>';
}
$paymentCardInProgress = $this->getApi()->getOrderManager()->isPaymentInProgress();
if ($paymentCardInProgress) {
    echo '<div class="verifonestatus">';
    $this->includefile("integratedpaymentprocess");
    echo '</div>';
}
?>
    
<style>
    .pricetext { display:inline-block; width: 130px; }
    .pricetag { display:inline-block; width: 80px; }
</style>

<?
if ($this->canTestNewRoutine()) {
?>
    <div class="information" style="border: solid 1px #DDD; padding: 10px; background-color: #feffc1; text-align: center">
        A new version of this process is under development (beta version), you can test it if you wish.
        <div class="gs_shop_small_icon" gsclick="switchToNewPaymentWindow">Show new version</div>
    </div>
<?
}
?>