<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$room = $this->getSelectedRoom();
$pmsBooking = $this->getPmsBooking();
$extraOrders = $this->getApi()->getPmsManager()->getExtraOrderIds($this->getSelectedMultilevelDomainName(), $pmsBooking->id);
$bookingItemType = $this->getApi()->getBookingEngine()->getBookingItemType($this->getSelectedMultilevelDomainName(), $room->bookingItemTypeId);
$bookingItemTypes = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName());

$productIdsForAllRoomsOfSameType = array();
foreach ($bookingItemTypes as $type) {
    $productIdsForAllRoomsOfSameType[] = $type->productId;
}

$orders = array();
?>
<div class="information" style="border: solid 1px #DDD; padding: 10px; background-color: #feffc1; text-align: center">
    This version is in early developement phase, its just for preview but we will be doing lots of developement on this during the upcoming days.
    <div class="gs_shop_small_icon" gsclick="switchToOldVersion">Go back to old version</div>
</div>
<?
foreach ($pmsBooking->orderIds as $orderId) {
    $orders[] = $this->getApi()->getOrderManager()->getOrder($orderId);
}

foreach ($extraOrders as $orderId) {
    $orders[] = $this->getApi()->getOrderManager()->getOrder($orderId);
}

/**
 * 
 * @param \core_ordermanager_data_Order[] $orders
 * @param type $date
 * @param \core_pmsmanager_PmsBookingRooms $room
 */
function getAmountPaidForRoom($orders, $date, $room, $productIds) {
    $total = 0;
    
    foreach ($orders as $order) {
        foreach ($order->cart->items as $item) {
            $product = $item->product;
            if (count($item->priceMatrix) && in_array($product->id, $productIds) && $product->externalReferenceId == $room->pmsBookingRoomId) {
                $total += $item->priceMatrix->{$date};
            }
            
            if (count($item->itemsAdded)) {
                foreach ($item->itemsAdded as $addonItem) {
                    $addonDate = date('d-m-Y', strtotime($addonItem->date));
                    if (in_array($addonItem->productId, $productIds) && $date == $addonDate) {
                        $total += $addonItem->count * $addonItem->price;
                    }
                }
            }
        }
    }
    
    return $total;
}

/**
 * 
 * @param \core_pmsmanager_PmsBookingRooms $room
 * @param type $date
 */
function getAddonsIncludedInRoomPriceAddons($room, $date) {
//    echo $date;
    $addonPrice = 0;
    foreach ($room->addons as $addon) {
        $addonDate = date('d-m-Y', strtotime($addon->date));
        if ($addonDate == $date && $addon->isIncludedInRoomPrice) {
            $addonPrice += ($addon->price * $addon->count);
        }
    }
    
    return $addonPrice;
}

function printRow($date, $totalForRoom, $amountPaidForRoomOnDate, $remaining, $product) {
        $allOk = $remaining == 0;
        $status = $allOk ? "<i class='fa fa-check'></i>" : "<i class='fa fa-close'></i>";
    ?>
        <div class="row <? echo $allOk ? 'allok' : 'notok'; ?> row_payment_status_line ">
            <div class="col col_status"><? echo $status; ?></div>
            <div class="col col_date"><? echo $date; ?></div>
            <div class="col col_product"><? echo $product->name; ?></div>
            <div class="col col_value"><? echo $totalForRoom; ?></div>
            <div class="col col_paid"><? echo $amountPaidForRoomOnDate; ?></div>
            <div class="col col_remaining"><? echo $remaining; ?></div>
        </div>
    <?
}

?>

<h2>Payment summary for <? echo $room->guests[0]->name; ?></h2>

<div style="width: calc(100% - 254px); display:inline-block; vertical-align: top; border: solid 1px #DDD; box-sizing: border-box; margin-bottom: 20px;">

    
    <div class="row row_payment_status_line header">
        <div class="col col_status"></div>
        <div class="col col_date"><? echo $this->__f("Date"); ?></div>
        <div class="col col_product"><? echo $this->__f("Product"); ?></div>
        <div class="col col_value"><? echo $this->__f("Price in booking"); ?></div>
        <div class="col col_paid"><? echo $this->__f("Created for in orders"); ?></div>
        <div class="col col_remaining"><? echo $this->__f("Guest owe you"); ?></div>
    </div>
    <?
    $totalRemaining = 0;
    foreach ($room->priceMatrix as $date => $totalForRoom) {
        $totalForRoom -= getAddonsIncludedInRoomPriceAddons($room, $date);
        $amountPaidForRoomOnDate = getAmountPaidForRoom($orders, $date, $room, $productIdsForAllRoomsOfSameType);
        $remaining = $amountPaidForRoomOnDate - $totalForRoom;
        $remaining = $remaining != 0 ? $remaining * -1 : $remaining;
        $product = $this->getApi()->getProductManager()->getProduct($bookingItemType->productId);
        $totalRemaining += $remaining;
        printRow($date, $totalForRoom, $amountPaidForRoomOnDate, $remaining, $product);
    }

    foreach ($room->addons as $addon) {
        $totalForRoom = ($addon->count * $addon->price);
        $addonDate = date('d-m-Y', strtotime($addon->date));
        $productIds = array($addon->productId);
        $amountPaidForRoomOnDate = getAmountPaidForRoom($orders, $addonDate, $room, $productIds);
        $remaining = $amountPaidForRoomOnDate - $totalForRoom;
        $remaining = $remaining != 0 ? $remaining * -1 : $remaining;
        $allOk = $remaining == 0;
        $status = $allOk ? "<i class='fa fa-check'></i>" : "<i class='fa fa-close'></i>";
        $product = $this->getApi()->getProductManager()->getProduct($addon->productId);
        $totalRemaining += $remaining;
        printRow($addonDate, $totalForRoom, $amountPaidForRoomOnDate, $remaining, $product);
    }
    ?>
    <div class="row row_payment_status_line header">
        <div class="col col_status"></div>
        <div class="col col_date"></div>
        <div class="col col_product"><? echo $this->__f("Total remaing"); ?></div>
        <div class="col col_value"></div>
        <div class="col col_paid"></div>
        <div class="col col_remaining"><? echo $totalRemaining; ?></div>
    </div>
    <?

?>

</div>
<div style="display: inline-block; width: 250px; display:inline-block; vertical-align: top; border: solid 1px #DDD;  box-sizing: border-box;" >
    <div style="background-color: #EDEDED; font-size: 16px; text-align: center; padding: 5px;">
        <? echo $this->__f("Payments"); ?>
    </div>
    <div class="row row_payment_status_line header">
        <div class="col col_status"> </div>
        <div class="col col_orderid"> Order id</div>
        <div class="col col_amount"> Amount </div>
    </div>
    <?
    foreach ($orders as $order) {
        $totalForOrder = $this->getApi()->getOrderManager()->getTotalForOrderById($order->id);
        ?>
        <div class="row row_payment_status_line ">
            <div class="col col_status"> <? echo $order->status == 7 ? "<i class='fa fa-check'></i>" : "<i style='color: red;' class='gsicon-bag-dollar'></i>"; ?> </div>
            <div class="col col_orderid"> <? echo $order->incrementOrderId; ?> </div>
            <div class="col col_amount"> <? echo $totalForOrder; ?></div>
            <div class="col col_action">
                <div class="gs_shop_small_icon fa fa-gear">
                    
                </div>
            </div>
        </div>
        <?
        
    }
    ?>
</div>