<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$pmsBooking = $this->getPmsBooking();
$pmsSelectedRoom = $this->getSelectedRoom();
$booking = $this->getBookingEngineBooking();

$user = $this->getUserForBooking();
$paymentApps = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();

$options = new stdClass();
$options->cellphone = $user->cellPhone;
$options->prefix = $user->prefix;
$options->message = $this->getApi()->getPmsManager()->getMessage($this->getSelectedMultilevelDomainName(), $pmsBooking->id, "booking_sendpaymentlink");
$options->canCreateOrderAfterStay = true;
$options->postMethod = "doPaymentNormal";
$options->gscallback = "app.PmsSearchBooking.toggleTabClicked";
$options->guestEmail = $user->emailAddress;
$options->invoicenote = $pmsBooking->invoiceNote;

$options->extraArgs = array();
$options->extraArgs['roomid'] = $pmsSelectedRoom->pmsBookingRoomId;
$options->extraArgs['id'] = $booking->id;
?>

<div class="topbuttons">
    <div class="gs_shop_small_icon toggleComment" title="<? echo $this->__f("Payment comment"); ?>"><i class="icon-bubble-pencil"></i></div>
    
    <div class="paymentcomment">
        <?
        echo $this->__f("Invoice note").":";
        ?>
        <textarea><? echo $pmsBooking->invoiceNote; ?></textarea>
        <div>
            <div class="shop_button toggleComment"><? echo $this->__f("close"); ?></div>
            <div class="shop_button saveInvoiceNote"><? echo $this->__f("Save"); ?></div>
        </div>
    </div>
</div>

<div class="isnotactive">
    <div class="kaipal infobox">
        // faces: happy,sad,talking,danger
        <div class="image happy"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("Payment"); ?></div>
            <div class="text">
                <?
                echo $this->__f("I am constantly looking out for you. Each time you change something that got to do with prices in the booking itself I will automatically recalculate for you what you havent claimed money for. Simply put, everything you see under in list the \"Need to by paid\" is all that you have not yet created orders for. When you create a new order the remaining part of what the guest owns you will still be under the list need to be paid.");
                ?>    
            </div>
        </div>
    </div>
</div>

<div class='insideheader'><? echo $this->__f("Need to be paid"); ?></div>
<?
$showingPaymentProcess = $this->startPaymentProcess();

if ($showingPaymentProcess) {
?>
<div class='booking_cart_buttons_area'>
    <div class='shop_button addselecteditemstocart'><? echo $this->__f("Add selected items to cart"); ?></div>
</div>
    
<?
}
?>

<div class='insideheader'><? echo $this->__f("Payment history"); ?></div>
<?
if (!count($this->pmsBooking->orderIds)) {
    ?>
    <div class="nopaymentscreatedyet payment_window">  
        <i class="fa fa-frown-o"></i> <? echo $this->__f("There are no payment created yet, create one by using the options above."); ?>
    </div>
    <?
} else {
    echo "<div class='payment_window'>";
    $i = 0;
    foreach ($this->pmsBooking->orderIds as $orderId) {
        $i++;
        $orderPrinter = new ns_f22e70e7_7c31_4c83_a8c1_20ae882853a7\OrderSimplePrinter();
        $orderPrinter->setOrderId($orderId);
        if (count($this->pmsBooking->orderIds) == $i) {
            $orderPrinter->setLastOrderInTable();
        }
        $orderPrinter->renderApplication(true);
    }
    echo "</div>";
}
?>
