
<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$pmsBooking = $this->getPmsBooking();
$pmsSelectedRoom = $this->getSelectedRoom();
$booking = $this->getBookingEngineBooking();

$user = $this->getUserForBooking();

if(isset($pmsSelectedRoom->hasBeenUpdated) && $pmsSelectedRoom->hasBeenUpdated) {
    ?>
    <div class="kaipal infobox">
        <div class="image sad"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("Unsaved changes"); ?></div>
            <div class="text">
                <?
                echo $this->__f("Before you can start handling payments you will have to save all the changes done first. Please save the payments by pressing the button above.");
                ?>    
            </div>
        </div>
    </div>
    <?
    return;
}

?>

<div class="topbuttons">
    <div class="tabcontent" orders_sub_tab="simple">
        <?
        $this->includefile("orderstabsimple");
        ?>
    </div>
    
    <div class="tabcontent active" orders_sub_tab="advanced">
        <? 
        $this->includefile("orderstabsimple");
        ?>
    </div>
    
    <script>
        app.PmsBookingRoomView.activateSelectedTabSubOrders('<? echo $pmsSelectedRoom->pmsBookingRoomId; ?>');
    </script>
</div>


<div class='insideheader'><? echo $this->__f("Payment history"); ?></div>
<?
if (!count($this->pmsBooking->orderIds)) {
    ?>
    <div class="nopaymentscreatedyet payment_window">  
        <? echo $this->__f("There are no payment created yet, create one by using the options above."); ?>
    </div>
    <?
} else {
    $this->printOrderList();
}
?>
