<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$pmsBooking = $this->getPmsBooking();
$pmsSelectedRoom = $this->getSelectedRoom();
$booking = $this->getBookingEngineBooking();

$user = $this->getUserForBooking();
$noGuests = !$user;
$cellPhone = "";
if ($user->cellPhone) {
    $cellPhone = "+".$user->prefix." ".$user->cellPhone;
}
$email = $user->emailAddress;
$deleted = $pmsSelectedRoom->deleted;

$dateForPaymentlinkToBeSent = $this->getApi()->getPmsInvoiceManager()->getPaymentLinkSendingDate($this->getSelectedMultilevelDomainName(), $pmsSelectedRoom->pmsBookingRoomId);
$canCreateOrders = true;
$itemsUnpaid = (array)$this->getApi()->getPmsInvoiceManager()->getAllUnpaidItemsForRoom($this->getSelectedMultilevelDomainName(), $pmsSelectedRoom->pmsBookingRoomId);
$unsettled = 0.0;
$roomPaid = false;
foreach($itemsUnpaid as $tmp) {
    if(!$tmp->orderId) {
        $unsettled += ($tmp->count * $tmp->product->price);
    }
}
?>

<div>
    <?
    if ($unsettled > 0) {
//        echo $this->showKaiPalSimple("You need to create an order of total $unsettled to recieve the payment for this guest, click on the handle payments button to start creating an order.", $canCreateOrders, false);
    } else if ($roomPaid) {
//        echo $this->showKaiPalSimple("Everything is already paid for.", $canCreateOrders, false);
    } else if ($noGuests) {
//        echo $this->showKaiPalSimple("There is no information about the booker, so I will not send any payment requests.", $canCreateOrders, false);
    } else if (!$cellPhone && !$email) {
//        echo $this->showKaiPalSimple("I am missing email and cellphone, so I can not send any payment requests.", $canCreateOrders, false);
    } else if ($cellPhone && !$email) {
//        echo $this->showKaiPalSimple("Payment link will be sent to $cellPhone at $dateForPaymentlinkToBeSent", $canCreateOrders, true);
    } else if (!$cellPhone && $email) {
//        echo $this->showKaiPalSimple("Payment link will be sent by sms to $cellPhone $dateForPaymentlinkToBeSent", $canCreateOrders, true);
    }  else if ($deleted) {
//        $this->showKaiPalSimple("This room has been deleted, so I will not send out any payment requests.", $canCreateOrders, false);
    }  else if ($cellPhone && $email) {
//        $this->showKaiPalSimple("Payment request will be sent by sms to $cellPhone and by email to $email on the $dateForPaymentlinkToBeSent", $canCreateOrders, true);        
    }
    ?>
</div>