<?php
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$pmsBooking = $this->getPmsBooking();
$pmsBookingRoom = $this->getSelectedRoom();

$isgroup = "no";
if (sizeof($pmsBooking->rooms) > 1) {
    $isgroup = "yes";
}

if(!$pmsBooking->confirmed) {
    echo "<div style='text-align:center; color:#fff; background-color:red;padding: 10px;'>This booking has not been confirmed, <span gsclick='confirmbooking' style='cursor:pointer;'>confirm.</span></div>";
}

$missingOnGroup = 0;
foreach($pmsBooking->rooms as $room) {
    $missingOnGroup += $room->unpaidAmount;
}

?>

<div class='headerboxes'>
<?php
if($pmsBookingRoom->unpaidAmount > 0.1) {
    echo "<div class='unpaidamountwarning'><i class='fa fa-warning'></i> For this room there is a total of " . $pmsBookingRoom->unpaidAmount ." which not yet has been paid";
    echo "<div class='shop_button addselecteditemstocart' isgroup='yes' roomid='".$pmsBookingRoom->pmsBookingRoomId."' style='background-color: #86c330; color: #FFF; vertical-align: top;border-radius: 3px; border: solid 0px; float:right;'>Start payment process</div>";
    echo "</div>";
} else {
    $summary = $this->getApi()->getPmsManager()->getSummaryWithoutAccrued($this->getSelectedMultilevelDomainName(), $pmsBooking->id, $room->pmsBookingRoomId);
    $found = false;
    foreach ($summary->rows as $row) {
        if ($row->count == 0) {
            continue;
        } 
        $found = true;
    }
    
    if($found) {
        echo "<div class='unpaidamountwarning'><i class='fa fa-warning'></i> This booking is out of sync with the accounting information.";
        echo "<div class='shop_button' onclick='$(\".whyoutofsync\").slideDown()' style='background-color: #86c330; color: #FFF; vertical-align: top;border-radius: 3px; border: solid 0px; float:right;'>Show me why</div>";
        echo "</div>";
        echo "<div class='whyoutofsync'>";
        echo "<b>Here is the problem</b><br>";
        foreach ($summary->rows as $row) {
            if ($row->count == 0) {
                continue;
            } 
            
            $product = $this->getApi()->getProductManager()->getProduct($row->createOrderOnProductId);
            
            echo "At " . $row->date . " you need to create an order for " . $product->name . " for a total of " . $row->priceToCreateOrders . "<br>";
        }
        
        echo "<br><b>Why is this happening?</b><br>";
        echo "The answer is simple. The guest books and pay for a stay and everything is registered into the accounting module. This data can not be modified later on and thus correction orders are needed to be created. An example, a guest books for a stay on monday and are sendt a reciept for the monday. Then he decides to move the stay ahead to Tuesday. He now have a reciept for Monday but a stay for Tuesday. A correction is needed.";
        echo "<br><br><b>How do I solve this?</b><br>";
        echo "There are two ways to correct data that is out of sync.<br>";
        echo "1. Credit the original order and create a new one that is correct.<br>";
        echo "2. Create a new order by starting a payment process that has the differences included (an order with a total amount of 0).";
        echo "<div class='shop_button addselecteditemstocart' isgroup='yes' roomid='".$pmsBookingRoom->pmsBookingRoomId."' style='background-color: #86c330; color: #FFF; vertical-align: top;border-radius: 3px; border: solid 0px; float:right;'>Start payment process</div>";
        echo "</div>";
    }
}

$willbedeleted = $this->getApi()->getPmsManager()->willAutoDelete($this->getSelectedMultilevelDomainName(), $pmsBooking->id);
if($willbedeleted) {
    $start = strtotime($pmsBooking->completedDate);
    $start = $start+(60*90);
    echo "<div class='unpaidamountwarning' style='font-size: 18px;'><i class='fa fa-warning'></i> This booking has been booked online and not yet paid, will be autodeleted at " . date("d.m.Y H:i", $start). ".";
    echo "<span class='shop_button' style='float:right;' gsclick='cancelautodeletion'>Cancel autodeletion</span>";
    echo "</div>";
}

?>
    <div class='collapsable_shadowbox first_collapsable_shadowbox' defaultclosed='false'>
        <div class='colheader'>
            Booking information
            <div class='collapser closed'><i class='fa fa-angle-up'></i></div>
            <div class='collapser open'><i class='fa fa-angle-down'></i></div>
        </div>
        <div class='collapsable_content'><?php $this->includefile("bookinginfo"); ?></div>
    </div>

    <div class='collapsable_shadowbox' defaultclosed='true'>
        <div class='colheader'>
            Internal Comments
            <div class='extraheaderstuff'>
                <span class='title'>Pinned comment:</span>
                <span class='text userdescription' title="<? echo $this->getPinnedComment(); ?>"><? echo $this->getPinnedComment(); ?></span>
                <span class='title'>Order note:</span>
                <span class='text' title="<?php echo $pmsBooking->invoiceNote; ?>"><? echo $pmsBooking->invoiceNote; ?></span>
            </div>
            <div class='collapser closed'><i class='fa fa-angle-up'></i></div>
            <div class='collapser open'><i class='fa fa-angle-down'></i></div>
        </div>
        
        <div class="subheader">
            <?
            $this->includefile("comments");
            ?>
        </div>
        <div class='collapsable_content' style="background-color: #EFEFEF; ">
            
            <div><?php $this->includefile("internalcomments"); ?></div>
        </div>
    </div>

    <div class='collapsable_shadowbox' defaultclosed='true'>
        <div class='colheader'>
            Payments
            
            <div class='extraheaderstuff'>
                <div class="shop_button addselecteditemstocart" isgroup='<?php echo $isgroup; ?>' roomid='<? echo $pmsBookingRoom->pmsBookingRoomId; ?>' style="background-color: #86c330; color: #FFF; vertical-align: top; margin-top: -10px; border-radius: 3px;"><? echo $this->__f("Start payment process"); ?></div>
                <?php
                $bookedby = $this->getApi()->getUserManager()->getUserById($pmsBooking->bookedByUserId);
                $isAdmin = (@$bookedby->type > 10) ? true : false;
                $autosend = $this->getApi()->getPmsInvoiceManager()->autoSendPaymentLink($this->getSelectedMultilevelDomainName(), $pmsBooking->id);
                if($isAdmin && $pmsBooking->bookedByUserId != "gs_system_scheduler_user") {
                    $text = "Autosend";
                    if($pmsBooking->autoSendPaymentLink) {
                        $text = "Deactivate autosend";
                    }
                ?>
                    <div class="shop_button activateautosendpaymentlink"  gs_callback='app.PmsBookingRoomView.refresh' gsclick='activateautosendpaymentlink' isgroup='<?php echo $isgroup; ?>' roomid='<? echo $pmsBookingRoom->pmsBookingRoomId; ?>' style="background-color: #86c330; color: #FFF; vertical-align: top; margin-top: -10px; border-radius: 3px;"><? echo $text; ?></div>
                <? } ?>
                <span class='missingonroomgroup'>
                    <?php 
                    $totalOrdersRoom = $this->getApi()->getPmsInvoiceManager()->getTotalOnOrdersForRoom($this->getSelectedMultilevelDomainName(), $pmsBookingRoom->pmsBookingRoomId, true);
                    $unsettledRoom = round($pmsBookingRoom->unpaidAmount);
                    echo "Missing on group: " . $missingOnGroup; 
                    echo ", Missing on room: " . $unsettledRoom;
                    ?>
                </span>
            </div>
            <div class='collapser closed'><i class='fa fa-angle-up'></i></div>
            <div class='collapser open'><i class='fa fa-angle-down'></i></div>
        </div>
        
        <div class='pmsroomcheckoutview checkoutview'>
            <i class='fa fa-close' onclick='$(".checkoutview").hide();$(".getshoptableoverlaybody").css("height","auto");' style='position:absolute;right:1px; top:1px; cursor:pointer;'></i>
            <i class='fa fa-angle-up' style='position: absolute;top: -10px;right: 45px;color:#bbb;'></i>
            <div class='checkoutviewinner'></div>
        </div>
        <?php
        echo "<div style='padding: 3px;font-style: italic; color:#bbb;'>";
        if($autosend) {
            $date = $this->getApi()->getPmsInvoiceManager()->getPaymentLinkSendingDate($this->getSelectedMultilevelDomainName(), $pmsBooking->id);
            $date = date("d.m.Y", strtotime($date));
            echo "* A payment link will automatically be sent to the guest at " . $date;
        } else {
            $reason = $this->getApi()->getPmsInvoiceManager()->getReasonForNotSendingPaymentLink($this->getSelectedMultilevelDomainName(), $pmsBooking->id);
            echo "No payment link will be sent, reason: " . $this->translateNotSendPaymentLinkReason($reason);
        }
        echo "</div>";
        ?>
        
        <div class='collapsable_content'>
        <?php
        $this->includefile("paymentsheader");
        ?>
        </div>
    </div>
</div>
