<?php
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$pmsBooking = $this->getPmsBooking();
$pmsBookingRoom = $this->getSelectedRoom();

$isgroup = "no";
if (sizeof($pmsBooking->rooms) > 1) {
    $isgroup = "yes";
}

if(!$pmsBooking->confirmed) {
    echo "<div style='text-align:center; color:#fff; background-color:red;padding: 10px;'>This booking has not been confirmed, <span gsclick='confirmbooking' style='cursor:pointer;'>confirm.</span></div>";
}

?>

<div class='headerboxes'>

    <div class='collapsable_shadowbox first_collapsable_shadowbox' defaultclosed='false'>
        <div class='colheader'>
            Booking information
            <div class='collapser closed'><i class='fa fa-angle-up'></i></div>
            <div class='collapser open'><i class='fa fa-angle-down'></i></div>
        </div>
        <div class='collapsable_content'><?php $this->includefile("bookinginfo"); ?></div>
    </div>

    <div class='collapsable_shadowbox' defaultclosed='true'>
        <div class='colheader'>
            Internal Comments
            <div class='extraheaderstuff'>
                <span class='title'>Pinned comment:</span>
                <span class='text userdescription' title="<? echo $this->getPinnedComment(); ?>"><? echo $this->getPinnedComment(); ?></span>
                <span class='title'>Order note:</span>
                <span class='text'><? echo $pmsBooking->invoiceNote; ?></span>
            </div>
            <div class='collapser closed'><i class='fa fa-angle-up'></i></div>
            <div class='collapser open'><i class='fa fa-angle-down'></i></div>
        </div>
        
        <div class="subheader">
            <?
            $this->includefile("comments");
            ?>
        </div>
        <div class='collapsable_content' style="background-color: #EFEFEF; ">
            
            <div><?php $this->includefile("internalcomments"); ?></div>
        </div>
    </div>

    <div class='collapsable_shadowbox' defaultclosed='true'>
        <div class='colheader'>
            Payments
            
            <div class='extraheaderstuff'>
                <div class="shop_button addselecteditemstocart" isgroup='<?php echo $isgroup; ?>' roomid='<? echo $pmsBookingRoom->pmsBookingRoomId; ?>' style="background-color: #86c330; color: #FFF; vertical-align: top; margin-top: -10px; border-radius: 3px;"><? echo $this->__f("Start payment process"); ?></div>
                <span class='missingonroomgroup'>
                    <?php 
                    $totalOrdersRoom = $this->getApi()->getPmsInvoiceManager()->getTotalOnOrdersForRoom($this->getSelectedMultilevelDomainName(), $pmsBookingRoom->pmsBookingRoomId, true);
                    $unsettledRoom = round($pmsBookingRoom->totalCost - $totalOrdersRoom);
                    echo "Missing on group: " . $pmsBooking->unsettled; 
                    echo ", Missing on room: " . $unsettledRoom;
                    ?>
                </span>
            </div>
            
            <div class='collapser closed'><i class='fa fa-angle-up'></i></div>
            <div class='collapser open'><i class='fa fa-angle-down'></i></div>
        </div>
        
        <div class='pmsroomcheckoutview checkoutview'>
            <i class='fa fa-close' onclick='$(".checkoutview").hide();$(".getshoptableoverlaybody").css("height","auto");' style='position:absolute;right:1px; top:1px; cursor:pointer;'></i>
            <i class='fa fa-angle-up' style='position: absolute;top: -10px;right: 45px;color:#bbb;'></i>
            <div class='checkoutviewinner'></div>
        </div>
        
        <div class='collapsable_content'>
        <?php
        $this->includefile("paymentsheader");
        ?>
        </div>
    </div>
</div>
