<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$carts = $this->getCartsForPaymentProcess();

if (!count($carts)) {
    return;
}

foreach ($carts as $cart) {
    echo "<div class='SalesPointCartCheckout' roomid='".$cart->roomId."'>";
        $salesPointCartCheckout = new \ns_90d14853_2dd5_4f89_96c1_1fa15a39babd\SalesPointCartCheckout();
        $salesPointCartCheckout->setRoomCart($cart->roomId);
        $salesPointCartCheckout->render();
    echo "</div>";
}
?>
<div>
    <div class="shop_button toggle_payment_process_window"><i class="fa fa-close"></i> <? echo $this->__f("Close"); ?></div>
    <div gs_callback="app.PmsSearchPaymentProcess.updatePaymentProcess" class="shop_button" synchron="true" gsclick="cancelAllPaymentProcesses"><i class="fa fa-trash-o"></i> <? echo $this->__f("Cancel all payments"); ?></div>
</div>
