<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$pmsBooking = $this->getPmsBooking();
$pmsSelectedRoom = $this->getSelectedRoom();
$booking = $this->getBookingEngineBooking();
$cart = json_decode($_SESSION['payment_process_cart_'.$this->getSelectedRoom()->pmsBookingRoomId]);

$total = 0;
if ($cart) {
    $total = $this->getApi()->getCartManager()->getCartTotal($cart);
}
?>

<div class="payment_process_started">
    <? echo $this->__f("Payment process started for")." ".$total; ?>
    <br/> <? echo $this->__f("To complete the process, go to the payment gateway in the top right corner"); ?>
    <br/> 
    <br/> <div class="gs_shop_small_icon" synchron="true" gs_callback="app.PmsSearchBooking.ordersTabChanged"  gsclick="cancelPaymentProcess" id="<? echo $booking->id; ?>" roomId="<? echo $pmsSelectedRoom->pmsBookingRoomId; ?>"><i class="fa fa-close"></i> <? echo $this->__f("Cancel"); ?></div>
</div>