<?php
$type = $_POST['data']['type'];
$roomId = $_POST['data']['roomid'];
$booking = $this->getApi()->getPmsManager()->getBookingFromRoom($this->getSelectedMultilevelDomainName(), $roomId);
$currentRoom = null;
 foreach($booking->rooms as $room) {
    if($room->pmsBookingRoomId == $roomId) {
        $currentRoom = $room;
    }
}
?>
<div>
    <select class='gsniceselect1' gsname='numberofguests'>
        <?php
        for($i = 1;$i < 30; $i++) {
            $selected = "";
            if($i == $currentRoom->numberOfGuests) {
                $selected = "SELECTED";
            }
            echo "<option value='$i' $selected>$i guest(s)</option>";
        }
        ?>
    </select>
    <div>
        <span style='width:190px; display:inline-block;'>Name</span>
        <span style='width:190px; display:inline-block;'>Email</span>
        <span style='width:60px; display:inline-block;'>Prefix</span>
        <span>Phone</span>
    </div>
    <?php
    for($i = 0; $i < 30; $i++) {
        $guest = new core_pmsmanager_PmsGuests();
        if(isset($currentRoom->guests[$i])) {
            $guest = $currentRoom->guests[$i];
        }
        $display = "";
        if($i+1 > $currentRoom->numberOfGuests) {
            $display = "display:none;";
        }
        $prefix = $guest->prefix;
        if(!$prefix) {
            $prefix = $this->getDefaultPrefix();
        }
        ?>
        <div style='width:700px; <?php echo $display; ?>' guest='<?php echo $i; ?>'>
            <input type='text' class='gsniceinput1' gsname='name_<?php echo $i; ?>' value='<?php echo $guest->name; ?>'>
            <input type='text' class='gsniceinput1' gsname='email_<?php echo $i; ?>' value='<?php echo $guest->email; ?>'>
            <input type='text' class='gsniceinput1' style='width:50px;' gsname='prefix_<?php echo $i; ?>' value='<?php echo $prefix; ?>'>
            <input type='text' class='gsniceinput1'  gsname='phone_<?php echo $i; ?>' value='<?php echo $guest->phone; ?>'>
            <input type='hidden' class='gsniceinput1'  gsname='guestid_<?php echo $i; ?>' value='<?php echo $guest->guestId; ?>'>
        </div>
        <?php
    }
    ?>
    <div style='text-align: right; margin-top: 10px;'>
        <span class='shop_button' gstype='submit'>Update guest information</span>
</div>
    
<script>
    $("select[gsname='numberofguests']").on('change', function() {
        var guests = $(this).val();
        $("[guest]").hide();
        $("[guest]").each(function() {
           var guestCounter = parseInt($(this).attr('guest'));
           if(guestCounter < guests) {
               $(this).show();
           }
        });
    });
</script>