<div class='masseditpricesbox'>
    <select class="gsniceselect1 masseditpricestay" style="width:100%; margin-bottom: 5px;" gsname='periodePriceType'>
        <option value="dayprice">Same price all days</option>
        <option value="start_of_month">Monthly price beginning of month</option>
        <option value="start_of_stay">Monthly price beginning of stay</option>
        <option value="wholestay">Total cost for whole stay</option>
    </select>
    <input type="text" class="gsniceinput1 massupdatepricevalue" placeholder="value" gsname='periodePrice'>
    <span class="shop_button massupdateprices" style="float:right;" gstype='submit'>Update</span>

    <div class='priceselectionhelp' type="dayprice" style='display:block;'>This will set the same price for each day.</div>
    <div class='priceselectionhelp' type="start_of_month">This will calculate the daily price to be the same as a total of monthly cost, since each month has different days it will use the number of days in month where the base will be the first day in the month.</div>
    <div class='priceselectionhelp' type="start_of_stay">This will calculate the daily price to be the same as a total of monthly cost, since each month has different days it will use the number of days in month where the base will be the first day of the stay, if the stay start the 15 one month will be calculated from 15 to 15.</div>
    <div class='priceselectionhelp' type="wholestay">This will calculate the daily price for each day which the total will be the same as you entered.</div>
</div>

<style>
    .priceselectionhelp { display:none; padding-top: 50px; width:100%; font-style: italic; }
</style>
<script>
    $('.masseditpricestay').on('change', function() {
        $('.priceselectionhelp').hide();
        var type = $(this).val();
        $('.priceselectionhelp[type="'+type+'"]').show();
    });
    $('.priceselectionhelp[type="dayprice"]').show();
</script>