<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$room = $this->getSelectedRoom();

$startDate = date('d.m.Y H:i', strtotime($room->date->start));
$endDate = date('d.m.Y H:i', strtotime($room->date->end));
?>

<div class="itemview" bookingid="<? echo $room->bookingId; ?>" roomid='<? echo $room->pmsBookingRoomId; ?>'>
    <?
    $this->includefile("itemview");
    ?>
</div>

<script>
    $('.PmsBookingRoomView .startdate').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true});
    $('.PmsBookingRoomView .enddate').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true});
</script>
    