<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$pmsBooking = $this->getPmsBooking();
$pmsSelectedRoom = $this->getSelectedRoom();
$booking = $this->getBookingEngineBooking();

$user = $this->getUserForBooking();
$ticket = new ns_9c29f94a_6c42_4590_aa1c_7736c58ff0a5\TicketCreateNew();
$ticket->setUser($user);
$ticket->setExternalId($pmsSelectedRoom->pmsBookingRoomId);
$ticket->renderApplication(true, $this);
echo "<br/>";

echo "<div style='border-top: solid 1px #DDD; padding-top: 20px; margin-top: 20px; padding-bottom: 20px; font-weight: bold;'>".$this->__f("Filters")."</div>";

$filter = new \core_ticket_Ticket();
$filter->userId = $user->id;

$ticketList = new ns_419c41e7_1dd5_4c96_b820_c1b77a2fffa3\TicketList();
$ticketList->setFilter($filter);
$ticketList->renderApplication(true, $this);
?>