<div class='steptitle'>Add to existing</div>
<div class='gsshadowbox addtoexistingbox'>
    <div class='stepboxtitle'>Add to existing</div>
    <div gstype='form' method='searchBooking' synchron='true' gstoarea='.searchbookingresult' class='stepboxbody'>
        <div style='position: relative; text-align: left; padding-left: 20px;padding-bottom: 20px;'>
            <i class='fa fa-info-circle' style='position:absolute;left: 0px;top: 5px;'></i>
            Do you need to add more room to an existing booking?<br>
            Search for the booking above and proceed.
        </div>
                    
        <span style='position:relative'>
            <i class='fa fa-search' gstype='submit' style='position:absolute; right: 10px; color:#8cd8f6; font-size: 20px; top: -2px;cursor:pointer;'></i>
            <input type='text' placeholder='Booking information' gsname='keyword' class='gsniceinput1 searchforbookinginput' gstype='submitenter' style='width: 100%; box-sizing: border-box;'>
            </span>
    </div>
</div>
<div class='searchbookingresult'></div>