<?php
/* @var $this ns_bf644a39_c932_4e3b_a6c7_f6fd16baa34d\PmsNewBooking20 */
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
$start = $_POST['data']['start'] . " " . $config->defaultStart;
$start = $this->convertToJavaDate(strtotime($start));

if (!$_POST['data']['start'] || !$_POST['data']['end']) {
    echo "<div class='searchforbooking'>The date you have selected are invalid, please choose another time periode.</div>";
    return;
}

$end = $_POST['data']['end'] . " " . $config->defaultEnd;
$end = $this->convertToJavaDate(strtotime($end));
$items = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);
$total = 0;
$items = $this->getApi()->getPmsManager()->getAllRoomTypes($this->getSelectedMultilevelDomainName(), $start, $end);
$current = $this->getApi()->getPmsManager()->getCurrentBooking($this->getSelectedMultilevelDomainName());
?>
<div class='datetitle'><i class='fa fa-clock-o'></i> <?php echo date("d.m.Y H:i", strtotime($start)) . " - " . date("d.m.Y H:i", strtotime($end)); ?></div>
<div class='avilabilityarea' gstype='form' method='registerRoomsFromAvailabilityCheck' synchron='true' gstoarea='.roomsreadytobeadded'>
    <input type='hidden' gsname='start' value='<?php echo strtotime($start); ?>'>
    <input type='hidden' gsname='end' value='<?php echo strtotime($end); ?>'>
    <?php
    foreach ($items as $item) {
        $count = $size = $this->getNumberOfAvailableForType($item->type, $current, $start, $end);
        $total += $count;
        ?>
        <div class='searchbookingrow'>
            <span class='itemtypename ellipsis secondarytextcolor'><?php echo $item->type->name; ?></span>
            <span class='numberavailable secondarytextcolor'><?php echo $count; ?></span>
            <span class='price secondarytextcolor'><?php echo $item->price; ?></span>
            <span class='selection counterrow'>
                <i class='fa fa-minus-circle decreaseroomcounter'></i>
                <input type='text' value='0' class='gsniceinput1 roomcount' gsname='<?php echo $item->type->id; ?>' style='width: 20px;text-align: center;'>
                <i class='fa fa-plus-circle increaseroomcounter'></i>
            </span>
        </div>
        <?php
    }
    ?>
    <div class='searchbookingrow' style='font-weight: bold;'>
        <span class='itemtypename'>Total</span>
        <span class='numberavailable'><?php echo $total; ?></span>
            <span class='price secondarytextcolor'></span>
        <span class='selection'><span class='selectallbutton'>select all</span>
        </span>
    </div>
    <div><span class='shop_button selectavailablerooms' gstype='submit' onclick="$(window).scrollTop(10000);">Select room(s)</span></div>
</div>
<style>
    .avilabilityarea .fa { cursor:pointer; }
    .selectavailablerooms {max-width: 480px; width: 100%;box-sizing: border-box; margin-bottom: 5px;}
    .selectallbutton { color: #8cd8f6; cursor:pointer; font-weight: normal; }
    .avilabilityarea { border-bottom: solid 0px;background-color:#fff; max-width: 510px; display:inline-block; margin:auto;}
    .searchbookingrow { border-bottom: solid 1px #e9ebed; padding-left: 20px; margin:auto; text-align: left; font-size: 18px; padding-bottom: 5px; margin-bottom: 5px; }
    .selection .fa { font-size: 18px; }
    .itemtypename { width: 260px; display:inline-block; }
    .numberavailable { width: 45px; display:inline-block; text-align: center;}
    .price { width: 65px; display:inline-block; }
    .datetitle { font-size: 14px; margin-bottom: 10px; text-align: left;padding-left: 20px; font-weight: bold; margin-top: 5px; margin-bottom: 20px;}
    .datetitle .fa-clock-o { color:#8cd8f6;}
</style>

