<?php
/* @var $this ns_bf644a39_c932_4e3b_a6c7_f6fd16baa34d\PmsNewBooking20 */
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
$start = $_POST['data']['start'] . " " . $config->defaultStart;
$start = $this->convertToJavaDate(strtotime($start));

if(!$_POST['data']['start'] || !$_POST['data']['end']) {
    echo "<div class='searchforbooking'>The date you have selected are invalid, please choose another time periode.</div>";
    return;
}

$end = $_POST['data']['end'] . " " . $config->defaultEnd;
$end = $this->convertToJavaDate(strtotime($end));
$items = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);
foreach($items as $item) {
    if($item->id == "gsconference") {
        continue;
    }
    $count = $this->getApi()->getPmsManager()->getNumberOfAvailable($this->getSelectedMultilevelDomainName(),$item->id, $start, $end);
    $price = $this->getApi()->getPmsManager()->getPriceForRoomWhenBooking($this->getSelectedMultilevelDomainName(), $start, $end,$item->id);
    ?>
    <div class="freeroomresultbox gsshadowbox" gstype='form' method='addTypesToBooking'>
        <input type='hidden' gsname='typeid' value='<?php echo $item->id; ?>'>
        <input type='hidden' gsname='start' value='<?php echo strtotime($start); ?>'>
        <input type='hidden' gsname='end' value='<?php echo strtotime($end); ?>'>
        <div class="stepboxtitle" title='<?php echo $item->name; ?>'><?php echo $item->name; ?></div>
        <div class="availroomstep secondarytextcolor">Available</div>
        <div class="numberavailable secondarytextcolor"><?php echo $count; ?></div>
        <div class="price secondarytextcolor">Price <b style='color:#000;'><?php echo round($price,2); ?></b> / day</div>
        <div class="counterrow">
            <span class='outercountbutton'><i class="fa fa-minus decreaseroomcounter"></i></span>
            <input type="txt" class="roomcount" gsname='count' style="    width: 33px;text-align: center;border: 0px;border-left: solid 1px #dcdcdc;height: 38px;border-right: solid 1px #dcdcdc;" value="0">
            <span class='outercountbutton'><i class="fa fa-plus increaseroomcounter"></i></span>
        </div>
        <br>
    </div>
<style>
    .counterrow { border: solid 1px #dcdcdc;border-radius: 3px;width: 100px;margin: auto;position: relative; }
    .freeroomresultbox .counterrow .fa { top: -1px;color: #8cd8f6;width: 30px;text-align: center;left: 0px;height: 37px;line-height: 37px; }
    .PmsNewBooking20 .freeroomresultbox .outercountbutton { height: 23px !important; }
</style>
    <?php
}


$closedtext = $this->checkIfClosedPeriodes($start,$end);
$closedRoom = "";
if($closedtext) {
    echo "<div>";
    echo "<div class='warnclosedroom'>";
    echo "<h2>We have closed rooms in this time periode.</h2>";
    echo $closedtext;
    echo "<span class='shop_button' onclick='$(\".warnclosedroom\").hide();$(\".addroomssummary\").show();'>Yes, I understand that we are closed in this periode.</span>";
    echo "</div>";
    echo "</div>";
    $closedRoom = "isclosed";
}
?>
<div class='addroomssummary disabled <?php echo $closedRoom; ?>'>
    <div class='description'>You have not selected any rooms yet.<br>Please choose one or more rooms in the options above.</div>
    <span class='shop_button addroomscategories'>Add <span class='roomselection'>0</span> room(s)</span>
</div>

<style>
.roomsaddedarea { display:none; }
</style>