<?php
/* @var $this ns_bf644a39_c932_4e3b_a6c7_f6fd16baa34d\PmsNewBooking20 */
?>
<div class='newbookingprocess' for='start'>
    <?php $this->includefile("newbookingstart"); ?>
</div>

<div class='newbookingprocess' for="newcustomer">
    <?php $this->includefile("newcustomer"); ?>
</div>
<div class='newbookingprocess' for="search">
    <?php $this->includefile("searchcustomer"); ?>
</div>
<div class='newbookingprocess' for="checkavailability">
    <?php $this->includefile("checkavailability"); ?>
</div>
<div class='newbookingprocess' for="newconference">
    <?php $this->includefile("newconference"); ?>
</div>
<div class='newbookingprocess' for="addtoexisting">
    <?php $this->includefile("addtoexisting"); ?>
</div>

