<h1>Step 1 of 3 - who is this booking for?</h1>
<span class="newbookingoption" goto="newcustomer">
    <div class="title">New customer</div>
    <div class="descriptionimage">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/New_user_icon-01.svg/512px-New_user_icon-01.svg.png">
    </div>
    <div class='description'>
        Register a booking on a new customer
    </div>
</span>
<span class="newbookingoption" goto="search">
    <div class="title">Existing customer</div>
    <div class="descriptionimage">
        <img src="https://secure.aos.org/store/img/menu-icon.svg">
    </div>
    <div class='description'>
        Register a booking on an existing customer
    </div>
</span>
<span class="newbookingoption" goto="checkavailability">
    <div class="title">Check availability</div>
    <div class="descriptionimage">
        <img src="https://cdn1.iconfinder.com/data/icons/navigation-icon/128/check-512.png">
    </div>
    <div class='description'>
        Check availability
    </div>
</span>