<?php
$items = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);
$items = $this->indexList($items);
/* @var $this ns_bf644a39_c932_4e3b_a6c7_f6fd16baa34d\PmsNewBooking20 */

$booking = $this->getApi()->getPmsManager()->getCurrentBooking($this->getSelectedMultilevelDomainName());
if(sizeof($booking->rooms) == 0) {
    echo "No room selected yet.";
    return;
}

$totalrooms = 0;
?>

<div class='selectedroomsrow'>
    <span class='selectedroomname'><b>Room type</b></span>
    <span class='selectedroomcount'><b>Guests</b></span>
    <span class='selectedroomstartdate'><b>Check-in</b></span>
    <span class='selectedroomenddate'><b>Check-out</b></span>
    <span class='selectedroomcost'><b>Price</b></span>
</div>

<?php
$totalrooms = 0;
$totalPrice = 0;
$totalguests = 0;
foreach($booking->rooms as $room) {
    ?>
    <div class='selectedroomsrow'>
    <?php
    $item = $items[$room->bookingItemTypeId];
    echo "<span class='selectedroomname'>";
    echo "<i class='fa fa-trash-o' gstype='clicksubmit' method='deleteRoom' style='cursor:pointer;' gsname='roomid' gsvalue='".$room->pmsBookingRoomId."' gstoarea='.roomsreadytobeadded'></i> ";
    echo $item->name . "</span>";
    echo "<span class='selectedroomcount'><i class='fa fa-minus-circle increasedecreasecount' increase='".($room->numberOfGuests-1)."' roomid='".$room->pmsBookingRoomId."' style='cursor:pointer;'></i> ";
    echo $room->numberOfGuests;
    echo " <i class='fa fa-plus-circle increasedecreasecount' increase='".($room->numberOfGuests+1)."' roomid='".$room->pmsBookingRoomId."' style='cursor:pointer;'></i></span> ";
    echo "<span class='selectedroomstartdate'>" . date("d.m.Y", strtotime($room->date->start)) . "</span>";
    echo "<span class='selectedroomenddate'>" . date("d.m.Y", strtotime($room->date->end)) . "</span>";
    echo "<span class='selectedroomcost'>" . $room->totalCost . "</span>";
    $totalrooms++;
    $totalguests += $room->numberOfGuests;
    $totalPrice += $room->totalCost;
    ?>
    </div>
    <?php
}
?>
<div class='selectedroomsummary'>
    Rooms <?php echo $totalrooms . ", " . $totalguests; ?> guests.
    <span class='removeallrooms' gsclick='clearRoomList' synchron='true' gs_callback='app.PmsNewBooking20.roomListCleared'>clear roomlist</span>
    <span style="float:right; font-size: 20px;"><b>Total <?php echo $totalPrice; ?></b></span>
</div>
<br>
<br>
<div style='text-align: center;margin-bottom: 3px;'>
    <span class='shop_button proceedwithreservation quickreservation'
          gsclick='quickReserveBookingList' 
          synchron='true' 
          gs_callback='app.PmsNewBooking20.bookingCompleted'>Quick<br>reservation</span>
    <span class='shop_button proceedwithreservation navigatetonext newcustomer' goto="newcustomer">New<br>customer</span>
    <span class='shop_button proceedwithreservation navigatetonext existingcustomer' goto="search">Existing<br>customer</span>
    <span class='shop_button proceedwithreservation navigatetonext existingbooking' goto="addtoexisting">Existing<br>booking</span>
</div>
<style>
    .selectedroomcost { float:right;}
    .removeroomfrombooking { cursor:pointer; }
    .proceedwithreservation { width: 20%;height: 50px;line-height: 20px;padding-top: 10px; }
    .proceedwithreservation:hover { font-weight: bold; }
    .removeallrooms { color: blue; cursor:pointer; }
    .selectedroomsrow { padding: 5px; }
    .selectedroomsummary { padding: 10px; }
    .roomsreadytobeadded { max-width: 800px; background-color:#fff; text-align: left; margin: auto; margin-top: 50px; }
    .selectedroomname { display:inline-block; width: 500px; }
    .selectedroomcount { display:inline-block; width: 60px; text-align: center; }
    .selectedroomstartdate { display:inline-block; width: 90px; }
    .selectedroomenddate { display:inline-block; width: 90px; }
    .existingcustomer { background-color: #3423de; }
    .existingbooking { background-color: #3629b1; }
    .newcustomer { background-color: #6558e1; }
    .quickreservation { background-color: #847bde; }
</style>