<h1>Step 1 of 3 - Search for existing customer</h1>
<div gstype="form" method="searchCustomer">
    <input type="text" class="gsniceinput1" gstype="clicksubmit" gstoarea=".customersearcharea"  method="searchCustomer" gsname="searchfield">
    <span class="shop_button" gstype="submit" gstoarea=".customersearcharea" gs_callback='app.PmsNewBooking20.searchCustomerResult'>Search for customer</span>
</div>

<div class="customersearcharea">
</div>