<?php
$integrations = array();

$integration = new stdClass();
$integration->name = "xledger";
$integration->description = "Generate an accounting file and transfer your accounting data directly into the accounting system.";
$integration->image = "";
$integration->type = "accounting";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "visma business";
$integration->description = "Visma business is a widely used accounting system, we create files supported by visma business and enables export of financial data into visma business.";
$integration->image = "";
$integration->type = "accounting";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "visma.net";
$integration->description = "Visma.net is an cloud based accounting system, by api we transfer financial data to this accounting system.";
$integration->image = "";
$integration->type = "accounting";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "powerofficego";
$integration->description = "Poweroffice Go is a new and forward leaned accounting system, we transfer invoices, and financial data into powerofficego by api.";
$integration->image = "";
$integration->type = "accounting";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "tripletex";
$integration->description = "We transfer financial data to tripletex using file their file transfer export format.";
$integration->image = "";
$integration->type = "accounting";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "gbat10";
$integration->description = "A lot of different accounting system supports transferring financial data using gbat10.";
$integration->image = "";
$integration->type = "accounting";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Stripe";
$integration->description = "Start accepting payments using stripe, look at www.stripe.com for more information, a brilliant fully and embeddedable online payment system.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Stripe autocollect";
$integration->description = "Get in touch with us if you want to automatically fetch cards from the OTA's and start charging the cards. With no human interactions involved at all.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Braintree";
$integration->description = "Reach more buyers and drive higher conversion with the only payments platform that delivers PayPal, Venmo (in the US), credit and debit cards, and popular digital wallets like Apple Pay and Google Pay in a single, seamless integration.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Nets terminal";
$integration->description = "By integrating a payment terminal into your pms you can charge your customers directly by a push of a button.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Verifone terminal";
$integration->description = "Start charging customers using a physical verfione payment terminal, we support the paypoint api.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Epay";
$integration->description = "A payment gateway now operating under bambora. Supports visa / mastercard payments.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Dibs";
$integration->description = "A scandinavian online payment gateway handling visa / mastercard. An excelent choice for low costs transactions.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Invoice Payment";
$integration->description = "Generate invoices directly into the PMS by activating the invoice payment method. Send them out by printing them, by email, or even by EHF.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Combined invoicing";
$integration->description = "For returning customers visiting weekly and you want to invoice them monthly. Then the combining invoicing payment method are great. Just create a combined invoice to later combine into one invoice and ship it away.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Dept collector (lowell)";
$integration->description = "Having trouble getting paid? Just get a deal with lowell and you can make them take care of all the boring debt collection stuff.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Expedia";
$integration->description = "Keep track of all payments paid to expedia. Whenever someone pays directly to expedia this payment method is activated and the guest is granted access automatically.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Booking.com";
$integration->description = "From time to time booking.com is handling the payments for you, we detect that the payment is done using a virtual card or bank transfer. When this happends we automatically grants access to the guest.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Airbnb";
$integration->description = "When renting out at airbnb all the payments are handled by airbnb. To keep track of the money and set them apart you this payment method is used.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "EHF";
$integration->description = "EHF – Elektronisk Handelsformat (Electronic Trading Format) – is the central government standard format for electronic invoicing.";
$integration->image = "";
$integration->type = "payment";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Wubook";
$integration->description = "Connect to 100 different channels using wubook, included but not limited to expedia, booking.com, trivago, hotels.com, and much more. See www.wubook.com for more information.";
$integration->image = "";
$integration->type = "channelmanager";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "GetShop Check In Kiosk";
$integration->description = "If you have the need of a check in kiosk we can provide one for you weather its a check in kiosk for indoor and outdoor usage. Its integrated to GetShop PMS and requires the lock system created by GetShop.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "GetShop Apac";
$integration->description = "GetShop Automated Property Access Control system helps you to get rid of physical devices like keys and keycards. Just give them a pin code for a given time periode and you are good to go.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "D2O (PMI)";
$integration->description = "An extensive reporting system that help you keep track of the financial data over time, keep track of goals and key figures easily";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "GetShop messenger";
$integration->description = "A fully automated messaging system that supports all languages and help you sending out codes automatically and keep the automated and needed communication with your guests.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "GetShop salespos";
$integration->description = "A simple but powerful salespos system that has all the integrations found in this page. If you need to sell extra accessorier at your property this is the perfect cloud based tool for you.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Trivec";
$integration->description = "A more advanced salespos for those with extra needs. Extensive reporting and lots of more features than the GetShop salespos.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "nets ocr";
$integration->description = "Whenever someone pay your bill the bank can send us a file that marks your bill as paid automatically in the system. No need to keep track of payments anymore.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "GetShop booking engine";
$integration->description = "A fully embeddable booking engine that can be embeded into any kind of webpage with a simple jquery plugin. It is simple but also a powerful tool that support coupon codes and advanced pricing.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "difi (postcode lookup)";
$integration->description = "For the norwegian marked we have integrated us into the Norwegian postal code system enabling us to look up a postcode instantly.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Brreg";
$integration->description = "Searching a fetching data directly from the Norwegian company registration database, meaning you would only need to search for the name of the business and the rest is filled out for you.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Allabolag";
$integration->description = "Searching a fetching data directly from the Swedish company registration database, meaning you would only need to search for the name of the business and the rest is filled out for you.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "getshop.express";
$integration->description = "A simple cloud based version of GetShop PMS that fits perfectly in your pocket. The perfect way for your cleaning staff to keep track of rooms to clean, and much more.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "GetShop PGA";
$integration->description = "A mobile adapted web page that can be sent to your guests to keep track of their stay, order extras and even extend their stay.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "KNX";
$integration->description = "KNX is a great way to keep track of the comfort in your rooms, connect your KNX system to GetShop and start automating temperatures, lights, and much more.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;

$integration = new stdClass();
$integration->name = "Z-wave";
$integration->description = "The z-wave wireless technology is perfect for home automation and for hotel automation.";
$integration->image = "";
$integration->type = "other";
$integrations[] = $integration;


$typeTranslations = array();
$typeTranslations['accounting'] = "Accounting systems";
$typeTranslations['payment'] = "Payment methods";
$typeTranslations['channelmanager'] = "Channel managers";
$typeTranslations['other'] = "Other integrations";

?>

<div class="page_row row_1">
    <div class="page_row_inner">
        <?php
            ContentManager::render("integrations_row1");
        ?>
    </div>
</div>
<div class="page_row row_2">
    <div class="page_row_inner">
        <?php
        
        $types = array();
        foreach($integrations as $integration) {
            $types[$integration->type] = "";
        }
        
        foreach($types as $type => $val) {
            echo "<h2>" . $typeTranslations[$type] . "</h2>";
            foreach($integrations as $integration) {
                if($type != $integration->type) {
                    continue;
                }
                echo "<div class='integrationbox'>";
                echo "<div class='title'>" . $integration->name . "</div>";
                echo "<div class='desc'>" . $integration->description . "</div>";
                echo "<div class='footer'>" . $integration->type . "</div>";
                echo "</div>";
            }
        }
        ?>
    </div>
</div>
