<?
/* @var $this \ns_2d6a27b9_b238_4406_9f03_c4ca8184f590\ApacGateways */

$server = $this->getServer();
$isUpdating = true;
$numberOfLocks = 0;
foreach ($server->locks as $lock) {
    $numberOfLocks++;
}
?>


<div class='locklist'>
    <div class='menuarea'>
        <div class='shop_button' gsclick='startFetchingOfLocks' serverid='<? echo $server->id; ?>'><i class='fa fa-lock'></i> Fetch locks</div>
        <div gs_confirm='Are you sure?' class='shop_button' gsclick='deleteServer' serverid='<? echo $server->id; ?>'><i class='fa fa-trash'></i> Delete</div>
        <div class='shop_button' gsclick='toggleUpdate' serverid='<? echo $server->id; ?>'>
            <? if ($isUpdating) { ?>
                <i class='fa fa-pause'></i> Toggle update ( currently updating )
            <? } else { ?>
                <i class='fa fa-play'></i> Toggle update ( currently not updating )
            <? } ?>
        </div>
        <div class='shop_button' gsclick='runCheck' serverid='<? echo $server->id; ?>'><i class='fa fa-play'></i> Run check</div>
        
        <div class="serverdetails" gstype="form" method="saveConnectionDetails">
            <input type="hidden" gsname="serverid" value="<? echo $server->id; ?>"/>
            Given name<br/> <input style='line-height: 29px; vertical-align: top;' gsname='servername' class="gsniceinput1" placeholder="Server name" value="<? echo $server->givenName; ?>">
            <br/>Hostname<br/> <input style='line-height: 29px; vertical-align: top;' gsname='hostname' class="gsniceinput1" placeholder="Hostname" value="<? echo $server->hostname; ?>">
            <br/>Username<br/> <input style='line-height: 29px; vertical-align: top;' gsname='username' class="gsniceinput1" placeholder="Username" value="<? echo $server->username; ?>">
            <br/>Password<br/> <input style='line-height: 29px; vertical-align: top;' gsname='password' class="gsniceinput1" placeholder="Password" value="<? echo $server->password; ?>">        
            <br/><div class="shop_button" gstype="submit"><? echo $this->__f("Save"); ?></div>
        </div>
    </div>
    
    <i class="fa fa-lock"></i> <? echo $this->__f("Number of locks in this gateway").": $numberOfLocks"; ?>
</div>
