<? namespace ns_0cf21aa0_5a46_41c0_b5a6_fd52fb90216f; ?>
<div class="textfield setting"  id="code">
    <span class="title"><?php echo $this->__("Google analytics code") ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php 
        echo $this->__("This is a code that you need to get from your google analytics account. If you need help to get it we would be more then happy to help you out, just contact our customer support by email and you will have an answer within an hour");
        ?>
    </div>
</div>

<div class="button savebutton"><div class="rightglare"></div><div class="filler"></div><ins><?php echo $this->__("Save settings"); ?></ins></div>
