<?
/* @var $this ns_93b0a895_0713_4c59_acf3_c4714ad1f200\EventEditorBooking */
$event = $this->getEvent();    
$result = null;

if (isset($_POST['data']['searchstring']) && $_POST['data']['searchstring'] != "") {
    $result = $this->getApi()->getUserManager()->findUsers($_POST['data']['searchstring']);
}

?>

<div class='usersearchresults'>
    <?
    if ($result == null) {
        echo $this->__f("Please search for users.");
    } else if (!count($result)) {
        echo $this->__f("Did not find any users by the criteria");
    } else {
        
        echo "<div class='usersearchrow'>";
            echo "<div>Name</div>";
            echo "<div>Email</div>";
            echo "<div>Cellphone</div>";
            echo "<div>Company</div>";
        echo "</div>";
            
        foreach ($result as $user) {
            if (!$user) {
                continue;
            }
            $companyName = $user && $user->companyObject != null ? $user->companyObject->name : "N/A";
            $subAccountTitle = $this->__w("Create a new sub account");
            $addAccountTitle = $this->__w("Add this account to the event");
            echo "<div class='usersearchrow'>";
                echo "<div>$user->fullName</div>";
                echo "<div>$user->emailAddress</div>";
                echo "<div>$user->cellPhone</div>";
                echo "<div>$companyName</div>";
                echo "<div class='gs_shop_small_icon' title='$addAccountTitle' gsclick='addUserToEvent' eventid='$event->id' userid='$user->id'><i class='fa fa-plus'></i></div>";
                echo "<div class='gs_shop_small_icon' title='$subAccountTitle'><i class='fa fa-external-link'></i></div>";
            echo "</div>";
        }
    }
    ?>
</div>