<?
/* @var $this ns_098bb0fe_eb51_42c6_9fbb_dadb7b52dd56\Shipper */

namespace ns_098bb0fe_eb51_42c6_9fbb_dadb7b52dd56;

$startupCost = $this->getStartUpCost();
$itemPrice = $this->getItemPrice();
$freeShipment = $this->getFreeShipmentPrice();

?>

<div class='gss_settings_header'>
    <i class='fa fa-truck'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Shipping settings"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("We offer multiple shipping methods, this is the standard one that is not integraded to any third parties. If need something more advanced you can activate some of our other shipping applications under \"Applications\".");
            ?>	
        </div>
    </div>	
</div>

<div class='gss_settings_content'>

    <div class="gss_simple_shipping">
        <div class="textfield gss_setting"  id="postbox">
            <span class="title"><?php echo $this->__f("Start up price"); ?></span>
            <input type="textfield" gs_model='shippingmodel' gs_model_attr='startupCost' value="<? echo $startupCost; ?>">
            <div class="description">
                <?php echo $this->__("Should there be a fixed "); ?>
            </div>
        </div>
    </div>

    <div class="gss_simple_shipping">
        <div class="textfield gss_setting"  id="postbox">
            <span class="title"><?php echo $this->__f("Price for each item"); ?></span>
            <input type="textfield" gs_model='shippingmodel' gs_model_attr='itemPrice' value="<? echo $itemPrice; ?>">
            <div class="description">
                <?php echo $this->__("Should there be a fixed "); ?>
            </div>
        </div>
    </div>

    <div class="gss_simple_shipping">
        <div class="textfield gss_setting"  id="postbox">
            <span class="title"><?php echo $this->__f("Free shipment"); ?></span>
            <input type="textfield" gs_model='shippingmodel' gs_model_attr='freeShipping' value="<? echo $freeShipment; ?>">
            <div class="description">
                <?php echo $this->__("Should there be a fixed "); ?>
            </div>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="shippingmodel" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>
</div>
