<div class='typeselector'>
    <?
    echo $this->__f("Please select type");
    ?>
    <br/>
    <div class='quest_back_type_selected' type='1'><i class='fa fa-check'></i> Checkboxes</div>
    <div class='quest_back_type_selected' type='2'><i class='fa fa-circle-o'></i> Radio buttons</div>
    <div class='quest_back_type_selected' type='3'><i class='fa fa-pencil'></i> Text</div>
    <div class='quest_back_type_selected' type='4'><i class='fa fa-image'></i> Picture</div>
</div>