<?
/* @var $this ns_07422211_7818_445e_9f16_ad792320cb10\QuestBack */

$isNotInTest = !\ns_cc678bcb_0e87_4c6c_aaad_8ec24ecdf9df\QuestBackUserOverview::getCurrentRunningTestId();

$x = $this->getConfigurationSetting("x");
$y = $this->getConfigurationSetting("y");
$x2 = $this->getConfigurationSetting("x2");
$y2 = $this->getConfigurationSetting("y2");
$w = $this->getConfigurationSetting("width");
$h = $this->getConfigurationSetting("height");

$variables = "";
if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator() && $isNotInTest) {
    if ($x && $y && $w && $h) {
        $variables = "x='$x' y='$y' x2='$x2' y2='$y2' w='$w' h='$h'";
    }
    
    $variables .= " useCrop='y'";
}
?>

<div class="croppedImage QuestBackImage" imageLoadedTrigger="QuestBackImage" <? echo $variables ?>>
    <?
    $this->wrapApp("831647b5-6a63-4c46-a3a3-1b4a7c36710a", "image");
    ?>
</div>

<?
$this->printNextButton();
?>
<script>
    
</script>