<?php
/* @var $this \ns_dabb8a85_f593_43ec_bf0d_240467118a40\News */
?>

<div gstype="form" method="saveAppInstanceSettings">
    <table width="80%" class="contactConfigTable">
    <tr>
        <td width="50%">News list id</td>
        <td width="50%">
            <input gsname="setting_newslistid" value="<?php echo $this->getConfigurationSetting("newslistid"); ?>">
        </td>
    </tr>
    </table>
    <input gstype="submit" type="button" value='Save' class='logoutclick'>
</div>
