<?
/* @var $this ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e\GetShopPriceModel */

$rooms = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['rooms']) ? $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['rooms'] : 0;
$locks = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['locks']) ? $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['locks'] : 0;
$salespoints = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['salespoints']) ? $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['salespoints'] : 0;
$restaurantEntryPoints = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['restaurantEntryPoints']) ? $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['restaurantEntryPoints'] : 0;
$entrancelocks = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['entrancelocks']) ? $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['entrancelocks'] : 0;
$selfcheckinindoor = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['selfcheckinindoor']) ? $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['selfcheckinindoor'] : 0;
$selfcheckinoutdoor = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['selfcheckinoutdoor']) ? $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['selfcheckinoutdoor'] : 0;
$pgas = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['pgas']) ? $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['pgas'] : 0;
$customwebsite = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['customwebsite']) && $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['customwebsite'] === "true";
$directbylocks = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['directbylocks']) && $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['directbylocks'] === "true";
$integrationtoaccounting = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['integrationtoaccounting']) && $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['integrationtoaccounting'] === "true";
$getshopdosetup = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['getshopdosetup']) && $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['getshopdosetup'] === "true";
$getshopinstalllocks = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['getshopinstalllocks']) && $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['getshopinstalllocks'] === "true";
$getshoptraining = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['getshoptraining']) && $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['getshoptraining'] === "true";
$currency = isset($_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['currency']) ? $_SESSION['ns_94c0992f_85d5_4a63_a30c_685ee0f8b17e_calcdata']['currency'] : "1";

$customwebsite = $customwebsite ? 'checked="true"' : "";
$directbylocks = $directbylocks ? 'checked="true"' : "";
$integrationtoaccounting = $integrationtoaccounting ? 'checked="true"' : "";
$getshopdosetup = $getshopdosetup ? 'checked="true"' : "";
$getshopinstalllocks = $getshopinstalllocks ? 'checked="true"' : "";
$getshoptraining = $getshoptraining ? 'checked="true"' : "";
?>

<h1>Pricing</h1>
* Enter what you need below, the total will be shown under.
<div class='row'>
    <div class='col1'>Currency</div>
    <div class='col2'>
        <select class='gsniceselect1 inputvalue currency' >
            <option value='1' <? echo $currency == "1" ? 'selected="true"' : ""; ?>>USD</option>
            <option value='2' <? echo $currency == "2" ? 'selected="true"' : ""; ?>>NOK</option>
            <option value='3' <? echo $currency == "3" ? 'selected="true"' : ""; ?>>EUR</option>
        </select>
    </div>
</div>

<div class='row'>
    <div class='col1'>Number of rooms</div>
    <div class='col2'><input type='text' class='gsniceinput1 inputvalue rooms' value='<? echo $rooms; ?>'></div>
</div>

<div class='row'>
    <div class='col1'>Number of locks (hotel room)</div>
    <div class='col2'><input type='text' class='gsniceinput1 inputvalue locks' value='<? echo $locks; ?>'></div>
</div>

<div class='row'>
    <div class='col1'>Number of locks (common entrance)</div>
    <div class='col2'><input type='text' class='gsniceinput1 inputvalue entrancelocks' value='<? echo $entrancelocks; ?>'></div>
</div>

<div class='row'>
    <div class='col1'>Number of self check in terminal (indoor)</div>
    <div class='col2'><input type='text' class='gsniceinput1 inputvalue selfcheckinindoor' value='<? echo $selfcheckinindoor; ?>'></div>
</div>

<div class='row'>
    <div class='col1'>Number of self check in terminal (outdoor)</div>
    <div class='col2'><input type='text' class='gsniceinput1 inputvalue selfcheckinoutdoor' value='<? echo $selfcheckinoutdoor; ?>'></div>
</div>

<div class='row'>
    <div class='col1'>Number of restaurant kiosks</div>
    <div class='col2'><input type='text' class='gsniceinput1 inputvalue restaurantEntryPoints' value='<? echo $restaurantEntryPoints; ?>'></div>
</div>

<div class='row'>
    <div class='col1'>Number of PGA's</div>
    <div class='col2'><input type='text' class='gsniceinput1 inputvalue pgas' value='<? echo $pgas; ?>'></div>
</div>

<div class='row'>
    <div class='col1'>SalesPoints</div>
    <div class='col2'><input type='text' class='gsniceinput1 inputvalue salespoints' value='<? echo $salespoints; ?>'></div>
</div>

<div class='row'>
    <div class='col1'>I want a custom made website</div>
    <div class='col2'><input type='checkbox' class='selection inputvalue customwebsite' <? echo $customwebsite; ?> ></div>
</div>

<div class='row'>
    <div class='col1'>I need integration to accounting</div>
    <div class='col2'><input type='checkbox' class='selection inputvalue integrationtoaccounting' <? echo $integrationtoaccounting; ?>></div>
</div>

<div class='row'>
    <div class='col1'>Have GetShop set up the booking system</div>
    <div class='col2'><input type='checkbox' class='selection inputvalue getshopdosetup' <? echo $getshopdosetup; ?>></div>
</div>

<div class='row'>
    <div class='col1'>Have GetShop install the locks</div>
    <div class='col2'><input type='checkbox' class='selection inputvalue getshopinstalllocks' <? echo $getshoptraining; ?>></div>
</div>

<div class='row'>
    <div class='col1'>Include GetShop's training program</div>
    <div class='col2'><input type='checkbox' class='selection inputvalue getshoptraining' <? echo $customwebsite; ?>></div>
</div>

<div class='row'>
    <div class='col1'>Buyer buys locks directly from Locstar</div>
    <div class='col2'><input type='checkbox' class='selection inputvalue directbylocks' <? echo $directbylocks; ?>></div>
</div>
<br>
<br>
<br>
<div class="summary">
    <? $this->includefile("summary"); ?>
</div>



<div class="emailoffer" link='' gstype="form" method="sendOffer">
    <h2><? echo $this->__f("Save this offer for later"); ?></h2>
    <input type="hidden" gsname="link" value=""/>
    <input class="gsniceinput1" type="" gsname="email" placeholder="Your email address"/>
    <br/>
    <br/><div class="shop_button" gstype="submit">Send offer to me</div>
    
    <?
    if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
        ?>
        <hr/>
        <br/>Discount total cost %: <input gsname="discounttotal" class="inputvalue gsniceinput1"/>
        <br/>Discount license %: <input gsname="discountlicense" type='textfield' class="inputvalue gsniceinput1"/> 
        <br/><br/><div class='shop_button' gstype="downloadpdf" filename="GetShop Offer.pdf" method="downloadPdf">Download offer</div>
        <?
    }
    ?>
</div>
<?php
if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
    ?>
    <center>
        <h1>Connect offer to lead</h1>
        <input class='gsniceinput1 searchlead' gstype='submitenter'>
        <div class='leadlist'></div>
    </center>
    <?php
}
?>


<style>
    .row { clear:  both; margin-bottom: 5px; }
    .col1 { width: 340px; display:inline-block; float:left; line-height: 35px; }
    .col2 .gsniceinput1 { width: 30px; text-align: center;}
    .col2 { text-align: center; width: 100px; float:left; }
    .col2 .selection { width: 30px; height: 30px; }
</style>
    