<?
/* @var $this \ns_c3f32e06_365b_4c7f_995a_79012b9ea0fe\AccountingGeneralSettings */
$config = $this->getApi()->getPaymentManager()->getStorePaymentConfiguration($_POST['data']['id']);
$value = $config ? $config->userCustomerNumber : "";
$description  = $config && isset($config->accountingDescription) ? $config->accountingDescription : "";
?>

<div gstype="form" method="savePaymentMethod">
    <input type='hidden' gsname='id' value='<? echo $_POST['data']['id']; ?>'/>
    <? echo $this->__f("Accounting description"); ?>:
    <br/><input class="gsniceinput1" gsname='accountingDescription' value="<? echo $description; ?>"/>
    <br/><? echo $this->__f("Customer Number"); ?>:
    <br/><input class="gsniceinput1" gsname='customernumber' value="<? echo $value; ?>"></input> <div class="shop_button" gstype='submit'><? echo $this->__f("Save"); ?></div>
</div>