<?
/* @var $this \ns_c3f32e06_365b_4c7f_995a_79012b9ea0fe\AccountingGeneralSettings */
$config = $this->getApi()->getPaymentManager()->getStorePaymentConfiguration($_POST['data']['id']);
$value = $config ? $config->userCustomerNumber : "";
$customernumberpaid = $config ? $config->userCustomerNumberPaid : "";
$description  = $config && isset($config->accountingDescription) ? $config->accountingDescription : "";
$offsetAccountingId_accrude  = $config && isset($config->offsetAccountingId_accrude) ? $config->offsetAccountingId_accrude : "";
$offsetAccountingId_prepayment  = $config && isset($config->offsetAccountingId_prepayment) ? $config->offsetAccountingId_prepayment : "";
?>

<div gstype="form" method="savePaymentMethod">
    <input type='hidden' gsname='id' value='<? echo $_POST['data']['id']; ?>'/>
    <? echo $this->__f("Accounting description"); ?>:
    <br/><input class="gsniceinput1" gsname='accountingDescription' value="<? echo $description; ?>"/>
    <br/><? echo $this->__f("Customer Number"); ?>:
    <br/><input class="gsniceinput1" gsname='customernumber' value="<? echo $value; ?>"></input> 
    <br/><? echo $this->__f("Customer Number Paid"); ?>:
    <br/><input class="gsniceinput1" gsname='customernumberpaid' value="<? echo $customernumberpaid; ?>"></input> 
    <br/><? echo $this->__f("Accounting Offset Account (Accrude)"); ?>:
    <br/><input class="gsniceinput1" gsname='offsetAccountingId_accrude' value="<? echo $offsetAccountingId_accrude; ?>"></input> 
    <br/><? echo $this->__f("Accounting Offset Account (PrePayment)"); ?>:
    <br/><input class="gsniceinput1" gsname='offsetAccountingId_prepayment' value="<? echo $offsetAccountingId_prepayment; ?>"></input> 
    <br/>
    <br/><div class="shop_button" gstype='submit'><? echo $this->__f("Save"); ?></div>
</div>