
<div class="blockquote-wrapper">
  <div class="blockquote">
    <h1>
     If You Want To Go Fast, <span style='color: #FFF;'>Go Alone</span>. If You Want To Go Far, <span style='color: #FFF;'>Go Together</span>
     </h1>
      <h4>&mdash; Forbes<br><em><a target='_blank' href='https://www.forbes.com/sites/michaelsimmons/2013/07/22/power-of-relational-thinking/#495f493f10e3'><span style='color: #FFF;'> ref: Forbes Artikkel</span></a></em></h4>
  </div>
</div>



<div class='pagerowinner'>
    <div>
        <h2>VISJON</h2>
        <div style='margin-bottom: 50px'>
            GetShop AS har som mål å bli ledende i Europa innenfor hotellsystemer innen 2025 og på verdensbasis innen 2030. 
            Første kapitalinnskudd vil være med på å sterke sin posisjon i Nord-Europa ved å opprette salgsavdelinger i England, Tyskland, Nederland og Sverige.
            <br/><br/>GetShop har i dag en unik teknologi-stack som er velutviklet, testet og klar for en kraftig ekspansjon. 
        </div>
    </div>
</div>



<section id=timeline>
	<h1>GetShop Teknologi Stack</h1>
        <p class="leader">Teknologien under utgjør et fullverdig hotell-system som fungerer på små, medium og store hoteller. Systemene er utviklet over en periode på 5 år og har rundt 15.000 endringer siden oppstart. <br/><br/>Rundt 30.000 timer jobb er lagt ned i utvikling av programvaren.</p>
	<div class="demo-card-wrapper">
		<div class="demo-card demo-card--step1">
			<div class="head">
				<div class="number-box">
					<span>01</span>
				</div>
				<h2><span class="small">Property Management System</span> Bookingsystem</h2>
			</div>
			<div class="body">
				<p>
                                    Et fullverdig bookingsystem med automatikk langt over hva våre konkurenter har. På nåværende tidspunkt er det rundt 40 hoteller som benytter systemet daglig og totalt har systemet håndtert rundt 300 000 gjester siden Aug 2016. 
                                    <br/>
                                    <br/><b> Systemet håndterte kapital i 2018 for:</b> Kr 155.000.000,-
                                    <br/><b> Fordelt på antall betalinger: </b> 64900 stk.
                                    <br/>
                                    <br/> Estimert omsetning i systemet 2019 er 330 000 000 og da vil systemet behandle 270.000 gjester årlig.
                                    <br/><br/><b>Største konkurenter</b>: Opera, Hoist, Protell
                                    <br/><b>Andre mindre konkurenter</b>: Mews, Sirvoy, CloudBeds
                                </p>
                                <a href='/?page=pms' target='_blank'><div style='width: 100%; background-color: #333; color: #FFF; padding: 5px; position: absolute;  bottom: 0px; lefT: 0px; right:0px; text-align: center;' >Les mer om systemet her</div></a>
			</div>
		</div>

		<div class="demo-card demo-card--step2">
			<div class="head">
				<div class="number-box">
					<span>02</span>
				</div>
				<h2><span class="small">Adgangskontrollsystem</span> APAC</h2>
			</div>
			<div class="body">
				<p>Adgangskontrollsystemet er utviklet med tanke på hotell-automatisering og er unikt i sin klasse. Det er godt egnet for små hoteller, til store hoteller og er 100% cloud. Installasjonen er enkel og kan erstatte de fleste låser på markedet.
                                    <br/><br/><b>Antall låser levert av GetShop</b>: Ca 1000 stk.
                                    <br/><br/><b>Største konkurenter</b>: Assa Hospitality, Kaba, Hoist, OpenKey, 4-suit
                                    
                                    <br/><br/><span style="font-style: italic">Cloud access control system vil ta en dominant posisjon i markedet, her ønsker vi å posisjonere oss sterkere.</span>
                                </p>
                                <a href='/?page=apac' target='_blank'><div style='width: 100%;bottom: 0px;  background-color: #333; color: #FFF; padding: 5px; position: absolute; lefT: 0px; right:0px; text-align: center;' >Les mer om systemet her</div></a>
			</div>
		</div>

		<div class="demo-card demo-card--step3">
			<div class="head">
				<div class="number-box">
					<span>03</span>
				</div>
				<h2><span class="small">Cloud</span> Kassesystem</h2>
			</div>
			<div class="body">
                            <p>
                                De fleste hoteller har kiosk, campingplass etc og trenger derfor et kasse-system. GetShop har utviklet et kassesystem som fungerer til SBM og MBM. Systemet er 100% cloud-bassert, enkelt å lære seg og fungerer godt for kiosker, restauranter og som ekstrasalg i respesjoner.  
                                <br/>
                                <br/><b>Funksjoner:</b> Thermoskriver, Integrert betalingsterminaler, Bongskriver for kjøkkenets kokker.
                            </p>
                            <a href='/?page=pos' target='_blank'><div style='width: 100%;bottom: 0px;  background-color: #333; color: #FFF; padding: 5px; position: absolute; lefT: 0px; right:0px; text-align: center;' >Les mer om systemet her</div></a>
			</div>
		</div>

		<div class="demo-card demo-card--step4">
			<div class="head">
				<div class="number-box">
					<span>04</span>
				</div>
				<h2><span class="small">Selvbetjeningsterminal</span> Terminal</h2>
			</div>
			<div class="body">
				<p>Våre selvbetjente terminaler for utendørs og innendørs bruk. Utstyrt med kvitteringsskriver og kort-terminal, samt en touch-skjerm.
                                <br/>
                                <br/> Terminalene er ekstratilskudd til systemet da alt kan gjøres via mobil, likevel er det enkelte hotell-eiere som ønsker å tilby denne tjenesten til sine gjester.
                                <br/> 
                                <br/><b> Største konkurenter:</b> Ariane
                                
                                <br/> 
                                <br/> <span style='font-style: italic'> Kioskene kan også brukes på andre områder dersom det er ønskelig å satse på et større område</span>
                                </p>
                                <a href='/?page=terminals' target='_blank'><div style='width: 100%;bottom: 0px;  background-color: #333; color: #FFF; padding: 5px; position: absolute; lefT: 0px; right:0px; text-align: center;' >Les mer om systemet her</div></a>
			</div>
		</div>

		<div class="demo-card demo-card--step5">
			<div class="head">
				<div class="number-box">
					<span>05</span>
				</div>
				<h2><span class="small">Personal Guest Assistant</span> PGA </h2>
			</div>
			<div class="body">
                            <p>
                                Et unikt software laget for å av-laste resepsjonistene. Gjestene kan selv gjøre handlinger som vanligvis ikke er mulig uten å kontakte resepsjonen, slik som utvide oppholdet, bytte rom osv. Dette er mulig pga den unike teknologien utviklet av bookingsystemet, adgangskontrollsystemet og online betalingstjenestene.
                                <br/> 
                                <br/> Det finnes noen som har tilsvarende løsninger på markedet, men det er ikke noen som er like godt integrert i systemet som hva vi har da vi har hele stacken.
                                <br/>
                                <br/><b> Største konkurenter:</b> Softbank 
                                <br/>
                              
                            </p>
                            <a href='/?page=pga' target='_blank'><div style='width: 100%;bottom: 0px;  background-color: #333; color: #FFF; padding: 5px; position: absolute; lefT: 0px; right:0px; text-align: center;' >Les mer om systemet her</div></a>
			</div>
		</div>
    
                <div class="demo-card demo-card--step2">
			<div class="head">
				<div class="number-box">
					<span>06</span>
				</div>
				<h2><span class="small">Online booking form</span> BookingEngine</h2>
			</div>
			<div class="body">
				<p>Dette er rett og slett en plugin som hotell-eierene kan benytte på hvilken som helst av sine nettsider. Denne teknologien muliggjør at det er enkelt for hotell-gjestene å bestille nye opphold og betale for dem.
                                <br/>
                                <br/><b> Største konkurenter:</b> Ingen
                                
                                </p>
                                <a href='/?page=onlinebooking' target='_blank'><div style='width: 100%;bottom: 0px;  background-color: #333; color: #FFF; padding: 5px; position: absolute; lefT: 0px; right:0px; text-align: center;' >Les mer om systemet her</div></a>
			</div>
		</div>
	</div>
        
        
</section>


<div style='text-align: center; font-size: 30px; padding: 50px; color: #FFF;'> Markedsanalyser </div>
<div style='max-width: 1000px; margin: 0 auto; margin-bottom: 100px; background-color: #FFF; padding: 50px;'>
    <h3>Property Management System</h3>
    <br/> Kundegruppe: små, medium og store hoteller. 
    <br/> Antall hoteller i Norge: 887 / ref: <a href='https://www.ssb.no/en/overnatting' target='_blank'>SSB</a>
    <br/> Total markedsverdi i Norge: 44.350.000,- (Oppstartsinntekter)
    <br/> Total markedsverdi i Norge: 28.383.996,- (Årlige inntekter)
    <br/>
    <br/> Nåværende markedsandel i Norge: 3.38%.
    <br/>
    <br/> <b>Utlandet</b>
    <br/> Ved å benytte innbyggertallene i de forskjellige landene og øke dette proposjonalt med markedsverdien i Norge kan vi finne ut en estimert markedsverdi til landene vi ønsker å etablere oss i. Landene har også en relativ lik økonomi i forhold CPI.
    <br/>
    <br/> Total markedsverdi i Sverige ( Faktor: 1.9 ): 84.265.000,- (Oppstartsinntekter)
    <br/> Total markedsverdi i Sverige ( Faktor: 1.9 ): 53.929.592,- (Årlige inntekter)
    <br/>
    <br/> Total markedsverdi i England ( Faktor: 12,55 ): 556.592.500,- (Oppstartsinntekter)
    <br/> Total markedsverdi i England ( Faktor: 12,55 ): 356.219.149,- (Årlige inntekter)
    <br/>
    <br/> Total markedsverdi i Tyskland ( Faktor: 15,74 ): 698.069.000,- (Oppstartsinntekter)
    <br/> Total markedsverdi i Tyskland ( Faktor: 15,74 ): 446.764.097,- (Årlige inntekter)
    <br/>
    <br/> Total markedsverdi i Nederland ( Faktor: 3,24 ): 143.694.000,- (Oppstartsinntekter)
    <br/> Total markedsverdi i Nederland ( Faktor: 3,24 ): 91.964.147,- (Årlige inntekter)
    <br/>
    <br/> Samlet markedsverdi satsningsland: 1.482.620.500,- (Oppstartsinntekter)
    <br/> Samlet markedsverdi satsningsland: 948.876.985,- (Årlige inntekter)
    <br/>
    <br/><span style='font-style: italic; color: green; font-weight: bold;'> Etter innvisteringspakken er gjennomført skal GetShop ha samme markedsandler i angitte land som vi på nåværende tidspunkt har i Norge. Dette vil gi en månedlig inntekt på 2.67 millioner og en oppstartsinntekt på 50.1 millioner.</span>
    <br/>
    <br/>
    <h3>Adgangskontrollsystem / Låser</h3>
    <br/> Ved å benytte faktorene regnet ut over kan vi konkludere med at det er ca 29652 hoteller i de angitte landene. 
    <br/>
    <br/> Totalt hoteller: 29652
    <br/> Antall hoteller ved 3% markedsandel: 889
    <br/> Statistisk lås-salg pr hotell: 33 stk
    <br/> Total solgte låser ved 3% markedandel: 29337
    <br/> Avanse pr lås: Kr 800,-
    <br/> Installasjons-inntekter pr lås: Kr 900,-
    <br/>
    <br/><span style='font-style: italic; color: green; font-weight: bold;'> Etter innvisteringspakken er gjennomført skal GetShop ha solgt låser med en avanse på rundt NOK 23.469.600,-. Samtidig skal det være tatt inn ca 26 millioner i inntekter ved installasjon av låsene.</span>
    <br/>
    <br/>
    
    <h3>Oppsummering</h3>
    <br/> <b> Samlet markedsverdi i landene (Oppstartinntekter + månedsinntekter + låser/adgangskontrollsystem): </b><div style='color: green; font-size: 25px; font-weight: bold; padding: 20px; text-align: centeR;'> 5.122.416.485</div>
    
    <br/> Inntekter oppstartskostander bookingsystem: 50,1 mill
    <br/> Akkumulert månedsinntekter over 36 måneder: 24 mill
    <br/> Salg låser uten hardware kostnader: 49 mill
    <br/> <span style='font-weight: bold; color: green;'>Total salgsinntekter: 123 millioner.</span>
</div>




<div style='text-align: center; font-size: 30px; padding: 50px; color: #FFF; padding-bottom: 20px; background-color: #0A0A0A'> Framdriftsplan </div>

<div style='color: #FFF; text-align: center; padding: 30px; background-color: #0A0A0A'>
    Framdrifsplanen under er antall måneder etter invisteringspakken har startet.
</div>

<div class='timeline_outer'>    
    <div class="entries2">
      <div class="entry2">
        <div class="title2">T +0</div>
        <div class="timelinebody">
          <p>Jobber med å lete etter og ansette daglig leder som kan gjennomføre veksten.</p>
        </div>
      </div>
      <div class="entry2">
        <div class="title2">T +3</div>
        <div class="timelinebody">
          <p>
              Daglig leder starter å sette opp salgskontorer og finne selgere til de angitte landene.
          </p>
        </div>
      </div>
      <div class="entry2">
        <div class="title2">T +7</div>
        <div class="timelinebody">
          <p>Salgskontorene er etablert i de gitte land. Starter med markedsføring og salgsaktiviter. </p>
        </div>
      </div>
      <div class="entry2">
        <div class="title2">T +12</div>
        <div class="timelinebody">
            <p>
                De første salgene blir landet ved hjelp av de nye selgerene.
            </p>
        </div>
      </div>
      <div class="entry2">
        <div class="title2">T +1 år</div>
        <div class="timelinebody">
          <p>
              Salgene og leveranser gjennomføres som planlagt. Ansetter flere system-utviklere, supportmedarbeidere og project-managers.
          </p>
        </div>
      </div>
      <div class="entry2">
        <div class="title2">T +2 år</div>
        <div class="timelinebody">
          <p>
              Økning av flere ansatte der hvor det skulle være behov.
          </p>
        </div>
      </div>
    </div>
</div>
<br/>
<div class='pagerowinner'>
    <h1>Kapitalbehov</h1>
    <div>
        Samlet kapitalbehoved for å gjennomføre visjonen..
        <div>
            <div class="row"><div class="col col_1">5 x Selgere</div><div  class="col col_2">8.000.000,-</div></div>
            <div class="row"><div class="col col_1">2 x software utvikler</div><div class="col col_2">1.500.000,-</div></div>
            <div class="row"><div class="col col_1">1 x Konsernleder</div><div class="col col_2">1.500.000,-</div></div>
            <div class="row"><div class="col col_1">Markedsføringsbudsjett</div><div class="col col_2">2.000.000,-</div></div>
            <br/>
            <div>
                Total kapitalbehov for 2 år<br/>etter 2 år skal selskapet være selvstendig og kunne genere overskudd.
                <br/><br/><b style='font-size: 30px;'>Kr 13.000.000,-</b>
            </div>
        </div>
    </div>
    <br/>
    <br/>
    <br/>
</div>
<br/>
