<?php
/* @var $this \ns_139d9335_2353_48fe_aae5_abc4268fc14e\PmsDayOverview */
$filter = $this->getSelectedFilter(true);
$bookings = $this->getApi()->getPmsManager()->getAllBookings($this->getSelectedName(), $filter);
$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
$items = $this->indexList($items);

?>
<span gstype="form" method="changeDate">
    <input type="date" value="<?php echo date('Y-m-d', $this->getSelectedDate()); ?>" gsname="date">
    <input type="button" gstype="submit" value="Change date">
</span>
<?php

echo "<h1>Checking in today</h1>";
printCheckingTodayTable($bookings, $items, $filter, $this);

$filter = $this->getSelectedFilter(true, 1);
$bookings = $this->getApi()->getPmsManager()->getAllBookings($this->getSelectedName(), $filter);
echo "<h1>Checking in tomorrow</h1>";
printCheckingTodayTable($bookings, $items, $filter, $this);


function printCheckingTodayTable($bookings, $items, $filter,$object) {
    echo "<table width='100%' cellspacing='0' cellpadding='0'>";
    echo "<tr>";
    echo "<th>Room</th>";
    echo "<th>Bookers name</th>";
    echo "<th>Guest name</th>";
    echo "<th>Guest phone</th>";
    echo "<th>Guest email</th>";
    echo "</tr>";

    $roomList = array();
    foreach($bookings as $booking) {
        foreach($booking->rooms as $room) {
            $pmsManager = new ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement();
            if(!$pmsManager->isActive($room, $filter)) {
                continue;
            }
            $room->userId = $booking->userId;
            $roomList[$items[$room->bookingItemId]->bookingItemName] = $room;
        }
    }

    ksort($roomList);

    foreach($roomList as $room) {
        $user = $object->getApi()->getUserManager()->getUserById($room->userId);
        echo "<tr>";
        echo "<td>" . $items[$room->bookingItemId]->bookingItemName . "</td><td>" . $user->fullName . "</td>";
        echo "<td>" . $room->guests[0]->name . "</td>";
        echo "<td>" . $room->guests[0]->phone . "</td>";
        echo "<td>" . $room->guests[0]->email . "</td>";
        echo "</tr>";
    }

    echo "</table>";    
}


$filter = $this->getSelectedFilter(false);
$bookings = $this->getApi()->getPmsManager()->getAllBookings($this->getSelectedName(), $filter);
$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
$items = $this->indexList($items);
if(!$bookings) {
    $bookings = array();
}
echo "<h1>Checking out today</h1>";
echo "<table width='100%' cellspacing='0' cellpadding='0'>";
echo "<tr>";
echo "<th>Room</th>";
echo "<th>Bookers name</th>";
echo "<th>Guest name</th>";
echo "<th>Guest phone</th>";
echo "<th>Guest email</th>";
echo "</tr>";

$roomList = array();
foreach($bookings as $booking) {
    foreach($booking->rooms as $room) {
        $pmsManager = new ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement();
        if(!$pmsManager->isActive($room, $filter)) {
            continue;
        }
        $room->userId = $booking->userId;
        $roomList[$items[$room->bookingItemId]->bookingItemName] = $room;
    }
}

ksort($roomList);

foreach($roomList as $room) {
    $user = $this->getApi()->getUserManager()->getUserById($room->userId);
    echo "<tr>";
    echo "<td>";
    echo $items[$room->bookingItemId]->bookingItemName . "</td>";
    echo "<td>";
    if($room->keyIsReturned) {
        echo "<i class='fa fa-key' style='color:green;'></i> ";
    }

    echo $user->fullName . "(" . $user->cellPhone . ") ". "</td>";
    echo "<td>" . $room->guests[0]->name . "</td>";
    echo "<td>" . $room->guests[0]->phone . "</td>";
    echo "<td>" . $room->guests[0]->email . "</td>";
    echo "</tr>";    
}

echo "</table>";

$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
echo "<br><br>";
echo "Current code is: " . $config->extraField . "<br>";
?>
<div gstype="form" method="updatecode">
    <input type="txt" gsname="code">
    <input type="button" gstype="submit" value="Set new code">
</div>
<br><br>
<h1>Keydrop</h1>
Click on the room where the key has been returned.<br>
<?php
$rooms = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
foreach($rooms as $room) {
    $marked = "";
    $found = $this->markedAsReturned($room->id);
    if($found === "notinuse") {
        $marked = "style='background-color:gray;'";
    } elseif($found == true) {
        $marked = "style='background-color:green;color:#fff;'";
    }
    echo "<span class='keyreturnedroom' roomid='".$room->id."' $marked>" . $room->bookingItemName . "</span>";
}
?>