<?php
namespace ns_9d94feed_f4fd_4e6d_8be8_81aa89f58dcf;
/* @var $this EventPartitipationData */
$data = $this->getApi()->getCalendarManager()->getEventPartitipatedData($this->getPage()->id);
$title = "";
$title2 = "";
$text = "";
$heading = "";
if($data) {
    $title = $data->title;
    $title2 = $data->title2;
    $text = $data->body;
    $heading = $data->heading;
}
?>
<? echo $this->__f("This is where you configure the text you would like to put on your diploma. The variables helps you personalise the diploma."); ?>
<br>
<br>
Variables:<bR>
%title% - The given title of the event<bR>
%date% - The given date for the event<bR>
%name% - The name of the partipiant.<bR>
%year% - The year for the event.<bR>
%month% - The month for the event.<bR>
%day% - The day for the event.<bR>
<br>
<? echo $this->__f("Title"); ?>
<input type="text" class="eventtitle" value="<? echo $title; ?>">
<br>
<br>
<? echo $this->__f("Secondary title"); ?>
<input type="text" class="eventtitle2" value="<? echo $title2; ?>">
<br>
<br>
<? echo $this->__f("Text heading"); ?>
<input type="text" class="heading" value="<? echo $heading; ?>">
<br>
<br>
<? echo $this->__f("Text"); ?>
<textarea class="eventtext"><? echo $text; ?></textarea>
<span class="gs_button save_event_partition_data"><? echo $this->__f("Save"); ?></span>

<?
if ($this->getFactory()->getStore()->id == "2fac0e57-de1d-4fdf-b7e4-5f93e3225445" && \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
?>
<div style="border: solid 1px #EEE; margin-top: 30px; padding: 20px;">
    Download complete user-reports:
    <?
    foreach ($this->getApi()->getUserManager()->getAllGroups() as $group) {
        $pageId = $this->getFactory()->getPage()->id;
        $groupId = $group->id;
        echo " <a ignorenavigateWithJavascript='true' href='/generateExcelReportAllNorway.php?pageId=$pageId&group=$groupId&type=calendarbookedusers'>$group->groupName</a> ";
    }
    ?>
</div>
<?
}
?>
    