<?
/* @var $this ns_99e7671e_1f11_4902_8459_faa3aaeeb885\MecaFleetCommunication */
$mecaCar = $this->getApi()->getMecaManager()->getCarByPageId($this->getPage()->getId());
$inviteSentClass = $mecaCar->inivitationSent != null ? "inviteSent" : "";
$fleet = $this->getApi()->getMecaManager()->getFleetByCar($mecaCar);

if (!$mecaCar) {
    echo "Did not find the car";
    return;
}
?>

<div class="fleetinformation">
    Flåte: <? echo $this->getApi()->getMecaManager()->getFleetByCar($mecaCar)->name; ?>
    <br/> 
    <?
    if ($fleet->followup) {
        echo "Dette er en manuell flåte";
    } else {
        echo "Dette er en automatisk flåte";
    }
    ?>
    <br/>
    
    <div class="shop_button" gs_show_modal="newcar" createnewcaronfleet="<? echo $fleet->id; ?>">Opprett nytt kjøretøy i flåten</div>
</div>

<?
if ($fleet->followup) {
    return;
}
?>
<br/>
<br/>
<div style="text-align: center;"><strong><span style="font-size:36px;">Kommunikasjon med bruker av kjøretøy</span></strong><br>
<br>
Her ser du status&nbsp;på om bruker av kjøreøy har tatt i bruk MECA Fleet app. Send&nbsp;purring dersom vedkommende ikke tar i bruk appen.</div>

<div>
    <div class="row">
        <div class="number">1</div>
        <div class="description">
            Kontroller informasjonen under "Bilkonfigurasjon". <br/>
            Når du er sikker på at denne er riktg trykker du på "Send invitasjon". 
        </div>
            
        <div class="shop_button <? echo $inviteSentClass; ?>" gsclick="sendInvitation" carid="<? echo $mecaCar->id; ?>">
            <? 
            if ($inviteSentClass) { 
                echo "Invitasjon sendt <br/> ".date("d/m-Y H:i", strtotime($mecaCar->inivitationSent))."";
            } else { 
                echo "Send invitasjon";
            } ?>
        
        </div>
    </div>
    
    <div class="row">
        <div class="number">2</div>
        <div class="description">
            Har bileier tatt i bruk appen?<br/>
            Dersom bileieren har begynt å bruke appen vil status til høyre være grønn.
        </div>
            
        <?
        if (count($mecaCar->tokens) > 0) {
        ?>
            <div class="appstatus confirmed"><i class="fa fa-check"></i></div>
        <? } else { ?>
            <div class="appstatus negative"><i class="fa fa-close"></i></div>
        <? } ?>
    </div>
</div>