<div class='result'>
    <?
    if (!isset($_SESSION['searchKey']) || $_SESSION['searchKey'] == "") {
        $this->includefile("information");
    } else {
        $key = $_SESSION['searchKey'];
        $result = $this->getSearchResult($key);
        
        if (count($result->products) == 0) {
            echo "<div class='noresult'><i class='fa fa-warning'></i> No result, please try another search criteria</div>";
        } else {
            $nextPageId = $result->pageNumber < $result->totalPages ? $result->pageNumber + 1 : $result->totalPages;
            $prevPageId = $result->pageNumber > 1 ? $result->pageNumber - 1 : 1;

            $next = "<a href='?searchppage=$nextPageId'>next -></a>";
            $prev = "<a href='?searchppage=$prevPageId'><- prev</a>";
            
            echo "<center>$prev : ".$result->pageNumber."/".$result->totalPages." : $next</center>";
            foreach ($result->products as $prod) { 
                $name = $prod->brand . " " . $prod->model . " " . $prod->engineSize . " " . $prod->power . " " . $prod->year . " " . $prod->originalChecksum ;
                $orgFile = null;

                foreach ($prod->binaryFiles as $binFile) {
                    /* @var $binFile core_sedox_SedoxBinaryFile */
                    if (trim($binFile->fileType) == "Original") {
                        $orgFile = $binFile;
                    }
                }

                /* @var $orgFile core_sedox_SedoxBinaryFile */
                /* @var $prod core_sedox_SedoxProduct */
                $onclick = "";
                if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject() != null) {
                    echo "<a href='?page=productview&productId=".$prod->id."'>";
                } else {
                    $onclick = "onclick='thundashop.common.Alert(\"Login\", \"Please login to see more information about the product\")'";
                }
                ?>
                
                    <div <? echo $onclick; ?> class='sedox_product_box productinfo'>
                        <div class='title'><? echo $name; ?></div>

                        
                        <div class='header'>
                            <div class='col col1'>Created:</div>
                            <div class='col col2'>Orig. Checksum:</div>
                            <div class='col col3'>ECU Brand:</div>
                            <div class='col col4'>ECU Type:</div>
                            <div class='col col5'>ECU Part Nr.:</div>
                            <div class='col col6'>ECU HW Nr.:</div>
                            <div class='col col7'>ECU SW Nr.:</div>
                            <div class='col col8'>Software Version:</div>
                            <div class='col col9'>Size:</div>
                            <div class='col col10'>Tool</div>
                        </div>
                        <div class='row'>
                            <div class='col col1'><? echo $prod->rowCreatedDate; ?></div>
                            <div class='col col2'><? echo $prod->originalChecksum; ?></div>
                            <div class='col col3'><? echo $prod->ecuBrand; ?></div>
                            <div class='col col4'><? echo $prod->ecuType; ?></div>
                            <div class='col col5'><? echo $prod->ecuPartNumber; ?></div>
                            <div class='col col6'><? echo $prod->ecuHardwareNumber; ?></div>
                            <div class='col col7'><? echo $prod->ecuSoftwareNumber; ?></div>
                            <div class='col col8'><? echo $prod->ecuSoftwareVersion; ?></div>
                            <div class='col col9'><? echo $prod->softwareSize; ?></div>
                            <div class='col col10'><? echo $prod->tool; ?></div>
                        </div>
                </div>
                
                <?
                    if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject() != null) {
                        echo "</a>";
                    }
                ?>              

            <? 
            }
            echo "<center>$prev : ".$result->pageNumber."/".$result->totalPages." : $next</center>";
        }
    }
    ?>
</div>
