<?
/* @var $this ns_0c6398b0_c301_481a_b4e7_faea0376e822\ProductList */
$accounts = $this->getApi()->getProductManager()->getAccountingAccounts();
?>
<div gstype="form" method="createNewProduct" class="createnewproductbox">
    <div style="margin-bottom: 5px;"><?echo $this->__f("Create new product");?></div>
    <select class='gsniceselect1' gsname='account'>
        <option value=''>No accounts specified</option>
        <?php
        foreach($accounts as $account) {
            echo "<option value='" . $account->accountNumber."'>" . $account->accountNumber . " (" . $account->description . ")</option>";
        }
        ?>
    </select>
    <input gsname="name" class="gsniceinput1" type="text" placeholder="<? echo $this->__f("Product name"); ?>"> <div gs_callback="app.ProductList.productCreated" class="shop_button" gstype="submit"><? echo $this->__f("Create"); ?></div>
</div>
