<div class="information">
    <?
    echo $this->__f("What is your opening hours?");
    ?>
</div>

<div class="setting onoff" id="isclosed">
    <span class="title"><?php echo $this->__f("Is closed?"); ?></span>
    <div class="onoff config" id="enabletls"></div>
    <div class="description">
        <?php echo $this->__f("If this is enabled it will override time settings and always show closed, can be used for vacations? haha, like there is such things."); ?>
    </div>
</div>

<div class="textfield setting"  id="1open">
    <span class="title"><?php echo $this->__f("Monday open"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 08:00"); ?>
    </div>
</div>
<div class="textfield setting"  id="1close">
    <span class="title"><?php echo $this->__f("Monday close"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 22:00"); ?>
    </div>
</div>

<div class="textfield setting"  id="2open">
    <span class="title"><?php echo $this->__f("Tuesday open"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 08:00"); ?>
    </div>
</div>
<div class="textfield setting"  id="2close">
    <span class="title"><?php echo $this->__f("Tuesday close"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 22:00"); ?>
    </div>
</div>

<div class="textfield setting"  id="3open">
    <span class="title"><?php echo $this->__f("Wednesday open"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 08:00"); ?>
    </div>
</div>
<div class="textfield setting"  id="3close">
    <span class="title"><?php echo $this->__f("Wednesday close"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 22:00"); ?>
    </div>
</div>

<div class="textfield setting"  id="4open">
    <span class="title"><?php echo $this->__f("Thursday open"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 08:00"); ?>
    </div>
</div>
<div class="textfield setting"  id="4close">
    <span class="title"><?php echo $this->__f("Thursday close"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 22:00"); ?>
    </div>
</div>

<div class="textfield setting"  id="5open">
    <span class="title"><?php echo $this->__f("Friday open"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 08:00"); ?>
    </div>
</div>
<div class="textfield setting"  id="5close">
    <span class="title"><?php echo $this->__f("Friday close"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 22:00"); ?>
    </div>
</div>

<div class="textfield setting"  id="6open">
    <span class="title"><?php echo $this->__f("Saturday open"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 08:00"); ?>
    </div>
</div>
<div class="textfield setting"  id="6close">
    <span class="title"><?php echo $this->__f("Saturday close"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 22:00"); ?>
    </div>
</div>

<div class="textfield setting"  id="7open">
    <span class="title"><?php echo $this->__f("Sunday open"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 08:00"); ?>
    </div>
</div>
<div class="textfield setting"  id="7close">
    <span class="title"><?php echo $this->__f("Sunday close"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Example 22:00"); ?>
    </div>
</div>

<div class="textfield setting"  id="onclick_goto_page">
    <span class="title"><?php echo $this->__f("To page"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("When clicking on it, where should you end up?"); ?>
    </div>
</div>

<div class="button savebutton"><div class="rightglare"></div><div class="filler"></div><ins><?php echo $this->__f("Save settings"); ?></ins></div>