<?
/* @var $this \ns_80fe9499_b4f5_41b4_8ce0_89c872b5bd87\AccountProducts */
$products = $this->getProducts();
$taxGroups = $this->getApi()->getProductManager()->getTaxes();
usort($products, array('ns_4404dc7d_e68a_4fd5_bd98_39813974a606\EcommerceProductView','sortProductByName'));
?>
<div class='primitiveaccountingconfig'>
    <div class="product_row sticky">
        <div class="name"><? echo $this->__f("Product name"); ?></div>
        <?
        foreach ($taxGroups as $group) {
            ?>
            <div class="taxes" ><? echo $group->taxRate."%"; ?></div>
            <?
        }
        ?>
    </div>
    <div class='content'>
        <?
        foreach ($products as $product) {
            $deleted = $product->deleted ? "(".$this->__f("Deleted").")" : "";

            if ($product->deleted)
                continue;

            $accountingInformation = $this->getAccountinProductInfoForTaxCode($product, $product->taxGroupObject->groupNumber);
            $accountingNumber = $accountingInformation ? $accountingInformation->accountingNumber : "";
            ?>
            <div class="product_row" gs_show_modal="productview" selectedtab="accounting" productid="<? echo $product->id; ?>" accountingid="<? echo $accountinInfo->id; ?>" taxgroup="<? echo $accountinInfo->taxGroupNumber; ?>">
                <div class="name"> <? echo $product->name ? $product->name : $this->__f("N/A"); ?> <? echo $deleted ?></div>

            <?
            foreach ($taxGroups as $group) {
                $found = false;
                foreach ($product->accountingConfig as $accountinInfo) {
                    $accountingInformation = $this->getAccountinProductInfoForTaxCode($product, $accountinInfo->taxGroupNumber);
                    $accountingNumber = $accountingInformation ? $accountingInformation->accountingNumber : "";
                    $taxGroup = $this->getTaxGroup($accountinInfo->taxGroupNumber, $taxGroups);
                    if ($taxGroup->groupNumber != $group->groupNumber) {
                        continue;
                    }
                    $found = true;
                    ?>
                    <div class="accointingtax" title='Tax <? echo $group->taxRate; ?>%'><? echo $accountingInformation && $accountingInformation->accountingNumber ? $accountingInformation->accountingNumber : "-"; ?></div>
                    <?
                }

                if (!$found) {
                    ?>
                    <div class="accointingtax" title='Tax <? echo $group->taxRate; ?>%'>-</div>
                    <?
                }
            }
            ?>
            </div>            
            <?
        }
        ?>
    </div>
</div>
