<?
/* @var $this \ns_80fe9499_b4f5_41b4_8ce0_89c872b5bd87\AccountProducts */
$products = $this->getApi()->getProductManager()->getAllProductsIncDeleted();
$distinctAccountingNames = array();

foreach ($products as $product) {
    $distinctAccountingNames[] = $product->accountingAccount;
}

$distinctAccountingNames = array_unique($distinctAccountingNames);

$taxes = $this->getApi()->getProductManager()->getTaxes();
foreach ($taxes as $tax) {
    if ($tax->accountingTaxAccount) {
        $distinctAccountingNames[] = $tax->accountingTaxAccount;
    }
}

?>
<div class="product_row">
    <div class="name"><? echo $this->__f("Product name"); ?></div>
    <div class="taxgroup"><? echo $this->__f("Tax group"); ?></div>
    <div class="taxes"><? echo $this->__f("Tax rate"); ; ?></div>
    <div class="taxcode"><? echo $this->__f("Tax code accounting"); ?></div>
    <div class="accountingcode"><? echo $this->__f("Accounting ProductId"); ?></div>
    <div class="accountingcode"><? echo $this->__f("Accounting Account"); ?></div>
</div>
<div gstype="form" method="saveTaxGroups">
    <?
    foreach ($products as $product) {
        if($product->deleted) {
            continue;
        }
        ?>
        <div class="product_row">
            <div class="name"><? echo $product->name ? $product->name : $this->__f("N/A"); ?></div>
            <div class="taxgroup"><? echo $product->taxgroup ; ?></div>
            <div class="taxes"><? echo $product->taxGroupObject != null && $product->taxGroupObject->taxRate; ?></div>
            <div class="taxcode"><input class="gsniceinput1" gsname="taxcode_<? echo $product->id; ?>" value="<? echo $product->sku; ?>"></div>
            <div class="accountingcode"><input class="gsniceinput1" gsname="product_<? echo $product->id; ?>" value="<? echo $product->accountingSystemId; ?>"></div>
            <div class="accointingtax"><input class="gsniceinput1" gsname="accounting_<? echo $product->id; ?>" value="<? echo $product->accountingAccount; ?>"></div>
        </div>
        <?
    }
    ?>
    <div class="shop_button" gstype="submit"><? echo $this->__f("Save"); ?></div>
</div>

<?
if (count($distinctAccountingNames)) {
?>
<div class="distinctAccounts" gstype="form" method="saveAccountingDescription">
    <h2><? echo $this->__f("Accounts"); ?></h2>
    <?
    
    echo "<div class='row_description'>";
        echo "<div class='col accountingid'>".$this->__f("Account name")."</div>";
        echo "<div class='col accountindesc'>".$this->__f("Description")."</div>";
        echo "<div class='col taxcode'>".$this->__f("Tax Code")."</div>";
        echo "<div class='col subaccountid'>".$this->__f("Sub Account Id")."</div>";
        echo "<div class='col subaccountsegment'>".$this->__f("Sub Account Segment")."</div>";
    echo "</div>";

    foreach ($distinctAccountingNames as $accountName) {
        if (!$accountName)
            continue;
        
        $detail = $this->getApi()->getProductManager()->getAccountingDetail($accountName);
        $accountDescription = $detail ? $detail->description : "";
        $accountTaxGroup = $detail ? $detail->taxgroup : "";
        $subaccountid = $detail ? $detail->subaccountid : "";
        $subaccountvalue = $detail ? $detail->subaccountvalue : "";
        
        echo "<div class='row_description'>";
            echo "<div class='col accountingid'>$accountName</div>";
            echo "<div class='col accountindesc'><input gsname='description_$accountName' class='gsniceinput1' value='$accountDescription'></div>";
            echo "<div class='col taxcode'><input gsname='taxcode_$accountName' class='gsniceinput1' value='$accountTaxGroup'></div>";
            echo "<div class='col subaccountid'><input gsname='subaccountid_$accountName' class='gsniceinput1' value='$subaccountid'></div>";
            echo "<div class='col subaccountvalue'><input gsname='subaccountvalue_$accountName' class='gsniceinput1' value='$subaccountvalue'></div>";
        echo "</div>";
    }
    ?>
    <br/>
    <div class="shop_button" gstype="submit"><? echo $this->__f("Save descriptions"); ?></div>
</div>
<?
}
?>
