<?
/* @var $this ns_d02f8b7a_7395_455d_b754_888d7d701db8\Dibs */

$email = $this->getConfigurationSetting("email");
$password = $this->getConfigurationSetting("password");
$originatorid = $this->getConfigurationSetting("originatorid");
?>

<div class='gss_settings_header'>
    <i class='fa fa-cc-visa'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <?php echo $this->getName(); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?php echo $this->getDescription(); ?>
        </div>
    </div>	
</div>

<div class='gss_settings_content'>

    <div class="gss_simple_shipping">
        <div class="textfield gss_setting"  id="email">
            <span class="title"><?php echo $this->__f("Email"); ?></span>
            <input type="textfield" gs_model='sendregningmodel' gs_model_attr='email' value="<? echo $email; ?>">
            <div class="description">
                <?php  echo $this->__f("Email used when logging on to sendregning."); ?>
            </div>
        </div>
        <div class="textfield gss_setting"  id="password">
            <span class="title"><?php echo $this->__f("Password to authenticate"); ?></span>
            <input type="textfield" gs_model='sendregningmodel' gs_model_attr='password' value="<? echo $password; ?>">
            <div class="description">
                <?php  echo $this->__f("Password used when logging on to sendregning."); ?>
            </div>
        </div>
        <div class="textfield gss_setting"  id="originatorid">
            <span class="title"><?php echo $this->__f("Originator id"); ?></span>
            <input type="textfield" gs_model='sendregningmodel' gs_model_attr='originatorid' value="<? echo $originatorid; ?>">
            <div class="description">
                <?php  echo $this->__f("Originator id found when logged on under account settings"); ?>
            </div>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="sendregningmodel" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>
</div>