<?php
if(isset($_POST['data']['selectedlang'])) {
    $_GET['setLanguage'] = $_POST['data']['selectedlang'];
}
$factory = IocContainer::getFactorySingelton();
$factory->read_csv_translation();
$storeTrans = new GetShopTranslation();
$storeTrans->language = $factory->getSelectedTranslation();
$trans = $storeTrans->getStoreTranslations($factory->getStore()->id);
$appName = "";
$incAdmText = false;
$incAdmTextSel = "";
$apps = array();
$selectedApp = "";
$activeLangs = $factory->getLanguageCodes();
$activeLangs[] = $factory->getMainLanguage();

if(isset($_POST['data']['app'])) {
    $selectedApp = $_POST['data']['app'];
}
if(isset($_POST['data']['admintext'])) {
    $incAdmText = $_POST['data']['admintext'] == "true";
    if($incAdmText)
        $incAdmTextSel = "CHECKED";
}

foreach($trans as $tran) {
    if($tran->userLevel > 10 && !$incAdmTextSel) {
            continue;
        }
    $apps[$tran->app] = $tran->app;
}
?>
<div gstype="form" method="loadTranslation">
    <input type='checkbox' gsname='admintext' <?php echo $incAdmTextSel; ?>> Include admin text<br>
    <?php
    echo "<select gsname='selectedlang'>";
    foreach($activeLangs as $lang) {
        $selected = "";
        if($lang == $factory->getSelectedTranslation()) {
            $selected = "SELECTED";
        }
        echo "<option value='$lang' $selected>$lang</option>";
    }
    echo "</select>";
    echo "<select gsname='app'>";
    echo "<option value=''>All application</option>";
    foreach($apps as $app) {
        $selected = "";
        if( $selectedApp == $app) {
            $selected = "SELECTED";
        }
        echo "<option value='$app' $selected>$app</option>";
    }
    echo "</select>";
    ?>
    <input gstype="submitToInfoBox" type="button" value='Update'>
</div>


<div gstype="form" method="saveTranslation">
    <input type="hidden" gsname='app' value='<?php echo $selectedApp; ?>'>
    <input type='hidden' gsname='admintext' <?php echo $incAdmTextSel; ?>>
<table width='100%'>
    <?php
    foreach($trans as $tran) {
        if($tran->userLevel > 10 && !$incAdmTextSel) {
            continue;
        }
        if($selectedApp && $tran->app != $selectedApp) {
            continue;
        }
        if($appName != $tran->app) {
            $appName = $tran->app;
            echo "<tr><td colspan='2'><br><b>" . $appName . "</b></td></tr>";
        }
        echo "<tr>";
        echo "<td width='50%'>" . $this->__f($tran->key) . "</td>";
        echo "<td width='50%'><textarea type='text' gsname='".$tran->key."' style='width:100%; height: 16px;'>".$tran->text."</textarea></td>";
        echo "</tr>";
    }
    ?>
</table>
    <div style='text-align:right;padding-top: 10px;'>
        <input type='button' gstype="submitToInfoBox" value='Save translation'>
    </div>
</div>