<div class='empty_app_area'>
    <div class='content_box'>
        <div class='title'>Add some content</div>
        <div>
            <img src='skin/default/images/add_image.png' title='Add an image' class='add_content_img'>
            <img src='skin/default/images/add_product.png' title='Add a product' class='add_content_img'>
            <img src='skin/default/images/add_text.png' title='Add text content' class='add_content_img'>
            <img src='skin/default/images/add_movie.png' title='Add video content' class='add_content_img'>
        </div>
        <div>+ 36 other applications (<span style='color:#0000FF'>open</span>)</div>
        <div style='color:#0000FF'>import an existing application</div>
            
    </div>
</div>
