<div class='empty_app_area'>
    <div class='content_box'>
        <div class='title'>Add some content</div>
        <div>
            <img src='skin/default/images/add_image.png' title='Add an image' class='add_content_img' appid='831647b5-6a63-4c46-a3a3-1b4a7c36710a'>
            <img src='skin/default/images/add_product.png' title='Import a product' class='add_content_img_noclick' gstype="clicksubmit" method="listproducts" gsvalue="import" gsname="target" output="informationbox" informationtitle="Import a product">
            <img src='skin/default/images/add_text.png' title='Add text content' class='add_content_img' appid='320ada5b-a53a-46d2-99b2-9b0b26a7105a'>
            <img src='skin/default/images/add_movie.png' title='Add video content' class='add_content_img'>
        </div>
        <div>+ 36 other applications (<span style='color:#0000FF; cursor:pointer;' class='empty_app_area_browse_apps'>open</span>)</div>
        <div style='color:#0000FF;cursor:pointer;' class='empty_app_area_browse_importapps'>import an existing application</div>
            
    </div>
</div>