<div class="chromeonly">
    <div>Sorry- Chrome or firefix only!</div>
    <div class="chromeonly_content">
        GetShop administration is only supported by Google Chrome and Mozilla Firefox.<br>
        <br>
        We have decided to only support Google Chrome / firefox to save you the cost it takes support multiple platforms when administrating your web shop.
        <br>
        <br>
        For more information about Google chrome visit:<br>
        <a href='http://www.google.com/chrome/'>http://www.google.com/chrome/</a><br>
        <br>
        Download, run chrome, and log on to your web shop to continue.<br>
        <br>
        Don't worry, we are supporting all major browsers when it comes to using your web shop.<br>
        
        <img class='logo' src='displayImage.php?id=3de3bbd7-551a-4a36-a516-c082b29490bd&height=40'>
        <br><br>
    </div>
</div>

    
<style>
    .chromeonly .logo { float: right; }
    .chromeonly { text-align: center;}
    .chromeonly_content { margin-top: 10px; padding: 10px; width: 600px; border: solid 1px; margin-left:auto; margin-right: auto; text-align: left; }
</style>