<?php
/* @var $factory Factory */
$factory = $this->getFactory();
$pool = $factory->getApplicationPool();
$added = $factory->getApplicationPool()->getAllAddedInstances();
$designs = $pool->getAllApplicationSettingsByType("ThemeApplication");


$addedTheme = "";
$curdesignbg = "inline-block";
foreach ($added as $add) {
    if ($add instanceof ThemeApplication) {
        $addedTheme = $add->applicationSettings->id;
        if(!ApplicationHelper::checkForBackground($add->applicationSettings)) {
            $curdesignbg = "none";
        }
        break;
    }
}

echo "<div class='designpreviews'>";

foreach ($designs as $design) {
    $selected = "";
    if ($design->id === $addedTheme) {
        $selected = "selecteddesign";
    }
    $appname = $design->appName;
    $appid = $design->id;
    $namespace = "ns_" . str_replace("-", "_", $design->id);
    
    $hasbg = ApplicationHelper::checkForBackground($design);
    
    echo "<div class='design $selected' id='$appid' hasbg='$hasbg' style='background-size:160px 140px; background-image:url(\"/showApplicationImages.php?appNamespace=$namespace&image=$appname.png\")'>";
    echo "<span class='price'>" . $design->price . "$ / ".$this->__f("year")."</span>";
    echo "</div>";
}

echo "<span class='prev slider'></span>";
echo "<span class='next slider'></span>";

echo "</div>";

$designArray = array();
?>
<div class='colorselection'>
    <div class='innerbox colorselectbox'>
        <div class='title'><? echo $this->__f("Colors"); ?></div>
        <?
        foreach ($designs as $design) {
            $selected = "";
            if ($design->id === $addedTheme) {
                $selected = "active";
            }

            echo "<div class='designattributes_color $selected' panel='" . $design->id . "'>";
            $result = ApplicationHelper::getApplicationColors($design);
            foreach ($result as $color) {
                echo "<div class='color' color='$color[1]'>";
                echo "<span class='preview' style='background-color:" . $color[2] . ";'></span>";
                echo "<span class='colortext'>" . $color[1] . "</span>";
                echo "</div>";
            }
            if (sizeof($result) == 0) {
                echo $this->__f("No colors available for this design.");
            }
            echo "</div>";
        }
        ?>
    </div>
    <div class='innerbox'>
        <div class='title'><? echo $this->__f("Backgrounds"); ?></div>
        <?
        $backgrounds = array();
        $backgrounds[] = "none";
        $backgrounds[] = "ticks";
        $backgrounds[] = "mooning";
        $backgrounds[] = "squairy_light";
        $backgrounds[] = "binding_dark";
        $backgrounds[] = "grey_wash_wall";
        $backgrounds[] = "knitting";
        $backgrounds[] = "honey_im_subtle";
        $backgrounds[] = "retina_wood";
        $backgrounds[] = "strange_bullseyes";
        $backgrounds[] = "carbon_fibre";
        $backgrounds[] = "always_grey";
        $backgrounds[] = "grunge_wall";
        $backgrounds[] = "concrete_wall_2";
        $backgrounds[] = "rubber_grip";
        $backgrounds[] = "inflicted";

        foreach ($backgrounds as $bgs) {
            echo "<span class='background' image='$bgs' type='skin/default/bgs/$bgs.png' style='background-image:url(\"skin/default/bgs/$bgs.png\"); display:$curdesignbg;'></span>";
        }
        echo "<span class='nobackground'>No background selection available for this design.</span>";
        ?>
    </div>
</div>
<span class='close'><? echo $this->__f("Close"); ?></span>

