<h1><? echo $this->__f("Meca Fleet Emails and Messages"); ?></h1>    


<div class="textfield gss_setting"  id="shouldSendEmail">
    <span class="title"><?php echo $this->__f("Call me subject"); ?></span>
    <input type='textfield' gs_model='emailmodel' gs_model_attr='callMeSubject' value="<? echo $this->getConfigurationSetting("callMeSubject"); ?>"/>
    <div class="description">
        <?php echo $this->__("Call me body?"); ?>
    </div>
</div>


<div class="textfield gss_setting"  id="shouldSendEmail">
    <span class="title"><?php echo $this->__f("Main order email"); ?></span>
    <textarea gs_model='emailmodel' gs_model_attr='callMeBody' style='position: initial; width: 945px; height: 300px;'><? echo $this->getConfigurationSetting("callMeBody"); ?></textarea>
    <div class="description">
        <div>
            <br/>
            <? echo $this->__f("Variables that can be used in email and subject"); ?>:
            <br/> {MecaFleet.CellPhone} = <? echo $this->__f("CellPhone"); ?>
        </div>
    </div>
</div>
<br/>
<br/>
<br/>
<div class="textfield gss_setting"  id="">
    <span class="title"><?php echo $this->__f("Contact form from app subject"); ?></span>
    <input type='textfield' gs_model='emailmodel' gs_model_attr='contactFormSubject' value="<? echo $this->getConfigurationSetting("contactFormSubject"); ?>"/>
</div>


<div class="textfield gss_setting"  id="shouldSendEmail">
    <span class="title"><?php echo $this->__f("Contact form from app body"); ?></span>
    <textarea gs_model='emailmodel' gs_model_attr='contactFormBody' style='position: initial; width: 945px; height: 300px;'><? echo $this->getConfigurationSetting("contactFormBody"); ?></textarea>
    <div class="description">
        <div>
            <br/>
            <? echo $this->__f("Variables that can be used in email and subject"); ?>:
            <br/> {MecaFleet.ContactMessage} = <? echo $this->__f("The message itself"); ?>
            <br/> {MecaFleet.LicensePlate} = <? echo $this->__f("The licenseplate for the car"); ?>
            <br/> {MecaFleet.CellPhone} = <? echo $this->__f("CellPhone"); ?>
        </div>
    </div>
</div>


<br/>
<br/>
<br/>
<div class="textfield gss_setting"  id="">
    <span class="title"><?php echo $this->__f("SMS signup"); ?></span>
    <textarea gs_model='emailmodel' gs_model_attr='signupSms' style='position: initial; width: 945px; height: 300px;'><? echo $this->getConfigurationSetting("signupSms"); ?></textarea>
    <div class="description">
        <div>
            <br/>
            <? echo $this->__f("Variables that can be used in email and subject"); ?>:
            <br/> {MecaFleet.StoreTitle} = <? echo $this->__f("the unique identifier to this system"); ?>
        </div>
    </div>
</div>
<br/>
<br/>
<br/>
<div class="textfield gss_setting"  id="">
    <span class="title"><?php echo $this->__f("SMS Car notification"); ?></span>
    <? // echo nl2br($this->getConfigurationSetting("smsRequestKilomters")); ?>
    <textarea gs_model='emailmodel' gs_model_attr='smsRequestKilomters' style='position: initial; width: 945px; height: 300px;'><? echo $this->getConfigurationSetting("smsRequestKilomters"); ?></textarea>
    <div class="description">
        <div>
            <br/>
            <? echo $this->__f("Variables that can be used in email and subject"); ?>:
            <br/> {MecaFleet.StoreTitle} = <? echo $this->__f("the unique identifier to this system"); ?>
        </div>
    </div>
</div>


<div class="textfield gss_setting"  id="">
    <span class="title"><?php echo $this->__f("PusNotification - Request kilometers"); ?></span>
    <input type='textfield' gs_model='emailmodel' gs_model_attr='pushRequestKilometers' value="<? echo $this->getConfigurationSetting("pushRequestKilometers"); ?>"/>
</div>

<div class="textfield gss_setting"  id="">
    <span class="title"><?php echo $this->__f("PusNotification - Request service"); ?></span>
    <input type='textfield' gs_model='emailmodel' gs_model_attr='pushRequestService' value="<? echo $this->getConfigurationSetting("pushRequestService"); ?>"/>
</div>

<div class="textfield gss_setting"  id="">
    <span class="title"><?php echo $this->__f("PusNotification - Request control"); ?></span>
    <input type='textfield' gs_model='emailmodel' gs_model_attr='pushRequestControl' value="<? echo $this->getConfigurationSetting("pushRequestControl"); ?>"/>
</div>