<?
/* @var $this \ns_6a7c8d8e_abd4_43b3_ad88_c568f245d4da\MecaFleetSettings */


?>

<div gstype="form" method="save">
    Åpningstider:
    <br/><textarea type="text" gsname="openinghours"><? echo $this->getConfigurationSetting("openinghours"); ?></textarea>
    <br/>
    <br/>Addresse / Veibeskrivelse:
    <br/><textarea type="text" gsname="roadmap"><? echo $this->getConfigurationSetting("roadmap"); ?></textarea>
    <br/>
    <br/> Kontaktperson:
    <br/> <input type="text" gsname="contact.name" class="gsniceinput1" placeholder="Navn" value="<? echo $this->getConfigurationSetting("contact.name"); ?>"/>
    <br/> <input type="text" gsname="contact.email" class="gsniceinput1" placeholder="Epost" value="<? echo $this->getConfigurationSetting("contact.email"); ?>"/>
    <br/> <input type="text" gsname="contact.cell" class="gsniceinput1" placeholder="Mobilnr"  value="<? echo $this->getConfigurationSetting("contact.cell"); ?>"/>
    <br/> <div class="shop_button" gstype="submit">Lagre</div>
</div>