<div gstype="form" method="saveAppInstanceSettings">
    <table width="80%" class="contactConfigTable" cellspacing='0' cellpadding='0'>
        <tr>
            <td width="50%">Name for booking engine to use</td>
            <td width="50%"><input type="text" gsname="setting_selectedkey" style='width:100%;' value="<? echo $this->getSelectedName(); ?>"></td>
        </tr>
    </table>
    <input gstype="submit" type="button" value='Save'>
</div>