<? $apiKey = $this->getApiKey(); ?>


<script>
     $.ajax({

        url: 'https://api.mailchimp.com/3.0/lists',
        type: 'GET',
        crossOrigin: true,
        beforeSend: function (xhr) {
            var hash = "<? echo base64_encode("fdsafsaf" . ':' . $apiKey); ?>";
            xhr.setRequestHeader ("Authorization", "Basic " + hash);
        },
        success: function() { alert("Success"); },
    });
    
</script>