<?php

namespace ns_932810f4_5bd1_4b56_a259_d5bd2e071be1;

$taxes = $this->getApi()->getProductManager()->getTaxes();
if (!is_array($taxes)) {
    $taxes = [];
}

$shipment = isset($taxes[0]) ? $taxes[0]->taxRate : "";
$group1 = isset($taxes[1]) ? $taxes[1]->taxRate : "";
$group2 = isset($taxes[2]) ? $taxes[2]->taxRate : "";
$group3 = isset($taxes[3]) ? $taxes[3]->taxRate : "";
$group4 = isset($taxes[4]) ? $taxes[4]->taxRate : "";
$group5 = isset($taxes[5]) ? $taxes[5]->taxRate : "";

echo "<h1>Previous files</h1>";
$files = $this->getApi()->getAccountingManager()->getAllFiles();

/* @var $this \ns_deab499e_b133_4cb6_a1b2_532018c31d46\Taxes */
?>

<div class="gss_settings_header">
    <i class="fa fa-dollar"></i>

    <div class="gss_settings_header_description">
        <div class="gss_settings_header_title"> <? echo $this->__f("Accounting transfer"); ?></div>

        <div class="gss_settings_header_description_inner">
            <? echo $this->getDescription(); ?>
        </div>
    </div>	
</div>


<div class='gss_settings_content'>
    <div class='gss_button_area' style='display:inline-block; float:right;'>
        <div class="gss_button" onclick="window.open('/scripts/accounting.php?type=user&onlynew=true');"><i class='fa fa-save'></i><?php echo $this->__("Download only new users"); ?></div>
        <div class="gss_button" onclick="window.open('/scripts/accounting.php?type=user');"><i class='fa fa-save'></i><?php echo $this->__("Download users"); ?></div>
        <div class="gss_button" onclick="window.open('/scripts/accounting.php');"><i class='fa fa-save'></i><?php echo $this->__("Download order file"); ?></div>
    </div>
<?php
echo "<h2>Download orderfile history</h2>";
foreach($files as $fileId => $date) {
    echo $date . ", <a style='color:blue;cursor:pointer;' onclick=\"window.open('/scripts/accounting.php?id=".$fileId."');\">download</a><br>";
}
?>
    <div style='clear:both;'></div>
</div>