<?php
 /* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
?>
<table cellspacing='0' cellpadding='0' width='100%' gstype='form' method='doAccountAction'>
    <tr>
        <th>Id</th>
        <th align='left'>Customer name</th>
        <th>Customer type</th>
        <th>Number of bookings</th>
        <th>Number of orders</th>
        <th>Last booking</th>
        <th>Preferences</th>
        <th>Payment type</th>
    </tr>
    <?php
    $users = $this->getApi()->getPmsManager()->getAllUsers($this->getSelectedName(), $this->getSelectedFilter());
    $methods = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
    
    foreach($users as $user) {
        $name = $user->name ? $user->name : "Unkown name";
        echo "<tr class='customertablerow loadAccountInformation' userid='".$user->userId."'>";
        echo "<td align='center'><input type='checkbox' gsname='user_".$user->userId."'></input> " . $user->customerId . "</td>";
        echo "<td>$name</td>";
        echo "<td align='center'>" . $user->customerType . "</td>";
        echo "<td align='center'>" . $user->numberOfBookings . "</td>";
        echo "<td align='center'>" . $user->numberOfOrders . "</td>";
        echo "<td align='center'>" . date("d.m.Y", strtotime($user->latestBooking)) . "</td>";
        echo "<td align='center'>";
        if($user->invoiceAfterStay) {
            echo " <i class='fa fa-arrow-right' title='Order created after stay'></i>";
        }
        if($user->hasDiscount) {
            echo " <i class='fa fa-dollar' title='This user has a discount'></i>";
        }
        if($user->suspended) {
            echo " <i class='fa fa-ban' style='color:red;' title='This user has been suspended'></i>";
        }
        echo "</td>";
        echo "<td align='center'>";
        if($user->preferredPaymentType) {
            foreach($methods as $met) {
                if($met->id == $user->preferredPaymentType) {
                    echo $met->appName;
                }
            }
        } else {
            echo "default";
        }
        echo "</td>";
        echo "</tr>";
    }
    echo "<tr><td colspan='200'><br>"
    . "<select gsname='action'><option value='disableaccounts'>Suspend account(s)</option></select>"
            . "<input type='button' value='Go' gstype='submit'></input>"
            . "<center>Row count : " . sizeof($users)  . "<br><br></center></td></tr>";
    ?>
</table>


<style>
    .customertablerow { cursor:pointer; }
    .customertablerow:hover td { color: green; }
</style>

<script>
    $('.customertablerow').click(function() {
        
    });
</script>