<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();
$selectedRoom = null;
foreach($booking->rooms as $room) {
    if($room->pmsBookingRoomId==$_POST['data']['roomid']) {
        $selectedRoom = $room;
    }
}

if(!$selectedRoom) {
    echo "No room found? This should be impossible.?";
    return;
}

$start = strtotime($selectedRoom->date->start);
$end = strtotime($selectedRoom->date->end);
$dates = $this->getDatesToAdd($start, $end, $selectedRoom);
echo "<div style='font-weight:bold;'>";
echo "<span style='width:105px;display:inline-block;padding-left:20px;'>Date</span>";
echo "<span style='width:55px;display:inline-block;'>Count</span>";
echo "<span style='width:50px;display:inline-block;'>Price</span>";
echo "</div>";

foreach($dates as $date => $obj) {
    echo "<div>";
    echo "<input type='checkbox' checked class='toggleifshouldbeadded' gsname='rowdate_$date'>";
    echo "<input type='txt' value='".date("d.m.Y", $date)."' style='width:100px;'>";
    echo "<input type='txt' value='".$obj->count."' style='width:40px;' gsname='count_$date'>";
    echo "<input type='txt' value='".$obj->price."' style='width:50px;' gsname='price_$date'>";
    echo "</div>";
}
?>

<script>
$('.toggleifshouldbeadded').on('click', function() {
    var checked = $(this).is(':checked');
    var row = $(this).closest('div');
    row.find('input').each(function() {
        if($(this).is(':checkbox')) {
            return;
        }
        if(checked) {
            $(this).attr('disabled',null);
        } else {
            $(this).attr('disabled','disabled');
        }
    });
});
</script>