<?php
 /* @var $this \ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$room = $this->getSelectedPmsRoom();
$booking = $this->getApi()->getPmsManager()->getBookingFromRoom($this->getSelectedName(), $room->pmsBookingRoomId);

$code = "Not active yet";
$forcedAccess = "<i class='fa fa-close'></i>";
$blockedAccess = "<i class='fa fa-close'></i>";
$resend = "Code not active yet";
$renew = "Code not active yet";
$lastAccess = "Room not assigned yet.";

$filter = new core_pmsmanager_PmsBookingFilter();
$filter->startDate = $room->date->start;
$filter->endDate = $room->date->start;
$filter->filterType = "checkout";

$selectedCheckoutRoom = null;
$checkoutbookings = $this->getApi()->getPmsManager()->getAllBookings($this->getSelectedName(), $filter);
foreach($checkoutbookings as $checkoutbooking) {
    foreach($checkoutbooking->rooms as $checkoutroom) {
        if($checkoutroom->bookingItemId == $room->bookingItemId) {
            $selectedCheckoutRoom = $checkoutroom;
        }
    }
}

if($selectedCheckoutRoom) {
    $checkouttime = strtotime($selectedCheckoutRoom->date->end);
}

if($selectedCheckoutRoom && $checkouttime > time()) {
    $code = "<b>Earliest time to give out code is " . date("H:i", $checkouttime) . ", because someone already occupy this room.</b>";
}

if(date("dmy", time()) != date("dmy", strtotime($room->date->start))) {
    $code = "<b>Not checking in today.</b>";
}

if($room->blocked) {
    $blockedAccess = "<i class='fa fa-check'></i>";
}

if($room->addedToArx) {
    $code = $room->code;
    $resend = "<span class='resendcode' style='color:blue; cursor:pointer;'>Resend</span>";
    $resendcheckin = "<span class='resendcheckin' style='color:blue; cursor:pointer;'>Resend</span>";
    $renew = "<span class='renewcode' style='color:blue; cursor:pointer;'>Renew</span>";
}
?>
<table cellspacing='0' cellpadding='0' width='100%' roomid='<?php echo $_POST['data']['roomid']; ?>'>
    <tr>
        <th style='width:100px;'></th>
        <th></th>
    <tr>
        <td>Code</td>
        <td><?php echo $code; ?><br>
        </td>
    </tr>
    <tr>
        <td>Resend code</td>
        <td><?php echo $resend; ?>
            <div class='resendcodepanel' style='display:none;'>
                <?php
                $prefix = $room->guests[0]->prefix;
                $phone = $room->guests[0]->phone;
                
                ?>
                <input type='text' toSend='prefix' value='<?php echo $prefix; ?>'>
                <input type='text' toSend='phone' value='<?php echo $phone; ?>'>
                <input type='button' value='Resend' class='doresend' method='resendCode'>
            </div>
        </td>
    </tr>
    <tr>
        <td>Renew code</td>
        <td><?php echo $renew; ?></td>
    </tr>
    <tr>
        <td>Force access</td>
        <?php if(!$booking->forceGrantAccess) { ?>
            <td><span class='forcegrantaccess' style='color:blue; cursor:pointer;'>Force access regardless of payment.</span></td>
        <?php } else { ?>
            <td><span class='unforcegrantaccess' style='color:blue; cursor:pointer;'>Unforce access regardless of payment.</span></td>
        <?php } ?>
    </tr>
    <tr>
        <td>Block access</td>
        <?php if($room->blocked) { ?>
            <td><span class='unblockaccess' style='color:blue; cursor:pointer;'>Unblock access for this room.</span></td>
        <?php } else { ?>
            <td><span class='blockaccess' style='color:blue; cursor:pointer;'>Block access for this room.</span></td>
        <?php } ?>
    </tr>
</table>
   

<script>
$('.renewcode').on('click', function() {
    var event = thundashop.Ajax.createEvent('','renewCode', $(this), { "roomid" : $(this).closest('table').attr('roomid')});
    thundashop.Ajax.postWithCallBack(event, function(res) {
        $('.additionalroominfobox_inner').html(res);
    });
});
$('.undocleaning').on('click', function() {
    var event = thundashop.Ajax.createEvent('','undoLastCleaning', $(this), { "roomid" : $(this).closest('table').attr('roomid')});
    thundashop.Ajax.postWithCallBack(event, function(res) {
        $('.additionalroominfobox_inner').html(res);
    });
});
$('.forcegrantaccess').on('click', function() {
    var event = thundashop.Ajax.createEvent('','forceGrantAccess', $(this), { "roomid" : $(this).closest('table').attr('roomid')});
    thundashop.Ajax.postWithCallBack(event, function(res) {
        $('.additionalroominfobox_inner').html(res);
    });
});
$('.unforcegrantaccess').on('click', function() {
    var event = thundashop.Ajax.createEvent('','forceUnGrantAccess', $(this), { "roomid" : $(this).closest('table').attr('roomid')});
    thundashop.Ajax.postWithCallBack(event, function(res) {
        $('.additionalroominfobox_inner').html(res);
    });
});
$('.blockaccess').on('click', function() {
    var event = thundashop.Ajax.createEvent('','forceBlockAccess', $(this), { "roomid" : $(this).closest('table').attr('roomid')});
    thundashop.Ajax.postWithCallBack(event, function(res) {
        $('.additionalroominfobox_inner').html(res);
    });
});
$('.unblockaccess').on('click', function() {
    var event = thundashop.Ajax.createEvent('','forceUnBlockAccess', $(this), { "roomid" : $(this).closest('table').attr('roomid')});
    thundashop.Ajax.postWithCallBack(event, function(res) {
        $('.additionalroominfobox_inner').html(res);
    });
});
$('.resendcode').on('click', function() {
    $('.resendcode').hide();
    $('.resendcodepanel').show();
});
$('.resendcheckin').on('click', function() {
    $('.resendcheckin').hide();
    $('.resendcheckinpanel').show();
});
$('.doresend').on('click', function() {
    var method = $(this).attr('method');
    var event = thundashop.Ajax.createEvent('',method, $(this), { 
        "roomid" : $(this).closest('table').attr('roomid'),
        "prefix" : $('[toSend="prefix"]').val(),
        "phone" : $('[toSend="phone"]').val()
    });
    thundashop.Ajax.postWithCallBack(event, function(res) {
        $('.additionalroominfobox_inner').html(res);
    });
});
    
</script>