<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$bookedRoom = $this->getFirstBookedRoom();
if(!$bookedRoom->date) {
    $bookedRoom->date = new core_pmsmanager_PmsBookingDateRange();
    $bookedRoom->date->start = $this->convertToJavaDate(time());
    $bookedRoom->date->end = $this->convertToJavaDate(time());
}
$endDate = date("d.m.Y", time()+(86400*30));
$repeat = $this->getRepeatingSummary();
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
echo $this->roomTable;
?>

<div class='itemrow' style='position:relative;'>
<span class='bookedaction'></span> 
<a class='addmoredates togglerepeatbox'><? 
if($repeat) {
    echo $repeat;
} else {
    echo $this->__w("Repeat event");
}
$curBooking = $this->getSelectedBooking();
?>
</a><?php
?>
    <span class='addMoredatesPanel' gstype='form' method='addRepeatingDates'>
        <input type="hidden" value="<?php echo $curBooking->id; ?>" gsname="bookingid">
        <i class='fa fa-close togglerepeatbox'></i>
        <i class='fa fa-caret-up'></i>
        <input type='hidden' value='repeat' gsname='repeattype'>
        <?php if($config->isItemBookingInsteadOfTypes) { ?>
        <div class='eventrow'>
            <span class='title'><? echo $this->__w("Room"); ?>:</span>
            <span class='optionbox'>
                <select gsname='itemid'>
                <?php
                $types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
                $types = $this->indexList($types);
                $rooms = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
                $rooms = $this->indexList($rooms);
                foreach($rooms as $idx => $room) {
                    $selected = "";
                    if($bookedRoom->bookingItemId == $room->id) {
                        $selected = "SELECTED";
                    }
                    echo "<option value='".$room->id."' $selected>".$room->bookingItemName."</option>";
                }
                ?>
                </select>
            </span>
        </div>
        <? } else { ?>
            <div class='eventrow'>
                <span class='title'><? echo $this->__w("Type"); ?>:</span>
                <span class='optionbox'>
                    <select gsname='typeid'>
                    <?php
                    $types =$this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
                    $types = $this->indexList($types);
                    foreach($types as $idx => $type) {
                        $selected = "";
                        if($bookedRoom->bookingItemTypeId == $type->id) {
                            $selected = "SELECTED";
                        }
                        echo "<option value='".$type->id."' $selected>".$type->name."</option>";
                    }
                    ?>
                    </select>
                </span>
            </div>
        
        <? } ?>
        
        <div class='eventrow'>
            <span class='title'>
                <span class='datetypepanel repeat'><? echo $this->__w("First event"); ?>:</span>
                <span class='datetypepanel single'><? echo $this->__w("New date"); ?>:</span>
            </span>
            <span class='optionbox dateselection'>
                <?php if(date("d.m.Y", strtotime($bookedRoom->date->start)) !=  date("d.m.Y", strtotime($bookedRoom->date->end))) { ?>
                    <input type='text' gsname='eventStartsAt' style='width:40%;text-align: center;' value='<? echo date("d.m.Y", strtotime($bookedRoom->date->start)); ?>'>
                    <input type='text' style='width: 20%;text-align: center;' value='<? echo date("H:i", strtotime($bookedRoom->date->start)); ?>' gsname='starttime'><br>
                    <input type='text' gsname='eventEndsAt' style='width:40%;text-align: center;' value='<? echo date("d.m.Y", strtotime($bookedRoom->date->end)); ?>'>
                    <input type='text' style='width: 20%;text-align: center;' value='<? echo date("H:i", strtotime($bookedRoom->date->end)); ?>' gsname='endtime'>
                <?php } else { ?>
                    <input type='text' gsname='eventStartsAt' style='width:40%;text-align: center; float:left; margin-right: 5px;' value='<? echo date("d.m.Y", strtotime($bookedRoom->date->start)); ?>'>
                    <input type='text' style='width: 20%;text-align: center; float:left; margin-right: 5px;' value='<? echo date("H:i", strtotime($bookedRoom->date->start)); ?>' gsname='starttime'>
                    <input type='text' style='width: 20%;text-align: center; float:left;' value='<? echo date("H:i", strtotime($bookedRoom->date->end)); ?>' gsname='endtime'>
                <?php } ?>
            </span>
        </div>
        
        <div class='datetypepanel repeat'>
            <div class='eventrow'>
                <span class='title'><? echo $this->__w("Repeats"); ?>:</span>
                <span class='optionbox'>
                    <select class="repeat_type" gsname='repeat_periode'>
                        <option value="0" title="Daily"><? echo $this->__w("Daily"); ?></option>
                        <option value="1" title="Weekly"><? echo $this->__w("Weekly"); ?></option>
                        <option value="2" title="Monthly"><? echo $this->__w("Monthly"); ?></option>
                    </select>
                </span>
            </div>
            <div class='eventrow repeatrow repeateachdaterow'>
                <span class='title'><? echo $this->__w("Repeat every"); ?>:</span>
                <span class='optionbox'>
                    <select style='width:20%; margin-right: 3px;' gsname='repeateachtime'>
                        <?php 
                        for($i = 1; $i <= 30; $i++) {
                            echo "<option value='$i'>$i.</option>";
                        }
                        ?>
                    </select>
                    <span class='repeat_0 repeatoption'><? echo $this->__w("day"); ?></span>
                    <span class='repeat_1 repeatoption'><? echo $this->__w("week"); ?></span>
                    <span class='repeat_2 repeatoption'><? echo $this->__w("month"); ?></span>
                </span>
            </div>
            <div class='eventrow repeatrow'>
                <span class='title'><? echo $this->__w("Repeat on"); ?>:</span>
                <span class='optionbox'>
                    <span class='repeat_0 repeatoption'>

                    </span>
                    <span class='repeat_1 repeatoption'>
                        <table>
                            <tr>
                                <td><input type='checkbox' gsname='repeatMonday'><? echo $this->__w("Mon"); ?></td>
                                <td><input type='checkbox' gsname='repeatTuesday'><? echo $this->__w("Tue"); ?></td>
                                <td><input type='checkbox' gsname='repeatWednesday'><? echo $this->__w("Wed"); ?></td>
                                <td><input type='checkbox' gsname='repeatThursday'><? echo $this->__w("Thu"); ?></td>
                            </tr>
                            <tr>
                                <td><input type='checkbox' gsname='repeatFriday'><? echo $this->__w("Fri"); ?></td>
                                <td><input type='checkbox' gsname='repeatSaturday'><? echo $this->__w("Sat"); ?></td>
                                <td><input type='checkbox' gsname='repeatSunday'><? echo $this->__w("Sun"); ?></td>
                            </tr>
                        </table>
                        <br>
                    </span>
                    <span class='repeat_2 repeatoption' style='padding-bottom: 10px;'>
                        <input type='radio' name='repeatmonthtype' gsname='repeatmonthtype' value='dayofmonth'><? echo $this->__w("day of the month"); ?><br>
                        <input type='radio' name='repeatmonthtype' gsname='repeatmonthtype' value='dayofweek'><? echo $this->__w("day of the week"); ?>
                        <br> <br>
                    </span>

                </span>
            </div>
            <div class='eventrow'>
                <span class='title'><? echo $this->__w("Ends"); ?>:</span>
                <span class='optionbox'><input type='text' gsname='endingAt' value='<? echo $endDate; ?>' style='width: 35%;text-align: center;'></span>
            </div>
        </div>
        <div class='eventrow'>
            <span class='title'></span>
            <span class='optionbox'>
                <input type='button'value='<? echo $this->__w("Add"); ?>' gstype='submitToInfoBox'>
                <input type='button'value='<? echo $this->__w("Close"); ?>' class='togglerepeatbox'>
            </span>
        </div>
    </span>
</div>

<?php
if($curBooking->lastRepeatingData) {
    ?>
    <script>
    $('[gsname="itemid"]').val('<? echo $curBooking->lastRepeatingData->bookingItemId; ?>');
    $('[gsname="typeid"]').val('<? echo @$curBooking->lastRepeatingData->bookingTypeId; ?>');
    $('[gsname="repeateachtime"]').val('<? echo $curBooking->lastRepeatingData->data->repeatEachTime; ?>');
    $('[gsname="repeat_periode"]').val(<? echo $curBooking->lastRepeatingData->data->repeatPeride; ?>);
    $('[gsname="repeat_periode"]').change();
    
    $('[gsname="repeatMonday"]').attr('checked', <? if(@$curBooking->lastRepeatingData->data->repeatMonday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatTuesday"]').attr('checked', <? if(@$curBooking->lastRepeatingData->data->repeatTuesday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatWednesday"]').attr('checked', <? if(@$curBooking->lastRepeatingData->data->repeatWednesday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatThursday"]').attr('checked', <? if(@$curBooking->lastRepeatingData->data->repeatThursday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatFriday"]').attr('checked', <? if(@$curBooking->lastRepeatingData->data->repeatFriday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatSaturday"]').attr('checked', <? if(@$curBooking->lastRepeatingData->data->repeatSaturday) { echo "true"; } else { echo "false"; } ?>);
    $('[gsname="repeatSunday"]').attr('checked', <? if(@$curBooking->lastRepeatingData->data->repeatSunday) { echo "true"; } else { echo "false"; } ?>);
    
    $('[gsname="endingAt"]').val('<? echo date("d.m.Y", strtotime($curBooking->lastRepeatingData->data->endingAt)); ?>');
    
    $('[gsname="eventStartsAt"]').val('<? echo date("d.m.Y", strtotime($curBooking->lastRepeatingData->data->firstEvent->start)); ?>');
    $('[gsname="eventEndsAt"]').val('<? echo date("d.m.Y", strtotime($curBooking->lastRepeatingData->data->firstEvent->end)); ?>');
    
    </script>
    <?
}
?>

<script>
    $('[gsname="eventStartsAt"],[gsname="eventEndsAt"],[gsname="endingAt"]').datepicker({ 
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
        dateFormat: "dd.mm.yy", minDate : 0,
    onSelect: function(dateText) {
        var date = moment(dateText, "DD.MM.YYYY");
        var month = (moment(date).get('month')+1);
        if(month < 10) {
            month = "0" + month;
        }
        $('#end_date').val((moment(date).get('date')+1) + "." + month + "." + moment(date).get('year'));
      }
    });
</script>
