<? 
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$booking = $this->getSelectedBooking();
$types = $this->getTypes();
$bookingItems = $this->getItems();

$items = array();
$items[1] = "BREAKFAST";
$items[2] = "PARKING";
$items[3] = "LATECHECKOUT";
$items[4] = "EARLYCHECKIN";
$items[5] = "EXTRABED";
$items[6] = "CANCELATION FEE";
$items[7] = "EXTRA CHILDBED";
?>

<h2>Addons</h2>
<div style='cursor: pointer' gs_downloadExcelReport='createExcelForAddons' gs_fileName='addons' bookingid='<? echo $booking->id; ?>'><i class='fa fa-download'></i> Download excel file</div>
<br/>
<?php
echo "<select id='roomsForAddons'>";
echo "<option value=''>All rooms</option>";
foreach($booking->rooms as $room) {
    if($room->deleted) {
        continue;
    }
    $roomName = $types[$room->bookingItemTypeId]->name;
    if($room->bookingItemId) {
        $roomName .= " (" . $bookingItems[$room->bookingItemId]->bookingItemName . ") " . $room->guests[0]->name;
    }
    echo "<option value='".$room->pmsBookingRoomId."'>$roomName</option>";
}
echo "</select> ";

echo "<select id='addontypeselection'>";
foreach($config->addonConfiguration as $addonConfig) {
    /* @var $addonConfig core_pmsmanager_PmsBookingAddonItem */
    if($addonConfig->isActive || $addonConfig->isAvailableForBooking || $addonConfig->isAvailableForCleaner) {
        if($addonConfig->productId) {
            $name = $this->getApi()->getProductManager()->getProduct($addonConfig->productId)->name;
        }
        if(isset($items[$addonConfig->addonType])) {
            $name = $items[$addonConfig->addonType];
        }
        echo "<option value='" . $addonConfig->addonType . "'>" . $name . "</option>";
    }
}
echo "</select> ";
echo "<span class='pmsbutton addAddonsButton'>Add addon</span> ";
echo "<span class='pmsbutton removeAddons' style='background-color:red'>Remove addon</span>";

echo "<br><br>";
foreach($booking->rooms as $room) {
    if($room->deleted) {
        continue;
    }
    $roomName = $types[$room->bookingItemTypeId]->name;
    if($room->bookingItemId) {
        $roomName .= " (" . $bookingItems[$room->bookingItemId]->bookingItemName . ") " . $room->guests[0]->name;
    }
    $guestName = "";
    if(isset($room->guests[0])) {
        $guestName = $room->guests[0]->name;
    }
    echo "<h2>$guestName " . $roomName . " - " . date("d.m.Y H:i" , strtotime($room->date->start)) . " - " . date("d.m.Y H:i" , strtotime($room->date->end)) . "</h2>";
    echo "<table cellspacing='0' cellpadding='0' width='100%' class='addonstable'>";
    echo "<tr>";
    echo "<th>Type</th>";
    echo "<th>Room</th>";
    echo "<th>Count</th>";
    echo "<th>Price</th>";
    echo "<th>Date</th>";
    echo "<th title='In room price'>Irm</th>";
    echo "</tr>";
    if(sizeof($room->addons) == 0) {
        echo "No addons added to this room.";
    } else {
        foreach($room->addons as $addon) {
            $name = "";
            if($addon->productId) {
                $name = $this->getApi()->getProductManager()->getProduct($addon->productId)->name;
            }
            if(isset($items[$addon->addonType])) {
                $name = $items[$addon->addonType];
            }
            echo "<tr addonid='".$addon->addonId."' roomid='".$room->pmsBookingRoomId."' class='addonrow'>";
            echo "<td>";
            echo $name . "</td>";
            echo "<td>" . $roomName . "</td>";
            echo "<td width='10'><input type='text' value='" . $addon->count . "' style='width:70px;' class='addoncount'></td>";
            echo "<td width='10'><input type='text' value='" .  $addon->price . "' style='width:70px;' class='addonprice'></td>";
            echo "<td>" . date("d.m.Y, H:i", strtotime($addon->date)) . "</td>";
            echo "<td align='center' width='10'>";
            if($addon->isIncludedInRoomPrice) {
                echo "<i class='fa fa-check addonincludedinroomprice' title='This addon is included in the room price'></i>";
            } else {
                echo "<i class='fa fa-close addonincludedinroomprice' title='This addon is not included in the room price'></i>";
            }
            echo "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";
}
echo "<span class='pmsbutton saveAddons' style='float:right; display:none;'>Save addons</span>";
?>