<? 
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$booking = $this->getSelectedBooking();
$types = $this->getTypes();
$bookingItems = $this->getItems();

$items = array();
$items[1] = "BREAKFAST";
$items[2] = "PARKING";
$items[3] = "LATECHECKOUT";
$items[4] = "EARLYCHECKIN";
$items[5] = "EXTRABED";
$items[6] = "CANCELATION FEE";
$items[7] = "EXTRA CHILDBED";
?>

<h2>Addons</h2>
<?php
echo "<select id='roomsForAddons'>";
echo "<option value=''>All rooms</option>";
foreach($booking->rooms as $room) {
    $roomName = $types[$room->bookingItemTypeId]->name;
    if($room->bookingItemId) {
        $roomName .= " (" . $bookingItems[$room->bookingItemId]->bookingItemName . ") " . $room->guests[0]->name;
    }
    echo "<option value='".$room->pmsBookingRoomId."'>$roomName</option>";
}
echo "</select> ";

echo "<select id='addontypeselection'>";
foreach($config->addonConfiguration as $addonConfig) {
    /* @var $addonConfig core_pmsmanager_PmsBookingAddonItem */
    if(!$addonConfig->isActive) {
        continue;
    }
    echo "<option value='" . $addonConfig->addonType . "'>" . $items[$addonConfig->addonType] . "</option>";
}
echo "</select> ";
echo "<span class='pmsbutton addAddonsButton'>Add addon</span> ";
echo "<span class='pmsbutton removeAddons' style='background-color:red'>Remove addon</span>";
echo "<span class='pmsbutton saveAddons' style='float:right;'>Update addons</span>";

echo "<br><br>";
foreach($booking->rooms as $room) {
    $roomName = $types[$room->bookingItemTypeId]->name;
    if($room->bookingItemId) {
        $roomName .= " (" . $bookingItems[$room->bookingItemId]->bookingItemName . ") " . $room->guests[0]->name;
    }
    echo "<h2>" . $roomName . " - " . date("d.m.Y H:i" , strtotime($room->date->start)) . " - " . date("d.m.Y H:i" , strtotime($room->date->end)) . "</h2>";
    echo "<table cellspacing='0' cellpadding='0' width='100%'>";
    echo "<tr>";
    echo "<th>Type</th>";
    echo "<th>Room</th>";
    echo "<th>Count</th>";
    echo "<th>Price</th>";
    echo "<th>Date</th>";
    echo "</tr>";
    if(sizeof($room->addons) == 0) {
        echo "No addons added to this room.";
    } else {
        foreach($room->addons as $addon) {
            echo "<tr addonid='".$addon->addonId."' roomid='".$room->pmsBookingRoomId."' class='addonrow'>";
            echo "<td>" . $items[$addon->addonType] . "</td>";
            echo "<td>" . $roomName . "</td>";
            echo "<td width='10'><input type='text' value='" . $addon->count . "' style='width:70px;' class='addoncount'></td>";
            echo "<td width='10'><input type='text' value='" .  $addon->price . "' style='width:70px;' class='addonprice'></td>";
            echo "<td>" . date("d.m.Y, H:i", strtotime($addon->date)) . "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";
}
?>