<?
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */

if(sizeof($this->errors) > 0) {
    echo "<h2>Error</h2>";
    echo "<div class='errorlist'>";
    foreach($this->errors as $error) {
        echo $error;
    }
    echo "</div>";
}

$bookingid = $_POST['data']['bookingid'];

$pmsManager = $this->getApi()->getPmsManager();
$config = $pmsManager->getConfiguration($this->getSelectedName());

$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
foreach ($types as $idx => $type) {
    $types[$type->id] = $type;
}

$booking = $pmsManager->getBooking($this->getSelectedName(), $bookingid);

if(!$booking->confirmed) {
    ?>
    <div class='needconfirmation'>
        This booking has not been confirmed yet.<br><br>
        <div gstype="form" method="confirmBooking">
            <input type='hidden' gsname='bookingid' value='<? echo $booking->id; ?>'>
            <span gstype="submitToInfoBox" class='pmsbutton'>Confirm booking</span>
        </div>
    </div>
    <?php
}

echo "<div class='bookinginfo'>";
$this->includefile("contactdata");
echo "<div style='clear:both;'></div>";
$this->includefile("roomsbooked");
$this->includefile("addons");
if($config->requirePayments) {
    $this->includefile("orderinformation");
}
?>
<br><br><br>
<span class='pmsbutton doneediting' style='float:right;'><? echo $this->__w("Done editing"); ?></span> 
<span class='pmsbutton deletebooking' bookingid='<? echo $booking->id; ?>' style='margin-right: 50px; background-color:red;'><? echo $this->__w("Delete booking"); ?></span>
<div style='clear:both;'></div>
</div>