<script>
    $('.ui-tooltip').remove();
</script>
<?
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
if(sizeof($this->errors) > 0) {
    echo "<h2>Error</h2>";
    echo "<div class='errorlist'>";
    foreach($this->errors as $error) {
        echo $error;
    }
    echo "</div>";
}

if(isset($_POST['event']) && $_POST['event'] == "fastordercreation") {
    echo "<div><i class='fa fa-check'></i> Action is executed<bR>";
    if(isset($this->paymentLinkSent) && $this->paymentLinkSent) {
        echo "<i class='fa fa-check'></i> Payment link has been sent.<br>";
    }
    echo "</div>";
}
$this->clearSavedBookingData();

$bookingid = $_POST['data']['bookingid'];

$_SESSION['latestBookingLoadedOnPms'] = $bookingid;

echo "<input type='hidden' id='openedbookingid' value='".$bookingid."'>";
$pmsManager = $this->getApi()->getPmsManager();
$config = $pmsManager->getConfiguration($this->getSelectedName());

$lang = $this->getFactory()->getCurrentLanguage();
$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
$hasArx = false;
if($config->arxHostname) {
    $hasArx = true;
}
foreach ($types as $idx => $type) {
    $types[$type->id] = $type;
}

$booking = $pmsManager->getBooking($this->getSelectedName(), $bookingid);
$user = $this->getApi()->getUserManager()->getUserById($booking->userId);
if(!$booking->confirmed) {
    ?>
    <div class='needconfirmation'>
        <?php if($booking->unConfirmed) {
            echo "This booking has been rejected by administrator.";
        } else {
            ?>
            This booking has not been confirmed yet.<br>
        <?php } ?>
    </div>
    <?php
}

if($booking->isDeleted) {
    ?>
    <div style='background-color:red; color: white; padding: 10px; margin-bottom: 10px; text-align:center;'>
    This booking is deleted
    <span gstype="form" method="undeleteBooking">
        <input type='hidden' gsname='bookingid' value='<? echo $booking->id; ?>'>
        <span gstype="submitToInfoBox" type="button" style='color:yellow; cursor:pointer; display:none;'>undelete it?</span>
    </span>

                                   
    </div>
    <?php
}

$this->includefile("contactdata");
if($config->fastOrderCreation) {
    echo "<div class='warnunsettledamountouter'>";
    $this->includefile("warningunsettledorders");
    echo "</div>";
}

echo "<div class='bookinginfo'>";
echo "<span class='tabs'>";
echo "<span class='tab' area='roomsbooked'>";
switch($config->bookingProfile) {
    case "subscription":
        echo "Subscription";
        break;
    default:
        echo "Rooms booked";
        break;
}
if($booking->totalPrice && ($booking->totalPrice < 1000000)) {
    echo " (kr " . round($booking->totalPrice) . ")";
}
echo "</span>";
if($config->requirePayments) {
    $totalOrders = 0;
    $orders = $this->getOrdersForSelectedBooking();
    foreach($orders as $order) {
        $totalOrders += $this->getApi()->getOrderManager()->getTotalAmount($order);
    }
    echo "<span class='tab' area='orderinformation'>Orders";
    if($totalOrders) {
        echo " (kr " . round($totalOrders) . ")";
    }
    echo "</span>";
    
    echo "<span class='tab' area='orderpreview'>Preview</span>";
    
}
echo "<span class='tab' area='messagearea'>Messaging</span>";
$hasAddons = false;
foreach($config->addonConfiguration as $addonConfig) {
    if($addonConfig->isActive || $addonConfig->isAvailableForBooking || $addonConfig->isAvailableForCleaner) {
        $hasAddons = true;
    }
}
if($hasAddons) {
    echo "<span class='tab' area='addons'>Addons</span>";
}
echo "<span class='tab' area='otherbookingoptions'>Other</span>";
if($hasArx && $config->bookingProfile == "subscription") {
    echo "<span class='tab' area='carddata'>Card / code</span>";
}
if($config->functionsEnabled) {
    echo "<span class='tab' area='functions'>Conference</span>";
}
echo "</span>";
echo "<div style='clear:both;'></div>";
echo "<div class='tabarea roomsbooked'>";
    $this->mightInclude("roomsbooked");
    echo "<div style='clear:both;'></div>";
echo "</div>";
echo "<div class='tabarea addons'>";
    $this->mightInclude("addons");
echo "</div>";
echo "<div class='tabarea messagearea'>";
    $this->mightInclude("messagearea");
echo "</div>";
if($config->requirePayments) {
    echo "<div class='tabarea orderinformation'>";
    $this->mightInclude("orderinformation");
    echo "</div>";
    echo "<div class='tabarea orderpreview'>";
    $this->mightInclude("orderpreview");
    echo "</div>";
}

if($hasArx) {
    echo "<div class='tabarea carddata'>";
    $this->mightInclude("carddata");
    echo "</div>";
}

echo "<div class='tabarea otherbookingoptions'>";
$this->mightInclude("otherbookingoptions");
echo "</div>";

if ($config->functionsEnabled) {
    echo "<div class='tabarea functions'>";
    $this->mightInclude("functions");
    echo "</div>";
}

if(!$booking->confirmed) { 
    $default =  $pmsManager->getDefaultMessage($this->getSelectedName(), $bookingid);
    ?>
    <div class='needconfirmation' style="margin:0px;margin-top: 20px;">
        <h2>Confirm this booking</h2>
        <div gstype="form" method="confirmBooking">
            <input type='hidden' gsname='bookingid' value='<? echo $booking->id; ?>'>
            <div style='text-align:left;'>Message to recipient:</div>
            <textarea style='width:100%; height: 100px; margin-bottom: 5px;' gsname='message'><? echo $default; ?></textarea>
            <span gstype="submit" class='pmsbutton' gsvalue='confirm'>Confirm booking</span>
            <span gstype="submit" class='pmsbutton' gsvalue='unconfirm' style='background-color:red;'>Do not confirm this booking</span>
        </div>
    </div>
<?php } 
?>
<br><br><br>
<span class='pmsbutton doneediting' style='float:right;'><? echo $this->__w("Done editing"); ?></span> 
<span class='pmsbutton' onclick='$(".resendconfirmationoption").slideDown();$(window).scrollTop(100000);' style='float:right; background-color:orange; margin-right: 20px;'><? echo $this->__w("Resend confirmation"); ?></span> 
<span class='pmsbutton showlog' bookingid='<? echo $booking->id; ?>' style='background-color:yellow; color:#000;'><? echo $this->__w("Show log"); ?></span>
<div style='clear:both;'></div>

<div style="text-align:right; margin-top: 10px;display:none;" class='resendconfirmationoption'>
    <input type="text" style="font-size: 16px; padding: 4px;" value='<?php echo $user->emailAddress; ?>' class='emailtosendconfirmationto'> <span class="pmsbutton sendconfirmation">Send</span>
</div>

<div id="logarea"></div>
</div>

<script>
    var area = localStorage.getItem('selectedbookinginfotab');
    if(!area) {
        area = "roomsbooked";
    }
    if(area) {
        $('.tab[area="'+area+'"]').click();
    }
    
    PubSub.subscribe("backendviewloaded", function() {
        app.PmsManagement.reloadtab();
    });
    
</script>