<?php
 /* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();
$user = $this->getApi()->getUserManager()->getUserById($booking->userId);
$instances = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
if($instances) {
    $instances2 = array();
    foreach($instances as $instance) {
        $ns = "ns_" . str_replace("-","_", $instance->id) ."\\".$instance->appName;
        $instances2[$ns] = $instance;
    }
    $instances = $instances2;
}
$avtalegiro = $this->getApi()->getStoreApplicationPool()->getApplication("8f5f7f8f-de42-4867-82cc-63eb0cb55fa1");
$config = $this->getConfigurationToUse();
?>
<table width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <th width="60%">Form filled out when registering</th>
        <th width="40%">Internal comments
            <span gstype="form" method="showBookingInformation">
                <input type='hidden' gsname="bookingid" value="<?php echo $booking->id; ?>">
                <i class='fa fa-refresh' gstype="submitToInfoBox" title='Refresh booking' style='cursor:pointer;'></i>
            </span>
        </th>
    </tr>
    <tr>
        <td valign="top">
            <?
            if($booking->channel) { echo "Channel : " . $booking->channel . "<br>"; }
            if($booking->couponCode) { echo "Discount coupon code :  " . $booking->couponCode . "<br>"; }
            if($booking->wubookchannelreservationcode) { echo "Channel res id : " . $booking->wubookchannelreservationcode . "<br>"; }
            if($booking->wubookreservationid) { 
                $modrestitle = "";
                foreach($booking->wubookModifiedResId as $modres) {
                    $modrestitle .= $modres . "<br>";
                }
                echo "<span title='$modrestitle'>";
                echo "Wubook res id : " . $booking->wubookreservationid . " (<a href='https://wubook.net/bookings/".$booking->wubookreservationid."' target='_new'>open in wubook</a>)<br>"; 
                echo "</span>";
                
            }
            if($booking->channel) {
                echo "<span class='marknoshowwubook' wubookid='".$booking->wubookreservationid."'> Wubook no show : ";
                echo $booking->wubookNoShow ? "Yes" : "no";
                echo "</span><br>"; 
            }
            if($booking->nonrefundable) {
                echo "This booking is non refundable, <span style='color:blue; cursor:pointer;' gstype='forceClicksubmitToInfoBox' method='toggleNonRefundable' gsname='id' gsvalue='".$booking->id."'>mark as refundable<span><br>";
            } else {
                echo "This booking is refundable, <span style='color:blue; cursor:pointer;' gstype='forceClicksubmitToInfoBox' method='toggleNonRefundable' gsname='id' gsvalue='".$booking->id."'>mark as non refundable<span><br>";
            }
            $isselect = false;
            
            foreach($config->data as $key => $field) {
                $key = $field->name;
                $value = "";
                if(isset($booking->registrationData->resultAdded->{$key}))
                    $value = $booking->registrationData->resultAdded->{$key};
                    
                if(stristr($key, "user_")) {
                    continue;
                }
                if(stristr($key, "company_")) {
                    continue;
                }
                if($key == "agreetoterms") {
                    continue;
                }
                if($key == "choosetyperadio") {
                    continue;
                }
                if($field->type == "radio"){
                    $checked = $field->title == $value ? "CHECKED" : "";
                    echo "<input class='radioinput' type='radio' name='".$name."' field='".$key."' value='" . $field->title . "' $checked>".$field->title;
                    continue;
                }
                if($field->type == "select"){
                    if(!$isselect) {
                        echo "<select class='contactdatadropdown' field='".$key."'>";
                    }
                    $isselect = true;
                    $selected = $field->title == $value ? "SELECTED" : "";
                    echo "<option value='" . $field->title . "' $selected>".$field->title."</option>";
                    continue;
                }
                if($isselect) {
                    echo "</select>";
                }
                $name = "";
                foreach($booking->registrationData->data as $val) {
                    if($val->name == $key) {
                        $name = $val->title;
                        if(!$val->title || $val->type == "radio") {
                            $name = $key;
                        }
                    }
                }
                if($key == "agreetoterms") {
                    $name = "Agreed to terms and condition";
                    if($value == "false") {
                        $value = $this->__w("No");
                    } else {
                        $value = $this->__w("Yes");
                    }
                }
                if($key == "choosetyperadio") {
                    $name = "Registration type";
                }                
                if(!$name) {
                    continue;
                }   
            ?>
            <div class='editfieldrow'>
                <b><i class='fa fa-edit editfield'></i> <? echo $name; ?></b><br>
                <span style='padding-left: 20px; padding-bottom: 10px;padding-top: 3px;display:block;' class='fieldtoedit'><? echo $value; ?></span>
                <div style='text-align:right'>
                    <input type='button' value='Save' class='savenewfielddata' style='display:none;' field='<?php echo $key; ?>'>
                </div>
            </div>         
            <?php
            }
            $keyarrays = array();
            foreach($booking->registrationData->resultAdded as $key => $val) {
                $keyarrays[$key] = $val;
            }
            echo "Created : " . date("d.m.Y H:i", strtotime($booking->rowCreatedDate)) . "<bR>";
            ksort($keyarrays);
            echo "<span onclick='$(\".allregisteredfields\").toggle()' style='cursor:pointer;color:blue;'>Show all registered fields</span>";
            echo "<div class='allregisteredfields' style='display:none;'>";
            echo "<table cellspacing='0' cellpadding='0' width='100%'>";
            
            echo "<tr>";
            echo "<tH>Key</th><th>Value</th>";
            echo "</tR>";
                
            foreach($keyarrays as $key => $val) {
                echo "<tr>";
                echo "<td>" . $key . "</td><td>" . $val . "</td>";
                echo "</tr>";
            }
            echo "</table>";
            echo "</div>";
            ?>
        </td>
        <td valign="top">
            <span gstype='form' method="addComment">
                <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>
                <input type="text" style="width: 260px;" gsname="comment" gstype="clicksubmitToInfoBox">
                <input type="button" value="Add" gstype="submitToInfoBox">
            </span>
            <br>
            <span class="commentfield">
                <?php
                $res = array();
                foreach($booking->comments as $key => $obj) {
                    $res[$key] = $obj;
                }
                krsort($res);
                foreach($res as $time => $obj) {
                    /* @var $obj core_pmsmanager_PmsBookingComment */
                    echo $obj->comment . "<br>";
                    echo "<div class='commentbottom'>";
                    if($this->getApi()->getUserManager()->getUserById($obj->userId)) {
                        echo "By " . $this->getApi()->getUserManager()->getUserById($obj->userId)->fullName . ", " . date("d.m.Y H:i", $time / 1000);
                    }
                    echo "</div>";
                }
                ?>
            </span>
        </td>
    </tr>
</table><br>

<?php
if(sizeof($booking->registrationData->contactsList) > 0) {
    echo '<h2>Kontaktliste</h2>';
    echo "<table cellspacing='0' cellpadding='0'>";
    echo "<tr>";
    echo "<th>Name</th>";
    echo "<th>Email</th>";
    echo "<th>Phone</th>";
    echo "<th>Title</th>";
    echo "</tr>";
    foreach($booking->registrationData->contactsList as $contact) {
        echo "<tr>";
        echo "<td>" . $contact->name . "</td>";
        echo "<td>" . $contact->email . "</td>";
        echo "<td>" . $contact->phone . "</td>";
        echo "<td>" . $contact->title . "</td>";
        echo "</tr>";
    }
    echo "</table>";
    ?>
    <?php
}


if(!$user->fullName) {
    $user->fullName = "Unknown name";
}
?>

<div class='contactdata'>
    <span style='float:right; cursor:pointer;'>
        <?php if($booking->testReservation) { ?>
        <span gstype='form' method="markTest">
            <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>
            <span gstype='submitToInfoBox' style='font-size: 10px;'>(This is in test mode, unmark)</span>
        </span>
        <?php } else { ?>
        <span gstype='form' method="markTest">
            <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>
            <span gstype='submitToInfoBox' style='font-size: 10px;'>(Mark booking as test)</span>
        </span>
        <?php } ?>
    </span>

    
    <div style='padding-left: 10px;'>
        <span class='roomprefix'>User</span>
        <span class='roompostfix' style='width: 227px;
    display: block;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;' >
            <?php
            if(!$user->cellPhone) {
                $user->prefix = "";
                $user->cellPhone = "no phone set";
            }
            if(!$user->emailAddress) {
                $user->emailAddress = "no email set";
            }
            ?>
            <span style="font-size:12px">
                <i class='fa fa-edit loadedituser'></i> <? echo $user->fullName; ?>, <? echo $user->emailAddress . ", phone +" . $user->prefix . $user->cellPhone; ?>
                <span id='edituserview' class='edituserview'></span>
            </span>
        </span>
        <div style='clear:both;'></div>
        <?php $booking->bookedByUserId;  if($booking->bookedByUserId) { ?>
            <span class='roomprefix'>Booked by</span>
            <span class='roompostfix' style='width: 227px;
    display: block;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;'>
                <?php
                $booker = $this->getApi()->getUserManager()->getUserById($booking->bookedByUserId);
                echo $booker->fullName;
                ?>
            </span>
            <div style='clear:both;'></div>
        <?php } ?>
        <? if($user->company && sizeof($user->company) > 0) { ?>
            <span class='roomprefix'>Company</span>
            <span class='roompostfix'>
            <? 
            foreach($user->company as $companyId) {
                $company = $this->getApi()->getUserManager()->getCompany($companyId);
                echo "<span style='font-size:12px'>";
                ?><a onclick='$(".PmsManagement .editcompanybox").fadeIn(function() {$(".editcompanybox select").chosen(); });'><?php
                echo $company->name;
                ?></a> <?php
                echo "Email: ";
                if($company->email) {
                     $company->email;
                } else {
                    echo "No email";
                }
                echo ", phone: ";
                if($company->phone) {
                    echo "+" . $company->prefix . $company->phone;
                } else {
                    echo "Missing phone";
                }
                echo "</span>";
            }
            ?></span>
            <div style='clear:both;'></div>
        <? } else {
            ?>
            <span class='roomprefix'>Company</span>
            <span class='roompostfix' style="font-size: 12px;">
                <span onclick='$(".PmsManagement .editcompanybox").fadeIn(function() {$(".editcompanybox select").chosen(); });'>No company connected to this user</span>
            </span>
            <div style='clear:both;'></div>
            <?php
        } 
        $this->includefile("companydata");
        ?>
        <div style='clear:both;'></div>
    </div>
</div>
<?php
$this->includeEventCalendar($booking->id);
?>