<?php
 /* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();
$user = $this->getApi()->getUserManager()->getUserById($booking->userId);
$instances = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
$instances2 = array();
foreach($instances as $instance) {
    $ns = "ns_" . str_replace("-","_", $instance->id) ."\\".$instance->appName;
    $instances2[$ns] = $instance;
}
$instances = $instances2;
$avtalegiro = $this->getApi()->getStoreApplicationPool()->getApplication("8f5f7f8f-de42-4867-82cc-63eb0cb55fa1");
?>

<div class='contactdata'>
    <h2>Contact data</h2>
    <div style='padding-left: 10px;'>
        <span class='roomprefix'>Type</span>
        <span class='roompostfix'>
        <? 
        if($user->isPrivatePerson) {
            echo "Private";
        } else {
            echo "Company";
        }
        ?>
        </span>
        <div style='clear:both;'></div>
        <? if($user->isPrivatePerson) { ?>
            <span class='roomprefix'>Birthday</span>
            <span class='roompostfix'><? echo $user->birthDay; ?></span>
            <div style='clear:both;'></div>
        <? } else { ?>
            <span class='roomprefix'>Orgid</span>
            <span class='roompostfix'><? echo $user->birthDay; ?></span>
            <div style='clear:both;'></div>
        <? } ?>
        <span class='roomprefix'>Name</span>
        <span class='roompostfix'><? echo $user->fullName; ?></span>
        <div style='clear:both;'></div>
        <span class='roomprefix'>Address</span>
        <span class='roompostfix'><? echo $user->address->address; ?></span>
        <div style='clear:both;'></div>
        <span class='roomprefix'>Postal code</span>
        <span class='roompostfix'><? echo $user->address->postCode; ?></span>
        <div style='clear:both;'></div>
        <span class='roomprefix'>City</span>
        <span class='roompostfix'><? echo $user->address->city; ?></span>
        <div style='clear:both;'></div>
        <span class='roomprefix'>Email</span>
        <span class='roompostfix'><? echo $user->emailAddress; ?></span>
        <div style='clear:both;'></div>
        <span class='roomprefix'>Phone</span>
        <span class='roompostfix'>+<? echo $user->prefix . " " . $user->cellPhone; ?></span>
        <div style='clear:both;'></div>
        <span class='roomprefix'>User id</span>
        <span class='roompostfix'><? echo $user->customerId; ?></span>
        <div style='clear:both;'></div>
        <?php if($avtalegiro) { 
            echo "<span class='roomprefix'>Avtalegiro</span>";
            echo "<span class='roompostfix'>";
            /* @var $autogiroapp ns_8f5f7f8f_de42_4867_82cc_63eb0cb55fa1\Avtalegiro */
            $autogiroapp = $this->getFactory()->getApplicationPool()->createInstace($avtalegiro);
            $link = $autogiroapp->createLink($user->id);
            echo "<a href='".$autogiroapp->createLink($user->id)."' target='_new'>Avtalegiro</a>";
            echo " - <a href='".$autogiroapp->createLink($user->id)."' target='_new'>Efaktura</a>";
            echo " - <a href='".$autogiroapp->createLink($user->id)."' target='_new'>Avtalegiro + efaktura</a>";
            echo "</span>";
            echo "<div style='clear:both;'></div>";
            ?>
        <? } ?>
        <div style='clear:both;'></div>
        <span class='roomattribute'>
                <span class='roomprefix'>
                    <i class='fa fa-edit'></i> Payment type
                </span>
            <span class='roompostfix'>
            <span class="viewmode">
                    <?
                    $appSettings = $instances[$user->preferredPaymentType];
                    $instance = $this->getFactory()->getApplicationPool()->createInstace($appSettings);
                    echo $appSettings->appName;
                    ?>
                </span>
                <span class="editmode" gstype='form' method="setNewPaymentType">
                    <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>
                    <select gsname="newtype">
                        <?php 
                        foreach($instances  as $ns => $instance) {
                            $selected = "";
                            if($ns == $user->preferredPaymentType) {
                                $selected = "SELECTED";
                            }
                            echo "<option value='".$ns."' $selected>".$instance->appName."</option>";
                        }
                        ?>
                    </select>
                    <span class='pmsbutton tiny' gstype='submitToInfoBox'>Change</span>
                </span>
            </span>
        </span>
        <div style='clear:both;'></div>
    </div>
</div>