<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$itemid = $_POST['data']['itemid'];

$cart = $this->getApi()->getCartManager()->getCart();
echo "<input type='hidden' value='$itemid' class='itemidinput'>";
echo "<div style='position:absolute; width: 300px; background-color:#fff; border: solid 1px; padding: 5px; right: 30px;'>";
foreach($cart->items as $item) {
    if($item->cartItemId == $itemid) {
        if(sizeof($item->priceMatrix) > 0) {
            foreach($item->priceMatrix as $day => $val) {
                echo $day . " <input type='txt' value='" . $val . "' style='width:50px;' offset='$day' class='extrapriceinput matrixpriceinput'><bR>";
            }
        }
        if($item->itemsAdded) {
            foreach($item->itemsAdded as $addonItem) {
                echo "<div class='addonstoedit' addonid='".$addonItem->addonId."'>";
                echo date("d.m.Y", strtotime($addonItem->date)) . " ";
                echo "<input type='txt' value='" . $addonItem->count . "' style='width:50px;' class='addonscountinput addoncountinput'>";
                echo "<input type='txt' value='" . $addonItem->price . "' style='width:50px;' class='extrapriceinput addonprice'>";
                echo "</div>";
            }
        }
    }
}
echo "<input type='button' value='Update price' class='saveitemsonorder'>";
echo "</div>";
?>

<script>
    $('.saveitemsonorder').click(function() {
        var area = $(this).closest('.loadEditAddonAndPriceMatrix');
        var matrixdata = {};
        var addondata = {};
        
        $('.matrixpriceinput').each(function() {
            matrixdata[$(this).attr('offset')] = $(this).val()
        });
        
        $('.addonstoedit').each(function() {
            var id = $(this).attr('addonid');
            var addonItemData = {};
            addonItemData['price'] = $(this).find('.addonprice').val();
            addonItemData['count'] = $(this).find('.addoncountinput').val();
            addondata[id] = addonItemData;
        });
        
        var event = thundashop.Ajax.createEvent('','saveItemOnOrder',$(this), {
            "itemid" : area.find('.itemidinput').val(),
            "matrixdata" : matrixdata,
            "addondata" : addondata
        });
        thundashop.Ajax.postWithCallBack(event, function(res) {
            
        });
        area.hide();
    });
    
    $('.extrapriceinput,.addonscountinput').keyup(function() {
        var area = $(this).closest('.loadEditAddonAndPriceMatrix');
       var count = 0;
       var amount = 0;
       var addonscount = 0;
       area.find('.extrapriceinput').each(function() {
           amount += parseFloat($(this).val());
           count++;
       });
       area.find('.addonscountinput').each(function() {
           addonscount += parseInt($(this).val());
       });
       var avg = Math.round(amount / count);
       $(this).closest('.cartitemselectionrow').find('.cartprice').val(avg);
       $(this).closest('.cartitemselectionrow').find('.cartcount').val(addonscount);
       app.PmsManagement.calculateCartCostFromTarget($(this));
    });