<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();
$userId = $booking->userId;
$type = "booking";
$orderId = "";
if(isset($_POST['data']['orderid'])) {
    $orderId = $_POST['data']['orderid'];
    if($orderId) {
        $order = $this->getApi()->getOrderManager()->getOrder($_POST['data']['orderid']);
        $userId = $order->userId;
        $type = "order";
    }
}
$user = $this->getApi()->getUserManager()->getUserById($userId);
$allUsers = $this->getApi()->getUserManager()->getAllUsers();
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());

if(!$user->address) {
    $user->address = new core_usermanager_data_Address();
}
$disabled = "";
if($user->isTransferredToAccountSystem && $config->denyUpdateUserWhenTransferredToAccounting) {
    $disabled = "DISABLED";
}
$paymentApps = (array)$this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();

?>
<div class="edituserbox" gstype='form' method='saveUser'>
    <input type='hidden' value='<? echo $type; ?>' class='changeusertype'>
    <input type='hidden' value='<? echo $orderId; ?>' gsname='orderid'>
    <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>
    <input type='hidden' value='<? echo $user->id; ?>' gsname='userid'>
    <table cellspacing='0' cellpadding='0'>
        <tr><th colspan="2">Userdata</th></tr>
        <tr>
            <td>Change user</td>
            <td>
                <select class='changeuseronbooking' bookingid='<?php echo $booking->id; ?>' orderid='<?php echo $orderId; ?>'>
                <?php
                foreach($allUsers as $user2) {
                    $selected = "";
                    if($user2->id == $user->id) {
                        $selected = "SELECTED";
                    }
                    $email = "";
                    if($user2->emailAddress) {
                        $email = " (" . $user2->emailAddress . ")";
                    }
                    echo "<option value='" . $user2->id . "' " . $selected.'>'.$user2->fullName . $email . "</option>";
                }
                ?>
                </select><br>
                <span style='cursor:pointer; color:blue;' class='createanewuserfromeditbox' bookingid='<?php echo $booking->id; ?>' orderid='<?php echo $orderId; ?>'>create a new user</span>
            </td>
        </tr>
        <tr><td><i class='fa fa-question' title='This is the name of the booker, if a company this is the company name. If its a private person its the name of the person.'></i> Name</td><td><input type="txt" gsname="fullName" value="<?php echo $user->fullName; ?>" <?php echo $disabled; ?>></td><tr>
        <tr><td>Prefix</td><td><input type="txt" gsname="prefix" value="<?php echo $user->prefix; ?>" <?php echo $disabled; ?>></td><tr>
        <tr><td>Phone</td><td><input type="txt" gsname="cellPhone" value="<?php echo $user->cellPhone; ?>" <?php echo $disabled; ?>></td><tr>
        <tr><td>Email</td><td><input type="txt" gsname="emailAddress" value="<?php echo $user->emailAddress; ?>" <?php echo $disabled; ?>></td><tr>
        <tr><td>Address</td><td><input type="txt" gsname="address.address" value="<?php echo $user->address->address; ?>" <?php echo $disabled; ?>></td><tr>
        <tr><td>Postcode</td><td><input type="txt" gsname="address.postCode" value="<?php echo $user->address->postCode; ?>" <?php echo $disabled; ?>></td><tr>
        <tr><td>City</td><td><input type="txt" gsname="address.city" value="<?php echo $user->address->city; ?>" <?php echo $disabled; ?>></td><tr>
        <tr><td>Birthdate</td><td><input type="txt" gsname="birthDay" value="<?php echo $user->birthDay; ?>" <?php echo $disabled; ?>></td><tr>
        <tr><td>Relationship</td><td><input type="txt" gsname="relationship" value="<?php echo $user->relationship; ?>" <?php echo $disabled; ?>></td><tr>
        <tr><td>Payment type</td><td>
                <select gsname='preferredpaymenttype'>
                    <?php
                    echo "<option value='' $selected>Default</option>";
                    foreach($paymentApps as $id => $type) {
                        $selected = "";
                        $instance = $this->getFactory()->getApplicationPool()->createInstace($type);
                        if($type->id == $user->preferredPaymentType) {
                            $selected = "SELECTED";
                        }
                        if(method_exists($instance, "getName")) {
                            echo "<option value='".$type->id."' $selected>".$instance->getName()."</option>";
                        }
                    }
                    ?>
                </select>
                
            </td><tr>
            <?php 
                if($this->hasAccountingTransfer()) {
                    ?>
                    <?php $accId = $user->customerId; 
                    if($user->accountingId) {
                        $accId = $user->accountingId;
                    }
                    if($accId == -1 || $accId == "-1") {
                        $accId = "";
                    }
                    ?>
                    <tr><td>Accounting id</td><td><input type="txt" gsname="accountingId" value="<?php echo $accId; ?>" disabled></td><tr>
                    <?php
                }
            ?>
        <?php
        if($user->isTransferredToAccountSystem && $config->denyUpdateUserWhenTransferredToAccounting) {
            echo "<tr><td colspan='2'>This user has been transferred to accounting, and can not be updated anymore.</td></tr>";
        }
        ?>
        <tr><td style='font-size: 12px; line-height: 12px; color:blue; cursor:pointer;' class='setNewPasswordOnUser'>New<br>password</td><td><span class='pmsbutton closeadduser' style='background-color:red;'>Close</span> <span class='pmsbutton' gstype='submitToInfoBox'>Save changes</span></td><tr>
    </table>
</div>
