<?php
/* @var $this \ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$bookingId = $_POST['data']['bookingId'];
$roomId = $_POST['data']['pmsRoomId'];
$booking = $this->getApi()->getPmsManager()->getBooking($this->getSelectedName(), $bookingId);
$types = $this->getTypes();
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
foreach($booking->rooms as $room) {
    if($room->pmsBookingRoomId == $roomId) {
        break;
    }
}

?>

<input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
<input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
<?php
$now = $room->date->start;
if(strtotime($now) < time() && strtotime($room->date->end) > time()) {
    $now = $this->convertToJavaDate(time());
}
?>
<i class="fa fa-times" style="float:right; cursor:pointer;" onclick="$('.editmode').hide();"></i>
<b>Room selected</b><br>
<select gsname='itemid'>
    <?php 
    $isAvailableItem = $this->getApi()->getBookingEngine()->getAllAvailbleItemsWithBookingConsidered($this->getSelectedName(), $now, $room->date->end, $room->bookingId);
    $isAvailableItem = $this->indexList($isAvailableItem);
    $allItems = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
    echo "<option value=''>Unassigned</option>";
    foreach($allItems as $item) {
        $selected = "";
        if($types[$item->bookingItemTypeId]->addon > 0) {
            continue;
        }

        $taken = " (" .$this->__w("Occupied"). ")";
        if($isAvailableItem[$item->id]) {
            $taken = "";
        }

        $desc = "";
        if($item->description) {
            $desc = ", ". strtolower($item->description);
        }

        if($room->bookingItemId == $item->id) {
            $selected = "SELECTED";
        }
        $clean = "";
        if($config->cleaningInterval > 0) {
            $clean = " (not clean)";
            $additionalInfoList = $this->getAdditionalInfoList();
            if($additionalInfoList[$item->id]->isCleanNotToday) {
                $clean = "(clean)";
            }
        }
        echo "<option value='".$item->id."' $selected>" . $item->bookingItemName . ", " . $types[$item->bookingItemTypeId]->name . "$taken $desc $clean" . "</option>";
    }
    ?>
</select><br>

<input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
<input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
<b>For selected time periode</b><br>
<span style='display:inline-block; width: 80px;'>Start</span> 
    <input type='text' gsname='start' value='<? echo date("d.m.Y", strtotime($room->date->start)); ?>' style='width:80px;' class='calinput'>
    <input type='text' gsname='starttime' value='<? echo date("H:i", strtotime($room->date->start)); ?>'  style='width:40px;'>
    <br>
<span style='display:inline-block; width: 80px;'>End</span> 
<input type='text' gsname='end' value='<? echo date("d.m.Y", strtotime($room->date->end)); ?>' style='width:80px;' class='calinput'>
<input type='text' gsname='endtime' value='<? echo date("H:i", strtotime($room->date->end)); ?>' style='width:40px;'>
<br>

<span class='pmsbutton tiny' gstype='submitToInfoBox' gsvalue='notsplit'>Change</span>
<?php
$start = strtotime($room->date->start);
$diff = strtotime($room->date->end) - $start;
$splitchange = false;
if($start < time() && $diff > 86400 && date("dmY", $start) != date("dmY", time())) {
    $splitchange = true;
}
