<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$d = new DateTime('first day of this month');
$d = strtotime("-1 month", $d->getTimestamp());
$d2 = time();
if(isset($_POST['data']['enddate'])) {
    $d2 = strtotime($_POST['data']['enddate']);
}
if(isset($_POST['event']) && $_POST['event'] == "globalInvoiceCreation" && $_POST['data']['preview'] !== "true") {
    echo "<h1>Orders has been created...</h1>";
}

$res = (array)$this->getApi()->getPmsInvoiceManager()->validateAllInvoiceToDates($this->getSelectedName());
if(sizeof($res) > 0) {
    echo "<br>";
    echo "<br>";
    foreach($res as $r) {
        echo "<div style='color:red; font-weight:bold'>" . $r . "</div>";
    }
    echo "<br>";
    echo "<br>";
    return;
}
?>
<div gstype="form" method="globalInvoiceCreation">
    <h2>Global order creation, just specify the end date of the order creation</h2>
    <input type="checkbox" CHECKED gsname="preview"> Create a preview<br>
    <select gsname="type">
        <option value="ended">Ended</option>
        <?php
        $select = "";
        if(isset($_POST['data']['type']) && $_POST['data']['type'] == "not_ended") { 
            $select = "SELECTED";
        }
        ?>
        <option value="not_ended" <?php echo $select; ?>>Not ended</option>
    </select>
    <input type="txt" gsname="enddate" value="<?php echo date("d.m.Y", $d2); ?>">
    <span class="pmsbutton" gstype="submit">Create orders</span>
</div>

<?php
$this->showBookersData = true;
$this->includeOrderGenerationPreview();
?>

<script>
    $('input[gsname=startdate]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('input[gsname=enddate]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
</script>