<div class='newinformationwarning'>
    <i class='fa fa-info-circle'></i> Hi there.<br>You are now using a new version of the table view below with increased filtering and performance.
    To use the old version click <b gstype='clicksubmit' style='cursor:pointer;' method='toggleFilterVersion' gsname='id' gsvalue='somevalue'>here</b>.<br>
    We will support the old version until 30.09.2016. Please report any incosistenscy to post@getshop.com.
</div>
<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$filter = $this->getSelectedFilter();
$rooms = $this->getApi()->getPmsManager()->getSimpleRooms($this->getSelectedName(), $filter);
$types = $this->getTypes();
$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$channels = $this->getChannelMatrix();
$hasPrices = false;

if($config->requirePayments) {
    $hasPrices = true;
}
foreach($items as $item) {
    $items[$item->id] = $item;
}

$rows = 0;
$headers = array();
$headers['actions'] = '<i gs_downloadexcelreport="exportBookingDataToExcel" title="Download to excel" style="cursor:pointer" class="fa fa-file-excel-o" aria-hidden="true" gs_filename="bookingdataexport"></i>';
$headers['regdate'] = "Reg";
$headers['periode'] = "Periode";
switch($config->bookingProfile) {
    case "subscription":
        $headers['visitor'] = "Owner";
        $headers['room'] = "Subscription";
        break;
    default:
        $headers['visitor'] = "Visitor";
        $headers['room'] = "Room";
        break;
}
if($hasPrices) {
    $headers['price'] = "Price";
}
$headers['state'] = "State";

if(!isset($filter->sorting)) {
    $filter->sorting = "regdate";
}

$prices = array();
$prices[1] = "daily";
$prices[2] = "monthly";
$prices[3] = "weekly";
$prices[4] = "minutly";
$prices[5] = "hourly";
$prices[6] = "secondly";
$prices[7] = "daily";
$prices[8] = "daily";


$states = array();
$states['rejected'] = "Rejected";
$states['deleted'] = "Deleted";
$states['notpaid'] = "Unpaid";
$states['confirmed'] = "Confirmed";
$states['unconfirmed'] = "Unconfirmed";
$states['active'] = "Active";
$states['ended'] = "Ended";
$states['waitingforlock'] = "Waiting for lock";

        
?>

<table width='100%' cellspacing='0' cellpadding='0'>
    <tr>
        <?php
        foreach($headers as $header => $value) {
            if($header == "price" && !$hasPrices) {
                continue;
            }
            echo "<th>" . $value . "</th>";
        }
        ?>
    </tr>
    
    <?php
    $tableArray = array();
    foreach($rooms as $room) {
        $row = array();
        $row['actions'] = "<i class='fa fa-info moreinformationaboutbooking actions' roomid='".$room->pmsRoomId."' bookingid='".$room->bookingId."'></i>";
        $row['regdate'] = date("d.m.Y H:i", strtotime($room->regDate));
        
        $diff = ($room->end - $room->start)/1000;
        if($diff < 40000) {
            $row['periode'] = date("d.m.Y H:i", $room->start/1000) . " - " . date("H:i", $room->end/1000);
        } else {
            $row['periode'] =  date("d.m.Y H:i", $room->start/1000) . "<br>" . date("d.m.Y H:i", $room->end/1000);
        }
        $row['visitor'] = "";
        foreach($room->guest as $guest) {
            $row['visitor'] .= $guest->name;
            if($guest->email) { $row['visitor'] .= " - " . $guest->email; }
            if($guest->phone) { $row['visitor'] .= " - +" . $guest->prefix . $guest->phone; }
            $row['visitor'] .= "<br>";
        }
        $row['visitor'] .= "<div class='secondary_text'>" . $room->owner . "</div>";
        if($room->keyIsReturned) {
            $row['room'] .=  '<i class="fa fa-key" title="Key has been returned" style="color:green;"></i> ';
        }
        
        $row['room'] = $room->room;
        $row['room'] .= "<div class='secondary_text'>".$room->roomType."</div>";
        $row['price'] = $room->price;
        $row['state'] = $room->progressState;
        $tableArray[] = $row;
    }
    foreach($tableArray as $row) {
        echo "<tr>";
         foreach($headers as $header => $value) {
             if($header == "state") {
                 echo "<td class='".$row[$header]."'>" . $states[$row[$header]] . "</td>";
             } else {
                 echo "<td>" . $row[$header] . "</td>";
             }
         }
        echo "</tr>";
    }
    ?>
</table>
