<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */

$filter = $this->getSelectedFilter();
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$channels = $this->getChannelMatrix();


$searchtypes = array();
$searchtypes['registered'] = "Registered";
$searchtypes['active'] = "Active";
$searchtypes['uncofirmed'] = "Unconfirmed";
$searchtypes['checkin'] = "Checking in";
$searchtypes['checkout'] = "Checking out";
$searchtypes['inhouse'] = "Inhouse";
$searchtypes['deleted'] = "Deleted";
$searchtypes['stats'] = "Coverage";
$searchtypes['summary'] = "Summary";
if($config->requirePayments) {
    $searchtypes['orderstats'] = "Order statistics";
    $searchtypes['invoicecustomers'] = "Invoice customers";
    $searchtypes['unbilled'] = "Unbilled cust.";
}
?>



<div class='booking_options' gstype='form' method='setFilter' style='position:relative;'>
    <span style="float:left;">
        <input type='text' gsname='start' class="start pmsinput" style="width: 100px;" value="<? echo date("d.m.Y", strtotime($filter->startDate)); ?>">
        <input type='text' gsname='end' class="end pmsinput" style="width: 100px;" value="<? echo date("d.m.Y", strtotime($filter->endDate)); ?>">

        <select class="pmsinput filterType" gsname='filterType'>
            <?php
            foreach($searchtypes as $idx => $type) {
                $selected = "";
                if($filter->filterType == $idx) {
                    $selected = "SELECTED";
                }
                echo "<option value='$idx' $selected>$type</option>";
            }
            ?>
        </select>
        
        <?php  
        $address = $_SERVER['SERVER_NAME'];
        $username = \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->emailAddress;
        $channels = (array)$channels;
       if(sizeof($channels) > 0) { ?>
            <select class="pmsinput filterType" gsname='channel'>
                <?php
                echo "<option value=''>All channels</option>";
                foreach($channels as $idx => $channel) {
                    $selected = "";
                    if($filter->channel == $idx) {
                        $selected = "SELECTED";
                    }
                    echo "<option value='$idx' $selected>$channel</option>";
                }
                ?>
            </select>
        <? } ?>
        <span gstype="submit" class="pmsbutton setFilter">Show</span>
        <span  style=' padding-left: 10px; top: 15px;display:inline-block;position:absolute;cursor:pointer;'>
            <i class='fa fa-trash-o' gstype="clicksubmit" method='emptyfilter' gsname="id" gsvalue="somevalue" title='Empty filter'></i>
            <i class='fa fa-refresh' gstype="clicksubmit" method='runProcessor' gsname="id" gsvalue="somevalue" title='Manually run processor'></i>
            <i class='fa fa-mobile-phone' style='font-size: 16px;' onclick='window.open("http://getshop.express#/login?address=<?php echo $address; ?>&username=<?php echo $username; ?>&password=")'></i>
        </span>
    </span>
   
    <input type="txt" gsname='searchWord' placeholder="Search" gstype="submitenter" class="pmsinput searchword" value="<? echo @$filter->searchWord; ?>">
    <span gstype="submit" class="pmsbutton addGroupOptions">Search</span>
    <br><br>
<?php
echo "<div style='text-align:left;' class='roomfilter'>";
$types = $this->getTypes();

if($config->fastCheckIn) {
    $this->includefile("fastcheckin");
}
if(!isset($filter->typeFilter)) {
    $filter->typeFilter = array();
}
foreach($types as $id => $type) {
    echo "<span class='typefilter'>";
    $checked = "";
    if(in_array($id, $filter->typeFilter)) {
        $checked = "CHECKED";
    }
    echo "<input type='checkbox' method='addTypeFilter' gsname='filter_$id' $checked>";
    echo $type->name . "</span>";
}
$checked = "";
$incDeleted = "";
if($this->isGroupedByBooking()) {
    $checked = "CHECKED";
}
if($this->isIncludeDeleted()) {
    $incDeleted = "CHECKED";
}
echo "<input type='checkbox' gstype='clicksubmitforce' method='groupByBooking' gsname='id' gsvalue='' $checked> Group by booking ";
echo "<input type='checkbox' gstype='clicksubmitforce' method='includeDeleted' gsname='incdelete' $incDeleted class='clicksubmitcheckbox'> Include deleted";
echo "</div>";
echo "<br>";
echo "</div>";

$this->includeManagementViewResult();
 ?>

<script>
    $('.start.pmsinput').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
    onSelect: function(dateText) {
        var date = moment(dateText, "DD.MM.YYYY");
        var month = (moment(date).get('month')+1);
        if(month < 10) {
            month = "0" + month;
        }
        var currentEnd = $('.end.pmsinput').val();
        var endMoment = moment(currentEnd, "DD.MM.YYYY");
        
        var diff = endMoment.diff(date, "minutes");
        if(diff < 0) {
            var day = moment(date).get('date');
            if(day < 10) {
                day = "0" + day;
            }
            $('.end.pmsinput').val(day + "." + month + "." + moment(date).get('year'));
        }
      }
    });
    $('.end.pmsinput').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            var date = moment(dateText, "DD.MM.YYYY");
            var month = (moment(date).get('month')+1);
            if(month < 10) {
                month = "0" + month;
            }
            var currentEnd = $('.start.pmsinput').val();
            var endMoment = moment(currentEnd, "DD.MM.YYYY");

            var diff = endMoment.diff(date, "minutes");
            if(diff > 0) {
                var day = moment(date).get('date');
                if(day < 10) {
                    day = "0" + day;
                }
                $('.start.pmsinput').val(day + "." + month + "." + moment(date).get('year'));
            }
        }
    });
</script>