<div class='orderinfobox'></div>
<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$filter = $this->getSelectedFilter();
$rooms = $this->getApi()->getPmsManager()->getSimpleRooms($this->getSelectedName(), $filter);
$types = $this->getTypes();
$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$channels = $this->getChannelMatrix();
$hasPrices = false;
$registrationRules = $this->getApi()->getBookingEngine()->getDefaultRegistrationRules($this->getSelectedName());

if($config->requirePayments) {
    $hasPrices = true;
}
foreach($items as $item) {
    $items[$item->id] = $item;
}

$rows = 0;
$headers = array();
$headers['actions'] = '<i class="fa fa-file-excel-o loadExcelExportOptions"></i>';
$headers['regdate'] = "Reg";
$headers['periode'] = "Periode";
switch($config->bookingProfile) {
    case "subscription":
        $headers['visitor'] = "Owner";
        $headers['room'] = "Subscription";
        break;
    default:
        $headers['visitor'] = "Visitor";
        $headers['room'] = "Room";
        break;
}
$headers['price'] = "Price";
$headers['state'] = "State";
$headers['invoicedto'] = "Invoiced to";

if(!isset($filter->sorting)) {
    $filter->sorting = "regdate";
}

$prices = array();
$prices[1] = "daily";
$prices[2] = "monthly";
$prices[3] = "weekly";
$prices[4] = "minutly";
$prices[5] = "hourly";
$prices[6] = "secondly";
$prices[7] = "daily";
$prices[8] = "daily";


$states = array();
$states['rejected'] = "Rejected";
$states['deleted'] = "Deleted";
$states['notpaid'] = "Unpaid";
$states['confirmed'] = "Confirmed";
$states['unconfirmed'] = "Unconfirmed";
$states['active'] = "Active";
$states['ended'] = "Ended";
$states['waitingforlock'] = "Cleaning needed";
$states['test'] = "Test";
$states['blocked'] = "Blocked";
$states['overbooking'] = "OVERBOOKING";
$states['waiting'] = "Waiting";
$channels = $this->getChannelMatrix();

$allFieldsToPrint = array();
foreach($headers as $key => $val) {
    $allFieldsToPrint[$key] = $val;
}
foreach($registrationRules->data as $key => $data) {
    if(stristr($key, "user_")) {
        continue;
    }
    if(stristr($key, "company_")) {
        continue;
    }
    if($data->active) {
        $allFieldsToPrint[$key] = $data->title;
    }
}
//echo "<span style='background-color: #d1efff;display: inherit;'><span class='toggleColumnFilter'>Column filter</span></span>";
echo "<div gstype='form' method='saveSelectedFields' class='columnfilter'>";
$selected = $this->getSelectedFields($allFieldsToPrint);
foreach($allFieldsToPrint as $key => $val) {
    echo "<div>";
    $checked = "";
    if(isset($selected[$key])) {
        $checked = "CHECKED";
    }
    echo "<input type='checkbox' gsname='fieldtoset_$key' $checked></input>";
    echo $val;
    echo "</div>";
}
echo "<div style='text-align:right'>";
echo "<input type='button' value='Select fields' gstype='submit'>";
echo "</div>";
echo "</div>";
$selectedFields = $this->getSelectedFields($allFieldsToPrint);

?>
<table width='100%' cellspacing='0' cellpadding='0'>
    <tr>
        <?php
        foreach($selectedFields as $header => $value) {
            $sort = "";
            if($filter->sorting == $header) {
                $sort = "<i class='fa fa-arrow-down'></i>";
            }
            if($filter->sorting == $header."_desc") {
                $sort = "<i class='fa fa-arrow-up'></i>";
            }

            if($header == "actions") {
                echo "<th width='10' class='changeSorting'>$sort " . $value;
                echo "<div class='excelexportoptions' style='padding: 10px; border: solid 1px; background-color:#d1efff;position:absolute; display:none;color:#000;'>";
                $this->includefile("excelreportgenerator");
                echo "</div>";
                echo "</th>";
            } else {
                echo "<th class='changeSorting' gsvalue='$header' method='sortTable' gsname='column' gstype='clicksubmit'>$sort " . $value . "</th>";
            }
        }
        ?>
    </tr>
    
    <?php
    $tableArray = array();
    $totalGuests = 0;
    foreach((array)$rooms as $room) {
        $comments = "";
        if(isset($room->bookingComments)) {
            foreach($room->bookingComments as $time => $val) {
                if($val->deleted) {
                    continue;
                }
                $comments .= $val->comment . "<br>";
            }
        }
        
        $row = array();
        $row['bookingid'] = $room->bookingId;
        $row['actions'] = "<i class='fa fa-info moreinformationaboutbooking actions' roomid='".$room->pmsRoomId."' bookingid='".$room->bookingId."'></i>";
        if($room->channel) {
            if($room->wubookreservationid) {
                $row['actions'] .= "<br><a href='https://wubook.net/bookings/".$room->wubookreservationid."' target='_new'>" . $channels->{$room->channel} . "</a>";
            } else {
                $row['actions'] .= "<br>" . $channels->{$room->channel};
            }
        }

        $row['regdate'] = date("d.m.y H:i", strtotime($room->regDate));
        if(!$room->bookingEngineId) {
            $row['regdate'] .= "<i class='fa fa-warning dontExpand' title='Booking not added to booking engine' style='cursor:pointer;' gstype='clicksubmit' method='tryAddToBookingEngine' gsname='id' gsvalue='".$room->pmsRoomId."'></i>";
        }
        $diff = ($room->end - $room->start)/1000;
        if($diff < 40000) {
            $row['periode'] = date("d.m.Y H:i", $room->start/1000) . " - " . date("H:i", $room->end/1000);
        } else {
            $row['periode'] =  date("d.m.y H:i", $room->start/1000) . "<br>" . date("d.m.y H:i", $room->end/1000);
        }
        $row['visitor'] = "";
        if($room->nonrefundable) {
            $row['visitor'] .= "<i class='fa fa-usd' title='Non refundable'></i> ";
        }
        if(trim($comments)) {
            $row['visitor'] .= "<i class='fa fa-comment' title='$comments'></i> ";
        }
        
        
        $breakfasts = $this->hasAddon($room, 1);
        
        if($breakfasts) {
            $row['visitor'] .= "<i class='fa fa-cutlery' title='Breakfast included: $breakfasts'></i> ";
        }
        $row['visitor'] .= $this->createAddonText($room) . " ";
        
        if($config->bookingProfile != "storage") {
            foreach($room->guest as $guest) {
                $row['visitor'] .= $guest->name;
                if($guest->email) { $row['visitor'] .= " - " . $guest->email; }
                if($guest->phone) { $row['visitor'] .= "<span style='float:right;' class='secondary_text'>+" . $guest->prefix . $guest->phone . "</span>"; }
                $row['visitor'] .= "<br>";
            }
            $totalGuests += $room->numberOfGuests;
            $row['visitor'] .= "<div style='clear:both;'></div><span style='float:right;' class='secondary_text'>" .$room->numberOfGuests  . " guests";
            if($room->checkedIn) {
                $row['visitor'] .= " <i class='fa fa-smile-o' title='Guest has checked in'></i>";
            }
            $row['visitor'] .= "</span>";

        }
        $row['visitor'] .= "<div class='secondary_text'>" . $room->owner . "</div>";
        if($room->requestedEndDate) {
            $row['visitor'] .= "<div class='secondary_text'> Requested end date <span style='float:right;'>" . date("d.m.Y", strtotime($room->requestedEndDate)) . "</span></div>";
        }
        if(@$filter->groupByBooking && $room->numberOfRoomsInBooking > 1) {
            $row['visitor'] .=  '<div>+ ' . ($room->numberOfRoomsInBooking-1) . " addititional entries.</div>";
        }
        $row['room'] = "";
        if($room->keyIsReturned) {
            $row['room'] .=  '<i class="fa fa-key" title="Key has been returned" style="color:green;"></i> ';
        }
        $row['room'] .= $room->room;
        $row['room'] .= "<div class='secondary_text roominfosub'>".$room->roomType."</div>";
        $row['price'] = round($room->price);
        if($room->totalCost) {
            $row['price'] = round($room->price) . "<div style='color:#aaa' title='Total cost for this room'>(" . round($room->totalCost) . ")</div>";
        }
        if(isset($filter->filterType) && $filter->filterType == "unsettled") {
            $row['price'] = $room->totalUnsettledAmount;
        }
        $row['state'] = $room->progressState;
        $row['stateadditional'] = "";
        if($room->invoicedTo) {
            $row['invoicedto'] = date("d.m.Y", strtotime($room->invoicedTo));
        } else {
            $row['invoicedto'] = "";
        }
        if((sizeof($room->orderIds) == 0 || (!$room->paidFor && $room->progressState != "notpaid")) && $config->requirePayments) {
            $row['stateadditional'] = "<span style='font-weight:bold; color:red;' title='Orders needs to be investegated on this booking'><i class='fa fa-warning'></i> orders</span>";
        }
        if($room->createOrderAfterStay) {
            $row['stateadditional'] = "<span title='Orders are being created after the stay'><i class='fa fa-arrow-right'></i></span>";
        }
        foreach($registrationRules->data as $key => $data) {
            if(stristr($key, "user_")) {
                continue;
            }
            if(stristr($key, "company_")) {
                continue;
            }
            if($data->active) {
                $row[$key] = "";
                if(isset($booking->registrationData->resultAdded->{$data->name})) {
                    $row[$key] = $booking->registrationData->resultAdded->{$data->name};
                }
            }
        }
        
        $tableArray[] = $row;
    }
    foreach($tableArray as $row) {
        echo "<tr  class='trBookingLine' bookingid='".$row['bookingid']."'>";
         foreach($selectedFields as $header => $value) {
             if($header == "actions") {
                echo "<td align='center'>" . $row[$header] . "</td>";
             } else if($header == "periode") {
                 echo "<td class='tdBookingLine1'width='110'>" . $row[$header] . "</td>";
             } else if($header == "regdate") {
                 echo "<td class='noShowMobile' width='110'>" . $row[$header] . "</td>";
             } else if($header == "room") {
                 echo "<td class='tdBookingLine' width='150'>" . $row[$header] . "</td>";
             } else if($header == "price") {
                 echo "<td class='pricecol' width='70' align='center'>" . $row[$header] . "</td>";
             } else if($header == "state") {
                 echo "<td class='".$row[$header]."' align='center' width='110'>";
                 echo $states[$row[$header]] . "<br>";
                 echo $row['stateadditional'];
                 echo "</td>";
             } else {
                 echo "<td style='text-align:left;'>" . $row[$header] . "</td>";
             }
         }
        echo "</tr>";
    }
    ?>
    <tr>
        <td colspan='1000' style='text-align:center;'>
            <br>
            Row count: <?php echo sizeof($tableArray); ?>, Guest count: <?php echo $totalGuests; ?>
            <br>
            <br>
        </td>
</table>
<script>
    $(window).width(addClickableTr);
    $(window).resize(addClickableTr);
    
    var addClickableTr = function(){
        if($(window).width() <= '800'){
            $('.trBookingLine').addClass('moreinformationaboutbooking');
        }else{
            $('.trBookingLine').removeClass('moreinformationaboutbooking');
        }
    };
</script>
