<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$rooms = $this->getApi()->getPmsManager()->getAllRooms($this->getSelectedName());
?>

<div gstype="form" method="addRoom">
    <input gsname="name" value="">
    <span gstype="submit" class="pmsbutton addRoom"><? echo $this->__w("Create room"); ?></span>
</div>

<div class="roomlist">
    <?php 
    foreach($rooms as $room) {
        /* @var $room core_bookingengine_data_BookingItemType */
        echo $room->name . "<bR>";
    }
    ?>
</div>

