<div class='orderinfobox'></div>
<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$filter = $this->getSelectedFilter();
$rooms = $this->getApi()->getPmsManager()->getSimpleRooms($this->getSelectedName(), $filter);
$types = $this->getTypes();
$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$channels = $this->getChannelMatrix();
$hasPrices = false;
$registrationRules = $this->getApi()->getBookingEngine()->getDefaultRegistrationRules($this->getSelectedName());

if($config->requirePayments) {
    $hasPrices = true;
}
foreach($items as $item) {
    $items[$item->id] = $item;
}

$rows = 0;
$headers = array();
$headers['actions'] = '<i class="fa fa-file-excel-o loadExcelExportOptions"></i>';
$headers['regdate'] = "Reg";
$headers['periode'] = "Periode";
switch($config->bookingProfile) {
    case "subscription":
        $headers['visitor'] = "Owner";
        $headers['room'] = "Subscription";
        break;
    default:
        $headers['visitor'] = "Visitor";
        $headers['room'] = "Room";
        break;
}
$headers['price'] = "Price";
$headers['state'] = "State";

if(!isset($filter->sorting)) {
    $filter->sorting = "regdate";
}

$prices = array();
$prices[1] = "daily";
$prices[2] = "monthly";
$prices[3] = "weekly";
$prices[4] = "minutly";
$prices[5] = "hourly";
$prices[6] = "secondly";
$prices[7] = "daily";
$prices[8] = "daily";


$states = array();
$states['rejected'] = "Rejected";
$states['deleted'] = "Deleted";
$states['notpaid'] = "Unpaid";
$states['confirmed'] = "Confirmed";
$states['unconfirmed'] = "Unconfirmed";
$states['active'] = "Active";
$states['ended'] = "Ended";
$states['waitingforlock'] = "Waiting for lock";
$states['test'] = "Test";
$channels = $this->getChannelMatrix();

$allFieldsToPrint = array();
foreach($headers as $key => $val) {
    $allFieldsToPrint[$key] = $val;
}
foreach($registrationRules->data as $key => $data) {
    if(stristr($key, "user_")) {
        continue;
    }
    if(stristr($key, "company_")) {
        continue;
    }
    if($data->active) {
        $allFieldsToPrint[$key] = $data->title;
    }
}
echo "<span class='toggleColumnFilter'>Column filter</span>";
echo "<div gstype='form' method='saveSelectedFields' class='columnfilter'>";
$selected = $this->getSelectedFields($allFieldsToPrint);
foreach($allFieldsToPrint as $key => $val) {
    echo "<div>";
    $checked = "";
    if(isset($selected[$key])) {
        $checked = "CHECKED";
    }
    echo "<input type='checkbox' gsname='fieldtoset_$key' $checked></input>";
    echo $val;
    echo "</div>";
}
echo "<div style='text-align:right'>";
echo "<input type='button' value='Select fields' gstype='submit'>";
echo "</div>";
echo "</div>";
$selectedFields = $this->getSelectedFields($allFieldsToPrint);

?>
<table width='100%' cellspacing='0' cellpadding='0'>
    <tr>
        <?php
        foreach($selectedFields as $header => $value) {
            $sort = "";
            if($filter->sorting == $header) {
                $sort = "<i class='fa fa-arrow-down'></i>";
            }
            if($filter->sorting == $header."_desc") {
                $sort = "<i class='fa fa-arrow-up'></i>";
            }

            if($header == "actions") {
                echo "<th width='10' class='changeSorting'>$sort " . $value;
                echo "<div class='excelexportoptions' style='padding: 10px; border: solid 1px; background-color:#fff;position:absolute; display:none;'>";
                $this->includefile("excelreportgenerator");
                echo "</div>";
                echo "</th>";
            } else {
                echo "<th class='changeSorting' gsvalue='$header' method='sortTable' gsname='column' gstype='clicksubmit'>$sort " . $value . "</th>";
            }
        }
        ?>
    </tr>
    
    <?php
    $tableArray = array();
    foreach($rooms as $room) {
        $booking = $this->getBooking($room->bookingId);
        $comments = "";
        foreach($booking->comments as $time => $val) {
            $comments .= $val->comment . "<br>";
        }
        
        $row = array();
        $row['bookingid'] = $room->bookingId;
        $row['actions'] = "<i class='fa fa-info moreinformationaboutbooking actions' roomid='".$room->pmsRoomId."' bookingid='".$room->bookingId."'></i>";
        if($room->channel) {
            if($room->wubookreservationid) {
                $row['actions'] .= "<br><a href='https://wubook.net/bookings/".$room->wubookreservationid."' target='_new'>" . $channels->{$room->channel} . "</a>";
            } else {
                $row['actions'] .= "<br>" . $channels->{$room->channel};
            }
        }

        $row['regdate'] = date("d.m.Y H:i", strtotime($room->regDate));
        if(!$room->bookingEngineId) {
            $row['regdate'] .= "<i class='fa fa-warning' title='Booking not added to booking engine' style='cursor:pointer;' gstype='clicksubmit' method='tryAddToBookingEngine' gsname='id' gsvalue='".$room->pmsRoomId."'></i>";
        }
        $diff = ($room->end - $room->start)/1000;
        if($diff < 40000) {
            $row['periode'] = date("d.m.Y H:i", $room->start/1000) . " - " . date("H:i", $room->end/1000);
        } else {
            $row['periode'] =  date("d.m.Y H:i", $room->start/1000) . "<br>" . date("d.m.Y H:i", $room->end/1000);
        }
        $row['visitor'] = "";
        
        if(trim($comments)) {
            $row['visitor'] .= "<i class='fa fa-comment' title='$comments'></i> ";
        }
        
        if($this->hasAddon($room, 1)) {
            $row['visitor'] .= "<i class='fa fa-cutlery' title='Breakfast included'></i> ";
        }
        
        foreach($room->guest as $guest) {
            $row['visitor'] .= $guest->name;
            if($guest->email) { $row['visitor'] .= " - " . $guest->email; }
            if($guest->phone) { $row['visitor'] .= " - +" . $guest->prefix . $guest->phone; }
            $row['visitor'] .= "<br>";
        }
        $row['visitor'] .= "<div class='secondary_text'>" . $room->owner . "</div>";
        if(@$filter->groupByBooking && $room->numberOfRoomsInBooking > 1) {
            $row['visitor'] .=  '<div>+ ' . ($room->numberOfRoomsInBooking-1) . " addititional entries.</div>";
        }
        $row['room'] = "";
        if($room->keyIsReturned) {
            $row['room'] .=  '<i class="fa fa-key" title="Key has been returned" style="color:green;"></i> ';
        }
        $row['room'] .= $room->room;
        $row['room'] .= "<div class='secondary_text'>".$room->roomType."</div>";
        $row['price'] = round($room->price);
        $row['state'] = $room->progressState;
        $row['stateadditional'] = "";
        if(sizeof($room->orderIds) == 0 && $config->markBookingsWithNoOrderAsUnpaid) {
            $row['stateadditional'] = "<span style='font-weight:bold; color:red;' title='No orders has been created for this booking yet'><i class='fa fa-warning'></i> orders</span>";
        }
        foreach($registrationRules->data as $key => $data) {
            if(stristr($key, "user_")) {
                continue;
            }
            if(stristr($key, "company_")) {
                continue;
            }
            if($data->active) {
                $row[$key] = "";
                if(isset($booking->registrationData->resultAdded->{$data->name})) {
                    $row[$key] = $booking->registrationData->resultAdded->{$data->name};
                }
            }
        }
        
        $tableArray[] = $row;
    }
    foreach($tableArray as $row) {
        echo "<tr bookingid='".$row['bookingid']."'>";
         foreach($selectedFields as $header => $value) {
             if($header == "actions") {
                echo "<td align='center'>" . $row[$header] . "</td>";
             } else if($header == "periode") {
                 echo "<td width='110'>" . $row[$header] . "</td>";
             } else if($header == "price") {
                 echo "<td class='pricecol' align='center'>" . $row[$header] . "</td>";
             } else if($header == "state") {
                 echo "<td class='".$row[$header]."' align='center'>";
                 echo $states[$row[$header]] . "<br>";
                 echo $row['stateadditional'];
                 echo "</td>";
             } else {
                 echo "<td>" . $row[$header] . "</td>";
             }
         }
        echo "</tr>";
    }
    ?>
</table>
