<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
?>
<table cellspacing='0' cellpadding='0'>
    <tr>
        <td width='50%' valign='top' style='padding: 10px;'>
            <h1>Send an email to the booker</h1>
            <div gstype="form" method="sendMessage">
                <select style="width:100%; margin-bottom: 10px;" gsname='email'>
                    <?php
                    $booking = $this->getSelectedBooking();
                    $user = $this->getApi()->getUserManager()->getUserById($booking->userId);
                    echo "<option value='" . $user->emailAddress ."'>" . $user->fullName . "(" . $user->emailAddress . ") ". "</option>";
                    foreach($booking->rooms as $room) {
                        foreach($room->guests as $guest) {
                            echo "<option value='" . $guest->email . "'>" . $guest->name . "("  . $guest->email . ")</option>";
                        }
                    }
                    ?>
                </select>
                <input type="hidden" gsname="bookingid" value="<?php echo $booking->id;?>">
                <input type="text" gsname='title' placeholder="Title" style="width:100%;margin-bottom: 2px;box-sizing: border-box;">
                <textarea gsname='message' style="width:100%; height: 200px;box-sizing: border-box;"></textarea>
                <span class="pmsbutton" style="float:right;" gstype='submitToInfoBox'>Send message</span>
                <?php if(isset($_POST['event']) && $_POST['event'] == "sendMessage") { ?>
                <h1 style='text-align:right;'>Message has been sent</h1>
                <?php } ?>
            </div>
        </td>
        <td width='50%' valign='top' style='padding: 10px;'>
            <h1>Send sms</h1>
            
            <div gstype="form" method="sendSms">
                <select style="width:100%; margin-bottom: 10px;" gsname='guestid'>
                    <?php
                    $booking = $this->getSelectedBooking();
                    $user = $this->getApi()->getUserManager()->getUserById($booking->userId);
                    foreach($booking->rooms as $room) {
                        foreach($room->guests as $guest) {
                            echo "<option value='" . $guest->guestId . "'>" . $guest->name . " +" . $guest->prefix . " " . $guest->phone . "</option>";
                        }
                    }
                    ?>
                </select>
                <input type="hidden" gsname="bookingid" value="<?php echo $booking->id;?>">
                <textarea gsname='message' style="width:100%; height: 200px;box-sizing: border-box;"></textarea>
                <span class="pmsbutton" style="float:right;" gstype='submitToInfoBox'>Send message</span>
                <?php if(isset($_POST['event']) && $_POST['event'] == "sendMessage") { ?>
                <h1 style='text-align:right;'>Message has been sent</h1>
                <?php } ?>
            </div>
            
        </td>
    </tr>
</table>
