<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$states = \ns_27716a58_0749_4601_a1bc_051a43a16d14\OrderManager::getOrderStatuses();
$states[-10] = "Everything transferred to accounting";
$filter = $this->getOrderStatsFilter();
$periodeTypes = array();
$periodeTypes['dayregistered'] = "Display as day registered";
$periodeTypes['dayslept'] = "Display as day slept";
$periodeTypes['firstdayslept'] = "Display as first day slept";
$periodeTypes['daypaid'] = "Display as day paid";

$pricetypes = array();
$pricetypes['inctaxes'] = "Prices inc taxes";
$pricetypes['extaxes'] = "Prices ex taxes";

?>

<style>
    .PmsManagement .booking_options .roomfilter { display:none; }
</style>
<hr>
<div class='statsorderfilter'>
    <select gsname='paymentmethod'>
        <option value="">All payment methods</option>
        <? 
        $paymentMethods = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
        foreach ($paymentMethods as $key => $method) {
            $selected = $filter->paymentMethod == $method->id ? "SELECTED" : "";
            ?>
            <option value="<? echo $method->id; ?>" <? echo $selected; ?>><? echo $method->appName; ?></option>
            <?php
         }
        ?>
    </select>
    <select gsname='paymentstatus'>
        <option value="">All statuses</option>
        <?
        $paymentMethods = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
        foreach ($states as $id => $status) {
            $selected = $filter->paymentStatus == $id ? "SELECTED" : "";
            ?>
            <option value="<? echo $id; ?>" <?php echo $selected; ?>><? echo $status; ?></option>
            <?php
         }
        ?>
    </select>
    <select gsname='priceType'>
        <?php
        foreach($pricetypes as $id => $type) {
            $selected = $filter->priceType == $id ? "SELECTED" : "";
            echo "<option value='$id' $selected>$type</option>";
        }
        ?>
    </select>
    <select gsname='viewtype'>
        <?php
        foreach($periodeTypes as $type => $name) {
            $selected = $filter->displayType == $type ? "SELECTED" : "";
            echo "<option value='$type' $selected>$name</option>";
        }
        ?>
    </select>

    <input type='button' value='Load data' style='float:right;' class='loadorderstatistics'>
</div>
<div class='orderstatsres'>
    <script>
        $('.loadorderstatistics').click();
    </script>
</div>
