<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$states = \ns_27716a58_0749_4601_a1bc_051a43a16d14\OrderManager::getOrderStatuses();
$states[-9] = "Credit notes";
$states[-10] = "Everything transferred to accounting";

$filter = $this->getOrderStatsFilter();
$periodeTypes = array();
$periodeTypes['dayregistered'] = "Display as day registered";
$periodeTypes['dayslept'] = "Display as day slept";
$periodeTypes['firstdayslept'] = "Display as first day slept";
$periodeTypes['daypaid'] = "Display as day paid";

$pricetypes = array();
$pricetypes['inctaxes'] = "Prices inc taxes";
$pricetypes['extaxes'] = "Prices ex taxes";
$checkedVirtual = $filter->includeVirtual ? "CHECKED" : "";
?>

<style>
    .PmsManagement .booking_options .roomfilter { display:none; }
</style>
<hr>
<div class='statsorderfilter'>
    <select gsname='paymentmethod'>
        <option value="">All payment methods</option>
        <? 
        $paymentMethods = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
        foreach ($paymentMethods as $key => $method) {
            $selected = $filter->paymentMethod == $method->id ? "SELECTED" : "";
            ?>
            <option value="<? echo $method->id; ?>" <? echo $selected; ?>><? echo $method->appName; ?></option>
            <?php
         }
        ?>
    </select>
    <select gsname='paymentstatus'>
        <option value="0">All statuses</option>
        <?
        foreach ($states as $id => $status) {
            ?>
            <option value="<? echo $id; ?>" <?php echo $selected; ?>><? echo $status; ?></option>
            <?php
         }
        ?>
    </select>
    <input type='button' value='Add payment method' class='addPaymentMethod'>
    
    <input type='button' value='Load data' style='float:right;' class='loadorderstatistics'>
    <select gsname='priceType' style='float:right;'>
        <?php
        foreach($pricetypes as $id => $type) {
            $selected = $filter->priceType == $id ? "SELECTED" : "";
            echo "<option value='$id' $selected>$type</option>";
        }
        ?>
    </select>
    <select gsname='viewtype' style='float:right;'>
        <?php
        foreach($periodeTypes as $type => $name) {
            $selected = $filter->displayType == $type ? "SELECTED" : "";
            echo "<option value='$type' $selected>$name</option>";
        }
        ?>
    </select>
    <div>
    <label>
        <input type="checkbox" gsname='includevirtual' <?php echo $checkedVirtual; ?>> Include virtual orders
        <input type="number" gsname='shift' style='width: 40px;' value='<?php echo $filter->shiftHours; ?>'> Shift with hours
    </label>
    </div>
</div>

<div class='orderstatsres'>
    <script>
        $('.loadorderstatistics').click();
    </script>
    <center style='font-size: 50px;'>
        <i class='fa fa-spin fa-spinner'></i>
    </center>
</div>
