<?php
/* @var $this \ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();
$this->createOrderPreview($booking, $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName()));
$cart = $this->getApi()->getCartManager()->getCart();

$toprint = array();
foreach($cart->items as $item) {
    $toprint[] = $item->product->externalReferenceId;
}

echo "<div style='margin-top: 30px; border-bottom: solid 1px; padding-bottom: 10px;'><b>Step 1/2 - What to add to the order</b>";
$products = $this->getApi()->getProductManager()->getAllProductsLight();
?>

    <span style="clear:both; float:right;" gstype='form' method='addProductToCart'>
        <input type='hidden' gsname='bookingid' value='<?php echo $booking->id; ?>'>
        <span style='text-align:left;'>
            <select gsname='productid' id="selectproducttoadd">
                <?php
                foreach($products as $product) {
                    echo "<option value='".$product->id."'>" . $product->name . "</option>";
                }
                ?>
            </select>
        </span>
        <input type='button' value='Add product' class='addproducttocart'>
    </span>
<?php
echo "</div>";
echo "<br>";
echo "<span class='roomselectionbtn selectall'>All rooms</span>";
foreach($booking->rooms as $room) {
    if(!in_array($room->pmsBookingRoomId, $toprint)) {
        continue;
    }
    echo "<span class='roomselectionbtn' roomid='".$room->pmsBookingRoomId."'>";
    if($room->bookingItemId) {
        $item = $this->getApi()->getBookingEngine()->getBookingItem($this->getSelectedName(), $room->bookingItemId);
        echo $item->bookingItemName . " - ";
    }
    if(isset($room->guests[0]) && $room->guests[0]->name) {
        echo $room->guests[0]->name;
    } else {
        echo "Unnamed room";
    }
    echo "</span>";
}
echo "<br>";


echo "<div class='ordercreationpreview'>";
$this->loadCartItems();
echo "</div>";
echo "<div style='border-bottom: solid 1px;margin-top: 30px; padding-bottom: 10px;'><b>Step 2/2 - Customer details</b></div>";
$this->includeFile("newordercreationpanelinpreview");
?>

<style>
    .roomselectionbtn { border: solid 1px #bbb; font-size: 11px; margin: 3px; padding: 3px; display:inline-block; border-radius: 3px; cursor:pointer; }
    .roomselectionbtn.selectedButton { background-color: green; color:#fff; }
</style>

<script>
    $('.roomselectionbtn').on('click', function(e) {
        if($(this).hasClass('selectedButton')) {
            $(this).removeClass('selectedButton');
        } else {
            $(this).addClass('selectedButton');
        }
        
        if($(this).hasClass('selectall')) {
            var curbtn = $(this);
            $('.roomselectionbtn').each(function() {
                if(curbtn.hasClass('selectedButton')) {
                    $(this).addClass('selectedButton');
                } else {
                    $(this).removeClass('selectedButton');
                }
            });
        }
        
        $('.roomselectionbtn').each(function() {
            var roomId = $(this).attr('roomid');
            if($(this).hasClass('selectedButton')) {
                $("[selectionroomrow='" + roomId + "']").find('.itemselection').attr('checked','checked');
                $("[selectionroomrow='" + roomId + "']").show();
            } else {
                $("[selectionroomrow='" + roomId + "']").find('.itemselection').attr('checked',null);
                $("[selectionroomrow='" + roomId + "']").hide();
            }
        });
        app.PmsManagement.calculcateCartCost(e);
    });
    $(document).on('keyup', '.PmsManagement .cartprice', app.PmsManagement.calculcateCartCost);
    $(document).on('keyup', '.PmsManagement .cartcount', app.PmsManagement.calculcateCartCost);
    $(document).on('click', '.PmsManagement .itemselection', app.PmsManagement.calculcateCartCost);
    $(document).on('keyup', '.PmsManagement .itemname', app.PmsManagement.calculcateCartCost);
</script>