<? 
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();

/*
 * public static int CREATED = 1;
    public static int WAITING_FOR_PAYMENT = 2;
    public static int PAYMENT_FAILED = 3;
    public static int COMPLETED = 4;
    public static int CANCELED = 5;
    public static int SENT = 6;
    public static int PAYMENT_COMPLETED = 7;
    public static int COLLECTION_FAILED = 8;
    public static int NEEDCOLLECTING = 9;
 */

$paymentTypes = array();
$paymentTypes[1] = "CREATED";
$paymentTypes[2] = "WAITING FOR PAYMENT";
$paymentTypes[3] = "FAILED";
$paymentTypes[4] = "COMPLETED";
$paymentTypes[5] = "CANCELED";
$paymentTypes[6] = "SENT";
$paymentTypes[7] = "PAYMENT COMPLETED";
$paymentTypes[8] = "COLLECTION_FAILED";
$paymentTypes[9] = "NEEDCOLLECTING";
$paymentTypes[10] = "SENTTOINVOICE";

$pricetypes = array();
$pricetypes[1] = "Daily";
$pricetypes[2] = "Monthly";
$pricetypes[3] = "Weekly";
$pricetypes[4] = "Per minute";
$pricetypes[5] = "Per hour";
$pricetypes[6] = "Per seconds";
$pricetypes[7] = "Progressive";
$pricetypes[8] = "Interval";

$instances = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
$instances2 = array();
if($instances) {
    foreach($instances as $instance) {
        $instances2[$instance->id] = $instance;
    }
    $instances = $instances2;
}

$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
$items = $this->indexList($items);
?>

<div class='orderinformation'>
    <h2>Orders</h2>
</div>

<span class='roomattribute'>
    <span class='roomprefix'>
        <i class='fa fa-edit'></i> Price type
    </span>
    <span class='roompostfix'>
        <span class='viewmode'>
            <? echo $pricetypes[$booking->priceType]; ?>
        </span>
        <span class='editmode' gstype='form' method='changePriceType'>
            <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>
            <?php
            echo "<select gsname='pricetype'>";
            foreach($pricetypes as $idx => $value) {
                echo "<option value='$idx'>$value</option>";
            }
            echo "</select>";
            ?>
            <span class='pmsbutton tiny' gstype='submitToInfoBox'>Change</span>
        </span>
    </span>
</span>
<div style='clear:both;'></div>


<?php
if($booking->orderIds) {
    foreach($booking->orderIds as $orderId) {
        $order = $this->getApi()->getOrderManager()->getOrder($orderId);
        $result[$order->incrementOrderId] = $order;
    }
    ksort($result);
    echo "<table cellspacing='0' cellpadding='0'>";
    echo "<tr>";
    echo "<th>Orderid</th>";
    echo "<th>Order date</th>";
    echo "<th>Price</th>";
    echo "<th>Payment status</th>";
    echo "<th>Payment type</th>";
    echo "<th>Transferred</th>";
    echo "</tr>";
    foreach($result as $order) {
        $total = $this->getApi()->getOrderManager()->getTotalAmount($order);
        echo "<tr>";
        echo "<td><a class='showorderbutton' orderid='".$order->id."'>" . $order->incrementOrderId . "</a></td>";
        echo "<td>" . date("d.m.Y", strtotime($order->rowCreatedDate))  . "</td>";
        echo "<td>" . round($total) . "</td>";
        echo "<td>" . $paymentTypes[$order->status] . "</td>";
        echo "<td>";
        echo $this->translatePaymenttype($order->payment->paymentType, $instances);
        if($order->status <= 5) {
            echo " - <a href='/?page=cart&payorder=" . $order->id."'>pay</a> - <span style='cursor:pointer; color:blue' class='sendpaymentlink' orderid='".$order->id."' bookingid='".$booking->id."'>Send payment link</span>";
        }
        echo "</td>";
        echo "<td align='center'>";

        if(isset($order->transferedToAccountingSystem) && $order->transferedToAccountingSystem) {
            echo "<i class='fa fa-check'>";
        } else {
            echo "<i class='fa fa-close'>";
        }
        echo "</td>";
        echo "</tr>";
    }
    echo "</table>";
} else {
    echo "<h2>No orders added to this booking yet.</h2>";
    echo "Please create an order below first.";
}

?>
<br>
<h2>Invoice information</h2>
<div gstype="form" method="updateInvoiceNote" style='text-align:right;'>
    <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>
    <textarea gsname='invoicenote' style="width:100%;height: 50px;"><?php echo $booking->invoiceNote; ?></textarea><br>
    <span class='pmsbutton' gstype="submitToInfoBox">Update invoice note</span>
</div>
<div gstype="form" method="createNewOrder">
    <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>

    <?php
    $endDate = time();
    foreach($booking->rooms as $room) {
        if($endDate < strtotime($room->date->end)) {
            $endDate = strtotime($room->date->end);
        }
    }
    if(isset($_POST['data']['endingAt'])) {
        $endDate = strtotime($_POST['data']['endingAt']);
    }
    
    $endingAt = date("d.m.Y", $endDate);
    
    $config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
    $filter = new \core_pmsmanager_NewOrderFilter();
    $filter->onlyEnded = false;
    $filter->prepayment = $config->prepayment;
    $filter->avoidOrderCreation = true;

    $filter->endInvoiceAt = $this->convertToJavaDate($endDate);
    $this->getApi()->getPmsManager()->createOrder($this->getSelectedName(), $booking->id, $filter);
    $cart = $this->getApi()->getCartManager()->getCart();
    if(sizeof($cart->items) > 0) {
        echo "<br><h2>Next order preview (invoice until $endingAt)</h2>";
        $this->includeOrderGenerationPreview();

        echo "<br><label><input type='checkbox' gsname='preview' CHECKED> Update preview only</label><br>";
        echo "<select gsname='itemid'>";
        echo "<option value=''>All rooms</option>";
        foreach($booking->rooms as $room) {
            echo "<option value='".$room->bookingItemId."'>" . $items[$room->bookingItemId]->bookingItemName . "</option>";
        }

        if(!$booking->invoicedTo) {
            $booking->invoicedTo = $booking->rooms[0]->date->start;
        }
        echo "<label style='display:inline-block;'>Invoice to<br><input type='text' gsname='endingAt' value='$endingAt' style='font-size: 18px; width: 100px;padding: 4px;' /></label>";
    } else {
        echo "There is nothing to invoice for this booking.";
    }
    
    ?>
    
    <span class='pmsbutton' gstype="submitToInfoBox">Create new order</span>
</div>

<script>
    $("[gsname='endingAt']").datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
</script>