<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$filter = $this->getOrderStatsFilter();

$products = $this->getApi()->getProductManager()->getAllProducts();
$products = $this->indexList($products);
$result = $this->getApi()->getPmsInvoiceManager()->generateStatistics($this->getSelectedName(), $filter);
$_SESSION['currentOrderStatsResult'] = serialize($result);
$productIds = array();
$priceType = $_POST['data']['priceType'];

$total = 0;
foreach($result->entries as $entry) {
    $prices = $entry->priceInc;
    if($priceType == "extaxes") {
        $prices = $entry->priceEx;
    }
    
    foreach($prices as $id => $val) {
        if(!isset($productIds[$id])) {
            $productIds[$id] = 0;
        }
        $productIds[$id] += $val;
        $total += $val;
    }
}

echo "<table cellspacing='0' cellpadding='0'>";
echo "<tr>";
echo "<th>Day</th>";
foreach($productIds as $id => $null) {
    echo "<th width='100'>" . $products[$id]->name . "</th>";
}
echo "<th></th>";
echo "</tr>";
$index = 0;
foreach($result->entries as $entry) {
    echo "<tr class='compressed'>";
    echo "<td class='loadStatsForDay' index='$index'>" . date("d.m.Y", strtotime($entry->day)) . "</td>";
    $totalRow = 0;
    foreach($productIds as $id => $price) {
         $prices = $entry->priceInc;
        if($priceType == "extaxes") {
            $prices = $entry->priceEx;
        }
        if(!isset($prices->{$id})) {
            echo "<td width='100'>0</td>";
        } else {
            echo "<td width='100'>" . round($prices->{$id}) . "</td>";
            $totalRow+= round($prices->{$id});
        }
    }
    echo "<td>" . $totalRow . "</td>";
    $index++;
    echo "</tr>";
}
echo "<tr>";
echo "<td>".round($total)."</td>";
foreach($productIds as $id => $price) {
    if(isset($price)) {
        echo "<td width='100'>" . round($price) . "</td>";
    } else {
        echo "<td width='100'>0</td>";
    }
}
echo "</tr>";
echo "</table>";
?>    
</pre>
