<?php
/* @var $this \ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$displayBooking = false;
$orders = (array)$this->getCreatedOrders($displayBooking);
$i = 1;
if(sizeof($orders) <= 1) {
    echo "Nothing to preview.<br><br>";
} else {
    echo "<table cellspacing='0' cellpadding='0' width='100%'>";
    echo "<tr>";
    if($displayBooking) {
        echo "<th>";
        echo '<i gs_downloadexcelreport="getOrderInvoiceArray" style="cursor:pointer" class="fa fa-file-excel-o" aria-hidden="true" gs_filename="Orderpreviewexport"></i>';
        echo "Booking</th>";
    }
    echo "<th>Room</th>";
    echo "<th>Start date</th>";
    echo "<th>End date</th>";
    echo "<th>Room</th>";
    echo "<th width='10'>Order price</th>";
    echo "<th width='10'>Room price</th>";
    echo "<th>Count</th>";
    echo "<th>Total</th>";
    echo "</tr>";

    foreach($orders as $res) {
        if($i != sizeof($orders)) {
            echo "<tr>";
            if($displayBooking) {
                echo "<td class='moreinformationaboutbooking' bookingid='".$res['id']."' style='cursor:pointeR;'>" . $res['fullname'] . "<br>";
                echo "<div style='color:#bbb;'>";
                echo "<b>" . $res['start'] . "</b> - <b>" . $res['end'] . "</b>";
                if($res['invoicedto']) {
                    echo "<br> invoiced until: " . $res['invoicedto'];
                }
                echo "</div>";
                echo "</td>";
            }
            echo "<td>" . $res['additionalmetadata'] . "</td>";
            echo "<td>" . $res['itemstart'] . "</td>";
            echo "<td>" . $res['itemend']  . "</td>";
            echo "<td>" . $res['productname'] ."<br><div style='color:#bbb;'>" . $res['metadata'] . "</div></td>";
            echo "<td>" . $res['priceex'] . "<br><div style='color:#bbb;'>" . $res['price'] . "</div></td>";
            echo "<td>" . $res['price'] . "<br>&nbsp;</div></td>";
            echo "<td>" . $res['count'] . "</td>";
            echo "<td>" . ($res['priceex'] * $res['count'])  . "<div style='color:#bbb;'>". ($res['price']  * $res['count']) ."</div></td>";
            echo "</td>";
            echo "</tr>";
        } else {
            echo "<tr>";
            echo "<td></td>";
            echo "<td></td>";
            echo "<td></td>";
            echo "<td></td>";
            echo "<td></td>";
            echo "<td></td>";
            echo "<td></td>";
            echo "<td>" . $res['count'] . "</td>";
            echo "<td>" . $res['priceex'] . "<div style='color:#bbb;'>". $res['price'] ."</div></td>";
            echo "</tr>";
        }
        $i++;
    }
    echo "</table>";
}
?>