<? 
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();
/*
 * public static int CREATED = 1;
    public static int WAITING_FOR_PAYMENT = 2;
    public static int PAYMENT_FAILED = 3;
    public static int COMPLETED = 4;
    public static int CANCELED = 5;
    public static int SENT = 6;
    public static int PAYMENT_COMPLETED = 7;
    public static int COLLECTION_FAILED = 8;
    public static int NEEDCOLLECTING = 9;
 */

$paymentTypes = array();
$paymentTypes[1] = "CREATED";
$paymentTypes[2] = "WAITING FOR PAYMENT";
$paymentTypes[3] = "FAILED";
$paymentTypes[4] = "COMPLETED";
$paymentTypes[5] = "CANCELED";
$paymentTypes[6] = "SENT";
$paymentTypes[7] = "PAYMENT COMPLETED";
$paymentTypes[8] = "COLLECTION_FAILED";
$paymentTypes[9] = "NEEDCOLLECTING";
$paymentTypes[10] = "SENTTOINVOICE";

$pricetypes = array();
$pricetypes[1] = "Daily";
$pricetypes[2] = "Monthly";
$pricetypes[3] = "Weekly";
$pricetypes[4] = "Per minute";
$pricetypes[5] = "Per hour";
$pricetypes[6] = "Per seconds";
$pricetypes[7] = "Progressive";
$pricetypes[8] = "Interval";

$instances = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
$instances2 = array();
if($instances) {
    foreach($instances as $instance) {
        $instances2[$instance->id] = $instance;
    }
    $instances = $instances2;
}

$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
$items = $this->indexList($items);

$user = $this->getApi()->getUserManager()->getUserById($booking->userId);
$invoiceEmail =  $user->emailAddress;
if($user->emailAddressToInvoice) {
    $invoiceEmail = $user->emailAddressToInvoice;
}
$phonePrefix = $user->prefix;
$phoneNumber = $user->cellPhone;
$bookerName = $user->fullName;
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$createdAfter = "";
if($booking->createOrderAfterStay) {
    $createdAfter = "CHECKED";
}

echo "<span class='changepaymenttypeform' gstype='form' method='updateOrder'>";
echo "<input type='hidden' gsname='orderid' class='selectedorderidtochange'>";
echo "<input type='hidden' gsname='bookingid' value='".$booking->id."'>";
foreach($instances as $app) {
    echo "<span class='' gstype='submitToInfoBox' gsvalue='".$this->createPaymentTypeText($app)."'>" . $app->appName . "</span><br>";
}
echo "</span>";

echo "<span class='markpaidform' gstype='form' method='markPaid'>";
echo "<input type='hidden' gsname='orderid' class='selectedorderidtomarkpaid'>";
echo "<input type='hidden' gsname='bookingid' value='".$booking->id."'>";
echo "Payment date<br>";
echo "<input class='paymentdateselection' type='txt' gsname='date' value='".date("d.m.Y H:i", time())."'>";
echo "<input type='button' value='Mark as paid' gstype='submitToInfoBox'>";
echo "</span>";

?>

<div class='orderinformation'>
    <h2>Orders</h2>
</div>
<div onclick='$(".PmsManagement .moreinvoiceoptions").toggle();' style='cursor:pointer;'>More options</div>
<span class="moreinvoiceoptions">
    <div>
        <b>Order for a given periode</b><br>
        <div  gstype="form" method="saveOrderSettingsOnBooking">
            <input type='hidden' value='<?php echo $booking->id; ?>' gsname='bookingid'>
            <input type='text' style='width:30px;' value='<?php echo $booking->dueDays; ?>' gsname='duedays'> number of days for due<br>
            <input type='text' style='width:30px;' value='<?php echo $booking->periodesToCreateOrderOn; ?>' gsname='periodesToCreateOrderOn'> number of periodes to create order on<br>
            <input type='button' style='float:right;' value='Save settings' gstype='submitToInfoBox'><br><br>
        </div>
        <b>Order for a given periode</b><br>
        <div  gstype="form" method="createPeriodeOrder">
            <input type='hidden' value='<?php echo $booking->id; ?>' gsname='bookingid'>
            <input type='txt' style='width:100px;' placeholder='Start date' class='periodeorderstartdate' gsname='start'>
            <input type='txt' style='width:100px;' placeholder='End date'  class='periodeorderenddate' gsname='end'>
            <input type='txt' style='width:50px;' placeholder='amount' gsname='amount'>
            <input type='button' value='Create order' gstype='submitToInfoBox'>
        </div>
    </div>
  </span>
<div style='clear:both;'></div>


<?php
if($booking->orderIds) {
    $result = $this->getOrdersForSelectedBooking();
    
    $totalAmount = 0;
    $totalAmountEx = 0;
    
    echo "<table cellspacing='0' cellpadding='0' width='100%'>";
    echo "<tr>";
    echo "<th>Order</th>";
    echo "<th>Guest</th>";
    echo "<th>Price</th>";
    echo "<th width='80'>Status</th>";
    echo "<th>Payment type</th>";
    echo "<th title='Closed'>Closed</th>";
    echo "<th></th>";
    echo "</tr>";
    foreach($result as $order) {
        if(!$order) {
            continue;
        }
        $total = $this->getApi()->getOrderManager()->getTotalAmount($order);
        $totalEx = $this->getApi()->getOrderManager()->getTotalAmountExTaxes($order);
        $createByManager = "";
        if(isset($order->createByManager)) {
            $createByManager = $order->createByManager;
        }
        $totalAmount += $total;
        $totalAmountEx += $totalEx;
        
        $roomIds = array();
        $items = (array)@$order->cart->items;
        foreach($items as $item) {
            if(isset($item->product->externalReferenceId)) {
                $roomIds[] = $item->product->externalReferenceId;
            }
        }
        
        $guests = array();
        $guestSelectedOffset = 0;
        foreach($booking->rooms as $room) {
            if(in_array($room->pmsBookingRoomId, $roomIds)) {
                $guests = array_merge($guests, $room->guests);
                if(isset($order->attachedToRoom) && $order->attachedToRoom && $room->pmsBookingRoomId == $order->attachedToRoom) {
                    $guestSelectedOffset = sizeof($guests);
                }

            }
        }
        $user = $this->getApi()->getUserManager()->getUserById($order->userId);
        $addr = $user->fullName . "<br>";
        $addr .= $user->address->address . "<br>";
        $addr .= $user->address->postCode . " " . $user->address->city . "<br>";
        $addr .= $user->emailAddressToInvoice ? $user->emailAddressToInvoice : $user->emailAddress . "<br>";
        if(isset($order->recieptEmail)) {
            $addr .= "Order receipt email: " . $order->recieptEmail;
        }
        
        
        echo "<tr orderid='".$order->id."'>";
        echo "<td width='200'> <a class='showorderbutton' orderid='".$order->id."'>" . $order->incrementOrderId . "</a> - ".date("d.m.Y", strtotime($order->rowCreatedDate));
        echo "<br>";
        echo "<i style='float:right; color:#bbb; margin-right: 5px; cursor:pointer;' class='fa fa-info-circle loadorderinformation' orderid='".$order->id."'></i>";
        echo "<span style='color:#bbb; width: 160px;display: block;overflow: hidden;text-overflow: ellipsis;white-space: nowrap;' title='$addr' orderid='".$order->id."'>";
        if(!isset($order->closed) || !$order->closed) {
            echo "<i class='fa fa-edit edituseronorderviewbutton' orderid='".$order->id."'></i> <span class='edituseronorderview edituserview'></span> ";
        }
        echo "<span class='changeRecieptEmail'>" . $user->fullName . "(" . $user->customerId . ")</span></span></td>";
        echo "<td width='120'>";
        $names = "";
        $name = "";
        foreach($guests as $guest) {
            if(!$name) {
                $name = $guest->name;
            }
            $names .= $guest->name . "<br>";
        }
        
        echo "<span style='width: 100px;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;display:inline-block;' title='$names'>$name</span>";
        
        
        echo "</td>";
        echo "<td>" . round($totalEx) . "<br><span style='color:#bbb'>" . round($total) . "</span></td>";
        echo "<td>";
        $show = true;
        if(stristr($order->payment->paymentType, "dibs") && $total > 0) {
            $show = false;
        }
        if($order->status == 7) {
            echo "<i class='fa fa-check'></i> Paid<br><span style='color:#bbb;' title='Payment date'>".date("d.m.Y", strtotime($order->paymentDate))."</span><br>";
        } else {
            if($show) {
                echo "<input type='button' value='Mark paid' class='markpaidbutton'>";
            } else {
                if($total < 0) {
                    echo "Credit note";
                } else {
                    echo "<i class='fa fa-times'></i> Not paid";
                }
            }
        }
        echo "</td>";
        echo "<td valign='top'>";
        
        echo "<span class='sendinvoicebox dosendbox' gstype='form' method='sendInvoice'>";
        
        echo "<div style='padding-bottom: 10px;'>";
        echo "<i class='fa fa-close closesendreciept' style='float:right;cursor:pointer;'></i>";
        echo "Send receipt";
        echo "</div>";
        echo "<input type='hidden' value='".$booking->id."' gsname='bookingid'>";
        echo "<input type='hidden' value='".$order->id."' gsname='orderid'>";
        echo "<div>";
        
        echo "<select style='width:100%; margin-bottom: 5px;' class='sendlinktouser'>";
        echo "<option value='$phonePrefix:$phoneNumber:$invoiceEmail'>Booker : $bookerName</option>";
        $k = 1;
        $selectedPhone = $phoneNumber;
        $selectedEmail = $invoiceEmail;
        $selectedPrefix = $phonePrefix;
        foreach($guests as $guest) {
            /* @var $guest core_pmsmanager_PmsGuests */
            if(!$guest->name) {
                continue;
            }
            $pref = $guest->prefix;
            $phone = $guest->phone;
            $email = $guest->email;
            $selected = "";
            if($k == $guestSelectedOffset) {
                $selectedPhone = $phone;
                $selectedEmail = $email;
                $selectedPrefix = $pref;
                $selected = "SELECTED";
            }

            echo "<option value='$pref:$phone:$email' $selected>Guest : " . $guest->name . "</option>";
            $k++;
        }
        
        echo "</select><br>";
        echo "<input type='txt' value='".$selectedEmail."' placeholder='Email' gsname='bookerEmail' style='width:100%; margin-bottom: 5px;box-sizing:border-box;'><br>";
        echo "<input type='button' gstype='submitToInfoBox' gsvalue='sendtobooker' value='Send' style='width:100%;'>";
        echo "</div>";
                
        
        echo "</span>";
        
        if(stristr($order->payment->paymentType, "invoice")) {
            $change = "";
            if(!isset($order->closed) || !$order->closed) {
                $change = "changeduedates";
            }
            $days = "default";
            if(isset($order->dueDays)) {
                $days = $order->dueDays;
            }
            $days = "<span style='color:#bbb;' title='Due days' days='$days' class='$change' orderid='".$order->id."'>" . $days . "</span>";
            echo "<span style='float:right;'>$days</span>";
        }

        
        echo "<span class='sendpaymentlinkbox dosendbox' gstype='form' method='sendPaymentLink'>";
        echo "<div style='padding-bottom: 10px;'>";
        echo "<i class='fa fa-close closesendpaymentlink' style='float:right;cursor:pointer;'></i>";
        echo "Send payment link";
        echo "</div>";
        echo "<input type='hidden' value='".$booking->id."' gsname='bookingid'>";
        echo "<input type='hidden' value='".$order->id."' gsname='orderid'>";
        echo "<div>";
        
        echo "<select style='width:100%; margin-bottom: 5px;' class='sendlinktouser'>";
        echo "<option value='$phonePrefix:$phoneNumber:$invoiceEmail'>Booker : $bookerName</option>";
        $selectedPhone = $phoneNumber;
        $selectedEmail = $invoiceEmail;
        $selectedPrefix = $phonePrefix;
        
        
        $k = 1;
        foreach($guests as $guest) {
            /* @var $guest core_pmsmanager_PmsGuests */
            if(!$guest->name) {
                continue;
            }
            $pref = $guest->prefix;
            $phone = $guest->phone;
            $email = $guest->email;
            $selected = "";
            if($k == $guestSelectedOffset) {
                $selectedPhone = $phone;
                $selectedEmail = $email;
                $selectedPrefix = $pref;
                $selected = "SELECTED";
            }

            echo "<option value='$pref:$phone:$email' $selected>Guest : " . $guest->name . "</option>";
            $k++;
        }
        $msg = $this->getApi()->getPmsManager()->getMessage($this->getSelectedName(), $booking->id, "booking_sendpaymentlink");
        
        echo "</select><br>";
        echo "<input type='txt' value='".$selectedEmail."' placeholder='Email' gsname='bookerEmail' style='width:100%; margin-bottom: 5px;box-sizing:border-box;'><br>";
        echo "<input type='txt' value='+".$selectedPrefix."' placeholder='bookerPrefix' gsname='bookerPrefix' style='width: 30px;'>";
        echo "<input type='txt' value='".$selectedPhone."' placeholder='bookerPhone' gsname='bookerPhone' style='width: 80px;'><input type='button' gstype='submitToInfoBox' gsvalue='sendtobooker' value='Send link'>";
        echo "<br><br><span style='font-size:12px;'>Message</span><br>";
        echo "<textarea style='font-size:10px; width:100%; height: 100px;' gsname='smsMessage'>$msg</textarea>";
        
        echo "</div>";
        
        echo "</span>";
        
        
        if(@!$order->closed) {
            echo "<div>";
            $foundPaymentType = false;
            foreach($instances as $id => $app) {
                if($this->isPaymentType($order->payment->paymentType, $app)) {
                    
                    $appInstance = $this->getFactory()->getApplicationPool()->createInstace($app);

                    $name = $appInstance->getName();
                    if($name == "InvoicePayment") {
                        $name = "Invoice";
                    }
                    echo "<i class='fa fa-edit changepaymenttypebutton' title='Change payment type'></i> " . $name;
                    $foundPaymentType = true;
                }
            }
            if(!$foundPaymentType) {
                echo "<i class='fa fa-edit changepaymenttypebutton' title='Change payment type'></i> ";
            }
            echo "</div>";
            if($order->status <= 5) {
                echo "<a href='/scripts/downloadInvoice.php?orderId=".$order->id."&incrementalOrderId=".$order->incrementOrderId."' target='_fdasf'><span style='cursor:pointer; color:blue' orderid='".$order->id."' bookingid='".$booking->id."'>download</span></a>";
                if($total > 0 && ((!stristr($order->payment->paymentType, "dibsautocollect") && stristr($order->payment->paymentType, "dibs")) || stristr($order->payment->paymentType, "\\epay") || stristr($order->payment->paymentType, "\\vipps"))) {
                    echo " - <a href='/?page=cart&payorder=" . $order->id."'>pay</a> - <span style='cursor:pointer; color:blue' class='sendpaymentlink' orderid='".$order->id."' bookingid='".$booking->id."'>Send payment link</span>";
                }
            }
            if(stristr($order->payment->paymentType, "verifone")) {
                echo " - <span style='color:blue; cursor:pointer;' class='doverifonepayment' orderid='".$order->id."'>pay</span>";
                echo "<span class='dopayment' style='display:none;'><i class='fa fa-spin fa-spinner'></i> Waiting for payment, cancel payment.</span>";
                echo "<div class='verifonefeedbackdata' style='font-size:12px;font-style: italic;padding-top: 10px; padding-bottom: 10px; display:none;'></div>";
            }
            if(stristr($order->payment->paymentType, "invoice") || stristr($order->payment->paymentType, "sendregning")) {
                echo " - <span style='cursor:pointer; color:blue' class='sendinvoice' orderid='".$order->id."' bookingid='".$booking->id."'>Send invoice</span>";
            }
            if(stristr($order->payment->paymentType, "dibsautocollect")) {
                if($booking->nonrefundable) {
                    $chargeText = date("d.m.Y", time());
                } else {
                    $chargeText = date("d.m.Y", $this->getChargeDate($order));
                }
                echo "<div>Will try to charge card at : " . $chargeText . "</div>";
            }
            
        } else {
            echo $this->translatePaymenttype($order->payment->paymentType, $instances);
            echo "<br>";
            if($order->status <= 5 && $total > 0) {
                if(stristr($order->payment->paymentType, "dibs") || stristr($order->payment->paymentType, "\\epay")) {
                    echo "<a href='/?page=cart&payorder=" . $order->id."'>pay</a> - <span style='cursor:pointer; color:blue' class='sendpaymentlink' orderid='".$order->id."' bookingid='".$booking->id."'>Send payment link</span>";
                }
                if(stristr($order->payment->paymentType, "invoice") || stristr($order->payment->paymentType, "sendregning")) {
                    echo "<span style='cursor:pointer; color:blue' class='sendinvoice' orderid='".$order->id."' bookingid='".$booking->id."'>Send invoice</span>";
                    echo " - <a href='/scripts/downloadInvoice.php?orderId=".$order->id."&incrementalOrderId=".$order->incrementOrderId."' target='_fdasf'><span style='cursor:pointer; color:blue' orderid='".$order->id."' bookingid='".$booking->id."'>download</span></a>";
                }
            } else {
                echo "<a href='/scripts/downloadInvoice.php?orderId=".$order->id."&incrementalOrderId=".$order->incrementOrderId."' target='_fdasf'><span style='cursor:pointer; color:blue' orderid='".$order->id."' bookingid='".$booking->id."'>download</span></a> - ";
                if(stristr($order->payment->paymentType, "invoice") || stristr($order->payment->paymentType, "sendregning")) {
                    echo "<span style='cursor:pointer; color:blue' class='sendinvoice' orderid='".$order->id."' bookingid='".$booking->id."'>Send invoice</span>";
                } else {
                    echo "<span style='cursor:pointer; color:blue' class='sendreciept' orderid='".$order->id."' bookingid='".$booking->id."'>Send receipt</span>";
                }
            }
        }
        $title = "";
        $sentDate = null;
        if(isset($order->shipmentLog) && sizeof($order->shipmentLog) > 0) {
            foreach($order->shipmentLog as $logEntry) {
                if(isset($logEntry->date)) {
                    $title .=  date("d.m.Y H:i", strtotime($logEntry->date)) . ", " . $logEntry->type . ": " . $logEntry->address . "<br>";
                    $sentDate = $logEntry->date;
                }
            }
        }
        if($title) { echo "<br><div title='$title'><i class='fa fa-share'></i>" . date("d.m.Y H:i", strtotime($sentDate)) . "</div>"; }
        echo "</td>";
        echo "<td align='center'>";

        if(@$order->closed) {
            echo "<i class='fa fa-check'>";
        } else {
            echo "<i class='fa fa-close'>";
        }
        echo "</td>";
        echo "<td style='position:relative; text-align:center;'>";
        echo "<i class='fa fa-edit' onclick='$(this).closest(\"td\").find(\".otherOrderOptions\").toggle()'></i>";
        if(!@$order->closed) {
            echo " <i class='fa fa-trash-o removeOrderFromBooking' style='cursor:pointer;' title='Remove this order' orderid='".$order->id."'></i>"; 
        }

        echo "<span class='otherOrderOptions' style='display:none; position:absolute;'>";
        echo "<table cellspacing='0' cellpadding='0'>";
        echo "<tr><th>Option</th><th>Action</th></tr>";
        echo "<tr>";
        echo "<td>";
        echo "Credit order, sometimes its nessesary to credit an order. This is when the order is incorrect and you need to create a new one.";
        if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject() != null && ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->showHiddenFields) {
            echo "<div><i class='fa fa-magic' title='Force detach order from from booking.' bookingid='$booking->id' gsclick='detachOrderFromBooking' orderid='".$order->id."'></i> <span class='edituseronorderview edituserview'></span></div>";
        }
        echo "</td>";
        echo "<td>";
            if(@$order->closed && !@$order->isCreditNote) {
                echo "<span class='doCreditOrder'>Credit order</span>";
            } else {
                echo "This order can not be credited.";
            }
        echo "</td>";
        echo "</tr>";
        echo "</table>";
        
        echo "</span>";
        
        echo "</td>";
        echo "</tr>";
        
        if(!@$order->closed) {
            $this->orderToDisplay = $order;
            $this->includefile("detailedorderinformation");
        }
        
    }
    
    echo "<tr>";
    echo "<td></td>";
    echo "<td></td>";
    echo "<td>".round($totalAmountEx)."<br><span style='color:#bbb'>".round($totalAmount)."</span></td>";
    echo "<td></td>";
    echo "<td></td>";
    echo "<td></td>";
    if(!$config->prepayment) {
        echo "<td></td>";
    }
    echo "</tr>";
    
    echo "</table>";
} else {
    echo "<h2>No orders added to this booking yet.</h2>";
    echo "Please create an order below first.";
}

?>
<script>
    $(".paymentdateselection").datetimepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
</script>