<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$states = \ns_27716a58_0749_4601_a1bc_051a43a16d14\OrderManager::getOrderStatuses();
$states[-9] = "Credit notes";
$states[-10] = "Everything transferred to accounting";

$filter = $this->getOrderStatsFilter();
$periodeTypes = array();
$periodeTypes['dayregistered'] = "Display as day registered";
$periodeTypes['dayslept'] = "Display as day slept";
$periodeTypes['firstdayslept'] = "Display as first day slept";
$periodeTypes['daypaid'] = "Display as day paid";

$pricetypes = array();
$pricetypes['inctaxes'] = "Prices inc taxes";
$pricetypes['extaxes'] = "Prices ex taxes";
$checkedVirtual = $filter->includeVirtual ? "CHECKED" : "";

$filters = $this->getApi()->getPmsInvoiceManager()->getAllStatisticsFilters($this->getSelectedName());
?>

<style>
    .PmsManagement .booking_options .roomfilter { display:none; }
</style>

<div class='statsorderfilter'>

    <span class="pmsbutton" gstype='clicksubmit' method='setneworderstatsfilter' gsname='filtertype' gsvalue=''>Default filter</span>
    <?php
    foreach((array)$filters as $filter) {
        if(!$filter->name) {
            continue;
        }
        echo "<span class='pmsbutton' gstype='clicksubmit' method='setneworderstatsfilter' gsname='filtertype' gsvalue='".$filter->name."'>" . $filter->name . "</span> ";
    }
    ?>

<span class="pmsbutton createnewfilter">Create a filter</span>


<div class='orderstatsres'>
        <script>
            app.PmsManagement.loadorderstatistics();
        </script>
        <center style='font-size: 50px;'>
            <i class='fa fa-spin fa-spinner'></i>
        </center>
</div>
