<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();
?>
<div gstype="form" method="createNewOrder">
    <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>

    <?php
    $endDate = time();
    $startDate = null;
    foreach($booking->rooms as $room) {
        if($endDate < strtotime($room->date->end)) {
            $endDate = strtotime($room->date->end)+86400;
        }
        if($startDate < strtotime($room->date->start)) {
            $startDate = strtotime($room->date->start)+86400;
        }
    }
    if(isset($_POST['data']['endingAt'])) {
        $endDate = strtotime($_POST['data']['endingAt']);
    }
    $invoiceRoomId = "";
    if(isset($_POST['data']['roomId'])) {
        $invoiceRoomId = $_POST['data']['roomId'];
    }

    $endingAt = date("d.m.Y", $endDate);
    
    $cart = $this->getApi()->getCartManager()->getCart();

    if($booking->ignoreCheckChangesInBooking) {
        echo "<b style='color:red; font-size: 20px;'>This booking is old and does not support autopricing since not enough data where connected to it when registering.</b><br><br>";
    }
    
    $this->includeOrderCreationPanel();

?>
<script>
    $("[gsname='endingAt']").datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    
    $(".periodeorderstartdate").datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    $(".periodeorderenddate").datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    
</script>