<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$cart = $this->getApi()->getCartManager()->getCart();
$booking = $this->getSelectedBooking();
$lastSelectedRoom = null;
foreach($cart->items as $item) {
    $selectedRoom = null;
    foreach($booking->rooms as $room) {
        if($room->pmsBookingRoomId == $item->product->externalReferenceId) {
            $selectedRoom = $room;
            break;
        }
    }
    if($lastSelectedRoom != $selectedRoom) {
        echo "<div selectionroomrow='".$selectedRoom->pmsBookingRoomId."'>";
        if(isset($selectedRoom) && $selectedRoom->bookingItemId) {
            $bookingItem = $this->getApi()->getBookingEngine()->getBookingItem($this->getSelectedName(), $selectedRoom->bookingItemId);
            echo $bookingItem->bookingItemName . " - ";
        }
        if(isset($selectedRoom->guests[0])) {
            echo $selectedRoom->guests[0]->name . "<br>";
        }
        $lastSelectedRoom = $selectedRoom;
        echo "</div>";
    }
    $lastSelectedId = "";
    if(isset($lastSelectedRoom->pmsBookingRoomId)) {
        $lastSelectedId = $lastSelectedRoom->pmsBookingRoomId;
    }
    $this->printSingleCartItem($item, $lastSelectedId);
}
?>