<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();
$pricetypes = array();
$pricetypes[1] = "Daily";
$pricetypes[2] = "Monthly";
$pricetypes[3] = "Weekly";
$pricetypes[4] = "Per minute";
$pricetypes[5] = "Per hour";
$pricetypes[6] = "Per seconds";
$pricetypes[7] = "Progressive";
$pricetypes[8] = "Interval pricing";

$user = $this->getApi()->getUserManager()->getUserById($booking->userId);

$isActiveFileUpload = $this->getApi()->getStoreApplicationPool()->isActivated("ed0c5af9-32a9-426a-9908-c7ac67e7b2f4");
?>
<input type='txt' value='<?php echo $user->id; ?>' id='selecteduseridoverride' style='display:none;'>
<br><br>
<div gstype='form' method='saveOtherBookingOptions'>
    <input type='hidden' gsname='bookingid' value='<?php echo $booking->id; ?>'>
    Price type for this booking :
    <select style='float:right;' gsname='priceType'>
        <?php 
        foreach($pricetypes as $id => $type) {
            $selected = $booking->priceType == $id ? "SELECTED" : "";
            echo "<option value='$id' $selected>$type</option>";
        }
        ?>
    </select>
    <div style="clear:both"></div>
<?php

if($isActiveFileUpload) {
    ?>
    Files connected to the user, <span class='gss_user_save_file' style='cursor:pointer; color:blue;' >upload new file</span><br>
    <?php
    foreach($user->files as $file) {
        echo "<span style='cursor:pointer; color:blue;' onclick='window.open(\"/scripts/downloadUserFile.php?userId=".$user->id. "&id=".$file->fileId."\", \"_blank\")'>". $file->fileName . "</span><br>";
    }
    ?>
    <div style="clear:both"></div>
<?php } ?>
    
    <div style='text-align:right; margin-top: 30px;'>
        <input type='button' gstype='submitToInfoBox' value='Save other options'>
    </div>
</div>
