<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();
$types = $this->getTypes();
$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
$items2 = array();
foreach ($items as $item) {
    $items2[$item->id] = $item;
}

$items = $items2;
$pricetypes = array();
$pricetypes[1] = "Daily";
$pricetypes[2] = "Monthly";
$pricetypes[3] = "Weekly";
$pricetypes[4] = "Per minute";
$pricetypes[5] = "Per hour";
$pricetypes[6] = "Per seconds";
?>
<div class='bookedrooms'>
    <h2>Rooms booked</h2>
    <div style='padding-left: 10px;'>
        <?php
        foreach ($booking->rooms as $room) {
            $date = $room->date;
            ?>
            <span class='roomattribute'>
                <span class='roomprefix'>
                    <i class='fa fa-edit'></i> Room type
                </span>
                <span class='roompostfix'>
                    <span class="viewmode">
                        <? echo $types[$room->bookingItemTypeId]->name; ?>
                    </span>
                    <span class="editmode" gstype='form' method="setItemType">
                        <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>
                        <input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
                        <select gsname='itemtype'>
                            <?php foreach ($types as $type) { ?>
                            <?php $selected = ""; if($type->id == $room->bookingItemTypeId) { $selected = "SELECTED"; } ?>
                                <option value='<? echo $type->id; ?>' <? echo $selected; ?>><? echo $type->name; ?></option>
                            <? }  ?>
                        </select>
                        <span class='pmsbutton tiny' gstype='submitToInfoBox'>Change</span>
                    </span>
                </span>
            </span>
            <span class='roomattribute'>
                <div style='clear:both;'></div>
                <span class='roomprefix'>
                    <i class='fa fa-edit'></i> Dates
                </span> 
                <span class='roompostfix'>
                    <?php echo date("d.m.Y H:i", strtotime($date->start)); ?>
                    <?php if ($date->end) { ?>
                        -> 
                        <?php echo date("d.m.Y H:i", strtotime($date->end)); ?>
                    <? } ?>
                </span>
            </span>
            <div style='clear:both;'></div>
            <span class='roomattribute'>
                <span class='roomprefix'>
                    <i class='fa fa-edit'></i> <?php echo $room->numberOfGuests; ?> guests
                </span>
                <span class='roompostfix'>
                    <?php
                    foreach ($room->guests as $guest) {
                        echo $guest->name . " - " . $guest->email . " - +" . $guest->prefix . $guest->phone;
                    }
                }
                ?>
            </span>
        </span>
        <div style='clear:both;'></div>
        <span class='roomattribute'>
            <span class='roomprefix'>
                <i class='fa fa-edit'></i> Assigned room
            </span>
            <span class='roompostfix'>
                <?
                if (!$room->booking->bookingItemId) {
                    echo "Not assigned yet";
                } else {
                    $items[$room->booking->bookingItemId]->bookingItemName;
                }
                ?>
            </span>
        </span>
        <div style='clear:both;'></div>
        <span class='roomattribute'>
            <span class='roomprefix'>
                <i class='fa fa-edit'></i> Price
            </span>
            <span class='roompostfix'>
                <? echo $room->price . " (" . $room->taxes . "% tax)"; ?>
            </span>
        </span>
        <div style='clear:both;'></div>
        <span class='roomattribute'>
            <span class='roomprefix'>
                <i class='fa fa-edit'></i> Price type
            </span>
            <span class='roompostfix'>
                <? echo $pricetypes[$room->priceType]; ?>
            </span>
        </span>
        <div style='clear:both;'></div>

    </div>
    <div style='clear:both;'></div>
</div>