<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$booking = $this->getSelectedBooking();
$types = $this->getTypes();
$items = $this->getItems();

$toPrint = array();
$addons = array();
$sorting = array();
foreach($booking->rooms as $room) {
    if($types[$room->bookingItemTypeId]->addon == 0) {
        $toPrint[] = $room;
        $sorting[] = strtotime($room->date->start);
    } else {
        $addons[] = $room;
    }
}
asort($sorting);
$sorted = array();
foreach($sorting as $key => $val) {
    $sorted[] = $toPrint[$key];
}
$toPrint = $sorted;

$prices = $this->getApi()->getPmsManager()->getPrices($this->getSelectedName(), $this->convertToJavaDate(time()), $this->convertToJavaDate(time()));
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$dates = $this->getApi()->getPmsManager()->getDefaultDateRange($this->getSelectedName());
$start = $this->convertToJavaDate(strtotime($dates->start));
$end = $this->convertToJavaDate(strtotime($dates->end));

$defaultType = $booking->rooms[0]->bookingItemTypeId;

$cleaningInterval = $config->cleaningInterval;
?>
<br>
<span gstype="form" method='addRoomToBooking'>
    <input type='hidden' value='<? echo $booking->id; ?>' gsname='bookingid'>
    <input type='text' class='newroomstartdate' style=' width: 80px;' value='<?php echo date("d.m.Y", strtotime($start)); ?>' gsname='start'>
    <input type='text' class='newroomstarttime' style='width: 40px;text-align: center;' value='<?php echo date("H:i", strtotime($start)); ?>' gsname='starttime'> - 
    <input type='text' class='newroomenddate' style='width: 80px;' value='<?php echo date("d.m.Y", strtotime($end)); ?>' gsname='end'>
    <input type='text' class='newroomendtime' style='margin-right: 10px; width: 40px;text-align: center;' value='<?php echo date("H:i", strtotime($end)); ?>' gsname='endtime'>
    <? $this->includeAddRoomOptions($items, $start, $end, $defaultType); ?>
    <span class='pmsbutton' gstype='submitToInfoBox'>
        <?php
        switch($config->bookingProfile) {
            case "subscription":
            case "storage":
                echo "Add subscription";
                break;
            default:
                echo  "Add room";
                break;
        }
        ?>
    </span>
    
    <?php
    if($config->supportMoreDates) {
        ?>
        <span class='repeatdateform'>
            <?php
            $this->includefile("addmoredates");
            ?>
        </span>
    <?php } ?>
</span>
<br><br>

<?php
$hasArx = false;
if($config->arxHostname) {
    $hasArx = true;
}
$hasPrices = false;

$arr = (array)$prices->dailyPrices;

if(($prices->defaultPriceType == 1 && !empty($arr)) || $prices->defaultPriceType != 1) {
     $hasPrices = true;
}

printRooms($toPrint, $types, $items, $booking, false, $hasPrices, $hasArx,$config, $this);

if(sizeof($addons) > 0) {
    echo '<h2>Addons</h2>';
    printRooms($addons, $types, $items, $booking, true, $hasPrices, $hasArx,$config, $this);
}

/**
 * 
 * @param type $rooms
 * @param type $types
 * @param type $items
 * @param type $bookingId
 * @param type $addons
 * @param type $hasPrices
 * @param type $hasArx
 * @param core_pmsmanager_PmsConfiguration $config
 * @param \ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement $object
 */
function printRooms($rooms, $types, $items, $booking, $addons, $hasPrices, $hasArx, $config, $object) {
    $bookingId = $booking->id;
    ?>
<table width='100%' cellspacing='0' cellpadding='0' class='guestoverviewtable'>
    <tr>
        <th width='10'></th>
        <th>Type</th>
        <th>Room</th>
        <th>Time periode</th>
        <?php if($config->manualcheckincheckout) { ?>
        <th>Check in/out</th>
        <?php } ?>
        <th>Guest</th>
        <?php if(!$addons && $hasPrices) { ?>
        <th>Price <i class='fa fa-edit showmassupdatepricesfield' title='Update prices for all rooms'></i>
            <div class='massupdatepricesfield' gstype="form" method="massUpdatePrices">
                <div style='padding: 5px; padding-top: 10px; padding-bottom: 10px; text-align:center;'>Update all prices for all rooms.
                <input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
                <i class='fa fa-close' style='float:right; cursor:pointer;'></i>
                </div>
                <table cellspacing='0' cellpadding='0'>
                    <tr>
                        <th>Day</th>
                        <th>Price</th>
                    </tr>
                    <tr>
                        <td>Every day</td>
                        <td><input type='txt' class='alldayprice'></td>
                    </tr>
                    <tr>
                        <td>Monday</td>
                        <td><input type='txt' class='dayprice' gsname='price_mon'></td>
                    </tr>
                    <tr>
                        <td>Tuesday</td>
                        <td><input type='txt' class='dayprice' gsname='price_tue'></td>
                    </tr>
                    <tr>
                        <td>Wednesday</td>
                        <td><input type='txt' class='dayprice' gsname='price_wed'></td>
                    </tr>
                    <tr>
                        <td>Thursday</td>
                        <td><input type='txt' class='dayprice' gsname='price_thu'></td>
                    </tr>
                    <tr>
                        <td>Friday</td>
                        <td><input type='txt' class='dayprice' gsname='price_fri'></td>
                    </tr>
                    <tr>
                        <td>Saturday</td>
                        <td><input type='txt' class='dayprice' gsname='price_sat'></td>
                    </tr>
                    <tr>
                        <td>Sunday</td>
                        <td><input type='txt' class='dayprice' gsname='price_sun'></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td style='text-align:center;'><span class='pmsbutton' gstype='submitToInfoBox'>Update</span></td>
                    </tr>
                </table>
            </div>
        
        </th>
            <th>Invoiced until</th>
        <?php } ?>
        <?php if($hasArx) { ?>
            <th>To lock</th>
        <?php } ?>
    </tr>

    <?php
    foreach ($rooms as $room) {
        /* @var $room core_pmsmanager_PmsBookingRooms */
        $date = $room->date;
        $roomCleaningInterval = $config->cleaningInterval;
        if($room->intervalCleaning) {
            $roomCleaningInterval = $room->intervalCleaning;
        }
        $deleted = "";
        if($room->deleted) {
            $deleted = "roomdeleted";
        }
        $lastSelectedRoom = $object->getLastSelectedRoom();

        $highlightclass = "";
        if($room->pmsBookingRoomId == $lastSelectedRoom) {
            $highlightclass = "highlight";
        }
        ?>
        <tr bookingid='<? echo $bookingId; ?>' roomid='<? echo $room->pmsBookingRoomId; ?>' class='<?php echo $deleted. " " . $highlightclass; ?>'>
            <td>
                <span gstype='form' method="removeRoom">
                    <input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
                    <input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
                    <?php if(!$deleted) { ?>
                        <i class='fa fa-trash-o' style="cursor:pointer;" gstype='submitToInfoBox'></i>
                    <?php } else { ?>
                        Deleted <i class='fa fa-undo'  gstype='submitToInfoBox' title="Undelete" style='cursor:pointer;'></i>
                    <?php } ?>
                </span>
                    <?php
                    if($config->autoExtend) {
                        ?>
                        <span gstype='form' method="markKeyReturned">
                            <input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
                            <input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
                            <i class='fa fa-key' gstype='submitToInfoBox' <?php if($room->keyIsReturned) { echo "style='color:green;'"; } ?>></i>
                        </span>
                        <?php
                    }
                    ?>
                <?php if(!$deleted) { ?>
                    <span gstype='form' method="splitToSingleBooking">
                        <input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
                        <input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
                        <i class='fa fa-random' gstype='submitToInfoBox' title='Split into single booking' style='cursor:pointer;'></i>
                    </span>
                <?php } ?>
            </td>
            <td>
                <? 
                $object->includeLegacyStuffForSemlagerhotell($booking, $room);

                echo $types[$room->bookingItemTypeId]->name; ?>
                <?php if($config->cleaningInterval) { ?>
                <?php echo "<div title='Cleaning interval' class='change_cleaning_interval' roomid='".$room->pmsBookingRoomId."'>CI: <span class='intervalset'>" . $roomCleaningInterval . "</span></div>"; ?>
                <?php } ?>
            </td>
            <td>
                    <span class='roomattribute'>
                        <span class='roompostfix'>
                            <span class="viewmode">
                                <?
                                if (!$room->bookingItemId) {
                                    echo "Not assigned yet";
                                } else {
                                    $notifications = "notifications: " . join(",", $room->notificationsSent);
                                    echo "<span title='Change room'>" . $items[$room->bookingItemId]->bookingItemName . "</span>";
                                }
                                if(!$object->getFactory()->isProductionMode()) {
//                                    echo " - <span class='resetnotifications' roomid='".$room->pmsBookingRoomId."' bookingid='".$bookingId."'>reset notifications</span>";
                                }

                                ?>
                            </span>
                            <span class="editmode" gstype='form' method='setBookingItem' >
                                <input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
                                <input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
                                <?php
                                $now = $room->date->start;
                                if(strtotime($now) < time() && strtotime($room->date->end) > time()) {
                                    $now = $object->convertToJavaDate(time());
                                }
                                ?>
                                <select gsname='itemid'>
                                    <?php 
                                    $isAvailableItem = $object->getApi()->getBookingEngine()->getAllAvailbleItemsWithBookingConsidered($object->getSelectedName(), $now, $room->date->end, $room->bookingId);
                                    $isAvailableItem = $object->indexList($isAvailableItem);
                                    $allItems = $object->getApi()->getBookingEngine()->getBookingItems($object->getSelectedName());
                                    echo "<option value=''>Unassigned</option>";
                                    foreach($allItems as $item) {
                                        $selected = "";
                                        if($types[$item->bookingItemTypeId]->addon > 0) {
                                            continue;
                                        }
                                        
                                        $taken = " (" .$object->__w("Occupied"). ")";
                                        if($isAvailableItem[$item->id]) {
                                            $taken = "";
                                        }

                                        $desc = "";
                                        if($item->description) {
                                            $desc = ", ". strtolower($item->description);
                                        }
                                        
                                        if($room->bookingItemId == $item->id) {
                                            $selected = "SELECTED";
                                        }
                                        echo "<option value='".$item->id."' $selected>" . $item->bookingItemName . " (" . $types[$item->bookingItemTypeId]->name . ")$taken $desc" . "</option>";
                                    }
                                    ?>
                                </select><br>
                                <span class='pmsbutton tiny' gstype='submitToInfoBox' gsvalue='notsplit'>Change</span>
                                <?php
                                $start = strtotime($room->date->start);
                                $diff = strtotime($room->date->end) - $start;
                                $splitchange = false;
                                if($start < time() && $diff > 86400 && date("dmY", $start) != date("dmY", time())) {
                                    $splitchange = true;
                                }
                                if($splitchange) {
                                ?>
                                    <span class='pmsbutton tiny' gstype='submitToInfoBox' gsvalue='split'>Split change</span>
                                <?php } ?>
                                <div class="tiparea" style="width: 500px;">
                                </div>
                                <?php if($splitchange) { ?>
                                    <div>
                                        * Change moves the entire stay to the new room<br>
                                        * Split change only move the stay from today.<br>
                                    </div>
                                <?php } ?>
                            </span>
                        </span>
                    </span>
                </td>
                <td>
                <span class='roomattribute'>
                    <span class='roompostfix' style='width: 230px;'>
                        <span class="viewmode">
                            <?php 
                            echo date("d.m.Y H:i", strtotime($date->start));
                            if(date("d.m.Y", strtotime($date->start)) == date("d.m.Y", strtotime($date->end))) {
                                echo " - " . date("H:i", strtotime($date->end));
                            } else {
                                echo "<br>" . date("d.m.Y H:i", strtotime($date->end));
                            }
                            if($config->bookingTimeInterval == 2) {
                                $diff = ((strtotime($date->end) - strtotime($date->start)) / 86400);
                                echo " <span title='Number of nights'>(" . round($diff) . ")</span>";
                            } 
                            ?>
                        </span>
                        <span class='editmode' gstype='form' method="setNewStartDate">
                            <input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
                            <input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
                            <span style='display:inline-block; width: 80px;'>Start</span> 
                                <input type='text' gsname='start' value='<? echo date("d.m.Y", strtotime($room->date->start)); ?>' style='width:80px;' class='calinput'>
                                <input type='text' gsname='starttime' value='<? echo date("H:i", strtotime($room->date->start)); ?>'  style='width:40px;'>
                                <br>
                            <span style='display:inline-block; width: 80px;'>End</span> 
                            <input type='text' gsname='end' value='<? echo date("d.m.Y", strtotime($room->date->end)); ?>' style='width:80px;' class='calinput'>
                            <input type='text' gsname='endtime' value='<? echo date("H:i", strtotime($room->date->end)); ?>' style='width:40px;'>
                            <br>
                            <span class='pmsbutton tiny' gstype='submitToInfoBox'>Change</span>
                        </span>
                    </span>
                </span>
            </td>
            <?php if($config->manualcheckincheckout) { ?>
            <td>
                <?php
                if(!$room->checkedin) {
                    ?>
                    <span gstype='form' method="checkInGuest">
                          <input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
                          <input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
                          <span class='pmsbutton' gstype='submitToInfoBox' method='checkinguest' gsname='id' style='padding:3px; width:80px; text-align: center;'>Check in</span>
                    </span>
                    <?php
                } else if(!$room->checkedout) { 
                    ?>
                    <span gstype='form' method="checkOutGuest">
                          <input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
                          <input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
                          <span class='pmsbutton' gstype='submitToInfoBox' method='checkinguest' gsname='id' style='padding:3px; width:80px; text-align: center;'>Check out</span>
                    </span>
                    <?php
                } else { 
                    echo "Checked out"; 
                }
                ?>
            </td>
            <? } ?>
            <? if(!$addons && $hasPrices) { ?>
                <td>
                    <span class='roomattribute'>
                        <span class='roompostfix editGuestToggle'>
                            <span class="viewmode">
                                <?php
                                foreach ($room->guests as $guest) {
                                    echo ($guest->name) ? $guest->name : "No name";
                                    echo "<br>";
                                }
                                ?>
                            </span>
                            <span class="editmode" gstype='form' method="setGuests" style="width:400px;">
                                <input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
                                <input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
                                <select gsname='numberofguests'>
                                <?php
                                for($i = 1; $i <= 20; $i++) {
                                    $selected = "";
                                    if($i == $room->numberOfGuests) {
                                        $selected = "SELECTED";
                                    }
                                    echo "<option value='$i' $selected>$i</option>";
                                }
                                ?>
                                </select><br>
                                <table>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                    </tr>
                                <?php for($i = 0; $i < 20; $i++) {
                                    $guest = new core_pmsmanager_PmsGuests();
                                    if(isset($room->guests[$i])) {
                                        $guest = $room->guests[$i];
                                    }
                                    echo "<tr class='guestrow_$i guestrow'>";
                                    echo "<td><input type='text' value='".$guest->name."' gsname='name_$i' style='width:100px;'></td>";
                                    echo "<td><input type='text' value='".$guest->email."' gsname='email_$i' style='width:100px;'></td>";
                                    echo "<td><input type='text' value='+".$guest->prefix."' gsname='prefix_$i' style='width:30px;float:left;'><input type='text' value='".$guest->phone."' gsname='phone_$i' style='float:left;width:70px;'></td>";
                                    echo "</tr>";
                                }
                                ?>
                                </table>
                                <span class='pmsbutton tiny' gstype='submitToInfoBox'>Change</span>
                            </span>
                        </span>
                    </span>
                </td>
                <td>
                    <span class='roomattribute'>
                        <span class='roompostfix'>
                            <span class='viewmode'>
                                <? 
                                echo round($room->price); 
                                ?>
                            </span>
                            <span class='editmode' method='changePrice' gstype='form'>
                                <input type='hidden' value='<? echo $bookingId; ?>' gsname='bookingid'>
                                <input type='hidden' value='<? echo $room->pmsBookingRoomId; ?>' gsname='roomid'>
                                <?
                                $matrix = array();
                                foreach($room->priceMatrix as $key => $val) {
                                    $matrix[strtotime($key)] = $val;
                                }
                                ksort($matrix);
                                
                                if(!$config->usePriceMatrixOnOrder) {
                                    ?>
                                    <input type='hidden' value='no' gsname='pricematrix'>
                                    <input type='text' gsname='price' value='<? echo $room->price; ?>'>
                                    <?php
                                } else {
                                    ?>
                                    <table cellspacing='0' cellpadding='0' class='roompricematrixtable'>
                                    <tr><th>Day</th><th>price</th></tr>
                                    <?php if(sizeof($matrix) > 1) { ?>
                                        <tr><th>All days</th><th><input type='text' class='matrixpricealldays' style='width: 40px; border: solid 1px;'></th></tr>
                                    <?php
                                    }
                                    echo "<input type='hidden' value='yes' gsname='pricematrix'>";
                                    foreach($matrix as $key => $val) {
                                        echo "<tr><td><div style='display:inline-block; width: 125px;'>" . date("d.m.Y", $key) . "</td><td><input type='txt' value='$val' gsname='matrixprice_$key' class='matrixdayprice' style='width: 40px; border: solid 1px;'></div></td></tr>";
                                    }
                                    ?> 
                                    </table>
                                <?php } ?>
                                <span class='pmsbutton tiny' gstype='submitToInfoBox'>Change</span>
                            </span>
                        </span>
                    </span>
                </td>
            <? } ?>
            <td class="changeInvoiceTo">
                <? 
                if($room->invoicedTo) {
                    echo date("d.m.Y" , strtotime($room->invoicedFrom)) . "<br>"; 
                    echo date("d.m.Y" , strtotime($room->invoicedTo)); 
                } else {
                    echo " - ";
                }
                ?>
            </td>
            <?php if($hasArx) { ?>
            <td align='center'>
                <? echo ($room->addedToArx) ? "yes" : "no"; ?>
            </td>
            <? } ?>
        </tr>
    <?php } ?>
</table>
<?php
}
?>

<script>
    $('.calinput').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('.newroomstartdate').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('.newroomenddate').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
</script>
    