<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$stats = $this->getManager()->getStatistics($this->getSelectedName(), $this->getSelectedFilter());
$filter = $this->getSelectedFilter();
$intervaloptions = array();
$intervaloptions['daily'] = "Daily";
$intervaloptions['weekly'] = "Weekly";
$intervaloptions['monthly'] = "Monthly";
$intervaloptions['yearly'] = "Yearly";
$firstWidth = 45;

$paymentTypes = array();
foreach ($stats->salesEntries as $saleEntry) {
    foreach($saleEntry->paymentTypes as $type => $val) {
        $paymentTypes[$type] = 1;
    }
}


if($filter->channel || sizeof($filter->typeFilter) > 0) {
    $firstWidth = 100;
}
?>
<div style='clear:both;' class='changeintervalrow'>
    <select class='changestatisticsinterval'>
        <?php
        foreach($intervaloptions as $type => $value) {
            $selected = ($type == $filter->timeInterval) ?  "SELECTED" : "";
            echo "<option value='$type' $selected>$value</option>";
        }
        ?>
    </select>
    <span style="float:right; font-size: 12px; cursor:pointer;" gstype='clicksubmit' method='saveCoverageSettings'>
        Save latest loaded filter
    </span>

    
</div>
<br>
<div class="pdfPageSizer" >
    <style>
        .coveragechart {
            width: 50%; height: 300px; float:left;
            border: solid 1px #bbb;
            box-sizing: border-box;
        }
    </style>
    
    <div id="guestroomchart" class='coveragechart'></div>
   
    <script type="text/javascript">
      function drawChart() {
        var data = google.visualization.arrayToDataTable(<?php echo $this->getChartData($stats->entries, $filter, "roomguest"); ?>);
        var options = {
          title: 'Rooms and guests',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('guestroomchart'));
        chart.draw(data, options);
      }
      drawChart();
    </script>
    
    <div id="performacechart" class='coveragechart'></div>
    <script type="text/javascript">
      function drawChart() {
        var data = google.visualization.arrayToDataTable(<?php echo $this->getChartData($stats->entries, $filter, "revpar"); ?>);
        var options = {
          title: 'Economy performance',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('performacechart'));
        chart.draw(data, options);
      }
      drawChart();
    </script>
    
    <div id="totalincomechart" class='coveragechart'></div>
    <script type="text/javascript">
      function drawChart() {
        var data = google.visualization.arrayToDataTable(<?php echo $this->getChartData($stats->entries, $filter, "income"); ?>);
        var options = {
          title: 'Total income',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('totalincomechart'));
        chart.draw(data, options);
      }
      drawChart();
    </script>
    
    <div id="coveragechart" class='coveragechart'></div>
    <script type="text/javascript">
      function drawChart() {
        var data = google.visualization.arrayToDataTable(<?php echo $this->getChartData($stats->entries, $filter, "coverage"); ?>);
        var options = {
          title: 'Coverage (percentage)',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('coveragechart'));
        chart.draw(data, options);
      }
      drawChart();
    </script>
</div>
<br>
<div class="pdfPageSizer" >
    <table cellspacing='0' cellpadding='0' class='statisticstable' width='100%'>
        <tr>
            <th>
                <i gs_downloadexcelreport="exportBookingStats" title="Download to excel" style="cursor:pointer" class="fa fa-file-excel-o" aria-hidden="true" gs_filename="bookingdataexport"></i>
                <?php echo $this->__w("Date"); ?></th>
            <th><?php echo $this->__w("Spare<br>rooms"); ?></th>
            <th><?php echo $this->__w("Rented<br>out"); ?></th>
            <th><?php echo $this->__w("Guests"); ?></th>
            <th><?php echo $this->__w("Avg.<br>price"); ?></th>
            <th><?php echo $this->__w("RevPar"); ?></th>
            <th><?php echo $this->__w("Total"); ?></th>
            <th><?php echo $this->__w("Budget"); ?></th>
            <th><?php echo $this->__w("Coverage"); ?></th>
        </tr>
        <?
        foreach ($stats->entries as $entry) {
            $included = $entry->roomsIncluded;
            $included = json_encode($included);
            
            $guests = $entry->guestCount;
            if ($entry->date) {
                $day = $this->getDayText($entry->date, $filter->timeInterval);
            } else {
                $day = "Sum";
            }
            echo "<tr class='statisticsrow' type='coverage' day='$day' included='$included'>";
            echo "<td>";
                echo $day;
            echo "</td>";
            echo "<td>"; if($entry->spearRooms >= 0) { echo $entry->spearRooms; } echo "</td>";
            echo "<td>"; if($entry->roomsRentedOut >= 0) { 
                echo $entry->roomsRentedOut; 
                if($entry->roomsNotIncluded > 0) {
                    echo " (" . $entry->roomsNotIncluded . ")";
                }
            }
            echo "</td>";
            echo "<td>$guests</td>";
            echo "<td>"; if($entry->avgPrice >= 0) { echo round($entry->avgPrice); } echo "</td>";
            echo "<td>"; if($entry->revPar >= 0) { echo round($entry->revPar); } echo "</td>";
            if ($entry->date) {
                echo "<td>"; if($entry->totalPrice >= 0) { echo $entry->totalPrice; } echo "</td>";
            } else {
                echo "<td>"; if($entry->totalPrice >= 0) { echo "<b>" . $entry->totalPrice . "</b>"; } echo "</td>";
            }
            echo "<td>" . $entry->bugdet . "%</td>";
            if($entry->bugdet < $entry->coverage) {
                echo "<td class='budget_success'><i class='fa fa-check' style='float:right;'></i> " . $entry->coverage . "%</td>";
            } else {
                echo "<td class='budget_fail'><i class='fa fa-close' style='float:right;'></i> " . $entry->coverage . "%</td>";
            }
            echo "</tr>";
        }
        ?>
    </table>
    <br><br>
</div>
<div class="pdfPageSizer">
<b>Sale statistics</b><br>
    <?php 
    
    if(!$filter->channel && sizeof($filter->typeFilter) == 0 || $_SERVER['REQUEST_URI'] == "/handler.php") { ?>
    <div>
        <table cellspacing='0' cellpadding='0' class='statisticstable' width='100%'>
            <tr>
                <th>
                    <i gs_downloadexcelreport="exportSaleStats" title="Download to excel" style="cursor:pointer" class="fa fa-file-excel-o" aria-hidden="true" gs_filename="salestats"></i>
                    <?php echo $this->__w("Date"); ?></th>
                <th><?php echo $this->__w("Nights"); ?></th>
                <th><?php echo $this->__w("Sales count"); ?></th>
                <th><?php echo $this->__w("Avg."); ?><br> order</th>
                <?php
                if(sizeof($paymentTypes) > 1) {
                    foreach($paymentTypes as $type => $val) {
                        $tmpType = explode("\\", $type);
                        echo "<th>" . $this->translatePtype($tmpType[1]) . "</th>";
                    }
                }
                ?>
                <th><?php echo $this->__w("Booking value"); ?></th>
                <th><?php echo $this->__w("Total"); ?></th>
            </tr>
            <?
            foreach ($stats->salesEntries as $saleEntry) {
                $day = "";
                if ($saleEntry->date) {
                    $day = $this->getDayText($saleEntry->date, $filter->timeInterval);
                }
                echo "<tr class='statisticsrow' type='sale' day='$day'>";
                echo "<td>";
                echo $day;
                echo "</td>";
                echo "<td>" . $saleEntry->nights . "</td>";
                echo "<td>" . $saleEntry->numberOfOrders . "</td>";
                echo "<td>" . $saleEntry->avgOrderPrice . "</td>";

                if(sizeof($paymentTypes) > 1) {
                    foreach($paymentTypes as $type => $val) {
                        $val = 0;
                        if(isset($saleEntry->paymentTypes->{$type})) {
                            $val = $saleEntry->paymentTypes->{$type};
                        }
                        echo "<td>" . round($val ) . "</td>";
                    }
                }
                echo "<td>" . round($saleEntry->bookingValue) . "</td>";
                echo "<td>" . round($saleEntry->totalPrice) . "</td>";
                echo "</tr>";
            }
            ?>
        </table>
    </div>
<?php } ?>
</div>
<div style='clear:both;'></div>
