<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$stats = $this->getManager()->getStatistics($this->getSelectedName(), $this->getSelectedFilter());
?>
<div style='float:left; width: 45%'>
    <table cellspacing='0' cellpadding='0' class='statisticstable' width='100%'>
        <tr>
            <th>Date</th>
            <th>Total</th>
            <th>Avg.<br>price</th>
            <th>Rented<br>out</th>
            <th>Spear<br>rooms</th>
            <th>Budget</th>
            <th>Coverage</th>
        </tr>
        <?
        foreach ($stats->entries as $entry) {
            echo "<tr>";
            echo "<td>";
            if ($entry->date) {
                echo date("d.m.Y", strtotime($entry->date));
            }
            echo "</td>";
            echo "<td>" . $entry->totalPrice . "</td>";
            echo "<td>" . $entry->avgPrice . "</td>";
            echo "<td>" . $entry->roomsRentedOut . "</td>";
            echo "<td>" . $entry->spearRooms . "</td>";
            echo "<td>" . $entry->bugdet . "%</td>";
            echo "<td>" . $entry->coverage . "%</td>";
            echo "</tr>";
        }
        ?>
    </table>
</div>

<div style='float:right; width: 45%'>
    <table cellspacing='0' cellpadding='0' class='statisticstable' width='100%'>
        <tr>
            <th>Date</th>
            <th>Total</th>
            <th>Types</th>
            <th>Nights</th>
            <th>Orders</th>
            <th>Avg. order</th>
        </tr>
        <?
        foreach ($stats->salesEntries as $saleEntry) {
            echo "<tr>";
            echo "<td>";
            if ($saleEntry->date) {
                echo date("d.m.Y", strtotime($saleEntry->date));
            }
            echo "</td>";
            echo "<td>" . $saleEntry->totalPrice . "</td>";
            echo "<td>";
            $i = 0;
            foreach($saleEntry->paymentTypes as $type => $price) {
                $type = $this->translateText($type);
                echo "<span title='$type'>".round($price)."</span>";
                if($i < count(get_object_vars($saleEntry->paymentTypes))-1) {
                    echo "<br>";
                }
                $i++;
            }
            echo "</td>";
            echo "<td>" . $saleEntry->nights . "</td>";
            echo "<td>" . $saleEntry->numberOfOrders . "</td>";
            echo "<td>" . $saleEntry->avgOrderPrice . "</td>";
            echo "</tr>";
        }
        ?>
    </table>
</div>
<div style='clear:both;'></div>
