<?php
/* @var $this ns_7e828cd0_8b44_4125_ae4f_f61983b01e0a\PmsManagement */
$orders = $this->getCreatedOrders();
$instances = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
$instances = $this->indexList($instances);
$booking = $this->getSelectedBooking();
$end = 0;
foreach($booking->rooms as $room) {
    if(!$room->deleted && strtotime($room->date->end) > $end) {
        $end = strtotime($room->date->end);
    }
}

$endDate = date("d.m.Y", $end);

$user = $this->getApi()->getUserManager()->getUserById($booking->userId);
$result = $this->getOrdersForSelectedBooking();

if(sizeof($orders) > 1) {
    $amount = $orders[sizeof($orders)-1]['price'];
    $preferred = $booking->paymentType;
    if(!$preferred) {
        $preferredType = $this->getApi()->getPmsInvoiceManager()->getPreferredPaymentMethod($this->getSelectedName(), $booking->id, null);
        $preferred = $preferredType->paymentId;
    }
    
    if($booking->createOrderAfterStay) {
        echo "<div class='warnunsettled' gstype='form' method='fastordercreation'>";
        echo "<i class='fa fa-trash-o removecreateafterstayfrombooking' style='cursor:pointer;'></i> <i class='fa fa-warning' style='color:red;'></i> An order of $amount, will be created at : $endDate, payment type ";
        foreach($instances as $id => $app) {
            $selected = "";
            if($id == $preferred) {
                echo "<b>" . $app->appName . "</b>";
            }
        }
        echo "</div>";
    } else {
        if($amount != 0) {
            echo "<div class='warnunsettled' gstype='form' method='fastordercreation'>";
            echo "<input type='hidden' gsname='bookingid' value='". $booking->id."'>";
            echo "<i class='fa fa-warning' style='color:red;'></i> You have a unsettled amount of $amount, what would you like to do with it?<br>";
            echo "<select class='paymenttypeunsetled' gsname='paymenttype'>";
            foreach($instances as $id => $app) {
                $selected = "";
                if($id == $preferred) { $selected = "SELECTED"; }
                echo "<option value='".$app->appName."' $selected> ".$app->appName."</option>";
            }
            echo "</select> ";

            echo "<select gsname='appendToOrderId'>";
            foreach($result as $order) {
                if(!$order->closed) {
                    echo "<option value='" . $order->id . "'>Add to order " . $order->incrementOrderId . "</option>";
                }
            }
            $createOrderText = "Create a new order";
            if($amount < 0) {
                $createOrderText = "Create a new credit note";
            }

            echo "<option value=''>$createOrderText</option>";
            echo "<option value='createafterstay'>Create order after booking has been completed</option>";
            echo "</select> ";

            echo " <input type='button' value='Execute' gstype='submitToInfoBox'><br>";
            echo "<div class='paymenttypeinfoarea' type='sendpaymentlink' style='font-size: 12px;'>";
            if($amount > 0) {
                echo "<input type='checkbox' checked gsname='sendpaymentlink' > Send payment link";
                echo "<div>";
                echo "<br>Sending to: ";
                echo "+<input type='txt' gsname='paymentlinkprefix' value='".$user->prefix."' placeholder='phone' gsname='paymentlinkphone' style='width:30px;'> ";
                echo "<input type='txt' gsname='paymentlinkphone' value='".$user->cellPhone."' placeholder='phone' gsname='paymentlinkphone'> ";
                echo "<input type='txt' gsname='paymentlinkemail' value='".$user->emailAddress."' style='width:300px;' placeholder='Email adress' gsname='paymentlinkemail'>";
                echo "</div>";
            }
            echo "</div>";
            echo "<div class='paymenttypeinfoarea' type='InvoicePayment'><br>Invoice information (fetched from user account above):<br>";
            echo "<span style='font-size:12px;'>" . $user->fullName . "<bR>";
            echo $user->address->address . "<br>";
            echo $user->address->postCode . " " . $user->address->address . "</span><bR>";
            echo "<br>Note on invoice:<br>";
            echo "<textarea style='width:100%; height: 100px;' gsname='invoicenoteinfo'>" . $booking->invoiceNote . "</textarea>";
            echo "</div>";
            echo "</div>";
        }
    }
}
?>

<style>
    .paymenttypeinfoarea { display:none; }
</style>
<script>

function loadPaymentTypeAreas() {
    var val = $('.paymenttypeunsetled').val();
    if(val === "Dibs" || val === "Epay") {
        val = "sendpaymentlink";
    }
    $('.paymenttypeinfoarea').hide();
    $('.paymenttypeinfoarea[type="'+val+'"]').show();
}
loadPaymentTypeAreas();
$('.paymenttypeunsetled').on('change',loadPaymentTypeAreas);
</script>