<?
/* @var $this \ns_b81bfb16_8066_4bea_a3c6_c155fa7119f8\DashBoard */
?>
<div class='gss_settings_main_area'>
    <div class='gss_settings_getshop_logo'>
        <div class='gss_logo'></div>
        <div class='gss_slogan'>GetShop Admin</div>
    </div>

    <div class='gss_appviews'>
        
        <?
        $apps = $this->getApi()->getStoreApplicationPool()->getApplications();
        foreach ($apps as $app) {
            
            $instance = $this->getFactory()->getApplicationPool()->createInstace($app);
            
            if ($instance) {
                ob_start();
                $instance->renderDashBoardWidget();
                $content = ob_get_contents();
                ob_end_clean();
                
                if ($content) {
                    echo "<div class='gss_appview'> ";
                    echo $content;
                    echo "</div>";
                }
            }
        }
        ?>
    </div>
</div>