<div class="registrationform">   
    <div class="registration_step step3">
        <div class="stepinfo">
            <? echo $this->__f("Step")." 3/3"; ?>
        </div>
        
        <div class="step_content">
            <label><? echo $this->__f("Search for company"); ?></label>
            <br/><input class="gsniceinput1" type="txt" id="searchforcompany"/><i class='gs_shop_small_icon fa fa-search searchforcompanyicon'></i> 
            <br/>
            <br/>
            <div class="searchresult">
                <? echo $this->__f("Please enter your companyname in the textfield above"); ?>
            </div>
        </div>
   </div>
</div>