<?
/* @var $this ns_77bd71b1_a0e2_494e_a9e9_6dcee3829c5c\ProMeisterCreateAccount */

$groups = $this->getApi()->getUserManager()->getAllGroups();

$groupsReference = [];
foreach ($groups as $group) {
    if ($group->usersRequireGroupReference) {
        $groupsReference[] = $group->id;
    }
}

$groupsReference = implode(",", $groupsReference);
?>

<div class="registrationform">
    <div class="registration_step step1">
        <div class="stepinfo">
            <? echo $this->__f("Step")." 1/3"; ?>
        </div>
            
        <?
        echo $this->__w("Please select group");
        echo "<br/>";
        echo "<br/>";
        foreach ($groups as $group) {
            echo "<div class='groupselect' value='$group->id'>";
            if ($group->imageId) {
                echo "<img src='displayImage.php?id=$group->imageId'/>";    
            } else {
                echo $group->groupName;
            }
            echo "</div>";
        }
        ?>
    </div>
    
    <div class="registration_step step2">
        <div class="stepinfo">
            <? echo $this->__f("Step")." 2/3"; ?>
        </div>
        
        <label>* <? echo $this->__f("Full name"); ?></label>
        <br/><input class="gsniceinput1" mandatory="yes" type="txt" name="fullname"/>
        <br/>
        <br/><label><? echo $this->__f("Email"); ?></label>
        <br/><input class="gsniceinput1" type="txt" name="email"/>
        <br/>
        <br/><label>* <? echo $this->__f("Invoice email"); ?></label>
        <br/><input class="gsniceinput1" type="txt"  mandatory="yes" name="invoicemail"/>
        <br/>
        <br/><label>* <? echo $this->__f("Cellphone"); ?></label>
        <br/><input class="gsniceinput1" type="txt"  mandatory="yes" name="cellphone"/>
        <br/>
        <br/>
        <div class='groupfield' avtivatedForGroups="<? echo $groupsReference; ?>">
            <label>* <? echo $this->__f("Customernumber"); ?></label>
            <br/><input class="gsniceinput1" type="txt"  mandatory="yes" name="groupreference"/>
        </div>
        <br/>
        <br/><input class="gsniceinput1" type="checkbox" name="isgarageleader"/><? echo $this->__f("Garage leader"); ?>
        <br/> <? echo $this->__f("Check this if you administrate your mechanics."); ?>
        <br/>
        <br/><label>* <? echo $this->__f("Password"); ?></label>
        <br/><input class="gsniceinput1" type="password" name="password"  mandatory="yes" />
        <br/>
        <br/><label>* <? echo $this->__f("Repeat password"); ?></label>
        <br/><input class="gsniceinput1" type="password" name="password_repeated"  mandatory="yes" />
        <br/>
        <br/>
        <div class="shop_button userinformationnext">
            <? echo $this->__f("Next"); ?>
        </div>
    </div>
    
    <div class="registration_step step3">
        <div class="stepinfo">
            <? echo $this->__f("Step")." 3/3"; ?>
        </div>
        
        <label><? echo $this->__f("Search for company"); ?></label>
        <br/><input class="gsniceinput1" type="txt" id="searchforcompany"/>
        <br/>
        <br/>
        <div class="searchresult">
            <? echo $this->__f("Please enter your companyname in the textfield above"); ?>
        </div>
        <br/>
        <br/>
        <div class="shop_button companyselected">
            <? echo $this->__f("Create account"); ?>
        </div>
    </div>
</div>