<?
/* @var $this ns_77bd71b1_a0e2_494e_a9e9_6dcee3829c5c\ProMeisterCreateAccount */

$groups = $this->getApi()->getUserManager()->getAllGroups();

$groupsReference = [];
foreach ($groups as $group) {
    if ($group->usersRequireGroupReference) {
        $groupsReference[] = $group->id;
    }
}

$groupsReference = implode(",", $groupsReference);
?>

<div class="registrationform">
    
    
<!--    <div class="registration_step step2">

    </div>-->
    <div class="registration_step step2">
        <div class="stepinfo">
            <? echo $this->__f("Step")." 2/3"; ?>
        </div>
        
    </div>
    
    <div class="registration_step step3">
        <div class="stepinfo">
            <? echo $this->__f("Step")." 3/3"; ?>
        </div>
        
        <label><? echo $this->__f("Search for company"); ?></label>
        <br/><input class="gsniceinput1" type="txt" id="searchforcompany"/>
        <br/>
        <br/>
        <div class="searchresult">
            <? echo $this->__f("Please enter your companyname in the textfield above"); ?>
        </div>
        <br/>
        <br/>
        <div class="shop_button companyselected">
            <? echo $this->__f("Create account"); ?>
        </div>
    </div>
</div>