<?
/* @var $this ns_77bd71b1_a0e2_494e_a9e9_6dcee3829c5c\ProMeisterCreateAccount */
$group = $this->getSelectedGroup();

?>
<div class="registrationform">
    <div class="registration_step step2">
        <div class="stepinfo">
            <? echo $this->__f("Step")." 3/3"; ?>
        </div>
        
        <div class="step_content">
            <label>* <? echo $this->__f("Full name"); ?></label>
            <br/><input class="gsniceinput1" mandatory="yes" type="txt" name="fullname"/>
            <br/>
            <br/><label><? echo $this->__f("Email"); ?></label>
            <br/><input class="gsniceinput1" type="txt" name="email"/>
            <br/>
            <br/><label>* <? echo $this->__f("Invoice email"); ?></label>
            <br/><input class="gsniceinput1" type="txt"  mandatory="yes" name="invoicemail"/>
            <br/>
            <br/><label>* <? echo $this->__f("Cellphone"); ?></label>
            <br/><input class="gsniceinput1" type="txt"  mandatory="yes" name="cellphone"/>
            <br/>
            <br/><input class="gsniceinput1" type="checkbox" name="isgarageleader"/><? echo $this->__f("Garage leader"); ?>
            <br/> <? echo $this->__f("Check this if you administrate your mechanics."); ?>
            <div class='othercompanies'>
                <br/><input class="gsniceinput1" type="txt"  mandatory="yes" name="othercompanies" placeholder="<? echo $this->__f("Other companies you need access to?"); ?>"/>    
            </div>
            <br/>
            <br/><label>* <? echo $this->__f("Password"); ?></label>
            <br/><input class="gsniceinput1" type="password" name="password"  mandatory="yes" />
            <br/>
            <br/><label>* <? echo $this->__f("Repeat password"); ?></label>
            <br/><input class="gsniceinput1" type="password" name="password_repeated"  mandatory="yes" />
            <br/>
            <br/>
            <div class="shop_button createAccount">
                <? echo $this->__f("Next"); ?>
            </div>
        </div>
    </div>
</div>