package com.thundashop.api.managers;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import com.thundashop.core.common.JsonObject2;
import com.thundashop.core.reportingmanager.data.ReportFilter;
import java.util.List;

public class APIReportingManager {

      private Transporter transport;

      public APIReportingManager(Transporter transport){
           this.transport = transport;
      }

     /**
     * Fetch all activity data for a given session at a given period in time.
     * @param startDate "yyyy-mm-dd"
     * @param stopDate "yyyy-mm-dd"
     * @param searchSessionId The id of the session to fetch data from.
     * @return List
     * @throws ErrorException 
     */

     public List getAllEventsFromSession(String startDate, String stopDate, String searchSessionId)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("startDate",new Gson().toJson(startDate));
          data.args.put("stopDate",new Gson().toJson(stopDate));
          data.args.put("searchSessionId",new Gson().toJson(searchSessionId));
          data.method = "getAllEventsFromSession";
          data.interfaceName = "core.reportingmanager.IReportingManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<List>() {}.getType();
          List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch all users which connected at a given time period.
     * These are users who has been logging on to your store.
     * @param startdate "yyyy-mm-dd"
     * @param stopDate "yyyy-mm-dd"
     * @param filter A report filter if you want to filter out more information, use null to avoid the filter.
     * @return List
     * @throws ErrorException 
     */

     public List getConnectedUsers(String startdate, String stopDate, ReportFilter filter)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("startdate",new Gson().toJson(startdate));
          data.args.put("stopDate",new Gson().toJson(stopDate));
          data.args.put("filter",new Gson().toJson(filter));
          data.method = "getConnectedUsers";
          data.interfaceName = "core.reportingmanager.IReportingManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<List>() {}.getType();
          List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * List all orders created at a given time period.
     * @param startDate "yyyy-mm-dd"
     * @param stopDate "yyyy-mm-dd"
     * @return List
     * @throws ErrorException 
     */

     public List getOrdersCreated(String startDate, String stopDate)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("startDate",new Gson().toJson(startDate));
          data.args.put("stopDate",new Gson().toJson(stopDate));
          data.method = "getOrdersCreated";
          data.interfaceName = "core.reportingmanager.IReportingManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<List>() {}.getType();
          List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch the page id for all page 
     * @param startDate "yyyy-mm-dd"
     * @param stopDate "yyyy-mm-dd"
     * @return List
     * @throws ErrorException 
     */

     public List getPageViews(String startDate, String stopDate)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("startDate",new Gson().toJson(startDate));
          data.args.put("stopDate",new Gson().toJson(stopDate));
          data.method = "getPageViews";
          data.interfaceName = "core.reportingmanager.IReportingManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<List>() {}.getType();
          List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch all viewed product for a given time period.
     * @param startDate "yyyy-mm-dd"
     * @param stopDate "yyyy-mm-dd"
     * @return List
     * @throws ErrorException 
     */

     public List getProductViewed(String startDate, String stopDate)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("startDate",new Gson().toJson(startDate));
          data.args.put("stopDate",new Gson().toJson(stopDate));
          data.method = "getProductViewed";
          data.interfaceName = "core.reportingmanager.IReportingManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<List>() {}.getType();
          List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch a report for a given time period.
     * @param startDate "yyyy-mm-dd"
     * @param stopDate "yyyy-mm-dd"
     * @param type 0, hourly, 1. daily, 2. weekly, 3. monthly
     * @return List
     * @throws ErrorException 
     */

     public List getReport(String startDate, String stopDate, int type)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("startDate",new Gson().toJson(startDate));
          data.args.put("stopDate",new Gson().toJson(stopDate));
          data.args.put("type",new Gson().toJson(type));
          data.method = "getReport";
          data.interfaceName = "core.reportingmanager.IReportingManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<List>() {}.getType();
          List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch a list of all users trying / logging on at a given time interval.
     * @param startDate "yyyy-mm-dd"
     * @param stopDate "yyyy-mm-dd"
     * @return List
     * @throws ErrorException 
     */

     public List getUserLoggedOn(String startDate, String stopDate)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new HashMap();
          data.args.put("startDate",new Gson().toJson(startDate));
          data.args.put("stopDate",new Gson().toJson(stopDate));
          data.method = "getUserLoggedOn";
          data.interfaceName = "core.reportingmanager.IReportingManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<List>() {}.getType();
          List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

}
