package com.thundashop.api.managers;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.LinkedHashMap;
import com.thundashop.core.common.JsonObject2;
import com.thundashop.core.youtubemanager.data.SearchResult;
import java.util.List;

public class APIYoutubeManager {

      public Transporter transport;

      public APIYoutubeManager(Transporter transport){
           this.transport = transport;
      }

     /**
 * The youtube manager handles the communication between the google youtube api and the frontend.
 */

     public List<SearchResult> searchYoutube(String searchword)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("searchword",new Gson().toJson(searchword));
          data.method = "searchYoutube";
          data.interfaceName = "core.youtubemanager.IYoutubeManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<List<SearchResult>>() {}.getType();
          List<SearchResult> object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

}
