<div class="bannerview">
    <?php
    $id = uniqid();
    $interval = $this->getInterval();
    $height = $this->getHeight() ? "height:".$this->getHeight()."px" : "";
    
    $texts = [];
    
    if (count($this->getBanners()) == 0 && $this->isEditorMode()) {
        ?>
        <div class='nobannersadded'>
            <div class='banner_info_text'>
                <? echo $this->__f('Almost done! all you need to do now is to upload your images. Hover the mouse over this image and the gear will appear.'); ?>    
            </div>
        </div>
        <script>
            $('.nobannersadded').each(function() {
                $(this).height($(this).width() / 3);
            });
        </script>
        <?
    }
    ?>
    <div class="uploadprogress_bannerslider">
        <? echo $this->__f("Upload in progress, please wait."); ?>
        <div class="bannerslider_uploads">
            
        </div>
    </div>
    <div class="gsgalleryroot">
        <div class="bannerslider" id="<? echo $id; ?>" interval="<? echo $interval; ?>">
            <?
            foreach ($this->getBanners() as $banner) {
                $imageId = $banner->imageId;
                $crop = json_decode($banner->crop_cordinates);
                list($width, $height) = getimagesize("../uploadedfiles/" . $imageId);
                $img = "displayImage.php?id=$imageId";
                echo "<div class='banner gsgallery' height='$height' width='$width' img='$img' index='0'>";
                echo "<img  width='100%' src='$img'/>";
                echo "</div>";
            }
            ?>
        </div>
        <div>
            <?
            $index = 1;
            $first = true;
            foreach ($this->getBanners() as $banner) {
                if($first) {
                    $first = false;
                    continue;
                }
                $imageId = $banner->imageId;
                echo "<div class='thumbnail' imageId='$imageId'>";
                list($width, $height) = getimagesize("../uploadedfiles/" . $imageId);
                $img = "displayImage.php?id=$imageId";
                echo "<span class='gsgallery'  height='$height' width='$width' img='$img' index='$index'>";
                echo "<img width='100%' src='displayImage.php?id=$imageId&height=90'/>";
                echo "</span>";
                echo "</div>";
                $index++;
            }
            ?>
        </div>
    </div>

<?
    $jsonTexts = json_encode($texts);
?>
    <script>
        app.Banner.Slider.start('<?php echo $id; ?>');
        app.Banner.Slider.showText('<?php echo $id; ?>', <? echo $jsonTexts; ?>)
    </script>
</div>