<?
/* @var $this ns_bd751f7e_5062_4d0d_a212_b1fc6ead654f\EventUserList */
$event = $this->getApi()->getEventBookingManager()->getEvent($this->getBookingEngineName(), $_POST['data']['eventId']);
$participatedStatus = @$event->participationStatus->{$_POST['data']['userId']};
$groupInvoiceIdStatus = @$event->groupInvoiceStatus->{$_POST['data']['userId']};
$invoiceGroups = $this->getApi()->getEventBookingManager()->getInvoiceGroups($this->getBookingEngineName(), $event->id);

?>

<div class="usersettings">
    Please select status: &nbsp;&nbsp;
    
    <select class="gsniceselect1 participationstatus" userid="<? echo $_POST['data']['userId']; ?>" eventId='<? echo $_POST['data']['eventId']; ?>'>
        <option value="participated" <? echo $participatedStatus == "participated" ? "selected='true'" : ""; ?>><? echo $this->getParticiationText("participated") ?></option>
        <option value="participated_free" <? echo $participatedStatus == "participated_free" ? "selected='true'" : ""; ?>><? echo $this->getParticiationText("participated_free") ?></option>
        <option value="participated_50" <? echo $participatedStatus == "participated_50" ? "selected='true'" : ""; ?>><? echo $this->getParticiationText("participated_50") ?></option>
        <option value="not_participated" <? echo $participatedStatus == "not_participated" ? "selected='true'" : ""; ?>><? echo $this->getParticiationText("not_participated") ?></option>
    </select>

    <?
    if (count($invoiceGroups)) {
    ?>
        <br/>
        <br/> Connected to an invoicegroup:

            <select class="gsniceselect1 groupinvoicingselected" userid="<? echo $_POST['data']['userId']; ?>" eventId='<? echo $_POST['data']['eventId']; ?>'>
            <option value="" <? echo !$groupInvoiceIdStatus ? "selected='true'" : ""; ?>>None</option>
            <?
            foreach ($invoiceGroups as $group) {
                ?>
                <option value="<? echo $group->id; ?>" <? echo $groupInvoiceIdStatus  == $group->id ? "selected='true'" : ""; ?>><? echo $group->name; ?></option>
                <?
            }
            ?>
        </select>
    <? 
    }
    ?>
        
    <br/>
    <br/>
    <br/>
    ( Automatically saved )
</div>