<?
/* @var $this ns_bd751f7e_5062_4d0d_a212_b1fc6ead654f\EventUserList */
$event = $this->getEvent();
$users = $this->getApi()->getEventBookingManager()->getUsersForEvent($this->getBookingEngineName(), $event->id);
$waitingListUsers = $this->getApi()->getEventBookingManager()->getUsersForEventWaitinglist($this->getBookingEngineName(), $event->id);
if (!$waitingListUsers) {
    $waitingListUsers = [];
}
$groups = $this->getApi()->getUserManager()->getAllGroups();
$isAdministrator = ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator();

if (!count($users)) {
    echo "<div style='padding: 20px;'>".$this->__w("No users added yet")."</div>";
    return;
}

if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
?>
    <div class='reports'>
        <center>Reports</center>
        <?
        foreach ($groups as $group) {
            $groupId = $group->id;
            $groupName = $group->groupName;
            $eventId = $event->id;
            $filename = date('d-m-Y', strtotime($event->mainStartDate))."-".$event->location->name."-".$event->subLocation->name."-".$event->bookingItemType->name."-".$groupName;
            echo "<div class='shop_button' gs_downloadExcelReport='downloadReport' gs_fileName='$filename' eventId='$eventId' groupid='$groupId'> $groupName </div>&nbsp;";
        }
        
        echo "<div class='shop_button' gs_downloadExcelReport='downloadReport' gs_fileName='users' eventId='$eventId' groupId='all'> All </div>&nbsp;";
        ?>
    </div>
<?
}

foreach ($users as $user) {
    $this->setCurrentUser($user);
    $this->setViewingWaitinglist(false);
    $this->includefile("userinforow");
}

?>
<br/>

<?
if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
?>
<div style='padding-left: 20px;'>
    <div class='shop_button' gs_show_modal="send_tests" eventid="<? echo $event->id; ?>"><? echo $this->__f("Send tests"); ?></div>
    <div class='shop_button' gs_show_modal="send_reminder" eventid="<? echo $event->id; ?>"><? echo $this->__f("Send reminders"); ?></div>
    <a class='gs_ignorenavigate' href="/scripts/promeister/download.php?eventId=<? echo $event->id; ?>"><div class='shop_button'><? echo $this->__f("Download PDFs"); ?></div></a>
    <?
    if ($event && !$event->markedAsReady) {
        echo "<div class='shop_button' gsclick='markAsReady' eventid='$event->id' gs_confirm='Are you sure you want to mark this as ready ?'>".$this->__w("Mark as ready")."</div>";
    }
    ?>
</div>
<?
}

if (count($waitingListUsers)) {
    echo "<div class='waitinglistusers'>";
        echo "<center>".$this->__f("Waitinglist")."</center>";
        foreach ($waitingListUsers as $user) {
            $this->setCurrentUser($user);
            $this->setViewingWaitinglist(true);
            $this->includefile("userinforow");
        }    
    echo "</div>";
}

if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
    $tests = $this->getApi()->getQuestBackManager()->getAllTests();
    if (count($tests)) {
    ?>
        <div class="questbacks">
            <div class="title"><? echo $this->__f("Available questbacks"); ?></div>
            <?
            foreach ($tests as $test) {
                if ($test->type === "questback") {
                    echo '<span class="gs_shop_small_icon" style="cursor: pointer" gs_show_modal="showTestResult" testid="'.$test->id.'" referenceId="'.$event->id.'">'.$this->__f("See result").'</span> - '.$test->name;
                }
            }
            ?>
        </div>
    <?
    }
}

?>

