<?
/* @var $this ns_bd751f7e_5062_4d0d_a212_b1fc6ead654f\EventUserList */
$event = $this->getEvent();
$users = $this->getApi()->getEventBookingManager()->getUsersForEvent($this->getBookingEngineName(), $event->id);
$groups = $this->getApi()->getUserManager()->getAllGroups();





if (!count($users)) {
    echo $this->__w("No users added yet");
    return;
}
?>

<div style='border: solid 1px #DDD; padding: 20px; background-color: #F9f9f9;'>
    <center>Reports</center>
    <?
    foreach ($groups as $group) {
        echo "<div class='shop_button'> $group->groupName</div>&nbsp;";
    }
    ?>
</div>
<br/>
<?
foreach ($users as $user) {
    $gradCapColor = "#006e63";
    $participatedStatus = @$event->participationStatus->{$user->id};
    $gradCapColor = $participatedStatus == "participated" ? "#006e63" : $gradCapColor;
    $gradCapColor = $participatedStatus == "participated_free" ? "#006e63" : $gradCapColor;
    $gradCapColor = $participatedStatus == "participated_50" ? "#d71e27" : $gradCapColor;
    $gradCapColor = $participatedStatus == "not_participated" ? "#d71e27" : $gradCapColor;
    
    ?>
    <div class="userline">
        <div class="gs_shop_small_icon" gsclick="removeUserFromEvent" gs_confirm="<? echo $this->__f("Are you sure you want to remove user from this event?"); ?>" eventid="<? echo $event->id; ?>"  userid="<? echo $user->id; ?>"><i class="fa fa-trash"></i></div>
        <? 
            $company = null;
            $group = null;
            
            if ($user->groups) {
                $group = $this->getApi()->getUserManager()->getGroup($user->groups[0]);
            }
            
            if ($user->company) {
                $company = $this->getApi()->getUserManager()->getCompany($user->company[0]);    
            }
            
            $commentColor = array_key_exists($user->id, $event->comments) ? "style='color: green;'" : "";
            
            echo $user->fullName;
            if ($company) {
                echo " - ".$company->name;
            } else {
                echo " - N/A";
            }
            
            if ($group) {
                echo " - ".$group->groupName;
            } else {
                echo " - N/A";
            }
        ?>
        <div class="options">
            <div class="gs_shop_small_icon addcomment" userId="<? echo $user->id; ?>" eventId="<? echo $event->id; ?>"><i class="fa fa-comments" <? echo $commentColor; ?>></i></div>
            <div class="gs_shop_small_icon showsettings" userId="<? echo $user->id; ?>" eventId="<? echo $event->id; ?>"><i class="fa fa-gears"></i></div>
            <i class='fa fa-graduation-cap' style='color: <? echo $gradCapColor; ?>'></i>
        </div>
    </div>
    <?
}
?>

<br/>
<div>
    <div class='shop_button'>Send reminders</div>
    <div class='shop_button'>Download PDFs</div>
</div>