<?
/* @var $this  ns_ed9b4b90_a5c8_4b25_99a4_d143f643dc2f\UserRoles */
$roles = $this->getApi()->getUserManager()->getUserRoles();
$user = $this->getCurrentUser();

if (!$roles) {
    $roles = array();
}
foreach ($roles as $role) {
    ?>

    <div class="textfield gss_setting"  id="showHiddenFields">
        
        <i gss_method="deleteRole" gss_confirmation="Are you sure you want to delete this role, it will be deleted for all users." gss_model="userrolemodel" gss_value_2="<? echo $role->id; ?>" class="fa fa-trash"></i> 
        <span class="title"><?php echo $role->name; ?></span>
        <div class="gss_onoff" gs_model="userrolemodel" gs_model_attr="<? echo $role->id; ?>">
            <?
            $faclass = in_array($role->id, $user->userRoleIds) ? "fa-toggle-on" : "fa-toggle-off";
            ?>
            Off<i class="fa <? echo $faclass; ?> "></i>On
        </div>
        <div class="description">
        </div>
    </div>
    <?
}
?>

Create new role:
<br/>
<div class="textfield gss_setting"  id="rolename">
    <span class="title"><?php echo $this->__f("Name"); ?></span>
    <input type="textfield" gs_model='userrolemodel' gs_model_attr='rolename' value="">
    <div class="description">
        Name of the new role.
    </div>
</div>
