<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<center>
<div class="application-configuration-top-menu">
    <span class="button"><ins class="entry" action="removeapplication">
        <?php echo $this->__("Delete selected application")." ( ".$_POST['core']['appname']." )"; ?>
    </ins></span>
</div>
</center>
<hr>
<!--
<div class="settings">
    <div id="toggle_application_sticky" class="entry">
        <div class="configobject" appid="<?php echo $this->getConfiguration()->id; ?>"></div>
        <div class="title inline"><?php echo $this->__("Set application sticky");?></div>
        <div class="inline"><div class="onoff off"></div></div>    
        <div class="extrainfo">
            <?php
            echo $this->__("By turning on this feature you will set this application to be visible on all pages.");
            ?>
        </div>
    </div>
</div> -->