<div class='gs_rowpicker_box'>
    <div class='gs_row_modeselection'>
        <div rowmode='cells' class='gs_row_mode_select gs_row_mode_select_active'><? echo $this->__f("Cells"); ?></div>
        <div rowmode='carousel' class='gs_row_mode_select'><? echo $this->__f("Carousel"); ?></div>
        <div rowmode='tabs' class='gs_row_mode_select'><? echo $this->__f("Tabs"); ?></div>
    </div>
   
    <div class='gs_row_selection_box' type='tabs' style='display: none'>
        <div class='gs_select_row_mode_information'>
            <?
            echo $this->__f("You can use tabmode if you wish to add content in multiple tabs, adding this will allow you to create as many tabs as you wish and add a variouse of content to it.");
            ?>
        </div>
        <div class='gs_row_box_to_select' rowtype="carouselmode" style='width: 780px; line-height: 50px; text-align: center; background: linear-gradient(to bottom, #22cb10, #10a600); border: solid 1px;'>
            <div class=''>
                <? 
                echo $this->__f("Insert as tab mode");
                ?>
            </div>
        </div>
    </div>
    
    <div class='gs_row_selection_box' type='carousel' style='display: none'>
        <div class='gs_select_row_mode_information'>
            <?
            echo $this->__f("Carousel mode is great if you wish to add sliding content, this means that you can add multiple slider and let your customers make a choice on what they want to view. Great for banners and advertisment.");
            ?>
        </div>
        <div class='gs_row_box_to_select' rowtype="tabmode" style='width: 780px; line-height: 50px; text-align: center; background: linear-gradient(to bottom, #22cb10, #10a600); border: solid 1px;'>
            <div class=''>
                <? 
                echo $this->__f("Insert as carousel mode");
                ?>
            </div>
        </div>
    </div>
    
    <div class='gs_row_selection_box' type='cells'>
        <div class='gs_select_row_mode_information'>
            <?
            echo $this->__f("Rows are created by multiple cells, you can combine them in any way you like. To do more options you need to learn the advanced mode. Click on the layout you wish to use.");
            ?>
        </div>
        <div class='gs_row_box_to_select' rowtype="cells_1">
            <div class='gs_illustration_row gs_illustration_row_1'>
                <div class='gs_illustration_column gs_illustration_column_size_1'><div class='gs_illustratration_inner'></div></div>
            </div>
        </div>
        <div class='gs_row_box_to_select' rowtype="cells_2">
            <div class='gs_illustration_row gs_illustration_row_1'>
                <div class='gs_illustration_column gs_illustration_column_size_2'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column gs_illustration_column_size_2'><div class='gs_illustratration_inner'></div></div>
            </div>
        </div>
        <div class='gs_row_box_to_select' rowtype="cells_3">
            <div class='gs_illustration_row gs_illustration_row_1'>
                <div class='gs_illustration_column gs_illustration_column_size_3'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column gs_illustration_column_size_3'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column gs_illustration_column_size_3'><div class='gs_illustratration_inner'></div></div>
            </div>
        </div>
        <div class='gs_row_box_to_select' rowtype="cells_4">
            <div class='gs_illustration_row gs_illustration_row_1'>
                <div class='gs_illustration_column gs_illustration_column_size_4'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column gs_illustration_column_size_4'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column gs_illustration_column_size_4'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column gs_illustration_column_size_4'><div class='gs_illustratration_inner'></div></div>
            </div>
        </div>
        
        
        <div class='gs_row_box_to_select' rowtype="cells_5">
            <div class='gs_illustration_row gs_illustration_row_1'>
                <div class='gs_illustration_column gs_illustration_column_size_4'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column ' style='width: 129px;'><div class='gs_illustratration_inner'></div></div>
            </div>
        </div>
        <div class='gs_row_box_to_select' rowtype="cells_6">
            <div class='gs_illustration_row gs_illustration_row_1'>
                <div class='gs_illustration_column gs_illustration_column_size_4'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column gs_illustration_column_size_4'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column ' style='width: 86px;'><div class='gs_illustratration_inner'></div></div>
            </div>
        </div>
        
        <div class='gs_row_box_to_select' rowtype="cells_7">
            <div class='gs_illustration_row gs_illustration_row_1'>
                <div class='gs_illustration_column ' style='width: 86px;'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column gs_illustration_column_size_4'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column gs_illustration_column_size_4'><div class='gs_illustratration_inner'></div></div>
            </div>
        </div>
        
        <div class='gs_row_box_to_select' rowtype="cells_8">
            <div class='gs_illustration_row gs_illustration_row_1'>
                <div class='gs_illustration_column ' style='width: 129px;'><div class='gs_illustratration_inner'></div></div>
                <div class='gs_illustration_column gs_illustration_column_size_4'><div class='gs_illustratration_inner'></div></div>
                
            </div>
        </div>
    </div>
    
</div>