<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

<div class="successdialoagbacksettings">
    <i class="fa fa-check"></i>
    <span class="message"></span>
</div>
<div class='gss_topmenu'>
    <div class='gss_settings_inner'>
        <div class='gss_topmenu-button gss_backtopage'><i class='fa fa-arrow-left'></i> Til min side</div>
        <div id="dashboardbutton" class='gss_topmenu-button' gss_goto_app="b81bfb16-8066-4bea-a3c6-c155fa7119f8"><i class='fa fa-tachometer'></i> Dashboard</div>
        <div class='gss_topmenu-button' gss_goto_app="d755efca-9e02-4e88-92c2-37a3413f3f41"><i class='fa fa-gears'></i> Instillinger</div>
        <div class='gss_topmenu-button' gss_goto_app="ba6f5e74-87c7-4825-9606-f2d3c93d292f"><i class='fa fa-users'></i> Users </div>
        <div class='gss_topmenu-button active' gss_goto_app='f1fc4af3-656e-4294-a268-40d2a82d0aa1'><i class='fa fa-cube'></i> Applikasjoner</div>
        <div class='gss_topmenu-button'><i class='fa fa-lightbulb-o'></i> GetShop admin</div>    
    </div>
</div>

<div class='gss_settings_inner apparea'>
<?
    $settingsFactory = IocContainer::getSettingsFactorySingleton();
    $settingsFactory->renderContent();
?>
</div>

<script>
	getshop.Settings.reload();
</script>