<?
/* @var $factory \Factory */

//$activatedApps = $factory->getApi()->getStoreApplicationPool()->getApplications();
?>
<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

<div class="successdialoagbacksettings">
    <i class="fa fa-check"></i>
    <span class="message"></span>
</div>
<div class='gss_topmenu'>
    <? 
        $settingsFactory = IocContainer::getSettingsFactorySingleton();
        $settingsFactory->renderTopMenu();
    ?>
</div>


<div class='gss_settings_inner apparea'>
<?
    $settingsFactory = IocContainer::getSettingsFactorySingleton();
    $settingsFactory->renderContent();
?>
</div>

<div id='gss_loading_icon'><i class='fa fa-cog fa-spin'></i> Loading...</div>

<script>
	getshop.Settings.reload();
</script>