<div class="gs_templatehaeaderfunctionspadding"></div>
<div class="gs_templatehaeaderfunctions">
    
    <div class="selectcolors">
        <div class='select_arrow_down_indicator'>
            <i class='fa fa-arrow-down'></i>
        </div>
        <div class='select_color_header'>
            <i class="fa fa-paint-brush"></i><? echo $this->__f("Change colors"); ?>
        </div>
        <div class='colors_menu'>
            <?
            $colors = $this->getStoreConfiguration()->colorTemplates;
            foreach ($colors as $key => $value) {
                echo "<a href='/index.php?colorselection=$key'><div class='color_select'>".$this->__f($key)."</div></a>";
            }
            ?>
            <div class='color_select close'><? echo $this->__f("Close"); ?></div>
        </div>
    </div>
    
    <div class="gs_start_template_text_form">
        <input id='gs_start_store_email' type="textfield" placeholder="<? echo $this->__w("Your email"); ?>"/>
    </div>
    
    <div class="gs_start_template_button">
        <? 
            echo $this->__f("Start editing this site"); 
        ?>    
    </div>
</div>