<div class="gs_templatehaeaderfunctions">
    <div class="gs_start_template_text_form">
        <input id='gs_start_store_name' type="textfield" placeholder="<? echo $this->__w("Your name"); ?>"/>
        <input id='gs_start_store_email' type="textfield" placeholder="<? echo $this->__w("Your email"); ?>"/>
        <input id='gs_start_store_phonenumber' type="textfield" placeholder="<? echo $this->__w("Your phonenumber"); ?>"/>
        <input id='gs_start_store_shopname' type="textfield" placeholder="<? echo $this->__w("Name of your shop"); ?>"/>
        <input id='gs_start_store_password1' type="password" placeholder="<? echo $this->__w("Password"); ?>"/>
        <input id='gs_start_store_password2' type="password" placeholder="<? echo $this->__w("Repeat password"); ?>"/>
    </div>
    
    <div class="gs_start_template_button">
        <? 
            echo $this->__f("Start a new webshop with this template"); 
        ?>    
    </div>
</div>