<?
/* @var $this \ns_1674e92d_feb5_4a78_9dba_1e5ba05a6a31\AccountingDownload */
?>

<div class="askForTransformation">
    <i class="fa fa-info"></i> 
    <br/> You dont have any files here yet, press the button below to transfer all files from the old system.
    <br/><div class="shop_button" gsclick="transferFromOldSystem"><? echo $this->__f("Transfer all files from the old system"); ?></div>
</div>
