<?
/* @var $this \ns_1674e92d_feb5_4a78_9dba_1e5ba05a6a31\AccountingDownload */

$logEntries = $this->getApi()->getGetShopAccountingManager()->getLogEntries();

if ($logEntries) {
    echo "<h2> Errors accurd: </h2>";
    foreach ($logEntries as $entry) {
        echo "<div>$entry</div>";
    }
} 


$data = array();
$toLoop = isset($_SESSION['AccountingDownload_filesCreated']) ? $_SESSION['AccountingDownload_filesCreated'] : array();
if (!is_array($toLoop)) {
    $toLoop = array();
}
foreach ($toLoop as $fileId) {
   $data[] = $this->getApi()->getGetShopAccountingManager()->getOrderFile($fileId);
}

if (count($data)) {
    echo "<h2>Files created now</h2>";
    $this->printFileTable($data);
}
?>

<br/>
<div>
    <div gsclick="clearSession" class="shop_button"><? echo $this->__f("Finished"); ?></div>
</div>