<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<style>
    .row {
        border-bottom: solid 1px #DDD;
        font-size: 16px;
        padding: 5px;
    }
    
    .row .col {
        display: inline-block;
        vertical-align: top;
        width: 200px;
    }
    
    .row .col.col_start {
        width: 80px;
    }
    
    .row .col.col_description {
        width: calc(100% - 480px);
    }
    
    
    .monthoverview {
        margin-bottom: 50px;
        margin-left: 20px;
        margin-right: 20px;
    }
    
    .monthheader {
        background-color: #EFEFEF;
        font-size: 18px;
        text-align: center;
        padding: 5px;
        line-height: 30px;
    }
    
    .summary {
        background-color: #EEE;
        padding: 20px;
        font-size: 20px;
        margin-top: 50px;
    }
    
    .heading2,
    .heading {
        padding: 20px;
        font-size: 20px;
    }
    
    .heading2 {
        page-break-before:always;
    }
    
    .attachment {
        margin-bottom: 50px;
        margin-left: 20px;
        margin-right: 20px;
    }
    
</style>    

<?php
setlocale(LC_TIME, 'nb_NO');

$factory = $this->getFactory();
$file = $factory->getApi()->getGetShopAccountingManager()->getOrderFile($_POST['data']['fileid']);
$eiendeler = array();

$GLOBALS['overAllDebit'] = 0;
$GLOBALS['overAllCredit'] = 0;


$gjeld = array();
$grouped = array();
foreach ($file->accountingTransactionLines as $line) {
    $monthDate = date('01.m.Y', strtotime($line->start));
    
    if ((int)$line->accountNumber < 2000) {
        $eiendeler[$line->accountNumber][] = $line;
        continue;
    }
    
    if ((int)$line->accountNumber > 2000 && (int)$line->accountNumber < 3000) {
        $gjeld[$line->accountNumber][] = $line;
        continue;
    }
    
    if (!isset($grouped[$line->accountNumber])) {
        $grouped[$line->accountNumber] = array();
    }
    
    $grouped[$line->accountNumber][] = $line;
}

function sortFunction($a, $b) {
    return ((int)$a) > ((int)$b);
}

function sortFunctionDate($a, $b) {
    return ((int)strtotime($a)) > ((int)strtotime($b));
}

$start = date('d.m.Y', strtotime($file->startDate));
$end = date('d.m.Y', strtotime($file->endDate));
?>

<div class="heading">
    <h2>Regnskapsbilag</h2>
    Opprettet dato: <? echo date('d/m-Y H:i:s', strtotime($file->rowCreatedDate)); ?>
    <br/> Eiendelsperiode: <? echo $start. " - ".$end; ?>
</div>

<?

function printLines($monthLines, $sumtext, $api) {
    $totalDebit=0;
    $totalCredit=0;
    
    uksort($monthLines, "sortFunction");

    echo "<div class='row total'>";
       echo "<div class='col col_start'>Konto</div>";
       echo "<div class='col col_description'></div>";
       echo "<div class='col col_debit'>Debit</div>";
       echo "<div class='col col_credit'>Credit</div>";
   echo "</div>";
   
    foreach ($monthLines as $accountNumber => $lines) {
        $subDebit = 0;
        $subCredit = 0;

        foreach ($lines as $line) {
            $subDebit += $line->debit;
            $subCredit += $line->credit;
        }

        if (!$subDebit && !$subCredit)
            continue;

        $desc = $line->description ? $line->description : "";
        if (!$desc) {
            $accountingDetail = $api->getProductManager()->getAccountingDetail($accountNumber);
            $desc = $accountingDetail ? $accountingDetail->description : "";
        }
        
        echo "<div class='row'>";
            echo "<div class='col col_start'>$accountNumber</div>";
            echo "<div class='col col_description'>$desc</div>";
            echo "<div class='col col_debit'>".$subDebit."</div>";
            echo "<div class='col col_credit'>".$subCredit."</div>";
        echo "</div>";

        $totalDebit += $subDebit;
        $totalCredit += $subCredit;
    }

    echo "<div class='row total'>";
       echo "<div class='col col_start'></div>";
       echo "<div class='col col_description'><b>$sumtext</b></div>";
       echo "<div class='col col_debit'><b>".$totalDebit."</b></div>";
       echo "<div class='col col_credit'><b>".$totalCredit."</b></div>";
   echo "</div>";
   
   $GLOBALS['overAllDebit'] += $totalDebit;
   $GLOBALS['overAllCredit'] += $totalCredit;
}


echo "<div class='monthoverview'>";
    echo "<div class='monthHeader'> Eiendeler $start - $end</div>";
    printLines($eiendeler, "Sum eiendeler", $factory->getApi());
echo "</div>";


echo "<div class='monthoverview'>";
    echo "<div class='monthHeader'> Egenkapital og gjeld - $start - $end</div>";
    printLines($gjeld, "Sum egenkapital og gjeld", $factory->getApi());
echo "</div>";


echo "<div class='monthoverview'>";
    echo "<div class='monthHeader'> Salgs og driftsinntekter - $start - $end</div>";
    printLines($grouped, "Sum Salgs og driftsinntekter", $factory->getApi());
echo "</div>";

$overAllDebit = round($GLOBALS['overAllDebit'], 2);
$overAllCredit = round($GLOBALS['overAllCredit'],2);


echo "<div class='monthoverview'>";
    echo "<div class='row total'>";
       echo "<div class='col col_start'></div>";
       echo "<div class='col col_description'>Sum</div>";
       echo "<div class='col col_debit'>".$overAllDebit."</div>";
       echo "<div class='col col_credit'>".$overAllCredit."</div>";
   echo "</div>";
echo "</div>";

$distinctOrders = array();

foreach ($file->accountingTransactionOutOfScope as $transaction) {
    foreach ($transaction->orderIds as $orderId) {
        $distinctOrders[] = $orderId;
    }
}

$distinctOrders = array_unique($distinctOrders);

if (count($distinctOrders)) {
    ?>
    <div class="heading2">
        <h2>Bilag 2900 - Forskudd fra kunder </h2>
    </div>

    <div class='attachment'>
        <?
        echo "<div class='row total'>";
            echo "<div class='col col_start'>Orderid</div>";
            echo "<div class='col col_description'></div>";
            echo "<div class='col col_debit'></div>";
            echo "<div class='col col_credit'>Amount</div>";
        echo "</div>";
        
        $total = 0;
        foreach ($distinctOrders as $orderId) {
            /* @var $order \core_ordermanager_data_Order */
            $order = $factory->getApi()->getOrderManager()->getOrder($orderId);
            $totalForOrder = $factory->getApi()->getOrderManager()->getTotalForOrderById($order->id);
            
            echo "<div class='row total'>";
                echo "<div class='col col_start'>$order->incrementOrderId</div>";
                echo "<div class='col col_description'></div>";
                echo "<div class='col col_debit'></div>";
                echo "<div class='col col_credit'>$totalForOrder</div>";
            echo "</div>";
            
            $total += $totalForOrder;
        }
        
        echo "<div class='row total'>";
            echo "<div class='col col_start'><b>Sum</b></div>";
            echo "<div class='col col_description'></div>";
            echo "<div class='col col_debit'></div>";
            echo "<div class='col col_credit'><b>$total</b></div>";
        echo "</div>";
        ?>
    </div>
    <?
}



$distinctOrders = array();

foreach ($file->accountingTransactionLines as $line) {
    if ((int)$line->accountNumber == 1499) {
        foreach ($line->orderIds as $orderId) {
            $distinctOrders[] = $orderId;
            
        }
//        die("TEST");
    }
}
//die("TEST2");

$distinctOrders = array_unique($distinctOrders);

if (count($distinctOrders)) {
    ?>
    <div class="heading2">
        <h2>Bilag 1499 - Kundefordringer GetShop. </h2>
    </div>

    <div class='attachment'>
        <?
        echo "<div class='row total'>";
            echo "<div class='col col_start'>Orderid</div>";
            echo "<div class='col col_description'>Name</div>";
            echo "<div class='col col_debit'></div>";
            echo "<div class='col col_credit'>Amount</div>";
        echo "</div>";
        
        $total = 0;
        foreach ($distinctOrders as $orderId) {
            /* @var $order \core_ordermanager_data_Order */
            $order = $factory->getApi()->getOrderManager()->getOrder($orderId);
            $totalForOrder = $factory->getApi()->getOrderManager()->getTotalForOrderById($order->id);
            $user = $factory->getApi()->getUserManager()->getUserById($order->userId);
            $name = $user ? $user->fullName : "N/A";
            
            echo "<div class='row total'>";
                echo "<div class='col col_start'>$order->incrementOrderId</div>";
                echo "<div class='col col_description'>$name</div>";
                echo "<div class='col col_debit'></div>";
                echo "<div class='col col_credit'>$totalForOrder</div>";
            echo "</div>";
            
            $total += $totalForOrder;
        }
        
        echo "<div class='row total'>";
            echo "<div class='col col_start'><b>Sum</b></div>";
            echo "<div class='col col_description'></div>";
            echo "<div class='col col_debit'></div>";
            echo "<div class='col col_credit'><b>$total</b></div>";
        echo "</div>";
        ?>
    </div>
    <?
}
?>