<?
/* @var $this ns_419c41e7_1dd5_4c96_b820_c1b77a2fffa3\TicketList */
$ticket = $this->getCurrentTicket();
?>
<div class="ticketview">
    <div class="dialog">
        <?
        foreach ($ticket->events as $event) {
            $user = $this->getApi()->getUserManager()->getUserById($event->updatedByUserId);
            ?>
            <div class="event">
                <div class="createdBy"> By: <? echo @$user->fullName; ?> ( <? echo $event->date; ?> ) / <? echo $event->eventType; ?></div>
                <div class="content">
                    <?
                    echo nl2br($event->content);
                    ?>
                </div>
            </div>
            <?
        }
        ?>
        
        <div gstype="form" method="addEvent">
            <input type="hidden" gsname="id" value="<? echo $ticket->id; ?>"/>
            <textarea gsname="content" class="gsnice"></textarea>
            <br/>
            <br/> What is this? 
            <br/><select class="gsniceselect1" gsname="eventType">
                <option value="OUTGOING_EMAIL"><? echo $this->__f("Outgoing Email"); ?> </option>
                <option value="INCOMING_OTHER"><? echo $this->__f("Incoming Other"); ?> </option>
                <option value="INCOMING_PHONE"><? echo $this->__f("Incoming Phone"); ?> </option>
                <option value="INCOMING_SMS"><? echo $this->__f("Incoming SMS"); ?> </option>
                <option value="INCOMING_EMAIL"><? echo $this->__f("Incoming email"); ?> </option>
            </select>
            <br/>
            <br/> New state? 
            <br/>
            <?
            $this->renderStates($ticket);
            ?>
            <br/>
            <br/>
            <div class="shop_button" gstype="submit"><? echo $this->__f("Save"); ?></div>
        </div>
    </div>
    
    <div class="ticket_actions" gstype="form" method="saveTicket">
        <input type="hidden" gsname="id" value="<? echo $ticket->id; ?>"/>
        
        Title:
        <br/><input gsname="title" gsname="title" class="gsniceinput1" value="<? echo $ticket->title; ?>"/>
        <br/>
        <br/>State:
        <br/><? $this->renderStates($ticket); ?>
        <br/>
        <br/>Type:
        <br/><select gsname="type" class="gsniceselect1">
            <option value="SUPPORT" <? echo $ticket->type == "SUPPORT" ? "selected='true'" : "" ?>><? echo $this->__f("Support"); ?></option>
            <option value="BUG" <? echo $ticket->type == "BUG" ? "selected='true'" : "" ?>><? echo $this->__f("Bug"); ?></option>
            <option value="FEATURE" <? echo $ticket->type == "FEATURE" ? "selected='true'" : "" ?>><? echo $this->__f("Feature"); ?></option>
        </select>
        <br/><br/>Time spent:
        <br/> <input gsname="timespent" class="gsniceinput1" value="<? echo  $ticket->timeSpent; ?>" />
        <br/><br/>Time to invoice:
        <br/> <input gsname="timeInvoice" class="gsniceinput1" value="<? echo  $ticket->timeInvoice; ?>" />
        <br/><br/>External id (ex, roomid):
        <br/> <input gsname="externalid" class="gsniceinput1" value="<? echo  $ticket->externalId; ?>" />
        <br/><br/>Created date:
        <br/> <input gsname="createddate" class="gsniceinput1" value="<? echo  date('d.m.Y', strtotime($ticket->rowCreatedDate));  ?>" />
        <?
        if ($ticket->currentState == "COMPLETED") {
        ?>
        <br/><br/>Completed date:
        <br/> <input gsname="completeddate" class="gsniceinput1" value="<? echo  date('d.m.Y', strtotime($ticket->dateCompleted));  ?>" />
        <?
        }
        ?>
        <br/>
        <br/><div class="shop_button" gstype="submit"><? echo $this->__f("Save ticket"); ?></div>
        - <div class="shop_button" gsclick="deleteTicket" gs_confirm="Are you sure?" id="<? echo $ticket->id; ?>"><? echo $this->__f("Delete ticket"); ?></div>
        <?
        if ($ticket->transferredToAccounting) {
            ?>
            <br/>
            <br/>
            <div class="shop_button" gsclick="unsetTransferred" gs_confirm="Are you sure want to unset this?" id="<? echo $ticket->id; ?>"><? echo $this->__f("Unset transferred to accounting"); ?></div>
            <?
        }
        ?>
    </div>
    
</div>