<?
/* @var $this ns_916aff23_c765_4b8c_9d8f_8783f1b7bd16\SrsTables */

$rooms = $this->getRooms();
$selectedRoom = $this->getSelectedRoom();
$roomName = $selectedRoom ? $selectedRoom->name : "N/A";

?>

<div>
    <?
    echo $this->__f("Selected room").": ".$roomName;
    ?>
    
    <div>
        <?
        foreach ($rooms as $room) {
            echo "<div gsclick='selectRoom' roomid='$room->id'>".$room->name."</div>";
        }
        ?>
    </div>
</div>

<?
if ($selectedRoom) { 
    foreach ($selectedRoom->tables as $table) {
        $data = $this->getApi()->getResturantManager()->getCurrentTableData($table->id);
        $state = count($data->cartItems) ? "inuse" : "available";
?>
    <a href="/index.php?page=resturanttable&tableid=<? echo $table->id; ?>">
        <div class="resturanttable <? echo $state; ?>">
            <div class="tablename"><? echo $table->name; ?></div>
        </div>
    </a>
<?
    }
}
?>