<?
/* @var $this ns_916aff23_c765_4b8c_9d8f_8783f1b7bd16\SrsTables */

$rooms = $this->getRooms();
$selectedRoom = $this->getSelectedRoom();
$roomName = $selectedRoom ? $selectedRoom->name : "N/A";
$selectedDate = time();

$currentDate = date('d.m.Y', $selectedDate);

if (isset($_SESSION['SrsTables_currentdate'])) {
    $currentDate = date('d.m.Y', strtotime($_SESSION['SrsTables_currentdate']));
}
?>
<div class='toprow' gstype='form' method='setCurrentDate'>
    
    <div class='changeroom'>
        <?
        echo $this->__f("Selected room").": ".$roomName;
        ?>

        <div class='showselectroom gs_shop_small_icon'><i class='fa fa-edit'></i> <? echo $this->__f("Change room"); ?></div>
        <div class='selectroom'>
            <?
            foreach ($rooms as $room) {
                echo "<div class='roomtoselect' gsclick='selectRoom' roomid='$room->id'>".$room->name."</div>";
            }
            ?>
        </div>
    </div>
    
    Change date <input id='day' gsname='date' class='gsniceinput1' value='<? echo $currentDate; ?>'/> <div class='gs_shop_small_icon' gstype='submit'><i class='fa fa-arrow-right'></i></div>
</div>

<div class='tables'>

    <?
    if ($selectedRoom) { 
        foreach ($selectedRoom->tables as $table) {
            $javaData = $this->convertToJavaDate(strtotime($currentDate));
            $storedData = $this->getApi()->getResturantManager()->getTableDayData($javaData, $table->id);
            $data = $this->getApi()->getResturantManager()->getCurrentTableData($table->id);
            $state = count($data->cartItems) ? "inuse" : "available";

            $events = array();
            
            foreach ($storedData->events as $event) {
                $entry = new ns_e8fedc44_b227_400b_8f4d_52d52e58ecfe\DayViewCalendarEntry();
                $entry->start = strtotime($event->start);
                $entry->end = strtotime($event->end);
                $entry->type = "reservation";
                $entry->roomId = $table->id;
                $entry->shortDisplayTitle = $event->referenceName;
                $entry->link = "/?page=restaurant&reservertionid=".$event->reservationId."&tableid=".$table->id;
                $events[] = $entry;
            }

            $app = new \ns_e8fedc44_b227_400b_8f4d_52d52e58ecfe\DayViewCalendar();
            $app->setNumberOfRooms(1);
            $app->setCalendarId($table->id);
            $app->setEvents($events);
            $app->setColumnWidth(80);
            
            $dt = new DateTime($currentDate);
            $dt->sub(new DateInterval('P1D'));
            $app->setDateRange($currentDate, $currentDate);

            echo "<div class='tableday'>";
            echo "<h2>".$table->name."</h2>";
            $app->render();
            echo "</div>";
        }
    }
    ?>
    
</div>

<div class='createnewtablesession' gstype='form' method='createNewTableSession'>
    <span>Name (optional): </span><input class='gsniceinput1' gsname='name'>
    <br/>
    <br/><span>Table</span>
    <select class='gsniceselect1' gsname='tableid'>
        <?
        foreach ($selectedRoom->tables as $table) {
            echo "<option value='$table->id'>$table->name</option>";
        }
        ?>
    </select>
    <br/>
    <br/><div class='subheader'><b>Start:</b></div>
    <span> </span><input class='gsniceinput1' gsname='start'/>
    <br/>
    <br/><div class='subheader'><b>End:</b></div>
    <span> </span><input class='gsniceinput1' gsname="end"/>
    <br/> 
    <br/> <div class='shop_button' gstype='submit'><? echo $this->__f("Create"); ?></div> <div class='shop_button closecreation'><? echo $this->__f("Close"); ?></div>
</div>

<script>
    $('.SrsTables #day').datepicker({ dateFormat: "dd.mm.yy"});
    $('.SrsTables [gsname="start"]').datetimepicker({ dateFormat: "dd.mm.yy"});
    $('.SrsTables [gsname="end"]').datetimepicker({ dateFormat: "dd.mm.yy"});
</script>