<?php
echo "<div class='unpayedappheader'>";
echo $this->__w("You have expired applications that requires payment.") . "<bR>";
echo $this->__w("To continue using this feature, you will need to pay, or remove the application.") . "<bR>";
echo "</div>";

$unpayed = $this->getApi()->getAppManager()->getUnpayedSubscription();

if(sizeof($unpayed) == 0) {
    ?>
<script>
    thundashop.common.hideInformationBox();
    thundashop.framework.reprintPage();
</script>
    
    <?
}

echo "<table width='970px' class='unpayedapptable'>";
echo "<tr>";
echo "<th width='100'>" . $this->__w("Count") . "</th>";
echo "<th>" . $this->__w("Name of the application") . "</th>";
echo "<th>" . $this->__w("Expire date") . "</th>";
echo "<th>" . $this->__w("Price") . "</th>";
echo "</tr>";

$price = 0;
foreach ($unpayed as $data) {
    /* @var $data core_appmanager_data_ApplicationSubscription */
    echo "<tr>";
    echo "<td>" . $data->numberOfInstancesAdded . "</td>";
    echo "<td>" . $data->app->appName . "</td>";
    echo "<td>" . $data->to_date . "</td>";
    echo "<td width='150'>\$ " . $data->app->price ." / ".$this->__f("year"). "</td>";
    echo "<td width='50' method='removeAllInstances' gstype='clicksubmit' style='cursor: pointer' gsname='id' gsvalue='".$data->appSettingsId."' output='informationbox'>".$this->__w("Remove")."</td>";
    echo "</tr>";
    $price += $data->app->price;
}
echo "<tr>";
echo "<td></td>";
echo "<td>Total</td>";
echo "<td></td>";
echo "<td>\$ $price,-</td>";
echo "</table>";


$notifyAddress = "http://". $_SERVER["SERVER_NAME"]."/callback.php?orderid=applications&app=c7736539-4523-4691-8453-a6aa1e784fc1";

/* @var $factory Factory */
$factory = $this->getFactory();
$instances = $factory->getApplicationPool()->getApplicationsInstancesByNamespace("ns_c7736539_4523_4691_8453_a6aa1e784fc1");
if($factory->getConfigurationFlag("devMode") == "true") {
    $url = "https://www.sandbox.paypal.com/cgi-bin/webscr";
    $address = "payment@getshop.com";
} else {
    $url = "https://www.paypal.com/cgi-bin/webscr";
    $address = "post@getshop.com";
}
?>

<form action='<? echo $url; ?>' method='POST' id='paypalform'>
    <input type="hidden" name="notify_url" value="<? echo $notifyAddress; ?>">
    <INPUT TYPE="hidden" NAME="return" value="<? echo "http://". $_SERVER["SERVER_NAME"]; ?>">

    <input type="hidden" name="cmd" value="_cart"> 
    <input type="hidden" name="upload" value="1">
    <input type="hidden" name="currency_code" value="USD">
    <input type="hidden" name="business" value="<? echo $address;?>">

    <input type="hidden" name="item_name_1" value="Payment for applications">
    <input type="hidden" name="amount_1" value="<? echo $price; ?>">
</form>

<div style="text-align:right; padding-right:10px;border-top: solid 1px #BBBBBB;">
    <div class="button-large payforapplications" onclick="$('#paypalform').submit();">
        <div class="rightglare"></div>
        <div class="filler" ></div>
        <ins><? echo $this->__w("Checkout"); ?></ins>
    </div>
</div>