<?
$application = $app;
$id = $application->configuration->appSettingsId;
$class = ($i++ % 2) ? 'odd' : 'even';
$positions = $application->getAvailablePositions();
$direct = (isset($application->singleton) && $positions == "") ? "direct" : '';

echo "<div applicationname='$id' appPositions='$positions' class='inline $class application $direct' id='$id'>";
    echo "<div class='image inline'><img src='" . ApplicationHelper::getApplicationImage($application)."'></div>";
    echo "<div class='rightwrapper inline'>";
        echo "<div class='name'>" . $application->getName() . "</div>";
        echo "<div class='description'>" . $application->getDescription() . "</div>";
    echo "</div>";
    
    if (\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
        if ($this->getFactory()->getApplicationPool()->isSingletonAndAddedBySettingsId($id)) {
            echo "<div class='allreadyaddedbutton'>" . $this->__("already_added", "common") . "</div>";
        } elseif ($this->getFactory()->getApplicationPool()->isPageSingletonAndAdded($id)) {
            echo "<div class='allreadyaddedbutton'>" . $this->__("only_one_per_page", "common") . "</div>";
        } else {
            echo "<div class='addappbutton'>" . $this->__("add_app_free", 'applicationmanager') . "</div>";
        }
    } else {
        echo "<div class='watchtrailerbutton'>".$this->__("Free", 'applicationmanager')."</div>";
    }
echo "</div>";
?>