<div>
    
    <div class='deepfreezeinformation'>
        <? echo $this->__f("What is deepfreeze? Well, if you activate deepfreeze you basically put all options on hold, all changes made after deepfreezeing will be purged each hour."); ?>
        <br>
        <hr>
        <br>
        If you activate deepfreezing, you need to enter a password of your choice. If you are deactivating it you should enter the password you used when you activated it.
        <br><br>
        Deepfreeze password: <input id='deepfreezepassword' type='text'/>
        <br>
        <br>
        <div class="button savedeepfreeze needreload"><div class="rightglare"></div><div class="filler"></div><ins>Activate / Deactivate</ins></div>
    </div>
    
</div>