<?php

namespace ns_96de3d91_41f2_4236_a469_cd1015b233fc;

/*  @var $this Contact */

$email = $this->getEmail();
$address = $this->getAddress();
$postalCode = $this->getPostalCode();
$phone = $this->getPhone();
$header = $this->getHeader();


$fields = $this->getFields();

if (isset($_POST['allfiedsrequired'])) {
    echo $this->__w("I am sorry, but all fields are required before sending a message.");
} else {
    if (isset($_POST['event']) && $_POST['event'] == "sendMessage") {
        echo "<div class='message_sent'>";
        echo $this->__f("Your message has been sent!");
        echo "</div>";
    }
}
?>

<div class='medium_contact_form contact_form'>
    <? 
    foreach($fields as $field => $text) {
        echo "<input type='textfield' class='max_length tobecleared contactfield' id='$field' placeholder='$text'></input>";
    }
    ?>
    <textarea class="max_length subject_textarea tobecleared content"  placeholder="<?php echo $this->getBodyTitle(); ?>"></textarea>
    <span class="send_email shop_button" id="send_email"><?php echo $this->__w("Send message"); ?></span>
</div>

<div class='normal_contact_form contact_form'>
    <table style="width:100%;">
        
        <?
        foreach($fields as $field => $text) {
        ?> 
        <tr>
            <td>
            <?php echo $text; ?>
            </td>
            <td>
                <input type="textfield" class="max_length tobecleared contactfield" id="<? echo $field; ?>"></input>
            </td>
        </tr>
        <? } ?>

        <tr>
            <td colspan="2">
                <?php echo $this->getBodyTitle(); ?>
            </td>
        </tr>

        <tr>
            <td colspan="2"><textarea class="max_length subject_textarea tobecleared contactfield content"><?php echo isset($_GET['prefilled']) ? $_GET['prefilled'] : ""; ?></textarea></td>
        </tr>

        <tr>
            <td colspan="2">
                <div class='shop_button send_email' id="send_email">
                    <div class="button_text_content"><?php echo $this->__w("Send message"); ?> </div>
                </div>
            </td>
        </tr>
    </table>
</div>
