<?
/* @var $this \ns_01b8bd0c_0375_42fa_a44e_d177485db704\ApacLocks */
$lock = $this->getApi()->getGetShopLockSystemManager()->getLock($_POST['data']['serverid'], $_POST['data']['lockid']);
$_SESSION['ns_3e89173c_42e2_493f_97bb_2261c0418bfe_editlock_lockid']  = $lock->id;
$this->setLock($lock);
?>
<div class='lock'>
<?
    if (isset($lock->zwaveDeviceId)) {
        $this->includefile('zwavelock');
    }

    ?>

    <div style='margin-top: 40px;'>
        Serverid: <? echo $this->getServer()->id; ?>
        <br/>Lockid: <? echo $lock->id; ?>
    </div>
    <div gstype='form' method='saveName'>
        <input type='hidden' gsname='lockid' value='<? echo $lock->id; ?>'/>
        <input type='hidden' gsname='serverid' value='<? echo $this->getServer()->id; ?>'/>
        Lock Name: <input gsname='name' class='gsniceinput1' value='<? echo $lock->name; ?>'/>
        <br/> <div gstype='submit'>Save</div>
    </div>
        
    <div class='slots'>
        <h2>Codes and slots</h2>
        <?

        foreach ($lock->userSlots as $slot) {
            /* @var $slot \core_getshoplocksystem_UserSlot */
            $this->setSlot($slot);
            $this->includefile('slotview');
        }
        ?>
    </div>
</div>