
<div class="gss_settings_header">
    <i class="fa fa-dollar"></i>

    <div class="gss_settings_header_description">
        <div class="gss_settings_header_title"> <? echo $this->__f("Form item configuration"); ?></div>

        <div class="gss_settings_header_description_inner">
            <? echo $this->getDescription(); ?>
        </div>
    </div>	
</div>


<div class='gss_settings_content'>
    <div class="textfield gss_setting" id="secret">
        <span class="title"><?php echo $this->__("Secret"); ?></span>
        <input type="textfield" gs_model="taxmodel" gs_model_attr="secret"  value="<? echo $this->getSecret(); ?>">
        <div class="description"><?php echo $this->__f("Please provide the google recapcha secret key if you want to us google recaptcha."); ?></div>
    </div>
    
    <div class="textfield gss_setting" id="sitekey">
        <span class="title"><?php echo $this->__f("Site key"); ?></span>
        <input type="textfield" gs_model="taxmodel" gs_model_attr="sitekey"  value="<? echo $this->getCaptchaKey(); ?>">
        <div class="description"><?php echo $this->__("Please provide the google recapcha site key if you want to us google recaptcha."); ?></div>
    </div>
    
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveConfig" gss_model="taxmodel" gss_success_message="<? echo $this->__f("Saves successfully"); ?>"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>
</div>