
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="https://unpkg.com/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"></script>



<div class="contentrow firstrow"> 
    <div class="row_inner">
        
        <div>
            <?php
            ContentManager::render("top_content_privat");
            ?>
        </div>
        <div style='max-width: 1000px; margin: 0 auto;' id='bookingprocess'></div>
    </div>
</div>



<div class="contentrow row_2" style='padding-top: 50px; padding-bottom: 50px;'> 
    <div class="row_inner">
        <div class="col col_1 col_size_2 mobilebox">
            <?php
                ContentManager::render("row2_naring_col_1");
            ?>
            <img src='/ba10/images/frontColage.png' style='width:100%;'>
        </div>
        <div class="col col_2 col_size_2 mobilebox" style='color:#9a9999; padding-right:0px;'>
            <?php
                ContentManager::render("row2_naring_col_2");
            ?>
            <br>
            <a href='/?page=contactus'><div class='utleienaeringbtn'><?php ContentManager::render("kontaktossknapp"); ?></div></a>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>


<?php

$floors = array();
$floors[2] = "2. Leiligheter";
$floors[3] = "3 Leiligheter";
$floors[4] = "4. Leiligheter";
$floors[5] = "5. Leiligheter";

if(!isset($_GET['plan'])) {
    $_GET['plan'] = "2";
}


if(!isset($_GET['plan'])) {
    $_GET['plan'] = "1";
}

echo "<div style='text-align:center;'>";
echo "<div style='text-align:center;color:#585b9e; font-size: 36px; padding-bottom: 20px;padding-top: 50px;'>Velg en etasje for mer informasjon</div>";
foreach($floors as $i => $name) {
    $chosenfloor = "";
    if(isset($_GET['plan']) && $_GET['plan'] == $i) {
        $chosenfloor = "chosenfloor";
    }
    echo "<a class='choosefloorbtn $chosenfloor' href='/?page=leiligheter&plan=$i'>$name</a>";
}
echo "</div>";


if(isset($_GET['plan'])) {
    echo "<bR>";
    echo "<bR>";
    echo "<div style='text-align:center;color:#585b9e; font-size: 36px; padding-bottom: 20px;padding-top: 50px;'>Velg en seksjon for beskrivelse og bilder av seksjonen</div>";
    echo '<div id="roomcategorygallery">';
    CategoryGallery::render("leiligheterplan".$_GET['plan']);
    echo '</div>';
    echo "<script>";
    echo "$(function() { $(window).scrollTop(localStorage.getItem('lastscroll')); });";
    echo "</script>";
}
?>

<script>
    $(window).on('scroll', function() {
        localStorage.setItem('lastscroll', $(this).scrollTop());
    });
</script>