<?
/* @var $this ns_fe5ceb57_c8ea_4032_a5e2_04b8b86dc38c\C3OtherCosts */
$otherCostObject = null;

if ($this->getModalVariable("otherid")) {
    $otherCostObject = $this->getApi()->getC3Manager()->getOtherCost($this->getModalVariable("otherid"));
}

$from = $otherCostObject ? date('d.m.Y', strtotime($otherCostObject->from)) : "";
$to = $otherCostObject ? date('d.m.Y', strtotime($otherCostObject->to)) : "";
$cost = $otherCostObject ? $otherCostObject->cost : "";
$type = $otherCostObject ? $otherCostObject->type : "";
$comment = $otherCostObject ? $otherCostObject->comment : "";

$projectId = $this->getModalVariable("projectid");
$project = $this->getApi()->getC3Manager()->getProject($projectId);
$projectPeriodeToShow = $project->currentProjectPeriode;
?>

<div>
    <div class="periodeopen">
        <?
        echo "<b>Prosjekt:</b> ".$project->name;
        echo "<br/><b>Åpen periode:</b> ".date('d.m.Y', strtotime($projectPeriodeToShow->from))." - ".date('d.m.Y', strtotime($projectPeriodeToShow->to));
        ?>
    </div>

    <h1>Andre kostnader</h1>
    <div gstype='form' method='saveCost'>
        Periode:
        <div class='gserrorfield' id='errorMessage'></div>
        <br/><input class='gsniceinput1' type='text' gsname='from' id='from' value='<? echo $from; ?>'/> - <input class='gsniceinput1' type='text' gsname='to' id='to' value='<? echo $to; ?>'/> 
        <br/>
        <br/>Type:
        <div class='gserrorfield' id='errorMessageComment'></div>
        <br/><input type='text' gsname='comment' class='gsniceinput1' style="width: 100%; box-sizing: border-box;" value='<? echo $comment; ?>' placeholder='Eksempel: Reise, Innkjøp etc'/>
        <br/>
        <br/> Kostnad (Kr):
        <div class='gserrorfield' id='errorMessageTimer'></div>
        <br/><input type='text' gsname='cost' class='gsniceinput1'  style="width: 100%; box-sizing: border-box;" value="<? echo $cost; ?>"/>
        
        
        <?
        if ($this->getApi()->getC3Manager()->allowedNfrOtherCostCurrentUser()) {
            ?>
            <br/>
            <input type='checkbox' gsname='nfr'/> Er dette forskningsrådets midler?
            <br/>
            <?
        }
        
        
        ?>
        <br/> 
        
        <?
        if ($otherCostObject) {
            echo "<div class='shop_button' gsclick='deleteCost' costId='$otherCostObject->id'> Slett oppføring </div>";
        }
        ?>
        <div class='shop_button' gstype='submit'> Lagre </div>
    </div>

    <script>
        $('#from').datepicker({dateFormat: "dd.mm.yy"});
        $('#to').datepicker({dateFormat: "dd.mm.yy"});
    </script>
</div>