<?php
$fleet = $this->getApi()->getMecaManager()->getFleetPageId($this->getPage()->getId());
$followup = $fleet->followup;
$isAdmin = \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isEditor() || \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator();
if($followup == "true"){
    $followuptext = "manuell";
    $directtext = "<span class='directfollowup'>Automatisk oppfølging</span>";
    $manualtext = "<span class='manualfollowup active'>Manuell oppfølging</span>";
    $sliderinput = "<input type='checkbox' value='<? echo $followup; ?>' gsname='fleetFollowup' id='followupslider' checked/>";
}else{
    $followuptext = "direkte";
    $directtext = "<span class='directfollowup active'>Automatisk oppfølging</span>";
    $manualtext = "<span class='manualfollowup'>Manuell oppfølging</span>";
    $sliderinput = "<input type='checkbox' value='<? echo $followup; ?>' gsname='fleetFollowup' id='followupslider'/>";
}
?>
<div class='title'><? echo $fleet->name ."<br><span style='font-size:16px;font-style:italic;'>En ".$followuptext." oppfølgingsflåte.</span>";?></div>
<?
if ($isAdmin) {
?>
<div class="editmecafleetform" gstype="form" method="updateFleet">
    <div class="leftFleetbox">
        <div id="createfleetfollowup">
            <?echo $directtext?>
            <div class="gsniceslider1">
                <? echo $sliderinput;?>
                <label for="followupslider"></label>
            </div>
            <?echo $manualtext; ?>
        </div>
        
        <div class="fleetfield">Navn på flåteavtalen <input class="gsniceinput1" gsname="fleetName" placeholder="Navn på flåteavtalen" value="<? echo $fleet->name; ?>"/></div>
        <div class="fleetfield">Kontaktperson <input class="gsniceinput1" gsname="contactName" placeholder="Kontaktperson" value="<? echo $fleet->contactName; ?>"/></div>
        <div class="fleetfield">E-post <input class="gsniceinput1" gsname="contactEmail" placeholder="E-post" value="<? echo $fleet->contactEmail; ?>"/></div>
        <div class="fleetfield">Telefon <input class="gsniceinput1" gsname="contactPhone" placeholder="Telefon" value="<? echo $fleet->contactPhone; ?>"/></div><br>
    </div>
    <div class="rightFleetbox">
        <div class="fleetfield">Rabatt<input class="gsniceinput1" gsname="discount" placeholder="Rabatt" value="<? echo $fleet->discount; ?>"/></div>
        <div class="fleetfield">Leiebil<input class="gsniceinput1" gsname="rentalcar" placeholder="Leiebil" value="<? echo $fleet->rentalcar; ?>"/></div>
        <div class="fleetarea">&nbsp;&nbsp;Annet <textarea class="gsniceinput1" gsname="contactOther" value="<? echo $fleet->contactOther; ?>"><? echo $fleet->contactOther; ?></textarea></div>
    <?
    if (isset($_POST['data']['fleetName']) && !$_POST['data']['fleetName']) {
//        ?>
        <div class="warning"><i class="fa fa-warning"></i>Navnet kan ikke være blankt.</div><br/>
        <?
    }
    ?>
    </div>
    
    <?
    if (!$followup) {
        $text_none = "Det er kun hovedforspørselen som blir sendt ut.";
        $text_daily = "Sender først 1 reminder dagen etter hovedforspørselen, deretter en til 2 dager etter hovedforspørselen.";
        $text_weekly = "Sender først 1 reminder en uke etter hovedforspørselen, deretter en til etter 2 uker etter hovedforspørselen.";
    ?>
    <div class='followupoptions'>
        <b>Oppfølgingsfrekvens på kilometerstand forespørsel:</b>
        <div style="font-size: 13px; padding-top: 10px; padding-right: 100px;"> Systemet gjør forspørsler 1 gang i måneden etter kilometerstand. Ved å stille inn under så setter du hvor ofte systemet skal "mase" på brukerene. Dersom du ønsker at systemet aldri skal spørre etter kilometerstanden velger du "Manuell oppfølging"</div>
        <br/>
        <input type='radio' name='frequency' gsname='frequency_none'   <? echo $fleet->naggingInterval == "frequency_none" ? 'checked="true"' : ""; ?> /> Ingen    <i title='<? echo $text_none; ?>' class='fa fa-info-circle'></i>
        <input type='radio' name='frequency' gsname='frequency_daily'  <? echo $fleet->naggingInterval == "frequency_daily" ? 'checked="true"' : ""; ?> /> Daglig   <i title="<? echo $text_daily; ?>" class='fa fa-info-circle'></i>
        <input type='radio' name='frequency' gsname='frequency_weekly' <? echo $fleet->naggingInterval == "frequency_weekly" ? 'checked="true"' : ""; ?> /> Ukentlig <i title="<? echo $text_weekly; ?>" class='fa fa-info-circle'></i>
    </div>
    <?
    }
    ?>
    <div class='gserrorfield' style='text-align: right !important; width: 100% !important; margin-top: -20px; padding-right: 20px;' id='errorMessage'></div>
   <span class="saveform shop_button" gstype="submit"> Lagre </span>
</div>
<?
}
?>
