package com.thundashop.core.cartmanager;

import com.thundashop.core.cartmanager.data.Cart;
import com.thundashop.core.common.ErrorException;
import com.thundashop.core.common.GetShopApi;
import java.util.List;

/**
 * The cartmanager is a manager helping you keep track of your shopping cart.<br>
 * All orders are first being pushed to this shopping cart, then you are able to create an order based on the cart object.<br>
 * The cart object is being processed by the OrderManager.<br>
 */
@GetShopApi
public interface ICartManager {
    /**
     * Add a new product to the cart.
     * @param productId The product id generated by the productmanager.
     * @param int Number instances of the product ordered.
     * @return
     * @throws ErrorException 
     */
    public Cart addProduct(String productId, int count, List<String> variations) throws ErrorException;
    
    /**
     * Change the number of instances added to the product.
     * @param productId The product id generated by the productmanager.
     * @param count The number of instances (has to be a positive integer)
     * @return
     * @throws ErrorException 
     */
    public Cart updateProductCount(String productId, int count, List<String> variations) throws ErrorException;
    
    /**
     * Remove an added product from the cart.
     * @param productId The product id generated by the productmanager, that has been added to the cart.
     * @return
     * @throws ErrorException 
     */
    public Cart removeProduct(String productId, List<String> variations) throws ErrorException;
    
    /**
     * Fetch the current cart.
     * @return
     * @throws ErrorException 
     */
    public Cart getCart() throws ErrorException;
    
    /**
     * Returns the current total amount
     * note, this does not include shipping.
     * 
     * @return
     * @throws ErrorException 
     */
    public Double getCartTotalAmount() throws ErrorException;
    
    /**
     * Clear the current shopping cart.
     */
    public void clear() throws ErrorException;
}
