<?php
/* @var $this ns_27e174dc_b08c_4bf7_8179_9ea8379c91da\PmsEventCalendar */
$categories = $this->getCategories();
$time = "";
$day = "";
if(isset($_GET['time']) && $_GET['time']) {
    $time = $_GET['time'];
    $day = date("Y-m-d", $time);
}
$_SESSION['timeusedpmsmanager'] = @$_GET['time'];
$_SESSION['pmseventid'] = $_GET['eventid'];
 
$event = $this->getApi()->getPmsEventManager()->getEntry($this->getSelectedName(), $_GET['eventid'], $day);

//$imgDisplayer = $this->getImageDisplayer($event->id);
//$fileid = $imgDisplayer->getImageId();
//if($fileid && !$event->imageId) {
//    $event->imageId = $fileid;
//    $this->getApi()->getPmsEventManager()->saveEntry($this->getSelectedName(), $event, $day);
//}

$starttime = $event->dateRanges[0]->start;
if(!$event->starttime) {
    $event->starttime = date("H:i", strtotime($starttime));
}
$imgSrc = "";
if($event->imageId) {
    $imgSrc = "/displayImage.php?id=".$event->imageId . "&width=250";
}
$logoSrc = "";
if($event->logoId) {
    $logoSrc = "/displayImage.php?id=".$event->logoId . "&width=250";
}
?>
<?php if(sizeof($event->dateRanges) > 1) { ?>
<center>
    <form action="" method="GET" id="changedates">
        <input type="hidden" name="page" value="<?php echo $_GET['page']; ?>">
        <input type="hidden" name="eventid" value="<?php echo $_GET['eventid']; ?>">
        <select name="time" onchange="$('#changedates').submit();" style="width: 480px;">
            <option value="">Endre for alle datoer</option>
            <?php
            foreach($event->dateRanges as $range) {
                $selected = "";
                if($time == strtotime($range->start)) {
                    $selected = "SELECTED";
                }
                echo "<option value='".strtotime($range->start)."' $selected>" . date("d.m.Y", strtotime($range->start)). "</option>";
            }
            ?>
        </select>
    </form>
</center>
<?php } ?>

<div class='eventconfig'>
    <div gstype='form' method='updateEventFields' class='eventeditform'>
        <br><br>
        <input type='hidden' value='<?echo $_GET['eventid']; ?>' gsname='eventid'>
        <input type='hidden' value='<?echo $time; ?>' gsname='time'>
        <label>
            <span class='text'><?echo $this->__w("Title"); ?></span>
            <input type='text' gsname='title' value='<?php echo $event->title; ?>' maxlength="30">
        </label>
        <label>
            <span class='text'><?echo $this->__w("Short description"); ?></span>
            <textarea type='text' style='height: 50px;' gsname='shortdesc' maxlength="100"><?php echo $event->shortdesc; ?></textarea>
        </label>
        <label>
            <span class='text'>Starttidspunkt for arrangementet</span>
            <input type='text' gsname='starttime' value='<?php echo $event->starttime; ?>'>
        </label>
        <label>
            <span class='text'>Kontaktinformasjon</span>
            <input type='text' gsname='contact' value='<?php echo $event->contact; ?>'>
        </label>
        <!--Picture & logo upload display table-->
        <table id="entryconfigurationTable">
            <tr>
                <td id="entryconfigurationImage">
                    <form id="uploadImage" action="" method="post" enctype="multipart/form-data">
                        <input type="file" name="file" id="file"/>
                        <label for="file" id="labelFile">Last opp bilde</label>
                        <div id="imagePreview"><img id="previewing" src="<?php echo $imgSrc; ?>" /></div>  
                    </form>
                </td>
                <td id="entryconfigurationLogo">
                    <form id="uploadLogo" action="" method="post" enctype="multipart/form-data">
                        <input type="file" name="logo" id="logo"/>
                        <label for="logo" id="labelLogo">Last opp logo</label>
                        <div id="logoPreview"><img id="previewingLogo" src="<?php echo $logoSrc; ?>"/></div>
                    </form>
                </td>
            </tr>
        </table>
        <div id="message"></div>
        
        <br>
        <br>
        <label>
            <span class='text'><?echo $this->__w("Select a category"); ?></span>
            <select gsname='category'>
            <?php
            foreach($categories as $cat => $val) {
                $selected = "";
                if($event->category == $val) {
                    $selected = "SELECTED";
                }
                echo "<option value='$val' $selected>$val</option>";
            }
            ?>
            </select>
        </label>
        <hr>
        <label>
            <span class='text'>Mer utfyllende beskrivelse</span>
            <textarea type='text' style='height: 200px;' gsname='description'><?php echo $event->description; ?></textarea>
        </label>
    </div>
    <?php
    if(sizeof($event->lenker) > 0) {
        echo "Lenker som er lagt til:<br>";
        $i = 0;
        foreach($event->lenker as $link) {
            echo "<div style='margin-bottom: 5px;'>";
            echo "<span gstype='form' method='removeLink'>";
            echo "<input type='hidden' value='".$_GET['eventid']."' gsname='eventid'>";
            echo "<input type='hidden' value='".$time."' gsname='time'>";
            echo "<input type='hidden' value='$i' gsname='index'>";
            echo "<i gstype='submit' method='removeLink' gsname='index' gsvalue='$i' class='fa fa-trash-o'></i></span> <a href='".$link->link."'>".$link->name . " (" . $link->link . ")". "</a>";
            echo "</div>";
            $i++;
        }
        echo "<br>";
    }
    ?>
    
    <div gstype='form' method='addlink'>
        <input type='hidden' value='<?php echo $time; ?>' gsname='time'>
        <input type='hidden' value='<?echo $_GET['eventid']; ?>' gsname='eventid'>
        <label style='width:40%;float:left;'>
            <span class='text'>Lenke</span>
            <input type='text' gsname='link'>
        </label>
        <label style='width:40%;float:left;'>
            <span class='text'>Navn på lenken</span>
            <input type='text' gsname='name'>
        </label>
        <label style='width:20%;float:left;'>
            <span class='text'>&nbsp;</span>
            <input type='button' value='Legg til' gstype='submit'>
        </label>
    </div>
    <div style='clear:both;'></div>
    <div style='text-align: right;'>
    </div>
</div>
<div style='text-align:right; padding-right: 200px;'>
    <?php echo "<a href='?page=".$this->getPage()->javapage->id."'>"; ?>
        <span class='pmsbutton'>Ferdig å editere, gå til listen</span>
    </a>
    <?php 
    $shortId = explode("-", $event->id); 
    echo "<a href='scripts/generatepmssimpleeventpdf.php?engine=furuset"."&readevent=" . $shortId[0] . "&time=$time' target='_blank' >"; ?>
        <span class='pmsbutton'>Last ned PDF</span>
    </a>
    <?php echo "<a href='?page=".$this->getPage()->javapage->id."&readevent=".$shortId[0]."&time=$time'>"; ?>
        <span class='pmsbutton'>Ferdig å editere, gå til eventet</span>
    </a>
    
</div>


