<?php
/* @var $this \ns_27e174dc_b08c_4bf7_8179_9ea8379c91da\PmsEventCalendar */
$day = "";
$time = false;
if(isset($_GET['time'])) {
    $time = $_GET['time'];
    $day = date("Y-m-d", $time);
}

$event = $this->getApi()->getPmsEventManager()->getEntryShort($this->getSelectedName(), $_GET['readevent'], $day);
$edit = "";
if($this->isEditorMode()) {
    $edit = "<a href='?page=".$this->getPage()->javapage->id."&eventid=".$event->id."'><i class='fa fa-edit'></i></a> ";
}

$ranges = array();
foreach($event->dateRanges as $range) {
    $ranges[date("d.m.Y", strtotime($range->start))] = "true";
}
$dates = array();
$date = null;
foreach($ranges as $idx => $range) {
    $dates[] = $idx;
    if($idx > time()) {
        $date = $idx;
        break;
    }
}


if(!$event->starttime) {
    $event->starttime = date("H:i", strtotime($event->dateRanges[0]->start));
}

echo "<h1>" .$edit . $event->title . "</h1>";
echo "<div style='font-size:12px;'>";
if(!$time) {
    $time = strtotime($idx);
}


echo $this->__w(date("l", $time)) . " " . (int)date("d", $time) . ". " . strtolower($this->__w(date("F", $time))) . " klokken " . $event->starttime;
echo "</div>";
echo "<div >" . $event->arrangedBy;
if($event->arrangedBy) {
    echo ", ";
}
echo $event->location . "</div><br>";

echo nl2br($event->shortdesc) . "<br><br>";

$imgDisplayer = $this->getImageDisplayer($event->id);
$fileid = $imgDisplayer->getImageId();
if($fileid && !$event->imageId) {
    $event->imageId = $fileid;
    $this->getApi()->getPmsEventManager()->saveEntry($this->getSelectedName(), $event, $day);
}

if($event->imageId) {
    echo "<img id='imgtodisplay' src='/displayImage.php?id=" . $event->imageId . "' style='max-width: 600px; max-height: 600px;'>";
}

echo $event->description;
echo "<div style='clear:both;'></div>";
if(sizeof($event->lenker) > 0) {
    echo "<h2>Lenker</h2>";
    foreach($event->lenker as $link) {
        echo "<a style='cursor:pointer;' onclick=\"window.open('".$link->link."')\">" . $link->name . "</a>";
    }
}

?>

<script>
    window.parent.parent.scrollTo(0,0); 
</script>
