<?php
/* @var $this \ns_27e174dc_b08c_4bf7_8179_9ea8379c91da\PmsEventCalendar */

$event = $this->getApi()->getPmsEventManager()->getEntryShort($this->getSelectedName(), $_GET['readevent']);
$edit = "";
if($this->isEditorMode()) {
    $edit = "<a href='?page=".$this->getPage()->javapage->id."&eventid=".$event->id."'><i class='fa fa-edit'></i></a> ";
}

echo "<h1>" .$edit . $event->title . "</h1>";
echo "<div class='image'>";
$imgDisplayer = $this->getImageDisplayer($event->id);
$imgDisplayer->displayImage();
echo "</div>";
echo nl2br($event->shortdesc) . "<br>";
echo "<div style='clear:both;'></div>";
echo "<h2>Mer utfyllende beskrivelse</h2>";
echo $event->description;
if(sizeof($event->lenker) > 0) {
    echo "<h2>Lenker</h2>";
    foreach($event->lenker as $link) {
        echo "<a style='cursor:pointer;' onclick=\"window.open('".$link->link."')\">" . $link->name . "</a>";
    }
}

$ranges = array();
foreach($event->dateRanges as $range) {
    $ranges[date("d.m.Y", strtotime($range->start))] = "true";
}

$dates = array();
foreach($ranges as $idx => $range) {
    $dates[] = $idx;
}

echo "<div style='font-size:12px;color:#828282; margin-top: 20px;'>";
if(sizeof($dates) > 1) {
    echo "Eventet gjentas på følgende datoer:<br>";
} else {
    echo "Dato for eventet:<br>";
}
echo join(", ", $dates);
echo "</div>";

ob_start();
$imgDisplayer->displayAdditionalFiles();
$data = ob_get_contents();
ob_end_clean();
if(stristr($data, "<a")) {
    echo "<div class='filelist'>";
    echo "<h2>Flere filer og tillegg</h2>";
    echo $data;
    echo "</div>";
}
?>