<div class="footer_row"> 
    <div class='footer_inner'>
        <div class="col col1">
            <?php
            ContentManager::render("footer_product_text2", true);

            $pages = $router->getAllPages();
            echo "<ul>";
            foreach ($pages as $page) {
                if ($page->subpageof == "products") {
                    $className = get_class($page);
                    echo "<a href='?page=$className'><li>".$page->getMenuName()."</li></a>";
                }
            }
            echo "</ul>";
            ?>
        </div>
        
        <div class="col col2">
            <?php
                ContentManager::render("footer_text2", true);
            ?>
        </div>
        
        <div class="col col3">
            <?php
                ContentManager::render("footer_text3", true);
            ?>
        </div>
    </div>
    <div style='text-align: center; background-color: #888;'>
        <a href='https://www.visa.no' target='_blank'><img style='margin: 20px;' src='gkroen/images/visa.png'/></a>
        <a href='https://www.visa.no' target='_blank'><img style='margin: 20px;' src='gkroen/images/verifiedbyvisa.png'/></a>
        <a href='https://www.mastercard.no' target='_blank'><img style='margin: 20px;' src='gkroen/images/mastercard.png'/></a>
        <a href='https://www.mastercard.no' target='_blank'><img style='margin: 20px;' src='gkroen/images/mastercardsecure.png'/></a>
        
        <link href="https://aw.restaurantguru.com/aw.css" rel="stylesheet"/>
        <div style='display: inline-block; margin-bottom: 10px;' id="rg-aw" onclick="if(event.target.nodeName.toLowerCase() != 'a') {window.open(this.querySelector('.rg-rl').href);return 0;}"> <a href="https://restaurantguru.com/G-Kroen-Norway" title="G-Kroen at Restaurant Guru" target="_blank" class="rg-rl">G-Kroen</a> <img alt="G-Kroen at Restaurant Guru" src="https://pw.restaurantguru.com/b/45225202_ms5ens.png"/> <a href="https://restaurantguru.com" class="rg-sl" target="_blank">Restaurant Guru 2019</a></div>
    </div>
</div>