<?
/* @var $this ns_91192b8c_19da_465e_89ee_763fcf5d97c3\AuksjonenButton */
$url = $this->getUrl();
$randomid = uniqid();
?>
<span class='auksjon_<? echo $randomid; ?>'>
    <div style='font-size:16px;padding-top: 10px;'>
        Neste bud <span class='minimumPossibleBid'></span> <span class='gotoauction' onclick='window.open("https://www.auksjonen.no/auksjon/artistdugnad/<? echo $url; ?>")'>Gi bud <i class='fa fa-arrow-right'></i></span>
    </div>
    <div class='ending'>Avslutter<br> <span class='endTime'></span></div>
</span>
<script>
    $.get("scripts/getpage.php?url=<? echo urlencode("https://www.auksjonen.no/api/auction/".$url); ?>", function(data) {
        $('.auksjon_<? echo $randomid; ?> .minimumPossibleBid').html(data.minimumPossibleBid + " kr");
        var time = data.endTime / 1000;
        var d = new Date(0); // The 0 there is the key, which sets the date to the epoch
        d.setUTCSeconds(time);
       
        var dformat =  ("00" + (d.getMonth() + 1)).slice(-2) + "." + 
            ("00" + d.getDate()).slice(-2) + "." + 
            d.getFullYear() + " " + 
            ("00" + d.getHours()).slice(-2) + ":" + 
            ("00" + d.getMinutes()).slice(-2) + ":" + 
            ("00" + d.getSeconds()).slice(-2)
        
            $('.auksjon_<? echo $randomid; ?> .endTime').html(dformat);
    });
</script>