<div class="textfield gss_setting"  id="systemnumber">
    <span class="title"><?php echo $this->__f("Systemnummer"); ?></span>
    <input type="textfield" gs_model='systemmodel' gs_model_attr='systemnname' value="" placeholder="xxx">
    <div class="description">
        <?php echo $this->__("Name of the person that owns this new account."); ?>
    </div>
</div>

<div class="textfield gss_setting"  id="name">
    <span class="title"><?php echo $this->__f("Navn"); ?></span>
    <input type="textfield" gs_model='systemmodel' gs_model_attr='name' value="" placeholder="John Doe">
    <div class="description">
        <?php echo $this->__("Email address."); ?>
    </div>
</div>

<div class="textfield gss_setting"  id="email">
    <span class="title"><?php echo $this->__f("Mail address"); ?></span>
    <input type="textfield" gs_model='systemmodel' gs_model_attr='email' value="" placeholder="email@address.org">
    <div class="description">
        <?php echo $this->__("Email address."); ?>
    </div>
</div>

<div class="textfield gss_setting"  id="phone">
    <span class="title"><?php echo $this->__f("Phone number"); ?></span>
    <input type="textfield" gs_model='systemmodel' gs_model_attr='phonenumber' value="" placeholder='12345678'>
    <div class="description">
        <?php echo $this->__("The cell phone number to the owner of this account."); ?>
    </div>
</div>

<div class='gss_button_area'>
    <input type="hidden" gs_model='systemmodel' gs_model_attr='systemid' value="">
    <div class="gss_button" gss_fragment="editsystem" gss_view="gs_system_work_area" gss_method="createSystem" gss_model="systemmodel"><i class='fa fa-plus'></i><?php echo $this->__("Opprett system"); ?></div>
</div>
