<div class="gs_system_overview">
    <div class="gss_button" gss_fragment='systemlist' gss_view='gs_system_work_area'><i class="fa fa-list"></i><? echo $this->__f("All systems"); ?></div>
    <br/><div class="gss_button" gss_fragment='newsystem' gss_view='gs_system_work_area'><i class="fa fa-plus"></i><? echo $this->__f("New system"); ?></div>
</div>

<div class="gs_system_work_area">
    <?
    $this->includefile('systemlist');
    ?>
</div>