<div class="isnotactive" style='margin-top: 20px;'>
    <div class="kaipal infobox">
        <div class="image happy"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("First category has been created."); ?></div>
            <div class="text">
                <?
                echo "<div>" . $this->__f("Congratulation! You have created your first category / type. Now you can continue to add more categories or connect a room to the category below.") . "</div>";
                ?>
            </div>
        </div>
    </div>
</div>