<?php 
/* @var $this ns_a22747ef_10b1_4f63_bef8_41c02193edd8\PmsRoomConfiguration */
$types = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);
$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedMultilevelDomainName());
?>
<br>
<br>
<br>
<h2>Rooms <span class='openitemsorting' style='cursor:pointer;'>(open sorting)</span></h2>
<span gstype='form' method='createRoom'>
    <select gsname='type' class="gsniceselect1" style="height:34px;">
        <?php
        foreach($types as $type) {
            $selected = "";
            if(isset($_POST['data']['type']) && $_POST['data']['type'] == $type->id) {
                $selected = "SELECTED";
            }
            echo "<option value='".$type->id."' $selected>" . $type->name . "</option>";
        }
        
        $selected = "";
        if(isset($_POST['data']['type']) && $_POST['data']['type'] == "gsconference") {
            $selected = "SELECTED";
        }
        echo "<option value='gsconference' $selected>Conference room</option>";
        ?>
    </select>
    <input type="txt" class="gsniceinput1" placeholder='101' gsname='name'>
    <span gstype='submit' class='shop_button'>Create a new room</span>
</span>


<?php
$rooms = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedMultilevelDomainName());
$types = $this->indexList($types);

if (!is_array($rooms)) {
    $rooms = array();
}

$rows = array();
foreach($rooms as $room) {
    $additional = $this->getApi()->getPmsManager()->getAdditionalInfo($this->getSelectedMultilevelDomainName(), $room->id);
    $additional->name = $room->bookingItemName;
    if($room->bookingItemTypeId == "gsconference") {
        $additional->typeName = "Conference room";
    } else {
        $additional->typeName = $types[$room->bookingItemTypeId]->name;
    }
    $additional->description = $room->description;
    $rows[] = $additional;
            
}
$attributes = array(
    array('id', 'gs_hidden', 'itemId'),
    array('description', 'gs_hidden', 'description'),
    array('hideFromCleaningProgram', 'gs_hidden', 'hideFromCleaningProgram'),
    array('date', 'Date', null, 'formatDate'),
    array('bookingItemName', 'Name', 'name', 'formatName'),
    array('squareMetres', 'Square<br>metres', 'squareMetres', null),
    array('squareMetres', 'Last<br>cleaned', 'lastCleaned', 'formatCleanedDate'),
    array('squareMetres', 'Type', 'typeName', null),
);

$table = new \GetShopModuleTable($this, 'PmsRoomConfiguration', 'loadRoomConfiguration', null, $attributes);
$table->setData($rows);
echo "<div class='roomconfigtable'>";
$table->render();
echo "</div>";
?>


<style>
    .roomconfigtable .GetShopModuleTable .col { width: 10%; text-align: center; }
    .roomconfigtable .GetShopModuleTable .col.col_5 { width: 50%; text-align: left; }
    .roomconfigtable .GetShopModuleTable .col.col_8 { text-align: left; }
</style>