<?php
/* @var $this ns_a22747ef_10b1_4f63_bef8_41c02193edd8\PmsRoomConfiguration */
$id = $_POST['data']['id'];
$type = $this->getApi()->getBookingEngine()->getBookingItemType($this->getSelectedMultilevelDomainName(), $id);
$additional = $this->getApi()->getPmsManager()->getAdditionalTypeInformationById($this->getSelectedMultilevelDomainName(), $id);
$notVisible = $type->visibleForBooking ? "" : "SELECTED";
$images = $additional->images;
$accessories = (array)$this->getApi()->getPmsManager()->getAccesories($this->getSelectedMultilevelDomainName());
$languages = $this->getFactory()->getLanguageCodes();
$languages[] = $this->getFactory()->getCurrentLanguage();
$readable = $this->getFactory()->getLanguageReadable();
$product = $this->getApi()->getProductManager()->getProduct($type->productId);
$taxes = $this->getApi()->getProductManager()->getTaxes();

?>
<div gstype='form' method='saveTypeSettings'>
    <input type='hidden' gsname='id' value='<?php echo $id; ?>'>
    <?php
    foreach($languages as $lang) {
        $text = $type->name;
        if(isset($type->translationStrings->{$lang."_name"})) {
            $text = json_decode($type->translationStrings->{$lang."_name"});
        }
        echo "<b>" . $readable[$lang] . " title</b><br>";
    ?>
        <input type='txt' value='<?php echo $text; ?>' class='gsniceinput1' style='width:100%;box-sizing:border-box;' gsname='<?php echo $lang; ?>_name'><br><br>
    <?php
    }
    
    foreach($languages as $lang) {
        $text = $type->description;
        if(isset($type->translationStrings->{$lang."_description"})) {
            $text = json_decode($type->translationStrings->{$lang."_description"});
        }
        ?>
        <b>Description <?php echo $readable[$lang]; ?>:</b><br>
        <textarea style='width: 100%; height: 90px;border:solid 1px #dcdcdc;box-sizing:border-box; padding: 10px;' gsname='<?php echo $lang; ?>_description'><?php echo $text; ?></textarea>
        <?php
    }?>
            
    <table width='100%'>
        <tr>
            <th>Guests</th>
            <th>Children</th>
            <th>Adults</th>
            <th>Beds</th>
            <th>Beds for children</th>
            <th>Max beds</th>
            <th>Max beds for children</th>
            <th>Visible for booking</th>
            <th>Tax group</th>
        </tr>
        <tr style='text-align:center;'>
            <td><input type='txt' class='gsniceinput1' style='width: 40px;text-align:center;' value='<?php echo $type->size; ?>' gsname='size'></td>
            <td><input type='txt' class='gsniceinput1' style='width: 40px;text-align:center;' value='<?php echo $additional->numberOfChildren; ?>' gsname='numberOfChildren'></td>
            <td><input type='txt' class='gsniceinput1' style='width: 40px;text-align:center;' value='<?php echo $additional->numberOfAdults; ?>' gsname='numberOfAdults'></td>
            <td><input type='txt' class='gsniceinput1' style='width: 40px;text-align:center;' value='<?php echo $additional->defaultNumberOfBeds; ?>' gsname='defaultNumberOfBeds'></td>
            <td><input type='txt' class='gsniceinput1' style='width: 40px;text-align:center;' value='<?php echo $additional->defaultNumberOfChildBeds; ?>' gsname='defaultNumberOfChildBeds'></td>
            <td><input type='txt' class='gsniceinput1' style='width: 40px;text-align:center;' value='<?php echo $additional->maxNumberOfBeds; ?>' gsname='maxNumberOfBeds'></td>
            <td><input type='txt' class='gsniceinput1' style='width: 40px;text-align:center;' value='<?php echo $additional->maxNumberOfChildBeds; ?>' gsname='maxNumberOfChildBeds'></td>
            <td><select class='gsniceselect1' gsname='visibleForBooking'><option value='yes'>Yes</option><option value='no' <?php echo $notVisible; ?>>No</option></select></td>
            <td>
                <select class="gsniceselect1" gsname="tax">
                    <?php
                    foreach($taxes as $tax) {
                        $sel = "";
                        if($product->taxgroup == $tax->groupNumber) {
                            $sel = "SELECTED";
                        }
                        echo "<option value='" . $tax->groupNumber . "' $sel>" . $tax->taxRate . "</option>";
                    }
                    ?>
                </select>
            </td>
        </tr>
    </table>
    <b>Accesories: <span class='createnewaccessory' style='cursor:pointer;'>(create new)</span></b><br>
    <table width='100%'>
        <tr>
            <?php
            $i = 1;
            foreach ($accessories as $accessory) {
                $checked = in_array($accessory->id, $additional->accessories) ? "CHECKED" : "";
                $icon = "briefcase";
                if($accessory->icon) {
                    $icon = $accessory->icon;
                }
                echo "<td><input type='checkbox' gsname='accessory_" . $accessory->id . "' $checked> <i class='fa fa-$icon changeicon' data-id='".$accessory->id."'></i> " . $accessory->title . "</td>";
                if ($i % 8 == 0) {
                    echo "</tr><tr>";
                }
                $i++;
            }
            ?>
        </tr>
    </table>
    <div style="margin-top: 50px; padding-top: 50px; border-top: solid 1px #dcdcdc;">
        <b>Type: </b>
        <select gsname='systemCategory' class="gsniceselect1">
            <? $selected = $type->systemCategory == 0 ? "selected='true'" : "";?>
            <option value="0" <? echo $selected; ?>>Room</option>
            <? $selected = $type->systemCategory == 3 ? "selected='true'" : "";?>
            <option value="3" <? echo $selected; ?>>Camping.</option>
        </select>
    </div>
    <div style='text-align:right;padding-top: 20px;'>
        <input type='button' style='padding:9px; width: 200px;' gstype='submit' value='Save'>
    </div>
</div>

<br><br>
<span class='shop_button' style='float:right; background-color:red;' value='<?php echo $type->id; ?>' gs_confirm="Are you sure you want to do this?" gsclick="deletetype">Delete this category</span>
<b>Images: <input type='button' class='uploadTypeImage' value='Upload an image' typeid='<?php echo $type->id; ?>'></b><br>
<div class='imagearea'>
    <?php
        $_POST['data']['typeId'] = $type->id;
        $this->printImagesForType();
    ?>
</div>
