<?php 
/* @var $this ns_a22747ef_10b1_4f63_bef8_41c02193edd8\PmsRoomConfiguration */
$types = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);
?>
<h2>Room types <span class='opentypesorting' style='cursor:pointer;'>(open sorting)</span> - <span class='opentypesortingavailability' style='cursor:pointer;'>(sort categories for availability)</span></h2>
<span gstype='form'>
    <input type="txt" class="gsniceinput1" placeholder='Double room' gsname='name'>
    <span class='shop_button createType' gstype='submit'>Create a new room type</span>
</span>
<?php
    $taxes = $this->getApi()->getProductManager()->getTaxes();
    $unsorted = array();
    $sortList = array();
    
    if (!is_array($types)) {
        $types = array();
    }
    
    foreach($types as $type) {
        if($type->order == 0) {
            $unsorted[] = $type;
        } else {
            $sortList[$type->order] = $type;
        }
    }
    $sortList = array_merge($unsorted, $sortList);
    
    ksort($sortList);
    
    $types = $sortList;
    
    $rows = array();
    $rowNumber = 0;
    foreach($types as $type) {
        if(!$type->productId) {
            echo "<div style='font-size: 30px; font-weight: bold;'>WARNING, NO PRODUCT FOUND ON CATEGORY, AUTOCORRECTING PROBLEM</div>";
            $product = $this->getApi()->getProductManager()->createProduct();
            $product->name = $type->name;
            $this->getApi()->getProductManager()->saveProduct($product);
            $type->productId = $product->id;
            $this->getApi()->getBookingEngine()->updateBookingItemType($this->getSelectedMultilevelDomainName(), $type);
        }
        $product = $this->getApi()->getProductManager()->getProduct($type->productId);
        $additional = $this->getApi()->getPmsManager()->getAdditionalTypeInformationById($this->getSelectedMultilevelDomainName(), $type->id);
        $additional->rowNumber = $rowNumber;
        $additional->name = $type->name;
        $additional->guests = $type->size;
        $additional->description = $type->description;
        $additional->rowCreatedDate = $type->rowCreatedDate;
        foreach($taxes as $tax) {
            if($tax->groupNumber == $product->taxgroup) {
                $additional->tax = $tax->taxRate . "%";
            }
        }
        $rows[$rowNumber] = $additional;
        $rowNumber++;
    }
    
    $attributes = array(
        array('id', 'gs_hidden', 'typeId'),
        array('date', 'Date', null, 'formatDate'),
        array('description', 'Description', null, "formatDescription"),
        array('guests', 'Guests', 'guests', null),
        array('children', 'Children', 'numberOfChildren', null),
        array('adults', 'Adults', 'numberOfAdults', null),
        array('beds', 'Beds', 'defaultNumberOfBeds', null),
        array('bedsforchildren', 'Beds for children', 'defaultNumberOfChildBeds', null),
        array('maxbeds', 'Max beds', 'maxNumberOfBeds', null),
        array('maxchildbeds', 'Max childbeds', 'numberOfChildren', null),
        array('tax', 'Tax', 'tax', null),
    );
    
    $table = new \GetShopModuleTable($this, 'PmsManager', 'loadTypeResult', null, $attributes);
    $table->setData($rows);
    echo "<div class='roomtypeconfigtable'>";
    $table->render();
    echo "</div>";
?>

<style>
    .roomtypeconfigtable .GetShopModuleTable .col { width: 5%; text-align: center; }
    .roomtypeconfigtable .GetShopModuleTable .col.col_3 { width:calc(100% - 800px); text-align: left; }
</style>

<script>
    $( "#sortable" ).sortable();
    $( "#sortable" ).disableSelection();
</script>
