<?php
/* @var $this ns_a22747ef_10b1_4f63_bef8_41c02193edd8\PmsRoomConfiguration */
$types = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);

$ignoreSorting = false;
$sortList = array();
$unsorted = array();
foreach($types as $type) {
    if($type->orderAvailability == 0) {
        $unsorted[] = $type;
    } else {
        $type->name = $type->name;
        $sortList[$type->orderAvailability] = $type;
    }
}

ksort($sortList);

foreach($unsorted as $type) {
    $sortList[] = $type;
}

?>
<div style='font-size: 25px;text-align: center; margin-bottom: 4px;'>
Sorting categories for availability
</div>
<ul id="sortable">
<?php foreach($sortList as $type) { ?>
  <li class="ui-state-default" typeid="<?php echo $type->id; ?>"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span><?php echo $type->name; ?></li>
<?php } ?>
</ul>
  <style>
  #sortable { list-style-type: none; margin: 0; padding: 0; width: 100%; }
  #sortable li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; font-size: 1.4em; height: 18px; }
  #sortable li span { position: absolute; margin-left: -1.3em; }
  </style>
  
  <input type='button' class="savetypesorting" value='Save sorting' sortingtype='availability' style='float:right; padding: 8px;'>
<script>
    $( "#sortable" ).sortable();
    $( "#sortable" ).disableSelection();
</script>
<div style="clear:both;"></div>