<?
/* @var $this ns_9fef9b15_a4c3_49a4_866c_d422bd244e91\PageComment */
$comments = $this->getApi()->getPageManager()->getComments($this->getPage()->getId());
?>
<div class="" gstype="form" method="saveComment">
    <textarea gsname="comment" class="add_text_area" placeholder="Comment...."></textarea>
    <div class="shop_button" gstype="submit"><? echo $this->__f("Save comment"); ?></div>
</div>

<?

if (!$comments)
    return;

foreach ($comments as $comment) {
    $user = $this->getApi()->getUserManager()->getUserById($comment->addedByUserId);
    $fullName = $user != null ? $user->fullName : "N/A";
    $date = $comment->rowCreatedDate;
    
    ?>
    <div class='comment'>
        <? echo $comment->comment; ?>
        <div class='info-row'><span class='date'><? echo $date; ?></span><span class='name'><? echo $fullName; ?></span></div>
        <div class="gs_shop_small_icon" gsclick="deleteComment" commentid="<? echo $comment->id;?>" gs_confirm="Are you sure you want to delete this comment?"><i class="fa fa-trash"></i></div>
    </div>
    <?
}
?>

