<?php
class GalleryManager extends TestBase {
    public function GalleryManager($api) {
        $this->api = $api;
    }
    
    /**
     * Creating a gallery is simple, just call the create function.
     */
    public function test_createImageGallery() {
        $manager = $this->getApi()->getGalleryManager();
        
        $id = $manager->createImageGallery();
    }
    
    /**
     * Example on how to add a image to the gallery.
     */
    public function test_addImageToGallery() {
        $manager = $this->getApi()->getGalleryManager();

        //First create a gallery.
        $id = $manager->createImageGallery();
        
        //Then add it.
        $description = "a simple image description";
        $title = "image title";
        
        //This is should be generated by whatever handles uplading images.
        $imageId = "reference_to_image";
        
        $manager->addImageToGallery($id, $imageId, $description, $title);
    }
    
    /**
     * Are you in need of fetching all the images found for a list?
     */
    public function test_getAllImages() {
        $manager = $this->getApi()->getGalleryManager();

        //First create a gallery.
        $id = $manager->createImageGallery();
        
        //Just add some images.
        $manager->addImageToGallery($id, "imgid1", "c", "d");
        $manager->addImageToGallery($id, "imgid2", "c", "d");
        
        $entries = $manager->getAllImages($id);
        foreach($entries as $entry) {
             /** @var $entry app_gallery_data_ImageEntry */
        }
    }
    
    /**
     * Sometimes it is useful to fetch only one single entry from the gallery.
     */
    public function test_getEntry() {
        $manager = $this->getApi()->getGalleryManager();
        
         //First create a gallery.
        $id = $manager->createImageGallery();
        
        //Then add it.
        $description = "a simple image description";
        $title = "image title";
        
        //This is should be generated by whatever handles uplading images.
        $imageId = "reference_to_image";
        
        $entry = $manager->addImageToGallery($id, $imageId, $description, $title);
        
        //Now fetch one single entry.
        $entry_refetched = $manager->getEntry($entry->id);
    }
    
    /**
     * Need to remove a image from the gallery?
     */
    public function test_deleteImage() {
        $manager = $this->getApi()->getGalleryManager();
        
         //First create a gallery.
        $id = $manager->createImageGallery();
        
        //Then add it.
        $description = "a simple image description";
        $title = "image title";
        
        //This is should be generated by whatever handles uplading images.
        $imageId = "reference_to_image";
        
        $entry = $manager->addImageToGallery($id, $imageId, $description, $title);
        
        $manager->deleteImage($entry->id);
    }
    
    /**
     * Need to update an existing entry? Change the image description or title?
     */
    public function test_saveEntry() {
        $manager = $this->getApi()->getGalleryManager();
        
         //First create a gallery.
        $id = $manager->createImageGallery();
        
        //Then add it.
        $description = "a simple image description";
        $title = "image title";
        
        //This is should be generated by whatever handles uplading images.
        $imageId = "reference_to_image";
        
        $entry = $manager->addImageToGallery($id, $imageId, $description, $title);
        
        $entry->title = "new title";
        $entry->description = "new description";
        $manager->saveEntry($entry);
    }
}

?>
