<span class='shortinformationbox' style="background-color:#fff; border: solid 2px; position:absolute; z-index:15;margin-top:30px; margin-left: 5px;">
    <div class="shortinformationboxrow" action="closeroom">Close room</div>
    <div class="shortinformationboxrow" action="moveroom">Move room</div>
    <div class="shortinformationboxrow" action="deletereservation">Delete this reservation</div>
    <div class="shortinformationboxrow" action="changedates">Change dates</div>
</span>

<style>
.shortinformationboxrow { 
    border-bottom: solid 1px;
    padding: 5px;
    text-align: left;
    cursor:pointer;
}
.shortinformationboxrow:hover {
    background-color: #efefef;
}
</style>