<?php
$interval = array();
$interval[60] = "60 minutes";
$interval[60*60] = "1 hour";
$interval[60*60*24] = "1 day";
$interval[60*60*24*7] = "7 days";
$interval[60*60*24*31] = "31 days";
$interval[60*60*24*365] = "365 days";
$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
foreach($types as $type) {
    $types[$type->id] = $type;
}

/* @var $this ns_176ea989_c7bb_4cef_a4bd_0c8421567e0b\PmsAvailabilityTimeline */
$start = date("d.m.Y", $this->getStart());
$end = date("d.m.Y", $this->getEnd());
$selectedInterval = $this->getInterval();
?>

<div gstype="form" method="showTimeLine">
    <input type="text" gsname='start' value='<? echo $start; ?>'>
    <input type="text" gsname='end' value='<? echo $end; ?>'>
    <select gsname='interval'>
        <?php 
        foreach($interval as $minutes => $name) {
            $selected = "";
            if($selectedInterval == $minutes) {
                $selected = "SELECTED";
            }
            echo "<option value='$minutes' $selected>$name</option>";
        }
        ?>
    </select>
    <input gstype="submit" type="button" value="<? echo $this->__w("Load settings"); ?>">
</div>

<div class='timelineresult'>
    <?php
    $filter = new core_pmsmanager_PmsIntervalFilter();
    $filter->start = $this->convertToJavaDate($this->getStart());
    $filter->end = $this->convertToJavaDate($this->getEnd());
    $filter->interval = $this->getInterval();
    
    $result = $this->getApi()->getPmsManager()->getIntervalAvailability($this->getSelectedName(), $filter);
    echo "<table cellspacing='1'>";
    
    $printHeading = true;
    foreach($result->typeTimeLines as $type => $lines) {
        if($printHeading) {
            echo "<tr>";
            echo "<th></th>";
            foreach($lines as $line) {
                echo "<th>" . date("m.d.y", strtotime($line->start)) . "</th>";
            }
            echo "</tr>";
            $printHeading= false;
        }
        /* @var $line core_bookingengine_data_BookingTimeLine */
        echo "<tr>";
        echo "<td>" . $types[$type]->name .  "</td>";
        foreach($lines as $line) {
            $full = "available";
            if($lines[0]->totalAvailableSpots == $line->count) {
                $full = "full";
            }
            $title = $line->count . " of " . $lines[0]->totalAvailableSpots . " taken";
            echo "<td align='center' title='$title' class='$full'>" . $line->count . "/" . $line->totalAvailableSpots . "</td>";
        }
        echo "</tr>";
    }
    echo "</table>";
    ?>
</div>

<script>
    $('input[gsname="start"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('input[gsname="end"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
</script>
