<?php
$interval = array();
$interval[1] = "Minute";
$interval[60] = "Hour";
$interval[60*24] = "Days";
$interval[60*24*7] = "Weeks";

/* @var $this ns_176ea989_c7bb_4cef_a4bd_0c8421567e0b\PmsAvailabilityTimeline */
$start = date("d.m.Y", $this->getStart());
$end = date("d.m.Y", $this->getEnd());
$selectedInterval = $this->getInterval();
?>

<div gstype="form" method="showTimeLine">
    <input type="text" gsname='start' value='<? echo $start; ?>'>
    <input type="text" gsname='end' value='<? echo $end; ?>'>
    <select gsname='interval'>
        <option>Select an interval</option>
        <?php 
        foreach($interval as $minutes => $name) {
            $selected = "";
            if($selectedInterval == $minutes) {
                $selected = "SELECTED";
            }
            echo "<option value='$minutes' $selected>$name</option>";
        }
        ?>
    </select>
    <input gstype="submit" type="button" value="<? echo $this->__w("Load settings"); ?>">
</div>

<script>
    $('input[gsname="start"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('input[gsname="end"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
</script>
