<?php
$interval = array();
$interval[60] = "60 minutes";
$interval[60*60] = "1 hour";
$interval[60*60*24] = "1 day";
$interval[60*60*24*7] = "7 days";
$interval[60*60*24*31] = "31 days";
$interval[60*60*24*365] = "365 days";
$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());
foreach($types as $type) {
    $types[$type->id] = $type;
}
$items = $this->indexList($this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName()));
$viewtype = array();
$viewtype['types'] = "Types";
$viewtype['items'] = "Rooms";

$printTypeOverview = $this->printTypes();


/* @var $this ns_176ea989_c7bb_4cef_a4bd_0c8421567e0b\PmsAvailabilityTimeline */
$start = date("d.m.Y", $this->getStart());
$end = date("d.m.Y", $this->getEnd());
$selectedInterval = $this->getInterval();
$compact = $this->getCompactView();
$compactChecked = "";
if($compact) {
    $compactChecked = "CHECKED";
}
?>
<div gstype="form" method="showTimeLine">
    <input type='checkbox' gsname='compactmode' <?php echo $compactChecked; ?>> Compact view<br>
    <input type="text" gsname='start' value='<? echo $start; ?>'>
    <input type="text" gsname='end' value='<? echo $end; ?>'>
    <select gsname='interval'>
        <?php 
        foreach($interval as $minutes => $name) {
            $selected = "";
            if($selectedInterval == $minutes) {
                $selected = "SELECTED";
            }
            echo "<option value='$minutes' $selected>$name</option>";
        }
        ?>
    </select>
    <input gstype="submit" type="button" value="<? echo $this->__w("Show"); ?>">
    <input type='button' style='float:right;' onclick="$('.closeRoomOption').show();" value="Close a room">
</div>
<br>
<div gstype="form" method="closeRoom" style='display:none;' class='closeRoomOption'>
    Choose a room to close down: <br>
    <select gsname='itemid'>
        <?php
        foreach($items as $item) {
            echo "<option value='".$item->id."'>" . $item->bookingItemName . "</option>";
        }
        ?>
    </select>
    <input type="text" gsname='start' value='<? echo $start; ?>'>
    <input type="text" gsname='end' value='<? echo $end; ?>'>
    <input gstype="submit" type="button" value="<? echo $this->__w("Close room"); ?>">
    <?php
    if($this->roomWhereNotClosed) {
        echo "<div style='color:red; font-size: 20px;'>* Can not close this room since there are booking depending on it, this needs to be cleared out first.</div>";
    }
    ?>
</div>
<input type='hidden' value='<?php echo $this->getConfigurationSetting("pmsmanagerinstanceid"); ?>' id='bookinginstanceid'>
<div class='timelineresult'>
    <?php
    $filter = new core_pmsmanager_PmsIntervalFilter();
    $filter->start = $this->convertToJavaDate($this->getStart());
    $filter->end = $this->convertToJavaDate($this->getEnd());
    $filter->interval = $this->getInterval();
    
    $result = $this->getApi()->getPmsManager()->getIntervalAvailability($this->getSelectedName(), $filter);

    $numberOfDays = 0;
    foreach($result->typeTimeLines as $type => $lines) {
        foreach($lines as $line) {
            $numberOfDays++;
        }
        break;
    }
    
    $freecount = 0;
    $totalRooms = 0;
    foreach($result->itemTimeLines as $itemId => $days) {
        $taken = false;
        foreach($days as $time => $value) {
            if($value->count != 0) {
                $taken = true;
            }
        }
        $totalRooms++;
        if(!$taken) {
            $freecount++;
        }
    }
    $taken = ($totalRooms-$freecount);
    echo "Rooms free: " . $freecount . " of " . $totalRooms . " in total giving " . $taken .  " rooms taken.<bR><bR>";

    echo "<div class='timelineoverviewouter'>";
    echo "<div class='timelineoverview'>";
    echo "<table cellspacing='1'>";

    $printHeading = true;
    foreach($result->typeTimeLines as $type => $lines) {
        if($printHeading) {
            echo "<tr>";
            echo "<th></th>";
            foreach($lines as $line) {
                echo "<th>" . date("d.m.y", strtotime($line->start)) . "</th>";
            }
            echo "</tr>";
            $printHeading= false;
        }
        /* @var $line core_bookingengine_data_BookingTimeLine */
        echo "<tr>";
        echo "<td>" . $types[$type]->name .  "</td>";
        foreach($lines as $day => $line) {
            $full = "available";
            if($lines[0]->totalAvailableSpots == $line->count) {
                $full = "full";
            }
            $title = $line->count . " of " . $lines[0]->totalAvailableSpots . " taken";
            echo "<td align='center' type='$type' day='".$line->start."' title='$title' class='$full loadBookingList'>" . $line->count . "/" . $line->totalAvailableSpots . "</td>";
        }
        echo "</tr>";
    }
    echo "</table>";
    echo "</div>";
    echo "</div>";
    echo "<bR><bR>";

    $printHeader = true;
    $detailed = "";
    if(!$this->getCompactView()) {
        $detailed = "detailedview";
    }
    echo "<div class='timelineoverviewouter $detailed'>";
    echo "<div class='timelineoverview'>";
    echo "<div class='topspacingitemoverview'></div>";
    foreach($result->itemTimeLines as $itemId => $days) {
        $lastid = "";
        $toggle = true;
        if($printHeader) {
            echo "<div class='dateheadingrow'>";
            echo "<span class='valueentry_placeholder'>&nbsp;</span>";
            foreach($days as $time => $value) {
                echo "<span class='valueentry date'>" . date("d.m.y", $time/1000) . "</span>";
            }
            echo "</div>";
            echo "<div style='clear:both;'></div>";
            $printHeader = false;
        }

        echo "<span class='valueentry_item' title='".$items[$itemId]->description."'>" . $items[$itemId]->bookingItemName . " <span class='room_desc'>" . $items[$itemId]->description . "</span></span>";
        echo "<span class='valueentry_placeholder'>&nbsp;</span>";
        $printed = false;
        $free = "available";
        foreach($days as $time => $value) {
            $doPrint = true;
            $isTaken = true;
            $id = "";
            if($value->count == 0) {
                $doPrint = false;
                $free = "available";
                $isTaken = false;
            } else {
                $id = $value->bookingIds[0];
            }
            $name = "";
            $toggled = false;
            if($id != $lastid) {
                if($lastid)
                $toggle = !$toggle;
                $lastid = $id;
                if($isTaken) {
                    $toggled = true;
                    $printed = false;
                }
            }
            
            if(!$printed) {
                $name = $this->makeInitials($value->name);
                $name = htmlentities($name);
                if($isTaken) {
                    if($toggle) {
                        $free = "full";
                    } else {
                        $free = "full full_second";
                    }
                }
            }
            
            if($value->name == "cleaning") {
                $free = "needcleaning";
                if($name)
                    $name = $this->createDeleteBookingIcon($id);
            }
            if($value->name == "closed") {
                $free = "closedroom";
                if($name)
                    $name = $this->createDeleteBookingIcon($id);
            }
            
            echo "<span class='valueentry $free' time='$time' itemid='".$itemId."' bid='$id'>&nbsp;&nbsp;$name</span>";
            if($isTaken) {
                $printed = true;
            }
        }
        echo "<div style='clear:both;'></div>";
    }
    echo "</div>";
    echo "</div>";
    ?>
</div>

<script>
    $('.PmsAvailabilityTimeline .timelineoverview').width('<? echo ($numberOfDays*80)+200; ?>px');
    $('.PmsAvailabilityTimeline .dateheadingrow').width('<? echo ($numberOfDays*80)+200; ?>px');
    $('.PmsAvailabilityTimeline .dateheadingrow').css('position','absolute');
    $('.PmsAvailabilityTimeline .dateheadingrow').css('top','0px');
    $('input[gsname="start"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('input[gsname="end"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
    <?php if(!$printTypeOverview) { ?>
        $('select[gsname="viewtype"]').val('items');
    <?php } ?>
        $('.timelineoverviewouter').scroll(function() {
            var left = $(this).scrollLeft();
            $('.valueentry_item').css('left',left+"px");
            $('.PmsAvailabilityTimeline .dateheadingrow').css('top',$(this).scrollTop());
        });
</script>
