<div class='headertext'>
    <?php
    echo $this->__f("Are you sure you want to create a new tab?")
    ?>
    
</div>

<div class='buttonsarea' gstype='form' method='createNewTab'>
    <? echo $this->__f("Give it a reference name?"); ?>
    <br/><input gstype="submitenter" gsname='tabreferencename' class='gsniceinput1'/>
    <br/>
    <br/>
    <div class='shop_button' gstype='submit'><? echo $this->__f("Create"); ?></div>
</div>
