<?
/* @var $this ns_57db782b_5fe7_478f_956a_ab9eb3575855\SalesPointNewSale */
$tab = $this->getCurrentTab();    
$tabId = $tab ? $tab->id : "";
$tabActive = !$tab ? "tabnotactive" : "";
$showpaymentmodal = $tab ? "gs_show_modal='paymentmodal'" : "";
$cashpoints = $this->getApi()->getPosManager()->getCashPoints();
?>

<div class='menu'>
    <div class='entry taboperation printoverview' tab='printpreview'>
        <i class='fa fa-print'></i>
        Print / Reprint
    </div>
    
    <div class='printmenu'>
        <div class='entry taboperation printcurrenttab' tab='printpreview'>
            <i class='fa fa-bullhorn'></i>
            Print preview
        </div>

        <div class='entry taboperation showreprint' gsclick='activateView' view='reprint' tab='printpreview'>
            <i class='fa fa-history'></i>
            Reprint
        </div>

        <div class='entry taboperation <? echo $tabActive; ?> printkitchen'>
            <i class='fa fa-cutlery'></i>
            Print to kitchen
        </div>
    </div>
    
    <div class='entry taboperation startpaymentbutton <? echo $tabActive; ?>'  <? echo $showpaymentmodal; ?> tab='listtab' tabid='<? echo $tabId; ?>' paymentmethodid="">
        <i class='fa fa-credit-card'></i>
        Payment
    </div>
    <div class='entry taboperation deletetab <? echo $tabActive; ?>' tab='listtab'>
        <i class='fa fa-trash'></i>
        Delete tab
    </div>
    
    <br/>
    <br/>
    <br/>
    
    <div class='entry all' tab='newtab'>
        <i class='fa fa-dollar'></i>
        New tab
    </div>
    
    <div class='entry all' tab='listtab'>
        <i class='fa fa-tablet'></i>
        List tabs
    </div>
    
    <div class='entry showsearch' >
        <i class='fa fa-search'></i>
        Search
    </div>
    
    <?
    if ($this->getSelectedCashPointId() && count($cashpoints) > 1) {
    ?>
        <div class='entry all' onclick="localStorage.removeItem('cash_point_id');" gsclick='disconnectedCashPoint'>
            <i class='fa fa-chain-broken'></i>
            Disconnect Cashpoint
        </div>
    <?
    }
    ?>
</div>
