<?
/* @var $this ns_57db782b_5fe7_478f_956a_ab9eb3575855\SalesPointNewSale */
$product = $this->getApi()->getProductManager()->getProduct($_POST['data']['productid']);

$extras = $product->extras;

foreach ($extras as $extra) {
    echo "<div class='extraoptiongroup' type='$extra->type' extraid='$extra->id'>";
        echo "<h2>".$extra->name."</h2>";

        foreach ($extra->extras as $option) {
        ?>
            <div class="product checkbox">

                <div class="checkboxinner" optionid="<? echo $option->optionsubid; ?>">
                    <i class="fa fa-check-circle"></i>
                    <i class="fa fa-circle"></i>
                </div>

                <div class="inner">
                    <div class="productname"><? echo $option->name; ?></div>
                </div>
            </div>
            <?
        }
    echo "</div>";
}
?>

<div class="productionbuttonarea">
    <div class="shop_button addProductToCurrentTab" 
         <?
         foreach ($_POST['data'] as $key => $val) {
             echo $key."='$val' ";
         }
         ?>><? echo $this->__f("Next"); ?></div>
</div>
