<?
/* @var $this \ns_57db782b_5fe7_478f_956a_ab9eb3575855\SalesPointNewSale */

$result = $this->getApi()->getProductManager()->search($_POST['data']['searchvalue'], 9999, 1);

foreach ($result->products as $product) {
        ?>
        <div class='product addProductToCurrentTab' productid="<? echo $product->id; ?>">
            <div class='inner'>
                <div class='productname'><? echo $product->name; ?></div>
            </div>
        </div>
        <?
    }
?>