<?
/* @var $this ns_57db782b_5fe7_478f_956a_ab9eb3575855\SalesPointNewSale */
$tab = $this->getCurrentTab(); 

$canChangeTaxes = false;

$taxesToSelectBetween = (array)$this->getDistinctAdditionalTaxCodes($tab);

if (!$tab) {
    ?>
    <div class='header'>
        <div class='notabopen'>
            <?
            echo $this->__f("No tab open");
            ?>
        </div>
        <div class='notabopen_desc'>
            <?
            echo $this->__f("Create a new one or select one that already exists from the menu to the left");
            ?>
        </div>
    </div>
    <?
    return;
}
?>

<div class='header'>
    <? echo $this->__f("Tab").": ".$tab->name; ?>
</div>

<div class='tabcreateinfo'>
    <?
    $createdByUser = $this->getApi()->getUserManager()->getUserById($tab->createdByUserId);
    echo $this->__f("Created by").": ".$createdByUser->fullName;
    echo "<br/>".$this->__f("Created date").": ".$tab->rowCreatedDate;
    ?>    
</div>

<?
if (count($taxesToSelectBetween) || $tab->tabTaxGroupId) {
    ?>
    <div class='header2'> 
        <? echo $this->__f("Change to different tax rate"); ?>
    </div>

    <div class='taxrates'>
        <?
        if ( $tab->tabTaxGroupId) {
            ?>
            <div class="gs_shop_small_icon" gsclick='cancelCurrentTaxSelection'><? echo $this->__f("Undo"); ?></div>
            <?
        } else {
            foreach ($taxesToSelectBetween as $taxGroup) {
                $desc = $taxGroup->description ? " ( ".$taxGroup->description." )" : "";
                ?>
                <div class="gs_shop_small_icon" gsclick='changeTabTax' taxgroupnumber='<?  echo $taxGroup->id; ?>'><? echo $taxGroup->taxRate."%".$desc; ?></div>
                <?
            }
        }
        ?>
    </div>
<?
}
?>
<div class='header2'> 
    <? echo $this->__f("Added to tab"); ?>
</div>
<?
$cartItems = $tab->cartItems;
foreach ($cartItems as $item) {
    $foodIcon = $item->product->isFood ? "<i title='Food' class='fa fa-cutlery'></i> " : "";
    
    $priceToUse = $item->product->price;
    
    if ($item->overridePriceIncTaxes) {
        $priceToUse = $item->overridePriceIncTaxes;
    }
        
    $priceText = $this->getPriceHtml($item);
    
    echo "<div class='cartitemline' cartitemid='$item->cartItemId'>";
        echo "<div class='col count'>".$item->count."</div>";
        echo "<div class='col productname'>$foodIcon".$item->product->name."</div>";
        echo "<div class='col price'>".$priceText."</div>";
        
        echo "<div class='details'>";
        
            if (count((array)$item->product->selectedExtras)) {

                foreach ($item->product->selectedExtras as $optionId => $extraIds) {
                    echo "<div class='row_for_extras'>";
                        $extraOption = $this->getExtraOption($item->product->extras, $optionId);

                        echo "<b>".$extraOption->name."</b>:";
                        $i = 0;
                        foreach ($extraIds as $extraId) {
                            $i++;
                            $extraOptionSub = $this->getExtraOption($extraOption->extras, $extraId);
                            echo $extraOptionSub->name;
                            if ($i < count($extraIds)) {
                                echo ",";
                            }
                        }
                    echo "</div>";
                }
            }
            
            echo "<input class='gsniceinput1 changecount' value='".$item->count."' gstype='numpad' gsnumpadtitle='Please enter new count'/> ";
            echo " x <input class='gsniceinput1 changeprice' value='".$priceToUse."' gstype='numpad' gsnumpadtitle='Please enter new price'/>";
            ?>

            <span class="gs_shop_small_icon" title="<? echo $this->__f("Discount"); ?>" cartitemid='<? echo $item->cartItemId; ?>' gstype='numpad' gsmethod='methodToExecute' gsnumpadtitle='Please enter discount percent' gsnumpad_on_ok='app.SalesPointNewSale.itemDiscountChange'>
                <span class="fa-stack fa-lg">
                    <i class="fa fa-certificate fa-stack-2x"></i>
                    <i class="fa fa-tag fa-stack-1x fa-inverse"></i>
                </span> 
            </span>

            <span class="gs_shop_small_icon removefromtab">
                <span class="fa-stack fa-lg">
                    <i class="fa fa-stack-2x  fa-trash "></i>
                </span> 
            </span>
            <?
        echo "</div>";
    echo "</div>";
}
?>

<div class="total tabtotal">
    <?php
    $total = $this->getApi()->getPosManager()->getTotal($tab->id);
    echo $this->__f("Total").": <span>".$total."</span>";
    
    if ($tab->cashWithDrawal) {
    ?>
        <div>
            + Cash withdraw: <? echo $tab->cashWithDrawal; ?>
        </div>
    <? } ?>
    
</div>

<div class="tabmenu">
    <span class="gs_shop_small_icon" title="<? echo $this->__f("Tab discount"); ?>" gstype='numpad' gsnumpadtitle='Please enter discount percent' gsnumpad_on_ok='app.SalesPointNewSale.setTabDiscount'>
        <span class="fa-stack fa-lg">
            <i class="fa fa-certificate fa-stack-2x"></i>
            <i class="fa fa-tag fa-stack-1x fa-inverse"></i>
        </span> 
    </span>
</div>
