<div class="spacer s0" id="trigger"></div>

<div class='animationwarapper' >
<div style='top: 260px; position:absolute; font-size: 60px;text-align: center; width:100%;padding-top: 200px;'>
    Vi skreddersyr din webløsning.
</div>
    <div id="target" style="position:relative; left: 50%; top: 140px;">
        <div id="animation_l1" style='position: absolute; left:  0px; font-size: 100px;'>G</div>
        <div id="animation_l2" style='position: absolute; left:  70px; font-size: 100px;'>e</div>
        <div id="animation_l3" style='position: absolute; left:  130px; font-size: 100px;'>t</div>
        <div id="animation_l4" style='position: absolute; left:  180px; font-size: 100px;'>S</div>
        <div id="animation_l5" style='position: absolute; left:  240px; font-size: 100px;'>h</div>
        <div id="animation_l6" style='position: absolute; left:  300px; font-size: 100px;'>o</div>
        <div id="animation_l7" style='position: absolute; left:  360px; font-size: 100px;'>p</div>
        <img id="plane2" style='position: absolute; left: -130px;' src="https://www.getshop.com/displayImage.php?id=7d09b192-4aea-4045-88e3-69445b408c57">
    </div>
</div>

<script>
    app.GetShopAnimationFront.start();
</script>
