<?
/* @var $this ns_d3bd5a9e_2e8d_4992_b6c4_aacec6ae284e\SettingsDepartments */
$department = $this->getApi()->getDepartmentManager()->getDepartment($_SESSION['edit_department_id']);
?>

<div style='margin: 50px;' gstype='form' method='saveDepartment'>
    <h2><? echo $this->__f("Edit department"); ?></h2>
    
    <? echo $this->__f("Department name"); ?>
    <br/><input class='gsniceinput1' gsname='name' value='<? echo $department->name; ?>'/>
    <br/><br/><? echo $this->__f("Department code"); ?>
    <br/><input class='gsniceinput1' gsname='code' value='<? echo $department->code; ?>'/>
    <br/>
    <br/><div class='shop_button' gstype='submit'><? echo $this->__f("Save"); ?></div>
</div>