<div class="shellview">
    <a href="/?page=04e0d1d1-72d4-4c52-a6fd-8dd9539c78b7">  <div class="shellbox" id="shellbox1"></div></a>
    <a href="/?page=276d8e86-db42-46ca-9248-7c8fbf6bc020">  <div class="shellbox" id="shellbox2"></div></a>
    <a href="/?page=fc0ebe6da-87ad-4e83-822f-b6ab7640527f"> <div class="shellbox" id="shellbox3"></div></a>
    <a href="/?page=b9240177-f31d-40c6-b2fd-4561479dfb71">  <div class="shellbox" id="shellbox4"></div></a>
    <a href="/?page=16483c17-7820-4928-975c-647fc48940e3">  <div class="shellbox" id="shellbox5"></div></a>
    <a href="/?page=f9d76921-0043-47c9-9678-acb0f26f45b6">  <div class="shellbox" id="shellbox6"></div></a>
    <a href="/?page=7fd9112b-2018-4280-a882-120502cbcda1">  <div class="shellbox" id="shellbox7"></div></a>
                                                            <div class="shellbox" id="shellbox8"></div>
    <a href="/?page=8933cbb8-c1f2-4d88-93cb-ff48e01b4a46">  <div class="shellbox" id="shellbox9"></div></a>
</div>
