<?
/* @var $this ns_cf3f46d9_0073_4966_977d_8e202dc5abbb\SedoxBannerAndOpening */
?>

<div class="banner_and_opening">
    <div class="opening_container">
        <div class="description">
            <div class="description_content">
                <span class="fa fa-clock-o"></span>
                <span class="description_text">Opening Hours</span>
            </div>
        </div
        ><div class="opening_data">
            <div class="two_fifth_width">
                <div class="open_days"><span>Monday - Friday</span></div>
                <div class="half_width"><span><?php echo $this->getConfigurationSetting("monday_fri_fullservice"); ?></span><span>Full File<br>Service</div
                ><div class="half_width"><span>20-23h</span><span>Limited File Service</div>
            </div
            ><div class="two_fifth_width">
                <div class="open_days"><span>Saturday</div>
                <div class="half_width"><span>10-15h</span><span>Full File<br>Service</div
                ><div class="half_width"><span>15-22h</span><span>Limited File Service</div>
            </div
            ><div class="one_fifth_width">
                <div class="open_days"><span>Sunday</div>
                <div class="full_width"><span>10-22h</span><span>Limited File Service</div>
            </div>
        </div>
    </div
    ><div class="banner_container">
        <div class="description">
            <div class="description_content">
                <span class="fa fa-location-arrow"></span>
                <span class="description_text">Where to find us</span>
            </div>
        </div
        ><div class="banner_data">
            <div class="data_wrapper">
                <div class="one_forth_height">
                    <span class="fa fa-phone"></span>
                    <span>+47 909 16 585</span>
                </div>
                <div class="one_forth_height">
                    <span class="fa fa-envelope"></span>
                    <span>support@sedox.com</span>
                </div>
                <div class="two_forth_height">
                    <span class="fa fa-location-arrow"></span>
                    <span>Sverdrups gate 30, 4007 Stavanger<br>Norway</span>
                </div>
            </div>
        </div>
    </div>
</div>