<?
/* @var $this \ns_cf3f46d9_0073_4966_977d_8e202dc5abbb\SedoxBannerAndOpening */
?>

<div class='gss_settings_header'>

    <span class="fa-stack fa-lg" style="margin-right: 60px;">
        <i class="fa fa-gears fa-stack-1x"></i>

    </span>



    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Sedox Performance"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("Configuration for Sedox Performance.");
            ?>	
        </div>

    </div>	
</div>

<div class='gss_settings_content'>
    <div class="textfield gss_setting"  id="name">
        <span class="title"><?php echo $this->__f("Name"); ?></span>
        <input type="textfield" gs_model='sedoxopenmodel' gs_model_attr='monday_fri_fullservice' value="<? echo $this->getConfigurationSetting("monday_fri_fullservice"); ?>" placeholder="">
        <div class="description">
            <?php echo $this->__("Full service hours monday - friday"); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting"  id="name">
        <span class="title"><?php echo $this->__f("Name"); ?></span>
        <input type="textfield" gs_model='sedoxopenmodel' gs_model_attr='monday_fri_limitedservice' value="<? echo $this->getConfigurationSetting("monday_fri_limitedservice"); ?>" placeholder="">
        <div class="description">
            <?php echo $this->__("Limited service hours monday - friday."); ?>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveHours" gss_model="sedoxopenmodel"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>

</div>