<div class='gslfront_1'>
    <div class='gslbookingHeader'>
        <div class="fa_box destination">
            <input id="destination" placeholder="Destination?" onfocus="this.placeholder =''" onblur="this.placeholder ='Destination?'" style="border-right:1px solid #ddd;" readonly>
            <div class="destinationInfoBox">
                <div class='destination_line'><img class="destination_image" src="https://www.visitoslo.com/Images/Bilder%20Oslo/Attraksjoner/Akrobaten%20mot%20Barcode_Leif%20Harald%20Ruud.jpg?t=ScaleToFill%7C1450x720&ts=ajCYo6pTmf0Mfh7RGfLmeiDlLmE%3D"><span gstype='bookingtranslation' gstranslationfield='gsHotelOs'></span></div>
                <div class='destination_line'><img class="destination_image" src="https://media.newmindmedia.com/TellUs/image/?file=3F59853038189DAC967CB6AB12EE7B4F977148CA.jpg&dh=392&dw=526"><span gstype='bookingtranslation' gstranslationfield='gsHotelTb'></span></div>
            </div>
        </div><div class="fa_box date">
            <input id="date_picker" style="border-right:1px solid #ddd;" readonly>
        </div><div class="fa_box guests">
            <input id="guests" value="1 room, 1 guest" style="border-right:1px solid #ddd;" readonly>
            <div class="guestInfoBox">
                <div class='guestInfoBox_left'>
                    <div><span gstype='bookingtranslation' gstranslationfield='rooms'></span></div>
                    <div><span gstype='bookingtranslation' gstranslationfield='adults'></span></div>
                    <div style='top:-6px;'><span gstype='bookingtranslation' gstranslationfield='children'></span><br><span style="font-size:12px;position:absolute;left:0;"><span gstype='bookingtranslation' gstranslationfield='agestwototwelve'></span></span></div>
                </div>
                <div class='guestInfoBox_right'>
                    <div class="count_line">
                        <i id="subtract_room" class="fa fa-minus disabled"></i><input type="txt" class="count" id="count_room" value="1" readonly><i id="add_room" class="fa fa-plus"></i>
                    </div>
                    <div class="count_line">
                        <i id="subtract_adult" class="fa fa-minus disabled"></i><input type="txt" class="count" id="count_adult" value="1" readonly><i id="add_adult" class="fa fa-plus"></i>
                    </div>
                    <div class="count_line">
                        <i id="subtract_child" class="fa fa-minus disabled "></i><input type="txt" class="count" id="count_child" value="0" readonly><i id="add_child" class="fa fa-plus"></i>
                    </div>
                </div>
                <div class="guestInfoBox_footer">
                    <div onclick="confirmGuestInfoBox()"><span gstype='bookingtranslation' gstranslationfield='apply'></span></div>
                </div>
            </div>
        </div><div class="fa_box coupon">
            <input id='coupon_input' onfocus="this.placeholder =''" onblur="this.placeholder ='Discount coupon?'" placeholder="Discount coupon?">
        </div><div class="fa_box gsl_button" id="search_rooms" onclick="showProductList()"><span gstype='bookingtranslation' gstranslationfield='search'></span></div>
    </div>
    
    <div class="gslbookingBody">
        <div id="orderSum" class="noroomsfound"><span gstype='bookingtranslation' gstranslationfield='noRoomsMessage'></span></div>
        <div id="orderSum" class="ordersummary">
            <h3><i class='fa fa-smile-o'></i><span gstype='bookingtranslation' gstranslationfield='inLuckAvailable'></span><i class='fa fa-smile-o'></i></h3>
            <div class="selectedguests"></div>
            <span gstype='bookingtranslation' gstranslationfield='bestValue'></span><span class='totalprice'></span>
            <span class='gsl_button continue active'><span gstype='bookingtranslation' gstranslationfield='continue'></span></span>
            <div class='bottomspacer'></div>
        </div>
        <div class="productoverview">
            <div id="productentry"></div>
            <div id="productoverview_footer" style="position: relative;">
            </div>
        </div>
        <div class="addons_overview">
            <div style="width:30%;float:right;">
                <div style="padding:10px;">
                    <h4 style="border-bottom: 2px solid #ddd;padding-bottom: 4px;"><span gstype='bookingtranslation' gstranslationfield='yourStay'></span></h4>
                    <div class='yourstaysummary'></div>
                    <div style="position:absolute;bottom:10px;right:0; width:30%;">
                        <div class="gsl_button continue" onclick="showOverviewPage()" style='float:right;margin-right: 10px;'><span gstype='bookingtranslation' gstranslationfield='continue'></span><i class="fa fa-arrow-right"></i></div>
                    </div>
                </div>
            </div>
            <div style="width:70%;background-color:#f9f9f9;padding:20px;box-shadow: inset -1px 0 0 #ddd;">
                <div class="addonsentry">
                    <h3><span gstype='bookingtranslation' gstranslationfield='addons'></span></h3>
                    <span gstype='bookingtranslation' gstranslationfield='addAddonsOr'></span>
                    <div class="overview_addons">
                        <div class="addon" id='addon' style='display:none;'>
                            <div style="width:60%;"><span class='icon'></span> <span class='text'></span></div><div><span gstype='bookingtranslation' gstranslationfield='NOK'></span><span class='price'></span>,-</div><div id="addon_earlyCheckin" class="addButton gsl_button"><span gstype='bookingtranslation' gstranslationfield='add'></span></div>
                        </div>
                    </div>
                </div>
                <h3><span gstype='bookingtranslation' gstranslationfield='guestInfo'></span></h3>
                <span gstype='bookingtranslation' gstranslationfield='correctEmailforGuest'></span>
                <div class="roomentryframe">
                    <div class="roomentry" id='roomentrycontainer' style='display:none;'>
                        <h4><span class='roomname'></span> 
                            <span class='secondary_text'>
                                <span gstype='bookingtranslation' gstranslationfield='checkin'></span><span class='startdate'></span>, <span gstype='bookingtranslation' gstranslationfield='checkout'></span><span class='enddate'></span>
                            </span>
                        </h4>
                        
                        <div class="guestentry">
                            <div><span gstype='bookingtranslation' gstranslationfield='name'></span></div>
                            <div><span gstype='bookingtranslation' gstranslationfield='e-mail'></span></div>
                            <div><span gstype='bookingtranslation' gstranslationfield='phone'></span></div>
                            <div><span gstype='bookingtranslation' gstranslationfield='addons'></span></div>
                        </div>
                        <div class="guestentry" id='guestentryrow' style='display:none;'>
                            <div><input type="txt" gsname="name"></div>
                            <div><input type="txt" gsname="email"></div>
                            <div><input type="txt" class="guest_phone" value="47" gsname="prefix"><input type="text" style="width:75%;" gsname="phone"></div>
                            <div>
                                <div class="guest_addon"></div>
                            </div>
                        </div>
                        <div class='guestRows'></div>
                        <div class='errormessage'><span gstype='bookingtranslation' gstranslationfield='invalidguestinformation'></span></div>
                        <div class="addguest gsl_button"><i class="fa fa-plus"></i><span gstype='bookingtranslation' gstranslationfield='addGuest'></span></div>
                    </div>
<!--                    <div class="addroom gsl_button" style="float:right;"><i class="fa fa-plus"></i> Add another room</div>-->
                </div>
            </div>
        </div>
        <div class="overview">
            <div class="overview_room_info">
                <h4 style="border-bottom: 2px solid #ddd;padding-bottom: 4px;"><span gstype='bookingtranslation' gstranslationfield='yourStay'></span></h4>
                <div class='yourstaysummary'></div>
                <div class="overview_confirmation">
                    <div class="gsl_button return" onclick="showAddonsPage()"><i class="fa fa-arrow-left"></i><span gstype='bookingtranslation' gstranslationfield='return'></span></div><div class="gsl_button continue go_to_payment_button"><span gstype='bookingtranslation' gstranslationfield='goToPayment'></span></div>
                </div>
            </div>
            <div class="overview_article">
                <div class="overview_loggedon">
                    <h3>
                        <span gstype='bookingtranslation' gstranslationfield='loggedonas'></span><span class='loggedonusername'></span>
                        <input class='gssignoutbutton' type="button" style="float:right;" gstype='bookingtranslation' gstranslationfield='logout'>
                    </h3>
                    <b><span gstype='bookingtranslation' gstranslationfield='ordertext'></span></b><br>
                    <textarea gsname='ordertext' class="ordertext"></textarea>
                </div>
                
                <div class="overview_contact">
                    <h3><span gstype='bookingtranslation' gstranslationfield='contactInformation'></span></h3>
                    <div class="overview_contact_tab">
                        <label for="private" id="private" class='selectedusertype'>
                            <input type="radio" name="user" checked="checked"><span gstype='bookingtranslation' gstranslationfield='private'></span>
                        </label>
                        <label for="organization" id="organization" class='selectedusertype'>
                            <input type="radio" name="user"><span gstype='bookingtranslation' gstranslationfield='organization'></span>
                        </label>
                        <label for="gotAccount" id="gotAccount" class='selectedusertype'>
                            <input type="radio" name="user"><span gstype='bookingtranslation' gstranslationfield='alreadyGotanAccount'></span>
                        </label>
                    </div>
                    <br>
                    <div class="private_fields" type='user'>
                        <div class="guestentry guesttypeselection" type='private'>
                            <div><input type='checkbox' id='sameasguestselection' style='width:16px; padding:initial;'> <span gstype='bookingtranslation' gstranslationfield='sameasguest'></span></div>
                            <div style='clear:both;'></div><br>
                            <div style="width: 33.33%;float: left;">
                                <div><span gstype='bookingtranslation' gstranslationfield='name'></span></div><br>
                                <input type="txt" gsname="user_fullName">
                            </div>
                            <div style="width: 33.33%;float: left;">
                                <div><span gstype='bookingtranslation' gstranslationfield='e-mail'></span></div><br>
                                <input type="txt" gsname="user_emailAddress">
                            </div>
                            <div style="width: 33.33%;float: left;">
                                <div><span gstype='bookingtranslation' gstranslationfield='phone'></span></div><br>
                                <input type="txt" class="guest_phone" value="   47" gsname="user_prefix" style='float:left;'>
                                <input type="text" style="width:75%;border-right: 1px solid #ddd;float:left;"gsname="user_cellPhone">
                            </div>
                            <div style="width: 50%;float:left; padding-top: 10px;">
                                <div><span gstype='bookingtranslation' gstranslationfield='streetAdress'></span></div><br>
                                <input type="txt" gsname='user_address_address'>
                            </div>
                            <div style="width: 50%;float:left; padding-top: 10px;">
                                <div><span gstype='bookingtranslation' gstranslationfield='zipCode'></span></div><br>
                                <input id="guest_zipcode" type="txt"  class="guest_phone" value="" style="width:25%;border-right: 1px solid #ddd;float:left;" gsname='user_address_postCode'>
                                <input id="guest_zipname" type="text" style="width:75%;border-right: 1px solid #ddd;float:left;" gsname='user_address_city'>
                            </div>
                        </div>
                    </div>
                    <div class="company_fields guesttypeselection" style='display:none;' type='organization'>
                        <div class="guestentry">
                            <div style="width: 25%;float: left;">
                                <span gstype='bookingtranslation' gstranslationfield='companyName'></span><br>
                                <input type="txt" gsname="company_name">
                            </div>
                            <div style="width: 25%;float: left;">
                                <span gstype='bookingtranslation' gstranslationfield='vatNumber'></span><br>
                                <input type="txt" gsname="company_vatNumber">
                            </div>
                            <div style="width: 25%;float: left;">
                                <span gstype='bookingtranslation' gstranslationfield='e-mail'></span><br>
                                <input type="txt" gsname="company_email">
                            </div>
                            <div style="width: 25%;float: left;">
                                <span gstype='bookingtranslation' gstranslationfield='phone'></span><br>
                                <input type="txt" class="guest_phone" value="+47" gsname="company_prefix" style='float:left;'>
                                <input type="text" style="width:75%;border-right: 1px solid #ddd;float:left;"gsname="company_phone">
                            </div>
                            <div style="width: 50%;float:left; padding-top: 10px;">
                                <span gstype='bookingtranslation' gstranslationfield='streetAdress'></span><br>
                                <input type="txt" gsname='company_address_address'>
                            </div>
                            <div style="width: 50%;float:left; padding-top: 10px;">
                                <span gstype='bookingtranslation' gstranslationfield='zipCode'></span><br>
                                <input id="guest_zipcode" type="txt"  class="guest_phone" value="" style="width:25%;border-right: 1px solid #ddd;float:left;" gsname='company_address_postCode'>
                                <input id="guest_zipname" type="text" style="width:75%;border-right: 1px solid #ddd;float:left;" gsname='company_address_city'>
                            </div>
                        </div>
                    </div>
                    <div class="login_fields guesttypeselection" style='display:none;' type='gotAccount'>
                        <div class="guestentry">
                            <div style="width: 50%; float:left;"><span gstype='bookingtranslation' gstranslationfield='userOrEmail'></span><br><input type="txt" gsname="username"></div>
                            <div style="width: 50%; float:left;"><span gstype='bookingtranslation' gstranslationfield='password'></span><br><input type="password" gsname="password"></div>
                        </div>
                        <input type='button' class='gssigninbutton' gstype='bookingtranslation' gstranslationfield='signinbutton'>
                        
                        <div class='failedlogon'><span gstype='bookingtranslation' gstranslationfield='failedlogon'></span></div>
                        
                    </div>
                    <div style="clear: both;"></div>
                </div>
                <div style="padding:10px;" class='agreetotermsbox'>
                    <label for="agreeTerms">
                        <input id="agreeTerms" type="checkbox">
                        <span gstype='bookingtranslation' gstranslationfield='agreeTerms'></span>
                    </label>
                    <div><a style="cursor:pointer;"><span gstype='bookingtranslation' gstranslationfield='readTerms'></span></a></div>
                    <div><a style="cursor:pointer;"><span gstype='bookingtranslation' gstranslationfield='downloadTerms'></span></a></div>
                </div>
                <div class='errormessage'><span gstype='bookingtranslation' gstranslationfield='invalidguestinformation'></span></div>
                <div class='agreetotermserrormessage'><span gstype='bookingtranslation' gstranslationfield='agreetotermserrormessage'></span></div>
                
                <div style="clear: both;"></div>
            </div>
        </div>
    </div>
    <div class='successcompleted'><span gstype='bookingtranslation' gstranslationfield='successfulbooking'></span></div>
    <div class='errorcompleted'><span gstype='bookingtranslation' gstranslationfield='errorcompleted'></span></div>
</div>

<div class="roomentry" id="addnewroom">
    <h4><span gstype='bookingtranslation' gstranslationfield='roomExample1'></span></h4>
    <div class="guestentry">
        <div><span gstype='bookingtranslation' gstranslationfield='name'></span><br><input type="txt">
        </div><div><span gstype='bookingtranslation' gstranslationfield='e-mail'></span><br><input type="txt">
        </div><div><span gstype='bookingtranslation' gstranslationfield='phone'></span><br><input type="txt" class="guest_phone" value="+47"><input type="text" style="width:75%;">
        </div><div><span gstype='bookingtranslation' gstranslationfield='addons'></span><br>
            <div class="guest_addon">
            </div>
        </div>
    </div>
    <div class="addguest gsl_button"><i class="fa fa-plus"></i><span gstype='bookingtranslation' gstranslationfield='addGuest'></span></div>
</div>


<div class="productentry" id="productentrybox">
    <div class='productentry_gallery gsgalleryroot'>
        <i class="fa fa-times"></i>
        <div class="feature">
            <figure class="featured-image image-holder gsgallery" galidx="" width="300" height="300" index="0"></figure>
        </div>
        <span class="photoswipecontainer"></span>
        <div class="gallery-wrapper">
            <div class="gallery"></div>
        </div>
    </div>
    <div class="productentry_main">
        <div class="productentry_header">
            <div class="roomname"></div>
            <div style="float:right;"><span gstype='bookingtranslation' gstranslationfield='startingAt'></span><span class='lowpricedisplayer'></span>,-</div>
            <div class="product_availablerooms" value=""><span gstype='bookingtranslation' gstranslationfield='availableRooms'></span><span class='availableroomcontainer'></span></div>
        </div>
        <div class="productentry_body">
            <div class="guestselection"></div>
            <div class="roomdescription"></div>
            <div></div>
        </div>
        <div class="productentry_footer">
        </div>
    </div>
    <div style="clear:both;"></div>
</div>

<div class="guestentry" id="addnewguest">
    <div><input type="text">
    </div><div><input type="text">
    </div><div><input type="text"  class="guest_phone" value="+47"><input type="text" style="width:75%;">
    </div><div><div class="guest_addon">
        <i class="fa fa-sign-in" title="Early check in"></i>
        <i class="fa fa-cutlery" title="Breakfast"></i>
        <i class="fa fa-black-tie" title="Coat for one person"></i>
        <i class="fa fa-sign-out" title="Late check out"></i><i class="fa fa-times removeguest" title="Remove guest"></i>
    </div></div>
</div>


<link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
<script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" media="all" href="/js/daterangepicker/daterangepicker.css" />
<script type="text/javascript" src="/js/daterangepicker/moment.js"></script>
<script type="text/javascript" src="/js/daterangepicker/daterangepicker.js"></script>
<script>
    
//Reset page on load.
    localStorage.setItem('gslcurrentpage','');
    $('.gslbookingBody').hide();
    $('.addons_overview').hide();
    
    setBookingTranslation();
    setDatePicker();
</script>
