<div class="header">
    <div class='logo'></div>
    <div class='headerinfo'>
        <div class='maintitle'>Sylinder- og nøkkelbestilling</div>
        <div class='date'>Dato - <? echo date("d.m.y"); ?></div>
    </div>
</div>

<div class='orderpage order_page1' pageNumer='1'>
    <div class="pagetitle">Informasjon om rekvirent</div>

    <div class='col col1'>
        
        <table>
            <tr><td class='td_col_1'>Navn*</td><td><input type='text'/></td></tr>
            <tr><td>Epost*</td><td><input type='text'/></td></tr>
            <tr><td>Mobiltelefon*</td><td><input type='text'/></td></tr>
        </table>

        Informasjon til systemavdelingen
        <br/><textarea></textarea>
    </div>
    <div class='col col2'>
        <table>
            <tr><td class='td_col_1'>Org. Nr / Fødselsdato*</td><td><input type='text'/></td></tr>
            <tr><td>Navn / Firma*</td><td><input type='text'/></td></tr>
            <tr><td>Adresse*</td><td><input type='text'/></td></tr>
            <tr><td>Postnr / Sted*</td><td><input type='text'/></td></tr>
            <tr><td>Referanse*</td><td><input type='text'/></td></tr>
            <tr><td>Mobiltelefon*</td><td><input type='text'/></td></tr>
            <tr><td>E-post adresse</td><td><input type='text'/></td></tr>
            <tr><td>Kundenr</td><td><input type='text'/></td></tr>
        </table>

        <input type='checkbox'/> Leveringsaddresse lik fakturaaddresse

        Leveringsadresse
        <table>
            <tr><td class='td_col_1'>Navn / Firma*</td><td><input type='text'/></td></tr>
            <tr><td>Adresse*</td><td><input type='text'/></td></tr>
            <tr><td>Postnr / Sted*</td><td><input type='text'/></td></tr>
            <tr><td>Mobiltelefon*</td><td><input type='text'/></td></tr>
            <tr><td>E-post adresse</td><td><input type='text'/></td></tr>
        </table>
    </div>

    <div class='button_area'>
        <div class='shop_button next'>Neste</div>
    </div>
</div>


<div class='orderpage order_page2'  pageNumer='2'>
    <div class="pagetitle">Forsendelse</div>
    <div class='col col1'>
        <input type='radio' name="shippingtype" value='MyPack'/> MyPack
        <br/><input type='radio' name="shippingtype" gs_value='1' value='Bedriftspakke'/> Bedriftspakke
        <br/><input type='radio' name="shippingtype" gs_value='2' value='Rekommandert' /> Rekommandert
        <br/><input type='radio' name="shippingtype" gs_value='3' value='Express over natt' /> Express over natt
        <br/><input type='radio' name="shippingtype" gs_value='4' value='Hentes i butikk' /> Hentes i butikk
        <br/><input type='radio' name="shippingtype" gs_value='5' value='Annet leveringsmåte' /> Annet leveringsmåte
    </div>
    <div class='col col2'>
        <div class="select_stores">
            Velg butikk
            <table>
                <tr><td><input type='radio' name="selectedstore" /> Tromsø</td><td><input type='radio' name="selectedstore" /> Moss</td></tr>
                <tr><td><input type='radio' name="selectedstore" /> Trondheim</td><td><input type='radio' name="selectedstore" /> Fredrikstad</td></tr>
                <tr><td><input type='radio' name="selectedstore" /> Bergen</td><td><input type='radio' name="selectedstore" /> Halden</td></tr>
                <tr><td><input type='radio' name="selectedstore" /> Stavanger</td><td><input type='radio' name="selectedstore" /> Gjøvik</td></tr>
                <tr><td><input type='radio' name="selectedstore" /> Kristiansand</td><td><input type='radio' name="selectedstore" /> Hamar</td></tr>
                <tr><td><input type='radio' name="selectedstore" /> Sandefjord</td><td><input type='radio' name="selectedstore" /> Kongsvinger</td></tr>
                <tr><td><input type='radio' name="selectedstore" /> Drammen</td><td><input type='radio' name="selectedstore" /> Lillehammer</td></tr>
                <tr><td><input type='radio' name="selectedstore" /> Asker</td><td><input type='radio' name="selectedstore" /> Otta</td></tr>
                <tr><td><input type='radio' name="selectedstore" /> Bærum</td><td><input type='radio' name="selectedstore" /> Gardermoen</td></tr>
                <tr><td><input type='radio' name="selectedstore" /> Oslo</td><td></td></tr>
            </table>
        </div>

        <div class="specialsending">
            <textarea placeholder="Oppgi ekstrainformasjon om forsendelsen"></textarea>
        </div>
    </div>
    
    <div class='button_area'>
        <div class='shop_button prev'>Tilbake</div>
        <div class='shop_button next'>Neste</div>
    </div>
</div>


<div class='orderpage order_page3'  pageNumer='3'>
    <div class="pagetitle">Nøkler og Sylindrer</div>

    <div class='col col_0'>
        Vennligst velg hva du ønsker
        <br/>
        <input class='keyandcylinders' gs_value='1' type='checkbox' value='keys'/> Nøkler
        <br/><input class='keyandcylinders' gs_value='2' type='checkbox' value='cylinders'/> Sylindrer
    </div>

    <div class='col col_0 keys_setup'>
        Legg til nøklene
        <table>
            <tr><th>Systemnr.</th><th>Antall</th><th>Merking</th></tr>
            <tr class='keys_template_row'><td><input type='textfield'></td><td><input type='textfield'></td><td><input type='textfield'></td></tr>
            <tr><td><input type='textfield'></td><td><input type='textfield'></td><td><input type='textfield'></td></tr>
        </table>
        <div class='shop_button add_key_row'>
            +1 Linje
        </div>
    </div>
    <div class='col col_0 cylinder_setup'>
        Legg til sylindrer
        <table>
            <tr>
                <th>Systemnr.</th>
                <th>Antall</th>
                <th>Type sylinder</th>
                <th>Dørtykkelse</th>
                <th>Merking</th>
                <th>Lik sylinder</th>
                <th>Overflate</th>
                <th>Beskrivelse i låsplan</th>
            </tr>
            <tr class='cylinder_template_row'>
                <td><input type='textfield'></td>
                <td><input type='textfield'></td>
                <td><input type='textfield'></td>
                <td>dropboxes</td>
                <td><input type='textfield'></td>
                <td><input type='textfield'></td>
                <td>
                    <select>
                        <option>Overflate</option>
                        <option>Forkrommet matt</option>
                        <option>Forkrommet</option>
                        <option>Messing matt</option>
                        <option>Annen* Må beskrives i info felt</option>
                    </select>
                </td>
                <td><input type='textfield'></td>
            </tr>
            <tr >
                <td><input type='textfield'></td>
                <td><input type='textfield'></td>
                <td><input type='textfield'></td>
                <td>dropboxes</td>
                <td><input type='textfield'></td>
                <td><input type='textfield'></td>
                <td>
                    <select>
                        <option>Overflate</option>
                        <option>Forkrommet matt</option>
                        <option>Forkrommet</option>
                        <option>Messing matt</option>
                        <option>Annen* Må beskrives i info felt</option>
                    </select>
                </td>
                <td><input type='textfield'></td>
            </tr>
        </table>
        <div class='shop_button add_cylinder_row'>
            +1 Linje
        </div>
    </div>
    
    <div class='button_area'>
        <div class='shop_button prev'>Tilbake</div>
        <div class='shop_button next'>Neste</div>
    </div>
</div>

<div class='orderpage order_page4'  pageNumer='4'>    
    <div class="pagetitle">Sikkerhetsprosedyre</div>
    
    <div class='col col_0'>
    
        Velg ønsket sikkerhetsprosedyre
        <br/><input type='radio' name='security' gs_value='1' value='pincode'/> Pinkode
        <br/><input type='radio' name='security' gs_value='2' value='signature'/>Signatur

        <div class='pincodesetup'>
            Pinkode:
            <br/><input type='text'/>
            <br/>
            <br/>
            Send kvittering til e-mail
            <br/> <input type='text'/>
            <br/>
            
        </div>

        <div class='signaturesecurity'>
            Skannes og sendes til system@certego.no eller post
            <br/>Certego AS, Postboks 454, 3002 Drammen
            <br/>
            <br/>
            Send kvittering til e-mail
            <br/> <input type='text'/>
        </div>
    </div>
    
    <div class='button_area'>
        <div class='shop_button prev'>Tilbake</div>
        <div class='shop_button next' style='display: none'> Neste </div>
    </div>
</div>