<?
/* @var $this \ns_7004f275_a10f_4857_8255_843c2c7fb3ab\LasGruppenOrderSchema */
?>
<div class='orderpage order_page1' pageNumer='1'>
    
    <?
    
    if (!\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()) {
    ?>
        <div class="certego_pagetitle">Kontaktinformasjon
            <div class='stepof'>Steg 1 / 4</div>
        </div>
        <div class="certego_login">
            <div class='loginform'>
                <input type='textfield' placeholder='brukernavn' class='username'/>
                <input type='password' placeholder='passord' class='password'/>
                <div class='certego_login_button dologin'><i class="fa fa-play"></i></div>
            </div>
            <div class='loginform_picode'>
                <div >
                    <center>
                        Tast inn din personlige pinkode, <br/>dersom du ikke har den kan du bestille <br/> ny ved å trykke på "bestill ny kode"    
                    </center>
                </div>
                
                <br/>
                <div>
                    <div class='certego_login_button request_new_pincode'>Bestill ny kode</div>
                    <input type='password' placeholder='pincode' class='pincode'/>             
                    <div class='certego_login_button signin'><i class="fa fa-play"></i></div>
                </div>
            </div>
            <div>
                <div class='shop_button login_button'>
                    <i class="fa fa-key"></i> Logg inn
                </div>
            </div>
        </div>
    <?
    } else {
    ?>
        <div class="certego_login certego_logout">
            <div>
                <div class='shop_button logout_button'>
                    <i class="fa fa-key"></i> Logg ut
                </div>
            </div>
        </div>
    <?
    }
    
    if (\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()) {
        echo "<div class='welcomepagecontent'>";
        $this->includefile("welcome");
        echo "</div>";
    } else {
        $this->includefile("page1notloggedin");        
    }
?>
    
    
</div>


<!-- PAGE 2 -->
<div class='orderpage order_page2'  pageNumer='2'>
    <?
    $this->includefile('systemschema');
    ?>
</div>





<!-- PAGE 3 -->

<div class='orderpage order_page3'  pageNumer='3'>
    <div class="certego_pagetitle">Forsendelse
        <div class='stepof'>Steg 3 / 4</div>
    </div>
    <div class='col col1' radio_required='true'>
        <div class="shipping_div_option" id="shipping_bedriftspakke"><input type='radio' name="shippingtype" gs_value='1' value='Bedriftspakke'/> Bedriftspakke</div>
        <div class="shipping_div_option" id="shipping_express"><input type='radio' name="shippingtype" gs_value='3' value='Express over natt' /> Express over natt</div>
        <div class="shipping_div_option" id="shipping_service"><input type='radio' name="shippingtype" gs_value='6' value='Servicepakke' /> Servicepakke</div>
        <div class="shipping_div_option" id="shipping_rekomandert"><input type='radio' name="shippingtype" gs_value='2' value='Rekommandert' /> Rekommandert</div>
        <div class="shipping_div_option" id="shipping_store"><input type='radio' name="shippingtype" gs_value='4' value='Hentes i butikk' /> Hentes i butikk</div>
        <div class="shipping_div_option" id="shipping_other"><input type='radio' name="shippingtype" gs_value='5' value='Annet leveringsmåte' /> Annen leveringsmåte</div>
    </div>
    <div class='col col2'>
        <div class="select_stores" radio_required='true'>
            Velg butikk
            <table>
                <tr><td><input type='radio' name="selectedstore" value="Tromsø"/> Tromsø</td><td><input type='radio' name="selectedstore" value="Moss"/> Moss</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Trondheim"/> Trondheim</td><td><input type='radio' name="selectedstore" value="Fredrikstad"/> Fredrikstad</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Bergen"/> Bergen</td><td><input type='radio' name="selectedstore" value="Halden"/> Halden</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Stavanger"/> Stavanger</td><td><input type='radio' name="selectedstore" value="Gjøvik"/> Gjøvik</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Kristiansand"/> Kristiansand</td><td><input type='radio' name="selectedstore" value="Hamar"/> Hamar</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Sandefjord"/> Sandefjord</td><td><input type='radio' name="selectedstore" value="Kongsvinger"/> Kongsvinger</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Drammen"/> Drammen</td><td><input type='radio' name="selectedstore" value="Lillehammer"/> Lillehammer</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Asker"/> Asker</td><td><input type='radio' name="selectedstore" value="Otta"/> Otta</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Bærum"/> Bærum</td><td><input type='radio' name="selectedstore" value="Gardermoen"/> Gardermoen</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Oslo"/> Oslo</td><td></td></tr>
            </table>
            <div>
                <b>Informasjon om person som skal hente i butikk</b>
                <table>
                    <tr><td>Navn*</td><td><input type='text' required='true' id='store_deliver_name'/></td></tr>
                    <tr><td>Mobiltelefon*</td><td><input type='text' required='true' type_number='true' id='store_delivery_cellphone'/></td></tr>
                </table>
            </div>
        </div>

        <div class="extratext_shipping extratext_shipping_1">
            <? echo nl2br($this->getConfigurationSetting("page3_shippinginformation_bedriftspakke")); ?>
        </div>
        
        <div class="extratext_shipping extratext_shipping_2">
            <? echo nl2br($this->getConfigurationSetting("page3_shippinginformation_rekommandert")); ?>
         </div>
        
        <div class="extratext_shipping extratext_shipping_3">
            <? echo nl2br($this->getConfigurationSetting("page3_shippinginformation_express")); ?>
        </div>
        
        <div class="extratext_shipping extratext_shipping_6">
            <? echo nl2br($this->getConfigurationSetting("page3_shippinginformation_service")); ?>
        </div>
        
        <div class="specialsending">
            <textarea id="shipment_extra_description" placeholder="Oppgi ekstrainformasjon om forsendelsen"></textarea>
        </div>
    </div>
    <div class='shippinginformation' style="border-top: solid 1px #DDD;">
            <div class='col col1 deliveryinformationdiv'>
            <?
            if (\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject() != null) {
                echo "<div class='selectbox_del_addresses'>";
                $this->includefile('address_select_box');
                echo "</div>";
            } else {
            ?>
            <input type='checkbox' id='samedeliveryasinvoice'/> Leveringsaddresse lik fakturaaddresse
            <? } ?>
            <table>
                <tr><td class='td_col_1' colspan='2'><b>Leveringsaddresse</b></td></tr>
                <tr><td class='td_col_1'>Navn / Firma*</td><td><input required='true' type='text' id="delivery_company_name"/></td></tr>
                <tr><td>Adresse*</td><td><input type='text' required='true' id="delivery_address"/></td></tr>
                <tr><td>Adresse2</td><td><input type='text' id="delivery_address2"/></td></tr>
            </table>
        </div>

        <div class='col col2 deliveryinformationdiv'>
            <table>
                <tr><td>Postnr*</td><td><input type='text' required='true' id="delivery_postcode"/></td></tr>
                <tr><td>Sted*</td><td><input type='text' required='true' id="delivery_city"/></td></tr>
                <tr><td>Mobiltelefon*</td><td><input type='text' required='true' type_number="true" id="delivery_cellphone"/></td></tr>
                <tr><td>E-post adresse</td><td><input type='text' id="delivery_emailaddress" type_email='true'/></td></tr>
            </table>
        </div>
    </div>
    
    <div class='button_area'>
        <div class='shop_button prev'>Tilbake</div>
        <div class='shop_button next'>Neste</div>
    </div>
</div>





<!---- PAGE 5 ---->
<div class='orderpage order_page4'  pageNumer='4'>    
    <div class="certego_pagetitle">
        <span>Sikkerhetsprosedyre</span>
        <div class='stepof'>Steg 4 / 4</div>
    </div>
    
    <div class='col col_1 nosecurityneeded'>
        Din bestilling er nå klar til å sendes.
        
        <br/>
        <br/>
        Send kvittering til e-mail
        <br/> <input type='text' style='width: 300px;' class="send_copy_email"/>
    </div>
    
    <div class='col col_1 securityneeded'>
    
        Velg ønsket sikkerhetsprosedyre
        <br/><input type='radio' name='security' gs_value='1' value='pincode' id='pincode'/> Pinkode
        <br/><input type='radio' name='security' gs_value='2' value='signature' id='signature'/>Signatur

        <div class='pincodesetup'>
            Pinkode:
            <br/><input type='text' style='width: 300px;' id='pincode_textfield'/>
            <br/>
            <br/>
            Send kvittering til e-mail
            <br/> <input type='text' style='width: 300px;' class="send_copy_email"/>
            <br/>
        </div>

        <div class='signaturesecurity'>
            Skannes og sendes til system@certego.no eller post
            <br/>Certego AS, Postboks 454, 3002 Drammen
            <br/>
        </div>
    </div>
    
    <div class='col col_2'>
        <textarea id="order_extra_info" placeholder='Informasjon til systemavdelingen'></textarea>
    </div>
    <div class='button_area'>
        <div class='shop_button prev'>Tilbake</div>
        <div class='shop_button next' style='display: none'>Neste</div>
    </div>
</div>

<div class='orderpage order_page5'  pageNumer='5'>    
    <div class="certego_pagetitle">
        Bekreftelse
    </div>
    
    <div class='col col_0'>
    Din bestilling er nå sendt til CERTEGO AS for videre behandling.
    <br/>
    <br/>Normal leveringstid er 5 – 7 virkedager
    <br/>
    <div id='email_copy_sent_to'>
        Kopi av bestillingen er sendt til følgende e-post adresse <span></span>
    </div>

    <br/>
    <br/>
    <b>Vil du sende kopi til annen adresse</b>
    <br/><input type='text' style='width: 300px;'/>
    <br/>
    <br/>
    <div class='button_area'>
        <div class='shop_button next'>Fullfør</div>
    </div>
    </div>
</div>

<div class='orderpage order_page6'  pageNumer='6'>
    <div class='col col_0'>
        <center><h1>Takk for din henvendelse </h1></center>
        <br/>
        <br/>
        <center><div class='shop_button' onclick="document.location = '/'">Hjem</div></center>
    </div>
</div>