<?
/* @var $this \ns_7004f275_a10f_4857_8255_843c2c7fb3ab\LasGruppenOrderSchema */
$system = $this->getSelectedSystem();
        
$systemnumber = "";
$systemname = "";
$systememail = "";
$systemcellphone = "";

if (count($system)) {
    $systemnumber = 'disabled="true" value="'.$system->number.'"'; ;
    $systemname = 'disabled="true" value="'.$system->name.'"'; ;
    $systememail = 'disabled="true" value="'.$system->phoneNumber.'"'; ;
    $systemcellphone = 'disabled="true" value="'.$system->email.'"'; ;
}

?>

<div class='orderpage order_page1' pageNumer='1'>
    <div class="certego_pagetitle">Kontaktinformasjon
        <div class='stepof'>Steg 1 / 4</div>
    </div>
    <?
    
    if (!\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()) {
    ?>
        <div class="certego_login">
            <div class='loginform'>
                <input type='textfield' placeholder='brukernavn' class='username'/>
                <input type='password' placeholder='passord' class='password'/>
                <div class='certego_login_button dologin'><i class="fa fa-play"></i></div>
            </div>
            <div class='loginform_picode'>
                <div >
                    <center>
                        Tast inn din personlige pinkode, <br/>dersom du ikke har den kan du bestille <br/> ny ved å trykke på "bestill ny kode"    
                    </center>
                </div>
                
                <br/>
                <div>
                    <div class='certego_login_button request_new_pincode'>Bestill ny kode</div>
                    <input type='password' placeholder='pincode' class='pincode'/>             
                    <div class='certego_login_button signin'><i class="fa fa-play"></i></div>
                </div>
            </div>
            <div>
                <div class='shop_button login_button'>
                    <i class="fa fa-key"></i> Logg inn
                </div>
            </div>
        </div>
    <?
    } else {
    ?>
        <div class="certego_login">
            <div>
                <div class='shop_button logout_button'>
                    <i class="fa fa-key"></i> Logg ut
                </div>
            </div>
        </div>
        
    <?
    }
    ?>
    

    <div>
        <div class='col col1'>
            <table>
                <tr><td class='td_col_1' colspan='2'><b>Informasjon om rekvirent</b></td></tr>
                <tr><td class='td_col_1'>Systemnummer*</td><td><input class='systemnumber_uppercase' required='true' type='text'id="main_system_number" <? echo $systemnumber; ?>/></td></tr>
                <tr><td class='td_col_1'>Navn*</td><td><input required='true' type='text' id="main_name" <? echo $systemname;?> /></td></tr>
                <tr><td>Epost*</td><td><input required='true' type='text' type_email='true' id="main_email" <? echo $systememail;?> /></td></tr>
                <tr><td>Mobiltelefon*</td><td><input required='true' type='text' type_number='true' id="main_cell" <? echo $systemcellphone;?> /></td></tr>
            </table>
        </div>
    </div>
    <div style='border-top: solid 1px #DDD;'>
        <div class='col col1'>
            <table>
                <tr><td class='td_col_1' colspan='2'><b>Fakturainformasjon</b></td></tr>
                <tr><td class='td_col_1'>Org. Nr / Fødselsdato*</td><td><input required='true' type='text' id="companyid" type_number='true'/></td></tr>
                <tr><td>Navn / Firma*</td><td><input id="invoice_company_name" required='true' type='text'/></td></tr>
                <tr><td>Adresse*</td><td><input id="invoice_address" required='true' type='text'/></td></tr>
                <tr><td>Postnr / Sted*</td><td><input id="invoice_postcode" required='true' type='text'/></td></tr>
            </table>
        </div>

        <div class='col col2'>
            <table>
                <tr><td class='td_col_1' colspan='2'><b>&nbsp;</b></td></tr>
                <tr><td>Referanse*</td><td><input required='true' type='text' id="invoice_reference"/></td></tr>
                <tr><td>Mobiltelefon*</td><td><input id="invoice_cellphone" required='true' type_number='true' type='text'/></td></tr>
                <tr><td>E-post adresse</td><td><input type='text'id="invoice_emailaddress" type_email='true'/></td></tr>
                <tr><td>Kundenr</td><td><input type='text' id="invoice_cusomer_number"/></td></tr>
            </table>
        </div>
    </div>
    
    <div class='button_area'>
        <div class='shop_button next'>Neste</div>
    </div>
</div>


<!-- PAGE 2 -->
<div class='orderpage order_page2'  pageNumer='2'>
    <div class="certego_pagetitle">
        Nøkler og Sylindrer
        <div class='stepof'>Steg 2 / 4</div>
    </div>

    <div class='col col_1'>
        Vennligst velg hva du ønsker
        <br/>
        <input id='selection_key' class='keyandcylinders' gs_value='1' type='checkbox' value='keys'/> Nøkler
        <br/><input class='keyandcylinders' id='cylindersoption' gs_value='2' type='checkbox' value='cylinders'/> Sylindrer
        
    </div>
    
    <div class='col col_2'>
        Fyll ut informasjon om nøkler og sylindrer så nøyaktig som mulig.
        <br/>Hvis nødvendig kan utfyllende informasjon legges i feltet Informasjon til systemavdelingen på siste side (Steg 4/4).
    </div>
    
    

    <div class='col col_0 keys_setup'>
        Legg til nøklene
        <table id="keys_setup_table">
            <tr><th>Systemnr.</th><th>Antall</th><th>Merking</th></tr>
            <tr class='keys_template_row'><td><input type='textfield' class="systemnumber systemnumber_uppercase"></td><td><input type='textfield' class="keys_count"></td><td><input class="keys_marking" type='textfield'></td></tr>
        </table>
        <div class='shop_button add_key_row'>
            +1 Linje
        </div>
    </div>
    <div class='col col_0 cylinder_setup'>
        Legg til sylindrer
        <table>
            <tr>
                <th>Systemnr.</th>
                <th>Antall</th>
                <th>Type sylinder</th>
                <th>Dørtykkelse</th>
                <th>Angi hvilke nøkler som skal passe</th>
                <th>Overflate</th>
                <th>Beskrivelse i låsplan</th>
            </tr>
            <tr class='cylinder_template_row'>
                <td><input type='textfield' class="systemnumber systemnumber_uppercase"></td>
                <td><input type='textfield' style="width: 25px;" class='cylinder_count'></td>
                <td><input type='textfield' class='cylinder_type'></td>
                <td><input type='textfield' class='door_thickness'></td>
                <td><input type='textfield' style="width: 240px" class='keys_that_fits'></td>
                <td>
                    <select class='texture'>
                        <option value='overflate'>Overflate</option>
                        <option value='Forkrommet matt'>Forkrommet matt</option>
                        <option value='Forkrommet'>Forkrommet</option>
                        <option value='Messing matt'>Messing matt</option>
                        <option value='Messing polert'>Messing polert</option>
                        <option value='Sort rustikk'>Sort rustikk</option>
                    </select>
                </td>
                <td><input type='textfield' class='cylinder_description'></td>
            </tr>
        </table>
        <div class='shop_button add_cylinder_row'>
            +1 Linje
        </div>
    </div>
    
    <div class='button_area'>
        <div class='shop_button prev'>Tilbake</div>
        <div class='shop_button next'>Neste</div>
    </div>
</div>





<!-- PAGE 3 -->

<div class='orderpage order_page3'  pageNumer='3'>
    <div class="certego_pagetitle">Forsendelse
        <div class='stepof'>Steg 3 / 4</div>
    </div>
    <div class='col col1' radio_required='true'>
        <div class="shipping_div_option" id="shipping_bedriftspakke"><input type='radio' name="shippingtype" gs_value='1' value='Bedriftspakke'/> Bedriftspakke</div>
        <div class="shipping_div_option" id="shipping_rekomandert"><input type='radio' name="shippingtype" gs_value='2' value='Rekommandert' /> Rekommandert</div>
        <div class="shipping_div_option" id="shipping_express"><input type='radio' name="shippingtype" gs_value='3' value='Express over natt' /> Express over natt</div>
        <div class="shipping_div_option" id="shipping_store"><input type='radio' name="shippingtype" gs_value='4' value='Hentes i butikk' /> Hentes i butikk</div>
        <div class="shipping_div_option" id="shipping_other"><input type='radio' name="shippingtype" gs_value='5' value='Annet leveringsmåte' /> Annen leveringsmåte</div>
    </div>
    <div class='col col2'>
        <div class="select_stores" radio_required='true'>
            Velg butikk
            <table>
                <tr><td><input type='radio' name="selectedstore" value="Tromsø"/> Tromsø</td><td><input type='radio' name="selectedstore" value="Moss"/> Moss</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Trondheim"/> Trondheim</td><td><input type='radio' name="selectedstore" value="Fredrikstad"/> Fredrikstad</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Bergen"/> Bergen</td><td><input type='radio' name="selectedstore" value="Halden"/> Halden</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Stavanger"/> Stavanger</td><td><input type='radio' name="selectedstore" value="Gjøvik"/> Gjøvik</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Kristiansand"/> Kristiansand</td><td><input type='radio' name="selectedstore" value="Hamar"/> Hamar</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Sandefjord"/> Sandefjord</td><td><input type='radio' name="selectedstore" value="Kongsvinger"/> Kongsvinger</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Drammen"/> Drammen</td><td><input type='radio' name="selectedstore" value="Lillehammer"/> Lillehammer</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Asker"/> Asker</td><td><input type='radio' name="selectedstore" value="Otta"/> Otta</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Bærum"/> Bærum</td><td><input type='radio' name="selectedstore" value="Gardermoen"/> Gardermoen</td></tr>
                <tr><td><input type='radio' name="selectedstore" value="Oslo"/> Oslo</td><td></td></tr>
            </table>
            <div>
                <b>Informasjon om person som skal hente i butikk</b>
                <table>
                    <tr><td>Navn*</td><td><input type='text' required='true' id='store_deliver_name'/></td></tr>
                    <tr><td>Mobiltelefon*</td><td><input type='text' required='true' type_number='true' id='store_delivery_cellphone'/></td></tr>
                </table>
            </div>
        </div>

        <div class="extratext_shipping extratext_shipping_1">
            1 – 3 dager forsendelsetid
            <br/>Se www.postnordlogistics.no for mer informasjon
            <br/>Pris fra kr 140,- eks. Mva
        </div>
        
        <div class="extratext_shipping extratext_shipping_2">
            2 – 3 dager forsendelsetid
            <br/>Se www.posten.no       
            <br/>Pris fra kr 140,- eks. Mva
         </div>
        
        <div class="extratext_shipping extratext_shipping_3">
            1 dag forsendelsetid, levert innen klokken 10:00 de fleste steder.
            <br/>Se www.postnordlogistics.no for mer informasjon
            <br/>Pris fra kr 800 ,- eks. Mva
        </div>
        
        <div class="specialsending">
            <textarea id="shipment_extra_description" placeholder="Oppgi ekstrainformasjon om forsendelsen"></textarea>
        </div>
    </div>
    <div class='shippinginformation' style="border-top: solid 1px #DDD;">
            <div class='col col1 deliveryinformationdiv'>
            <input type='checkbox' id='samedeliveryasinvoice'/> Leveringsaddresse lik fakturaaddresse

            <table>
                <tr><td class='td_col_1' colspan='2'><b>Leveringsaddresse</b></td></tr>
                <tr><td class='td_col_1'>Navn / Firma*</td><td><input required='true' type='text' id="delivery_company_name"/></td></tr>
                <tr><td>Adresse*</td><td><input type='text' required='true' id="delivery_address"/></td></tr>
            </table>
        </div>

        <div class='col col2 deliveryinformationdiv'>
            <table>
                <tr><td>Postnr / Sted*</td><td><input type='text' required='true' id="delivery_postcode"/></td></tr>
                <tr><td>Mobiltelefon*</td><td><input type='text' required='true' type_number="true" id="delivery_cellphone"/></td></tr>
                <tr><td>E-post adresse</td><td><input type='text' id="delivery_emailaddress" type_email='true'/></td></tr>
            </table>
        </div>
    </div>
    
    <div class='button_area'>
        <div class='shop_button prev'>Tilbake</div>
        <div class='shop_button next'>Neste</div>
    </div>
</div>





<!---- PAGE 5 ---->
<div class='orderpage order_page4'  pageNumer='4'>    
    <div class="certego_pagetitle">
        Sikkerhetsprosedyre
        <div class='stepof'>Steg 4 / 4</div>
    </div>
    
    <div class='col col_1 nosecurityneeded'>
        Din bestilling er nå klar til å sendes.
        
        <br/>
        <br/>
        Send kvittering til e-mail
        <br/> <input type='text' style='width: 300px;' class="send_copy_email"/>
    </div>
    
    <div class='col col_1 securityneeded'>
    
        Velg ønsket sikkerhetsprosedyre
        <br/><input type='radio' name='security' gs_value='1' value='pincode' id='pincode'/> Pinkode
        <br/><input type='radio' name='security' gs_value='2' value='signature' id='signature'/>Signatur

        <div class='pincodesetup'>
            Pinkode:
            <br/><input type='text' style='width: 300px;' id='pincode_textfield'/>
            <br/>
            <br/>
            Send kvittering til e-mail
            <br/> <input type='text' style='width: 300px;' class="send_copy_email"/>
            <br/>
        </div>

        <div class='signaturesecurity'>
            Skannes og sendes til system@certego.no eller post
            <br/>Certego AS, Postboks 454, 3002 Drammen
            <br/>
        </div>
    </div>
    
    <div class='col col_2'>
        <textarea id="order_extra_info" placeholder='Informasjon til systemavdelingen'></textarea>
    </div>
    <div class='button_area'>
        <div class='shop_button prev'>Tilbake</div>
        <div class='shop_button next' style='display: none'>Neste</div>
    </div>
</div>

<div class='orderpage order_page5'  pageNumer='5'>    
    <div class="certego_pagetitle">
        Bekreftelse
    </div>
    
    <div class='col col_0'>
    Din bestilling er nå sendt til CERTEGO AS for videre behandling.
    <br/>
    <br/>Normal leveringstid er 5 – 7 virkedager
    <br/>
    <div id='email_copy_sent_to'>
        Kopi av bestillingen er sendt til følgende e-post adresse <span></span>
    </div>

    <br/>
    <br/>
    <b>Vil du sende kopi til annen adresse</b>
    <br/><input type='text' style='width: 300px;'/>
    <br/>
    <br/>
    <div class='button_area'>
        <div class='shop_button next'>Fullfør</div>
    </div>
    </div>
</div>

<div class='orderpage order_page6'  pageNumer='6'>
    <div class='col col_0'>
        <center><h1>Takk for din henvendelse </h1></center>
    </div>
</div>