
        <div>
            <div class='col col1'>
                <table>
                    <tr><td class='td_col_1' colspan='2'><b>Informasjon om rekvirent</b></td></tr>
                    <tr><td class='td_col_1'>Systemnummer*</td><td><input class='systemnumber_uppercase' required='true' type='text'id="main_system_number"/></td></tr>
                    <tr><td class='td_col_1'>Navn*</td><td><input required='true' type='text' id="main_name" /></td></tr>
                    <tr><td>Epost*</td><td><input required='true' type='text' type_email='true' id="main_email" /></td></tr>
                    <tr><td>Mobiltelefon*</td><td><input required='true' type='text' type_number='true' id="main_cell" /></td></tr>
                </table>
            </div>
        </div>
        <div style='border-top: solid 1px #DDD;'>
            <div class='col col1'>
                <table>
                    <tr><td class='td_col_1' colspan='2'><b>Fakturainformasjon</b></td></tr>
                    <tr><td class='td_col_1'>Org. Nr / Fødselsdato*</td><td><input required='true' type='text' id="companyid" type_number='true' /></td></tr>
                    <tr><td>Navn / Firma*</td><td><input id="invoice_company_name" required='true' type='text' /></td></tr>
                    <tr><td>Adresse*</td><td><input id="invoice_address" required='true' type='text' /></td></tr>
                    <tr><td>Adresse 2</td><td><input id="invoice_address2" type='text' /></td></tr>
                    <tr><td>Postnr*</td><td><input id="invoice_postcode" required='true' type='text' /></td></tr>
                    <tr><td>Sted*</td><td><input id="invoice_city" required='true' type='text' /></td></tr>
                </table>
            </div>

            <div class='col col2'>
                <table>
                    <tr><td class='td_col_1' colspan='2'><b>&nbsp;</b></td></tr>
                    <tr><td>Referanse</td><td><input type='text' id="invoice_reference" /></td></tr>
                    <tr><td>Mobiltelefon*</td><td><input id="invoice_cellphone" required='true' type_number='true' type='text' /></td></tr>
                    <tr><td>E-post adresse</td><td><input type='text'id="invoice_emailaddress" type_email='true'/></td></tr>
                    <tr><td>Kundenr</td><td><input type='text' id="invoice_cusomer_number"/></td></tr>
                </table>
            </div>
        </div>
    
        <div class='button_area'>

            <div class='shop_button next'>Neste</div>
        </div>