<div gstype="form" method="createFleet">
    <span>
        <div id="createfleetfollowup">  
            <span class="directfollowup active">Direkte oppfølging</span>
            <div class="gsniceslider1"> 
                <input type="checkbox" value="None" gsname="fleetFollowup" id="followupslider"/>
                <label for="followupslider"></label>
            </div>
            <span class="manualfollowup">Manuel oppfølging</span><br>
        </div>

        <input class="gsniceinput1" gsname="fleetName" class="checkbox" placeholder="Navn på flåteavtalen"/>
        <input class="gsniceinput1" gsname="contactName" class="checkbox" placeholder="Kontaktperson"/>
        <input class="gsniceinput1" gsname="contactEmail" class="checkbox" placeholder="E-post"/>
        <input class="gsniceinput1" gsname="contactPhone" class="checkbox" placeholder="Telefon"/>
    </span>
    <br/>
    <br/>
    <?
    if (isset($_POST['data']['fleetName']) && !$_POST['data']['fleetName']) {
        ?>
        <div class="warning"><i class="fa fa-warning"></i>Navnet kan ikke være blankt.</div><br/>
        <?
    }
    ?>
    <div class="shop_button" gstype="submit"> Opprett ny avtale </div>
</div>
<i class="fa fa-info-circle createfleetinfo" data-title="Velg om flåten skal følges opp direkte eller manuelt. Telefonnummer blir fjernet på biler ved manuel oppfølging!"></i><br>
