<div gstype="form" method="createFleet">
    <div> <input class="gsniceinput1" gsname="fleetName" class="checkbox" placeholder="Navn på flåteavtalen"/></div>
    <br/>
    <?
    if (isset($_POST['data']['fleetName']) && !$_POST['data']['fleetName']) {
        ?>
        <div class="warning"><i class="fa fa-warning"></i>Navnet kan ikke være blankt.</div><br/>
        <?
    }
    ?>
    <div class="shop_button" gstype="submit"> Opprett ny avtale </div>
</div>