<?
/* @var $this \ns_2f62f832_5adb_407f_a88e_208248117017\CompanyView */
$companies = $this->getApi()->getUserManager()->getAllCompanies();

?>
<div>
    Filter: <input class='gsniceinput1 filtercompanylist'/> | OR <div class='shop_button closeConnectToCompany'>Cancel</div>
</div>
<br/>
<?
foreach ($companies as $company) {
    ?>
    <div style='border-bottom: solid 1px #DDD; padding: 5px;' class='companyrow'>
        <div class='shop_button startconnection' gsclick='doConnection' companyid='<? echo $company->id; ?>' msgid=''>Select</div>&nbsp; <? echo $company->name; ?>
    </div>
    <?
}
?>

<div class='shop_button closeConnectToCompany' style='margin: 50px;'>Cancel</div>