<?
/* @var $this \ns_f1706b4c_f779_4eb7_aec3_ee08f182e090\GetShopInbox */
$emails = $this->getEmails();
$types = $this->getAllTypes();
?>
<div class='connectMailToCompany'>
    <?
    // Done like this as it might be case for speed improvement in future by loading
    // the companies as Ajax.
    $this->includefile("companies");
    ?>
</div>

<div class="row email header">
    <div class="col checkbox">
        <input type="checkbox" />
    </div>

    <div class="col date"><? echo $this->__f("Date"); ?></div>
    <div class="col subject"><? echo $this->__f("Subject"); ?></div>
    <div class="col from">
        <? 
        echo $this->__f("From");
        ?>
    </div>
    <div class="col company"><? echo $this->__f("Company"); ?></div>
    <div class="col timespent"><? echo $this->__f("Time spent"); ?></div>

    <div class="col icons">
        
    </div>
</div>
<?php
if(!$this->isCompletedEmails()) {
?>
    <div class='mailview'>
        <i class='fa fa-close closebox'></i>
        <div class='inner_mail_view'>
        </div>
    </div>
<?
}

foreach ($emails as $email) {
    if ($email->inSent) {
        continue;
    }
    $this->setCurrentEmail($email);
    $attachment = strstr($email->contentType, "multipart/mixed") ? '<i class="fa fa-paperclip"></i>' : "";
    $replied = $email->inSent ? '<i class=" fa fa-reply"></i>' : ""; 
    $company = $email->connectedToCompanyId ? $email->connectedToCompanyName : "<i class='gs_shop_small_icon fa fa-link connecttocompany' msgid='$email->id' title='Connect to company'></i>"; 
    ?>
    <div class="row email showemail" msgid='<? echo $email->id; ?>'>
        <div class="col checkbox">
            <input type="checkbox" class='rowcheckbox' value="<? echo $email->id; ?>"/>
        </div>
        
        <div class="col date"><? echo date('d.m.Y H:i', strtotime($email->date)); ?></div>
        <div class="col subject"><? 
        echo $email->subject . "<br>";
        echo "<span style='color:#bbb;font-style: italic;'>" . $types[$email->type] . "</span>";
        ?></div>
        <div class="col from">
            <? 
            $toPrint = str_replace(">", "", $email->from); 
            $toPrint = str_replace("<", "<br/>", $toPrint); 
            echo $toPrint;
            ?>
        </div>
        <div class="col company"><? echo $company; ?></div>
        <div class="col timespent timespentupdate" msgid="<?php echo $email->id;?>" style="padding: 10px;"><? echo $email->timeSpent; ?></div>
        
        <div class="col icons">
            <? echo $replied." ".$attachment; ?>
        </div>
        <div class='col buttons'>
            <div class='selected_checkbox_options'>
                <div class='fa fa-arrow-circle-o-down checkboxaction'></div>
                <?php
                $this->includefile("emailassignmentmenu");
                ?>
            </div>
        </div>
    </div>
    <?
}
?>