
<?
/* @var ns_f1706b4c_f779_4eb7_aec3_ee08f182e090\GetShopInbox */
?>
<div class='menu'>
    
    <div class='entry taboperation' tab='yourcases'>
        <i class='fa fa-lightbulb-o'></i>
        Your cases
    </div>
    
    <div class='entry taboperation' tab='unassigned'>
        <i class='fa fa-list'></i>
        New Tickets
    </div>
    
    <div class='entry taboperation' tab='backlog'>
        <i class='fa fa-bug'></i>
        Backlog
    </div>
    
    <div class='entry taboperation' tab='billing'>
        <i class='fa fa-info-circle'></i>
        History
    </div>
    
    <div class='entry taboperation' tab='notifications'>
        <i class='fa fa-asterisk'></i>
        Notifications
    </div>
    
    <div class='entry taboperation' tab='pretickets'>
        <i class='fa fa-hand-o-up'></i>
        Setup tickets
    </div>
    
    <div class='entry taboperation' tab='inprogress'>
        <i class='fa fa-product-hunt'></i>
        In progress
    </div>
    
    <div class='entry taboperation' tab='statistics'>
        <i class='fa fa-star'></i>
        Stats
    </div>
    
    <div class='entry taboperation' tab='search'>
        <i class='fa fa-search'></i>
        Search
    </div>
    
    <div class='entry taboperation' tab='settings'>
        <i class='fa fa-sliders'></i>
        Settings
    </div>
    
</div>