<?
/* @var $this ns_f1706b4c_f779_4eb7_aec3_ee08f182e090\GetShopInbox */
$userId = ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->id;
$user = $this->getApi()->getUserManager()->getUserById($userId);
$settings = $this->getApi()->getTicketManager()->getPushOverSettings($userId);
$checked = $settings->receiveMessagesForUnassignedTickets ? "checked='true'" : "";
?>

<div gstype="form" method="savePushOver" style='margin: 50px;'>
    <h2>Pushover</h2>
    Your user pushover token: <input gsname="pushovertoken" class="gsniceinput1" value='<? echo $user->metaData->{"pushovertoken"}; ?>'/>
    <br/> <input <? echo $checked; ?> type='checkbox' gsname='receiveMessagesForUnassignedTickets' /> Should receive messages from unassigned messages?
    <br/>
    <br/><div class='shop_button' gstype='submit'><? echo $this->__f("Save"); ?></div>
</div>