<?
/* @var $this ns_e005f6e5_221c_4b02_9b65_327a63a0af3b\AccountingAccounts */
$accounts = $this->getApi()->getProductManager()->getAccountingAccounts();
?>
<div class="distinctAccounts" gstype="form" method="saveAccountingDescription">
    
    <h2><? echo $this->__f("Accounts"); ?></h2>
    <?
    
    echo "<div class='row_description'>";
        echo "<div class='col accountingid'>".$this->__f("Account name")."</div>";
        echo "<div class='col accountindesc'>".$this->__f("Description")."</div>";
        echo "<div class='col taxcode'>".$this->__f("Tax Code")."</div>";
        echo "<div class='col subaccountid'>".$this->__f("Sub Account Id")."</div>";
        echo "<div class='col subaccountsegment'>".$this->__f("Sub Account Segment")."</div>";
    echo "</div>";

    foreach ($accounts as $account) {
        $accountName = $account->accountNumber;
        $accountDescription = $account->description;
        $accountTaxGroup = $account->taxgroup;
        $subaccountid = $account->subaccountid;
        $subaccountvalue = $account->subaccountvalue;
        
        echo "<div class='row_description'>";
            echo "<div class='col accountingid'>";
            if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isGetShopUser()) {
                echo "<i class='gs_shop_small_icon changeaccountingname fa fa-edit' oldnumber='$account->accountNumber' accountid='$accountName'></i> ";
            }
            echo "<i class='gs_shop_small_icon fa fa-trash' gs_confirm='Are you sure?' gsclick='deleteAccount' accountid='$accountName'></i> $accountName</div>";
            echo "<div class='col accountindesc'><input gsname='description_$accountName' class='gsniceinput1' value='$accountDescription'></div>";
            echo "<div class='col taxcode'><input gsname='taxcode_$accountName' class='gsniceinput1' value='$accountTaxGroup'></div>";
            echo "<div class='col subaccountid'><input gsname='subaccountid_$accountName' class='gsniceinput1' value='$subaccountid'></div>";
            echo "<div class='col subaccountvalue'><input gsname='subaccountvalue_$accountName' class='gsniceinput1' value='$subaccountvalue'></div>";
        echo "</div>";
    }
    ?>
    <br/>
    <div class="shop_button" gstype="submit"><? echo $this->__f("Save descriptions"); ?></div>
</div>

<div class='createAccountBox' gstype='form' method='createAccountingAccoutn'>
    <span>Account number: </span><input class='gsniceinput1' gsname='accountnumber'/>
    <br/><span>Description: </span><input class='gsniceinput1' gsname='accountdescription'/>
    <br/>
    <br/><div gstype='submit' class='shop_button'>Create account</div>
</div>