<?php

namespace ns_dcd22afc_79ba_4463_bb5c_38925468ae26;

/* @var $product core_productmanager_data_Product */
$product = $this->getProduct();
$weight = !isset($product) ? "" : $product->weight;
$stockQuantity = !isset($product) ? "" : $product->stockQuantity;
$taxes = !isset($product) ? "" : $product->taxes;
/* @var $this ProductManager */
$taxgroups = $this->getApi()->getProductManager()->getTaxes();
$skui = $product->sku;
?>


<div class='information_box'>
    <b><? echo $this->__f("Advanced settings"); ?></b>
    <br><? echo $this->__f("Advanced settings allows you to finetune different aspects to your product."); ?>
</div>


<div class="additional_settings" gstype="form" method="saveAdditionalSettings">
    <div class="row">
        <span class='title'><? echo $this->__f("Free shipping"); ?></span>
        <select class="config smallinput gs_product_data" data="shipping">
            <option value="false"><? echo $this->__f("No"); ?></option>
            <option value="true" <?
            if ($product->freeShipping) {
                echo "selected";
            }
            ?>><? echo $this->__f("Yes"); ?></option>
        </select>
    </div>
    <div class="row">
        <span class='title'><? echo $this->__f("Should this product listed as a featured product?"); ?></span>
        <select class="config smallinput gs_product_data" data="promoted">
            <option value="false"><? echo $this->__f("No"); ?></option>
            <option value="true" <?
            if ($product->promoted) {
                echo "selected";
            }
            ?>><? echo $this->__f("Yes"); ?></option>
        </select>
    </div>
    <div class="row">
        <span class='title'><? echo $this->__f("Hide shipping price from this product?"); ?></span>
        <select class="config smallinput gs_product_data" data="hideShippingPrice">
            <option value="false"><? echo $this->__f("No"); ?></option>
            <option value="true" <?
            if ($product->hideShippingPrice) {
                echo "selected";
            }
            ?>><? echo $this->__f("Yes"); ?></option>
        </select>
    </div>
    <div class="row">
        <span class='title'><? echo $this->__f("SKU code"); ?></span>
        <input type="txt" class="config smallinput gs_product_data" data="skui" id="skui" value="<?php echo $skui; ?>">    
    </div>

    <? if (sizeof($taxgroups) > 0) { ?>
        <div class="row">
            <span class='title'><?php echo $this->__("taxes"); ?></span>
            <select class="config smallinput taxgroup gs_product_data" data="taxgroup" id="taxgroup">
                <option value="-1"><? echo $this->__f("Not set"); ?></option>
                <?
                foreach ($taxgroups as $grp) {
                    if ($grp->groupNumber == 0) {
                        continue;
                    }

                    $selected = "";
                    if ($product->taxgroup == $grp->groupNumber) {
                        $selected = "SELECTED";
                    }
                    ?>
                    <option value="<? echo $grp->groupNumber; ?>" <? echo $selected; ?>><? echo $this->__f("Tax group") . " " . $grp->groupNumber . " (" . $grp->taxRate . "%)"; ?></option> 
    <? } ?>
            </select>
        </div>
<? } ?>
</div>
