
<?
/* @var $this ns_06f9d235_9dd3_4971_9b91_88231ae0436b\Product */
$products = $this->getAllProducts();
$type = $_POST['data']['type'];
$selectedProducts = [];
if($type == "list") {
    $entries = $this->getApi()->getListManager()->getList($_POST['data']['id']);
    if(!$entries) {
        $entries = array();
    }
    foreach($entries as $entry) {
        $selectedProducts[] = $entry->productId;
    }
}

echo "<div class='product_picker'>";
echo "<div class='picker_header'>";
if($type == "single") {
    echo $this->__f("Please select a product by clicking it");
} else if($type == "delete") {
    echo $this->__f("Select the products you would like to delete by clicking on them");
} else {
    echo "<input type='checkbox' id='display_only_selected'>" . $this->__f("Display only selected products");
}
echo "<span class='right_container'>";
echo "<input type='text' placeholder='".$this->__f("Search for a product")."'>";
if($type != "single") {
    $buttonName = "Done selecting";
    if($type == "delete") {
        $buttonName = "Delete selected products";
    }
    echo "<span class='gs_button done_selection_products'>".$buttonName."</span>";
}
echo "</span>";

echo "</div>";
echo "<div class='product_list_container'>";
foreach($products as $product) {
    echo "<div class='product_line' productid='".$product->id."'>";
    if(in_array($product->id, $selectedProducts)) {
        echo '<i class="fa fa-check"></i>';
    }
    if($product->name) {
        echo $product->name . " ";
    } else {
        echo "Untitled product";
    }
    echo "<span class='product_price'>" . $this->getFactory()->getCurrencyName() .$product->price . "</span>";
    echo "</div>";
}
echo "</div>";
echo "</div>";
?>
