<?php
namespace ns_06f9d235_9dd3_4971_9b91_88231ae0436b;

/* @var $this Product */
/* @var $factory \Factory */
$factory = $this->getFactory();
/* @var $page \core_pagemanager_data_Page */
$page = $this->getPage()->backendPage;

$title = $page->title;

if(!$title) {
    $title = $this->__f("Product title");
}

/* @var $product \core_productmanager_data_Product */
$product = $factory->getApi()->getProductManager()->getProductByPage($page->id);
$price = $product->price;
$variations = $product->variations;
?>

<h1 class='product_title'>
<? if($this->hasWriteAccess()) { ?>
    <i class="fa fa-pencil-square-o" title="<? echo $this->__f("Edit product details"); ?>"></i>
<? } ?>
    <? echo $title; ?>
</h1>

<input type='hidden' value='<? echo $product->id; ?>' id='ProductId'>

<?
foreach($variations as $variation) {
    /* @var $variation \core_productmanager_data_ProductVariation */
    echo "<select class='product_variation_selection'>";
    echo "<option value='none'>". $this->__f("Please select") ." " . $variation->title . "</option>";
    foreach($variation->children as $child) {
        /* @var $child \core_productmanager_data_ProductVariation */
        echo "<option value='".$child->id."' price='".$child->priceDifference."'>" . $child->title . "</option>";
    }
    echo "</select>";
}
?>
<span class='price'>
<? echo $this->getFactory()->getCurrencyName()."<span class='price_inner' price='".$price."'>". $price ."</span>"; ?>
</span>
<span class='buy gs_button'><? echo $this->__w("Buy"); ?></span>
<span class='gs_button save'><? echo $this->__f("Save"); ?></span>