<?php
/* @var $this ns_06f9d235_9dd3_4971_9b91_88231ae0436b\Product */
$product = $this->getApi()->getProductManager()->getProductByPage($this->getPage()->getId());
?>

<input type="hidden" id="productId" value="<? echo $product->id; ?>"/>
<div class="product_title">
    <? echo $product->name; ?>
</div>

<div class="product_price">
    <? echo ns_9de54ce1_f7a0_4729_b128_b062dc70dcce\ECommerceSettings::formatPrice($product->price); ?>
</div>

<div class="images">
    <section id="gallery">
        <div class="mainimage">
            <?
            if (isset($product->imagesAdded[0])) {
                $fistImage = $product->imagesAdded[0];
                echo "<a class='gs_ignorenavigate fluidbox' rel='sample-gallery' href='/displayImage.php?id=$fistImage'><img src='/displayImage.php?id=$fistImage'/></a>";
            } else {
                echo '<i class="fa fa-image"></i>';
            }
            ?>
        </div>

        <div class="subimages">
            <?
            $i = 0;
            $subImagesExists = false;
            foreach ($product->imagesAdded as $image) {
                if ($image == $fistImage) {
                    continue;
                }
                
                $subImagesExists = true;
                if ($i == 0) {
                    echo "<div>";
                }

                $i++;

                $class = "";
                if ($i == 1) {
                    $class = "first_in_row";
                }
                if ($i == 3) {
                    $class = "last_in_row";
                }

                echo "<div class='subimage $class'><a class='gs_ignorenavigate fluidbox' rel='sample-gallery' href='/displayImage.php?id=$image'><img src='/displayImage.php?id=$image'/></a></div>";


                if ($i == 3) {
                    $i = 0;
                    echo "</div>";
                }
            }

            if ($i != 0 && $subImagesExists) {
                $i = 0;
                echo "</div>";
            }
            ?>
        </div>
    </section>
</div>
<div class="product_contentbox">

    <div class="short_description_title"><? echo $this->__w("Short description"); ?></div>
    <div class="short_description">
        <?
        echo $product->shortDescription;
        ?>
    </div>

    <div productId='<? echo $product->id; ?>' class="shop_button addProductToCart"><? echo $this->__f("Add to cart"); ?></div>
</div>

<script>
    var parent = $('.product_contentbox').parent();
    var containerWidth = parent.innerWidth();
    var imagecontainerwidth = parent.find('.images').outerWidth();
    var contentBoxWidth = containerWidth - imagecontainerwidth - 5;
    $('.product_contentbox').outerWidth(contentBoxWidth);
    
    $(document).ready(function() {
        $('.fluidbox').fluidbox();
    });
    
</script>