<div class='gs_tabs'>
    <span class='gs_tab gs_tab_selected' target='product_basic_data'><? echo $this->__f("Basic information"); ?></span>
    <span class='gs_tab' target='product_varitions_area'><? echo $this->__f("Variations"); ?></span>
    <span class='gs_tab' target="product_attributes"><? echo $this->__f("Attributes"); ?></span>
    <span class='gs_tab' target="product_advanced"><? echo $this->__f("Advanced"); ?></span>
</div>

<div class='product_edit_area'>
    <div class='gs_tab_area gs_tab_area_active product_basic_data'>
        <? $this->includefile("basicproductdata"); ?>
    </div>

    <div class='gs_tab_area product_varitions_area'>
        <div class='information_box'>
            <b><? echo $this->__f("What is product variations?"); ?></b>
            <br><? echo $this->__f("You guessed correctly, in this panel you can setup a variation of your product. If you for instance has a product that has two different colors, you can set it up here and make your customers to specify the color before they can add it to the cart."); ?>
        </div>

        <div class="tabs" id="productvariations">
            <div class="tab_content">
                <div class='content_holder active' id='advanced'>
                    <div id='builder'></div>
                </div>
            </div>
        </div>

        <script>
            var config = <? echo json_encode($this->getProduct()->variations); ?>;
            var test = new ProductManagerVariation.MainPanel($('#builder'), config);
            app.Product.variations = test;
        </script>

    </div>

    <div class="gs_tab_area product_attributes">
        <? $this->includefile("attributeadministration"); ?>
    </div>

    <div class="gs_tab_area product_advanced">
            <? $this->includefile("edit_advancedoptions"); ?>

    </div>

</div>
<br>
<br><br>
<span class='gs_button save_product'><? echo $this->__f("Save product"); ?></span>

