<?php
/* @var $this ns_36de3b7e_e29e_4327_b3f5_7206febf4909\OcrReader */
$avtaleid = $this->getApi()->getStoreOcrManager()->getAccountingId();

$details = $this->getApi()->getInvoiceManager()->getAccountingDetails();

?>
<div style='max-width: 1600px; margin: auto;margin-top: 50px;margin-bottom: 20px;'>
    <div class="isnotactive">
        <div class="kaipal infobox">
            // faces: happy,sad,talking,danger
            
            <?php
            if(!$avtaleid) {
                ?>
                <div class="image sad"></div>
                <div class="textbox">
                    <div class="header"><? echo $this->__f("OCR scanning (for norwegian customers)"); ?></div>
                    <div class="text">
                        <?
                        echo $this->__f("OCR reading is a system for automatically marking invoices as paid when paid by bank.") . "<br>";
                        echo $this->__f("It has not been set up yet.") . "<br>";
                        ?>
                        <div class="buttonarea">
                            <div class="buttonareaheader"><? echo $this->__f("Do you have an account at nets, IT HAS TO BE EXACTLY 9 DIGITS!"); ?></div>
                            <div class="shop_button dosetaccountingid"><? echo $this->__f("Set up account (enter avtaleid)"); ?></div>
                        </div>
                    </div>
                </div>
                <?php
            } else {
                ?>
                <div class="image happy"></div>
                <div class="textbox">
                    <div class="header"><? echo $this->__f("OCR scanning (for norwegian customers)"); ?></div>
                    <div class="text">
                        <?
                        echo $this->__f("OCR reading is a system for automatically marking invoices as paid when paid by bank.") . "<br>";
                        echo $this->__f("Below you find a complete list for payments recieved.") . "<br>";
                        echo "<span style='color:blue; cursor:pointer; float:right' gstype='clicksubmitforce' method='retryConnectUnmatched'>Retry connecting unmatched orders</span>";
                        echo $this->__f("I am connected to id : $avtaleid") . ", <span style='color:blue; cursor:pointer;' gstype='clicksubmitforce' method='disconnectAccountingId' gs_prompt='Password'>disconnect</span>.<br>";
                        ?>
                    </div>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    
    <?php
    if(!$avtaleid) {
        return;
    }
    ?>
    <br><br>
    <table width='100%'>
        <tr>
            <th align='left'>Avtaleid</th>
            <th align='left'>Date</th>
            <th align='left'>TXTLINE</th>
            <th align='left'>Amount</th>
            <th align='left'>KID (kidsize)</th>
            <th align='left'>Matched to</th>
        </tr>
    <?php
    
    $transactions = $this->getApi()->getStoreOcrManager()->getAllTransactions();
    foreach($transactions as $trans) {
        $kidsize = strlen(trim($trans->kid));
        if($kidsize != $details->kidSize) {
            echo "<tr style='color:#bbb;' title='Kid size does not match configuration in invoice settings'>";
        } else {
            echo "<tr>";
        }
        echo "<td>" . $trans->avtaleId . "</td>";
        echo "<td>" . $trans->matchDate . "</td>";
        echo "<td>" . $trans->rawLine . "</td>";
        echo "<td>" . $trans->amount . "</td>";
        echo "<td>" . $trans->kid  . " ($kidsize)</td>";
        echo "<td>" . $trans->matchOnOrderId . "</td>";
        echo "</tr>";
    }
    ?>
    </table>
    
</div>