<?
/* @var $this ns_138a1b9a_d8e3_4fec_8f3f_1cae11bca54f\UserEventList */

$userId = $this->getUserId();
$events = $this->getEventsToPrint();

$mekonomenUser = false;
if ($this->isOldMode()) {
    $mekonomenUser = $this->getApi()->getMekonomenManager()->getMekonomenUser($this->getUserId());    
}

if ($mekonomenUser) {     
    foreach ($mekonomenUser->events as $event) {
        if (strtolower($event->category) == "utbildning") {
            echo "<div class='downloadrow'><div>".$event->event->eventName."</div>";
                echo "<div>".$this->__w("Date").": ". ns_d5444395_4535_4854_9dc1_81b769f5a0c3\Event::formatOnlyStartDates2($event)."</div>";
            echo "</div>";
        }
    }
    
}
if (!count($events) && !$mekonomenUser) {
    echo $this->__w("No events available");
}

foreach ($events as $event) {
    echo "<div class='downloadrow'>";
        echo "<div>".$event->bookingItemType->name."</div>";
        if (isset($event->manEvent)) {
            echo "<div>".$this->__w("Date").": ". ns_d5444395_4535_4854_9dc1_81b769f5a0c3\Event::formatOnlyStartDates($event)."</div>";
        } else {
            echo "<div>".$this->__w("Date").": ". ns_d5444395_4535_4854_9dc1_81b769f5a0c3\Event::formatMainStartDates($event)."</div>";
        }
        
        echo "<div class='downloadcertificates'>";
        $userId = $this->getUserId();
        if ($event->markedAsReady && $this->getApi()->getEventBookingManager()->canDownloadCertificate($this->getBookingEngineName(), $event->id)) {
            echo "<a class='gs_ignorenavigate' href='/scripts/promeister/download.php?eventId=$event->id&userId=$userId'><div class='gs_shop_small_icon' title='Download certificate'><i class='fa fa-download'></i></div>&nbsp;</a>";
        }
        
        if (isset($event->manEvent)) {
            foreach ($event->manEvent->files as $file ){
                $fileId = $file->fileId;
                echo "<a target='_blank' class='gs_ignorenavigate' href='/scripts/downloadExternalCertificate.php?id=$fileId&userId=$userId'><div class='gs_shop_small_icon' title='Download certificate'><i class='fa fa-download'></i></div>&nbsp;</a>";
            }
        }
        
        $user = $this->getApi()->getUserManager()->getUserWithPermissionCheck($event->currentUserId);
        if ($userId == "company")
            echo "<div>".$user->fullName."</div>";
        
        $externalCertificates = $this->getApi()->getEventBookingManager()->getExternalCertificates($this->getBookingEngineName(), $userId, $event->id);
        if ($externalCertificates) {
            foreach ($externalCertificates as $external) {
                $entry = $this->getApi()->getFileManager()->getFile($external->fileId);
                if ($entry) {
                    echo "<a onclick=\"window.open('loadFile.php?fileid=".$entry->id."')\">" ;
                    echo "<div class='gs_shop_small_icon' title='Download certificate'><i class='fa fa-download'></i></div>&nbsp;";
                    echo "</a>";
                }
            }
        }
        echo "</div>";
    echo "</div>";
}

?>
<div class=""></div>