<?
/* @var $this ns_8edb700e_b486_47ac_a05f_c61967a734b1\IntegratedPaymentTerminal */
$ids = $this->getIds();

?>

<div class='gss_settings_header'>
    <i class='fa fa-cc-visa'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <?php echo $this->getName(); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?php echo $this->getDescription(); ?>
            Configuration for verifone terminal.
        </div>
    </div>	
</div>

<div class='gss_settings_content'>
    <?php
    foreach($ids as $offset => $id) {
        $ip = $this->getConfigurationSetting("token".$offset);
    ?>
        <div class="gss_simple_shipping">
            <div class="textfield gss_setting"  id="token<?php echo $offset; ?>">
                <span class="title"><?php echo $this->__f("Token"); ?></span>
                <input type="textfield" gs_model='dibsmodel' gs_model_attr='token<?php echo $offset; ?>' value="<? echo $ip; ?>">
                <div class="description">
                    <?php  echo $this->__f("The token for the terminal $offset") . " (id:" . $id . ")"; ?> 
                </div>
            </div>
        </div>
    <?php
    }
    ?>
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="dibsmodel" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>
</div>