<?php
$notifications = array();
$notifications['booking_starting_1_day'] = "Booking starting in 1 day";
$notifications['booking_starting_2_days'] = "Booking starting in 2 days";
$notifications['booking_starting_today'] = "Booking is starting today";
$notifications['booking_completed'] = "Booking has been completed";
$notifications['booking_confirmed'] = "Booking has been confirmed";
$notifications['booking_started'] = "Booking is started";
$notifications['booking_ended'] = "Booking is ended";
$notifications['booking_ended_2_days'] = "Two days since booking ended";
?>

<h1>Booking notification system</h1>

<span class="changeview pmsbutton active" data-panel='email_notifcations'>Emails</span>
<span class="changeview pmsbutton" data-panel='sms_notifcations'>Sms'es</span>
<span class="changeview pmsbutton" data-panel='admin_notifications'>Admin messages</span>

<div gstype="form" method="saveNotifications">
    <div class='email_notifcations notificationpanel'>
        <?php
        foreach($notifications as $index => $name) {
            echo "<h2>$name</h2>";
            echo "<textarea gsname='$index' style='width: 100%; height: 400px;'></textarea>";
        }
        ?>
    </div>

    <div class='sms_notifcations notificationpanel'>
        <?php
        foreach($notifications as $index => $name) {
            echo "<h2>$name</h2>";
            echo "<textarea gsname='".$index."_sms' style='width: 100%; height: 100px;'></textarea>";
        }
        ?>
    </div>

    <div class='admin_notifications notificationpanel'>
        <?php
        foreach($notifications as $index => $name) {
            echo "<h2>$name</h2>";
            echo "<textarea gsname='".$index."_admin' style='width: 100%; height: 100px;'></textarea>";
        }
        ?>
    </div><br><br>
    <div style='text-align: right;'>
        <span class='pmsbutton' gstype='submit'>Save changes</span>
    </div>
</div>

