<?php
namespace ns_00d8f5ce_ed17_4098_8925_5697f6159f66;

/* @var $entry core_listmanager_data_Entry */
/* @var $menu ns_00d8f5ce_ed17_4098_8925_5697f6159f66\LeftMenu */
$entry = $this->getCurrentMenuEntry();
$isLastInLeft = $this->isLastInLevel() ? "last" : "";
$menu = $this;
$addSubentry = false;
$rename = false;
$dept = $menu->getDept();

$event = @$_POST['event'];
$postedId = @$_POST['data']['id'];
if ($event == "addSubEntry" && $postedId == $entry->id) {
    $addSubentry = true; //Indicates that someone wants to add a subentry to this object.
}
$setting = $this->getConfigurationSetting("disableedit");

if($event == "renameEntry" && $postedId == $entry->id) {
    $rename = true; //Someone wants to rename this entry.
}
?>
<div class="menu_<?php echo $dept; echo " "; echo $isLastInLeft; echo " "; echo "topleveldepth_".$this->getTopLevelDepth();?>">
    <?php
    $leftMenuConfig = $menu->getFactory()->getStyleSheet()->getLeftMenuSkinSettings();
    if ($menu->getSkinVariable("canUploadIcons")) {
        echo '<div class="menu_icon">';
        $height = $menu->getSkinVariable("ICON_HEIGHT");
        $width = $menu->getSkinVariable("ICON_WIDTH");
        if ($entry->imageId != "")
            echo "<img src='displayImage.php?id=" . $entry->imageId . "&width=$width&height=$height'>";
        echo '</div>';
    }
    ?>
    
    <div class="entry menuEntry droparea" after="" parentid='<?php echo $entry->id; ?>'>
        <?php
        if($this->hasWriteAccess() && $setting !== "true") {
            $this->displayMenuConfiguration($entry->id);
            echo '<span class="edit"></span>';
        }
        if($rename) {
            ?>
            <div gstype="form" method="renameEntry">
                <input type="hidden" gsname="entryId" value="<?php echo $entry->id; ?>">
                <input type="txt" gstype="submitenter" gsname="newName" placeholder="<?php echo $entry->name; ?>">
            </div>
            <?php
        } else {
            $active = "";
            if($menu->getPage()->id == $entry->pageId) {
                $active = "active";
            }
            if($entry->hardLink) {
                $link = $entry->hardLink;
                $hardlink = "hardlink='true'";
                $url = $link;
            } else {
                $hardlink = "";
                $link = "?page=".$entry->pageId;
                
                $url = \GetShopHelper::makeSeoUrl($entry->name);
            }
            echo "<a ajaxlink='".$link."' href='$url' class='".$active."' $hardlink><div class='menuName'>" . $entry->name . "</div></a>";
        }
        ?>
    </div>
    <? if(sizeof(@$entry->subentries) == 0) { ?>
        <div class="droparea droparea_split" after="<?php echo $entry->id; ?>" parentid='<?php echo $entry->parentId; ?>'></div>
    <? } ?>
</div>
<?php
if(sizeof($entry->subentries) > 0) {
    ?>
<div class="menu_<?php echo ($dept+1); ?> top_submenu_split">
        <div class="droparea droparea_split" after="" parentid='<?php echo $entry->id; ?>'></div>
</div>
    <?
    foreach($entry->subentries as $subentry) {
        $menu->displayMenuEntry($subentry, ($dept+1));
    }
    ?>
        <div class="droparea droparea_split" after="<?php echo $entry->id; ?>" parentid='<?php echo $entry->parentId; ?>'></div>
    <?
}

if($addSubentry) {
    ?>
        <div class="menu_<?php echo ($dept+1); ?>">
            <div class="entry menuEntry">
            <div gstype="form" method="addSubEntry">
                <input type="hidden" gsname="entryId" value="<?php echo $entry->id; ?>">
                <input type="txt" gstype="submitenter" gsname="newentry" placeholder="<?php echo $this->__f("Subentry name"); ?>">
            </div>
         </div>
        </div>
    <?php
}

?>