<?
namespace ns_00d8f5ce_ed17_4098_8925_5697f6159f66;
?>

<div class="droparea droparea_split" after="" parentid=''></div>

<?php
/* @var $menu LeftMenu */
$menu = $this;
$entries = $menu->getEntries();
if (sizeof($entries) > 0) {
    foreach ($entries as $entry) {
        /* @var $entry core_listmanager_data_Entry */
        $menu->displayMenuEntry($entry, 0);
    }
}
$setting = $this->getConfigurationSetting("disableedit");
if ($this->hasWriteAccess() && $setting !== "true") {
    ?>
    <div class="addmenuentrybutton systembutton">
        <?php echo $this->__f("Add Menu entry"); ?>
    </div>
    <div gstype="form" method="addEntry" class="addmenuentryform">
        <input gstype="submitenter" gsname="newentry" type="txt" placeholder="<?php echo $this->__f("Enter a menu name"); ?>">
    </div>
    <script>
        thundashop.app.LeftMenu.activateOrdering();
    </script>
    <?php
}
?>