<?
/* @var $this \ns_6dfcf735_238f_44e1_9086_b2d9bb4fdff2\VerifoneTerminal */
$app = $this->getApi()->getStoreApplicationPool()->getApplication("6dfcf735-238f-44e1-9086-b2d9bb4fdff2");
$order = $this->getCurrentOrder();

$text = isset($paymentFailed) && $paymentFailed ? $this->__f("Retry") : $this->__f("Send to terminal");
$offset = 0;
for ($offset=0; $offset<5; $offset++) {
    $ip = $app->settings->{"ipaddr$offset"}->value;
    if ($ip) {
        ?>
        <div class='shop_button' gs_callback='app.VerifoneTerminal.refresh' gsclick='sendToVerifone' verifonid='<? echo $offset; ?>' orderid='<? echo $order->id; ?>'><? echo $text; ?></div>
        <?
    }
}
?>

