<?
/* @var $this ns_d02f8b7a_7395_455d_b754_888d7d701db8\Dibs */
$ids = $this->getIds();

?>

<div class='gss_settings_header'>
    <i class='fa fa-cc-visa'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <?php echo $this->getName(); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?php echo $this->getDescription(); ?>
            Configuration for verifone terminal.
        </div>
    </div>	
</div>

<div class='gss_settings_content'>
<?php
foreach($ids as $offset => $id) {
    $ip = $this->getConfigurationSetting("ipaddr".$offset);
?>
    <div class="gss_simple_shipping">
        <div class="textfield gss_setting"  id="ipaddr<?php echo $offset; ?>">
            <span class="title"><?php echo $this->__f("Ip adress"); ?></span>
            <input type="textfield" gs_model='dibsmodel' gs_model_attr='ipaddr<?php echo $offset; ?>' value="<? echo $ip; ?>">
            <div class="description">
                <?php  echo $this->__f("The ip adress to the terminal $offset") . "(id:" . $id . ")"; ?> 
            </div>
        </div>
    </div>
<?php
}
?>
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="dibsmodel" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>
</div>