<?
/* @var $this \ns_0b9a8784_5399_415f_9d79_b1c271f3bed2\SimpleEventList */
$event = $this->getApi()->getSimpleEventManager()->getEventById($_POST['data']['eventid']);
?>
<div class="row" gstype="form" method="saveEvent">
<input type='hidden' gsname='eventid' value='<?php echo $_POST['data']['eventid']; ?>'>
<div class="col"><input class="gsniceinput1" gsname="date" value="<? echo date('d/m-Y', strtotime($event->date)); ?>"/></div>
<div class="col"><input class="gsniceinput1" gsname="name" value="<? echo $event->name; ?>"/></div>
<div class="col"><input class="gsniceinput1" gsname="location" value="<? echo $event->location; ?>"/></div>
<div class="col"><div class="shop_button" gstype="submit"><? echo $this->__f("Update"); ?></div></div>
</div>

<script>
    $('.gsniceinput1[gsname="date"]').datepicker();
</script>
