<?
/* @var $this ns_78b5c3b4_f475_40eb_aa87_171e78c24200\DayEventLister */
$events = $this->getApi()->getEventBookingManager()->getBookingsByPageId($this->getBookingEgineName(), $this->getPage()->getId(), true);

if (!count($events)) {
    echo $this->__f("No events");
    return;
}

foreach ($events as $event) {
    echo "<a href='/$event->eventPage'>".date("d / m - Y", strtotime($event->mainStartDate))."&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".date("H:i", strtotime($event->mainStartDate))." - ".date("H:i", strtotime($event->mainEndDate)). "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;". $event->location->name."</a><br/>";
}
?>