<div class="activation_area">
    <div class="infobox"><? echo $this->__f("Enter the address to your page in the field below to activate this news feed."); ?></div>
    <div class="activate_fields">
        <div><input type="text" class="activate_page" placeholder="http://www.facebook.com/getshop"></div>
        <div><span class="gs_button activatePageFeed"><? echo $this->__f("Activate news feed"); ?></span></div>
    </div>
</div>
