<?
/* @var $this ns_f7b3bfd9_0bd7_483b_abe5_01b0ff0d67db\MecaFleetUserManagement */
$fleets = $this->getApi()->getMecaManager()->getFleets();
$users = $this->getApi()->getUserManager()->getAllUsers();

$newusers = array();
foreach ($users as $user) {
    if ($user->type == 10) {
        $newusers[] = $user;
    }
}        
?>
<div style="margin-top: 50px;">
    Under ser du en liste over alle brukerene som har tilgang til flåtene sine. <br/>
    Nederst kan du legge til flere brukere.
</div>

<?
if (count($newusers)) {
?>
    <table>
        <? foreach ($newusers as $user) {
            $fleetToUse = false;
            foreach ($fleets as $fleet) {
                if (isset($user->metaData->mecafleetportalid) && $fleet->id == $user->metaData->mecafleetportalid) {
                    $fleetToUse = $fleet;
                }
            }

            $deleteIcon = '<div gsclick="deleteUser" userid="'.$user->id.'" gs_confirm="Are you sure?" class="gs_shop_small_icon"><i class="fa fa-trash"></i></div>';
            $fleetName = $fleetToUse ? $fleet->name : "";
            echo "<tr><td>$deleteIcon</td><td>".$user->fullName."</td><td>".$user->emailAddress."</td><td>$fleetName</td></tr>";
        }
        ?>
    </table>
<?
}
?>

<div gstype="form" method="createuser" style="margin-top: 50px; margin-bottom: 50px;">
    Navn på brukeren:
    <br/> <input class="gsniceinput1" type="textfield" gsname="navn" />
    <br/> Epost (brukes som brukernavn):
    <br/> <input class="gsniceinput1" type="textfield" gsname="epost" />
    <br/> Passord:
    <br/> <input class="gsniceinput1" type="textfield" gsname="passord" />
    <br/> Flåte:
    <br/> <select gsname="fleetid" class="gsniceselect1">
    <?
    foreach ($fleets as $fleet) {
        echo "<option value='$fleet->id'>$fleet->name</option>";
    }
    ?>
        </select>
        
    <br/>
    <br/>
    <div class="shop_button" gstype="submit">Opprett ny bruker</div>
</div>