<?php
$nextPage = $this->getText("next_page");

if(!$nextPage) {
    $nextPage = "/?page=booking_" . $this->getSelectedName();
}
?>
<div class="pmsfront6">
    <div class='gslbookingHeader'>
<!--        <div class="pmsfrontTheme">
            <i class="fa fa-eyedropper"></i>
        </div>-->
        <div class="fa_box date">
            <input id="date_picker" style="border-right:1px solid #ddd;" readonly>
        </div><div class='datepickermobile'>
            <div class='mobilecheckinheading'>
                <span gstype='bookingtranslation' gstranslationfield='checkin'></span>
                <input id="date_picker_start" type='date'>
            </div>
            <div class='mobilecheckoutheading'>
                <span gstype='bookingtranslation' gstranslationfield='checkout'></span>
                <input id="date_picker_end" type='date'>
            </div>

        </div><div class="fa_box guests">
            <input id="guests" value="" style="border-right:1px solid #ddd;" readonly>
            <div class="guestInfoBox">
                <div class='guestInfoBox_left'>
                    <div><span gstype='bookingtranslation' gstranslationfield='rooms'></span></div>
                    <div>
                        <span class="excludeChildSelection" gstype='bookingtranslation' gstranslationfield='adults'></span>
                        <span class="switchAdultToGuest" gstype='bookingtranslation' gstranslationfield='numberofguests'></span>
                    </div>
                    <div class="excludeChildSelection" style='top:-6px;'><span gstype='bookingtranslation' gstranslationfield='children'></span><br><span style="font-size:12px;position:absolute;left:0;"><span gstype='bookingtranslation' gstranslationfield='agebelow'></span></span></div>
                </div>
                <div class='guestInfoBox_right'>
                    <div class="inner">
                        <i id="subtract_room" class="fa fa-minus disabled"></i><input type="txt" class="count" id="count_room" value="1" readonly><i id="add_room" class="fa fa-plus"></i>
                    </div>
                    <div class="inner">
                        <i id="subtract_adult" class="fa fa-minus disabled"></i><input type="txt" class="count" id="count_adult" value="1" readonly><i id="add_adult" class="fa fa-plus"></i>
                    </div>
                    <div class="inner excludeChildSelection">
                        <i id="subtract_child" class="fa fa-minus disabled "></i><input type="txt" class="count" id="count_child" value="0" readonly><i id="add_child" class="fa fa-plus"></i>
                    </div>
                </div>
            </div>
        </div><div class="fa_box coupon">
            <input id='coupon_input' placeholder="" gstype='bookingtranslation_placeholder' gstranslationfield='discountcode'>
        </div><div class="fa_box gsl_button searchbutton" id="search_rooms" next_page='<? echo $nextPage; ?>'><span gstype='bookingtranslation' gstranslationfield='search'></span></div>
    </div>
    <div style="clear:both;"></div>
</div>
<link rel="stylesheet" type="text/css" media="all" href="/js/daterangepicker/daterangepicker.css" />
<script type="text/javascript" src="/js/daterangepicker/moment.js"></script>
<script type="text/javascript" src="/js/daterangepicker/daterangepicker.js"></script>
<script>
    getshop_setBookingTranslation();
    getshop_setDatePicker();
</script>