<?
/* @var $this ns_8dcbf529_72ae_47dd_bd6b_bd2d0c54b30a\PmsBooking */
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());

$date = date("d.m.Y", time());
$date2 = date("d.m.Y", time()+(86400*$config->minStay));
$nextPage = $this->getText("next_page");
if(!$nextPage) {
    $nextPage = "/?page=booking_" . $this->getSelectedName();
}
$rooms = $this->getApi()->getPmsManager()->getAllRoomTypes($this->getSelectedName(), $this->convertToJavaDate(time()), $this->convertToJavaDate(time()+86400));
?>

<div class="pmsfront pmsfront2">
    <span class='inputblock bedblock'>
        <i class='fa fa-bed'></i>
    </span>
    <span class='inputblock'>
        <span class='start_date dates'>
            <div><span class='inputhelpertext'><? echo $this->__w("Check in"); ?></span></div>
            <span class='dates_inner'>
                <input class='start_date_input' value='<? echo $date; ?>'></input>
                <span></span>
                <i class='fa fa-calendar start_cal'></i>
            </span>
        </span>
    </span>
    <?php if($this->getText("display_end_date") == "yes") { ?>
        <span class='inputblock'>
            <span class='end_date dates'>
                <div><span class='inputhelpertext'><? echo $this->__w("Check out"); ?></span></div>
                <span class='dates_inner'>
                    <input class='end_date_input' value='<? echo $date2; ?>'></input>
                    <span></span>
                    <i class='fa fa-calendar end_cal'></i>
                </span>
            </span>
        </span>
    <? } ?>
        
    <div class='productlist' style='display:none;'>
        <span class='inputhelpertext'><? echo $this->getText("select_product"); ?></span>
        <select class='selected_product'>
            <?php
            foreach($rooms as $room) {
                /* @var $room core_bookingengine_data_Booking */
                echo "<option value='".$room->type->id."'>";
                if($this->getText("display_prices") != "no") {
                    if($room->price > 0) {
                        echo round($room->price) . " NOK ";
                    }
                }
                echo $room->type->name . "</option>";
            }
            ?>
        </select>
        
    </div>
    
    
    <span class='inputblock bookingbuttonblock'>
        <span class='check_available_button' next_page='<? echo $nextPage; ?>'><? echo $this->__w("Continue to booking"); ?></span>
    </span>
    <div style='clear:both;'></div>
</div>

<script>
    $('.start_date_input').datepicker({ dateFormat: "dd.mm.yy", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
           var date = moment(dateText, "DD.MM.YYYY");
           var month = (moment(date).get('month')+1);
           if(month < 10) {
               month = "0" + month;
           }
           var currentEnd = $('.end_date_input').val();
           var endMoment = moment(currentEnd, "DD.MM.YYYY");

           var diff = endMoment.diff(date, "minutes");
           if(diff <= 0) {
               var day = moment(date).get('date')+2;
               if(day < 10) {
                   day = "0" + day;
               }
               $('.end_date_input').val(day + "." + month + "." + moment(date).get('year'));
           }
         }
     });
    $('.end_date_input').datepicker({ dateFormat: "dd.mm.yy", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('.start_cal').on('click', function() { $('.start_date_input').focus(); });
    $('.end_cal').on('click', function() { $('.end_date_input').focus(); });
</script>