<?php
$nextPage = $this->getText("next_page");
//$infoText = $this->getApi()->getPmsManager()->getConfiguration('info_textarea');
$infoText = $this->getConfigurationSetting('info_textarea');
if(!$nextPage) {
    $nextPage = "/?page=booking_" . $this->getSelectedName();
}
?>
<div class="pmsfront4">
    <?if($infoText  != ""){
        echo '<i id="information" class="fa fa-info-circle"></i>';
        echo '<div id="informationBox" class="infoBox">'.$infoText.'</div>';
    } ?>
    <div class="pfheader"><span gstype='bookingtranslation' gstranslationfield='bookStay'></span>!</div>
    <div style="width:100%;padding-bottom:10px;">
        <div style="width:50%;text-align: center;float:left;"><span gstype='bookingtranslation' gstranslationfield='checkin'></span></div>
        <div style="width:50%;text-align: center;float:left;"><span gstype='bookingtranslation' gstranslationfield='checkout'></span></div>
        <div class="date_pickerwrapper"><input id="date_picker" type="txt"></div>
            <div class='datepickermobile'>
                <input id="date_picker_start" type='date'>
                <input id="date_picker_end" type='date' style="float:right;">
            </div>
        </div>
    <div style="clear:both;"></div>
    
    <div class="pfbox">
        <div class="inner">
            <div gstype='bookingtranslation' gstranslationfield='rooms'></div>
            <i id="subtract_room" class="fa fa-minus disabled"></i>
            <input type="txt" class="count" id="count_room" value="1" readonly>
            <i id="add_room" class="fa fa-plus"></i>
        </div>
    </div>
    <div class="pfbox">
        <div class="inner">
            <div class="excludeChildSelection" gstype='bookingtranslation' gstranslationfield='adults'></div>
            <div class="switchAdultToGuest" gstype='bookingtranslation' gstranslationfield='numberofguests'></div>
            <i id="subtract_adult" class="fa fa-minus disabled"></i>
            <input type="txt" class="count" id="count_adult" value="1" readonly>
            <i id="add_adult" class="fa fa-plus"></i>
        </div>
    </div>
    <div class="pfbox excludeChildSelection">
        <div class="inner">
            <div gstype='bookingtranslation' gstranslationfield='children'></div>

            <i id="subtract_child" class="fa fa-minus disabled "></i>
            <input type="txt" class="count" id="count_child" value="0" readonly>
            <i id="add_child" class="fa fa-plus"></i>
        </div>
    </div>
    <div style="padding-top:60px;"><span class="showdiscountline" id="discountPrefix" style="cursor:pointer;color:#316ac5;">+ </span><span class="showdiscountline" style="cursor:pointer;color:#316ac5;" gstype='bookingtranslation' gstranslationfield='discountcode'></span></div>
    <input id="coupon_input" type="txt">
    <div class="searchbutton" next_page='<? echo $nextPage; ?>'><span gstype='bookingtranslation' gstranslationfield='search'></div>
</div>


<link rel="stylesheet" type="text/css" media="all" href="/js/daterangepicker/daterangepicker.css" />
<script type="text/javascript" src="/js/daterangepicker/moment.js"></script>
<script type="text/javascript" src="/js/daterangepicker/daterangepicker.js"></script>
<script>
    $('#information').hover(function() {
        $('#informationBox').show();
    }, function() {
        $('#informationBox').hide();
    });
    $('.showdiscountline').on('mousedown touchstart', function(){
        if($('#coupon_input').is(':visible')){
            $('#coupon_input').hide();
            $('#discountPrefix').html('+ ');
        }else{
            $('#coupon_input').show();
            $('#discountPrefix').html('- ');
        }
    });
    getshop_setBookingTranslation();
    getshop_setDatePicker();
</script>