<?
/* @var $this ns_8dcbf529_72ae_47dd_bd6b_bd2d0c54b30a\PmsBooking */
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
$engine = $this->getConfigurationSetting("booking_engine_name");
if(!isset($engine)|| $engine == ""){
    $engine = "default";
}
$appId = "class_".$this->getAppInstanceId();
$appId = str_replace("-", "_", $appId);

$date = date("d.m.Y", time());
$date2 = date("d.m.Y", time()+(86400*$config->minStay));

if($this->getAppInstanceId() == "3e91f859-ed77-4931-8e64-f3b8c6535b20") { $date2 = date("d.m.Y", time()+(7*86400)); };
if($this->getAppInstanceId() == "b10d45fa-b356-4a04-95e5-8f1ed2b2f1b8") { $date2 = date("d.m.Y", strtotime("+1 month", time())); };
if($this->getAppInstanceId() == "dca8905d-7fae-4b25-aca7-b5aa0efc4580") { $date2 = date("d.m.Y", time()+(365*86400)); };

$nextPage = $this->getText("next_page");
if(!$nextPage) {
    $nextPage = "/?page=booking_" . $this->getSelectedName();
}
?>

<div class="pmsfront pmsfront3">
    <span class='inputblock'>
        <span class='start_date dates'>
            <div><span class='inputhelpertext'><? echo $this->__w("Check in"); ?></span></div>
            <span class='dates_inner'>
                <i class='fa fa-calendar start_cal <? echo $appId;?>'></i>
                <input class='start_date_input <? echo $appId;?>' value='<? echo $date; ?>' appid="<?php echo $this->getAppInstanceId(); ?>"></input>
            </span>
        </span>
    </span>
    <?php if($this->getText("display_end_date") == "yes") { ?>
    <span class='inputblock'>
        <span class='end_date dates'>
            <div><span class='inputhelpertext'><? echo $this->__w("Check out"); ?></span></div>
            <span class='dates_inner'>
                <i class='fa fa-calendar end_cal <? echo $appId;?>'></i>
                <input class='end_date_input <? echo $appId;?>' value='<? echo $date2; ?>'></input>
            </span>
        </span>
    </span>
    <? } ?>
        
    <div class='productlist'>
        <span class='inputhelpertext'><? echo $this->getText("select_product"); ?></span>
        <div class="select_arrow"><select class='selected_product <? echo $appId;?>'></select></div>
    </div>
    
    <span class="inputblock_button">
        <div class='go_to_page_button <? echo $appId;?>' next_page='<? echo $nextPage; ?>'><? echo $this->__w("Continue to booking"); ?></div>
    </span>
    <div style='clear:both;'></div>
</div>

<script>
    $('.dates_inner input').on('focus', function(){
        $(this).siblings('i').css('background-color','#4fa7bb');
        $(this).css('background-color','#8dd4e4');
    });
    $('.dates_inner input').on('blur', function(){
        $(this).siblings('i').css('background-color','#f29400');
        $(this).css('background-color','#ffb33a');
    });
    $('.start_date_input.'+'<?echo $appId;?>').datepicker({ dateFormat: "dd.mm.yy", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
           var date = moment(dateText, "DD.MM.YYYY");
           var month = (moment(date).get('month')+1);
           var year = moment(date).get('year');
           
           var appid = $(this).attr('appid');
           var currentEnd = $('.end_date_input.'+'<?echo $appId;?>').val();
           var endMoment = moment(currentEnd, "DD.MM.YYYY");

           var diff = endMoment.diff(date, "minutes");
           if(appid === "3e91f859-ed77-4931-8e64-f3b8c6535b20") { diff -= (7*60*24); }
           if(appid === "b10d45fa-b356-4a04-95e5-8f1ed2b2f1b8") { diff -= (30*60*24); }
           if(appid === "dca8905d-7fae-4b25-aca7-b5aa0efc4580") { diff -= (800*60*24); }
           if(diff <= 0) {
               var day = moment(date).get('date')+1;
               if(appid === "3e91f859-ed77-4931-8e64-f3b8c6535b20") {
                   day = moment(date).get('date')+8;
               }
               if(appid === "b10d45fa-b356-4a04-95e5-8f1ed2b2f1b8") {
                   month = moment(date).get('month')+2;//Month
                   day = moment(date).get('date')+1;
               }
               if(appid === "dca8905d-7fae-4b25-aca7-b5aa0efc4580") {
                   month = moment(date).get('month')+2;//Month
                   day = moment(date).get('date')+1;
                   year = moment(date).get('year')+1;
               }
               if(day < 10) { day = "0" + day; }
               if(month < 10) { month = "0" + month; }
               $('.end_date_input.'+'<?echo $appId;?>').val(day + "." + month + "." + year);
           }
           loadAvailability();
         }
    });
    $('.go_to_page_button.'+'<? echo $appId;?>').click(function() {
        var appId = '<? echo $appId ?>';
        var start = $('.start_date_input.'+ appId).val();
        var end = $('.end_date_input.'+ appId).val();
        var type = $('.selected_product.'+ appId).val();
        var nextPage = $(this).attr('next_page');
        if(!type) {
            alert('No type selected');
        }
        window.location.href=nextPage+"&start=" + start + "&end=" + end + "&type=" + type;
    });
    
    $('.end_date_input.'+'<?echo $appId;?>').datepicker({ dateFormat: "dd.mm.yy", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            loadAvailability('<?echo $appId;?>','<?php echo $this->getText("rest_endpoint"); ?>');
        }
    });
    $('.start_cal.'+'<?echo $appId;?>').on('click', function() { $('.start_date_input.'+'<?echo $appId;?>').focus(); });
    $('.end_cal.'+'<?echo $appId;?>').on('click', function() { $('.end_date_input.'+'<?echo $appId;?>').focus(); });
    
    function loadAvailability(appId, endpoint) { 
        var select = $('.selected_product.'+ appId);
        var start = $('.start_date_input.'+ appId).val();
        var end = $('.end_date_input.'+ appId).val();
        var engine = '<?echo $engine;?>';
        endpoint = endpoint+"?manager=PmsWebBookingManager&method=getAllRooms&arg1="+engine+"&arg2="+start+"&arg3="+end;
        $.ajax({
            url: endpoint,
            dataType: "jsonp",
            success: function( response ) {
                console.log(response);
                var found = false;
                select.html('');
                for(var k in response) {
                    var room = response[k];
                    select.append("<option value='"+room.roomId+"'>" + room.name + "</option>");
                }
            }
        });
    }
    loadAvailability('<?echo $appId;?>','<?php echo $this->getText("rest_endpoint"); ?>');
</script>