<?
/* @var $this ns_8dcbf529_72ae_47dd_bd6b_bd2d0c54b30a\PmsBooking */
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());

$date = date("d.m.Y", time());
$date2 = date("d.m.Y", time()+(86400*$config->minStay));
$nextPage = $this->getText("next_page");
if(!$nextPage) {
    $nextPage = "/?page=booking_" . $this->getSelectedName();
}
?>

<div class="pmsfront pmsfront2">
    <span class='inputblock'>
        <span class='start_date dates'>
            <div><span class='inputhelpertext'><? echo $this->__w("Check in"); ?></span></div>
            <span class='dates_inner'>
                <input class='start_date_input' value='<? echo $date; ?>'></input>
                <span></span>
                <i class='fa fa-calendar start_cal'></i>
            </span>
        </span>
    </span>
    <?php if($this->getText("display_end_date") == "yes") { ?>
        <span class='inputblock'>
            <span class='end_date dates'>
                <div><span class='inputhelpertext'><? echo $this->__w("Check out"); ?></span></div>
                <span class='dates_inner'>
                    <input class='end_date_input' value='<? echo $date2; ?>'></input>
                    <span></span>
                    <i class='fa fa-calendar end_cal'></i>
                </span>
            </span>
        </span>
    <? } ?>
        
    <div class='productlist'>
        <span class='inputhelpertext'><? echo $this->getText("select_product"); ?></span>
        <select class='selected_product'></select>
    </div>
    
    <span class='inputblock'>
        <span class='go_to_page_button' next_page='<? echo $nextPage; ?>'><? echo $this->__w("Continue to booking"); ?></span>
    </span>
    <div style='clear:both;'></div>
</div>

<script>
    $('.start_date_input').datepicker({ dateFormat: "dd.mm.yy", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
           var date = moment(dateText, "DD.MM.YYYY");
           var month = (moment(date).get('month')+1);
           if(month < 10) {
               month = "0" + month;
           }
           var currentEnd = $('.end_date_input').val();
           var endMoment = moment(currentEnd, "DD.MM.YYYY");

           var diff = endMoment.diff(date, "minutes");
           if(diff < 0) {
               var day = moment(date).get('date')+1;
               if(day < 10) {
                   day = "0" + day;
               }
               $('.end_date_input').val(day + "." + month + "." + moment(date).get('year'));
           }
           loadAvailability();
         }
    });
    $('.go_to_page_button').click(function() {
        var start = $('.start_date_input').val();
        var end = $('.end_date_input').val();
        var type = $('.selected_product').val();
        var nextPage = $(this).attr('next_page');
        if(!type) {
            alert('No type selected');
        }
        window.location.href=nextPage+"&start=" + start + "&end=" + end + "&type=" + type;
    });
    
    $('.end_date_input').datepicker({ dateFormat: "dd.mm.yy", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            loadAvailability();
        }
    });
    $('.start_cal').on('click', function() { $('.start_date_input').focus(); });
    $('.end_cal').on('click', function() { $('.end_date_input').focus(); });
    
    function loadAvailability() {
        var start = $('.start_date_input').val();
        var end = $('.end_date_input').val();
        var endpoint = "<?php echo $this->getText("rest_endpoint"); ?>?manager=PmsWebBookingManager&method=getAllRooms&arg1=default&arg2="+start+"&arg3="+end;
        $.ajax({
            url: endpoint,
            dataType: "jsonp",
            success: function( response ) {
                console.log(response);
                var found = false;
                $('.selected_product').html('');
                for(var k in response) {
                    var room = response[k];
                    if(room.availableRooms > 0) {
                        found = true;
                        $('.selected_product').append("<option value='"+room.roomId+"'>" + room.name + " " + room.price + "kr " + "</option>");
                    }
                }
                if(!found) {
                    $('.selected_product').append("<option>No rooms available for given periode</option>");
                }
            }
        });
    }
    loadAvailability();
</script>