<?
/* @var $this ns_8dcbf529_72ae_47dd_bd6b_bd2d0c54b30a\PmsBooking */
$date = date("d.m.Y", time());
if(!$this->getText("next_page")) {
    echo "<b>Next page not set up yet, please fix.</b>";
}
$rooms = $this->getApi()->getPmsManager()->getAllRoomTypes($this->getSelectedName(), $this->convertToJavaDate(time()), $this->convertToJavaDate(time()+86400));
?>

<div class="pmsfront">
    <span class="heading">
        <? echo $this->getText("title"); ?>
    </span>
    <span class='start_date dates'>
        <div><span class='inputhelpertext'><? echo $this->getText("start_date"); ?></span></div>
        <span class='dates_inner'>
            <input class='start_date_input' value='<? echo $date; ?>'></input>
            <span></span>
            <i class='fa fa-calendar start_cal'></i>
        </span>
    </span>
    <?php if($this->getText("display_end_date") == "no") { ?>
        <span class='end_date dates'>
            <div><span class='inputhelpertext'><? echo $this->getText("end_date"); ?></span></div>
            <span class='dates_inner'>
                <input class='end_date_input' value='<? echo $date; ?>'></input>
                <span></span>
                <i class='fa fa-calendar end_cal'></i>
            </span>
        </span>
    <? } ?>
    <div style='clear:both;'></div>
    
    <div class='productlist'>
        <span class='inputhelpertext'><? echo $this->getText("select_product"); ?></span>
        <select class='selected_product'>
            <?php
            foreach($rooms as $room) {
                /* @var $room core_bookingengine_data_Booking */
                echo "<option value='".$room->type->id."'>";
                if($room->price > 0) {
                    echo $room->price . " NOK ";
                }
                echo $room->type->name . "</option>";
            }
            ?>
        </select>
        
    </div>
    
    
    <div class='infotext'>
        <? echo $this->getText("info_text"); ?>
    </div>
    <span class='check_available_button' next_page='<? echo $this->getText("next_page"); ?>'><? echo $this->getText("check_availability"); ?></span>
</div>

<script>
    $('.start_date_input').datepicker({ dateFormat: "dd.mm.yy", maxDate: "+30d", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('.end_date_input').datepicker({ dateFormat: "dd.mm.yy", maxDate: "+30d", minDate: "-1d", changeMonth: true, changeYear: true, showButtonPanel: true });
    $('.start_cal').on('click', function() { $('.start_date_input').focus(); });
    $('.end_cal').on('click', function() { $('.end_date_input').focus(); });
</script>