<div gstype="form" method="saveSettings">
    <table width="80%" class="contactConfigTable">
    <tr>
        <td width="50%">Heading text</td>
        <td width="50%"><input type="text" gsname="title" style='width:100%;' value="<? echo $this->getText("title"); ?>"></td>
    </tr>
    <tr>
        <td width="50%">Start date text</td>
        <td width="50%"><input type="text" gsname="start_date" style='width:100%;' value="<? echo $this->getText("start_date"); ?>"></td>
    </tr>
    <tr>
        <td width="50%">End date text</td>
        <td width="50%"><input type="text" gsname="end_date" style='width:100%;' value="<? echo $this->getText("end_date"); ?>"></td>
    </tr>
    <tr>
        <td width="50%">Information text</td>
        <td width="50%"><input type="text" gsname="info_text" style='width:100%;' value="<? echo $this->getText("info_text"); ?>"></td>
    </tr>
    <tr>
        <td width="50%">Check availability button</td>
        <td width="50%"><input type="text" gsname="check_availability" style='width:100%;' value="<? echo $this->getText("check_availability"); ?>"></td>
    </tr>
    <tr>
        <td width="50%">Select product list text</td>
        <td width="50%"><input type="text" gsname="select_product" style='width:100%;' value="<? echo $this->getText("select_product"); ?>"></td>
    </tr>
    <tr>
        <td width="50%">Name for booking engine to use</td>
        <td width="50%"><input type="text" gsname="booking_engine_name" style='width:100%;' value="<? echo $this->getText("booking_engine_name"); ?>"></td>
    </tr>
    <tr>
        <td width="50%">Next page to go to example: /order.html</td>
        <td width="50%"><input type="text" gsname="next_page" style='width:100%;' value="<? echo $this->getText("next_page"); ?>"></td>
    </tr>
    <tr>
        <td width="50%">Display end date</td>
        <td width="50%">
            <select gsname="display_end_date">
                <option value='yes'>Yes</option>
                <option value='no' <? if($this->getText("display_end_date") == "no") { echo "SELECTED"; } ?>>No</option>
            </select>
        </td>
    </tr>
    <tr>
        <td width="50%">Display prices</td>
        <td width="50%">
            <select gsname="display_prices">
                <option value='yes'>Yes</option>
                <option value='no' <? if($this->getText("display_prices") == "no") { echo "SELECTED"; } ?>>No</option>
            </select>
        </td>
    </tr>
    </table>
    <input gstype="submit" type="button" value='Save'>
</div>
