<div gstype="form" method="saveSettings">
    <table width="80%" class="contactConfigTable">
    <tr>
        <td width="50%"><? echo $this->__w("Heading text"); ?></td>
        <td width="50%"><input type="text" gsname="title" style='width:100%;' value="<? echo $this->getText("title"); ?>"></td>
    </tr>
    <tr>
        <td width="50%"><? echo $this->__w("Start date text"); ?></td>
        <td width="50%"><input type="text" gsname="start_date" style='width:100%;' value="<? echo $this->getText("start_date"); ?>"></td>
    </tr>
    <tr>
        <td width="50%"><? echo $this->__w("End date text"); ?></td>
        <td width="50%"><input type="text" gsname="end_date" style='width:100%;' value="<? echo $this->getText("end_date"); ?>"></td>
    </tr>
    <tr>
        <td width="50%"><? echo $this->__w("Information text"); ?></td>
        <td width="50%"><input type="text" gsname="info_text" style='width:100%;' value="<? echo $this->getText("info_text"); ?>"></td>
    </tr>
    <tr>
        <td width="50%"><? echo $this->__w("Check availability button"); ?></td>
        <td width="50%"><input type="text" gsname="check_availability" style='width:100%;' value="<? echo $this->getText("check_availability"); ?>"></td>
    </tr>
    <tr>
        <td width="50%"><? echo $this->__w("Select product list text"); ?></td>
        <td width="50%"><input type="text" gsname="select_product" style='width:100%;' value="<? echo $this->getText("select_product"); ?>"></td>
    </tr>
    <tr>
        <td width="50%"><? echo $this->__w("Name for booking engine to use"); ?></td>
        <td width="50%"><input type="text" gsname="select_product" style='width:100%;' value="<? echo $this->getText("booking_engine_name"); ?>"></td>
    </tr>
    </table>
    <input gstype="submit" type="button" value='Save'>
</div>
