<?
/* @var $this \ns_2f62f832_5adb_407f_a88e_208248117017\CompanyView */

$companies = $this->getApi()->getUserManager()->getAllCompanies();

function sortByName($a, $b) {
    return strcmp($a->name, $b->name);
}

usort($companies, 'sortByName');

$unnamedCompanies = [];

foreach ($companies as $result) {
    if($result->name == '')
    {
        array_push($unnamedCompanies, $result );
    }
    else
    {
        echo "<div class='row companysearch'>";
        echo "<div class='col companyname'>$result->name</div>";
        echo "<div class='col buttons'><div class='gs_shop_small_icon' gsclick='selectCompany' companyId='$result->id'>Select</div></div>";
        echo "</div>";
    }
}
//echo '<h1>Companies without a name</h1>';
//echo '<pre>' . print_r($unnamedCompanies,1) . '</pre>';
?>
