
<?
/* @var \ns_2f62f832_5adb_407f_a88e_208248117017\CompanyView */
?>
<div class='menu'>
    <div class='entry taboperation' tab='companylist'>
        <i class='fa fa-list'></i>
        All companies
    </div>
    <div class='entry taboperation' tab='search'>
        <i class='fa fa-search'></i>
        Search
    </div>
    <div class='entry taboperation' tab='orderlines'>
        <i class='fa fa-plus'></i>
        New
    </div>
</div>
