<div gstype='form' style='padding:5px;' method='searchForEvent' gstoarea='.currentconferences'>
    <input type='text' class='gsniceinput1' style='width:100%;box-sizing: border-box;' placeholder='Search for conference' gsname='keyword' gstype='submitenter'>
</div>
<div class='currentconferences'>
    <?php
    /* @var $this ns_3e2bc00a_4d7c_44f4_a1ea_4b1b953d8c01\PmsBookingGroupRoomView */
    $booking = $this->getPmsBooking();

    foreach($booking->rooms as $room) {
        foreach($room->guests as $guest) {
            if($guest->guestId == $_POST['data']['guestid']) {
                $userId = $booking->userId;
                $filter = new core_pmsmanager_PmsConferenceEventFilter();
                $filter->start = $this->convertToJavaDate(strtotime($room->date->start));
                $filter->end = $this->convertToJavaDate(strtotime($room->date->end));
                $filter->userId = $booking->userId;

                $events = (array)$this->getApi()->getPmsConferenceManager()->getConferenceEventsByFilter($filter);
                $this->printEvents($events, @$guest->pmsConferenceEventId);
            }
        }
    }
    ?>
</div>