<?php
/* @var $this ns_3e2bc00a_4d7c_44f4_a1ea_4b1b953d8c01\PmsBookingGroupRoomView */
$pmsBooking = $this->getPmsBooking();
$pmsSelectedRoom = $this->getPmsBookingRoom();
$user = $this->getUserForBooking();
$bookingEngineBooking = $this->getBookingEngineBooking();

$extraArgs = array();
$extraArgs['userid'] = $user->id;
if($bookingEngineBooking) {
    $extraArgs['id'] = $bookingEngineBooking->id;
}
$extraArgs['roomId'] = $pmsSelectedRoom->pmsBookingRoomId;
$codes = $this->getApi()->getCartManager()->getCoupons();
$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
$segments = $this->getApi()->getPmsCoverageAndIncomeReportManager()->getSegments($this->getSelectedMultilevelDomainName());
$title = "Avoid autodelete disabled";
if($pmsBooking->avoidAutoDelete) {
    $title = "Avoid autodelete done";
}
$channelList = $this->getApi()->getPmsManager()->getChannelMatrix($this->getSelectedMultilevelDomainName());
$formater = new \ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBookingColumnFormatters(null);
$channelNames = $formater->getChannels();
?>
<div class='col_box_width_2'>
    <div class="row odd">
        <div class="col col1" title="<?php echo $title; ?>"><? echo $this->__f("GetShop booking id"); ?></div>
        <?php
        $disabled = stristr($pmsBooking->channel, "wubook_") ? "DISABLED" :"";
        $style = $disabled ? "color:gray;background-image:none;" : "";
        ?>
        <div class="col col2"><? echo $pmsBooking->incrementBookingId; ?>
            <select class="changechannel gsniceselect1" style="width:50%; float:right;<?php echo $style;?>" <?php echo $disabled; ?> >
                <?php
                echo "<option value=''>No source</option>";
                foreach($channelList as $idx => $channel) {
                    $name = $channelNames[$idx] ? $channelNames[$idx] : $channel;
                    $selected = $idx == $pmsBooking->channel ? "SELECTED" : "";
                    if(stristr($idx, "wubook_")) {
                        continue;
                    }
                    echo "<option value='$idx' $selected>$name</option>";
                }
                echo "<option value='getshop_new_source'>Add a new source</option>";
                ?>
            </select>
        </div>
    </div>
    <div class="row odd">
        <div class="col col1"><? echo $this->__f("Discount code / segment"); ?></div>
        <div class="col col2">
            
            <div class='checkifneedupdateprices' style='position:absolute; background-color: #fff; border: solid 1px #bbb;padding: 3px; display:none;'>
                <div>Update prices as well?</div>
                <span class='shop_button doChangeDiscount' updateprices='true' style='width:50%;box-sizing: border-box;float:left;background-color:green;'>Yes</span>
                <span class='shop_button doChangeDiscount' updateprices='false' style='width:50%;box-sizing: border-box;background-color:red;'>No</span>
            </div>
            
            <span class="codeselection">
                <select class="changediscountcode gsniceselect1" style="width:48%">
                    <option value="">Not set</option>
                    <?php
                    foreach($codes as $code) {
                        $selected = (strtolower($code->code) == strtolower($pmsBooking->couponCode)) ? "SELECTED" : "";
                        echo "<option value='".$code->code."' $selected>" . $code->code . "</option>";
                    }
                    ?>
                </select>
                <select class="changesegment gsniceselect1" style="width:50%; float:right;">
                    <option value="">Not set</option>
                    <?php
                    foreach($segments as $segment) {
                        $selected = ($segment->id == $pmsBooking->segmentId) ? "SELECTED" : "";
                        echo "<option value='".$segment->id."' $selected>" . $segment->name . "</option>";
                    }
                    ?>
                </select>
            </span>
        </div>    
    </div>

    <div class="row odd">
        <div class="col col1"><? echo $this->__f("Channel reservation ids"); ?></div>
        <div class="col col2"><? echo $pmsBooking->wubookchannelreservationcode ? $pmsBooking->wubookchannelreservationcode . "/" . $pmsBooking->wubookreservationid : "N/A"; ?></div>    
    </div>

    <div class="row odd">
        <div class="col col1"><? echo $this->__f("Room non refundable"); ?></div>
        <?php
        if ($pmsSelectedRoom->nonrefundable) {
            ?>
            <div class="col col2">Yes, <span style='cursor:pointer;' class='bookinghighlightcolor' roomid='<?php echo $pmsSelectedRoom->pmsBookingRoomId; ?>' gsclick='togglerefundable'>make it refundable</span></div>    
            <?php
        } else {
            ?>
            <div class="col col2">No, <span style='cursor:pointer;' class='bookinghighlightcolor' roomid='<?php echo $pmsSelectedRoom->pmsBookingRoomId; ?>' gsclick='togglerefundable'>make it non refundable</span></div>    
            <?php
        }
        ?>
    </div>
    
    <div class="row odd">
        <div class="col col1"><? 
        echo "<i class='fa fa-edit bookinghighlightcolor adduserdescription' style='cursor:pointer;'></i> ";
        echo $this->__f("Pinned comment"); 
        
        ?></div>
        <div class="col col2"><? 
        if($user->description) {
            echo "<i class='fa fa-trash-o' style='cursor:pointer;' gsclick='deleteUserDescription' roomid='".$pmsSelectedRoom->pmsBookingRoomId."'></i> ";
        }
        echo $user->description; ?></div>    
    </div>    

    <div class="row odd">
        <div class="col col1"><? 
        echo " <i class='fa fa-edit bookinghighlightcolor addordernote' style='cursor:pointer;'></i> ";
        echo $this->__f("Order note");
        ?></div>
        <div class="col col2"><? 
        if($pmsBooking->invoiceNote) {
            echo "<i class='fa fa-trash-o' style='cursor:pointer;' gsclick='deleteInvoiceNote' roomid='".$pmsSelectedRoom->pmsBookingRoomId."'></i> ";
        }

        echo $pmsBooking->invoiceNote; ?>
        </div>    
    </div>
    
    <?php
    if($config->wubookAutoCharging) {
    ?>
        <div class="row odd">
            <div class="col col1"><? echo $this->__f("Autocharge card"); ?></div>
            <?php
            if ($pmsBooking->tryAutoCharge) {
                ?>
                <div class="col col2">Yes, <span style='cursor:pointer;' class='bookinghighlightcolor' gsclick='toggleautocharging'>stop autocharging</span></div>    
                <?php
            } else {
                ?>
                <div class="col col2">No, <span style='cursor:pointer;' class='bookinghighlightcolor' gsclick='toggleautocharging'>retry autocharging</span></div>    
                <?php
            }
            ?>
        </div>
    <?php
    }
    ?>
</div>
    
<div class='col_box_width_2 second'>
    <div class="row">
        <div class="col col1"><? echo $this->__f("Date created"); ?></div>
        
        <?php
        $browser = "";
        if($pmsBooking->browserUsed) {
            $browser = "Booked by browser : " . $pmsBooking->browserUsed->name . ", version: " . $pmsBooking->browserUsed->version;
        }
        ?>
        
        <div class="col col2" title="<?php echo $browser; ?>"><div class='ellipsis'><b><? echo date("d.m.Y H:i", strtotime($pmsBooking->rowCreatedDate)); ?> by 
            <?php if($pmsBooking->bookedByUserId) { 

                if($pmsBooking->bookedByUserId == "gs_system_scheduler_user") {
                    ?>
                    <div class="col col2">OTA</div>    
                    <?php            
                } else {
                    $name = $this->getApi()->getUserManager()->getUserById($pmsBooking->bookedByUserId)->fullName;
                    if(!$name) { $name = "No name"; }
                    echo $name; 
                } 
            } else {
                echo $user->fullName;
            } ?>
                </b></div>
        </div>  
    </div>

    <div class="row odd">
        <div class="col col1"><span><? echo $this->__f("Booked for"); ?></span> (
            <span class='bookinghighlightcolor' style='cursor:pointer;'  onclick='$(".change_user_form").hide();$(".edit_details_of_user").toggle();'>edit</span> or 
            <span class='bookinghighlightcolor' style='cursor:pointer;' onclick='$(".edit_details_of_user").hide();$(".change_user_form").toggle();'>change</span>)</div>
        <div class="col col2">
            <?
            $extraArgs = array();
            $extraArgs['invokeJavascriptFunctionAfterActions'] = "app.PmsBookingGroupRoomView.refresh";
            $extraArgs['roomid'] = $pmsSelectedRoom->pmsBookingRoomId;
            $quser = new \ns_b5e9370e_121f_414d_bda2_74df44010c3b\GetShopQuickUser();
            $quser->setUser($user);
            $quser->setExtraArgs($extraArgs);
            $quser->renderApplication(true, $this, true);
            ?>
        </div>
    </div>

    <div class="row odd">
        <div class="col col1"><span><? echo $this->__f("Phone"); ?></span></div>
        <div class="col col2"><?php echo "+" . $user->prefix . " " . $user->cellPhone; ?></div>
    </div>
    <div class="row odd">
        <div class="col col1"><span><? echo $this->__f("Email (for payments)"); ?></span></div>
        <div class="col col2 bookinghighlightcolor"><?php echo $user->emailAddress; ?></div>
    </div>

    <div class="row odd">
        <div class="col col1"><? echo $this->__f("Adress"); ?></div>
        <div class="col col2">
            <?php
            if (isset($user->address)) {
                echo $user->address->address . " ";
                if ($user->address->postCode || $user->address->city ) {
                    echo " / ".$user->address->postCode . " " . $user->address->city . "<br>";
                }
            }
            ?>
        </div>
    </div>

    <div class="row odd" style="display: none">
        <div class="col col1"><span><? echo $this->__f("Registration information"); ?></span></div>
        <div class="col col2" onclick='$(".registeredinformation").toggle();' style='cursor:pointer;'>Display registration information</div>
        <div class='registeredinformation' style='display:none;'>
            <?php
            foreach ($pmsBooking->registrationData->resultAdded as $key => $val) {
                echo "<div>" . $key . " : " . $val . "</div>";
            }
            ?>
        </div>
    </div>
    <div style='clear:both;'></div>
    <div class='commentarea'>
        <div class='commentsheader'>Comments - <span class='bookinghighlightcolor' style='cursor:pointer;' onclick='$(".PmsBookingGroupRoomView .addcommentarea").toggle();$(".addcommenttobooking").focus();'>add comment</span> - 
            <span class='bookinghighlightcolor' style='cursor:pointer;' onclick='$(".notforroom").show();$(".hiddencomment").show();'>show all comments (<?php echo sizeof((array)$pmsBooking->comments); ?></span>)</div>
        <?php
        $counter = 0;
        foreach($pmsBooking->comments as $time => $comment) {
            /* @var $comment core_pmsmanager_PmsBookingComment */
            $notForRoom = "";
            
            $hiddenclass = $counter >= 3 ? "hiddencomment" : "";
            $deletedClass = "";
            
            if($comment->deleted) {
                $hiddenclass = "hiddencomment";
                $deletedClass = "deletedcomment";
            } else if($comment->pmsBookingRoomId) {
                if($comment->pmsBookingRoomId != $this->getSelectedRoomId()) {
                    $notForRoom = "notforroom";
                } else {
                    $notForRoom = "forroom";
                    $counter++;
                }
            } else {
                $counter++;
            }
            
            $user = $this->getApi()->getUserManager()->getUserById($comment->userId);
            echo "<div class='$notForRoom $hiddenclass $deletedClass commentrow' roomid='".$pmsSelectedRoom->pmsBookingRoomId."' commentid='".$comment->commentId."'>";
            echo "<span class='commenttime'>";
            echo "<i class='fa fa-trash-o' gsclick='deleteComment' style='cursor:pointer;' gs_confirm='Are you sure?' roomid='".$pmsSelectedRoom->pmsBookingRoomId."' commentid='".$comment->commentId."'></i> ";
            echo "<i class='fa fa-edit editcomment' style='cursor:pointer'></i> " . date("d.m.y h:i", $time/1000) . "</span>";
            echo "<span class='commenttext'>" . $comment->comment . "</span>";
            echo "<span class='commentby'>" . $user->fullName . "</span>";
            echo "</div>";
        }
        ?>
    </div>
    <div class='addcommentarea' gstype='form' method='addComment'>
        <input type='hidden' gsname='roomid' value='<?php echo $pmsSelectedRoom->pmsBookingRoomId; ?>'>
        <textarea class='addcommenttobooking' gsname='comment'></textarea>
        <span class='shop_button addcommentbtn' gstype='submit' gsvalue='group' style='float:right;'>Add to group</span>
        <span class='shop_button addcommentbtn' gstype='submit' gsvalue='room'>Add to room</span>
    </div>
    
    <span class='shop_button savecomment'>Save comment</span>
</div>


<style>
    .PmsBookingGroupRoomView .notforroom { display:none; }
    .PmsBookingGroupRoomView .savecomment { display:none; }
    .PmsBookingGroupRoomView .hiddencomment { display:none; }
    .PmsBookingGroupRoomView .forroom { color:#bb2d2d; }
    .PmsBookingGroupRoomView .deletedcomment { text-decoration: line-through; }
    .PmsBookingGroupRoomView .addcommentarea { margin-top: 10px;display:none; }
    .PmsBookingGroupRoomView .addcommentbtn { width:45%; box-sizing: border-box; float:left;}
    .PmsBookingGroupRoomView .addcommenttobooking { width:100%; box-sizing: border-box; height: 80px; }
    .PmsBookingGroupRoomView .commentsheader { text-align: left;  margin-top: 10px; color:#777; }
    .PmsBookingGroupRoomView .commentarea { padding-left: 10px; font-size: 12px; }
    .PmsBookingGroupRoomView .commentby { float:right; color:#bbb; }
    .PmsBookingGroupRoomView .commenttime { color:#bbb; width: 120px; display:inline-block; }
    .PmsBookingGroupRoomView .bookerinformation .col { width: 40%; display:inline-block; }
    .PmsBookingGroupRoomView .bookerinformation .col_box_width_2 { width: 50%; display:inline-block; float:left; }
    .PmsBookingGroupRoomView .col1 {     width: 190px; line-height: 20px; padding-left: 10px; box-sizing: border-box;color: #777; }
    .PmsBookingGroupRoomView { font-size: 15px; }
    .PmsBookingGroupRoomView .show_edit_user, .PmsBookingGroupRoomView .show_change_user, .PmsBookingGroupRoomView .bookinghighlightcolor { color: #4da6cb; }
    .PmsBookingGroupRoomView .edit_user_btn { display:none; }
    .PmsBookingGroupRoomView .commenttext { width: calc(100% - 250px );display: inline-block;  white-space: nowrap;  overflow: hidden;  text-overflow: ellipsis: }
</style>