<?php
/* @var $this ns_3e2bc00a_4d7c_44f4_a1ea_4b1b953d8c01\PmsBookingGroupRoomView */

$eventId = $this->getSelectedEventId();
if(!$eventId) {
    echo "<div style='font-size: 20px; margin: 40px;'>";
    echo "No events created for this event yet. Please click on 'Add another event' at the right hand side.";
    echo "</div>";
    return;
}

if ($eventId == "overview") {
    $this->includefile("conferenceoverview");
    return;
}

$menu = array();
$menu['conference_overview'] = "Overview";
$menu['conference_activities'] = "Activities";
$menu['conference_pos'] = "Pos";
$menu['conference_timeline'] = "Timeline";
$menu['conference_report'] = "Report";


$icons = array();
$icons['conference_overview'] = "info-circle";
$icons['conference_activities'] = "play-circle-o";
$icons['conference_timeline'] = "play-circle-o";
$icons['conference_pos'] = "money";
$icons['conference_report'] = "file-pdf-o";

$selected = "guests";
if(isset($_POST['data']['subsection'])) {
    $selected = $_POST['data']['subsection'];
}

$first = true;
echo "<div class='menurow'>";
foreach($menu as $id => $val) {
    $hide = "";
    if($id == "confirmation") {
        $hide = "display:none;";
    }
    if($id == "log") {
        $hide = "display:none;";
    }
    $right = "";
    if($id == "conference_timeline") {
        $right = "style='float:right;'";
    }
    
    $select = ($selected == $id) ? "selected" : "";
    $firstClass = $first ? "first" : "";
    echo "<span $right class='menubutton $select $firstClass' subsection='$id' style='$hide'>";
    echo "<span ><div><i class='fa fa-" . $icons[$id] . "'></i></div></span>";
    echo "<div>$val</div></span>";
    $first = false;
}
echo "</div>";
?>



<?php



if(in_array($selected,array_keys($menu))) {
    echo "<div class='$selected' style='background-color:#fff;'>";
    echo "<div style='padding: 20px;'>";
    $this->includefile($selected);
    echo "<div style='clear:both;'></div>";
    echo "</div>";
    echo "</div>";
}



?>
<style>
.dateheader {
    border: solid 1px #bbb;
    text-align: center;
    font-weight: bold;
    background-color: #efefef;
    margin: 10px;
    padding: 10px;
    
}
.eventheader {
    margin-top: 10px;
    font-weight: bold;
    padding-bottom: 10px;
}
</style>