<?php
/* @var $this ns_3e2bc00a_4d7c_44f4_a1ea_4b1b953d8c01\PmsBookingGroupRoomView */

$booking = $this->getPmsBooking();
$filter = new core_pmsmanager_PmsBookingFilter();
$filter->bookingId = $booking->id;
$filter->includeDeleted = true;
$rooms = $this->getApi()->getPmsManager()->getSimpleRooms($this->getSelectedMultilevelDomainName(), $filter);
$formatter = new ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBookingColumnFormatters(new \ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBooking());
$types = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);

$bookingStart = "";
$bookingEnd = "";

$start = date("d.m.Y", time());
$end = date("d.m.Y", strtotime(date("d.m.Y", time()) . " +1 day"));


foreach ($booking->rooms as $r) {
    if (!$bookingStart || strtotime($r->date->start) < $bookingStart) {
        $bookingStart = strtotime($r->date->start);
    }
    if (!$bookingEnd || strtotime($r->date->end) > $bookingEnd) {
        $bookingEnd = strtotime($r->date->end);
    }
}

?>

<div class='manipulateroomoptions'>
    <span class='groupmaninpualtionbtn shop_button disabled' type='delete'><i class='fa fa-trash-o'></i> Delete selected rooms</span>
    <span class='groupmaninpualtionbtn shop_button disabled' type='split'><i class='fa fa-users'></i> Split group</span>
    <span class='groupmaninpualtionbtn shop_button disabled' type='updateGuestCount'><i class='fa fa-plus-square-o'></i> Update guest count</span>
    <span class='groupmaninpualtionbtn shop_button disabled updatePricePanelbtn' type='updatepricepanelbtn' avoidaction='true'><i class='fa fa-money'></i> Update prices</span>
    <span class='groupmaninpualtionbtn shop_button disabled addAddonsPanelbtn' type='addAddon' avoidaction='true'><i class='fa fa-plus-square-o'></i> Add/remove addons</span>
    <span class='groupmaninpualtionbtn shop_button disabled moveCategoryPanelbtn' type='moveToCategory' avoidaction='true'><i class='fa fa-forward'></i> Move category</span>
    
    <span class="shop_button addfromdifferentroom" style="float:right; margin-left: 5px; border-radius: 3px;"><i class='fa fa-arrow-circle-down'></i> Import room</span>
    <span class='shop_button doaddroomtogroup' onclick='$(".addroombox").toggle();$(".findroomfrombooking").hide();' style="float:right; border-radius: 3px;"><i class='fa fa-plus-circle'></i> Add room</span>
    
    <i class='fa fa-caret-down'></i>
<!--</div>-->

<div style="position:relative">
    <span class="findroomfrombooking" style="padding:10px;">
        <div style='text-align:right;margin-bottom: 10px;'><i class='fa fa-close' style='cursor:pointer;' onclick='$(".findroomfrombooking").hide();'></i></div>
        <input type="txt" class="gsniceinput1" placeholder="Search for booking" style="width:100%;box-sizing: border-box;" gstype='clicksubmit' gsname='keyword' method="searchbooking"  gstoarea=".searcharea">
        <div class="searcharea" style='margin-top:10px;'><span style='font-size: 16px;'>Search for a booking to add in the box above.</span></div>
        <div style='text-align: right;'><span  class='shop_button' onclick='$(".menubutton.selected").click();'>Done importing</span></div>
    </span>
</div>

<div class='addroombox' style='display:none;margin-bottom:15px;' gstype="form" method="addRoomToGroup">
    <h3>Add another room to this group</h3>
    <input type='txt' class='gsniceinput1' value='<?php echo $start; ?>' gsname='start'> 
    <input type='txt' class='gsniceinput1' value='<?php echo $end; ?>' gsname='end'> 
    <input type='hidden' gsname='roomid' value='<?php echo $booking->id; ?>'>
    <select class='gsniceselect1' style='height:38px;' gsname='type'>
        <?php
        foreach ($types as $type) {
            echo "<option value='" . $type->id . "'>" . $type->name . "</option>";
        }
        ?>
    </select>
    <select class='gsniceselect1' style='height:38px; max-width:200pX;' gsname='guestInfoOnRoom'>
        <?php
        echo "<option value=''>No guest information</option>";
        foreach ($booking->rooms as $room) {
            $guestInfo = "";
            if (isset($room->guests[0])) {
                $guestInfo = $room->guests[0]->name . " - ";
                $guestInfo .= $room->guests[0]->email . " - ";
                $guestInfo .= $room->guests[0]->prefix . " - ";
                $guestInfo .= $room->guests[0]->phone;
            }
            echo "<option value='" . $room->pmsBookingRoomId . "'>" . $guestInfo . "</option>";
        }
        ?>
    </select>
    <input type='txt' class='gsniceinput1' gsname='count' value="1" style="width:30px;"> 
    <span class='shop_button doaddroomtogroup' gstype="submit">Add room</span>
    <div class="notavailablerooms">I am sorry, you can not add room using the above selection, there are not enough rooms for that, if adding them they will be added to a waiting queue.</div>
</div>



<div class="addAddonsPanel" style='margin-bottom: 30px;'>
<?php
$this->includefile("addaddonstogroup");
?>    
</div>
<div class="moveCategoryPanel" style='margin-bottom: 30px;'>
    <i class="fa fa-close" style="float:right; cursor:pointer;" onclick="$('.moveCategoryPanel').hide();"></i>
    <div>Please choose a category you would like to try to move the rooms to</div>
    <br>
    <select class='gsniceselect1 movetoroomtype'>
        <?php
        $categories = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);
        foreach($categories as $category) {
            echo "<option value='" . $category->id . "'>" . $category->name . "</option>";
        }
        ?>
    </select>
    <span class='shop_button startmovecategory'>Try to move</span>
</div>

<div class="updatepricepanel" style='margin-bottom: 30px;'>
    <div>
        <h2>Update all prices for all selected rooms</h2>
    </div>
    <div>
        <span style='width:100px; display:inline-block;'>From date</span>
        <span style='width:100px; display:inline-block;'>To date</span>
        <span style='width:154px; display:inline-block;'>Price type</span>
        <span>Value</span>
    </div>
    <input type='txt' class='gsniceinput1' gsname='start' value='<?php echo date("d.m.Y", $bookingStart); ?>' style='width:80px'>
    <input type='txt' class='gsniceinput1' gsname='end' value='<?php echo date("d.m.Y", $bookingEnd); ?>' style='width:80px'>
    <select class="gsniceselect1 masseditpricestay" style='width:150px;' gsname='pricetype'>
        <option value="dayprice">Daily price</option>
        <option value="start_of_month">Monthly price beginning of month</option>
        <option value="start_of_stay">Monthly price beginning of stay</option>
        <option value="wholestay">Total cost for whole stay</option>
    </select>
    <input type='txt' class='gsniceinput1' gsname='value' value='100'  style='width:40px'>
    <span class='shop_button setnewpricebutton'>Set new price</span>
</div>



<table style='width:100%;' class='roomtable'>
    <?php
    echo "<tr>";
    echo "<th width='10'><input type='checkbox' class='toggleallrooms'></th>";
    echo "<th>Check in</th>";
    echo "<th>Check out</th>";
    echo "<th>Guests</th>";
    echo "<th>Guest information</th>";
    echo "<th>Addons</th>";
    echo "<th>Room</th>";
    echo "<th>Price</th>";
    echo "<th>Total</th>";
    echo "</tr>";
    
    foreach($rooms as $room) {
        echo "<tr class='roomrows ".$room->progressState."'>";
        echo "<td width='10' align='center'><input type='checkbox' class='roomcheckbox' roomid='".$room->pmsRoomId."'></td>";
        echo "<td align='center'>" . $formatter->formatStartPeriode($room) . "</td>";
        echo "<td align='center'>" . $formatter->formatEndPeriode($room) . "</td>";
        echo "<td align='center'>" . $formatter->formatGuests($room) . "</td>";
        echo "<td>" . $formatter->formatVistior($room) . "</td>";
        echo "<td align='center'>" . $formatter->formatAddons($room) . "</td>";
        echo "<td>" . $formatter->formatRoom($room) . "</td>";
        echo "<td align='center'>" . $formatter->formatPrice($room) . "</td>";
        echo "<td align='center'>" . $formatter->formatTotalPrice($room) . "</td>";
        echo "</tr>";
    }
    ?>
</table>


<style>
    .findroomfrombooking { display:none; }
    .addfromotherroomrow { border-bottom: solid 1px #fff; padding-bottom: 10px; }
    .addfromotherroomrow:hover { border-bottom: solid 1px #bbb; padding-bottom: 10px; }
    .addfromotherroomrow .col { width: 150px !important; }
    .addfromotherroomrow .owner { width: calc(100% - 900px) !important; }
    .addfromotherroomrow .room { text-align: center; }
    .addfromotherroomrow .importroom { text-align: center; cursor:pointer; }
    .notavailablerooms { display:none; }
    .moveCategoryPanel { display:none; }
    .addAddonsPanel { display:none; }
    .addonsrow { clear:both; height: 42px; }
    .addonsrow .shop_button { float:right; margin-left: 3px; }
    .updatepricepanel { display:none; }
    .guesticon,.langaugeandtypeindicator { display:none; }
    .roomrows.deleted td { color:red !important; }
    .manipulateroomoptions { margin-bottom: 10px; position: relative; border-bottom: solid 1px #bbb; padding-bottom: 10px;  }
    .unsettledamountwarning { color:red; font-weight: bold; }
    .roomcheckbox,.toggleallrooms { height: 30px; width: 30px; }
    .roomrows td { position: relative; }
    .quickfunctions { display:none; }
    .flag { display:none !important; }
    .addedtocheckout { display:none; }
    .fa-arrows-h { display:none; }
    .roomrows { border-bottom: solid 1px #000; }
    .shop_button.disabled {
        background-color: #efefef;
        color: #aaa !important;
        cursor: inherit;
    }
    
    .manipulateroomoptions .fa-caret-down {
        position: absolute;
        bottom: -14px;
        font-size: 20px;
        left: 23px;
        color: #bbb;
    }
    .numberofguests {
        border-radius: 1000px;
        height: 40px;
        width: 40px;
        border: solid 2px #82cdf3;
        text-align: center;
        line-height: 40px;
        font-size: 20px;
        font-weight: bold;
        position: relative;
        display: inline-block;
        vertical-align: top;
    }
    .manipulateroomoptions .shop_button { margin: 3px; }
    .roomtable {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }

      .roomtable td, .roomtable th {
        border: 1px solid #ddd;
        padding: 8px;
      }

      .roomtable tr:nth-child(even){background-color: #f2f2f2;}

      .roomtable tr:hover {background-color: #ddd;}

      .roomtable th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #4CAF50;
        color: white;
      }
    
</style>

<script>
    getshop_loadDatePicker($("[gsname='start']"), {});
    getshop_loadDatePicker($("[gsname='end']"), {});
</script>