<?php
/* @var $this ns_3e2bc00a_4d7c_44f4_a1ea_4b1b953d8c01\PmsBookingGroupRoomView */

$booking = $this->getPmsBooking();
$unpaid = $this->getApi()->getPmsInvoiceManager()->getUnpaidAmountOnBooking($this->getSelectedMultilevelDomainName(), $booking->id);
$unpaid = round($unpaid, 2);
$config = $this->getPmsConfiguration();

    echo "<div>Number of rooms in booking " . "<span style='float:right;'>" .  sizeof($booking->rooms) . "</span></div>";
echo "<div>Total for group <span style='float:right;'>" . round($booking->totalPrice,2) . "</span></div>";
echo "<div>Total unpaid for group <span style='float:right;'>" . $unpaid . "</span></div>";
?>
<bR>
<div class='shop_button toggleafterstaybtn'  
     gsclick='togglePayAfterStayForGroup' 
     roomid='<?php echo $this->getPmsBookingRoom()->pmsBookingRoomId; ?>'  
     gs_callback='app.PmsBookingGroupRoomView.refresh'
     style='width:45%;box-sizing: border-box;border-radius:3px;float:left;font-size:12px;line-height: 14px; padding-top: 6px;'>
    <?php
if($booking->createOrderAfterStay) {
    echo "Undo pay after stay";
} else {
    echo "Pay after stay for whole group";
}
?>
</div>
<div class='shop_button startpaymentprocessbtn' style='width:45%;box-sizing: border-box;background-color:#86c330;border-radius:3px;float:right;font-size:12px;line-height: 14px; padding-top: 6px;'>Start payment process</div>
<div style='clear:both;'></div>
<?php
echo "<div class='otheroptions'><a target='_new' href='/pms.php?page=0da68de9-da08-4b60-9652-3ac456da2627&groupview=$booking->id' style='cursor:pointer;' class='opengroup bookinghighlightcolor'>open in availability</a></div> ";
if($config->conferenceSystemActive) {
    echo "<div class='otheroptions'>";
    if($booking->conferenceId) {
        if($this->isConferenceView()) {
            echo "<a class='bookinghighlightcolor openconference'>list rooms</a>";
        } else {
            echo "<a class='bookinghighlightcolor openconference'>open conference</a>";
        }
    } else {
        echo "<a class='bookinghighlightcolor craeteconference'>create conference</a>";
        ?>
        <div class='createconferencepanel' style='text-align: left;'>
            <h3>Create a new conference:</h3>
            <div gstype='form' method='createNewConference'>
                <input type='hidden' gsname='roomid' value='<?php echo $this->getSelectedRoomId(); ?>'>
                <span style='display: inline-block; width: 80px;'>Title:</span> <input type='txt' class='gsniceinput1' gsname='title' placeholder=''>
                <br/><span style='display: inline-block; width: 80px;'>Date:</span> <input type='txt' class='gsniceinput1' gsname='conferencedate' placeholder=''>
                <br/><br/><span class='shop_button' gstype='submit' gs_callback='app.PmsBookingGroupRoomView.conferenceSelected'>Create conference</span>
            </div>
            <div>
                <h4>Or connect to an existing conference:</h4>
                <input type='txt' class='gsniceinput1 searchconferencetitle' placeholder='Conference title'>
                <div class='searchconferencearea'></div>
            </div>

            <script>
                getshop_loadDatePicker($('[gsname="conferencedate"]'), {});
            </script>
        </div>

    <?php
    }
    
    echo "</div>";
}
echo "<div class='otheroptions'>";
echo "<a target='_new' href='/pms.php?page=afe687b7-219e-4396-9e7b-2848f5ed034d&groupview=$booking->id' style='cursor:pointer;' class='opengroup bookinghighlightcolor'>open in report</a>";
echo "</div>";
if ($this->isPgaSupportActivated()) {
    echo "<div class='otheroptions'>";
    echo "<a href='/pga.php?token=$booking->token' target='_pga' class='bookinghighlightcolor'>pga</a>";
    echo "</div>";
}
?>
