<?
/* @var $this \ns_f8cc5247_85bf_4504_b4f3_b39937bd9955\PmsBookingRoomView */
$pmsBooking = $this->getPmsBooking();
$savedRoom = $this->getSelectedRoom();
$room = $this->getTmpSelectedRoom($savedRoom->pmsBookingRoomId);
$types = $this->getTypes();
$items = $this->getItems();

$start = $room->date->start;
$end = $room->date->end;

$priceMatrix = (array)$room->priceMatrix;
uksort($priceMatrix, array('ns_28886d7d_91d6_409a_a455_9351a426bed5\PmsAvailability','sortByDate'));


?>

<div class="item_prices">
    <div class='pricecontainerbox'>
        <div class="stayheader">Daily prices <i class='fa fa-edit bookinghighlightcolor' style='float:right;cursor:pointer;font-size:20px;' onclick='$(".masseditpricesbox").toggle()'></i></div>
        <div class='masseditpricesbox' style='display:none;'>
            <select class="gsniceselect1 masseditpricestay" style="width:100%; margin-bottom: 5px;">
                <option value="dayprice">Same price all days</option>
                <option value="start_of_month">Monthly price beginning of month</option>
                <option value="start_of_stay">Monthly price beginning of stay</option>
                <option value="wholestay">Total cost for whole stay</option>
            </select>
            <input type="text" class="gsniceinput1 massupdatepricevalue" placeholder="value">
            <span class="shop_button massupdateprices" style="float:right;">Update</span>

            <div class='priceselectionhelp' type="dayprice" style='display:block;'>This will set the same price for each day.</div>
            <div class='priceselectionhelp' type="start_of_month">This will calculate the daily price to be the same as a total of monthly cost, since each month has different days it will use the number of days in month where the base will be the first day in the month.</div>
            <div class='priceselectionhelp' type="start_of_stay">This will calculate the daily price to be the same as a total of monthly cost, since each month has different days it will use the number of days in month where the base will be the first day of the stay, if the stay start the 15 one month will be calculated from 15 to 15.</div>
            <div class='priceselectionhelp' type="wholestay">This will calculate the daily price for each day which the total will be the same as you entered.</div>
        </div>

        <div class="pricerows">
            <?
            $total = 0;
            foreach ($priceMatrix as $date => $price) {
                $total += $price;
                $datetext = date("d.m.Y", strtotime($date));
                echo "<div class='pricerow' date='$date'> <div class='col col1 secondarytextcolor'>$datetext </div> <div class='col col2' style='float:right;    margin-right: 14px;'><input class='gsniceinput1 unitprice_changed' gsname='$date' value='$price' ></div> </div>";
                echo "<div style='clear:both;'></div>";
            }
            ?>
        </div>

        <div class='totalrow secondarytextcolor'>
            <?
            echo "<span style='color:#000000'>" .  $this->__f("Total").": <span><b>".$total."</b></span></span>";
            ?>
            <div class='extrainfo'>
                <i class='fa fa-info-circle'></i>
                <?
                echo $this->__f("The total here is only for the rooms itselfs, it does not contain addons unless they are included in the roomprice");
                ?>
            </div>
        </div>
    </div>
</div>
    
<script>
$('.masseditpricestay').on('change', function() {
    var type = $(this).val();
    $('.priceselectionhelp').hide();
    $('.priceselectionhelp[type="'+type+'"]').show();
});

$('.setnewdates').on('click',function() {
    app.PmsBookingRoomView.updateAvailability();
});
</script>