<?php
/* @var $this ns_3e2bc00a_4d7c_44f4_a1ea_4b1b953d8c01\PmsBookingGroupRoomView */

$booking = $this->getPmsBooking();
$selectedRoom = $this->getPmsBookingRoom();

$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName());
$types = $this->indexList($types);

$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedMultilevelDomainName());
$items = $this->indexList($items);

foreach($booking->rooms as $room) {
    $deleted = $room->deleted ? "roomisdeleted" : "";
    $selected = $selectedRoom->pmsBookingRoomId == $room->pmsBookingRoomId ? "selected" : "";
    echo "<div class='roomgroupbox changeRoomByEvent $selected $deleted' roomid='".$room->pmsBookingRoomId."'>";
    echo "<div>";
    echo "<b>" . $types[$room->bookingItemTypeId]->name . "</b>";
    if($room->deleted) {
        echo " (<i class='fa fa-trash-o' title='Room has been deleted'></i>)"; 
    }
    if($room->bookingItemId) {
        echo "<span style='float:right;'>" . $items[$room->bookingItemId]->bookingItemName . "</span>";
    } else {
        echo "<span style='float:right; color:#8c2626;'>floating</span>";
    }
    echo "</div>";
    foreach($room->guests as $guest) {
        echo "&nbsp;&nbsp;&nbsp;" . $guest->name . "<br>";
    }
    echo "<div style='color:#8c2626;'><span class='dates'>".date("d/m H:i", strtotime($room->date->start)) . " - " . date("d/m H:i", strtotime($room->date->end)) . "</span>";
    echo "<span class='unpaidindicator'>" . round($room->unpaidAmount,2)  . "/" . round($room->totalCost,2). "</span>";
    echo "</div>";
    echo "</div>";
}

?>


<script>
    if(lastScrollTopPosition) {
        $('.roomsingroupinformation').scrollTop(lastScrollTopPosition);
    }
</script>