<div class="heading">
    <?php
    echo $this->__f("Please select");
    ?>
</div>

<div class="optionboxes">
    <a href="/?page=alreadybooked">
        <div class="optionbox">
            <span class="icon-tablet"></span>
            <div class="title">
                <?php
                echo $this->__f("Already booked?");
                ?>    
            </div>
        </div>
    </a>

    <a href="/?page=bookroompage">
        <div class="optionbox">
            <span class="icon-bed"></span>
            <div class="title">
                <?php
                echo $this->__f("Book room");
                ?>    
            </div>
        </div>
    </a>

    <?php
    if ($this->hasAnyCampingSpots()) {
    ?>
    <a href="/?page=bookcampingpage">
        <div class="optionbox">
            <span class="icon-landscape"></span>
            <div class="title">
                <?php
                echo $this->__f("Book camping");
                ?>
            </div>
        </div>
    </a>
    <?php
    }
    ?>

    <a href="/">
        <div class="optionbox">
            <span class="icon-close"></span>
            <div class="title">
                <?php
                echo $this->__f("Cancel");
                ?>    
            </div>
        </div>
    </a>
    
</div>

