<?
/* @var $this \ns_74ea4e90_2d5a_4290_af0c_230a66e09c78\Booking */
$company = $this->getCompany();
if (!$company) {
    echo $this->__w("Did not find the specified company, please check your company number");
    return;
}
?>

<table>
    <tr><td style="width: 73px"><? echo $this->__w("Name"); ?></td><td><? echo $company->name;?></td></tr>
    <tr><td><? echo $this->__w("Address"); ?></td><td><? echo $company->streetAddress;?></td></tr>
    <tr><td><? echo $this->__w("Post code"); ?></td><td><? echo $company->postnumber;?></td></tr>
    <tr><td><? echo $this->__w("City"); ?></td><td><? echo $company->city;?></td></tr>
</table>