<?
namespace ns_74ea4e90_2d5a_4290_af0c_230a66e09c78;
?>

<div class="setting onoff" id="sendmail">
    <span class="title"><?php echo $this->__("Send email"); ?></span>
    <div class="onoff config" id="sendmail"></div>
    <div class="description">
        <?php echo $this->__("Enable this option to send email when a booking has been made."); ?>
    </div>
</div>

<div class="setting onoff" id="sendsms">
    <span class="title"><?php echo $this->__("Send sms to attendee?"); ?></span>
    <div class="onoff config" id="sendsms"></div>
    <div class="description">
        <?php echo $this->__("If this option has been enabled the attendee will receive an sms."); ?>
    </div>
</div>

<div class="setting onoff" id="extradep">
    <span class="title"><?php echo $this->__("Extra information for department?"); ?></span>
    <div class="onoff config" id="extradep"></div>
    <div class="description">
        <?php echo $this->__("Extra information for department."); ?>
    </div>
</div>

<div class="setting onoff" id="connectedtopage">
    <span class="title"><?php echo $this->__("Is this booking form connected to this page?"); ?></span>
    <div class="onoff config" id="connectedtopage"></div>
    <div class="description">
        <?php echo $this->__("A bookingform can be connected to the page its added to, meaning that the content of this page is the content that are being sold, not an event or course itself."); ?>
    </div>
</div>

<div class="textfield setting"  id="smstext">
    <span class="title"><?php echo $this->__("SMS Text"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__("What should the text message contain?"); ?>
    </div>
</div>

<div class="textfield setting"  id="smsfrom">
    <span class="title"><?php echo $this->__("SMS From"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__("What should be the sender name?"); ?>
    </div>
</div>

<div class="setting onoff" id="useBrRegToGetCompanyInformation">
    <span class="title"><?php echo $this->__f("Try to get the company information from Br Reg."); ?></span>
    <div class="onoff config" id="useBrRegToGetCompanyInformation"></div>
    <div class="description">
        <?php echo $this->__f("If you turn on this feature, it will try to get the company information from  brreg. Simplify the form significantly."); ?>
    </div>
</div>

<div class="setting onoff" id="useEniroSearchEngine">
    <span class="title"><?php echo $this->__f("Try to get the company information from Eniro."); ?></span>
    <div class="onoff config" id="useEniroSearchEngine"></div>
    <div class="description">
        <?php echo $this->__f("If you turn on this feature, it will try to get the company information from  eniro. Simplify the form significantly."); ?>
    </div>
</div>

<div class="setting onoff" id="addExtraEmailToBeSentTo">
    <span class="title"><?php echo $this->__f("Invoice email field."); ?></span>
    <div class="onoff config" id="addExtraEmailToBeSentTo"></div>
    <div class="description">
        <?php echo $this->__f("Extra invoice email field, can be useful if candidate is not the same as the one that pays the bill"); ?>
    </div>
</div>

<div class="setting onoff" id="allowadd">
    <span class="title"><?php echo $this->__f("Allow guests to add events."); ?></span>
    <div class="onoff config" id="allowadd"></div>
    <div class="description">
        <?php echo $this->__f("Turn this featur on if you wish to allow guests to add events to your calendar. Events needs to be confirmed by an adminstrator"); ?>
    </div>
</div>

<div class="textfield setting"  id="email_booking_notification">
    <span class="title"><?php echo $this->__("Send a email notification that user has booked."); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__f("Send an email notification that a user has made a booking on this app?"); ?>
    </div>
</div>

<div id="allowaddonsettings" style="<? echo !$this->getAllowAdd() ? "display:none;" : ""?>">    
    <div class="textfield setting"  id="description_for_allowaddon">
        <span class="title"><?php echo $this->__f("Description when adding"); ?></span>
        <input type="textfield" class="config">
        <div class="description">
            <?php echo $this->__f("This will be displayed as description if someone adds event"); ?>
        </div>
    </div>

    <div class="textfield setting"  id="location_for_allowaddon">
        <span class="title"><?php echo $this->__f("Automatic location"); ?></span>
        <input type="textfield" class="config">
        <div class="description">
            <?php echo $this->__f("This will be displayed as the location if someone adds event"); ?>
        </div>
    </div>

    <div class="textfield setting"  id="starthour_for_allowaddon">
        <span class="title"><?php echo $this->__f("Start hour"); ?></span>
        <input type="textfield" class="config">
        <div class="description">
            <?php echo $this->__f("Start hour when people should be able to request booking (example: 16)"); ?>
        </div>
    </div>

    <div class="textfield setting"  id="stophour_for_allowaddon">
        <span class="title"><?php echo $this->__f("End hour"); ?></span>
        <input type="textfield" class="config">
        <div class="description">
            <?php echo $this->__f("Last hour of the day that people should be able to make a booking (example: 23)"); ?>
        </div>
    </div>
    
    <div class="textfield setting"  id="email_for_allowaddon">
        <span class="title"><?php echo $this->__f("Email address"); ?></span>
        <input type="textfield" class="config">
        <div class="description">
            <?php echo $this->__f("If this email address is specified, it will send notificition to this one if a requested event has been made."); ?>
        </div>
    </div>
</div>

<div class="textfield setting"  id="subject">
    <span class="title"><?php echo $this->__f("Title when sending emails"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__("The default title to use when sending emails."); ?>
    </div>
</div>

<div class="textarea setting"  id="bookingmail">
    <span class="title"><?php echo $this->__f("This is the mail that will be sent upon booking"); ?></span>
    <br><br>
    <textarea style="width:100%; height: 200px;" type="textfield" class="config"></textarea>
    <div class="description">
        
            <br><b>Variables</b>
            <br>{FULLNAME} - Name 
            <br>{USER_CELLPHONE} - Users cellphone number
            <br>{USERNAME} - Username
            <br>{PASSWORD} - Password
            <br>{EVENT_TITLE} - event title 
            <br>{EVENT_DATE} - event date, will display all days of a event including time.
            <br>{EVENT_LOCATION} - event location
            <br>{EVENT_LOCATION_EXTENDED} - event location extended
            <br>{EVENT_DESCRIPTION} - event description
            <br>{GROUP_LOGO} - logo of the group the current user belongs to.
            <br>{USER_EMAILADDRESS} - The email address from the users.
            <br>{COMPANY_NAME} - Name of the company.
            <br>{COMPANY_VAT} - Vat number of the company.
            <br>{COMPANY_STREETADDRESS} - Company street address.
            <br>{COMPANY_POSTNUMBER} - Company postnumber street address.
            <br>{COMPANY_COUNTRY} - Country where the company are registered.
            <br>{COMPANY_CITY} - City where the company are registered
    </div>
</div>

<div class="textfield setting"  id="smstextwaiting">
    <span class="title"><?php echo $this->__("SMS Text (waiting list)"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__("This sms is sent when a candidate is added to waitinglist?"); ?>
    </div>
</div>

<div class="textfield setting"  id="subjectwaiting">
    <span class="title"><?php echo $this->__f("Title when sending emails to waitinglist"); ?></span>
    <input type="textfield" class="config">
    <div class="description">
        <?php echo $this->__("The subject of the email that goes to the attendees set on waitinglist."); ?>
    </div>
</div>

<div class="textarea setting"  id="bookingmailwaiting">
    <span class="title"><?php echo $this->__f("This is the mail that will be sent to attendees under the category waiting list."); ?></span>
    <br><br>
    <textarea style="width:100%; height: 200px;" type="textfield" class="config"></textarea>
    <div class="description">
        
            <br><b>Variables</b>
            <br>{FULLNAME} - Name 
            <br>{USER_CELLPHONE} - Users cellphone number
            <br>{USERNAME} - Username
            <br>{PASSWORD} - Password
            <br>{EVENT_TITLE} - event title 
            <br>{EVENT_DATE} - event date, will display all days of a event including time.
            <br>{EVENT_LOCATION} - event location
            <br>{EVENT_LOCATION_EXTENDED} - event location extended
            <br>{EVENT_DESCRIPTION} - event description
            <br>{GROUP_LOGO} - logo of the group the current user belongs to.
            <br>{USER_EMAILADDRESS} - The email address from the users.
            <br>{COMPANY_NAME} - Name of the company.
            <br>{COMPANY_VAT} - Vat number of the company.
            <br>{COMPANY_STREETADDRESS} - Company street address.
            <br>{COMPANY_POSTNUMBER} - Company postnumber street address.
            <br>{COMPANY_COUNTRY} - Country where the company are registered
            <br>{COMPANY_CITY} - City where the company are registered
    </div>
</div>

<div class="bottom_menu_settings">
    <div class="gs_button savebutton"><?php echo $this->__("Save settings"); ?></div>
</div>

<script>
    <? echo "currentSettings = ".json_encode($this->getConfiguration()->settings).";"; ?>
    var appInstance = $('#informationbox[appid=<? echo $this->getConfiguration()->id?>]');
    thundashop.app.Settings.init(appInstance);
</script>