<?
if ($this->hasReadAccess()) {
    $users = $this->getUsersConnectedToSchema();
    usort($users, array($this, "usortUsersByCommentDate"));
    
    if (count($users)) {

        echo "<hr>";
        echo "<h1> " . $this->__w("Current users added to this booking") . "</h1>";
        echo "<div class='userlistoverview'>";

        $found = false;
        foreach ($users as $user) {
            $comment = $this->getComment($user);
            if ($comment->extraInformation) {
                continue;
            }
            $found = true;
            $link = "?page=users_all_users&userid=" . $user->id;
            $donemarker = "<div class='donemarker' userId='" . $user->id . "'>" . $this->__f("Mark as done") . "</div>";
            echo "<div class='userentry'><a href='$link'>" . $user->fullName . "<div class='datecreated'>" . $comment->dateCreated . "</a></div>$donemarker</div>";
        }

        if (!$found) {
            echo "<div class='userentry'>" . $this->__f("There is no new entries") . "</div>";
        }
        echo "<br/>";
        echo "<H1>" . $this->__f("Users that has been marked as done") . "</h1>";

        $found = false;
        foreach ($users as $user) {
            $comment = $this->getComment($user);
            if (!$comment->extraInformation) {
                continue;
            }
            $found = true;
            $id = $user->id;
            $link = "?page=users_all_users&userid=" . $user->id;
            $color = $this->isInvoiced($user->id) ? "green" : "red";
            echo "<div class='userentryouter'><div class='userentry'><a href='$link'>" . $user->fullName . "<div class='datecreated'>" . $comment->dateCreated . "</a></div></div><i style='color: $color;' class='fa fa-dollar toggleUserId' userId='$id' ></i></div> ";
        }

        if (!$found) {
            echo "<div class='userentry'>" . $this->__f("There is no new entries") . "</div>";
        }
        echo "</div>";
    }
}
?>