<?
/* @var $this ns_74ea4e90_2d5a_4290_af0c_230a66e09c78\Booking */
namespace ns_74ea4e90_2d5a_4290_af0c_230a66e09c78;

if (!isset($_SESSION['userEmailToBook'])) {
    $_SESSION['userEmailToBook'] = null;
}

/* Temp */
//$_SESSION['userEmailToBook'] = "karsten@inkorgen.nu"; 
       
$userToBook = $this->getUserToBook();

if ($userToBook) {
    $_SESSION['group'] = $userToBook->groups[0];
}
$allowAdd = $this->getAllowAdd();
$settings = $this->getConfiguration()->settings;
$starthour = isset($settings->starthour_for_allowaddon) ? $settings->starthour_for_allowaddon->value : 0;
$stophour = isset($settings->stophour_for_allowaddon) ? $settings->stophour_for_allowaddon->value : 24;

$companyRemote = $this->isGetCompanyInformationRemoteEnabled();
$extradep = $this->isExtraDepActivated();
$updateClass = $companyRemote ? "updateOnBlur" : "";
$groups = $this->getApi()->getUserManager()->getAllGroups();

$currentEntry = isset($_GET['entry']) ? $this->getFactory()->getApi()->getCalendarManager()->getEntry($_GET['entry']) : "";


if ($groups != null) {
    shuffle($groups);
}

if ($_SESSION['userEmailToBook'] == null) {
    echo "<div class='pre_booking_signup'>";
    ?>
    <div>
        <div><? echo $this->__f("Event").": ".$currentEntry->title; ?></div>
        <div><? echo $this->__f("Date").": ".$currentEntry->day."/".$currentEntry->month."-".$currentEntry->year; ?></div>
        <div><? echo $this->__f("Location").": ".$currentEntry->location; ?></div>
        <div><? echo $currentEntry->locationObject->locationExtra; ?></div>
    </div>
    <?
    echo "<br/><hr/>".$this->__f("You can use this form to sign up other attendees then yourself since you are an editor or administrator.");
    echo "<br/><br/>".$this->__f("Enter emailaddress to customer: ");
    echo "<br/><input type='textfield' id='bookingEmailCheckAddress' placeholder='customer@emailaddress.xx' style='padding: 5px;'><br/>";
    ?>
        <div class="button check_for_user" entryId="<? echo $currentEntry->entryId; ?>">
            <div class="rightglare"></div>
            <div class="filler"></div>
            <ins class="" id=""><? echo $this->__w("Next"); ?></ins>
        </div>
    <?
    echo "</div>";
}

if ($groups != null && is_array($groups) && count($groups) > 0 && !isset($_SESSION['group']) && $_SESSION['userEmailToBook'] != null && (!$userToBook || !count($userToBook->groups))) {
    if (isset($_GET['entry'])) {
        $_SESSION['entry'] = $_GET['entry'];
    }

    echo "<div class='groupselection'>";
    echo $this->__w("Please select department");
    echo "<br><br>";

    foreach ($groups as $group) {
        $id = $group->id;
        echo "<div groupid='$id' class='selectbox' entryid='$currentEntry->entryId'>";
        $imageId = $group->imageId;
        if ($imageId == "") {
            echo $group->groupName;
        } else {
            echo "<img src='displayImage.php?id=$imageId'/>";
        }
        echo "</div>";
    }
    echo "</div>";
} elseif ($_SESSION['userEmailToBook'] != null) {

    if (isset($_GET['entry']) && isset($_SESSION['entry'])) {
        unset($_SESSION['entry']);
    }

    if (isset($_SESSION['entry'])) {
        $_GET['entry'] = $_SESSION['entry'];
        unset($_SESSION['entry']);
    }
    ?>

    <div style='text-align: center; '>
        <center>
            <div style='width: 510px; border: solid 1px #DDD; background-color: #f9f9f9;margin-bottom: 20px; padding: 10px; font-size: 16px; '>
                <div><? echo $this->__f("Event").": ".$currentEntry->title; ?></div>
                <div><? echo $this->__f("Date").": ".$currentEntry->day."/".$currentEntry->month."-".$currentEntry->year; ?></div>
                <div><? echo $this->__f("Location").": ".$currentEntry->location; ?></div>
                <div><? echo $currentEntry->locationObject->locationExtra; ?></div>
            </div>
        </center>
    </div>

    <center>
        <div style='border: solid 1px #DDD; padding: 10px; width: 510px;'>
        <?
        if (isset($_SESSION['group'])) {
            foreach ($groups as $group) {
                if ($group->id == $_SESSION['group']) {
                    echo "<div class='selected'>";
                    $imageId = $group->imageId;

                    if ($imageId == "") {
                        echo $group->groupName;
                    } else {
                        echo "<img src='displayImage.php?id=$imageId'/>";
                    }
                    echo "<div class='changeit' entryid='$currentEntry->entryId'>" . $this->__w("change") . "</div>";
                    echo "</div>";
                }
            }
        }
        
        $bookingUserName = $userToBook ? "disabled='true' value='$userToBook->fullName'" : "";
        $bookingUserEmail = isset($_SESSION['userEmailToBook']) ? "disabled='true' value='".$_SESSION['userEmailToBook']."'" : "";
        $bookingInvoiceEmail = $userToBook ? "disabled='true' value='$userToBook->emailAddressToInvoice'" : "";
        $bookingcellPhone = $userToBook ? "disabled='true' value='$userToBook->cellPhone'" : "";
        $bookingbirthDay = $userToBook ? "disabled='true' value='$userToBook->birthDay'" : "";
        $bookinReference = $userToBook ? " value='$userToBook->referenceKey'" : "";
        ?>
        <table id="bookingtable" allowadd="<? echo ($allowAdd == true) ? "true" : "false"; ?>">
            <tr><td class="col1"><?php echo $this->__w("Candidate name"); ?></td><td><input id="candidateName" type='textfield'<? echo $bookingUserName; ?>/></td></tr>
            <tr><td class="col1"><?php echo $this->__w("email", 'contact'); ?></td><td><input id="candidateEmail" type='textfield' <? echo $bookingUserEmail; ?>/></td></tr>
            <? if ($this->isInvoiceEmailActivated()) { ?>
                <tr><td class="col1"><?php echo $this->__w("Invoice email"); ?></td><td><input id="candiateInvoiceemail" type='textfield' <? echo $bookingInvoiceEmail; ?>/></td></tr>
            <? } ?>
            <tr><td class="col1"><?php echo $this->__w("phone", 'contact'); ?></td><td><input id="candidateCellphone" type='textfield' <? echo $bookingcellPhone; ?>/></td></tr>

            <? if (!$allowAdd) { ?>
                <tr><td><? echo $this->__w("Company"); ?></td><td>
                        <input type="text" placeholder="" class="search_company" <? echo $bookingbirthDay; ?>>
                        <span class="search_result_area"></span>
                    </td>
                </tr>
                <tr style="display:none;"><td class="col1"><?php echo $this->__w("orgnummer"); ?></td>
                    <td>
                        <input orgLength="<? echo $this->getOrgNumberLength(); ?>" onkeypress='Booking.validate(event)'  class="<? echo $updateClass; ?>" id="candidateBirthday" type='textfield' disabled/>
                    </td>
                </tr>                
                <? if (!$companyRemote) { ?>
                    <tr><td class="col1"><?php echo $this->__w("org", 'contact'); ?></td><td><input id="company" type='textfield'/></td></tr>
                <? } else { ?>
                    <tr><td class="col1"></td><td><div class="companyinformation"><? echo $this->__w("Search for the company you want to enter by clicking the button above, and this box will be filled automatically."); ?></div></td></tr>
                <? } ?>

                <? if ($extradep) { ?>
                    <tr><td class="col1"><? echo $this->getTextForExtraDep(); ?></td><td><input id="candidateExtradep" checktype='<? echo $this->getCheckType(); ?>' <? echo $bookinReference; ?>type='textfield'/></td></tr>
                <? } ?>

                <? if (!$this->isConnectedToCurrentPage()) { ?> 
                    <tr><td class="col1"><?php echo $this->__w("course"); ?></td>
                        <td>
                            <?
                            $places = [];
                            foreach ($this->entries as $entry) {
                                $places[$entry->location] = true;
                            }
                            asort($places);

                            $selectedEntry = false;
                            if (isset($_GET["entry"])) {
                                $selectedEntry = $this->getApi()->getCalendarManager()->getEntry($_GET['entry']);
                            }

                            if (!$selectedEntry) {
                                ksort($places);
                                ?>
                                <select class='select_course_location'>
                                    <option value=''><? echo $this->__w("Select event location"); ?></option>
                                    <?
                                    foreach ($places as $place => $number) {
                                        echo "<option value='" . $place . "'>" . $place . "</option>";
                                    }
                                    ?>
                                </select><br>
                                <?
                            }
                            ?>

                            <select id="event" style='<? echo!$selectedEntry ? "display:none;" : ""; ?>'>
                                <?php
                                foreach ($this->entries as $entry) {
                                    /* @var $entry core_calendarmanager_data_Entry */
                                    $date = str_pad($entry->day, 2, "0", STR_PAD_LEFT) . "/" . str_pad($entry->month, 2, "0", STR_PAD_LEFT) . "-" . $entry->year . " : ";
                                    $title = $entry->title;
                                    $location = $entry->location;
                                    $entryid = $entry->entryId;
                                    if ($entry->lockedForSignup) {
                                        continue;
                                    }
                                    $display = "none";
                                    $selected = "";
                                    if ($selectedEntry && $selectedEntry->entryId == $entryid) {
                                        $display = "";
                                        $selected = "SELECTED";
                                    }

                                    echo "<option value='$entryid' style='display:" . $display . "' location='" . $entry->location . "' " . $selected . ">$date $title</option>";
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                <? } ?>

            <? } else { ?>
                <tr><tr><td class="col1"><?php echo $this->__w("Date"); ?></td><td><input id="date"  style="width:140px;" type='textfield'/> <input style="width:50px;" id="time" type='textfield'/></td></tr></tr>
            <? } ?>
            <tr>
                <td colspan="2" align="right">
                    
                    <div class="button unsetEnteteredUserToBook"  entryid="<? echo $currentEntry->entryId; ?>">
                        <div class="rightglare"></div>
                        <div class="filler"></div>
                        <ins class="send_email" id="send_email"><?
                                echo $this->__w("Change user");
                            ?></ins>
                    </div>
                    
                    <div class="button savebooking" entryid="<? echo $currentEntry->entryId; ?>">
                        <div class="rightglare"></div>
                        <div class="filler"></div>
                        <ins class="send_email" id="send_email"><?
                            if (isset($_GET['waiting'])) {
                                echo $this->__w("Sign up for waiting list");
                            } else {
                                echo $this->isConnectedToCurrentPage() ? $this->__w("Place order") : $this->__w("Sign up");
                            }
                            ?>
                        </ins>
                    </div>
                </td>
            </tr>
        </table>
        </div>
        <?
        if ($userToBook) {
        ?>
            <div class="booking_subusers" style="border: solid 1px #FAFAFA; width: 510px; background-color: #FEfEfE; font-size: 16px; margin-top: 30px; padding: 20px;">
            <?
                $subUsers = $this->getApi()->getUserManager()->getSubUsers($userToBook->id);
                echo "<b>".$this->__w("Sub Accounts")."</b><br/><br/>";
                if (!count($subUsers)) {
                    echo $this->__w("You dont have any subaccounts yet. Fill form below and click \"create user\" to add subaccount");
                } else {
                    ?>
                    <div style="text-align: left; margin-bottom: 5px; padding-left: 5px;">
                        <i class="fa fa-graduation-cap" style=" margin-left: 10px; color:#006e63;"></i> = <? echo $this->__f("Signed on"); ?>
                        <br/><i class="fa fa-graduation-cap" style="margin-left: 10px; color:#d4c300;"></i> = <? echo $this->__f("Waitinglist"); ?>
                        <br/><i class="fa fa-graduation-cap" style="margin-left: 10px; color:#DDD;"></i> = <? echo $this->__f("Not signed on"); ?>
                        <br/>
                        <br/><center> <? echo $this->__f("Click on the user below you wish to attend to this event"); ?></center>
                    </div>
                
                    <?
                    foreach ($subUsers as $subUser) {
                        $color = in_array($subUser->id, $currentEntry->attendees) ? "006e63" : "DDD";
                        $color = in_array($subUser->id, $currentEntry->waitingList) ? "d4c300" : $color;
                        echo "<div style='text-align: left; padding: 5px; border: solid 1px #DDD;' class='addSubUserToEvent' entryid='$currentEntry->entryId' userid='$subUser->id'>";
                        echo '<i class="fa fa-graduation-cap" style="margin-right: 10px; margin-left: 10px; color:#'.$color.';"></i>';
                        echo $subUser->fullName . ", " . $subUser->cellPhone;
                        echo "</div>";
                    }
                }
            ?>
                
                <div>
                    
                    <div class="addUser_booking">
                        
                        <table style="border: solid 1px #DDD; margin-top: 20px; padding: 20px; width: 510px;" >
                            <tr><td colspan="2" style=''><center style='margin-bottom: 5px; border-bottom: solid 1px #DDD; padding-bottom: 5px;'> <b><? echo $this->__f("Add new account"); ?> </b></center></td> </tr>
                            <tr><td class="col1"><?php echo $this->__w("Candidate name"); ?></td><td><input id="subAccountCandidateName" type='textfield' /></td></tr>
                            <tr><td class="col1"><?php echo $this->__w("phone", 'contact'); ?></td><td><input id="subAccountCandidatePhone" type='textfield' /></td></tr>
                            <tr>
                                <td colspan="2" align="right">
                                    <div class="button createSubAccount" entryid="<? echo $currentEntry->entryId; ?>" parent="<? echo $userToBook->id; ?>">
                                        <div class="rightglare"></div>
                                        <div class="filler"></div>
                                        <ins class="send_email" id="send_email">
                                            <?
                                                echo $this->__w("Create user");
                                            ?>
                                        </ins>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>

                </div>
            </div>
        <?
        }
        ?>
               
    </center>    

    <? if ($allowAdd) { ?>

        <script>
            //    $('#date').datetimepicker();
            $("#date").datetimepicker({
                altField: "#time",
                stepMinute: 15,
                hourMin: <? echo $starthour; ?>,
                hourMax: <? echo $stophour; ?>
            });
        </script>
        <?
    }
}

if ($this->hasReadAccess()) {
    $users = $this->getUsersConnectedToSchema();
    if (count($users)) {

        echo "<hr>";
        echo "<h1> " . $this->__w("Current users added to this booking") . "</h1>";
        echo "<div class='userlistoverview'>";

        $found = false;
        foreach ($users as $user) {
            $comment = $this->getComment($user);
            if ($comment->extraInformation) {
                continue;
            }
            $found = true;
            $link = "?page=users_all_users&userid=" . $user->id;
            $donemarker = "<div class='donemarker' userId='" . $user->id . "'>" . $this->__f("Mark as done") . "</div>";
            echo "<div class='userentry'><a href='$link'>" . $user->fullName . "<div class='datecreated'>" . $user->rowCreatedDate . "</a></div>$donemarker</div>";
        }

        if (!$found) {
            echo "<div class='userentry'>" . $this->__f("There is no new entries") . "</div>";
        }
        echo "<br/>";
        echo "<H1>" . $this->__f("Users that has been marked as done") . "</h1>";

        $found = false;
        foreach ($users as $user) {
            $comment = $this->getComment($user);
            if (!$comment->extraInformation) {
                continue;
            }
            $found = true;
            $id = $user->id;
            $link = "?page=users_all_users&userid=" . $user->id;
            $color = $this->isInvoiced($user->id) ? "green" : "red";
            echo "<div class='userentryouter'><div class='userentry'><a href='$link'>" . $user->fullName . "<div class='datecreated'>" . $user->rowCreatedDate . "</a></div></div><i style='color: $color;' class='fa fa-dollar toggleUserId' userId='$id' ></i></div> ";
        }

        if (!$found) {
            echo "<div class='userentry'>" . $this->__f("There is no new entries") . "</div>";
        }
        echo "</div>";
    }
}
?>
