<?
/* @var $this ns_74ea4e90_2d5a_4290_af0c_230a66e09c78\Booking */
$entry = $this->getApi()->getCalendarManager()->getEntry($_GET['entryId']);
$positions = $this->getCountOfFreePositions($entry);

?>
<input type="hidden" id="entry_id_to_order" value="<? echo $entry->entryId; ?>"/>

<div>
    Antall personer <select class="select_persons">
        <?
        for ($i=1;$i <= $positions;$i++) {
            echo "<option value='$i'>$i</option>";
        }
        
        ?>
    </select>
    
    <?
        for ($i=1;$i <= $positions;$i++) {
            
            echo "<div class='personrow' person='$i'>";
            echo "Person $i";
            echo "<div class='innercontent'>";
            echo "<br/><input class='name' type='textfield' placeholder='Navn'/> ";
            echo "<br/><input class='email' type='textfield' placeholder='din@epost.no'/> ";
            echo "<br/><input class='cellphone' type='textfield'  placeholder='Mobilnr'/> ";
            echo "<br/><input style='width: 20px;'type='checkbox' class='children'/>Barn (til og med 16 år) ";
            echo "</div>";
            echo "</div>";
        }
    ?>
    
    <div class="order_summary_booking">
        
    </div>
    <br/>
    <div class="shop_button" style="float: right;">Gå til betaling</div>
    <br/>
    <br/>
</div>

<script>
    $(document).ready(function() {
        app.Booking.personsChanged();
    });
</script>