<?php

namespace ns_900e5f6b_4113_46ad_82df_8dafe7872c99;

/* @var $this CartManager */

$cartItems = (array) $this->getApi()->getCartManager()->getCart()->items;

if (count($cartItems) == 0) {
    $this->includefile("nocartitemss");
    return;
}
?>

<div class="cart">
    <div class="shoppingcartheader">
    <?php echo $this->__w("Cart overview"); ?>
    </div>

    <?
    

    foreach ($cartItems as $cartItem) {
        /* @var $product core_productmanager_data_Product */
        $product = $cartItem->product;

        if (isset($cartItem->variations)) {
            $variations = implode(":", $cartItem->variations);
        }
        
        ?>
        <div class="product" productid="<?php echo $product->id; ?>">
            <table class='product_row_table'>
                <tr>
                    <td valign='top' class='image_area'>
                        <div class="productcount inline">
                            <div class="up" cartItemId="<? echo $cartItem->cartItemId; ?>">/\</div>
                            <div class="counter"> <?php echo $cartItem->count; ?></div>
                            <div class="down" cartItemId="<? echo $cartItem->cartItemId; ?>">\/</div>
                        </div>
                        <?php
                        $imagedata = \ProductHelper::findMainImageId($product);
                        if ($imagedata) {
                            ?>
                            <div class="image inline"><img src="displayImage.php?id=<?php echo $imagedata ?>&width=100&height=100"/></div>
                        <?php } else { ?>
                            <span class="no_image"><span class="inner"><?php echo $this->__("No image added for this product"); ?></span></span>
    <?php } ?>

                    </td>
                    <td valign='top'>
                        <a href='?page=<? echo $product->page->id; ?>'>
                            <div class="wrapperright inline">
                                <div class="title"><?php echo $product->name; ?></div>
                                <div class="cartdesc"><?php echo $product->description[0]; ?></div>
                            </div>
                            <div class="price"> <?php
                                $imteprice = $cartItem->product->price; 
                                $imteprice = $this->getPriceWithTaxSpecifed($imteprice, $product);
//                                echo sprintf('%0.2f', $imteprice);
                                echo \ns_9de54ce1_f7a0_4729_b128_b062dc70dcce\ECommerceSettings::formatPrice($imteprice);
                                ?></div>
                                    <? if (count($cartItem->variations) > 0) { ?>
                                <div>
                                    <div class='variationselection'>
                                        <?
                                        echo \HelperCart::getVartionsText($cartItem);
                                        ?>
                                    </div>
                                </div>
    <? } ?>
                        </a>
                        <a class='removeproductfromcart' data-avoidscroll='true' href="?page=cart&action=removeproduct&cartItemId=<? echo $cartItem->cartItemId; ?>"><i class='fa fa-trash-o'></i><span class='removeitemtext'> <? echo $this->__w("Remove item"); ?></span></a>

                    </td>
                </tr>
            </table>
        </div>
        <?
    }

    if ($this->canCalculateShippingPrice() == false) {
        $shippingprice = $this->__w("Click next to select shipping options");
    } else {
        $shippingprice = $this->getShippingPrice(true);
    }

    $taxes = $this->getApi()->getCartManager()->getTaxes();
    ?>
</div>

<div class='summary'>
    <? if (isset($this->cart->couponCost) && $this->cart->couponCost) { ?>
        <div class='row'><? echo $this->__w("Coupon discount"); ?><span> <?php echo $this->getFactory()->getCurrencyName(); ?><? echo sprintf('%0.2f', $this->cart->couponCost); ?></span></div>
    <? } ?>
    <div class='row shipping_price'><? echo $this->__w("Shipping price"); ?><span><? echo \ns_9de54ce1_f7a0_4729_b128_b062dc70dcce\ECommerceSettings::formatPrice($shippingprice); ?> </span></div>
        <? if ($taxes) { ?>
        <div class='row'>
            <?
            echo $this->__w("Taxes");

            foreach ($taxes as $tax) {
                echo "<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" . $this->__w("Taxes") . " (" . $tax->taxGroup->taxRate . "%) <span>" .  \ns_9de54ce1_f7a0_4729_b128_b062dc70dcce\ECommerceSettings::formatPrice($tax->sum) . "</span>";
            }
            ?>
            <br> 
        </div>
<? } ?>
    <div class='row'><? echo $this->__w("Total");
if ($taxes) {
    echo " (" . $this->__w("included taxes") . ")";
} ?><span> <? echo \ns_9de54ce1_f7a0_4729_b128_b062dc70dcce\ECommerceSettings::formatPrice($this->getTotalAmount()); ?></span></div>
</div>

