<?
$paymentMethods = $this->getPaymentMethods(true);
?>
<div class="payment">
    <div class='shoppingcartheader'><?php echo $this->__w("Please select a payment method."); ?></div>
    <div class='checkoutinner'>
        <center>
            <?php
            $selected = "selected";
            foreach ($paymentMethods as $paymentMethod) {
                $appName = $paymentMethod->getName();
                $logo = $paymentMethod->getLogo();
                $id = $paymentMethod->getId();
                $appId = $paymentMethod->getPaymentApplication()->getApplicationSettings()->id;
                echo "
                    <div paymentid='$id' appid='$appId' class='inline method $selected'>
                        <div class='logo'><img src='$logo'/></div>
                        <div class='title'>$appName</div>
                    </div>
                ";
                $selected="";
            }
            ?>
        </center>
    </div>
    <div class='extended_payment_option'>
        <?
        $first = true;
        foreach ($paymentMethods as $paymentMethod) {
            $html = $paymentMethod->getPaymentApplication()->getExtendedPaymentForm($paymentMethod);
            $id = $paymentMethod->getId();
            $add = "";
            if ($first) {
                $first = false;
                $add = "style='display:block;'";
            }
            
            $details = $paymentMethod->getPaymentDetails();
            if (!$details) {
                $app = $paymentMethod->getPaymentApplication();
                if ($app != null && method_exists($app, "getDetails")) {
                    $details = $app->getDetails();
                }
            }
            echo "<div $add class='extendedinfo' extendedid='$id'>$html</div>";
            echo "<div $add class='paymentdetails $id'>$details<br><br></div>";
        }
        ?>
    </div>

    <div class='checkout_button_area'>
        <div id="previouse" class="shop_button previouse"><?php echo $this->__w("Previous"); ?></div>
        <div id="confirmorder" class="shop_button"><?php echo $this->__w("Confirm order"); ?></div>
    </div>
</div>
