<?
/* @var $this \ns_900e5f6b_4113_46ad_82df_8dafe7872c99\CartManager */
$count = $this->getCount();
$text = $this->__w("Items in your basket").": ".$count;
if (!$count) {
    $text = $this->__w("No items added");
}
?>

<div class='checkout_area'>
    <i class='fa fa-shopping-cart'></i>
    <? echo $text; ?>
    <a href='/?page=cart'><div class='checkout'><? echo $this->__f("Check out"); ?></div></a>
</div>

<?

?>