<?
/* @var $pms \ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBooking */
/* @var $this \ns_1ba01a11_1b79_4d80_8fdd_c7c2e286f94c\PmsSearchBox */
$pms = new \ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBooking();

$types = $this->getSearchTypes();
$filter = $pms->getSelectedFilter();
$searchWord = $filter ? $filter->searchWord : "";
$bookingItems = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName());
$activeDelete = "";
$activeGrouping = "";
$channels = (array)$this->getChannelMatrix();
if($filter->includeDeleted) {
    $activeDelete = "advanceserachbuttonenabled";
}
if($filter->groupByBooking) {
    $activeGrouping = "advanceserachbuttonenabled";
}
?>


<span class="advancesearch" gstype='form' method='doAdvanceSearch'>
    <div title="<? echo $this->__f("Group booking"); ?>" class="top-row-icon"><i class="fa fa-users advancesearchicon <?php echo $activeGrouping; ?>" forfilter='groupbooking'></i></div>
    <div title="<? echo $this->__f("Include deleted"); ?>" class="top-row-icon"><i class="fa fa-trash-o advancesearchicon <?php echo $activeDelete; ?>" forfilter='includedeleted'></i></div>
    <input type='hidden' gsname='groupbooking' value=''>
    <input type='hidden' gsname='includedeleted' value=''>
    <div class="gs_headerbox">
        <div>
            <?
            echo $this->__f("From");
            ?>
        </div>
        <input class="gsniceinput1" id="startdate" value="<? echo date("d.m.Y", strtotime($filter->startDate)); ?>" gsname='from'/>
        <i class="gsicon-calendar-text"></i>
    </div>

    <div class="gs_headerbox">
        <div>
            <?
            echo $this->__f("To");
            ?>
        </div>
        <input class="gsniceinput1" id="enddate" value="<? echo date("d.m.Y", strtotime($filter->endDate)); ?>" gsname='to'/>
        <i class="gsicon-calendar-text"></i>
    </div>

    <div class="gs_headerbox">
        <div>
            <?
            echo $this->__f("Filtertype");
            ?>
        </div>
        <select gsname='filtertype'>
            <?php
            foreach($types as $typeId => $val) {
                $selected = "";
                if($filter->filterType == $typeId) {
                    $selected = "SELECTED";
                }
                echo "<option value='$typeId' $selected>$val</option>";
            }
            ?>
        </select>
    </div>

    <?php 
    if(sizeof($channels) > 0) { 
        $pmssearchbox = new \ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBookingColumnFormatters(null);
        $chnls = $pmssearchbox->getChannels();
        ?>
        <div class="gs_headerbox">
            <div>
                <?
                echo $this->__f("Channel");
                ?>
            </div>
            <select class="managementviewdropdowninput filterType" gsname='channel'>
                <?php
                echo "<option value=''>All channels</option>";
                foreach($channels as $idx => $channel) {
                    $selected = "";
                    if($filter->channel == $idx) {
                        $selected = "SELECTED";
                    }
                    $name = $chnls[$idx] ? $chnls[$idx] : $idx;
                    echo "<option value='$idx' $selected>".$name."</option>";
                }
                ?>
            </select>
        </div>
    <? } ?>
    
    <div class="gs_headerbox">
        <div>
            <?
            echo $this->__f("Room types");
            $counter = "All";
            if(sizeof($filter->typeFilter) > 0) {
                $counter = sizeof($filter->typeFilter);
            }
            ?>
        </div>
        <div style='padding-top:4px;color:blue; cursor:pointer;' class='typeselectiontoggle'><span class='selectioncount'><?php echo $counter; ?></span> types</div>
        <span class='roomtypeselection'>
            <i class='fa fa-close' style='position:absolute;top:3px;cursor:pointer;'></i>
            <?php
            foreach($bookingItems as $type) {
                $checked = "";
                if(in_array($type->id, (array)$filter->typeFilter)) {
                    $checked = "CHECKED";
                }
                echo "<div class='type'><input type='checkbox' style='float:left;' gsname='typeselection_".$type->id."' $checked>" . $type->name . "</div>";
            }
            ?>
        </span>
    </div>
    
    <div class="gs_headerbox">
        <div>
            <?
            echo $this->__f("Other");
            $customers = sizeof($filter->customers);
            $codes = sizeof($filter->codes);
            $addons = sizeof($filter->addons);
            $counter = "($customers,$codes,$addons)";
            ?>
        </div>
        <div style='padding-top:4px;color:blue; cursor:pointer;' class='otherselectiontoggle'><span class='selectioncount'><?php echo $counter; ?></span></div>
        <span class='otherselection'>
            <?php
            $this->displayOtherSelection();
            ?>
        </span>
    </div>

    <div class="gs_headerbox">
        <span class='shop_button applyfilterbutton'>Apply filter</span>
        <span class='shop_button opensimplesearch' style='margin-left: 5px;'>Open simple search</span>
        <span class='shop_button clearfilter' style='margin-left: 5px;'>Clear filter</span>
        <span class="top-row-icon" gsclick="runProcessor" title='Run processor' style='margin-left: 25px;'><i class="fa fa-cube"></i></span>
        <span class="top-row-icon" gsclick="resetAutoAssignedStatusForCheckinsToday" title='Reset auto assigned status' style='margin-left: 25px;'><i style="right: -20px;" class="fa fa-magic"></i></span>
    </div>
</span>

<span class='dailydaterangepicker'>
    <i class='fa fa-close' onclick='$(".dailydaterangepicker").slideUp()' style='float:right; cursor:pointer;'></i>
    <div class='header' type='checkin'>Checking in</div>
    <div class='header' type='checkout'>Checking out</div>
    <div class='header' type='registered'>Registered</div>
    <div daytype='today'>Today</div>
    <div daytype='tomorrow'>Tomorrow</div>
    <div daytype='aftertomorrow'>Day after tomorrow</div>
    <div daytype='yesterday'>Yesterday</div>
    <div daytype='beforeyesterday'>Day before yesterday</div>
    <div daytype='pastthreedays'>Past three days</div>
    <div daytype='nextthreedays'>Next three days</div>
</span>
<span gstype="form" method="search" class='simplesearch'>
    
    <div title="<? echo $this->__f("Latest registered users"); ?>" type='registered' daytype='today' class="top-row-icon displaydailydatepicker <? echo $filter && $filter->filterType == "registered" ? 'active' : ''; ?>"><i class="gsicon-database-upload"></i></div>
    <div title="<? echo $this->__f("Users checkin today"); ?>" type='checkin' day="0" daytype='today' class="top-row-icon displaydailydatepicker <? echo $filter && $filter->filterType == "checkin" ? 'active' : ''; ?>"><i class="gsicon-enter"></i></div>
    <div title="<? echo $this->__f("Users checkout today"); ?>" type='checkout' day="0" daytype='today' class="top-row-icon displaydailydatepicker <? echo $filter && $filter->filterType == "checkout" ? 'active' : ''; ?>"><i class="gsicon-exit"></i></div>
    <input class="gsniceinput1" gstype='submitenter' gsname='searchtext' placeholder="<? echo $this->__f("Search"); ?>" value='<? echo $searchWord; ?>'/>
    <div class="top-row-icon <? echo $searchWord ? 'active' : ''; ?>" gstype='submit' title='Show filtering'><i class="gsicon-search"></i></div>
    <div class="top-row-icon advancesearchtoggle"><i class="gsicon-search2" title='Advance search'></i></div>
    <div class="top-row-icon clearfilter" title='Clear filter'><i class="fa fa-trash-o"></i></div>
    
    <?php
    if($this->getApi()->getPmsManager()->hasLockSystemActive($this->getSelectedMultilevelDomainName())) {
        ?>
        <div class="top-row-icon" onclick="window.open('/scripts/securitylist.php?engine=<?php echo $this->getSelectedMultilevelDomainName(); ?>', 'securitylisttab')" title='Printable list'><i class="fa fa-file-pdf-o"></i></div>
        <?php
    } else {
        ?>
        <div class="top-row-icon" onclick="window.open('/scripts/securitylist.php?engine=<?php echo $this->getSelectedMultilevelDomainName(); ?>&useCheckinInstead=true', 'securitylisttab')" title='Printable list'><i class="fa fa-file-pdf-o"></i></div>
        <?php
    }
    ?>
</span>




<script>
    $('#startdate').datepicker({ dateFormat: "dd.mm.yy",  changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            $('.PmsNewBooking [gsname="numberOfRooms"]').val(0);
            var curEnd = moment.utc($('#enddate').val(), "DD.MM.YYYY").local();
            var date = moment(dateText, "DD.MM.YYYY");
            
            var diff = curEnd.valueOf() - date.valueOf();
            if(diff < 0) {
                date.add(1, 'days');
                $('#enddate').val(date.format('DD.MM.YYYY')); 
            }
        }
    });
    
    $('#enddate').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            $('.PmsNewBooking [gsname="numberOfRooms"]').val(0);
            var curStart = moment.utc($('#startdate').val(), "DD.MM.YYYY").local();
            var date = moment.utc(dateText, "DD.MM.YYYY").local();
            
            var diff = date.valueOf() - curStart.valueOf();
            if(diff < 0) {
                $('#startdate').val(date.format('DD.MM.YYYY')); 
            }
        }
    });
    $(document).on('click', '.PmsNewBooking .gsicon-calendar-text', function() {
        $(this).closest('div').find('input').focus();
    });
    
    if(localStorage.getItem('advancesearchtoggled') === "true") {
        $('.PmsSearchBox .simplesearch').hide();
        $('.PmsSearchBox .advancesearch').show();
    }
    
    $(document).on('click', '.PmsSearchBox .gsicon-calendar-text', function() {
        $(this).closest('div').find('input').focus();
    });
    
</script>