<?php
/* @var $this \ns_1ba01a11_1b79_4d80_8fdd_c7c2e286f94c\PmsSearchBox */
$servers = (array)$this->getApi()->getGetShopLockSystemManager()->getLockServers();

foreach($servers as $server) {
    $down = false;
    if(!$server->lastPing) {
        $down = true;
    }
    $diff = time() - strtotime($server->lastPing);
    if($diff > 300) {
        $down = true;
    }
    if($down) {
        echo "<div style='font-size:14px; color:red; font-weight:bold; text-align:left'>";
        echo "WARNING: Server with servername: " . $server->givenName . " is not responding, last contact: ". date("d.m.Y H:i", strtotime($server->lastPing)) . " - <a target='resolveserver' href='/scripts/resolveserver/index.php?id=".$server->id."&step=2&unit=zwaveserver'>click here to resolve the issue</a>";
        echo "</div>";
    }
}

$hasEmailProblem = $this->getApi()->getStoreManager()->hasEmailErrors();
if($hasEmailProblem) {
        echo "<div style='font-size:14px; color:red; font-weight:bold; text-align:left'>";
        echo "<i class='fa fa-inbox'></i> EMAIL ERROR: We are not able to authenticate with your email server, please update your email settings <a href='/settings.php?page=mailsettings' target='_newemailsettings'>here</a>";
        echo "</div>";
}

?>