package com.getshop.javaapi.core;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import java.util.LinkedHashMap;
import com.google.gson.JsonElement;
import com.thundashop.core.common.JsonObject2;
import com.thundashop.core.common.Communicator;
public class APILogoManager {

      public Communicator transport;

      public APILogoManager(Communicator transport){
           this.transport = transport;
      }

     /**
     * Remove the current logo.
     * @return
     * @throws ErrorException
     */
     public void deleteLogo()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "deleteLogo";
          gs_json_object_data.interfaceName = "app.logo.ILogoManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Get the logo file id.
     * @return
     * @throws ErrorException
     */
     public JsonElement getLogo()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getLogo";
          gs_json_object_data.interfaceName = "app.logo.ILogoManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          JsonElement object = gson.fromJson(result, JsonElement.class);
          return object;
     }

     /**
     * Set a logo to your webshop.
     * @param fileId The file id generated by the one storing this.
     * @return
     * @throws ErrorException
     */
     public void setLogo(Object fileId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("fileId",new Gson().toJson(fileId));
          gs_json_object_data.method = "setLogo";
          gs_json_object_data.interfaceName = "app.logo.ILogoManager";
          String result = transport.send(gs_json_object_data);
     }

}
