<?
/* @var $this \ns_3ff6088a_43d5_4bd4_a5bf_5c371af42534\QuestBackManagement */
$test = $this->getApi()->getQuestBackManager()->getTest($_POST['data']['testid']);
$tree = $this->getConfigurationSetting("list");
$questions = false;
if ($tree) {
    $tree = json_decode($tree);
    $questions = $tree[0]->children;
}


?>
<div class='testsettings'>
    <?
    echo "Test name:&nbsp;&nbsp;<input type='textfield' class='test_name' value='$test->name'/>";
    $chcekdForce = $test->forceCorrectAnswer ? "checked='checked'" : "";
    echo "<br/><br/><input type='checkbox' $chcekdForce class='force_correct_answers'/> Force correct answers?";
    
    if (!$questions) {
        echo "You have not created any questions yet";
    } else {
        foreach ($questions as $category) {
            echo "<h2>".$category->text."</h2>";
            foreach ($category->children as $question) {
                $questionId = $question->li_attr->nodeid;
                $selected = in_array($questionId, $test->questions) ? "checked='checked'" : "";
                echo "<input $selected type='checkbox' class='test_qustions_added' value='$questionId' style='position: relative; top: 2px;'/> ".$question->text."<br/>";
            }
        }
    }
    
    ?>
    <div class='category_settings_box'>
        <div class='category_settings_title'>Red</div>
        <table>
            <tr><td>From</td><td><input style='width: 400px;' id="red_from"  type='textfield' value='<? echo $test->redFrom; ?>' /></td></tr>
            <tr><td>To</td><td><input style='width: 400px;' id="red_to" type='textfield' value='<? echo $test->redTo; ?>' /></td></tr>
            <tr><td>Text</td><td><textarea style='width: 400px;' id="red_text" ><? echo $test->redText; ?></textarea></td></tr>
        </table>
    </div>    
    
    <div class='category_settings_box'>
        <div class='category_settings_title'>Yellow</div>
        <table>
            <tr><td>From</td><td><input id="yellow_from" style='width: 400px;' type='textfield' value='<? echo $test->yellowFrom; ?>' /></td></tr>
            <tr><td>To</td><td><input id="yellow_to" style='width: 400px;' type='textfield' value='<? echo $test->yellowTo; ?>' /></td></tr>
            <tr><td>Text</td><td><textarea id="yellow_text" style='width: 400px;' ><? echo $test->yellowText; ?></textarea></td></tr>
        </table>
    </div>

    <div class='category_settings_box'>
        <div class='category_settings_title'>Green</div>
        <table>
            <tr><td>From</td><td><input id="green_from" style='width: 400px;' value='<? echo $test->greenFrom; ?>' type='textfield'/></td></tr>
            <tr><td>To</td><td><input id="green_to" style='width: 400px;' type='textfield' value='<? echo $test->greenTo; ?>' /></td></tr>
            <tr><td>Text</td><td><textarea id="green_text" style='width: 400px;' ><? echo $test->greenText; ?></textarea></td></tr>
        </table>
    </div>
    
    <br/><br/>
    <div class='gs_button saveTestSettings' testid='<?  echo $test->id; ?>'><? echo $this->__f("Save"); ?></div>
</div>