
<?
/* @var $this ns_3ff6088a_43d5_4bd4_a5bf_5c371af42534\QuestBackManagement */
if (!$_POST['data']['searchWord']) {
    return;
}

$foundUsers = $this->getApi()->getUserManager()->findUsers($_POST['data']['searchWord']);
$compGrouped = $this->groupByCompany($foundUsers);
foreach ($compGrouped as $compId => $allUsers) {
    $comp = $this->getApi()->getUserManager()->getCompany($compId);
    echo "<div class='groupedByCompany'>";
    echo $comp->name;
?>
    <table id="usermanagementTable" width='100%'>
        <th></th>
        <th><? echo $this->__f("Name"); ?></th>
        <th><? echo $this->__f("Email"); ?></th>
        <th><? echo $this->__f("CellPhone"); ?></th>
        <?
        foreach ($allUsers as $user) {
            if ($user->fullName || $user->emailAddress || $user->cellPhone) {
                $checked = "";
                if (isset($_SESSION['ns_3ff6088a_43d5_4bd4_a5bf_5c371af42534/selectedUsers'])) {
                    $index = array_search($user->id, $_SESSION['ns_3ff6088a_43d5_4bd4_a5bf_5c371af42534/selectedUsers']);
                    if($index !== FALSE){
                        $checked = "checked='true'";
                    }
                }
                
                echo "<tr><td width='25'><input type='checkbox' $checked class='user_to_send' value='$user->id'></td><td>$user->fullName</td><td>$user->emailAddress</td><td>$user->cellPhone</td></tr>";
            }
        }
        ?>

    </table>
<?
    echo "</div>";
}
?>