<?
/* @var $this ns_3ff6088a_43d5_4bd4_a5bf_5c371af42534\QuestBackManagement */
?>
<div>
    <h2><? echo $this->__f("Send tests"); ?></h2>
    What test do you want to send out?: &nbsp;&nbsp;
    <dl class="dropdown">
        <dt>
            <a href="#">
                <span class="hida"><? echo $this->__w("Choose test");?></span>
                <p class="multiSel"></p>      
            </a>
        </dt>
        <dd>
           <div class="multiSelect">
               <ul>
                    <?
                        $tests = $this->getApi()->getQuestBackManager()->getAllTests();
                        foreach ($tests as $test) {
                            echo "<li> <input type='checkbox' class='usertest' value='$test->name' testid='$test->id'>$test->name</li>";
                        }
                    ?>
               </ul>
            </div> 
        </dd>
    </dl>
    
    <div class="usermanagement"> 
        <label><? echo $this->__w("Search");?></label>
        <input id="usermanagementInput" class="gsniceinput1" type="txt" gstype="submitenter" name="searchField" placeholder="<? echo $this->__w("Search");?>">    
    </div>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <div class="testUserSearchResult">
        
    </div>
    
    <br/>
    
    <div class='summary'>
        <? $this->includefile("personlist"); ?>
    </div>
    <div class='gs_button assignTestsToUser'><? echo $this->__f("Send"); ?></div>
</div>