<?php
/* @var $this ns_9f8483b1_eed4_4da8_b24b_0f48b71512b9\CrmListFilter */
$whens = array();
$whens['whenregistered'] = "When registered";
$whens['whenbooked'] = "When booked";

$types = array();
$types['all'] = "All types";
$types['companies'] = "Companies only";
$types['private'] = "Private only";

$filter = $this->getSelectedFilter();
$keyword = "";
$start = "";
$end = "";
$when = "";
$selectiontype = "";
if(isset($filter['keyword'])) { $keyword = $filter['keyword']; }
if(isset($filter['start'])) { $start = $filter['start']; }
if(isset($filter['end'])) { $end = $filter['end']; }
if(isset($filter['when'])) { $when = $filter['when']; }
if(isset($filter['selectiontype'])) { $selectiontype = $filter['selectiontype']; }

?>
<div style='text-align: center; margin-bottom:20px; max-width:1500px; margin:auto;' gstype='form' method='applyFilter'>
    <h3>Filter</h3>
    <span class='shop_button newcustomerbutton' style='float:left; background-color:green;'>Add a new customer</span>
    <input type="text" gsname='start' class='gsniceinput1 startdate' placeholder='start' value='<?php echo $start; ?>'>
    <input type="text" gsname='end' class='gsniceinput1 enddate' placeholder='end' value='<?php echo $end; ?>'>
    <select class='gsniceselect1' style='height:35px;' gsname='when'>
        <?php
        foreach($whens as $idx => $text) {
            $selected = "";
            if($when == $idx) {
                $selected = "SELECTED";
            }
            echo "<option value='$idx' $selected>$text</option>";
        }
        ?>
    </select>
    <select class='gsniceselect1' style='height:35px;' gsname='selectiontype'>
        <?php
        foreach($types as $idx => $val) {
            $selected = "";
            if($selectiontype == $idx) { $selected = "SELECTED"; }
            echo "<option value='$idx' $selected>$val</option>";
        }
        ?>
    </select>
    <input type="text" gsname='keyword' class="gsniceinput1" placeholder='Search word' value='<?php echo $keyword; ?>'>
    <span class='shop_button' gstype='submit'>Load filter</span>
    
    <?php
    $this->includefile("newcustomer");
    if($this->createdCustomer) {
        echo "<div class='successcreate'><i class='fa fa-check'></i> Customer has been created, look in the list below.</div>";
    }
    if($this->createdCustomerFailed) {
        echo "<div class='failedcreate'><i class='fa fa-warning'></i> Customer has not been created, it most likely exists already.</div>";
    }
    ?>

    <h3>Result</h3>
</div>

<script>
     $('.startdate').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
     $('.enddate').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true });
     
     setTimeout(function() {
         $('.successcreate').fadeOut();
         $('.failedcreate').fadeOut();
     }, "3000");
</script>
