<?
/* @var $this ns_a5175115_187a_4721_90e5_4752fa52ca7a\SupportNew */
$email = ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->emailAddress;
$prefix = ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->prefix;
$phone = ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject()->cellPhone;
?>
<script>document.location.href='https://support.zauistay.com/hc/en-us/';</script>
<div class='questionbox' style="display:none;">

    <div class='inner'>
        <i class='fa fa-close closebutton'></i>
        
        <div class='ticketcreated'>
            <div class='ticketcreatedheader'>
                <i class='fa fa-check'></i>
                <?
                echo $this->__f("Your ticket has been created");
                ?>
            </div>
            <?
            echo "<div class='ticketinfo'>".$this->__f("Ticket")."</div>";
            ?>
            <div class='ticketnumber'>
                123456
            </div>
            
            <div>
                <? echo $this->__f("We will respond as soon as possible"); ?>
            </div>
        </div>
        
        <div class='askquestion'>
            <h2>Almost done...</h2>
            <div>
                <? echo $this->__f("Changes/Updates to this issue will be notified to the following email address"); ?>
                <br/>
                <br/> Email
                <br/>
                <input class='gsniceinput1 emailtonotify' value='<? echo $email; ?>'/>
                <br/> Phone
                <br/>
                <input class='gsniceinput1 phoneprefix' value='<? echo $prefix; ?>'/>
                <input class='gsniceinput1 phonenumber' value='<? echo $phone; ?>'/>
            </div>
            <br/>
            <?
            echo $this->__f("Please specify urgency..");
            ?>
            <br/>
            <div class='shop_button urgency' type='normal'><? echo $this->__f("Normal"); ?></div>
            <br/><div class='shop_button urgency' type='urgent'><? echo $this->__f("Urgent"); ?></div>         
        </div>
        
    </div>
</div>

<div class='supportright'>
    <div class="infomation">
        <div class="title">
            <?
            echo $this->__f("Need help?");
            ?>
        </div>
        <?
        echo $this->__f("If the systems are down you can reach us at the phone <b>+47 33 20 08 48</b>, this number should <b>ONLY</b> be used if the systems are unavailable. All other issues needs to be addressed trough the form below. Please make a note of this number where you can access it if the system is down. This number is open monday - friday 15:00 - 21:00, 08:00 - 21:00 in the weekends. If abused you might risk being charged for the call.");
        
        $filter = new core_ticket_TicketFilter();
        $filter->start = $this->convertToJavaDate(strtotime(date("01.m.Y")));
        $filter->end =  $this->convertToJavaDate(strtotime(date("t.m.Y")));
        $filter->storeId = $this->getApi()->getStoreManager()->getStoreId();
        $stats = $this->getSystemGetShopApi()->getCustomerTicketManager()->getTicketReportForCustomer($filter->start, $filter->end, $filter->storeId, null);
        
        echo "<div style='font-weight:bold;margin-top: 20px;'>";
        echo "PS: You have " . round($stats->hoursIncluded,2) . " hours included in your support package, and have used: " . $stats->billableHours . " hours ". $stats->billableMinutes ." minutes of them<br>";
        echo "Meetings, accounting, and extraordinary support is not included in the free support.<br>";
        echo "We will charge an additional fee for all support above the monthly included time, for a more detailed view go to the reports section in the top menu.";
        echo "</div>";
        
//        $timeSpent = $this->getSystemGetShopApi()->getCustomerTicketManager()->getTimeSpentInvoiceThisPeriode();
        ?>
    </div>

    <div class="warningbox">
        <i class="fa fa-warning"></i>
        <?
        echo $this->__f("Only register one support issue for each ticket!")
        ?>
    </div>

    <div>
        <span class='label'>
            <? echo $this->__f("Subject"); ?>    
        </span>

        <br/>
        <input class="gsniceinput1 subject" />
        <br/>
        <br/>

        <span class='label'>
            <? echo $this->__f("What can we help you with?"); ?>    
        </span>

        <br/>
        <textarea class="textarea content" id='editor'></textarea>

        <div class="shop_button sendbutton">
            <? echo $this->__f("Send"); ?>
        </div>

        <br/>
        <br/>

    </div>
</div>

<div class='dropleft'>
    <div id="dropzone" action="/file-upload"
      class="dropzone gsdropzone"
      id="my-awesome-dropzone"></div>
</div>

<script>
    gsDropZone = new Dropzone("div#dropzone", { 
        url: "/scripts/ticket_dropzone.php"
    });
    
    gsDropZone.on('sending', function(file, xhr, formData){
        formData.append('uuid', file.upload.uuid);
    });
</script>