<?
/* @var $this \ns_486009b1_3748_4ab6_aa1b_95a4d5e2d228\DefaultPaymentHandlingAction */
$order = $this->getOrder();
$cashpoints = (array)$this->getApi()->getGdsManager()->getDevices();
$canCreditOrder = !$order->isCreditNote && !count($order->creditOrderId);
$roomid = $_SESSION['PmsBookingRoomView_current_pmsroom_id'];
?>
<div class='commonbox'>
    
    <div class='order_action_button' onclick='window.open("/scripts/downloadInvoice.php?orderId=<? echo $order->id; ?>&incrementalOrderId=<? echo $order->incrementOrderId; ?>");'>
        <i class='fa fa-download'></i>
        <? echo $this->__f("Download"); ?>
    </div>
    
    <div class='order_action_button updateOrderNote' orderid='<? echo $order->id; ?>' style='position: relative;' >
        <i class='fa fa-plus-square-o'></i> 
        <? echo $this->__f("Update order note"); ?>
    </div>

    <?
    if (count($cashpoints)) {
        foreach ($cashpoints as $cashpoint) {
            if ($cashpoint->type == "cashap") {
                $orderId = isset($order->id) ? $order->id : $order->orderId;
                ?>
                <div class='order_action_button' gsclick='sendReceipt' deviceid='<? echo $cashpoint->id; ?>' orderid='<? echo $orderId; ?>' title='Print receipt on <? echo $cashpoint->name; ?>'><i class='fa fa-print' ></i> <? echo $cashpoint->name; ?> </div>
                <?
                
            }
        }
    }

    if ($canCreditOrder) {
    ?>

        <div class='order_action_button' gs_confirm="Are you sure?" gs_callback='app.DefaultPaymentHandlingAction.creditCompleted' gsclick='creditOrder' orderid='<? echo $order->id; ?>'>
            <i class='fa fa-history'></i>
            <? echo $this->__f("Credit order"); ?>
        </div>
    <?
    }
    
    if($order->status == 7) {
        $booking = $this->getApi()->getPmsManager()->getBookingFromRoom($this->getSelectedMultilevelDomainName(), $roomid);
        $msg = $this->getApi()->getPmsNotificationManager()->getSpecificMessage($this->getSelectedMultilevelDomainName(), "sendreciept", $booking, null, "email", null);
        $user = $this->getApi()->getUserManager()->getUserById($order->userId);
        ?>
        <div class="sendReceiptWithMessageForm" style="position:absolute; width: 500px; border-radius:4px; background-color:#fff; border: solid 2px #bbb;display:none; right:0px;">
            <input type="txt" gsname="email" class="gsniceinput1" value='<?php echo $user->emailAddress; ?>' style="width:100%; box-sizing: border-box;">
            <input type="txt" gsname="subject" class="gsniceinput1" value='<?php echo $msg->title; ?>' style="width:100%; box-sizing: border-box;">
            <input type="hidden" gsname="bookingid" value="<?php echo $booking->id; ?>">
            <input type="hidden" gsname="orderid" value="<?php echo $order->id; ?>">
            <textarea gsname="message" style="width:100%; height: 200px;"><?php echo $msg->content; ?></textarea>
            <span class='shop_button sendReceiptWithMessage' style="width:100%; box-sizing: border-box;">Send</span>
        </div>
        <div class='order_action_button' onclick="$('.sendReceiptWithMessageForm').slideDown();">
            <? echo $this->__f("Send reciept"); ?>
            <i class='fa fa-arrow-right'></i>
        </div>
        <?
    }
    ?>

</div>