<?
/* @var $this \ns_486009b1_3748_4ab6_aa1b_95a4d5e2d228\DefaultPaymentHandlingAction */
$order = $this->getOrder();
$cashpoints = (array)$this->getApi()->getGdsManager()->getDevices();
$canCreditOrder = !$order->isCreditNote && !count($order->creditOrderId);
$roomid = $_SESSION['PmsBookingRoomView_current_pmsroom_id'];
$amount = $this->getApi()->getOrderManager()->getTotalAmount($order);

$hidePayButton = false;
if($order->payment->paymentType == "ns_6dfcf735_238f_44e1_9086_b2d9bb4fdff2\VerifoneTerminal" || $order->payment->paymentType == "ns_8edb700e_b486_47ac_a05f_c61967a734b1\IntegratedPaymentTerminal") {
     $hidePayButton = true;
}

?>
<div class='commonbox'>
    <?php
        
    if($order->status != 7) {
        ?>
        <div class='commonbox' style="position:absolute; top:70px;">
            <div style='display:inline-block; vertical-align: top;'>
                <? echo $this->__f("Payment date").":"; ?>
                <br/><input class="gsniceinput1 payment_date" style='width: 110px;' gsname='paymentdate' value='<? echo date('d.m.Y H:i'); ?>'/>    
            </div>
        </div>
        <?php
         $text = "Mark as paid";
         if($order->payment->paymentType == "ns_92bd796f_758e_4e03_bece_7d2dbfa40d7a\ExpediaPayment" && $amount > 0) {
             $text = "Bill Expedia";
         }
         if($order->payment->paymentType == "ns_d79569c6_ff6a_4ab5_8820_add42ae71170\BookingComCollectPayments" && $amount > 0) {
             $text = "Bill Booking.com";
         }
    
        if(!$hidePayButton) {
        ?>
            <div class='order_action_button' gs_also='payment_date' orderid='<? echo $order->id; ?>' gsclick='markOrderAsPaid' gs_callback='app.DefaultPaymentHandlingAction.markAsPaidCompleted'><i class='fa fa-check'></i> <? echo $text; ?></div>
        <?php
        }
    }
    ?>
    
    
    <div class='order_action_button' onclick='window.open("/scripts/downloadInvoice.php?orderId=<? echo $order->id; ?>&incrementalOrderId=<? echo $order->incrementOrderId; ?>");'>
        <i class='fa fa-download'></i>
        <? echo $this->__f("Download"); ?>
    </div>
    
    <div class='order_action_button updateOrderNote' orderid='<? echo $order->id; ?>' style='position: relative;' >
        <i class='fa fa-plus-square-o'></i> 
        <? echo $this->__f("Update order note"); ?>
    </div>
    <div class='ordernotesupdatearea'>
        <textarea class='notetextarea'><?php echo @$order->invoiceNote; ?></textarea>
        <span class='shop_button doupdateOrderNote' orderid='<? echo $order->id; ?>'>Update order note</span>
    </div>

    <?
    if (count($cashpoints)) {
        foreach ($cashpoints as $cashpoint) {
            if ($cashpoint->type == "cashap") {
                $orderId = isset($order->id) ? $order->id : $order->orderId;
                ?>
                <div class='order_action_button' gsclick='sendReceipt' deviceid='<? echo $cashpoint->id; ?>' orderid='<? echo $orderId; ?>' title='Print receipt on <? echo $cashpoint->name; ?>'><i class='fa fa-print' ></i> <? echo $cashpoint->name; ?> </div>
                <?
                
            }
        }
    }

    if ($canCreditOrder) {
    ?>

        <div class='order_action_button' gs_confirm="Are you sure?" gs_callback='app.DefaultPaymentHandlingAction.creditCompleted' gsclick='creditOrder' orderid='<? echo $order->id; ?>'>
            <i class='fa fa-history'></i>
            <? echo $this->__f("Credit order"); ?>
        </div>
    <?
    }
    
    if($order->status == 7) {
        $booking = $this->getApi()->getPmsManager()->getBookingFromRoom($this->getSelectedMultilevelDomainName(), $roomid);
        $msg = $this->getApi()->getPmsNotificationManager()->getSpecificMessage($this->getSelectedMultilevelDomainName(), "sendreciept", $booking, null, "email", null);
        $user = $this->getApi()->getUserManager()->getUserById($order->userId);
        ?>
        <div class="sendReceiptWithMessageForm" style="position:absolute; width: 500px; border-radius:4px; background-color:#fff; border: solid 2px #bbb;display:none; right:0px;">
            <input type="txt" gsname="email" class="gsniceinput1" value='<?php echo $user->emailAddress; ?>' style="width:100%; box-sizing: border-box;">
            <input type="txt" gsname="subject" class="gsniceinput1" value='<?php echo $msg->title; ?>' style="width:100%; box-sizing: border-box;">
            <input type="hidden" gsname="bookingid" value="<?php echo $booking->id; ?>">
            <input type="hidden" gsname="orderid" value="<?php echo $order->id; ?>">
            <textarea gsname="message" style="width:100%; height: 200px;"><?php echo $msg->content; ?></textarea>
            <span class='shop_button sendReceiptWithMessage' style="width:100%; box-sizing: border-box;">Send</span>
        </div>
        <div class='order_action_button' onclick="$('.sendReceiptWithMessageForm').slideDown();">
            <? echo $this->__f("Send receipt"); ?>
            <i class='fa fa-arrow-right'></i>
        </div>
        <?
    } else if($order->payment->paymentType == "ns_92bd796f_758e_4e03_bece_7d2dbfa40d7a\ExpediaPayment") {
        echo "<div>";
        echo "* Only mark this order as paid if you are going to invoice expedia for the stay. If it is a virtual card change the payment method to be the same as the one you are using to charge the card.";
        echo "</div>";
    } else if($order->payment->paymentType == "ns_d79569c6_ff6a_4ab5_8820_add42ae71170\BookingComCollectPayments") {
        echo "<div>";
        echo "* Only mark this order as paid if you are going to invoice booking or having a bank transfer from booking.com If it is a virtual card change the payment method to be the same as the one you are using to charge the card.";
        echo "</div>";
    } else if($order->payment->paymentType == "ns_6dfcf735_238f_44e1_9086_b2d9bb4fdff2\VerifoneTerminal" || $order->payment->paymentType == "ns_8edb700e_b486_47ac_a05f_c61967a734b1\IntegratedPaymentTerminal") {
        echo "<div>";
        echo "* Integrated payment terminals are not able to manually mark as paid!";
        echo "</div>";
    }


    
    ?>

</div>