<?
/* @var $this \ns_486009b1_3748_4ab6_aa1b_95a4d5e2d228\DefaultPaymentHandlingAction */
$order = $this->getOrder();
$cashpoints = $this->getApi()->getGdsManager()->getDevices();
$canCreditOrder = !$order->isCreditNote && !count($order->creditOrderId);
?>
<div class='commonbox'>
    
    <div class='order_action_button' onclick='window.open("/scripts/downloadInvoice.php?orderId=<? echo $order->id; ?>&incrementalOrderId=<? echo $order->incrementOrderId; ?>");'>
        <i class='fa fa-download'></i>
        <? echo $this->__f("Download"); ?>
    </div>

    <?
    if (count($cashpoints)) {
        foreach ($cashpoints as $cashpoint) {
            if ($cashpoint->type == "cashap") {
                $orderId = isset($order->id) ? $order->id : $order->orderId;
                ?>
                <div class='order_action_button' gsclick='sendReceipt' deviceid='<? echo $cashpoint->id; ?>' orderid='<? echo $orderId; ?>' title='Print receipt on <? echo $cashpoint->name; ?>'><i class='fa fa-print' ></i> <? echo $cashpoint->name; ?> </div>
                <?
                
            }
        }
    }

    if ($canCreditOrder) {
    ?>

        <div class='order_action_button' gs_confirm="Are you sure?" gs_callback='app.DefaultPaymentHandlingAction.refresh' gsclick='creditOrder' orderid='<? echo $order->id; ?>'>
            <i class='fa fa-history'></i>
            <? echo $this->__f("Credit order"); ?>
        </div>
    <?
    }
    ?>

</div>