<?
/* @var $this \ns_486009b1_3748_4ab6_aa1b_95a4d5e2d228\DefaultPaymentHandlingAction */
$order = $this->getOrder();
$cashpoints = $this->getApi()->getGdsManager()->getDevices();
$canCreditOrder = !$order->isCreditNote && !count($order->creditOrderId);
?>

<div class='commonbox' style='font-size: 17px;'> 
    <i class='fa fa-paperclip' style='display: inline-block; width: 30px; text-align: center;'></i> <? echo $order->incrementOrderId; ?>
    <br/>
    <?
    if (!$order->isCreditNote && count($order->creditOrderId)) {
        ?>
        <i class='fa fa-info-circle' style='display: inline-block; width: 30px; text-align: center;'></i> <? echo $this->__f("This order has been credited"); ?><br/>
        <?
    } 
    
    if ($order->closed) {
    ?>
        <i class='fa fa-lock' style='display: inline-block; width: 30px; text-align: center;'></i> <? echo $this->__f("Closed for modifications"); ?>
    <?
    } else {
    ?>
        <i class='fa fa-unlock' style='display: inline-block; width: 30px; text-align: center;'></i> <? echo $this->__f("Open for modification"); ?>
    <?    
    }
    
    if ($order->status == 7) {
        ?>
        <br/><i class='fa fa-money' style='display: inline-block; width: 30px; text-align: center;'></i> <? echo $this->__f("Order has been paid"); ?>
        <?
    } 

    ?>

</div>