<? namespace ns_dabb8a85_f593_43ec_bf0d_240467118a40; 
$imgApp = $this->getImageDisplayer();
?>
<script src='/js/packery.js'></script>
<?php
/* @var $this News */
if ($this->hasWriteAccess()) {
    ?>
<div class='addnewsrow'>
        <table width='100%'>
            <tr>
                <td width='20%' valign='top'>
                <?php
                    $this->getFactory()->getPage()->renderApplicationSimple($imgApp->configuration->id,$this);
                ?>
                <td>
                <td width='80%' valign='top'>
                    <div class="outeraddnewscontainer">
                        <? echo $this->__f("Subject"); ?><br> <input id="subject" name="subject" type="text" class='gsautosave' value='<? echo $this->getAutoSaved("subject"); ?>'/>
                        <br><br> <? echo $this->__f("Extended description"); ?> 
                        <br>
                        <textarea  name='content' class='gsautosave' 
                                   style="width: 100%; height: 100px; padding: 10px;box-sizing: border-box;" 
                                   placeholder="<? echo $this->__f("Click on me to edit"); ?>"><? echo $this->getAutoSaved("content"); ?></textarea>
                        <div class="gs_button addevent">
                            <? echo $this->__f("Add"); ?>
                        </div>
                    </div>
                <td>
            </tr>
        </table>
</div>
    <?php
} 
echo "<div class='newsboxtemplate_" . $this->getTemplateNumber() . "'>";
$this->includefile("newstemplate".$this->getTemplateNumber());
echo "</div>";
?>
