<?php
$entries = (array)$this->getAllEntries();
$i = 0;
?>
<div class='newscontainerbox'  data-packery-options='{ "columnWidth": ".grid-sizer", "itemSelector": ".news_container", "percentPosition": true, "gutter": 10 }'>
<?php
foreach($entries as $entry) {
    /* @var $entry app_newsmanager_data_NewsEntry */
    $last = (sizeof($entries)-1) == $i ? "last" : "";
    $id = $entry->id;
    echo "<a href='?page=".$entry->pageId."'>";
    echo "<div class='news_container item news_container_$i $last' id='".$id."' style='display:inline-block;'>";
    if($entry->image) {
        echo "<img src='displayImage.php?id=".$entry->image."'>";
    }
    if ($this->hasWriteAccess()) {
        echo "<div class='gs_button small delete'>".$this->__f("Delete")."</div>";
    }
    echo "<div class='news_entry_header'><h2>" . $entry->subject . "</h2></div>";
    echo "<div class='content'>";
    echo $entry->content . "<br>";
    echo "</div>";
    echo "<div class='news_entry_footer'>" . $entry->date ."</div>";
    echo "</div>";
    echo "</a>";
    $i++;
}

?>
<script>
    app.News.needPackery = true;
$(function() {
    $(document).find('img').batchImageLoad({
        loadingCompleteCallback: function() {
            <?php if(!$this->getFactory()->isMobile()) { ?>
                $('.newscontainerbox').packery({ gutter: 10 });
            <?php } ?>
        }
    });
});
</script>