<?php
/* @var $this \ns_dabb8a85_f593_43ec_bf0d_240467118a40\News */
$entries = $this->getAllEntries();
$i = 0;

foreach($entries as $entry) {
    echo "<div class='news_container' id='".$entry->id."'>";
    echo "<span class='date'><span class='dateday'>" . date("d", strtotime($entry->rowCreatedDate)) . "</span><div></div><span class='datemonth'>". $this->__w(date("M", strtotime($entry->rowCreatedDate))) . "</span></span>";
    if($entry->userId) {
        echo "AV";
    }
    if($entry->image) {
        echo "<span style='background-image:url(\"displayImage.php?id=".$entry->image."\")' class='newsimage'></span>";
    } else {
        echo "<span style='background-image:url(\"displayImage.php?id=noimg)' class='newsimage'></span>";
    }
    if ($this->hasWriteAccess()) {
        echo "<div class='gs_button small delete'>".$this->__f("Delete")."</div>";
    }

    echo "<span class='newscontent'>";
    echo "<div class='by'>AV: Admin</div>"; 
    echo "<div class='subject'>" . $entry->subject . "</div>";
    echo "<span class='subjecttextseperator'></span>";
    echo "<div class='newstext'>" . $entry->content . "</div>";
    echo "<a href='?page=".$entry->pageId."'>". $this->__w("Read more") . "</a>";
    echo "</span>";
    echo "</div>";
}
?>