package com.getshop.javaapi;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.LinkedHashMap;
import com.thundashop.core.common.JsonObject2;
public class APICartManager {

      public Transporter transport;

      public APICartManager(Transporter transport){
           this.transport = transport;
      }

     /**
     * Add coupons to the system.
     */
     public void addCoupon(com.thundashop.core.cartmanager.data.Coupon coupon)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("coupon",new Gson().toJson(coupon));
          gs_json_object_data.method = "addCoupon";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Need to attach a reference number manually to the cart?
     * @throws ErrorException
     */
     public void addMetaDataToProduct(java.lang.String cartItemId, java.lang.String metaData)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("cartItemId",new Gson().toJson(cartItemId));
          gs_json_object_data.args.put("metaData",new Gson().toJson(metaData));
          gs_json_object_data.method = "addMetaDataToProduct";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Add a new product to the cart.
     * @param productId The product id generated by the productmanager.
     * @param int Number instances of the product ordered.
     * @return
     * @throws ErrorException
     */
     public com.thundashop.core.cartmanager.data.Cart addProduct(java.lang.String productId, int count, java.util.List variations)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("productId",new Gson().toJson(productId));
          gs_json_object_data.args.put("count",new Gson().toJson(count));
          gs_json_object_data.args.put("variations",new Gson().toJson(variations));
          gs_json_object_data.method = "addProduct";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.cartmanager.data.Cart>() {}.getType();
          com.thundashop.core.cartmanager.data.Cart object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Add a new product to the cart.
     * @param productId The product id generated by the productmanager.
     * @param int Number instances of the product ordered.
     * @return
     * @throws ErrorException
     */
     public com.thundashop.core.cartmanager.data.CartItem addProductItem(java.lang.String productId, int count)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("productId",new Gson().toJson(productId));
          gs_json_object_data.args.put("count",new Gson().toJson(count));
          gs_json_object_data.method = "addProductItem";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.cartmanager.data.CartItem>() {}.getType();
          com.thundashop.core.cartmanager.data.CartItem object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Apply the coupon to the cart.
     */
     public void applyCouponToCurrentCart(java.lang.String code)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("code",new Gson().toJson(code));
          gs_json_object_data.method = "applyCouponToCurrentCart";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Send in a cart and you shall have the total price for all products.
     */
     public java.lang.Double calculateTotalCost(com.thundashop.core.cartmanager.data.Cart cart)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("cart",new Gson().toJson(cart));
          gs_json_object_data.method = "calculateTotalCost";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.lang.Double>() {}.getType();
          java.lang.Double object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Clear the current shopping cart.
     */
     public void clear()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "clear";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Fetch the current cart.
     * @return
     * @throws ErrorException
     */
     public com.thundashop.core.cartmanager.data.Cart getCart()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getCart";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.cartmanager.data.Cart>() {}.getType();
          com.thundashop.core.cartmanager.data.Cart object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the current total amount
     * note, this does not include shipping.
     *
     * @return
     * @throws ErrorException
     */
     public java.lang.Double getCartTotalAmount()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getCartTotalAmount";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.lang.Double>() {}.getType();
          java.lang.Double object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns a list of all coupons.
     * @return
     */
     public java.util.List getCoupons()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getCoupons";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.cartmanager.data.Coupon>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the shipping cost
     * @return
     */
     public java.lang.Double getShippingCost()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getShippingCost";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.lang.Double>() {}.getType();
          java.lang.Double object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch the total amount of price to use when calculating shipping price.
     * @return
     * @throws ErrorException
     */
     public java.lang.Double getShippingPriceBasis()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getShippingPriceBasis";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.lang.Double>() {}.getType();
          java.lang.Double object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the current calculation of taxes.
     * @return
     */
     public java.util.List getTaxes()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getTaxes";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.cartmanager.data.CartTax>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Remove all coupons from the system.
     * @throws ErrorException
     */
     public void removeAllCoupons()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "removeAllCoupons";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Remove a coupon from the system.
     *
     * @param coupon
     * @throws ErrorException
     */
     public void removeCoupon(java.lang.String code)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("code",new Gson().toJson(code));
          gs_json_object_data.method = "removeCoupon";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Remove an added product from the cart.
     * @param productId The product id generated by the productmanager, that has been added to the cart.
     * @return
     * @throws ErrorException
     */
     public com.thundashop.core.cartmanager.data.Cart removeProduct(java.lang.String cartItemId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("cartItemId",new Gson().toJson(cartItemId));
          gs_json_object_data.method = "removeProduct";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.cartmanager.data.Cart>() {}.getType();
          com.thundashop.core.cartmanager.data.Cart object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Set a new address to the current cart.
     */
     public void setAddress(com.thundashop.core.usermanager.data.Address address)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("address",new Gson().toJson(address));
          gs_json_object_data.method = "setAddress";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Need to attach a reference number manually to the cart?
     * @throws ErrorException
     */
     public void setReference(java.lang.String reference)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("reference",new Gson().toJson(reference));
          gs_json_object_data.method = "setReference";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Sets the shipping cost.
     * Should be in base currency.
     */
     public void setShippingCost(double shippingCost)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("shippingCost",new Gson().toJson(shippingCost));
          gs_json_object_data.method = "setShippingCost";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Change the number of instances added to the product.
     * @param productId The product id generated by the productmanager.
     * @param count The number of instances (has to be a positive integer)
     * @return
     * @throws ErrorException
     */
     public com.thundashop.core.cartmanager.data.Cart updateProductCount(java.lang.String cartItemId, int count)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("cartItemId",new Gson().toJson(cartItemId));
          gs_json_object_data.args.put("count",new Gson().toJson(count));
          gs_json_object_data.method = "updateProductCount";
          gs_json_object_data.interfaceName = "core.cartmanager.ICartManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.cartmanager.data.Cart>() {}.getType();
          com.thundashop.core.cartmanager.data.Cart object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

}
