package com.getshop.javaapi;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.LinkedHashMap;
import com.thundashop.core.common.JsonObject2;
public class APIContentManager {

      public Transporter transport;

      public APIContentManager(Transporter transport){
           this.transport = transport;
      }

     /**
     * Create a new instance for the content manager.<br>
     * An id will automatically be generated and returned on creation.<br>
     *
     * @param content The content to build upon.
     * @return The id for the new content.
     * @throws ErrorException
     */
     public java.lang.String createContent(java.lang.String content)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("content",new Gson().toJson(content));
          data.method = "createContent";
          data.interfaceName = "app.content.IContentManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.lang.String>() {}.getType();
          java.lang.String object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Remove the content for a given id.
     * @param id The id to remove the content for.
     * @throws ErrorException
     */
     public void deleteContent(java.lang.String id)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("id",new Gson().toJson(id));
          data.method = "deleteContent";
          data.interfaceName = "app.content.IContentManager";
          String result = transport.send(data);
     }

     /**
     * Fetch all content saved until now.
     * @return A list of all content accosiated with its given id.
     * @throws ErrorException
     */
     public java.util.HashMap getAllContent()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.method = "getAllContent";
          data.interfaceName = "app.content.IContentManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.HashMap<java.lang.String,java.lang.String>>() {}.getType();
          java.util.HashMap object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch the content for a given id.
     * @param id The id which is identifying the content.
     * @return
     * @throws ErrorException
     */
     public java.lang.String getContent(java.lang.String id)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("id",new Gson().toJson(id));
          data.method = "getContent";
          data.interfaceName = "app.content.IContentManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.lang.String>() {}.getType();
          java.lang.String object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Update / replace the content for a given id.
     * @param id The id to update the content for.
     * @param content The content to update. This could be html / text.
     * @throws ErrorException
     */
     public void saveContent(java.lang.String id, java.lang.String content)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("id",new Gson().toJson(id));
          data.args.put("content",new Gson().toJson(content));
          data.method = "saveContent";
          data.interfaceName = "app.content.IContentManager";
          String result = transport.send(data);
     }

}
