package com.getshop.javaapi;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.LinkedHashMap;
import com.thundashop.core.common.JsonObject2;
public class APIChatManager {

      public Transporter transport;

      public APIChatManager(Transporter transport){
           this.transport = transport;
      }

     /**
     * Reply to a chat message.
     *
     * @param id - Chatters id
     * @param message
     */
     public void closeChat(java.lang.String id)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("id",new Gson().toJson(id));
          data.method = "closeChat";
          data.interfaceName = "core.chat.IChatManager";
          String result = transport.send(data);
     }

     /**
     * Returns a list of available poeple to chat with.
     * @return
     */
     public java.util.List getChatters()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.method = "getChatters";
          data.interfaceName = "core.chat.IChatManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.chatmanager.Chatter>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Get all your chat messages
     *
     * @return
     */
     public java.util.List getMessages()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.method = "getMessages";
          data.interfaceName = "core.chat.IChatManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.chatmanager.ChatMessage>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Notify the manager that someone is online, this will effectivly stop the notification to continue.
     *
     * No need to notify everyone if the chat is handeled properly anyway.
     * @throws ErrorException
     */
     public void pingMobileChat(java.lang.String chatterid)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("chatterid",new Gson().toJson(chatterid));
          data.method = "pingMobileChat";
          data.interfaceName = "core.chat.IChatManager";
          String result = transport.send(data);
     }

     /**
     * Reply to a chat message.
     *
     * @param id - Chatters id
     * @param message
     */
     public void replyToChat(java.lang.String id, java.lang.String message)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("id",new Gson().toJson(id));
          data.args.put("message",new Gson().toJson(message));
          data.method = "replyToChat";
          data.interfaceName = "core.chat.IChatManager";
          String result = transport.send(data);
     }

     /**
     * Send a message to administrator
     *
     * @param message
     * @throws ErrorException
     */
     public void sendMessage(java.lang.String message)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("message",new Gson().toJson(message));
          data.method = "sendMessage";
          data.interfaceName = "core.chat.IChatManager";
          String result = transport.send(data);
     }

}
