package com.getshop.javaapi;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.LinkedHashMap;
import com.thundashop.core.common.JsonObject2;
public class APIFooterManager {

      public Transporter transport;

      public APIFooterManager(Transporter transport){
           this.transport = transport;
      }

     /**
     * Get the current configuration.
     * @return
     * @throws ErrorException
     */
     public com.thundashop.app.footermanager.data.Configuration getConfiguration()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.method = "getConfiguration";
          data.interfaceName = "app.footer.IFooterManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.app.footermanager.data.Configuration>() {}.getType();
          com.thundashop.app.footermanager.data.Configuration object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Change the layout for the columns.<br>
     * Defaults to 1 if nothing else is set.<br>
     * @param numberOfColumns The number of columns you want to display.
     * @throws ErrorException
     */
     public com.thundashop.app.footermanager.data.Configuration setLayout(java.lang.Integer numberOfColumns)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("numberOfColumns",new Gson().toJson(numberOfColumns));
          data.method = "setLayout";
          data.interfaceName = "app.footer.IFooterManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.app.footermanager.data.Configuration>() {}.getType();
          com.thundashop.app.footermanager.data.Configuration object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Change the type of a given column.
     * @param column The column it regards
     * @param type The type,0 for text, 1 for list.
     * @return
     * @throws ErrorException
     */
     public com.thundashop.app.footermanager.data.Configuration setType(java.lang.Integer column, java.lang.Integer type)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("column",new Gson().toJson(column));
          data.args.put("type",new Gson().toJson(type));
          data.method = "setType";
          data.interfaceName = "app.footer.IFooterManager";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.app.footermanager.data.Configuration>() {}.getType();
          com.thundashop.app.footermanager.data.Configuration object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

}
