package com.getshop.javaapi;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.LinkedHashMap;
import com.thundashop.core.common.JsonObject2;
public class APIGetShopApplicationPool {

      public Transporter transport;

      public APIGetShopApplicationPool(Transporter transport){
           this.transport = transport;
      }

     /**
     * Save an application
     *
     * @param application
     */
     public void deleteApplication(java.lang.String applicationId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("applicationId",new Gson().toJson(applicationId));
          gs_json_object_data.method = "deleteApplication";
          gs_json_object_data.interfaceName = "core.applications.IGetShopApplicationPool";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Get an application by an given id.
     *
     * @param applicationId
     * @return
     */
     public com.thundashop.core.appmanager.data.Application get(java.lang.String applicationId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("applicationId",new Gson().toJson(applicationId));
          gs_json_object_data.method = "get";
          gs_json_object_data.interfaceName = "core.applications.IGetShopApplicationPool";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.appmanager.data.Application>() {}.getType();
          com.thundashop.core.appmanager.data.Application object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns a list of all available applications.
     *
     * @return
     */
     public java.util.List getApplications()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getApplications";
          gs_json_object_data.interfaceName = "core.applications.IGetShopApplicationPool";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.appmanager.data.Application>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Save an application
     *
     * @param application
     */
     public void saveApplication(com.thundashop.core.appmanager.data.Application application)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("application",new Gson().toJson(application));
          gs_json_object_data.method = "saveApplication";
          gs_json_object_data.interfaceName = "core.applications.IGetShopApplicationPool";
          String result = transport.send(gs_json_object_data);
     }

}
