package com.getshop.javaapi;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.LinkedHashMap;
import com.thundashop.core.common.JsonObject2;
public class APIInformationScreenManager {

      public Transporter transport;

      public APIInformationScreenManager(Transporter transport){
           this.transport = transport;
      }

     /**
     *
     * @author ktonder
     */
     public void addSlider(com.thundashop.core.informationscreen.Slider slider, java.lang.String tvId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("slider",new Gson().toJson(slider));
          gs_json_object_data.args.put("tvId",new Gson().toJson(tvId));
          gs_json_object_data.method = "addSlider";
          gs_json_object_data.interfaceName = "core.informationscreenmanager.IInformationScreenManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     *
     * @author ktonder
     */
     public void deleteSlider(java.lang.String sliderId, java.lang.String tvId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("sliderId",new Gson().toJson(sliderId));
          gs_json_object_data.args.put("tvId",new Gson().toJson(tvId));
          gs_json_object_data.method = "deleteSlider";
          gs_json_object_data.interfaceName = "core.informationscreenmanager.IInformationScreenManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     *
     * @author ktonder
     */
     public java.util.List getHolders()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getHolders";
          gs_json_object_data.interfaceName = "core.informationscreenmanager.IInformationScreenManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.informationscreen.CustomerInfoScreenHolder>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     *
     * @author ktonder
     */
     public java.util.List getInformationScreens()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getInformationScreens";
          gs_json_object_data.interfaceName = "core.informationscreenmanager.IInformationScreenManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.informationscreen.InfoScreen>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     *
     * @author ktonder
     */
     public com.thundashop.core.informationscreen.InfoScreen getScreen(java.lang.String id)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("id",new Gson().toJson(id));
          gs_json_object_data.method = "getScreen";
          gs_json_object_data.interfaceName = "core.informationscreenmanager.IInformationScreenManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.informationscreen.InfoScreen>() {}.getType();
          com.thundashop.core.informationscreen.InfoScreen object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     *
     * @author ktonder
     */
     public java.util.List getTypes()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getTypes";
          gs_json_object_data.interfaceName = "core.informationscreenmanager.IInformationScreenManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.informationscreen.SliderType>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     *
     * @author ktonder
     */
     public void registerTv(java.lang.String customerId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("customerId",new Gson().toJson(customerId));
          gs_json_object_data.method = "registerTv";
          gs_json_object_data.interfaceName = "core.informationscreenmanager.IInformationScreenManager";
          String result = transport.send(gs_json_object_data);
     }

}
