package com.getshop.javaapi;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.LinkedHashMap;
import com.thundashop.core.common.JsonObject2;
public class APIMecaApi {

      public Transporter transport;

      public APIMecaApi(Transporter transport){
           this.transport = transport;
      }

     /**
     *
     * @author emil
     */
     public com.thundashop.core.meca.data.RPCResult addVehicle(java.lang.String phoneNumber, com.thundashop.core.meca.data.Vehicle vehicle)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("phoneNumber",new Gson().toJson(phoneNumber));
          gs_json_object_data.args.put("vehicle",new Gson().toJson(vehicle));
          gs_json_object_data.method = "addVehicle";
          gs_json_object_data.interfaceName = "core.mecamanager.IMecaApi";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.meca.data.RPCResult>() {}.getType();
          com.thundashop.core.meca.data.RPCResult object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     *
     * @author emil
     */
     public com.thundashop.core.meca.data.RPCResult changePassword(java.lang.String phoneNumber, java.lang.String oldPassword, java.lang.String newPassword1, java.lang.String newPassword2)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("phoneNumber",new Gson().toJson(phoneNumber));
          gs_json_object_data.args.put("oldPassword",new Gson().toJson(oldPassword));
          gs_json_object_data.args.put("newPassword1",new Gson().toJson(newPassword1));
          gs_json_object_data.args.put("newPassword2",new Gson().toJson(newPassword2));
          gs_json_object_data.method = "changePassword";
          gs_json_object_data.interfaceName = "core.mecamanager.IMecaApi";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.meca.data.RPCResult>() {}.getType();
          com.thundashop.core.meca.data.RPCResult object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     *
     * @author emil
     */
     public com.thundashop.core.meca.data.RPCResult createAccount(java.lang.String phoneNumber)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("phoneNumber",new Gson().toJson(phoneNumber));
          gs_json_object_data.method = "createAccount";
          gs_json_object_data.interfaceName = "core.mecamanager.IMecaApi";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.meca.data.RPCResult>() {}.getType();
          com.thundashop.core.meca.data.RPCResult object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     *
     * @author emil
     */
     public com.thundashop.core.meca.data.RPCResult login(java.lang.String phoneNumber, java.lang.String password)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("phoneNumber",new Gson().toJson(phoneNumber));
          gs_json_object_data.args.put("password",new Gson().toJson(password));
          gs_json_object_data.method = "login";
          gs_json_object_data.interfaceName = "core.mecamanager.IMecaApi";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.meca.data.RPCResult>() {}.getType();
          com.thundashop.core.meca.data.RPCResult object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

}
