package com.getshop.javaapi;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.LinkedHashMap;
import com.thundashop.core.common.JsonObject2;
public class APIOrderManager {

      public Transporter transport;

      public APIOrderManager(Transporter transport){
           this.transport = transport;
      }

     /**
     * Change order status of a specified order.
     * The id could be the orderId or the transaction id.
     */
     public void changeOrderStatus(java.lang.String id, int status)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("id",new Gson().toJson(id));
          gs_json_object_data.args.put("status",new Gson().toJson(status));
          gs_json_object_data.method = "changeOrderStatus";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Returns the total amount of sales for a given year. If you year is left blank you
     * will get the total amount for all years.
     *
     * @param year
     * @return
     */
     public void changeOrderType(java.lang.String orderId, java.lang.String paymentTypeId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("orderId",new Gson().toJson(orderId));
          gs_json_object_data.args.put("paymentTypeId",new Gson().toJson(paymentTypeId));
          gs_json_object_data.method = "changeOrderType";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Create an order out of a given cart.
     * @param cart The cart object generated by cartmanager.
     * @return
     * @throws ErrorException
     */
     public com.thundashop.core.ordermanager.data.Order createOrder(com.thundashop.core.usermanager.data.Address address)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("address",new Gson().toJson(address));
          gs_json_object_data.method = "createOrder";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.ordermanager.data.Order>() {}.getType();
          com.thundashop.core.ordermanager.data.Order object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * If a customer is providing a customer reference id, it should be possible to create order by it.
     * @param cart The cart object generated by cartmanager.
     * @return
     * @throws ErrorException
     */
     public com.thundashop.core.ordermanager.data.Order createOrderByCustomerReference(java.lang.String referenceKey)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("referenceKey",new Gson().toJson(referenceKey));
          gs_json_object_data.method = "createOrderByCustomerReference";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.ordermanager.data.Order>() {}.getType();
          com.thundashop.core.ordermanager.data.Order object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * This will create a order for a given userId.
     * To avoid fraud, shipment address and etc will only be
     * able to set to the already registered user in the database.
     *
     * @param userId
     */
     public com.thundashop.core.ordermanager.data.Order createOrderForUser(java.lang.String userId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("userId",new Gson().toJson(userId));
          gs_json_object_data.method = "createOrderForUser";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.ordermanager.data.Order>() {}.getType();
          com.thundashop.core.ordermanager.data.Order object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch all orders for a user.
     * @param userId
     * @return
     * @throws ErrorException
     */
     public java.util.List getAllOrdersForUser(java.lang.String userId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("userId",new Gson().toJson(userId));
          gs_json_object_data.method = "getAllOrdersForUser";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.ordermanager.data.Order>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch all orders on product.
     * @param userId
     * @return
     * @throws ErrorException
     */
     public java.util.List getAllOrdersOnProduct(java.lang.String productId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("productId",new Gson().toJson(productId));
          gs_json_object_data.method = "getAllOrdersOnProduct";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.ordermanager.data.Order>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the total amount of sales for a given year. If you year is left blank you
     * will get the total amount for all years.
     *
     * @param year
     * @return
     */
     public java.util.Map getMostSoldProducts(int numberOfProducts)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("numberOfProducts",new Gson().toJson(numberOfProducts));
          gs_json_object_data.method = "getMostSoldProducts";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.Map<java.lang.String,java.util.List<com.thundashop.core.ordermanager.data.Statistic>>>() {}.getType();
          java.util.Map object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch a single order based on its id.
     * @param orderId
     * @return
     * @throws ErrorException
     */
     public com.thundashop.core.ordermanager.data.Order getOrder(java.lang.String orderId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("orderId",new Gson().toJson(orderId));
          gs_json_object_data.method = "getOrder";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.ordermanager.data.Order>() {}.getType();
          com.thundashop.core.ordermanager.data.Order object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Got a reference number for the order, fetch it from here.
     * @param referenceId
     * @throws ErrorException
     */
     public com.thundashop.core.ordermanager.data.Order getOrderByReference(java.lang.String referenceId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("referenceId",new Gson().toJson(referenceId));
          gs_json_object_data.method = "getOrderByReference";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.ordermanager.data.Order>() {}.getType();
          com.thundashop.core.ordermanager.data.Order object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * @param id
     * @return
     * @throws ErrorException
     */
     public com.thundashop.core.ordermanager.data.Order getOrderByincrementOrderId(java.lang.Integer id)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("id",new Gson().toJson(id));
          gs_json_object_data.method = "getOrderByincrementOrderId";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.ordermanager.data.Order>() {}.getType();
          com.thundashop.core.ordermanager.data.Order object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch a single order based on its id.
     * @param orderId
     * @return
     * @throws ErrorException
     */
     public com.thundashop.core.ordermanager.data.Order getOrderSecure(java.lang.String orderId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("orderId",new Gson().toJson(orderId));
          gs_json_object_data.method = "getOrderSecure";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.ordermanager.data.Order>() {}.getType();
          com.thundashop.core.ordermanager.data.Order object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Get a list of already created orders.
     * @param orderIds A list of all orders you want to fetch, all orders are retrieved if this list is empty.
     * @param page What page are you fetching (default 0)
     * @param pageSize Number of entries for each page (default 10)
     * @return
     * @throws ErrorException
     */
     public java.util.List getOrders(java.util.ArrayList orderIds, java.lang.Integer page, java.lang.Integer pageSize)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("orderIds",new Gson().toJson(orderIds));
          gs_json_object_data.args.put("page",new Gson().toJson(page));
          gs_json_object_data.args.put("pageSize",new Gson().toJson(pageSize));
          gs_json_object_data.method = "getOrders";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.ordermanager.data.Order>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Fetch a single order based on its id.
     * @param orderId
     * @return
     * @throws ErrorException
     */
     public java.util.List getOrdersFromPeriode(long start, long end, boolean statistics)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("start",new Gson().toJson(start));
          gs_json_object_data.args.put("end",new Gson().toJson(end));
          gs_json_object_data.args.put("statistics",new Gson().toJson(statistics));
          gs_json_object_data.method = "getOrdersFromPeriode";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.ordermanager.data.Order>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the total amount of sales for a given year. If you year is left blank you
     * will get the total amount for all years.
     *
     * @param year
     * @return
     */
     public java.util.List getOrdersNotTransferredToAccountingSystem()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getOrdersNotTransferredToAccountingSystem";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.ordermanager.data.Order>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the total amount of sales for a given year. If you year is left blank you
     * will get the total amount for all years.
     *
     * @param year
     * @return
     */
     public java.util.List getOrdersToCapture()  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.method = "getOrdersToCapture";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.ordermanager.data.Order>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns how many pages there is for this store with the given pagesize
     * @return
     */
     public int getPageCount(int pageSize, java.lang.String searchWord)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("pageSize",new Gson().toJson(pageSize));
          gs_json_object_data.args.put("searchWord",new Gson().toJson(searchWord));
          gs_json_object_data.method = "getPageCount";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<Integer>() {}.getType();
          Integer object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the total amount of sales for a given year. If you year is left blank you
     * will get the total amount for all years.
     *
     * @param year
     * @return
     */
     public java.util.List getSalesNumber(int year)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("year",new Gson().toJson(year));
          gs_json_object_data.method = "getSalesNumber";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.ordermanager.data.Statistic>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the total amount of sales for a given year. If you year is left blank you
     * will get the total amount for all years.
     *
     * @param year
     * @return
     */
     public java.util.HashMap getSalesStatistics(java.lang.Long startDate, java.lang.Long endDate, java.lang.String type)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("startDate",new Gson().toJson(startDate));
          gs_json_object_data.args.put("endDate",new Gson().toJson(endDate));
          gs_json_object_data.args.put("type",new Gson().toJson(type));
          gs_json_object_data.method = "getSalesStatistics";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.HashMap<java.lang.Long,com.thundashop.core.ordermanager.data.SalesStats>>() {}.getType();
          java.util.HashMap object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns a list over taxes
     * for the specified order.
     *
     * @param order
     * @return
     * @throws ErrorException
     */
     public java.util.List getTaxes(com.thundashop.core.ordermanager.data.Order order)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("order",new Gson().toJson(order));
          gs_json_object_data.method = "getTaxes";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.cartmanager.data.CartTax>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Calculate the total amount to pay for the order.
     *
     * @param order
     * @return
     */
     public java.lang.Double getTotalAmount(com.thundashop.core.ordermanager.data.Order order)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("order",new Gson().toJson(order));
          gs_json_object_data.method = "getTotalAmount";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.lang.Double>() {}.getType();
          java.lang.Double object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the total amount of sales for a given year. If you year is left blank you
     * will get the total amount for all years.
     *
     * @param year
     * @return
     */
     public java.lang.Double getTotalForOrderById(java.lang.String orderId)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("orderId",new Gson().toJson(orderId));
          gs_json_object_data.method = "getTotalForOrderById";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.lang.Double>() {}.getType();
          java.lang.Double object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the total amount of sales for a given year. If you year is left blank you
     * will get the total amount for all years.
     *
     * @param year
     * @return
     */
     public java.lang.Double getTotalSalesAmount(java.lang.Integer year, java.lang.Integer month, java.lang.Integer week, java.lang.Integer day, java.lang.String type)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("year",new Gson().toJson(year));
          gs_json_object_data.args.put("month",new Gson().toJson(month));
          gs_json_object_data.args.put("week",new Gson().toJson(week));
          gs_json_object_data.args.put("day",new Gson().toJson(day));
          gs_json_object_data.args.put("type",new Gson().toJson(type));
          gs_json_object_data.method = "getTotalSalesAmount";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.lang.Double>() {}.getType();
          java.lang.Double object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns the total amount of sales for a given year. If you year is left blank you
     * will get the total amount for all years.
     *
     * @param year
     * @return
     */
     public void logTransactionEntry(java.lang.String orderId, java.lang.String entry)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("orderId",new Gson().toJson(orderId));
          gs_json_object_data.args.put("entry",new Gson().toJson(entry));
          gs_json_object_data.method = "logTransactionEntry";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Update or modify an existing order.
     * @param order The order to modify
     * @return
     * @throws ErrorException
     */
     public void saveOrder(com.thundashop.core.ordermanager.data.Order order)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("order",new Gson().toJson(order));
          gs_json_object_data.method = "saveOrder";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Returns how many pages there is for this store with the given pagesize
     * @return
     */
     public java.util.List searchForOrders(java.lang.String searchWord, java.lang.Integer page, java.lang.Integer pageSize)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("searchWord",new Gson().toJson(searchWord));
          gs_json_object_data.args.put("page",new Gson().toJson(page));
          gs_json_object_data.args.put("pageSize",new Gson().toJson(pageSize));
          gs_json_object_data.method = "searchForOrders";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.ordermanager.data.Order>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * If everything is ok, the price is the same as the order and the currency, then update the status.
     * @param password A predefined password needed to update the status.
     * @param orderId The id of the order to update
     * @param currency The currency the transaction returned
     * @param price The price.
     * @throws ErrorException
     */
     public void setOrderStatus(java.lang.String password, java.lang.String orderId, java.lang.String currency, double price, int status)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("password",new Gson().toJson(password));
          gs_json_object_data.args.put("orderId",new Gson().toJson(orderId));
          gs_json_object_data.args.put("currency",new Gson().toJson(currency));
          gs_json_object_data.args.put("price",new Gson().toJson(price));
          gs_json_object_data.args.put("status",new Gson().toJson(status));
          gs_json_object_data.method = "setOrderStatus";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
     }

     /**
     * Returns the total amount of sales for a given year. If you year is left blank you
     * will get the total amount for all years.
     *
     * @param year
     * @return
     */
     public void updatePriceForOrderLine(java.lang.String cartItemId, java.lang.String orderId, double price)  throws Exception  {
          JsonObject2 gs_json_object_data = new JsonObject2();
          gs_json_object_data.args = new LinkedHashMap();
          gs_json_object_data.args.put("cartItemId",new Gson().toJson(cartItemId));
          gs_json_object_data.args.put("orderId",new Gson().toJson(orderId));
          gs_json_object_data.args.put("price",new Gson().toJson(price));
          gs_json_object_data.method = "updatePriceForOrderLine";
          gs_json_object_data.interfaceName = "core.ordermanager.IOrderManager";
          String result = transport.send(gs_json_object_data);
     }

}
