package com.getshop.javaapi;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.LinkedHashMap;
import com.thundashop.core.common.JsonObject2;
public class APIStoreApplicationPool {

      public Transporter transport;

      public APIStoreApplicationPool(Transporter transport){
           this.transport = transport;
      }

     /**
     * Activate an application.
     *
     * @param applicationId
     */
     public void activateApplication(java.lang.String applicationId)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("applicationId",new Gson().toJson(applicationId));
          data.method = "activateApplication";
          data.interfaceName = "core.applications.IStoreApplicationPool";
          String result = transport.send(data);
     }

     /**
     * Return an activated application by the given Id.
     *
     * @param id
     * @return
     */
     public com.thundashop.core.appmanager.data.Application getApplication(java.lang.String id)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("id",new Gson().toJson(id));
          data.method = "getApplication";
          data.interfaceName = "core.applications.IStoreApplicationPool";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.appmanager.data.Application>() {}.getType();
          com.thundashop.core.appmanager.data.Application object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns a list of all applications this store
     * has activated.
     *
     * @return
     */
     public java.util.List getApplications()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.method = "getApplications";
          data.interfaceName = "core.applications.IStoreApplicationPool";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.appmanager.data.Application>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns a list of all applications that are available
     * for this store. This also includes applications that has
     * not yet been activated by the administrator.
     *
     * @return
     */
     public java.util.List getAvailableApplications()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.method = "getAvailableApplications";
          data.interfaceName = "core.applications.IStoreApplicationPool";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.appmanager.data.Application>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * This is a filtered list of the getAvailableApplications function.
     *
     * @return
     */
     public java.util.List getAvailableApplicationsThatIsNotActivated()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.method = "getAvailableApplicationsThatIsNotActivated";
          data.interfaceName = "core.applications.IStoreApplicationPool";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.appmanager.data.Application>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Returns a list of all available theme applications.
     *
     * @return
     */
     public java.util.List getAvailableThemeApplications()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.method = "getAvailableThemeApplications";
          data.interfaceName = "core.applications.IStoreApplicationPool";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<java.util.List<com.thundashop.core.appmanager.data.Application>>() {}.getType();
          java.util.List object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Return the themeapplication that is currently set.
     *
     * @return
     */
     public com.thundashop.core.appmanager.data.Application getThemeApplication()  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.method = "getThemeApplication";
          data.interfaceName = "core.applications.IStoreApplicationPool";
          String result = transport.send(data);
          Gson gson = new GsonBuilder().serializeNulls().create();
          Type typeJson_3323322222_autogenerated = new TypeToken<com.thundashop.core.appmanager.data.Application>() {}.getType();
          com.thundashop.core.appmanager.data.Application object = gson.fromJson(result, typeJson_3323322222_autogenerated);
          return object;
     }

     /**
     * Use this function to change or set the
     * theme application you wish to use.
     * @param applicationId
     */
     public void setThemeApplication(java.lang.String applicationId)  throws Exception  {
          JsonObject2 data = new JsonObject2();
          data.args = new LinkedHashMap();
          data.args.put("applicationId",new Gson().toJson(applicationId));
          data.method = "setThemeApplication";
          data.interfaceName = "core.applications.IStoreApplicationPool";
          String result = transport.send(data);
     }

}
