<?php
 /* @var $this \ns_7b68e527_b6fe_4d56_8628_0f981e0b87eb\UsersRow */
?>
<div class='menuentry <?php if($this->getSelectedArea() == "userinfo") { echo "selectedmenuentry"; } ?>' area='userinfo'>User information</div>
<div class='menuentry <?php if($this->getSelectedArea() == "password") { echo "selectedmenuentry"; } ?>' area='password'>Password</div>
<div class='menuentry <?php if($this->getSelectedArea() == "orders") { echo "selectedmenuentry"; } ?>' area='orders'>Payments</div>
<div class='menuentry <?php if($this->getSelectedArea() == "company") { echo "selectedmenuentry"; } ?>' area='company'>Company</div>
<div class='menuentry <?php if($this->getSelectedArea() == "bookings") { echo "selectedmenuentry"; } ?>' area='bookings'>Bookings</div>
<div class='menuentry <?php if($this->getSelectedArea() == "discounts") { echo "selectedmenuentry"; } ?>' area='discounts'>Discounts</div>
<div class='menuentry <?php if($this->getSelectedArea() == "savedcards") { echo "selectedmenuentry"; } ?>' area='savedcards'>Saved cards</div>
<div class='menuentry <?php if($this->getSelectedArea() == "modules") { echo "selectedmenuentry"; } ?>' area='modules'>Modules</div>
<div class='menuentry <?php if($this->getSelectedArea() == "getshopexpress") { echo "selectedmenuentry"; } ?>' area='getshopexpress'>GetShop.express</div>
<div class='menuentry <?php if($this->getSelectedArea() == "log") { echo "selectedmenuentry"; } ?>' area='log'>Log</div>
<div class='menuentry <?php if($this->getSelectedArea() == "settings") { echo "selectedmenuentry"; } ?>' area='settings'>Settings</div>
<div class='menuentry <?php if($this->getSelectedArea() == "accounting") { echo "selectedmenuentry"; } ?>' area='accounting'>Accounting</div>