<div gstype='form' method='updateUsersRight'>
    <?php
    $modules = $this->getAccessModules();
    echo "<div class='header'>Restrictions</div>";
    $user = $this->getUser();
    foreach($modules as $module) {
        echo "<div style='clear:both;'>";
        $checked = "";
        if(in_array($module->id, $user->hasAccessToModules)) {
            $checked = "CHECKED";
        }
        echo $module->name;
        echo "<input class='checkbox' style='float:right;' type='checkbox' gsname='".$module->id."' $checked>";
        echo "</div>";
    }
    ?>
    <div class='footer'>
        <span class='shop_button' gstype='submit'>Update access rights</span>
    </div>
</div>