<?
/* @var $this ns_2059b00f_8bcb_466d_89df_3de79acdf3a1\PmsCalendar */
$items = $this->getApi()->getBookingEngine()->getBookingItems($this->getSelectedName());
$types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedName());

$config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedName());
if(!$config->exposeUnsecureBookings && $this->isEditorMode()) {
    echo "Warning: Bookings not showing inside of calendar, due to not configured to expose data when not administrator";
}
unset($_SESSION['calendarselectedday']);

$filter = new core_pmsmanager_PmsBookingFilter();
$filter->needToBeConfirmed = true;
$filter->startDate = $this->convertToJavaDate(strtotime("01.01.2000"));
$filter->endDate = $this->convertToJavaDate(strtotime("01.01.2200"));

$bookings = $this->getApi()->getPmsManager()->getAllBookingsUnsecure($this->getSelectedName(), $filter);


$pageId = $this->getPage()->javapage->id;

$headingText = $this->getConfigurationSetting("headingroomoverview");
if(!$headingText) {
    $headingText = "SELECT A ROOM";
}
echo "<div class='roombookingpanel'>";
echo "<h1>".$headingText."</h1>";
foreach($types as $type) {
    if(!$type->visibleForBooking) {
        continue;
    }
    
    foreach($items as $item) {
        $counter = 0;
        if($bookings) {
            foreach($bookings as $booking) {
                foreach($booking->rooms as $room) {
                    if($room->bookingItemId == $item->id) {
                        $counter++;
                    }
                }
            }
        }
        
        if($item->bookingItemTypeId != $type->id) {
            continue;
        }
        echo "<span class='roomentry'>";
        echo "<a href='?roomName=".$item->bookingItemName."&page=$pageId'>";
        echo "<span class='roomentryinner'>";
        echo $item->bookingItemName;
        echo "<span class='nobookings'>$counter bookinger<br>";
        echo "</span>";
        echo "</span>";
        echo "</a>";
        echo "<a class='description' href='?page=".$item->id."'>Beskrivelse</a>";
        echo "</span>";
    }
}
echo "</div>";
?>

