<?php
/* @var $this \ns_2059b00f_8bcb_466d_89df_3de79acdf3a1\PmsCalendar */

$bookings = $this->getConfirmedBookingsForDay();
$selectedRoom = false;
if(isset($_GET['roomName']) && $_GET['roomName']) {
    $selectedRoom = $this->getRoomFromName($_GET['roomName']);
}
?>

<div class='daycalendar'>
    <?php
    $iteration = 60;
    $time = strtotime($_GET['day']. " 07:00");
    for($i = 0; $i < 11; $i++) {
        $next = $time + ($iteration*60);
        $freeClass = "free";
        $taken = "";
        if($selectedRoom) {
            $taken = $this->isBookedAtSlot($time, $bookings, $selectedRoom->id);
        }
        if($taken) {
            $freeClass = "taken";
        }
        echo "<div class='dayslot $freeClass' start='$time' end='$next'>";
        echo date("H:i", $time);
        echo " " . $taken;
        echo "</div>";
        $time = $next;
    }
    ?>
</div>