<?php
 /* @var $this \ns_2059b00f_8bcb_466d_89df_3de79acdf3a1\PmsCalendar */
$itemId = $this->getPage()->javapage->id;
$rooms = $this->getAllTypes();
$room = null;
$before = null;
$next = null;
$bef = null;
foreach($rooms as $r) {
    if(!$next && $room) {
        $next = $r->pageId;
    }
    if($r->pageId == $itemId) {
        $before = $bef;
        $room = $r;
    }
    $bef = $r->pageId;
}

$nextPage = $this->__w("summary") . "_" . $this->getSelectedName();
echo "<input type='hidden' class='continue' value='$nextPage'>";
?>
<div class='addbookingpopup' typeid="<? echo $room->id; ?>">
    <div style="position:relative;padding-bottom: 5px;">
        Bekreft tidspunkt og fortsett
        <i class="fa fa-close" onclick="$('.addbookingpopup').fadeOut();" style="position:absolute;right: 0px; top: 0px;"></i>
        &nbsp;
    </div>
    <table width="100%" cellspacing='2' cellpadding='0'>
        <tr>
            <td>Start dato</td>
            <td>
                <input type='date' class='selecteddate' value='<?php echo date("Y-m-d", $this->getSelectedDay()); ?>'>
            </td>
        </tr>
        <tr>
            <td>Start tid</td>
            <td>
                <input type="number" value="" min="0" max="23" gsname="starthour" class="starthour addmobilesmall">
                <input type="number" value="" min="0" max="59" gsname="startminute" class="startminute addmobilesmall">
            </td>
        </tr>
        <tr>
            <td>Slutt tid</td>
            <td>
                <input type="number" value=""  min="0" max="23" gsname="endhour" class="endhour addmobilesmall">
                <input type="number" value="" min="0" max="59" gsname="endminute" class="endminute addmobilesmall">
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <span class="continuebuttonmobile" gstype='submit'>Fortsett</span>
            </td>
        </tr>
    </table>
</div>

<div class="roomentry" style="border:11px #fff;">
    <?php
    if($before) {
        echo "<a href='?page=$before'><i class='fa fa-angle-left'></i></a>";
    }
    if($next) {
        echo "<a href='?page=$next'><i class='fa fa-angle-right'></i></a>";
    }
    $img = $this->getImageFromPage($itemId);
    echo "<img src='displayImage.php?id=$img'>";
    ?>
    <div class="bottomdesc">
        <?php echo "<b>" . $room->name . "</b><br>"; 
        echo "<span class='capasity'>Kapasitet: <br>" . $room->capacity . " personer</span>";
        echo $room->description;
        ?>
    </div>

</div>
<div class="dayselectioncheck"></div>
    <div style="border: solid 1px; background-color:#fff; text-align: center; padding-top: 10px; padding-bottom: 10px;" class="dayselection">
        <div class="smalltypeselection">
            <span class="changedateleft gotopage" style="padding: 10px;" pageid='<?php echo $before; ?>'>
                <?php
                if($before) {
                       echo "<i class='fa fa-caret-left'></i>";
                }             
                ?>
            </span>
            <? echo $room->name; ?>
            <span class="changedateright gotopage" style="padding: 10px;"  pageid='<?php echo $next; ?>'>
                <?php
                if($next) {
                    echo "<i class='fa fa-caret-right'></i>";
                }                
                ?>
            </span>
        </div>
        <div class="textdescription">
            Velg ønsket dag og tidspunkt for å starte bookingen
        </div>
            
        <div style="text-align: center;font-size: 40px; position:relative;">
            <span class="changedateleft" style="padding: 10px;" gstype="clicksubmit" method="setPrevious" gsname="type" gsvalue="day">
                <i class="fa fa-caret-left" method="setPrevious" gsname="type" gsvalue="day"></i>
            </span>
            <input type="date" value="<? echo date('Y-m-d', $this->getSelectedDay()); ?>" class="changemonthmobile">
            <span class="changedateright" style="padding: 10px;" gstype="clicksubmit" method="setNext" gsname="type" gsvalue="day">
               <i class="fa fa-caret-right " method="setNext" gsname="type" gsvalue="day"></i>
            </span>
        </div>
    </div>
<div>
<?php 
$curTime = $this->getStartTime($this->getSelectedDay()); 
$end = $this->getEndTime($this->getSelectedDay()); 
while(true) {
    $time = date("H", $curTime);
    $startTime = $curTime;
    $endTime = $startTime + 1800;
    $state = $this->getBlockState($room->id, $curTime, $startTime, $endTime);
    
    $startTime2 = $endTime;
    $endTime2 = $startTime2 + 1800;
    $state2 = $this->getBlockState($room->id, $curTime, $startTime2, $endTime2);
    
    echo "<div class='timerow'><span class='timebox'>$time</span>";
    echo "<span class='halfourbox first $state mobileentry' startTime='".date("H", $startTime)."' startMinute='".date("i", $startTime)."' endTime='".date("H", $endTime)."' endMinute='".date("i", $endTime)."'></span>";
    echo "<span class='halfourbox $state2 mobileentry' startTime='".date("H", $startTime2)."' startMinute='".date("i", $startTime2)."' endTime='".date("H", $endTime2)."' endMinute='".date("i", $endTime2)."'></span></div>";
    if($curTime >= $end) {
        break;
    }
    $curTime += 3600;
}
?>
</div>
