<?php
/* @var $this \ns_2059b00f_8bcb_466d_89df_3de79acdf3a1\PmsCalendar */
$rooms = $this->getAllTypes();
foreach($rooms as $room) {
    if(!$room->visibleForBooking && !$this->isEditorMode()) {
        continue;
    }
    if($room->addon) {
        continue;
    }
    if($this->isItemPage()) {
        if($room->pageId != $this->getPage()->javapage->id) {
            continue;
        }
    }
    ?>
<a href="?page=<?php echo $room->pageId; ?>">
    <div class='roomentry roomlistmobileouter'>
        <div class='roomentry roomlistmobile'>
            <?php 
            $img = $this->getImageFromPage($room->pageId);
            echo "<img src='displayImage.php?id=$img'>";
            ?>
            <div class="bottomdesc">
                <?php echo "<b>" . $room->name . "</b><br>"; 
                echo "<span class='capasity'>Kapasitet: <br>" . $room->capacity . " personer</span>";
                echo $room->description;
                ?>
            </div>
        </div>
    </div>
</a>
    <?php
}
?>