<?php
/* @var $this \ns_2059b00f_8bcb_466d_89df_3de79acdf3a1\PmsCalendar */
$rooms = $this->getAllRooms();
$types = $this->getAllTypes();
$type = $this->getDayType();

//need to be here to include theese days into the translation
$f = $this->__w("Monday");
$f = $this->__w("Tuesday");
$f = $this->__w("Wednesday");
$f = $this->__w("Thursday");
$f = $this->__w("Friday");
$f = $this->__w("Saturday");
$f = $this->__w("Sunday");

?>
<div class='calendartopheader'>
    <h2><?php echo $this->getConfigurationSetting("headingroomoverview"); ?></h2>
    <?php 
    if($type != "month") {
        $this->includefile("tinycalendar"); 
    }
    ?>
    <div style='padding-top: 70px;'>
        <div>
        <?php
            echo "<span class='typebutton "; if($type =="day") { echo "selected"; } echo "' gstype='clicksubmit' method='setDayType' gsname='type' gsvalue='day'>Dag</span>";
            echo "<span class='typebutton "; if($type =="week") { echo "selected"; } echo "' gstype='clicksubmit' method='setDayType' gsname='type' gsvalue='week'>Uke</span>";
            if($this->isItemPage()) {
                echo "<span class='typebutton "; if($type =="month") { echo "selected"; } echo "' gstype='clicksubmit' method='setDayType' gsname='type' gsvalue='month'>Måned</span>";
            }
        ?>
        </div>
        <div style='padding-top: 10px;'>
            <span style='padding-right: 30px; cursor:pointer;' gstype="clicksubmit" method="setPrevious" gsname="type" gsvalue="day">
                <i class='fa fa-caret-left'></i> <? echo $this->__w("Previous"); ?>
            </span>
            <? 
            if($type == "day") {
                echo $this->__w(date("d.m.Y", $this->getSelectedDay())); 
            } 
            if($type == "week") {
                echo $this->__w("Week") . " " . date("W", $this->getSelectedDay());
            }
            if($type == "month") {
                echo date("M Y", $this->getSelectedDay());
            }
            ?>
            <span style='padding-left: 30px; cursor:pointer;' gstype="clicksubmit" method="setNext" gsname="type" gsvalue="day">
                <? echo $this->__w("Next"); ?> <i class='fa fa-caret-right'></i>
            </span>
        </div>
        <span style='position:absolute; right:0px; bottom: 30px; display:inline-block; width: 150px; text-align: left;'>
            <div class='statedesrow'><span class='statedescbox occupied'></span> Opptatt</div>
            <div class='statedesrow'><span class='statedescbox notconfirmed'></span> Ikke bekreftet</div>
            <div class='statedesrow'><span class='statedescbox available'></span> Tilgjengelig</div>
            <div class='statedesrow'><span class='statedescbox not_available'></span> Ikke tilgjenglig</div>
            <div class='statedesrow'><span class='statedescbox selected_periode2'></span> Valgt</div>
        </span>
    </div>
</div>
<?


$withSideBar = "";
if(!$this->isItemPage() || $type == "month") {
    $withSideBar = "withSideBar";
}

echo "<div class='roomrow $withSideBar'>";
if($withSideBar) {
    echo "<span class='roomdescouter roomdesc_$type'></span>";
}
echo "<span class='timecontainer $withSideBar timecontainer_$type'>";
if($type == "day") {
    $this->printHeader($this->getSelectedDay(), $type);
}
if($type == "week" || $type == "month") {
    $start = strtotime('this week', $this->getSelectedDay());
    for($i = 0; $i < 7; $i++) {
        $this->printHeader($start, $type);
        $start += 86400;
    }
}
echo "<div style='clear:both;'></div>";
echo "</span>";
echo "</div>";

if($type == "month") {
    $dates = $this->getDates($this->getSelectedYear());
    $month = $this->getSelectedMonth();
    $year = $this->getSelectedYear();
    $monthDates = $dates[$month];
    
    foreach($monthDates as $week => $days) {
        echo "<div class='roomrow itemlist' itemid='".$this->getPage()->javapage->id."'>";
        ?>
        <span class='roomdescouter roomdesc_<? echo $type; ?>'>
            <span class='roomdesc'>
                <? echo $week; ?>
            </span>
        </span>
        <?php
         echo "<span class='timecontainer $withSideBar timecontainer_$type'>";
        for($i = 0; $i < 7; $i++) {
            $day="";
            if(isset($days[$i])) {
                $day = $days[$i]."-".$month."-".$year;
            }

            echo "<div class='weekdaycontainer'>";
            $this->printBlocks(strtotime($day), $type, $this->getPage()->javapage->id, $withSideBar);
            echo "</div>";
        }
        echo "</span>";
        echo "</div>";
     }
} else {
    foreach($rooms as $room) {
        if(!$types[$room->bookingItemTypeId]->visibleForBooking) {
            continue;
        }
        if($this->isItemPage()) {
            if($room->id != $this->getPage()->javapage->id) {
                continue;
            }
        }
        ?>
        <div class='roomrow itemlist' itemid='<? echo $room->id; ?>'>
            <?php
            if(!$this->isItemPage()) {
                $imgId = $this->getImageFromPage($room->id);
            ?>
                <span class='roomdescouter roomdesc_<? echo $type; ?>'>
                    <span class='roomdesc'>
                        <img src='displayImage.php?id=<? echo $imgId; ?>'>
                        <span class='roomattributes'>
                            <span class='roomname'><? echo $room->bookingItemName; ?></span><br>
                            <span class='roomcap'>Kap: 8 personer.</span><br>
                            <span class='roomequipment'>Utstyr: Prosjektor, smartboard, lydanlegg.</span>
                            <span class='readmorelink'><a href='?page=<? echo $room->id; ?>'><? echo $this->__w("Read more"); ?></a></span>
                        </span>
                    </span>
                </span>
                <?php
            }
            echo "<span class='timecontainer $withSideBar timecontainer_$type'>";
            if($type == "day") {
                $this->printBlocks($this->getSelectedDay(), $type, $room->id, $withSideBar);
            }
            if($type == "week") {
                $start = strtotime('this week', $this->getSelectedDay());
                for($i = 0; $i < 7; $i++) {
                    echo "<div class='weekdaycontainer'>";
                    $this->printBlocks(($start+(86400*$i)), $type, $room->id, $withSideBar);
                    echo "</div>";
                }
            }
            echo '</span>';
            ?>
        </div>
        <?
    }    
}

$nextPage = $this->getConfigurationSetting("continue");
if(!$nextPage) {
    $nextPage = "/" . $this->__w("summary") . "_" . $this->getSelectedName() . ".html";
}

?>
<div class='calendarfooter'>
    <span class='continue_button disabled' continue="<?php echo $nextPage; ?>"><? echo $this->__w("Continue"); ?></span>
</div>
