<?
$type = array();
$type['start_date'] = "Start date";
$type['end_date'] = "End date";
$dateType = $this->getConfigurationSetting("date_type");
?>

<div gstype="form" method="saveSettings">
    <table width="80%" class="contactConfigTable">
        <tr>
            <td width="50%"><? echo $this->__w("Name of the booking engine"); ?></td>
            <td width="50%"><input type="text" gsname="engine_name" style='width:100%;' value="<? echo $this->getConfigurationSetting("engine_name"); ?>"></td>
        </tr>
        <tr>
            <td width="50%"><? echo $this->__w("Continue to page"); ?></td>
            <td width="50%"><input type="text" gsname="continue" style='width:100%;' value="<? echo $this->getConfigurationSetting("continue"); ?>"></td>
        </tr>
        <tr>
            <td width="50%"><? echo $this->__w("Heading for room overview"); ?></td>
            <td width="50%"><input type="text" gsname="headingroomoverview" style='width:100%;' value="<? echo $this->getConfigurationSetting("headingroomoverview"); ?>"></td>
        </tr>
        <tr>
            <td width="50%"><? echo $this->__w("Heading text for calendar view"); ?></td>
            <td width="50%"><input type="text" gsname="headingcalendarview" style='width:100%;' value="<? echo $this->getConfigurationSetting("headingcalendarview"); ?>"></td>
        </tr>
        <tr>
            <td width="50%"><? echo $this->__w("Heading text for single room view"); ?></td>
            <td width="50%"><input type="text" gsname="headingbookroom" style='width:100%;' value="<? echo $this->getConfigurationSetting("headingbookroom"); ?>"></td>
        </tr>
        <tr>
            <td width="50%"><? echo $this->__w("Heading text for existing bookings in day view"); ?></td>
            <td width="50%"><input type="text" gsname="existingBookingsText" style='width:100%;' value="<? echo $this->getConfigurationSetting("existingBookingsText"); ?>"></td>
        </tr>
        <tr>
            <td width="50%"><? echo $this->__w("Heading text for select room in day view"); ?></td>
            <td width="50%"><input type="text" gsname="roomSelectedText" style='width:100%;' value="<? echo $this->getConfigurationSetting("roomSelectedText"); ?>"></td>
        </tr>
    </table>
    <input gstype="submit" type="button" value='Save'>
</div>
