<div class='filehistory'>
    <div class="sedox_filter_searchbox">
        <center>
        You can filter your result here by enter text in the textfield below:
        <br/><br/><input type="textfield" placeholder="search" id="filtercredithistory"/>
        </center>
    </div>
    <div class="credithistory_list">
        <?
        $hists = $this->getOrders();

        if (count($hists) == 0) {
            echo "No history";
            return;
        }

        foreach ( $hists as $order) {
            $product = $this->getApi()->getSedoxProductManager()->getProductById($order->productId);
            if ($product == null) {
                continue;
            }
            $name = $product->brand . " " . $product->model . " " . $product->engineSize . " " . $product->power . " " . $product->year;
            $id = $product->id;
            $date = $product->rowCreatedDate;

            echo "<a href='/index.php?page=productview&productId=$id'><div class='row'>"
            . "<div class='col col1'>$id</div>"
            . "<div class='col col2'>$name</div>"
            . "<div class='col col3'>$date</div>"
            . "</div></a>";
        }
        ?>

    </div>
</div>