<div class='sedox_box'>
    <div class='icon'>&nbsp;<i class='fa fa-user'></i>&nbsp;</div>
    <div class='details'>
        <b>Kai Tønder</b>
        <table>
            <tr><td>Email</td><td>kai@sedox.com</td></tr>
            <tr><td colspan="2"></td></tr>
            <tr><td style='width: 200px;'>Remaining credit</td><td>2311</td></tr>
            <tr><td>Files uploaded</td><td>211</td></tr>
            <tr><td>Slaves</td><td>0</td></tr>
        </table>
    </div>
</div>

<div class='sedox_box filehistory'>
    <div class='icon'>&nbsp;<i class='fa fa-file'></i>&nbsp;</div>
    <div class='details'>
        <b>Your files</b>
        <table>
            <tr><th class='col1'>Sedox Id</th><th class='col2'>File</th><th class='col3'>Uploaded</th></tr>
            <tr><td>10001</td><td>Audi A6 2.0 TDI 2005 200hp</td><td>2014-05-16 19:48:18</td></tr>
            <tr><td>10002</td><td>Audi A6 2.0 TDI 2005 200hp</td><td>2014-05-16 19:48:18</td></tr>
            <tr><td>10003</td><td>Audi A6 2.0 TDI 2005 200hp</td><td>2014-05-16 19:48:18</td></tr>
            <tr><td>10004</td><td>Audi A6 2.0 TDI 2005 200hp</td><td>2014-05-16 19:48:18</td></tr>
        </table>
    </div>
    <div class='gs_button'>More <i class="fa fa-arrow-right"></i></div>
</div>

<div class='sedox_box credithistory'>
    <div class='icon'>&nbsp;<i class='fa fa-university'></i>&nbsp;</div>
    <div class='details'>
        <b>Credit account</b>
        <table>
            <tr><th class='col1'>Sedox Id</th><th class='col2'>File</th><th class='col3'>Uploaded</th></tr>
            <tr><td>10001</td><td>Bought product: VW Golf 5 GTI 2.0T 147kW 2005 CmdEncrypted</td><td>2014-05-16 19:48:18</td></tr>
            <tr><td>10002</td><td>VW Passat 1.6TDI 2012 Siemens 105.0 A6EC CmdEncrypted/Original/Tune</td><td>2014-05-16 19:48:18</td></tr>
            <tr><td>10003</td><td>VW Passat 1.6TDI 2012 Siemens 105.0 A6EC</td><td>2014-05-16 19:48:18</td></tr>
            <tr><td>10004</td><td>Bought product: Buick Regal 1.6T 179.0 2010 CmdEncrypted/Original/Tune</td><td>2014-05-16 19:48:18</td></tr>
        </table>
    </div>
    <div class='gs_button'>More <i class="fa fa-arrow-right"></i></div>
</div>

<div class='sedox_box'>
    <div class='icon'>&nbsp;<i class='fa fa-users'></i>&nbsp;</div>
    <div class='details'>
        <b>Your partners</b>
        <table>
            <tr><td>Sorry, but there is no partners setup for you. Do you have partners that needs to be connected? let us know.</td></tr>
        </table>
    </div>
    <div class='gs_button'>More <i class="fa fa-arrow-right"></i></div>
</div>
<div class='bottom_information'>
    Dont see all of the information that you wish to see here? Let us know if you find anything missing.
</div>