<?
/* @var $this ns_32b5f680_dd8d_11e3_8b68_0800200c9a66\SedoxUserPanel */
?>

<div class='sedox_box'>
    <div class='icon'>&nbsp;<i class='fa fa-user'></i>&nbsp;
    </div><div class='details'>
        <b>General statistic</b>
        <table>
            <tr><td style='width: 200px;'>Name</td><td>-</td></tr>
            <tr><td colspan="2"></td></tr>
            <tr><td>Remaining credit</td><td><? echo $this->getCreditAccountBalance(); ?></td></tr>
            <tr><td>Files uploaded</td><td><? echo $this->getFileCount(); ?></td></tr>
            <tr><td>Slaves</td><td>0</td></tr>
        </table>
    </div>
</div>

<div class='sedox_box filehistory'>
    <div class='icon'>&nbsp;<i class='fa fa-file'></i>&nbsp;
    </div><div class='details'>
        <b>Your files</b>
        
        <div class='filehistory'>
            <?
                $lastestUploadedProducts = $this->getLatestUploadedProducts();
                if ($lastestUploadedProducts  != null) {
                    echo "<div class='row'><div class='col col1'>Sedox Id</div><div class='col col2'>File</div><div class='col col3'>Uploaded</div></div>";
                    foreach ($lastestUploadedProducts as $product) {
                        $name = $product->brand." ".$product->model." ".$product->build." ".$product->power." ".$product->year;
                        $id = $product->id;
                        $date = $product->rowCreatedDate;
                        
                        // TODO - Use divs?
                        echo "<a href='?page=productview&productId=$id'><div class='row'><div class='col col1'>$id</div><div class='col col2'>$name</div><div class='col col3'>$date</div></div></a>";
                    }
                } else {
                    echo "<div class='row'>You have not uploaded any files yet.</div>";
                }
            ?>
        </div>
    </div>
    <div class='sedox_button'>More <i class="fa fa-arrow-right"></i></div>
</div>

<div class='sedox_box credithistory'>
    <div class='icon'>&nbsp;<i class='fa fa-university'></i>&nbsp;
    </div><div class='details'>
        <b>Credit account</b>
        <table>
            <?
            $latestCreditHistory = $this->getLatestCreditHistory();
            if ($latestCreditHistory != null) {
                echo "<tr><th class='col1'>Sedox Id</th><th class='col2'>Description</th><th class='col3'>Date</th></tr>";
                foreach ($latestCreditHistory as $hist) { ?>
                    <tr><td><? echo $hist->transactionReference; ?></td><td><? echo $hist->description; ?></td><td><? echo $hist->dateCreated; ?></td></tr>
                <?}
            } else {
                echo "<tr><td colspan='4'>You have not made any credit transactions yet.</td></tr>";
            }
            ?>
        </table>
    </div>
    <div class='sedox_button'>More <i class="fa fa-arrow-right"></i></div>
</div>

<div class='sedox_box'>
    <div class='icon'>&nbsp;<i class='fa fa-users'></i>&nbsp;
    </div><div class='details'>
        <b>Your partners</b>
        <table>
            <tr><td>Sorry, but there is no partners setup for you. Do you have partners that needs to be connected? let us know.</td></tr>
        </table>
    </div>
    <div class='sedox_button'>More <i class="fa fa-arrow-right"></i></div>
</div>
<div class='bottom_information'>
    Dont see all of the information that you wish to see here? Let us know if you find anything missing.
</div>