<?php
/* @var $this ns_a6d68820_a8e3_4eac_b2b6_b05043c28d78\Company */
$company = $this->getApi()->getUserManager()->getCompany($_POST['value']);
//print_r($company);
?>

<div class='gss_settings_header'>
    <i class='fa fa-edit'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $company->name; ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?php
            echo $this->__f("Change company settings below");
            ?>
        </div>
    </div>
</div>

<div class='gss_settings_content'>

    <input type="hidden" gs_model='companymodel' gs_model_attr='companyid' value="<? echo $company->id; ?>"/>

    <div class="gss_settings_title"><? echo $this->__f("General company settings"); ?></div>
    <div class="textfield gss_setting"  id="vatNumber">
        <span class="title"><?php echo $this->__f("Vat number"); ?></span>
        <input type="textfield" gs_model='companymodel' gs_model_attr='vatNumber' value="<? echo $company->vatNumber; ?>" DISABLED>
        <div class="description">
            <?php echo $this->__("The vat number"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="name">
        <span class="title"><?php echo $this->__f("Name"); ?></span>
        <input type="textfield" gs_model='companymodel' gs_model_attr='name' value="<? echo $company->name; ?>">
        <div class="description">
            <?php echo $this->__("The company name"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="prefix">
        <span class="title"><?php echo $this->__f("Phone prefix"); ?></span>
        <input type="textfield" gs_model='companymodel' gs_model_attr='prefix' value="<? echo $company->prefix; ?>">
        <div class="description">
            <?php echo $this->__("Country prefix for mobile phone"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="phone">
        <span class="title"><?php echo $this->__f("Phone"); ?></span>
        <input type="textfield" gs_model='companymodel' gs_model_attr='phone' value="<? echo $company->phone; ?>">
        <div class="description">
            <?php echo $this->__("Phone number for company"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="email">
        <span class="title"><?php echo $this->__f("Email"); ?></span>
        <input type="textfield" gs_model='companymodel' gs_model_attr='email' value="<? echo $company->email; ?>">
        <div class="description">
            <?php echo $this->__("Company's main email"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="invoiceEmail">
        <span class="title"><?php echo $this->__f("Invoice email"); ?></span>
        <input type="textfield" gs_model='companymodel' gs_model_attr='invoiceEmail' value="<? echo $company->invoiceEmail; ?>">
        <div class="description">
            <?php echo $this->__("Company's main email"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="website">
        <span class="title"><?php echo $this->__f("Website"); ?></span>
        <input type="textfield" gs_model='companymodel' gs_model_attr='website' value="<? echo $company->website; ?>">
        <div class="description">
            <?php echo $this->__("Company's website"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="contactPerson">
        <span class="title"><?php echo $this->__f("Contact"); ?></span>
        <input type="textfield" gs_model='companymodel' gs_model_attr='contactPerson' value="<? echo $company->contactPerson; ?>">
        <div class="description">
            <?php echo $this->__("Default contact person for company"); ?>
        </div>
    </div>
    
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="deleteCompany" gss_confirmation="Are you sure you want to delete this company?" gss_model="companymodel"><i class="fa fa-remove"></i>Slett firma</div>
        <div class="gss_button" gss_method="updateCompanyInformation" gss_model="companymodel" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Update"); ?></div>
    </div>

</div>
