<?
/* @var $this ns_d02f8b7a_7395_455d_b754_888d7d701db8\Dibs */

$automarkpaid = $this->getConfigurationSetting("automarkpaid");

?>

<div class='gss_settings_header'>
    <i class='fa fa-envelope'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <?php echo $this->getName(); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?php echo $this->getDescription(); ?>
        </div>
    </div>	
</div>

<div class='gss_settings_content' gstype='form' method='saveSettings'>
    
    <div class="textfield gss_setting"  id="ordertype">
        <span class="title"><?php echo $this->__f("Intrum customer number"); ?></span>
        <input type="textfield" gs_model='intrumcontrol' gs_model_attr='customernumber' value="<? echo $this->getConfigurationSetting("customernumber"); ?>">
        <div class="description">
            <?php  echo $this->__f("A designated customer number given by Intrum"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="ordertype">
        <span class="title"><?php echo $this->__f("Intrum customer number"); ?></span>
        <input type="textfield" gs_model='intrumcontrol' gs_model_attr='department' value="<? echo $this->getConfigurationSetting("department"); ?>">
        <div class="description">
            <?php  echo $this->__f("A designated department number given by Intrum"); ?>
        </div>
    </div>
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="intrumcontrol" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>

</div>
