<?
/* @var $this \ns_df607cb0_efb4_44f8_bbac_7bf6fa4bc5b7\Carousel */

$slideIds = array_filter(explode("|", $this->getConfigurationSetting("slideids")));
$appId = $this->getAppInstanceId();
?>

<div id="slider1" class="csslider infinity" style="<? echo $this->getConfigurationSetting("carouselheight") != "" ? "height: " . $this->getConfigurationSetting("carouselheight") . "px; " : ""?>">
  
    <?
        foreach ($slideIds as $slideId) {
    ?>
            <input type="radio" name="slides" id="slides_<? echo $slideId; ?>" <? echo $slideId == $slideIds[0] ? "checked" : ""?>>
    <?
        }
    ?>
    <ul>
        <?
            if(!empty($slideIds)) {
                foreach ($slideIds as $slideId) {
        ?>
                    <li style="background-image: url(/displayImage.php?id=<? echo $this->getApi()->getBannerManager()->getSlideById($slideId)->backgroundFileId ?>">
                        <? 
                        $this->printCell($appId . "_" . $slideId);
                        ?>
                    </li>
        <?  
                }
            } else {
                ?>
                    <li class="start_adding_slides"><span>Start adding slides by using the application's settings!</span></li>
                <?
            }
        ?>
    </ul>
    <?
      $arrowStyle = "";
      if($this->getConfigurationSetting("showarrows") == "false") {
          $arrowStyle .= "display: none; ";
      }
      if($this->getConfigurationSetting("arrowvertical") != "") {
          $arrowStyle .= "top: " . $this->getConfigurationSetting("arrowvertical") . "%; ";
      }
      if($this->getConfigurationSetting("arrowhorizontal") != "") {
          $arrowStyle .= "left: " . $this->getConfigurationSetting("arrowhorizontal") . "%; ";
          $arrowStyle .= "width: " . (100 - 2 * $this->getConfigurationSetting("arrowhorizontal")) . "%; ";
      }
    ?>
    <div class="arrows" style="<? echo $arrowStyle ?>" >
        <?
            foreach ($slideIds as $slideId) {
        ?>
                <label for="slides_<? echo $slideId; ?>"></label>
        <?
            }
        ?>
        <label for="slides_<? echo $slideIds[0];?>" class="goto-first"></label>
        <label for="slides_<? echo $slideIds[count($slideIds) - 1]; ?>" class="goto-last"></label>
    </div>
    <div class="navigation" <? echo $this->getConfigurationSetting("showbullets") == "false" ? "style='display: none;'" : "" ?> >
        <div>
            <?
                foreach ($slideIds as $slideId) {
            ?>
                    <label for="slides_<? echo $slideId; ?>"></label>
            <?
                }
            ?>
        </div>
    </div>
</div>

<?
if($this->getConfigurationSetting("autoslide") == "true") {
?>
<script>
// Auto clicker for slide
var forwarder = function() {
    var direction = "<? echo $this->getConfigurationSetting("slidedirection"); ?>";
    $(".Carousel[appid='<? echo $appId; ?>'] .arrows label").each(function() {
       if($(this).css(direction) === "0px") {
           $(this).click();
           return false;
       } 
    });
};

var slideInterval = "<? echo $this->getConfigurationSetting("slidespeed"); ?>"
var slideInterval = slideInterval != "" ? slideInterval : 3000;
var forwarderInterval = setInterval(forwarder, slideInterval);

$(".Carousel[appid='<? echo $appId; ?>'] .arrows label").on('click', function() {
    clearInterval(forwarderInterval);
    forwarderInterval = setInterval(forwarder, slideInterval);
});
// Auto clicker for slide

// CSS definitios for transition types
var transitionType = "<? echo $this->getConfigurationSetting("transition"); ?>";
var cssAnimation = document.createElement('style');
cssAnimation.type = 'text/css';

if(transitionType == "slide") {
    var cssString = "" + 
            ".Carousel[appid='<? echo $appId; ?>'] .csslider > ul > li {" +
            "position: relative;" +
            "}";
    
    for(var i = 1; i <= 10; i++) {
        cssString += "" +
            ".Carousel[appid='<? echo $appId; ?>'] .csslider > input:nth-of-type(" + i + "):checked ~ ul li:first-of-type {" +
            "margin-left: -" + (i-1) * 100 + "%;" +
            "}";
    }
} else if(transitionType == "fade") {
    var cssString = "" + 
            ".Carousel[appid='<? echo $appId; ?>'] .csslider > ul > li {" +
            "position: absolute;" +
            "opacity: 0;" +
            "}";
    
    for(var i = 1; i <= 10; i++) {
        cssString += "" +
            ".Carousel[appid='<? echo $appId; ?>'] .csslider > input:nth-of-type(" + i + "):checked ~ ul li:nth-of-type(" + i + ") {" +
            "opacity: 1;" +
            "}";
    }
}

var rules = document.createTextNode(cssString);
cssAnimation.appendChild(rules);
$("head")[0].appendChild(cssAnimation);
// CSS definitios for transition types
</script>
<?
}
?>
