<?
/* @var $this \ns_df607cb0_efb4_44f8_bbac_7bf6fa4bc5b7\Carousel */
?>

<div id="slider1" class="csslider infinity" style="<? echo $this->getConfigurationSetting("carouselheight") != "" ? "height: " . $this->getConfigurationSetting("carouselheight") . "px; " : ""?>">
  
    <?
        for ($i = 1; $i <= $this->getConfigurationSetting("slidenumber"); $i++) {
    ?>
            <input type="radio" name="slides" id="slides_<? echo $i; ?>" <? echo $i == 1 ? "checked" : ""?>>
    <?
        }
    ?>
    <ul>
        <?
            for ($i = 1; $i <= $this->getConfigurationSetting("slidenumber"); $i++) {
                $id = $this->getAppInstanceId();
            ?>
                <li style='padding-left: 150px;padding-right: 150px;'>
                    <? 
                    $this->printCell($id . "_" . $i);
                    if($this->getConfigurationSetting("slideimage" . $i)) { ?>
                        <img src="/displayImage.php?id=<? echo $this->getConfigurationSetting("slideimage" . $i); ?>"> 
                    <? } ?>
                </li>
        <?
            }
        ?>
    </ul>
    <?
      $arrowStyle = "";
      if($this->getConfigurationSetting("showarrows") == "false") {
          $arrowStyle .= "display: none; ";
      }
      if($this->getConfigurationSetting("arrowvertical") != "") {
          $arrowStyle .= "top: " . $this->getConfigurationSetting("arrowvertical") . "%; ";
      }
      if($this->getConfigurationSetting("arrowhorizontal") != "") {
          $arrowStyle .= "left: " . $this->getConfigurationSetting("arrowhorizontal") . "%; ";
          $arrowStyle .= "width: " . (100 - 2 * $this->getConfigurationSetting("arrowhorizontal")) . "%; ";
      }
    ?>
    <div class="arrows" style="<? echo $arrowStyle ?>" >
        <?
            for ($i = 1; $i <= $this->getConfigurationSetting("slidenumber"); $i++) {
        ?>
                <label for="slides_<? echo $i; ?>"></label>
        <?
            }
        ?>
        <label for="slides_1" class="goto-first"></label>
        <label for="slides_<? echo $this->getConfigurationSetting("slidenumber")?>" class="goto-last"></label>
    </div>
    <div class="navigation" <? echo $this->getConfigurationSetting("showbullets") == "false" ? "style='display: none;'" : "" ?> >
        <div>
            <?
                for ($i = 1; $i <= $this->getConfigurationSetting("slidenumber"); $i++) {
            ?>
                    <label for="slides_<? echo $i; ?>"></label>
            <?
                }
            ?>
        </div>
    </div>
</div>

<?
if($this->getConfigurationSetting("autoslide") == "true") {
?>
<script>
var forwarder = function() {
    var direction = "<? echo $this->getConfigurationSetting("slidedirection"); ?>";
    $(".arrows label").each(function() {
       if($(this).css(direction) === "0px") {
           $(this).click();
           return false;
       } 
    });
};

var slideInterval = "<? echo $this->getConfigurationSetting("slidespeed"); ?>"
var slideInterval = slideInterval != "" ? slideInterval : 3000;
var forwarderInterval = setInterval(forwarder, slideInterval);

$(".arrows label").on('click', function() {
    clearInterval(forwarderInterval);
    forwarderInterval = setInterval(forwarder, slideInterval);
});
</script>
<?
}
?>
