<?
/* @var $this \ns_df607cb0_efb4_44f8_bbac_7bf6fa4bc5b7\Carousel */

$slideIds = array_filter(explode("|", $this->getConfigurationSetting("slideids")));
$appId = $this->getAppInstanceId();
?>

<div id="slider1" class="csslider infinity" style="<? echo $this->getConfigurationSetting("heighttype") != "ratio" ? $this->getConfigurationSetting("carouselheight") != "" ? "height: " . $this->getConfigurationSetting("carouselheight") . $this->getConfigurationSetting("heighttype") : "" : ""?>">
  
    <?
        foreach ($slideIds as $slideId) {
    ?>
            <input type="radio" name="slides" id="slides_<? echo $slideId; ?>" <? echo $slideId == $slideIds[0] ? "checked" : ""?>>
    <?
        }
    ?>
    <ul>
        <?
            if(!empty($slideIds)) {
                foreach ($slideIds as $slideId) {
        ?>
                    <li style="background: url('/displayImage.php?id=<? echo $this->getApi()->getBannerManager()->getSlideById($slideId)->backgroundFileId ?>') no-repeat center center fixed; background-size:cover;">
                        <? 
                        $this->printCell($appId . "_" . $slideId);
                        ?>
                    </li>
        <?  
                }
            } else {
                ?>
                    <li class="start_adding_slides"><span>Start adding slides by using the application's settings!</span></li>
                <?
            }
        ?>
    </ul>
    <?
      $arrowStyle = "";
      if($this->getConfigurationSetting("showarrows") == "false") {
          $arrowStyle .= "display: none; ";
      }
      if($this->getConfigurationSetting("arrowvertical") != "") {
          $arrowStyle .= "top: " . $this->getConfigurationSetting("arrowvertical") . "%; ";
      }
      if($this->getConfigurationSetting("arrowhorizontal") != "") {
          $arrowStyle .= "left: " . $this->getConfigurationSetting("arrowhorizontal") . "%; ";
          $arrowStyle .= "width: " . (100 - 2 * $this->getConfigurationSetting("arrowhorizontal")) . "%; ";
      }
    ?>
    <div class="arrows" style="<? echo $arrowStyle ?>" >
        <?
            foreach ($slideIds as $slideId) {
        ?>
                <label for="slides_<? echo $slideId; ?>"></label>
        <?
            }
        ?>
        <label for="slides_<? echo $slideIds[0];?>" class="goto-first"></label>
        <label for="slides_<? echo $slideIds[count($slideIds) - 1]; ?>" class="goto-last"></label>
    </div>
    <div class="navigation" <? echo $this->getConfigurationSetting("showbullets") == "false" ? "style='display: none;'" : "" ?> >
        <div>
            <?
                foreach ($slideIds as $slideId) {
            ?>
                    <label for="slides_<? echo $slideId; ?>"></label>
            <?
                }
            ?>
        </div>
    </div>
</div>

<script>
app.Carousel.setTransitionType("<? echo $this->getConfigurationSetting("transition"); ?>", "<? echo $appId; ?>")
app.Carousel.setSlideNumber("<? echo $appId; ?>");
</script>

<?
if($this->getConfigurationSetting("autoslide") == "true") {
?>
<script>
// Auto clicker for slide
app.Carousel.initAutoClicker("<? echo $appId; ?>", "<? echo $this->getConfigurationSetting("slidedirection"); ?>", "<? echo $this->getConfigurationSetting("slidespeed"); ?>");
</script>
<?
}

if($this->getConfigurationSetting("heighttype") == "%") {
?>
<script>
app.Carousel.setCarouselPercentageHeight("<? echo $appId; ?>");
</script>
<?
}

if($this->getConfigurationSetting("heighttype") == "ratio") {
?>
<script>
app.Carousel.alignCarousel("<? echo $appId; ?>", "<? echo $this->getConfigurationSetting("carouselheight"); ?>");
    
$(window).resize(function() {
    app.Carousel.alignCarousel("<? echo $appId; ?>", "<? echo $this->getConfigurationSetting("carouselheight"); ?>");
});
</script>
<?
}
?>