<?
/* @var $this ns_c7b87917_6a26_43cf_9876_7e3ef9eeab3e\SedoxFileMatched */
/* @var $product core_sedox_SedoxProduct */
$product = $this->getCurrentProduct();
$productName = $product->printableName;


if (!function_exists("sedox_notAvailableCheck")) {
    function sedox_notAvailableCheck($input) {
        if (!$input) {
            return "N/A";
        }

        return $input;
    }
}
?>
<div class="sedox_internal_view" style="display: block;">
    
    <div class="innerview">
        <div class='title boldFont'>
            <i class='fa fa-file'></i> <? echo $productName; ?>
            <div class="extra_title_information">
                <br/>Orig. Checksum: <? echo sedox_notAvailableCheck($product->originalChecksum); ?>
                <br/>ECU Brand / Type: <? echo sedox_notAvailableCheck($product->ecuBrand); ?>
                <br/>ECU Part No.: <? echo sedox_notAvailableCheck($product->ecuPartNumber); ?>
                <br/>ECU Hardware No.: <? echo sedox_notAvailableCheck($product->ecuHardwareNumber); ?>
                <br/>ECU Software No.: <? echo sedox_notAvailableCheck($product->ecuSoftwareNumber); ?>
                <br/>ECU Version: <? echo sedox_notAvailableCheck($product->ecuSoftwareVersion); ?>
                <br/>File Size: <? echo sedox_notAvailableCheck($product->softwareSize); ?>
                <br/>Tool: <? echo sedox_notAvailableCheck($product->tool); ?>
            </div>
        </div>
        <div class='downloadinfo'>
            <div class='box_header boldFont'>
                Download Information
            </div>
            <div class='box_content'>
                <?
                echo "<select class='fileselector'>";
                foreach ($product->binaryFiles as $binFile) {
                    $checksumCorrect = $binFile->checksumCorrected ? "Yes" : "No";
                    $extraInfo = sedox_notAvailableCheck($binFile->extraInformation);
                    echo "<option checksumupdated='$checksumCorrect' extrainfo='N/A' admintools='N/A'>" . $binFile->fileType . "</option>";
                }
                echo "</select>";
                ?>

                <div class='row_type1'>
                    Checksum updated:
                    <div class='row_subinfo' lookingfor="checksumupdated">-</div>
                </div>

                <div class='row_type1'>
                    Extra information:
                    <div class='row_subinfo' lookingfor="extrainfo">-</div>
                </div>

                <div class='row_type1'>
                    Admin Tools:
                    <div class='row_subinfo' lookingfor="admintools">-</div>
                </div>

                <div class='priceview'>
                    <div class='price boldFont'>100</div>
                    <div class='pricetext boldFont'>CREDITS</div>
                    <div class='sedox_blue_button'>Purchase and Download</div>
                </div>
            </div>
        </div>

        <div class='fileinfo'>
            <div class='box_header boldFont'>
                Request modification
                <div class='subinfo'>
                    Created: <? echo $product->rowCreatedDate; ?>
                </div>
            </div>

            <div class='box_content' gstype="form" method="requestSpecialFile">
                Please specify in detail what changes you require:
                <br/>
                <input type="hidden" gsname="productId" value="<? echo $_GET['productId']; ?>"/>
                <textarea gsname="description"></textarea>
                
                <div class="inner_button_area_request_special">
                    <div class="sedox_blue_button request_special_file" gstype="submit" >Request file</div>
                </div>
            </div>            
        </div>    
        
        <div class='creditinformation'>
            <div class='sedox_blue_button'>Purchase Credits</div> 
            All files at this page are developed by Sedox Performance.
             <div class='redinfo'>Download is not available unless you have credit at your account.</div>       
         </div>
    </div>
    
</div>