<?php
/* @var $this BookRoomPage */
$test = $this->getApi()->getPmsBookingProcess()->saveGuestInformation($this->getBookingEngineName(), array());
?>
<div class='heading'>
    Summary
</div>

<div class='headerinfo'>
    <?php echo $this->__f("Checkout date").": ". $_SESSION['checkoutdate']; ?> 
    <div class='button changecheckoutdate'><?php echo $this->__f("Change checkout date"); ?></div>
    <a href='/?page=bookingfrontpage'><div class='button red cancelbooking'><?php echo $this->__f("Cancel booking"); ?></div></a>
</div>


<div class='roomrow '>
    <div class='guestname'><?php echo $this->__f("Guest Count"); ?></div>
    <div class='total'><?php echo $this->__f("Price") ?></div>
</div>

<?php

$i = 0;
$sum = 0;
foreach ($test->rooms as $room) {
    $i++;
    $sum += $room->totalCost;
    ?>
    <div class='roomrow' >
        <span class="iconbutton icon-trash deleteroom" roomid='<?php echo $room->roomId; ?>'></span><div class='roomname1'><?php echo $room->roomName; ?></div>
        <div class='guestname'><div class='guestcount'><?php echo $room->guestCount; ?></div></div>
        <div class='guestcountselector'>
            <?php
            for ($j=1;$j<=$room->maxGuests;$j++) {
                echo "<div class='guestcountselect' count='$j' roomid='$room->roomId'>$j</div>";
            }
            ?>
        </div>
        <div class='total'><?php echo $room->totalCost; ?></div>
    </div>    
    <?php
}
?>

<div class='roomrow last'>
    <div class='guestname'></div>
    <div class='roomname1'><?php echo $this->__f("Total"); ?></div>
    <div class='total final'><?php echo $sum; ?></div>
</div>    

<div class='button addmorerooms'><i class='icon-undo'></i> <?php echo $this->__f("Add more rooms"); ?></div>

<div class='button nextbutton'><?php echo $this->__f("Next"); ?> <i class='icon-redo'></i> </div>