<?php
/* @var $this BookRoomPage */
$bookingInfo = $this->startBooking();
?>

<div class="heading">
    <?php
    echo $this->__f("Select your room");
    ?>
</div>

<div class='headerinfo'>
    <?php echo $this->__f("Checkout date").": ". $_SESSION['checkoutdate']; ?> 
    <div class='button changecheckoutdate'><?php echo $this->__f("Change checkout date"); ?></div>
    <a href='/?page=bookingfrontpage'><div class='button red cancelbooking'><?php echo $this->__f("Cancel booking"); ?></div></a>
</div>

<script>
    images = {};
</script>

<div>
    <?php
    $i = 0;
    
    $anyToSelect = false;
    foreach ($bookingInfo->rooms as $room) {
        if (!$room->visibleForBooker) {
            continue;
        }
        
        if (!$room->systemCategory == 0) {
            continue;
        }
        
        if ($this->isRoomAvailableForSelect($room->availableRooms, $room->id)) {
            $anyToSelect = true;
            break;
        }
    }
    
    if (!$anyToSelect) {
        echo "<div class='no_rooms_available'>";
            echo $this->__f("Sorry, we dont have any available rooms");
            echo "<br/>";
            echo "<br/>";
            if ($this->anyRoomsInCart()) {
                echo "<div class='button gotooverview'>".$this->__f("Continue")."</div>";
            } else {
                echo "<a href='/?page=bookingfrontpage'><div class='button gotooverview'>".$this->__f("Continue")."</div></a>";
            }
        echo "</div>";
        return;
    }

    
    foreach ($bookingInfo->rooms as $room) {
        if (!$room->visibleForBooker)
            continue;
        
        if (!$room->systemCategory == 0) {
            continue;
        }
        
        $i++;
        
        ?>
    
        <script>
         var imageList = [];
        <?php
        foreach ($room->images as $image) {
            ?>
            imageList.push({
                src: '<?php echo "https://www.getshop.com/displayImage.php?id=".$image->fileId; ?>',
                w: 1024,
                h: 680
            })
            <?php
        }
        $odd = $i % 2 ? "odd" : "";
        
        $canSelectRoom = $this->isRoomAvailableForSelect($room->availableRooms, $room->id);
        ?>
        images['<?php echo $room->id;?>'] = imageList;
        </script>
        <div class='roomtype <?php echo $odd; ?>'>
            <div class='roomname'><?php echo $room->name; ?></div>
            <div class="image" onclick='pga.page.showPhotoSwipe("<?php echo $room->id; ?>")'>
                <?php
                $defaultImage = $this->getDefaultImage($room->images);
                echo "<img src='https://www.getshop.com/displayImage.php?id=$defaultImage->fileId&width=300'/>";
                ?>
            </div>
            <div class='description'>
                <?php
                echo $room->description;
                ?>
            </div>
            
            <?php
            if ($canSelectRoom) {
                ?>
                <div class='button selectroom' typeid='<?php echo $room->id; ?>'><?php echo $this->__f("Select"); ?></div>
                <?php
            } else {
                ?>
                <div class='button red'><?php echo $this->__f("Sold out"); ?></div>
                <?php
            }
            ?>
        </div>
        <?php
    }
    ?>
</div>