<div class="newcustomerform" gstype="form" method="addCustomer">
    <input type='text' placeholder='Search customer' class='searchbrregcustomer' style='width:95%; margin-left: 20px;'>
    <div class='brregresult'>
        
    </div>
    <label>
        Org id
        <input type="txt" gsname="orgid">
    </label>
    <label>
        Company name
        <input type="txt" gsname="name">
    </label>
    <label>
        Street address
        <input type="txt" gsname="streetAddress">
    </label>
    <label>
        Phone number
        <input type="txt" gsname="phone">
    </label>
    <label>
        Contact person
        <input type="txt" gsname="contactPerson">
    </label>
    <label>
        Website
        <input type="txt" gsname="website">
    </label>
    <span class='mybutton' gstype='submit'>Register customer</span>
</div>