<?
/* @var $this \ns_ae288b19_9934_4e34_ade7_e8abba43b477\SedoxFiluploadCount */
?>
<div class="uploadcounter counter1">
    <div class="filecount boldFont"><? echo $this->getUploadCount(); ?></div>
    <div class="subinfo boldFont"> Uploads</div>
</div>

<div class="uploadcounter counter2">
    <div class="filecount boldFont"><? echo $this->getDownloadCount(); ?></div>
    <div class="subinfo boldFont"> Downloads </div>
</div>