<?php
/* @var $this ns_994d7fed_d0cf_4a78_a5ff_4aad16b9bcab\SimpleFileUpload */
$entries = $this->getAllFiles();
if(!$entries) {
    $entries = array();
}
if(sizeof($entries) == 0) {
    echo $this->__w("No files added.");
}
echo "<table width='100%'>";
foreach($entries as $entry) {
    if($this->imagePrinted == $entry->id) {
        continue;
    }
    
    if($this->isEditorMode()) {
        echo "<tr fileid='".$entry->id."'>";
            echo "<td width='100' colspan='4'>";

                $filename = $this->getFileName($entry);
                echo "<i class='fa fa-edit' fileName='$filename'></i> ";
                echo "<i class='fa fa-trash-o'></i> ";
            echo "</td>";
        echo "</tr>";
    }
    
    echo "<tr fileid='".$entry->id."'>";
    echo "<td width='50'>";
        echo "<i class='fa fa-" . $this->translateFile($entry->name, $entry->type) . "'></i>";
    echo "</td>";
    echo "<td width='80'>" . date("d.m.Y", strtotime($entry->rowCreatedDate)) . "</td>";
    echo "<td><a onclick=\"window.open('loadFile.php?fileid=".$entry->id."')\">" . $entry->name . "</a></td>";
    echo "<td width='100' align='right'>" . $this->humanFileSize($entry->size) . "</td>";
    echo "</tr>";
    if($this->isEditorMode()) {
        echo "<tr fileid='".$entry->id."'><td colspan='4'><hr/></td></tr>";
    }
}
echo "</table>";
?>