<?
/* @var $this \ns_c0f2b792_479c_49ad_8e46_34e50f7f4e88\WorkPackages */
$package = $this->getApi()->getC3Manager()->getWorkPackage($_POST['value']);

?>

<?
/* @var $this \ns_c0f2b792_479c_49ad_8e46_34e50f7f4e88\WorkPackages */
?>

<div class='gss_settings_header'>

    <input gs_model='wpmodel' type='hidden' value='<? echo $package->id; ?>' gs_model_attr='value'>
    
    <span class="fa-stack fa-lg" style="margin-right: 50px;">
        <i class="fa fa-briefcase fa-stack-1x"></i>
    </span>
 
    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Create new workpackage"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("Fill out the form below to create a new workpackage.");
            ?>	
        </div>
    </div>	
</div>

<div class='gss_settings_content'>
    <div class="textfield gss_setting"  id="name" >
        <span class="title"><?php echo $this->__f("Name"); ?></span>
        <input type="textfield" gs_model='wpmodel' gs_model_attr='name' placeholder="wp" value="<? echo $package->name; ?>">
        <div class="description">
            <?php echo $this->__("Name of the workpackage that owns this new account."); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting" id="shouldSendEmail">
        <span class="title">Description of workpackage</span>
        <textarea gs_model="wpmodel" gs_model_attr="description" style="position: initial; width: 945px; height: 300px;"><? echo $package->description; ?></textarea>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_fragment="wplist" gss_view="gs_wp_workarea" gss_method="deleteWorkPackage" gss_model="wpmodel"><i class='fa fa-remove'></i><?php echo $this->__("Delete"); ?></div>
        <div class="gss_button" gss_success_message="Saved" gss_fragment="editwp" gss_view="gs_wp_workarea" gss_method="saveWorkPackage" gss_model="wpmodel"><i class='fa fa-plus'></i><?php echo $this->__("Save workpackage"); ?></div>
    </div>
</div>