<?
/* @var $this \ns_c0f2b792_479c_49ad_8e46_34e50f7f4e88\WorkPackages */
?>

<div class='gss_settings_header'>

    <span class="fa-stack fa-lg" style="margin-right: 50px;">
        <i class="fa fa-briefcase fa-stack-1x"></i>
    </span>



    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Create new workpackage"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("Fill out the form below to create a new workpackage.");
            ?>	
        </div>

    </div>	
</div>

<div class='gss_settings_content'>
    <div class="textfield gss_setting"  id="name">
        <span class="title"><?php echo $this->__f("Arbiedspakke"); ?></span>
        <input type="textfield" gs_model='wpmodel' gs_model_attr='name' value="" placeholder="wp">
        <div class="description">
            <?php echo $this->__("Name of the workpackage that owns this new account."); ?>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_fragment="editwp" gss_view="gs_wp_workarea" gss_method="createWorkPackage" gss_model="wpmodel"><i class='fa fa-plus'></i><?php echo $this->__("Create workpackage"); ?></div>
    </div>
</div>