<div class="gs_user_menu">
    <div class="gss_button" gss_fragment='wplist' gss_view='gs_wp_workarea'><i class="fa fa-list"></i><? echo $this->__f("All WP"); ?></div>
    <br/><div class="gss_button" gss_fragment='newwp' gss_view='gs_wp_workarea'><i class="fa fa-plus"></i><? echo $this->__f("New WP"); ?></div>
</div>

<div class="gs_wp_workarea">
    <?
    $this->includefile('wplist');
    ?>
</div>