<?php
/* @var $this \ns_9a6ea395_8dc9_4f27_99c5_87ccc6b5793d\EcommerceOrderList */
$order = $this->getSelectedOrder();
$user = $this->getApi()->getUserManager()->getUserById($order->userId);

echo "<span class='sendpaymentlinkbox dosendbox dontExpand' gstype='form' method='sendEmail'>";
echo "<div style='padding-bottom: 10px;'>";
echo "<i class='fa fa-close closesendpaymentlink' style='float:right;cursor:pointer;'></i>";
echo "Send order / invoice";
echo "</div>";
echo "</span>";  

$app = $this->getApi()->getStoreApplicationPool()->getApplication("d755efca-9e02-4e88-92c2-37a3413f3f41");
$isCompany = $user->companyObject != null && $user->companyObject->vatNumber;

$isInvoice = $order->payment && $order->payment->paymentId == "70ace3f0-3981-11e3-aa6e-0800200c9a66";

if ($app && $isCompany && $isInvoice) {
    $vatnumber = $user->companyObject->vatNumber;
    $vatnumber = str_replace(' ', '', $vatnumber);
    $canUseEhf = $this->getApi()->getGetShop()->canInvoiceOverEhf($vatnumber);
    $ehfValitation = $this->getEhfProblems($order, $user);
    $ehfConfigErrors = $this->getApi()->getOrderManager()->isConfiguredForEhf();
    
    if (count($ehfConfigErrors)) {
        echo "<hr>";
        echo "<b>EHF:</b>";
        echo "<div>";
        echo "This ivoice can not be sent by EHF because you have not configured the invoice settings properly.";
        foreach ($ehfConfigErrors as $error) {
            echo "<div>* $error</div>";
        }
        echo "</div>";
        
    } elseif (!$canUseEhf) {
        echo $this->__f("This company can not receive invoice by EHF.");
    } elseif (count($ehfValitation)) {
        echo "<b>EHF Cant be sent due to:</b>";
        foreach ($ehfValitation as $error) {
            echo "<br/>* ".$error;
        }
    } else {
        $storeSettingsInstance = $this->getFactory()->getApplicationPool()->createInstace($app);

        if (strtolower($storeSettingsInstance->getConfigurationSetting("currencycode")) == "nok") {
            ?>
            <span class='sendpaymentlinkbox dosendbox dontExpand sendehfbox' gstype='form' method='sendByEhf'>
                <div style='padding-bottom: 10px;'>
                    <input type='txt' gsname="vatNumber" value="<?php echo $user->companyObject->vatNumber; ?>" placeholder="Email">
                    <input type='hidden' gsname="bookingid" value="<?php echo $booking->id; ?>">
                    <input type='hidden' gsname="orderid" value="<?php echo $order->id; ?>">
                    <input type="button" gstype='submit' onclick="app.EcommerceOrderList.showSendingEhfMessage()" value='Send EHF' gs_callback='<?php echo $sendEmailCallbackEhf; ?>'>
                    <br/><?
                    echo $this->__f("* Ehf costs Kr 2.50,- pr invoice and you will be billed monthly.");
                    ?>
                </div>
            </span>
            <div class="sendingehf" style="display: none;">
                Sending EHF, please wait...
            </div>
            <?
        }
    }
}
?>