<?
/* @var $this \ns_9a6ea395_8dc9_4f27_99c5_87ccc6b5793d\EcommerceOrderList */

?>

<div gstype='form' method="updateBooking" class="bookingoverview_content_row">
    <input type='hidden' gsname='id' value='<? echo $_POST['data']['id']; ?>'/>
    <input type='hidden' gsname='roomId' value='<? echo $pmsSelectedRoom->pmsBookingRoomId; ?>'/>
   
     
    <div class="menuarea">
        <div class="menuentry <? echo $this->isTabActive('overview'); ?>" tab='overview'><span><? echo $this->__f("Overview"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('orderlines'); ?>" tab='orderlines'><span><? echo $this->__f("Orderlines"); ?></span></div>
        <div class="menuentry <? echo $this->isTabActive('accounting'); ?>" tab='accounting'><span><? echo $this->__f("Accounting"); ?></span></div>
    </div>
    
    <div class="workarea">
 
        <div class="orderinformation <? echo $this->isTabActive('overview'); ?>" tab='overview'>
            <?
            $this->includefile("orderoverview");
            ?>
        </div>
        
        <div class="guestinformation <? echo $this->isTabActive('orderlines'); ?>" tab='orderlines'>
            <? 
            $this->includefile("orderlines");
            ?>
        </div>
        
        <div class="guestinformation <? echo $this->isTabActive('accounting'); ?>" tab='accounting'>
            <? 
            $this->includefile("accounting");
            ?>
        </div>
        
        <div class="bottommenuarea">
            <a href="/?page=groupbooking&bookingEngineId=<? echo $this->bookingEngineBooking->id; ?>">
                <div gstype="submit" class="shop_button" gs_local_update_only="true"><i class="fa fa-chain"></i> <? echo $this->__f("Open group"); ?></div>
            </a>
            <div gstype="submit" class="shop_button disabled" gs_callback="app.PmsSearchBooking.contentSaved" synchron="true"><i class="fa fa-save"></i> <? echo $this->__f("Save"); ?></div>
        </div>
    </div>
</div>
