<div class="page_row row_1">
    <div class="page_row_inner">
        <?php
            ContentManager::render("online_booking_row_1");
        ?>
    </div>
</div>

<div class="page_row row_2 image_left">
    <div class="page_row_inner">
        <?php
            ContentManager::render("online_booking_row_2");
        ?>
    </div>
</div>


<div class="page_row row_3 image_left">
    <div class="page_row_inner">
        <?php
            ContentManager::render("online_booking_row_3");
        ?>
    </div>
</div>

