<?php

namespace ns_deab499e_b133_4cb6_a1b2_532018c31d46;

$taxes = $this->getApi()->getProductManager()->getTaxes();
if (!is_array($taxes)) {
    $taxes = array();
}

/* @var $this \ns_deab499e_b133_4cb6_a1b2_532018c31d46\Taxes */
$numberOfGroups = 5;
?>

<div gstype='form' method='saveTaxes'>
    <div class="gss_settings_header">
        <i class="fa fa-dollar"></i>

        <div class="gss_settings_header_description">
            <div class="gss_settings_header_title"> <? echo $this->__f("Taxes"); ?></div>

            <div class="gss_settings_header_description_inner">
                <? echo $this->getDescription(); ?>
            </div>
        </div>	
    </div>


    <div class='gss_settings_content'>

        <div class="textfield gss_setting" id="title">
            <div class="col1 col title"><?php echo $this->__("Taxgroup") . " $i"; ?></div>
            <div class="col2 col"><? echo $this->__f("Tax rate (%)"); ?></div>
            <div class="col3 col"><? echo $this->__f("Accounting account"); ?></div>
            <div class="col3 col"><? echo $this->__f("Description"); ?></div>
        </div>

        <?
        for ($i=1;$i<=$numberOfGroups;$i++) {
            $arrId = $i-1;
            $groupTax = isset($taxes[$arrId]) ? $taxes[$arrId]->taxRate : "";
            $accountinTaxCode = isset($taxes[$arrId]) ? $taxes[$arrId]->accountingTaxAccount : "";
            $description = isset($taxes[$arrId]) ? $taxes[$arrId]->description : "";
            $default = $i == 1 ? " (". $this->__f("Default").")" : "";
        ?>
            <div class="textfield gss_setting" id="title">
                <div class="col1 col title"><?php echo $this->__("Taxgroup") . " $i ". $default; ?></div>
                <div class="col2 col"><input class='gsniceinput1' type="textfield" gs_model="taxmodel" gsname="group<? echo $arrId; ?>" value="<? echo $groupTax; ?>"></div>
                <div class="col3 col"><input class='gsniceinput1' type="textfield" gs_model="taxmodel" gsname="accounttaxcode<? echo $arrId; ?>" value="<? echo $accountinTaxCode; ?>"></div>
                <div class="col4 col"><input class='gsniceinput1' type="textfield" gs_model="taxmodel" gsname="description<? echo $arrId; ?>" value="<? echo $description; ?>"></div>
            </div>
        <?
        }
        ?>
        
        <div class='gss_button_area'>
            <span class='shop_button' gstype='submit'><i class='fa fa-save'></i> Save taxes setup</span>
        </div>
    </div>
</div>
