<?php
/* @var $factory Factory */
$factory = $this->getFactory();
$themes = $factory->getApplicationPool()->getAllApplicationSettingsByType("ThemeApplication");
echo "<div class='theme_selection_menu'>";
foreach($themes as $index => $theme) {
    $selected = "902cccc1-c315-4a93-8005-d080d414ecee";
    $selectedns = "ns_" . str_replace("-", "_", $selected);
    if($index == 0) {
        $selected = "theme_selection_selected";
    } else {
        $selected = "";
    }
    /* @var $theme core_applicationmanager_ApplicationSettings */
    echo "<span class='theme_selection_button ".$selected."' theme='".$theme->id."'>" . $theme->appName . "</span>";
}
echo "</div>";
?>
<span class='gs_pad_view'></span>
<img class='gs_mac_view' src="/showApplicationImages.php?appNamespace=<? echo $selectedns; ?>&image=desktop.png">
<img class='gs_phone_view' src="/showApplicationImages.php?appNamespace=<? echo $selectedns; ?>&image=mobile.png">
<img class='gs_pad_view' src="/showApplicationImages.php?appNamespace=<? echo $selectedns; ?>&image=pad.png">

<img src="skin/default/initdata/macpad.png" class='gs_macpad'>
<img src="skin/default/initdata/iphone.png" class='gs_iphone'>
<span class="gs_button select_theme_button"><? echo $this->__f("Select this theme"); ?></span>
<span class="example_text"><? echo $this->__f("Preview at :"); ?> http://amandus.getshop.com</span>
