<?
/* @var $this \ns_686d5674_8c58_46a5_b38f_09772c9e5e02\SrsReturantTable */
$reservation = $this->getCurrentReservation();
$data = $this->getApi()->getResturantManager()->getTableDataForReservation($reservation->reservationId);

?>

<div class="shop_button" gs_show_modal="addfood" reservationid="<? echo $reservation->reservationId; ?>">
    <? echo $this->__f("Add food"); ?>
</div>

<?
if (count($data->cartItems)) {
    echo "<div class='shop_button startpaymentprocess' reservationid='".$reservation->reservationId."'>".$this->__f("Start payment process")."</div>";
}

$groupedItems = $this->groupItemsOnPersons($data->cartItems);
foreach ($groupedItems as $personNumber => $cartItems) {
    
    if (!count($cartItems)) {
        continue;
    }
    
    $header = $personNumber == 0 ? $this->__f("General") : $this->__f("Person").": ".$personNumber;
    
    echo "<div>";
        echo "<div class='productHeader'>".$header."</div>";
        echo "<div class='productlist'>";
        $this->printTable($cartItems);
        echo "</div>";
    echo "</div>";
}

?>