<?
/* @var $this \ns_5278fb21_3c0a_4ea1_b282_be1b76896a4b\SedoxDownloadHistory */

$orders = $this->getCurrentOrders();
//echo "<pre>";
//print_r($orders);
//echo "</pre>";
?>

<div class="header">
    <div class="col_header col1">Sedox ID</div>
    <div class="col_header col2">Date</div>
    <div class="col_header col3">File</div>
    <div class="col_header col4">
        <input type="textfield"/>
        <div class="sedox_download"></div>
    </div>
</div>

<div class="tablecontent">
    <?
    foreach ($orders as $order) {
        $product = $this->getApi()->getSedoxProductManager()->getProductById($order->productId);
        $productName = \ns_5278fb21_3c0a_4ea1_b282_be1b76896a4b\SedoxDownloadHistory::createProductName($product);
        
        $time = $this->formatJavaDateToTime($order->dateCreated);
        $date = date("d M Y", $time);
        echo "<div class='col_row_content'>";
            echo "<div class='col_content col1'>$order->productId</div>";
            echo "<div class='col_content col2'>$date</div>";
            echo "<div class='col_content col3'>$productName</div>";
            echo "<div class='col_content col4'>View Product</div>";
        echo "</div>";
    }
    ?>
</div>