//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 07:57:31 PM GMT+01:00 
//


package com.assaabloy.arxdata.access;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AccessCategories_QNAME = new QName("", "access_categories");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccessCategoryType }
     * 
     */
    public AccessCategoryType createAccessCategoryType() {
        return new AccessCategoryType();
    }

    /**
     * Create an instance of {@link DomainType }
     * 
     */
    public DomainType createDomainType() {
        return new DomainType();
    }

    /**
     * Create an instance of {@link AccessCategoryList }
     * 
     */
    public AccessCategoryList createAccessCategoryList() {
        return new AccessCategoryList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessCategoryList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "access_categories")
    public JAXBElement<AccessCategoryList> createAccessCategories(AccessCategoryList value) {
        return new JAXBElement<AccessCategoryList>(_AccessCategories_QNAME, AccessCategoryList.class, null, value);
    }

}
