<?
/* @var $this ns_a5599ed1_60be_43f4_85a6_a09d5318638f\PmsAvailabilityDateSelector */
$app = new \ns_28886d7d_91d6_409a_a455_9351a426bed5\PmsAvailability();
$types = $app->getTypes();
$cats = $app->getCategoryFilter();
?>

<div class="gs_headerbox">
    <div>
        <?
        echo $this->__f("From");
        ?>
    </div>
    
    <input class="gsniceinput1" id="startdate" value="<? echo $this->getStartDate(); ?>"/>
    
    <i class="gsicon-calendar-text"></i>
</div>

<div class="gs_headerbox">
    <div>
        <?
        echo $this->__f("To");
        ?>
    </div>
    
    <input class="gsniceinput1" id="enddate" value="<? echo $this->getEndDate(); ?>"/>
    
    <i class="gsicon-calendar-text"></i>
</div>

<div class="gs_headerbox">
    <div>
        <?
        echo $this->__f("Sorting");
        ?>
    </div>
    
    <select id='sorting'>
        <option value='category'>By category</option>
        <option value='room' <?php if($app->getSortType() == "room") { echo "selected"; }?>>By room</option>
    </select>
</div>
<i class="fa fa-ban" style='margin-right:25px; cursor:pointer;' onclick='$(".closeforperiodebox").toggle();'></i>
<div>
    <div gstype='form' method='closeForPeriode' class='closeforperiodebox' style='position:Absolute; width: 500px; text-align: left;z-index:2;background-color:#fff; border: solid 1px #bbb; padding: 10px;right:25px; display:none;'>
        <div>Sometimes it comes in handy to close down the hotel for a given timeframe. For example you need to do restructuring of all bookings, to avoid more bookings you can close the hotel for new bookings meanwhile</div>
        <input type='txt' class='startdate gsniceinput1' gsname='start' value='<? echo $this->getStartDate(); ?>' style='width:80px;'>
        <input type='txt' class='enddate gsniceinput1' gsname='end' value='<? echo $this->getEndDate(); ?>' style='width:80px;'>
        <span class="shop_button" gstype="submit">Close hotel for periode</span>
    </div>
</div>

<div style='font-size: 12px;padding-top:5px;'>
    <?php
    foreach($types as $type) {
        $checked = "";
        if(in_array($type->id, $cats)) {
            $checked = "CHECKED";
        }
        echo "<span style='margin-right:20px;margin-top:5px;'><input type='checkbox' class='typesinput' typeid='".$type->id."' $checked>" . $type->name . "</span>";
    }
    echo "<input type='button' value='Update' style='cursor:pointer;' class='updateavailability'>";
    ?>
</div>

<script>
    $('#startdate').datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            var curEnd = moment($('#enddate').val(), "DD.MM.YYYY");
            var date = moment(dateText, "DD.MM.YYYY");
            
            var diff = curEnd.valueOf() - date.valueOf();
            if(diff <= 0) {
                date.add(7, 'days');
                $('#enddate').val(date.format('DD.MM.YYYY')); 
            }
//            app.PmsAvailabilityDateSelector.changed();
        }
    });
    $('#enddate').datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            var curStart = moment($('#startdate').val(), "DD.MM.YYYY");
            var date = moment(dateText, "DD.MM.YYYY");
            
            var diff = date.valueOf() - curStart.valueOf();
            if(diff <= 0) {
                date.add(-7, 'days');
                $('#startdate').val(date.format('DD.MM.YYYY')); 
            }
//            app.PmsAvailabilityDateSelector.changed();
        }
    });
</script>