<?
/* @var $this ns_a5599ed1_60be_43f4_85a6_a09d5318638f\PmsAvailabilityDateSelector */
?>

<div class="gs_headerbox">
    <div>
        <?
        echo $this->__f("From");
        ?>
    </div>
    
    <input class="gsniceinput1" id="startdate" value="<? echo $this->getStartDate(); ?>"/>
    
    <i class="icon-calendar-text"></i>
</div>

<div class="gs_headerbox">
    <div>
        <?
        echo $this->__f("To");
        ?>
    </div>
    
    <input class="gsniceinput1" id="enddate" value="<? echo $this->getEndDate(); ?>"/>
    
    <i class="icon-calendar-text"></i>
</div>

<div class="gs_headerbox">
    <div>
        <?
        echo $this->__f("Room");
        ?>
    </div>
    
    <select>
        <option>All</option>
    </select>
    
</div>

<script>
    $('#startdate').datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            var curEnd = moment($('#enddate').val(), "DD.MM.YYYY");
            var date = moment(dateText, "DD.MM.YYYY");
            
            var diff = curEnd.valueOf() - date.valueOf();
            if(diff <= 0) {
                date.add(7, 'days');
                $('#enddate').val(date.format('DD.MM.YYYY')); 
            }
        }
    });
    $('#enddate').datepicker({dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true,
        onSelect: function(dateText) {
            var curStart = moment($('#startdate').val(), "DD.MM.YYYY");
            var date = moment(dateText, "DD.MM.YYYY");
            
            var diff = date.valueOf() - curStart.valueOf();
            if(diff <= 0) {
                date.add(-7, 'days');
                $('#startdate').val(date.format('DD.MM.YYYY')); 
            }
        }
    });
</script>