<div class="page_row row_1 row_with_image">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_intro");
        ?>
    </div>
</div>

<div class="page_row row_2 image_left">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_floating");
        ?>
    </div>
</div>

<div class="page_row row_3 image_right">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_pricing");
        ?>
    </div>
</div>

<div class="page_row row_4 fullwidth">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_bookings");
        ?>
    </div>
</div>

<div class="page_row row_5 image_left">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_guestmanagement");
        ?>
    </div>
</div>

<div class="page_row row_6 image_right">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_guest_stay");
        ?>
    </div>
</div>

<div class="page_row row_7 image_left">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_addons");
        ?>
    </div>
</div>

<div class="page_row row_9 image_right">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_accesscodes");
        ?>
    </div>
</div>

<div class="page_row row_10 fullwidth">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_payment");
        ?>
    </div>
</div>

<div class="page_row row_11 image_right">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_reports");
        ?>
    </div>
</div>

<div class="page_row row_8 fullwidth">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pms_top");
        ?>
    </div>
</div>

