<?
/* @var $this \ns_b3f563f6_2408_4989_8499_beabaad36574\ScormList */
//
if ($this->isCompanySelected()) {
    echo $this->__w("Company does not have scorm packages, please select a user instead.");
    return;
}

$scorms = $this->getApi()->getScormManager()->getMyScorm($this->getUserId());
if (!$scorms)
    return;

?>
<div class="scormrow">
    <div><? echo $this->__f("Name"); ?></div>
    <div><? echo $this->__f("Score"); ?></div>
    <div><? echo $this->__f("Completed"); ?></div>
    <div><? echo $this->__f("Link"); ?></div>
</div>

<?
foreach ($scorms as $scorm) {
    $this->printRow($scorm);

    if ($scorm->groupedScormPackage) {
        foreach ($scorm->groupedScormPackageIds as $id) {
            $iScorm = $this->getApi()->getScormManager()->getScormForCurrentUser($id, $this->getUserId());
            $this->printRow($iScorm, true);
        }
    }
    
}
?>