<div style='padding: 30px;'>
    <table>
        <tr><td><? echo $this->__f("Candidate name"); ?></td><td><input type='textfield' id='new_subuser_name'/></td></tr>
        <tr><td><? echo $this->__f("Cellphone"); ?></td><td><input type='textfield' id='new_subuser_cellphone'/></td></tr>
        <tr><td colspan='2' align='right' ><div leaderId='<? echo $_POST["data"]['leaderId']; ?>' class='gs_button createButton_subuser_admin'><? echo $this->__("Create user"); ?></div></td></tr>
    </table>
</div>