<?
namespace ns_ba6f5e74_87c7_4825_9606_f2d3c93d292f;
/* @var $this ns_6c245631_effb_4fe2_abf7_f44c57cb6c5b\Account */

?>

<div class="overview inline">
    <div class="section_user">
        <b class="heading">Edit user details</b>
    </div>
    <div class="personal_information">
        <?php
        $this->includefile("RegistrationForm", "Account");
        ?>
    </div>
    <br>
    <br>
    
    <div class="change_passord">
        <?php
        $this->includefile("accountPages/password", "Account");
        ?>
    </div>
    <div class="application_permission_overview">
        <?php
        $this->includefile("accountPages/applicationpermissions", "Account");
        ?>
    </div>
    <div class="orders_madeby_user">
        <?php
        $this->includefile("accountPages/ordersmade", "Account");
        ?>
    </div>
    <div class="comments_on_user">
        <?php
        $this->includefile("accountPages/commentsonuser", "Account");
        ?>
    </div>
    <div class="comments_on_user">
        <?php
        $this->includefile("accountPages/parentoverview", "Account");
        ?>
    </div>
    <?
    if ($this->getFactory()->getStore()->id == "d27d81b9-52e9-4508-8f4c-afffa2458488") {
    ?>
    
        <div class="scoresettings">
            <?php
            $this->includefile("accountPages/scoresettings", "Account");
            ?>
        </div>
    <? } ?>
</div>

