<div class='gss_settings_header'>

    <span class="fa-stack fa-lg" style="margin-right: 20px;">
        <i class="fa fa-user fa-stack-1x"></i>
        <i style="color: #FFF; font-size: 15px; line-height: 60px; padding-left: 1px;" class="fa fa-plus fa-stack-2x"></i>
    </span>



    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Create new user"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("Fill out the form below to create a new user.");
            ?>	
        </div>

    </div>	
</div>

<div class='gss_settings_content'>
    <div class="textfield gss_setting"  id="name">
        <span class="title"><?php echo $this->__f("Name"); ?></span>
        <input type="textfield" gs_model='usermodel' gs_model_attr='name' value="" placeholder="John Doe">
        <div class="description">
            <?php echo $this->__("Name of the person that owns this new account."); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="email">
        <span class="title"><?php echo $this->__f("Mail address"); ?></span>
        <input type="textfield" gs_model='usermodel' gs_model_attr='email' value="" placeholder="email@address.org">
        <div class="description">
            <?php echo $this->__("Email address."); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="phone">
        <span class="title"><?php echo $this->__f("Phone number"); ?></span>
        <input type="textfield" gs_model='usermodel' gs_model_attr='phone_number' value="" placeholder='123456798'>
        <div class="description">
            <?php echo $this->__("The cell phone number to the owner of this account."); ?>
        </div>
    </div>

    <div class="textfield gss_setting" style="height: 38px;">
        <div class="gss_button" id="autogeneratepassword" style="position: absolute; right: 14px; width: 262px;"><? echo $this->__f("Click to autogenerate password"); ?></div>
    </div>
    
    <div class="textfield gss_setting"  id="password1">
        <span class="title"><?php echo $this->__f("Password"); ?></span>
        <input id='gss_new_user_password1' type="password" gs_model='usermodel' gs_model_attr='password1' value="" placeholder="*******">
        <div class="description">
            <?php echo $this->__("Please enter the accounts password."); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="password2">
        <span class="title"><?php echo $this->__f("Repeat password password"); ?></span>
        <input id='gss_new_user_password2' type="password" gs_model='usermodel' gs_model_attr='password2' value="" placeholder="*******">
        <div class="description">
            <?php echo $this->__("Make sure that the password you wrote above is the correct."); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="admin">
        <span class="title"><?php echo $this->__f("Administrator"); ?></span>
        <div class="gss_onoff" gs_model="usermodel" gs_model_attr="isadmin">
            Off<i class="fa fa-toggle-off"></i>On
        </div>
        <div class="description">
            <?php echo $this->__("Is this an administrator account"); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="editor">
        <span class="title"><?php echo $this->__f("Editor"); ?></span>
        <div class="gss_onoff" gs_model="usermodel" gs_model_attr="iseditor">
            Off<i class="fa fa-toggle-off"></i>On
        </div>
        <div class="description">
            <?php echo $this->__("Is this an editor account?"); ?>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_pre_post="validatePassword" gss_fragment="user" gss_view="gs_user_workarea" gss_method="createUser" gss_model="usermodel"><i class='fa fa-plus'></i><?php echo $this->__("Create account"); ?></div>
    </div>

</div>