<div class="gs_user_menu">
    <div class="gss_button" gss_fragment='userlist' gss_view='gs_user_workarea'><i class="fa fa-list"></i><? echo $this->__f("All users"); ?></div>
    <br/><div class="gss_button" gss_fragment='newuser' gss_view='gs_user_workarea'><i class="fa fa-plus"></i><? echo $this->__f("New user"); ?></div>
</div>

<div class="gs_user_workarea">
    <?
    $this->includefile('userlist');
    ?>
</div>