<?php
$users = $this->getAllUsers();
if(!count($users)) {
    echo $this->__f("No users found");
    return;
}
foreach ($users as $user) { 
    $id = $user->id;
    $admin = ($user->type == 100) ? "admin" : "";
?>
<a href="?page=users_all_users&userid=<?echo $id;?>">
    <div class="user <? echo $admin; ?>">
        <div class="inline image">

        </div>
        <div class="inline info">
            <? echo $user->fullName; ?>
            <br><? echo $user->emailAddress; ?>
            <br><? echo $user->cellPhone; ?>
            <?
            if ($user->company) {
                 echo "<br>".$user->company->name; 
            }
            ?>
            
        </div>
        <div class="inline address">
            <? echo "<b>".$this->__f("Address").":</b>";
            if ($user->address) { 
               echo "<br>".$user->address->address; 
               echo "<br>".$user->address->postCode." ".$user->address->city;
            } else {
                echo "<br>No address information available";
            }
            ?>
        </div>
        
        <?
        if ($user->isMaster) {
            ?>
            <div class='showIsMaster'>
                <i class='fa fa-star' title='this user is a masteruser'></i>
            </div>
            <?
        }
        ?>
    </div>
</a>
<? } ?>
