<?
/* @var $this \ns_ba6f5e74_87c7_4825_9606_f2d3c93d292f\Users */


$searchtext = $this->getSearchText();
?>

<div class='gss_settings_header'>
    <i class='fa fa-info'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Userlist"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
                echo $this->__f("Below you see a list of all users registered in this system. To see more information about a user you can simply click on it.").".";
            ?>	
        </div>
    </div>	
</div>

<div class="gss_settings_header">
    <i class="fa fa-search"></i>

    <div class="gss_settings_header_description" >
        <div class="gss_settings_header_title"><? echo $this->__f("Search (leave blank to see all)"); ?></div>
        <div class="gss_settings_header_description_inner" style="position: relative; width: 868px;">
            <input id='gss_order_filter_search_text' gs_model='orders' gs_model_attr='order_filter' type="textfield" style="left: 0px; top: 0px;" placeholder="<? echo $this->__f("Filter users"); ?>" value='<? echo $searchtext; ?>'/>
            <input id='gss_order_filter_startdate' gs_model='orders' gs_model_attr='start_date' type="textfield" style="left: 300px; top: 0px; width: 100px;" placeholder="<? echo $this->__f("From"); ?>" value=''/>
            <input id='gss_order_filter_enddate' gs_model='orders' gs_model_attr='end_date' type="textfield" style="left: 420px; top: 0px; width: 100px;" placeholder="<? echo $this->__f("To"); ?>" value=''/>

            <div class="gss_dropdown" style='top: 1px; right: 116px; width: 200px;'>
                <select class="config" gs_model='orders' gs_model_attr='status'>
                    <? 
                    $languages = array();
                    $languages['0'] = "ALL";
                    $languages['10'] = "Customers";
                    $languages['50'] = "Editor";
                    $languages['100'] = "Admin";
                    
                    foreach ($languages as $key => $lang) { 
                        $selected = $this->getFactory()->getMainLanguage() == $key ? "selected='true'" : "";
                        ?>
                        <option <? echo $selected; ?> value="<? echo $key; ?>"><? echo $lang; ?></option>
                    <? } ?>
                </select>
            </div>
            <div id='gss_order_filter_search_button' gss_method='filterOrders' gss_view='gss_outer_searchresult' gss_fragment='searchresult' gss_model='orders' style='position: absolute; right: 0px;height: 11px;line-height: 11px;top: 2px;' class='gss_button'><? echo $this->__f("Search"); ?></div>
        </div>
    </div>	
</div>

<div class='gss_outer_searchresult gss_settings_content'>
    <? $this->includefile("searchresult"); ?>
</div>    


<script>
    $('#gss_order_filter_startdate').datepicker({ dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true });
    $('#gss_order_filter_enddate').datepicker({ dateFormat: "yy-mm-dd",changeMonth: true, changeYear: true });        
</script>