<?
/* @var $this \ns_ba6f5e74_87c7_4825_9606_f2d3c93d292f\Users */

$users = $this->getApi()->getUserManager()->getAllUsers();
?>

<div class='gss_settings_header'>
	<i class='fa fa-info'></i>

	<div class='gss_settings_header_description'>
		<div class='gss_settings_header_title'>
			<? echo $this->__f("Userlist"); ?>
		</div>
		<div class='gss_settings_header_description_inner'>
			<?
			echo $this->__f("Below you see a list of all users registered in this system. To see more information about a user you can simply click on it.").".";
			?>	
		</div>
	</div>	
</div>


<div class='gss_settings_content'>

    <?
    foreach ($users as $user) {
        $name = $user->fullName;
        $email = $user->emailAddress;
        $phone = $user->cellPhone;
        $created = $user->rowCreatedDate;
        $icon = "fa-user on fa-gears";
        $id = $user->id;
        ?>
        <div class='user_entry_row' gss_fragment="user" gss_view="gs_user_workarea" gss_value="<? echo $id; ?>">
            <div class="image">
                <span class="fa-stack fa-lg">
                    <? if ($user->type === 100) { ?>
                        <i style="color: #f35858;" class="fa fa-user fa-stack-1x"></i>
                        <i style="color: #FFF; font-size: 12px; line-height: 50px; width: 85px;" class="fa fa-circle-o fa-stack-2x"></i>
                        <i style="color: #FFF; font-size: 12px; line-height: 50px; width: 115px;" class="fa fa-circle-o fa-stack-2x"></i>
                        <i style="color: #FFF; font-size: 25px; line-height: 142px; width: 101px;" class="fa fa-power-off fa-stack-2x"></i>
                    <? } else if ($user->type === 50) { ?>
                        <i style="color: #d5bf2b;" class="fa fa-user fa-stack-1x"></i>
                        <i style="color: #FFF; font-size: 12px; line-height: 50px; width: 85px;" class="fa fa-circle-o fa-stack-2x"></i>
                        <i style="color: #FFF; font-size: 12px; line-height: 50px; width: 115px;" class="fa fa-circle-o fa-stack-2x"></i>
                        <i style="color: #FFF; font-size: 25px; line-height: 142px; width: 101px;" class="fa fa-flash fa-stack-2x"></i>
                    <? } else { ?>
                        <i style="color: #2ac32a;" class="fa fa-user fa-stack-1x"></i>
                        <i style="color: #FFF; font-size: 12px; line-height: 50px; width: 85px;" class="fa fa-circle-o fa-stack-2x"></i>
                        <i style="color: #FFF; font-size: 12px; line-height: 50px; width: 115px;" class="fa fa-circle-o fa-stack-2x"></i>
                    <? } ?>
                </span>
                
                <div class="user_level">
                    <? if ($user->type === 100) { 
                        echo $this->__f("Admin");
                    } else if ($user->type === 50) {
                        echo $this->__f("Editor");
                    } else {
                        echo $this->__f("Customer");
                    }
                    ?>    
                </div>
            </div>

            <div class="content">
                <div class="name"><? echo $name; ?></div>
                <div class="email"> <? echo $email; ?></div>
                <div class="phone"><? echo $phone; ?></div>
                <div class="created"><? echo $created; ?></div>
            </div>
        </div>
        <?
    }
    ?>

</div>