<div class="contentrow row_width_degreed"> 
    <div class="row_inner">
        <div class="col col_1 col_size_2">
            <img  onclick='showGallary("apartment")' src="https://20490gc6.getshop.com/displayImage.php?id=b1a800c4-08dc-45ea-af7e-f15b75bfd48c" style="width: 100%; border-radius: 10px;"/>
        </div>
        <div class="col col_2 col_size_2">
            <?php
                ContentManager::render("row_2_room_1");
            ?>
        </div>
    </div>
</div>

<div class="contentrow "> 
    <div class="row_inner">
        <div class="col col_1 col_size_2">
            <img  onclick='showGallary("studioapartment")' src="https://20490gc6.getshop.com/displayImage.php?id=a11036ac-ea6a-4d23-ab40-cafb2491c058" style="width: 100%; border-radius: 10px;"/>
        </div>
        <div class="col col_2 col_size_2">
            <?php
                ContentManager::render("row_3_room_1");
            ?>
        </div>
    </div>
</div>

<div class="contentrow row_width_degreed_reversed"> 
    <div class="row_inner">
        <div class="col col_1 col_size_2">
            <img  onclick='showGallary("anneks")' src="https://20490gc6.getshop.com/displayImage.php?id=c991dc5e-4248-4012-b154-b2d63a62e291" style="width: 100%; border-radius: 10px;"/>
        </div>
        <div class="col col_2 col_size_2">
            <?php
                ContentManager::render("row_4_room_1");
            ?>
        </div>
    </div>
</div>

<script>
    function showGallary(t) {
        var pswpElement = document.querySelectorAll('.pswp')[0];

        // build items array
        var items = [
            {
                src: 'https://20490gc6.getshop.com/displayImage.php?id=b1a800c4-08dc-45ea-af7e-f15b75bfd48c',
                w: 1600,
                h: 900
            },
            {
                src: 'https://20490gc6.getshop.com/displayImage.php?id=22d76132-5117-45a8-af32-9d708495d40b',
                w: 1388,
                h: 753
            }
        ];

        if (t == "studioapartment") {
            var items = [
            {
                src: 'https://20490gc6.getshop.com/displayImage.php?id=a11036ac-ea6a-4d23-ab40-cafb2491c058',
                w: 1200,
                h: 900
            },
            {
                src: 'https://20490gc6.getshop.com/displayImage.php?id=9e25ad98-e4d4-4136-ace6-c01ec5d09807',
                w: 1600,
                h: 900
            }
        ];
        }

        if (t == "anneks") {
            var items = [
            {
                src: 'https://20490gc6.getshop.com/displayImage.php?id=c991dc5e-4248-4012-b154-b2d63a62e291',
                w: 1600,
                h: 900
            }
        ];
        }
        // define options (if needed)
        var options = {
            // optionName: 'option value'
            // for example:
            index: 0 // start at first slide
        };

        // Initializes and opens PhotoSwipe
        var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
        gallery.init();
    }
</script>