<div class='gss_settings_header'>

    <span class="fa-stack fa-lg" style="margin-right: 40px;">
        <i class="fa fa-users fa-stack-1x"></i>
        <i style="color: #FFF; font-size: 15px; line-height: 60px; padding-left: 8px; top: 3px;" class="fa fa-plus fa-stack-2x"></i>
    </span>



    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Create new group"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->__f("Fill out the form below to create a new group.");
            ?>	
        </div>

    </div>	
</div>

<div class='gss_settings_content'>
    <div class="textfield gss_setting"  id="name">
        <span class="title"><?php echo $this->__f("Name"); ?></span>
        <input type="textfield" gs_model='groupmodel' gs_model_attr='name' value="" placeholder="Group name">
        <div class="description">
            <?php echo $this->__("Name of the group."); ?>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_fragment="group" gss_view="gs_user_workarea" gss_method="createGroup" gss_model="groupmodel"><i class='fa fa-plus'></i><?php echo $this->__("Create group"); ?></div>
    </div>

</div>