<?
/* @var $this ns_3983a370_d0cc_46de_ba94_cc22fe7becbb\UserGroups */
$users = $this->getApi()->getUserManager()->getUsersBasedOnGroupId($_POST['value']);


    
if (!count($users)) {
    echo "<div style='padding: 20px;'><i class='fa fa-warning'></i> No users has been added to this group</div>";
} else {
    echo "<center><h3>".$this->__f("Click on user to remove.")."</center></h3s>";
    foreach ($users as $user) {
        
        echo "<div gss_method='removeUserFromGroup' gss_value_2='$user->id' gss_value='".$_POST['value']."' gss_fragment='usersingroup' gss_view='gss_users_in_group' class='gs_select_searched_user_group_add'>$user->fullName ($user->emailAddress) - $user->cellPhone</div>";
        
    }
}
?>