<?
/* @var $this ns_b6143df9_a5cd_424c_9f17_8e24616b2c3f\ZReport */
$payments = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
$orders = $this->getOrders();

?>

<div gstype="form" method="showReport">
    <div class="col1">Dato/tid: </div><input type="textfield" class="gsniceinput1" gsname="from" id="from" value="<? echo @$_POST['data']['from']; ?>"/> - <input type="textfield" class="gsniceinput1" id="to" gsname="to" value="<? echo @$_POST['data']['to']; ?>"/>
    <br/>
    <br/><div class="col1">User: </div><select gsname="userid" class="gsniceselect1">
        <option value="">All</option>
        <?
        $admins = $this->getApi()->getUserManager()->getUsersByType(100);
        foreach ($admins as $admin) {
            $selected = $_POST['data']['userid'] == $admin->id ? "selected='true'" : "";
            echo "<option $selected value='$admin->id'>$admin->fullName</option>";
        }
        ?>
    </select>

    <br/><div class="col1">Payment type:</div><select gsname="paymentid" class="gsniceselect1">
        <option value="">All</option>
        <?
        foreach ($payments as $payment) {
            $paymentMethodName = $this->getFactory()->convertUUIDtoString($payment->id)."\\".$payment->appName;
            $selected = $_POST['data']['paymentid'] == $paymentMethodName ? "selected='true'" : "";
            echo "<option $selected value='$paymentMethodName'>$payment->appName</option>";
        }
        ?>
    </select>

    <br/>
    <br/><div class="shop_button" gstype="submit">Show</div>

</div>

<script>
    $('#from').datetimepicker();
    $('#to').datetimepicker();
</script>
  
<?
if (!$orders) {
    return;
}
?>

<div>
    <br/>
    <table width='100%;'>
    <?
    
    
    $sum = 0;
    foreach ($orders as $order) {
        foreach ($order->payment->transactionLog as $time => $text) {
        }
        
        $readableTime = date("Y-m-d H:i", strtotime($order->paymentDate));
        $total = $this->getApi()->getOrderManager()->getTotalAmount($order);
        $sum += $total; 
        
        echo "<tr><td width='100'>".$readableTime . "</td><td width='50'>$order->incrementOrderId</td><td style='text-align: left;'></td><td width='100'>$total</td></tr>";
      
    }
    
    echo "<tr><td width='150'></td><td></td><td style='text-align: left;'>Total</td><td width='100'>$sum</td></tr>";
    ?>
    </table>
    
    <?
    if (isset($_POST['data']['paymentid']) && $_POST['data']['paymentid'] && !$_POST['data']['userid'] && "a" == "b") { ?>
        <div class="shop_button" gsclick="closePeriode">Close periode</div>
    <?
    }
    ?>
</div>

<div class="summary_bottom">
    <h2>Summary based on products.</h2>
    <?
    $groupedItems = $this->groupByProduct($orders);
    echo "<table cellspacing='0' cellpadding='0' width='100%'>";
    echo "<tr><td>Product</td><td>Ex taxes</td><td>Inc taxes</td></tr>";
    $totex = 0;
    $totinc = 0;
    foreach ($groupedItems as $productId => $items) {    
        $exPrice = 0;
        $price = 0;
        $product = null;

        foreach ($items as $item) {
            /* @var $item core_cartmanager_data_CartItem */
            $count = $item->count;
            if (!isset($item->product->priceExTaxes) || !$item->product->price) {
                continue;
            }
            $product = $item->product;
            $exPrice += $item->product->priceExTaxes*$count;
            $price += $item->product->price*$count;
        }
        if (!$product)
            continue;
        
        $totex += $exPrice;
        $totinc += $price;
        echo "<tr><td>$product->name</td><td>".round($exPrice,2)."</td><td>".round($price,2)."</td></tr>";
    }
    echo "<tr><td>Total</td><td>".round($totex,2)."</td><td>".round($totinc,2)."</td></tr>";
    echo "</table>";
    ?>
</div>