<? namespace ns_de0b9b83_a41d_4fca_a2d4_3d3945cc8b9e; ?>
<div class="header">
    <? echo $this->__w("Related products"); ?>
</div>

<?php
$products = (array)$this->products;
foreach ($products as $product):
/* @var $product core_productmanager_data_Product */
    reset($product->images);
    $productLink = \ProductHelper::findMainImageId($product);
?>
<a href="?page=<?php echo $product->page->id;?>">
    <div class="entry" productId="<?echo $product->id; ?>">
        <div class="title"><? echo $product->name; ?></div>
        <? if($productLink) { ?>
            <div class="image"><img src="displayImage.php?id=<? echo $productLink; ?>"/></div>
            <? } else { ?>
            <div class="image"><span class="no_image"><span class="inner">No image added for this product</span></span></div>
        <? } ?>
        <div class="price"><?php echo $this->getFactory()->getCurrencyName(); ?> <? echo $product->price; ?>,-</div>
    </div>
</a>

<? endforeach; ?>
