<div class="assistrow">
    <i class="fa fa-minus"></i> <input id="assist_days" type="number" value="5"/> <i class="fa fa-plus"></i> 
    <div class="subinfo">Arbeidstimer i uken</div>
</div>

<div class="assistrow">
    <i class="fa fa-minus"></i> <input id="assist_hours" type="number" value="1"/> <i class="fa fa-plus"></i> 
    <div class="subinfo">Antall stasjoner</div>
</div>

<div class="assistrow">
    <input type="number" value="360" id="assist_hourprice"/> 
    <div class="subinfo" >Timelønn</div>
</div>

<div class="saving_summary">
    
    <span class="assist_total_hours">720</span> timer i året!

    <div class="total_price">
        <span class="price_sum">259200</span>,- Kr    
    </div>

</div>
