<div class="assistrow">
    <i class="fa fa-minus"></i> <input id="assist_days" type="text" value="5"/> <i class="fa fa-plus"></i> 
    <div class="subinfo">Arbeidsdager/uke</div>
</div>

<div class="assistrow">
    <i class="fa fa-minus"></i> <input id="assist_hours" type="text" value="1"/> <i class="fa fa-plus"></i> 
    <div class="subinfo">Antall testere</div>
</div>

<div class="assistrow lastchild">
    <input type="text" value="800" id="assist_hourprice"/> 
    <div class="subinfo" >Timelønn</div>
</div>

<div class="saving_summary">
    
    <span class="assist_total_hours">240</span> timer i året!

    <div class="total_price">
        <span class="price_sum">192000</span>,- Kr    
    </div>

</div>
