package com.thundashop.app.logo;

import com.thundashop.app.logomanager.data.SavedLogo;
import com.thundashop.core.common.Administrator;
import com.thundashop.core.common.ErrorException;
import com.thundashop.core.common.GetShopApi;

/**
 * A good webshop allways need a logo, and that is exactly what this does.<br>
 * This manager helps you remember / store the id of the logo for your webshop instance. <br>
 */
@GetShopApi
public interface ILogoManager {
    /**
     * Set a logo to your webshop.
     * @param fileId The file id generated by the one storing this.
     * @return 
     * @throws ErrorException 
     */
    @Administrator
    public void setLogo(String fileId) throws ErrorException;
    
    /**
     * Remove the current logo.
     * @return
     * @throws ErrorException 
     */
    @Administrator
    public void deleteLogo() throws ErrorException;
    
    /**
     * Get the logo file id.
     * @return
     * @throws ErrorException 
     */
    public SavedLogo getLogo() throws ErrorException;
}
