<?php
/* @var $this ns_cbcf3e53_c035_43c2_a1ca_c267b4a8180f\PmsGroupBookingHeader */
$booking = $this->getCurrentBooking();
$start = null;
$end = null;
foreach($booking->rooms as $room) {
    if(!$start  || strtotime($room->date->start) < $start) { $start = strtotime($room->date->start); }
    if(!$end  || strtotime($room->date->end) > $end) { $end = strtotime($room->date->end); }
}
?>
<i class='fa fa-close' style='float:right;cursor:pointer;' onclick='$(".addAddonsPanel").hide();'></i>
<center>
    <h3>Addons possible to add to this group</h3>
</center>


<div class="addaddonrows step1">
    <input type='text' class='gsniceinput1 searchaddaddonslist' placeholder='Search addons' style='width:100%; box-sizing: border-box; margin-bottom: 10px;'>
    
    <div>
        <span style='float:right;'>
            <input type='txt' gsname='start' class='gsniceinput1' value='<?php echo date("d.m.Y", $start); ?>' style='width:80px; text-align: center;'>
            <input type='txt' gsname='end' class='gsniceinput1' value='<?php echo date("d.m.Y", $end); ?>' style='width:80px; text-align: center;'>
        </span>
        <input type='checkbox' class='setsingleday' gsname='singleday'>Single day
    </div>
    <div style='clear:both;height: 20px;'></div>
    <?php
    /* @var $this ns_7ca01dc3_49e7_4bad_a0f9_4f1eae1199d6\PmsAddonSelection */
    $types = $this->getApi()->getBookingEngine()->getBookingItemTypes($this->getSelectedMultilevelDomainName());
    $productsToExclude = array();
    foreach($types as $type) {
        $productsToExclude[] = $type->productId;
    }
    
    $config = $this->getApi()->getPmsManager()->getConfiguration($this->getSelectedMultilevelDomainName());
    $addonsConfigList = array();
    foreach($config->addonConfiguration as $id => $item) {
        $addonsConfigList[$item->productId] = "";
    }
    $addonsConfigList = array_keys($addonsConfigList);
    
    
    $found = false;
    $products = $this->getApi()->getProductManager()->getAllProducts();
    $newproducts = array();
    foreach($products as $prod) {
        $newproducts[$prod->name] = $prod;
    }
    ksort($newproducts);
    
    foreach($newproducts as $product) {
        if(in_array($product->id, $productsToExclude)) {
            continue;
        }
        if(!in_array($product->id, $addonsConfigList)) {
            continue;
        }
        $found = true;
        echo "<div class='addonsrow'>" . $product->name;
        echo "<span class='shop_button removeAddonFromRoom' style='background-color:red;' productid='".$product->id."' quickadd='$quickadd' type='removeaddon'>Remove</span>";
        echo "<span class='shop_button addAddonsToRoom' productid='".$product->id."' quickadd='$quickadd' type='addaddon'>Add</span>";
        echo "</div>";
    }
    if(!$found) {
        echo "<div style='padding: 10px;'>No addons has been created yet<br>Go to settings -> Products / Addons to set up addons.</div>";
    }
    ?>
</div>



<div class="addaddonrows step2">
    
</div>
