<?php
/* @var $this \ns_cbcf3e53_c035_43c2_a1ca_c267b4a8180f\PmsGroupBookingHeader */
$booking = $this->getCurrentBooking();
$startDate = null;
foreach($booking->rooms as $room) {
    if($startDate == null || strtotime($room->date->start) < $startDate) {
        $startDate = strtotime($room->date->start);
    }
}
?>
<h1>Conference rooms</h1>
 <div class="kaipal infobox">
        // faces: happy,sad,talking,danger
        <div class="image sad"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("I am ready to welcome the guest"); ?></div>
            <div class="text">
                <?
                echo $this->__f("You do not have any conference rooms registered yet, go to room configuration and add your first conference room.");
                ?>    
            </div>
        </div>
    </div>

<h1>Action points</h1>
<div gstype='form' method='addactionpoint'>
    <input type='hidden' gsname='bookingid' value='<?php echo $this->getCurrentBooking()->id; ?>'>
    <input type='text' gsname='date' class='gsniceinput1' value="<?php echo date("d.m.Y", $startDate); ?>">
    <input type='text' gsname='where' class='gsniceinput1' placeholder="Location">
    <input type='text' gsname='from' class='gsniceinput1' placeholder="Start hour" style='width:70px;'>
    <input type='text' gsname='to' class='gsniceinput1' placeholder="End hour" style='width:70px;'>
    <input type='text' gsname='size' class='gsniceinput1' placeholder="Guests" style='width:50px;'>
    <input type='text' gsname='name' class='gsniceinput1' placeholder="Name" style='width: 300px;'>
    <span class='shop_button' gstype='submit'>Add action point</span>
</div>
<div>
    <div>* Start hour : When does this event start?</div>
    <div>* End hour : When does this event end?</div>
    <div>* Guests : The number of guests for this action point for example: dinner between 14 - 16 guests: 16, 16 guests</div>
</div>
<br>

<?php
$confdata = $this->getApi()->getPmsManager()->getConferenceData($this->getSelectedMultilevelDomainName(), $this->getCurrentBooking()->id);
if(!$confdata->days || sizeof($confdata->days) == 0) {
    echo "<h2>Start setting up your conference by adding action points above.</h2>";
}
foreach($confdata->days as $day) {
    echo "<b>" . $day->day . "</b><br>";
    ?>
    <span style='width: 190px; display:inline-block; padding-left: 40px;'>Location</span>
    <span style='width: 75px; display:inline-block;'>Starting</span>
    <span style='width: 75px; display:inline-block;'>Ending</span>
    <span style='width: 70px; display:inline-block;'>Size</span>
    <span>Name</span>

    <?php
    foreach($day->conferences as $conf) {
        ?>
        <div style='margin-bottom: 5px;' gstype='form' method='updateActionPoint'>
            <span class='shop_button' style='margin-right: 2px;' gstype='clicksubmit' gsvalue='<?php echo $conf->rowId; ?>' gs_confirm='Are you sure?' gsname='id' method='removeRow'>
                <i class='fa fa-trash-o' gsvalue='<?php echo $conf->rowId; ?>' gs_confirm='Are you sure?' gsname='id' method='removeRow'></i></span>
            <input type='hidden' gsname='bookingid' value='<?php echo $this->getCurrentBooking()->id; ?>'>
            <input type='hidden' gsname='rowid' value='<?php echo $conf->rowId; ?>'>
            <input type='text' gsname='where' class='gsniceinput1' value='<?php echo $conf->place; ?>'>
            <input type='text' gsname='from' class='gsniceinput1' value='<?php echo $conf->from; ?>' style='width:50px;'>
            <input type='text' gsname='to' class='gsniceinput1' value='<?php echo $conf->to; ?>' style='width:50px;'>
            <input type='text' gsname='size' class='gsniceinput1' value='<?php echo $conf->attendeesCount; ?>' style='width:50px;'>
            <input type='text' gsname='name' class='gsniceinput1' value='<?php echo $conf->actionName; ?>' style='width: 300px;'>
            <span class='shop_button' gstype='submit'>Update action point</span>
        </div>
        <?php
    }
}
?>