<?
/* @var $this \ns_cbcf3e53_c035_43c2_a1ca_c267b4a8180f\PmsGroupBookingHeader */
$pmsBooking = $this->getCurrentBooking();
$rooms = 0;
foreach($pmsBooking->rooms as $r) {
    if(!$r->deleted) {
        $rooms++;
    }
}
$orderCount = count($pmsBooking->orderIds);
$user = $this->getApi()->getUserManager()->getUserById($pmsBooking->userId);
$guestcount = 0;

foreach($pmsBooking->rooms as $room) {
    if($room->deleted) {
        continue;
    }
    $guestcount += $room->numberOfGuests;
}
?>

<div style='text-align: center;'>
    <h1 style='border-bottom: solid 1px; padding-bottom: 10px; margin-bottom: 40px;'>
    <?php 
    echo "Grouped booking for " . $user->fullName; 
    echo ", total : " . round($pmsBooking->totalPrice); 
    $area = $this->getArea();
    ?>
    </h1>

    <div class="top_box <?php if($area == "owner") { echo "selected"; } ?>" areatype="owner">
        <div class="title">Guest(s)</div>
        <i class="fa fa-user"></i>
    </div>
    
    <div class="top_box <?php if($area == "rooms") { echo "selected"; } ?>" areatype="rooms">
        <div class="title">Rooms</div>
        <i class="fa fa-building"></i> <? echo $rooms; ?>
    </div>
    
    <div class="top_box <?php if($area == "payments") { echo "selected"; } ?>" areatype="payments">
        <div class="title displayorders">Payments</div>
        <i class="fa fa-shopping-bag"></i> <? echo $orderCount; ?>
    </div>
    
    <div class="top_box <?php if($area == "stay") { echo "selected"; } ?>" areatype="stay">
        <div class="title displayorders">Stay</div>
        <i class="fa fa-bed"></i>
    </div>
    
    <div class="top_box <?php if($area == "addons") { echo "selected"; } ?>" areatype="addons">
        <div class="title displayorders">Addons</div>
        <i class="fa fa-plus-square"></i>
    </div>
    
    <div class="top_box <?php if($area == "conference") { echo "selected"; } ?>" areatype="conference">
        <div class="title displayorders">Conference</div>
        <i class="fa fa-table"></i>
    </div>
</div>

<div class="booker_main_user <?php if($area == "owner") { echo "selected"; } ?>" areatype="owner"><?php $this->includeSelectedArea(); ?></div>
<div style='clear:both;'></div>

