
<?php
/* @var $this ns_cbcf3e53_c035_43c2_a1ca_c267b4a8180f\PmsGroupBookingHeader */
$booking = $this->getCurrentBooking();
if(sizeof($booking->orderIds) > 0) {
    $ids = array();
    foreach($booking->rooms as $r) {
        $ids[] = $r->pmsBookingRoomId;
    }
    $orderlist = new \ns_9a6ea395_8dc9_4f27_99c5_87ccc6b5793d\EcommerceOrderList();
    $orderlist->setOrderIds($this->getCurrentBooking()->orderIds);
    $orderlist->setExternalReferenceIds($ids);
    $orderlist->setPaymentLinkCallBack("app.PmsGroupBookingHeader.refreshPayments");
    $orderlist->renderApplication(true, $this);
} else {
    echo "<h1>No orders created yet, create one by pressing start payment process for all rooms.</h1>";
}
?>