<?php
/* @var $this ns_cbcf3e53_c035_43c2_a1ca_c267b4a8180f\PmsGroupBookingHeader */
$types = $this->getApi()->getBookingEngine()->getBookingItemTypesWithSystemType($this->getSelectedMultilevelDomainName(), null);
$start = date("d.m.Y", time());
$end = date("d.m.Y", strtotime(date("d.m.Y",time()) . " +1 day"));
$booking = $this->getCurrentBooking();
?>

<div class='manipulateroomoptions'>
    <span class='shop_button disabled' type='delete'><i class='fa fa-trash-o'></i> Delete selected rooms</span>
    <span class='shop_button disabled' type='split'><i class='fa fa-users'></i> Split into a new group</span>
    <span class='shop_button disabled' type='updateGuestCount'><i class='fa fa-plus-square-o'></i> Update guest count</span>
    <i class='fa fa-caret-down'></i>
</div>
<span class='shop_button' style='float:right;' onclick="$('.addroombox').toggle();">Add another room</span>


<div class='addroombox' style='display:none;' gstype="form" method="addRoomToGroup">
    <h3>Add another room to this group</h3>
    <input type='txt' class='gsniceinput1' value='<?php echo $start; ?>' gsname='start'> 
    <input type='txt' class='gsniceinput1' value='<?php echo $end; ?>' gsname='end'> 
    <select class='gsniceselect1' style='height:38px;' gsname='type'>
        <?php
        foreach($types as $type) {
            echo "<option value='" . $type->id . "'>" . $type->name . "</option>";
        }
        ?>
    </select>
    <select class='gsniceselect1' style='height:38px;' gsname='guestInfoOnRoom'>
        <?php
        echo "<option value=''>No guest information</option>";
        foreach($booking->rooms as $room) {
            $guestInfo = "";
            if(isset($room->guests[0])) {
                $guestInfo = $room->guests[0]->name . " - ";
                $guestInfo .= $room->guests[0]->email . " - ";
                $guestInfo .= $room->guests[0]->prefix . " - ";
                $guestInfo .= $room->guests[0]->phone;
            }
            echo "<option value='" . $room->pmsBookingRoomId . "'>" . $guestInfo . "</option>";
        }
        ?>
    </select>
    <input type='txt' class='gsniceinput1' gsname='count' value="1" style="width:30px;"> 
    <span class='shop_button doaddroomtogroup' gstype="submit">Add room</span>
    
    <div class="notavailablerooms">I am sorry, you can not add room using the above selection, there are not enough rooms for that, if adding them they will be added to a waiting queue.</div>
</div>

<?php
$filter = new core_pmsmanager_PmsBookingFilter();
$filter->includeDeleted = true;
$filter->bookingId = $booking->id;
$roomView = new \ns_961efe75_e13b_4c9a_a0ce_8d3906b4bd73\PmsSearchBooking();
$roomView->page = $this->page;
$roomView->setCurrentFilter($filter);
$roomView->renderApplication(true,$this);
?>

<style>
    .manipulateroomoptions { display:inline-block; padding: 2px; border-bottom: solid 1px #bbb; position: relative; }
    .shop_button.disabled { background-color:#efefef; color:#000; cursor:inherit; }
    .manipulateroomoptions .fa-caret-down { position:absolute; bottom: -13px; font-size: 20px; left: 32px; color:#bbb; }
</style>

<script>
    $('[gsname="start"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true, 
        onSelect: function(dateText) {
            var curEnd = moment($('[gsname="end"]').val(), "DD.MM.YYYY");
            var date = moment(dateText, "DD.MM.YYYY");
            
            var diff = curEnd.valueOf() - date.valueOf();
            if(diff <= 0) {
                date.add(1, 'days');
                $('[gsname="end"]').val(date.format('DD.MM.YYYY')); 
            }
            
            app.PmsGroupBookingHeader.checkIfCanAddRoom();
        }
    });
    
    $('[gsname="end"]').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true, 
        onSelect: function(dateText) {
            $('.PmsNewBooking [gsname="numberOfRooms"]').val(0);
            var curStart = moment($('[gsname="start"]').val(), "DD.MM.YYYY");
            var date = moment(dateText, "DD.MM.YYYY");
            
            var diff = date.valueOf() - curStart.valueOf();
            if(diff <= 0) {
                date.add(-1, 'days');
                $('[gsname="start"]').val(date.format('DD.MM.YYYY')); 
            }     
            app.PmsGroupBookingHeader.checkIfCanAddRoom();
        }
    });
</script>