<?
/* @var $this \ns_294a8d9e_bd48_44f4_a607_b7d86d2d85fc\ProMeisterCandidateSearch */
$users = $this->getUsers("fav");
$favList = $this->getFavList();

?>
<div class="favorits">
<?
if (!count($users)) {
    $this->wrapContentManager("no_fav_added", "To add users to favorite list, search and click on the star");
} else {
    $grouped = $this->groupByCompany($users);
    foreach ($grouped as $companyId => $users) {
        $company = $this->getApi()->getUserManager()->getCompany($companyId);
        echo "<div class='companyrow'>";
        $companyName = $company ? $company->name : $this->__f("Unassigned");
        
        $group = $company ? $this->getApi()->getUserManager()->getGroup($company->groupId) : "";
        $groupName = $group != null ? $group->groupName : "N/A";
        
        $inFavList = in_array($company->id, $favList);
        $color = $inFavList ? "style='color: yellow'" : "";
        echo "<div class='companyname'>";
        if ($company) {
            echo '<i class="fa fa-star-o" '.$color.' gsclick="addToFav" userid="'.$company->id.'"></i>';
        }
        echo "&nbsp; $companyName ( $groupName )</div>";
        
        foreach ($users as $user) {
            
            $groupName = $group != null ? $group->groupName : "N/A";
            $events = $this->getApi()->getEventBookingManager()->getEventsForUser($this->getBookingEngineName(), $user->id);
            $inFavList = in_array($user->id, $favList);
            $color = $inFavList ? "style='color: #0dac0d'" : "";
            $count = count($events);
            ?>
        
            <div class="userrow">
                <div class="starred"> <i class="fa fa-star-o" <? echo $color; ?> gsclick="addToFav" userid="<? echo $user->id; ?>"></i></div>
                <div class="groupname"><? echo $groupName; ?></div>
                <div class="name"><? echo $user->fullName; ?></div>
                <div class="info"> <i class="fa fa-info-circle gs_shop_small_icon show_user_information"> (<? echo $count; ?>)</i></div>
                <div class="userInformation">
                    <?
                    if (!is_array($events)) {
                        echo $this->__f("Hos not participated on any events");
                    } else {
                        foreach ($events as $event) {
                            $start = date("d.m.Y H:i", strtotime($event->mainStartDate));
                            $end = date("d.m.Y H:i", strtotime($event->mainEndDate));
                            echo "<div class='event_row'>$start - $end: ".$event->bookingItemType->name."</div>";
                        }
                    }
                    ?>
                </div>
            </div>
            <?
        }
        echo "</div>";
    }
}
?>

</div>