<span class="help">
    <div class='heading'><? echo $this->__f("Congratulation, you have added your first image."); ?></div>
    <div><? echo $this->__f("A quick tip; when the mouse is hovering the image, you will see a settings box where you can configure the image."); ?></div>
    <span class='close'>X</span>
    <script>
    $('.ImageDisplayer .deleteimage').addClass('helpactive');
    $('.ImageDisplayer .editimage').addClass('helpactive');
    </script>
</span>