<?
/* @var $this ns_451d5030_1936_4a8a_95fc_014066c0b24e\ProMeisterCreateCompanyAccount */
?>
<div gstype="form" method='createAccount'>
    <div><? $this->wrapContentManager("textfield_1", "Fullname") ?></div>
    <input type='txt' class='gsniceinput1' gsname='name'/>
    <div><? $this->wrapContentManager("textfield_2", "Email") ?></div>
    <input type='txt' class='gsniceinput1' gsname='email'/>
    <div><? $this->wrapContentManager("textfield_3", "*Cellphone") ?></div>
    <input type='txt' class='gsniceinput1' gsname='cellphone'/>
    <div><? $this->wrapContentManager("textfield_4", "*Password") ?></div>
    <input type='txt' class='gsniceinput1' gsname='password'/>
    
    <div class='shop_button' gstype='submit' >
        <? 
        echo $this->__w("Create account");
        ?>
    </div>
</div>