<?
/* @var $this ns_d02f8b7a_7395_455d_b754_888d7d701db8\Dibs */

$dibs = $this->getConfigurationSetting("merchantid");

$kidMethods = array();
$kidMethods[''] = "None";
$kidMethods['orderid'] = "Order id only";
$kidMethods['customerid'] = "Customer id only";
$kidMethods['customeridandorderid'] = "Orderid + customerid";

$langauges = array();
$langauges['en_en'] = "English";
$langauges['nb_no'] = "Norsk";
?>

<div class='gss_settings_header'>
    <i class='fa fa-envelope'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <?php echo $this->getName(); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?php echo $this->getDescription(); ?>
        </div>
    </div>	
</div>

<div class='gss_settings_content'>
    <div class="textfield gss_setting"  id="ordertype">
        <span class="title"><?php echo $this->__f("Account number"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='accountNumber' value="<? echo $this->getConfigurationSetting("accountNumber"); ?>">
        <div class="description">
            <?php  echo $this->__f("This is the accounting number that will be printed on the invoice, example XXXX XX XXXXX"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="ordertype">
        <span class="title"><?php echo $this->__f("Vat number"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='vatNumber' value="<? echo $this->getConfigurationSetting("vatNumber"); ?>">
        <div class="description">
            <?php  echo $this->__f("This is the vat number that will be printed on the invoice, example 123456789"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="ordertype">
        <span class="title"><?php echo $this->__f("Address"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='address' value="<? echo $this->getConfigurationSetting("address"); ?>">
        <div class="description">
            <?php  echo $this->__f("This is the address that will be printed on the invoice, example GetShop street 13"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="ordertype">
        <span class="title"><?php echo $this->__f("Company Name"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='companyName' value="<? echo $this->getConfigurationSetting("companyName"); ?>">
        <div class="description">
            <?php  echo $this->__f("This is the company name that will be printed on the invoice, example GetShop"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="ordertype">
        <span class="title"><?php echo $this->__f("Post code"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='postCode' value="<? echo $this->getConfigurationSetting("postCode"); ?>">
        <div class="description">
            <?php  echo $this->__f("This is the post code that will be printed on the invoice, example 4380"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="city">
        <span class="title"><?php echo $this->__f("City"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='city' value="<? echo $this->getConfigurationSetting("city"); ?>">
        <div class="description">
            <?php  echo $this->__f("This is the city that will be printed on the invoice, example Las Vegas"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="city">
        <span class="title"><?php echo $this->__f("Contact email"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='contactEmail' value="<? echo $this->getConfigurationSetting("contactEmail"); ?>">
        <div class="description">
            <?php  echo $this->__f("This is the email address that will be printed on the invoice, example post@getshop.com"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="webAddress">
        <span class="title"><?php echo $this->__f("Web address"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='webAddress' value="<? echo $this->getConfigurationSetting("webAddress"); ?>">
        <div class="description">
            <?php  echo $this->__f("This is the web address that will be printed on the invoice, example http://www.getshop.com"); ?>
        </div>
    </div>
    <div class="textfield gss_setting"  id="webAddress">
        <span class="title"><?php echo $this->__f("Due days"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='duedays' value="<? echo $this->getConfigurationSetting("duedays"); ?>">
        <div class="description">
            <?php  echo $this->__f("Number of days the customer have to pay the invoice, example 14"); ?>
        </div>
    </div>

    <div class="gss_setting" id="defaultKidMethod">
        <div class="text inline title"><?php echo $this->__f("Please select the default kid method"); ?></div>

        <div class="gss_dropdown">
            <select class="config" gs_model='invoicepaymentmodel' gs_model_attr='defaultKidMethod'>
                <? foreach ($kidMethods as $key => $name) { 
                    $selected = $this->getConfigurationSetting("defaultKidMethod") == $key ? "SELECTED" : "";
                    ?>
                    <option value="<? echo $key; ?>" <?php echo $selected; ?>><? echo $name; ?></option>
                <? } ?>
            </select>
        </div>
        <div class="description">
            <?php echo $this->__("This will be the default kid solution."); ?>
        </div>        
    </div>

    <div class="textfield gss_setting"  id="kidSize">
        <span class="title"><?php echo $this->__f("Kid size"); ?></span>
        <input type='textfield' gs_model='invoicepaymentmodel' gs_model_attr='kidSize' value="<? echo $this->getConfigurationSetting("kidSize"); ?>" style='width: 50px;'>
        <div class="description">
            <?php echo $this->__("If cartCustomerId is set, use this payment application id as default"); ?>
        </div>
    </div>

    <div class="textfield gss_setting"  id="currency">
        <span class="title"><?php echo $this->__f("Currency"); ?></span>
        <input type='textfield' gs_model='invoicepaymentmodel' gs_model_attr='currency' value="<? echo $this->getConfigurationSetting("currency"); ?>" style='width: 50px;'>
        <div class="description">
            <?php echo $this->__("Currency text on invoice"); ?>
        </div>
    </div>
        
    <div class="gss_setting">
        <div class="text inline title"><?php echo $this->__f("Please select your invoice template type"); ?></div>

        <?
        $states = array();
        $states['type1'] = "type1";
        $states['type2'] = "type2";
        ?>
        
        <div class="gss_dropdown">
            <select class="config" gs_model='invoicepaymentmodel' gs_model_attr='type'>
                <? foreach ($states as $key => $lang) { 
                    $selected = $this->getConfigurationSetting("type") == $key ? "selected='true'" : "";
                    ?>
                    <option <? echo $selected; ?> value="<? echo $key; ?>"><? echo $lang; ?></option>
                <? } ?>
            </select>
        </div>    
    </div>
    
    <div class="textfield gss_setting"  id="iban">
        <span class="title"><?php echo $this->__f("IBAN"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='iban' value="<? echo $this->getConfigurationSetting("iban"); ?>">
        <div class="description">
            <?php  echo $this->__f("Iban number"); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting"  id="swift">
        <span class="title"><?php echo $this->__f("SWIFT"); ?></span>
        <input type="textfield" gs_model='invoicepaymentmodel' gs_model_attr='swift' value="<? echo $this->getConfigurationSetting("swift"); ?>">
        <div class="description">
            <?php  echo $this->__f("Swift number"); ?>
        </div>
    </div>
    
    <div class="textfield gss_setting"  id="language">
        <span class="title"><?php echo $this->__f("Language"); ?></span>
        <div class="gss_dropdown">
            <select class="config" gs_model='invoicepaymentmodel' gs_model_attr='language'>
                <? foreach ($langauges as $key => $lang) { 
                    $selected = $this->getConfigurationSetting("language") == $key ? "selected='true'" : "";
                    ?>
                    <option <? echo $selected; ?> value="<? echo $key; ?>"><? echo $lang; ?></option>
                <? } ?>
            </select>
        </div>
        <div class="description">
            <?php  echo $this->__f("Selected language"); ?>
        </div>
    </div>
    
    
    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="invoicepaymentmodel" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Save"); ?></div>
    </div>
</div>
