<?
/* @var $this \ns_892ecdf0_381a_4c3a_9832_e425e85bd36b\TicketView */
$ticket = $this->getSystemGetShopApi()->getTicketManager()->getTicketByToken($this->getFactory()->getStore()->id, $_GET['ticketToken']);
$contents = $this->getSystemGetShopApi()->getCustomerTicketManager()->getTicketContents($this->getFactory()->getStore()->id, $ticket->ticketToken);
?>

<div class="heading">
    <? echo $ticket->title; ?>
</div>

<div class="ticketarea">
    <div class="contentbox">
        <? echo $ticket->content; ?>
    </div>
    <div class="infobox">
        <div>
            <?
            foreach ($contents as $content) {
                echo htmlspecialchars($content->content, ENT_QUOTES, 'UTF-8');
            }
            ?>
        </div>
    </div>
</div>

<div class="ticketinfo">
    Ticket: <? echo $ticket->incrementalId; ?>
    <br/>Status: <? echo $ticket->currentState; ?>
    <br/>
    <br/><b>Date created:</b>
    <br/> <? echo date('d.m.Y h:i', strtotime($ticket->rowCreatedDate)); ?>
</div>