<?php
    $merchid = $this->getConfigurationSetting("merchantid");
    $currency = \ns_9de54ce1_f7a0_4729_b128_b062dc70dcce\ECommerceSettings::fetchCurrencyCode();
    $order = $this->getOrder();
    $orderId = $order->incrementOrderId;
    $amount = $this->getApi()->getOrderManager()->getTotalAmount($order)*100;
    $amount = round($amount);

    $settings = $this->getFactory()->getSettings();
    $language = $this->getFactory()->getSelectedTranslation();
    $store = $this->getFactory()->getStore();


    $key = $merchid;
    if($this->getApi()->getStoreManager()->isProductMode()) {
        $key .= "-prod";
    } else {
        $key .= "-debug";
    }
    
    $callBack = "http://pullserver_".$key."_".$store->id.".getshop.com";
    $redirect_url = "http://" . $_SERVER["HTTP_HOST"] . "/callback.php?app=" . $this->applicationSettings->id. "&orderId=" . $this->order->id . "&nextpage=";
    
?>

<script charset="UTF-8" src="https://ssl.ditonlinebetalingssystem.dk/integration/ewindow/paymentwindow.js" type="text/javascript"></script>
<script type="text/javascript">
     paymentwindow = new PaymentWindow({
         'merchantnumber': "<?php echo $merchid; ?>",
         'amount': "<?php echo $amount; ?>",
         'instantcapture' : 1,
         'callbackurl' : "<?php echo $callBack; ?>",
         'accepturl' : "<?php echo $redirect_url; ?>payment_success",
         'cancelurl' : "<?php echo $redirect_url; ?>payment_failed",
         'currency': "NOK"
     });
     paymentwindow.open();
</script>
  
