<?
/* @var $this \ns_f06d0c6a_882e_4592_917c_b74273edfd11\EventLister */
$groupedEvents = $this->getEvents();
$locations = $this->getLocations($groupedEvents);
$loggedOnUser = ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::getUserObject();


echo "<div class='locationlist'>";
    foreach ($locations as $loc) {
        $extra = $loc->isFiltered ? "<i class='fa fa-check'></i>" : "";
        echo "<div gsclick='applyFilter' locationId='$loc->id'>$extra $loc->name</div>";
    }
echo "</div>";



echo "<div class='eventlist'>";
    if (!count($groupedEvents)) {
        $this->wrapContentManager("no_events", "Please come back later, no events available");
        return;
    }

    foreach ($groupedEvents as $key => $events) {
        ?>
            <div class='monthheader'>
                <div class="monthname">
                    <? 
                        $splitted = explode("_", $key);
                        echo $this->__f($splitted[0])." - ".$splitted[1];
                    ?>
                </div>
            
                <div class="col col1 location"><? echo $this->__w("Location"); ?></div>
                <div class="col col2 eventname"><? echo $this->__w("Event name"); ?></div>
                <div class='col col3 daysinformation'><? echo $this->__w("Dates"); ?></div>
                <div class="col col4 availablespots"><? echo $this->__w("Available spots"); ?></div>
            </div>
        <?
        foreach ($events as $event) {
            $pageId = $event->eventPage;
            
            $buttonText = $this->__w("Book");
            $canSignUp = true;
            
            if ($event->markedAsReady) {
                $buttonText = $this->__w("Closed");
                $canSignUp = false;
            } else if (!$event->bookingItem->freeSpots) {
                $buttonText = $this->__w("Full");
                $canSignUp = false;
            } else if ($event->isCanceled) {
                $buttonText = $this->__w("Canceled");
                $canSignUp = false;
            } else if ($event->bookingItem->isFull) {
                $buttonText = $this->__w("Full");
                $canSignUp = false;
            }
            
            if ($event->canBookWaitingList) {
                $buttonText = $this->__w("Waitinglist");
            }

            if ($event->canBook || $event->canBookWaitingList) {
                $canSignUp = true;
            }
            
            ?>
            <div class='eventline' style='display: inline-block;'>
            <?
            
            echo "<a href='/$pageId'>";
            ?>
            
                <div class="col col1 location"><? echo $event->location->name. " - " .$event->subLocation->name; ?></div>
                <div class="col col2 eventname"><? echo $event->bookingItemType->name; ?></div>

                <div class='col col3 daysinformation'>
                    <?
                    foreach ($event->days as $day) {
                        echo ns_d5444395_4535_4854_9dc1_81b769f5a0c3\Event::formatDates($day->startDate, $day->endDate)."<br/>";
//                        echo date("d/m-Y h:m", strtotime($day->startDate))." ".date("d/m-Y h:m", strtotime($day->endDate))."<br/>";
                    }
                    ?>
                </div>

                <div class="col col4 availablespots"><? echo $event->bookingItem->freeSpots; ?></div>
                <div class="col col5 availablespots">
                    <?
                    if (!$canSignUp) {
                    ?>
                        <? echo $buttonText; ?>
                    <? } else { ?>
                        <i class="gs_shop_small_icon"><? echo $buttonText; ?></i>
                    <? } ?>
                        
                    <a href='/?page=<? echo $event->bookingItemType->pageId; ?>'><i class="gs_shop_small_icon  fa fa-info"></i></a>
                </div>
            <?
            echo "</a>";
            ?>
            </div>
        <?
        }
    }
echo "</div>";
?>