<?
/* @var $this ns_a7cb1957_bbc9_42d3_8f79_fa91260c3ebf\EventStatistic */

$this->includefile("form");
?>


<div id='result'></div>
<br/>
<br/>
<div>
    <?
    $stats = $this->getStats();
    if ($stats) {
        echo '<div class="shop_button" gs_downloadexcelreport="downloadStatistic" gs_filename="statistic">Download excel</div>';
        
        $data = ""; 
        foreach ($stats as $stat) {

            $yrdata= strtotime("$stat->year-$stat->month-1");
            $monthName = date('M-Y', $yrdata);

            $data .= "['".$monthName."',".$stat->count.", '".$stat->count."'],";
        
            echo "<div class='monthstatistic'>";
                echo "<div class='monthheader'>$monthName</div>";
                foreach ($stat->users as $eventId => $users) {
                    $event = $this->getApi()->getEventBookingManager()->getEvent("booking", $eventId);
                    $date = ns_d5444395_4535_4854_9dc1_81b769f5a0c3\Event::formatMainStartDates($event);
                    echo "<div class='eventtitle'>".$event->bookingItemType->name." ( $date ) </div>";
                    foreach ($users as $userId) {
                        $user = $this->getApi()->getUserManager()->getUserById($userId);
                        $companyName = $user->companyObject ? $user->companyObject->name : "";
                        echo "<div class='userrow'><span class='candidatename'>".$user->fullName."</span><span class='candidatecompany'>$companyName</span></div>";
                    }
                }
            echo "</div>";
            
        }
        
        
        
    }
    ?>
</div>

<script>
    function drawIt() {
        
        var div = document.getElementById('result');
        
        var data = new google.visualization.arrayToDataTable([
            ['Element', 'Density', { role: 'annotation' } ],
            <? echo isset($data) ? $data : ""; ?>
        ]);
//            data.addColumn('string', 'Month');
//            data.addColumn('number', 'Participated');
//            data.addRows(<? echo isset($data) ? $data : ""; ?>);
//
//            // Set chart options
            var options = {
                'title': 'Mechanic eventdays',
                'width': 758,
                'height': 200
            };

            var chart = new google.visualization.ColumnChart(div);
            chart.draw(data, options);

        
    }
    
    $('.EventStatistic .starttime').datepicker();
    $('.EventStatistic .stopptime').datepicker();
    
    <?
    if ($stats) {
    ?>
        $(document).ready(drawIt);
    <?
    }
    ?>
</script>
    
    