<?php
namespace ns_13270e94_258d_408d_b9a1_0ed3bbb1f6c9;
/* @var $this OrderExport */
$states = \ns_27716a58_0749_4601_a1bc_051a43a16d14\OrderManager::getOrderStatuses();
$transfertypes = $this->getTransferTypes();

$newArray = array();
$newArray[-1] = "Credit notes";
$newArray[0] = "All states";
$states = $newArray + $states;

$files = $this->getApi()->getAccountingManager()->getAllFiles();
$newfile = array();
foreach($files as $file) {
    $newfile[strtotime($file->rowCreatedDate)] = $file;
}
ksort($newfile);

$finalFiles = array();
foreach($newfile as $time => $entry) {
    foreach($files as $file) {
        if(strtotime($file->rowCreatedDate) == $time) {
            $finalFiles[] = $file;
        }
    }
}
$finalFiles = array_reverse($finalFiles);
$files = $finalFiles;

$availableTypes = array();
$availableTypes['poweroffice'] = "Power Office Go";
$availableTypes['rubicon'] = "Rubicon";
$availableTypes['vismaordersr'] = "Visma ordersr";
$availableTypes['vismadirdbr'] = "Visma dirdbr";
$availableTypes['xledger'] = "Xledger";
$availableTypes['amesto'] = "Amesto";
$availableTypes['tripletex'] = "TripleTex";
$availableTypes['fiken'] = "Fiken";
$availableTypes['sveve'] = "Sveve creditor";
$availableTypes['getshop'] = "GetShop";
$availableTypes['bcomratemanager'] = "Booking.com rate manager";

$userIncludeTypes = array();
$userIncludeTypes[0] = "No users included";
$userIncludeTypes[1] = "All users included";
$userIncludeTypes[2] = "Only new users included";
$userIncludeTypes[3] = "All users connected to orders selected";
$userIncludeTypes[4] = "All users connected not transferred orders";

$subtypes = array();
$subtypes['order'] = "Transfer orders";
$subtypes['booking'] = "Transfer bookings";

$orderFiltertype = array();
$orderFiltertype["created"] = "Order created";
$orderFiltertype["started"] = "Order started";
$orderFiltertype["ended"] = "Order ended";
$orderFiltertype["paymentdate"] = "Order paid for";

$start = date("d.m.Y", time()-86400);
$end = date("d.m.Y", time()-86400);

$paymentMethods = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();
?>

<div class="gss_settings_header">
    <i class="fa fa-dollar"></i>

    <div class="gss_settings_header_description">
        <div class="gss_settings_header_title"> <? echo $this->__f("Accounting transfer"); ?></div>

        <div class="gss_settings_header_description_inner">
            <? echo $this->getDescription(); ?>
        </div>
    </div>
</div>


<div class='gss_settings_content'>
<?php
echo "<br>";
echo "<h2>Downloaded history</h2>";
echo "<table width='100%'>";
echo "<tr>";
echo "<th align='left'>Created date</th>";
echo "<th align='left'>Download</th>";
echo "<th align='left'>Type</th>";
echo "<th align='left'>Subtype</th>";
echo "<th align='left'>Transferred</th>";
echo "<th align='left'>Ex tax</th>";
echo "<th align='left'>Inc tax</th>";
echo "<th align='left'>Ex tax (p)</th>";
echo "<th align='left'>Inc taxes (p)</th>";
echo "<th align='left'>Orders</th>";
echo "<th align='left'>Start</th>";
echo "<th align='left'>End</th>";
echo "</tr>";

$totals = array();
$totals['amountEx'] = 0;
$totals['amountInc'] = 0;
$totals['amountExDebet'] = 0;
$totals['amountIncDebet'] = 0;
$totals['orders'] = 0;
    
foreach($files as $file) {
    $date = $file->rowCreatedDate;
    $fileId = $file->id;
    $transferred = "no";
    if($file->transferred) {
        $transferred = "yes";
    }
    
    $totals['amountEx'] += $file->amountEx;
    $totals['amountInc'] += $file->amountInc;
    $totals['amountExDebet'] += $file->amountExDebet;
    $totals['amountIncDebet'] += $file->amountIncDebet;
    $totals['orders'] += sizeof($file->orders);
    
    $tampered =  sizeof($file->tamperedOrders);
    $moreOrders = (sizeof($file->orders) - $file->numberOfOrdersNow);
    
    $warning = "";
    if($tampered != 0 || $moreOrders != 0) {
        $warning = "style='color:red; font-weight:bold;'";
    }
    
    echo "<tr $warning>";
    echo "<td>";
    if($warning) {
        echo "<i class='fa fa-warning' title='This file is not valid anymore. Something has changed since last time which makes it invalid. This should not happen and need to be investigated.'></i> ";
    }
    echo date("d.m.Y - H:i", strtotime($date)) . "</td>";
    echo "<td><a style='color:blue;cursor:pointer;' onclick=\"window.open('/scripts/accountingnew.php?id=".$fileId."');\">download</a></td>";
    echo "<td>".$file->type."</td>";
    echo "<td>".$file->subtype."</td>";
    echo "<td>$transferred</td>";
    echo "<td>".round($file->amountEx)."</td>";
    echo "<td>".round($file->amountInc)."</td>";
    echo "<td>".round($file->amountExDebet)."</td>";
    echo "<td>".round($file->amountIncDebet)."</td>";
    echo "<td>".sizeof($file->orders) ." <span title='Tampered files'>($tampered)</span> <span title='Additional orders'>($moreOrders)</span> "."</td>";
    echo "<td>".  date("d.m.Y H:i", strtotime($file->startDate)) ."</td>";
    echo "<td>".  date("d.m.Y H:i", strtotime($file->endDate)) ."</td>";
    echo "</tr>";
}

echo "<tr>";
echo "<td></td>";
echo "<td></td>";
echo "<td></td>";
echo "<td></td>";
echo "<td></td>";
echo "<td>".round($totals['amountEx'])."</td>";
echo "<td>".round($totals['amountInc'])."</td>";
echo "<td>".round($totals['amountExDebet'])."</td>";
echo "<td>".round($totals['amountIncDebet'])."</td>";
echo "<td>".round($totals['orders'])."</td>";
echo "</tr>";

echo "</table>";


echo "<br>";
echo "<br>";

echo "<select class='gssaddaccountingtype'>";
foreach($availableTypes as $type => $name) {
    echo "<option value='$type'>" . $name . "</option>"; 
}
echo "</select>";
echo "<input type='button' class='gssaddaccounting' value='Add integration'></option>";
echo "<br><br><div style='clear:both;'></div>";

$configs = (array)$this->getApi()->getAccountingManager()->getAllConfigs();

$first = true;
foreach($configs as $config) {
    $selected = "";
    if($first) {
        $selected = "selectedintegration";
        $first = false;
    }
    echo "<span class='integrationselection $selected' type='".$config->id."'><i class='fa fa-trash-o deletetransferconfig' configid='".$config->id."'></i> " .  $availableTypes[$config->transferType]  . " (" . $config->subType . ")". "</span>";
}

echo "<span class='integrationselection incomedistribution' type='incomedistribution'>Income distribution</span>";
echo "<br><br><div style='clear:both;'></div><hr>";
?>
<div class='configfield' type='incomedistribution' style='display:none;'>
<?php 

echo "<select class='viewstatsforfile'>";
echo "<option value=''>All orders</option>";
foreach($files as $file) {
    echo "<option value='". $file->id."'>" . $file->subtype . " - " . date("d.m.Y" , strtotime($file->startDate)) . " - " .  date("d.m.Y" , strtotime($file->endDate))  . "</option>";
}
echo "</select>";
echo "<br>";
echo "<br>";
echo "<div class='orderdistrstats'>";
$this->printStatistics();
echo "</div>";
?>
</div>    
<?php

$show = true;
foreach($configs as $config) {
    /* @var $config core_accountingmanager_AccountingTransferConfig */
    $hidestyle = "display:none";
    if($show) {
        $hidestyle = "";
    }
    $show = false;
    $ftp = $config->ftp;
    if(!$ftp) {
        $ftp = new \core_accountingmanager_TransferFtpConfig();
    }
    ?>
    <div class='configfield' type='<?php echo $config->id; ?>' style='<?php echo $hidestyle; ?>'>
    <div class="textfield gss_setting">
        <span class="title">Start date</span>
        <input type="textfield" class='gss_accdownloadstart' configid="<?php echo $config->id; ?>" value='<?php echo $start; ?>'>
    </div>
    <div class="textfield gss_setting">
        <span class="title">End date</span>
        <input type="textfield" class='gss_accdownloadend' configid="<?php echo $config->id; ?>" value='<?php echo $end; ?>'>
    </div>
    <div class="gss_button_area">
        <div class="gss_button gss_downloadaccountingfile" configid='<?php echo $config->id; ?>'><i class='fa fa-save'></i><?php echo $this->__("Download file"); ?></div>
    </div>
    <hr>


    <script>
    $('.gss_accdownloadstart').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true});
    $('.gss_accdownloadend').datepicker({ dateFormat: "dd.mm.yy", changeMonth: true, changeYear: true, showButtonPanel: true});
    </script>

    <div style='clear:both;'></div>
        <?php
        echo "<h2>Configuration for this ".$availableTypes[$config->transferType]." file </h2>";
        ?>
        <div class='gssaddpaymentcontainer'>
            <select class='gsspaymentmethod'>
                <? 
                foreach ($paymentMethods as $key => $method) {
                    $selected = $filter->paymentMethod == $method->id ? "SELECTED" : "";
                    ?>
                    <option value="<? echo $method->id; ?>" <? echo $selected; ?>><? echo $method->appName; ?></option>
                    <?php
                 }
                ?>
            </select>
        <?php

            echo "<select class='gsspaymentstatus'>";
            foreach($states as $type => $name) {
                echo "<option value='$type'>$name</option>";
            }
            echo "</select>";
            ?>
            <input type='button' value='Add filter' class='gss_addfiltertoconfig' configid='<?php echo $config->id; ?>'>
            
            <br><br>
            <?php
            $conftypes = (array)$config->paymentTypes;
            foreach($conftypes as $type) {
                foreach ($paymentMethods as $key => $method) {
                    if($method->id == $type->paymentType) {
                        echo "<i class='fa fa-trash-o gssremovepaymenttype' type='".$type->paymentType."' configid='".$config->id."' status='".$type->status."'></i> " . $method->appName . " - " . $states[$type->status] . "<br>";
                    }
                }
            }
            ?>
        </div>
        <br><br><br>
        <h2>Additional config</h2>

        <div class="textfield gss_setting"  id="name">
            <span class="title"><?php echo $this->__f("Users to include"); ?></span>
             <div class="gss_dropdown">
                <select class="property_select" gs_model="adminconfig_<?php echo $config->id; ?>" gs_model_attr="includeUsers">
                    <?php
                    foreach($userIncludeTypes as $id => $type) {
                        $selected = "";
                        if($config->includeUsers == $id) {
                            $selected = "SELECTED";
                        }
                        echo "<option value='".$id."' $selected>".$type."</option>";
                    }
                    ?>
                </select>
             </div>
        </div>
      <input type="hidden" gs_model="adminconfig_<?php echo $config->id; ?>" gs_model_attr="configid" value="<?php echo $config->id; ?>">
          
        <div class="textfield gss_setting"  id="orderFilterPeriode">
            <span class="title"><?php echo $this->__f("Filter order by"); ?></span>
             <div class="gss_dropdown">
                <select class="property_select" gs_model="adminconfig_<?php echo $config->id; ?>" gs_model_attr="orderFilterPeriode">
                    <?php
                    foreach($orderFiltertype as $id => $type) {
                        $selected = "";
                        if($config->orderFilterPeriode == $id) {
                            $selected = "SELECTED";
                        }
                        echo "<option value='".$id."' $selected>".$type."</option>";
                    }
                    ?>
                </select>
             </div>
        </div>
      
      <?php
        $conftypes = (array)$config->paymentTypes;
        $printed = array();
        foreach($conftypes as $type) {
            foreach ($paymentMethods as $key => $method) {
                if($method->id == $type->paymentType) {
                    if(in_array($method->id, $printed)) {
                        continue;
                    }
                    $printed[] = $method->id;
                    $customerId = "";
                    if(isset($config->paymentTypeCustomerIds->{$method->id})) {
                        $customerId = $config->paymentTypeCustomerIds->{$method->id};
                    }
                    ?>
                    <div class="textfield gss_setting">
                        <span class="title">Optional customer id for <?php echo $method->appName; ?></span>
                        <input type="textfield" gs_model="adminconfig_<?php echo $config->id; ?>" gs_model_attr="customeridforpaymentmethod_<?php echo $method->id; ?>" value='<?php echo $customerId; ?>'>
                    </div>
                    <?php
                }
            }
        }
      ?>
      <div class="textfield gss_setting">
          <span class="title">Subtype</span>
          <input type="textfield" gs_model="adminconfig_<?php echo $config->id; ?>" gs_model_attr="subtype" value='<?php echo $config->subType; ?>'>
      </div>
      <div class="textfield gss_setting">
          <span class="title">Username</span>
          <input type="textfield" gs_model="adminconfig_<?php echo $config->id; ?>" gs_model_attr="username" value='<?php echo $config->username; ?>'>
      </div>
      <div class="textfield gss_setting">
          <span class="title">Password</span>
          <input type="textfield" gs_model="adminconfig_<?php echo $config->id; ?>" gs_model_attr="password" value='<?php echo $config->password; ?>'>
      </div>
      
        <div class='gss_button_area'>
            <div class="gss_button" gss_method="saveAccountingConfig" gss_model="adminconfig_<?php echo $config->id; ?>" gss_success_message="Saved successfully"><i class='fa fa-save'></i><?php echo $this->__("Save settings"); ?></div>
        </div>
    </div>
<? } ?>
</div>

<script>
    var item = localStorage.getItem("savedTabOrderExport");
    if(item) {
        $('.integrationselection[type="'+item+'"]').click();
    }
</script>