
<h1><? echo $this->__w("Email text"); ?></h1>
<input style="width:100%;" class="emailtitle" value="<? echo $this->getEmailTitle(); ?>"></textarea>
<textarea style="width:100%; height: 100px;" class="emailtext"><? echo $this->getEmailText(); ?></textarea>
<span class="saveEmail" style="float:right;"><? echo $this->__f("Save email text"); ?></span>
<? if(isset($_POST['data']['email'])) { echo "<span style='float:right;'>Text has been saved...</span> "; } ?>


<h1><? echo $this->__w("Participients"); ?></h1>
<? 
$savedentries = $this->getSavedEntries();
echo "<table width='100%'>";
echo "<tr>";
echo "<th align='left'>" . $this->__w("Tipser") . "</th>";
echo "<th align='left'>" . $this->__w("To email") . "</th>";
echo "<th align='left'>" . $this->__w("To name") . "</th>";
echo "</tr>";
$count = 1;
foreach($savedentries as $name => $entries) {
    foreach($entries as $email => $name) {
        echo "<tr>";
        echo "<td>$count. " . $name . "</td>";
        echo "<td>" . $email . "</td>";
        echo "<td>" . $name . "</td>";
        echo "</tr>";
    }
}
echo "</table>";
?>
<bR><br><br>