<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=390097657728360&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<br>
<h1><? echo $this->__w("Your name"); ?></h1>
<input type="text" class="inputname">
<h1><? echo $this->__w("Your email"); ?></h1>
<input type="text" class="inputemail">
<br>
<form action="">
    <table style="width:100%;" class="emailspreader">
        <thead>
            <tr>
                <th align="left"><? echo $this->__w("Name of the person you want to tip"); ?></th>
                <th align="left"><? echo $this->__w("Email for this person"); ?></th>
            </tr>
        </thead>
        <tbody>
            <? for($i = 0; $i < 3; $i++) { ?>
                <tr>
                    <td width="50%"><input type="text" placeholder="Ola Norman" class="name"></td>
                    <td width="50%" align="right"><input type="text" placeholder="ola@normann.no" class="email"></td>
                </tr>
            <? } ?>
        </tbody>
    </table>
    <br>
    <span class="addcontacts"><? echo $this->__w("Add more contacts"); ?></span>
    <span class="sendcontacts"><? echo $this->__w("Send form"); ?></span>
</form>
<div style="clear:both">
    <br>
<div style="float:right;" class="fb-share-button" data-layout="button" data-href="<? echo "http://".$_SERVER["HTTP_HOST"].$_SERVER["REQUEST_URI"]; ?>"></div>

</div>