<div class='gss_settings_header'>
    <i class='fa fa-envelope'></i>

    <div class='gss_settings_header_description'>
        <div class='gss_settings_header_title'>
            <? echo $this->__f("Clickatell"); ?>
        </div>
        <div class='gss_settings_header_description_inner'>
            <?
            echo $this->getDescription();
            ?>	
        </div>
    </div>	
</div>

<div class='gss_settings_content'>
    <div class="textfield gss_setting">
        <span class="title"><?php echo $this->__f("Username"); ?></span>
        <input type="textfield" gs_model='clickatellmodel' gs_model_attr='username' value="<? echo $this->getConfigurationSetting("username"); ?>" placeholder="">
        <div class="description">
             <?php echo $this->__f("This is the username you receive from Clickatell when you create an account."); ?>
        </div>
    </div>

    <div class="textfield gss_setting">
        <span class="title"><?php echo $this->__f("Api id"); ?></span>
        <input type="textfield" gs_model='clickatellmodel' gs_model_attr='apiid' value="<? echo $this->getConfigurationSetting("apiid"); ?>" placeholder="">
        <div class="description">
             <?php echo $this->__f("The api id from Clickatell"); ?>
        </div>
    </div>

    <div class="textfield gss_setting">
        <span class="title"><?php echo $this->__f("Prefix number before sending"); ?></span>
        <input type="textfield" gs_model='clickatellmodel' gs_model_attr='numberprefix' value="<? echo $this->getConfigurationSetting("numberprefix"); ?>" placeholder="">
        <div class="description">
             <?php echo $this->__f("This is useful if you want to make sure that sms are only sent to a specific country, like for instance: 47"); ?>
        </div>
    </div>

    <div class="textfield gss_setting">
        <span class="title"><?php echo $this->__f("Password"); ?></span>
        <input type="textfield" gs_model='clickatellmodel' gs_model_attr='password' value="<? echo $this->getConfigurationSetting("password"); ?>" placeholder="">
        <div class="description">
             <?php echo $this->__f("The password you get from clickatell, this is something personal."); ?>
        </div>
    </div>

    <div class="textfield gss_setting">
        <span class="title"><?php echo $this->__f("Senders id"); ?></span>
        <input type="textfield" gs_model='clickatellmodel' gs_model_attr='from' value="<? echo $this->getConfigurationSetting("from"); ?>" placeholder="">
        <div class="description">
             <?php echo $this->__f("If you got an approved sender id from clickatell, if not leave empty."); ?>
        </div>
    </div>

    <div class='gss_button_area'>
        <div class="gss_button" gss_method="saveSettings" gss_model="clickatellmodel" gss_success_message="<? echo $this->__f("Saved settings"); ?>"><i class='fa fa-save'></i><?php echo $this->__("Save settings"); ?></div>
    </div>
    
</div>

