<?
/* @var $this ns_cf32e5a8_faf9_4039_92cd_176b5d3113ec\MecaFleetCarCreate */
$car = $this->getApi()->getMecaManager()->getCarByPageId($this->getPage()->getId());
$isAdmin = \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isEditor() || \ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator();
$disabled = !$isAdmin ? "disabled='true'" : "";

if ($this->getModalVariable("createnewcaronfleet")) {
    $car = null;
}

if ($car) {
    $fleet = $this->getApi()->getMecaManager()->getFleetByCar($car);
}


//$fleet = $this->getApi()->getMecaManager()->getFleetByCar($car);
//$followup = $fleet ? $fleet->followup : "";

$id = $car ? $car->id : "";
$regnr = $car ? $car->licensePlate : "";
$km = $car ? $car->kilometers : "";
$phone = $car ? $car->cellPhone : "";
$carowner = $car ? $car->carOwner : "";
$carinfo = $car ? $car->carInfo : "";
$eutime = $car && $car->prevControll ? strtotime($car->prevControll . " + 2 year") : time();
$eu =date('Y-m-d', $eutime);

?>
<div gstype="form" method="saveCar">
    <?
    if (!$this->getModalVariable("createnewcaronfleet")) {
    ?>
    <input type='hidden' value='<? echo $id; ?>' gsname='carId'/>
    <?
    } else {
    ?>
        <input type='hidden' value='<? echo $this->getModalVariable("createnewcaronfleet"); ?>' gsname='createnewcaronfleet'/>
    <?
    }
    ?>
    <div>
        Reg nr:
        <br/><input class="gsniceinput1" <? echo $disabled; ?> type="textfield" gsname="regnr" placeholder="" value='<? echo $regnr; ?>'/>
    </div>
    <br/>
    
    <div>
        Nåværende km stand:
        <br/><input class="gsniceinput1" <? echo $disabled; ?> type="textfield" gsname="kmstand" placeholder=""  value='<? echo $km; ?>'/>
    </div>
    <br/>
    
    <div>
        Når skal bilen inn til neste PKK?:
        <br/><input class="gsniceinput1" <? echo $disabled; ?> type="textfield" id='nextpkk' gsname="eukontroll" value='<? echo $eu; ?>'/>
    </div>
    <br/>
    
    <div>
        Navn på sjåfør:
        <br/><input class="gsniceinput1" <? echo $disabled; ?> type="textfield" gsname="carowner" placeholder=""  value='<? echo $carowner; ?>'/>
    </div>
    <br>
    <? // if($followup == false){
        echo "<div>Telefon:<br><input class='gsniceinput1' $disabled type='textfield' gsname='phone' placeholder='' value='$phone'/></div><br/>";
//    }?>
    
    <div>
        Bilmerke og modell:
        <br/><textarea class="gsniceinput1" <? echo $disabled; ?> gsname="carinfo" value='<? echo $carinfo; ?>'><? echo $carinfo; ?></textarea>
    </div>
    <br/>
    <?
    if ($isAdmin) {
    ?>
    <div class="shop_button" gstype="submit" gs_close_modal='true' gs_callback='app.MecaFleetCarCreate.goToCar'><i class="fa fa-save"></i> Lagre</div>
    <?
        if ($car && !$fleet->followup) {
            echo "<div class='shop_button sendKilomterRequest' gsclick='sendKilomterRequest' regnr='$car->licensePlate' ownerid='$car->carOwner' carid='$car->id'><i class='fa fa-envelope'></i> Send ny kilometerforspørsel</div>";
        }
    }
    ?>
</div>

<script>
    $('#nextpkk').datepicker({ dateFormat: 'yy-mm-dd', changeMonth: true, changeYear: true });
</script>