<?
/* @var $this \ns_cc678bcb_0e87_4c6c_aaad_8ec24ecdf9df\QuestBackUserOverview */
$allTests = $this->getApi()->getQuestBackManager()->getTests();
?>
<div class='yourtests'>
    
    <?
    if (!count($allTests)) {
        echo $this->__f("You currently dont have any tests, please contact admin to get access to one");
    } else {
        foreach ($allTests as $test) {
            echo "<div class='test' testid='$test->id'>";
            echo $test->name;
            $progress = $this->getApi()->getQuestBackManager()->getProgress($test->id);
            echo "<div class='progress_in_test'>$progress %</div>";
            echo "</div>";
        }
    }
    ?>

</div>