<?php
 /* @var $this ns_c844b3fe_84b0_4d26_a8e2_8aa361ed82c4\TripTease */
$key = $this->getHotelKey();
?>
<div class="configurationpanel" gstype="form" method="saveTripTeaseConfig">
    <input type="txt" class="gsniceinput1" style="float:right;" gsname="hotelkey" value="<?php echo $key; ?>">
    Hotel key
    <div style="clear:both; text-align:right; padding-top: 20px;">
        <input type="button" style="padding:8px; width:200px;" value="Save settings" gstype="submit">
    </div>
</div>