<?
/* @var $this ns_5ebb7b42_35b7_48d3_b047_825dc2b30b5f\TrackAndTraceRouteManagement */

$routes = $this->getApi()->getTrackAndTraceManager()->getAllRoutes();

if ($this->getSortingFunction()) {
    usort($routes, $this->getSortingFunction());
}

if ($routes) {
   
    echo "<div class='routelist'>";
    echo "<h1>All routes:</h1>";
    ?>
    
    <div class="sortings">
        Sorting:
        <br/><div class="shop_button" gsclick="toggleSortByDeliveryDate">Delivery date descending</div>
    </div>

    <div class="routeview" style="background-color: #FFF; font-weight: bold;">
        Information
        <div class="servicedate">Service Date</div>
    </div>
    <?
    foreach ($routes as $route) {
        $started = $route->startInfo != null && $route->startInfo->started ? "started" : "";
        $completedClass = $route->completedInfo != null && $route->completedInfo->completedTimeStamp ? "completed" : "";
        
        $completed = "";
        if ($route->completedInfo->completedTimeStamp) {
            $future = strtotime($route->completedInfo->completedTimeStamp);
            $future = $future + (24*3600*7.5);
            $date = time();
            $hours = ($future - $date)/60/60;
            $hours = ceil($hours);
            $completedInfo = $route->completedInfo->completed ? "Completed, " : "";
            $completed = " ( $completedInfo will be deleted in $hours hours ) ";
        }
        echo "<div class='routeview $started $completedClass'> "
        . "<div gsclick='changeToRouteView' routeid='$route->id' class='gs_shop_small_icon'><i class='fa fa-edit'></i></div> ";
        if (\ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
            $confirmText = "Are you sure you want to delete the route?";
            if ($started) {
                $confirmText = "Are you sure you want to delete.  This route is Started In Progress";
            }
            if ($completedClass) {
                $confirmText = "Are you sure you want to delete.  This route is Completed";
            }
            if (!$started && $completedClass) {
                $confirmText = "Are you sure you want to delete.  This route is Relief Route";
            }
            echo  "<div gsclick='deleteRoute' gs_confirm='$confirmText' routeid='$route->id' class='gs_shop_small_icon'><i class='fa fa-trash'></i></div> "
                . " ";
        }
        echo $route->name." $completed";
        if (ns_df435931_9364_4b6a_b4b2_951c90cc0d70\Login::isAdministrator()) {
            echo ", Depot: ". $route->depotId;
        }
        
        if ($started && !$completedClass) {
            echo ", <span style='font-weight: bold;'> ( Started ) </span>";
        }
        
        if (!$route->deliveryServiceDate) {
            echo "<div class='servicedate'> N /A </div>";
        } else {
            echo "<div class='servicedate'>".date('m/d-Y', strtotime($route->deliveryServiceDate))."</div>";
        }
        
        echo "</div>";
    }
    echo "</div>";
    echo "<br/>";
    echo "<br/>";
}
?>

<!--<div gstype="form" method="createRoute" style="background-color: #EFEFEF; padding: 0px 10px 20px 10px;">
    <h1>Create new route</h1>
    Route name: 
    <br/><input gsname="routename" type="textfield" class="gsniceinput1" placeholder="Route name"/>
    <br/><br/><div class="shop_button" gstype="submit">Create</div>
</div>-->

