<?
/* @var $this ns_5ebb7b42_35b7_48d3_b047_825dc2b30b5f\TrackAndTraceRouteManagement */

$route = $this->getRoute();
?>
<div class="topmenu">
    <div class="shop_button" gsclick="backToRoutes"><i class="fa fa-backward"></i> Back to routes</div>
</div>

<div>
    <div class="routebox" gstype='form' method='saveRoute'>
        Route name: <input class='gsniceinput1' gsname='routename' type='textfield' value='<? echo $route->name; ?>'>
        <br/>
        <div class='shop_button' style="margin-top: 20px" gstype='submit'>Save</div>
    </div>
    
    <div class="routebox drivermanagement">
        <h2>Drivers with access to this route</h2>
        <?
        $userIds = $route->userIds;
        foreach ($userIds as $userId) {
            $user = $this->getApi()->getUserManager()->getUserById($userId);
            echo "<div>".$user->fullName."</div>";
        }
        ?>
        
        <div class='shop_button' style="margin-top: 20px" gsclick='showAddDrivers'>Add drivers</div>
    </div>
    
    <div class="routebox destinations">
        <h2>Destinations</h2>
        <?
        foreach ($route->destinations as $destionation) {
            ?>
            <div class='destinationrow'>
                <div class='gs_shop_small_icon' gsclick='moveToPool' destionationid='<? echo $destionation->id; ?>'><i class='fa fa-arrow-down'></i></div>
                <div class='gs_shop_small_icon' gsclick='showEditDestionation' destionationid='<? echo $destionation->id; ?>'><i class='fa fa-edit'></i></div>
                <? echo $destionation->company->name; ?>
                </div>
            <?
        }
        ?>
    </div>
    
    <div class="routebox drivermanagement">
        <h2>Loose destinations in pool ( click on the arrow up to add destination to this route)</h2>
        
        <div class='destinationrow'>
            <span style='width: 800px; display: inline-block; padding-left: 40px;'>Company / destination</span>
            <span> From Route </span>
        </div>

        <?
        $destinations = $this->getApi()->getTrackAndTraceManager()->getPooledDestiontions();
  
        if (!$destinations) {
            $destinations = array();
            echo "<div style='font-weight: bold; color: red; padding: 15px;'>No destination currently in pool</div>";
        }
        foreach ($destinations as $poolDest) {
            $destination = $this->getApi()->getTrackAndTraceManager()->getDestinationById($poolDest->destionationId);
            ?>
            <div class='destinationrow'>
                <div class='gs_shop_small_icon' gsclick='addDestinationToRoute' destid='<? echo $poolDest->id; ?>'><i class='fa fa-arrow-up'></i></div>
                <span style='width: 800px; display: inline-block;'><? echo $destination->company->name; ?></span>
                <span><? echo $poolDest->originalRouteId; ?></span>
            </div>
            <?
        }
        ?>
    </div>
</div>

