<?
/* @var $this ns_5ebb7b42_35b7_48d3_b047_825dc2b30b5f\TrackAndTraceRouteManagement */

$route = $this->getRoute();
?>
<div class="topmenu">
    <div class="shop_button" gsclick="backToRoutes"><i class="fa fa-backward"></i> Back to routes</div>
</div>

<div>
    <div class="routebox" gstype='form' method='saveRoute'>
        Route name: <input class='gsniceinput1' gsname='routename' type='textfield' value='<? echo $route->name; ?>'>

        <h2>Route instruction</h2>
        <textarea placeholder="Todays instruction" gsname='instruction' style='width: 100%; box-sizing: border-box; height: 100px; border: solid 1px #DDD; padding: 10px;'><? echo $route->instruction; ?></textarea>
        
        <div class='shop_button' style="margin-top: 20px" gstype='submit'>Save</div>
    </div>
    
    <div class="routebox drivermanagement">
        <h2>Drivers with access to this route</h2>
        <?
        $userIds = $route->userIds;
        foreach ($userIds as $userId) {
            $user = $this->getApi()->getUserManager()->getUserById($userId);
            echo "<div>".$user->fullName."</div>";
        }
        ?>
        
        <div class='shop_button' style="margin-top: 20px" gsclick='showAddDrivers'>Add drivers</div>
    </div>
    
    <div class="routebox destinations">
        <h2>Destinations</h2>
        <?
        foreach ($route->destinations as $destionation) {
            echo "<div class='destinationrow'><div class='gs_shop_small_icon' gsclick='showEditDestionation' destionationid='$destionation->id'><i class='fa fa-edit'></i></div> ".$destionation->company->name."</div>";
        }
        ?>
        
        <div class='shop_button' style="margin-top: 20px" gsclick='showAddDestionation'>Add destionation</div>
    </div>
</div>

