<? namespace ns_d755efca_9e02_4e88_92c2_37a3413f3f41; ?>
<div class="extendedModeTitle">
    Need more flexibility to your webshop?
</div>
<div class="extendedModeTitle_sub">Access our extended version and gain access to:</div>
<div class="info">1. Flexible menu structures for top menu, and left menu.</div>
<div class="info">2. An extended application list.</div>
<div class="info">3. Free support.</div>
<div class="info">4. Page configuration and layout configuration.</div>
<div class="info">5. More designs to pick between, and the possibility to create your own.</div>
<div class="info">6. And much more.</div>
<span class="button"><ins class='activate_extended'>Activate extended mode</ins></span>
<div>
    <div class="sent_request">
        <center><b>Request has been sent!</b></center>
        <div>
            Your request for extended getshop mode has been sent.
        </div>
        <div>
            We will find you a personal getshop expert that will guide you into the extended world of GetShop.
        </div>
        <div>
            He / she will contact you within 24 hours.
        </div>
    </div>
</div>