<?php

namespace ns_1d8e7f34_14ee_4018_a3f4_190500dce026;

/* @var $this \ns_1d8e7f34_14ee_4018_a3f4_190500dce026\HelloWorld */
?>
<div class="start_row">
    <div class='started_div'><? echo $this->__w("Start your 30 days free trial now"); ?></div>
    <span style='display:inline-block;'>
        <input type="text" class="name" placeholder="<? echo $this->__f("Your name"); ?>">
        <div class='allfields'><? echo $this->__w("Your name"); ?></div>
    </span>
    <span style='display:inline-block;'>
        <input type="text" class="email" placeholder="<? echo $this->__f("Email address"); ?>">
        <div class='allfields'><? echo $this->__w("Your email"); ?></div>
    </span>
    <span style='display:inline-block;'>
        <input type="password" class="password" placeholder="<? echo $this->__f("Password"); ?>">
        <div class='allfields'><? echo $this->__w("Password"); ?></div>
    </span>
    <span style='display:inline-block;'>
        <span class="start_button"><span class='text'><? echo $this->__f("Build your store now"); ?></span> <i class="fa fa-arrow-right"></i></span><br>
        <div class="allfields">
            <? echo $this->__f("All fields are required, email need to be valid."); ?>
        </div>
    </span>
</div>
