<?php
/* @var $this ns_ee96fe89_e09d_4f7b_921a_3272462e9b7e\Airgram */
$orders = $this->getApi()->getOrderManager()->getAllOrdersForUser($_GET['userid']);
if(sizeof($orders) > 0) {
    echo "<br><br><br>";
    echo '<div class="form_text registration_heading"><b>'.$this->__f("Orders done by this user").'</b></div>';

    echo "<table>";
    foreach($orders as $order) {
        echo "<tr>";
        echo "<td>" . $order->createdDate . "&nbsp;&nbsp;&nbsp;</td>";
        echo "<td>";
        foreach($order->cart->items as $item) {
            echo $item->product->name . " (" . $item->product->price . ")". "<bR>";
        }
        echo "</td>";
        echo "</tr>";
    }
}
?>