<?
/* @var $this ns_20d70922_63fb_4cd8_bcc6_cfd1c1a1a4fd\EventSendTestToCandidates */

?>
<div gstype='form' method='sendTest'>
    <?
    $eventId = $this->getModalVariable("eventid");
    $users = $this->getApi()->getEventBookingManager()->getUsersForEvent($this->getBookingEngineName(), $eventId);
    $tests = $this->getApi()->getQuestBackManager()->getAllTests();

    echo "Select test: &nbsp; &nbsp; &nbsp; <select class='gsniceselect1 selectQuestBackTest' gsname='testid' testId='".$this->getModalVariable("eventid")."'>";

    echo "<option value=''>".$this->__f("Please select")."</option>";
    foreach ($tests as $test) {
        echo "<option value='$test->id'>$test->name ($test->type)</option>";
    }
    echo "</select>";
    ?>

    <div class='userInformationlist'>
        <?
        if (isset($_POST['event']) && $_POST['event'] === "sendTest") {
            echo "<br/>";
            echo $this->__f("Tests sent");
        }
        ?>
    </div>
  
    <br/><br/><div class="shop_button" gstype="submit"><? echo $this->__w("Send"); ?></div>
</div>