<?
/* @var $this ns_20d70922_63fb_4cd8_bcc6_cfd1c1a1a4fd\EventSendTestToCandidates */

?>
<div gstype='form' method='sendTest'>
    <?
    $eventId = $this->getModalVariable("eventid");
    $users = $this->getApi()->getEventBookingManager()->getUsersForEvent($this->getBookingEngineName(), $eventId);
    $tests = $this->getApi()->getQuestBackManager()->getAllTests();

    echo "Select test: &nbsp; &nbsp; &nbsp; <select class='gsniceselect1' gsname='testid'>";

    foreach ($tests as $test) {
        echo "<option value='$test->id'>$test->name</option>";
    }
    echo "</select>";
    ?>

    <br/>
    <br/>

    <b><? echo $this->__f("Select users you wish to send test to"); ?></b>
    <br/>

    <?
    foreach ($users as $user) {
        $tests = $this->getApi()->getQuestBackManager()->getTestsForUser($user->id);
        echo "<br/><input type='checkbox' gsname='$user->id' value='$user->id'/> ".$user->fullName;
        
        if ($tests) {
            echo " | Already has tests: (";
            $i = 0;
            foreach ($tests as $test) {
                $i++;
                echo $test->name;
                if (count($tests) != $i) {
                    echo ",";
                }
            }
            echo ")";
        }
    }
    ?>

    <br/><br/><div class="shop_button" gstype="submit"><? echo $this->__w("Send"); ?></div>
</div>