<?
/* @var $this \ns_90d14853_2dd5_4f89_96c1_1fa15a39babd\SalesPointCartCheckout */
$originalCart = $this->getOriginalCartFromSession();
$currentCart = $this->getApi()->getCartManager()->getCart();
$total = $this->getApi()->getCartManager()->getCartTotalAmount();

$items = $originalCart->items;
$i = 0;
foreach ($items as $item) {
    $i++;
    $lastItem = count($items) == $i ? "last_row" : "";
    $this->setCurrentItem($item);
    
    echo '<div class="cartitem row '.$lastItem.'" cartItemId="'.$item->cartItemId.'">';
    
    if ($item->addedByGetShopModule == "pms") {
        if ($item->priceMatrix && count($item->priceMatrix)) {
            $this->includefile("pmswithmatrixitem");
        } else if($item->itemsAdded && count($item->itemsAdded)) {
            $this->includefile("pmsaddons");
        } else {
            $this->includefile("pmsnormalcartitem");
        }
    }
    
    echo "</div>";
}
?>

<div class='summary'>
    <? echo $this->__f("Total"); ?>: <span><? echo $total; ?></span>
</div>

<div style='text-align: right; margin-top: 30px;'>
    <div class='shop_button'><i class='fa fa-magic'></i> <? echo $this->__f("Reset"); ?></div>
    <a href='/?page=selectPayment'><div class='shop_button'><? echo $this->__f("Select payment method"); ?> <i class='fa fa-arrow-right'></i></div></a>
</div>