<?/* @var $this \ns_90d14853_2dd5_4f89_96c1_1fa15a39babd\SalesPointCartCheckout */
$item = $this->getCurrentItem();
$i = 0;
$roomNumber = $item->product->additionalMetaData;
$guestName = $item->product->metaData;

$priceMatrix = (array)$item->priceMatrix;
uksort($priceMatrix, array('ns_28886d7d_91d6_409a_a455_9351a426bed5\PmsAvailability','sortByDate'));
if(trim($roomNumber)) {
    $roomNumber = " (" . $roomNumber . ")";
}
if(trim($guestName)) {
    $guestName = "<div style='color:#bbb;'>" . $guestName . "</div>";
}
echo "<i class='fa fa-trash-o removeitem'></i>";
echo "<b>".$item->count." x ".$item->product->name." $roomNumber</b>";
echo $guestName;
foreach ($priceMatrix as $date => $value) {
    $i++;
    $oddClass = $i % 2 ? "even" : "odd";
    ?>
    <div class='pricematrix_row <? echo $oddClass; ?> '>
        
        <?
        if ($this->isReadOnly()) {
        ?>
            <span><? echo trim($date);?></span>
            <span class='gsniceinput1 matrix_item matrix_price'><? echo $value; ?></span>
        <?
        } else {
        ?>
            <input type='checkbox' checked='true' class='matrix_input gsnicecheckbox1'> 
            <span><? echo trim($date);?></span>
            <input type='textfield' class='gsniceinput1 matrix_item matrix_price' value="<? echo $value; ?>">
        <?
        }
        ?>
    </div>
    <?
}
?>
