<?
/* @var $this \ns_c2730dd0_cffc_4e9d_bcd7_338623dc24ad\EventLog */

$eventLogs = $this->getApi()->getEventBookingManager()->getEventLog($this->getBookingEngineName(), $this->getEvent()->id);

echo "<div class='eventlogentry'>";
    echo "<div class='action' style='font-weight: bold'>".$this->__f("Action")."</div>"; 
    echo "<div class='blame' style='font-weight: bold'>".$this->__f("Who to blame")."</div>"; 
    echo "<div class='comment' style='font-weight: bold'>".$this->__f("Comment")."</div>"; 
    echo "<div class='date'  style='font-weight: bold'>".$this->__f("Date")."</div>"; 
echo "</div>";

foreach ($eventLogs as $eventLog) {
    $doneBy = $this->getApi()->getUserManager()->getUserById($eventLog->doneBy);
    
    if (!$doneBy) {
        $doneBy = "";
    } else {
        $doneBy = $doneBy->fullName;
    }
    
    $icon = $eventLog->action;
    $icon = $eventLog->action == "SMS_SIGNUP_SENT" ? "<i class='fa fa-mobile-phone'></i>" : $icon;
    $icon = $eventLog->action == "SMS_REMOVED_SENT" ? "<i class='fa fa-mobile-phone'></i>" : $icon;
    
    $icon = $eventLog->action == "SIGNUP_MAIL_SENT_FAILED" ? "<i class='fa fa-envelope' style='color: red'></i>" : $icon;
    $icon = $eventLog->action == "SIGNUP_MAIL_SENT" ? "<i class='fa fa-envelope'></i>" : $icon;
    $icon = $eventLog->action == "REMOVED_MAIL_SENT" ? "<i class='fa fa-envelope'></i>" : $icon;
    
    $icon = $eventLog->action == "USER_REMOVED_WAITING" ? "<i class='fa fa-user'></i>" : $icon;
    $icon = $eventLog->action == "USER_REMOVED" ? "<i class='fa fa-user'></i>" : $icon;
    $icon = $eventLog->action == "USER_ADDED_WAITING" ? "<i class='fa fa-user'></i>" : $icon;
    $icon = $eventLog->action == "USER_ADDED" ? "<i class='fa fa-user'></i>" : $icon;
    
    $icon = $eventLog->action == "EVENT_UPDATED" ? "<i class='fa fa-edit'></i>" : $icon;
    $icon = $eventLog->action == "EVENT_CREATED" ? "<i class='fa fa-edit'></i>" : $icon;
    
    echo "<div class='eventlogentry'>";
        echo "<div class='action'>$icon</div>"; 
        echo "<div class='blame'>".$doneBy."</div>"; 
        echo "<div class='comment'>".nl2br($eventLog->comment)."</div>"; 
        echo "<div class='date'>".$eventLog->rowCreatedDate."</div>"; 
    echo "</div>";
}
?>
