<div class="contentrow firstrow"> 
    <div class="row_inner">
        <div style='max-width: 1000px; margin: 0 auto;' id='bookingprocess'></div>

<script>
    gsisdevmode = false;
    
    $ = jQuery;
    jQuery(function ($) {
        $.getScript("https://20494gc6.getshop.com/js/getshop.bookingembed.js", function (data, textStatus, jqxhr) {
            $("#bookingprocess").getshopbooking(
                {
                    "endpoint": "https://20494gc6.getshop.com/",
                    "jsendpoint": "https://20494gc6.getshop.com/",
                    "domain" : "default",
                    "language" : "no",
                    "websocket" : "websocket6.getshop.com"
                }
            );
        });
    });
</script>
    </div>
</div>

