<div class="page_row row_1">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pos_row1");
        ?>
    </div>
</div>

<div class="page_row row_2 image_right">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pos_row2");
        ?>
    </div>
</div>

<div class="page_row row_3 image_left">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pos_row3");
        ?>
    </div>
</div>



<div class="page_row row_4 image_left">
    <div class="page_row_inner">
        <?php
            ContentManager::render("pos_row4");
        ?>
    </div>
</div>


