<?php
/* @var $this \ns_8f7198af_bd49_415a_8c39_9d6762ef1440\ComfortDashBoard */
?>
<div class="isnotactive">
    <div class="kaipal infobox">
        <div class="image happy"></div>
        <div class="textbox">
            <div class="header"><? echo $this->__f("Welcome to GetShop's comfort module."); ?></div>
            <div class="text">
                <?
                echo $this->__f("GetShop's comfort module is a module where you can set up preferred comfort states for your rooms. This requires integration to KNX or using one of our supported z-wave temperature sensors") . "<br>";
                echo "When set up correctly the temperature, electricity and lightning can be adjusted automatically based on its room occupancy.";
                ?>    
            </div>
        </div>
    </div>
</div>
<br>
<br>
<br>
<div class="informationarea">
    <div class='title'>Number of units set up</div>
    <div class='summarytext'>Number of gateways <span class='summarytextamount'>0</span></div>
    <div class='summarytext'>Number of temperature thermostats set up <span class='summarytextamount'>0</span></div>
    <div class='summarytext'>Number of light switches set up <span class='summarytextamount'>0</span></div>
    <div class='summarytext'>Number of power outlets set up <span class='summarytextamount'>0</span></div>
    <div class='summarytext'>Number of rooms connected <span class='summarytextamount'>0</span></div>
    <div class='summarytext'>Number of rooms in closed state <span class='summarytextamount'>0</span></div>
    <div class='summarytext'>Number of rooms in use state <span class='summarytextamount'>0</span></div>
    <div class='summarytext'>Number of rooms in sleep state <span class='summarytextamount'>0</span></div>
</div>

<div class="informationarea right">
    <div class='title'>Comfort automation log</div>
    <div>
    <?php
    $entries = (array)$this->getApi()->getComfortManager()->getAllLogEntries();
    $found = false;
    foreach($entries as $entry) {
        $textEvent = $this->translateEventFromText($entry->pmsEvent);
        $room = $this->getApi()->getBookingEngine()->getBookingItem($this->getSelectedMultilevelDomainName(), $entry->roomId);
        if(!$textEvent || !$room) {
            continue;
        }
        $found = true;
        echo "<div class='logentry'>";
        echo "<span class='date'>" . date("d.m.Y H:i", strtotime($entry->rowCreatedDate)) . "</span>";
        echo "<span class='description'>";
        echo $textEvent;
        if($entry->state) {
            echo ", temperature adjusted to " . $entry->state->temperature . " degrees";
        }
        echo "</span>";
        echo "<span class='room'>" . $room->bookingItemName . "</span>";
        echo "</div>";
    }
    if(!$found) {
        echo "No entries logged yet";
    }
    ?>
    </div>
</div>
