<?php

namespace ns_deab499e_b133_4cb6_a1b2_532018c31d46;

$taxes = $this->getApi()->getProductManager()->getTaxes();
if (!is_array($taxes)) {
    $taxes = [];
}

$shipment = isset($taxes[0]) ? $taxes[0]->taxRate : "";
$group1 = isset($taxes[1]) ? $taxes[1]->taxRate : "";
$group2 = isset($taxes[2]) ? $taxes[2]->taxRate : "";
$group3 = isset($taxes[3]) ? $taxes[3]->taxRate : "";
$group4 = isset($taxes[4]) ? $taxes[4]->taxRate : "";
$group5 = isset($taxes[5]) ? $taxes[5]->taxRate : "";

/* @var $this \ns_deab499e_b133_4cb6_a1b2_532018c31d46\Taxes */
?>

<div class="gss_settings_header">
    <i class="fa fa-dollar"></i>

    <div class="gss_settings_header_description">
        <div class="gss_settings_header_title"> <? echo $this->__f("Taxes"); ?></div>

        <div class="gss_settings_header_description_inner">
            <? echo $this->getDescription(); ?>
        </div>
    </div>	
</div>


<div class='gss_settings_content'>


    <div class='gss_button_area'>
        <div class="gss_button" onclick="window.open('/scripts/xledger.php');"><i class='fa fa-save'></i><?php echo $this->__("Download transfer file"); ?></div>
    </div>
</div>