<?php
/* @var $this \ns_b3dce8c9_b77b_4c4b_a398_af98863c2f91\OrderPaymentMethodConverter */
$methods = $this->getApi()->getStoreApplicationPool()->getActivatedPaymentApplications();

$states = array();
$states['0'] = "All";
$states['1'] = "Created";
$states['2'] = "Waiting for payment";
$states['3'] = "Payment failed";
$states['4'] = "Completed";
$states['5'] = "Canceled";
$states['6'] = "Sent";
$states['7'] = "Payment completed";
$states['8'] = "Collection failed";
$states['9'] = "Need collecting";
$states['10'] = "Send to invoice";

echo "<center gstype='form' method='convertPaymentMethods'>";
?>
<h1>Convert all payment methods from one method to a different one</h1>
<?php
echo "<select class='gsniceselect1' gsname='fromtype'>";
foreach($methods as $method) {
    echo "<option value='" . $method->id . "'>" . $method->appName . "</option>";
}
echo "</select>";

echo "<select class='gsniceselect1' gsname='state'>";
foreach($states as $state => $text) {
    echo "<option value='" . $state . "'>" . $text . "</option>";
}
echo "</select>";
echo "&nbsp;&nbsp;&nbsp;&nbsp;";
echo "<select class='gsniceselect1' gsname='totype'>";
foreach($methods as $method) {
    echo "<option value='" . $method->id . "'>" . $method->appName . "</option>";
}
echo "</select>";
echo "&nbsp;&nbsp;&nbsp;&nbsp;";
echo "<span class='shop_button' gstype='submit'>Do conversion</span>";
echo "</center>";
?>
