<?
/* @var $this \ns_b7fb195b_8cea_4d7b_922e_dee665940de2\InvoicingOverdueList */
$overDueInvoices = $this->getOverDueInvoices();
$debtCollectors = (array)$this->getApi()->getStoreApplicationPool()->getActivatedApplications("DebtCollectorApplication");
$hasDebtCollector = sizeof($debtCollectors) > 0;
?>

<div class="duerow header">
    <div class="col incrementalOrderId"><? echo $this->__f("Order id"); ?></div>
    <div class="col name"><? echo $this->__f("Name"); ?></div>
    <div class="col duedate"><? echo $this->__f("Due date"); ?></div>
    <div class="col totalamount"><? echo $this->__f("Total"); ?></div>
    <div class="col totalpaid"><? echo $this->__f("Paid"); ?></div>
    <div class="col remaining"><? echo $this->__f("Remaining"); ?></div>
    <?php
    if($hasDebtCollector) {
        ?>
        <div class="col todebt"><? echo $this->__f(""); ?></div>
        <?php
    }
    ?>
</div>

<?
$totalOrderAmount = 0;
$totalOrderPaid = 0;

foreach ($overDueInvoices as $order) {
    $dueDays = $this->calculateDaysSince($order->dueDate);
    $color = "blue";
    $color = $dueDays < 1 ? "gray" : $color;
    $color = $dueDays > 14 ? "yellow" : $color;
    $color = $dueDays > 30 ? "red" : $color;
    
    $debtcollectorText = "";
    foreach($order->shipmentLog as $slog) {
        if($slog->type == "debtCollector") {
            $debtcollectorText .= "Sent to debt collector at : " . date("d.m.Y H:i", strtotime($slog->date)) . "\r\n";
        }
    }
    
    ?>

    <div class="duerow  <? echo $color; ?>" duedays='<? echo $dueDays; ?>'>
        <a href='/invoicing.php?page=orderviewpage&orderid=<? echo $order->id; ?>&tab=paymenthistory' target='_new'>
            <div class="col incrementalOrderId"><? echo $order->incrementOrderId; ?>
                <?php
                if($order->internalComment) {
                    echo '<i class="fa fa-comment" title="'.$order->internalComment.'"></i>';
                }
                ?>
            </div>
            <div class="col name"><? echo $order->cart->address->fullName; ?></div>
            <div class="col duedate">
                <? echo date('d.m.Y', strtotime($order->dueDate)); ?>
                <span class="overduedays"> ( <? echo $dueDays . " " . $this->__f("days") ?> )</span>
            </div>
            <div class="col totalamount">
                <?
                $amount = $this->getTotalAmountForOrder($order);
                $totalOrderAmount += $amount;
                echo $amount;
                ?>
            </div>
            <div class="col totalpaid">
                <?
                $paidAmount = $this->getTotalPaidAmount($order);
                $totalOrderPaid += $paidAmount;
                echo $paidAmount;
                ?>
            </div>

            <div class="col remaining">
                <?
                echo $amount - $paidAmount;
                ?>
            </div>
            
            <?php if($hasDebtCollector) { 
                
                $appName = $debtCollectors[0]->appName;
                $appId = $debtCollectors[0]->id;
                $nameSpace = "ns_" . str_replace("-","_",$appId) . "\\" . $appName;
                $orderId = $order->incrementOrderId;
                ?>
                <div class="col todebt" style='float:right;'>
                    <a href='/scripts/transferToDebtCollector.php?app=<?php echo $nameSpace; ?>&orderid=<?php echo $orderId; ?>' target='_debtnew'>
                        <?php if($debtcollectorText) { ?>
                            <i title='<?php echo $debtcollectorText; ?>' class='fa fa-forward' style='color:#bbb;'></i>
                        <?php } else { ?>
                            <i title='Send to debt collector' class='fa fa-forward'></i>
                        <?php } ?>
                    </a>
                </div>
            <?php } ?>
        </a>
    </div>

    <?
}
?>
<script>
    app.InvoicingOverdueList.listLoaded();
</script>