<?
/* @var $this \ns_b7fb195b_8cea_4d7b_922e_dee665940de2\InvoicingOverdueList */
$overDueInvoices = $this->getOverDueInvoices();
$debtCollectors = (array)$this->getApi()->getStoreApplicationPool()->getActivatedApplications("DebtCollectorApplication");
$hasDebtCollector = sizeof($debtCollectors) > 0;

if( $_SESSION['massupdatewh'] == 'yes') $mwh = true;
if($mwh)
{
?>
<script>

function registerWHManualPayment(duedate,orderid,amount,button)
{
    console.log('Manual payment registrtation: date:' + duedate + '; orderid: ' + orderid + '; amount: ' + amount);

    var data = {};
    data.orderid = orderid;
    data.date = duedate;
    data.amount = amount;
    data.comment = '';

    var event = thundashop.Ajax.createEvent(null, "addTransactionRecord", $(button), data);
    event['synchron'] = true;
    event.core.pageid = 'orderviewpage';
    event.core.instanceid = '4be8e427-bead-491e-8d9f-7dd16356d8eb';


    $.ajax({
        type: "POST",
        url: '/data.php',
        data: thundashop.base64.encodeForAjax(event),
        dataType: 'html',
        context: document.body,
        success: function(response) {
            console.log('AJAX CAME BACK' + response);
            if(runallWH) runThroughAll();
        },
        xhr: function()
        {
            var xhr = new window.XMLHttpRequest();
            if (!xhr.upload) {
                return xhr;
            }

            xhr.upload.addEventListener("progress", function(evt) {
                if (evt.lengthComputable) {
                    var percentComplete = (evt.loaded / evt.total) * 100;
                    if(uploadcallback) {
                        uploadcallback(percentComplete);
                    }
                }
            }, false);

            return xhr;
        },
        error: function(e) { console.log('AJAX error ' + e); }
    });
}

var runallWH = false;
var totalWHcounter = 0;
function runThroughAll()
{
    $ = jQuery;
    runallWH = false;
    /*
    * we go through all .paythisWH elements and check if their duedate does not contain 2021 or 2020 - if this is true, we click one at a time and re-run this function
    * */
    var t = $('[duedate]:first')[0];
    if( $(t).attr('duedate').indexOf('2020') == -1 && $(t).attr('duedate').indexOf('2021') == -1 )
    {
       console.log('we will run for this day ' + $(t).attr('duedate'));
       runallWH = true;
       t.removeAttribute('duedate');

       totalWHcounter++;
       $('#whrunallbutton').html('Updating data at the backend for the ' + totalWHcounter + ' time now!' );

       $(t).click();

       //window.setTimeout(runThroughAll, 2000);
       return;
    }
    else
    {
       console.log('NO RUN FOR THIS '+ $(t).attr('duedate'));
       t.removeAttribute('duedate');
       window.setTimeout(runThroughAll, 200);
       return;
    }

}

</script>
<h1 id="whrunallbutton" style="color:#ff0000; cursor:pointer;" onclick="runThroughAll()">RUN THROUGH ALL UNTIL END OF 2019</h1>

<?php
} // end if massupdatewh
?>
<div class="duerow header">
    <div class="col incrementalOrderId"><? echo $this->__f("Order id"); ?></div>
    <div class="col name"><? echo $this->__f("Name"); ?></div>
    <div class="col duedate"><? echo $this->__f("Due date"); ?></div>
    <div class="col totalamount"><? echo $this->__f("Total"); ?></div>
    <div class="col totalpaid"><? echo $this->__f("Paid"); ?></div>
    <div class="col remaining"><? echo $this->__f("Remaining"); ?></div>
    <?php
    if($mwh) echo '<div class="col remaining">WHUPDATE</div>';
    if($hasDebtCollector) {
        ?>
        <div class="col todebt"><? echo $this->__f(""); ?></div>
        <?php
    }
    ?>
</div>

<?
$totalOrderAmount = 0;
$totalOrderPaid = 0;

foreach ($overDueInvoices as $order) {
    $dueDays = $this->calculateDaysSince($order->dueDate);
    $color = "blue";
    $color = $dueDays < 1 ? "gray" : $color;
    $color = $dueDays > 14 ? "yellow" : $color;
    $color = $dueDays > 30 ? "red" : $color;
    
    $debtcollectorText = "";
    foreach($order->shipmentLog as $slog) {
        if($slog->type == "debtCollector") {
            $debtcollectorText .= "Sent to debt collector at : " . date("d.m.Y H:i", strtotime($slog->date)) . "\r\n";
        }
    }

    $amount = $this->getTotalAmountForOrder($order);
    $paidAmount = $this->getTotalPaidAmount($order);

    // MANUAL HACK FOR WH INVOICES THAT HAVE NOT BEEN PAID EVER
    if($mwh)
    {
      echo '<div><div class="app" app="OrderView" appid=""></div>';
      echo '<div class="paythisWH" duedate="'. date('d.m.Y', strtotime($order->dueDate)) .'" class="duerow" onclick="registerWHManualPayment(\''. date('d.m.Y', strtotime($order->dueDate)) .'\',\''. $order->id .'\',\''. ($amount - $paidAmount) .'\',this)">RUN FOR THIS ORDER</div>';
      echo '<pre style="display:none;">'. print_r($order,1) .'</pre>';
      echo '</div>';
    }

?>
    <div class="duerow  <? echo $color; ?>" duedays='<? echo $dueDays; ?>'>
        <a href='/invoicing.php?page=orderviewpage&orderid=<? echo $order->id; ?>&tab=paymenthistory' target='_new'>
            <div class="col incrementalOrderId"><? echo $order->incrementOrderId; ?>
                <?php
                if($order->internalComment) {
                    echo '<i class="fa fa-comment" title="'.$order->internalComment.'"></i>';
                }
                ?>
            </div>
            <div class="col name"><? echo $order->cart->address->fullName; ?></div>
            <div class="col duedate">
                <? echo date('d.m.Y', strtotime($order->dueDate)); ?>
                <span class="overduedays"> ( <? echo $dueDays . " " . $this->__f("days") ?> )</span>
            </div>
            <div class="col totalamount">
                <?

                $totalOrderAmount += $amount;
                echo $amount;
                ?>
            </div>
            <div class="col totalpaid">
                <?

                $totalOrderPaid += $paidAmount;
                echo $paidAmount;
                ?>
            </div>

            <div class="col remaining">
                <?
                echo $amount - $paidAmount;
                ?>
            </div>
            <?php
            if($hasDebtCollector) {
                
                $appName = $debtCollectors[0]->appName;
                $appId = $debtCollectors[0]->id;
                $nameSpace = "ns_" . str_replace("-","_",$appId) . "\\" . $appName;
                $orderId = $order->incrementOrderId;
                ?>
                <div class="col todebt" style='float:right;'>
                    <a href='/scripts/transferToDebtCollector.php?app=<?php echo $nameSpace; ?>&orderid=<?php echo $orderId; ?>' target='_debtnew'>
                        <?php if($debtcollectorText) { ?>
                            <i title='<?php echo $debtcollectorText; ?>' class='fa fa-forward' style='color:#bbb;'></i>
                        <?php } else { ?>
                            <i title='Send to debt collector' class='fa fa-forward'></i>
                        <?php } ?>
                    </a>
                </div>
            <?php } ?>
        </a>
    </div>

    <?
}
?>
<script>
    app.InvoicingOverdueList.listLoaded();
</script>